from calc1_core import *
D=CalcDoc('2.6',[169,170,171],lambda n:169 if n<=22 else 170 if n<=46 else 171)
x,y=s.symbols('x y',real=True)
def same(t):return(d(t),d(t))
def add(n,st,steps,ans,ck,parts=()):return D.add(n,('음함수 미분','Implicit differentiation'),st,('y를 x의 함수로 보고 y가 포함된 항마다 연쇄법칙을 적용한다. 미분계수를 모은 뒤 분모와 특이점을 확인한다.','Treat y as a function of x and apply the chain rule to every term involving y. Collect the derivative terms and check denominators and singular points.'),steps,ans,ck,parts)
def der(F):return s.factor(-s.diff(F,x)/s.diff(F,y))
def total(f,p):return s.diff(f,x)+s.diff(f,y)*p
regular=('공식은 원래 관계식을 만족하고 표시된 분모가 0이 아닌 점에서 적용한다. 미분한 관계식에 대입하면 잔차가 0이다.','The formula applies at points of the original relation where the displayed denominator is nonzero. Substitution into the differentiated relation gives zero residual.')
for n,F,explicit,note in[(1,5*x*x-y**3-7,(5*x*x-7)**s.Rational(1,3),('세제곱근은 실수근이다. y=0에서는 나눗셈 공식을 적용하지 않는다.','Interpret the cube root as real. The division formula does not apply at y=0.')),(2,6*x**4+y**5-2*x,(2*x-6*x**4)**s.Rational(1,5),('다섯제곱근은 실수근이다. y=0에서 도함수 존재 여부는 별도로 판단한다.','Interpret the fifth root as real. Points with y=0 require separate consideration.')),(3,s.sqrt(x)+s.sqrt(y)-1,(1-s.sqrt(x))**2,('원래 식의 정의역은 0≤x≤1이고 미분식은 0<x<1에서 비교한다. 끝점은 양쪽 미분의 내점이 아니다.','The original domain is 0≤x≤1;compare derivatives on 0<x<1. Endpoints are not interior points for a two-sided derivative.')),(4,2/x-1/y-4,x/(2-4*x),('원래 식에서 x≠0,y≠0이고 명시식에는 x≠1/2도 필요하다. 명시식의 x=0은 원식의 해가 아니다.','The original equation requires x≠0,y≠0;the explicit form also excludes x=1/2. Its value at x=0 is not a solution of the original equation.'))]:
 p=der(F);de=s.diff(explicit,x)
 add(n,('관계 '+m(tex(F)+'=0')+'에 대해 (a)음함수 미분, (b)y를 명시적으로 풀어 미분, (c)대입하여 두 결과를 비교하라.','For '+m(tex(F)+'=0')+', (a)differentiate implicitly,(b)solve explicitly for y and differentiate,and(c)compare by substitution.'),[same(tex(s.diff(F,x))+'+('+tex(s.diff(F,y))+r')y\prime=0'),same(r'\text{(a) }y\prime='+tex(p)),same(r'\text{(b) }y='+tex(explicit)+r',\quad y\prime='+tex(de)),('(c)명시적 y를 (a)에 대입하고 같은 실수근을 정리하면 (b)와 일치한다. '+note[0], '(c)Substitute the explicit y into(a)and simplify using the same real root to recover(b). '+note[1])],d(r'y\prime='+tex(p)+r';\quad y='+tex(explicit)+r',\quad y\prime='+tex(de)),note,list('abc'))
Fs={5:x*x-4*x*y+y*y-4,6:2*x*x+x*y-y*y-2,7:x**4+x*x*y*y+y**3-5,8:x**3-x*y*y+y**3-1,9:x*x/(x+y)-y*y-1,10:y**5+x*x*y**3-1-x**4*y,11:s.sin(x)+s.cos(y)-2*x+3*y,12:y*s.sin(x*x)-x*s.sin(y*y),13:s.sin(x+y)-s.cos(x)-s.cos(y),14:s.tan(x-y)-2*x*y**3-1,15:s.tan(x/y)-x-y,16:s.sin(x*y)-s.cos(x+y),17:s.sqrt(x+y)-x**4-y**4,18:s.sin(x)*s.cos(y)-x*x+5*y,19:s.sqrt(x*y)-1-x*x*y,20:x*y-s.sqrt(x*x+y*y)}
for n,F in Fs.items():
 A,B=s.diff(F,x),s.diff(F,y);p=der(F)
 add(n,('관계 '+m(tex(F)+'=0')+'의 dy/dx를 구하라.','Find dy/dx for '+m(tex(F)+'=0')+'.'),[same(tex(A)+'+('+tex(B)+r')y\prime=0'),('y′가 곱해진 항을 모으고 그 계수로 나눈다.','Collect the terms multiplying y′ and divide by their coefficient.'),same(r'y\prime=-\frac{F_x}{F_y}='+tex(p))],d(r'y\prime='+tex(p)),regular)
add(21,('f(x)+x²[f(x)]³=10,f(1)=2일 때 f′(1)를 구하라.','Given f(x)+x²[f(x)]³=10 and f(1)=2,find f′(1).'),[same(r'f\prime+2xf^3+3x^2f^2f\prime=0'),same(r'(1+3\cdot1^2\cdot2^2)f\prime(1)=-2\cdot1\cdot2^3')],d(r'f\prime(1)=-16/13'),('점의 원식은2+8=10이며 미분계수13은0이 아니다.','The source point satisfies2+8=10 and the derivative coefficient13 is nonzero.'))
add(22,('g(x)+x sin(g(x))=x²일 때 g′(0)를 구하라.','For g(x)+x sin(g(x))=x²,find g′(0).'),[same(r'g(0)=0'),same(r'g\prime+\sin g+x\cos g\,g\prime=2x'),same(r'g\prime(0)+0+0=0')],d(r'g\prime(0)=0'),('먼저 원식에서 g(0)을 정한 뒤 미분식에 대입했다.','First determined g(0) from the original equation,then substituted into its derivative.'))
for n,F in[(23,x**4*y*y-x**3*y+2*x*y**3),(24,y*s.sec(x)-x*s.tan(y))]:
 q=s.factor(-s.diff(F,y)/s.diff(F,x))
 add(n,('y를 독립변수,x를 종속변수로 하여 '+m(tex(F)+'=0')+'의 dx/dy를 구하라.','Treat y as independent and x as dependent;find dx/dy for '+m(tex(F)+'=0')+'.'),[same('('+tex(s.diff(F,x))+r')\frac{dx}{dy}+'+tex(s.diff(F,y))+'=0'),same(r'\frac{dx}{dy}='+tex(q))],d(r'\frac{dx}{dy}='+tex(q)),('이번에는 x항에 dx/dy를 곱한다. 결과를 미분한 식에 대입하여 확인했다. 분모0은 별도이다.','Here the x terms acquire dx/dy. Substitution checks the differentiated equation;zero denominators are separate.'))
tangent_data={25:(y*s.sin(2*x)-x*s.cos(2*y),s.pi/2,s.pi/4),26:(s.tan(x+y)+s.sec(x-y)-2,s.pi/8,s.pi/8),28:(y*y*(6-x)-x**3,2,s.sqrt(2)),29:(x*x-x*y-y*y-1,2,1),30:(x*x+2*x*y+4*y*y-12,2,1),31:(x*x+y*y-(2*x*x+2*y*y-x)**2,0,s.Rational(1,2)),32:(x*x*y*y-(y+1)**2*(4-y*y),2*s.sqrt(3),1),33:(2*(x*x+y*y)**2-25*(x*x-y*y),3,1),34:(y*y*(y*y-4)-x*x*(x*x-5),0,-2)}
for n,(F,a,b)in tangent_data.items():
 p=der(F);slope=s.simplify(p.subs({x:a,y:b}));line=s.expand(b+slope*(x-a))
 add(n,('곡선 '+m(tex(F)+'=0')+'의 점 '+m('('+tex(a)+','+tex(b)+')')+'에서 접선을 구하라.','Find the tangent to '+m(tex(F)+'=0')+' at '+m('('+tex(a)+','+tex(b)+')')+'.'),[same(r'y\prime='+tex(p)),same(r'm=y\prime\big|_{('+tex(a)+','+tex(b)+')}='+tex(slope)),same('y-('+tex(b)+')=('+tex(slope)+')(x-('+tex(a)+'))')],d('y='+tex(line)),('주어진 점을 원식과 접선에 대입하여 확인하고 미분계수의 분모가0이 아닌지 점검했다.','Checked the point in both the curve and the line,and checked that the derivative denominator is nonzero.'))
add(27,('아스트로이드 x^(2/3)+y^(2/3)=4의 점(−3√3,1)에서 접선을 구하라. 거듭제곱은 실수 세제곱근의 제곱이다.','Find the tangent to the astroid x^(2/3)+y^(2/3)=4 at(−3√3,1),interpreting each power as the square of a real cube root.'),[same(r'\frac23x^{-1/3}+\frac23y^{-1/3}y\prime=0'),same(r'y\prime=-\frac{\sqrt[3]y}{\sqrt[3]x},\quad m=-\frac1{-\sqrt3}=\frac1{\sqrt3}'),same(r'y-1=\frac{x+3\sqrt3}{\sqrt3}')],d(r'y=x/\sqrt3+4'),('실수 세제곱근 ∛(−3√3)=−√3을 사용하면 원식3+1=4와 접점이 모두 확인된다.','The real cube root of−3√3 is−√3,checking both3+1=4 and the contact point.'))
for n,F,a,b,parts in[(35,y*y-5*x**4+x*x,1,2,'ab'),(36,y*y-x**3-3*x*x,1,-2,'abc')]:
 p=der(F);slope=p.subs({x:a,y:b});line=s.expand(b+slope*(x-a));st=('(a)곡선 '+m(tex(F)+'=0')+'의 점'+m('('+str(a)+','+str(b)+')')+'에서 접선을 구하라. '+('(b)곡선과 접선을 그려라.'if n==35 else'(b)수평 접점들을 구하고 (c)곡선과 위 접선들을 그려라.'),'(a)Find the tangent to '+m(tex(F)+'=0')+' at'+m('('+str(a)+','+str(b)+')')+'. '+('(b)Plot the curve and tangent.'if n==35 else'(b)Find the horizontal contacts and(c)plot the curve and these tangent lines.'))
 steps=[same(r'y\prime='+tex(p)),same('m='+tex(slope)+r',\quad y='+tex(line))]
 if n==36:steps +=[same(r'3x(x+2)=0,\quad y\ne0\Rightarrow x=-2,\ y=\pm2'),('원점에서는 두 가지가 y≈±√3x의 방향으로 교차하므로 수평 접선이 아니다.','At the origin two branches cross in directions y≈±√3x,so neither tangent is horizontal.')]
 add(n,st,steps,(d('y='+tex(line))if n==35 else d(r'y=-9x/4+1/4;\quad(-2,\pm2),\ y=\pm2')),('접선 방정식은 주어진 점을 통과하며 음함수 미분의 기울기와 일치한다. 아래 그림에 실수 가지들을 함께 그렸다.','The tangent passes through the given point and has the implicit derivative slope. The figure includes the real branches.'),list(parts))
secondFs={37:x*x+4*y*y-4,38:x*x+x*y+y*y-3,39:s.sin(y)+s.cos(x)-1,40:x**3-y**3-7}
secondFinal={37:-1/y**3/4,38:-18/(x+2*y)**3,39:(s.cos(x)*s.cos(y)**2+s.sin(x)**2*s.sin(y))/s.cos(y)**3,40:-14*x/y**5}
for n,F in secondFs.items():
 p=der(F);q=s.factor(total(p,p));ans=secondFinal[n]
 add(n,('관계 '+m(tex(F)+'=0')+'에서 y″를 음함수 미분으로 구하여 정리하라.','Use implicit differentiation to find and simplify y″ for '+m(tex(F)+'=0')+'.'),[same(r'y\prime='+tex(p)),same(r'y\prime\prime=\frac{\partial y\prime}{\partial x}+\frac{\partial y\prime}{\partial y}y\prime='+tex(q)),('원래 관계식을 이용하여 계수를 정리한다.','Simplify using the original relation.')],d(r'y\prime\prime='+tex(ans)),('첫 도함수를 전미분하고 원래 곡선 조건을 대입하여 최종식과 비교했다. 분모가0인 점은 공식의 적용 대상이 아니다.','Totally differentiated the first derivative and compared with the final expression on the curve. Zero denominators are outside the formula.'))
add(41,('xy+y³=1에서 x=0인 점의 y″를 구하라.','For xy+y³=1,find y″ at the point with x=0.'),[same(r'x=0\Rightarrow y=1'),same(r'y+(x+3y^2)y\prime=0\Rightarrow y\prime(0)=-1/3'),same(r'2y\prime+6y(y\prime)^2+(x+3y^2)y\prime\prime=0'),same(r'-2/3+6/9+3y\prime\prime=0')],d(r'y\prime\prime(0)=0'),('두 항−2/3과2/3이 정확히 상쇄된다.','The terms−2/3 and2/3 cancel exactly.'))
add(42,('x²+xy+y³=1에서 x=1인 점의 y‴를 구하라.','For x²+xy+y³=1,find y‴ at the point with x=1.'),[same(r'x=1\Rightarrow y+y^3=0\Rightarrow y=0'),same(r'2x+y+(x+3y^2)y\prime=0\Rightarrow y\prime=-2'),same(r'2+2y\prime+6y(y\prime)^2+(x+3y^2)y\prime\prime=0\Rightarrow y\prime\prime=2'),same(r'3y\prime\prime+6(y\prime)^3+18yy\prime y\prime\prime+(x+3y^2)y\prime\prime\prime=0'),same(r'6-48+y\prime\prime\prime=0')],d(r'y\prime\prime\prime=42'),('원점 이동 x=1+h에서 y=−2h+h²+7h³+…을 대입해 원식의 h³까지 계수가0인지 확인하면 y‴=6·7이다.','Substituting y=−2h+h²+7h³+… at x=1+h cancels coefficients through h³,checking y‴=6·7.'))
add(43,('곡선 y(y²−1)(y−2)=x(x−1)(x−2)에 대해 (a)그래프와 수평 접점의 수·x좌표 근삿값,(b)(0,1),(0,2)에서의 접선,(c)수평 접점의 정확한 x좌표를 구하라. (d)식을 바꾼 새로운 곡선도 그려라.','For y(y²−1)(y−2)=x(x−1)(x−2),(a)plot and estimate the number and x-coordinates of horizontal contacts,(b)find tangents at(0,1),(0,2),and(c)find the exact horizontal-contact x-coordinates. (d)Modify the equation to draw another curve.'),[same(r'(4y^3-6y^2-2y+2)y\prime=3x^2-6x+2'),same(r'y\prime=0\Rightarrow x=1\pm1/\sqrt3\approx0.42265,1.57735'),('각 x값에 대해 y근은 4개이다. 첫 x에서는 약−1.0578,0.2295,0.7705,2.0578이고 둘째에서는−0.9263,−0.1824,1.1824,1.9263이다. 따라서 수평 접점은8개이다.','Each x-value gives four y-roots. At the first they are approximately−1.0578,0.2295,0.7705,2.0578;at the second,−0.9263,−0.1824,1.1824,1.9263. Thus there are eight horizontal contacts.'),same(r'\text{(b) }y\prime(0,1)=2/(-2)=-1,\quad y\prime(0,2)=2/6=1/3'),same(r'y=1-x,\qquad y=2+x/3'),same(r'\text{(d) Example: }y(y^2-1)(y-2)=x(x-1)(x-2)(x-3)')],('수평 접점8개,x=1±1/√3. 접선 y=1−x,y=2+x/3. (d)의 한 예는 아래 두 번째 도해이다.','Eight horizontal contacts at x=1±1/√3. Tangents:y=1−x and y=2+x/3. The second figure supplies one example for(d).'),('t=y−1/2로 놓으면 좌변은 t⁴−(5/2)t²+9/16이다. 우변 c=±2/(3√3)에 대해 t²=(5±4√(1+c))/4가 서로 다른 두 양수이므로 네 실근과 0이 아닌 y미분계수가 확인된다.','With t=y−1/2,the left side is t⁴−(5/2)t²+9/16. For c=±2/(3√3),t²=(5±4√(1+c))/4 gives two distinct positive values,confirming four simple real roots for each x.'),list('abcd'))
add(44,('2y³+y²−y⁵=x⁴−2x³+x²의 (a)그래프를 그리고 왜 튀는 마차처럼 보이는지 설명하라. (b)수평 접점의 개수와 x좌표를 구하라.','(a)Plot 2y³+y²−y⁵=x⁴−2x³+x² and describe its resemblance to a bouncing wagon. (b)Find the number and x-coordinates of horizontal contacts.'),[same(r'(6y^2+2y-5y^4)y\prime=2x(x-1)(2x-1)'),('(a)윗부분은 차체 같은 폐곡선이고,아래 두 작은 고리와 이어진 아래쪽 곡선이 바퀴와 흔들리는 모양을 만든다. 도해에서 x=1/2 대칭도 보인다.','(a)The upper closed shape resembles a wagon body;the two lower loops and the lower connecting curve suggest wheels and bouncing. The graph is symmetric about x=1/2.'),same(r'\text{(b) }x=0,\ 1/2,\ 1'),('x=0,1에서는 y=−1,(1−√5)/2,(1+√5)/2의 세 점씩이 정칙 수평 접점이다. y=0은 특이점으로,국소식 y²≈x² 또는 y²≈(x−1)²에서 기울기±1인 두 접선을 갖는다.','At x=0 and1,the three regular horizontal contacts have y=−1,(1−√5)/2,(1+√5)/2. The point y=0 is singular;local equations y²≈x² or y²≈(x−1)² give slopes±1.'),('x=1/2에서는−y⁵+2y³+y²=1/16의 실근이 약−1.049338,0.210424,1.613921의 세 개이고 모두 정칙이다. 따라서 총9점이다.','At x=1/2,the equation−y⁵+2y³+y²=1/16 has three real roots,approximately−1.049338,0.210424,1.613921,all regular. The total is nine.')],('수평 접점9개. x좌표는0,1/2,1이며 각각3점이다.','Nine horizontal contacts:three at each of x=0,1/2,1.'),('중복근 y=0을 분자0이라는 이유만으로 세지 않았다. x=1/2의 다항식 실근 수3은 정확한 유리계수 다항식의 실근 개수 검사로 확인했다.','Excluded the repeated root y=0 rather than counting every zero numerator. The count of three roots at x=1/2 was independently checked for the exact rational-coefficient polynomial.'),list('ab'))
add(45,('렘니스케이트 2(x²+y²)²=25(x²−y²)의 수평 접점을 모두 구하라.','Find every horizontal tangent point of 2(x²+y²)²=25(x²−y²).'),[same(r'y\prime=\frac{x[25-4(x^2+y^2)]}{y[25+4(x^2+y^2)]}'),('x=0을 대입하면 원점만 나오지만 그곳은 기울기±1의 교차점이다. 정칙 수평 접선에서는 x²+y²=25/4이다.','Putting x=0 gives only the origin,where two branches cross with slopes±1. Regular horizontal contacts therefore satisfy x²+y²=25/4.'),same(r'x^2-y^2=25/8,\quad x^2=75/16,\quad y^2=25/16')],d(r'(x,y)=(\pm5\sqrt3/4,\ \pm5/4)\quad\text{(four independent sign choices)}'),('네 점 모두 원식에 속하고 도함수 분모가0이 아니며 분자는0이다.','All four points satisfy the curve,with zero derivative numerator and nonzero denominator.'))
for n,sign in[(46,1),(47,-1)]:
 eqtex=r'x^2/a^2'+('+'if sign==1 else'-')+r'y^2/b^2=1';tan=r'x_0x/a^2'+('+'if sign==1 else'-')+r'y_0y/b^2=1'
 add(n,('곡선 '+m(eqtex)+' 위 점(x₀,y₀)의 접선 방정식을 구하고 증명하라. a,b>0이다.','Derive and prove the tangent equation at(x₀,y₀) on '+m(eqtex)+',with a,b>0.'),[same(r'2x/a^2'+('+'if sign==1 else'-')+r'2yy\prime/b^2=0'),same(r'y\prime='+('-'if sign==1 else'')+r'b^2x/(a^2y)'),('점기울기식에 대입한 뒤 점이 원래 곡선 위에 있다는 조건으로 상수항을1로 바꾼다.','Insert the slope into point-slope form;use the original equation at the point to make the constant term1.'),same(tan),('y₀=0이면 x₀=±a이고 위 식은 수직 접선 x=x₀을 그대로 준다.','If y₀=0,then x₀=±a and the same equation gives the vertical tangent x=x₀.')],d(tan),('미분식의 기울기뿐 아니라 분모0인 수직 접선 경우까지 포함했다.','Included the vertical-tangent case that is lost by dividing by y.'))
add(48,('c>0일 때 √x+√y=√c의 접선이 두 좌표축과 이루는 절편의 합이 c임을 보이라.','For c>0,show that the sum of the axis intercepts of a tangent to √x+√y=√c is c.'),[same(r'y\prime=-\sqrt{y/x}'),same(r'\sqrt{y_0}(x-x_0)+\sqrt{x_0}(y-y_0)=0'),same(r'X=x_0+\sqrt{x_0y_0},\quad Y=y_0+\sqrt{x_0y_0}'),same(r'X+Y=(\sqrt{x_0}+\sqrt{y_0})^2=c'),('양의 좌표를 갖는 접점에서 위 절편식을 유도한다. 끝점(0,c),(c,0)의 수직·수평 접선에서는 통상적인 두 유한 절편을 모두 정의할 수 없어,주장은 내점 접선 또는 그 극한의 의미이다.','The intercept calculation applies to positive-coordinate contacts. At endpoints(0,c),(c,0),the vertical or horizontal tangent does not have two uniquely defined finite intercepts;the claim is for interior tangents or their limiting intercepts.')],d(r'X+Y=c'),('끝점 퇴화 경우를 명시하여 절편이 둘 다 정의된다는 숨은 가정을 구분했다.','Explicitly separated endpoint degeneracies from the case where both intercepts are defined.'))
add(49,('중심O인 원 위 점P의 접선이 반지름OP와 수직임을 음함수 미분으로 증명하라.','Use implicit differentiation to prove that a circle’s tangent at P is perpendicular to the radius OP.'),[same(r'(x-h)^2+(y-k)^2=r^2\Rightarrow(x-h)+(y-k)y\prime=0'),('접선 방향벡터(1,y′)와 반지름벡터(x−h,y−k)의 내적이0이다.','The tangent direction(1,y′) has zero dot product with the radius(x−h,y−k).'),('y=k인 원의 좌우 끝점은 수직 접선과 수평 반지름을 가지므로 이 경우도 수직이다.','At the left and right endpoints where y=k,the tangent is vertical and the radius horizontal,so the conclusion still holds.')],('모든 정칙 접점에서 OP⊥접선.','At every regular contact,OP is perpendicular to the tangent.'),('r>0의 원에는 반지름벡터가0인 점이 없어 수직성 주장이 항상 의미 있다.','For a circle with r>0,the radius vector never vanishes.'))
add(50,('y=x^(p/q)가 미분 가능하다고 가정하고,y^q=x^p의 음함수 미분으로 유리수 지수의 거듭제곱 법칙을 증명하라.','Assuming y=x^(p/q) is differentiable,use y^q=x^p and implicit differentiation to prove the rational-power rule.'),[same(r'qy^{q-1}y\prime=px^{p-1}'),same(r'y\prime=\frac pq\frac{x^{p-1}}{(x^{p/q})^{q-1}}=\frac pq x^{p/q-1}'),('q>0인 정수로 잡고 실수 거듭제곱이 정의되는 구간에서 계산한다. x=0에서 위 나눗셈이 불가능한 경우에는 극한으로 별도 판단한다.','Take integer q>0 and work on a domain where the real powers are defined. If division fails at x=0,that point requires a separate limit argument.')],d(r'\frac d{dx}x^{p/q}=\frac pq x^{p/q-1}'),('지수 차(p−1)−(p/q)(q−1)=p/q−1을 확인했다.','Checked the exponent difference(p−1)−(p/q)(q−1)=p/q−1.'))
for n,eq1,eq2,steps in[(51,r'x^2+y^2=r^2',r'ax+by=0',[same(r'm_1=-x/y,\quad m_2=-a/b=y/x\Rightarrow m_1m_2=-1')]),(52,r'x^2+y^2=ax',r'x^2+y^2=by',[same(r'm_1=(a-2x)/(2y),\quad m_2=-2x/(2y-b)'),same(r'a=(x^2+y^2)/x,\quad b=(x^2+y^2)/y'),same(r'm_1=\frac{y^2-x^2}{2xy},\quad m_2=-\frac{2xy}{y^2-x^2}')]),(53,r'y=cx^2',r'x^2+2y^2=k',[same(r'm_1=2cx=2y/x,\quad m_2=-x/(2y)\Rightarrow m_1m_2=-1')]),(54,r'y=ax^3',r'x^2+3y^2=b',[same(r'm_1=3ax^2=3y/x,\quad m_2=-x/(3y)\Rightarrow m_1m_2=-1')])]:
 steps +=[('기울기 나눗셈을 할 수 없는 축 위 교점에서는 접선이 수평·수직 한 쌍인지 원래 미분식으로 확인한다. 매개변수는 원이나 타원이 점으로 퇴화하지 않는 값을 사용한다.','At axis intersections where slope division fails,check the original differentiated equations for a horizontal–vertical pair. Use parameter values for which circles or ellipses do not degenerate to a point.')]
 if n==52:steps +=[('두 원의 공통 원점에서는 첫 원의 접선 x=0,둘째 원의 접선 y=0이다(a,b≠0).','At the common origin,the first circle has tangent x=0 and the second y=0 for nonzero a,b.')]
 add(n,('두 곡선족 '+m(eq1)+', '+m(eq2)+'이 정칙 교점에서 직교함을 보이고 두 족의 예들을 같은 좌표에 그려라.','Show that the families '+m(eq1)+' and '+m(eq2)+' meet orthogonally at regular intersections,and sketch representative members on common axes.'),steps,('모든 정칙 교점에서 두 접선은 수직이다. 아래 도해는 두 곡선족의 대표 예이다.','The tangents are perpendicular at every regular intersection. The figure shows representative members of both families.'),('유한 기울기에서는 곱−1,나머지 축 위 교점에서는 수평·수직 방향으로 확인했다.','Checked product−1 for finite slopes,and horizontal–vertical directions at remaining axis intersections.'))
add(55,('a,b,A,B>0,A²<a²,a²−b²=A²+B²일 때 타원 x²/a²+y²/b²=1과 쌍곡선 x²/A²−y²/B²=1이 교점에서 직교함을 보이라.','Let a,b,A,B>0,A²<a²,and a²−b²=A²+B². Prove that the ellipse x²/a²+y²/b²=1 and hyperbola x²/A²−y²/B²=1 meet orthogonally.'),[same(r'C=a^2-b^2=A^2+B^2'),same(r'x^2=\frac{a^2A^2}{C},\quad y^2=\frac{b^2B^2}{C}'),('두 원식은 x²,y²에 관한 일차 연립방정식이므로 위 값을 얻는다.','The two curve equations form a linear system in x²,y²,which gives these values.'),same(r'm_E=-\frac{b^2x}{a^2y},\quad m_H=\frac{B^2x}{A^2y},\quad m_Em_H=-\frac{b^2B^2x^2}{a^2A^2y^2}=-1')],('공통 초점을 갖는 두 곡선은 모든 교점에서 직교한다.','The confocal curves intersect orthogonally.'),('교점의 x²,y²가 양수이므로 사용한 기울기의 모든 분모가0이 아니다.','Both squared coordinates are positive,so every denominator used is nonzero.'))
add(56,('곡선족 y=(x+c)⁻¹과 y=a(x+k)^(1/3)이 서로 직교하도록 실수 a를 구하라.','Find real a for which the families y=(x+c)⁻¹ and y=a(x+k)^(1/3) are orthogonal.'),[same(r'm_1=-(x+c)^{-2}=-y^2'),same(r'y^3=a^3(x+k)\Rightarrow m_2=a^3/(3y^2)'),same(r'm_1m_2=-a^3/3=-1\Rightarrow a^3=3')],d(r'a=\sqrt[3]3'),('첫 곡선족은 y=0을 갖지 않으므로 교점에서 y²로 나누어도 된다.','The first family never has y=0,so division by y² is valid at intersections.'))
add(57,('반데르발스식 (P+n²a/V²)(V−nb)=nRT에서 (a)T를 고정하고 dV/dP를 구하라. (b)n=1 mol,V=10 L,P=2.5 atm,a=3.592 L²·atm/mol²,b=0.04267 L/mol에서 그 값을 구하라.','For the van der Waals equation(P+n²a/V²)(V−nb)=nRT,(a)find dV/dP at fixed T. (b)Evaluate for n=1 mol,V=10 L,P=2.5 atm,a=3.592 L²·atm/mol²,b=0.04267 L/mol.'),[same(r'(V-nb)+\left[P+\frac{n^2a}{V^2}-\frac{2n^2a(V-nb)}{V^3}\right]\frac{dV}{dP}=0'),same(r'\frac{dV}{dP}=-\frac{V^3(V-nb)}{PV^3-an^2V+2abn^3}'),same(r'\frac{dV}{dP}=-\frac{1000(9.95733)}{2500-35.92+2(3.592)(0.04267)}\approx-4.0405\ {\rm L/atm}')],d(r'\frac{dV}{dP}=-\frac{V^3(V-nb)}{PV^3-an^2V+2abn^3};\quad -4.0405\ {\rm L/atm}'),('주어진 상태에서 분모는 양수라 압력이 증가하면 부피가 감소한다. 단위는 L/atm이다.','The denominator is positive at the supplied state,so volume decreases as pressure increases;units are L/atm.'),list('ab'))
add(58,('(a)x²+xy+y²+1=0을 형식적으로 미분하여 y′를 구하라. (b)실수 좌표에서 그래프를 그리고 존재 여부를 증명하라. (c)그 결과를 바탕으로(a)의 의미를 설명하라.','(a)Formally differentiate x²+xy+y²+1=0. (b)Plot in real coordinates and prove whether any curve exists. (c)Explain what this means for(a).'),[same(r'(2x+y)+(x+2y)y\prime=0\Rightarrow y\prime=-\frac{2x+y}{x+2y}'),same(r'x^2+xy+y^2+1=(x+y/2)^2+3y^2/4+1\ge1'),('(b)실수 해가 없으므로 그래프는 빈집합이다. (c)형식적인 식은 이 관계의 어떤 실수 점에서도 실제 도함수로 평가할 수 없다.','(b)There are no real solutions,so the graph is empty. (c)The formal expression cannot represent a derivative at any real point of this relation.')],('(a)−(2x+y)/(x+2y);(b)실수 그래프 없음;(c)실제 실수 곡선의 도함수가 아니다.','(a)−(2x+y)/(x+2y);(b)no real graph;(c)no derivative of a real curve here.'),('완전제곱의 합이 최소1이므로 화면에 곡선이 없는 것은 계산·표시 오류가 아니다.','The sum of squares is at least1,so the empty plot is mathematical,not a plotting error.'),list('abc'))
add(59,('회전된 타원 x²−xy+y²=3의 x축 교점을 구하고 두 접선이 평행임을 보이라.','Find the x-axis crossings of x²−xy+y²=3 and prove their tangents are parallel.'),[same(r'y=0\Rightarrow x=\pm\sqrt3'),same(r'y\prime=\frac{y-2x}{2y-x},\quad y\prime\big|_{y=0}=2'),same(r'y=2(x-\sqrt3),\quad y=2(x+\sqrt3)')],d(r'(\pm\sqrt3,0);\quad y=2x\mp2\sqrt3'),('두 접선의 기울기는 모두2이고 절편은 서로 달라 서로 다른 평행선이다.','Both slopes equal2 and the intercepts differ,so the lines are distinct and parallel.'))
add(60,('(a)타원 x²−xy+y²=3의 점(−1,1)에서 법선이 타원과 다시 만나는 점을 구하라. (b)타원과 법선을 그려라.','(a)Find the second intersection of the normal to x²−xy+y²=3 at(−1,1) with the ellipse. (b)Plot the ellipse and normal.'),[same(r'y\prime=\frac{y-2x}{2y-x},\quad m_T(-1,1)=1,\quad m_N=-1'),same(r'y-1=-(x+1)\Rightarrow y=-x'),same(r'x^2+x^2+x^2=3\Rightarrow x=\pm1')],d(r'\text{Normal: }y=-x;\quad\text{second point: }(1,-1)'),('두 점 모두 원식에 속하며 법선은 접선 기울기의 음의 역수를 갖는다.','Both points satisfy the ellipse and the normal slope is the negative reciprocal of the tangent slope.'),list('ab'))
add(61,('곡선 x²y²+xy=2에서 접선 기울기가−1인 모든 점을 구하라.','Find every point on x²y²+xy=2 where the tangent slope is−1.'),[same(r'(xy+2)(xy-1)=0\Rightarrow xy=1\text{ or }-2'),same(r'(2xy+1)(y+xy\prime)=0\Rightarrow y\prime=-y/x'),same(r'y\prime=-1\Rightarrow y=x,\quad x^2=1\text{ or }-2')],d(r'(1,1),\quad(-1,-1)'),('xy=−2에서는 y=x가 실수로 성립할 수 없다. 두 해에서 x≠0,2xy+1=3이다.','The branch xy=−2 has no real point with y=x. At both solutions,x≠0 and2xy+1=3.'))
add(62,('점(12,3)을 지나며 타원 x²+4y²=36에 접하는 두 직선을 구하라.','Find both lines through(12,3) tangent to x²+4y²=36.'),[same(r'y=m(x-12)+3=mx+b,\quad b=3-12m'),same(r'x^2+4(mx+b)^2=36'),('x의 이차방정식이 중근을 가지려면 판별식이0이어야 하며,b²=9+36m²가 된다.','Tangency requires a repeated root of the quadratic in x;its zero discriminant gives b²=9+36m².'),same(r'(3-12m)^2=9+36m^2\Rightarrow36m(3m-2)=0')],d(r'y=3,\quad y=\frac23x-5'),('접점은 각각(0,3),(24/5,−9/5)이며 원식과 접선을 만족한다. x=12는 타원과 만나지 않으므로 빠진 수직 접선은 없다.','The contacts are(0,3) and(24/5,−9/5),satisfying both curves and lines. The vertical line x=12 misses the ellipse,so no vertical tangent is omitted.'))
add(63,('y≠0일 때 동치인 두 식 x/y=y²+1과 x=y³+y를 각각 음함수 미분하고 그 도함수가 곡선 위에서 같음을 보여라.','For y≠0,differentiate both equivalent equations x/y=y²+1 and x=y³+y,and show the derivatives agree on the curve.'),[same(r'\frac{y-xy\prime}{y^2}=2yy\prime\Rightarrow y\prime=\frac y{x+2y^3}'),same(r'1=(3y^2+1)y\prime\Rightarrow y\prime=\frac1{3y^2+1}'),same(r'\frac y{x+2y^3}=\frac y{y^3+y+2y^3}=\frac1{3y^2+1}')],d(r'y\prime=\frac y{x+2y^3}=\frac1{3y^2+1}'),('약분은 y≠0이라는 주어진 조건으로 정당화되고 최종 분모는 항상 양수이다.','Cancellation is justified by y≠0,and the final denominator is always positive.'))
add(64,('0차 베셀함수 J가 xJ″+J′+xJ=0,J(0)=1을 만족한다. (a)J′(0),(b)J″(0)를 구하라.','The order-zero Bessel function J satisfies xJ″+J′+xJ=0 and J(0)=1. Find(a)J′(0) and(b)J″(0).'),[same(r'x=0\Rightarrow J\prime(0)=0'),same(r'J\prime\prime+xJ\prime\prime\prime+J\prime\prime+J+xJ\prime=0'),same(r'x=0\Rightarrow2J\prime\prime(0)+1=0')],d(r'\text{(a) }J\prime(0)=0;\quad\text{(b) }J\prime\prime(0)=-1/2'),('멱급수 J=1−x²/4+…를 원식에 대입하면 상수항·x항이 상쇄되어 두 값을 다시 확인할 수 있다.','The series J=1−x²/4+… cancels the constant and linear terms of the equation,checking both values.'),list('ab'))
add(65,('램프는(3,h),h>0에 있고 불투명한 타원 영역 x²+4y²≤5가 그림자를 만든다. 그림자 경계의 한 광선이(−5,0)을 지날 때 램프 높이 h를 구하라.','A lamp is at(3,h),h>0,and the opaque ellipse region x²+4y²≤5 casts a shadow. One boundary ray passes through(−5,0). Find the lamp height h.'),[same(r'\text{Ray: }y=m(x+5),\quad h=8m,\quad m>0'),same(r'x^2+4m^2(x+5)^2=5'),same(r'\Delta=(40m^2)^2-4(1+4m^2)(100m^2-5)=20-320m^2'),same(r'\Delta=0\Rightarrow m=1/4,\quad h=2')],d(r'h=2'),('광선 y=(x+5)/4는(−1,1)에서 타원에 접하고(3,2),(−5,0)을 모두 지나므로 원래 그림 조건을 만족한다.','The ray y=(x+5)/4 is tangent at(−1,1) and passes through(3,2) and(−5,0),checking the geometric constraints.'))
# Direct numerical contours, generated from the stated equations; no source image reuse.
def contour(F,bounds,color='#1d4ed8',resolution=190):
 fn=s.lambdify((x,y),F,'math');a,b,c,e=bounds;nx=resolution;ny=resolution
 xs=[a+(b-a)*i/nx for i in range(nx+1)];ys=[c+(e-c)*j/ny for j in range(ny+1)];vals=[[fn(xx,yy)for xx in xs]for yy in ys];curves=[]
 for j in range(ny):
  for i in range(nx):
   pts=[(xs[i],ys[j]),(xs[i+1],ys[j]),(xs[i+1],ys[j+1]),(xs[i],ys[j+1])];vs=[vals[j][i],vals[j][i+1],vals[j+1][i+1],vals[j+1][i]]
   for tri in[(0,1,2),(0,2,3)]:
    hits=[]
    for k,l in[(tri[0],tri[1]),(tri[1],tri[2]),(tri[2],tri[0])]:
     if (vs[k]<0)!=(vs[l]<0):
      t=vs[k]/(vs[k]-vs[l]);hits.append((pts[k][0]+t*(pts[l][0]-pts[k][0]),pts[k][1]+t*(pts[l][1]-pts[k][1])))
    if len(hits)==2:curves.append({'points':hits,'color':color})
 return curves
def linepoints(a,b,lo,hi,color='#dc2626'):return{'points':[(lo,a*lo+b),(hi,a*hi+b)],'color':color}
for n,bounds in[(31,(-.3,1.15,-.65,.65)),(32,(-7,7,-2.4,2.4)),(33,(-4,4,-2,2)),(34,(-3.5,3.5,-3.3,3.3))]:
 F,a,b=tangent_data[n];sl=float(der(F).subs({x:a,y:b}));inter=float(b-sl*a);D.fig(n,[panel('Blue: implicit curve; red: tangent',bounds,contour(F,bounds)+[linepoints(sl,inter,bounds[0],bounds[1])],[(float(a),float(b))])])
F=y*y-5*x**4+x*x;bounds=(-1.6,1.6,-5,5);D.fig(35,[panel('Kampyle and tangent y=9x/2-5/2',bounds,contour(F,bounds)+[linepoints(4.5,-2.5,-1.6,1.6)],[(0,0),(1,2)])])
F=y*y-x**3-3*x*x;bounds=(-3.2,2.2,-5,5);D.fig(36,[panel('Cubic: tangent and horizontal contacts',bounds,contour(F,bounds)+[linepoints(-2.25,.25,-3.2,2.2),linepoints(0,2,-3.2,2.2,'#15803d'),linepoints(0,-2,-3.2,2.2,'#15803d')],[(1,-2),(-2,2),(-2,-2)])])
F=y*(y*y-1)*(y-2)-x*(x-1)*(x-2);bounds=(-1.2,3.2,-1.6,2.6);dots=[]
for aa in[1-1/s.sqrt(3),1+1/s.sqrt(3)]:
 for yy in s.nroots(F.subs(x,aa)):dots.append((float(aa),float(s.re(yy))))
D.fig(43,[panel('Original curve; eight horizontal contacts',bounds,contour(F,bounds)+[linepoints(-1,1,-1.2,3.2,'#dc2626'),linepoints(1/3,2,-1.2,3.2,'#15803d')],dots),panel('Modification: extra factor (x-3)',(-1,4,-2,3),contour(y*(y*y-1)*(y-2)-x*(x-1)*(x-2)*(x-3),(-1,4,-2,3)))])
F=2*y**3+y*y-y**5-x*x*(x-1)**2;bounds=(-1.6,2.6,-1.8,2);dots=[]
for aa in[0,.5,1]:
 for yy in s.nroots(F.subs(x,aa),maxsteps=100):
  if abs(float(s.im(yy)))<1e-9 and abs(float(s.re(yy)))>1e-8:dots.append((aa,float(s.re(yy))))
D.fig(44,[panel('Bouncing wagon; nine regular horizontal contacts',bounds,contour(F,bounds,resolution=300),dots)])
# Equal x/y scale in the orthogonal-family figures.
bounds=(-6,6,-81/26,81/26)
def param(fn,n=900):return[fn(2*math.pi*i/n)for i in range(n+1)]
cs=[]
for rr in[.8,1.6,2.4]:cs.append({'points':param(lambda t,rr=rr:(rr*math.cos(t),rr*math.sin(t))),'color':'#1d4ed8'})
for sl in[-2,-.5,0,.5,2]:cs.append(linepoints(sl,0,-6,6,'#dc2626'))
cs.append({'points':[(0,-4),(0,4)],'color':'#dc2626'});D.fig(51,[panel('Blue: concentric circles; red: radial lines',bounds,cs)])
cs=[]
for aa in[-4,-2,2,4]:
 cs.append({'points':param(lambda t,aa=aa:(aa/2+abs(aa)/2*math.cos(t),abs(aa)/2*math.sin(t))),'color':'#1d4ed8'})
 cs.append({'points':param(lambda t,aa=aa:(abs(aa)/2*math.cos(t),aa/2+abs(aa)/2*math.sin(t))),'color':'#dc2626'})
bounds52=(-8.32,8.32,-4.32,4.32);D.fig(52,[panel('Blue: x-axis centers; red: y-axis centers',bounds52,cs)])
for n,power,weight in[(53,2,2),(54,3,3)]:
 cs=[]
 for aa in[-1,-.25,0,.25,1]:cs.append({'points':samples(lambda xx,aa=aa:aa*xx**power,-5,5,800),'color':'#1d4ed8'})
 for kk in[1,4,9,16]:cs.append({'points':param(lambda t,kk=kk:(math.sqrt(kk)*math.cos(t),math.sqrt(kk/weight)*math.sin(t))),'color':'#dc2626'})
 D.fig(n,[panel('Blue: power family; red: ellipses',bounds,cs)])
D.fig(58,[panel('Empty real locus: (x+y/2)^2+3y^2/4+1 >= 1',(-3,3,-3,3),[])],caption=('해가 없으므로 곡선이 없는 좌표평면이 정답이다.','The empty coordinate plane is the correct real graph.'))
bounds60=(-4,4,-27/13,27/13);D.fig(60,[panel('Ellipse and normal; contacts (-1,1),(1,-1)',bounds60,contour(x*x-x*y+y*y-3,bounds60)+[linepoints(-1,0,-3,3)], [(-1,1),(1,-1)])])
bounds65=(-6,4,-2.5,3);D.fig(65,[panel('Lamp (3,2); tangent ray through (-5,0)',bounds65,[{'points':param(lambda t:(math.sqrt(5)*math.cos(t),math.sqrt(5)/2*math.sin(t))),'color':'#1d4ed8'},linepoints(.25,1.25,-6,3),{'points':[(3,0),(3,2)],'color':'#15803d'}],[(-5,0),(-1,1),(3,2)])])
normalize_prose_inequalities(D)
D.save(65)
