from calc1_core import *
x=s.symbols('x',real=True)
D=CalcDoc('1.2',[33,34,35,36],lambda n:33 if n<=15 else 34 if n<=26 else 35 if n<=32 else 36)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('기본함수와 수학적 모형','Elementary functions and mathematical models'),st,('함수식의 구조를 식별하고 조건과 단위를 함께 적용한다.','Identify the structure of the function, then apply the conditions and units.'),steps,ans,check,parts)
classes={1:[(r'x^3+3x^2','3차 다항함수','polynomial of degree3'),(r'\cos^2t-\sin t','삼각함수식','trigonometric function'),(r't^{\sqrt3}','거듭제곱함수','power function'),(r'8^t','지수함수','exponential function'),(r'\sqrt x/(x^2+1)','대수함수','algebraic function'),(r'\log_{10}u','로그함수','logarithmic function')],2:[(r'(3t^2+2)/t','유리함수','rational function'),(r'2.3^r','지수함수','exponential function'),(r'\sqrt{t+4}','대수함수(평행이동한 제곱근 함수)','algebraic function (shifted square-root function)'),(r'x^4+5','4차 다항함수','polynomial of degree4'),(r'\sqrt[3]x','근함수이자 거듭제곱함수','root function and power function'),(r'1/x^2','거듭제곱함수이자 유리함수','power function and rational function')]}
for n,rows in classes.items():
 add(n,('다음 여섯 식을 거듭제곱·근·다항(차수 포함)·유리·대수·삼각·지수·로그 중 분류하라: '+', '.join('('+chr(97+i)+') '+m(r[0]) for i,r in enumerate(rows))+'.','Classify these six expressions as power, root, polynomial (with degree), rational, algebraic, trigonometric, exponential, or logarithmic functions: '+', '.join('('+chr(97+i)+') '+m(r[0]) for i,r in enumerate(rows))+'.'),[('고정 지수에 입력을 거듭제곱하면 거듭제곱함수이고, 입력이 지수에 있으면 지수함수이다. 다항식의 비는 유리함수이며 근호로 얻는 식은 대수함수이다.','A variable base with fixed exponent is a power function; a variable exponent with fixed base is exponential. A ratio of polynomials is rational, and expressions constructed with radicals are algebraic.'),('분류는 겹칠 수 있다. 특히 다항·유리함수는 대수함수에도 속한다.','Categories can overlap: polynomials and rational functions are also algebraic.')],('; '.join('('+chr(97+i)+') '+r[1] for i,r in enumerate(rows)),'; '.join('('+chr(97+i)+') '+r[2] for i,r in enumerate(rows))),('다항 차수는 가장 높은 비음수 정수 지수이며 음수·분수 지수 항은 다항식 항이 아니다.','Polynomial degree is the highest nonnegative integer exponent; negative or fractional powers are not polynomial terms.'),list('abcdef'))
add(3,('도해의 f는 원점을 지나는 홀수형, g와 h는 y축 대칭이다. (a)y=x²,(b)y=x⁵,(c)y=x⁸을 f,g,h에 대응시키되 계산기 없이 이유를 설명하라.','In the diagram f has odd symmetry through the origin, while g and h have y-axis symmetry. Match(a)y=x²,(b)y=x⁵,(c)y=x⁸ to f,g,h and justify without using a calculator.'),[('음의 x에서 음수가 되는 것은 x⁵뿐이므로 f이다.','Only x⁵ is negative for negative x, identifying f.'),('0<x<1에서는 x⁸<x²이므로 축에 더 붙어 있는 g가 x⁸, 나머지 h가 x²이다.','For0<x<1, x⁸<x², so g, the flatter curve near the axis, is x⁸; h is x².')],('(a)h,(b)f,(c)g.','(a)h,(b)f,(c)g.'),('x>1에서는 x⁸>x²로 순서가 바뀌고 두 짝함수는 x=±1에서 만나는 원본 형태와 일치한다.','For x>1, x⁸>x² reverses the order; both even curves meet at x=±1, matching the source.'),list('abc'))
D.fig(3,[panel('h blue: x²; f red: x⁵; g green: x⁸',(-1.5,1.5,-2,3),[samples(lambda z:z*z,-1.5,1.5),samples(lambda z:z**5,-1.5,1.5),samples(lambda z:z**8,-1.5,1.5)])])
add(4,('도해의 f는 양수인 지수형, g는 원점을 지나는 완만한 세제곱근형, F는 수평 접선으로 원점을 지나는 곡선, G는 직선이다. (a)3x,(b)3ˣ,(c)x³,(d)∛x를 대응시켜 설명하라.','In the diagram f is a positive exponential-shaped curve, g has cube-root shape, F passes through the origin with a horizontal tangent, and G is a line. Match(a)3x,(b)3ˣ,(c)x³,(d)∛x and explain.'),[('직선은 G, y절편1을 갖고 항상 양수인 것은 f이다.','G is the line, and f is the always-positive curve with intercept1.'),('원점에서 평평한 것은 x³인 F, 원점에서 가파르고 멀리서는 완만해지는 것은 ∛x인 g이다.','F is x³, flat at the origin; g is ∛x, steep at the origin and flatter farther away.')],('(a)G,(b)f,(c)F,(d)g.','(a)G,(b)f,(c)F,(d)g.'),('x=0에서 세 함수는0, 지수함수만1이며 x<0에서 지수함수만 양수이다.','At x=0 three functions give0 and only the exponential gives1; for x<0 only the exponential is positive.'),list('abcd'))
D.fig(4,[panel('f blue, F red, G green, g purple',(-2,2,-3,5),[samples(lambda z:3**z,-2,2),samples(lambda z:z**3,-2,2),samples(lambda z:3*z,-2,2),samples(lambda z:math.copysign(abs(z)**(1/3),z),-2,2)])])
for n,expr,dom,ko,en,ck,ce in [(5,r'\cos x/(1-\sin x)',r'\mathbb R\setminus\{\pi/2+2k\pi:k\in\mathbb Z\}','sin x=1에서 분모가0이므로 그 입력만 제외한다.','Exclude exactly the inputs where sin x=1 makes the denominator zero.','cos x도0이더라도 원식의0/0은 정의되지 않는다.','Even when cos x is also zero, the original0/0 remains undefined.'),(6,r'1/(1-\tan x)',r'\mathbb R\setminus\bigl(\{\pi/2+k\pi\}\cup\{\pi/4+k\pi\}\bigr),\ k\in\mathbb Z','tan x가 정의되려면 cos x≠0이고, 바깥 분모가0이 아니려면 tan x≠1이다.','Require cos x≠0 so that tan x exists, and tan x≠1 so that the outer denominator is nonzero.','cos x/(cos x−sin x)로 바꾸어도 원래 tan이 정의되지 않는 점은 되살릴 수 없다.','Rewriting as cos x/(cos x−sin x) does not restore points where the original tangent is undefined.')]:
 add(n,('함수 '+m(expr)+'의 정의역을 구하라.','Find the domain of '+m(expr)+'.'),[(ko,en)],d('D='+dom),(ck,ce))
add(7,('(a)기울기2인 모든 직선의 식과 몇 예의 그래프,(b)f(2)=1인 모든 직선의 식과 예,(c)두 집합에 공통인 함수를 구하라.','Find and sketch(a) the family of lines of slope2,(b) the family satisfying f(2)=1, and(c) their common member.'),[('기울기를 고정하면 절편만 자유로워 f(x)=2x+b이다.','Fixing the slope leaves the intercept free: f(x)=2x+b.'),('점(2,1)을 고정하면 점기울기식 f(x)=1+m(x−2)이다. 공통 함수는 m=2를 대입한다.','Fixing(2,1) gives f(x)=1+m(x−2). Set m=2 to find the common member.')],d(r'(a)\ f(x)=2x+b;\quad(b)\ f(x)=1+m(x-2);\quad(c)\ f(x)=2x-3'),('공통식의 기울기는2이며 f(2)=4−3=1이다.','The common formula has slope2 and f(2)=4−3=1.'),list('abc'))
D.fig(7,[panel('(a) Slope2; b=-2,0,2',(-3,3,-8,8),[samples(lambda z,b=b:2*z+b,-3,3) for b in [-2,0,2]]),panel('(b) Through(2,1); m=-1,0,2',(-2,4,-7,7),[samples(lambda z,m=m:1+m*(z-2),-2,4) for m in [-1,0,2]],[(2,1)])])
for n,expr,ko,en,ck,ce in [(8,'1+m(x+3)','모든 직선은(−3,1)을 지나며 m이 기울기이다.','Every line passes through(−3,1), with slope m.','x=−3을 대입하면 m에 관계없이1이다.','Substitution of x=−3 gives1 for every m.'),(9,'c-x','모두 기울기−1이어서 서로 평행하며 c가 y절편이다.','All have slope−1 and are parallel; c is the y-intercept.','두 식을 빼면 상수 c₁−c₂이므로 세로 간격이 일정하다.','Subtracting two formulas gives the constant c₁−c₂, confirming a fixed vertical separation.')]:
 add(n,('직선족 '+m('f(x)='+expr)+'의 공통점을 설명하고 여러 예를 그려라.','Describe the common feature of '+m('f(x)='+expr)+' and sketch several members.'),[(ko,en)],(ko,en),(ck,ce))
D.fig(8,[panel('Lines through(-3,1)',(-5,1,-5,7),[samples(lambda z,m=m:1+m*(z+3),-5,1) for m in [-1,0,1,2]],[(-3,1)])])
D.fig(9,[panel('Parallel lines; c=-2,0,2',(-3,3,-6,6),[samples(lambda z,c=c:c-z,-3,3) for c in [-2,0,2]])])
add(10,('다항식족 '+m('P(x)=x^3-cx^2')+'의 여러 그래프를 그리고 c에 따른 변화를 설명하라.','Plot several members of '+m('P(x)=x^3-cx^2')+' and explain how varying c changes them.'),[(d('P(x)=x^2(x-c)'),d('P(x)=x^2(x-c)')),('c≠0이면 원점에서 x축에 접하고 x=c에서 축을 지난다. c=0이면 x³이다.','For c≠0 the graph touches the axis at0 and crosses at c. For c=0 it is x³.'),('c가 증가하면 x≠0의 높이는 내려간다. c>0이면 원점이 국소 최대이고 오른쪽에 골, c<0이면 원점이 국소 최소이고 왼쪽에 봉우리가 있다.','Increasing c lowers every height with x≠0. For c>0 the origin is a local maximum with a trough to the right; for c<0 it is a local minimum with a peak to the left.')],('영점은0과c. c의 증가에 따라 원점 이외 높이는 감소하고 다른 영점이 오른쪽으로 이동한다.','Zeros occur at0 and c. Increasing c lowers all nonzero-input heights and moves the other zero to the right.'),('c₂>c₁일 때 P₂(x)−P₁(x)=−(c₂−c₁)x²≤0으로 높이 변화를 직접 확인했다.','For c₂>c₁, P₂(x)−P₁(x)=−(c₂−c₁)x²≤0 verifies the height change.'))
D.fig(10,[panel('c=-2 blue,0 red,2 green',(-3,3,-15,15),[samples(lambda z,c=c:z**3-c*z*z,-3,3) for c in [-2,0,2]])])
add(11,('꼭짓점(3,0), 통과점(4,2), y절편18인 포물선의 식을 구하라.','Find the quadratic with vertex(3,0), passing through(4,2), and y-intercept18.'),[('꼭짓점형 f(x)=a(x−3)²에(4,2)를 넣으면 a=2이다.','Using vertex form f(x)=a(x−3)² and the point(4,2) gives a=2.')],d('f(x)=2(x-3)^2'),('f(0)=18, f(3)=0, f(4)=2가 모두 주어진 값과 일치한다.','The values f(0)=18,f(3)=0,f(4)=2 match all supplied information.'))
add(12,('포물선이(−2,2),(0,1),(1,−2.5)를 지난다. 식을 구하라.','Find the quadratic through(−2,2),(0,1),(1,−2.5).'),[('g(x)=ax²+bx+c에서 c=1이다. 다른 두 점으로4a−2b=1,a+b=−3.5를 얻는다.','Writing g(x)=ax²+bx+c gives c=1. The other points yield4a−2b=1 and a+b=−3.5.'),('연립하면 a=−1,b=−5/2이다.','Solving gives a=−1 and b=−5/2.')],d(r'g(x)=-x^2-\tfrac52x+1'),('세 입력에 대입하면 각각2,1,−2.5이다.','Substitution at the three inputs gives2,1,−2.5 respectively.'))
add(13,('삼차함수의 영점이−1,0,2이고 f(1)=6이다. 함수를 구하라.','Find a cubic with zeros−1,0,2 and f(1)=6.'),[('서로 다른 세 영점을 인수로 쓰면 f(x)=A(x+1)x(x−2)이다.','The three distinct zeros give f(x)=A(x+1)x(x−2).'),('x=1에서−2A=6이므로 A=−3이다.','At x=1,−2A=6, so A=−3.')],d('f(x)=-3x(x+1)(x-2)'),('각 영점은 인수 하나를0으로 만들며 f(1)=−3×1×2×(−1)=6이다.','Each zero annihilates a factor, and f(1)=−3×1×2×(−1)=6.'))
add(14,('교재의 선형 기온 모형 T=0.02t+8.50에서 t는1900년 이후 연수, T는°C이다. (a)기울기와 절편을 해석하고 (b)2100년 모형값을 구하라.','In the textbook model T=0.02t+8.50, t is years since1900 and T is in°C. (a) Interpret slope and intercept; (b) evaluate the model for2100.'),[('기울기0.02는 모형에서 연간0.02°C 증가, 절편8.50은1900년의 모형 온도이다.','The slope represents a modeled increase of0.02°C per year;8.50 is the modeled1900 temperature.'),('2100년은 t=200이므로 T=0.02×200+8.50이다.','The year2100 corresponds to t=200, giving T=0.02×200+8.50.')],('(a)0.02°C/년,1900년에8.50°C. (b)12.50°C.','(a)0.02°C/year and8.50°C in1900. (b)12.50°C.'),('연도를2100으로 직접 대입하지 않고 경과연수200을 사용했다. 결과는 주어진 교재 모형의 산술값이다.','Used elapsed time200 rather than calendar year2100. This is the arithmetic output of the supplied textbook model.'),list('ab'))
add(15,('교재의 용량 모형 c=0.0417D(a+1)에서 D=200 mg, a는 나이(년)이다. 이 식만을 이용해 (a)기울기와 의미,(b)a=0의 모형값을 구하라.','For the textbook dosage model c=0.0417D(a+1), take D=200 mg and age a in years. Using only this formula, find(a) the slope and its interpretation and(b) its value at a=0.'),[('상수 D를 넣으면 c(a)=8.34a+8.34이다.','Substitution of D gives c(a)=8.34a+8.34.'),('기울기는 모형에서 나이1년당8.34 mg 증가를 뜻하며 a=0이면 절편값이다.','The slope describes an increase of8.34 mg per year in this model; a=0 gives the intercept.')],('(a)8.34 mg/년. (b)8.34 mg(교재 식의 값).','(a)8.34 mg/year. (b)8.34 mg as the textbook formula’s value.'),('0.0417×200=8.34를 확인했다. 실제 약물 선택이나 처방이 아닌 주어진 식의 계산이다.','Verified0.0417×200=8.34. This evaluates the supplied expression rather than selecting a drug or prescribing a dose.'),list('ab'))
add(16,('임대료 x달러일 때 임대되는 자리 수를 y=200−4x로 모형화한다. (a)물리적으로 가능한 그래프를 그리고 (b)기울기와 두 절편을 해석하라.','Rental demand is modeled by y=200−4x spaces at a rental price of x dollars. (a) Plot the physically relevant graph; (b) interpret its slope and both intercepts.'),[('x≥0과 y≥0을 함께 적용하면0≤x≤50이다.','Requiring both x≥0 and y≥0 gives0≤x≤50.'),('기울기−4는1달러 인상당4자리 감소, y절편200은 무료일 때200자리, x절편50은 수요가0이 되는 가격이다.','Slope−4 means4 fewer spaces for each$1 increase. The intercept200 is demand at zero price;50 is the price giving zero demand.')],('(a)(0,200)과(50,0)을 잇는 선분. (b)위 해석.','(a)The segment joining(0,200) and(50,0). (b)The interpretations above.'),('x=0,50을 대입해 양끝을 확인했다. 실제 자리 수는 정수지만 직선은 연속 수요 모형이다.','Substitution checks both endpoints. Actual spaces are integers; the line is a continuous demand model.'),list('ab'))
D.fig(16,[panel('Rental demand',(0,50,0,210),[[(0,200),(50,0)]],xlabel='$',ylabel='spaces')])
add(17,('섭씨와 화씨 관계 F=9C/5+32에 대해 (a)그래프를 그리고 (b)기울기와 F절편의 의미를 설명하라.','For F=9C/5+32, (a) sketch the Fahrenheit–Celsius relation and(b) interpret slope and F-intercept.'),[('기울기는9/5=1.8 °F/°C이며 섭씨1도 증가에 화씨1.8도 증가한다.','The slope is9/5=1.8°F/°C: a1°C increase gives a1.8°F increase.'),('C=0이면 F=32이므로 F절편은 섭씨0도에 대응하는 화씨 온도이다.','At C=0, F=32; the F-intercept is the Fahrenheit value corresponding to0°C.')],('(a)(0,32),(100,212)를 지나는 직선. (b)기울기1.8, 절편32.','(a)The line through(0,32),(100,212). (b)Slope1.8 and intercept32.'),('C=−40에서 F=−40이 되어 두 눈금이 일치하는 교차값을 확인했다.','At C=−40 the formula gives F=−40, checking where the two scales agree.'),list('ab'))
D.fig(17,[panel('Fahrenheit versus Celsius',(-40,100,-40,220),[[(-40,-40),(100,212)]],[(0,32)],xlabel='C',ylabel='F')])
add(18,('Jade는6:50, Jari는7:00에 출발해 일정 속도로 달린다. t는7시 후 분이며 그래프는 Jade의(0,10),(6,16), Jari의(0,0),(6,7)을 지난다. (a)더 빠른 사람,(b)각 속력 mi/h,(c)거리 함수를 구하라.','Jade leaves at6:50 and Jari at7:00, each at constant speed. For t minutes after7:00 the graph has Jade through(0,10),(6,16) and Jari through(0,0),(6,7). Find(a) the faster driver,(b) speeds in mi/h,(c) distance functions.'),[('Jade의 기울기는(16−10)/6=1 mi/min, Jari는7/6 mi/min이다.','Jade has slope(16−10)/6=1 mi/min, and Jari has slope7/6 mi/min.'),('시간당 단위로 바꾸려면60을 곱한다. 초기거리10과0을 각각 절편으로 넣는다.','Multiply by60 to convert to hourly units. Use initial distances10 and0 as the respective intercepts.')],('(a)Jari. (b)Jade60 mi/h,Jari70 mi/h. (c)f(t)=t+10(t≥−10),g(t)=7t/6(t≥0), 거리 mile.','(a)Jari. (b)Jade60 mi/h,Jari70 mi/h. (c)f(t)=t+10(t≥−10),g(t)=7t/6(t≥0), distances in miles.'),('f(−10)=0으로 이른 출발이 반영되며 f(6)=16,g(6)=7이 그래프와 일치한다.','f(−10)=0 encodes the earlier start, and f(6)=16,g(6)=7 match the graph.'),list('abc'))
D.fig(18,[panel('Jade blue; Jari red',(-10,15,0,30),[[(-10,0),(15,25)],[(0,0),(15,17.5)]],[(6,16),(6,7)],xlabel='min',ylabel='mile')])
add(19,('의자100개 생산비2200달러,300개 생산비4800달러이다. (a)선형 비용 C(x)를 구해 그리고,(b)기울기,(c)절편을 해석하라.','Producing100 chairs costs$2200 and300 chairs costs$4800. (a) Find and graph a linear cost C(x); (b) interpret its slope; (c) interpret its intercept.'),[(d(r'm=\frac{4800-2200}{300-100}=13,\quad b=2200-13(100)=900'),d(r'm=\frac{4800-2200}{300-100}=13,\quad b=2200-13(100)=900')),('기울기는 의자 한 개당 추가13달러, 절편은 생산량과 무관한 고정비900달러이다.','The slope is an additional$13 per chair; the intercept is a fixed$900 cost independent of output.')],d(r'C(x)=13x+900,\quad x\ge0'),('C(100)=2200,C(300)=4800으로 두 자료가 정확히 복원된다. 생산 개수는 실제로 비음수 정수이다.','C(100)=2200 and C(300)=4800 recover both observations. Actual chair counts are nonnegative integers.'),list('abc'))
D.fig(19,[panel('Chair production cost',(0,400,0,6500),[[(0,900),(400,6100)]],[(100,2200),(300,4800)],xlabel='chairs',ylabel='$')])
add(20,('월 주행480 mile에380달러,800 mile에460달러가 들었다. (a)선형 비용 C(d),(b)1500 mile 예상비,(c)그래프와 기울기,(d)절편,(e)선형 모형의 타당한 이유를 구하라.','Monthly driving costs were$380 for480 miles and$460 for800 miles. Find(a) a linear cost C(d),(b) its prediction for1500 miles,(c) graph and slope interpretation,(d) intercept interpretation,(e) a reason a linear model is plausible.'),[(d(r'm=\frac{460-380}{800-480}=0.25,\quad b=380-0.25(480)=260'),d(r'm=\frac{460-380}{800-480}=0.25,\quad b=380-0.25(480)=260')),('기울기는 mile당0.25달러의 변동비, 절편260달러는 주행하지 않아도 생기는 고정비이다. 고정비와 대략 일정한 mile당 비용의 합은 선형 모형이 된다.','The slope is a variable cost of$0.25 per mile; the$260 intercept is fixed cost even without driving. Fixed costs plus approximately constant per-mile costs motivate a linear model.')],('(a)C(d)=0.25d+260(d≥0). (b)635달러. (c)기울기0.25달러/mile. (d)고정비260달러. (e)고정비와 일정한 단위거리비의 합.','(a)C(d)=0.25d+260(d≥0). (b)$635. (c)Slope$0.25/mile. (d)Fixed cost$260. (e)Fixed cost plus constant per-mile cost.'),('C(480)=380,C(800)=460,C(1500)=635이다. 선형 가정은 비용 체계가 같은 범위에서 적용한다.','C(480)=380,C(800)=460,C(1500)=635. The linear assumption applies over a range with the same cost structure.'),list('abcde'))
D.fig(20,[panel('Monthly driving cost',(0,1600,0,700),[[(0,260),(1600,660)]],[(480,380),(800,460),(1500,635)],xlabel='miles',ylabel='$')])
add(21,('수면 압력15 lb/in²이고10 ft 내려갈 때마다4.34 lb/in² 증가한다. (a)깊이 d의 압력식,(b)압력100 lb/in²인 깊이를 구하라.','Pressure is15 lb/in² at the surface and rises4.34 lb/in² per10 ft of depth. Find(a) pressure as a function of depth d and(b) depth at100 lb/in².'),[('ft당 증가량은4.34/10=0.434이다.','The increase per foot is4.34/10=0.434.'),(d(r'P(d)=15+0.434d,\quad d=\frac{100-15}{0.434}\approx195.853'),d(r'P(d)=15+0.434d,\quad d=\frac{100-15}{0.434}\approx195.853'))],('(a)P(d)=15+0.434d,d≥0. (b)약195.85 ft.','(a)P(d)=15+0.434d,d≥0. (b)Approximately195.85 ft.'),('10 ft 간격 압력차가4.34이며 d=85/0.434를 넣으면100이 된다.','The10-ft pressure difference is4.34; substitution of d=85/0.434 gives100.'),list('ab'))
add(22,('같은 재질·길이 철사의 저항은 R(x)=kx⁻²이다. 지름0.005 m에서140Ω일 때 (a)k,(b)지름0.008 m에서 저항을 구하라.','For wires of the same material and length, resistance is R(x)=kx⁻². Given140Ω at diameter0.005 m, find(a) k and(b) resistance at0.008 m.'),[(d(r'k=140(0.005)^2=0.0035\ \Omega\,\mathrm{m^2}'),d(r'k=140(0.005)^2=0.0035\ \Omega\,\mathrm{m^2}')),(d(r'R(0.008)=0.0035/(0.008)^2=54.6875\ \Omega'),d(r'R(0.008)=0.0035/(0.008)^2=54.6875\ \Omega'))],('(a)k=0.0035 Ω·m². (b)54.6875Ω.','(a)k=0.0035 Ω·m². (b)54.6875Ω.'),('비율 검산:140×(0.005/0.008)²=54.6875이며 더 굵은 철사의 저항이 작다.','Ratio check:140×(0.005/0.008)²=54.6875; the thicker wire has lower resistance.'),list('ab'))
add(23,('조도가 광원까지 거리의 역제곱에 비례한다. 램프까지의 거리를 절반으로 줄이면 조도는 몇 배인가?','Illumination obeys an inverse-square law. By what factor does it change when the distance to a lamp is halved?'),[(d(r'\frac{I(r/2)}{I(r)}=\frac{k/(r/2)^2}{k/r^2}=4'),d(r'\frac{I(r/2)}{I(r)}=\frac{k/(r/2)^2}{k/r^2}=4'))],('4배이다.','It becomes4 times as bright.'),('r=2에서 r=1로 바꾸면 k/4에서 k로 바뀌어 같은 비율이다.','Changing r=2 to r=1 changes k/4 to k, confirming the factor.'))
add(24,('293 K로 일정한 산소 시료는 P=k/V를 따른다. V=0.671 m³에서 P=39 kPa일 때 (a)k,(b)V=0.916 m³의 압력을 구하라.','At constant293 K an oxygen sample follows P=k/V. Given P=39 kPa at V=0.671 m³, find(a) k and(b) pressure at V=0.916 m³.'),[(d(r'k=PV=39(0.671)=26.169\ \mathrm{kPa\,m^3}'),d(r'k=PV=39(0.671)=26.169\ \mathrm{kPa\,m^3}')),(d(r'P=26.169/0.916\approx28.5699\ \mathrm{kPa}'),d(r'P=26.169/0.916\approx28.5699\ \mathrm{kPa}'))],('(a)26.169 kPa·m³. (b)약28.57 kPa.','(a)26.169 kPa·m³. (b)Approximately28.57 kPa.'),('부피가 커져 압력이 감소하며 두 상태의 PV는 같은26.169이다.','Increasing volume lowers pressure, and PV is26.169 in both states.'),list('ab'))
vals=[.214*math.pi*30**2*v**3 for v in [10,15,25]]
add(25,('풍력터빈 모형 P=kAv³에서 (a)풍속만2배,(b)날개 길이만2배일 때 출력 배수를 구하라. (c)날개 길이30 m,k=0.214 kg/m³일 때 v=10,15,25 m/s의 W단위 출력을 구하라.','For turbine power P=kAv³, find the output factor if(a) only wind speed doubles and(b) only blade length doubles. (c) With blade length30 m and k=0.214 kg/m³, evaluate power in W at v=10,15,25 m/s.'),[('풍속은 세제곱이므로2³=8배이다. 회전 면적은 A=πr²이므로 날개 길이2배는 면적·출력4배이다.','The cubic speed dependence gives2³=8. Swept area A=πr² makes doubled blade length quadruple area and power.'),(d(r'P=0.214\pi(30)^2v^3=192.6\pi v^3\ \mathrm W'),d(r'P=0.214\pi(30)^2v^3=192.6\pi v^3\ \mathrm W'))],('(a)8배,(b)4배,(c)각각 '+', '.join(f'{v:,.2f}' for v in vals)+' W.','(a)8-fold,(b)4-fold,(c)respectively '+', '.join(f'{v:,.2f}' for v in vals)+' W.'),('단위는(kg/m³)·m²·(m³/s³)=kg·m²/s³=W이며 출력비도 풍속비의 세제곱이다.','Units are(kg/m³)·m²·(m³/s³)=kg·m²/s³=W; output ratios also equal cubed speed ratios.'),list('abc'))
add(26,('복사 모형 E(T)=5.67×10⁻⁸T⁴에서 (a)100≤T≤300 K의 그래프를 그리고 (b)T 증가에 따른 E 변화를 설명하라.','For E(T)=5.67×10⁻⁸T⁴, (a) graph100≤T≤300 K and(b) describe how E changes as T rises.'),[('T=100,200,300에서 E는 각각5.67,90.72,459.27이다.','At T=100,200,300 the values are5.67,90.72,459.27.'),('양의 온도에서 증가하며 같은 온도 증가에 따른 E 증가량도 커진다. 온도가2배이면 E는16배이다.','For positive temperature E increases at an increasing rate. Doubling temperature multiplies E by16.')],('(a)첨부 증가·아래로 볼록 그래프. (b)T⁴에 비례하여 가파르게 증가한다.','(a)Attached increasing, concave-up graph. (b)It grows rapidly in proportion to T⁴.'),('E(300)/E(100)=3⁴=81이다. 식은 단위면적당 복사출력을 나타내므로 E의 물리 단위는 W/m²이다.','E(300)/E(100)=3⁴=81. As radiant power per unit area, E physically has units W/m².'),list('ab'))
D.fig(26,[panel('Radiant exitance',(100,300,0,480),[samples(lambda z:5.67e-8*z**4,100,300)],[(100,5.67),(200,90.72),(300,459.27)],xlabel='K',ylabel='W/m²')])
for n,st,se,ko,en,ans,anse in [(27,'(a)진폭과 주기가 비슷하게 반복되는 산점도,(b)거의 일정한 음의 기울기를 가진 산점도','(a)a scatter plot with roughly repeating amplitude and period,(b)a scatter plot with nearly constant negative slope','(a)반복되는 봉우리와 골은 삼각함수에 맞고,(b)일정한 감소율은 일차함수에 맞는다.','(a)Repeating peaks and troughs suggest a trigonometric model;(b)a constant decrease suggests a linear model.','(a)A cos(Bx+C)+D 같은 삼각함수. (b)mx+b,m<0.','(a)A trigonometric model such as A cos(Bx+C)+D. (b)mx+b with m<0.'),(28,'(a)처음 완만했다가 위로 더 가파르게 증가하는 산점도,(b)양수이면서 처음 빠르게 감소하고0쪽으로 평평해지는 산점도','(a)a scatter plot rising slowly at first and then more steeply,(b)a positive plot that decreases rapidly and then flattens toward zero','(a)위로 볼록한 이차함수나 지수함수가 가능하다.(b)역수·역제곱 또는 지수감소 모형이 가능하다.','(a)An upward quadratic or exponential model is possible.(b)A reciprocal, inverse-square, or exponential-decay model is possible.','(a)예:ax²+c,a>0. (b)예:k/x 또는 k/x²,k>0,x>0. 수치 자료가 없어 유일한 선택은 아니다.','(a)For example ax²+c,a>0. (b)For example k/x or k/x²,k>0,x>0. Without numerical data the choice is not unique.')]:
 add(n,(st+'의 적절한 함수 모형 종류를 고르고 이유를 설명하라.','Choose suitable function families for '+se+' and explain.'),[(ko,en)],(ans,anse),('제시된 도해는 정량 적합계수를 결정하지 않으므로 모양이 뒷받침하는 함수족만 제안했다.','The supplied plots do not determine numerical fitting coefficients, so only families supported by their shape are proposed.'),list('ab'))
D.fig(27,[panel('(a) Periodic pattern; schematic',(0,8,0,4),dots=[(z,2+.8*math.cos(2*z)+.04*math.sin(13*z)) for z in [i/5 for i in range(41)]]),panel('(b) Linear trend; schematic',(0,8,0,4),dots=[(z,3.6-.4*z+.07*math.sin(9*z)) for z in [i/5 for i in range(41)]])],('원본 산점도의 질적 패턴을 재현한 합성 예시이며 원자료가 아니다.','Synthetic illustration of the source plot’s qualitative pattern, not original measurements.'))
D.fig(28,[panel('(a) Increasing curvature; schematic',(0,4,0,5),dots=[(z,1+.22*z*z+.07*math.sin(19*z)) for z in [i/8 for i in range(31)]]),panel('(b) Inverse trend; schematic',(0,8,0,5),dots=[(z,2/z+.04*math.sin(11*z)) for z in [.5+i/5 for i in range(36)]])],('원본 산점도의 질적 패턴을 재현한 합성 예시이며 원자료가 아니다.','Synthetic illustration of the source plot’s qualitative pattern, not original measurements.'))
def regression(n,pts,log=False):
 data=[(math.log(u),math.log(v)) for u,v in pts] if log else pts
 q=[(s.Rational(str(u)),s.Rational(str(v))) for u,v in data];N=len(q);sx=sum(u for u,v in q);sy=sum(v for u,v in q);sxx=sum(u*u for u,v in q);sxy=sum(u*v for u,v in q)
 slope=s.factor((N*sxy-sx*sy)/(N*sxx-sx*sx));b=s.factor((sy-slope*sx)/N)
 residuals=[v-(slope*u+b) for u,v in q];assert sum(residuals)==0 and sum(u*r for (u,v),r in zip(q,residuals))==0
 r2=1-float(sum(r*r for r in residuals)/sum((v-sy/N)**2 for u,v in q))
 D.checks.append({'number':n,'method':'log-linear least squares' if log else 'linear least squares','slope':float(slope),'intercept':float(b),'rSquared':r2,'normalEquationResiduals':[str(sum(residuals)),str(sum(u*r for (u,v),r in zip(q,residuals)))]})
 eq=d(r'm=\frac{n\sum xy-(\sum x)(\sum y)}{n\sum x^2-(\sum x)^2}='+f'{float(slope):.9g}'+r',\quad b=\bar y-m\bar x='+f'{float(b):.9g}')
 return float(slope),float(b),r2,('최소제곱 계수를 구한다. '+eq,'Compute the least-squares coefficients. '+eq)
def regfig(n,pts,fn,title,xlabel='x',ylabel='y',extra=()):
 xx=[u for u,v in pts];yy=[v for u,v in pts];lo=min(xx);hi=max(xx);dx=(hi-lo)*.1;dy=(max(yy)-min(yy))*.15
 D.fig(n,[panel(title,(max(0,lo-dx),hi+dx,min(0,min(yy)-dy),max(yy)+dy),[samples(fn,max(0,lo-dx),hi+dx),*extra],pts,xlabel=xlabel,ylabel=ylabel)])
ulcer=[(4000,14.1),(6000,13),(8000,13.4),(12000,12.5),(16000,12),(20000,12.4),(30000,10.5),(45000,9.4),(60000,8.2)]
m29,b29,r29,step=regression(29,ulcer);mend=(8.2-14.1)/56000;bend=14.1-mend*4000
add(29,('소득달러·100명당 평생 궤양률 자료 '+str(ulcer)+'에 대해(a)산점도와 선형성,(b)양끝점 직선,(c)회귀선,(d)25000달러,(e)80000달러의 회귀 예측,(f)200000달러 적용 타당성을 구하라.','For the(income in dollars,lifetime ulcers per100 people) data '+str(ulcer)+', find(a) scatter plot and linear suitability,(b) endpoint line,(c) regression line,(d) prediction at$25000,(e) at$80000,(f) suitability at$200000.'),[('자료는 대체로 감소하는 직선 근처에 있으므로 관측 범위 안에서 선형 근사가 가능하다.','The points lie near a decreasing line, supporting a linear approximation within the observed range.'),(d(f'L(x)={mend:.10f}x+{bend:.8f}'),d(f'L(x)={mend:.10f}x+{bend:.8f}')),step,('80000달러는 자료 밖 외삽이며200000달러에서는 음수 비율이 나와 모형이 부적절하다.','The$80000 value is an extrapolation. At$200000 the predicted rate becomes negative, making the model inappropriate.')],('(b)'+m(f'L(x)={mend:.10f}x+{bend:.8f}')+'; (c)'+m(f'R(x)={m29:.10f}x+{b29:.8f}')+f'; (d){m29*25000+b29:.3f}/100명; (e){m29*80000+b29:.3f}%; (f)부적절, 예측={m29*200000+b29:.3f}%.','(b)'+m(f'L(x)={mend:.10f}x+{bend:.8f}')+'; (c)'+m(f'R(x)={m29:.10f}x+{b29:.8f}')+f'; (d){m29*25000+b29:.3f} per100; (e){m29*80000+b29:.3f}%; (f)inappropriate, prediction={m29*200000+b29:.3f}%.'),('반올림 전 계수에서 잔차의 합과 입력가중 잔차의 합이 모두0이다. '+f'R²={r29:.5f}.','Before rounding, residuals and input-weighted residuals each sum to zero. '+f'R²={r29:.5f}.'),list('abcdef'))
regfig(29,ulcer,lambda z:m29*z+b29,'Ulcer rates: regression blue; endpoint line red','income $','per100',extra=[[(4000,14.1),(60000,8.2)]])
asbestos=[(50,2),(400,6),(500,5),(900,10),(1100,26),(1600,42),(1800,37),(2000,38),(3000,50)]
m30,b30,r30,step=regression(30,asbestos)
add(30,('실험의 석면 노출량(fibers/mL)·폐종양 발생률(%) 자료 '+str(asbestos)+'에 대해(a)회귀선,(b)산점도와 적합성,(c)y절편의 의미를 구하라.','For experimental asbestos exposure(fibers/mL) and lung-tumor percentage data '+str(asbestos)+', find(a) a regression line,(b) a scatter plot and fit assessment,(c) the meaning of the intercept.'),[step,('산점도는 상당한 산포가 있지만 대체로 증가하는 직선을 따른다. 절편은 노출량0에서의 예측 발생률이다.','Despite noticeable scatter, the points show an approximately increasing linear trend. The intercept predicts the percentage at zero exposure.'),('절편은 약0.305%로, 노출이 없어도 발생하는 배경 종양률의 모형 추정치이다. 관측 최저 노출은50이므로0에서의 값은 약한 외삽이다.','The intercept is about0.305%, a model estimate of background tumor incidence without exposure. Since the smallest observed exposure is50, the value at zero is a short extrapolation.')],('(a)'+m(f'y={m30:.8f}x{b30:+.8f}')+f'. (b)관측 범위의 대략적 모형,R²={r30:.4f}. (c)무노출 예측{b30:.3f}%의 배경 발생률 추정이다.','(a)'+m(f'y={m30:.8f}x{b30:+.8f}')+f'. (b)An approximate model over the observed range,R²={r30:.4f}. (c)Its zero-exposure prediction is{b30:.3f}%, an estimate of background incidence.'),('원자료9쌍을 사용했고 정규방정식의 두 잔차 합이0임을 확인했다.','Used all9 pairs and verified both normal-equation residual sums are zero.'),list('abc'))
regfig(30,asbestos,lambda z:m30*z+b30,'Exposure and tumor percentage','fibers/mL','%')
femur=[(50.1,178.5),(48.3,173.6),(45.2,164.8),(44.7,163.7),(44.5,168.3),(42.7,165),(39.5,155.4),(38,155.8)]
m31,b31,r31,step=regression(31,femur)
add(31,('남성8명의 대퇴골 길이·키(cm) 자료 '+str(femur)+'로(a)산점도,(b)회귀선과 그래프,(c)대퇴골53 cm의 예상 키를 구하라.','Using the8 male(femur length,height) pairs in cm '+str(femur)+', find(a) a scatter plot,(b) the regression line and graph,(c) predicted height for a53-cm femur.'),[step,('L=53을 회귀식에 대입한다. 관측 최대50.1 cm보다 크므로 외삽이다.','Substitute L=53 into the regression line. This extrapolates beyond the observed maximum50.1 cm.')],('(b)'+m(f'H(L)={m31:.8f}L+{b31:.8f}')+f'; (c)약{m31*53+b31:.2f} cm.','(b)'+m(f'H(L)={m31:.8f}L+{b31:.8f}')+f'; (c)approximately{m31*53+b31:.2f} cm.'),('최소제곱 정규방정식의 잔차합0을 확인했다. '+f'R²={r31:.5f}. 이 표본에 적합한 모형이다.','Verified zero residual sums in the least-squares normal equations. '+f'R²={r31:.5f}. The model is fitted to this sample.'),list('abc'))
regfig(31,femur,lambda z:m31*z+b31,'Femur length and height','femur cm','height cm')
for n,base,data,ask,desc,de,unit in [(32,2000,[(0,8.24),(2,8.44),(4,8.95),(6,10.40),(8,11.26),(10,11.54),(12,11.88),(14,12.52),(16,12.90)],[2005,2017],'미국 주거용 전기 소매가격','US residential electricity price','cents/kWh'),(33,1985,[(0,60083),(5,66533),(10,70099),(15,76784),(20,84077),(25,87302),(30,94071)],[2002,2017],'세계 일평균 석유 소비량','world daily oil consumption','thousand barrels/day')]:
 slope,b,r2,step=regression(n,data);pred=[slope*(yr-base)+b for yr in ask]
 add(n,(f'{desc}의({base}년 이후 연수, {unit}) 자료 '+str(data)+f'로(a)산점도와 선형 적합성,(b)회귀선과 그래프,(c){ask[0]}년과{ask[1]}년의 모형값을 구하라.',f'For {de}, the(years since{base},{unit}) data are '+str(data)+f'. Find(a) a scatter plot and linear suitability,(b) the regression line and graph,(c) predictions for{ask[0]} and{ask[1]}.'),[('산점도는 대체로 직선적으로 상승한다.','The scatter plot shows an approximately linear upward trend.'),step,(f'연도를 경과시간으로 바꾸면 t={ask[0]-base},{ask[1]-base}이다. 첫 값은 보간, 두 번째 값은 표의 끝을 넘는 외삽이다.',f'Convert the years to elapsed times t={ask[0]-base},{ask[1]-base}. The first estimate interpolates; the second extrapolates beyond the table.')],('(b)'+m(f'y={slope:.9f}t+{b:.9f}')+f'; (c){pred[0]:.4f}, {pred[1]:.4f} {unit}.','(b)'+m(f'y={slope:.9f}t+{b:.9f}')+f'; (c){pred[0]:.4f}, {pred[1]:.4f} {unit}.'),(f'모든 자료를 사용한 회귀의 잔차합을 확인했다. R²={r2:.5f}.',f'Checked the residual sums using every data point. R²={r2:.5f}.'),list('abc'))
 regfig(n,data,lambda z,m=slope,b=b:m*z+b,de,f'years since{base}',unit)
planet=[(.387,.241),(.723,.615),(1,1),(1.523,1.881),(5.203,11.861),(9.541,29.457),(19.190,84.008),(30.086,164.784)]
pow34,logk34,r34,step=regression(34,planet,True);k34=math.exp(logk34)
add(34,('수성부터 해왕성까지의(태양거리 d:지구=1,공전주기 T:년) 자료 '+str(planet)+'로(a)거듭제곱 모형을 적합하고(b)T²∝d³라는 Kepler 제3법칙과 비교하라.','For Mercury through Neptune, the(distance d with Earth=1,period T in years) data are '+str(planet)+'. (a) Fit a power law and(b) compare with Kepler’s third law T²∝d³.'),[('T=kdᵖ의 로그를 취하여 log T=log k+p log d를 최소제곱 직선으로 적합한다. 아래 계수식의 x,y는 각각 log d,log T이다.','Take logs of T=kdᵖ and fit log T=log k+p log d by least squares. In the coefficient formula below,x and y mean log d and log T.'),step,('지수는 약1.5, 계수는 약1이므로 T²≈d³이다.','The exponent is near1.5 and the coefficient near1, so T²≈d³.')],('(a)'+m(rf'T\approx{k34:.8f}d^{{{pow34:.8f}}}')+'; (b)제3법칙을 잘 뒷받침한다.','(a)'+m(rf'T\approx{k34:.8f}d^{{{pow34:.8f}}}')+'; (b)The fit strongly supports the third law.'),('로그 자료 정규방정식의 잔차합0을 확인했다. '+f'로그 R²={r34:.8f}. 표의 반올림 때문에 정확히1,1.5가 아닐 수 있다.','Checked zero residual sums for the log-data normal equations. '+f'Log-space R²={r34:.8f}. Rounded data need not produce exactly1 and1.5.'),list('ab'))
regfig(34,planet,lambda z:k34*z**pow34,'Planetary period power fit','d','years')
a35=.7*60**.3;b35=(4/.7)**(1/.3)
add(35,('동굴 면적 A(m²)와 박쥐 종수 S의 모형은 S=0.7A⁰·³이다. (a)A=60일 때 종수,(b)S=4일 때 면적을 추정하라.','The cave-area and bat-species model is S=0.7A⁰·³ with A in m². Estimate(a) species count at A=60 and(b) area for S=4.'),[(d(r'S(60)=0.7(60)^{0.3}\approx'+f'{a35:.6f}'),d(r'S(60)=0.7(60)^{0.3}\approx'+f'{a35:.6f}')),(d(r'A=(4/0.7)^{1/0.3}\approx'+f'{b35:.6f}'),d(r'A=(4/0.7)^{1/0.3}\approx'+f'{b35:.6f}'))],(f'(a)약{a35:.2f}종(대략2~3종). (b)약{b35:.2f} m².',f'(a)About{a35:.2f} species(roughly2–3). (b)About{b35:.2f} m².'),('추정 면적을0.7A⁰·³에 넣으면4가 복원된다. 종수 모형은 연속적인 평균 추정값을 주므로 정수가 아닐 수 있다.','Substituting the estimated area into0.7A⁰·³ restores4. The model gives a continuous expected count, which need not be an integer.'),list('ab'))
islands=[(4,5),(40,9),(3459,40),(4411,39),(29418,84),(44218,76)]
p36,lk36,r36,step=regression(36,islands,True);k36=math.exp(lk36);pred36=k36*291**p36
add(36,('카리브 섬의(면적 A:mi²,파충류·양서류 종수 N) 자료 Saba(4,5),Montserrat(40,9),Puerto Rico(3459,40),Jamaica(4411,39),Hispaniola(29418,84),Cuba(44218,76)로(a)거듭제곱 모형,(b)면적291 mi²인 Dominica의 종수를 구하라.','For Caribbean islands the(area A in mi²,reptile/amphibian species N) pairs are Saba(4,5),Montserrat(40,9),Puerto Rico(3459,40),Jamaica(4411,39),Hispaniola(29418,84),Cuba(44218,76). Find(a) a power model and(b) the prediction for Dominica,area291 mi².'),[('N=kAᵖ에서 log N=log k+p log A를 적합한다. 아래 x,y는 log A,log N이다.','Fit log N=log k+p log A for N=kAᵖ. In the next formula,x,y are log A,log N.'),step,(d(rf'N(291)={k36:.8f}(291)^{{{p36:.8f}}}\approx{pred36:.5f}'),d(rf'N(291)={k36:.8f}(291)^{{{p36:.8f}}}\approx{pred36:.5f}'))],('(a)'+m(rf'N\approx{k36:.8f}A^{{{p36:.8f}}}')+f'. (b)약{pred36:.2f}, 대략{round(pred36)}종.','(a)'+m(rf'N\approx{k36:.8f}A^{{{p36:.8f}}}')+f'. (b)About{pred36:.2f}, roughly{round(pred36)} species.'),('로그 정규방정식의 잔차합0을 확인했다. '+f'로그 R²={r36:.5f}. 종수는 이 경험적 모형의 추정값이다.','Verified zero residual sums for the log normal equations. '+f'Log-space R²={r36:.5f}. The species count is an empirical-model estimate.'),list('ab'))
regfig(36,islands,lambda z:k36*z**p36,'Island area and species','mi²','species')
add(37,('세기 S>0인 점광원·힘이 모든 방향으로 균일하게 퍼진다. 반지름 r에서 강도는 S를 해당 구면 넓이로 나눈 값일 때 역제곱 법칙을 유도하라.','A point source of strength S>0 spreads uniformly in all directions. At radius r its intensity is S divided by the sphere’s surface area. Derive the inverse-square law.'),[('반지름 r의 구면 넓이는4πr²이다. 총량 S를 이 넓이에 균등 분배한다.','A sphere of radius r has surface area4πr². Spread the total strength S uniformly over that area.'),(d(r'I(r)=\frac S{4\pi r^2}=\frac{k}{r^2},\quad k=\frac S{4\pi}>0,\quad r>0'),d(r'I(r)=\frac S{4\pi r^2}=\frac{k}{r^2},\quad k=\frac S{4\pi}>0,\quad r>0'))],d(r'I(r)=k/r^2,\quad k=S/(4\pi)'),('I(r)·4πr²=S이므로 모든 반지름의 구면에서 원천의 총 세기가 보존된다.','Since I(r)·4πr²=S, the total source strength is conserved across every surrounding sphere.'))
D.save(37)
