"""Original cross-product solutions with independent symbolic checks."""
from early_helpers import Book
import sympy as s,math,json
from pathlib import Path
b=Book('12.4',[899,900,901]);checks=[]
def m(x):return r'\('+x+r'\)'
def v(a):return r'\langle'+','.join(s.latex(s.simplify(x))for x in a)+r'\rangle'
def add(n,k,e,ks,es,a,ae=None,parts=[],ck='원래 조건에 대입하여 확인했다.',ce='The result was checked against the original conditions.'):
 b.add(n,899 if n<=10 else 900 if n<=39 else 901,('외적과 공간기하','Cross products and spatial geometry'),(k,e),list(zip(ks,es)),(a,a if ae is None else ae),parts,check=(ck,ce));b.E[n]['conceptHref']='../../calc1/index.html'
def eq(label,a,c):
 if isinstance(a,s.MatrixBase):assert all(s.simplify(q)==0 for q in a-c),(label,a,c)
 else:assert s.simplify(a-c)==0,(label,a,c)
 checks.append(label)
t=s.symbols('t',real=True);I=s.Matrix([1,0,0]);J=s.Matrix([0,1,0]);K=s.Matrix([0,0,1]);Z=s.zeros(3,1)
for n,aa,bb in [(1,(2,3,0),(1,0,5)),(2,(4,3,-2),(2,-1,1)),(3,(0,2,-4),(-1,3,1)),(4,(3,3,-3),(3,-3,3)),(5,(s.Rational(1,2),s.Rational(1,3),s.Rational(1,4)),(1,2,-3)),(6,(t,s.cos(t),s.sin(t)),(1,-s.sin(t),s.cos(t))),(7,(t**3,t**2,t),(t,2*t,3*t)),(8,(1,0,-2),(0,1,1))]:
 a=s.Matrix(aa);c=s.Matrix(bb);r=s.simplify(a.cross(c));eq(f'{n} perpendicular a',r.dot(a),0);eq(f'{n} perpendicular b',r.dot(c),0)
 add(n,m('a='+v(a)+r',\ b='+v(c))+'의 외적을 구하고 두 벡터에 수직임을 확인하라.'+(' 세 벡터를 원점에서 그려라.'if n==8 else''),'Find the cross product for '+m('a='+v(a)+r',\ b='+v(c))+' and verify orthogonality.'+(' Sketch all three vectors from the origin.'if n==8 else''),[m(r'a\times b=\langle a_2b_3-a_3b_2,a_3b_1-a_1b_3,a_1b_2-a_2b_1\rangle'),m(r'(a\times b)\cdot a=(a\times b)\cdot b=0')],[m(r'a\times b=\langle a_2b_3-a_3b_2,a_3b_1-a_1b_3,a_1b_2-a_2b_1\rangle'),m(r'(a\times b)\cdot a=(a\times b)\cdot b=0')],m(r'a\times b='+v(r)),ck='두 내적을 성분별로 전개해0임을 독립 확인했다.',ce='Both dot products were independently expanded and simplified to zero.')
for n,st,steps,ans in [(9,r'(i\times j)\times k',[r'i\times j=k',r'k\times k=0'],'0'),(10,r'k\times(i-2j)',[r'k\times i=j,\quad k\times j=-i',r'k\times(i-2j)=j+2i'],'2i+j'),(11,r'(j-k)\times(k-i)',[r'j\times k-j\times i-k\times k+k\times i=i+k+j'],'i+j+k'),(12,r'(i+j)\times(i-j)',[r'i\times i-i\times j+j\times i-j\times j=-k-k'],'-2k')]:add(n,'행렬식 없이 외적 성질로 '+m(st)+'를 구하라.','Use cross-product properties without determinants to evaluate '+m(st)+'.',[m(q)for q in steps],[m(q)for q in steps],m(ans),ck='기저의 순환 외적 i×j=k,j×k=i,k×i=j를 사용했다.',ce='The cyclic basis relations i×j=k,j×k=i,k×i=j were used.')
add(13,'(a)a·(b×c),(b)a×(b·c),(c)a×(b×c),(d)a·(b·c),(e)(a·b)×(c·d),(f)(a×b)·(c×d)의 의미와 결과 종류를 설명하라.','Classify(a)a·(b×c),(b)a×(b·c),(c)a×(b×c),(d)a·(b·c),(e)(a·b)×(c·d),(f)(a×b)·(c×d).',['내적은 스칼라, 외적은 벡터를 내놓으며 두 연산 모두 입력은 두 벡터이다.','(b),(d)는 두 번째 입력이 스칼라이고(e)는 두 입력이 모두 스칼라라 정의되지 않는다.'],['A dot product returns a scalar, a cross product returns a vector, and each requires vector inputs.','In(b),(d)the second input is scalar; in(e)both are scalar, so these are undefined.'],'(a)스칼라,(c)벡터,(f)스칼라. (b),(d),(e)는 정의되지 않음.','(a)Scalar,(c)Vector,(f)Scalar. (b),(d),(e)are undefined.',list('abcdef'))
add(14,'그림에서 u는오른쪽 아래로 길이10,v는아래로 길이8이며 공통 시작점의 각은60°이다. |u×v|와 종이 안팎 방향을 구하라.','u points down-right with length10, v downward with length8, and their common-tail angle is60°. Find the cross-product magnitude and page direction.',[m(r'|u\times v|=10\cdot8\sin60^\circ'),'u에서v로 작은 각으로 돌면 시계방향이므로 외적은 종이 안쪽이다.'],[m(r'|u\times v|=10\cdot8\sin60^\circ'),'The smaller turn from u to v is clockwise, so the cross product points into the page.'],m(r'|u\times v|=40\sqrt3')+'; 종이 안쪽.',m(r'|u\times v|=40\sqrt3')+'; into the page.',ck='화살표 순서를 바꾸면 방향이 뒤집힌다.',ce='Reversing vector order reverses the direction.')
add(15,'u는오른쪽 길이4이고 그 끝에서v가오른쪽 아래로 길이3이다. 그림의 내각150°를 이용해 |u×v|와 종이 안팎 방향을 구하라.','u runs right with length4; v runs down-right from its tip with length3. The displayed interior angle is150°. Find |u×v| and its page direction.',[m(r'\theta=180^\circ-150^\circ=30^\circ,\quad |u\times v|=4\cdot3\sin30^\circ'),'공통 시작점으로 옮겼을 때 u에서v로의 회전은 시계방향이다.'],[m(r'\theta=180^\circ-150^\circ=30^\circ,\quad |u\times v|=4\cdot3\sin30^\circ'),'After translating to a common tail, the turn from u to v is clockwise.'],m(r'|u\times v|=6')+'; 종이 안쪽.',m(r'|u\times v|=6')+'; into the page.',ck='sin150°=sin30°이지만 실제 두 벡터 사이의 작은 각은30°이다.',ce='Although sin150°=sin30°, the smaller angle between the vectors is30°.')
add(16,'xy평면의 양의x,y성분을 가진 a의 길이는3, 양의z방향 b의 길이는2이다. (a)|a×b|,(b)각 성분의 부호를 구하라.','a has positive x,y components in xy and length3; b points along positive z with length2. Find(a)|a×b| and(b)its component signs.',[m(r'a=\langle a_x,a_y,0\rangle,\quad b=\langle0,0,2\rangle,\quad a\times b=\langle2a_y,-2a_x,0\rangle'),m(r'|a\times b|=3\cdot2=6')],[m(r'a=\langle a_x,a_y,0\rangle,\quad b=\langle0,0,2\rangle,\quad a\times b=\langle2a_y,-2a_x,0\rangle'),m(r'|a\times b|=3\cdot2=6')],m(r'(a)\ 6;\quad(b)\ (+,-,0)'),parts=list('ab'),ck='a와bは수직이므로 sinθ=1이다.'.replace('は','는'),ce='a and b are perpendicular, so sinθ=1.')
a=s.Matrix([2,-1,3]);c=s.Matrix([4,2,1]);r=a.cross(c)
add(17,m('a='+v(a)+r',\ b='+v(c))+'에 대해 양 순서의 외적을 구하라.','Find both ordered cross products for '+m('a='+v(a)+r',\ b='+v(c))+'.',[m(r'b\times a=-(a\times b)')],[m(r'b\times a=-(a\times b)')],m(r'a\times b='+v(r)+r',\quad b\times a='+v(-r)))
a=s.Matrix([1,0,1]);c=s.Matrix([2,1,-1]);dd=s.Matrix([0,1,3]);left=a.cross(c.cross(dd));right=a.cross(c).cross(dd)
add(18,m('a='+v(a)+r',b='+v(c)+r',c='+v(dd))+'에서 외적의 결합법칙이 성립하지 않음을 보여라.','Show that cross products are not associative for '+m('a='+v(a)+r',b='+v(c)+r',c='+v(dd))+'.',[m(r'b\times c='+v(c.cross(dd))+r',\quad a\times b='+v(a.cross(c)))],[m(r'b\times c='+v(c.cross(dd))+r',\quad a\times b='+v(a.cross(c)))],m(r'a\times(b\times c)='+v(left)+r'\ne'+v(right)+r'=(a\times b)\times c'),ck='두 결과의 각 성분을 직접 비교했다.',ce='The two resulting vectors differ componentwise.')
for n,aa,bb in [(19,(3,2,1),(-1,1,0)),(20,(0,1,-1),(1,1,0))]:
 a=s.Matrix(aa);c=s.Matrix(bb);r=a.cross(c);unit=r/r.norm();add(n,m(v(a)+r',\ '+v(c))+'에 모두 수직인 두 단위벡터를 구하라.','Find both unit vectors perpendicular to '+m(v(a)+r',\ '+v(c))+'.',[m(r'n=a\times b='+v(r)+r',\quad |n|='+s.latex(r.norm()))],[m(r'n=a\times b='+v(r)+r',\quad |n|='+s.latex(r.norm()))],m(r'u=\pm'+v(unit)),ck='두 내적은0이고 정규화한 길이는1이다.',ce='Both dot products vanish and the normalized length is1.')
a=s.Matrix(s.symbols('a1:4',real=True));c=s.Matrix(s.symbols('b1:4',real=True));dd=s.Matrix(s.symbols('c1:4',real=True));ee=s.Matrix(s.symbols('d1:4',real=True));lam=s.symbols('lambda',real=True)
proof_rows=[(21,r'0\times a=0=a\times0','외적의 성분 공식에0벡터를 대입하면 각 항이0이다.','Substituting the zero vector in the coordinate formula makes every term zero.',Z.cross(a),Z),(22,r'(a\times b)\cdot b=0','여섯 삼중곱 항이 서로 반대 부호로 두 번씩 나타나 상쇄된다.','The six triple products cancel in opposite-signed pairs.',a.cross(c).dot(c),0),(23,r'a\times b=-b\times a','입력 순서를 바꾸면 각 성분의 두 곱이 교환되어 부호가 반대가 된다.','Reversing inputs exchanges the two products in each component and reverses the sign.',a.cross(c),-c.cross(a)),(24,r'(\lambda a)\times b=\lambda(a\times b)=a\times(\lambda b)','각 성분의 두 항 모두에 λ가 곱해져 공통인수로 빠져나온다.','Every term in each component contains λ, which factors out.',(lam*a).cross(c),lam*a.cross(c)),(25,r'a\times(b+c)=a\times b+a\times c','첫 성분을 전개하면 a₂(b₃+c₃)−a₃(b₂+c₂)이다. b항,c항을 모으고 다른 성분에도 같은 전개를 적용한다.','The first component is a₂(b₃+c₃)−a₃(b₂+c₂). Group b-terms and c-terms, then repeat for the other components.',a.cross(c+dd),a.cross(c)+a.cross(dd)),(26,r'(a+b)\times c=a\times c+b\times c','반대칭성과 오른쪽 분배법칙을 적용하면 −c×(a+b)=−c×a−c×b이다.','Antisymmetry and right distributivity give−c×(a+b)=−c×a−c×b.',(a+c).cross(dd),a.cross(dd)+c.cross(dd))]
for n,formula,ko,en,L,R in proof_rows:
 eq(f'{n} identity',L,R);add(n,'항등식을 증명하라: '+m(formula),'Prove '+m(formula)+'.',[ko],[en],m(formula),ck='일반 실수 성분을 두어 기호 전개로도 검산했다.',ce='The identity was also checked by symbolic expansion with arbitrary real components.')
for n,pts,names in [(27,[(-3,0),(-1,3),(5,2),(3,-1)],'ABCD'),(28,[(1,0,2),(3,3,3),(7,5,8),(5,2,7)],'PQRS')]:
 pp=[s.Matrix(list(p)+([0]if len(p)==2 else[]))for p in pts];u=pp[1]-pp[0];vv=pp[3]-pp[0];cross=u.cross(vv);add(n,'꼭짓점 '+m(','.join(f'{names[i]}={pts[i]}'for i in range(4)))+'인 평행사변형의 넓이를 구하라.','Find the parallelogram area for '+m(','.join(f'{names[i]}={pts[i]}'for i in range(4)))+'.',[m(r'u='+v(u)+r',\ v='+v(vv)+r',\ u\times v='+v(cross))],[m(r'u='+v(u)+r',\ v='+v(vv)+r',\ u\times v='+v(cross))],m(r'A='+s.latex(cross.norm())),ck='같은 꼭짓점에서 나가는 두 인접변을 사용했다.',ce='The calculation uses two adjacent edges from a common vertex.')
for n,pts in [(29,[(3,1,1),(5,2,4),(8,5,3)]),(30,[(-2,0,4),(1,3,-2),(0,3,5)]),(31,[(7,-2,0),(3,1,3),(4,-4,2)]),(32,[(2,-3,4),(-1,-2,2),(3,1,-3)])]:
 P,Q,R=map(s.Matrix,pts);u=Q-P;vv=R-P;cr=u.cross(vv);eq(f'{n} normal perpendicular',cr.dot(u),0)
 add(n,m(','.join(f'{name}={point}'for name,point in zip('PQR',pts)))+'에서(a)평면에 수직인0이 아닌 벡터,(b)삼각형 넓이를 구하라.','For '+m(','.join(f'{name}={point}'for name,point in zip('PQR',pts)))+', find(a)a nonzero plane normal and(b)triangle area.',[m(r'PQ='+v(u)+r',\ PR='+v(vv)),m(r'n=PQ\times PR,\quad A=|n|/2')],[m(r'PQ='+v(u)+r',\ PR='+v(vv)),m(r'n=PQ\times PR,\quad A=|n|/2')],m(r'(a)\ n='+v(cr)+r';\quad(b)\ A='+s.latex(cr.norm()/2)),parts=list('ab'),ck='법선의 반대 부호도 가능하며 넓이는 양수이다.',ce='The opposite normal is also valid, and the area is positive.')
for n,aa,bb,cc in [(33,(1,2,3),(-1,1,2),(2,1,4)),(34,(1,1,0),(0,1,1),(1,1,1))]:
 aa,bb,cc=map(s.Matrix,(aa,bb,cc));det=aa.dot(bb.cross(cc));eq(f'{n} determinant',det,s.Matrix.hstack(aa,bb,cc).det());add(n,m('a='+v(aa)+r',b='+v(bb)+r',c='+v(cc))+'가 만드는 평행육면체 부피를 구하라.','Find the parallelepiped volume generated by '+m('a='+v(aa)+r',b='+v(bb)+r',c='+v(cc))+'.',[m(r'a\cdot(b\times c)='+s.latex(det))],[m(r'a\cdot(b\times c)='+s.latex(det))],m(r'V='+s.latex(abs(det))),ck='부호있는 삼중곱의 절댓값을 취했다.',ce='Take the absolute value of the signed triple product.')
for n,pts in [(35,[(-2,1,0),(2,3,2),(1,4,-1),(3,6,1)]),(36,[(3,0,1),(-1,2,5),(5,1,-1),(0,4,2)])]:
 P,Q,R,SS=map(s.Matrix,pts);u=Q-P;vv=R-P;w=SS-P;det=u.dot(vv.cross(w));add(n,m(','.join(f'{a}={pt}'for a,pt in zip('PQRS',pts)))+'에서 인접변PQ,PR,PS의 평행육면체 부피를 구하라.','Find the volume with adjacent edges PQ,PR,PS for '+m(','.join(f'{a}={pt}'for a,pt in zip('PQRS',pts)))+'.',[m(r'PQ='+v(u)+r',PR='+v(vv)+r',PS='+v(w)),m(r'PQ\cdot(PR\times PS)='+s.latex(det))],[m(r'PQ='+v(u)+r',PR='+v(vv)+r',PS='+v(w)),m(r'PQ\cdot(PR\times PS)='+s.latex(det))],m(r'V='+s.latex(abs(det))),ck='끝점 좌표 자체가 아니라 P로부터의 변위를 사용했다.',ce='Use displacement from P rather than the endpoint coordinates themselves.')
u=s.Matrix([1,5,-2]);vv=s.Matrix([3,-1,0]);w=s.Matrix([5,9,-4]);eq('37 coplanarity',u.dot(vv.cross(w)),0)
add(37,m('u='+v(u)+r',v='+v(vv)+r',w='+v(w))+'가 한 평면에 있음을 스칼라 삼중곱으로 보여라.','Use the scalar triple product to show coplanarity of '+m('u='+v(u)+r',v='+v(vv)+r',w='+v(w))+'.',[m(r'u\cdot(v\times w)=0')],[m(r'u\cdot(v\times w)=0')],'세 벡터는 한 평면에 있다.','The three vectors are coplanar.',ck='직접 w=2u+v라는 관계도 성립한다.',ce='Directly, w=2u+v also holds.')
P,Q,R,SS=map(s.Matrix,[(1,3,2),(3,-1,6),(5,2,0),(3,6,-4)]);det=(Q-P).dot((R-P).cross(SS-P))
add(38,'A=(1,3,2),B=(3,−1,6),C=(5,2,0),D=(3,6,−4)가 같은 평면에 있는지 판정하라.','Test whether A=(1,3,2),B=(3,−1,6),C=(5,2,0),D=(3,6,−4) are coplanar.',[m(r'AB='+v(Q-P)+r',AC='+v(R-P)+r',AD='+v(SS-P)),m(r'AB\cdot(AC\times AD)='+s.latex(det))],[m(r'AB='+v(Q-P)+r',AC='+v(R-P)+r',AD='+v(SS-P)),m(r'AB\cdot(AC\times AD)='+s.latex(det))],'같은 평면에 있다.'if det==0 else'같은 평면에 있지 않다.','Coplanar.'if det==0 else'Not coplanar.',ck='삼중곱이0이면 세 변위벡터가 선형종속이다.',ce='A zero triple product is equivalent to linear dependence of the three displacements.')
add(39,'길이18cm 페달축의 오른쪽 끝P에 대해60N 힘의 토크 크기를 구하라. 그림에서 축은수평보다10°기울고 힘의 작용선은수평과70°이다.','Find the torque magnitude about the right pivotP of an18cm pedal arm under60N. The arm tilts10° from horizontal and the force line makes70° with horizontal.',[m(r'\theta=80^\circ,\quad |\tau|=0.18\cdot60\sin80^\circ')],[m(r'\theta=80^\circ,\quad |\tau|=0.18\cdot60\sin80^\circ')],m(r'|\tau|=10.8\sin80^\circ\approx10.636\ \mathrm{N\,m}'),ck='18cm를0.18m로 변환했고, 위치벡터는 P에서 힘 작용점으로 향한다.',ce='18cm was converted to0.18m, and r points from P to the force application point.')
add(40,'변속레버에 오른쪽 수평20lb 힘을 가한다. P 위높이2ft인 손잡이와 높이0.6ft인 굽은점에 각각 작용할 때 P에 대한 토크 크기를 구하라.','Apply a20lb rightward horizontal force at a gearshift handle2ft above P, then at its elbow0.6ft above P. Find both torque magnitudes.',[m(r'\tau_z=r_xF_y-r_yF_x=-20r_y'),'수평 힘의 모멘트팔은 각 점의 수직높이이다.'],[m(r'\tau_z=r_xF_y-r_yF_x=-20r_y'),'The lever arm for a horizontal force is the vertical height.'],m(r'(a)\ 40\ \mathrm{ft\,lb};\quad(b)\ 12\ \mathrm{ft\,lb}'),parts=list('ab'),ck='수평거리1ft,0.6ft는 이 수평 힘의 토크에 기여하지 않는다.',ce='The horizontal offsets do not contribute to torque from this horizontal force.')
add(41,'양의y축 위30cm 렌치 끝에 방향(0,3,−4)로 힘을 가한다. 토크100N·m를 만들 힘의 크기를 구하라.','A30cm wrench lies along positive y. A force in direction(0,3,−4)must produce100N·m. Find its magnitude.',[m(r'r=\langle0,0.3,0\rangle,\quad F=\frac{f}{5}\langle0,3,-4\rangle'),m(r'r\times F=\langle-0.24f,0,0\rangle,\quad0.24f=100')],[m(r'r=\langle0,0.3,0\rangle,\quad F=\frac{f}{5}\langle0,3,-4\rangle'),m(r'r\times F=\langle-0.24f,0,0\rangle,\quad0.24f=100')],m(r'f=\frac{1250}{3}\approx416.667\ \mathrm N'),ck='힘의y성분은レンチ에평행이라 토크를 만들지 않는다.'.replace('レンチ','렌치'),ce='The y-component is parallel to the wrench and produces no torque.')
add(42,'v=5j이고 길이3인 u가xy평면에서 회전한다. |u×v|의 최댓값·최솟값과 외적의 방향을 구하라.','Let v=5j while u of length3 rotates in xy. Find the maximum/minimum of |u×v| and the possible directions.',[m(r'u=3\langle\cos\theta,\sin\theta,0\rangle,\quad u\times v=15\cos\theta\,k')],[m(r'u=3\langle\cos\theta,\sin\theta,0\rangle,\quad u\times v=15\cos\theta\,k')],'최댓값15,최솟값0. 0이 아니면 +z 또는−z방향이다.','Maximum15, minimum0; nonzero products point along positive or negative z.',ck='u가±i방향이면최대,±j방향이면0이며 영벡터에는 방향이 없다.',ce='The maximum occurs along±i; the product vanishes along±j and then has no direction.')
add(43,m(r'a\cdot b=\sqrt3,\quad a\times b=\langle1,2,2\rangle')+'일 때 사이각을 구하라.','Find the angle given '+m(r'a\cdot b=\sqrt3,\quad a\times b=\langle1,2,2\rangle')+'.',[m(r'|a\times b|=3,\quad\tan\theta=\frac{|a\times b|}{a\cdot b}=\sqrt3'),'내적이 양수이므로 예각을 선택한다.'],[m(r'|a\times b|=3,\quad\tan\theta=\frac{|a\times b|}{a\cdot b}=\sqrt3'),'The positive dot product selects the acute angle.'],m(r'\theta=\pi/3=60^\circ'))
add(44,'(a)(1,2,1)×v=(3,1,−5)의 모든 해를 구하고 (b)우변이(3,1,5)이면 해가 없는 이유를 설명하라.','Solve(a)(1,2,1)×v=(3,1,−5)and explain(b)why replacing the right side with(3,1,5)gives no solution.',[m(r'v=\langle x,y,z\rangle:\quad2z-y=3,\ x-z=1,\ y-2x=-5'),m(r'z=t,\quad x=1+t,\quad y=2t-3'),m(r'\langle1,2,1\rangle\cdot\langle3,1,5\rangle=10\ne0')],[m(r'v=\langle x,y,z\rangle:\quad2z-y=3,\ x-z=1,\ y-2x=-5'),m(r'z=t,\quad x=1+t,\quad y=2t-3'),m(r'\langle1,2,1\rangle\cdot\langle3,1,5\rangle=10\ne0')],m(r'(a)\ v=\langle1+t,2t-3,t\rangle,\ t\in\mathbb R')+'; (b)해 없음.',m(r'(a)\ v=\langle1+t,2t-3,t\rangle,\ t\in\mathbb R')+'; (b)no solution.',list('ab'),ck='외적은 첫 입력과 수직이어야 한다.',ce='A cross product must be perpendicular to its first input.')
P=s.Matrix([1,1,1]);Q=s.Matrix([0,6,8]);R=s.Matrix([-1,4,7]);aa=R-Q;bb=P-Q;D=aa.cross(bb).norm()/aa.norm()
add(45,'(a)P에서 Q,R을 지나는 직선까지의 거리 공식을 외적으로 증명하라. (b)P=(1,1,1),Q=(0,6,8),R=(−1,4,7)에 적용하라.','(a)Prove the cross-product distance formula from P to the line through Q,R. (b)Apply it to P=(1,1,1),Q=(0,6,8),R=(−1,4,7).',[m(r'a=QR\ne0,\quad b=QP,\quad |a\times b|=|a|d'),m(r'a='+v(aa)+r',\ b='+v(bb)+r',\ a\times b='+v(aa.cross(bb)))],[m(r'a=QR\ne0,\quad b=QP,\quad |a\times b|=|a|d'),m(r'a='+v(aa)+r',\ b='+v(bb)+r',\ a\times b='+v(aa.cross(bb)))],m(r'd=\frac{|a\times b|}{|a|};\quad d_{\rm example}='+s.latex(D)),parts=list('ab'),ck='평행사변형 넓이=밑변×높이이며 이 높이가 직선까지의 거리이다.',ce='Parallelogram area equals base times height, with height the line distance.')
add(46,'(a)평면QRS까지 P의 거리가 |a·(b×c)|/|a×b|임을 증명하라(a=QR,b=QS,c=QP). (b)P=(2,1,4),Q=(1,0,0),R=(0,2,0),S=(0,0,3)에 적용하라.','(a)Prove the distance to plane QRS is |a·(b×c)|/|a×b|, where a=QR,b=QS,c=QP. (b)Use P=(2,1,4),Q=(1,0,0),R=(0,2,0),S=(0,0,3).',[m(r'n=a\times b\ne0,\quad d=\frac{|n\cdot c|}{|n|}'),'순환 삼중곱으로 분자를 문제의 순서로 쓸 수 있다.',m(r'n=\langle6,3,2\rangle,\quad c=\langle1,1,4\rangle,\quad |n|=7,\quad n\cdot c=17')],[m(r'n=a\times b\ne0,\quad d=\frac{|n\cdot c|}{|n|}'),'Cyclic invariance rewrites the numerator in the stated order.',m(r'n=\langle6,3,2\rangle,\quad c=\langle1,1,4\rangle,\quad |n|=7,\quad n\cdot c=17')],m(r'd=\frac{|a\cdot(b\times c)|}{|a\times b|};\quad d_{\rm example}=17/7'),parts=list('ab'),ck='Q,R,S가 한 직선에 있지 않아야 분모가0이 아니다.',ce='Q,R,S must be noncollinear so the denominator is nonzero.')
eq('47 Lagrange identity',a.cross(c).dot(a.cross(c)),a.dot(a)*c.dot(c)-a.dot(c)**2)
add(47,'라그랑주 항등식을 증명하라.','Prove Lagrange’s identity.',[m(r'|a\times b|^2=|a|^2|b|^2\sin^2\theta'),m(r'(a\cdot b)^2=|a|^2|b|^2\cos^2\theta'),'두 식을 더하고 sin²θ+cos²θ=1을 쓴다. 영벡터인 경우도 양변0이다.'],[m(r'|a\times b|^2=|a|^2|b|^2\sin^2\theta'),m(r'(a\cdot b)^2=|a|^2|b|^2\cos^2\theta'),'Add and use sin²θ+cos²θ=1. Zero-vector cases give zero on both sides.'],m(r'|a\times b|^2=|a|^2|b|^2-(a\cdot b)^2'),ck='독립적으로 임의 성분의 기호 전개도0 잔차를 준다.',ce='An independent arbitrary-component expansion also gives zero residual.')
add(48,'a+b+c=0이면 세 순환 외적이 같음을 보여라.','Show the cyclic cross products agree when a+b+c=0.',[m(r'b\times c=b\times(-a-b)=-b\times a=a\times b'),m(r'c\times a=(-a-b)\times a=-b\times a=a\times b')],[m(r'b\times c=b\times(-a-b)=-b\times a=a\times b'),m(r'c\times a=(-a-b)\times a=-b\times a=a\times b')],m(r'a\times b=b\times c=c\times a'))
add(49,m(r'(a-b)\times(a+b)=2(a\times b)')+'를 증명하라.','Prove '+m(r'(a-b)\times(a+b)=2(a\times b)')+'.',[m(r'(a-b)\times(a+b)=a\times a+a\times b-b\times a-b\times b')],[m(r'(a-b)\times(a+b)=a\times a+a\times b-b\times a-b\times b')],m(r'(a-b)\times(a+b)=2(a\times b)'),ck='자기 외적은0이고 반대 순서 외적은 부호가 바뀐다.',ce='Self-products vanish and reversing order changes the sign.')
eq('50 vector triple product',a.cross(c.cross(dd)),a.dot(dd)*c-a.dot(c)*dd)
add(50,'벡터 삼중곱 공식을 증명하라.','Prove the vector triple-product formula.',[m(r'[a\times(b\times c)]_1=a_2(b_1c_2-b_2c_1)-a_3(b_3c_1-b_1c_3)'),m(r'=b_1(a_2c_2+a_3c_3)-c_1(a_2b_2+a_3b_3)'),'서로 상쇄되는 a₁b₁c₁항을 더하고 빼면 우변의 첫 성분이다. 나머지 성분은 첨자를 순환한다.'],[m(r'[a\times(b\times c)]_1=a_2(b_1c_2-b_2c_1)-a_3(b_3c_1-b_1c_3)'),m(r'=b_1(a_2c_2+a_3c_3)-c_1(a_2b_2+a_3b_3)'),'Insert cancelling a₁b₁c₁ terms to obtain the first right-hand component; cycle indices for the others.'],m(r'a\times(b\times c)=(a\cdot c)b-(a\cdot b)c'),ck='세 성분을 임의 변수로 독립 전개해 일치함을 확인했다.',ce='All three components were independently checked with symbolic variables.')
add(51,'벡터 삼중곱 공식으로 야코비 항등식을 증명하라.','Use the triple-product formula to prove the Jacobi identity.',[m(r'a\times(b\times c)=(a\cdot c)b-(a\cdot b)c'),m(r'b\times(c\times a)=(a\cdot b)c-(b\cdot c)a'),m(r'c\times(a\times b)=(b\cdot c)a-(a\cdot c)b')],[m(r'a\times(b\times c)=(a\cdot c)b-(a\cdot b)c'),m(r'b\times(c\times a)=(a\cdot b)c-(b\cdot c)a'),m(r'c\times(a\times b)=(b\cdot c)a-(a\cdot c)b')],m(r'a\times(b\times c)+b\times(c\times a)+c\times(a\times b)=0'),ck='각 항이 반대 부호의 항과 정확히 상쇄된다.',ce='Every term cancels with an opposite-signed term.')
eq('52 scalar quadruple product',a.cross(c).dot(dd.cross(ee)),a.dot(dd)*c.dot(ee)-a.dot(ee)*c.dot(dd))
add(52,'두 외적의 내적을2×2행렬식으로 나타내는 항등식을 증명하라.','Prove the2×2 determinant identity for the dot product of two cross products.',[m(r'(a\times b)\cdot(c\times d)=a\cdot[b\times(c\times d)]'),m(r'=a\cdot[(b\cdot d)c-(b\cdot c)d]')],[m(r'(a\times b)\cdot(c\times d)=a\cdot[b\times(c\times d)]'),m(r'=a\cdot[(b\cdot d)c-(b\cdot c)d]')],m(r'(a\times b)\cdot(c\times d)=\begin{vmatrix}a\cdot c&a\cdot d\\b\cdot c&b\cdot d\end{vmatrix}'),ck='행렬식을 전개하면 두 곱의 차가 된다.',ce='Expanding the determinant yields the difference of the two products.')
add(53,'a≠0일 때(a)a·b=a·c,(b)a×b=a×c,(c)두 조건 모두가 각각 b=c를 함의하는가?','For a≠0, does each condition imply b=c: (a)a·b=a·c,(b)a×b=a×c,(c)both conditions?', ['(a)아니다. a=i,b=j,c=0은 내적이 모두0이다. (b)아니다. a=i,b=i,c=0은 외적이 모두0이다.',m(r'(c)\quad d=b-c,\quad a\cdot d=0,\quad a\times d=0'),'두 번째 조건은 d가a와평행, 첫 조건은 수직이라는 뜻이므로d=0이다.'],['(a)No: a=i,b=j,c=0 have equal zero dot products. (b)No: a=i,b=i,c=0 have equal zero cross products.',m(r'(c)\quad d=b-c,\quad a\cdot d=0,\quad a\times d=0'),'The second condition makes d parallel to a and the first makes it perpendicular, so d=0.'],'(a)아니오 (b)아니오 (c)예.','(a)No (b)No (c)Yes.',list('abc'),ck='a≠0이라는 가정이(c)의 유일성을 보장한다.',ce='The assumption a≠0 ensures uniqueness in(c).')
add(54,'비공면 v₁,v₂,v₃에 대해 D=v₁·(v₂×v₃), k₁=(v₂×v₃)/D,k₂=(v₃×v₁)/D,k₃=(v₁×v₂)/D라 하자. (a)서로 다른 첨자의 kᵢ,vⱼ는 수직,(b)kᵢ·vᵢ=1,(c)k₁·(k₂×k₃)=1/D임을 보여라.','For noncoplanar v₁,v₂,v₃ set D=v₁·(v₂×v₃), k₁=(v₂×v₃)/D,k₂=(v₃×v₁)/D,k₃=(v₁×v₂)/D. Prove(a)kᵢ⊥vⱼ for i≠j,(b)kᵢ·vᵢ=1,(c)k₁·(k₂×k₃)=1/D.', ['비공면이므로D≠0이다. (a)분자의 외적은 두 입력 각각에 수직이다.','(b)순환 스칼라 삼중곱은 모두D이므로 D로나누면1이다.',m(r'V=[v_1\ v_2\ v_3],\quad K=[k_1\ k_2\ k_3],\quad K^TV=I'),m(r'\det K\det V=1,\quad\det V=D,\quad\det K=k_1\cdot(k_2\times k_3)')],['Noncoplanarity givesD≠0. (a)Each numerator is orthogonal to its two inputs.','(b)Each cyclic scalar triple product equalsD; division gives1.',m(r'V=[v_1\ v_2\ v_3],\quad K=[k_1\ k_2\ k_3],\quad K^TV=I'),m(r'\det K\det V=1,\quad\det V=D,\quad\det K=k_1\cdot(k_2\times k_3)')],m(r'k_i\cdot v_j=\delta_{ij},\quad k_1\cdot(k_2\times k_3)=1/D'),parts=list('abc'),ck='(a),(b)가 보여 주는 쌍대기저 관계의 행렬식을 취해(c)를 얻었다.',ce='Taking determinants of the dual-basis relation from(a),(b)establishes(c).')
assert list(b.E)==list(range(1,55));b.save()
(Path(__file__).parent/'s12-4-report.json').write_text(json.dumps({'section':'12.4','sourceVisualPdfPages':[936,937,938],'passed':len(checks),'independentSymbolicChecks':checks},indent=2)+'\n')
print('54 exercises;',len(checks),'symbolic checks')
