"""Complete rectangular double-integral exercises; source visually checked."""
from core_15 import *
from plot_15 import solid,attach,ASSETS
import math,mpmath as mp,html
x,y,u,v,t,p=s.symbols('x y u v t phi',real=True)
D=Doc('15.1',[1087,1088,1089],lambda n:1087 if n<=14 else(1088 if n<=40 else 1089))
def add(n,st,steps,ans,parts=(),check=('표본점·적분구간을 원본과 대조하고 적분 계산을 검산했다.','Sample points and bounds were compared with the source and the calculations were checked.')):
 return D.add(n,('직사각형 위 이중적분','Double integrals over rectangles'),st,('영역과 표본점을 먼저 정하고, 안쪽 적분에서는 다른 변수를 상수로 둔다.','Identify the region and sample points; treat the other variable as constant in each inner integral.'),steps,ans,check,parts)
def calc(n,f,lims,st=None,setup=None,parts=()):
 vv,ss=D.evaluated(f,lims);ss.insert(0,setup or('Fubini 정리로 반복적분을 계산한다. '+d('I='+integral(f,lims)),'Use Fubini to evaluate the iterated integral. '+d('I='+integral(f,lims))))
 add(n,st or('다음 이중적분을 계산하라. '+d(integral(f,lims)),'Evaluate '+d(integral(f,lims))),ss,d('I='+tex(vv)),parts);return vv
for n,f,rect,mn,kinds in [(1,x*y,(0,6,0,4),(3,2),('ur','mid')),(2,1-x*y*y,(0,4,-1,2),(2,3),('lr','ul')),(3,x*s.exp(-x*y),(0,2,0,1),(2,2),('ur','mid')),(4,1+x*x+3*y,(1,2,0,3),(2,2),('ll','mid'))]:
 aa,bb,cc,dd=map(s.Rational,rect);mm,nn=mn;dx=(bb-aa)/mm;dy=(dd-cc)/nn;ss=[('각 작은 직사각형의 넓이를 구한다. '+d(r'\Delta x='+tex(dx)+r',\ \Delta y='+tex(dy)+r',\ \Delta A='+tex(dx*dy)),'Compute each cell area. '+d(r'\Delta x='+tex(dx)+r',\ \Delta y='+tex(dy)+r',\ \Delta A='+tex(dx*dy)))];res=[];names={'ur':('오른쪽 위','upper-right'),'lr':('오른쪽 아래','lower-right'),'ul':('왼쪽 위','upper-left'),'ll':('왼쪽 아래','lower-left'),'mid':('중점','midpoint')}
 for label,kind in zip('ab',kinds):
  ox,oy={'ur':(1,1),'lr':(1,0),'ul':(0,1),'ll':(0,0),'mid':(s.Rational(1,2),s.Rational(1,2))}[kind];xs=[aa+(i+ox)*dx for i in range(mm)];ys=[cc+(j+oy)*dy for j in range(nn)];terms=[s.simplify(f.subs({x:xx,y:yy})) for xx in xs for yy in ys];vv=s.simplify(dx*dy*sum(terms));res.append(vv)
  ss.append(('('+label+') '+names[kind][0]+' 표본은 x='+m(tex(s.Tuple(*xs)))+', y='+m(tex(s.Tuple(*ys)))+'의 모든 조합이다. '+d(label+'='+tex(dx*dy)+r'\left['+'+'.join('('+tex(q)+')' for q in terms)+r'\right]='+tex(vv)),'('+label+') '+names[kind][1]+' samples use all combinations of x='+m(tex(s.Tuple(*xs)))+' and y='+m(tex(s.Tuple(*ys)))+'. '+d(label+'='+tex(dx*dy)+r'\left['+'+'.join('('+tex(q)+')' for q in terms)+r'\right]='+tex(vv))))
 add(n,(''+m('f='+tex(f))+', '+m('R=['+tex(aa)+','+tex(bb)+']\\times['+tex(cc)+','+tex(dd)+']')+'를 '+str(mm)+'×'+str(nn)+'로 분할한다. (a)'+names[kinds[0]][0]+' 표본, (b)'+names[kinds[1]][0]+' 표본으로 '+('부피' if n in(1,4) else '적분')+'를 근사하라.','For '+m('f='+tex(f))+' on '+m('R=['+tex(aa)+','+tex(bb)+']\\times['+tex(cc)+','+tex(dd)+']')+', use a '+str(mm)+'×'+str(nn)+' grid to approximate the '+('volume' if n in(1,4) else 'integral')+' using (a) '+names[kinds[0]][1]+' and (b) '+names[kinds[1]][1]+' samples.'),ss,d('(a)\ '+tex(res[0])+',\quad(b)\ '+tex(res[1])),('a','b'))
add(5,(''+m(r'f=\sqrt{52-x^2-y^2}')+' 아래의 '+m('[2,4]\\times[2,6]')+' 위 부피를 V라 하자. x=3,y=4로4분할하고 왼쪽 아래 표본합 L, 오른쪽 위 표본합 U를 쓴다. 계산 없이 V,L,U를 작은 순서로 나열하라.','Let V be the volume under '+m(r'\sqrt{52-x^2-y^2}')+' over '+m('[2,4]\\times[2,6]')+'. Split at x=3,y=4 and let L and U use lower-left and upper-right samples. Order V,L,U without evaluating them.'),[('이 양의 사분면에서 x나 y가 커지면 제곱근 안이 작아져 함수가 감소한다.','On this positive rectangle the function decreases when either coordinate increases.'),('각 칸의 최대는 왼쪽 아래, 최소는 오른쪽 위다. 따라서 L은 상계, U는 하계이며 내부에서 엄격한 부등식이 성립한다.','Each cell has its maximum at the lower-left and minimum at the upper-right. Thus L overestimates and U underestimates; the inequalities are strict on interior points.')],d('U<V<L'))
table=[[2,3,4,6,7,8,8],[2,3,4,7,8,10,8],[2,4,6,8,10,12,10],[2,3,4,5,6,8,7],[2,2,2,2,3,4,4]]
arr=r'\begin{array}{c|rrrrrrr}y\backslash x&0&5&10&15&20&25&30\\'+'\\'.join(str(j*5)+'&'+'&'.join(map(str,row)) for j,row in enumerate(table))+r'\end{array}'
add(6,('20×30피트 수영장의5피트 간격 깊이 측정값(피트)은 다음과 같다. 물 부피를 근사하라. '+d(arr),'Depths in feet, measured on a5-foot grid in a20×30-foot pool, are shown below. Estimate its water volume. '+d(arr)),[('10×10피트인6개 직사각형을 사용하면 중심값이 모두 표에 있다. 중심은 '+m('x=5,15,25;\ y=5,15')+'이다.','Use six10×10-foot cells whose centers all appear in the table: '+m('x=5,15,25;\ y=5,15')+'.'),('각 중심 깊이에100제곱피트를 곱해 합친다. '+d(r'V\approx100(3+7+10+3+5+8)=3600'),'Multiply each center depth by100square feet and sum: '+d(r'V\approx100(3+7+10+3+5+8)=3600'))],d(r'V\approx3600\ \mathrm{ft^3}'))
add(7,('교재 등고선의 '+m('[0,4]^2')+' 영역을2×2로 분할한다. 중점 '+m('(1,1),(3,1),(1,3),(3,3)')+'에서 읽은 값은 각각 약27,15,5,15이다. (a)적분과 (b)영역평균을 추정하라.','Use a2×2 midpoint grid on '+m('[0,4]^2')+' for the textbook contour map. At '+m('(1,1),(3,1),(1,3),(3,3)')+', graphical readings are approximately27,15,5,15. Estimate (a) the integral and (b) the area average.'),[('(a) 각 칸 넓이는4이다. '+d(r'\iint_Rf\,dA\approx4(27+15+5+15)=248'),'(a) Each cell has area4: '+d(r'\iint_Rf\,dA\approx4(27+15+5+15)=248')),('(b) 넓이16으로 나누면 '+m('248/16=15.5')+'이다. 등고선 판독은 근사라 마지막 자리는 달라질 수 있다.','(b) Divide by area16 to obtain '+m('248/16=15.5')+'. Graphical readings are approximate, so final digits can vary.')],d(r'(a)\approx248,\quad(b)\approx15.5'),('a','b'),('4개 중점은 독립 시각 판독과 대조했다. 각 판독오차가 ε 이하라면 적분오차는16ε, 평균오차는 ε 이하이다(중점법 자체 오차 제외).','Four midpoint readings were cross-checked visually. If each reading error is at most ε, the resulting reading error is at most16ε in the integral and ε in the average, apart from midpoint-rule error.'))
vals=[[30,22,42,42],[34,18,42,46],[42,26,58,46],[30,30,50,42]];total=sum(map(sum,vals));avg=total/16
arr=r'\begin{pmatrix}'+'\\'.join('&'.join(map(str,row)) for row in vals)+r'\end{pmatrix}'
add(8,('동서388마일·남북276마일인 콜로라도의 교재 기온 등고선(화씨,2월 오후4시)에4×4 중점법을 적용해 평균기온을 구하라. 북쪽부터 남쪽 행, 서쪽부터 동쪽 열로 읽은 근삿값은 '+d(arr)+'이다.','Apply a4×4 midpoint rule to the textbook Colorado temperature map (°F,4PM in February), using dimensions388miles east-west and276miles north-south. Approximate readings, rows north-to-south and columns west-to-east, are '+d(arr)+'.'),[('각 칸은97×69마일이므로 넓이는6693제곱마일이다.','Each cell measures97×69miles, with area6693square miles.'),('같은 넓이의16개 칸이므로 넓이인자는 평균에서 소거된다. '+d(r'T_{\mathrm{avg}}\approx\frac{6693\sum_{i,j}T_{ij}}{16\cdot6693}=\frac{'+str(total)+r'}{16}='+str(avg)),'All16cells have equal area, so the area factor cancels: '+d(r'T_{\mathrm{avg}}\approx\frac{6693\sum_{i,j}T_{ij}}{16\cdot6693}=\frac{'+str(total)+r'}{16}='+str(avg))),('기온선 간격과 선형 보간 때문에 이는 대략적인 지도 판독 추정값이다.','Contour spacing and graphical interpolation make this an approximate map-based estimate.')],d(r'T_{\mathrm{avg}}\approx'+str(avg)+r'{}^\circ F'),check=('표시한16개 표본과 산술평균을 보존한다. 각 값의 판독오차가2°F라면 평균의 판독오차 상한도2°F이다. 중점법 공간오차는 별도이다.','All16readings and their arithmetic mean are recorded. If each graphical reading has error at most2°F, its contribution to mean error is at most2°F; spatial midpoint error is separate.'))
for n,f,ll,why in [(9,s.sqrt(2),[(y,-1,5),(x,2,6)],('밑면4×6, 높이 '+m(r'\sqrt2')+'인 직육면체이다.','It is a rectangular box of base4×6 and height '+m(r'\sqrt2')+'.')),(10,2*x+1,[(y,0,4),(x,0,2)],('xz단면은 평행변1과5, 사이거리2인 사다리꼴이며 y방향 길이는4이다.','The xz section is a trapezoid with parallel sides1and5 separated by2; its y-length is4.')),(11,4-2*y,[(y,0,1),(x,0,1)],('yz단면의 평행변은4와2, 사이거리는1이고 x방향 길이는1이다.','The yz trapezoid has sides4and2 separated by1; its x-length is1.'))]:calc(n,f,ll,('적분을 입체 부피로 해석하여 계산하라. '+d(integral(f,ll)),'Interpret as volume and evaluate '+d(integral(f,ll))),why)
add(12,(''+m(r'\iint_R\sqrt{9-y^2}\,dA,\ R=[0,4]\times[0,2]')+'가 나타내는 입체를 그려라.','Sketch the solid represented by '+m(r'\iint_R\sqrt{9-y^2}\,dA,\ R=[0,4]\times[0,2]')+'.'),[('높이는 '+m(r'z=\sqrt{9-y^2}')+'이므로 지붕은 x축에 평행한 반지름3원기둥 '+m('y^2+z^2=9')+'의 위쪽이다.','The roof '+m(r'z=\sqrt{9-y^2}')+' is the upper radius3cylinder '+m('y^2+z^2=9')+' parallel to the x-axis.'),('밑면 직사각형에 수직으로 높이를 세우면 '+m(r'0\le x\le4,\ 0\le y\le2,\ 0\le z\le\sqrt{9-y^2}')+'가 된다.','The solid is '+m(r'0\le x\le4,\ 0\le y\le2,\ 0\le z\le\sqrt{9-y^2}')+'.')],('위 원기둥 아래의 길이4인 입체 조각(자체 도해 참조).','A length4cylindrical segment below the upper cylinder; see the original diagram.'))
for n,f in [(13,x+3*x*x*y*y),(14,y*s.sqrt(x+2))]:
 vx,sx=D.evaluated(f,[(x,0,2)]);vy,sy=D.evaluated(f,[(y,0,3)])
 add(n,(''+m('f='+tex(f))+'에 대해 '+m(r'\int_0^2f(x,y)dx')+'와 '+m(r'\int_0^3f(x,y)dy')+'를 각각 구하라.','For '+m('f='+tex(f))+', find '+m(r'\int_0^2f(x,y)dx')+' and '+m(r'\int_0^3f(x,y)dy')+' separately.'),[('첫 번째는 y, 두 번째는 x를 상수로 둔다.','Treat y as constant in the first integral and x as constant in the second.')]+sx+sy,d(r'\int_0^2f\,dx='+tex(vx)+r',\quad\int_0^3f\,dy='+tex(vy)))
spec={15:(6*x*x*y-2*x,[(y,0,2),(x,1,4)]),16:((x+y)**2,[(x,0,1),(y,0,1)]),17:(x+s.exp(-y),[(x,1,2),(y,0,1)]),18:(x*x+y**-2,[(y,1,2),(x,-3,1)]),19:(y+y*y*s.cos(x),[(x,0,s.pi/2),(y,-3,3)]),20:(s.log(y)/(x*y),[(y,1,5),(x,1,3)]),21:(x/y+y/x,[(y,1,2),(x,1,4)]),22:(y*s.exp(x-y),[(x,0,2),(y,0,1)]),23:(t*t*s.sin(p)**3,[(p,0,s.pi/2),(t,0,3)]),24:(x*y*s.sqrt(x*x+y*y),[(y,0,1),(x,0,1)]),25:(v*(u+v*v)**4,[(u,0,1),(v,0,1)]),26:(s.sqrt(u+t),[(u,0,1),(t,0,1)]),27:(x/s.cos(y)**2,[(y,0,s.pi/4),(x,0,2)]),28:(y+x/y**2,[(y,1,2),(x,0,2)]),29:(x*y*y/(x*x+1),[(y,-3,3),(x,0,1)]),30:(s.tan(t)/s.sqrt(1-u*u),[(u,0,s.Rational(1,2)),(t,0,s.pi/3)]),31:(x*s.sin(x+y),[(y,0,s.pi/3),(x,0,s.pi/6)]),32:(x/(1+x*y),[(x,0,1),(y,0,1)]),33:(y*s.exp(-x*y),[(x,0,2),(y,0,3)]),34:(1/(1+x+y),[(y,1,2),(x,1,3)])}
# Exercise32: choose y inner to keep an elementary logarithmic integral.
spec[32]=(x/(1+x*y),[(y,0,1),(x,0,1)])
for n,(f,ll) in spec.items():calc(n,f,ll)
for n,f,ll in [(35,4-x-2*y,[(x,0,1),(y,0,1)]),(36,2-x*x-y*y,[(y,0,1),(x,0,1)]),(37,4-x*x,[(y,-1,3),(x,-2,2)])]:
 st=('다음 적분의 부피에 해당하는 입체를 그려라. '+d(integral(f,ll)),'Sketch the solid whose volume is '+d(integral(f,ll)))
 calc(n,f,ll,st,('영역의 각 점에서 z=0부터 '+m('z='+tex(f))+'까지 선분을 올린다.','At each base point, draw the vertical segment from z=0 to '+m('z='+tex(f))+'.'))
add(38,(''+m(r'z=x^2\sqrt y,\ 0\le x\le2,\ 1\le y\le4')+' 아래의 입체 S에 대해 (a)x축에 수직인 단면적을 구하고 x=1,2단면을 그려라. (b)y축에 수직인 단면적과 y=1,3단면을 그려라. (c)부피를 구하라.','For the solid under '+m(r'z=x^2\sqrt y,\ 0\le x\le2,\ 1\le y\le4')+', (a) find x-normal cross-sectional area and draw sections x=1,2; (b) find y-normal area and draw sections y=1,3; (c) find volume.'),[('(a) x=c를 고정하면 '+d(r'A_x(c)=\int_1^4c^2\sqrt y\,dy=\frac{14c^2}{3},\quad A_x(1)=14/3,\ A_x(2)=56/3')+'이다.','(a) At x=c, '+d(r'A_x(c)=\int_1^4c^2\sqrt y\,dy=\frac{14c^2}{3},\quad A_x(1)=14/3,\ A_x(2)=56/3')),('(b) y=c를 고정하면 '+d(r'A_y(c)=\int_0^2x^2\sqrt c\,dx=\frac{8\sqrt c}{3},\quad A_y(1)=8/3,\ A_y(3)=8\sqrt3/3')+'이다.','(b) At y=c, '+d(r'A_y(c)=\int_0^2x^2\sqrt c\,dx=\frac{8\sqrt c}{3},\quad A_y(1)=8/3,\ A_y(3)=8\sqrt3/3')),('(c) 어느 단면방향으로 적분해도 같다. '+d(r'V=\int_0^2\frac{14x^2}{3}dx=\int_1^4\frac{8\sqrt y}{3}dy=\frac{112}{9}'),'(c) Both slicing directions agree: '+d(r'V=\int_0^2\frac{14x^2}{3}dx=\int_1^4\frac{8\sqrt y}{3}dy=\frac{112}{9}'))],d(r'(a)\ A_x(c)=14c^2/3;\quad(b)\ A_y(c)=8\sqrt c/3;\quad(c)\ V=112/9'),('a','b','c'))
vols={39:(x*y,[(y,0,2),(x,0,2)]),40:(s.cos(x)*s.cos(y),[(y,-s.pi/4,s.pi/4),(x,-s.pi/4,s.pi/4)]),41:(1+y*s.exp(x*y),[(x,0,1),(y,1,2)]),42:(x*x+y*y,[(y,1,3),(x,1,2)]),43:((4*x+6*y+15)/2,[(y,-1,1),(x,-1,2)]),44:(3*y*y-x*x+2,[(y,1,2),(x,-1,1)]),45:(1-x*x/4-y*y/9,[(y,-2,2),(x,-1,1)]),46:(x*x+x*y*y,[(y,-2,2),(x,0,5)]),47:(1+x*x*y*s.exp(y),[(y,0,1),(x,-1,1)]),48:(16-x*x,[(y,0,5),(x,0,4)]),49:(1+x*x+(y-2)**2,[(y,0,4),(x,-1,1)]),50:(x+2*y-2*x*y/(x*x+1),[(y,0,4),(x,0,2)]),51:(x**5*y**3*s.exp(x*y),[(x,0,1),(y,0,1)])}
for n,(f,ll) in vols.items():
 desc=',\ '.join(tex(lo)+r'\le '+tex(vv)+r'\le '+tex(hi) for vv,lo,hi in ll)
 if n==49:st=('곡면 '+m(r'z=2+x^2+(y-2)^2')+'와 z=1 사이, '+m(desc)+'의 부피를 구하라.','Find the volume between '+m(r'z=2+x^2+(y-2)^2')+' and z=1 over '+m(desc)+'.')
 elif n==50:st=(''+m(r'z=2xy/(x^2+1),\ z=x+2y')+' 사이에서 '+m(desc)+'인 입체를 그리고 부피를 구하라.','Graph and find the volume between '+m(r'z=2xy/(x^2+1)')+' and '+m(r'z=x+2y')+' over '+m(desc)+'.')
 else:st=(''+m('z='+tex(f))+' 아래, '+m(desc)+' 위의 부피를 '+('(a)적분으로 세우고 (b)계산하라.' if n in(39,40,41,42) else('CAS로 정확히 구하고 입체를 그려라.' if n==51 else '구하라.')),'Find the volume beneath '+m('z='+tex(f))+' over '+m(desc)+('. (a) Set up; (b) evaluate.' if n in(39,40,41,42) else(' Use a CAS for the exact value and graph the solid.' if n==51 else '.')))
 calc(n,f,ll,st,('높이는 위 곡면에서 아래 곡면을 뺀 것이다. '+d('V='+integral(f,ll)),'Height is upper surface minus lower surface. '+d('V='+integral(f,ll))),('a','b') if n in(39,40,41,42) else ())
mp.mp.dps=30;fn=lambda xx,yy:2-xx*xx-yy*yy-mp.exp(-xx*xx)*mp.cos(xx*xx+yy*yy);v52=mp.quad(lambda xx:mp.quad(lambda yy:fn(xx,yy),[0,1]),[0,1])*4
add(52,(''+m(r'z=e^{-x^2}\cos(x^2+y^2),\ z=2-x^2-y^2')+' 사이, '+m('[-1,1]^2')+' 위 입체를 그리고 부피를 소수 넷째 자리까지 구하라.','Graph the solid between '+m(r'z=e^{-x^2}\cos(x^2+y^2)')+' and '+m(r'z=2-x^2-y^2')+' over '+m('[-1,1]^2')+' and find volume to four decimals.'),[(''+m(r'q=x^2+y^2\in[0,2]')+'라 하자. q≤1이면 위 곡면은1이상, 아래 곡면은1이하이다. 1≤q≤π/2이면 '+m(r'\cos q=\sin(\pi/2-q)\le\pi/2-q\le2-q')+'이므로 '+m(r'\cos q\le2-q')+'이고, π/2≤q≤2이면 cosq≤0≤2-q이다. 따라서 포물면이 위다.','Put '+m(r'q=x^2+y^2\in[0,2]')+'. For q≤1 the paraboloid is at least1and the other surface at most1. For1≤q≤π/2, use '+m(r'\cos q=\sin(\pi/2-q)\le\pi/2-q\le2-q')+' to obtain '+m(r'\cos q\le2-q')+'; for π/2≤q≤2, cosq≤0≤2-q. Thus the paraboloid is upper.'),('두 좌표에 짝대칭인 높이를 수치적분한다. '+d(r'V=4\int_0^1\int_0^1[2-x^2-y^2-e^{-x^2}\cos(x^2+y^2)]\,dy\,dx\approx'+str(v52)),'Numerically integrate the height, even in both coordinates: '+d(r'V=4\int_0^1\int_0^1[2-x^2-y^2-e^{-x^2}\cos(x^2+y^2)]\,dy\,dx\approx'+str(v52)))],d('V\\approx'+f'{float(v52):.4f}'))
for n,f,ll,area_ in [(53,x*x*y,[(y,0,5),(x,-1,1)],10),(54,s.exp(y)*s.sqrt(x+s.exp(y)),[(y,0,1),(x,0,4)],4)]:
 vv,ss=D.evaluated(f,ll);ss.insert(0,('平均は積分を領域面積で割る。','Divide the integral by the region area.'));ss.append(('영역넓이 '+str(area_)+'로 나눈다.','Divide by area '+str(area_)+'.'));add(n,('직사각형 '+m(',\ '.join(tex(lo)+r'\le '+tex(vv)+r'\le '+tex(hi) for vv,lo,hi in ll))+'에서 '+m(tex(f))+'의 평균을 구하라.','Find the average of '+m(tex(f))+' over '+m(',\ '.join(tex(lo)+r'\le '+tex(vv)+r'\le '+tex(hi) for vv,lo,hi in ll))+'.'),ss,d(r'f_{\rm avg}='+tex(s.simplify(vv/area_))))
for n,st,steps,ans in [(55,(m(r'xy/(1+x^4)')+'를 '+m('[-1,1]\\times[0,1]')+'에서 대칭으로 적분하라.','Use symmetry to integrate '+m(r'xy/(1+x^4)')+' on '+m('[-1,1]\\times[0,1]')+'.'),[('분모는 x에 짝함수, 분자는 x에 홀함수이며 영역은 x반사 대칭이다. 따라서 양쪽이 상쇄된다.','The denominator is even and numerator odd in x, while the region is x-symmetric, so contributions cancel.')],d('I=0')),(56,(m(r'1+x^2\sin y+y^2\sin x')+'를 '+m('[-\\pi,\\pi]^2')+'에서 대칭으로 적분하라.','Use symmetry to integrate '+m(r'1+x^2\sin y+y^2\sin x')+' on '+m('[-\\pi,\\pi]^2')+'.'),[('첫 사인항은 y에 홀함수, 두 번째는 x에 홀함수여서 각각0이다. 상수1의 적분은 정사각형넓이이다.','The first sine term is odd in y and the second odd in x; each integrates to zero. The constant term contributes the square area.')],d(r'I=4\pi^2'))]:add(n,st,steps,ans)
add(57,(''+m(r'f(x,y)=(x-y)/(x+y)^3')+'에 대해 단위 정사각형의 dy dx와 dx dy 반복적분을 각각 계산하고 값이 다른 이유를 설명하라.','For '+m(r'f(x,y)=(x-y)/(x+y)^3')+', calculate both dy dx and dx dy iterated integrals over the unit square and explain why they differ.'),[('x>0에서 y원시함수는 '+m(r'y/(x+y)^2')+'이므로 '+d(r'\int_0^1\int_0^1f\,dy\,dx=\int_0^1\frac{dx}{(1+x)^2}=\frac12')+'이다.','For x>0, a y-antiderivative is '+m(r'y/(x+y)^2')+', hence '+d(r'\int_0^1\int_0^1f\,dy\,dx=\int_0^1\frac{dx}{(1+x)^2}=\frac12')),('y>0에서 x원시함수는 '+m(r'-x/(x+y)^2')+'이므로 '+d(r'\int_0^1\int_0^1f\,dx\,dy=-\int_0^1\frac{dy}{(1+y)^2}=-\frac12')+'이다.','For y>0, an x-antiderivative is '+m(r'-x/(x+y)^2')+', hence '+d(r'\int_0^1\int_0^1f\,dx\,dy=-\int_0^1\frac{dy}{(1+y)^2}=-\frac12')),('원점에서 함수가 특이하다. 예를 들어 '+m(r'0\le y\le x/2')+'에서는 '+m(r'|f|\ge4/(27x^2)')+'이므로 절댓값 이중적분은 '+m(r'\int_0^1 dx/x')+'처럼 발산한다. 연속성도 절대적분가능성도 없어 Fubini의 가정을 만족하지 않는다.','The origin is singular. On '+m(r'0\le y\le x/2')+', '+m(r'|f|\ge4/(27x^2)')+', so the absolute double integral diverges like '+m(r'\int_0^1dx/x')+'. Neither continuity nor absolute integrability holds; Fubini does not apply.')],d(r'\int dx\int dy\,f=1/2,\qquad\int dy\int dx\,f=-1/2'))
add(58,('(a)Fubini 정리와 Clairaut 정리의 유사성을 설명하라. (b)연속함수 f에 대해 '+m(r'g(x,y)=\int_a^x\int_c^yf(s,t)\,dt\,ds')+'의 두 혼합편미분이 f와 같음을 보여라.','(a) Explain the analogy between Fubini and Clairaut. (b) For continuous f, show both mixed partials of '+m(r'g(x,y)=\int_a^x\int_c^yf(s,t)\,dt\,ds')+' equal f.'),[('(a) 두 정리 모두 적절한 연속성 가정 아래 서로 다른 변수에 대한 두 연산의 순서를 바꿀 수 있음을 말한다.','(a) Both allow the order of two operations in different variables to be exchanged under suitable continuity hypotheses.'),('(b) 미적분학 기본정리로 '+m(r'g_x=\int_c^yf(x,t)dt')+'이며 다시 y로 미분하면 '+m('g_{xy}=f(x,y)')+'이다.','(b) The fundamental theorem gives '+m(r'g_x=\int_c^yf(x,t)dt')+'; differentiating in y yields '+m('g_{xy}=f(x,y)')+'.'),('Fubini로 먼저 '+m(r'g=\int_c^y\int_a^xf(s,t)dsdt')+'로 바꾸면 '+m(r'g_y=\int_a^xf(s,y)ds')+', 따라서 '+m('g_{yx}=f(x,y)')+'이다. f 자체의 미분가능성은 필요 없다.','Fubini rewrites '+m(r'g=\int_c^y\int_a^xf(s,t)dsdt')+'. Thus '+m(r'g_y=\int_a^xf(s,y)ds')+' and '+m('g_{yx}=f(x,y)')+'. Differentiability of f itself is unnecessary.')],d(r'g_{xy}=g_{yx}=f(x,y)'),('a','b'))
# Original solids required by sketch/graph prompts.
specs={12:(lambda u,v,w:(4*u,2*v,w*math.sqrt(9-4*v*v)),'0 ≤ x ≤ 4; 0 ≤ y ≤ 2; 0 ≤ z ≤ √(9 - y²)'),35:(lambda u,v,w:(u,v,w*(4-u-2*v)),'0 ≤ x,y ≤ 1; 0 ≤ z ≤ 4 - x - 2y'),36:(lambda u,v,w:(u,v,w*(2-u*u-v*v)),'0 ≤ x,y ≤ 1; 0 ≤ z ≤ 2 - x² - y²'),37:(lambda u,v,w:(-2+4*u,-1+4*v,w*(4-(-2+4*u)**2)),'-2 ≤ x ≤ 2; -1 ≤ y ≤ 3; 0 ≤ z ≤ 4 - x²'),50:(lambda u,v,w:(2*u,4*v,2*(2*u)*(4*v)/(1+4*u*u)+w*(2*u+8*v-2*(2*u)*(4*v)/(1+4*u*u))),'2xy/(1+x²) ≤ z ≤ x + 2y'),51:(lambda u,v,w:(u,v,w*u**5*v**3*math.exp(u*v)),'z = x⁵ y³ exp(xy); unit-square base'),52:(lambda u,v,w:(-1+2*u,-1+2*v,math.exp(-(-1+2*u)**2)*math.cos((-1+2*u)**2+(-1+2*v)**2)+w*(2-(-1+2*u)**2-(-1+2*v)**2-math.exp(-(-1+2*u)**2)*math.cos((-1+2*u)**2+(-1+2*v)**2))),'exp(-x²) cos(x²+y²) ≤ z ≤ 2 - x² - y²')}
for n,(fn,caption) in specs.items():
 name=f's15-1-{n}.svg';solid(name,f'15.1 / {n} - Solid',fn,subtitle=caption,resolution=14);attach(next(e for e in D.items if e['number']==n),name,('방정식과 경계에서 직접 만든 입체 도해','Original solid diagram generated from its equations and bounds'),(caption,caption))
# Four planar cross sections in one labeled vector artifact.
name='s15-1-38.svg';out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 560"><title>Four cross sections of z = x²√y</title><rect width="800" height="560" fill="#fbfcff"/>']
for i,(label,lo,hi,fun,axis) in enumerate([('x = 1',1,4,lambda q:math.sqrt(q),'y'),('x = 2',1,4,lambda q:4*math.sqrt(q),'y'),('y = 1',0,2,lambda q:q*q,'x'),('y = 3',0,2,lambda q:q*q*math.sqrt(3),'x')]):
 ox=30+(i%2)*400;oy=30+(i//2)*275;mx=max(fun(lo),fun(hi));pts=[(lo,0)]+[(lo+(hi-lo)*j/60,fun(lo+(hi-lo)*j/60)) for j in range(61)]+[(hi,0)];coords=' '.join(f'{ox+35+280*(q-lo)/(hi-lo):.2f},{oy+205-165*z/mx:.2f}' for q,z in pts);out.append(f'<text x="{ox}" y="{oy+10}" font-family="sans-serif" font-size="18">{label}</text><polygon points="{coords}" fill="#a0bfea" stroke="#285481"/><text x="{ox+35}" y="{oy+228}" font-family="sans-serif">{lo} ≤ {axis} ≤ {hi}; 0 ≤ z ≤ {mx:.3g}</text>')
out.append('</svg>');(ASSETS/name).write_text('\n'.join(out));attach(next(e for e in D.items if e['number']==38),name,('x=1,2와 y=1,3에서의 네 단면','Four cross sections at x=1,2and y=1,3'),('각 패널은 표시된 고정좌표에서 지붕 아래 단면이다.','Each panel is the section below the roof at the fixed coordinate shown.'))
for e in D.items:
 e['steps']['ko']=[q.replace('平均は積分を領域面積で割る。','평균은 적분을 영역넓이로 나눈다.') for q in e['steps']['ko']]
D.save(58)

report_path=ROOT/"exercise-checks/s15-1-report.json"
report=json.loads(report_path.read_text());report["uncertainties"]=[{"exercise":7,"kind":"graphical estimate","note":"Four midpoint readings27,15,5,15 were independently visually cross-checked; graph interpolation and midpoint discretization remain approximate."},{"exercise":8,"kind":"graphical estimate","note":"Sixteen temperature readings were independently visually cross-checked; reported37.5F is a midpoint map estimate, not an exact value."}];report_path.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n")
