"""Independent dot-product exercises, source pp.890–892."""
from early_helpers import Book
import sympy as S,math
b=Book('12.3',[890,891,892]);proofs=[]
def m(x):return r'\('+x+r'\)'
def v(a):return r'\langle '+','.join(S.latex(S.sympify(x))for x in a)+r'\rangle'
def add(n,st,se,ks,es,an,ae=None,parts=[],ck='원래 조건과 계산 결과를 대조했다.',ce='The result was checked against the original conditions.'):
 b.add(n,890 if n<=7 else 891 if n<=44 else 892,('내적·각도·정사영','Dot products, angles and projections'),(st,se),list(zip(ks,es)),(an,an if ae is None else ae),parts,check=(ck,ce));b.E[n]['conceptHref']='../../calc1/index.html'
def exact(n,a,c,task='dot'):
 av=S.Matrix(a);bv=S.Matrix(c);dot=av.dot(bv);den=av.norm()*bv.norm()
 if task=='dot':ans=m(r'a\cdot b='+S.latex(dot));ks=[m(r'a\cdot b='+ '+'.join('('+S.latex(x)+')('+S.latex(y)+')'for x,y in zip(av,bv)))];es=ks;ko='내적을 구하라: ';en='Find the dot product: '
 else:
  co=S.simplify(dot/den);ang=math.degrees(math.acos(float(co)));ans=m(r'\theta=\arccos\left('+S.latex(co)+fr'\right)\approx{ang:.0f}^\circ');ks=[m(r'a\cdot b='+S.latex(dot)+r',\quad|a||b|='+S.latex(den)),m(r'\cos\theta=\frac{a\cdot b}{|a||b|}')];es=ks;ko='사이각의 정확한 식과 가장 가까운 정수 도를 구하라: ';en='Find the exact angle and round to the nearest degree: '
 add(n,ko+m('a='+v(a)+r',\ b='+v(c)),en+m('a='+v(a)+r',\ b='+v(c)),ks,es,ans,ck='성분별 곱의 합으로 내적을 독립 계산했다.',ce='The dot product was independently computed as a sum of coordinate products.')
add(1,'(a)(a·b)·c,(b)(a·b)c,(c)|a|(b·c),(d)a·(b+c),(e)a·b+c,(f)|a|·(b+c)의 정의 가능 여부를 설명하라.','Determine which expressions are defined: (a)(a·b)·c,(b)(a·b)c,(c)|a|(b·c),(d)a·(b+c),(e)a·b+c,(f)|a|·(b+c).',['내적은 두 벡터에서 스칼라를 만든다. 스칼라배는 벡터에 스칼라를 곱하는 연산이다.','(a),(f)는 스칼라와 벡터를 내적하려 하고 (e)는 서로 다른 종류를 더한다.'],['A dot product takes two vectors and returns a scalar. Scalar multiplication multiplies a vector by a scalar.','(a),(f) try to dot a scalar with a vector; (e) adds unlike types.'],'정의됨: (b)벡터,(c)스칼라,(d)스칼라. 정의되지 않음: (a),(e),(f).','Defined:(b)vector,(c)scalar,(d)scalar. Undefined:(a),(e),(f).',list('abcdef'),ck='곱셈과 내적 기호를 구분해야 한다.',ce='Distinguish scalar multiplication from the dot product.')
p,q=S.symbols('p q',real=True)
for n,a,c in [(2,(5,-2),(3,4)),(3,(S.Rational(3,2),S.Rational(2,5)),(-4,6)),(4,(6,-2,3),(2,5,-1)),(5,(4,1,S.Rational(1,4)),(6,-3,-8)),(6,(p,-p,2*p),(2*q,q,-q)),(7,(2,1,0),(1,-1,1)),(8,(3,2,-1),(4,0,5))]:exact(n,a,c)
for n,aa,bb,theta in [(9,7,4,S.pi/6),(10,80,50,3*S.pi/4)]:
 val=aa*bb*S.cos(theta);add(n,m(fr'|a|={aa},|b|={bb},\theta='+S.latex(theta))+'일 때 내적을 구하라.','Find the dot product given '+m(fr'|a|={aa},|b|={bb},\theta='+S.latex(theta))+'.',[m(r'a\cdot b=|a||b|\cos\theta')],[m(r'a\cdot b=|a||b|\cos\theta')],m(r'a\cdot b='+S.latex(val)),ck='예각이면 양수, 둔각이면 음수이다.',ce='An acute angle gives a positive product and an obtuse one a negative product.')
add(11,'정삼각형 꼭대기에서 왼쪽·오른쪽 꼭짓점으로 향하는 벡터를 u,v, 왼쪽에서 오른쪽 밑변을 w라 하자. |u|=1일 때 u·v,u·w를 구하라.','In an equilateral triangle, u,v run from the top to the left/right bottom vertices and w runs left to right. Given |u|=1, find u·v,u·w.',[m(r'|u|=|v|=|w|=1,\quad \angle(u,v)=60^\circ,\quad\angle(u,w)=120^\circ')],[m(r'|u|=|v|=|w|=1,\quad \angle(u,v)=60^\circ,\quad\angle(u,w)=120^\circ')],m(r'u\cdot v=1/2,\quad u\cdot w=-1/2'),ck='w=v−u이므로 u·w=u·v−1=−1/2이다.',ce='Since w=v−u, u·w=u·v−1=−1/2.')
add(12,'단위 정사각형의 왼쪽 위에서 오른쪽 위·왼쪽 아래·중심으로 향하는 벡터를 각각 u,w,v라 하자. u·v,u·w를 구하라.','In a unit square, vectors u,w,v go from the upper-left corner to the upper-right, lower-left, and center. Find u·v,u·w.',[m(r'u=\langle1,0\rangle,\ w=\langle0,-1\rangle,\ v=\langle1/2,-1/2\rangle')],[m(r'u=\langle1,0\rangle,\ w=\langle0,-1\rangle,\ v=\langle1/2,-1/2\rangle')],m(r'u\cdot v=1/2,\quad u\cdot w=0'),ck='v=(u+w)/2이고 u,w는 수직이다.',ce='v=(u+w)/2 and u,w are perpendicular.')
add(13,'표준기저i,j,k에 대해 (a)서로 다른 두 기저의 내적은0,(b)자기 자신과의 내적은1임을 보여라.','For standard basis vectors i,j,k, prove(a)distinct basis vectors have dot product0 and(b)each self-product equals1.',[m(r'i=\langle1,0,0\rangle,\ j=\langle0,1,0\rangle,\ k=\langle0,0,1\rangle'),'서로 다른 벡터의 대응 성분 곱은 모두0이다. 같은 벡터는1²인 항 하나를 갖는다.'],[m(r'i=\langle1,0,0\rangle,\ j=\langle0,1,0\rangle,\ k=\langle0,0,1\rangle'),'All coordinate products vanish for distinct basis vectors; a self-product has one term1².'],m(r'i\cdot j=j\cdot k=k\cdot i=0,\quad i\cdot i=j\cdot j=k\cdot k=1'),parts=list('ab'))
add(14,'판매량A=(a,b,c)와 단가P=(4,2.5,1)달러가 햄버거·핫도그·물에 해당한다. A·P의 의미를 설명하라.','Quantities A=(a,b,c) and prices P=(4,2.5,1)dollars correspond to hamburgers, hot dogs, and water. Interpret A·P.',[m(r'A\cdot P=4a+2.5b+c')],[m(r'A\cdot P=4a+2.5b+c')],'그날의 총 매출액(달러).','Total sales revenue for the day, in dollars.',ck='각 항은 수량×달러/개이므로 달러 단위이다.',ce='Each quantity times dollars per item contributes dollars.')
for n,a,c in [(15,(5,1),(3,2)),(16,(1,-3),(-3,4)),(17,(1,-4,1),(0,2,-2)),(18,(-1,3,4),(5,2,1)),(19,(1,-4,1),(-3,1,5)),(20,(8,-1,4),(0,4,2))]:exact(n,a,c,'angle')
for n,names,pts in [(21,'PQR',[(2,0),(0,3),(3,4)]),(22,'ABC',[(1,0,-1),(3,-2,0),(1,3,3)])]:
 ks=[];ans=[]
 for i in range(3):
  a=S.Matrix(pts[(i+1)%3])-S.Matrix(pts[i]);c=S.Matrix(pts[(i+2)%3])-S.Matrix(pts[i]);co=S.simplify(a.dot(c)/(a.norm()*c.norm()));deg=math.degrees(math.acos(float(co)));ks.append(m(r'\cos\angle '+names[i]+'='+S.latex(co)));ans.append(fr'\angle {names[i]}\approx{deg:.0f}^\circ')
 add(n,'삼각형 '+m(','.join(names[i]+'='+str(pts[i])for i in range(3)))+'의 세 각을 정수 도로 구하라.','Find the three angles, to the nearest degree, for '+m(','.join(names[i]+'='+str(pts[i])for i in range(3)))+'.',ks,ks,m(r',\ '.join(ans)),ck='반올림 전의 각도 합은180°이다.',ce='The unrounded angles sum to180°.')
cc=S.symbols('c',real=True)
for n,pairs in [(23,[((9,3),(-2,6)),((4,5,-2),(3,-1,5)),((-8,12,4),(6,-9,-3)),((3,-1,3),(5,9,-2))]),(24,[((-5,4,-2),(3,4,-1)),((9,-6,3),(-6,4,-2)),((cc,cc,cc),(cc,0,-cc))])]:
 ks=[];ans=[];english=[];stat=[]
 for i,(aa,bb)in enumerate(pairs):
  a=S.Matrix(aa);c=S.Matrix(bb);dot=S.expand(a.dot(c));rank=S.Matrix.hstack(a,c).rank();label=chr(97+i);stat.append(m(fr'({label})\ a='+v(a)+r',\ b='+v(c)));ks.append(m(fr'({label})\ a\cdot b='+S.latex(dot)))
  k,e=('직교','orthogonal')if dot==0 else('평행','parallel')if rank==1 else('둘 다 아님','neither');ans.append(f'({label}){k}');english.append(f'({label}){e}')
 if n==24:ks.append('c=0이면 두 벡터가 영벡터여서 방향각은 정의되지 않지만 내적0이라는 직교 조건은 성립한다.')
 es=ks[:-1]+['If c=0 both vectors are zero, so their angle is undefined, although their dot product is zero.']if n==24 else ks
 add(n,'직교·평행·그 외로 분류하라: '+'; '.join(stat),'Classify as orthogonal, parallel, or neither: '+'; '.join(stat),ks,es,'; '.join(ans),'; '.join(english),list('abcd')if n==23 else list('abc'),ck='내적0을 먼저 확인하고, 0이 아니면 성분비를 비교했다.',ce='Check zero dot product first, then compare coordinate ratios when it is nonzero.')
add(25,'P=(1,−3,−2),Q=(2,0,−4),R=(6,−2,−5)인 삼각형이 직각인지 벡터로 판정하라.','Use vectors to test whether P=(1,−3,−2),Q=(2,0,−4),R=(6,−2,−5) form a right triangle.',[m(r'QP=\langle-1,-3,2\rangle,\quad QR=\langle4,-2,-1\rangle'),m(r'QP\cdot QR=-4+6-2=0')],[m(r'QP=\langle-1,-3,2\rangle,\quad QR=\langle4,-2,-1\rangle'),m(r'QP\cdot QR=-4+6-2=0')],'Q에서 직각이다.','The right angle is at Q.',ck='세 변의 제곱은14,21,35로14+21=35이다.',ce='The squared side lengths14,21,35 satisfy14+21=35.')
add(26,m(r'\langle2,1,-1\rangle,\langle1,x,0\rangle')+'의 사이각이45°가 되는 x를 구하라.','Find x making the angle between '+m(r'\langle2,1,-1\rangle,\langle1,x,0\rangle')+' equal45°.',[m(r'\frac{x+2}{\sqrt6\sqrt{1+x^2}}=\frac1{\sqrt2},\quad x+2>0'),m(r'(x+2)^2=3(1+x^2)\ \Longrightarrow\ 2x^2-4x-1=0')],[m(r'\frac{x+2}{\sqrt6\sqrt{1+x^2}}=\frac1{\sqrt2},\quad x+2>0'),m(r'(x+2)^2=3(1+x^2)\ \Longrightarrow\ 2x^2-4x-1=0')],m(r'x=1\pm\frac{\sqrt6}{2}'),ck='두 근 모두x+2>0이어서 제곱 전 식도 만족한다.',ce='Both roots satisfyx+2>0 and hence the original unsquared equation.')
add(27,'i+j와i+k에 모두 수직인 단위벡터 하나를 구하라.','Find one unit vector perpendicular to both i+j and i+k.',[m(r'u=\langle a,b,c\rangle:\quad a+b=a+c=0'),m(r'b=c=-a,\quad3a^2=1')],[m(r'u=\langle a,b,c\rangle:\quad a+b=a+c=0'),m(r'b=c=-a,\quad3a^2=1')],m(r'u=\frac1{\sqrt3}\langle1,-1,-1\rangle'),ck='반대 부호의 벡터도 가능한 답이다.',ce='The negative of this vector is another valid answer.')
add(28,m(r'v=\langle3,4\rangle')+'와60°를 이루는 두 단위벡터를 구하라.','Find both unit vectors making60° with '+m(r'v=\langle3,4\rangle')+'.',[m(r'\hat v=\langle3/5,4/5\rangle,\quad n=\langle-4/5,3/5\rangle'),m(r'u_{\pm}=\tfrac12\hat v\pm\tfrac{\sqrt3}{2}n')],[m(r'\hat v=\langle3/5,4/5\rangle,\quad n=\langle-4/5,3/5\rangle'),m(r'u_{\pm}=\tfrac12\hat v\pm\tfrac{\sqrt3}{2}n')],m(r'u_\pm=\left\langle\frac{3\mp4\sqrt3}{10},\frac{4\pm3\sqrt3}{10}\right\rangle'),ck='각 벡터의 길이는1이고 v와의 내적은5/2이다.',ce='Each vector has length1 and dot product5/2 with v.')
for n,stat,a,c in [(29,r'y=4-3x,\ y=3x+2',(1,-3),(1,3)),(30,r'5x-y=8,\ x+3y=15',(1,5),(3,-1))]:
 u=S.Matrix(a);vv=S.Matrix(c);co=S.simplify(abs(u.dot(vv))/(u.norm()*vv.norm()));deg=math.degrees(math.acos(float(co)));add(n,m(stat)+' 두 직선 사이 예각을0.1°까지 구하라.','Find the acute angle between '+m(stat)+' to0.1°.',[m('d_1='+v(a)+r',\ d_2='+v(c)),m(r'\cos\theta=\frac{|d_1\cdot d_2|}{|d_1||d_2|}='+S.latex(co))],[m('d_1='+v(a)+r',\ d_2='+v(c)),m(r'\cos\theta=\frac{|d_1\cdot d_2|}{|d_1||d_2|}='+S.latex(co))],m(fr'\theta\approx{deg:.1f}^\circ'),ck='절댓값을 취하여 두 직선 사이의 예각을 선택했다.',ce='The absolute dot product selects the acute angle between lines.')
add(31,m(r'y=x^2,\ y=x^3')+'의 교점에서 접선 사이 각을0.1°까지 구하라.','Find the tangent angles at intersections of '+m(r'y=x^2,\ y=x^3')+' to0.1°.',[m(r'x^2=x^3\Longrightarrow x=0,1'),'원점에서는 두 접선이 모두수평이다. (1,1)에서 기울기는2,3이다.',m(r'\tan\theta=\left|\frac{3-2}{1+2\cdot3}\right|=1/7')],[m(r'x^2=x^3\Longrightarrow x=0,1'),'At the origin both tangents are horizontal. At(1,1) their slopes are2 and3.',m(r'\tan\theta=\left|\frac{3-2}{1+2\cdot3}\right|=1/7')],m(r'(0,0):0.0^\circ;\quad(1,1):8.1^\circ'),ck='원점에서는 엄밀히 예각이 아니라 각0°의 접촉이다.',ce='At the origin the angle is0°, rather than strictly acute.')
add(32,m(r'y=\sin x,y=\cos x,\ 0\le x\le\pi/2')+'의 교점에서 예각을0.1°까지 구하라.','Find the acute intersection angle of '+m(r'y=\sin x,y=\cos x,\ 0\le x\le\pi/2')+' to0.1°.',[m(r'x=\pi/4,\quad m_1=1/\sqrt2,\quad m_2=-1/\sqrt2'),m(r'\tan\theta=\frac{\sqrt2}{1-1/2}=2\sqrt2')],[m(r'x=\pi/4,\quad m_1=1/\sqrt2,\quad m_2=-1/\sqrt2'),m(r'\tan\theta=\frac{\sqrt2}{1-1/2}=2\sqrt2')],m(r'\theta=\arctan(2\sqrt2)\approx70.5^\circ'),ck='단위 접선의 내적 코사인은1/3이다.',ce='The unit tangent cosine is1/3.')
for n,aa in [(33,(4,1,8)),(34,(-6,2,9)),(35,(3,-1,-2)),(36,(S.Rational(-7,10),S.Rational(12,10),S.Rational(-8,10))), (37,(1,1,1))]:
 a=S.Matrix(aa);cos=a/a.norm();ang=[math.degrees(math.acos(float(q)))for q in cos];statement=m('a='+v(aa))if n!=37 else m(r'a=\langle c,c,c\rangle,\ c>0');add(n,statement+'의 방향코사인과 방향각(0.1°)을 구하라.','Find direction cosines and angles(to0.1°) for '+statement+'.',[m(r'(\cos\alpha,\cos\beta,\cos\gamma)=\frac{a}{|a|}='+v(cos))],[m(r'(\cos\alpha,\cos\beta,\cos\gamma)=\frac{a}{|a|}='+v(cos))],m(r'(\cos\alpha,\cos\beta,\cos\gamma)='+v(cos)+fr',\quad(\alpha,\beta,\gamma)=({ang[0]:.1f}^\circ,{ang[1]:.1f}^\circ,{ang[2]:.1f}^\circ)'),ck='세 방향코사인 제곱의 합은1이다.',ce='The sum of squared direction cosines is1.')
add(38,m(r'\alpha=\pi/4,\beta=\pi/3')+'일 때 세 번째 방향각γ를 구하라.','Find the third direction angleγ if '+m(r'\alpha=\pi/4,\beta=\pi/3')+'.',[m(r'\cos^2\gamma=1-1/2-1/4=1/4,\quad\cos\gamma=\pm1/2')],[m(r'\cos^2\gamma=1-1/2-1/4=1/4,\quad\cos\gamma=\pm1/2')],m(r'\gamma=\pi/3\ \text{or}\ 2\pi/3'),ck='z성분의 부호가 주어지지 않아 두 값 모두 가능하다.',ce='The unspecified sign of the z-component permits both values.')
for n,aa,bb in [(39,(-5,12),(4,6)),(40,(1,4),(2,3)),(41,(4,7,-4),(3,-1,1)),(42,(-1,4,8),(12,1,2)),(43,(3,-3,1),(2,4,-1)),(44,(1,2,3),(5,0,-1))]:
 a=S.Matrix(aa);c=S.Matrix(bb);dot=a.dot(c);comp=dot/a.norm();proj=dot/a.dot(a)*a;add(n,m('a='+v(a)+r',\ b='+v(c))+'에 대해 b의 a방향 스칼라·벡터 정사영을 구하라.','Find the scalar and vector projections of b onto a for '+m('a='+v(a)+r',\ b='+v(c))+'.',[m(r'a\cdot b='+S.latex(dot)+r',\quad |a|^2='+S.latex(a.dot(a))),m(r'\operatorname{comp}_a b=\frac{a\cdot b}{|a|},\quad\operatorname{proj}_a b=\frac{a\cdot b}{|a|^2}a')],[m(r'a\cdot b='+S.latex(dot)+r',\quad |a|^2='+S.latex(a.dot(a))),m(r'\operatorname{comp}_a b=\frac{a\cdot b}{|a|},\quad\operatorname{proj}_a b=\frac{a\cdot b}{|a|^2}a')],m(r'\operatorname{comp}_a b='+S.latex(comp)+r',\quad\operatorname{proj}_a b='+v(proj)),ck='b에서 벡터 정사영을 뺀 나머지와 a의 내적은0이다.',ce='The residual b minus its projection has zero dot product with a.')
add(45,m(r'a\ne0,\quad\operatorname{orth}_a b=b-\operatorname{proj}_a b')+'가 a와 수직임을 보여라.','Show that '+m(r'\operatorname{orth}_a b=b-\operatorname{proj}_a b')+' is orthogonal to nonzero a.',[m(r'a\cdot\operatorname{orth}_a b=a\cdot b-\frac{a\cdot b}{|a|^2}(a\cdot a)=0')],[m(r'a\cdot\operatorname{orth}_a b=a\cdot b-\frac{a\cdot b}{|a|^2}(a\cdot a)=0')],m(r'\operatorname{orth}_a b\perp a'),ck='정사영 정의에 a≠0이 필요하다.',ce='The projection requires a≠0.')
add(46,m(r'a=\langle1,4\rangle,b=\langle2,3\rangle')+'에 대해 직교성분을 구하고 a,b,정사영,직교성분을 그려라.','For '+m(r'a=\langle1,4\rangle,b=\langle2,3\rangle')+', find the orthogonal component and draw a,b and both components.',[m(r'\operatorname{proj}_a b=\frac{14}{17}\langle1,4\rangle'),m(r'\operatorname{orth}_a b=\langle2,3\rangle-\langle14/17,56/17\rangle')],[m(r'\operatorname{proj}_a b=\frac{14}{17}\langle1,4\rangle'),m(r'\operatorname{orth}_a b=\langle2,3\rangle-\langle14/17,56/17\rangle')],m(r'\operatorname{orth}_a b=\langle20/17,-5/17\rangle'),ck='20/17+4(−5/17)=0이다.',ce='20/17+4(−5/17)=0.')
add(47,m(r'a=\langle3,0,-1\rangle')+'이고 compₐb=2인 b 하나를 구하라.','Find one b satisfying compₐb=2 for '+m(r'a=\langle3,0,-1\rangle')+'.',[m(r'\operatorname{comp}_a b=\frac{3b_1-b_3}{\sqrt{10}}=2'),'a와 같은 방향이며 길이2인 b를 택하면 된다.'],[m(r'\operatorname{comp}_a b=\frac{3b_1-b_3}{\sqrt{10}}=2'),'Choose b in the direction of a with length2.'],m(r'b=\frac{2}{\sqrt{10}}\langle3,0,-1\rangle'),ck='더 일반적으로3b₁−b₃=2√10이고 b₂는 자유롭다.',ce='More generally3b₁−b₃=2√10, with b₂ arbitrary.')
add(48,'0이 아닌 a,b에 대해 (a)compₐb=comp_ba,(b)projₐb=proj_ba가 성립할 조건을 구하라.','For nonzero a,b, determine when(a)compₐb=comp_ba and(b)projₐb=proj_ba.',[m(r'(a)\quad(a\cdot b)\left(\frac1{|a|}-\frac1{|b|}\right)=0'),m(r'(b)\quad(a\cdot b)\left(\frac{a}{|a|^2}-\frac{b}{|b|^2}\right)=0'),'내적이0이 아닌 두 번째 경우, 양쪽 벡터의 길이를 비교하면|a|=|b|이고 이어a=b이다.'],[m(r'(a)\quad(a\cdot b)\left(\frac1{|a|}-\frac1{|b|}\right)=0'),m(r'(b)\quad(a\cdot b)\left(\frac{a}{|a|^2}-\frac{b}{|b|^2}\right)=0'),'In(b), when the dot product is nonzero, comparing norms gives|a|=|b|, and hence a=b.'],'(a)a⊥b 또는|a|=|b|. (b)a⊥b 또는a=b.','(a)a⊥b or|a|=|b|. (b)a⊥b or a=b.',list('ab'),ck='충분성은 각 조건을 정사영 공식에 직접 대입하여 확인한다.',ce='Each condition is sufficient by direct substitution into the projection formula.')
add(49,m(r'F=\langle8,-6,9\rangle')+' N이 물체를(0,10,8)에서(6,12,20)m로 이동시킬 때 일을 구하라.','Find the work by '+m(r'F=\langle8,-6,9\rangle')+' N for displacement from(0,10,8)to(6,12,20)m.',[m(r'D=\langle6,2,12\rangle,\quad W=F\cdot D=48-12+108')],[m(r'D=\langle6,2,12\rangle,\quad W=F\cdot D=48-12+108')],m(r'W=144\ \mathrm J'),ck='단위는N·m=J이다.',ce='The unit is N·m=J.')
for n,F,D,angle,unit,ko,en in [(50,1500,1000,30,'J','견인줄 장력1500N, 도로와30°일 때1km 견인한 일을 구하라.','Find work towing a car1km with1500N tension at30° to the road.'),(51,30,80,40,r'ft\cdot lb','수평길을80ft 움직이는 썰매를40°의30lb 힘으로 당긴 일을 구하라.','Find the work pulling a sled80ft horizontally with30lb at40°.'),(52,400,120,36,r'ft\cdot lb','S36°E 방향400lb 바람이 배를남쪽으로120ft 이동시킨 일을 구하라.','Find the work of a400lb wind toward S36°E as a boat moves south120ft.')]:
 val=F*D*math.cos(math.radians(angle));add(n,ko,en,[m(fr'W=|F||D|\cos\theta={F}\cdot{D}\cos{angle}^\circ')],[m(fr'W=|F||D|\cos\theta={F}\cdot{D}\cos{angle}^\circ')],m(fr'W={F*D}\cos{angle}^\circ\approx{val:.3f}\ \mathrm{{{unit}}}'),ck='힘의 이동방향 성분만 일에 기여한다.',ce='Only the force component along displacement contributes work.')
add(53,'스칼라 정사영으로 점(x₁,y₁)에서 ax+by+c=0까지의 거리 공식을 증명하고 (−2,3)에서3x−4y+5=0까지의 거리를 구하라.','Use scalar projection to prove the distance from(x₁,y₁)to ax+by+c=0, then apply it to(−2,3)and3x−4y+5=0.',[m(r'n=\langle a,b\rangle\ne0,\quad n\cdot(P_1-P_0)=ax_1+by_1+c'),'직선 위 임의점P₀에서 P₁로의 변위를 법선 방향에 정사영하고 절댓값을 취한다.',m(r'D=\frac{|-6-12+5|}{5}=13/5')],[m(r'n=\langle a,b\rangle\ne0,\quad n\cdot(P_1-P_0)=ax_1+by_1+c'),'Project displacement from a point P₀ on the line to P₁ onto the normal and take its absolute value.',m(r'D=\frac{|-6-12+5|}{5}=13/5')],m(r'D=\frac{|ax_1+by_1+c|}{\sqrt{a^2+b^2}};\quad D_{\rm example}=13/5'),ck='법선벡터는0이 아니어야 직선이 정의된다.',ce='A nonzero normal is necessary for the line.')
add(54,m(r'(r-a)\cdot(r-b)=0')+'이 구를 나타냄을 보이고 중심·반지름을 구하라.','Show that '+m(r'(r-a)\cdot(r-b)=0')+' defines a sphere and find its center and radius.',[m(r'\left|r-\frac{a+b}{2}\right|^2=\frac{|a-b|^2}{4}')],[m(r'\left|r-\frac{a+b}{2}\right|^2=\frac{|a-b|^2}{4}')],m(r'C=\frac{a+b}{2},\quad R=\frac{|a-b|}{2}'),ck='a=b이면 반지름0의 한 점으로 퇴화한다.',ce='If a=b, it degenerates to a single point of radius0.')
for n,k,e,co in [(55,'정육면체의 공간대각선과 한 모서리 사이각을0.1°까지 구하라.','Find the angle between a cube’s space diagonal and an edge to0.1°.',1/S.sqrt(3)),(56,'정육면체의 공간대각선과 한 면의 대각선 사이각을0.1°까지 구하라.','Find the angle between a cube’s space diagonal and a face diagonal to0.1°.',S.sqrt(S.Rational(2,3)))]:
 dd=(1,0,0)if n==55 else(1,1,0);add(n,k,e,[m(r'd=\langle1,1,1\rangle,\ e='+v(dd)),m(r'\cos\theta='+S.latex(co))],[m(r'd=\langle1,1,1\rangle,\ e='+v(dd)),m(r'\cos\theta='+S.latex(co))],m(fr'\theta\approx{math.degrees(math.acos(float(co))):.1f}^\circ'),ck='정육면체 크기를 바꾸어도 각도는 변하지 않는다.',ce='Scaling the cube leaves the angle unchanged.')
add(57,'메테인의 네 수소를 정사면체 꼭짓점(1,0,0),(0,1,0),(0,0,1),(1,1,1), 탄소를 중심에 놓아 H–C–H 결합각이 약109.5°임을 보여라.','Place hydrogen atoms at(1,0,0),(0,1,0),(0,0,1),(1,1,1)and carbon at their centroid. Show the H–C–H angle is about109.5°.',[m(r'C=(1/2,1/2,1/2),\quad u=\langle1/2,-1/2,-1/2\rangle,\ v=\langle-1/2,1/2,-1/2\rangle'),m(r'u\cdot v=-1/4,\quad|u||v|=3/4,\quad\cos\theta=-1/3')],[m(r'C=(1/2,1/2,1/2),\quad u=\langle1/2,-1/2,-1/2\rangle,\ v=\langle-1/2,1/2,-1/2\rangle'),m(r'u\cdot v=-1/4,\quad|u||v|=3/4,\quad\cos\theta=-1/3')],m(r'\theta=\arccos(-1/3)\approx109.5^\circ'),ck='정사면체 대칭에 의해 다른 수소 쌍도 같은 각도이다.',ce='Tetrahedral symmetry gives the same angle for every other pair.')
add(58,m(r'c=|a|b+|b|a')+'이고 a,b,c가 모두0이 아닐 때 c가 a,b의 사이각을 이등분함을 보여라.','Show that nonzero '+m(r'c=|a|b+|b|a')+' bisects the angle between nonzero a,b.',[m(r'c=|a||b|\left(\frac a{|a|}+\frac b{|b|}\right)'),m(r'\frac{a\cdot c}{|a||c|}=\frac{|a||b|+a\cdot b}{|c|}=\frac{b\cdot c}{|b||c|}')],[m(r'c=|a||b|\left(\frac a{|a|}+\frac b{|b|}\right)'),m(r'\frac{a\cdot c}{|a||c|}=\frac{|a||b|+a\cdot b}{|c|}=\frac{b\cdot c}{|b||c|}')],'c는 내부 각이등분선 방향이다.','c points along the internal angle bisector.',ck='두 단위벡터의 양의 합이며 c≠0이므로 서로 반대인 퇴화경우는 제외된다.',ce='The positive sum of unit vectors is internal; c≠0 excludes opposite directions.')
add(59,'내적의 교환법칙, 스칼라배와의 양립성,0벡터와의 내적이0임을 성분으로 증명하라(정리2의2·4·5).','Prove commutativity, compatibility with scalar multiplication, and the zero-vector property using components(Theorem2, properties2,4,5).',[m(r'a\cdot b=\sum_i a_i b_i=\sum_i b_i a_i=b\cdot a'),m(r'(\lambda a)\cdot b=\sum_i\lambda a_i b_i=\lambda(a\cdot b)=a\cdot(\lambda b)'),m(r'0\cdot a=\sum_i0a_i=0')],[m(r'a\cdot b=\sum_i a_i b_i=\sum_i b_i a_i=b\cdot a'),m(r'(\lambda a)\cdot b=\sum_i\lambda a_i b_i=\lambda(a\cdot b)=a\cdot(\lambda b)'),m(r'0\cdot a=\sum_i0a_i=0')],'세 성질이 모두 성립한다.','All three identities hold.',ck='각 성분은 실수여서 보통의 곱셈·덧셈 법칙을 적용할 수 있다.',ce='Ordinary real-number arithmetic applies to each component.')
add(60,'네 변 길이가 같고 마주 보는 변이 평행한 사각형의 대각선이 수직임을 벡터로 증명하라.','Use vectors to show that a quadrilateral with equal sides and parallel opposite sides has perpendicular diagonals.',[m(r'|a|=|b|,\quad d_1=a+b,\quad d_2=a-b'),m(r'd_1\cdot d_2=|a|^2-|b|^2=0')],[m(r'|a|=|b|,\quad d_1=a+b,\quad d_2=a-b'),m(r'd_1\cdot d_2=|a|^2-|b|^2=0')],m(r'd_1\perp d_2'),ck='공통 꼭짓점에서 나가는 인접한 두 변을 a,b로 택했다.',ce='a,b are adjacent side vectors from a common vertex.')
add(61,'내적의 각도 공식을 이용해 코시–슈바르츠 부등식을 증명하라.','Prove Cauchy–Schwarz using the angle formula.',[m(r'|a\cdot b|=|a||b||\cos\theta|\le|a||b|'),'어느 벡터가0이면 양변이0이므로 별도로 성립한다.'],[m(r'|a\cdot b|=|a||b||\cos\theta|\le|a||b|'),'If either vector is zero, both sides are zero and the result still holds.'],m(r'|a\cdot b|\le|a||b|'),ck='0이 아닌 경우 등호는 평행일 때 성립한다.',ce='For nonzero vectors equality holds exactly for parallel vectors.')
add(62,'삼각부등식의(a)기하적 의미를 설명하고(b)코시–슈바르츠로 증명하라.','Explain(a)the geometry of the triangle inequality and(b)prove it using Cauchy–Schwarz.',['직접 가는 선분 길이는 두 변을 거쳐 가는 길이보다 길지 않다.',m(r'|a+b|^2=|a|^2+2a\cdot b+|b|^2\le(|a|+|b|)^2'),'양변이 음수가 아니므로 제곱근을 취한다.'],['The direct side is no longer than the route along the other two sides.',m(r'|a+b|^2=|a|^2+2a\cdot b+|b|^2\le(|a|+|b|)^2'),'Both sides are nonnegative, so taking square roots preserves the inequality.'],m(r'|a+b|\le|a|+|b|'),parts=list('ab'),ck='0이 아닌 경우 두 벡터가 같은 방향일 때 등호이다.',ce='For nonzero vectors equality requires the same direction.')
add(63,'평행사변형 항등식의(a)기하적 의미,(b)내적에 의한 증명을 제시하라.','Give(a)the geometric meaning and(b)a dot-product proof of the parallelogram identity.',['두 대각선 길이 제곱의 합은 네 변 길이 제곱의 합과 같다.',m(r'|a+b|^2=|a|^2+2a\cdot b+|b|^2'),m(r'|a-b|^2=|a|^2-2a\cdot b+|b|^2'),'두 식을 더하면 교차항이 상쇄된다.'],['The squared diagonal lengths sum to the sum of the four squared side lengths.',m(r'|a+b|^2=|a|^2+2a\cdot b+|b|^2'),m(r'|a-b|^2=|a|^2-2a\cdot b+|b|^2'),'Adding cancels the cross terms.'],m(r'|a+b|^2+|a-b|^2=2|a|^2+2|b|^2'),parts=list('ab'))
add(64,'u+v와u−v가 수직이면 |u|=|v|임을 보여라.','Show that orthogonality of u+v and u−v implies |u|=|v|.',[m(r'0=(u+v)\cdot(u-v)=|u|^2-|v|^2')],[m(r'0=(u+v)\cdot(u-v)=|u|^2-|v|^2')],m(r'|u|=|v|'),ck='길이는 음수가 아니므로 제곱이 같으면 길이도 같다.',ce='Nonnegative lengths are equal when their squares are equal.')
add(65,'0이 아닌 a,b의 사이각θ에 대해 두 상호 정사영의 내적 항등식을 증명하라.','Prove the dot-product identity for the mutual projections of nonzero a,b with angleθ.',[m(r'\operatorname{proj}_a b\cdot\operatorname{proj}_b a=\frac{(a\cdot b)^3}{|a|^2|b|^2}'),m(r'\frac{(a\cdot b)^2}{|a|^2|b|^2}=\cos^2\theta')],[m(r'\operatorname{proj}_a b\cdot\operatorname{proj}_b a=\frac{(a\cdot b)^3}{|a|^2|b|^2}'),m(r'\frac{(a\cdot b)^2}{|a|^2|b|^2}=\cos^2\theta')],m(r'\operatorname{proj}_a b\cdot\operatorname{proj}_b a=(a\cdot b)\cos^2\theta'),ck='분모에 길이가 있으므로 두 벡터가0이 아니어야 한다.',ce='The denominators require both vectors to be nonzero.')
add(66,'0이 아닌 u,v에 대해(a)수직이면 피타고라스 항등식,(b)그 항등식이면 수직임을 증명하라.','For nonzero u,v, prove(a)orthogonality implies the Pythagorean identity and(b)the converse.',[m(r'|u+v|^2=|u|^2+2u\cdot v+|v|^2'),'수직이면 중간항이0이다. 반대로 피타고라스 항등식을 위 식에서 빼면2u·v=0이다.'],[m(r'|u+v|^2=|u|^2+2u\cdot v+|v|^2'),'Orthogonality makes the middle term zero. Conversely, subtracting the Pythagorean identity gives2u·v=0.'],m(r'|u+v|^2=|u|^2+|v|^2\quad\Longleftrightarrow\quad u\perp v'),parts=list('ab'),ck='0이 아닌 벡터에서 내적0은90°와 동치이다.',ce='For nonzero vectors, zero dot product is equivalent to90°.')
assert list(b.E)==list(range(1,67));b.save()
