"""Source-checked line and plane exercises, with exact substitution checks."""
from early_helpers import Book
import sympy as S, math,json
from pathlib import Path
b=Book('12.5',[910,911,912]);checks=[]
x,y,z,t,u=S.symbols('x y z t u',real=True);X=S.Matrix([x,y,z]);M=S.Matrix
R=S.Rational
def tex(q):return S.latex(S.simplify(q))
def v(q):return r'\langle'+','.join(tex(a) for a in q)+r'\rangle'
def m(q):return r'\('+q+r'\)'
def line(p,d):return 'r='+v(p)+'+t'+v(d)
def par(p,d):return r',\quad '.join(a+'='+tex(q)for a,q in zip(['x','y','z'],p+t*d))
def sym(p,d):
 frac=[r'\frac{'+tex(q-a)+'}{'+tex(c)+'}'for q,a,c in zip(X,p,d)if c!=0];fixed=[tex(q)+'='+tex(a)for q,a,c in zip(X,p,d)if c==0]
 return r',\quad '.join(['='.join(frac)]+fixed)
def plane(n,p):return tex(n.dot(X))+'='+tex(n.dot(p))
def eq(label,a,c=0):
 q=a-c
 assert all(S.simplify(i)==0 for i in q)if isinstance(q,S.MatrixBase)else S.simplify(q)==0,(label,a,c)
 checks.append(label)
def add(n,k,e,ks,es,ans,ae=None,parts=[]):
 b.add(n,910 if n<=30 else 911 if n<=68 else 912,('직선과 평면의 방정식','Equations of lines and planes'),(k,e),list(zip(ks,es)),(ans,ans if ae is None else ae),parts,check=('방향·법선의 내적, 대입식 또는 제시한 반례로 조건을 확인했다.','The conditions were checked by direction/normal dot products, substitution, or the stated counterexample.'));b.E[n]['conceptHref']='../../calc1/index.html'
add(1,'공간에서 다음 명제의 참·거짓을 판별하라. (a,b)같은 직선에 평행/수직인 두 직선은 서로 평행. (c,d)같은 평면에 평행/수직인 두 평면은 서로 평행. (e,f)같은 평면에 평행/수직인 두 직선은 서로 평행. (g,h)같은 직선에 평행/수직인 두 평면은 서로 평행. (i)두 평면,(j)두 직선,(k)평면과 직선은 만나거나 평행하다.','Decide in space: (a,b) Two lines parallel/perpendicular to one line are parallel. (c,d) Two planes parallel/perpendicular to one plane are parallel. (e,f) Two lines parallel/perpendicular to one plane are parallel. (g,h) Two planes parallel/perpendicular to one line are parallel. (i) Two planes,(j) two lines,(k) a plane and line intersect or are parallel.', ['같은 방향의 배수인 직선 또는 같은 법선의 배수인 평면은 평행하다. 이로부터(a),(c),(f),(h)가 참이다.','(b) x축과 y축은 z축에 수직이나 서로 평행하지 않다. (d) xz,yz평면은 xy평면에 수직이나 서로 만난다.','(e) z=1에 놓인 x방향,y방향 직선은 xy평면에 평행이나 서로 교차한다. (g) y=0,y=x평면은 직선(0,1,t)에 평행이나 서로 교차한다.','(i),(k)는 교집합이 있으면 만난다고 해석하면 참이다. (j)는 꼬인 직선 때문에 거짓이다.'],['Lines with proportional directions and planes with proportional normals are parallel; this proves(a),(c),(f),(h).','For(b), x- and y-axes are perpendicular to z but not parallel. For(d), xz and yz are perpendicular to xy but intersect.','For(e), x- and y-directed lines in z=1 are parallel to xy but intersect. For(g), y=0 and y=x are parallel to the line(0,1,t) but intersect.','Statements(i),(k) are true when intersect means having a point in common; (j) fails for skew lines.'],'참: a,c,f,h,i,k. 거짓: b,d,e,g,j.','True: a,c,f,h,i,k. False: b,d,e,g,j.',list('abcdefghijk'))
line_rows=[(2,(4,2,-3),(2,-1,6),'주어진 방향벡터','the given direction'),(3,(-1,8,7),(R(1,2),R(1,3),R(1,4)),'주어진 방향벡터','the given direction'),(4,(6,0,-2),(-3,4,5),'직선 (4,−1,6)+t(−3,4,5)에 평행','parallel to (4,−1,6)+t(−3,4,5)'),(5,(5,7,1),(3,-2,2),'평면3x−2y+2z=8에 수직','perpendicular to 3x−2y+2z=8')]
for n,pp,dd,k,e in line_rows:
 p,d=M(pp),M(dd);add(n,m(v(p))+'를 지나며 '+k+(' '+m(v(d))if n<4 else'')+'인 직선의 벡터식과 매개식을 구하라.','Find vector and parametric equations through '+m(v(p))+' with '+e+(' '+m(v(d))if n<4 else'')+'.',[m('p='+v(p)+r',\ d='+v(d)),'한 점p와 방향d를 알면 r=p+td이다.'],[m('p='+v(p)+r',\ d='+v(d)),'A point p and direction d give r=p+td.'],m(line(p,d))+'; '+m(par(p,d)));eq(f'{n} base point',(p+t*d).subs(t,0),p)
for n,aa,bb in [(6,(-5,2,5),(1,6,-2)),(7,(0,0,0),(8,-1,3)),(8,(R(4,10),R(-2,10),R(11,10)),(R(13,10),R(8,10),R(-23,10))),(9,(12,9,-13),(-7,9,11))]:
 p,q=M(aa),M(bb);d=q-p;eq(f'{n} second endpoint',p+d,q);add(n,'두 점 '+m(v(p)+r',\ '+v(q))+'을 지나는 직선의 매개식과 대칭식을 구하라.','Find parametric and symmetric equations through '+m(v(p)+r',\ '+v(q))+'.',[m('d=Q-P='+v(d)),'방향성분이0인 좌표는 상수식으로 남긴다.'],[m('d=Q-P='+v(d)),'A coordinate with zero direction component remains constant.'],m(par(p,d))+'; '+m(sym(p,d)))
for n,pp,dd,ko,en,step in [(10,(2,1,0),(1,-1,1),'i+j와 j+k에 모두 수직','perpendicular to i+j and j+k',r'd=(i+j)\times(j+k)=\langle1,-1,1\rangle'),(11,(-6,2,3),(2,3,1),'x/2=y/3=z+1에 평행','parallel to x/2=y/3=z+1',r'x=2t,\ y=3t,\ z=t-1\Rightarrow d=\langle2,3,1\rangle'),(12,(1,0,0),(5,2,-3),'두 평면 x+2y+3z=1, x−y+z=1의 교선','the intersection of x+2y+3z=1 and x−y+z=1',r'\langle1,2,3\rangle\times\langle1,-1,1\rangle=\langle5,2,-3\rangle')]:
 p,d=M(pp),M(dd);add(n,(m(v(p))+'를 지나며 'if n!=12 else'')+ko+'인 직선의 매개식과 대칭식을 구하라.','Find parametric and symmetric equations for '+en+(' through '+m(v(p))if n!=12 else'')+'.',[m(step),m('p='+v(p))],[m(step),m('p='+v(p))],m(par(p,d))+'; '+m(sym(p,d)))
eq('12 both plane identities',M([M([1,2,3]).dot(M([1,0,0])+t*M([5,2,-3]))-1,M([1,-1,1]).dot(M([1,0,0])+t*M([5,2,-3]))-1]),M([0,0]))
add(13,'(−4,−6,1),(−2,0,−3)을 잇는 직선과(10,18,4),(5,3,14)를 잇는 직선이 평행한가?','Are the lines through (−4,−6,1),(−2,0,−3) and through (10,18,4),(5,3,14) parallel?',[m(r'd_1=\langle2,6,-4\rangle,\quad d_2=\langle-5,-15,10\rangle=-\tfrac52d_1')],[m(r'd_1=\langle2,6,-4\rangle,\quad d_2=\langle-5,-15,10\rangle=-\tfrac52d_1')],'예. 방향벡터가 비례한다.','Yes; their directions are proportional.')
add(14,'(−2,4,0),(1,1,1)의 직선과(2,3,4),(3,−1,−8)의 직선이 수직한가?','Are the lines through (−2,4,0),(1,1,1) and through (2,3,4),(3,−1,−8) perpendicular?',[m(r'd_1=\langle3,-3,1\rangle,\quad d_2=\langle1,-4,-12\rangle'),m(r'd_1\cdot d_2=3+12-12=3\ne0')],[m(r'd_1=\langle3,-3,1\rangle,\quad d_2=\langle1,-4,-12\rangle'),m(r'd_1\cdot d_2=3+12-12=3\ne0')],'아니오.','No.')
for n,pp,dd in [(15,(1,-5,6),(-1,2,-3)),(16,(2,4,6),(1,-1,3))]:
 p,d=M(pp),M(dd);pts=[];steps=[]
 for i,name in enumerate(['yz','xz','xy']):
  val=-p[i]/d[i];q=p+val*d;eq(f'{n} {name} zero coordinate',q[i]);pts.append(name+': '+m(v(q)));steps.append(m('t='+tex(val)+r'\Rightarrow '+v(q)))
 add(n,'(a)'+m(v(p))+'를 지나 '+('방향'+m(v(d))+'에 평행한 직선의 대칭식'if n==15 else'평면 x−y+3z=7에 수직인 직선의 매개식')+'을 구하고,(b)세 좌표평면과의 교점을 구하라.','(a) Find '+('symmetric equations with direction '+m(v(d))if n==15 else'parametric equations perpendicular to x−y+3z=7')+' through '+m(v(p))+'. (b) Find intersections with all coordinate planes.',[m(line(p,d)),'x,y,z를 각각0으로 놓아 t를 구한다.']+steps,[m(line(p,d)),'Set x,y,z equal to zero in turn and solve for t.']+steps,'(a) '+m(sym(p,d)if n==15 else par(p,d))+'; (b) '+'; '.join(pts),parts=list('ab'))
for n,aa,bb in [(17,(6,-1,9),(7,6,0)),(18,(-2,18,31),(11,4,48))]:
 p,q=M(aa),M(bb);d=q-p;eq(f'{n} endpoints',p+d,q);add(n,m(v(p)+r',\ '+v(q))+'를 잇는 선분의 '+('벡터식'if n==17 else'매개식')+'을 구하라.','Find '+('a vector equation'if n==17 else'parametric equations')+' for the segment from '+m(v(p))+' to '+m(v(q))+'.',[m(r'r=(1-t)P+tQ,\quad 0\le t\le1')],[m(r'r=(1-t)P+tQ,\quad 0\le t\le1')],m((line(p,d)if n==17 else par(p,d))+r',\quad0\le t\le1'))
for n,pp,dd,qq,ee in [(19,(3,4,1),(2,-1,3),(1,3,4),(4,-2,5)),(20,(5,3,1),(-12,9,-3),(3,0,7),(8,-6,2)),(21,(2,3,1),(1,-2,-3),(3,-4,2),(1,3,-7)),(22,(0,1,2),(1,-1,3),(2,3,0),(2,-2,7))]:
 p,d,q,e=map(M,[pp,dd,qq,ee]);sol=S.solve(p+t*d-q-u*e,(t,u));cross=d.cross(e);ks=[m(r'd_1\times d_2='+v(cross))];es=ks.copy()
 if cross==M([0,0,0]):ans='서로 다른 평행선.';ae='Distinct parallel lines.';ks+=['방향은 비례하나 한 직선의 기준점이 다른 직선 위에 있지 않다.'];es+=['Directions are proportional, but a base point does not lie on the other line.']
 elif sol:
  point=p+sol[t]*d;eq(f'{n} intersection',point,q+sol[u]*e);ans=ae=m(v(point));ks+=[m('t='+tex(sol[t])+r',\ u='+tex(sol[u]))];es+=ks[-1:]
 else:ans='꼬인 직선.';ae='Skew lines.';ks+=['세 좌표를 동시에 같게 놓은 연립식은 해가 없다.'];es+=['Equating all three coordinates gives an inconsistent system.']
 add(n,m('L_1:'+line(p,d))+', '+m('L_2:'+line(q,e).replace('t','u'))+'의 위치관계를 판별하고 교점이 있으면 구하라.','Classify '+m('L_1:'+line(p,d))+' and '+m('L_2:'+line(q,e).replace('t','u'))+'; find any intersection.',ks,es,ans,ae)
plane_rows=[(23,(3,2,1),(5,4,6),'법선(5,4,6)','normal (5,4,6)'),(24,(-3,4,2),(6,1,-1),'법선(6,1,−1)','normal (6,1,−1)'),(25,(5,-2,4),(-1,2,3),'벡터(−1,2,3)에 수직','perpendicular to (−1,2,3)'),(26,(0,0,0),(-8,-7,2),'직선(1,−1,4)+t(−8,−7,2)에 수직','perpendicular to (1,−1,4)+t(−8,−7,2)'),(27,(1,3,-1),(4,-1,5),'직선(x+3)/4=−y=(z−1)/5에 수직','perpendicular to (x+3)/4=−y=(z−1)/5'),(28,(9,-4,-5),(2,-3,-1),'평면z=2x−3y에 평행','parallel to z=2x−3y'),(29,(R(21,10),R(17,10),R(-9,10)),(2,-1,3),'평면2x−y+3z=1에 평행','parallel to 2x−y+3z=1'),(30,(1,2,4),(5,2,1),'직선(1,2,4)+t(1,−1,−3)을 포함하고5x+2y+z=1에 평행','containing (1,2,4)+t(1,−1,−3) and parallel to 5x+2y+z=1')]
for n,pp,nn,k,e in plane_rows:
 p,normal=M(pp),M(nn);eq(f'{n} plane point',normal.dot(p)-normal.dot(p));add(n,m(v(p))+'를 지나고 '+k+'인 평면을 구하라.','Find the plane through '+m(v(p))+' with '+e+'.',[m('n='+v(normal)),m(r'n\cdot(X-P)=0')],[m('n='+v(normal)),m(r'n\cdot(X-P)=0')],m(plane(normal,p)))
eq('30 whole line contained',M([5,2,1]).dot(M([1,2,4])+t*M([1,-1,-3]))-13)
for n,aa,bb,cc in [(31,(0,1,1),(1,0,1),(1,1,0)),(32,(0,0,0),(3,-2,1),(1,1,1)),(33,(2,1,2),(3,-8,6),(-2,-3,1)),(34,(3,0,-1),(-2,-2,3),(7,1,-4))]:
 p,q,r=map(M,[aa,bb,cc]);d=q-p;e=r-p;normal=d.cross(e)
 for j,point in enumerate([p,q,r]):eq(f'{n} point {j}',normal.dot(point-p))
 add(n,'세 점 '+m(v(p)+r',\ '+v(q)+r',\ '+v(r))+'을 지나는 평면을 구하라.','Find the plane through '+m(v(p)+r',\ '+v(q)+r',\ '+v(r))+'.',[m('Q-P='+v(d)+r',\ R-P='+v(e)),m(r'n=(Q-P)\times(R-P)='+v(normal))],[m('Q-P='+v(d)+r',\ R-P='+v(e)),m(r'n=(Q-P)\times(R-P)='+v(normal))],m(plane(normal,p)))
for n,pp,qq,dd in [(35,(3,5,-1),(4,-1,0),(-1,2,-3)),(36,(6,-1,3),(0,-4,0),(3,1,2))]:
 p,q,d=map(M,[pp,qq,dd]);normal=d.cross(p-q);eq(f'{n} line identity',normal.dot(q+t*d-p));add(n,'점 '+m(v(p))+'과 직선 '+m(line(q,d))+'을 포함하는 평면을 구하라.','Find the plane containing '+m(v(p))+' and '+m(line(q,d))+'.',[m(r'n=d\times(P-Q)='+v(normal)),m(r'n\cdot(X-P)=0')],[m(r'n=d\times(P-Q)='+v(normal)),m(r'n\cdot(X-P)=0')],m(plane(normal,p)))
add(37,'(3,1,4)를 지나고 x+2y+3z=1, 2x−y+z=−3의 교선을 포함하는 평면을 구하라.','Find the plane through (3,1,4) containing the intersection of x+2y+3z=1 and 2x−y+z=−3.',[m(r'(x+2y+3z-1)+\lambda(2x-y+z+3)=0'),m(r'16+12\lambda=0\Rightarrow\lambda=-4/3')],[m(r'(x+2y+3z-1)+\lambda(2x-y+z+3)=0'),m(r'16+12\lambda=0\Rightarrow\lambda=-4/3')],m('x-2y-z+3=0'))
eq('37 pencil simplification',3*(x+2*y+3*z-1)-4*(2*x-y+z+3),-5*(x-2*y-z+3))
p=M([0,-2,5]);q=M([-1,3,1]);normal=(q-p).cross(M([5,4,-2]));eq('38 orthogonal normals',normal.dot(M([5,4,-2])))
add(38,'(0,−2,5),(−1,3,1)을 지나고2z=5x+4y에 수직인 평면을 구하라.','Find the plane through (0,−2,5),(−1,3,1), perpendicular to 2z=5x+4y.',[m(r'n=\langle-1,5,-4\rangle\times\langle5,4,-2\rangle='+v(normal))],[m(r'n=\langle-1,5,-4\rangle\times\langle5,4,-2\rangle='+v(normal))],m(plane(normal,p)))
normal=M([2,1,-2]).cross(M([1,0,3]));p=M([1,5,1]);add(39,'(1,5,1)을 지나고2x+y−2z=2와x+3z=4에 모두 수직인 평면을 구하라.','Find the plane through (1,5,1) perpendicular to both 2x+y−2z=2 and x+3z=4.',[m(r'n=\langle2,1,-2\rangle\times\langle1,0,3\rangle='+v(normal))],[m(r'n=\langle2,1,-2\rangle\times\langle1,0,3\rangle='+v(normal))],m(plane(normal,p)))
add(40,'x−z=1,y+2z=3의 교선을 포함하고x+y−2z=1에 수직인 평면을 구하라.','Find the plane containing the intersection of x−z=1,y+2z=3 and perpendicular to x+y−2z=1.',[m(r'(x-z-1)+\lambda(y+2z-3)=0'),m(r'\langle1,\lambda,-1+2\lambda\rangle\cdot\langle1,1,-2\rangle=3-3\lambda=0')],[m(r'(x-z-1)+\lambda(y+2z-3)=0'),m(r'\langle1,\lambda,-1+2\lambda\rangle\cdot\langle1,1,-2\rangle=3-3\lambda=0')],m('x+y+z=4'))
for n,nn,c in [(41,(2,5,1),10),(42,(3,1,2),6),(43,(6,-3,4),6),(44,(6,5,-3),15)]:
 normal=M(nn);inter=[M([R(c,nn[0]),0,0]),M([0,R(c,nn[1]),0]),M([0,0,R(c,nn[2])])]
 for j,p in enumerate(inter):eq(f'{n} intercept {j}',normal.dot(p),c)
 add(n,'절편을 이용해 '+m(tex(normal.dot(X))+'='+str(c))+'를 그려라.','Sketch '+m(tex(normal.dot(X))+'='+str(c))+' using intercepts.',['두 좌표를0으로 놓아 각 축과의 교점을 구한다.','세 절편을 잇는 삼각형은 평면의 일부이며 세 방향으로 무한히 연장된다.'],['Set two coordinates to zero to find each axis intersection.','The triangle joining the intercepts is only part of the plane, which extends indefinitely.'],'x,y,z 절편점: '+', '.join(m(v(p))for p in inter),'x,y,z intercept points: '+', '.join(m(v(p))for p in inter))
for n,pp,dd,nn,c in [(45,(2,0,1),(-2,3,1),(1,2,-1),7),(46,(-1,1,3),(1,2,-1),(3,-1,2),5),(47,(0,0,-2),(R(1,5),2,1),(10,-7,3),-24),(48,(-3,1,0),(2,4,6),(2,1,-1),-2)]:
 p,d,normal=map(M,[pp,dd,nn]);val=S.simplify((c-normal.dot(p))/normal.dot(d));point=p+val*d;eq(f'{n} plane substitution',normal.dot(point),c)
 add(n,'직선 '+m(line(p,d))+'과 평면 '+m(tex(normal.dot(X))+'='+str(c))+'의 교점을 구하라.','Find the intersection of '+m(line(p,d))+' and '+m(tex(normal.dot(X))+'='+str(c))+'.',[m(tex(normal.dot(p+t*d))+'='+str(c)),m('t='+tex(val))],[m(tex(normal.dot(p+t*d))+'='+str(c)),m('t='+tex(val))],m(v(point)))
add(49,'x+y+z=1과x+z=0의 교선의 방향수를 구하라.','Find direction numbers for the intersection of x+y+z=1 and x+z=0.',[m(r'd=\langle1,1,1\rangle\times\langle1,0,1\rangle=\langle1,0,-1\rangle')],[m(r'd=\langle1,1,1\rangle\times\langle1,0,1\rangle=\langle1,0,-1\rangle')],m('(1,0,-1)'))
add(50,'x+y+z=0과x+2y+3z=1이 이루는 작은 각의 코사인을 구하라.','Find the cosine of the smaller angle between x+y+z=0 and x+2y+3z=1.',[m(r'\cos\theta=\frac{|n_1\cdot n_2|}{|n_1||n_2|}=\frac6{\sqrt3\sqrt{14}}')],[m(r'\cos\theta=\frac{|n_1\cdot n_2|}{|n_1||n_2|}=\frac6{\sqrt3\sqrt{14}}')],m(r'\sqrt{6/7}'))
for n,nn,c,mm,d in [(51,(1,4,-3),1,(-3,6,7),0),(52,(9,-3,6),2,(6,-2,4),0),(53,(1,2,-1),2,(2,-2,1),1),(54,(1,-1,3),1,(3,1,-1),2),(55,(2,-3,-1),0,(4,-6,-2),3),(56,(5,2,3),2,(4,-1,-6),0)]:
 a,bb=M(nn),M(mm);dot=a.dot(bb);co=abs(dot)/(a.norm()*bb.norm());steps=[m(r'n_1\cdot n_2='+tex(dot)+r',\quad n_1\times n_2='+v(a.cross(bb)))]
 if a.cross(bb)==M([0,0,0]):ans='평행.';ae='Parallel.'
 elif dot==0:ans='수직.';ae='Perpendicular.'
 else:
  angle=math.degrees(math.acos(float(co)));ans=ae=m(r'\theta=\cos^{-1}('+tex(co)+rf')\approx{angle:.1f}^\circ');steps.append(m(r'\cos\theta=\frac{|n_1\cdot n_2|}{|n_1||n_2|}'))
 add(n,m(tex(a.dot(X))+'='+str(c))+', '+m(tex(bb.dot(X))+'='+str(d))+'가 평행인지 수직인지 판별하고 둘 다 아니면 각을0.1°까지 구하라.','Classify '+m(tex(a.dot(X))+'='+str(c))+' and '+m(tex(bb.dot(X))+'='+str(d))+' as parallel, perpendicular, or neither; in the last case find the angle to0.1°.',steps,steps,ans,ae)
for n,nn,c,mm,d in [(57,(1,1,1),1,(1,2,2),1),(58,(3,-2,1),1,(2,1,-3),3),(59,(5,-2,-2),1,(4,1,1),6),(60,(2,-1,-1),5,(4,3,-1),5)]:
 a,bb=M(nn),M(mm);direction=a.cross(bb);sol=S.linsolve([a.dot(X)-c,bb.dot(X)-d],(x,y,z));general=M(list(sol)[0]);p=general.subs({x:0,y:0,z:0});eq(f'{n} plane1 identity',a.dot(p+t*direction),c);eq(f'{n} plane2 identity',bb.dot(p+t*direction),d)
 steps=[m(r'd=n_1\times n_2='+v(direction)),m('P='+v(p))];ans=m(par(p,direction)if n<59 else sym(p,direction))
 if n<59:
  co=abs(a.dot(bb))/(a.norm()*bb.norm());ang=math.degrees(math.acos(float(co)));steps.append(m(r'\cos\theta='+tex(co)));ans+='; '+m(rf'\theta\approx{ang:.1f}^\circ')
 add(n,'두 평면 '+m(tex(a.dot(X))+'='+str(c))+', '+m(tex(bb.dot(X))+'='+str(d))+'의 교선의 '+('매개식과 평면 사이 각'if n<59 else'대칭식')+'을 구하라.','For '+m(tex(a.dot(X))+'='+str(c))+' and '+m(tex(bb.dot(X))+'='+str(d))+', find '+('parametric equations of their intersection and the plane angle'if n<59 else'symmetric equations of their intersection')+'.',steps,steps,ans,parts=list('ab')if n<59 else[])
for n,aa,bb in [(61,(1,0,-2),(3,4,0)),(62,(2,5,5),(-6,3,1))]:
 p,q=M(aa),M(bb);normal=q-p;mid=(p+q)/2;eq(f'{n} squared distance identity',(X-p).dot(X-p)-(X-q).dot(X-q),2*normal.dot(X-mid));add(n,'두 점 '+m(v(p)+r',\ '+v(q))+'에서 거리가 같은 점들의 평면을 구하라.','Find the plane of points equidistant from '+m(v(p)+r',\ '+v(q))+'.',[m(r'|X-P|^2=|X-Q|^2\Rightarrow2(Q-P)\cdot X=|Q|^2-|P|^2'),m('M='+v(mid)+r',\ n='+v(normal))],[m(r'|X-P|^2=|X-Q|^2\Rightarrow2(Q-P)\cdot X=|Q|^2-|P|^2'),m('M='+v(mid)+r',\ n='+v(normal))],m(plane(normal,mid)))
add(63,'x,y,z절편이 각각 a,b,c인 평면의 방정식을 구하라.','Find the plane with x,y,z intercepts a,b,c.',[m(r'\frac xa+\frac yb+\frac zc=1'),'a,b,c는0이 아닌 유한 절편이라고 가정한다. 세 절편점을 대입하면 각각1=1이다.'],[m(r'\frac xa+\frac yb+\frac zc=1'),'Assume finite nonzero intercepts. Substituting each of the three intercept points gives1=1.'],m(r'\frac xa+\frac yb+\frac zc=1'))
add(64,'직선 r=(1,1,0)+t(1,−1,2), r=(2,0,2)+s(−1,1,0)의(a)교점과(b)두 직선을 포함하는 평면을 구하라.','For r=(1,1,0)+t(1,−1,2) and r=(2,0,2)+s(−1,1,0), find(a)the intersection and(b)the containing plane.',[m(r'2t=2\Rightarrow t=1,\quad s=0'),m(r'n=\langle1,-1,2\rangle\times\langle-1,1,0\rangle=\langle-2,-2,0\rangle')],[m(r'2t=2\Rightarrow t=1,\quad s=0'),m(r'n=\langle1,-1,2\rangle\times\langle-1,1,0\rangle=\langle-2,-2,0\rangle')],m(r'(a)\ (2,0,2);\quad(b)\ x+y=2'),parts=list('ab'))
add(65,'(0,1,2)를 지나고 x+y+z=2에 평행하며 직선(1,1,0)+t(1,−1,2)과 수직 방향인 직선의 매개식을 구하라.','Find parametric equations through (0,1,2), parallel to x+y+z=2 and with direction perpendicular to (1,1,0)+t(1,−1,2).',[m(r'd=\langle1,1,1\rangle\times\langle1,-1,2\rangle=\langle3,-1,-2\rangle'),'두 방향벡터의 수직을 뜻하며 주어진 직선과의 교차는 별도 조건이 아니다.'],[m(r'd=\langle1,1,1\rangle\times\langle1,-1,2\rangle=\langle3,-1,-2\rangle'),'Perpendicular here refers to direction vectors; intersection is not an additional condition.'],m(r'x=3t,\quad y=1-t,\quad z=2-2t'))
p=M([0,1,2]);q=M([1,1,0]);d=M([1,-1,2]);val=(p-q).dot(d)/d.dot(d);foot=q+val*d;direction=foot-p;eq('66 perpendicular foot',direction.dot(d))
add(66,'(0,1,2)를 지나며 직선(1,1,0)+t(1,−1,2)에 수직으로 교차하는 직선의 매개식을 구하라.','Find a line through (0,1,2) that intersects (1,1,0)+t(1,−1,2) at a right angle.',[m(r'Q(t)=\langle1+t,1-t,2t\rangle,\quad(Q(t)-P)\cdot\langle1,-1,2\rangle=6t-3'),m(r't=1/2,\quad Q=(3/2,1/2,1)')],[m(r'Q(t)=\langle1+t,1-t,2t\rangle,\quad(Q(t)-P)\cdot\langle1,-1,2\rangle=6t-3'),m(r't=1/2,\quad Q=(3/2,1/2,1)')],m(r'x=3u,\quad y=1-u,\quad z=2-2u'))
add(67,'P₁:3x+6y−3z=6, P₂:4x−12y+8z=5, P₃:9y=1+3x+6z, P₄:z=x+2y−2 중 평행하거나 같은 평면을 찾으라.','Identify parallel or identical planes among P₁:3x+6y−3z=6, P₂:4x−12y+8z=5, P₃:9y=1+3x+6z, P₄:z=x+2y−2.',[m(r'P_1,P_4:\ x+2y-z=2'),m(r'P_2:\ x-3y+2z=5/4,\quad P_3:\ x-3y+2z=-1/3')],[m(r'P_1,P_4:\ x+2y-z=2'),m(r'P_2:\ x-3y+2z=5/4,\quad P_3:\ x-3y+2z=-1/3')],'P₁=P₄. P₂와P₃는 서로 다른 평행면. 두 쌍 사이에는 평행 관계가 없다.','P₁=P₄. P₂ andP₃ are distinct parallel planes. No plane in one pair is parallel to a plane in the other.')
add(68,'L₁=(1,1,5)+t(6,−3,12), L₂=(1,0,1)+t(2,1,4), L₃:2x−2=4−4y=z+1, L₄=(3,1,5)+t(4,2,8) 중 평행하거나 같은 직선을 찾으라.','Identify parallel or identical lines among L₁=(1,1,5)+t(6,−3,12), L₂=(1,0,1)+t(2,1,4), L₃:2x−2=4−4y=z+1, L₄=(3,1,5)+t(4,2,8).',[m(r'd_1=6\langle1,-1/2,2\rangle,\quad d_3=\langle1/2,-1/4,1\rangle'),'L₃의 점(1,1,−1)은L₁ 위에 있지 않으므로 서로 다른 평행선이다.',m(r'd_4=2d_2,\quad(3,1,5)=(1,0,1)+(2,1,4)')],[m(r'd_1=6\langle1,-1/2,2\rangle,\quad d_3=\langle1/2,-1/4,1\rangle'),'The point(1,1,−1)onL₃ is not onL₁, so they are distinct parallel lines.',m(r'd_4=2d_2,\quad(3,1,5)=(1,0,1)+(2,1,4)')],'L₁∥L₃는 서로 다르고 L₂=L₄이다.','L₁∥L₃ are distinct; L₂=L₄.')
for n,pp,qq,dd in [(69,(4,1,-2),(1,3,4),(1,-2,-3)),(70,(0,1,3),(0,6,3),(2,-2,1))]:
 p,q,d=map(M,[pp,qq,dd]);cross=(p-q).cross(d);dist=S.simplify(cross.norm()/d.norm());foot=q+(p-q).dot(d)/d.dot(d)*d;eq(f'{n} projection distance',dist**2,(p-foot).dot(p-foot));add(n,'점 '+m(v(p))+'과 직선 '+m(line(q,d))+' 사이 거리를 외적 공식으로 구하라.','Use the cross-product formula for the distance from '+m(v(p))+' to '+m(line(q,d))+'.',[m(r'(P-Q)\times d='+v(cross)),m(r'D=\frac{|(P-Q)\times d|}{|d|}')],[m(r'(P-Q)\times d='+v(cross)),m(r'D=\frac{|(P-Q)\times d|}{|d|}')],m('D='+tex(dist)))
for n,pp,nn,c in [(71,(1,-2,4),(3,2,6),5),(72,(-6,3,5),(1,-2,-4),8)]:
 p,normal=M(pp),M(nn);num=normal.dot(p)-c;dist=abs(num)/normal.norm();add(n,'점 '+m(v(p))+'과 평면 '+m(tex(normal.dot(X))+'='+str(c))+'의 거리를 구하라.','Find the distance from '+m(v(p))+' to '+m(tex(normal.dot(X))+'='+str(c))+'.',[m(r'D=\frac{|n\cdot P-c|}{|n|}=\frac{|'+tex(num)+'|}{'+tex(normal.norm())+'}')],[m(r'D=\frac{|n\cdot P-c|}{|n|}=\frac{|'+tex(num)+'|}{'+tex(normal.norm())+'}')],m('D='+tex(dist)))
add(73,'2x−3y+z=4와4x−6y+2z=3의 거리를 구하라.','Find the distance between 2x−3y+z=4 and 4x−6y+2z=3.',[m(r'2x-3y+z=4,\quad2x-3y+z=3/2'),m(r'D=\frac{|4-3/2|}{\sqrt{4+9+1}}')],[m(r'2x-3y+z=4,\quad2x-3y+z=3/2'),m(r'D=\frac{|4-3/2|}{\sqrt{4+9+1}}')],m(r'\frac5{2\sqrt{14}}'))
add(74,'6z=4y−2x와9z=1−3x+6y의 거리를 구하라.','Find the distance between 6z=4y−2x and 9z=1−3x+6y.',[m(r'x-2y+3z=0,\quad x-2y+3z=1/3'),m(r'D=\frac{1/3}{\sqrt{1+4+9}}')],[m(r'x-2y+3z=0,\quad x-2y+3z=1/3'),m(r'D=\frac{1/3}{\sqrt{1+4+9}}')],m(r'\frac1{3\sqrt{14}}'))
add(75,'평행면 ax+by+cz+d₁=0와ax+by+cz+d₂=0 사이 거리 공식을 증명하라.','Prove the distance formula for parallel planes ax+by+cz+d₁=0 and ax+by+cz+d₂=0.',[m(r'n=\langle a,b,c\rangle\ne0,\quad n\cdot P=-d_1'),m(r'D=\frac{|n\cdot P+d_2|}{|n|}=\frac{|d_2-d_1|}{\sqrt{a^2+b^2+c^2}}')],[m(r'n=\langle a,b,c\rangle\ne0,\quad n\cdot P=-d_1'),m(r'D=\frac{|n\cdot P+d_2|}{|n|}=\frac{|d_2-d_1|}{\sqrt{a^2+b^2+c^2}}')],m(r'D=\frac{|d_2-d_1|}{\sqrt{a^2+b^2+c^2}}'))
add(76,'x+2y−2z=1에서 거리2만큼 떨어진 평행면들을 구하라.','Find the parallel planes two units from x+2y−2z=1.',[m(r'x+2y-2z=c,\quad \frac{|c-1|}{3}=2\Rightarrow c=1\pm6')],[m(r'x+2y-2z=c,\quad \frac{|c-1|}{3}=2\Rightarrow c=1\pm6')],m(r'x+2y-2z=7,\quad x+2y-2z=-5'))
for n,pp,dd,qq,ee in [(77,(0,0,0),(1,1,1),(-1,0,0),(1,2,3)),(78,(1,1,0),(1,6,2),(1,5,-2),(2,15,6)),(79,(0,0,0),(2,0,-1),(1,-1,1),(3,2,2))]:
 p,d,q,e=map(M,[pp,dd,qq,ee]);cross=d.cross(e);num=(q-p).dot(cross);dist=S.simplify(abs(num)/cross.norm());assert num!=0;checks.append(f'{n} nonzero triple product proves skew');sol=S.solve([(p+t*d-q-u*e).dot(d),(p+t*d-q-u*e).dot(e)],(t,u));gap=(p+t*d-q-u*e).subs(sol);eq(f'{n} closest point distance',gap.dot(gap),dist**2)
 add(n,'直線 '.replace('直線','직선')+m(line(p,d))+', '+m(line(q,e).replace('t','u'))+'의 거리를 구하라.'+(' 꼬인 위치임도 보여라.'if n==77 else''),'Find the distance between '+m(line(p,d))+' and '+m(line(q,e).replace('t','u'))+'.'+(' Also prove they are skew.'if n==77 else''),[m(r'd_1\times d_2='+v(cross)),m(r'(Q-P)\cdot(d_1\times d_2)='+tex(num)+r'\ne0'),m(r'D=\frac{|(Q-P)\cdot(d_1\times d_2)|}{|d_1\times d_2|}')],[m(r'd_1\times d_2='+v(cross)),m(r'(Q-P)\cdot(d_1\times d_2)='+tex(num)+r'\ne0'),m(r'D=\frac{|(Q-P)\cdot(d_1\times d_2)|}{|d_1\times d_2|}')],m('D='+tex(dist)))
p=M([1,2,6]);d=M([1,2,2]);a=M([3,2,-1]);bb=M([0,0,1]);cc=M([1,2,1]);normal=(bb-a).cross(cc-a);n1=M([1,-1,2]);e=n1.cross(normal);general=M(list(S.linsolve([n1.dot(X)+1,normal.dot(X-a)],(x,y,z)))[0]);q=general.subs({x:0,y:0,z:0});cross=d.cross(e);dist=S.simplify(abs((q-p).dot(cross))/cross.norm());eq('80 P2 points',M([normal.dot(bb-a),normal.dot(cc-a)]),M([0,0]));eq('80 intersection line',M([n1.dot(q+t*e)+1,normal.dot(q+t*e-a)]),M([0,0]));sol=S.solve([(p+t*d-q-u*e).dot(d),(p+t*d-q-u*e).dot(e)],(t,u));gap=(p+t*d-q-u*e).subs(sol);eq('80 nearest points',gap.dot(gap),dist**2)
add(80,'L₁은(1,2,6),(2,4,8)을 지난다. L₂는x−y+2z+1=0과 세 점(3,2,−1),(0,0,1),(1,2,1)의 평면의 교선이다. 두 직선 사이 거리를 구하라.','L₁ passes through(1,2,6),(2,4,8). L₂ is the intersection of x−y+2z+1=0 with the plane through(3,2,−1),(0,0,1),(1,2,1). Find their distance.',[m('P_2:'+plane(normal,a)),m('L_1:'+line(p,d)),m('L_2:'+line(q,e)),m(r'D=\frac{|(Q-P)\cdot(d_1\times d_2)|}{|d_1\times d_2|}')],[m('P_2:'+plane(normal,a)),m('L_1:'+line(p,d)),m('L_2:'+line(q,e)),m(r'D=\frac{|(Q-P)\cdot(d_1\times d_2)|}{|d_1\times d_2|}')],m('D='+tex(dist)))
add(81,'모의훈련의 두 탱크 위치는 A=(325,810,561),B=(765,675,599)이다. (a)시선의 매개식을 구하라. (b)A에서B까지5등분한 네 중간지점 지형 높이가549,566,586,589이면 서로 보이는가?','In a simulation tanks are at A=(325,810,561),B=(765,675,599). (a)Parametrize their sight line. (b)The terrain elevations at the four fifth-division points are549,566,586,589; can they see each other?',[m(r'r=\langle325,810,561\rangle+t\langle440,-135,38\rangle,\quad0\le t\le1'),m(r'z(1/5),z(2/5),z(3/5),z(4/5)=568.6,576.2,583.8,591.4'),'세 번째 지형586은 시선583.8보다2.2높다. 따라서 시선이 가려진다.'],[m(r'r=\langle325,810,561\rangle+t\langle440,-135,38\rangle,\quad0\le t\le1'),m(r'z(1/5),z(2/5),z(3/5),z(4/5)=568.6,576.2,583.8,591.4'),'At the third intermediate point the terrain586 is2.2 above the sight line583.8, so it blocks visibility.'],'(a)x=325+440t,y=810−135t,z=561+38t,0≤t≤1. (b)보이지 않는다.','(a)x=325+440t,y=810−135t,z=561+38t,0≤t≤1. (b)They cannot see each other.',list('ab'))
add(82,'평면족(a)x+y+z=c,(b)x+y+cz=1,(c)y cosθ+z sinθ=1의 기하적 모양을 설명하라.','Describe the families(a)x+y+z=c,(b)x+y+cz=1,(c)y cosθ+z sinθ=1.', ['(a)법선(1,1,1)을 공유하는 모든 평행면이며 원점에서 거리는|c|/√3이다.','(b)z=0,x+y=1인 공통 직선을 축으로 회전하는 평면들이다. 유한c로는z=0자체를 포함하지 않는다.','(c)x축과 평행하며 원점에서 거리1인 평면들이다. yz단면은 단위원 y²+z²=1의 접선이므로 전체는 원기둥 y²+z²=1의 접평면들이다.'],['(a)All parallel planes with normal(1,1,1), at distance|c|/√3 from the origin.','(b)Planes rotating about the common line z=0,x+y=1; finite c does not include z=0 itself.','(c)Planes parallel to the x-axis at distance1 from the origin. Their yz traces are tangents to y²+z²=1, so they are the tangent planes of that circular cylinder.'],'(a)평행면족 (b)공통 직선을 지나는 평면족 (c)x축 중심 반지름1 원기둥의 접평면족.','(a)Parallel planes (b)Planes through a fixed line (c)Tangent planes to the unit cylinder about the x-axis.',list('abc'))
add(83,'a,b,c가 모두0은 아닐 때 ax+by+cz+d=0이 법선(a,b,c)을 갖는 평면임을 증명하라.','Prove that ax+by+cz+d=0 represents a plane with normal(a,b,c) when not all a,b,c vanish.',[m(r'n=\langle a,b,c\rangle\ne0'),'a≠0이면 P=(−d/a,0,0)을 선택한다. 다른 계수만0이 아니면 그 좌표를 같은 방법으로 고른다.',m(r'ax+by+cz+d=n\cdot(X-P)=0'),'이는 P를 지나고0이 아닌n에 수직인 모든 점의 집합이므로 평면의 점·법선식이다.'],[m(r'n=\langle a,b,c\rangle\ne0'),'If a≠0 choose P=(−d/a,0,0); otherwise use a nonzero b or c in the same way.',m(r'ax+by+cz+d=n\cdot(X-P)=0'),'This is the point-normal equation for all points through P perpendicular to the nonzero vector n.'],m(r'n=\langle a,b,c\rangle')+'가 법선인 평면.',m(r'n=\langle a,b,c\rangle')+' is its normal.')
assert sorted(b.E)==list(range(1,84));b.save()
(Path(__file__).parent/'s12-5-report.json').write_text(json.dumps({'section':'12.5','sourceVisualPdfPages':[947,948,949],'passed':len(checks),'independentChecks':checks},indent=2)+'\n')
print('83 exercises;',len(checks),'checks')
