"""Worked differentiation/integration solutions with exact checks."""
from early_helpers import Book
from pathlib import Path
import sympy as s,json,math
b=Book('13.2',[940,941,942]);t=s.symbols('t',real=True);M=s.Matrix;R=s.Rational;checks=[]
def tex(x):return s.latex(s.simplify(x))
def v(a):return r'\langle'+','.join(tex(x)for x in a)+r'\rangle'
def m(x):return r'\('+x+r'\)'
def eq(label,a,c=0):
 q=a-c;assert all(s.simplify(x)==0 for x in q)if isinstance(q,s.MatrixBase)else s.simplify(q)==0,(label,a,c)
 checks.append(label)
def add(n,k,e,ks,es,ans,ae=None,parts=[]):
 b.add(n,940 if n<=16 else 941 if n<=55 else 942,('벡터함수의 미분과 적분','Derivatives and integrals of vector functions'),(k,e),list(zip(ks,es)),(ans,ans if ae is None else ae),parts,check=('성분별 미분·대입과 원래 조건을 비교하거나 사용한 항등식을 전개하여 확인했다.','Checked by component differentiation/substitution against the original conditions or expansion of the stated identity.'));b.E[n]['conceptHref']='../../calc1/index.html'
add(1,'그림의 P=r(4),Q=r(4.2),R=r(4.5)에 대해(a)두 변위,(b)각 변위를0.2와0.5로 나눈 벡터를 그려라. (c)r′(4),T(4)를 극한으로 표현하고(d)T(4)를 그려라.','The figure marks P=r(4),Q=r(4.2),R=r(4.5). (a)Draw the displacements. (b)Draw each divided by0.2 or0.5. (c)Express r′(4),T(4)by limits and(d)draw T(4).',['(a)변위는 P에서Q로, P에서R로 향한다. (b)PQ를5배, PR을2배 하되 시작점은P로 둔다.',m(r"r'(4)=\lim_{h\to0}\frac{r(4+h)-r(4)}h,\quad T(4)=\frac{r'(4)}{|r'(4)|}"),'(d)P에서 t가 증가하는 쪽(Q,R쪽)으로 향하는 접선 위의 길이1벡터를 그린다. 수치 성분은 이 개형만으로 정확히 정할 수 없다.'],['(a)The displacements run from P to Q and P to R. (b)Draw5PQ and2PR with tail at P.',m(r"r'(4)=\lim_{h\to0}\frac{r(4+h)-r(4)}h,\quad T(4)=\frac{r'(4)}{|r'(4)|}"),'(d)Draw a unit vector tangent at P toward increasing t, toward Q and R. The schematic does not determine exact numerical components.'],m(r'\overrightarrow{PQ},\ \overrightarrow{PR};\quad5\overrightarrow{PQ},\ 2\overrightarrow{PR}')+'; T(4)는 진행 방향 단위접선.',m(r'\overrightarrow{PQ},\ \overrightarrow{PR};\quad5\overrightarrow{PQ},\ 2\overrightarrow{PR}')+'; T(4)is the forward unit tangent.',list('abcd'))
add(2,m(r'r(t)=\langle t^2,t\rangle,\quad0\le t\le2')+'를 그리고(a)r(1),r(1.1),두 점의 변위,(b)r′(1)과 전진 차분몫을 비교하라.','Sketch '+m(r'r(t)=\langle t^2,t\rangle,\quad0\le t\le2')+' and(a)r(1),r(1.1),their displacement;(b)compare r′(1)with the forward difference quotient.',[m(r'r(1)=\langle1,1\rangle,\quad r(1.1)=\langle1.21,1.1\rangle'),m(r'r(1.1)-r(1)=\langle0.21,0.1\rangle'),m(r"r'(1)=\langle2,1\rangle,\quad\frac{r(1.1)-r(1)}{0.1}=\langle2.1,1\rangle"),'일반 전진차분은(2+h,1)이므로 오차벡터는(h,0)이다. h=0.1이면 길이0.1만큼만 달라 방향과 길이가 가깝다.'],[m(r'r(1)=\langle1,1\rangle,\quad r(1.1)=\langle1.21,1.1\rangle'),m(r'r(1.1)-r(1)=\langle0.21,0.1\rangle'),m(r"r'(1)=\langle2,1\rangle,\quad\frac{r(1.1)-r(1)}{0.1}=\langle2.1,1\rangle"),'The general forward quotient is(2+h,1), so its error is(h,0). For h=0.1 the error length is only0.1, making the directions and magnitudes close.'],m(r"r'(1)=\langle2,1\rangle,\quad\text{secant quotient}=\langle2.1,1\rangle"),parts=list('ab'))
plane_rows=[(3,[t-2,t*t+1],-1,r'y=(x+2)^2+1'),(4,[t*t,t**3],1,r'y^2=x^3,\quad x\ge0'),(5,[s.exp(2*t),s.exp(t)],0,r'x=y^2,\quad y>0'),(6,[s.exp(t),2*t],0,r'y=2\ln x,\quad x>0'),(7,[4*s.sin(t),-2*s.cos(t)],3*s.pi/4,r'x^2/16+y^2/4=1'),(8,[s.cos(t)+1,s.sin(t)-1],-s.pi/3,r'(x-1)^2+(y+1)^2=1')]
for n,ff,at,curve in plane_rows:
 r=M(ff);d=r.diff(t);p=r.subs(t,at);tan=d.subs(t,at)
 add(n,m('r(t)='+v(r))+', '+m('t_0='+tex(at))+'에 대해(a)곡선,(b)도함수,(c)위치벡터와 접선벡터를 구하고 그려라.','For '+m('r(t)='+v(r))+', '+m('t_0='+tex(at))+', (a)sketch the curve,(b)find its derivative,(c)draw the position and tangent vectors.',[m(curve),m("r'(t)="+v(d)),'위치벡터는 원점에서P로, 접선벡터는P에서P+r′(t₀)로 그린다.'],[m(curve),m("r'(t)="+v(d)),'Draw the position vector from the origin to P, and the tangent from P to P+r′(t₀).'],m("r'(t)="+v(d))+ '; '+m('P='+v(p)+r',\quad D='+v(tan)),parts=list('abc'))
a,bb,c=s.symbols('a b c',real=True)
for n,ff in [(9,[s.sqrt(t-2),3,t**-2]),(10,[s.exp(-t),t-t**3,s.log(t)]),(11,[t*t,s.cos(t*t),s.sin(t)**2]),(12,[1/(1+t),t/(1+t),t*t/(1+t)]),(13,[t*s.sin(t),s.exp(t)*s.cos(t),s.sin(t)*s.cos(t)]),(14,[s.sin(a*t)**2,t*s.exp(bb*t),s.cos(c*t)**2])]:
 r=M(ff);d=s.simplify(r.diff(t));domain='t>2'if n==9 else't>0'if n==10 else't≠−1'if n==12 else'실수 t';de='t>2'if n==9 else't>0'if n==10 else't≠−1'if n==12 else'real t'
 add(n,m('r(t)='+v(r))+'를 미분하라.','Differentiate '+m('r(t)='+v(r))+'.',['각 성분에 거듭제곱·곱·몫·연쇄법칙을 적용한다.','도함수의 실수 정의구간: '+domain+'.'],['Apply power, product, quotient, and chain rules componentwise.','Real derivative domain: '+de+'.'],m("r'(t)="+v(d)))
add(15,'상수벡터 a,b,c에 대해 r(t)=a+tb+t²c를 미분하라.','Differentiate r(t)=a+tb+t²c for constant vectors a,b,c.', ['상수벡터는 미분하면0이며 스칼라 계수만 미분한다.'],['Constant vectors differentiate to zero; differentiate their scalar coefficients.'],m("r'(t)=b+2tc"))
add(16,'상수벡터 a,b,c에 대해 r(t)=ta×(b+tc)를 미분하라.','Differentiate r(t)=ta×(b+tc) for constant vectors a,b,c.',[m(r'r(t)=t(a\times b)+t^2(a\times c)')],[m(r'r(t)=t(a\times b)+t^2(a\times c)')],m(r"r'(t)=a\times b+2t(a\times c)"))
unitrows=[(17,[t*t-2*t,1+3*t,t**3/3+t*t/2],2),(18,[s.atan(t),2*s.exp(2*t),8*t*s.exp(t)],0),(19,[s.cos(t),3*t,2*s.sin(2*t)],0),(20,[s.sin(t)**2,s.cos(t)**2,s.tan(t)**2],s.pi/4),(21,[t**3+1,3*t-5,4/t],1),(22,[s.sin(t),5*t,s.cos(t)],0)]
for n,ff,at in unitrows:
 r=M(ff);d=s.simplify(r.diff(t));atd=s.simplify(d.subs(t,at));unit=s.simplify(atd/atd.norm());eq(f'{n} unit length',unit.dot(unit),1);p=r.subs(t,at)
 add(n,m('r(t)='+v(r))+'에서 '+(m('t='+tex(at))if n<21 else'점'+m(v(p)))+'의 단위접선벡터를 구하라.','Find the unit tangent for '+m('r(t)='+v(r))+' at '+(m('t='+tex(at))if n<21 else'the point '+m(v(p)))+'.',[m('t_0='+tex(at)),m("r'(t_0)="+v(atd)+r',\quad|r^{\prime}(t_0)|='+tex(atd.norm()))],[m('t_0='+tex(at)),m("r'(t_0)="+v(atd)+r',\quad|r^{\prime}(t_0)|='+tex(atd.norm()))],m('T='+v(unit)))
for n,ff,at in [(23,[t**4,t,t*t],1),(24,[s.exp(2*t),s.exp(-3*t),t],0)]:
 r=M(ff);d=r.diff(t);dd=d.diff(t);cross=d.cross(dd);atd=d.subs(t,at);unit=atd/atd.norm();eq(f'{n} cross perpendicular first',cross.dot(d));eq(f'{n} cross perpendicular second',cross.dot(dd));exprd=d if n==23 else atd;exprdd=dd if n==23 else dd.subs(t,at);exprcross=cross if n==23 else cross.subs(t,at)
 add(n,m('r(t)='+v(r))+'에 대해 '+('r′(t),T(1),r″(t),r′(t)×r″(t)'if n==23 else'r′(0),T(0),r″(0),r′(0)×r″(0)')+'를 구하라.','For '+m('r(t)='+v(r))+' find '+('r′(t),T(1),r″(t),r′(t)×r″(t)'if n==23 else'r′(0),T(0),r″(0),r′(0)×r″(0)')+'.',[m("r'(t)="+v(d)),m("r''(t)="+v(dd)),m(r'T(t_0)=r^{\prime}(t_0)/|r^{\prime}(t_0)|')],[m("r'(t)="+v(d)),m("r''(t)="+v(dd)),m(r'T(t_0)=r^{\prime}(t_0)/|r^{\prime}(t_0)|')],m(r'r^{\prime}='+v(exprd)+r',\quad T='+v(unit))+ '; '+m(r'r^{\prime\prime}='+v(exprdd)+r',\quad r^{\prime}\times r^{\prime\prime}='+v(exprcross)))
tangentrows=[(25,[t*t+1,4*s.sqrt(t),s.exp(t*t-t)],1),(26,[s.log(t+1),t*s.cos(2*t),2**t],0),(27,[s.exp(-t)*s.cos(t),s.exp(-t)*s.sin(t),s.exp(-t)],0),(28,[s.sqrt(t*t+3),s.log(t*t+3),t],1),(31,[t,s.exp(-t),2*t-t*t],0),(32,[2*s.cos(t),2*s.sin(t),4*s.cos(2*t)],s.pi/6),(33,[t*s.cos(t),t,t*s.sin(t)],s.pi)]
for n,ff,at in tangentrows:
 r=M(ff);p=s.simplify(r.subs(t,at));d=s.simplify(r.diff(t).subs(t,at));ans=m(r',\quad '.join(a+'='+tex(p[i]+s.Symbol('u')*d[i])for i,a in enumerate(['x','y','z'])))
 add(n,m('r(t)='+v(r))+'의 점 '+m(v(p))+'에서 접선 매개식을 구하라.'+(' 곡선과 접선을 같은 그림에 나타내라.'if n>=31 else''),'Find tangent-line parametric equations for '+m('r(t)='+v(r))+' at '+m(v(p))+'.'+(' Plot curve and tangent together.'if n>=31 else''),[m('t_0='+tex(at)+r',\quad r^{\prime}(t_0)='+v(d)),m('L(u)='+v(p)+'+u'+v(d))],[m('t_0='+tex(at)+r',\quad r^{\prime}(t_0)='+v(d)),m('L(u)='+v(p)+'+u'+v(d))],ans)
n1=M([6,8,0]);n2=M([0,8,4]);d=n1.cross(n2);eq('29 tangent first cylinder',n1.dot(d));eq('29 tangent second cylinder',n2.dot(d))
add(29,'원기둥x²+y²=25와y²+z²=20의 교선에서(3,4,2)의 접선 벡터식을 구하라.','Find a vector equation of the tangent at(3,4,2)to the intersection of x²+y²=25 and y²+z²=20.',[m(r'n_1=\langle6,8,0\rangle,\quad n_2=\langle0,8,4\rangle'),m(r'n_1\times n_2=8\langle4,-3,6\rangle')],[m(r'n_1=\langle6,8,0\rangle,\quad n_2=\langle0,8,4\rangle'),m(r'n_1\times n_2=8\langle4,-3,6\rangle')],m(r'L(u)=\langle3,4,2\rangle+u\langle4,-3,6\rangle'))
add(30,m(r'r(t)=\langle2\cos t,2\sin t,e^t\rangle,\quad0\le t\le\pi')+'에서 접선이 평면√3x+y=1에 평행한 점을 구하라.','Find the point on '+m(r'r(t)=\langle2\cos t,2\sin t,e^t\rangle,\quad0\le t\le\pi')+' whose tangent is parallel to √3x+y=1.',[m(r'\langle-2\sin t,2\cos t,e^t\rangle\cdot\langle\sqrt3,1,0\rangle=0'),m(r'\cos t=\sqrt3\sin t\Rightarrow t=\pi/6')],[m(r'\langle-2\sin t,2\cos t,e^t\rangle\cdot\langle\sqrt3,1,0\rangle=0'),m(r'\cos t=\sqrt3\sin t\Rightarrow t=\pi/6')],m(r'(\sqrt3,1,e^{\pi/6})'))
add(34,m(r'r(t)=\langle\sin\pi t,2\sin\pi t,\cos\pi t\rangle')+'의 t=0,1/2에서 두 접선의(a)교점을 구하고(b)곡선과 접선들을 함께 그려라.','For '+m(r'r(t)=\langle\sin\pi t,2\sin\pi t,\cos\pi t\rangle')+' at t=0,1/2, (a)find the tangent-line intersection and(b)plot both tangents with the curve.',[m(r'L_0(u)=\langle0,0,1\rangle+u\langle1,2,0\rangle'),m(r'L_{1/2}(v)=\langle1,2,0\rangle+v\langle0,0,1\rangle'),m(r'u=1,\quad v=1')],[m(r'L_0(u)=\langle0,0,1\rangle+u\langle1,2,0\rangle'),m(r'L_{1/2}(v)=\langle1,2,0\rangle+v\langle0,0,1\rangle'),m(r'u=1,\quad v=1')],m('(1,2,1)'),parts=list('ab'))
a=M([1,0,0]);bb=M([1,2,1]);angle=math.degrees(math.acos(float(a.dot(bb)/(a.norm()*bb.norm()))))
add(35,'r₁(t)=(t,t²,t³),r₂(s)=(sin s,sin2s,s)는 원점에서 만난다. 교각을1°단위로 구하라.','r₁(t)=(t,t²,t³)and r₂(s)=(sin s,sin2s,s)meet at the origin. Find their angle to the nearest degree.',[m(r'r_1^{\prime}(0)=\langle1,0,0\rangle,\quad r_2^{\prime}(0)=\langle1,2,1\rangle'),m(r'\cos\theta=1/\sqrt6')],[m(r'r_1^{\prime}(0)=\langle1,0,0\rangle,\quad r_2^{\prime}(0)=\langle1,2,1\rangle'),m(r'\cos\theta=1/\sqrt6')],m(rf'\theta\approx{angle:.0f}^\circ'))
u=s.symbols('u',real=True);r1=M([t,1-t,3+t*t]);r2=M([3-u,u-2,u*u]);sol=s.solve(r1-r2,(t,u),dict=True);assert len(sol)==1;tv,uv=sol[0][t],sol[0][u];p=r1.subs(t,tv);a=r1.diff(t).subs(t,tv);bb=r2.diff(u).subs(u,uv);co=abs(a.dot(bb))/(a.norm()*bb.norm());ang=math.degrees(math.acos(float(co)));eq('36 intersection',p,r2.subs(u,uv))
add(36,'r₁(t)=(t,1−t,3+t²)와r₂(s)=(3−s,s−2,s²)의 교점과 교각(1°단위)을 구하라.','Find the intersection and nearest-degree angle of r₁(t)=(t,1−t,3+t²)and r₂(s)=(3−s,s−2,s²).',[m('t='+tex(tv)+r',\quad s='+tex(uv)),m(r'r_1^{\prime}='+v(a)+r',\quad r_2^{\prime}='+v(bb)),m(r'\cos\theta='+tex(co))],[m('t='+tex(tv)+r',\quad s='+tex(uv)),m(r'r_1^{\prime}='+v(a)+r',\quad r_2^{\prime}='+v(bb)),m(r'\cos\theta='+tex(co))],m(v(p))+ '; '+m(rf'\theta\approx{ang:.0f}^\circ'))
for n,ff,lo,hi in [(37,[t,-t**3,3*t**5],0,2),(38,[2*t**R(3,2),0,(t+1)*s.sqrt(t)],1,4),(39,[1/(t+1),1/(t*t+1),t/(t*t+1)],0,1),(40,[s.sec(t)*s.tan(t),t*s.cos(2*t),s.sin(2*t)**2*s.cos(2*t)],0,s.pi/4),(41,[1/(1+t*t),t*s.exp(t*t),s.sqrt(t)],None,None),(42,[t*s.cos(t*t),1/t,s.sec(t)**2],None,None)]:
 r=M(ff);anti=r.applyfunc(lambda f:s.integrate(s.expand(f),t));
 if n==38:anti=M([R(4,5)*t**R(5,2),0,R(2,5)*t**R(5,2)+R(2,3)*t**R(3,2)])
 if n==40:anti=M([s.sec(t),t*s.sin(2*t)/2+s.cos(2*t)/4,s.sin(2*t)**3/6])
 if n==42:anti[1]=s.log(s.Abs(t))
 for j in range(3):
  diff=s.diff(anti[j],t)-r[j]
  if n==42 and j==1:diff=diff.subs(t,s.symbols('positive_t',positive=True))
  eq(f'{n} antiderivative{j}',diff)
 result=anti if lo is None else s.simplify(anti.subs(t,hi)-anti.subs(t,lo));op=r'\int'if lo is None else r'\int_{'+tex(lo)+'}^{'+tex(hi)+'}'
 add(n,m(op+v(r)+r'\,dt')+'를 계산하라.','Evaluate '+m(op+v(r)+r'\,dt')+'.',[m('F(t)='+v(anti)),('C는 각 성분마다 독립인 벡터 적분상수이다.'if lo is None else'각 성분의 원시함수에서 위끝값과 아래끝값의 차를 구한다.')],[m('F(t)='+v(anti)),('C is an arbitrary vector constant, with independent components.'if lo is None else'Evaluate each antiderivative at the upper and lower limits and subtract.')],m(v(result)+('+C'if lo is None else'')))
for n,ff,at,pp in [(43,[2*t,3*t*t,s.sqrt(t)],1,[1,1,0]),(44,[t,s.exp(t),t*s.exp(t)],0,[1,1,1])]:
 d=M(ff);p=M(pp);anti=d.applyfunc(lambda f:s.integrate(f,t));constant=p-anti.subs(t,at);r=anti+constant;eq(f'{n} initial value',r.subs(t,at),p);eq(f'{n} differential equation',r.diff(t),d)
 add(n,m(r'r^{\prime}(t)='+v(d))+', '+m('r('+tex(at)+')='+v(p))+'를 만족하는 r(t)를 구하라.','Find r(t)given '+m(r'r^{\prime}(t)='+v(d))+' and '+m('r('+tex(at)+')='+v(p))+'.',[m('r(t)='+v(anti)+'+C'),m('C='+v(constant))],[m('r(t)='+v(anti)+'+C'),m('C='+v(constant))],m('r(t)='+v(r)))
proofrows=[(45,r'(u+v)^{\prime}=u^{\prime}+v^{\prime}',['각 좌표 i에 실수함수의 합 미분법을 적용한다.',m(r'\frac d{dt}(u_i+v_i)=u_i^{\prime}+v_i^{\prime}'),'세 좌표를 모으면 벡터식이다.'],['Apply the scalar sum rule to coordinate i.',m(r'\frac d{dt}(u_i+v_i)=u_i^{\prime}+v_i^{\prime}'),'Assemble the coordinates to obtain the vector identity.']),(46,r'(fu)^{\prime}=f^{\prime} u+fu^{\prime}',[m(r'\frac d{dt}(fu_i)=f^{\prime} u_i+fu_i^{\prime}'),'각 좌표에 스칼라 곱 미분법을 적용하고 벡터로 모은다.'],[m(r'\frac d{dt}(fu_i)=f^{\prime} u_i+fu_i^{\prime}'),'Apply the scalar product rule coordinatewise and assemble the vector.']),(47,r'(u\times v)^{\prime}=u^{\prime}\times v+u\times v^{\prime}',[m(r'\frac d{dt}(u_2v_3-u_3v_2)=u_2^{\prime} v_3+u_2v_3^{\prime}-u_3^{\prime} v_2-u_3v_2^{\prime}'),'u의 미분항과v의 미분항을 모으면 우변의 첫 성분이다. 나머지 성분은 첨자를 순환하여 같은 계산을 한다.'],[m(r'\frac d{dt}(u_2v_3-u_3v_2)=u_2^{\prime} v_3+u_2v_3^{\prime}-u_3^{\prime} v_2-u_3v_2^{\prime}'),'Group derivatives of u and of v to obtain the first right-hand component; cyclically repeat for the others.']),(48,r'\frac d{dt}u(f(t))=f^{\prime}(t)u^{\prime}(f(t))',[m(r'\frac d{dt}u_i(f(t))=u_i^{\prime}(f(t))f^{\prime}(t)'),'각 좌표에 실수 연쇄법칙을 적용했다.'],[m(r'\frac d{dt}u_i(f(t))=u_i^{\prime}(f(t))f^{\prime}(t)'),'This is the scalar chain rule applied coordinatewise.'])]
for n,formula,ks,es in proofrows:add(n,'미분 공식을 증명하라: '+m(formula),'Prove the differentiation rule '+m(formula)+'.',ks,es,m(formula))
u=M([s.sin(t),s.cos(t),t]);vv=M([t,s.cos(t),s.sin(t)])
for n in[49,50]:
 result=s.simplify(u.diff(t).dot(vv)+u.dot(vv.diff(t)))if n==49 else s.simplify(u.diff(t).cross(vv)+u.cross(vv.diff(t)));direct=s.diff(u.dot(vv),t)if n==49 else u.cross(vv).diff(t);eq(f'{n} direct versus product rule',result,direct);op=r'\cdot'if n==49 else r'\times';answer=tex(result)if n==49 else v(result)
 add(n,m('u(t)='+v(u)+r',\quad v(t)='+v(vv))+'에서 '+m(r'\frac d{dt}(u'+op+'v)')+'를 곱 미분법으로 구하라.','Use the product rule to find '+m(r'\frac d{dt}(u'+op+'v)')+' for '+m('u(t)='+v(u)+r',\quad v(t)='+v(vv))+'.',[m(r'u^{\prime}='+v(u.diff(t))+r',\quad v^{\prime}='+v(vv.diff(t))),m(r'\frac d{dt}(u'+op+r'v)=u^{\prime}'+op+'v+u'+op+r'v^{\prime}')],[m(r'u^{\prime}='+v(u.diff(t))+r',\quad v^{\prime}='+v(vv.diff(t))),m(r'\frac d{dt}(u'+op+r'v)=u^{\prime}'+op+'v+u'+op+r'v^{\prime}')],m(answer))
u2=M([1,2,-1]);du2=M([3,0,4]);v2=M([2,4,8]);dv2=M([1,4,12])
for n in[51,52]:
 result=du2.dot(v2)+u2.dot(dv2)if n==51 else du2.cross(v2)+u2.cross(dv2);op=r'\cdot'if n==51 else r'\times'
 add(n,'u(2)=(1,2,−1),u′(2)=(3,0,4),v(t)=(t,t²,t³)일 때 '+m(r'\frac d{dt}(u'+op+r'v)\big|_{t=2}')+'를 구하라.','Given u(2)=(1,2,−1),u′(2)=(3,0,4),v(t)=(t,t²,t³), find '+m(r'\frac d{dt}(u'+op+r'v)\big|_{t=2}')+'.',[m('v(2)='+v(v2)+r',\quad v^{\prime}(2)='+v(dv2)),m(r'u^{\prime}(2)'+op+'v(2)+u(2)'+op+r'v^{\prime}(2)')],[m('v(2)='+v(v2)+r',\quad v^{\prime}(2)='+v(dv2)),m(r'u^{\prime}(2)'+op+'v(2)+u(2)'+op+r'v^{\prime}(2)')],m(tex(result)if n==51 else v(result)))
add(53,'상수벡터a,b와 상수ω에 대해 r(t)=a cosωt+b sinωt이면 r×r′=ωa×b임을 보여라.','For constant vectors a,b and scalar ω, let r(t)=a cosωt+b sinωt. Prove r×r′=ωa×b.',[m(r'r^{\prime}=-\omega a\sin\omega t+\omega b\cos\omega t'),m(r'r\times r^{\prime}=\omega\cos^2\omega t(a\times b)-\omega\sin^2\omega t(b\times a)'),m(r'b\times a=-a\times b')],[m(r'r^{\prime}=-\omega a\sin\omega t+\omega b\cos\omega t'),m(r'r\times r^{\prime}=\omega\cos^2\omega t(a\times b)-\omega\sin^2\omega t(b\times a)'),m(r'b\times a=-a\times b')],m(r'r\times r^{\prime}=\omega(a\times b)'))
add(54,'r(t)=a cosωt+b sinωt가 r″+ω²r=0을 만족함을 보여라.','Show that r(t)=a cosωt+b sinωt satisfies r″+ω²r=0.',[m(r'r^{\prime\prime}=-\omega^2a\cos\omega t-\omega^2b\sin\omega t=-\omega^2r')],[m(r'r^{\prime\prime}=-\omega^2a\cos\omega t-\omega^2b\sin\omega t=-\omega^2r')],m(r'r^{\prime\prime}+\omega^2r=0'))
add(55,m(r'\frac d{dt}(r\times r^{\prime})=r\times r^{\prime\prime}')+'를 증명하라.','Prove '+m(r'\frac d{dt}(r\times r^{\prime})=r\times r^{\prime\prime}')+'.',[m(r'\frac d{dt}(r\times r^{\prime})=r^{\prime}\times r^{\prime}+r\times r^{\prime\prime}'),'자기 자신과의 외적은0이다.'],[m(r'\frac d{dt}(r\times r^{\prime})=r^{\prime}\times r^{\prime}+r\times r^{\prime\prime}'),'A vector crossed with itself is zero.'],m(r'\frac d{dt}(r\times r^{\prime})=r\times r^{\prime\prime}'))
add(56,'스칼라 삼중곱 u·(v×w)의 도함수를 구하라.','Differentiate the scalar triple product u·(v×w).',[m(r'\frac d{dt}[u\cdot(v\times w)]=u^{\prime}\cdot(v\times w)+u\cdot(v\times w)^{\prime}'),'괄호 안 외적에 다시 곱 미분법을 적용한다.'],[m(r'\frac d{dt}[u\cdot(v\times w)]=u^{\prime}\cdot(v\times w)+u\cdot(v\times w)^{\prime}'),'Apply the cross-product rule inside the remaining derivative.'],m(r'u^{\prime}\cdot(v\times w)+u\cdot(v^{\prime}\times w)+u\cdot(v\times w^{\prime})'))
add(57,'r(t)≠0이면 |r|의 도함수가(r·r′)/|r|임을 보여라.','For r(t)≠0, prove that the derivative of |r| is(r·r′)/|r|.',[m(r'|r|^2=r\cdot r'),m(r'2|r|\frac d{dt}|r|=2r\cdot r^{\prime}'),'|r|>0으로 나눌 수 있다.'],[m(r'|r|^2=r\cdot r'),m(r'2|r|\frac d{dt}|r|=2r\cdot r^{\prime}'),'Division by |r|>0 is allowed.'],m(r'\frac d{dt}|r|=\frac{r\cdot r^{\prime}}{|r|}'))
add(58,'위치벡터r가 항상 접선벡터r′와 수직이면 |r|가 상수이며 원점 중심 구 위에 곡선이 놓임을 증명하라.','Prove that r·r′=0 throughout a parameter interval forces constant |r|, so the curve lies on a sphere centered at the origin.',[m(r'\frac d{dt}|r|^2=2r\cdot r^{\prime}=0'),'따라서 연결된 매개변수 구간에서 |r|²=R²는 상수이다. R>0이면 반지름R의 구이고,R=0이면 원점 한 점이다.'],[m(r'\frac d{dt}|r|^2=2r\cdot r^{\prime}=0'),'On a connected parameter interval, |r|²=R² is constant. For R>0 this is a sphere; R=0 is the single origin.'],m(r'|r(t)|=R\quad\text{constant}'))
add(59,'u(t)=r·(r′×r″)이면 u′=r·(r′×r‴)임을 보여라.','If u(t)=r·(r′×r″), prove u′=r·(r′×r‴).',[m(r'u^{\prime}=r^{\prime}\cdot(r^{\prime}\times r^{\prime\prime})+r\cdot(r^{\prime\prime}\times r^{\prime\prime})+r\cdot(r^{\prime}\times r^{\prime\prime\prime})'),'첫 항은 같은 벡터가 반복된 스칼라 삼중곱이라0이고, 둘째 항은 자기 외적이라0이다.'],[m(r'u^{\prime}=r^{\prime}\cdot(r^{\prime}\times r^{\prime\prime})+r\cdot(r^{\prime\prime}\times r^{\prime\prime})+r\cdot(r^{\prime}\times r^{\prime\prime\prime})'),'The first term is a scalar triple product with a repeated vector; the second contains a self-cross-product. Both vanish.'],m(r'u^{\prime}=r\cdot(r^{\prime}\times r^{\prime\prime\prime})'))
add(60,'접선벡터 r′(t)가 t증가 방향을 가리킴을 양·음의 차분으로 설명하라.','Explain using positive and negative increments why r′(t)points toward increasing t.', ['h>0이면 r(t+h)−r(t)는 뒤에서 앞으로 향하고 양수h로 나누어도 방향은 같다.','h<0이면 변위는 더 작은 매개변수 쪽으로 향하지만 음수h로 나누면서 방향이 뒤집혀 다시 증가 방향이다.',m(r'r^{\prime}(t)=\lim_{h\to0}\frac{r(t+h)-r(t)}h'),'극한이0이 아닌 정칙점에서 이 공통 극한 방향이 접선 방향이다. r′=0인 점에서는0벡터 자체에 방향이 없다.'],['For h>0 the displacement r(t+h)−r(t)points forward and division by positive h preserves its direction.','For h<0 the displacement points toward a smaller parameter, but division by negative h reverses it, again pointing forward.',m(r'r^{\prime}(t)=\lim_{h\to0}\frac{r(t+h)-r(t)}h'),'At a regular point with nonzero derivative, the common limiting direction is the tangent direction. A zero derivative vector has no direction.'],'r′(t)≠0인 정칙점에서 증가 방향의 접선벡터이다.','At regular points where r′(t)≠0, it is the tangent vector oriented toward increasing t.')
assert sorted(b.E)==list(range(1,61));b.save();(Path(__file__).parent/'s13-2-report.json').write_text(json.dumps({'section':'13.2','sourceVisualPdfPages':[977,978,979],'passed':len(checks),'checks':checks},indent=2)+'\n');print('60 exercises;',len(checks),'checks')
