import json,sympy as s
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=[];checks=[]
x,y,z,r,t,p=s.symbols('x y z r theta phi',real=True)
def pair(a,b=None):return {'ko':a,'en':a if b is None else b}
def add(n,ko,en,steps,ans,check=None,parts=[]):
 E.append({'id':f'stewart9-review-15-{n}','number':n,'subparts':parts,'topic':pair('15장 복습','Chapter 15 Review'),'statement':pair(ko,en),'hint':pair('영역과 미분요소를 먼저 적고, 적분 순서 또는 좌표계를 선택한다.','Describe the region and differential element before choosing the integration order or coordinates.'),'steps':{'ko':[v[0] for v in steps],'en':[v[1] for v in steps]},'answer':pair(ans),'check':pair(*(check or ('경계와 미분요소를 대조하고 별도 계산으로 검산했다.','The bounds and differential element were checked and the calculation was independently verified.'))),'status':'math-verified','source':{'printedPage':1156 if n<=13 else 1157 if n<=46 else 1158,'pdfPage':1193 if n<=13 else 1194 if n<=46 else 1195},'conceptHref':'../s15-9.html'})
def calc(n,expr,lims,description=None,setup=None):
 I=expr; stages=[]
 for lim in lims:
  old=I;I=s.simplify(s.integrate(I,lim));stages.append((fr'\({s.latex(lim[0])}\)에 대해 적분한다: \[\int_{{{s.latex(lim[1])}}}^{{{s.latex(lim[2])}}}({s.latex(old)})\,d{s.latex(lim[0])}={s.latex(I)}.\]',fr'Integrate with respect to \({s.latex(lim[0])}\): \[\int_{{{s.latex(lim[1])}}}^{{{s.latex(lim[2])}}}({s.latex(old)})\,d{s.latex(lim[0])}={s.latex(I)}.\]'))
 full=s.latex(s.Integral(expr,*lims))
 ko,en=description or (fr'반복적분 \({full}\)을 계산하라.',fr'Evaluate the iterated integral \({full}\).')
 if setup:stages.insert(0,setup)
 add(n,ko,en,stages,fr'\[{s.latex(I)}.\]');checks.append({'number':n,'integral':str(s.Integral(expr,*lims)),'value':str(I)})
# Exact repeated integrations, with the displayed bounds as the source data.
calc(3,y+2*x*s.exp(y),[(x,0,2),(y,1,2)])
calc(4,y*s.exp(x*y),[(x,0,1),(y,0,1)])
calc(5,s.cos(x*x),[(y,0,x),(x,0,1)])
calc(6,3*x*y*y,[(y,x,s.exp(x)),(x,0,1)])
calc(7,y*s.sin(x),[(z,0,s.sqrt(1-y*y)),(y,0,1),(x,0,s.pi)])
calc(8,6*x*y*z,[(z,x,1),(x,0,y),(y,0,1)])
add(9,r'上半平面の半円環 \(4\le x^2+y^2\le16,\ y\ge0\)上の \(\iint_R f\,dA\) を反復積分で表せ。'.replace('上半平面の半円環','상반평면의 반원 고리').replace('上の','에서').replace('を反復積分で表せ。','를 반복적분으로 나타내라.'),r'Write the integral of a continuous \(f\) over \(4\le x^2+y^2\le16,\ y\ge0\) in iterated form.',[(r'반지름은 2부터 4, 각은 0부터 π이다. 극좌표의 면적요소는 \(r\,dr\,d\theta\)이다.',r'The radius runs from 2 to 4 and the angle from 0 to π. Use \(dA=r\,dr\,d\theta\).')],r'\[\int_0^\pi\int_2^4 f(r\cos\theta,r\sin\theta)r\,dr\,d\theta.\]')
add(10,r'꼭짓점 \((-4,0),(0,4),(4,0)\)인 삼각형에서 \(\iint_R f\,dA\)를 반복적분으로 나타내라.',r'Write an iterated integral of \(f\) over the triangle with vertices \((-4,0),(0,4),(4,0)\).',[(r'높이 y에서 양 끝은 \(x=y-4\), \(x=4-y\)이고 \(0\le y\le4\)이다.',r'At height y the endpoints are \(x=y-4\) and \(x=4-y\), with \(0\le y\le4\).')],r'\[\int_0^4\int_{y-4}^{4-y} f(x,y)\,dx\,dy.\]')
add(11,r'원기둥좌표 \((2\sqrt3,\pi/3,2)\)를 직교좌표와 구면좌표로 바꾸어라.',r'Convert cylindrical \((2\sqrt3,\pi/3,2)\) to rectangular and spherical coordinates.',[(r'\(x=r\cos\theta=\sqrt3,y=r\sin\theta=3\).',r'\(x=r\cos\theta=\sqrt3,y=r\sin\theta=3\).'),(r'\(\rho=\sqrt{r^2+z^2}=4,\ \phi=\arccos(z/\rho)=\pi/3\).',r'\(\rho=\sqrt{r^2+z^2}=4,\ \phi=\arccos(z/\rho)=\pi/3\).')],r'\[(x,y,z)=(\sqrt3,3,2),\quad(\rho,\theta,\phi)=(4,\pi/3,\pi/3).\]')
add(12,r'직교좌표 \((2,2,-1)\)를 원기둥좌표와 구면좌표로 바꾸어라.',r'Convert \((2,2,-1)\) to cylindrical and spherical coordinates.',[(r'\(r=\sqrt{x^2+y^2}=2\sqrt2,\theta=\pi/4\).',r'\(r=\sqrt{x^2+y^2}=2\sqrt2,\theta=\pi/4\).'),(r'\(\rho=3\), 아래쪽 반공간이므로 \(\phi=\arccos(-1/3)>\pi/2\).',r'\(\rho=3\); the point is below the xy-plane, so \(\phi=\arccos(-1/3)>\pi/2\).')],r'\[(r,\theta,z)=(2\sqrt2,\pi/4,-1),\quad(\rho,\theta,\phi)=(3,\pi/4,\arccos(-1/3)).\]')
add(13,r'구면좌표 \((8,\pi/4,\pi/6)\)를 직교좌표와 원기둥좌표로 바꾸어라.',r'Convert spherical \((8,\pi/4,\pi/6)\) to rectangular and cylindrical coordinates.',[(r'\(r=\rho\sin\phi=4,\ z=\rho\cos\phi=4\sqrt3\).',r'\(r=\rho\sin\phi=4,\ z=\rho\cos\phi=4\sqrt3\).'),(r'\(x=r\cos\theta=2\sqrt2,y=r\sin\theta=2\sqrt2\).',r'\(x=r\cos\theta=2\sqrt2,y=r\sin\theta=2\sqrt2\).')],r'\[(x,y,z)=(2\sqrt2,2\sqrt2,4\sqrt3),\quad(r,\theta,z)=(4,\pi/4,4\sqrt3).\]')
add(14,r'(a) \(\theta=\pi/4\), (b) \(\phi=\pi/4\)의 곡면을 설명하라.',r'Identify the surfaces (a) \(\theta=\pi/4\), (b) \(\phi=\pi/4\).',[(r'(a) 방위각 고정이므로 \(y=x,x\ge0\)인 수직 반평면이다.',r'(a) A fixed azimuth gives the vertical half-plane \(y=x,x\ge0\).'),(r'(b) 양의 z축과 45°를 이루므로 \(z=\sqrt{x^2+y^2}\)인 위쪽 원뿔이다.',r'(b) The angle to the positive z-axis is 45°, giving the upper cone \(z=\sqrt{x^2+y^2}\).')],r'(a) \(y=x,\ x\ge0\); (b) \(z=\sqrt{x^2+y^2}\).',parts=['(a)','(b)'])
add(15,r'(a) \(x^2+y^2+z^2=4\), (b) \(x^2+y^2=4\)를 원기둥·구면좌표로 나타내라.',r'Express (a) \(x^2+y^2+z^2=4\), (b) \(x^2+y^2=4\) in cylindrical and spherical coordinates.',[(r'\(x^2+y^2=r^2=\rho^2\sin^2\phi\), \(r^2+z^2=\rho^2\)를 대입한다.',r'Substitute \(x^2+y^2=r^2=\rho^2\sin^2\phi\) and \(r^2+z^2=\rho^2\).')],r'(a) \(r^2+z^2=4,\ \rho=2\); (b) \(r=2,\ \rho\sin\phi=2\).',parts=['(a)','(b)'])
add(16,r'\(0\le\theta\le\pi/2,\ 0\le\phi\le\pi/6,\ 0\le\rho\le2\cos\phi\)인 입체를 그려라.',r'Sketch the solid specified by \(0\le\theta\le\pi/2,\ 0\le\phi\le\pi/6,\ 0\le\rho\le2\cos\phi\).',[(r'\(\rho^2\le2z\)를 완전제곱하면 \(x^2+y^2+(z-1)^2\le1\)이다.',r'Completing the square in \(\rho^2\le2z\) gives \(x^2+y^2+(z-1)^2\le1\).'),(r'나머지 각 조건은 \(x,y\ge0\), \(z\ge\sqrt3\sqrt{x^2+y^2}\)이다.',r'The angle constraints give \(x,y\ge0\) and \(z\ge\sqrt3\sqrt{x^2+y^2}\).')],r'\[x,y\ge0,\quad x^2+y^2+(z-1)^2\le1,\quad z\ge\sqrt{3(x^2+y^2)}.\]')
add(17,r'넓이 적분 \(\int_0^{\pi/2}\int_0^{\sin2\theta}r\,dr\,d\theta\)의 영역을 설명하라.',r'Describe the region represented by the area integral \(\int_0^{\pi/2}\int_0^{\sin2\theta}r\,dr\,d\theta\).',[(r'이 각 구간에서 \(\sin2\theta\ge0\)이다. 원점에서 장미곡선까지의 반지름을 모두 채운다.',r'Here \(\sin2\theta\ge0\); each radius fills the segment from the origin to the rose curve.')],r'\[0\le\theta\le\pi/2,\quad0\le r\le\sin2\theta.\]',('네 잎 장미곡선 중 제1사분면 잎 하나의 내부이다.','This is the interior of the first-quadrant petal of the four-leaved rose.'))
calc(18,r*r*s.sin(p),[(r,1,2),(p,0,s.pi/2),(t,0,s.pi/2)],(r'\(\int_0^{\pi/2}\int_0^{\pi/2}\int_1^2\rho^2\sin\phi\,d\rho\,d\phi\,d\theta\)의 입체를 설명하고 부피를 계산하라.',r'Describe the solid and evaluate \(\int_0^{\pi/2}\int_0^{\pi/2}\int_1^2\rho^2\sin\phi\,d\rho\,d\phi\,d\theta\).'),(r'반지름 1과2 사이 구껍질의 제1팔분공간 부분이다. 계산에서 r는 구면 반지름 ρ를 뜻한다.',r'This is the first-octant part of the shell between radii 1 and 2. In the calculation r denotes the spherical radius ρ.'))
calc(19,s.cos(y*y),[(x,0,y),(y,0,1)],(r'\(\int_0^1\int_x^1\cos(y^2)\,dy\,dx\)를 순서를 바꾸어 계산하라.',r'Reverse the order to evaluate \(\int_0^1\int_x^1\cos(y^2)\,dy\,dx\).'),(r'\(0\le x\le y\le1\)이므로 x부터 적분한다.',r'The region is \(0\le x\le y\le1\), so integrate x first.'))
calc(20,y*s.exp(x*x)/x**3,[(y,0,x*x),(x,0,1)],(r'\(\int_0^1\int_{\sqrt y}^1 ye^{x^2}/x^3\,dx\,dy\)를 순서를 바꾸어 계산하라.',r'Reverse the order to evaluate \(\int_0^1\int_{\sqrt y}^1 ye^{x^2}/x^3\,dx\,dy\).'),(r'\(0\le y\le x^2,0\le x\le1\). 원점 특이점은 비음수 적분의 극한으로 처리한다.',r'The region is \(0\le y\le x^2,0\le x\le1\). Interpret the origin by the limit of nonnegative integrals.'))
calc(21,y*s.exp(x*y),[(x,0,2),(y,0,3)])
calc(22,x*y,[(x,y*y,y+2),(y,0,1)])
calc(23,y/(1+x*x),[(y,0,s.sqrt(x)),(x,0,1)])
calc(24,1/(1+x*x),[(y,x,1),(x,0,1)])
calc(25,y,[(x,y*y,8-y*y),(y,0,2)])
calc(26,y,[(x,1/y,y),(y,1,2)])
calc(27,r**4,[(r,0,3),(t,0,s.pi/3)],(r'제1사분면에서 \(y=0,y=\sqrt3x,x^2+y^2=9\)로 둘러싸인 영역 위 \(\iint_D(x^2+y^2)^{3/2}\,dA\)를 구하라.',r'Integrate \((x^2+y^2)^{3/2}\) over the first-quadrant sector bounded by \(y=0,y=\sqrt3x,x^2+y^2=9\).'),(r'극좌표에서 함수는 r³이고 야코비안은 r, 따라서 적분함수는 r⁴이다.',r'The function is r³ and the Jacobian is r, giving the integrand r⁴.'))
calc(28,r*r*s.cos(t),[(r,1,s.sqrt(2)),(t,0,s.pi/2)],(r'제1사분면의 \(1\le x^2+y^2\le2\)에서 \(\iint_D x\,dA\)를 구하라.',r'Evaluate \(\iint_D x\,dA\) on the first-quadrant annulus \(1\le x^2+y^2\le2\).'),(r'\(x=r\cos\theta,dA=r\,dr\,d\theta\)이다.',r'Use \(x=r\cos\theta,dA=r\,dr\,d\theta\).'))
calc(29,x*y,[(z,0,x+y),(y,0,x),(x,0,3)])
calc(30,x*y,[(z,0,1-3*x-y),(y,0,1-3*x),(x,0,s.Rational(1,3))])
calc(31,r**5*s.cos(t)**2*s.sin(t)**2,[(x,0,1-r*r),(r,0,1),(t,0,2*s.pi)],(r'\(x=1-y^2-z^2\), \(x=0\) 사이에서 \(\iiint_E y^2z^2\,dV\)를 구하라.',r'Integrate \(y^2z^2\) over the solid between \(x=1-y^2-z^2\) and \(x=0\).'),(r'yz평면에서 \(y=r\cos\theta,z=r\sin\theta\), \(dV=r\,dx\,dr\,d\theta\)이다.',r'Use \(y=r\cos\theta,z=r\sin\theta\) in the yz-plane, with \(dV=r\,dx\,dr\,d\theta\).'))
calc(32,z,[(x,0,2-y),(z,0,s.sqrt(1-y*y)),(y,0,1)])
calc(33,r*r*s.sin(t)*z,[(z,0,r*s.sin(t)),(r,0,2),(t,0,s.pi)],(r'\(x^2+y^2\le4,0\le z\le y\)에서 \(\iiint_E yz\,dV\)를 구하라.',r'Evaluate \(\iiint_E yz\,dV\) where \(x^2+y^2\le4,0\le z\le y\).'),(r'y≥0이 필요하여 \(0\le\theta\le\pi\). 야코비안 r를 포함한다.',r'The condition y≥0 gives \(0\le\theta\le\pi\). Include the Jacobian r.'))
calc(34,r**6*s.cos(p)**3*s.sin(p),[(r,0,1),(p,0,s.pi/2),(t,0,2*s.pi)],(r'단위 위쪽 반구 H에서 \(\iiint_H z^3\sqrt{x^2+y^2+z^2}\,dV\)를 구하라.',r'Evaluate \(\iiint_H z^3\sqrt{x^2+y^2+z^2}\,dV\) over the upper unit half-ball.'),(r'계산의 r는 ρ이며 \(z=\rho\cos\phi\), 부피요소는 \(\rho^2\sin\phi\)이다.',r'Here r denotes ρ. Use \(z=\rho\cos\phi\) and volume factor \(\rho^2\sin\phi\).'))
calc(35,x*x+4*y*y,[(y,1,4),(x,0,2)],(r'\(z=x^2+4y^2\) 아래, \([0,2]\times[1,4]\) 위의 부피를 구하라.',r'Find the volume below \(z=x^2+4y^2\) and above \([0,2]\times[1,4]\).'))
calc(36,x*x*y,[(x,y+1,4-2*y),(y,0,1)],(r'\(z=x^2y\) 아래, 꼭짓점 \((1,0),(2,1),(4,0)\)인 삼각형 위의 부피를 구하라.',r'Find the volume below \(z=x^2y\) over the triangle with vertices \((1,0),(2,1),(4,0)\).'),(r'수평 단면의 경계는 \(x=y+1\), \(x=4-2y\)이다.',r'The horizontal bounds are \(x=y+1\) and \(x=4-2y\).'))
add(37,r'꼭짓점 \((0,0,0),(0,0,1),(0,2,0),(2,2,0)\)인 사면체의 부피를 구하라.',r'Find the volume of the tetrahedron with vertices \((0,0,0),(0,0,1),(0,2,0),(2,2,0)\).',[(r'밑면은 xy평면의 삼각형으로 넓이가2이고 높이는1이다.',r'The triangular base in the xy-plane has area 2 and the height is 1.'),(r'\(V=\frac13Ah=\frac13(2)(1)\).',r'\(V=\frac13Ah=\frac13(2)(1)\).')],r'\[V=\frac23.\]')
calc(38,(3-r*s.sin(t))*r,[(r,0,2),(t,0,2*s.pi)],(r'\(x^2+y^2=4\), \(z=0\), \(y+z=3\)으로 둘러싸인 부피를 구하라.',r'Find the volume bounded by \(x^2+y^2=4\), \(z=0\), and \(y+z=3\).'),(r'원판 전체에서 높이 \(3-y>0\). 높이에 극좌표 야코비안 r를 곱한다.',r'The height \(3-y\) is positive throughout the disk. Multiply it by the polar Jacobian r.'))
a,m=s.symbols('a m',positive=True)
calc(39,m*a**3*r*r*s.cos(t)/3,[(r,0,1),(t,-s.pi/2,s.pi/2)],(r'\(x^2+9y^2=a^2\)를 \(z=0,z=mx\)로 잘라 얻는 쐐기 하나의 부피를 구하라. \(a,m>0\).',r'For \(a,m>0\), find the volume of one wedge cut from \(x^2+9y^2=a^2\) by \(z=0,z=mx\).'),(r'오른쪽 쐐기에서 \(x=ar\cos\theta,y=(a/3)r\sin\theta\), 야코비안 \(a^2r/3\). m<0이면 결과에서 m을 |m|로 바꾼다.',r'For the right wedge use \(x=ar\cos\theta,y=(a/3)r\sin\theta\), with Jacobian \(a^2r/3\). Replace m by |m| if m<0.'))
calc(40,(r-r*r)*r,[(r,0,1),(t,0,2*s.pi)],(r'\(z=x^2+y^2\) 위, \(z=\sqrt{x^2+y^2}\) 아래의 부피를 구하라.',r'Find the volume above \(z=x^2+y^2\) and below \(z=\sqrt{x^2+y^2}\).'),(r'교선은 r²=r, 즉 r=1. 높이는 r−r²이다.',r'The nontrivial intersection is r=1 and the height is r−r².'))
lam=lambda f:s.integrate(f,(x,0,1-y*y),(y,0,1))
M=lam(y);Mx=lam(y*y);My=lam(x*y);Ix=lam(y**3);Iy=lam(x*x*y)
add(41,r'제1사분면의 좌표축과 \(x=1-y^2\)로 둘러싸인 판의 밀도는 \(\rho=y\)이다. (a)질량 (b)질량중심 (c)x,y축 관성모멘트와 회전반경을 구하라.',r'A lamina bounded by the coordinate axes and \(x=1-y^2\) in the first quadrant has density \(\rho=y\). Find (a) mass, (b) center of mass, (c) moments of inertia and radii of gyration about the x- and y-axes.',[(r'\(0\le y\le1,0\le x\le1-y^2\)이고 \(M=\iint y\,dA=1/4\).',r'The bounds are \(0\le y\le1,0\le x\le1-y^2\), and \(M=\iint y\,dA=1/4\).'),(fr'\[M_x={s.latex(Mx)},\quad M_y={s.latex(My)},\quad I_x={s.latex(Ix)},\quad I_y={s.latex(Iy)}.\]',fr'\[M_x={s.latex(Mx)},\quad M_y={s.latex(My)},\quad I_x={s.latex(Ix)},\quad I_y={s.latex(Iy)}.\]'),(r'\(\bar x=M_y/M,\bar y=M_x/M,k_x=\sqrt{I_x/M},k_y=\sqrt{I_y/M}\)를 사용한다.',r'Use \(\bar x=M_y/M,\bar y=M_x/M,k_x=\sqrt{I_x/M},k_y=\sqrt{I_y/M}\).')],fr'\[M={s.latex(M)},\quad(\bar x,\bar y)=({s.latex(My/M)},{s.latex(Mx/M)}),\quad I_x={s.latex(Ix)},\ I_y={s.latex(Iy)},\quad(k_x,k_y)=({s.latex(s.sqrt(Ix/M))},{s.latex(s.sqrt(Iy/M))}).\]',parts=['(a)','(b)','(c)'])
add(42,r'제1사분면의 \(x^2+y^2\le a^2\)에서 (a)도심 (b)밀도 \(\rho=xy^2\)일 때 질량중심을 구하라.',r'For the first-quadrant part of \(x^2+y^2\le a^2\), find (a) the centroid and (b) the center of mass for density \(\rho=xy^2\).',[(r'(a) 넓이 \(\pi a^2/4\), 두 일차모멘트는 각각 \(a^3/3\)이다.',r'(a) The area is \(\pi a^2/4\), and both first moments are \(a^3/3\).'),(r'(b) 극좌표로 질량과 모멘트를 계산한다: \[M=a^5/15,\quad M_y=\pi a^6/96,\quad M_x=a^6/24.\]',r'(b) Polar integration gives \[M=a^5/15,\quad M_y=\pi a^6/96,\quad M_x=a^6/24.\]')],r'(a) \((4a/(3\pi),4a/(3\pi))\); (b) \((5\pi a/32,5a/8)\).',parts=['(a)','(b)'])
add(43,r'밑면 반지름 a, 높이 h인 원뿔의 밑면을 z=0에, 꼭짓점을 z=h에 둔다. (a)도심 (b)밀도 \(\rho=\sqrt{x^2+y^2}\)일 때 z축 관성모멘트를 구하라.',r'A cone has base radius a at z=0 and vertex at z=h. Find (a) its centroid and (b) its axial moment of inertia for density \(\rho=\sqrt{x^2+y^2}\).',[(r'높이 z에서 반지름은 \(a(1-z/h)\). 대칭으로 도심의 x,y좌표는0이다.',r'At height z the radius is \(a(1-z/h)\). Symmetry makes the centroid x- and y-coordinates zero.'),(r'\[V=\pi a^2h/3,\quad\iiint z\,dV=\pi a^2h^2/12.\]',r'\[V=\pi a^2h/3,\quad\iiint z\,dV=\pi a^2h^2/12.\]'),(r'\[I_z=2\pi\int_0^h\int_0^{a(1-z/h)}r^4\,dr\,dz=\pi a^5h/15.\]',r'\[I_z=2\pi\int_0^h\int_0^{a(1-z/h)}r^4\,dr\,dz=\pi a^5h/15.\]')],r'(a) \((0,0,h/4)\); (b) \(I_z=\pi a^5h/15\).',parts=['(a)','(b)'])
add(44,r'\(a>0\)일 때 \(z^2=a^2(x^2+y^2)\)에서 \(1\le z\le2\)인 부분의 넓이를 구하라.',r'For \(a>0\), find the area of \(z^2=a^2(x^2+y^2)\) between z=1 and z=2.',[(r'양의 가지는 z=ar, 따라서 \(1/a\le r\le2/a\). 그래프 면적요소는 \(\sqrt{1+a^2}r\,dr\,d\theta\)이다.',r'The positive branch is z=ar, so \(1/a\le r\le2/a\). Its area element is \(\sqrt{1+a^2}r\,dr\,d\theta\).'),(r'\[A=2\pi\sqrt{1+a^2}\int_{1/a}^{2/a}r\,dr.\]',r'\[A=2\pi\sqrt{1+a^2}\int_{1/a}^{2/a}r\,dr.\]')],r'\[A=3\pi\sqrt{1+a^2}/a^2.\]')
calc(45,s.sqrt(2+4*x*x),[(y,0,2-2*x),(x,0,1)],(r'\(z=x^2+y\)에서 \((0,0),(1,0),(0,2)\)인 삼각형 위 부분의 넓이를 구하라.',r'Find the area of \(z=x^2+y\) over the triangle with vertices \((0,0),(1,0),(0,2)\).'),(r'\(f_x=2x,f_y=1\)이므로 면적 배율은 \(\sqrt{2+4x^2}\).',r'Since \(f_x=2x,f_y=1\), the area factor is \(\sqrt{2+4x^2}\).'))
calc(47,r**4*s.cos(t),[(r,0,3),(t,-s.pi/2,s.pi/2)],(r'\(\int_0^3\int_{-\sqrt{9-x^2}}^{\sqrt{9-x^2}}(x^3+xy^2)\,dy\,dx\)를 극좌표로 계산하라.',r'Use polar coordinates to evaluate \(\int_0^3\int_{-\sqrt{9-x^2}}^{\sqrt{9-x^2}}(x^3+xy^2)\,dy\,dx\).'),(r'오른쪽 반원판이며 \(x(x^2+y^2)dA=r^4\cos\theta\,dr\,d\theta\).',r'The domain is a right half-disk, and \(x(x^2+y^2)dA=r^4\cos\theta\,dr\,d\theta\).'))
calc(48,r**5*s.sin(p)**3*s.sin(t)**2,[(r,0,2),(p,0,s.pi),(t,-s.pi/2,s.pi/2)],(r'반지름2인 공의 x≥0 절반에서 \(\iiint y^2\sqrt{x^2+y^2+z^2}\,dV\)를 구하라.',r'Integrate \(y^2\sqrt{x^2+y^2+z^2}\) over the x≥0 half of the radius-2 ball.'),(r'계산의 r는 구면반지름ρ이다. \(y=\rho\sin\phi\sin\theta\)와 야코비안을 대입한다.',r'Here r denotes spherical radius ρ. Substitute \(y=\rho\sin\phi\sin\theta\) and the Jacobian.'))
# Weighted tetrahedron moments.
tri=lambda f:s.integrate(f,(z,0,3*(1-x-y/2)),(y,0,2*(1-x)),(x,0,1))
rho=x*x+y*y+z*z;mass=tri(rho);mom=[tri(v*rho) for v in (x,y,z)]
add(50,r'꼭짓점 \((0,0,0),(1,0,0),(0,2,0),(0,0,3)\), 밀도 \(x^2+y^2+z^2\)인 사면체의 질량중심을 구하라.',r'Find the center of mass of the tetrahedron with vertices \((0,0,0),(1,0,0),(0,2,0),(0,0,3)\) and density \(x^2+y^2+z^2\).',[(r'\(0\le x\le1,0\le y\le2(1-x),0\le z\le3(1-x-y/2)\)이다.',r'Use \(0\le x\le1,0\le y\le2(1-x),0\le z\le3(1-x-y/2)\).'),(fr'\[M={s.latex(mass)},\quad(\iiint x\rho,\iiint y\rho,\iiint z\rho)=({",".join(s.latex(v) for v in mom)}).\]',fr'\[M={s.latex(mass)},\quad(\iiint x\rho,\iiint y\rho,\iiint z\rho)=({",".join(s.latex(v) for v in mom)}).\]'),(r'세 가중 모멘트를 각각 질량으로 나눈다.',r'Divide each weighted moment by the mass.')],fr'\[(\bar x,\bar y,\bar z)=({",".join(s.latex(s.simplify(v/mass)) for v in mom)}).\]')
add(51,r'\([0,3]\times[0,2]\)에서 결합밀도 \(f=C(x+y)\), 그 밖에서0이다. (a)C (b) \(P(X\le2,Y\ge1)\) (c) \(P(X+Y\le1)\)을 구하라.',r'The joint density is \(C(x+y)\) on \([0,3]\times[0,2]\), and zero elsewhere. Find (a) C, (b) \(P(X\le2,Y\ge1)\), (c) \(P(X+Y\le1)\).',[(r'정규화: \(1=C\int_0^3\int_0^2(x+y)\,dy\,dx=15C\).',r'Normalization gives \(1=C\int_0^3\int_0^2(x+y)\,dy\,dx=15C\).'),(r'\[P_b=\frac1{15}\int_0^2\int_1^2(x+y)\,dy\,dx=\frac13.\]',r'\[P_b=\frac1{15}\int_0^2\int_1^2(x+y)\,dy\,dx=\frac13.\]'),(r'\[P_c=\frac1{15}\int_0^1\int_0^{1-x}(x+y)\,dy\,dx=\frac1{45}.\]',r'\[P_c=\frac1{15}\int_0^1\int_0^{1-x}(x+y)\,dy\,dx=\frac1{45}.\]')],r'(a) \(C=1/15\); (b) \(1/3\); (c) \(1/45\).',parts=['(a)','(b)','(c)'])
add(52,r'평균수명800시간의 지수분포를 따르는 전구3개의 총수명이1000시간 이내일 확률을 구하라. 세 수명은 독립이라고 가정한다.',r'Three independent bulb lifetimes are exponentially distributed with mean 800 hours. Find the probability that their total lifetime is at most 1000 hours.',[(r'독립성에 의해 결합밀도는 \(800^{-3}e^{-(x+y+z)/800}\)이다.',r'Independence gives joint density \(800^{-3}e^{-(x+y+z)/800}\).'),(r'합 t의 밀도는 \(t^2e^{-t/800}/(2\cdot800^3)\). u=t/800으로 적분한다.',r'The sum has density \(t^2e^{-t/800}/(2\cdot800^3)\). Set u=t/800.'),(r'\[P=\frac12\int_0^{5/4}u^2e^{-u}du=1-e^{-5/4}(1+5/4+25/32).\]',r'\[P=\frac12\int_0^{5/4}u^2e^{-u}du=1-e^{-5/4}(1+5/4+25/32).\]')],r'\[1-\frac{97}{32}e^{-5/4}\approx0.1315.\]',('세 전구 각각의 수명이1000이하인 사건과 총수명1000이하인 사건은 다르다. 독립성은 모형 가정이다.','The sum being at most 1000 differs from each individual lifetime being at most 1000. Independence is a modeling assumption.'))
add(53,r'\(\int_{-1}^1\int_{x^2}^1\int_0^{1-y}f\,dz\,dy\,dx\)를 dx dy dz 순서로 바꾸어라.',r'Rewrite \(\int_{-1}^1\int_{x^2}^1\int_0^{1-y}f\,dz\,dy\,dx\) in dx dy dz order.',[(r'영역은 \(x^2\le y,0\le z\le1-y\)이다. z를 고정하면 \(0\le y\le1-z\).',r'The region is \(x^2\le y,0\le z\le1-y\). Fixing z gives \(0\le y\le1-z\).'),(r'마지막 부등식은 \(-\sqrt y\le x\le\sqrt y\)로 푼다.',r'Solve the remaining condition as \(-\sqrt y\le x\le\sqrt y\).')],r'\[\int_0^1\int_0^{1-z}\int_{-\sqrt y}^{\sqrt y}f(x,y,z)\,dx\,dy\,dz.\]')
forms=[r'\int_0^2\int_0^{y^2}\int_0^{y^3}f\,dx\,dz\,dy',r'\int_0^8\int_{\sqrt[3]x}^2\int_0^{y^2}f\,dz\,dy\,dx',r'\int_0^4\int_{\sqrt z}^2\int_0^{y^3}f\,dx\,dy\,dz',r'\int_0^8\left[\int_0^{x^{2/3}}\int_{\sqrt[3]x}^2f\,dy\,dz+\int_{x^{2/3}}^4\int_{\sqrt z}^2f\,dy\,dz\right]dx',r'\int_0^4\left[\int_0^{z^{3/2}}\int_{\sqrt z}^2f\,dy\,dx+\int_{z^{3/2}}^8\int_{\sqrt[3]x}^2f\,dy\,dx\right]dz']
add(54,r'\(\int_0^2\int_0^{y^3}\int_0^{y^2}f\,dz\,dx\,dy\)와 같은 나머지 다섯 순서의 반복적분을 써라.',r'Give the five other integration orders for \(\int_0^2\int_0^{y^3}\int_0^{y^2}f\,dz\,dx\,dy\).',[(r'공통 영역은 \(0\le y\le2,0\le x\le y^3,0\le z\le y^2\). y를 먼저 적분할 때 아래경계는 \(\max(\sqrt[3]x,\sqrt z)\)이므로 나눈다.',r'The region is \(0\le y\le2,0\le x\le y^3,0\le z\le y^2\). Integrating y first requires splitting at the change in \(\max(\sqrt[3]x,\sqrt z)\).')]+[(fr'순서별 결과: \[{f}.\]',fr'The corresponding order gives \[{f}.\]')for f in forms],r'다섯 적분은 위 해설에 제시했다. / The five integrals are listed in the solution.')
calc(55,x/(2*y),[(x,-2,0),(y,2,4)],(r'꼭짓점 \((0,2),(1,1),(2,2),(1,3)\)인 정사각형 위 \(\iint_R (x-y)/(x+y)\,dA\)를 \(u=x-y,v=x+y\)로 계산하라.',r'Use \(u=x-y,v=x+y\) to integrate \((x-y)/(x+y)\) over the square with vertices \((0,2),(1,1),(2,2),(1,3)\).'),(r'변환영역은 \(-2\le u\le0,2\le v\le4\), 역야코비안 절댓값1/2. 아래 계산의 x,y는 각각 u,v를 나타낸다.',r'The transformed rectangle is \(-2\le u\le0,2\le v\le4\), with absolute inverse Jacobian 1/2. In the calculation below x,y denote u,v.'))
calc(56,8*x*y*z,[(z,0,1-x-y),(y,0,1-x),(x,0,1)],(r'\(\sqrt x+\sqrt y+\sqrt z=1\)과 좌표평면 사이의 부피를 \(x=u^2,y=v^2,z=w^2\)로 구하라.',r'Use \(x=u^2,y=v^2,z=w^2\) to find the volume bounded by \(\sqrt x+\sqrt y+\sqrt z=1\) and the coordinate planes.'),(r'\(u,v,w\ge0,u+v+w\le1\)이고 야코비안은8uvw. 아래 계산의 x,y,z는 u,v,w이다.',r'The transformed simplex is \(u,v,w\ge0,u+v+w\le1\), with Jacobian8uvw. The calculation below uses x,y,z for u,v,w.'))
calc(57,(x*x-y*y)/8,[(y,0,2),(x,0,2)],(r'꼭짓점 \((0,0),(1,1),(2,0),(1,-1)\)인 정사각형 위 \(\iint_R xy\,dA\)를 변수변환으로 구하라.',r'Use a change of variables to integrate xy over the square with vertices \((0,0),(1,1),(2,0),(1,-1)\).'),(r'\(u=x+y,v=x-y\)이면 0≤u,v≤2, xy=(u²−v²)/4, 야코비안1/2. 아래 x,y는 u,v이다.',r'Set \(u=x+y,v=x-y\). Then 0≤u,v≤2, xy=(u²−v²)/4, and the Jacobian is1/2. Below x,y denote u,v.'))
add(58,r'정수 n, \(0<r<R\)에 대해 (a)원형 고리의 \(\iint(x^2+y^2)^{-n/2}\,dA\) (b)r→0 수렴조건 (c)구껍질의 \(\iiint(x^2+y^2+z^2)^{-n/2}\,dV\) (d)r→0 수렴조건을 구하라.',r'For integer n and \(0<r<R\), compute (a) the integral of \((x^2+y^2)^{-n/2}\) over the annulus, (b) its convergence condition as r→0, (c) the integral of \((x^2+y^2+z^2)^{-n/2}\) over the spherical shell, and (d) its convergence condition.',[(r'평면에서는 각 적분이2π를 주므로 \(2\pi\int_r^R s^{1-n}ds\)이다. n=2는 로그를 따로 계산한다.',r'In the plane the angle integral is2π, giving \(2\pi\int_r^R s^{1-n}ds\). Treat n=2 logarithmically.'),(r'공간에서는 각 적분이4π를 주므로 \(4\pi\int_r^R s^{2-n}ds\)이다. n=3은 로그를 따로 계산한다.',r'In space the angle integral is4π, giving \(4\pi\int_r^R s^{2-n}ds\). Treat n=3 logarithmically.'),(r'원점의 거듭제곱 적분은 지수가−1보다 클 때에만 수렴한다.',r'A power integral at the origin converges exactly when its exponent is greater than−1.')],r'\[(a)\ \begin{cases}\frac{2\pi}{2-n}(R^{2-n}-r^{2-n}),&n\ne2,\\2\pi\ln(R/r),&n=2;\end{cases}\quad(b)\ n<2.\]\[(c)\ \begin{cases}\frac{4\pi}{3-n}(R^{3-n}-r^{3-n}),&n\ne3,\\4\pi\ln(R/r),&n=3;\end{cases}\quad(d)\ n<3.\]',parts=['(a)','(b)','(c)','(d)'])
for n,vals,sampling in [(1,[[2.7,4.7,6.7],[4.5,6.5,8.5],[8,10,12]],('오른쪽 위 꼭짓점','upper-right corners')),(2,[[1.1,3.1,5.1],[2.2,4.2,6.2],[5.2,7.2,9.2]],('중점','midpoints'))]:
 total=sum(map(sum,vals));table=r'\begin{pmatrix}'+r'\\'.join('&'.join(map(str,row))for row in vals)+r'\end{pmatrix}'
 add(n,fr'원문 등고선의 \([0,3]^2\) 영역을 단위 정사각형9개로 나누고 {sampling[0]}의 값을 읽어 이중적분을 추정하라.',fr'Estimate the integral on \([0,3]^2\) from the source contour map, using nine unit squares and their {sampling[1]}.',[(r'각 소영역의 넓이는1이다. 아래 행은 y가 작은 순서, 열은 x가 작은 순서의 보간값이다.',r'Each cell has area1. Rows below run from low to high y and columns from low to high x.'),(fr'\[{table}.\]',fr'\[{table}.\]'),(fr'아홉 값을 더하면 약 {total:.1f}이다. 등고선 사이 읽기 오차를 고려해 반올림한다.',fr'The sum is approximately {total:.1f}; round to reflect graphical reading uncertainty.')],fr'\[\iint_R f\,dA\approx {round(total)}.\]',('그림에서 읽은 근삿값이며 정밀한 함수값이 아니다. 1번 부록의 약64와 독립 판독값63.6이 부합한다.','These are approximate graphical readings, not exact function values. The independent reading63.6 for Exercise1 agrees with the appendix estimate64.'))
import mpmath as mp
areas=[]
for prec in (30,45):
 mp.mp.dps=prec
 av=4*mp.quad(lambda yy:mp.quad(lambda xx:mp.sqrt(1+mp.sin(yy)**2+xx**2*mp.cos(yy)**2),[0,3]),[0,mp.pi/2,mp.pi]);areas.append(av)
assert abs(areas[0]-areas[1])<mp.mpf('1e-25')
add(46,r'\(-3\le x\le3,-\pi\le y\le\pi\)에서 \(z=x\sin y\)를 그리고 곡면적을 소수점아래4자리까지 구하라.',r'Graph \(z=x\sin y\) on \(-3\le x\le3,-\pi\le y\le\pi\) and find its surface area to four decimal places.',[(r'\(f_x=\sin y,f_y=x\cos y\), 따라서 면적 배율은 \(\sqrt{1+\sin^2y+x^2\cos^2y}\).',r'\(f_x=\sin y,f_y=x\cos y\), so the area factor is \(\sqrt{1+\sin^2y+x^2\cos^2y}\).'),(r'\[A=4\int_0^\pi\int_0^3\sqrt{1+\sin^2y+x^2\cos^2y}\,dx\,dy.\]',r'\[A=4\int_0^\pi\int_0^3\sqrt{1+\sin^2y+x^2\cos^2y}\,dx\,dy.\]'),(fr'30자리와45자리 정밀도로 각각 수치적분하면 \(A\approx{mp.nstr(areas[-1],20)}\).',fr'Independent integrations at30 and45 digits give \(A\approx{mp.nstr(areas[-1],20)}\).')],fr'\[A\approx{float(areas[-1]):.4f}.\]')
roots=[];nums=[]
for prec in (30,45):
 mp.mp.dps=prec;aa=mp.findroot(lambda q:1-q*q-mp.exp(q),(-.9,-.5));vv=mp.quad(lambda q:((1-q*q)**3-mp.exp(3*q))/3,[aa,0]);roots.append(aa);nums.append(vv)
assert abs(nums[0]-nums[1])<mp.mpf('1e-25')
add(49,r'\(y=1-x^2\)와 \(y=e^x\)로 둘러싸인 영역 D에서 \(\iint_D y^2\,dA\)의 근삿값을 구하라.',r'Approximate \(\iint_D y^2\,dA\), where D is bounded by \(y=1-x^2\) and \(y=e^x\).',[(fr'교점의 x좌표는0과 \(a\approx{mp.nstr(roots[-1],14)}\)이다. 이 사이에서 포물선이 위에 있다.',fr'The intersection abscissas are0 and \(a\approx{mp.nstr(roots[-1],14)}\). The parabola lies above the exponential between them.'),(r'\[I=\int_a^0\int_{e^x}^{1-x^2}y^2\,dy\,dx=\frac13\int_a^0[(1-x^2)^3-e^{3x}]\,dx.\]',r'\[I=\int_a^0\int_{e^x}^{1-x^2}y^2\,dy\,dx=\frac13\int_a^0[(1-x^2)^3-e^{3x}]\,dx.\]'),(fr'교점 계산과 적분을30자리·45자리로 반복하여 \({mp.nstr(nums[-1],18)}\)를 얻는다.',fr'Repeating the root solve and integration at30 and45 digits gives \({mp.nstr(nums[-1],18)}\).')],fr'\[I\approx{float(nums[-1]):.6f}.\]')
checks.extend([{'number':46,'numerical':mp.nstr(areas[-1],40),'precisionAgreement':'30/45 digits, difference <1e-25'},{'number':49,'intersection':mp.nstr(roots[-1],40),'numerical':mp.nstr(nums[-1],40),'precisionAgreement':'30/45 digits, difference <1e-25'}])
next(e for e in E if e['number']==54)['answer']=pair('다섯 적분은 위 해설에 제시했다.','The five integrals are listed in the solution.')
E.sort(key=lambda v:v['number']);assert [v['number']for v in E]==list(range(1,59))
# Restore explicit source regions where a compact equivalent iterated integral was used.
regions={21:(r'\(0\le x\le2,0\le y\le3\)',r'ye^{xy}'),22:(r'\(0\le y\le1,y^2\le x\le y+2\)',r'xy'),23:(r'\(y=\sqrt x,y=0,x=1\)',r'y/(1+x^2)'),24:(r'\((0,0),(1,1),(0,1)\)',r'1/(1+x^2)'),25:(r'\(x=y^2,x=8-y^2,x,y\ge0\)',r'y'),26:(r'\(xy\ge1,y\ge x,y\le2,x,y>0\)',r'y'),29:(r'\(0\le x\le3,0\le y\le x,0\le z\le x+y\)',r'xy'),30:(r'\((0,0,0),(1/3,0,0),(0,1,0),(0,0,1)\)',r'xy'),32:(r'\(y,z\ge0,y^2+z^2\le1,0\le x\le2-y\)',r'z')}
for n,(region,fun) in regions.items():
 e=E[n-1];dim='삼중'if n>=29 else'이중';shape='꼭짓점으로 지정한 삼각형/사면체'if n in(24,30)else'경계 또는 부등식으로 지정한 영역'
 e['statement']=pair(fr'{shape} {region}에서 함수 \({fun}\)의 {dim}적분을 계산하라.',fr'Integrate \({fun}\) over the region specified by {region}'+(' (the listed vertices define the simplex).'if n in(24,30)else'.'))
(R/'exercise-content/s15-10.json').write_text(json.dumps({'section':'15.10','kind':'review','source':{'title':'Calculus','edition':9,'language':'en','printedPages':[1156,1157,1158],'pdfPages':[1193,1194,1195]},'exercises':E},ensure_ascii=False,indent=2)+'\n')
(R/'exercise-checks/s15-10-report.json').write_text(json.dumps({'section':'15.10','sourceVisualPages':[1193,1194,1195],'checks':checks,'manualReview':[1,2,9,10,11,12,13,14,15,16,17,37,41,42,43,44,50,51,52,53,54,58]},ensure_ascii=False,indent=2)+'\n')
print('Saved Chapter15 Review58; numerical area',mp.nstr(areas[-1],20))

import runpy
runpy.run_path(str(R/"exercise-checks/s15-10-figures.py"))
