from calc1_core import *
import mpmath as mp
D=CalcDoc('1.6',[70,71,72],lambda n:70 if n<=9 else 71 if n<=49 else 72)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('극한 법칙·대수적 변형·조임정리','Limit laws, algebraic simplification, and squeezing'),st,('먼저 대입 가능 여부를 확인하고, 필요하면 약분·유리화 또는 한쪽 극한을 사용한다.','First check whether substitution is valid; otherwise use cancellation, rationalization, or one-sided limits.'),steps,ans,check,parts)
add(1,('x→2에서 f→4, g→−2, h→0이다. 다음 극한을 구하라: (a)f+5g, (b)g³, (c)√f, (d)3f/g, (e)g/h, (f)gh/f.','As x→2, f→4, g→−2, h→0. Find the limits of (a)f+5g, (b)g³, (c)√f, (d)3f/g, (e)g/h, and (f)gh/f.'),[('합·상수배·거듭제곱 법칙으로 (a)4+5(−2), (b)(−2)³이다. 양수 4에서 제곱근 법칙을 적용한다.','The sum, constant-multiple, and power laws give (a)4+5(−2) and (b)(−2)³. The root law applies at the positive limit 4.'),('(d),(f)는 분모 극한이 0이 아니어서 몫 법칙이 적용된다. (e)는 0이 아닌 분자가 0으로 가는 분모로 나뉘므로 유한 극한이 없고 발산 부호도 주어진 정보로 결정되지 않는다.','The quotient law applies in (d) and (f) because the denominator limits are nonzero. In (e), a nonzero numerator limit divided by a vanishing denominator has no finite limit; the divergence sign is not determined by the data.')],('(a)−6; (b)−8; (c)2; (d)−6; (e)유한 극한 없음; (f)0.','(a)−6; (b)−8; (c)2; (d)−6; (e)no finite limit; (f)0.'),('만약 (e)의 유한 극한 L이 존재한다면 g=(g/h)h의 극한은 L·0=0이 되어 −2와 모순이다.','If (e) had a finite limit L, the product identity g=(g/h)h would force its limit to be L·0=0, contradicting −2.'),list('abcdef'))
add(2,('원본 그래프에서 f의 접근값은 x=−1,0,2,3에서 각각 1,2,−1,1이고 f(−1)=3이다. g는 −1에서 2, 2에서 2로 접근하고 0의 좌우 극한은 3,1이다. 3에서 g는 양수에서 0, 음수에서 0으로 접근한다. (a)lim₂(f+g), (b)lim₀(f−g), (c)lim₋₁(fg), (d)lim₃(f/g), (e)lim₂(x²f), (f)f(−1)+lim₋₁g를 구하라.','The source graphs give limiting f-values 1,2,−1,1 at x=−1,0,2,3, with f(−1)=3. The g-limits at −1 and 2 are both 2; its limits at 0 from the left and right are 3 and 1. At 3, g approaches zero through positive values on the left and negative values on the right. Evaluate (a)lim₂(f+g), (b)lim₀(f−g), (c)lim₋₁(fg), (d)lim₃(f/g), (e)lim₂(x²f), (f)f(−1)+lim₋₁g.'),[('(a)−1+2=1. (b)왼쪽은 2−3=−1, 오른쪽은 2−1=1로 다르다. (c)1·2=2.','(a)−1+2=1. In (b), the left value 2−3=−1 differs from the right value 2−1=1. (c)1·2=2.'),('(d)분자가 양수 1에 가까우므로 왼쪽 +∞, 오른쪽 −∞이다. (e)4(−1)=−4. (f)는 구멍의 높이 1이 아니라 지정값 3을 사용한다.','In (d), the numerator approaches positive 1, giving +∞ on the left and −∞ on the right. (e)4(−1)=−4. Part (f) uses the assigned value 3, rather than the hole height 1.')],('(a)1; (b)없음; (c)2; (d)없음; (e)−4; (f)5.','(a)1; (b)does not exist; (c)2; (d)does not exist; (e)−4; (f)5.'),('원본 PDF107 격자에서 열린 점과 닫힌 점을 분리하여 읽고, 불일치 항은 두 한쪽 값을 비교했다.','Read open and filled points separately on PDF107 and compared both one-sided values for the failures.'),list('abcdef'))
x,h=s.symbols('x h',real=True)
poly=[(3,4*x*x-5*x,5),(4,2*x**3+6*x*x-9,-3),(5,(x*x+2*x)*(2*x**3-5),2),(6,(3*x*x+1)/(x*x-5*x+2),7),(7,s.sqrt(9-x**3+2*x*x),-2),(8,s.real_root(x+5,3)*(2*x*x-3*x),3),(9,((2*x**5-x**4)/(5*x*x+4))**3,-1),(11,3*x-7,-2),(12,8-x/2,6)]
for n,f,a in poly:
 value=s.simplify(f.subs(x,a));formula=tex(f)
 law=('상수·합·거듭제곱 법칙으로 각 x를 접근값으로 바꾼다. 곱은 각 극한의 곱, 분수는 0이 아닌 분모 극한으로 나누며 근호는 해당 정의역에서 연속이다.','Use the constant, sum, and power laws on each term. Products multiply limits; quotients divide by a nonzero denominator limit, and roots are continuous on their applicable domains.')
 if n==8:formula=r'\sqrt[3]{x+5}(2x^2-3x)'
 add(n,('극한 '+d(r'\lim_{x\to'+tex(a)+'}'+formula)+'을 계산하고 사용한 극한 법칙을 설명하라.','Evaluate '+d(r'\lim_{x\to'+tex(a)+'}'+formula)+' and identify the applicable limit laws.'),[law,(d(r'L='+formula.replace('x','('+tex(a)+')')+'='+tex(value)),d(r'L='+formula.replace('x','('+tex(a)+')')+'='+tex(value)))],d(tex(value)),('대입한 분모·근호 조건을 확인하고 원식의 기호 극한과 일치함을 검산했다.','Checked the substituted denominator/root conditions and agreement with a separate symbolic limit.'))
add(10,('(a)(x²+x−6)/(x−2)=x+3에 빠진 조건을 찾고, (b)x→2에서 두 식의 극한이 같은 이유를 설명하라.','(a)Identify the missing condition in (x²+x−6)/(x−2)=x+3. (b)Explain why their limits as x→2 nevertheless agree.'),[('분자는 (x−2)(x+3)이므로 약분에는 x≠2가 필요하다. 왼쪽은 2에서 정의되지 않는다.','The numerator factors as (x−2)(x+3), so cancellation requires x≠2. The left expression is undefined at 2.'),('극한은 뚫린 근방의 값만 사용하며 두 식은 그 근방에서 같다.','A limit depends only on values in a punctured neighborhood, where the expressions agree.')],('(a)x≠2를 명시해야 한다. (b)공통 극한은 5.','(a)State x≠2. (b)The common limit is 5.'),('x=2를 원식 분모에 넣으면 0, 약분식에 넣으면 5라는 차이가 함수값과 극한의 구별을 확인한다.','Substitution at 2 makes the original denominator zero but gives 5 in the extension, confirming the distinction between value and limit.'),list('ab'))
# Explicit transformations are recorded independently of symbolic limit evaluation.
items=[
(13,(x*x-2*x-8)/(x-4),4,x+2,r'\frac{(x-4)(x+2)}{x-4}=x+2',6),
(14,(x*x+3*x)/(x*x-x-12),-3,x/(x-4),r'\frac{x(x+3)}{(x+3)(x-4)}=\frac{x}{x-4}',s.Rational(3,7)),
(17,(x*x-x-6)/(3*x*x+5*x-2),-2,(x-3)/(3*x-1),r'\frac{(x-3)(x+2)}{(3x-1)(x+2)}=\frac{x-3}{3x-1}',s.Rational(5,7)),
(18,(2*x*x+9*x-5)/(x*x-25),-5,(2*x-1)/(x-5),r'\frac{(2x-1)(x+5)}{(x-5)(x+5)}=\frac{2x-1}{x-5}',s.Rational(11,10)),
(19,(x**3-27)/(x*x-9),3,(x*x+3*x+9)/(x+3),r'\frac{(x-3)(x^2+3x+9)}{(x-3)(x+3)}=\frac{x^2+3x+9}{x+3}',s.Rational(9,2)),
(20,(x+1)/(x**3+1),-1,1/(x*x-x+1),r'\frac{x+1}{(x+1)(x^2-x+1)}=\frac1{x^2-x+1}',s.Rational(1,3)),
(21,((x-3)**2-9)/x,0,x-6,r'\frac{x^2-6x}{x}=x-6',-6),
(22,(9-x)/(3-s.sqrt(x)),9,3+s.sqrt(x),r'\frac{(3-\sqrt x)(3+\sqrt x)}{3-\sqrt x}=3+\sqrt x',6),
(23,(s.sqrt(9+x)-3)/x,0,1/(s.sqrt(9+x)+3),r'\frac{\sqrt{9+x}-3}{x}=\frac1{\sqrt{9+x}+3}',s.Rational(1,6)),
(24,(2-x)/(s.sqrt(x+2)-2),2,-s.sqrt(x+2)-2,r'\frac{2-x}{\sqrt{x+2}-2}=-\sqrt{x+2}-2',-4),
(25,(1/x-s.Rational(1,3))/(x-3),3,-1/(3*x),r'\frac{(3-x)/(3x)}{x-3}=-\frac1{3x}',-s.Rational(1,9)),
(26,(1/(x-2)+s.Rational(1,2))/x,0,1/(2*(x-2)),r'\frac{1/(x-2)+1/2}{x}=\frac1{2(x-2)}',-s.Rational(1,4)),
(27,(s.sqrt(1+x)-s.sqrt(1-x))/x,0,2/(s.sqrt(1+x)+s.sqrt(1-x)),r'\frac{\sqrt{1+x}-\sqrt{1-x}}x=\frac2{\sqrt{1+x}+\sqrt{1-x}}',1),
(28,1/x-1/(x*x+x),0,1/(1+x),r'\frac1x-\frac1{x(x+1)}=\frac1{x+1}',1),
(29,(4-s.sqrt(x))/(16*x-x*x),16,1/(x*(4+s.sqrt(x))),r'\frac{4-\sqrt x}{x(16-x)}=\frac1{x(4+\sqrt x)}',s.Rational(1,128)),
(30,(x*x-4*x+4)/(x**4-3*x*x-4),2,(x-2)/((x+2)*(x*x+1)),r'\frac{(x-2)^2}{(x-2)(x+2)(x^2+1)}=\frac{x-2}{(x+2)(x^2+1)}',0),
(31,1/(x*s.sqrt(1+x))-1/x,0,-1/(s.sqrt(1+x)*(1+s.sqrt(1+x))),r'\frac{1-\sqrt{1+x}}{x\sqrt{1+x}}=-\frac1{\sqrt{1+x}(1+\sqrt{1+x})}',-s.Rational(1,2)),
(32,(s.sqrt(x*x+9)-5)/(x+4),-4,(x-4)/(s.sqrt(x*x+9)+5),r'\frac{\sqrt{x^2+9}-5}{x+4}=\frac{x^2-16}{(x+4)(\sqrt{x^2+9}+5)}=\frac{x-4}{\sqrt{x^2+9}+5}',-s.Rational(4,5))]
for n,f,a,g,work,value in items:
 add(n,('다음 극한을 구하라. '+d(r'\lim_{x\to'+tex(a)+'}'+tex(f)),'Find the limit '+d(r'\lim_{x\to'+tex(a)+'}'+tex(f))),[('대입하면 0/0 꼴이다. 접근점 자체를 제외하고 인수분해·통분 또는 켤레식을 곱한다.','Substitution produces 0/0. Away from the approach point, factor, combine fractions, or multiply by a conjugate.'),(d(work),d(work)),('변형한 식은 접근점에서 분모가 0이 아니므로 직접 대입한다.','The transformed expression has a nonzero denominator at the approach point, so substitute directly.')],d(tex(value)),('뚫린 근방에서 두 식의 차를 0으로 단순화하고, 변형식의 대입값과 원식의 기호 극한을 비교했다.','Simplified the difference of the expressions to zero on the punctured domain and compared substitution in the transformed form with a symbolic limit of the original.'))
 assert s.simplify(f-g)==0,(n,s.simplify(f-g))
 assert s.limit(f,x,a)==value
 D.checks.append({'number':n,'method':'algebraic identity and symbolic limit','value':str(value)})
for n,f,a in [(15,(x*x+5*x+4)/(x-2),2),(16,(x*x+3*x)/(x*x-x-12),4)]:
 add(n,('다음 극한의 존재 여부를 판단하라. '+d(r'\lim_{x\to'+str(a)+'}'+tex(f)),'Determine whether this limit exists: '+d(r'\lim_{x\to'+str(a)+'}'+tex(f))),[('분자는 접근점에서 양수이고, 분모는 왼쪽에서 음수 0, 오른쪽에서 양수 0으로 간다.','The numerator approaches a positive number; the denominator approaches zero through negative values on the left and positive values on the right.'),(d(r'\lim_{x\to'+str(a)+r'^-}f(x)=-\infty,\quad\lim_{x\to'+str(a)+r'^+}f(x)=+\infty'),d(r'\lim_{x\to'+str(a)+r'^-}f(x)=-\infty,\quad\lim_{x\to'+str(a)+r'^+}f(x)=+\infty'))],('양쪽 극한은 존재하지 않는다.','The two-sided limit does not exist.'),('한쪽 기호 극한으로 서로 반대인 발산 방향을 확인했다.','Separate symbolic one-sided limits confirm opposite divergence directions.'))
for n,f,g,work,value in [(33,((x+h)**3-x**3)/h,3*x*x+3*x*h+h*h,r'\frac{3x^2h+3xh^2+h^3}{h}=3x^2+3xh+h^2',3*x*x),(34,(1/(x+h)**2-1/x**2)/h,-(2*x+h)/(x*x*(x+h)**2),r'\frac{x^2-(x+h)^2}{hx^2(x+h)^2}=-\frac{2x+h}{x^2(x+h)^2}',-2/x**3)]:
 add(n,('x를 고정하여 '+d(r'\lim_{h\to0}'+tex(f))+'을 구하라.','With x fixed, evaluate '+d(r'\lim_{h\to0}'+tex(f))),[('h≠0에서 분자를 전개하거나 통분하여 h를 약분한다.','For h≠0, expand or combine the numerator and cancel h.'),(d(work),d(work))],d(tex(value))+(' (x≠0)'if n==34 else''),('차분몫의 원함수 x³ 또는 x⁻²를 미분한 값과 독립적으로 일치한다. 34번은 원식 때문에 x≠0이 필요하다.','An independent derivative of x³ or x⁻² gives the same result. The original expression in 34 requires x≠0.'))
 assert s.simplify(f-g)==0
 assert s.simplify(s.limit(f,h,0)-value)==0
for n,form,fn,work,value in [(35,r'\frac{x}{\sqrt{1+3x}-1}',lambda z:(math.sqrt(1+3*z)+1)/3,r'\frac{x}{\sqrt{1+3x}-1}=\frac{\sqrt{1+3x}+1}{3}',s.Rational(2,3)),(36,r'\frac{\sqrt{3+x}-\sqrt3}{x}',lambda z:1/(math.sqrt(3+z)+math.sqrt(3)),r'\frac{\sqrt{3+x}-\sqrt3}{x}=\frac1{\sqrt{3+x}+\sqrt3}',1/(2*s.sqrt(3)))]:
 table='; '.join(f'{z:g} → {fn(z):.8f}'for z in [-.1,-.01,-.001,.001,.01,.1])
 add(n,('함수 '+m('f(x)='+form)+'의 x→0 극한을 (a)그래프, (b)수치표로 추정하고 (c)극한 법칙으로 정확히 구하라.'+(' 그래프는 소수 둘째 자리, 표는 넷째 자리까지 추정한다.'if n==36 else''),'Estimate the limit at 0 of '+m('f(x)='+form)+' using (a)a graph and (b)a table, then (c)find it exactly with limit laws.'+(' Give the graph estimate to two decimals and the table estimate to four decimals.'if n==36 else'')),[('(a)확대 그래프는 '+f'{float(value):.2f}'+' 부근에 접근한다.','(a)The zoomed graph approaches about '+f'{float(value):.2f}'+'.'),('(b)'+table,'(b)'+table),(d(work),d(work)),('(c)변형된 연속식에 0을 대입한다.','(c)Substitute zero into the continuous transformed expression.')],d(tex(value))+f' ≈ {float(value):.4f}',('켤레식을 이용해 작은 두 수의 차를 빼지 않고 계산했다. 원식과 변형식의 값을 0이 아닌 양·음 입력에서 비교했다.','Used conjugates to avoid cancellation and compared the original and transformed values at nonzero positive and negative inputs.'),list('abc'))
 D.fig(n,[panel('Rationalized function near zero',(-.2,.2,float(value)-.15,float(value)+.15),[samples(fn,-.2,-.00001),samples(fn,.00001,.2)],[(0,float(value),'open')])])
for n,form,lower,upper,ko,en,fn in [(37,r'x^2\cos(20\pi x)',-x*x,x*x,'|cos(20πx)|≤1에 x²≥0을 곱하면 −x²≤x²cos(20πx)≤x²이다.','Multiply |cos(20πx)|≤1 by x²≥0 to obtain −x²≤x²cos(20πx)≤x².',lambda z:z*z*math.cos(20*math.pi*z)),(38,r'\sqrt{x^3+x^2}\sin(\pi/x)',-s.sqrt(x**3+x*x),s.sqrt(x**3+x*x),'0 근처에서 √(x³+x²)=|x|√(1+x)≥0이고 |sin(π/x)|≤1이므로 부호가 반대인 두 근호로 감싼다.','Near zero, √(x³+x²)=|x|√(1+x)≥0 and |sin(π/x)|≤1, giving bounds with opposite signs.',lambda z:abs(z)*math.sqrt(1+z)*math.sin(math.pi/z)),(41,r'x^4\cos(2/x)',-x**4,x**4,'|cos(2/x)|≤1에 음이 아닌 x⁴을 곱하면 −x⁴≤x⁴cos(2/x)≤x⁴이다.','Multiplying |cos(2/x)|≤1 by nonnegative x⁴ gives −x⁴≤x⁴cos(2/x)≤x⁴.',None),(42,r'\sqrt x[1+\sin^2(2\pi/x)]',s.sqrt(x),2*s.sqrt(x),'x>0에서 0≤sin²(2π/x)≤1이므로 √x≤√x[1+sin²(2π/x)]≤2√x이다.','For x>0, 0≤sin²(2π/x)≤1 implies √x≤√x[1+sin²(2π/x)]≤2√x.',None)]:
 side='^+'if n==42 else''
 add(n,('조임정리를 이용하여 '+d(r'\lim_{x\to0'+side+'}'+form+'=0')+'임을 증명하라.'+(' 세 함수를 한 화면에 그려라.'if n in [37,38]else''),'Prove '+d(r'\lim_{x\to0'+side+'}'+form+'=0')+' using the Squeeze Theorem.'+(' Plot all three functions together.'if n in [37,38]else'')),[(ko,en),(d(tex(lower)+r'\longrightarrow0,\quad '+tex(upper)+r'\longrightarrow0'),d(tex(lower)+r'\longrightarrow0,\quad '+tex(upper)+r'\longrightarrow0')),('두 경계의 극한이 같으므로 그 사이 함수의 극한도 0이다.','Both bounds approach the same number, so the middle function also approaches zero.')],d('0'),('각 승수는 사용한 근방에서 음이 아니므로 부등호 방향이 보존된다. 진동인자 자체에 극한이 있다는 가정은 쓰지 않았다.','Each multiplier is nonnegative on the stated neighborhood, preserving the inequalities. No limit of the oscillating factor itself is assumed.'))
 if fn:
  lo=s.lambdify(x,lower,'math');up=s.lambdify(x,upper,'math')
  D.fig(n,[panel('Lower bound, oscillating function, upper bound',(-.5,.5,-.7,.7),[samples(lo,-.5,.5),samples(fn,-.5,-.0001,900),samples(fn,.0001,.5,900),samples(up,-.5,.5)])])
for n,a,b,c,value,st in [(39,4*x-9,x*x-4*x+7,4,7,('x≥0에서 4x−9≤f(x)≤x²−4x+7이다. x→4의 f 극한을 구하라.','For x≥0, 4x−9≤f(x)≤x²−4x+7. Find the limit of f as x→4.')),(40,2*x,x**4-x*x+2,1,2,('모든 x에서 2x≤g(x)≤x⁴−x²+2이다. x→1의 g 극한을 구하라.','For all x, 2x≤g(x)≤x⁴−x²+2. Find the limit of g as x→1.'))]:
 add(n,st,[(d(r'\lim_{x\to'+str(c)+'}('+tex(a)+')='+str(value)+r'=\lim_{x\to'+str(c)+'}('+tex(b)+')'),d(r'\lim_{x\to'+str(c)+'}('+tex(a)+')='+str(value)+r'=\lim_{x\to'+str(c)+'}('+tex(b)+')')),('다항식의 연속성과 조임정리를 적용한다.','Apply polynomial continuity and the Squeeze Theorem.')],d(str(value)),('위·아래 식의 차는 '+m(tex(s.factor(b-a)))+'으로, 접근점에서 0이며 근방에서 음이 아니다.','The upper-minus-lower difference is '+m(tex(s.factor(b-a)))+', which vanishes at the approach point and is nonnegative nearby.'))
absitems=[(43,s.Abs(x+4)-2*x,-4,'+-',8,'절댓값도 연속이므로 |0|−2(−4)=8이다.','Absolute value is continuous, so |0|−2(−4)=8.'),(44,s.Abs(x+4)/(2*x+8),-4,'+-',None,'x<−4에서는 −1/2, x>−4에서는 1/2이다.','The expression equals −1/2 for x<−4 and 1/2 for x>−4.'),(45,(2*x-1)/s.Abs(2*x**3-x*x),s.Rational(1,2),'-',-4,'x<1/2이고 0 근처를 제외하면 분모=x²(1−2x)이므로 식은 −1/x²이다.','For x<1/2 near the approach point, the denominator is x²(1−2x), so the expression is −1/x².'),(46,(2-s.Abs(x))/(2+x),-2,'+-',1,'−2의 충분히 작은 근방에서 x<0, |x|=−x이므로 식은 (2+x)/(2+x)=1이다.','In a sufficiently small neighborhood of −2, x<0 and |x|=−x, making the quotient (2+x)/(2+x)=1.'),(47,1/x-1/s.Abs(x),0,'-',-s.oo,'x<0이면 |x|=−x이므로 식은 2/x이고 −∞로 발산한다.','For x<0, |x|=−x, so the expression is 2/x and diverges to −∞.'),(48,1/x-1/s.Abs(x),0,'+',0,'x>0이면 |x|=x이므로 식은 정확히 0이다.','For x>0, |x|=x, so the expression is identically zero.')]
for n,f,a,side,value,ko,en in absitems:
 form=d(r'\lim_{x\to'+tex(a)+('^'+side if side!='+-'else'')+'}'+tex(f))
 add(n,('절댓값의 부호를 나누어 '+form+'을 구하라.','Resolve the absolute-value signs to evaluate '+form),[(ko,en),('한쪽 극한을 구할 때에는 그쪽에서만 유효한 부호를 사용한다. 양쪽 극한은 두 값이 같아야 한다.','Use the sign valid on the specified side. A two-sided limit requires agreement between both sides.')],d(tex(value))if value is not None else('좌우가 달라 극한이 없다.','The one-sided limits disagree, so the limit does not exist.'),('각 한쪽 근방에서 절댓값을 제거한 식을 원식과 대조했다.','Compared the sign-resolved expression with the original on each relevant one-sided neighborhood.'))
sgndef=r'\operatorname{sgn}x=\begin{cases}-1&x<0\\0&x=0\\1&x>0\end{cases}'
add(49,('부호함수 '+d(sgndef)+'에 대해 (a)그래프를 그리고 (b)(i)0⁺, (ii)0⁻, (iii)0에서의 극한, (iv)0에서 |sgn x|의 극한을 구하라.','For the sign function '+d(sgndef)+', (a)sketch its graph and (b)find the limits at (i)0⁺, (ii)0⁻, (iii)0, and (iv)the limit of |sgn x| at 0.'),[('양의 입력에서 1, 음의 입력에서 −1이므로 좌우가 다르다. 절댓값을 취하면 x≠0에서 항상 1이다.','The value is 1 for positive inputs and −1 for negative inputs, so the sides disagree. Taking absolute values gives 1 for every x≠0.')],('(b)(i)1, (ii)−1, (iii)없음, (iv)1.','(b)(i)1, (ii)−1, (iii)does not exist, (iv)1.'),('sgn 0=0은 열린 근방의 두 상수값이나 절댓값 극한을 바꾸지 않는다.','The assignment sgn 0=0 does not change either punctured-neighborhood value or the absolute-value limit.'),['a','b(i)','b(ii)','b(iii)','b(iv)'])
D.fig(49,[panel('Sign function',(-3,3,-1.5,1.5),[[(-3,-1),(0,-1)],[(0,1),(3,1)]],[(0,-1,'open'),(0,0),(0,1,'open')],yticks=[-1,0,1])])
add(50,('g(x)=sgn(sin x)이다. (a)0⁺,0⁻,0,π⁺,π⁻,π의 순서로 극한을 구하고, (b)양쪽 극한이 없는 모든 a를 찾으며 (c)그래프를 그려라.','Let g(x)=sgn(sin x). (a)Find the limits at 0⁺,0⁻,0,π⁺,π⁻,π in that order. (b)Find every a where the two-sided limit fails. (c)Sketch the graph.'),[('sin x는 (kπ,(k+1)π)에서 부호 (−1)ᵏ을 가지며 kπ에서는 0이다.','On (kπ,(k+1)π), sin x has sign (−1)ᵏ; at kπ its sign value is zero.'),('모든 정수배 kπ에서 부호가 바뀌고, 그 사이에서는 상수이다.','The sign changes at every integer multiple kπ and is constant between these points.')],('(a)1,−1,없음,−1,1,없음. (b)a=kπ(k∈ℤ).','(a)1,−1,does not exist,−1,1,does not exist. (b)a=kπ for k∈ℤ.'),('π의 오른쪽은 sin x<0, 왼쪽은 sin x>0임을 확인하여 0 근방과 부호 순서가 반대임을 검산했다.','Immediately right of π the sine is negative and immediately left it is positive, confirming the reversal from the signs around zero.'),['a(i)','a(ii)','a(iii)','a(iv)','a(v)','a(vi)','b','c'])
cs=[];dots=[]
for k in range(-2,2):
 y=(-1)**k;cs.append([(k*math.pi,y),((k+1)*math.pi,y)]);dots.extend([(k*math.pi,y,'open'),((k+1)*math.pi,y,'open')])
dots += [(k*math.pi,0)for k in range(-2,3)]
D.fig(50,[panel('Sign of sine; repeats every 2 pi',(-2*math.pi,2*math.pi,-1.5,1.5),cs,dots,xticks=[k*math.pi for k in range(-2,3)],yticks=[-1,0,1])])
add(51,('g(x)=(x²+x−6)/|x−2|이다. (a)2⁺와 2⁻의 극한, (b)2의 양쪽 극한을 구하고 (c)그래프를 그려라.','For g(x)=(x²+x−6)/|x−2|, (a)find the limits at 2⁺ and 2⁻, (b)decide the two-sided limit at 2, and (c)sketch the graph.'),[(d(r'g(x)=(x+3)\frac{x-2}{|x-2|}=\begin{cases}-x-3&x<2\\x+3&x>2\end{cases}'),d(r'g(x)=(x+3)\frac{x-2}{|x-2|}=\begin{cases}-x-3&x<2\\x+3&x>2\end{cases}')),('오른쪽은 5, 왼쪽은 −5로 접근한다.','The right side approaches 5 and the left side approaches −5.')],('(a)(i)5, (ii)−5. (b)존재하지 않는다.','(a)(i)5, (ii)−5. (b)Does not exist.'),('분자 인수 (x−2)를 절댓값 분모와 약분할 때 남는 부호를 보존했다. x=2에서는 정의되지 않는다.','Preserved the sign left after dividing the numerator factor (x−2) by the absolute-value denominator. The function is undefined at 2.'),['a(i)','a(ii)','b','c'])
D.fig(51,[panel('Opposite linear branches',(-3,5,-8,9),[[(-3,0),(2,-5)],[(2,5),(5,8)]],[(2,-5,'open'),(2,5,'open')])])
add(52,('f(x)=x²+1(x<1), (x−2)²(x≥1)이다. (a)1의 좌우 극한, (b)양쪽 극한 존재 여부, (c)그래프를 구하라.','Let f(x)=x²+1 for x<1 and (x−2)² for x≥1. Find (a)the one-sided limits at 1, (b)whether the two-sided limit exists, and (c)the graph.'),[('왼쪽 식에 1을 대입하면 2, 오른쪽 식에 대입하면 1이다. 실제 f(1)=1은 오른쪽 조각에 속한다.','Substitution in the left formula gives 2 and in the right formula gives 1. The assigned value f(1)=1 belongs to the right piece.')],('(a)왼쪽 2, 오른쪽 1. (b)없음.','(a)Left 2, right 1. (b)Does not exist.'),('그래프에서 (1,2)는 열린 점, (1,1)은 닫힌 점으로 표시하여 조건 x<1과 x≥1을 보존했다.','The graph uses an open point at (1,2) and a filled point at (1,1), preserving the inequalities x<1 and x≥1.'),list('abc'))
D.fig(52,[panel('Two quadratic pieces',(-2,4,-.5,6),[samples(lambda z:z*z+1,-2,1),samples(lambda z:(z-2)**2,1,4)],[(1,2,'open'),(1,1)])])
add(53,('B(t)=4−t/2(t<2), √(t+c)(t≥2)이다. t→2에서 극한이 존재하게 하는 c를 구하라.','Let B(t)=4−t/2 for t<2 and √(t+c) for t≥2. Find c so that the limit as t→2 exists.'),[('왼쪽 극한은 4−1=3이다. 오른쪽 극한 √(2+c)가 3이어야 한다.','The left limit is 4−1=3. The right limit √(2+c) must equal 3.'),(d(r'\sqrt{2+c}=3\iff 2+c=9\iff c=7'),d(r'\sqrt{2+c}=3\iff 2+c=9\iff c=7'))],d(r'c=7,\quad L=3'),('c=7이면 2 근방에서 근호 내부가 양수이고 두 한쪽 극한이 정확히 3이다.','For c=7 the radicand is positive near 2 and both one-sided limits equal 3.'))
add(54,('g(x)=x(x<1), g(1)=3, g(x)=2−x²(1<x≤2), g(x)=x−3(x>2)이다. (a)(i)lim₁₋g,(ii)lim₁g,(iii)g(1),(iv)lim₂₋g,(v)lim₂₊g,(vi)lim₂g를 구하고 (b)그려라.','Let g(x)=x for x<1, g(1)=3, g(x)=2−x² for 1<x≤2, and g(x)=x−3 for x>2. (a)Find (i)lim₁₋g,(ii)lim₁g,(iii)g(1),(iv)lim₂₋g,(v)lim₂₊g,(vi)lim₂g. (b)Sketch the graph.'),[('1에서는 두 접근값이 1로 같지만 지정값은 3이다. 2에서는 왼쪽 2−4=−2, 오른쪽 2−3=−1이다.','At 1 both limiting values equal 1, while the assigned value is 3. At 2 the left value is 2−4=−2 and the right value is 2−3=−1.')],('(a)1,1,3,−2,−1,없음.','(a)1,1,3,−2,−1,does not exist.'),('1의 단일점 변경은 극한을 바꾸지 않으며, 2의 닫힌 점 −2는 좌우 불일치를 해소하지 않는다.','The single-point reassignment at 1 does not affect its limit; the filled value −2 at 2 does not resolve the disagreement of its one-sided limits.'),['a(i)','a(ii)','a(iii)','a(iv)','a(v)','a(vi)','b'])
D.fig(54,[panel('Hole at one and jump at two',(-1,4,-3,4),[[(-1,-1),(1,1)],samples(lambda z:2-z*z,1,2),[(2,-1),(4,1)]],[(1,1,'open'),(1,3),(2,-2),(2,-1,'open')],xticks=[-1,0,1,2,3,4])])
add(55,('바닥함수 ⌊x⌋에 대해 (a)−2⁺,−2,−2.4의 극한, (b)정수 n의 좌우 극한, (c)양쪽 극한이 존재하는 모든 a를 구하라.','For the floor function ⌊x⌋, find (a)the limits at −2⁺,−2,−2.4, (b)the one-sided limits at an integer n, and (c)all a with a two-sided limit.'),[('정수 n의 바로 왼쪽에서는 n−1, 바로 오른쪽에서는 n이다. 정수가 아닌 a는 한 계단의 내부에 있다.','Immediately left of an integer n the value is n−1; immediately right it is n. A noninteger a lies inside one constant step.')],('(a)−2,없음,−3. (b)왼쪽 n−1,오른쪽 n. (c)a∉ℤ.','(a)−2,does not exist,−3. (b)Left n−1,right n. (c)a∉ℤ.'),('−2.4는 (−3,−2)에 있어 바닥값 −3이다. 음수에서 0 쪽으로 버림한 −2와 혼동하지 않는다.','The number −2.4 lies in (−3,−2), so its floor is −3, not the truncation-toward-zero value −2.'),['a(i)','a(ii)','a(iii)','b(i)','b(ii)','c'])
add(56,('−π≤x≤π에서 f(x)=⌊cos x⌋이다. (a)그래프를 그리고 (b)0, (π/2)⁻, (π/2)⁺, π/2의 극한을 구하라. (c)극한이 존재하는 a를 기술하라.','For −π≤x≤π, let f(x)=⌊cos x⌋. (a)Sketch the graph. (b)Find limits at 0,(π/2)⁻,(π/2)⁺,π/2. (c)Describe the points a where a limit exists.'),[('|x|>π/2이면 −1, 0<|x|≤π/2이면 0, x=0이면 1이다.','The value is −1 for |x|>π/2, 0 for 0<|x|≤π/2, and 1 at x=0.'),('0에서는 양쪽의 값이 0이다. ±π/2에서는 계단이 바뀐다.','At zero both sides have value zero. The steps change at ±π/2.')],('(b)0,0,−1,없음. (c)내부 −π<a<π에서는 a≠±π/2. 끝점 ±π의 정의역 내 한쪽 극한도 −1이다.','(b)0,0,−1,does not exist. (c)For interior points −π<a<π, all a except ±π/2. The domain-relative one-sided limits at ±π also equal −1.'),('cos 0=1이어서 f(0)=1이지만 주변의 cos는 1보다 작아 바닥값이 0이다. 끝점은 양쪽 접근이 아닌 한쪽 접근임을 구분했다.','Although cos 0=1 gives f(0)=1, nearby cosine values are below 1 and have floor zero. Endpoint limits are explicitly distinguished as one-sided.'),['a','b(i)','b(ii)','b(iii)','b(iv)','c'])
D.fig(56,[panel('Floor of cosine',(-math.pi,math.pi,-1.5,1.5),[[(-math.pi,-1),(-math.pi/2,-1)],[(-math.pi/2,0),(0,0)],[(0,0),(math.pi/2,0)],[(math.pi/2,-1),(math.pi,-1)]],[(-math.pi,-1),(-math.pi/2,-1,'open'),(-math.pi/2,0),(0,0,'open'),(0,1),(math.pi/2,0),(math.pi/2,-1,'open'),(math.pi,-1)],xticks=[-math.pi,-math.pi/2,0,math.pi/2,math.pi],yticks=[-1,0,1])])
add(57,('f(x)=⌊x⌋+⌊−x⌋에서 x→2의 극한은 존재하지만 f(2)와 다름을 보여라.','Show that f(x)=⌊x⌋+⌊−x⌋ has a limit as x→2 that differs from f(2).'),[('정수가 아닌 x에 대해 n<x<n+1이면 −n−1<−x<−n이므로 두 바닥값의 합은 n+(−n−1)=−1이다.','If n<x<n+1 for a noninteger x, then −n−1<−x<−n, so the floor values sum to n+(−n−1)=−1.'),('0<|x−2|<1인 모든 x는 정수가 아니므로 f(x)=−1이다. 그러나 f(2)=2−2=0이다.','Every x with 0<|x−2|<1 is noninteger and has f(x)=−1. However, f(2)=2−2=0.')],d(r'\lim_{x\to2}f(x)=-1\ne0=f(2)'),('양쪽 모두 동일한 뚫린 근방에서 상수 −1임을 확인하므로 수치 추정에 의존하지 않는다.','The function is identically −1 on a full punctured neighborhood, proving both sides without numerical estimation.'))
add(58,('로런츠 길이 모형 L=L₀√(1−v²/c²)에서 v→c⁻의 극한을 해석하고 왼쪽 접근이 필요한 이유를 설명하라.','For the Lorentz length model L=L₀√(1−v²/c²), find and interpret the limit as v→c⁻ and explain why the approach is from the left.'),[('v→c⁻일 때 1−v²/c²→0⁺이므로 제곱근과 고정 상수 L₀의 곱은 0으로 간다.','As v→c⁻, 1−v²/c²→0⁺, so the root times the fixed constant L₀ tends to zero.'),('이 모형에서 관찰 길이는 속도가 c에 접근할수록 0에 가까워진다. 실수 근호와 주어진 물리 범위는 v<c 쪽이다.','In this model the observed length approaches zero as the speed approaches c. The real-valued formula and stated physical range require approach with v<c.')],d(r'\lim_{v\to c^-}L=0'),('v>c이면 근호 내부가 음수가 되어 이 실수값 모형의 오른쪽 접근을 사용할 수 없다.','For v>c the radicand is negative, excluding a right-hand approach within this real-valued model.'))
add(59,('임의의 다항식 p와 실수 a에 대해 lim(x→a)p(x)=p(a)를 극한 법칙으로 증명하라.','Prove from the limit laws that lim(x→a)p(x)=p(a) for any polynomial p and real a.'),[(d(r'p(x)=\sum_{k=0}^{n}c_kx^k'),d(r'p(x)=\sum_{k=0}^{n}c_kx^k')),('lim x=a에서 거듭제곱 법칙으로 lim xᵏ=aᵏ이다. 상수배 법칙과 유한 합 법칙을 차례로 적용한다.','Starting from lim x=a, the power law gives lim xᵏ=aᵏ. Apply constant multiplication and the finite-sum law term by term.')],d(r'\lim_{x\to a}p(x)=\sum_{k=0}^{n}c_ka^k=p(a)'),('k=0인 상수항은 상수 극한 법칙으로 처리하며 무한급수에 관한 가정은 필요하지 않다.','The k=0 term uses the constant-limit law, and no assertion about infinite series is needed.'))
add(60,('유리함수 r의 정의역에 있는 a에서 lim(x→a)r(x)=r(a)임을 다항식 극한을 이용해 증명하라.','Use polynomial limits to prove lim(x→a)r(x)=r(a) whenever a belongs to the domain of the rational function r.'),[('r=p/q로 쓰면 정의역 조건은 q(a)≠0이다. 각 다항식의 극한은 p(a),q(a)이다.','Write r=p/q. Its domain condition gives q(a)≠0, and the polynomial limits are p(a) and q(a).'),('분모 극한이 0이 아니므로 몫 법칙을 적용한다.','Since the denominator limit is nonzero, the quotient law applies.')],d(r'\lim_{x\to a}\frac{p(x)}{q(x)}=\frac{p(a)}{q(a)}=r(a)'),('q(a)=0인 구멍이나 점근선은 명제의 정의역 가정에서 제외되어 있다.','Zeros of q, including holes or possible asymptotes, are excluded by the domain hypothesis.'))
add(61,('lim(x→1)(f(x)−8)/(x−1)=10일 때 lim(x→1)f(x)를 구하라.','Given lim(x→1)(f(x)−8)/(x−1)=10, determine lim(x→1)f(x).'),[(d(r'f(x)=8+(x-1)\frac{f(x)-8}{x-1}\quad(x\ne1)'),d(r'f(x)=8+(x-1)\frac{f(x)-8}{x-1}\quad(x\ne1)')),('곱의 두 극한은 0과 10이므로 결과는 8+0·10이다.','The two factors have limits 0 and 10, giving 8+0·10.')],d('8'),('이 등식은 뚫린 근방에서 성립하므로 f(1)의 실제 값에 대한 가정은 없다.','The identity holds on a punctured neighborhood and makes no assumption about the assigned value f(1).'))
add(62,('lim(x→0)f(x)/x²=5이다. (a)lim f(x), (b)lim f(x)/x를 구하라.','Assume lim(x→0)f(x)/x²=5. Find (a)lim f(x) and (b)lim f(x)/x.'),[(d(r'f(x)=x^2\frac{f(x)}{x^2},\quad\frac{f(x)}x=x\frac{f(x)}{x^2}\quad(x\ne0)'),d(r'f(x)=x^2\frac{f(x)}{x^2},\quad\frac{f(x)}x=x\frac{f(x)}{x^2}\quad(x\ne0)')),('각각 0·5와 0·5로 극한을 계산한다.','The product limits are 0·5 in both cases.')],d(r'\text{(a) }0,\quad\text{(b) }0'),('주어진 비가 유한값 5로 가므로 근방에서 유계이며 x 또는 x²을 곱하면 0이 된다.','The given quotient approaches finite 5 and is therefore bounded nearby; multiplication by x or x² forces the product to zero.'),list('ab'))
add(63,('유리수 x에서는 f(x)=x², 무리수 x에서는 f(x)=0이다. x→0에서 f의 극한을 증명하라.','Define f(x)=x² at rational inputs and f(x)=0 at irrational inputs. Prove its limit as x→0.'),[('유리수인지 여부와 관계없이 0≤f(x)≤x²이다.','Regardless of rationality, 0≤f(x)≤x².'),('양쪽 경계가 0으로 가므로 조임정리로 극한은 0이다.','Both bounds approach zero, so the Squeeze Theorem gives a zero limit.')],d(r'\lim_{x\to0}f(x)=0'),('임의의 ε>0에 δ=√ε를 고르면 |x|<δ에서 |f(x)|≤x²<ε로 직접 확인할 수도 있다.','For any ε>0, choosing δ=√ε gives |f(x)|≤x²<ε whenever |x|<δ, providing a direct check.'))
for n,product in [(64,False),(65,True)]:
 op='곱'if product else'합';enop='product'if product else'sum'
 formula=r'f(x)=\operatorname{sgn}(x-a),\quad g(x)='+(''if product else'-')+r'\operatorname{sgn}(x-a)'
 add(n,(f'f와 g 각각의 x→a 극한은 없지만 {op}의 극한은 존재하는 예를 구성하라.',f'Construct f and g whose individual limits at a fail but whose {enop} has a limit.'),[(d(formula),d(formula)),('각 함수는 a의 좌우에서 서로 다른 ±1에 접근한다.','Each function approaches different values ±1 on the two sides of a.'),('x≠a에서 '+('fg=1'if product else'f+g=0')+'이므로 그 식의 극한은 존재한다.','For x≠a, '+('fg=1'if product else'f+g=0')+', so that expression has a limit.')],d(r'\lim_{x\to a}'+('f(x)g(x)=1'if product else'[f(x)+g(x)]=0')),('각 개별 함수의 두 한쪽 극한과 합성된 식의 상수값을 따로 확인했다.','Checked the two one-sided limits of each individual function and the constant value of the combined expression separately.'))
add(66,('극한 '+d(r'\lim_{x\to2}\frac{\sqrt{6-x}-2}{\sqrt{3-x}-1}')+'을 구하라.','Evaluate '+d(r'\lim_{x\to2}\frac{\sqrt{6-x}-2}{\sqrt{3-x}-1}')),[(d(r'\sqrt{6-x}-2=\frac{2-x}{\sqrt{6-x}+2},\quad\sqrt{3-x}-1=\frac{2-x}{\sqrt{3-x}+1}'),d(r'\sqrt{6-x}-2=\frac{2-x}{\sqrt{6-x}+2},\quad\sqrt{3-x}-1=\frac{2-x}{\sqrt{3-x}+1}')),(d(r'\frac{\sqrt{6-x}-2}{\sqrt{3-x}-1}=\frac{\sqrt{3-x}+1}{\sqrt{6-x}+2}\longrightarrow\frac24'),d(r'\frac{\sqrt{6-x}-2}{\sqrt{3-x}-1}=\frac{\sqrt{3-x}+1}{\sqrt{6-x}+2}\longrightarrow\frac24'))],d('1/2'),('x≠2에서만 공통인자 2−x를 약분했으며, 변형식 분모는 접근점에서 4로 0이 아니다.','Cancelled the common factor 2−x only for x≠2; the transformed denominator approaches nonzero 4.'))
add(67,('lim(x→−2)(3x²+ax+a+3)/(x²+x−2)가 유한하게 존재하도록 하는 a가 있는지 판단하고 극한값도 구하라.','Determine whether a can make lim(x→−2)(3x²+ax+a+3)/(x²+x−2) finite, and find the resulting limit.'),[('분모=(x+2)(x−1)이므로 분자도 −2에서 0이어야 한다. 대입하면 15−a=0이다.','The denominator is (x+2)(x−1), so the numerator must also vanish at −2. Substitution gives 15−a=0.'),(d(r'a=15:\quad\frac{3x^2+15x+18}{x^2+x-2}=\frac{3(x+2)(x+3)}{(x+2)(x-1)}=\frac{3(x+3)}{x-1}'),d(r'a=15:\quad\frac{3x^2+15x+18}{x^2+x-2}=\frac{3(x+2)(x+3)}{(x+2)(x-1)}=\frac{3(x+3)}{x-1}'))],d(r'a=15,\quad L=-1'),('a≠15이면 분자 극한이 0이 아니고 분모 부호가 바뀌어 유한 양쪽 극한이 불가능하므로 이 값은 유일하다.','If a≠15, the numerator has a nonzero limit and the denominator changes sign, excluding a finite two-sided limit; the choice is unique.'))
add(68,('고정 원 C₁:(x−1)²+y²=1과 원점 중심 반지름 r인 원 C₂가 있다. P=(0,r), Q는 위쪽 교점, R은 직선 PQ의 x절편이다. r→0⁺일 때 R의 위치를 구하라.','A fixed circle C₁ has equation (x−1)²+y²=1. Circle C₂ is centered at the origin with radius r. Let P=(0,r), let Q be their upper intersection, and let R be the x-intercept of line PQ. Find the limiting position of R as r→0⁺.'),[('두 원 식을 빼면 2x=r²이다. 0<r<2에서 위쪽 교점은 다음과 같다.','Subtracting the circle equations gives 2x=r². For 0<r<2, the upper intersection is'),(d(r'Q=\left(\frac{r^2}{2},r\sqrt{1-r^2/4}\right)'),d(r'Q=\left(\frac{r^2}{2},r\sqrt{1-r^2/4}\right)')),(d(r'R_x=\frac{r(r^2/2)}{r-r\sqrt{1-r^2/4}}=\frac{r^2}{2(1-\sqrt{1-r^2/4})}=2\left(1+\sqrt{1-r^2/4}\right)'),d(r'R_x=\frac{r(r^2/2)}{r-r\sqrt{1-r^2/4}}=\frac{r^2}{2(1-\sqrt{1-r^2/4})}=2\left(1+\sqrt{1-r^2/4}\right)'))],d(r'R\longrightarrow(4,0)'),('구한 Q를 두 원에 대입하고 P,Q,R의 기울기가 같은지 확인했다. r=.5와 .1에서 Rₓ≈3.93649,3.99750으로 4에 접근한다.','Substituted Q into both circles and checked collinearity of P,Q,R. At r=.5 and .1, Rₓ≈3.93649 and 3.99750, approaching 4.'))
pps=[]
for rad in [1,.4]:
 qx=rad*rad/2;qy=rad*math.sqrt(1-rad*rad/4);rx=2*(1+math.sqrt(1-rad*rad/4))
 circles=[[(1+math.cos(t),math.sin(t))for t in [2*math.pi*k/200 for k in range(201)]],[(rad*math.cos(t),rad*math.sin(t))for t in [2*math.pi*k/200 for k in range(201)]],[(0,rad),(rx,0)]]
 pps.append(panel(f'Circles and line PQ: r={rad:g}; R x={rx:.4f}',(-1.2,4.3,-1.2,1.4),circles,[(0,rad),(qx,qy),(rx,0)],xticks=[-1,0,1,2,3,4]))
D.fig(68,pps,('서로 다른 두 반지름에서 직접 계산한 원·교점·직선.','Circles, intersections, and secant lines computed for two radii.'))
normalize_prose_inequalities(D)
D.save(68)
