from calc1_core import *
D=CalcDoc('2.4',[154,155],lambda n:154 if n<=42 else 155)
x,h=s.symbols('x h',real=True);a,b=s.symbols('a b',real=True)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('삼각함수의 미분','Derivatives of trigonometric functions'),st,('각도는 라디안이다.삼각함수 미분과 곱·몫 법칙을 적용하고 극한은 sin u/u→1로 정리한다.','Angles are in radians.Apply trigonometric,product,and quotient rules;reduce limits using sin u/u→1.'),steps,ans,check,parts)
def same(q):return(d(q),d(q))
def tx(f,var='x'):return tex(f).replace('x',var)
def plots(n,fs,bounds,segments=None,title='Blue: function; red: derivative'):
 cs=[]
 for f,c in zip(fs,['#1d4ed8','#dc2626','#15803d']):
  for lo,hi in segments or[(bounds[0],bounds[1])]:cs.append({'points':samples(s.lambdify(x,f,'math'),lo,hi,500),'color':c})
 D.fig(n,[panel(title,bounds,cs)])
forms={1:3*s.sin(x)-2*s.cos(x),2:s.tan(x)-4*s.sin(x),3:x*x+s.cot(x),4:2*s.sec(x)-s.csc(x),5:x*x*s.sin(x),6:3*x+x*x*s.cos(x),7:s.sec(x)*s.tan(x),8:s.sin(x)*s.cos(x),9:(x-s.cos(x))*s.sin(x),10:x*s.cos(x)+2*s.tan(x),11:s.cos(x)**2,12:x*(a*s.cos(x)+b*s.cot(x)),13:s.sin(x)/(1+s.cos(x)),14:s.cos(x)/(1-s.sin(x)),15:x/(2-s.tan(x)),16:s.cot(x)/x**2,17:(1+s.sec(x))/(1-s.sec(x)),18:s.sin(x)/(1+s.tan(x)),19:x*s.sin(x)/(1+x),20:x/(s.sec(x)+s.tan(x)),21:x*s.cos(x)*s.sin(x),22:x*x*s.sin(x)*s.tan(x)}
varmap={5:r'\theta',7:r'\theta',8:r'\theta',9:r'\theta',11:'t',12:'u',13:r'\theta',16:'t',17:'w',18:'t',19:'t',20:'z',21:r'\theta'}
for n,f in forms.items():
 v=varmap.get(n,'x');der=s.diff(f,x);steps=[]
 if n<=4:steps=[('각 항을 독립적으로 미분하고 상수배를 유지한다.','Differentiate each term separately,preserving constant factors.'),same(r'f\prime='+tx(der,v))]
 elif n in[13,14,15,16,17,18,19,20]:
  U,V=s.fraction(f);steps=[same('U='+tx(U,v)+r',\ U\prime='+tx(s.diff(U,x),v)+r',\ V='+tx(V,v)+r',\ V\prime='+tx(s.diff(V,x),v)),same(r'f\prime=\frac{VU\prime-UV\prime}{V^2}')]
 else:
  terms=s.Add.make_args(f)
  for term in terms:
   if n==11:steps.append(same(r'\frac d{dt}(\cos t\cos t)=(-\sin t)\cos t+\cos t(-\sin t)'))
   else:steps.append(same(r'\frac d{d'+v+r'}\left('+tx(term,v)+r'\right)='+tx(s.diff(term,x),v)))
  steps.insert(0,('곱의 각 인수 하나씩 미분한 항을 더한다.합인 경우 항별로 적용한다.','Add terms differentiating one product factor at a time;apply this separately to each sum term.'))
 add(n,('함수 '+m('f('+v+')='+tx(f,v))+'를 미분하라.','Differentiate '+m('f('+v+')='+tx(f,v))+'.'),steps,d(r'f\prime('+v+')='+tx(der,v)),('분모 또는 삼각함수가 정의되지 않는 점을 제외한다.각 인수 미분을 합한 결과를 독립 기호 미분과 대조했다.','Exclude points where denominators or trigonometric functions are undefined.Checked the factorwise calculation against independent symbolic differentiation.'))
for n,f,base,work,ans in[(23,s.csc(x),1/s.sin(x),r'(1/\sin x)\prime=-\frac{\cos x}{\sin^2x}',r'-\csc x\cot x'),(24,s.sec(x),1/s.cos(x),r'(1/\cos x)\prime=\frac{\sin x}{\cos^2x}',r'\sec x\tan x'),(25,s.cot(x),s.cos(x)/s.sin(x),r'(\cos x/\sin x)\prime=\frac{-\sin^2x-\cos^2x}{\sin^2x}',r'-\csc^2x')]:
 add(n,('공식 '+m(r'\frac d{dx}('+tex(f)+')='+ans)+'를 증명하라.','Prove '+m(r'\frac d{dx}('+tex(f)+')='+ans)+'.'),[('사인·코사인으로 바꾸고 몫 법칙을 적용한다.','Rewrite in sine and cosine and use the quotient rule.'),same(work),same('='+ans)],d(r'\frac d{dx}('+tex(f)+')='+ans),('sin²x+cos²x=1과 역수 함수의 정의로 정리했다.원래 함수의 정의역에서만 주장한다.','Simplified using sin²x+cos²x=1 and reciprocal definitions.The identity is asserted only on the original domain.'))
add(26,('미분계수 정의로 f(x)=cos x의 도함수가−sin x임을 증명하라.','Prove from the derivative definition that the derivative of cos x is−sin x.'),[same(r'\frac{\cos(x+h)-\cos x}h=\cos x\frac{\cos h-1}h-\sin x\frac{\sin h}h'),('h→0에서 첫 극한은0,둘째는1이다.','As h→0 the first quotient tends to0 and the second to1.')],d(r'f\prime(x)=-\sin x'),('덧셈공식을 사용했고,표준 극한만으로 결론을 얻었다.','Used the angle-addition formula and only the standard trigonometric limits.'))
for n,f,at,val in[(27,s.sin(x)+s.cos(x),0,1),(28,x+s.sin(x),s.pi,s.pi),(29,x+s.tan(x),s.pi,s.pi),(30,(1+s.sin(x))/s.cos(x),s.pi,-1),(31,2*x*s.sin(x),s.pi/2,s.pi),(32,3*x+6*s.cos(x),s.pi/3,s.pi+3)]:
 der=s.diff(f,x);slope=s.simplify(der.subs(x,at));line=s.expand(val+slope*(x-at))
 add(n,('곡선 '+m('y='+tex(f))+'의 점 '+m('('+tex(at)+','+tex(val)+')')+'에서 '+('(a)접선식을 구하고(b)곡선과 접선을 함께 그려라.'if n>=31 else'접선식을 구하라.'),'For '+m('y='+tex(f))+' at '+m('('+tex(at)+','+tex(val)+')')+', '+('(a)find the tangent and(b)plot it with the curve.'if n>=31 else'find the tangent equation.')),[same(r'y\prime='+tex(der)+r',\quad m='+tex(slope)),same('y-('+tex(val)+')=('+tex(slope)+')(x-('+tex(at)+'))')],d('y='+tex(line)),('접점 대입과 기울기를 각각 확인했다.','Checked point incidence and tangent slope separately.'),list('ab')if n>=31 else())
 if n>=31:plots(n,[f,line],(-1,5,-12,20),title='Blue: curve; red: tangent')
for n,f,bounds in[(33,s.sec(x)-x,(-1.5,1.5,-5,15)),(34,s.sqrt(x)*s.sin(x),(0,2*math.pi,-3,3))]:
 der=s.diff(f,x)
 add(n,('함수 '+m('f(x)='+tex(f))+'의(a)도함수를 구하고(b)'+('|x|<π/2'if n==33 else'0≤x≤2π')+'에서 f,f′ 그래프를 비교하라.','For '+m('f(x)='+tex(f))+', (a)find f′ and(b)compare f,f′ on '+('|x|<π/2.'if n==33 else'0≤x≤2π.')),[same(r'f\prime(x)='+tex(der)),('도함수의 양·음 구간은 원함수의 증가·감소 구간이고 영점은 수평 접선과 일치한다.','Derivative signs correspond to increase/decrease of f,and zeros correspond to horizontal tangents.')]+([('0의 오른쪽 차분몫은 sin h/√h=√h(sin h/h)→0이므로 그림에서 도함수의 오른쪽 끝값은0으로 채울 수 있다.','At zero the right quotient sin h/√h=√h(sin h/h) tends to0,so the derivative sketch may include the right-endpoint value0.')]if n==34 else[]),d(r'f\prime(x)='+tex(der)),('독립 미분식과 그래프의 부호·영점을 대조했다.'+('34의 근호식 도함수는 x>0이고0은 오른쪽 미분으로 구별했다.'if n==34 else''),'Checked derivative signs and zeros against the independent formula.'+('In34 the radical formula requires x>0;the right derivative at0 is distinguished.'if n==34 else'')),list('ab'))
 plots(n,[f,der],bounds,[(.0001,2*math.pi)]if n==34 else None)
f=s.sin(x)/x;der=s.diff(f,x);dd=s.diff(f,x,2)
add(35,('g(θ)=sinθ/θ의 g′(θ),g″(θ)를 구하라.','Find g′(θ),g″(θ) for g(θ)=sinθ/θ.'),[same(r'g\prime(\theta)=\frac{\theta\cos\theta-\sin\theta}{\theta^2}'),same(r'g\prime\prime(\theta)=-\frac{\sin\theta}\theta-\frac{2\cos\theta}{\theta^2}+\frac{2\sin\theta}{\theta^3}')],d(r'g\prime=\frac{\theta\cos\theta-\sin\theta}{\theta^2},\quad g\prime\prime=\frac{(2-\theta^2)\sin\theta-2\theta\cos\theta}{\theta^3}'),('두 결과는 θ≠0에서 성립한다.분수식과 거듭제곱 합 형태를 각각 미분해 대조했다.','Both formulas require θ≠0;compared differentiation of quotient and inverse-power forms.'))
add(36,('f(t)=sec t일 때 f″(π/4)를 구하라.','For f(t)=sec t,find f″(π/4).'),[same(r'f\prime=\sec t\tan t,\quad f\prime\prime=\sec t\tan^2t+\sec^3t'),same(r'f\prime\prime(\pi/4)=\sqrt2+2\sqrt2=3\sqrt2')],d(r'3\sqrt2'),('sec(π/4)=√2,tan(π/4)=1을 각각 대입했다.','Substituted sec(π/4)=√2 and tan(π/4)=1 independently.'))
add(37,('f(x)=(tan x−1)/sec x를(a)몫 법칙으로 미분하고(b)사인·코사인으로 먼저 간단히 해 미분한 뒤(c)두 결과가 같음을 보여라.','Differentiate f(x)=(tan x−1)/sec x(a)by the quotient rule and(b)after simplifying in sine and cosine;then(c)show equivalence.'),[same(r'f\prime=\frac{\sec^3x-(\tan x-1)\sec x\tan x}{\sec^2x}'),same(r'f=\sin x-\cos x\Rightarrow f\prime=\cos x+\sin x'),same(r'\frac{\sec^2x-\tan^2x+\tan x}{\sec x}=\frac{1+\tan x}{\sec x}=\cos x+\sin x')],d(r'f\prime(x)=\cos x+\sin x\quad(\cos x\ne0)'),('단순화된 사인·코사인 식이 더 넓게 정의되어도 원식의 cos x≠0 조건은 유지한다.','Although the simplified expression has a larger domain,the original restriction cos x≠0 remains.'),list('abc'))
add(38,('f(π/3)=4,f′(π/3)=−2이고 g(x)=f(x)sin x,h(x)=cos x/f(x)이다.(a)g′(π/3),(b)h′(π/3)를 구하라.','Given f(π/3)=4,f′(π/3)=−2,g=f sin x,and h=cos x/f,find(a)g′(π/3),(b)h′(π/3).'),[same(r'g\prime=f\prime\sin x+f\cos x\Rightarrow g\prime(\pi/3)=-\sqrt3+2'),same(r'h\prime=\frac{-f\sin x-f\prime\cos x}{f^2}\Rightarrow h\prime(\pi/3)=\frac{1-2\sqrt3}{16}')],d(r'\text{(a) }2-\sqrt3;\quad\text{(b) }(1-2\sqrt3)/16'),('곱에는−2·√3/2와4·1/2,몫에는 분모4²를 대입했다.','Used−2·√3/2 and4·1/2 in the product,and denominator4² in the quotient.'),list('ab'))
add(39,('f(x)=x+2sin x의 수평 접선 위치 x를 모두 구하라.','Find all arguments where f(x)=x+2sin x has a horizontal tangent.'),[same(r'f\prime=1+2\cos x=0\Rightarrow\cos x=-1/2')],d(r'x=2\pi/3+2k\pi\ \text{or}\ 4\pi/3+2k\pi,\quad k\in\mathbb Z'),('한 주기의 두 해에 모든2π 정수배 이동을 포함했다.','Included both solutions in one period and all integer multiples of2π.'))
add(40,('곡선 y=cos x/(2+sin x)의 수평 접선 접점을 모두 구하라.','Find every point with a horizontal tangent on y=cos x/(2+sin x).'),[same(r'y\prime=\frac{-\sin x(2+\sin x)-\cos^2x}{(2+\sin x)^2}=-\frac{1+2\sin x}{(2+\sin x)^2}'),same(r'\sin x=-1/2\Rightarrow x=7\pi/6+2k\pi,\ 11\pi/6+2k\pi')],d(r'(7\pi/6+2k\pi,-\sqrt3/3),\quad(11\pi/6+2k\pi,\sqrt3/3),\quad k\in\mathbb Z'),('분모2+sin x는 항상1이상이므로 빠진 극점은 없고 두 접점 높이는 원식에 대입해 확인했다.','The denominator is always at least1,so no singularities are omitted;checked both ordinates in the original expression.'))
add(41,('수평 용수철 질량의 변위는 x(t)=8sin t(cm),t는초이다.(a)속도·가속도 함수,(b)t=2π/3의 위치·속도·가속도와 이동방향을 구하라.','A horizontal spring mass has displacement x(t)=8sin t cm,with t in seconds.(a)Find velocity and acceleration.(b)Find position,velocity,acceleration,and direction at t=2π/3.'),[same(r'v(t)=8\cos t,\quad a(t)=-8\sin t'),same(r'x(2\pi/3)=4\sqrt3,\quad v(2\pi/3)=-4,\quad a(2\pi/3)=-4\sqrt3')],('위치4√3cm,속도−4cm/s,가속도−4√3cm/s²이며 음의x방향(왼쪽)으로 이동한다.','Position4√3cm,velocity−4cm/s,acceleration−4√3cm/s²;motion is in the negative x-direction(left).'),('가속도는−x이고 방향은 변위 부호가 아니라 속도 부호로 판단했다.','Acceleration equals−x;motion direction follows the velocity sign rather than the displacement sign.'),list('ab'))
add(42,('고무줄에 매단 질량의 아래쪽 양의 변위가 s(t)=2cos t+3sin t(cm),t≥0초이다.(a)v,a,(b)v,a 그래프,(c)첫 평형점 통과 시각,(d)평형점에서 최대 거리,(e)속력이 가장 큰 시각을 구하라.','A suspended mass has downward-positive displacement s(t)=2cos t+3sin t cm for t≥0 seconds.Find(a)v,a,(b)their graphs,(c)the first equilibrium crossing,(d)maximum distance from equilibrium,and(e)times of greatest speed.'),[same(r'v=-2\sin t+3\cos t,\quad a=-2\cos t-3\sin t=-s'),same(r's=\sqrt{13}\sin(t+\alpha),\quad\alpha=\arctan(2/3)'),same(r's=0\Rightarrow t=\pi-\alpha+k\pi,\quad k=0,1,2,\ldots'),('진폭은√13cm이다.속력의 최대값도√13cm/s이며 위 평형 통과 시각에 발생한다.','The displacement amplitude is√13cm.Maximum speed is√13cm/s and occurs at the equilibrium crossings.')],d(r't_{\rm first}=\pi-\arctan(2/3)\approx2.554\ {\rm s};\quad |s|_{\max}=\sqrt{13}\ {\rm cm};\quad t_{|v|\max}=\pi-\arctan(2/3)+k\pi\ (k\ge0)'),('s²+v²=13이므로 s=0에서 속력이 최대라는 결론을 독립 확인한다.','The identity s²+v²=13 independently confirms that speed is greatest at s=0.'),list('abcde'))
plots(42,[-2*s.sin(x)+3*s.cos(x),-2*s.cos(x)-3*s.sin(x)],(0,2*math.pi,-4,4),title='Blue: velocity(cm/s); red: acceleration(cm/s^2)')
add(43,('길이10ft 사다리가 수직 벽에 놓여 있고 θ는 사다리 위쪽 끝과 벽 사이 각도,x는 아래쪽 끝과 벽의 수평거리이다.θ=π/3일 때 dx/dθ를 구하라.','A10ft ladder rests against a vertical wall.Let θ be the angle between its upper end and the wall,and x the horizontal distance from the base to the wall.Find dx/dθ at θ=π/3.'),[same(r'x=10\sin\theta,\quad\frac{dx}{d\theta}=10\cos\theta'),same(r'\left.\frac{dx}{d\theta}\right|_{\pi/3}=5')],('5ft/radian.','5ft/radian.'),('θ가 바닥과의 각도가 아닌 벽과의 각도이므로 맞은편 변 x에 sin을 사용했다.','Because θ is measured from the wall rather than the floor,x is the opposite side and uses sine.'))
mu,W=s.symbols('mu W',positive=True)
add(44,('수평 바닥의 물체를 각도θ의 줄로 끌 때 F=μW/(μsinθ+cosθ),μ는상수이다.(a)dF/dθ,(b)0이 되는 각도,(c)W=50lb,μ=0.6의 그래프와 정지점 각도를 구하라.','For a load pulled by a rope at angle θ,F=μW/(μsinθ+cosθ),with constant μ.Find(a)dF/dθ,(b)where it vanishes,and(c)plot the case W=50lb,μ=0.6 and locate the stationary angle.'),[same(r'F\prime(\theta)=\frac{\mu W(\sin\theta-\mu\cos\theta)}{(\mu\sin\theta+\cos\theta)^2}'),same(r'F\prime=0\Rightarrow\tan\theta=\mu\Rightarrow\theta=\arctan\mu\quad(0\le\theta<\pi/2)'),same(r'\theta=\arctan0.6\approx0.54042\ {\rm rad}=30.96^\circ')],d(r'\theta\approx0.54042;\quad F_{\min}=30/\sqrt{1.36}\approx25.725\ {\rm lb}'),('분모는 해당 범위에서 양수이고 도함수 분자는 해 앞에서 음수,뒤에서 양수이므로 최소이다.','The denominator is positive on the physical interval;the derivative numerator changes negative to positive,confirming a minimum.'),list('abc'))
plots(44,[30/(s.Rational(3,5)*s.sin(x)+s.cos(x))],(0,math.pi/2,24,52),title='Pulling force(lb) versus rope angle(radians)')
limitcases={45:(s.sin(5*x)/(3*x),0,r'\frac53\frac{\sin5x}{5x}',s.Rational(5,3)),46:(s.sin(x)/s.sin(s.pi*x),0,r'\frac1\pi\frac{\sin x/x}{\sin(\pi x)/(\pi x)}',1/s.pi),47:(s.sin(3*x)/s.sin(x),0,r'3\frac{\sin3x/(3x)}{\sin x/x}',3),48:(s.sin(3*x)**2/x,0,r'9x\left(\frac{\sin3x}{3x}\right)^2',0),49:((s.sin(x)-s.sin(x)*s.cos(x))/x**2,0,r'\frac{\sin x}{x}\frac{1-\cos x}{x}',0),50:((1-s.sec(x))/(2*x),0,r'\frac{\cos x-1}{x}\frac1{2\cos x}',0),51:(s.tan(2*x)/x,0,r'2\frac{\sin2x}{2x}\frac1{\cos2x}',2),52:(s.sin(x)/s.tan(7*x),0,r'\frac17\frac{\sin x/x}{\sin7x/(7x)}\cos7x',s.Rational(1,7)),53:(s.sin(3*x)/(5*x**3-4*x),0,r'\frac{3}{5x^2-4}\frac{\sin3x}{3x}',-s.Rational(3,4)),54:(s.sin(3*x)*s.sin(5*x)/x**2,0,r'15\frac{\sin3x}{3x}\frac{\sin5x}{5x}',15),55:(s.sin(x)/(x+s.tan(x)),0,r'\frac{\sin x/x}{1+\tan x/x}',s.Rational(1,2)),56:(s.csc(x)*s.sin(s.sin(x)),0,r'\frac{\sin(\sin x)}{\sin x}',1),57:((s.cos(x)-1)/(2*x*x),0,r'-\left(\frac{\sin(x/2)}x\right)^2',-s.Rational(1,4)),58:(s.sin(x*x)/x,0,r'x\frac{\sin(x^2)}{x^2}',0),59:((1-s.tan(x))/(s.sin(x)-s.cos(x)),s.pi/4,r'-1/\cos x',-s.sqrt(2)),60:(s.sin(x-1)/(x*x+x-2),1,r'\frac{\sin(x-1)}{x-1}\frac1{x+2}',s.Rational(1,3))}
for n,(f,at,work,val)in limitcases.items():
 v={47:'t',52:r'\theta',55:r'\theta',57:r'\theta'}.get(n,'x')
 add(n,('극한 '+m(r'\lim_{'+v+r'\to'+tex(at)+'}'+tx(f,v))+'을 구하라.','Evaluate '+m(r'\lim_{'+v+r'\to'+tex(at)+'}'+tx(f,v))+'.'),[('접근점 이외에서 식을 다음처럼 재정리한다.','Away from the approach point,rewrite the expression as follows.'),same(work.replace('x',v)),('sin u/u→1,(1−cos u)/u→0과 연속인 나머지 인자의 극한을 적용한다.','Apply sin u/u→1,(1−cos u)/u→0,and continuity for the remaining factors.')],d(tex(val)),('표준 극한에 들어가는 변수도0으로 가며,변형식과 원식의 차이를 기호 항등식으로 대조했다.','The standard-limit argument also tends to0;checked algebraic equivalence of the transformed and original expressions.'))
add(61,('sin x의99계 도함수를 구하라.','Find the99th derivative of sin x.'),[same(r'\sin x\to\cos x\to-\sin x\to-\cos x\to\sin x'),same(r'99\equiv3\pmod4')],d(r'-\cos x'),('네 번 미분할 때마다 반복되므로99차는3차와 같다.','The four-step cycle makes the99th derivative equal to the third.'))
add(62,('x sin x의35계 도함수를 처음 몇 번 미분한 패턴으로 구하라.','Find the35th derivative of x sin x by observing the pattern in the first few derivatives.'),[same(r'(x\sin x)\prime=\sin x+x\cos x,\quad(x\sin x)\prime\prime=2\cos x-x\sin x'),same(r'\frac{d^n}{dx^n}(x\sin x)=x\sin(x+n\pi/2)+n\sin(x+(n-1)\pi/2)'),same(r'35\equiv3\pmod4,\quad34\equiv2\pmod4')],d(r'-x\cos x-35\sin x'),('곱의 고계 미분식에서 x의2계 이상 도함수는0이어서 두 항만 남는다.','Only two terms survive in the higher product rule because derivatives of x of order2 and above vanish.'))
add(63,('y=A sin x+B cos x가 y″+y′−2y=sin x를 만족하도록 A,B를 구하라.','Find A,B so y=A sin x+B cos x satisfies y″+y′−2y=sin x.'),[same(r'y\prime=A\cos x-B\sin x,\quad y\prime\prime=-A\sin x-B\cos x'),same(r'(-3A-B)\sin x+(A-3B)\cos x=\sin x'),same(r'-3A-B=1,\quad A-3B=0')],d(r'A=-3/10,\quad B=-1/10'),('대입하면 사인 계수1,코사인 계수0으로 원방정식이 성립한다.','Substitution gives sine coefficient1 and cosine coefficient0,verifying the equation.'))
add(64,('극한 lim(x→0)x sin(1/x)를 구하고 그래프로 확인하라.','Evaluate lim(x→0)x sin(1/x) and illustrate graphically.'),[same(r'|x\sin(1/x)|\le|x|\to0'),('진동은 점점 빨라지지만 y=±|x| 사이의 높이는0으로 좁아진다.','Oscillations accelerate,but their heights are squeezed between y=±|x| toward zero.')],d('0'),('좌우에서 모두 같은 절댓값 경계가 적용되어 양쪽 극한이0이다.','The same absolute-value bound holds on both sides,giving a two-sided zero limit.'))
plots(64,[x*s.sin(1/x),s.Abs(x),-s.Abs(x)],(-.5,.5,-.55,.55),[(-.5,-.002),(.002,.5)],title='Blue: oscillation; red/green: envelopes')
add(65,('양변을 미분하여 항등식을 얻어라:(a)tan x=sin x/cos x,(b)sec x=1/cos x,(c)sin x+cos x=(1+cot x)/csc x.','Differentiate both sides to obtain identities:(a)tan x=sin x/cos x,(b)sec x=1/cos x,(c)sin x+cos x=(1+cot x)/csc x.'),[same(r'\text{(a) }\sec^2x=\frac{\cos^2x+\sin^2x}{\cos^2x}=1+\tan^2x'),same(r'\text{(b) }\sec x\tan x=\frac{\sin x}{\cos^2x}'),same(r'\text{(c) }\cos x-\sin x=\frac{-\csc^3x+(1+\cot x)\csc x\cot x}{\csc^2x}=\frac{\cot x-1}{\csc x}')],d(r'\sec^2x=1+\tan^2x;\quad\sec x\tan x=\sin x/\cos^2x;\quad\cos x-\sin x=(\cot x-1)/\csc x'),('각 미분식은 해당 원래 항등식의 정의역에서 성립하며,사인·코사인으로 바꾸어 직접 확인했다.','Each differentiated identity holds on the original domain and was checked directly in sine and cosine.'),list('abc'))
add(66,('두 같은 변 RP=RQ=10cm인 이등변삼각형 PQR의 꼭짓각이θ이고,PQ를 지름으로 하는 반원이 삼각형 위에 놓인다.반원 넓이A(θ),삼각형 넓이B(θ)에 대해 lim(θ→0⁺)A/B를 구하라.','An isosceles triangle has RP=RQ=10cm and vertex angle θ.A semicircle lies above it with diameter PQ.If A(θ),B(θ) are their areas,find lim(θ→0⁺)A/B.'),[same(r'PQ=20\sin(\theta/2),\quad A=50\pi\sin^2(\theta/2),\quad B=50\sin\theta'),same(r'\frac AB=\frac\pi2\tan(\theta/2)\to0')],d('0'),('작은 θ에서 A는 θ² 정도,B는 θ 정도이므로 비는0으로 가며 정확한 식과 일치한다.','For small θ,A is of orderθ² and B of orderθ,so the ratio tends to zero,agreeing with the exact expression.'))
r=5;hh=math.sqrt(75)
D.fig(66,[panel('Example theta=pi/3: equal sides10cm',(-17*26/27,17*26/27,-10,7),[samples(lambda z:math.sqrt(max(0,25-z*z)),-5,5,400),[(-5,0),(0,-hh),(5,0),(-5,0)]],[(-5,0),(5,0),(0,-hh)],xlabel='P=(-5,0),Q=(5,0),R=(0,-sqrt75)',ylabel='cm')])
add(67,('반지름r인 원에서 중심각θ가 만드는 호 길이는s,현 길이는d이다.lim(θ→0⁺)s/d를 구하라.','A central angle θ in a radius-r circle subtends arc length s and chord length d.Find lim(θ→0⁺)s/d.'),[same(r's=r\theta,\quad d=2r\sin(\theta/2)'),same(r'\frac sd=\frac{\theta/2}{\sin(\theta/2)}\to1')],d('1'),('작은 양의 각도에서는 sin u<u이므로 s/d>1이며1에 위쪽에서 접근한다.','For small positive u,sin u<u,so s/d>1 and approaches1 from above.'))
D.fig(67,[panel('Arc and chord for an example central angle',(-2.6*26/27,2.6*26/27,-1.3,1.3),[[(math.cos(t),math.sin(t))for t in[2*math.pi*i/400 for i in range(401)]],[(math.cos(math.pi/4),math.sin(math.pi/4)),(math.cos(3*math.pi/4),math.sin(3*math.pi/4))],[(math.cos(math.pi/4),math.sin(math.pi/4)),(0,0),(math.cos(3*math.pi/4),math.sin(3*math.pi/4))]])])
add(68,('f(x)=x/√(1−cos2x)에 대해(a)그래프에서0의 불연속 유형을 추측하고(b)좌우 극한을 계산하여 확인하라.','For f(x)=x/√(1−cos2x),(a)graph it and identify the apparent discontinuity at0;(b)calculate both one-sided limits to confirm.'),[same(r'\sqrt{1-\cos2x}=\sqrt{2\sin^2x}=\sqrt2|\sin x|'),same(r'f(x)=\frac1{\sqrt2}\frac{x}{|\sin x|}\to\begin{cases}-1/\sqrt2&x\to0^-\\1/\sqrt2&x\to0^+\end{cases}')],('0에서 점프 불연속;좌극한−1/√2,우극한1/√2.','Jump discontinuity at0;left limit−1/√2,right limit1/√2.'),('√(sin²x)를 sin x가 아니라 |sin x|로 써야 좌극한 부호를 보존한다.','Using |sin x| rather than sin x for √(sin²x)preserves the left-limit sign.'),list('ab'))
plots(68,[x/s.sqrt(1-s.cos(2*x))],(-3,3,-5,5),[(-3,-.001),(.001,3)],title='Jump at0: one-sided limits +/-1/sqrt2')
normalize_prose_inequalities(D)
D.save(68)
