from calc1_core import *
import mpmath as mp
D=CalcDoc('2.1',[116,117,118,119],lambda n:116 if n<=14 else 117 if n<=33 else 118 if n<=53 else 119)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('미분계수·접선·순간변화율','Derivatives, tangents, and instantaneous rates'),st,('평균변화율의 차분몫을 만든 뒤 극한을 취한다. 접선은 점–기울기 식으로 쓴다.','Form the difference quotient and take its limit. Write a tangent using point–slope form.'),steps,ans,check,parts)
x,h,a=s.symbols('x h a',real=True)
def tangfig(n,f,points,bounds,zoom=False):
 fn=s.lambdify(x,f,'math');panels=[]
 cs=[samples(fn,bounds[0],bounds[1])]
 for at in points:
  value=float(f.subs(x,at));der=float(s.diff(f,x).subs(x,at));cs.append([(bounds[0],value+der*(bounds[0]-at)),(bounds[1],value+der*(bounds[1]-at))])
 panels.append(panel('Curve and tangent lines',bounds,cs,[(float(z),float(f.subs(x,z)))for z in points]))
 if zoom:
  at=float(points[0]);val=float(f.subs(x,at));der=float(s.diff(f,x).subs(x,at))
  for w in [.1,.005]:panels.append(panel(f'Zoom around tangent point: half-width {w}',(at-w,at+w,val-abs(der)*w*1.3,val+abs(der)*w*1.3),[samples(fn,at-w,at+w),[(at-w,val-der*w),(at+w,val+der*w)]]))
 D.fig(n,panels)
add(1,('곡선 y=f(x)의 P=(3,f(3)),Q=(x,f(x))에 대해 (a)할선 기울기, (b)P의 접선 기울기 식을 쓰라.','For P=(3,f(3)) and Q=(x,f(x)) on y=f(x), give expressions for (a)the secant slope and (b)the tangent slope at P.'),[('기울기는 세로 변화량을 가로 변화량으로 나눈 값이다. 접선은 Q가 P로 접근할 때의 유한 극한이다.','Slope is the vertical change divided by the horizontal change. The tangent slope is the finite limit as Q approaches P.')],d(r'\text{(a) }\frac{f(x)-f(3)}{x-3},\ x\ne3;\quad\text{(b) }\lim_{x\to3}\frac{f(x)-f(3)}{x-3}=f\prime(3)'),('분모 0인 x=3에서는 할선식이 정의되지 않으며 유한 극한이 존재할 때 접선 기울기를 준다.','The secant expression excludes x=3; an existing finite limit gives the tangent slope.'),list('ab'))
add(2,('y=sin x를 [−2,2]²,[−1,1]²,[−0.5,0.5]²에서 그려 원점 확대 시 모습을 설명하라.','Plot y=sin x in the squares [−2,2]²,[−1,1]²,[−0.5,0.5]² and describe what happens when zooming toward the origin.'),[('구간이 작아질수록 사인 곡선은 원점을 지나는 직선 y=x와 비슷해진다.','On smaller windows the sine curve approaches the appearance of the line y=x through the origin.'),(d(r'\lim_{x\to0}\frac{\sin x-0}{x-0}=1'),d(r'\lim_{x\to0}\frac{\sin x-0}{x-0}=1'))],('원점 근처에서 기울기 1인 직선처럼 보인다.','Near the origin it looks like a straight line of slope 1.'),('sin x−x의 크기는 작은 x에서 약 |x|³/6이므로 확대 시 상대적인 굽음이 줄어든다.','For small x the error sin x−x has magnitude about |x|³/6, so its relative curvature diminishes under zooming.'))
D.fig(2,[panel(f'Sine and y=x in window +/-{w}',(-w,w,-w,w),[samples(math.sin,-w,w),[(-w,-w),(w,w)]])for w in [2,1,.5]])
for n,f,at in [(3,x*x+3*x,-1),(4,x**3+1,1)]:
 val=f.subs(x,at);qx=s.cancel((f-val)/(x-at));qh=s.expand((f.subs(x,at+h)-val)/h);der=s.limit(qh,h,0);line=s.expand(val+der*(x-at))
 add(n,('곡선 '+m('y='+tex(f))+f'의 점 ({at},{val})에서 (a)x→a와 h→0의 두 차분몫 정의로 기울기, (b)접선식, (c)확대한 곡선과 접선 그래프를 구하라.','For '+m('y='+tex(f))+f' at ({at},{val}), find (a)the slope using both x→a and h→0 difference quotients, (b)the tangent equation, and (c)progressively zoomed graphs.'),[(d(r'\frac{f(x)-f('+str(at)+')}{x-('+str(at)+')}='+tex(qx)+r'\longrightarrow'+tex(der)),d(r'\frac{f(x)-f('+str(at)+')}{x-('+str(at)+')}='+tex(qx)+r'\longrightarrow'+tex(der))),(d(r'\frac{f('+str(at)+r'+h)-f('+str(at)+')}{h}='+tex(qh)+r'\longrightarrow'+tex(der)),d(r'\frac{f('+str(at)+r'+h)-f('+str(at)+')}{h}='+tex(qh)+r'\longrightarrow'+tex(der))),('접점과 기울기로 y−f(a)=f′(a)(x−a)를 쓴다.','Use the point and slope in y−f(a)=f′(a)(x−a).')],d('m='+tex(der)+r',\quad y='+tex(line)),('두 독립 차분몫이 같은 기울기를 주고 접선에 접점이 대입된다. 확대 도해에서도 두 곡선이 가까워진다.','Both difference quotients agree and the tangent passes through the specified point. The zoomed views show the curves converging locally.'),['a(i)','a(ii)','b','c'])
 tangfig(n,f,[at],(-3,1,-5,4)if n==3 else(-1,3,-3,10),True)
for n,f,at,val in [(5,2*x*x-5*x+1,3,4),(6,x*x-2*x**3,1,-1),(7,(x+2)/(x-3),2,-4),(8,s.sqrt(1-3*x),-1,2)]:
 der=s.simplify(s.limit((f.subs(x,at+h)-val)/h,h,0));line=s.expand(val+der*(x-at));quot=s.simplify((f.subs(x,at+h)-val)/h)
 if n==8:work=r'\frac{\sqrt{4-3h}-2}{h}=\frac{-3}{\sqrt{4-3h}+2}'
 else:work=r'\frac{f(a+h)-f(a)}h='+tex(quot)
 add(n,('곡선 '+m('y='+tex(f))+f'의 점 ({at},{val})에서 접선 방정식을 구하라.','Find the tangent to '+m('y='+tex(f))+f' at ({at},{val}).'),[(d(work),d(work)),('h→0 극한으로 기울기 '+m(tex(der))+'를 얻고 점–기울기 식에 대입한다.','Taking h→0 gives slope '+m(tex(der))+', which enters the point–slope equation.')],d('y='+tex(line)),('원곡선과 접선 모두 지정점을 지나고, 독립 미분값도 접선 기울기와 일치한다.','Both the curve and line pass through the point, and an independent derivative agrees with the tangent slope.'))
for n,f,pts,bounds,derform in [(9,3+4*x*x-2*x**3,[1,2],(-1,3,-5,8),8*a-6*a*a),(10,2*s.sqrt(x),[1,9],(.01,12,0,13),1/s.sqrt(a))]:
 valat=f.subs(x,a);qh=s.simplify((f.subs(x,a+h)-valat)/h)
 if n==10:work=r'\frac{2\sqrt{a+h}-2\sqrt a}{h}=\frac2{\sqrt{a+h}+\sqrt a}\longrightarrow\frac1{\sqrt a}\quad(a>0)'
 else:work=tex(s.expand(qh))+r'\longrightarrow'+tex(derform)
 ans=[]
 for at in pts:
  der=s.diff(f,x).subs(x,at);line=s.expand(f.subs(x,at)+der*(x-at));ans.append(m('x='+str(at)+': y='+tex(line)))
 add(n,('함수 '+m('y='+tex(f))+'에 대해 (a)x=a에서 접선 기울기, (b)x='+','.join(map(str,pts))+'의 접선식, (c)곡선과 두 접선을 한 화면에 그려라.','For '+m('y='+tex(f))+', find (a)the tangent slope at a, (b)the tangent equations at x='+','.join(map(str,pts))+', and (c)plot the curve with both tangents.'),[(d(work),d(work)),('각 접점에서 y−f(a)=f′(a)(x−a)를 적용한다.','At each point use y−f(a)=f′(a)(x−a).')],d(r'f\prime(a)='+tex(derform))+ '; '+ '; '.join(ans),('각 직선의 접점 통과와 기울기를 직접 확인했다.'+('10번의 유한 기울기는 a>0에서만 유효하고 a=0은 수직 접선이다.'if n==10 else''),'Checked point incidence and slope for each line.'+('In 10 the finite-slope formula requires a>0; a=0 has a vertical tangent.'if n==10 else'')),list('abc'))
 tangfig(n,f,pts,bounds)
add(11,('수면 위 100 ft에서 떨어지는 물체의 낙하거리 d(t)=16t² ft이다. (a)수면 도달 시각, (b)그때 속도를 구하라.','A diver starts 100 ft above water, with downward distance d(t)=16t² ft. Find (a)the time of impact and (b)impact velocity.'),[('16t²=100에서 양의 해 t=2.5초를 고른다.','The positive solution of 16t²=100 is t=2.5 seconds.'),(d(r'\lim_{h\to0}\frac{16(t+h)^2-16t^2}{h}=32t'),d(r'\lim_{h\to0}\frac{16(t+h)^2-16t^2}{h}=32t'))],('(a)2.5 s. (b)아래 방향 80 ft/s(위쪽을 양수로 잡으면 −80 ft/s).','(a)2.5 s. (b)80 ft/s downward, or −80 ft/s if upward is positive.'),('낙하거리를 양수로 정의한 방향을 명시하여 높이 좌표의 속도 부호와 구별했다.','Explicitly distinguished positive downward distance from the velocity sign in an upward-positive height coordinate.'),list('ab'))
add(12,('화성에서 H(t)=10t−1.86t² m이다. (a)1초 속도, (b)t=a 속도, (c)지면 재도달 시각, (d)그때 속도를 구하라.','On Mars let H(t)=10t−1.86t² m. Find (a)velocity at 1 second, (b)velocity at t=a, (c)return time to the surface, and (d)impact velocity.'),[(d(r'\frac{H(a+h)-H(a)}h=10-3.72a-1.86h\longrightarrow10-3.72a'),d(r'\frac{H(a+h)-H(a)}h=10-3.72a-1.86h\longrightarrow10-3.72a')),('H(t)=t(10−1.86t)=0의 양의 해는 500/93초이다.','The positive root of H(t)=t(10−1.86t)=0 is 500/93 seconds.')],('(a)6.28 m/s; (b)10−3.72a m/s; (c)500/93≈5.376344 s; (d)−10 m/s.','(a)6.28 m/s; (b)10−3.72a m/s; (c)500/93≈5.376344 s; (d)−10 m/s.'),('재도달 시각을 높이에 대입하면 0, 속도식에 대입하면 −10으로 출발속도와 크기가 같다.','At the return time the height is zero and the velocity is −10, matching the initial speed in magnitude.'),list('abcd'))
add(13,('위치 s(t)=1/t² m인 입자의 속도를 t=a,1,2,3초에서 구하라.','For displacement s(t)=1/t² m, find velocity at t=a,1,2,3 seconds.'),[(d(r'\frac{1/(a+h)^2-1/a^2}{h}=-\frac{2a+h}{a^2(a+h)^2}\longrightarrow-\frac2{a^3}'),d(r'\frac{1/(a+h)^2-1/a^2}{h}=-\frac{2a+h}{a^2(a+h)^2}\longrightarrow-\frac2{a^3}'))],d(r'v(a)=-2/a^3,\quad v(1)=-2,\quad v(2)=-1/4,\quad v(3)=-2/27\ \mathrm{m/s}'),('a>0인 시간 영역에서 위치가 감소하여 속도가 음수라는 결과와 일치한다.','For positive time the displacement decreases, agreeing with the negative velocity.'))
f=x*x/2-6*x+23;windows=[(4,8),(6,8),(8,10),(8,12)];vels=[s.simplify((f.subs(x,b)-f.subs(x,a))/(b-a))for a,b in windows]
add(14,('s(t)=t²/2−6t+23 ft이다. (a)[4,8],[6,8],[8,10],[8,12]의 평균속도, (b)8초 순간속도, (c)네 할선과 접선을 위치곡선과 함께 그려라.','Let s(t)=t²/2−6t+23 ft. Find (a)average velocities on [4,8],[6,8],[8,10],[8,12], (b)instantaneous velocity at 8, and (c)plot the four secants and tangent with the position curve.'),[('각 평균은 (s(b)−s(a))/(b−a)이며 이 이차식에서는 (a+b)/2−6으로 단순화된다.','Each average is (s(b)−s(a))/(b−a), simplifying here to (a+b)/2−6.'),(d(r'v(t)=\lim_{h\to0}(t-6+h/2)=t-6,\quad v(8)=2'),d(r'v(t)=\lim_{h\to0}(t-6+h/2)=t-6,\quad v(8)=2'))],('(a)0,1,3,4 ft/s. (b)2 ft/s. 접선 s=2t−9.','(a)0,1,3,4 ft/s. (b)2 ft/s. Tangent s=2t−9.'),('양쪽의 가까운 평균 1과 3의 평균이 순간속도 2와 일치하며, 접선은 (8,7)을 지난다.','The average of neighboring secant slopes 1 and 3 equals instantaneous slope 2; the tangent passes through (8,7).'),['a(i)','a(ii)','a(iii)','a(iv)','b','c'])
cs=[samples(lambda z:z*z/2-6*z+23,3,13)]
for (lo,hi),v in zip(windows,vels):
 yy=float(f.subs(x,lo));cs.append([(3,yy+float(v)*(3-lo)),(13,yy+float(v)*(13-lo))])
cs.append([(3,-3),(13,17)]);D.fig(14,[panel('Position, four secants, and tangent',(3,13,0,32),cs,[(8,7)],xlabel='seconds',ylabel='feet')])
add(15,('위치 그래프는 (t,s)=(0,0),(1,3),(2,3),(3,1),(4,1),(6,3)을 차례로 직선 연결한 것이다. (a)오른쪽·왼쪽 이동 및 정지 구간을 찾고 (b)속도 그래프를 그려라.','The position graph connects (t,s)=(0,0),(1,3),(2,3),(3,1),(4,1),(6,3) with line segments. (a)Find the intervals of rightward motion, leftward motion, and rest. (b)Graph velocity.'),[('위치의 기울기는 차례로 3,0,−2,0,1 m/s이다. 양수는 오른쪽, 음수는 왼쪽, 0은 정지이다.','The successive position slopes are 3,0,−2,0,1 m/s. Positive means rightward, negative leftward, and zero rest.')],('오른쪽:(0,1),(4,6); 왼쪽:(2,3); 정지:(1,2),(3,4). 모서리 1,2,3,4에서는 속도 미정의.','Rightward:(0,1),(4,6); leftward:(2,3); rest:(1,2),(3,4). Velocity is undefined at corners 1,2,3,4.'),('구간별 속도×시간을 더하면 3+0−2+0+2=3 m로 최종 변위와 일치한다.','Summing velocity times duration gives 3+0−2+0+2=3 m, matching net displacement.'),list('ab'))
cs=[];dots=[]
for lo,hi,v in [(0,1,3),(1,2,0),(2,3,-2),(3,4,0),(4,6,1)]:cs.append([(lo,v),(hi,v)]);dots.extend([(lo,v,'open'),(hi,v,'open')])
D.fig(15,[panel('Velocity from position segments',(0,6,-3,4),cs,dots,xticks=list(range(7)),yticks=[-2,0,1,3],xlabel='seconds',ylabel='m/s')])
add(16,('원본 100 m 경주 그래프에서 A는 출발점부터 약 14초의 결승점까지 직선이고 B는 아래에서 시작해 점점 가팔라지는 곡선으로 같은 점에 도착한다. (a)달리기를 비교하고 (b)거리차가 최대인 시각, (c)속도가 같은 시각을 추정하라.','In the source 100 m race graph, A follows a straight position-time line to the finish at about 14 seconds. B follows an initially lower curve that steepens and reaches the same endpoint. (a)Compare their motion, (b)estimate the time of greatest separation, and (c)estimate when their velocities match.'),[('A는 약 100/14 m/s의 일정한 속도로 달린다. B는 더 느리게 시작하여 가속하고, 마지막에는 A보다 빨라져 따라잡는다.','A runs at an approximately constant 100/14 m/s. B starts slower, accelerates, and runs faster than A near the finish to catch up.'),('거리차 A(t)−B(t)가 최대인 곳은 두 위치곡선의 접선이 평행한 곳이다. 그림에서는 대략 9–10초 부근이다.','The separation A(t)−B(t) is greatest where the position tangents are parallel, around 9–10 seconds in the figure.')],('(b),(c)둘 다 대략 9초(그림 판독 약 ±1초).','(b),(c)Both approximately 9 seconds, with roughly ±1 second of graphical uncertainty.'),('최대 거리차의 도함수는 A′−B′=0이어서 (b),(c)가 같은 시각이라는 점을 독립적으로 확인한다. 원본에 정확한 식은 주어져 있지 않다.','At maximum separation the derivative A′−B′ is zero, independently linking (b) and (c). The source supplies no exact formulas.'),list('abc'))
add(17,('원본 g 그래프에서 x=0은 내려가는 부분, −2는 가장 가파른 상승, 2는 중간 상승, 4는 완만한 상승에 있다. 0,g′(−2),g′(0),g′(2),g′(4)를 작은 순서로 배열하라.','In the source graph, g decreases at 0, rises most steeply at −2, rises moderately at 2, and rises gently at 4. Order 0,g′(−2),g′(0),g′(2),g′(4) increasingly.'),[('내려가는 접선의 기울기는 음수이고 세 상승 기울기는 양수이다. 상승 부분끼리는 가파른 정도로 비교한다.','The descending tangent has negative slope and all rising tangents have positive slopes. Compare the steepness among the rising portions.')],d(r'g\prime(0)<0<g\prime(4)<g\prime(2)<g\prime(-2)'),('함수 높이가 아니라 접선의 기울기를 비교했으며, −2의 상승이 2보다 더 가파름을 원본 그림에서 확인했다.','Compared tangent slopes rather than function heights and checked that the ascent at −2 is steeper than at 2.'))
add(18,('원본 f 그래프의 격자 판독값은 f(10)≈400,f(20)≈300,f(40)≈200,f(50)≈400,f(60)≈700,f(80)≈800이다. (a)[20,60] 평균변화율, (b)평균변화율 0인 구간, (c)(f(40)−f(10))/30과 기하 의미, (d)f′(50), (e)f′(10)>f′(30)인지, (f)f′(60)>(f(80)−f(40))/40인지 판단하라.','Grid readings from the source f-graph are f(10)≈400,f(20)≈300,f(40)≈200,f(50)≈400,f(60)≈700,f(80)≈800. Find (a)the average rate on [20,60], (b)an interval with zero average rate, (c)(f(40)−f(10))/30 and its geometric meaning, (d)f′(50), and determine (e)whether f′(10)>f′(30) and (f)whether f′(60)>(f(80)−f(40))/40.'),[('(a)(700−300)/40≈10. (b)[10,50]에서는 양 끝 높이가 같다. (c)(200−400)/30≈−6.67로 두 점을 잇는 할선 기울기이다.','(a)(700−300)/40≈10. (b)On [10,50] the endpoint heights agree. (c)(200−400)/30≈−6.67 is the slope of the secant through those points.'),('(d)50 부근 접선의 기울기는 약 30이다. (e)10에서 더 가파르게 감소하므로 도함수는 더 작다. (f)60의 상승 접선은 할선 기울기 (800−200)/40=15보다 가파르다.','(d)The tangent slope near 50 is about 30. (e)The descent at 10 is steeper, so its derivative is smaller. (f)The rising tangent at 60 is steeper than the secant slope (800−200)/40=15.')],('(a)≈10; (b)예:[10,50]; (c)≈−20/3; (d)≈30; (e)아니오; (f)예.','(a)≈10; (b)e.g.[10,50]; (c)≈−20/3; (d)≈30; (e)No; (f)Yes.'),('수치는 그래프 판독 근사이며, 비교 문항은 접선 방향과 상대 가파름으로 별도 확인했다.','Numerical values are graph-reading estimates; comparison parts were checked separately by tangent direction and relative steepness.'),list('abcdef'))
for n,f,at in [(19,s.sqrt(4*x+1),6),(20,5*x**4,-1),(21,x*x/(x+6),3),(22,1/s.sqrt(2*x+2),1)]:
 val=f.subs(x,at);de=s.simplify(s.diff(f,x).subs(x,at))
 if n==19:work=r'\frac{\sqrt{25+4h}-5}{h}=\frac4{\sqrt{25+4h}+5}\longrightarrow2/5'
 elif n==20:work=tex(s.expand((f.subs(x,at+h)-val)/h))+r'\longrightarrow-20'
 elif n==21:work=r'\frac{x^2/(x+6)-1}{x-3}=\frac{(x-3)(x+2)}{(x+6)(x-3)}=\frac{x+2}{x+6}\longrightarrow5/9'
 else:work=r'\frac{1/\sqrt{2x+2}-1/2}{x-1}=-\frac1{\sqrt{2x+2}(2+\sqrt{2x+2})}\longrightarrow-1/8'
 add(n,('함수 '+m('f(x)='+tex(f))+f'에서 a={at}의 미분계수를 '+('h→0 차분몫 정의로 구하라.'if n<=20 else'x→a 차분몫 정의로 구하라.'),'For '+m('f(x)='+tex(f))+f', find the derivative at a={at} using '+('the h→0 difference quotient.'if n<=20 else'the x→a difference quotient.')),[(d(work),d(work)),('접근점 이외에서 약분·유리화한 뒤 연속인 식의 극한을 취한다.','Cancel or rationalize off the approach point, then take the limit of the continuous transformed expression.')],d(r'f\prime('+str(at)+')='+tex(de)),('요구된 차분몫 결과를 독립 미분법 계산과 비교하여 검산했다.','Compared the required difference-quotient result against independent differentiation.'))
for n,f in [(23,2*x*x-5*x+3),(24,x**3-3*x),(25,1/(x*x+1)),(26,x/(1-4*x))]:
 quotient=s.factor(s.cancel((f.subs(x,a+h)-f.subs(x,a))/h));der=s.factor(s.diff(f,x).subs(x,a))
 add(n,('함수 '+m('f(x)='+tex(f))+'의 f′(a)를 구하라.','Find f′(a) for '+m('f(x)='+tex(f))+'.'),[(d(r'\frac{f(a+h)-f(a)}h='+tex(quotient)),d(r'\frac{f(a+h)-f(a)}h='+tex(quotient))),('h→0으로 보내고 a는 원함수의 정의역에 둔다.','Take h→0 with a in the original domain.')],d(r'f\prime(a)='+tex(der)),('일반 차분몫의 기호 극한을 미분식과 비교했다.'+('26번은 a≠1/4가 필요하다.'if n==26 else''),'Compared the symbolic limit of the general difference quotient with the derivative.'+('In 26, a≠1/4 is required.'if n==26 else'')))
for n,at,val,de,name in [(27,6,0,-s.Rational(1,2),'B'),(28,5,-3,4,'g')]:
 line=s.expand(val+de*(x-at))
 add(n,(f'{name}({at})={val}, {name}′({at})={de}일 때 x={at}의 접선식을 구하라.',f'Given {name}({at})={val} and {name}′({at})={de}, find the tangent at x={at}.'),[(d('y-('+str(val)+')='+tex(de)+'(x-'+str(at)+')'),d('y-('+str(val)+')='+tex(de)+'(x-'+str(at)+')'))],d('y='+tex(line)),('직선에 x='+str(at)+'를 대입하면 주어진 함수값을 얻고 기울기는 미분계수와 같다.','Substitution at x='+str(at)+' gives the assigned value, and the line’s slope equals the derivative.'))
for n,f,at,val in [(29,3*x*x-x**3,1,2),(30,x**4-2,1,-1),(31,5*x/(1+x*x),2,2)]:
 q=s.factor(s.cancel((f.subs(x,at+h)-val)/h));de=s.limit(q,h,0);line=s.expand(val+de*(x-at))
 add(n,('함수 '+m('f(x)='+tex(f))+f'의 f′({at})와 점 ({at},{val})의 접선식을 구하라.'+(' 곡선과 접선도 함께 그려라.'if n==31 else''),'For '+m('f(x)='+tex(f))+f', find f′({at}) and the tangent at ({at},{val}).'+(' Plot the curve and tangent together.'if n==31 else'')),[(d(r'\frac{f(a+h)-f(a)}h='+tex(q)+r'\longrightarrow'+tex(de)),d(r'\frac{f(a+h)-f(a)}h='+tex(q)+r'\longrightarrow'+tex(de))),('기울기와 접점을 점–기울기 식에 넣는다.','Insert the slope and contact point into point–slope form.')],d(r'f\prime('+str(at)+')='+tex(de)+r',\quad y='+tex(line)),('원식의 미분값과 접선 기울기가 같고 접점을 정확히 지나는지 확인했다.','Verified the original derivative equals the tangent slope and the line passes through the exact point.'),list('ab')if n==31 else())
 if n==31:tangfig(n,f,[at],(-3,5,-3,4))
f=4*x*x-x**3
add(32,('(a)G(x)=4x²−x³의 G′(a)와 (2,8),(3,9)의 접선을 구하고 (b)곡선과 두 접선을 그려라.','(a)Find G′(a) for G(x)=4x²−x³ and the tangents at (2,8),(3,9). (b)Plot the curve and both tangents.'),[(d(r'\frac{G(a+h)-G(a)}h=8a-3a^2+(4-3a)h-h^2\longrightarrow8a-3a^2'),d(r'\frac{G(a+h)-G(a)}h=8a-3a^2+(4-3a)h-h^2\longrightarrow8a-3a^2')),('a=2에서는 기울기 4, a=3에서는 −3이다.','The slopes are 4 at a=2 and −3 at a=3.')],d(r'G\prime(a)=8a-3a^2;\quad y=4x;\quad y=-3x+18'),('두 접선에 2와 3을 대입하여 각각 8과 9를 얻는다.','The two lines give 8 and 9 at x=2 and x=3, respectively.'),list('ab'))
tangfig(32,f,[2,3],(-1,5,-6,13))
add(33,('x=2에서 y=f(x)의 접선이 y=4x−5이다. f(2),f′(2)를 구하라.','The tangent to y=f(x) at x=2 is y=4x−5. Find f(2) and f′(2).'),[('접선은 접점을 지나므로 f(2)=4·2−5=3이고, 접선 기울기 4가 미분계수이다.','The line passes through the contact point, so f(2)=4·2−5=3; its slope 4 is the derivative.')],d(r'f(2)=3,\quad f\prime(2)=4'),('함수값은 직선의 높이, 미분계수는 직선의 기울기로 서로 다른 정보를 사용한다.','The function value comes from line height and the derivative from line slope.'))
add(34,('곡선의 (4,3)에서 접선이 (0,2)도 지난다. f(4),f′(4)를 구하라.','The tangent at (4,3) also passes through (0,2). Find f(4) and f′(4).'),[('접점의 높이로 f(4)=3, 두 점의 기울기로 f′(4)=(3−2)/(4−0)=1/4이다.','The contact height gives f(4)=3; the slope through the two points gives f′(4)=(3−2)/(4−0)=1/4.')],d(r'f(4)=3,\quad f\prime(4)=1/4'),('접선식 y=2+x/4가 두 주어진 점을 모두 지난다.','The tangent y=2+x/4 passes through both specified points.'))
for n,f,de in [(35,80*x-6*x*x,32),(36,10+45/(x+1),-s.Rational(9,5))]:
 add(n,('위치 '+m('s(t)='+tex(f).replace('x','t'))+' m인 입자의 t=4초 속도와 속력을 구하라.','For displacement '+m('s(t)='+tex(f).replace('x','t'))+' m, find velocity and speed at t=4 seconds.'),[(d('v(t)='+tex(s.diff(f,x)).replace('x','t')),d('v(t)='+tex(s.diff(f,x)).replace('x','t'))),('속도는 부호를 가진 위치 변화율, 속력은 그 절댓값이다.','Velocity is the signed position rate; speed is its absolute value.')],d('v(4)='+tex(de)+r'\ \mathrm{m/s},\quad |v(4)|='+tex(abs(de))+r'\ \mathrm{m/s}'),('차분몫 극한과 미분값을 비교했으며 음의 속도에서도 속력은 양수로 표시했다.','Compared the difference-quotient limit and derivative, and kept speed nonnegative even for negative velocity.'))
add(37,('따뜻한 음료를 차가운 냉장고에 넣었을 때 온도–시간 곡선을 그려라. 처음의 온도 변화율은 한 시간 뒤보다 큰가, 작은가?','Sketch temperature versus time for a warm drink placed in a cold refrigerator. Is its initial temperature rate greater or less than the rate after an hour?'),[('온도는 처음 빠르게 떨어지고 점차 냉장고 온도에 가까워져 평탄해진다. 따라서 기울기는 음수에서 0 쪽으로 증가한다.','Temperature initially falls rapidly and then levels toward refrigerator temperature. Its negative slope increases toward zero.'),('예시 모형 T(t)=4+20e⁻ᵗ에서 T′(0)=−20, T′(1)=−20/e이다.','An illustrative model T(t)=4+20e⁻ᵗ has T′(0)=−20 and T′(1)=−20/e.')],('처음의 부호 있는 변화율이 더 작다(더 음수). 냉각 속도의 크기는 처음이 더 크다.','The initial signed rate is smaller, meaning more negative. The magnitude of cooling is initially greater.'),('도해의 숫자는 현상 설명을 위한 예이며 원본에 없는 실제 온도나 냉각상수로 단정하지 않았다.','The plotted numbers are illustrative, not assertions of actual temperatures or a cooling constant absent from the source.'))
D.fig(37,[panel('Illustrative cooling toward refrigerator temperature',(0,5,0,26),[samples(lambda z:4+20*math.exp(-z),0,5),[(0,4),(5,4)]],xlabel='hours',ylabel='temperature')])
add(38,('185°F의 물체를 75°F 방에 꺼낸 원본 냉각 그래프에서 60분의 접선이 대략 (30분,150°F),(90분,105°F)을 지난다. 한 시간 뒤 온도 변화율을 추정하라.','In the source cooling graph, an object starts at 185°F in a 75°F room. The tangent at 60 minutes passes approximately through (30 min,150°F) and (90 min,105°F). Estimate the temperature rate after one hour.'),[(d(r'T\prime(60)\approx\frac{105-150}{90-30}=-0.75\ \mathrm{^\circ F/min}'),d(r'T\prime(60)\approx\frac{105-150}{90-30}=-0.75\ \mathrm{^\circ F/min}'))],('약 −0.75°F/min: 그때 분당 약 0.75°F씩 내려간다.','Approximately −0.75°F/min: temperature is falling by about 0.75°F per minute at that time.'),('접선 위 두 점은 눈금 판독 근사이며 곡선의 서로 먼 두 점으로 만든 평균변화율과 구별했다.','The two tangent points are approximate grid readings, distinguished from a secant average across distant curve points.'))
add(39,('f(0)=0,f′(0)=3,f′(1)=0,f′(2)=−1을 만족하는 함수의 그래프를 구성하라.','Construct a graph with f(0)=0,f′(0)=3,f′(1)=0,f′(2)=−1.'),[('세 기울기를 지나는 이차식 f′(x)=x²−4x+3을 택하고 상수를 0으로 정한다.','Choose the quadratic slope function f′(x)=x²−4x+3 and set the integration constant to zero.')],d(r'f(x)=x^3/3-2x^2+3x'),('f′(0)=3,f′(1)=0,f′(2)=−1과 f(0)=0을 직접 대입해 확인했다.','Direct substitution checks f′(0)=3,f′(1)=0,f′(2)=−1 and f(0)=0.'))
D.fig(39,[panel('Constructed cubic with prescribed slopes',(-.5,3.5,-2,3),[samples(lambda z:z**3/3-2*z*z+3*z,-.5,3.5)],[(0,0),(1,4/3),(2,2/3)])])
form40=r'g(x)=\begin{cases}x/(x+1)&-1<x<0\\(2/\pi)\sin(\pi x/2)&0\le x\le4\\(x-4)/(5-x)&4<x<5\end{cases}'
add(40,('g(0)=g(2)=g(4)=0,g′(1)=g′(3)=0,g′(0)=g′(4)=1,g′(2)=−1,lim(x→5⁻)g=∞,lim(x→−1⁺)g=−∞를 만족하는 그래프를 구성하라.','Construct a graph with g(0)=g(2)=g(4)=0,g′(1)=g′(3)=0,g′(0)=g′(4)=1,g′(2)=−1,lim(x→5⁻)g=∞,and lim(x→−1⁺)g=−∞.'),[(d(form40),d(form40)),('가운데 조각의 도함수는 cos(πx/2)이다. 양 끝 유리식은 0,4에서 값 0·기울기 1로 연결된다.','The middle derivative is cos(πx/2). The rational end pieces join with value zero and slope 1 at 0 and 4.'),('왼쪽의 x+1→0⁺이고 분자는 −1, 오른쪽의 5−x→0⁺이고 분자는 1로 간다.','On the left x+1→0⁺ with numerator approaching −1; on the right 5−x→0⁺ with numerator approaching 1.')],('위의 조각함수가 모든 조건을 만족한다.','The displayed piecewise function satisfies every condition.'),('접합점 0과 4에서 좌우 미분계수까지 일치함을 검산하여 단순 연속만 확보한 도해가 아님을 확인했다.','Checked matching one-sided derivatives at 0 and 4, ensuring the graph meets differentiability as well as continuity conditions.'))
D.fig(40,[panel('Sine arc joined to two poles',(-1,5,-4,4),[samples(lambda z:z/(z+1),-.99,0),samples(lambda z:2/math.pi*math.sin(math.pi*z/2),0,4),samples(lambda z:(z-4)/(5-z),4,4.99)],[(0,0),(2,0),(4,0)],xticks=[-1,0,1,2,3,4,5])])
form41=r'g(x)=\begin{cases}\frac1{x+5}+\frac{x+2}{9}-\frac13&-5<x<-2\\(x+2)^2/4&-2\le x\le0\\1+x-3x^2/25&0<x<5\end{cases}'
add(41,('정의역 (−5,5)에서 연속이고 g(0)=1,g′(0)=1,g′(−2)=0,lim(x→−5⁺)g=∞,lim(x→5⁻)g=3인 그래프를 구성하라.','Construct a continuous graph on domain (−5,5) satisfying g(0)=1,g′(0)=1,g′(−2)=0,lim(x→−5⁺)g=∞,and lim(x→5⁻)g=3.'),[(d(form41),d(form41)),('−2에서는 두 값이 0, 두 기울기도 0이다. 0에서는 두 값 1, 두 기울기 1로 이어진다.','At −2 both values and both slopes are zero. At 0 both values equal 1 and both slopes equal 1.'),('왼쪽 끝의 역수항은 +∞, 오른쪽 끝의 이차식은 1+5−3=3으로 간다.','The reciprocal term tends to +∞ at the left end, and the quadratic tends to 1+5−3=3 at the right end.')],('제시한 조각함수가 한 예이다.','The displayed piecewise function is one example.'),('모든 접합점의 값·미분계수와 두 끝점 극한을 별도로 확인했다.','Checked all junction values and derivatives and both endpoint limits separately.'))
D.fig(41,[panel('Continuous graph with constrained endpoint limits',(-5,5,-.5,6),[samples(lambda z:1/(z+5)+(z+2)/9-1/3,-4.99,-2),samples(lambda z:(z+2)**2/4,-2,0),samples(lambda z:1+z-3*z*z/25,0,5)],[(-2,0),(0,1),(5,3,'open')],xticks=[-5,-2,0,5])])
form42=r'f(x)=\begin{cases}\frac{2x}{4-x^2}-\frac52x&-2<x<2,\ x\ne\pm1\\0&x=\pm1\end{cases}'
add(42,('정의역 (−2,2), f′(0)=−2, lim(x→2⁻)f=∞, ±1에서만 불연속인 홀함수 f의 그래프를 구성하라.','Construct an odd function on domain (−2,2), with f′(0)=−2,lim(x→2⁻)f=∞,and discontinuities only at ±1.'),[(d(form42),d(form42)),('기본 유리식은 홀함수이고 원점 기울기는 1/2−5/2=−2이다. ±1의 두 값을 모두 0으로 바꾸어 홀대칭을 유지한다.','The base expression is odd, with origin slope 1/2−5/2=−2. Reassigning both ±1 values to zero preserves odd symmetry.'),('1의 극한은 −11/6, −1의 극한은 11/6으로 지정값 0과 다르다.','The limits at 1 and −1 are −11/6 and 11/6, differing from their assigned value zero.')],('위의 홀함수가 요구 조건을 만족한다.','The displayed odd function satisfies the conditions.'),('2의 왼쪽에서는 2x/(4−x²)→+∞이고 다른 항은 유한하다. 홀대칭에 의해 −2의 오른쪽은 −∞가 된다.','As x→2⁻ the term 2x/(4−x²) tends to +∞ while the other term stays finite. Odd symmetry gives −∞ at −2 from the right.'))
D.fig(42,[panel('Odd rational graph with two reassigned holes',(-2,2,-5,5),[samples(lambda z:2*z/(4-z*z)-2.5*z,-1.99,1.99,600)],[(-1,11/6,'open'),(-1,0),(1,-11/6,'open'),(1,0)],xticks=[-2,-1,0,1,2])])
for n,lim,fn,at,val in [(43,r'\lim_{h\to0}\frac{\sqrt{9+h}-3}{h}',r'\sqrt x','9','3'),(44,r'\lim_{h\to0}\frac{2^{3+h}-8}{h}',r'2^x','3','8'),(45,r'\lim_{x\to2}\frac{x^6-64}{x-2}',r'x^6','2','64'),(46,r'\lim_{x\to1/4}\frac{1/x-4}{x-1/4}',r'1/x','1/4','4'),(47,r'\lim_{h\to0}\frac{\tan(\pi/4+h)-1}{h}',r'\tan x',r'\pi/4','1'),(48,r'\lim_{\theta\to\pi/6}\frac{\sin\theta-1/2}{\theta-\pi/6}',r'\sin x',r'\pi/6','1/2')]:
 add(n,('극한 '+d(lim)+'을 f′(a)로 해석할 수 있는 함수 f와 수 a를 제시하라.','Identify a function f and number a whose derivative is represented by '+d(lim)),[('분자의 빼는 상수는 '+m('f(a)='+val)+'이고 분모는 입력에서 중심 a까지의 변화량이다.','The subtracted constant is '+m('f(a)='+val)+', and the denominator is the input displacement from a.')],d('f(x)='+fn+r',\quad a='+at),('선택한 f(a)를 대입해 분자의 상수를 회복하고 변화된 입력이 a+h 또는 x임을 확인했다.','Substitution recovers the numerator’s constant and verifies that the shifted input is a+h or x.'))
add(49,('생산비 C(x)=5000+10x+0.05x² 달러이다. (a)100→105,100→101의 평균변화율과 (b)x=100의 순간변화율을 구하라.','Production cost is C(x)=5000+10x+0.05x² dollars. Find (a)average rates from 100 to 105 and 100 to 101 and (b)the instantaneous rate at 100.'),[(d(r'\frac{C(100+h)-C(100)}h=20+0.05h'),d(r'\frac{C(100+h)-C(100)}h=20+0.05h')),('h=5,1을 대입하고 순간값은 h→0으로 구한다.','Substitute h=5 and 1; take h→0 for the instantaneous rate.')],('(a)20.25,20.05 달러/개; (b)20 달러/개.','(a)20.25,20.05 dollars per unit; (b)20 dollars per unit.'),('고정비 5000은 차분에서 소거되어 변화율에 영향을 주지 않는다.','The fixed cost 5000 cancels in differences and does not affect the rate.'),['a(i)','a(ii)','b'])
add(50,('H(t)는 외기온 t°F일 때 사무실의 하루 난방비(달러)이다. (a)H′(58)의 의미·단위, (b)예상 부호를 설명하라.','Let H(t) be the daily heating cost in dollars when outside temperature is t°F. Explain (a)the meaning and units of H′(58) and (b)its expected sign.'),[('58°F 부근에서 외기온이 1°F 증가할 때 하루 난방비가 얼마나 변하는지 나타낸다.','It measures the change in daily heating cost per 1°F increase in outside temperature near 58°F.'),('다른 조건이 같다면 더 따뜻할수록 난방 수요가 줄어 H′(58)<0을 기대한다.','With other conditions fixed, warmer outside air reduces heating demand, so H′(58)<0 is expected.')],('(a)달러/°F의 하루 난방비 변화율. (b)음수 예상.','(a)Rate of change of daily heating cost, in dollars/°F. (b)Expected negative.'),('독립변수는 시간이나 건물 면적이 아니라 외기온이며, 하루 비용이라는 출력의 의미를 유지했다.','The independent variable is outside temperature, not time or floor area; the output remains a daily cost.'),list('ab'))
add(51,('금 x온스를 생산하는 비용은 f(x)달러이다. (a)f′(x)의 의미·단위, (b)f′(800)=17의 해석, (c)단기·장기 변화 경향을 설명하라.','The cost of producing x ounces of gold is f(x) dollars. Explain (a)the meaning and units of f′(x), (b)f′(800)=17, and (c)possible short-run and long-run trends.'),[('(a)생산량 1온스 증가당 비용 증가율인 한계비용이며 달러/온스이다. (b)800온스 부근에서 1온스를 더 생산하면 비용이 약 $17 증가한다.','(a)It is marginal cost, the cost increase per extra ounce, in dollars/ounce. (b)Near 800 ounces, producing one more ounce increases cost by about $17.'),('(c)단기에는 경험·규모 효율로 감소할 수 있고, 장기에는 쉬운 광석 고갈과 더 어려운 채굴로 증가할 수 있다. 원문 조건만으로 필연적인 단조성은 정해지지 않는다.','(c)It may decrease initially through learning and scale efficiencies, then increase as easy ore is depleted and extraction becomes harder. The data do not force a particular monotonic trend.')],('f′는 한계비용이며 f′(800)=17은 약 $17/온스의 추가 비용을 뜻한다.','f′ is marginal cost; f′(800)=17 means an additional cost of approximately $17 per ounce.'),('17을 총비용이나 800온스 전체의 평균비용으로 해석하지 않았고 경향은 조건부 설명으로 제시했다.','Did not confuse 17 with total or average cost, and presented the trend as conditional.'),list('abc'))
add(52,('커피 가격 p달러/파운드에서 판매량 Q=f(p)파운드이다. (a)f′(8)의 의미·단위, (b)예상 부호를 설명하라.','Coffee sales are Q=f(p) pounds at a price p dollars per pound. Explain (a)the meaning and units of f′(8) and (b)its expected sign.'),[('가격이 $8/파운드 부근일 때 가격을 $1/파운드 올리는 데 따른 판매량 변화율이다.','It measures the sales change per $1/pound price increase near a price of $8/pound.'),('다른 조건이 같으면 가격 상승으로 수요가 줄어 음수를 예상한다.','With other conditions fixed, increasing price generally reduces demand, so the expected sign is negative.')],('(a)파운드/(달러/파운드)=파운드²/달러. (b)음수 예상.','(a)Pounds per (dollar/pound), equivalently pounds²/dollar. (b)Expected negative.'),('출력 단위 파운드를 입력 단위 달러/파운드로 나눈 것으로, 단순 파운드/달러와 구별했다.','Divided output pounds by input dollars/pound, distinguishing this from plain pounds/dollar.'),list('ab'))
add(53,('산소 용해도 S(mg/L)의 수온 T(°C) 그래프에서 S(8)≈12.4,S(16)≈10.4,S(24)≈8.8이다. (a)S′(T)의 의미·단위, (b)S′(16)을 접선으로 추정해 해석하라.','From the oxygen-solubility graph S in mg/L versus water temperature T in °C, S(8)≈12.4,S(16)≈10.4,S(24)≈8.8. (a)Interpret S′(T) and its units. (b)Estimate and interpret S′(16) from a tangent.'),[('도함수는 1°C 증가당 용해도 변화율로 단위는 (mg/L)/°C이다.','The derivative is the solubility change per 1°C increase, in (mg/L)/°C.'),('16 근처 접선은 이웃 점들로 얻은 중심 기울기 (8.8−12.4)/16=−0.225와 비슷하다.','The tangent near 16 is consistent with the neighboring centered slope (8.8−12.4)/16=−0.225.')],('S′(16)≈−0.23 (mg/L)/°C(그래프상 약 −0.2~−0.25). 16°C 부근에서 온도가 오르면 용해도가 줄어든다.','S′(16)≈−0.23 (mg/L)/°C, roughly −0.2 to −0.25 from the graph. Solubility decreases as temperature rises near 16°C.'),('이는 교재 도표의 근사 기울기이며 정확한 용해도 모형을 새로 가정하지 않았다.','This is an approximate slope from the textbook graph, without assuming a new exact solubility model.'),list('ab'))
add(54,('은연어의 최대 지속 유영속도 S(cm/s)와 수온 T(°C)의 원본 곡선은 약 19°C까지 상승한 뒤 내려간다. (a)S′의 의미·단위, (b)15°C와 25°C의 접선 기울기를 추정해 해석하라.','The source curve of maximum sustained Coho swimming speed S in cm/s versus water temperature T in °C rises to about 19°C and then falls. (a)Interpret S′ and its units. (b)Estimate and interpret tangent slopes at 15°C and 25°C.'),[('S′는 수온 1°C 증가당 최대 지속속도 변화량으로 (cm/s)/°C이다.','S′ measures the change in maximum sustained speed per 1°C rise, in (cm/s)/°C.'),('15°C의 완만한 상승 접선은 약 +1,25°C의 하강 접선은 약 −2이다.','The moderately rising tangent at 15°C is about +1; the falling tangent at 25°C is about −2.')],('S′(15)≈1, S′(25)≈−2 (cm/s)/°C. 15°C에서는 따뜻해지면 빨라지고 25°C에서는 느려진다.','S′(15)≈1 and S′(25)≈−2 (cm/s)/°C. Warming increases speed near 15°C but decreases it near 25°C.'),('기울기는 원본 곡선에서 읽은 근사치이다. 세로축 cm/s를 온도축 °C로 나눈 단위를 유지했다.','The slopes are graphical estimates, with units obtained by dividing cm/s by °C.'),list('ab'))
add(55,('교재의 평균 농도 자료는 t(시간)=1,1.5,2,2.5,3에 C(g/dL)=0.033,0.024,0.018,0.012,0.007이다. (a)[1,2],[1.5,2],[2,2.5],[2,3] 평균변화율, (b)2시간의 순간변화율을 추정하고 단위·의미를 쓰라.','The textbook mean-concentration data give C in g/dL as 0.033,0.024,0.018,0.012,0.007 at t=1,1.5,2,2.5,3 hours. (a)Find average rates on [1,2],[1.5,2],[2,2.5],[2,3]. (b)Estimate the instantaneous rate at 2 hours and interpret it with units.'),[('차례로 (0.018−0.033)/1, (0.018−0.024)/0.5, (0.012−0.018)/0.5, (0.007−0.018)/1을 계산한다.','Compute (0.018−0.033)/1, (0.018−0.024)/0.5, (0.012−0.018)/0.5, and (0.007−0.018)/1.'),('가까운 좌우 평균이 모두 −0.012이므로 그 평균으로 C′(2)를 추정한다.','The nearest left and right averages both equal −0.012, so use their average to estimate C′(2).')],('(a)−0.015,−0.012,−0.012,−0.011 (g/dL)/h. (b)약 −0.012 (g/dL)/h: 교재 평균자료의 농도가 그때 시간당 약 0.012 g/dL씩 감소한다.','(a)−0.015,−0.012,−0.012,−0.011 (g/dL)/h. (b)About −0.012 (g/dL)/h: the concentration in the textbook mean data is then decreasing by roughly 0.012 g/dL per hour.'),('중심 차분 (C(2.5)−C(1.5))/1도 −0.012이며, 표만으로 정확한 순간 미분계수가 결정되지는 않는다.','The centered quotient (C(2.5)−C(1.5))/1 also gives −0.012; the finite table does not determine an exact instantaneous derivative.'),['a(i)','a(ii)','a(iii)','a(iv)','b'])
# A smooth illustrative interpolation with the centered slope at 2010.
ys56=[2008,2010,2012,2014,2016];ns56=[16680,16858,18066,21366,25085]
def curve56(t):
 if t<=2010:
  u=(t-2008)/2;return 16680+19*u**3+159*u**4
 if t<=2012:
  u=(t-2010)/2;return 16858+693*u+515*u*u
 # Cubic Hermite continuation with endpoint slopes chosen for smooth joins.
 idx=2 if t<=2014 else 3;lo=ys56[idx];hi=ys56[idx+1];u=(t-lo)/(hi-lo)
 slopes=[0,346.5,861.5,1754.75,1859.5];p=ns56[idx];q=ns56[idx+1];dt=hi-lo
 return (2*u**3-3*u*u+1)*p+(u**3-2*u*u+u)*dt*slopes[idx]+(-2*u**3+3*u*u)*q+(u**3-u*u)*dt*slopes[idx+1]
add(56,('체인 점포 수 N은 2008,2010,2012,2014,2016년 각각 16680,16858,18066,21366,25085이다. (a)2008–2010과 2010–2012의 평균 성장률·결론, (b)두 평균으로 2010의 순간 성장률, (c)그래프 접선으로 같은 값을 추정하라.','A chain has 16680,16858,18066,21366,25085 locations in 2008,2010,2012,2014,2016. Find (a)average growth rates for 2008–2010 and 2010–2012 and compare them, (b)an instantaneous 2010 estimate from their average, and (c)a tangent-based graphical estimate.'),[('(a)(16858−16680)/2=89, (18066−16858)/2=604 점포/년으로 두 번째 기간 성장률이 더 크다.','(a)(16858−16680)/2=89 and (18066−16858)/2=604 locations/year; the second interval has faster growth.'),('(b)(89+604)/2=346.5 점포/년. (c)자료를 매끈하게 잇는 안내곡선에 그린 접선은 약 350 점포/년의 기울기를 보인다.','(b)(89+604)/2=346.5 locations/year. (c)A tangent on a smooth illustrative curve through the data has slope about 350 locations/year.')],('(a)89,604 점포/년; (b)346.5 점포/년; (c)약 350 점포/년.','(a)89,604 locations/year; (b)346.5 locations/year; (c)about 350 locations/year.'),('도해의 보간선은 점들을 잇는 한 예로 접선 추정값을 시각화한다. 유한한 표만으로 정확한 도함수를 정할 수 없음을 명시한다.','The interpolation is one illustrative curve through the data, visualizing the tangent estimate. A finite table cannot determine an exact derivative.'),['a(i)','a(ii)','b','c'])
D.fig(56,[panel('Locations and illustrative 2010 tangent',(2008,2016,16000,26000),[samples(curve56,2008,2016),[(2008,16858-693),(2012,16858+693)]],list(zip(ys56,ns56)),xticks=ys56,yticks=[16000,18000,20000,22000,24000,26000],xlabel='year',ylabel='locations')])
for n,power in [(57,1),(58,2)]:
 add(n,('f(x)='+m('x'+('^2'if power==2 else'')+r'\sin(1/x)')+'(x≠0), f(0)=0에서 f′(0)의 존재 여부를 판단하라.','For f(x)='+m('x'+('^2'if power==2 else'')+r'\sin(1/x)')+' when x≠0 and f(0)=0, determine whether f′(0) exists.'),[(d(r'\frac{f(h)-f(0)}h='+('h'if power==2 else'')+r'\sin(1/h)'),d(r'\frac{f(h)-f(0)}h='+('h'if power==2 else'')+r'\sin(1/h)')),(('h=1/(π/2+2kπ)와 1/(3π/2+2kπ)에서 차분몫은 각각 1,−1이다.'if power==1 else'|h sin(1/h)|≤|h|→0이므로 조임정리를 적용한다.'),('Along h=1/(π/2+2kπ) and h=1/(3π/2+2kπ), the quotients equal 1 and −1.'if power==1 else'Use the bound |h sin(1/h)|≤|h|→0 and the Squeeze Theorem.'))],('f′(0)은 존재하지 않는다.'if power==1 else'f′(0)=0.','f′(0) does not exist.'if power==1 else'f′(0)=0.'),('함수 자체의 연속성 대신 차분몫의 극한을 조사했다. 두 함수 모두 0에서 연속이지만 미분 가능성은 다르다.','Examined the difference-quotient limit rather than continuity alone. Both functions are continuous at zero, but their differentiability differs.'))
fn59=lambda z:math.sin(z)-math.sin(1000*z)/1000
add(59,('f(x)=sin x−sin(1000x)/1000을 (a)[−2π,2π]×[−4,4], (b)[−0.4,0.4]×[−0.25,0.25], (c)[−0.008,0.008]×[−0.005,0.005]에서 확대하며 f′(0)의 추정을 비교하라.','Plot f(x)=sin x−sin(1000x)/1000 on (a)[−2π,2π]×[−4,4], (b)[−0.4,0.4]×[−0.25,0.25], and (c)[−0.008,0.008]×[−0.005,0.005], comparing estimates of f′(0).'),[('(a),(b)에서는 진폭 0.001의 빠른 진동이 잘 보이지 않아 기울기가 1처럼 보일 수 있다. (c)에서는 원점에서 평평해지는 모양이 드러난다.','In (a) and (b) the fast oscillation of amplitude 0.001 is hard to see, so the slope may appear to be 1. In (c) the flattening at the origin becomes visible.'),(d(r'\frac{f(h)}h=\frac{\sin h}h-\frac{\sin(1000h)}{1000h}\longrightarrow1-1=0'),d(r'\frac{f(h)}h=\frac{\sin h}h-\frac{\sin(1000h)}{1000h}\longrightarrow1-1=0'))],('큰 화면에서는 약 1로 보이지만 실제 f′(0)=0이며 마지막 확대에서 추정을 수정한다.','Large windows can suggest about 1, but the true derivative is f′(0)=0, revealed by the final zoom.'),('원점 기울기는 차분몫의 두 사인 극한으로 독립 확인했다. 큰 화면의 점 샘플만으로 미세 진동의 기울기를 판단하지 않는다.','The two sine limits independently establish the slope. Large-window point sampling alone cannot determine the fine-scale tangent.'),list('abc'))
D.fig(59,[panel(f'Zoom window: +/-{w:g}',(-w,w,-v,v),[samples(fn59,-w,w,count)],[(0,0)])for w,v,count in [(2*math.pi,4,18000),(.4,.25,2500),(.008,.005,1200)]])
f=x**3-2*x*x+2;dlt=s.Rational(2,5);vleft=s.simplify((f.subs(x,1)-f.subs(x,1-dlt))/dlt);vright=s.simplify((f.subs(x,1+dlt)-f.subs(x,1))/dlt);vcenter=(vleft+vright)/2
add(60,('중심차분 [f(a+d)−f(a−d)]/(2d)를 사용하라. (a)교재 예제의 D(2004)=7596.1,D(2008)=10699.8,D(2012)=16432.7(십억 달러)로 2008 증가율을 구하라. (b)중심차분이 두 이웃 평균변화율의 평균임을 증명하라. (c)f(x)=x³−2x²+2,a=1,d=0.4에서 미분계수를 추정하고 세 할선 그래프를 비교하라.','Use the centered quotient [f(a+d)−f(a−d)]/(2d). (a)Estimate the 2008 rate from textbook values D(2004)=7596.1,D(2008)=10699.8,D(2012)=16432.7 billion dollars. (b)Prove that it equals the average of the two adjacent average rates. (c)For f(x)=x³−2x²+2,a=1,d=0.4, estimate the derivative and compare the three secants graphically.'),[('(a)(16432.7−7596.1)/8=1104.575 십억 달러/년으로 예제의 약 1105와 일치한다.','(a)(16432.7−7596.1)/8=1104.575 billion dollars/year, agreeing with the example’s approximate 1105.'),(d(r'\frac12\left[\frac{f(a)-f(a-d)}d+\frac{f(a+d)-f(a)}d\right]=\frac{f(a+d)-f(a-d)}{2d}'),d(r'\frac12\left[\frac{f(a)-f(a-d)}d+\frac{f(a+d)-f(a)}d\right]=\frac{f(a+d)-f(a-d)}{2d}')),('(c)왼쪽·오른쪽 할선 기울기는 −1.24,−0.44이므로 중심차분은 −0.84이다. 정확한 f′(1)=−1에 대한 오차는 각각 0.24,0.56,0.16이다.','(c)Left and right secant slopes are −1.24 and −0.44, giving centered slope −0.84. Their errors relative to exact f′(1)=−1 are 0.24,0.56,0.16.')],('(a)1104.575 십억 달러/년; (c)f′(1)≈−0.84, 중심 할선이 세 후보 중 가장 가깝다.','(a)1104.575 billion dollars/year; (c)f′(1)≈−0.84, with the centered secant closest among the three.'),('원본 예제 표를 PDF152에서 직접 확인했다. (c)의 정확한 중심차분은 −1+d²여서 d=0.4의 오차가 0.16임을 별도로 확인한다.','Checked the original example table directly on PDF152. In (c), the centered quotient is exactly −1+d², independently giving error 0.16 at d=0.4.'),list('abc'))
cs=[samples(lambda z:z**3-2*z*z+2,.4,1.6)]
for lo,hi in [(s.Rational(3,5),1),(1,s.Rational(7,5)),(s.Rational(3,5),s.Rational(7,5))]:
 v=s.simplify((f.subs(x,hi)-f.subs(x,lo))/(hi-lo));y0=f.subs(x,lo);cs.append([(.4,float(y0+v*(s.Rational(2,5)-lo))),(1.6,float(y0+v*(s.Rational(8,5)-lo)))])
cs.append([(.4,1.6),(1.6,.4)])
D.fig(60,[panel('Three secants and the exact tangent',(.4,1.6,.2,1.8),cs,[(.6,float(f.subs(x,s.Rational(3,5)))),(1,1),(1.4,float(f.subs(x,s.Rational(7,5))))],xticks=[.6,1,1.4])])
normalize_prose_inequalities(D)
D.save(60)
