"""Original vector-function solutions and exact coordinate checks."""
from early_helpers import Book
from pathlib import Path
import sympy as s,json,math
b=Book('13.1',[933,934,935,936]);t=s.symbols('t',real=True);checks=[]
def m(x):return r'\('+x+r'\)'
def tex(x):return s.latex(s.simplify(x))
def v(a):return r'\langle '+','.join(tex(x)for x in a)+r'\rangle'
def add(n,k,e,ks,es,ans,ae=None,parts=[]):
 b.add(n,933 if n<=4 else 934 if n<=40 else 935 if n<=60 else 936,('벡터함수와 공간곡선','Vector functions and space curves'),(k,e),list(zip(ks,es)),(ans,ans if ae is None else ae),parts,check=('각 성분의 조건·극한 또는 소거한 관계식에 대입하여 확인했다.','Checked the coordinate conditions, limits, or substitutions in the eliminated relations.'));b.E[n]['conceptHref']='../../calc1/index.html'
def eq(label,a,c=0):assert s.simplify(a-c)==0,(label,a,c);checks.append(label)
add(1,m(r'r(t)=\langle\ln(t+1),t/\sqrt{9-t^2},2^t\rangle')+'의 정의역을 구하라.','Find the domain of '+m(r'r(t)=\langle\ln(t+1),t/\sqrt{9-t^2},2^t\rangle')+'.',[m(r't+1>0,\quad9-t^2>0'),'분모의 제곱근은0이 될 수 없다. 지수함수는 모든 실수에서 정의된다.'],[m(r't+1>0,\quad9-t^2>0'),'The square-root denominator cannot be zero; the exponential is defined for every real t.'],m('(-1,3)'))
add(2,m(r'r(t)=\langle\cos t,\ln t,1/(t-2)\rangle')+'의 정의역을 구하라.','Find the domain of '+m(r'r(t)=\langle\cos t,\ln t,1/(t-2)\rangle')+'.',[m(r't>0,\quad t\ne2')],[m(r't>0,\quad t\ne2')],m(r'(0,2)\cup(2,\infty)'))
for n,ff,at,known,ks,es in [(3,[s.exp(-3*t),t**2/s.sin(t)**2,s.cos(2*t)],0,[1,1,1],[r'\frac{t^2}{\sin^2t}=\left(\frac{t}{\sin t}\right)^2\to1'],[r'\frac{t^2}{\sin^2t}=\left(\frac{t}{\sin t}\right)^2\to1']),(4,[(t*t-t)/(t-1),s.sqrt(t+8),s.sin(s.pi*t)/s.log(t)],1,[1,3,-s.pi],[r'\frac{t^2-t}{t-1}=t,\quad\sqrt{t+8}\to3',r'\frac{\sin\pi t}{\ln t}\to\frac{\pi\cos\pi}{1}=-\pi'],[r'\frac{t^2-t}{t-1}=t,\quad\sqrt{t+8}\to3',r'\frac{\sin\pi t}{\ln t}\to\frac{\pi\cos\pi}{1}=-\pi']),(5,[(1+t*t)/(1-t*t),s.atan(t),(1-s.exp(-2*t))/t],s.oo,[-1,s.pi/2,0],[r'\frac{1+t^2}{1-t^2}=\frac{t^{-2}+1}{t^{-2}-1}\to-1',r'\tan^{-1}t\to\pi/2,\quad(1-e^{-2t})/t\to0'],[r'\frac{1+t^2}{1-t^2}=\frac{t^{-2}+1}{t^{-2}-1}\to-1',r'\tan^{-1}t\to\pi/2,\quad(1-e^{-2t})/t\to0']),(6,[t*s.exp(-t),(t**3+t)/(2*t**3-1),t*s.sin(1/t)],s.oo,[0,s.Rational(1,2),1],[r'te^{-t}\to0,\quad\frac{t^3+t}{2t^3-1}\to\frac12',r't\sin(1/t)=\frac{\sin(1/t)}{1/t}\to1'],[r'te^{-t}\to0,\quad\frac{t^3+t}{2t^3-1}\to\frac12',r't\sin(1/t)=\frac{\sin(1/t)}{1/t}\to1'])]:
 for j,(f,a)in enumerate(zip(ff,known)):eq(f'{n} limit component{j}',s.limit(f,t,at),a)
 add(n,m(r'\lim_{t\to'+tex(at)+'}'+v(ff))+'를 구하라.','Evaluate '+m(r'\lim_{t\to'+tex(at)+'}'+v(ff))+'.',[m(q)for q in ks],[m(q)for q in es],m(v(known)))
curves=[(7,[-s.cos(t),t],r'x=-\cos y','y가 증가하는 옆으로 놓인 코사인 곡선. t=0에서(−1,0),t=π에서(1,π)이다.','A sideways cosine curve traversed toward increasing y; t=0 gives(−1,0)and t=π gives(1,π).'),(8,[t*t-1,t],r'x=y^2-1','꼭짓점(−1,0)의 오른쪽으로 열린 포물선. y가 증가하는 방향이다.','A right-opening parabola with vertex(−1,0), traversed toward increasing y.'),(9,[3*s.sin(t),2*s.cos(t)],r'x^2/9+y^2/4=1','t=0의(0,2)에서 오른쪽으로 출발하여 시계방향으로 돈다.','Starts at(0,2)when t=0 and moves right, hence clockwise.'),(10,[s.exp(t),s.exp(-t)],r'xy=1,\quad x>0,y>0','제1사분면 쌍곡선 위에서 x가 증가하고 y가 감소한다.','Along the first-quadrant hyperbola, x increases and y decreases.'),(11,[t,2-t,2*t],r'y=2-x,\quad z=2x','(0,2,0)을 지나 방향(1,−1,2)로 진행하는 직선이다.','A line through(0,2,0), directed along(1,−1,2).'),(12,[s.sin(s.pi*t),t,s.cos(s.pi*t)],r'x^2+z^2=1','y축 주위 반지름1 나선. t가2증가하면 한 바퀴 돌며 y가2높아진다. t=0에서(0,0,1),초기 방향은(π,1,0)이다.','A unit-radius helix about y. Increasing t by2 completes a turn and advances y by2. It starts at(0,0,1)with initial direction(π,1,0).'),(13,[3,t,2-t*t],r'x=3,\quad z=2-y^2','x=3평면의 아래로 열린 포물선이며 y가 증가한다.','A downward parabola in x=3, traversed toward increasing y.'),(14,[2*s.cos(t),2*s.sin(t),1],r'x^2+y^2=4,\quad z=1','z=1의 반지름2 원. 위에서 보면 반시계방향이며 t=0은(2,0,1)이다.','A radius2 circle in z=1, counterclockwise viewed from above; t=0 is(2,0,1).'),(15,[t*t,t**4,t**6],r'y=x^2,\quad z=x^3,\quad x\ge0','뒤틀린 삼차곡선의 x≥0부분. t<0에서 원점으로 접근하고 t>0에서 같은 자취를 반대로 나간다.','The x≥0 portion of a twisted cubic; for t<0 it approaches the origin, then retraces outward for t>0.'),(16,[s.cos(t),-s.cos(t),s.sin(t)],r'y=-x,\quad x^2+z^2=1','기울어진 평면 y=−x의 타원이다. t=0의(1,−1,0)에서 위쪽으로 움직인다. 공간에서의 반축 길이는√2와1이다.','An ellipse in y=−x; it moves upward from(1,−1,0)at t=0. Its spatial semiaxes have lengths√2 and1.')]
for n,ff,formula,ko,en in curves:add(n,m('r(t)='+v(ff))+'의 자취를 그리고 t가 증가하는 방향을 표시하라.','Sketch '+m('r(t)='+v(ff))+' and indicate increasing t.',[m(formula),ko],[m(formula),en],ko,en)
add(17,m(r'r(t)=\langle t^2,t^3,t^{-3}\rangle')+'를 yz평면에 사영하여 그려라.','Draw the yz projection of '+m(r'r(t)=\langle t^2,t^3,t^{-3}\rangle')+'.',[m(r'y=t^3,\quad z=t^{-3}\Rightarrow yz=1,\quad t\ne0')],[m(r'y=t^3,\quad z=t^{-3}\Rightarrow yz=1,\quad t\ne0')],m(r'x=0,\quad z=1/y,\quad y\ne0')+'; 두 쌍곡선 가지.',m(r'x=0,\quad z=1/y,\quad y\ne0')+'; both hyperbola branches.')
add(18,m(r'r(t)=\langle t+1,3t+1,\cos(t/2)\rangle')+'를 xy평면에 사영하여 그려라.','Draw the xy projection of '+m(r'r(t)=\langle t+1,3t+1,\cos(t/2)\rangle')+'.',[m(r't=x-1,\quad y=3(x-1)+1')],[m(r't=x-1,\quad y=3(x-1)+1')],m(r'y=3x-2,\quad z=0'))
add(19,m(r'r(t)=\langle t,\sin t,2\cos t\rangle')+'의 세 좌표평면 사영을 그리고 공간곡선을 그려라.','Sketch the coordinate projections and spatial curve of '+m(r'r(t)=\langle t,\sin t,2\cos t\rangle')+'.',[m(r'xy:\ y=\sin x;\quad xz:\ z=2\cos x;\quad yz:\ y^2+z^2/4=1'),'x축을 따라 전진하는 타원 나선이며 한 회전당 x가2π증가한다.'],[m(r'xy:\ y=\sin x;\quad xz:\ z=2\cos x;\quad yz:\ y^2+z^2/4=1'),'An elliptical helix advancing along x by2π each turn.'],m(r'y^2+z^2/4=1')+' 위의 타원 나선.', 'An elliptical helix on '+m(r'y^2+z^2/4=1')+'.')
add(20,m(r'r(t)=\langle t,t,t^2\rangle')+'의 세 좌표평면 사영을 그리고 공간곡선을 그려라.','Sketch the coordinate projections and spatial curve of '+m(r'r(t)=\langle t,t,t^2\rangle')+'.',[m(r'xy:\ y=x;\quad xz:\ z=x^2;\quad yz:\ z=y^2'),'공간 자취는 평면 y=x안에서 위로 열린 포물선이다.'],[m(r'xy:\ y=x;\quad xz:\ z=x^2;\quad yz:\ z=y^2'),'The spatial curve is an upward parabola in the plane y=x.'],m(r'y=x,\quad z=x^2'))
for n,aa,bb in [(21,[-2,1,0],[5,2,-3]),(22,[0,0,0],[-7,4,6]),(23,[s.Rational(35,10),s.Rational(-14,10),s.Rational(21,10)],[s.Rational(18,10),s.Rational(3,10),s.Rational(21,10)]),(24,list(s.symbols('a b c')),list(s.symbols('u v w')))]:
 p,q=s.Matrix(aa),s.Matrix(bb);r=p+t*(q-p)
 for j in range(3):eq(f'{n} end{j}',r[j].subs(t,1),q[j])
 ans=m('r(t)='+v(p)+'+t'+v(q-p)+r',\quad0\le t\le1')+'; '+m(r',\quad '.join(a+'='+tex(vv)for a,vv in zip(['x','y','z'],r)))
 add(n,'P='+m(v(p))+',Q='+m(v(q))+'를 잇는 선분의 벡터식과 매개식을 구하라.','Find vector and parametric equations for the segment from P='+m(v(p))+' to Q='+m(v(q))+'.',[m(r'r(t)=(1-t)P+tQ,\quad0\le t\le1')],[m(r'r(t)=(1-t)P+tQ,\quad0\le t\le1')],ans)
matchrows=[(25,[t*s.cos(t),t,t*s.sin(t)],'II',r'x^2+z^2=t^2=y^2','y가 증가할수록 반지름이 커지는 원뿔 나선이다.','A conical spiral about y whose radius grows with y.'),(26,[s.cos(t),s.sin(t),1/(1+t*t)],'VI',r'x^2+y^2=1,\quad0<z\le1','t=0에서 최고점z=1이며 |t|→∞에서는 아래쪽 원에 점점 가까워진다.','The maximum height1 occurs at t=0; as |t|→∞ the curve approaches the bottom circle.'),(27,[t,1/(1+t*t),t*t],'V',r'z=x^2,\quad y=1/(1+z)','z≥0이며(0,1,0)에서 출발하는 두 가지가 위로 갈수록 y=0에 가까워진다.','With z≥0, two branches from(0,1,0)approach y=0 as they rise.'),(28,[s.cos(t),s.sin(t),s.cos(2*t)],'I',r'x^2+y^2=1,\quad z=x^2-y^2','높이가 한 회전당 두 번 진동하는 닫힌 곡선이다.','A closed curve whose height oscillates twice per revolution.'),(29,[s.cos(8*t),s.sin(8*t),s.exp(s.Rational(4,5)*t)],'IV',r'x^2+y^2=1,\quad z=e^{0.8t}','t≥0에서 위로 갈수록 회전 사이 높이 간격이 커지는 나선이다.','For t≥0 the helix has increasing vertical gaps between successive turns.'),(30,[s.cos(t)**2,s.sin(t)**2,t],'III',r'x+y=1,\quad0\le x,y\le1','평면x+y=1안에서 좌우로 진동하면서 z가 증가한다.','It oscillates within the plane x+y=1 while z increases.')]
choicesko='원본 그림의 형태는 I:닫힌 상하 진동곡선, II:y축 원뿔 나선, III:수직 평면의 파형, IV:위로 갈수록 간격이 커지는 나선, V:위로 뻗는 두 가지, VI:아래쪽 원에 접근하는 감김이다. '
choicesen='Original choices: I a closed vertically oscillating curve; II a conical spiral about y; III a wave in a vertical plane; IV a helix with increasing gaps; V two rising branches; VI coils approaching a bottom circle. '
for n,ff,label,formula,ko,en in matchrows:add(n,choicesko+m('r(t)='+v(ff))+(' (t≥0)'if n in[25,29]else'')+'에 맞는 그림을 골라 이유를 설명하라.',choicesen+'Match '+m('r(t)='+v(ff))+(' (t≥0)'if n in[25,29]else'')+' and justify.',[m(formula),ko],[m(formula),en],label+'; '+ko,label+'; '+en)
for n,ff,formula in [(31,[t,4,t*t],'y=4'),(32,[t,t*t,t],'x-z=0'),(33,[s.sin(t),s.cos(t),-s.cos(t)],'y+z=0'),(34,[2*t,s.sin(t),t+1],'x-2z+2=0')]:add(n,m('r(t)='+v(ff))+'를 포함하는 평면을 구하라.','Find a plane containing '+m('r(t)='+v(ff))+'.',['성분 사이의 선형 관계를 찾으면 t와 무관한 평면식을 얻는다.'],['A linear relation between coordinates eliminates t and gives a plane equation.'],m(formula))
eq('35 cone', (t*s.cos(t))**2+(t*s.sin(t))**2,t*t)
add(35,m(r'r(t)=\langle t\cos t,t\sin t,t\rangle')+'가 원뿔z²=x²+y² 위에 있음을 보이고 곡선을 그려라.','Prove that '+m(r'r(t)=\langle t\cos t,t\sin t,t\rangle')+' lies on z²=x²+y² and sketch it.',[m(r'x^2+y^2=t^2(\cos^2t+\sin^2t)=t^2=z^2'),'수평 반지름은|t|,높이는t이다. 음의t는 아래 원뿔에서 원점으로 접근하고 양의t는 위 원뿔을 감으며 커진다.'],[m(r'x^2+y^2=t^2(\cos^2t+\sin^2t)=t^2=z^2'),'The horizontal radius is|t|and height is t. Negative t approaches the origin on the lower cone; positive t spirals outward on the upper cone.'],m(r'z^2=x^2+y^2')+' 위의 양쪽 원뿔 나선.', 'A spiral on both nappes of '+m(r'z^2=x^2+y^2')+'.')
eq('36 cylinder',s.sin(t)**2+s.cos(t)**2,1)
add(36,m(r'r(t)=\langle\sin t,\cos t,\sin^2t\rangle')+'가 z=x²와x²+y²=1의 교선임을 보이고 그려라.','Show that '+m(r'r(t)=\langle\sin t,\cos t,\sin^2t\rangle')+' is the intersection of z=x² and x²+y²=1, and sketch it.',[m(r'z=\sin^2t=x^2,\quad x^2+y^2=1'),'반대로 단위원의 모든(x,y)는(sin t,cos t)로 나타나고 z=x²가 유일하게 결정된다. 높이는0부터1까지 두 번 오르내리는 닫힌 곡선이다.'],[m(r'z=\sin^2t=x^2,\quad x^2+y^2=1'),'Conversely every point of the unit circle is(sin t,cos t), and z=x² fixes its height. The resulting closed curve rises and falls twice between0 and1.'],m(r'z=x^2,\quad x^2+y^2=1'))
add(37,m(r'r(t)=\langle2t,e^t,e^{2t}\rangle')+'를 포함하는 서로 다른 곡면 세 개를 구하라.','Find three distinct surfaces containing '+m(r'r(t)=\langle2t,e^t,e^{2t}\rangle')+'.',[m(r't=x/2\Rightarrow y=e^{x/2},\quad z=e^x'),m(r'z=(e^t)^2=y^2')],[m(r't=x/2\Rightarrow y=e^{x/2},\quad z=e^x'),m(r'z=(e^t)^2=y^2')],m(r'y=e^{x/2},\quad z=e^x,\quad z=y^2'))
add(38,m(r'r(t)=\langle t^2,\ln t,1/t\rangle')+'를 포함하는 서로 다른 곡면 세 개를 구하라.','Find three distinct surfaces containing '+m(r'r(t)=\langle t^2,\ln t,1/t\rangle')+'.',[m(r't>0,\quad t=e^y\Rightarrow x=e^{2y},\quad z=e^{-y}'),m(r'xz^2=t^2/t^2=1')],[m(r't>0,\quad t=e^y\Rightarrow x=e^{2y},\quad z=e^{-y}'),m(r'xz^2=t^2/t^2=1')],m(r'x=e^{2y},\quad z=e^{-y},\quad xz^2=1'))
add(39,m(r'r(t)=\langle t,0,2t-t^2\rangle')+'와 z=x²+y²의 교점을 구하라.','Find the intersections of '+m(r'r(t)=\langle t,0,2t-t^2\rangle')+' with z=x²+y².',[m(r'2t-t^2=t^2\Rightarrow2t(1-t)=0\Rightarrow t=0,1')],[m(r'2t-t^2=t^2\Rightarrow2t(1-t)=0\Rightarrow t=0,1')],m(r'(0,0,0),\quad(1,0,1)'))
add(40,m(r'r(t)=\langle\sin t,\cos t,t\rangle')+'와 구x²+y²+z²=5의 교점을 구하라.','Find the intersections of '+m(r'r(t)=\langle\sin t,\cos t,t\rangle')+' with x²+y²+z²=5.',[m(r'\sin^2t+\cos^2t+t^2=5\Rightarrow t^2=4\Rightarrow t=\pm2')],[m(r'\sin^2t+\cos^2t+t^2=5\Rightarrow t^2=4\Rightarrow t=\pm2')],m(r'(\sin2,\cos2,2),\quad(-\sin2,\cos2,-2)'))
# Continuation above the next section heading on printed935–936.
extra_curves=[(41,[s.cos(t)*s.sin(2*t),s.sin(t)*s.sin(2*t),s.cos(2*t)],r'x^2+y^2+z^2=1','단위구를 감는 닫힌 곡선이다. 0≤t≤2π에서 전체 자취를 확인한다.','A closed curve on the unit sphere; use0≤t≤2π to see the full trace.'),(42,[t*s.exp(t),s.exp(-t),t],r'xy=z,\quad y=e^{-z}','주기적이지 않다. t<0과t>0의 비대칭적인 뻗음을 여러 시점에서 본다.','It is nonperiodic; multiple views show the asymmetric negative- and positive-t branches.'),(43,[s.sin(3*t)*s.cos(t),t/4,s.sin(3*t)*s.sin(t)],r'x^2+z^2=\sin^2(3t)','y축을 따라 전진하면서 반지름이 주기적으로0과1사이를 변한다. t=kπ/3에서y축을 지난다.','It advances along y while the radius varies between0 and1; it crosses the axis at t=kπ/3.'),(44,[s.cos(8*s.cos(t))*s.sin(t),s.sin(8*s.cos(t))*s.sin(t),s.cos(t)],r'x^2+y^2+z^2=1','구 위의 진동하는 감김이다. 0≤t≤2π를 사용하고 z축 방향에서도 확인한다.','An oscillating wrap on a unit sphere; plot0≤t≤2π and also view along z.'),(45,[s.cos(2*t),s.cos(3*t),s.cos(4*t)],r'z=2x^2-1','상자[−1,1]³안의 유한 자취이다. [0,π]에서 한 번 그리고[π,2π]에서 역으로 따라간다.','A bounded trace in[−1,1]³;[0,π]traces it once and[π,2π]retraces it backward.')]
for n,ff,relation,ko,en in extra_curves:add(n,m('r(t)='+v(ff))+'를 적절한 구간과 여러 시점으로 그려 모양을 설명하라.','Graph '+m('r(t)='+v(ff))+' with suitable parameter ranges and viewpoints; describe its shape.',[m(relation),ko],[m(relation),en],ko,en)
add(46,m(r'r(t)=\langle\sin t,\sin2t,\cos4t\rangle')+'를 그리고 세 좌표평면 사영으로 모양을 설명하라.','Plot '+m(r'r(t)=\langle\sin t,\sin2t,\cos4t\rangle')+' and explain it through all coordinate projections.',[m(r'xy:\ y^2=4x^2(1-x^2),\quad |x|\le1'),m(r'xz:\ z=1-8x^2+8x^4'),m(r'yz:\ z=1-2y^2,\quad |y|\le1'),'xy사영은8자형이며 나머지 두 사영이 그 위의 높이를 결정한다.'],[m(r'xy:\ y^2=4x^2(1-x^2),\quad |x|\le1'),m(r'xz:\ z=1-8x^2+8x^4'),m(r'yz:\ z=1-2y^2,\quad |y|\le1'),'The xy projection is a figure eight; the other projections determine its height.'],m(r'y^2=4x^2(1-x^2),\quad z=1-2y^2'))
add(47,'x=(1+cos16t)cos t,y=(1+cos16t)sin t,z=1+cos16t를 그리고 원뿔 위에 놓임을 보여라.','Graph x=(1+cos16t)cos t,y=(1+cos16t)sin t,z=1+cos16t and show it lies on a cone.',[m(r'x^2+y^2=(1+\cos16t)^2=z^2,\quad0\le z\le2'),'한 회전에서 반지름이16번 늘었다 줄며 원점에16번 닿는다.'],[m(r'x^2+y^2=(1+\cos16t)^2=z^2,\quad0\le z\le2'),'During one revolution the radius expands and contracts16 times, meeting the apex16 times.'],m(r'z=\sqrt{x^2+y^2},\quad0\le z\le2'))
add(48,'A(t)=√(1−0.25cos²10t)라 하자. x=A(t)cos t,y=A(t)sin t,z=0.5cos10t를 그리고 어떤 구 위에 놓이는지 보여라.','Let A(t)=√(1−0.25cos²10t). Plot x=A(t)cos t,y=A(t)sin t,z=0.5cos10t and identify its sphere.',[m(r'x^2+y^2=1-\tfrac14\cos^2(10t),\quad z^2=\tfrac14\cos^2(10t)'),'단위구의 적도 부근에서 높이가−1/2와1/2사이를10번 진동한다.'],[m(r'x^2+y^2=1-\tfrac14\cos^2(10t),\quad z^2=\tfrac14\cos^2(10t)'),'It oscillates10 times between heights−1/2 and1/2 near the equator of the unit sphere.'],m('x^2+y^2+z^2=1'))
add(49,'x=t²,y=1−3t,z=1+t³이(1,4,0),(9,−8,28)을 지나지만(4,7,−6)을 지나지 않음을 보여라.','Show that x=t²,y=1−3t,z=1+t³ passes through(1,4,0),(9,−8,28), but not(4,7,−6).',[m(r't=-1\Rightarrow(1,4,0),\quad t=3\Rightarrow(9,-8,28)'),'세 번째 점의 y=7은t=−2를 강제하는데 이때z=−7이므로 주어진−6과 다르다.'],[m(r't=-1\Rightarrow(1,4,0),\quad t=3\Rightarrow(9,-8,28)'),'For the third point, y=7 forces t=−2, whose z=−7 differs from−6.'],'첫 두 점만 곡선 위에 있다.','Only the first two points lie on the curve.')
intersectionrows=[(50,[2*s.cos(t),2*s.sin(t),4*s.cos(t)*s.sin(t)],'x²+y²=4, z=xy',r'0\le t\le2\pi'),(51,[t,(t*t-1)/2,(t*t+1)/2],'z=√(x²+y²), z=1+y',r't\in\mathbb R'),(52,[t,t*t,4*t*t+t**4],'z=4x²+y², y=x²',r't\in\mathbb R'),(53,[s.cos(t),s.sin(t),s.cos(2*t)],'z=x²−y², x²+y²=1',r'0\le t\le2\pi'),(54,[s.cos(t),s.sqrt(3)*s.Abs(s.cos(t)),s.sin(t)],'x²+y²+4z²=4,y≥0, x²+z²=1',r'0\le t\le2\pi')]
for n,ff,st,domain in intersectionrows:
 ko='첫 곡면의 원형 단면을 삼각함수로 나타내고 나머지 좌표를 대입해 구한다.'if n in[50,53,54]else'x=t로 두고 두 식을 순서대로 풀어y,z를 구한다.'
 en='Parametrize the circular section trigonometrically and substitute to obtain the remaining coordinate.'if n in[50,53,54]else'Set x=t and solve the two equations successively for y,z.'
 if n==51:ko+=' 제곱 후 z=(t²+1)/2>0이므로 원래 양의 제곱근 조건도 만족한다.';en+=' After squaring, z=(t²+1)/2>0 also satisfies the original positive-root condition.'
 if n==54:ko+=' y≥0이므로 y=√3|cos t|에서 절댓값이 필요하다.';en+=' The absolute value in y=√3|cos t| enforces y≥0.'
 add(n,'두 곡면 '+st+'의 교선을 나타내는 벡터함수를 구하라.','Parametrize the intersection of '+st+'.',[ko],[en],m('r(t)='+v(ff)+r',\quad '+domain))
add(55,'x²+y²=4와z=x²의 교선을 먼저 개형으로 그리고 매개식을 구해 확인하라.','Sketch the intersection of x²+y²=4 and z=x², then find a parametrization and plot it.',[m(r'x=2\cos t,\quad y=2\sin t,\quad z=4\cos^2t'),'반지름2원 위에서 높이가0과4사이를 두 번 오르내리는 닫힌 곡선이다.'],[m(r'x=2\cos t,\quad y=2\sin t,\quad z=4\cos^2t'),'A closed curve over the radius2 circle, rising and falling twice between0 and4.'],m(r'r(t)=\langle2\cos t,2\sin t,4\cos^2t\rangle,\quad0\le t\le2\pi'))
add(56,'y=x²와 타원체x²+4y²+4z²=16의 위쪽 절반의 교선을 그리고 매개식을 구하라.','Sketch and parametrize the intersection of y=x² with the upper half of x²+4y²+4z²=16.',[m(r'x=t,\quad y=t^2,\quad z=\tfrac12\sqrt{16-t^2-4t^4}'),m(r'4(t^2)^2+t^2-16\le0\Rightarrow |t|\le\sqrt{(\sqrt{257}-1)/8}')],[m(r'x=t,\quad y=t^2,\quad z=\tfrac12\sqrt{16-t^2-4t^4}'),m(r'4(t^2)^2+t^2-16\le0\Rightarrow |t|\le\sqrt{(\sqrt{257}-1)/8}')],m(r'r(t)=\langle t,t^2,\tfrac12\sqrt{16-t^2-4t^4}\rangle,\quad|t|\le\sqrt{(\sqrt{257}-1)/8}'))
add(57,'t≥0에서 두 입자의 위치는 r₁(t)=(t²,7t−12,t²),r₂(t)=(4t−3,t²,5t−6)이다. 충돌하는가?','For t≥0, particles have positions r₁(t)=(t²,7t−12,t²),r₂(t)=(4t−3,t²,5t−6). Do they collide?',[m(r'x:\ t^2=4t-3\Rightarrow t=1,3'),m(r'y:\ t^2=7t-12\Rightarrow t=3,4'),m(r'z:\ t^2=5t-6\Rightarrow t=2,3'),'모든 성분을 같은 시각에 만족하는 것은t=3뿐이다.'],[m(r'x:\ t^2=4t-3\Rightarrow t=1,3'),m(r'y:\ t^2=7t-12\Rightarrow t=3,4'),m(r'z:\ t^2=5t-6\Rightarrow t=2,3'),'Only t=3 satisfies all coordinates at the same time.'],m(r't=3,\quad(9,9,9)')+'에서 충돌한다.', 'They collide at '+m(r't=3,\quad(9,9,9)')+'.')
add(58,'r₁(t)=(t,t²,t³),r₂(t)=(1+2t,1+6t,1+14t)인 입자들이 충돌하는지와 경로가 교차하는지를 구별하라.','For r₁(t)=(t,t²,t³),r₂(t)=(1+2t,1+6t,1+14t), distinguish collisions from path intersections.', ['같은시각의x성분은t=−1을 강제하지만 y성분은1과−5로 달라 충돌하지 않는다.',m(r'r_1(t)=r_2(s)\Rightarrow s=(t-1)/2,\quad t^2=3t-2'),m(r't=1,2;\quad t^3=7t-6\text{ is satisfied by both}')],['Equal-time x coordinates force t=−1, but the y coordinates then differ(1 and−5), so there is no collision.',m(r'r_1(t)=r_2(s)\Rightarrow s=(t-1)/2,\quad t^2=3t-2'),m(r't=1,2;\quad t^3=7t-6\text{ is satisfied by both}')],'충돌 없음. 경로는(1,1,1)과(2,4,8)에서 교차하며 각 매개변수쌍은(1,0),(2,1/2)이다.','No collision. Paths intersect at(1,1,1)and(2,4,8), with parameter pairs(1,0),(2,1/2).')
A=s.Rational(27,26);B=s.Rational(8,39);D=s.Rational(144,65)
eq('59 constant identity',144*(A-B)**2,100);eq('59 oscillation coefficient',144*4*A*B,25*D*D)
add(59,m(r'x=\tfrac{27}{26}\sin8t-\tfrac8{39}\sin18t,\quad y=-\tfrac{27}{26}\cos8t+\tfrac8{39}\cos18t,\quad z=\tfrac{144}{65}\sin5t')+'를(a)그리고(b)144x²+144y²−25z²=100위에 놓임을 보여라.','For '+m(r'x=\tfrac{27}{26}\sin8t-\tfrac8{39}\sin18t,\quad y=-\tfrac{27}{26}\cos8t+\tfrac8{39}\cos18t,\quad z=\tfrac{144}{65}\sin5t')+', (a)plot the curve and(b)verify144x²+144y²−25z²=100.',[m(r'A=27/26,\quad B=8/39,\quad x^2+y^2=A^2+B^2-2AB\cos10t'),m(r'x^2+y^2=(A-B)^2+4AB\sin^25t'),m(r'144(A-B)^2=100,\quad144\cdot4AB=25(144/65)^2')],[m(r'A=27/26,\quad B=8/39,\quad x^2+y^2=A^2+B^2-2AB\cos10t'),m(r'x^2+y^2=(A-B)^2+4AB\sin^25t'),m(r'144(A-B)^2=100,\quad144\cdot4AB=25(144/65)^2')],m('144x^2+144y^2-25z^2=100'),parts=list('ab'))
add(60,'세잎매듭 x=(2+cos1.5t)cos t,y=(2+cos1.5t)sin t,z=sin1.5t를 위와 여러 방향에서 그려라. 위에서 본 반지름 범위와 높이 극값의 관계를 설명하고 교차의 위아래를 표시하라.','Draw the trefoil x=(2+cos1.5t)cos t,y=(2+cos1.5t)sin t,z=sin1.5t from above and other viewpoints. Relate projected radius to extreme heights and mark over/under crossings.',[m(r'\rho=2+\cos(3t/2),\quad\theta=t,\quad1\le\rho\le3,\quad0\le t\le4\pi'),m(r'z=\pm1\iff\cos(3t/2)=0\iff\rho=2'),'전체 매듭은4π주기이다. 위에서의 세 교차각은π/3,π,5π/3이고, 같은 위치의 두 매개변수는2π차이나며 높이가+1과−1이다. +1가닥을 끊지 않고−1가닥에 틈을 둔다.'],[m(r'\rho=2+\cos(3t/2),\quad\theta=t,\quad1\le\rho\le3,\quad0\le t\le4\pi'),m(r'z=\pm1\iff\cos(3t/2)=0\iff\rho=2'),'The full knot has period4π. Top-view crossings occur at anglesπ/3,π,5π/3; the paired parameters differ by2π and have heights+1 and−1. Draw the+1 strand continuously and leave a gap in the−1 strand.'],m(r'1\le\rho\le3;\quad z=\pm1\text{ at }\rho=2')+'; 첨부한 교차 도해 참조.',m(r'1\le\rho\le3;\quad z=\pm1\text{ at }\rho=2')+'; see the crossing diagram.')
add(61,'t→a에서 u→U,v→V이고 c는 상수일 때 극한의(a)합,(b)상수배,(c)내적,(d)외적 법칙을 증명하라.','If u→U,v→V as t→a and c is constant, prove the limit rules for(a)sums,(b)scalar multiples,(c)dot products,(d)cross products.', ['성분별로 실수 극한의 합·상수배·곱 법칙을 적용한다.',m(r'\lim(u_i+v_i)=U_i+V_i,\quad\lim(cu_i)=cU_i'),m(r'\lim\sum_i u_iv_i=\sum_iU_iV_i'),'외적의 각 성분도 두 곱의 차이므로 같은 실수 법칙을 적용하면 된다.'],['Apply scalar sum, constant-multiple, and product limit rules coordinatewise.',m(r'\lim(u_i+v_i)=U_i+V_i,\quad\lim(cu_i)=cU_i'),m(r'\lim\sum_i u_iv_i=\sum_iU_iV_i'),'Every cross-product component is a difference of two products, so the scalar rules apply again.'],m(r'\lim(u+v)=U+V,\quad\lim cu=cU,\quad\lim(u\cdot v)=U\cdot V,\quad\lim(u\times v)=U\times V'),parts=list('abcd'))
add(62,'벡터함수의 성분별 극한 r(t)→b가 유클리드 거리의 ε–δ정의와 동치임을 증명하라.','Prove equivalence of the coordinatewise limit r(t)→b and the Euclidean ε–δ definition.',[m(r'|r_i(t)-b_i|\le|r(t)-b|'),'따라서 거리의ε–δ조건은 각 좌표의 극한을 준다. 반대로 n개 좌표마다 오차를ε/√n보다 작게 하는 δᵢ를 잡고 최소값을 사용한다.',m(r'|r(t)-b|=\sqrt{\sum_{i=1}^n|r_i(t)-b_i|^2}<\sqrt{n(\varepsilon/\sqrt n)^2}=\varepsilon')],[m(r'|r_i(t)-b_i|\le|r(t)-b|'),'The norm condition implies each coordinate limit. Conversely choose δᵢ making the ith error smaller thanε/√n, and use the minimum δ.',m(r'|r(t)-b|=\sqrt{\sum_{i=1}^n|r_i(t)-b_i|^2}<\sqrt{n(\varepsilon/\sqrt n)^2}=\varepsilon')],m(r'\forall\varepsilon>0\ \exists\delta>0:\quad0<|t-a|<\delta\Rightarrow|r(t)-b|<\varepsilon'))
assert sorted(b.E)==list(range(1,63));b.save();(Path(__file__).parent/'s13-1-report.json').write_text(json.dumps({'section':'13.1','sourceVisualPdfPages':[970,971,972,973],'passed':len(checks),'checks':checks},indent=2)+'\n');print('62 exercises;',len(checks),'checks')
