"""Hydrostatic loads, centroids and Pappus; source PDF659–661."""
from early_helpers import Book
from pathlib import Path
import sympy as s,json,mpmath as mp,re
mp.mp.dps=40;x=s.symbols('x',real=True);a,h=s.symbols('a h',positive=True);R=s.Rational
b=Book('8.3',[622,623,624]);checks=[]
def m(v):return r'\('+v+r'\)'
def F(v):return(m(v),m(v))
def tx(v):return s.latex(s.simplify(v))
def add(n,k,e,steps,ans,parts=''):
 b.add(n,622 if n<=16 else 623 if n<=36 else 624,('물리학과 공학에의 응용','Applications to Physics and Engineering'),(k,e),steps,(ans,ans),list(parts),check=('압력에는 수직 깊이,힘에는 실제 면적을 사용한다. 도심은 면적과 두 모멘트의 비로 검산한다.','Use vertical depth for pressure and actual surface area for force.Verify a centroid using area and both first moments.'));b.E[n]['conceptHref']='../../calc1/index.html'
convention=('물의 무게밀도는 교재에 따라62.5lb/ft³ 또는9800N/m³를 사용하며 대기압을 뺀 게이지압을 계산한다.','Use the textbook water weight density62.5lb/ft³ or9800N/m³ and compute gauge pressure, excluding atmospheric pressure.')
add(1,'길이5ft,폭2ft,깊이3ft 수조가 물로 가득하다. (a)바닥 압력,(b)바닥 힘,(c)한쪽 끝의 힘을 구하라.','A full aquarium is5ft long,2ft wide and3ft deep.Find(a)bottom pressure,(b)bottom force,(c)force on one end.',[convention,F(r'p=62.5(3)=187.5'),F(r'F_{bottom}=187.5(5\cdot2)=1875'),F(r'F_{end}=62.5\int_0^3 2y\,dy=562.5')],m(r'(a)\ 187.5\mathrm{lb/ft^2};\ (b)\ 1875\mathrm{lb};\ (c)\ 562.5\mathrm{lb}'),'abc')
add(2,'8m×4m×2m 탱크에 밀도820kg/m³ 등유가1.5m 깊이로 있다. (a)바닥 압력,(b)바닥 힘,(c)한 끝의 힘을 구하라.','An8m×4m×2m tank contains kerosene of density820kg/m³ to depth1.5m.Find(a)bottom pressure,(b)bottom force,(c)end force.',[F(r'\delta=820(9.8)=8036\mathrm{N/m^3}'),F(r'p=8036(1.5)=12054\mathrm{Pa}'),F(r'F_{bottom}=12054(32)=385728\mathrm N'),F(r'F_{end}=8036\int_0^{1.5}4y\,dy=36162\mathrm N')],m(r'(a)\ 12054\mathrm{Pa};\ (b)\ 385728\mathrm N;\ (c)\ 36162\mathrm N'),'abc')
# Each row states its own depth coordinate and strip width, then evaluates the load.
plates={3:(R(125,2),[(3,11,s.Integer(2))],'윗변이수면아래3ft,높이8ft,폭2ft인직사각형','a rectangle2ft wide and8ft high with its top3ft below water'),4:(R(125,2),[(2,7,2*(x-2))],'윗꼭짓점깊이2ft,높이5ft,밑변10ft인직각삼각형','a right triangle with top vertex2ft deep,height5ft and base10ft'),5:(9800,[(4,20,2*s.sqrt(64-(x-12)**2))],'반지름8m,윗끝깊이4m인원판','a disk of radius8m with its top4m deep'),6:(9800,[(0,4,2*s.sqrt(36-(4-x)**2))],'반지름6m인윗반원판의밑변위4m까지물에잠긴부분','the submerged part of an upper semicircle of radius6m,water4m above its diameter'),7:(9800,[(0,6,2*x/3)],'꼭짓점이수면에있고높이6m,밑변4m인삼각형','a triangle with vertex at the surface,height6m and base4m'),8:(R(125,2),[(3,7,R(3,2)*(7-x))],'윗변깊이3ft,윗변6ft,같은두변5ft인아래로향한삼각형','a downward triangle with top width6ft at depth3ft and equal sides5ft'),9:(R(125,2),[(0,2,R(16,3)+4*x/3)],'윗변4ft가수면위1ft,밑변8ft가수면아래2ft인사다리꼴','a trapezoid with upper width4ft1ft above water and lower width8ft2ft below water'),10:(s.Symbol('delta',positive=True),[(0,a/s.sqrt(2),2*x),(a/s.sqrt(2),a*s.sqrt(2),2*(a*s.sqrt(2)-x))],'한변a인정사각형을마름모방향으로놓고윗꼭짓점이수면에닿게한판','a square of side a rotated into a diamond,top vertex at water level'),11:(s.Symbol('delta',positive=True),[(0,h,2*a-a*x/h)],'수면의윗변2a,바닥변a,높이h인사다리꼴','a trapezoid with top width2a at the surface,bottom width a and height h')}
for n,(delta,segments,k,e)in plates.items():
 val=s.simplify(sum(delta*s.integrate(x*w,(x,lo,hi))for lo,hi,w in segments));steps=[convention,('y를 수면에서 아래로 잰 깊이로 두고 수평 띠로 나눈다.','Let y be vertical depth below the surface and divide the plate into horizontal strips.'),F(r'\Delta F_i\approx\delta y_i^*w(y_i^*)\Delta y,\quad F=\lim\sum_i\Delta F_i')]
 for lo,hi,w in segments:steps.append(F(tx(lo)+r'\le y\le '+tx(hi)+r':\quad w(y)='+tx(w).replace('x','y')))
 integ='+'.join(r'\int_{'+tx(lo)+'}^{'+tx(hi)+r'}y\left('+tx(w).replace('x','y')+r'\right)dy'for lo,hi,w in segments);steps.append(F('F='+tx(delta)+r'\left['+integ+r'\right]='+tx(val)))
 if n in[10,11]:steps.append(('δ=ρg는 물의 무게밀도이다. 길이 단위가 지정되지 않아 힘도 δ를 포함한 식으로 쓴다.','δ=ρg is the weight density.Length units are not specified, so retain δ in the force.'))
 add(n,k+'의한쪽면수압힘을리만합으로설명하고적분계산하라.','Explain a Riemann-sum model and integrate the force on one side of '+e+'.',steps,m('F='+tx(val)+(''if n>=10 else r'\mathrm{lb}'if delta==R(125,2)else r'\mathrm N')));checks.append({'exercise':n,'force':str(val)})
add(12,'높이12m 댐에 수면은 꼭대기보다2m 낮다. 바닥의 지름4m 반원 수문에 작용하는 힘을 구하라.','A12m dam holds water2m below its top.Find the force on a semicircular bottom gate of diameter4m.',[F(r'0\le y\le2,\quad\text{depth}=10-y,\quad w=2\sqrt{4-y^2}'),F(r'F=9800\int_0^2(10-y)2\sqrt{4-y^2}\,dy'),F(r'F=9800(20\pi-16/3)')],m(r'9800(20\pi-16/3)\mathrm N'))
add(13,'지름8ft,길이40ft 수평 원통에 무게밀도47lb/ft³ 휘발유가 가득하다. 한쪽 끝의 힘을 구하라.','A horizontal cylinder8ft in diameter and40ft long is full of gasoline of weight density47lb/ft³.Find the end force.',[F(r'F=47\int_0^8y\,2\sqrt{16-(y-4)^2}\,dy'),('원판의 도심 깊이는4ft,넓이는16πft²이다. 길이40ft는 끝면 힘에 영향을 주지 않는다.','The end disk has centroid depth4ft and area16πft².The tank length40ft does not affect the end force.'),F(r'F=47(4)(16\pi)=3008\pi')],m(r'3008\pi\mathrm{lb}'))
add(14,'위폭2m,높이3m의 사다리꼴 단면인 길이6m 홈통에 밀도925kg/m³ 기름이 있다. (a)가득 찼을 때,(b)깊이1.2m일 때 끝면의 힘을 구하라.','A6m trough has a trapezoidal end3m high and2m wide at the top, with oil of density925kg/m³.Find end force(a)when full and(b)at depth1.2m.',[('제공된9판 그림에는 아래 폭의 수치가 없다. 아래 폭을 b(m)로 두면 해는 다음과 같으며, 그림 비율만으로 b=1이라고 단정하지 않는다.','The supplied ninth-edition diagram does not label the bottom width.Call it b meters; the answer therefore depends on b.Do not infer b=1 solely from drawing proportions.'),F(r'w(y)=b+(2-b)y/3,\quad\delta=925(9.8)=9065'),F(r'F(H)=9065\int_0^H(H-y)[b+(2-b)y/3]\,dy'),F(r'F(H)=9065[bH^2/2+(2-b)H^3/18]'),F(r'F(3)=27195(b+1),\quad F(1.2)=9065(78b+24)/125')],m(r'(a)\ 27195(b+1)\mathrm N;\quad(b)\ 9065(78b+24)/125\mathrm N'),'ab')
add(15,'깊이1m 수조 바닥에 한변20cm 정육면체가 있다. (a)윗면,(b)옆면 하나의 수압힘을 구하라.','A20cm cube rests on the bottom of1m-deep water.Find the force on(a)the top and(b)one side.',[F(r'F_{top}=9800(.8)(.2)^2=313.6'),F(r'F_{side}=9800(.2)\int_{.8}^1 y\,dy=352.8')],m(r'(a)\ 313.6\mathrm N;\quad(b)\ 352.8\mathrm N'),'ab')
add(16,'수직에서30° 기울어진 댐은 위폭100ft,아래폭50ft,경사높이70ft이다. 물이 꼭대기까지 찰 때 힘을 구하라.','A dam inclined30° from vertical is a trapezoid100ft wide at the top,50ft at the bottom and70ft along its slope.Find the full-water force.',[F(r'\text{vertical depth}=u\cos30^\circ,\quad w(u)=100-5u/7'),F(r'F=62.5\int_0^{70}u\cos30^\circ(100-5u/7)\,du'),F(r'F=15312500\sqrt3/3')],m(r'15312500\sqrt3/3\mathrm{lb}'))
add(17,'폭20ft,길이40ft 수영장 바닥이 깊이3ft에서9ft까지 평면으로 경사진다. 가득 찬 물의 힘을 (a)네 옆면,(b)바닥에 대해 구하라.','A20ft×40ft pool slopes uniformly from3ft to9ft depth.Find the full-water force on(a)each wall and(b)the bottom.',[F(r'F_{shallow}=62.5(20)\int_0^3y\,dy=5625'),F(r'F_{deep}=62.5(20)\int_0^9y\,dy=50625'),F(r'F_{long}=\tfrac{62.5}2\int_0^{40}(3+3x/20)^2\,dx=48750'),F(r'A_{bottom}=20\sqrt{40^2+6^2}=40\sqrt{409},\quad\bar d=6'),F(r'F_{bottom}=62.5(6)(40\sqrt{409})=15000\sqrt{409}')],m(r'(a)\ 5625,50625,48750,48750\mathrm{lb};\quad(b)\ 15000\sqrt{409}\mathrm{lb}'),'ab')
add(18,'밀도ρ의 유체 속 수직판이 깊이a부터b까지 있고 깊이x에서 폭w(x)이다. 힘의 적분식을 증명하라.','A vertical plate in fluid densityρ extends from depth a to b with width w(x).Prove its force formula.',[F(r'p_i\approx\rho gx_i^*,\quad\Delta A_i\approx w(x_i^*)\Delta x'),F(r'F=\lim\sum_i\rho gx_i^*w(x_i^*)\Delta x=\int_a^b\rho gxw(x)\,dx')],m(r'F=\int_a^b\rho gxw(x)\,dx'))
dep=list(map(R,['7','7.4','7.8','8.2','8.6','9','9.4']));width=list(map(R,['1.2','1.8','2.9','3.8','3.6','4.2','4.4']));force=64*R(2,5)/3*sum((1 if i in[0,6]else 4 if i%2 else 2)*dep[i]*width[i]for i in range(7))
add(19,'해수 무게밀도64lb/ft³에서 깊이[7,7.4,7.8,8.2,8.6,9,9.4]ft의 판폭은[1.2,1.8,2.9,3.8,3.6,4.2,4.4]ft이다. Simpson 법칙으로 힘을 추정하라.','In seawater of weight density64lb/ft³, widths[1.2,1.8,2.9,3.8,3.6,4.2,4.4]ft occur at depths[7,7.4,7.8,8.2,8.6,9,9.4]ft.Estimate force by Simpson’s rule.',[F(r'f_i=x_iw_i,\quad\Delta x=.4'),F(r'F\approx64\frac{.4}3(f_0+4f_1+2f_2+4f_3+2f_4+4f_5+f_6)'),F(r'F\approx'+tx(force))],m(r'F\approx'+f'{float(force):.3f}'+r'\mathrm{lb}'))
add(20,'(a)수직판의 힘은 도심 깊이에서의 압력×넓이임을 보이고,(b)이 식으로10번을 다시 풀어라.','(a)Show force on a vertical plate equals pressure at centroid depth times area.(b)Apply it to10.',[F(r'A=\int_a^b w(x)\,dx,\quad\bar x=A^{-1}\int_a^b xw(x)\,dx'),F(r'F=\rho g\int_a^b xw(x)\,dx=\rho g\bar x A'),F(r'\text{diamond: }A=a^2,\quad\bar x=a/\sqrt2,\quad F=\rho ga^3/\sqrt2')],m(r'(a)\ F=\rho g\bar xA;\quad(b)\ F=\rho ga^3/\sqrt2'),'ab')
for n,masses,positions in[(21,[6,9],[10,30]),(22,[12,15,20],[-3,2,8])]:
 total=sum(masses);moment=sum(a*c for a,c in zip(masses,positions));add(n,'x축 위 질량 '+str(masses)+'이 위치 '+str(positions)+'에 있다. 원점 모멘트와 질량중심을 구하라.','Masses'+str(masses)+'lie at x-coordinates'+str(positions)+'.Find the moment about0 and center of mass.',[F(r'M=\sum m_ix_i='+str(moment)),F(r'\bar x=M/\sum m_i='+tx(R(moment,total)))],m('M='+str(moment)+r',\quad\bar x='+tx(R(moment,total))))
for n,masses,pts in[(23,[5,8,7],[(3,1),(0,4),(-5,-2)]),(24,[4,3,6,3],[(6,1),(3,-1),(-2,2),(-2,-5)])]:
 total=sum(masses);Mx=sum(a*p[1]for a,p in zip(masses,pts));My=sum(a*p[0]for a,p in zip(masses,pts));add(n,'질량 '+str(masses)+'을 점 '+str(pts)+'에 둔다. 두 모멘트와 질량중심을 구하라.','Place masses'+str(masses)+'at'+str(pts)+'.Find moments and center of mass.',[F('m='+str(total)+r',\quad M_x=\sum m_iy_i='+str(Mx)+r',\quad M_y=\sum m_ix_i='+str(My)),F(r'(\bar x,\bar y)=(M_y/m,M_x/m)')],m('M_x='+str(Mx)+',M_y='+str(My)+r';\quad(\bar x,\bar y)=('+tx(R(My,total))+','+tx(R(Mx,total))+')'))
centroids={}
def centroid(n,segs,k,e,visual=False,rho=1):
 A=s.simplify(sum(s.integrate(f-g,(x,lo,hi))for lo,hi,f,g in segs));My=s.simplify(sum(s.integrate(x*(f-g),(x,lo,hi))for lo,hi,f,g in segs));Mx=s.simplify(sum(s.integrate((f*f-g*g)/2,(x,lo,hi))for lo,hi,f,g in segs));cx=s.simplify(My/A);cy=s.simplify(Mx/A);centroids[n]=(segs,cx,cy)
 steps=[]
 if visual:steps.append(('그림에서 도심을 대략 ('+f'{float(cx):.1f},{float(cy):.1f}'+') 부근으로 예상한다.','Visual estimate: near('+f'{float(cx):.1f},{float(cy):.1f}'+').'))
 steps +=[F(r'A=\sum\int(f-g)dx='+tx(A)),F(r'M_y/\rho=\sum\int x(f-g)dx='+tx(My)),F(r'M_x/\rho=\tfrac12\sum\int(f^2-g^2)dx='+tx(Mx)),F(r'\bar x=M_y/(\rho A),\quad\bar y=M_x/(\rho A)')]
 ans=m(r'(\bar x,\bar y)=('+tx(cx)+','+tx(cy)+')')
 if rho!=1:steps.insert(0,F(r'\rho='+str(rho)+r',\quad m='+tx(rho*A)));ans=m('M_x='+tx(rho*Mx)+r',\quad M_y='+tx(rho*My))+ '; '+ans
 add(n,k,e,steps,ans);checks.append({'exercise':n,'area':str(A),'MxOverDensity':str(Mx),'MyOverDensity':str(My),'centroid':[str(cx),str(cy)]})
centroid(25,[(0,2,4-2*x,s.Integer(0))],'0≤x≤2,0≤y≤4−2x 영역의 도심을 그림으로 추정하고 정확히 구하라.','Estimate and compute the centroid of0≤x≤2,0≤y≤4−2x.',True)
centroid(26,[(-1,1,s.exp(x),s.Integer(0))],'−1≤x≤1,0≤y≤eˣ의 도심을 그림으로 추정하고 정확히 구하라.','Estimate and compute the centroid under eˣ on[−1,1].',True)
centroid(27,[(0,2,x*x/2,s.Integer(0))],'0≤x≤2,0≤y≤x²/2의 도심을 그림으로 추정하고 정확히 구하라.','Estimate and compute the centroid under x²/2 on[0,2].',True)
centroid(28,[(1,2,1/x,s.Integer(0))],'1≤x≤2,0≤y≤1/x의 도심을 그림으로 추정하고 정확히 구하라.','Estimate and compute the centroid under1/x on[1,2].',True)
centroid(29,[(0,1,s.sqrt(x),x)],'y=x와 x=y² 사이 영역의 도심을 구하라.','Find the centroid bounded by y=x and x=y².')
centroid(30,[(-2,1,2-x*x,x)],'y=2−x²와 y=x 사이 영역의 도심을 구하라.','Find the centroid between y=2−x² and y=x.')
centroid(31,[(0,s.pi/3,s.sin(2*x),s.sin(x))],'0≤x≤π/3에서 y=sin2x와 y=sin x 사이 영역의 도심을 구하라.','Find the centroid between sin2x and sin x on[0,π/3].')
centroid(32,[(0,1,x**3,s.Integer(0)),(1,2,2-x,s.Integer(0))],'y=x³,x+y=2,y=0으로 둘러싸인 영역의 도심을 구하라.','Find the centroid bounded by y=x³,x+y=2,y=0.')
# Horizontal integration is cleaner for33.
y=s.symbols('y');A=s.integrate(2-y-y*y,(y,-2,1));My=s.integrate(((2-y)**2-y**4)/2,(y,-2,1));Mx=s.integrate(y*(2-y-y*y),(y,-2,1))
add(33,'x+y=2와 x=y² 사이 영역의 도심을 구하라.','Find the centroid between x+y=2 and x=y².',[F(r'-2\le y\le1,\quad y^2\le x\le2-y'),F('A='+tx(A)+r',\quad M_x=\int_{-2}^1 y(2-y-y^2)dy='+tx(Mx)),F(r'M_y=\frac12\int_{-2}^1[(2-y)^2-y^4]dy='+tx(My))],m(r'(\bar x,\bar y)=('+tx(My/A)+','+tx(Mx/A)+')'))
centroid(34,[(0,2,3-R(3,2)*x,s.Integer(0))],'밀도ρ=4,꼭짓점(0,0),(2,0),(0,3)인 판의 모멘트와 질량중심을 구하라.','Find moments and center of mass for density4 on the triangle(0,0),(2,0),(0,3).',rho=4)
centroid(35,[(0,4,s.sqrt(16-x*x),s.Integer(-2))],'밀도ρ=6,0≤x≤4,−2≤y≤√(16−x²)인 판의 모멘트와 질량중심을 구하라.','Find moments and center of mass for density6 on0≤x≤4,−2≤y≤√(16−x²).',rho=6)
ys=list(map(R,['0','2','2.6','2.3','2.2','3.3','4','3.2','0']));sim=lambda vals:sum((1 if i in[0,8]else 4 if i%2 else 2)*vals[i]for i in range(9))/3
Ar=sim(ys);My=sim([i*v for i,v in enumerate(ys)]);Mx=sim([v*v/2 for v in ys]);cx=My/Ar;cy=Mx/Ar
add(36,'주어진0≤x≤8 그래프 아래 영역의 도심을 Simpson 법칙으로 추정하라.','Use Simpson’s rule to estimate the centroid under the supplied graph on[0,8].',[('정수 x=0,…,8에서 높이를 약[0,2,2.6,2.3,2.2,3.3,4,3.2,0]으로 읽는다. 원본 그래프의 근사 판독이며 정확한 함수값이 아니다.','Read approximate heights[0,2,2.6,2.3,2.2,3.3,4,3.2,0]at integer x=0,…,8.These are graphical estimates, not exact function data.'),F(r'A\approx S_8[f]='+tx(Ar)+r',\quad M_y\approx S_8[xf]='+tx(My)+r',\quad M_x\approx\tfrac12S_8[f^2]='+tx(Mx)),F(r'\bar x\approx'+f'{float(cx):.3f}'+r',\quad\bar y\approx'+f'{float(cy):.3f}')],m(r'(\bar x,\bar y)\approx('+f'{float(cx):.2f},{float(cy):.2f}'+')'))
centroid(37,[(-1,0,x**3-x,x*x-1),(0,1,x**3-x,x*x-1)],'y=x³−x와 y=x²−1로 둘러싸인 영역의 도심을 구하고 그림에 표시하라.','Find and plot the centroid of the region bounded by y=x³−x and y=x²−1.')
# Crossings also occur at x=1; no order switch at the double root x=1.
lo=mp.findroot(lambda z:mp.exp(z)+z*z-2,-1.3);hi=mp.findroot(lambda z:mp.exp(z)+z*z-2,.5)
Af=mp.quad(lambda z:2-z*z-mp.exp(z),[lo,hi]);Myf=mp.quad(lambda z:z*(2-z*z-mp.exp(z)),[lo,hi]);Mxf=mp.quad(lambda z:((2-z*z)**2-mp.exp(2*z))/2,[lo,hi]);cx38=Myf/Af;cy38=Mxf/Af
add(38,'y=eˣ와 y=2−x²의 교점 x와 사이 영역의 도심을 수치적으로 구하라.','Numerically find the intersections and centroid between y=eˣ and y=2−x².',[F(r'e^x+x^2-2=0\Longrightarrow a\approx'+f'{float(lo):.8f}'+r',\ b\approx'+f'{float(hi):.8f}'),('eˣ+x²−2의 이계도함수는 항상 양수이고 양끝에서 양의 무한대로 가므로 이 두 교점이 전부이다.','The second derivative of eˣ+x²−2 is positive; its limits at both ends are infinity, so these are the only two crossings.'),F(r'A=\int_a^b(2-x^2-e^x)dx\approx'+f'{float(Af):.8f}'),F(r'M_y=\int_a^b x(2-x^2-e^x)dx,\quad M_x=\tfrac12\int_a^b[(2-x^2)^2-e^{2x}]dx')],m(r'(\bar x,\bar y)\approx('+f'{float(cx38):.6f},{float(cy38):.6f}'+')'))
add(39,'삼각형의 도심이 세 중선의 교점임을 증명하라.','Prove that a triangle’s centroid is the intersection of its medians.',[F(r'P=(a,0),\ Q=(0,b),\ R=(c,0),\quad a<c,\ b>0'),F(r'x_L(y)=a(1-y/b),\quad x_R(y)=c(1-y/b)'),F(r'A=(c-a)b/2,\quad M_x=(c-a)b^2/6,\quad M_y=(c^2-a^2)b/6'),F(r'(\bar x,\bar y)=((a+c)/3,b/3)=(P+Q+R)/3'),('이 점은 각 꼭짓점에서 맞은편 변 중점으로 가는 중선의2/3 위치이다. 좌표 이동·회전은 도심과 중선을 함께 옮기므로 모든 삼각형에 성립한다.','This point lies two-thirds along each median from its vertex.Translations and rotations preserve both the centroid and medians, giving the result for every triangle.')],m(r'G=(P+Q+R)/3'))
add(40,'꼭짓점(−1,0),(2,0),(0,2),(−1,2) 영역을 직사각형과 삼각형으로 나눠 적분 없이 도심을 구하라.','Without integration, find the centroid of the polygon(−1,0),(2,0),(0,2),(−1,2) by decomposition.',[F(r'A_1=2,\ C_1=(-1/2,1);\quad A_2=2,\ C_2=(2/3,2/3)'),F(r'\bar x=[2(-1/2)+2(2/3)]/4=1/12,\quad\bar y=[2(1)+2(2/3)]/4=5/6')],m(r'(1/12,5/6)'))
add(41,'밑 직사각형[−2,2]×[−1,0] 위에 꼭짓점(−1,2),(1,2)의 삼각형 두 개가 놓인 영역의 도심을 적분 없이 구하라.','Find the centroid without integration of[−2,2]×[−1,0] topped by two triangles with peaks(−1,2),(1,2).',[F(r'\bar x=0\quad\text{by symmetry}'),F(r'A_{rect}=4,\ y_{rect}=-1/2,\quad A_{triangles}=4,\ y_{triangles}=2/3'),F(r'\bar y=[4(-1/2)+4(2/3)]/8=1/12')],m(r'(0,1/12)'))
add(42,'a×b 직사각형을 원점 꼭짓점에서 반대 꼭짓점까지의 포물선으로 나눈다. 아래 영역R₁과 위 영역R₂의 도심을 구하라.','Divide an a×b rectangle by a parabola from the origin vertex to the opposite vertex.Find centroids below(R₁)and above(R₂).',[F(r'y=bx^2/a^2,\quad A_1=ab/3,\quad\bar x_1=3a/4,\quad\bar y_1=3b/10'),F(r'A_2=2ab/3,\quad A_1\bar x_1+A_2\bar x_2=ab(a/2)'),F(r'A_1\bar y_1+A_2\bar y_2=ab(b/2)')],m(r'R_1:(3a/4,3b/10);\quad R_2:(3a/8,3b/5)'))
add(43,'f 아래 영역의 도심 x좌표가 x̄이면 ∫(cx+d)f(x)dx=(cx̄+d)∫f(x)dx임을 증명하라.','If x̄ is the centroid coordinate under f, prove ∫(cx+d)f(x)dx=(cx̄+d)∫f(x)dx over[a,b].',[F(r'A=\int_a^bf(x)dx,\quad A\bar x=\int_a^bxf(x)dx'),F(r'\int_a^b(cx+d)f(x)dx=cA\bar x+dA=(c\bar x+d)A')],m(r'\int_a^b(cx+d)f(x)dx=(c\bar x+d)\int_a^bf(x)dx'))
add(44,'Pappus 정리로 반지름r 구의 부피를 구하라.','Use Pappus’s theorem to find the volume of a sphere of radius r.',[F(r'A_{semicircle}=\pi r^2/2,\quad\bar y=4r/(3\pi)'),F(r'V=A(2\pi\bar y)=4\pi r^3/3')],m(r'V=4\pi r^3/3'))
add(45,'Pappus 정리로 높이h,반지름r 원뿔의 부피를 구하라.','Use Pappus’s theorem to find the volume of a cone of height h and radius r.',[F(r'A_{triangle}=rh/2,\quad\bar y=r/3'),F(r'V=(rh/2)(2\pi r/3)=\pi r^2h/3')],m(r'V=\pi r^2h/3'))
add(46,'꼭짓점(2,3),(2,5),(5,4)인 삼각형을 x축 주위로 회전한 입체의 부피를 Pappus 정리로 구하라.','Use Pappus’s theorem for the triangle(2,3),(2,5),(5,4) rotated about the x-axis.',[F(r'A=\tfrac12(2)(3)=3,\quad(\bar x,\bar y)=(3,4)'),F(r'V=A(2\pi\bar y)=24\pi')],m(r'V=24\pi'))
add(47,'균일한 철사인 1/4원 y=√(16−x²),0≤x≤4의 도심을 구하라.','Find the centroid of the uniform quarter-circle wire y=√(16−x²),0≤x≤4.',[F(r'x=4\cos t,\ y=4\sin t,\ ds=4dt,\quad0\le t\le\pi/2'),F(r'L=2\pi,\quad\int_Cx\,ds=\int_0^{\pi/2}16\cos t\,dt=16'),F(r'\int_Cy\,ds=16\quad\text{by symmetry}')],m(r'(\bar x,\bar y)=(8/\pi,8/\pi)'))
add(48,'(a)y=f(x)≥0 곡선의 x축 회전 표면에 대해 Pappus 제2정리를 증명하고,(b)47번 곡선의 회전으로 얻는 반구 표면적을 구하라.','(a)Prove the second Pappus theorem for y=f(x)≥0 rotated about the x-axis.(b)Apply it to the hemisphere from47.',[F(r'S=\int_C2\pi y\,ds=2\pi L\bar y=L(2\pi\bar y)'),F(r'S=(2\pi)(2\pi\cdot8/\pi)=32\pi=2\pi(4)^2'),('반구의 곡면적 공식과 일치하며 밑면 원판은 포함하지 않는다.','This agrees with the curved area of a hemisphere, excluding the base disk.')],m(r'(a)\ S=L(2\pi\bar y);\quad(b)\ 32\pi'),'ab')
add(49,'반지름r 원을 중심에서R>r 떨어진 같은 평면의 축 주위로 회전한 토러스의 표면적을 Pappus 제2정리로 구하라.','Use the second Pappus theorem for a circle of radius r rotated about a coplanar axis R>r from its center.',[F(r'L=2\pi r,\quad\text{centroid travel}=2\pi R'),F(r'S=(2\pi r)(2\pi R)=4\pi^2Rr')],m(r'S=4\pi^2Rr'))
add(50,'0≤n<m인 정수에 대해0≤x≤1의 y=xᵐ,y=xⁿ 사이 영역을 (a)스케치,(b)도심 계산,(c)도심이 영역 밖인 예를 찾으라.','For integers0≤n<m,consider the region between xᵐ and xⁿ on[0,1].(a)Sketch it,(b)find the centroid,(c)find an example whose centroid lies outside.',[F(r'x^m\le y\le x^n,\quad A=(m-n)/[(n+1)(m+1)]'),F(r'M_y=(m-n)/[(n+2)(m+2)],\quad M_x=(m-n)/[(2n+1)(2m+1)]'),F(r'\bar x={(n+1)(m+1)\over(n+2)(m+2)},\quad\bar y={(n+1)(m+1)\over(2n+1)(2m+1)}'),F(r'n=3,m=4:\quad(\bar x,\bar y)=(2/3,20/63),\quad20/63>(2/3)^3=8/27')],m(r'(c)\ n=3,m=4:\ (2/3,20/63)\text{ lies above }y=x^3'),'abc')
add(51,'위곡선f와 아래곡선g 사이 영역의 도심 공식9를 증명하라.','Prove Formulas9 for the centroid between an upper curve f and lower curve g.',[F(r'\Delta A_i\approx[f(x_i^*)-g(x_i^*)]\Delta x'),F(r'\text{strip center}=\left(x_i^*,\frac{f(x_i^*)+g(x_i^*)}2\right)'),F(r'A=\int_a^b(f-g)dx,\quad M_y=\int_a^bx(f-g)dx'),F(r'M_x=\frac12\int_a^b(f+g)(f-g)dx=\frac12\int_a^b(f^2-g^2)dx'),F(r'\bar x=\frac1A\int_a^bx(f-g)dx,\quad\bar y=\frac1{2A}\int_a^b(f^2-g^2)dx')],m(r'\bar x=M_y/A,\quad\bar y=M_x/A'))
assert sorted(b.E)==list(range(1,52))
def norm(v):
 if isinstance(v,str):
  chunks=re.split(r'(\\\(.*?\\\)|\\\[.*?\\\])',v,flags=re.S);return ''.join(z if i%2 else z.replace('<',r'\(\lt\)')for i,z in enumerate(chunks))
 if isinstance(v,list):return[norm(z)for z in v]
 if isinstance(v,dict):return{k:norm(z)for k,z in v.items()}
 return v
b.E=norm(b.E);b.save();Path(__file__).with_name('s8-3-report.json').write_text(json.dumps({'section':'8.3','exercises':51,'sourcePdfPages':[659,660,661],'exactIntegrationRecords':checks,'numerical38':{'intersections':[str(lo),str(hi)],'centroid':[str(cx38),str(cy38)]}},ensure_ascii=False,indent=2)+'\n');print('8.3 authored51')
