from calc1_core import *
import mpmath as mp
mp.mp.dps=60
D=CalcDoc('1.8',[92,93,94],lambda n:92 if n<=20 else 93 if n<=50 else 94)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('연속성·중간값 정리','Continuity and the Intermediate Value Theorem'),st,('정의역과 함수값, 양쪽 극한을 먼저 확인한다. 중간값 정리는 닫힌 구간의 연속성을 요구한다.','First check the domain, assigned value, and two-sided limit. The Intermediate Value Theorem requires continuity on a closed interval.'),steps,ans,check,parts)
add(1,('f가 4에서 연속임을 하나의 등식으로 나타내라.','Express continuity of f at 4 as an equation.'),[('주변에서 접근하는 값이 실제 지정값과 같아야 한다.','The approached value must equal the assigned value.')],d(r'\lim_{x\to4}f(x)=f(4)'),('이 등식은 f(4)의 정의와 유한 극한의 존재를 모두 전제한다.','The equation requires both a defined f(4) and an existing finite limit.'))
add(2,('실수 전체에서 연속인 함수의 그래프는 어떤 성질을 갖는가?','What property does the graph of a function continuous on all real numbers have?'),[('모든 점에서 극한과 함수값이 일치하므로 구멍·점프·수직 발산에 의한 끊김이 없다.','At every point the limit agrees with the value, excluding holes, jumps, and breaks caused by vertical divergence.')],('그래프가 끊김 없이 이어진다. 모서리는 있을 수 있다.','The graph is unbroken; corners are still possible.'),('예를 들어 |x|는 0에서 모서리가 있어도 연속이므로 매끄러움까지 요구하지 않는다.','For example, |x| is continuous despite its corner at zero, so smoothness is not required.'))
add(3,('원본 f 그래프에는 −4에 빈 구멍, −2에 좌우 높이가 다른 두 조각(왼쪽 끝 닫힘), 2에 점프(오른쪽 시작 닫힘), 4에 왼쪽 −∞와 유한한 오른쪽 닫힌 시작점이 있다. (a)불연속점을 설명하고 (b)각 점의 한쪽 연속성을 분류하라.','The source f-graph has an unfilled hole at −4; a jump at −2 with the left endpoint filled; a jump at 2 with the right endpoint filled; and at 4 a left limit −∞ with a finite filled starting point on the right. (a)Explain the discontinuities and (b)classify one-sided continuity.'),[('−4는 값이 없어 어느 쪽으로도 연속이 아니다. −2는 지정값이 왼쪽 극한에만, 2와 4는 오른쪽 극한에만 일치한다.','At −4 the missing value prevents continuity from either side. At −2 the assigned value matches only the left limit; at 2 and 4 it matches only the right limit.')],('(a)−4,−2,2,4. (b)차례로 어느 쪽도 아님, 왼쪽, 오른쪽, 오른쪽.','(a)−4,−2,2,4. (b)Neither, left, right, right, respectively.'),('PDF129의 점 표시와 4의 왼쪽 발산을 따로 읽어 단순 점프와 무한 불연속을 구분했다.','Read the markers and the left divergence at 4 separately on PDF129, distinguishing jumps from infinite discontinuity.'),list('ab'))
add(4,('원본 g 그래프는 −2에 구멍, −1에서 양쪽 −∞, 0에서 서로 다른 좌우 높이, 1에서 서로 다른 좌우 높이와 별도 지정값을 갖는다. 불연속점을 이유와 함께 쓰라.','The source g-graph has a hole at −2, divergence to −∞ on both sides of −1, unequal one-sided heights at 0, and unequal one-sided heights with a separate assigned value at 1. Identify and explain its discontinuities.'),[('구멍에서는 값이 없고, 발산점에서는 유한 극한이 없으며, 두 점프에서는 공통 양쪽 극한이 없다.','The hole lacks an assigned value; the divergent point lacks a finite limit; both jumps lack a common two-sided limit.')],('−2:제거 가능; −1:무한; 0,1:점프 불연속.','−2:removable; −1:infinite; 0 and 1:jump discontinuities.'),('−3과 3은 그래프의 닫힌 정의역 끝점이며 정의역 내부 방향의 연속성을 가지므로 추가 불연속점으로 세지 않는다.','The filled domain endpoints −3 and 3 are continuous from within their domain and are not counted as additional discontinuities.'))
for n,bad,holes,description in [(5,[1],[3],('1에서 점프하고 3에서 극한 높이와 다른 닫힌 값이 있는 그래프','a graph with a jump at 1 and a reassigned value at a hole at 3')),(6,[1,5],[3],('1에서 양쪽 +∞이며 유한한 지정값이 있고, 3에 재지정된 구멍, 5에 점프가 있는 그래프','a graph with two-sided +∞ at 1 and a finite assigned value, a reassigned hole at 3, and a jump at 5'))]:
 add(n,('원본은 '+description[0]+'이다. (a)유한 극한이 없는 a, (b)불연속인 a, (c)극한은 있으나 불연속인 a를 구하라.','The source shows '+description[1]+'. Find (a)a with no finite limit, (b)all discontinuities, and (c)a where a limit exists but continuity fails.'),[('점프·발산은 유한 양쪽 극한을 없앤다. 지정값만 바뀐 구멍은 극한을 유지하지만 연속은 아니다.','Jumps and divergence prevent a finite two-sided limit. Reassigning a value at a hole preserves the limit but destroys continuity.')],('(a)'+str(bad)+'; (b)'+str(sorted(bad+holes))+'; (c)'+str(holes), '(a)'+str(bad)+'; (b)'+str(sorted(bad+holes))+'; (c)'+str(holes)),('축의 한 칸이 1임을 기준으로 문제별 불연속 위치를 독립적으로 판독했다.','Read each discontinuity position independently using the unit tick spacing.'),list('abc'))
construct=[(7,('−2에 제거 가능, 2에 무한 불연속','a removable discontinuity at −2 and an infinite discontinuity at 2'),r'f(x)=\begin{cases}1/(x-2)&x\notin\{-2,2\}\\0&x\in\{-2,2\}\end{cases}',('−2의 극한은 −1/4인데 값은 0이다. 2에서는 좌우 발산하나 f(2)=0으로 실수 전체에 정의했다.','The limit at −2 is −1/4 while its value is zero. At 2 the sides diverge, but f(2)=0 makes the function defined on all real numbers.'),[samples(lambda z:1/(z-2),-5,1.98),samples(lambda z:1/(z-2),2.02,5)],[(-2,-.25,'open'),(-2,0),(2,0)],(-5,5,-3,3)),(8,('−3에 점프, 4에 제거 가능 불연속','a jump at −3 and a removable discontinuity at 4'),r'f(x)=\begin{cases}0&x<-3\\2&x=4\\1&x\ge-3,\ x\ne4\end{cases}',('−3에서 좌 0·우 1이다. 4에서는 양쪽 극한 1과 지정값 2가 다르다.','At −3 the limits are 0 and 1. At 4 both limits are 1, differing from the assigned value 2.'),[[(-5,0),(-3,0)],[(-3,1),(6,1)]],[(-3,0,'open'),(-3,1),(4,1,'open'),(4,2)],(-5,6,-.5,2.5)),(9,('0과 3에서만 불연속이며 0에서 오른쪽, 3에서 왼쪽 연속','discontinuities only at 0 and 3, right-continuous at 0 and left-continuous at 3'),r'f(x)=\begin{cases}0&x<0\\1&0\le x\le3\\2&x>3\end{cases}',('0의 값은 오른쪽 조각 1이고, 3의 값은 왼쪽 조각 1이다.','The value at 0 matches the right piece 1, and the value at 3 matches the left piece 1.'),[[(-2,0),(0,0)],[(0,1),(3,1)],[(3,2),(5,2)]],[(0,0,'open'),(0,1),(3,1),(3,2,'open')],(-2,5,-.5,2.5)),(10,('−1에서는 왼쪽으로만 연속, 3에서는 어느 쪽으로도 연속이 아닌 불연속','a discontinuity at −1 continuous only from the left, and one at 3 continuous from neither side'),r'f(x)=\begin{cases}0&x\le-1\\2&x=3\\1&x>-1,\ x\ne3\end{cases}',('−1의 좌극한·값은 0이고 우극한은 1이다. 3의 좌우 극한은 1이지만 값은 2이다.','At −1 the left limit and value are zero, while the right limit is 1. At 3 both limits are 1 but the value is 2.'),[[(-3,0),(-1,0)],[(-1,1),(5,1)]],[(-1,0),(-1,1,'open'),(3,1,'open'),(3,2)],(-3,5,-.5,2.5))]
for n,require,formula,reason,cs,dots,bounds in construct:
 add(n,('실수 전체에 정의되고 '+require[0]+'을 가지며 나머지 점에서는 연속인 함수를 그리고 제시하라.','Construct and sketch a function defined on all real numbers with '+require[1]+', continuous elsewhere.'),[(d(formula),d(formula)),reason],('위 조각함수가 한 예이다.','The displayed piecewise function is one example.'),('각 조각 내부는 연속이고 모든 접합점·별도 지정점에서 요구된 극한과 함수값을 확인했다.','Every piece is continuous internally, and each junction or reassigned point has the required limits and values.'))
 D.fig(n,[panel('Constructed continuity example',bounds,cs,dots)])
add(11,('통행료는 보통 $5, 07–10시와 16–19시에는 $7이다. (a)자정 이후 시간 t의 함수로 그리고 (b)불연속과 이용자의 의미를 설명하라.','A toll is $5 normally and $7 during 07–10 and 16–19. (a)Graph it against hours t after midnight and (b)explain its discontinuities and their meaning for travelers.'),[('시작 시각 포함·종료 시각 제외로 정하면 T=7은 [7,10)∪[16,19), 나머지 [0,24)에서는 T=5이다.','Using start-inclusive, end-exclusive intervals, T=7 on [7,10)∪[16,19) and T=5 elsewhere in [0,24).'),('경계 7,10,16,19에서 $2의 점프가 있어 아주 작은 통과 시각 차이가 요금을 바꾼다.','There are $2 jumps at 7,10,16,19, so a tiny change in crossing time can change the charge.')],('불연속 시각:07:00,10:00,16:00,19:00.','Discontinuities:07:00,10:00,16:00,19:00.'),('정확한 경계 시각의 요금은 원문의 끝점 규정이 없어 선택을 명시했다. 어느 규정이어도 네 시각의 점프는 유지된다.','Because the source does not specify boundary-time charges, the convention is explicit. Either convention retains the same four jumps.'),list('ab'))
D.fig(11,[panel('Toll by hour after midnight',(0,24,4,8),[[(0,5),(7,5)],[(7,7),(10,7)],[(10,5),(16,5)],[(16,7),(19,7)],[(19,5),(24,5)]],[(7,5,'open'),(7,7),(10,7,'open'),(10,5),(16,5,'open'),(16,7),(19,7,'open'),(19,5)],xticks=[0,7,10,16,19,24],yticks=[5,7],xlabel='hour',ylabel='$')])
add(12,('다음 양의 연속성을 설명하라: (a)한 장소의 시간별 온도, (b)한 시각에 뉴욕에서 서쪽으로 이동한 거리별 온도, (c)같은 거리별 고도, (d)택시 거리별 요금, (e)방 조명 회로의 시간별 전류.','Discuss continuity of (a)temperature versus time at one location, (b)temperature versus westward distance from New York at one time, (c)altitude versus the same distance, (d)taxi fare versus distance, and (e)lighting-circuit current versus time.'),[('(a),(b)는 통상적인 연속 매질 모형에서 작은 시간·위치 변화가 작은 온도 변화로 이어져 연속으로 본다.','In the usual continuous-medium model, (a) and (b) are continuous because small time or position changes produce small temperature changes.'),('(c)는 절벽을 수직으로 이상화하면 고도가 점프할 수 있다. (d)는 일정 거리마다 요금이 가산되는 계단 모형에서 불연속이다.','For (c), an idealized vertical cliff can create a jump in altitude. In (d), a fare increased at distance thresholds is a discontinuous step function.'),('(e)는 이상적 스위치 모형에서 켜고 끄는 순간 전류가 점프한다. 실제 물리 전이는 유한 시간에 걸칠 수 있다.','In (e), an ideal switch model makes current jump when switched on or off; a physical transition can take a finite time.')],('(a),(b)통상 연속 모형; (c)절벽에서 불연속 가능; (d)요금 임계거리에서 점프; (e)이상적 스위치 시각에서 점프.','(a),(b)usually modeled continuously; (c)possible discontinuities at cliffs; (d)jumps at fare thresholds; (e)jumps at ideal switching times.'),('물리량 자체와 문제에서 쓰는 이상화된 모형의 연속성을 구분해, 임의의 실제 관측 자료까지 단정하지 않았다.','Distinguished the idealized textbook models from unrestricted claims about every physical observation.'),list('abcde'))
x=s.symbols('x',real=True)
for n,f,a in [(13,3*x*x+(x+2)**5,-1),(14,(x*x+5*x)/(2*x+1),2),(15,2*s.sqrt(3*x*x+1),1),(16,(4*x*x-2*x+7)**s.Rational(1,3),-2)]:
 L=s.simplify(f.subs(x,a))
 add(n,('정의와 극한 법칙으로 '+m('f(x)='+tex(f))+f'가 a={a}에서 연속임을 보여라.','Using the definition and limit laws, show that '+m('f(x)='+tex(f))+f' is continuous at a={a}.'),[('다항식·근호·몫의 극한 법칙으로 해당 입력을 대입한다. 분모는 0이 아니고 근호는 실수 정의역에 있다.','Apply polynomial, root, and quotient limit laws by substitution; denominators are nonzero and roots lie in their real domains.'),(d(r'\lim_{x\to'+str(a)+'}f(x)='+tex(L)+'=f('+str(a)+')'),d(r'\lim_{x\to'+str(a)+'}f(x)='+tex(L)+'=f('+str(a)+')'))],('연속이며 공통값은 '+m(tex(L))+'.','Continuous, with common value '+m(tex(L))+'.'),('원래 식의 함수값과 독립 기호 극한을 비교했다.','Compared direct evaluation of the original expression with an independent symbolic limit.'))
add(17,('f(x)=x+√(x−4)가 [4,∞)에서 연속임을 정의로 보여라.','Show from continuity and limit laws that f(x)=x+√(x−4) is continuous on [4,∞).'),[('a>4에서는 lim f(x)=a+√(a−4)=f(a)이다. 끝점에서는 오른쪽만 접근하여 lim(x→4⁺)f(x)=4=f(4)를 얻는다.','For a>4, lim f(x)=a+√(a−4)=f(a). At the endpoint use the right-hand limit, lim(x→4⁺)f(x)=4=f(4).')],('[4,∞)에서 연속.','Continuous on [4,∞).'),('x<4는 실수 근호의 정의역 밖이므로 끝점에 양쪽 극한을 요구하지 않는다.','Inputs x<4 are outside the real-root domain, so a two-sided endpoint limit is not required.'))
add(18,('g(x)=(x−1)/(3x+6)가 (−∞,−2)에서 연속임을 보여라.','Show that g(x)=(x−1)/(3x+6) is continuous on (−∞,−2).'),[('임의 a<−2에서 3a+6≠0이므로 몫 법칙으로 lim g(x)=(a−1)/(3a+6)=g(a)이다.','For any a<−2, 3a+6≠0, so the quotient law gives lim g(x)=(a−1)/(3a+6)=g(a).')],('(−∞,−2)에서 연속.','Continuous on (−∞,−2).'),('제외된 끝점 −2에서는 분모가 0이므로 주어진 열린 구간의 조건이 필요하다.','At the excluded endpoint −2 the denominator is zero, confirming the relevance of the open interval.'))
for n in [19,20]:
 add(n,('함수 '+m(r'f(x)=1/(x+2)')+('에 대해 a=−2에서 불연속인 이유를 설명하고 그려라.'if n==19 else'를 x≠−2에 사용하고 f(−2)=1로 정한다. −2에서 불연속인 이유를 설명하고 그려라.'),'Use '+m(r'f(x)=1/(x+2)')+(' and explain its discontinuity at −2; sketch the graph.'if n==19 else' for x≠−2 and set f(−2)=1. Explain the discontinuity at −2 and sketch the graph.')),[(d(r'\lim_{x\to-2^-}f(x)=-\infty,\quad\lim_{x\to-2^+}f(x)=+\infty'),d(r'\lim_{x\to-2^-}f(x)=-\infty,\quad\lim_{x\to-2^+}f(x)=+\infty')),('유한 양쪽 극한이 없어 한 점의 값으로 연속성을 만들 수 없다.','There is no finite two-sided limit, so no single-point assignment can make the function continuous.')],('−2에서 무한 불연속.','Infinite discontinuity at −2.'),('분자는 양수 1, 분모는 접근 방향에 따라 부호가 달라지는 작은 수이므로 두 발산 방향을 확인할 수 있다.','The positive numerator 1 divided by a small denominator of opposite signs confirms both divergence directions.'))
 D.fig(n,[panel('Reciprocal with vertical asymptote',(-5,2,-5,5),[samples(lambda z:1/(z+2),-5,-2.01),samples(lambda z:1/(z+2),-1.99,2)],[]if n==19 else[(-2,1)])])
disc=[(21,r'\begin{cases}1-x^2&x<1\\1/x&x\ge1\end{cases}',1,('왼쪽 극한 0, 오른쪽 극한과 함수값 1로 점프한다.','The left limit is 0 while the right limit and value are 1, giving a jump.'),[samples(lambda z:1-z*z,-2,1),samples(lambda z:1/z,1,4)],[(1,0,'open'),(1,1)],(-2,4,-3,2)),(22,r'\begin{cases}(x^2-x)/(x^2-1)&x\ne1\\1&x=1\end{cases}',1,('x≠±1에서 f=x/(x+1)이므로 극한은 1/2이나 f(1)=1이다.','For x≠±1, f=x/(x+1), so the limit is 1/2 while f(1)=1.'),[samples(lambda z:z/(z+1),-3,-1.01),samples(lambda z:z/(z+1),-.99,3)],[(1,.5,'open'),(1,1)],(-3,3,-3,4)),(23,r'\begin{cases}\cos x&x<0\\0&x=0\\1-x^2&x>0\end{cases}',0,('두 한쪽 극한은 1이지만 f(0)=0이다.','Both one-sided limits are 1, but f(0)=0.'),[samples(math.cos,-3,0),samples(lambda z:1-z*z,0,2)],[(0,1,'open'),(0,0)],(-3,2,-3,2)),(24,r'\begin{cases}(2x^2-5x-3)/(x-3)&x\ne3\\6&x=3\end{cases}',3,('분자=(x−3)(2x+1)이므로 극한은 7, 지정값은 6이다.','The numerator is (x−3)(2x+1), so the limit is 7 while the assigned value is 6.'),[samples(lambda z:2*z+1,1,5)],[(3,7,'open'),(3,6)],(1,5,2,12))]
for n,form,a,reason,cs,dots,bounds in disc:
 add(n,('함수 '+d('f(x)='+form)+f'가 a={a}에서 불연속인 이유를 설명하고 그려라.','For '+d('f(x)='+form)+f', explain the discontinuity at a={a} and sketch the graph.'),[reason,('연속성에는 존재하는 양쪽 극한이 실제 함수값과 같아야 한다.','Continuity requires an existing two-sided limit equal to the assigned value.')],('점프 불연속.'if n==21 else'제거 가능 불연속.','Jump discontinuity.'if n==21 else'Removable discontinuity.'),('열린 점에는 접근값, 닫힌 점에는 지정값을 표시했다.'+('22번 원식은 −1에서도 정의되지 않으며 그 점근선도 그래프에 보존했다.'if n==22 else''),'Open points show approached values and filled points show assignments.'+(' In 22 the original expression is also undefined at −1; its asymptote is retained in the graph.'if n==22 else'')))
 D.fig(n,[panel('Assigned value versus limit',bounds,cs,dots)])
for n,form,g,L in [(25,r'\frac{x-3}{x^2-9}',r'\frac1{x+3}',s.Rational(1,6)),(26,r'\frac{x^2-7x+12}{x-3}',r'x-4',-1)]:
 add(n,('f(x)='+m(form)+'에 대해 (a)3의 불연속이 제거 가능함을 보이고 (b)연속이 되도록 f(3)을 정하라.','For f(x)='+m(form)+', (a)show that the discontinuity at 3 is removable and (b)assign f(3) to make it continuous there.'),[('x≠3에서 인수 (x−3)를 약분하면 '+m(g)+'이다.','Cancel the factor (x−3) for x≠3 to obtain '+m(g)+'.'),('이 식의 3에서 극한은 '+m(tex(L))+'로 유한하다.','Its limit at 3 is finite and equals '+m(tex(L))+'.')],d('f(3)='+tex(L)),('이 값만이 기존의 뚫린 근방 극한과 일치하므로 유일한 연속 재정의이다.'+('−3의 다른 특이점까지 제거하는 것은 아니다.'if n==25 else''),'This is the unique assignment agreeing with the existing punctured-neighborhood limit.'+(' It does not remove the other singularity at −3.'if n==25 else'')),list('ab'))
domains=[(27,r'\frac{x^2}{\sqrt{x^4+2}}',r'\mathbb R','x⁴+2≥2이므로 근호 분모가 항상 양수이다.','The radicand x⁴+2≥2 makes the denominator always positive.'),(28,r'\frac{3x-1}{x^2+2x-15}',r'\mathbb R\setminus\{-5,3\}','분모=(x+5)(x−3)이므로 −5,3을 제외한다.','The denominator factors as (x+5)(x−3), excluding −5 and 3.'),(29,r'\frac{\cos(x^2)}{1-x^2}',r'\mathbb R\setminus\{-1,1\}','cos(x²)는 연속이고 분모는 ±1에서만 0이다.','The composition cos(x²) is continuous and the denominator vanishes only at ±1.'),(30,r'\frac1x-\frac{x^2}{x-2}',r'\mathbb R\setminus\{0,2\}','두 유리식의 공통 정의역은 0과 2를 제외한 실수이다.','The common domain of the rational terms excludes 0 and 2.'),(31,r'x\sqrt{9-x^2}',r'[-3,3]','9−x²≥0을 풀면 −3≤x≤3이다.','Solving 9−x²≥0 gives −3≤x≤3.'),(32,r'\sqrt{3x-2}+\sqrt[3]{2x-3}',r'[2/3,\infty)','제곱근은 x≥2/3, 실수 세제곱근은 모든 x에서 정의된다.','The square root requires x≥2/3; the real cube root is defined for every x.'),(33,r'\sqrt{1+1/x}',r'(-\infty,-1]\cup(0,\infty)','(x+1)/x≥0이며 x≠0이어야 하므로 부호표로 두 구간을 얻는다.','Require (x+1)/x≥0 and x≠0; a sign chart gives the two intervals.'),(34,r'\sin(\cos(\sin x))',r'\mathbb R','사인과 코사인은 실수 전체에서 연속이며 세 합성 모두 정의된다.','Sine and cosine are continuous on all real numbers and every stage of the composition is defined.')]
for n,form,dom,ko,en in domains:
 add(n,('함수 '+m('f(x)='+form)+'의 정의역을 쓰고 정의역의 모든 점에서 연속인 이유를 설명하라.','State the domain of '+m('f(x)='+form)+' and explain why it is continuous at every point of that domain.'),[(ko,en),('연속인 기본함수의 합·곱·몫(분모≠0)·합성은 그 정의역에서 연속이다.','Sums, products, quotients with nonzero denominators, and compositions of continuous basic functions are continuous on their domains.')],d('D='+dom),('분모의 영점과 짝수근의 부등식을 먼저 처리하여 연속성 법칙을 정의역 밖에 적용하지 않았다. 끝점은 정의역 내 한쪽 연속성을 뜻한다.','Resolved denominator zeros and even-root inequalities before applying continuity laws. At a domain endpoint, continuity is from within the domain.'))
lims=[(35,x*s.sqrt(20-x*x),2,8),(36,s.sin(s.tan(s.cos(x))),s.pi/2,0),(37,x*x*s.tan(x),s.pi/4,s.pi**2/16),(38,x**3/s.sqrt(x*x+x-2),2,4)]
for n,f,a,L in lims:
 add(n,('연속성을 이용해 '+d(r'\lim_{x\to'+tex(a)+'}'+tex(f))+'을 구하라.','Use continuity to evaluate '+d(r'\lim_{x\to'+tex(a)+'}'+tex(f))),[('접근점에서 모든 구성함수가 정의되고 분모는 0이 아니므로 직접 대입할 수 있다.','Every component is defined at the approach point and any denominator is nonzero, so direct substitution is valid.'),(d('f('+tex(a)+')='+tex(L)),d('f('+tex(a)+')='+tex(L)))],d(tex(L)),('근호 내부·탄젠트 입력을 단계별로 대입해 합성 중 숨은 특이점이 없음을 확인했다.','Evaluated the radicands and tangent inputs stage by stage to check for hidden singularities in the composition.'))
add(39,('f(x)=1/√(1−sin x)의 불연속 위치를 구하고 그려라.','Locate the discontinuities of f(x)=1/√(1−sin x) and plot it.'),[('1−sin x≥0이지만 분모이므로 0인 점은 제외한다. sin x=1의 해는 π/2+2kπ이다.','Although 1−sin x≥0, its zeros must be excluded because the root is a denominator. The solutions of sin x=1 are π/2+2kπ.'),('각 제외점의 양쪽에서 양의 분모가 0으로 가므로 +∞로 발산한다.','On both sides of each excluded point, the positive denominator approaches zero and the function tends to +∞.')],d(r'x=\pi/2+2k\pi,\quad k\in\mathbb Z'),('항등식 1−sin(a+h)=1−cos h=2sin²(h/2)로 점근선 근처의 양의 발산을 확인한다.','The identity 1−sin(a+h)=1−cos h=2sin²(h/2) confirms positive divergence near each asymptote.'))
cuts=[-2*math.pi,-3*math.pi/2,math.pi/2,2*math.pi]
D.fig(39,[panel('Reciprocal square root of 1 - sin x',(-2*math.pi,2*math.pi,0,8),[samples(lambda z:1/math.sqrt(1-math.sin(z)),a+.005,b-.005)for a,b in zip(cuts,cuts[1:])])])
add(40,('y=tan√x의 불연속 위치를 찾고 그래프를 그려라.','Locate the discontinuities of y=tan√x and plot the graph.'),[('x≥0이 필요하다. √x=π/2+kπ에서 탄젠트가 정의되지 않으며 √x≥0이므로 k=0,1,2,…이다.','The square root requires x≥0. Tangent fails at √x=π/2+kπ; since √x≥0, k=0,1,2,….'),('나머지 정의역에서는 합성 연속이고 x=0에서도 오른쪽으로 연속이다.','The composition is continuous elsewhere in its domain and is right-continuous at x=0.')],d(r'x=(\pi/2+k\pi)^2,\quad k=0,1,2,\ldots'),('제곱으로 생길 수 있는 중복 해를 k≥0으로 제거했다. 음의 x는 정의역 밖이며 불연속점으로 별도 열거하지 않는다.','Restricting k≥0 removes duplicates from squaring. Negative x lies outside the domain and is not separately listed as a discontinuity.'))
cuts=[0,(math.pi/2)**2,(3*math.pi/2)**2,30]
D.fig(40,[panel('tan of square root', (0,30,-8,8),[samples(lambda z:math.tan(math.sqrt(z)),a+.005,b-.005)for a,b in zip(cuts,cuts[1:])],[(0,0)])])
for n,form,a,vl,vr,L in [(41,r'\begin{cases}1-x^2&x\le1\\\sqrt{x-1}&x>1\end{cases}',1,'1−1²','√(1−1)',0),(42,r'\begin{cases}\sin x&x<\pi/4\\\cos x&x\ge\pi/4\end{cases}',r'\pi/4','sin(π/4)','cos(π/4)',s.sqrt(2)/2)]:
 add(n,('함수 '+d('f(x)='+form)+'가 모든 실수에서 연속임을 보여라.','Show that '+d('f(x)='+form)+' is continuous on all real numbers.'),[('각 조각 내부에서는 기본함수의 연속성이 적용된다. 접합점의 왼쪽·오른쪽 극한은 '+vl+', '+vr+'이다.','Each piece is continuous internally. At the junction, the one-sided limits are '+vl+' and '+vr+'.'),('두 값과 접합점의 지정값이 모두 '+m(tex(L))+'로 같다.','Both limits and the assigned junction value equal '+m(tex(L))+'.')],('ℝ 전체에서 연속.','Continuous on ℝ.'),('접합점의 부등호가 지정값을 어느 조각에서 정하는지 확인했고, 그 값도 공통 극한과 일치한다.','Checked which branch supplies the endpoint value and verified it equals the common limit.'))
for n,form,reason,answer,cs,dots,bounds in [(43,r'\begin{cases}x^2&x<-1\\x&-1\le x<1\\1/x&x\ge1\end{cases}',('−1에서 좌극한 1, 우극한·값 −1이다. 1에서는 양쪽과 값이 모두 1이다.','At −1 the left limit is 1 while the right limit and value are −1. At 1 both limits and the value equal 1.'),('−1에서만 불연속이며 오른쪽으로 연속.','Discontinuous only at −1, where it is right-continuous.'),[samples(lambda z:z*z,-2,-1),[(-1,-1),(1,1)],samples(lambda z:1/z,1,4)],[(-1,1,'open'),(-1,-1),(1,1)],(-2,4,-2,5)),(44,r'\begin{cases}x^2+1&x\le1\\3-x&1<x\le4\\\sqrt x&x>4\end{cases}',('1에서는 좌우·값이 2이다. 4에서는 좌극한·값 −1, 우극한 2로 점프한다.','At 1 both limits and the value equal 2. At 4 the left limit and value are −1 while the right limit is 2.'),('4에서만 불연속이며 왼쪽으로 연속.','Discontinuous only at 4, where it is left-continuous.'),[samples(lambda z:z*z+1,-2,1),[(1,2),(4,-1)],samples(math.sqrt,4,7)],[(1,2),(4,-1),(4,2,'open')],(-2,7,-2,6)),(45,r'\begin{cases}x+2&x<0\\2x^2&0\le x\le1\\2-x&x>1\end{cases}',('0에서 좌극한 2, 우극한·값 0이다. 1에서 좌극한·값 2, 우극한 1이다.','At 0 the left limit is 2 and the right limit and value are 0. At 1 the left limit and value are 2 and the right limit is 1.'),('0,1에서 불연속. 0은 오른쪽, 1은 왼쪽으로 연속.','Discontinuous at 0 and 1; right-continuous at 0 and left-continuous at 1.'),[[(-2,0),(0,2)],samples(lambda z:2*z*z,0,1),[(1,1),(4,-2)]],[(0,2,'open'),(0,0),(1,2),(1,1,'open')],(-2,4,-3,3))]:
 add(n,('함수 '+d('f(x)='+form)+'의 불연속점·한쪽 연속성을 분류하고 그래프를 그려라.','Classify discontinuities and one-sided continuity of '+d('f(x)='+form)+' and sketch its graph.'),[reason,('다른 점들은 각 연속 조각 내부이므로 추가 불연속이 없다.','Every other point lies inside a continuous piece, so no additional discontinuities occur.')],answer,('접합점마다 왼쪽 극한·오른쪽 극한·지정값의 세 값을 따로 비교했다.','Compared the left limit, right limit, and assigned value separately at every junction.'))
 D.fig(n,[panel('Piecewise continuity classification',bounds,cs,dots)])
add(46,('G,M,R>0이고 F(r)=GMr/R³(r<R), GM/r²(r≥R)이다. 거리 r≥0에서 연속인지 판단하라.','For G,M,R>0, define F(r)=GMr/R³ when r<R and GM/r² when r≥R. Determine continuity for distances r≥0.'),[('각 조각 내부는 연속이고 접합점 R의 두 접근값은 GMR/R³=GM/R²이다. 오른쪽 지정값도 같다.','Both pieces are continuous internally. At R both approach GMR/R³=GM/R², which also equals the assigned value.'),('r=0에서는 첫 식의 오른쪽 극한 0이 F(0)=0과 같다.','At r=0, the first formula has right limit zero, equal to F(0).')],('[0,∞) 전체에서 연속.','Continuous on [0,∞).'),('r⁻² 식은 r≥R>0에서만 사용되므로 원점 특이점이 이 조각함수에 나타나지 않는다.','The r⁻² formula is used only for r≥R>0, so its apparent singularity at the origin is absent from the piecewise function.'))
add(47,('f(x)=cx²+2x(x<2), x³−cx(x≥2)가 모든 실수에서 연속이 되게 c를 정하라.','Choose c so that f(x)=cx²+2x for x<2 and x³−cx for x≥2 is continuous on all real numbers.'),[('접합점 2의 좌우를 맞추면 4c+4=8−2c이다.','Matching the sides at 2 gives 4c+4=8−2c.'),(d(r'6c=4\Longrightarrow c=2/3'),d(r'6c=4\Longrightarrow c=2/3'))],d('c=2/3'),('이 값을 대입하면 양쪽 극한과 f(2)가 모두 20/3이다.','Substitution makes both limits and f(2) equal 20/3.'))
add(48,('f(x)=(x²−4)/(x−2)(x<2), ax²−bx+3(2≤x<3), 2x−a+b(x≥3)가 모든 실수에서 연속이 되도록 a,b를 구하라.','Choose a,b so that f(x)=(x²−4)/(x−2) for x<2, ax²−bx+3 for 2≤x<3, and 2x−a+b for x≥3 is continuous everywhere.'),[('첫 조각은 x+2로 약분되어 2의 좌극한이 4이다. 따라서 4a−2b+3=4이다.','The first piece cancels to x+2 and has left limit 4 at 2, giving 4a−2b+3=4.'),('3에서 9a−3b+3=6−a+b, 즉 10a−4b=3이다.','Matching at 3 gives 9a−3b+3=6−a+b, or 10a−4b=3.'),(d(r'4a-2b=1,\quad10a-4b=3\Longrightarrow a=b=1/2'),d(r'4a-2b=1,\quad10a-4b=3\Longrightarrow a=b=1/2'))],d('a=b=1/2'),('2에서 공통값 4, 3에서 공통값 6으로 직접 다시 대입해 확인했다.','Direct substitution recovers common value 4 at 2 and common value 6 at 3.'))
add(49,('f,g가 연속이고 g(2)=6, lim(x→2)[3f(x)+f(x)g(x)]=36이다. f(2)를 구하라.','Let f,g be continuous, with g(2)=6 and lim(x→2)[3f(x)+f(x)g(x)]=36. Find f(2).'),[('연속성과 합·곱 법칙으로 3f(2)+f(2)g(2)=36이다.','Continuity and the sum/product laws give 3f(2)+f(2)g(2)=36.'),(d('9f(2)=36'),d('9f(2)=36'))],d('f(2)=4'),('구한 값으로 3·4+4·6=36을 확인한다.','The check is 3·4+4·6=36.'))
add(50,('f(x)=1/x, g(x)=1/x²이다. (a)f∘g의 식과 정의역을 구하고 (b)실수 전체에서 연속인지 판단하라.','Let f(x)=1/x and g(x)=1/x². (a)Find f∘g and its domain. (b)Is it continuous on all real numbers?'),[(d(r'(f\circ g)(x)=\frac1{1/x^2}=x^2\quad(x\ne0)'),d(r'(f\circ g)(x)=\frac1{1/x^2}=x^2\quad(x\ne0)')),('0에서는 안쪽 함수 g가 정의되지 않으므로 합성도 정의되지 않는다.','At zero the inner function g is undefined, so the composition is undefined too.')],('(a)x², 정의역 ℝ∖{0}. (b)아니다. 정의역에서는 연속이며 0에 값을 0으로 추가하면 연속 확장된다.','(a)x², domain ℝ∖{0}. (b)No. It is continuous on its domain and extends continuously by assigning value zero at 0.'),('약분한 식이 같아도 합성의 원래 정의역 제한은 유지해야 한다.','Equality of the simplified formula does not erase the original composition-domain restriction.'),list('ab'))
add(51,('(a)(x⁴−1)/(x−1),a=1; (b)(x³−x²−2x)/(x−2),a=2; (c)⌊sin x⌋,a=π의 불연속이 제거 가능한지 판단하고 가능하면 연속 확장식을 쓰라.','Decide whether each discontinuity is removable, and give a continuous extension where possible: (a)(x⁴−1)/(x−1) at 1; (b)(x³−x²−2x)/(x−2) at 2; (c)⌊sin x⌋ at π.'),[('(a)x⁴−1=(x−1)(x³+x²+x+1)이므로 확장값은 4이다.','(a)x⁴−1=(x−1)(x³+x²+x+1), giving extension value 4.'),('(b)x³−x²−2x=x(x−2)(x+1)이므로 확장값은 6이다.','(b)x³−x²−2x=x(x−2)(x+1), giving extension value 6.'),('(c)π의 왼쪽에서 sin x는 작은 양수여서 바닥값 0, 오른쪽에서는 작은 음수여서 −1이다.','(c)Immediately left of π, sine is small and positive and its floor is 0; immediately right it is small and negative and its floor is −1.')],('(a)가능:g=x³+x²+x+1. (b)가능:g=x²+x. (c)점프이므로 불가능.','(a)Removable:g=x³+x²+x+1. (b)Removable:g=x²+x. (c)Not removable because it is a jump.'),('두 다항식 확장은 제외점을 뺀 모든 입력에서 원식과 동일하며, 바닥함수의 좌우 불일치는 단일점 변경으로 해소되지 않는다.','The polynomial extensions agree with the originals off the excluded points. A single-point reassignment cannot remove the floor function’s one-sided disagreement.'),list('abc'))
add(52,('[0,1]에서 0.25만 불연속이고 f(0)=1,f(1)=3이다. f(c)=2가 전혀 없는 예와 여전히 존재하는 예를 각각 그려 중간값 정리의 가정과 결론을 구별하라.','On [0,1], f is discontinuous only at 0.25 and has f(0)=1,f(1)=3. Sketch one example with no f(c)=2 and another where f(c)=2 still occurs, distinguishing the theorem’s hypothesis from its conclusion.'),[('예 A:f=1(x<1/4), f=3(x≥1/4). 값 2는 나타나지 않는다.','Example A:f=1 for x<1/4 and f=3 for x≥1/4. The value 2 never occurs.'),('예 B:f=1(x<1/4), f=4x−1(x≥1/4). 점프는 있지만 f(3/4)=2이다.','Example B:f=1 for x<1/4 and f=4x−1 for x≥1/4. Despite the jump, f(3/4)=2.')],('연속성 가정이 없으면 결론은 보장되지 않지만 우연히 성립할 수도 있다.','Without continuity the conclusion is not guaranteed, though it may still hold.'),('두 예 모두 끝값 1,3과 유일한 불연속점 1/4를 직접 확인했다.','Both examples have the required endpoint values 1 and 3 and exactly one discontinuity at 1/4.'))
D.fig(52,[panel('Example A: misses value 2',(0,1,-.3,3.5),[[(0,1),(.25,1)],[(.25,3),(1,3)],[(0,2),(1,2)]],[(0,1),(.25,1,'open'),(.25,3),(1,3)],xticks=[0,.25,.75,1]),panel('Example B: reaches 2 at 0.75',(0,1,-.3,3.5),[[(0,1),(.25,1)],[(.25,0),(1,3)],[(0,2),(1,2)]],[(0,1),(.25,1,'open'),(.25,0),(.75,2),(1,3)],xticks=[0,.25,.75,1])])
add(53,('f(x)=x²+10sin x가 어떤 실수 c에서 1000을 취함을 증명하라.','Prove that f(x)=x²+10sin x equals 1000 at some real c.'),[('f는 다항식과 사인의 합이므로 연속이다. f(0)=0<1000이다.','The sum of a polynomial and sine is continuous, and f(0)=0<1000.'),('sin32≥−1이므로 f(32)≥32²−10=1014>1000이다.','Since sin32≥−1, f(32)≥32²−10=1014>1000.')],('중간값 정리에 의해 c∈(0,32)에서 f(c)=1000.','By the Intermediate Value Theorem, some c∈(0,32) satisfies f(c)=1000.'),('삼각함수의 근삿값 없이 하계 1014로 엄격한 양끝 부등식을 확보했다.','The lower bound 1014 establishes the strict endpoint inequalities without approximating sine.'))
add(54,('f는 [1,5]에서 연속이고 f(x)=6의 해는 1과 4뿐이다. f(2)=8일 때 f(3)>6인 이유를 증명하라.','Suppose f is continuous on [1,5], and the only solutions to f(x)=6 are 1 and 4. Given f(2)=8, prove f(3)>6.'),[('3은 주어진 해가 아니므로 f(3)≠6이다. 만약 f(3)<6이면 2의 값 8과 3의 값 사이에 6이 있다.','Since 3 is not a listed solution, f(3)≠6. If f(3)<6, the value 6 lies between f(2)=8 and f(3).'),('중간값 정리는 (2,3)에 새로운 해를 주어 유일한 해가 1,4라는 가정과 모순이다.','The Intermediate Value Theorem then produces another solution in (2,3), contradicting the stated complete solution set.')],d('f(3)>6'),('등호와 작은 경우를 각각 배제했으므로 남는 부등호는 엄격한 >이다.','Equality and the smaller case have both been excluded, leaving the strict inequality >.'))
ivt=[(55,-x**3+4*x+1,-1,0,r'-x^3+4x+1=0'),(56,2/x-x+s.sqrt(x),2,3,r'2/x=x-\sqrt x'),(57,s.cos(x)-x,0,1,r'\cos x=x'),(58,s.sin(x)-x*x+x,1,2,r'\sin x=x^2-x')]
for n,f,a,b,equation in ivt:
 fa=s.simplify(f.subs(x,a));fb=s.simplify(f.subs(x,b))
 add(n,('방정식 '+m(equation)+f'이 ({a},{b}) 안에 해를 가짐을 중간값 정리로 증명하라.','Use the Intermediate Value Theorem to show that '+m(equation)+f' has a solution in ({a},{b}).'),[('양변 차를 '+m('F(x)='+tex(f))+f'로 놓으면 [{a},{b}]에서 연속이다.','Set '+m('F(x)='+tex(f))+f'; it is continuous on [{a},{b}].'),(d('F('+str(a)+')='+tex(fa)+r',\quad F('+str(b)+')='+tex(fb)),d('F('+str(a)+')='+tex(fa)+r',\quad F('+str(b)+')='+tex(fb))),('양끝 값의 부호가 반대이므로 중간에서 F=0이 된다.','The endpoint values have opposite signs, so F vanishes at an interior point.')],(f'해 c∈({a},{b})가 존재한다.',f'A solution c∈({a},{b}) exists.'),('근호·분모 정의역을 닫힌 구간 전체에서 확인하고 양끝 부호를 별도로 검산했다.','Checked root and denominator domains over the entire closed interval and independently verified endpoint signs.'))
rootspec=[(59,lambda z:mp.cos(z)-z**3,(0,1),r'\cos x=x^3'),(60,lambda z:z**5-z*z+2*z+3,(-1,0),r'x^5-x^2+2x+3=0'),(61,lambda z:z**5-z*z-4,(1,2),r'x^5-x^2-4=0'),(62,lambda z:mp.sqrt(z-5)-1/(z+3),(5,6),r'\sqrt{x-5}=1/(x+3)')]
for n,fn,(a,b),eqn in rootspec:
 root=mp.findroot(fn,(a,b));root=float(mp.re(root));lo=math.floor(root*100)/100;hi=lo+.01
 # A narrow sign bracket certifies the reported three-decimal rounding.
 nl=math.floor(root*100000)/100000;nh=nl+.00001
 assert float(fn(a))*float(fn(b))<0
 assert float(fn(lo))*float(fn(hi))<0
 assert float(fn(nl))*float(fn(nh))<0
 add(n,('(a)방정식 '+m(eqn)+'의 실근 존재를 보이고 (b)'+('해를 포함하는 길이 0.01의 구간을 계산하라.'if n<61 else'그래프로 해를 소수 셋째 자리까지 구하라.'),'(a)Prove existence of a real solution to '+m(eqn)+' and (b)'+('find a containing interval of length 0.01.'if n<61 else'locate the solution graphically to three decimal places.')),[(f'양변 차 F는 [{a},{b}]에서 연속이고 F({a})≈{float(fn(a)):.8f}, F({b})≈{float(fn(b)):.8f}로 부호가 반대이다.',f'The difference F is continuous on [{a},{b}], with F({a})≈{float(fn(a)):.8f} and F({b})≈{float(fn(b)):.8f}, of opposite signs.'),(f'계산으로 F({lo:.2f})≈{float(fn(lo)):.9f}, F({hi:.2f})≈{float(fn(hi)):.9f}를 얻어 이 작은 구간에도 해가 있다.',f'Computed F({lo:.2f})≈{float(fn(lo)):.9f} and F({hi:.2f})≈{float(fn(hi)):.9f}, so the smaller interval also contains a root.')],(f'(b)[{lo:.2f},{hi:.2f}]'if n<61 else f'(b)x≈{root:.3f}',f'(b)[{lo:.2f},{hi:.2f}]'if n<61 else f'(b)x≈{root:.3f}'),(f'추가 부호 괄호 [{nl:.5f},{nh:.5f}]에서 반올림을 확인했다. 원래 방정식의 정의역을 유지하여 제곱에 의한 가짜 해를 만들지 않았다.',f'The additional sign bracket [{nl:.5f},{nh:.5f}] checks rounding. The original equation’s domain is preserved, avoiding extraneous roots from squaring.'),list('ab'))
 D.checks.append({'number':n,'method':'60-digit root plus independently evaluated sign brackets','root':root,'bracket':[lo,hi],'roundingBracket':[nl,nh]})
 if n>=61:
  w=.12 if n==61 else .025;ll=max(a,root-w);rr=root+w
  D.fig(n,[panel('Equation residual and zero crossing',(ll,rr,float(fn(ll))-.05,float(fn(rr))+.05),[samples(lambda z:float(fn(z)),ll,rr)],[(root,0)],xticks=[ll,root,rr])])
add(63,('그래프 없이 y=sin(x³)가 (1,2)에서 적어도 두 x절편을 가짐을 보여라.','Without graphing, show that y=sin(x³) has at least two x-intercepts in (1,2).'),[('x³=π 또는 2π이면 사인값이 0이다. 1<π<2π<8이므로 두 실수 세제곱근은 모두 (1,2)에 있다.','Sine vanishes when x³=π or 2π. Since 1<π<2π<8, both real cube roots lie in (1,2).')],d(r'x=\sqrt[3]\pi,\quad x=\sqrt[3]{2\pi}'),('두 입력은 서로 다르고 각각 sinπ=sin2π=0을 정확히 만족한다.','The inputs are distinct and satisfy sinπ=sin2π=0 exactly.'))
add(64,('그래프 없이 y=x²−3+1/x가 (0,2)에서 적어도 두 x절편을 가짐을 보여라.','Without graphing, show that y=x²−3+1/x has at least two x-intercepts in (0,2).'),[(d(r'f(1/4)=17/16>0,\quad f(1)=-1<0,\quad f(2)=3/2>0'),d(r'f(1/4)=17/16>0,\quad f(1)=-1<0,\quad f(2)=3/2>0')),('[1/4,1]과 [1,2]에서 분모가 0이 아니므로 연속이다. 각 구간에 중간값 정리를 적용한다.','The denominator is nonzero on [1/4,1] and [1,2], so the function is continuous there. Apply the Intermediate Value Theorem on each interval.')],('서로 다른 두 해가 (1/4,1)과 (1,2)에 존재한다.','Distinct roots exist in (1/4,1) and (1,2).'),('열린 두 구간은 겹치지 않고 f(1)≠0이므로 같은 해를 두 번 센 것이 아니다.','The open intervals are disjoint and f(1)≠0, so the argument does not count one root twice.'))
add(65,('f가 a에서 연속인 것과 lim(h→0)f(a+h)=f(a)가 동치임을 보여라.','Show that continuity of f at a is equivalent to lim(h→0)f(a+h)=f(a).'),[('치환 x=a+h에서 x→a와 h→0은 동치이고 0<|x−a|<δ는 0<|h|<δ와 정확히 같다.','Under x=a+h, x→a is equivalent to h→0, and 0<|x−a|<δ is exactly 0<|h|<δ.'),('따라서 두 극한의 ε–δ 조건은 같은 입력들을 이름만 바꾸어 기술한다.','Thus the epsilon–delta conditions describe the same inputs under a change of name.')],d(r'\lim_{x\to a}f(x)=f(a)\iff\lim_{h\to0}f(a+h)=f(a)'),('f(a)가 정의되어야 한다는 연속성의 조건을 양쪽 명제 모두에서 유지한다.','Both statements retain the requirement that f(a) be defined.'))
for n,trig,identity,L in [(66,'sin',r'\sin(a+h)=\sin a\cos h+\cos a\sin h',r'\sin a'),(67,'cos',r'\cos(a+h)=\cos a\cos h-\sin a\sin h',r'\cos a')]:
 add(n,('0에서 sin h→0, cos h→1을 이용하여 '+trig+'이 모든 실수에서 연속임을 증명하라.','Using sin h→0 and cos h→1 as h→0, prove that '+trig+' is continuous at every real number.'),[(d(identity),d(identity)),('고정 a의 삼각함수 값은 상수이므로 합·곱 극한 법칙을 적용한다.','The trigonometric values at fixed a are constants, so apply the sum and product limit laws.'),(d(r'\lim_{h\to0}'+chr(92)+trig+'(a+h)='+L),d(r'\lim_{h\to0}'+chr(92)+trig+'(a+h)='+L))],('임의의 a에서 연속이므로 ℝ 전체에서 연속.','Continuous at every arbitrary a, hence on all of ℝ.'),('사인·코사인의 전체 연속성을 미리 사용하지 않고 0의 두 극한과 덧셈 공식만으로 결론을 얻었다.','The proof uses only the two limits at zero and the addition identities, without assuming global trigonometric continuity in advance.'))
add(68,('연속함수에 관한 정리의 (a)상수배 cf, (b)몫 f/g(g(a)≠0)의 연속성 부분을 증명하라.','Prove the continuity theorem for (a)a constant multiple cf and (b)a quotient f/g when g(a)≠0.'),[('(a)lim cf(x)=c lim f(x)=cf(a)=(cf)(a).','(a)lim cf(x)=c lim f(x)=cf(a)=(cf)(a).'),('(b)f,g의 연속성으로 극한은 f(a),g(a)이고 g(a)≠0이므로 몫 법칙에서 lim(f/g)=f(a)/g(a)=(f/g)(a)이다.','(b)Continuity gives limits f(a),g(a). Since g(a)≠0, the quotient law yields lim(f/g)=f(a)/g(a)=(f/g)(a).')],('두 함수 모두 a에서 연속이다.','Both resulting functions are continuous at a.'),('g의 연속성으로 근방에서 |g(x)|>|g(a)|/2를 확보할 수 있어 몫은 실제로 정의된다.','Continuity of g ensures |g(x)|>|g(a)|/2 nearby, so the quotient is genuinely defined.'),list('ab'))
add(69,('연속함수와 극한의 합성 정리를 사용하여 거듭제곱 법칙과 n제곱근 법칙을 증명하라.','Use the composition-with-limits theorem to prove the power law and nth-root law.'),[('g(x)→L일 때 바깥 함수 F(t)=tⁿ은 L에서 연속이므로 F(g(x))→F(L)=Lⁿ이다.','If g(x)→L, the outer function F(t)=tⁿ is continuous at L, giving F(g(x))→F(L)=Lⁿ.'),('F(t)=ⁿ√t도 실수 정의역에서 연속이므로 근들이 정의되는 근방에서 ⁿ√g(x)→ⁿ√L이다. 짝수 n에서는 g(x)≥0과 L≥0이라는 실수근 조건을 유지한다.','The real root function F(t)=ⁿ√t is continuous on its domain, so ⁿ√g(x)→ⁿ√L wherever the roots are defined nearby. For even n retain the real-root conditions g(x)≥0 and L≥0.')],d(r'\lim[g(x)]^n=L^n,\quad\lim\sqrt[n]{g(x)}=\sqrt[n]L'),('합성 정리의 핵심 가정은 안쪽 극한값 L에서 바깥 함수가 연속이라는 것이며, 단지 g가 a에서 정의될 필요는 없다.','The key hypothesis is continuity of the outer function at the inner limit L; g need not be defined at a itself.'))
add(70,('자기 세제곱보다 정확히 1 큰 실수가 존재하는가?','Does there exist a real number exactly one greater than its cube?'),[('x=x³+1은 p(x)=x³−x+1=0과 같다. p는 연속이고 p(−2)=−5,p(−1)=1이다.','The equation x=x³+1 is p(x)=x³−x+1=0. The polynomial is continuous, with p(−2)=−5 and p(−1)=1.')],('존재한다. 적어도 하나가 (−2,−1)에 있다.','Yes; at least one lies in (−2,−1).'),('문장 조건의 방향을 x−x³=1로 확인했으며 x³−x=1과 혼동하지 않았다.','The wording gives x−x³=1, rather than x³−x=1.'))
add(71,('유리수에서 f=0, 무리수에서 f=1인 함수는 어디에서 연속인가?','Where is the function equal to 0 on rational inputs and 1 on irrational inputs continuous?'),[('임의의 a에 접근하는 유리수 수열과 무리수 수열을 잡으면 출력은 각각 0과 1이다.','At any a, rational and irrational sequences approaching a yield constant outputs 0 and 1.'),('조밀성으로 이 두 종류 입력이 모든 근방에 있어 공통 극한이 없다.','Density places both kinds of inputs in every neighborhood, excluding a common limit.')],('어디에서도 연속이 아니다.','Nowhere continuous.'),('a의 유리·무리 여부에 무관하게 접근값 자체가 다르므로 모든 a가 제외된다.','The limiting values disagree regardless of whether a itself is rational or irrational.'))
add(72,('유리수에서 g(x)=0, 무리수에서 g(x)=x인 함수의 연속점을 구하라.','Find the continuity points of g(x)=0 at rational x and g(x)=x at irrational x.'),[('|g(x)|≤|x|이므로 x→0에서 g→0=g(0)이다.','Since |g(x)|≤|x|, g→0=g(0) as x→0.'),('a≠0에서는 유리수 접근값이 0, 무리수 접근값이 a로 달라 공통 극한이 없다.','At a≠0, rational inputs give limit 0 and irrational inputs give limit a, so no common limit exists.')],d(r'x=0\text{ only}'),('0의 연속성은 조임정리로, 나머지 불연속성은 조밀한 두 입력 집합의 서로 다른 극한으로 각각 증명했다.','Continuity at zero follows from squeezing; failure elsewhere follows from distinct limits along the two dense input sets.'))
add(73,('f(x)=x⁴sin(1/x)(x≠0), f(0)=0이 모든 실수에서 연속임을 증명하라.','Prove that f(x)=x⁴sin(1/x) for x≠0, with f(0)=0, is continuous everywhere.'),[('x≠0에서는 연속함수들의 합성·곱이다. 0에서는 |x⁴sin(1/x)|≤x⁴→0이다.','For x≠0 it is a product and composition of continuous functions. At zero, |x⁴sin(1/x)|≤x⁴→0.'),('극한 0이 지정값 f(0)과 같아 접합점도 연속이다.','The zero limit equals f(0), establishing continuity at the junction.')],('ℝ 전체에서 연속.','Continuous on all of ℝ.'),('sin(1/x) 자체의 극한은 사용하지 않았으며 x⁴이 진동의 크기를 0으로 줄인다.','No limit of sin(1/x) itself is used; the x⁴ factor reduces the oscillation amplitude to zero.'))
add(74,('a,b>0일 때 a/(x³+2x²−1)+b/(x³+x−2)=0이 (−1,1)에서 적어도 하나의 해를 가짐을 증명하라.','For a,b>0, prove that a/(x³+2x²−1)+b/(x³+x−2)=0 has at least one solution in (−1,1).'),[(d(r'P=(x+1)(x^2+x-1),\quad Q=(x-1)(x^2+x+2),\quad\alpha=(\sqrt5-1)/2'),d(r'P=(x+1)(x^2+x-1),\quad Q=(x-1)(x^2+x+2),\quad\alpha=(\sqrt5-1)/2')),('α<x<1에서 P>0,Q<0이며 두 분모 모두 0이 아니다. 다항식 H=aQ+bP를 고려한다.','For α<x<1, P>0,Q<0 and neither denominator vanishes. Consider the polynomial H=aQ+bP.'),('H(α)=aQ(α)<0이고 H(1)=bP(1)=2b>0이므로 중간값 정리에 의해 H(c)=0인 c∈(α,1)이 존재한다.','Since H(α)=aQ(α)<0 and H(1)=bP(1)=2b>0, the Intermediate Value Theorem gives H(c)=0 for some c∈(α,1).'),('그 열린 구간에서 PQ≠0이므로 H/(PQ)=a/P+b/Q=0이다.','On that open interval PQ≠0, so H/(PQ)=a/P+b/Q=0.')],d(r'\exists c\in((\sqrt5-1)/2,1)\subset(-1,1)'),('분모가 0인 점을 포함하는 원래 유리함수에 중간값 정리를 잘못 적용하지 않고, 연속 다항식 H에 적용한 뒤 분모를 검증했다.','Applied the theorem to continuous polynomial H, then checked the denominators, avoiding an invalid application across poles of the original rational function.'))
add(75,('같은 산길을 첫날 07–19시에 오르고 다음날 같은 시간 동안 내려온다. 두 날에 정확히 같은 시각에 같은 지점을 지나는 순간이 있음을 중간값 정리로 보여라.','A monk ascends a fixed mountain path from 07:00 to 19:00 and descends it during the same hours the next day. Use the Intermediate Value Theorem to show a location crossed at exactly the same clock time on both days.'),[('길을 따라 아래에서 잰 거리를 사용하고 전체 길이를 ℓ>0이라 하자. 같은 시각 t의 첫날·둘째 날 위치를 u(t),d(t)라 두면 둘 다 연속이다.','Use distance along the path from its bottom, with total length ℓ>0. Let u(t),d(t) be the continuous positions on the two days at the same clock time.'),('h(t)=u(t)−d(t)는 연속이고 07시에 −ℓ,19시에 ℓ이다.','The difference h(t)=u(t)−d(t) is continuous, equals −ℓ at 07:00, and equals ℓ at 19:00.'),('중간값 정리는 h(t₀)=0인 시각을 주어 두 날의 위치가 같아진다.','The Intermediate Value Theorem gives a time t₀ with h(t₀)=0, so the positions on both days coincide.')],('두 날에 같은 시각·같은 산길 지점을 통과한다.','There is a path location reached at the same clock time on both days.'),('속도가 일정하거나 항상 단조로 움직인다는 가정은 필요 없고, 같은 길에서 위치가 연속이라는 조건만 썼다.','Constant speed or monotone motion is unnecessary; the proof only uses continuous position along the same path.'))
add(76,('(a)|x|가 모든 곳에서 연속임을 보이고, (b)연속 f의 |f|도 연속임을 증명하라. (c)|f|의 연속성이 f의 연속성을 함의하는지도 판단하라.','(a)Prove |x| is continuous everywhere. (b)Show that |f| is continuous whenever f is. (c)Determine whether continuity of |f| implies continuity of f.'),[(d(r'\big||x|-|a|\big|\le|x-a|\longrightarrow0'),d(r'\big||x|-|a|\big|\le|x-a|\longrightarrow0')),('(b)역삼각부등식 ||f(x)|−|f(a)||≤|f(x)−f(a)|→0이다.','(b)The reverse triangle inequality gives ||f(x)|−|f(a)||≤|f(x)−f(a)|→0.'),('(c)f(x)=−1(x<0),1(x≥0)이면 |f|=1은 연속이지만 f는 0에서 점프한다.','(c)Let f(x)=−1 for x<0 and 1 for x≥0. Then |f|=1 is continuous, but f jumps at zero.')],('(a),(b)참. (c)역은 거짓이며 위 계단함수가 반례이다.','(a),(b)True. (c)The converse is false; the step function is a counterexample.'),('반례는 f(0)까지 ±1로 지정하여 |f|이 0에서 구멍 없이 실제로 상수 1이 되도록 했다.','The counterexample assigns f(0) one of ±1, ensuring that |f| is truly constant 1 even at zero.'),list('abc'))
normalize_prose_inequalities(D)
D.save(76)
