"""General Exercises3.2; visually checked PDF262–263, including graph estimates."""
from early_helpers import Book
from pathlib import Path
import sympy as s,json,re
b=Book('3.2',[225,226]);x=s.symbols('x',positive=True);checks=[]
def m(t):return r'\('+t+r'\)'
def add(n,k,e,steps,ans,ae=None,parts=[]):
 b.add(n,225 if n<=26 else 226,('평균값 정리','The Mean Value Theorem'),(k,e),steps,(ans,ans if ae is None else ae),parts,check=('연속성·내부 미분가능성·끝점의 할선 기울기를 확인하고 c가 열린 구간 안에 있는지 확인한다. 그림에서 읽은 수치는 근삿값이다.','Check continuity, interior differentiability, the endpoint secant slope, and that c is interior. Graph readings are approximate.'));b.E[n]['conceptHref']='../../calc1/index.html'
def formula(t):return(m(t),m(t))
add(1,'그림의 f에 롤의 정리를 적용하여 f′(c)=0인 c를 추정하라.','Use Rolle’s theorem on the supplied graph to estimate where f′(c)=0.',[('곡선은 [0,8]에서 연속이고 내부에서 매끄러우며 f(0)=f(8)=3이다.','The curve is continuous on[0,8], smooth inside, and f(0)=f(8)=3.'),('골짜기와 봉우리의 수평접선을 읽으면 c≈1,5이다.','The horizontal tangents at the valley and peak give c≈1,5.')],m(r'c\approx1,5'))
add(2,'[0,8]에서 f(0)=f(8)=3이지만 어떤 곳에서도 도함수가 0이 아닌 함수의 예를 그리고 롤의 정리가 적용되지 않는 이유를 설명하라.','Sketch an example with f(0)=f(8)=3 on[0,8]but no zero derivative, and explain why Rolle’s theorem does not apply.',[formula(r'f(x)=|x-4|-1'),('양 끝값은 3이다. x<4에서는 기울기 −1, x>4에서는 1이며 x=4에서는 미분할 수 없다.','Both endpoint values are3. The slopes are−1 to the left of4 and1 to the right; the derivative does not exist at4.')],m(r'f(x)=|x-4|-1')+'; 내부 미분가능성 실패.',m(r'f(x)=|x-4|-1')+'; interior differentiability fails.')
add(3,'그림의 g에 대해 (a)[0,8]에서 평균값 정리의 가정을 확인하고, (b)[0,8], (c)[2,6]의 할선에 평행한 접선의 c를 추정하라.','For the supplied g graph,(a)check the MVT hypotheses on[0,8]; estimate c for secant-parallel tangents on(b)[0,8]and(c)[2,6].',[('(a)닫힌 구간에서 연속이고 열린 구간에서 매끄럽다.','(a)The curve is continuous on the closed interval and smooth in its interior.'),formula(r'(b)\quad {g(8)-g(0)\over8}={4-1\over8}={3\over8}'),('양의 기울기 3/8인 접선을 양쪽 증가 구간에서 찾으면 c≈2.2,6.4이다.','Tangents of positive slope3/8 occur on the two increasing portions, near c≈2.2,6.4.'),formula(r'(c)\quad {g(6)-g(2)\over4}\approx{1-3\over4}=-{1\over2}'),('감소 구간에서 기울기 −1/2인 접선은 c≈3.7,5.5이다.','On the decreasing portion the slope−1/2 occurs near c≈3.7,5.5.')],'(a)성립; (b)c≈2.2,6.4; (c)c≈3.7,5.5.','(a)Yes;(b)c≈2.2,6.4;(c)c≈3.7,5.5.',list('abc'))
add(4,'f(0)=1,f(8)=4인 연속함수 중 도함수가 평균 기울기 3/8을 갖지 않는 예를 그려라.','Sketch a continuous function with f(0)=1,f(8)=4 whose derivative never equals the average slope3/8.',[formula(r'f(x)=\begin{cases}1&0\le x\le4\\1+{3\over4}(x-4)&4<x\le8\end{cases}'),('두 조각은 x=4에서 만나 연속이다. 기울기는 0 또는 3/4이고 4에서는 미분 불가능하다.','The pieces meet continuously at4. Their slopes are0 and3/4; at4 the derivative is undefined.')],'위 꺾은선이 한 예이며 x=4의 모서리가 평균값 정리의 가정을 위반한다.','The displayed polygonal curve is an example; its corner at4 violates the MVT hypothesis.')
for n,k,e in [(5,'아니오. 내부의 꺾인 점 x≈3에서 좌우 기울기가 달라 미분할 수 없다.','No. At the interior corner x≈3, unequal one-sided slopes prevent differentiability.'),(6,'예. 연속이며 내부에서 미분 가능하다. 양 끝값이 같아 평균 기울기는 0이고 수평접선은 c≈1,3이다.','Yes. The curve is continuous and differentiable inside. Equal endpoint heights give average slope0, attained near c≈1,3.'),(7,'예. 내부에서는 매끄럽다. 끝점의 수직접선은 가정을 위반하지 않는다. 평균 기울기 (3−1)/5=0.4인 접선을 읽으면 c≈3.8이다.','Yes. The interior is smooth; a vertical tangent at an endpoint does not violate the hypotheses. A tangent with average slope(3−1)/5=0.4 occurs near c≈3.8.'),(8,'아니오. x≈4의 뾰족한 점에서 유한한 도함수가 존재하지 않는다.','No. At the cusp near x≈4 a finite derivative does not exist.')]:
 add(n,'주어진 [0,5] 그래프가 평균값 정리의 가정을 만족하는지 판단하고, 가능하면 c를 추정하라.','Decide whether the supplied graph on[0,5]satisfies the MVT hypotheses and estimate c when it does.',[(k,e)],k,e)
# Exact Rolle/MVT computations, checking every returned interior value.
data=[(9,2*x*x-4*x+5,-1,3,[1],'Rolle'),(10,x**3-2*x*x-4*x+2,-2,2,[-s.Rational(2,3)],'Rolle'),(11,s.sin(x/2),s.pi/2,3*s.pi/2,[s.pi],'Rolle'),(12,x+1/x,s.Rational(1,2),2,[1],'Rolle'),(15,2*x*x-3*x+1,0,2,[1],'MVT'),(16,x**3-3*x+2,-2,2,[-2/s.sqrt(3),2/s.sqrt(3)],'MVT'),(17,x**s.Rational(1,3),0,1,[1/(3*s.sqrt(3))],'MVT'),(18,1/x,1,3,[s.sqrt(3)],'MVT'),(19,s.sqrt(x),0,4,[1],'MVT'),(20,x**3-2*x,-2,2,[-2/s.sqrt(3),2/s.sqrt(3)],'MVT')]
for n,f,a,z,cs,kind in data:
 slope=s.simplify((f.subs(x,z)-f.subs(x,a))/(z-a));df=s.diff(f,x)
 for c in cs:
  assert float(c)>float(a) and float(c)<float(z);assert s.simplify(df.subs(x,c)-slope)==0;checks.append(f'{n}: derivative at {c}')
 if kind=='Rolle':assert slope==0;checks.append(f'{n}: equal endpoints')
 intro='롤의 정리'if kind=='Rolle'else'평균값 정리'
 stmt=m('f(x)='+s.latex(f))+', '+m('['+s.latex(a)+','+s.latex(z)+']')
 steps=[('함수는 주어진 닫힌 구간에서 연속이고 내부에서 미분 가능하다.','The function is continuous on the given closed interval and differentiable in its interior.'),formula(r'{f(b)-f(a)\over b-a}='+s.latex(slope)),formula(r'f^{\prime}(x)='+s.latex(df)),('도함수를 평균 기울기와 같게 놓고 열린 구간에 속하는 해만 남긴다.','Set the derivative equal to the average slope and keep only interior solutions.')]
 if n==10:steps.append(('또 다른 해 x=2는 끝점이므로 제외한다.','The other algebraic solution x=2 is an endpoint and must be excluded.'))
 if n in [17,19]:steps.append(('x=0에서 미분 불가능해도 끝점이므로 정리를 적용할 수 있다.','Failure of differentiability at the endpoint0 does not prevent application of the theorem.'))
 if n==19:steps.append(formula(r'\text{secant: }y=x/2,\qquad\text{tangent: }y=x/2+1/2'))
 if n==20:steps.append(formula(r'\text{secant: }y=2x,\qquad\text{tangents: }y=2x\pm{16\over3\sqrt3}'))
 answer=m('c='+','.join(s.latex(c)for c in cs))
 if n in [19,20]:answer+='; 접선과 할선은 평행하다.';ae=m('c='+','.join(s.latex(c)for c in cs))+'; tangent(s)and secant are parallel.'
 else:ae=answer
 add(n,stmt+'에서 '+intro+'의 가정을 확인하고 가능한 모든 c를 구하라.'+(' 접선과 할선도 그려 비교하라.'if n in[19,20]else''),'Verify the hypotheses of '+kind+' for '+stmt+' and find every valid c.'+(' Graph the secant and corresponding tangent(s).'if n in[19,20]else''),steps,answer,ae)
add(13,m(r'f(x)=1-x^{2/3}')+'의 f(−1)=f(1)을 확인하고, 내부에 f′=0인 점이 없어도 롤의 정리와 모순되지 않는 이유를 설명하라.','Verify equal endpoint values for '+m(r'f(x)=1-x^{2/3}')+' on[−1,1]and explain why the absence of a zero derivative does not contradict Rolle’s theorem.',[formula(r'f(-1)=f(1)=0,\qquad f^{\prime}(x)=-{2\over3\sqrt[3]x}\quad(x\ne0)'),('x=0에서 도함수가 존재하지 않아 내부 미분가능성 가정이 실패한다.','The derivative does not exist at0, so interior differentiability fails.')],'0에서 미분 불가능하므로 롤의 정리가 적용되지 않는다.','Rolle’s theorem does not apply because f is not differentiable at0.')
add(14,m(r'f(x)=\tan x')+'의 [0,π] 끝값과 도함수를 살펴 롤의 정리를 적용할 수 없는 이유를 설명하라.','Examine endpoint values and the derivative of tan x on[0,π]and explain the failure of Rolle’s theorem.',[formula(r'f(0)=f(\pi)=0,\qquad f^{\prime}(x)=\sec^2x>0'),('π/2에서 함수가 정의되지 않으므로 닫힌 구간에서 연속이 아니다.','The function is undefined atπ/2 and therefore is not continuous on the closed interval.')],'π/2에서 불연속이므로 정리의 가정이 실패한다.','Continuity fails atπ/2.')
add(21,m(r'f(x)=(x-3)^{-2}')+'에 대해 [1,4]의 평균 기울기와 같은 도함수를 갖는 내부 c가 없음을 보이고 이유를 설명하라.','For '+m(r'f(x)=(x-3)^{-2}')+' on[1,4], show there is no interior c with derivative equal to the secant slope, and explain.',[formula(r'{f(4)-f(1)\over3}={1\over4},\qquad {-2\over(c-3)^3}={1\over4}\Longrightarrow c=1'),('유일한 대수적 해는 끝점이다. x=3에서 함수가 정의되지 않아 평균값 정리의 연속성 가정이 성립하지 않는다.','The only algebraic solution is an endpoint. The function is undefined at3, violating continuity.')],'내부 해 없음; x=3의 불연속.','No interior solution; discontinuity at3.')
add(22,m(r'f(x)=2-|2x-1|')+'에 대해 [0,3]의 평균 기울기와 같은 도함수가 없음을 설명하라.','Explain why '+m(r'f(x)=2-|2x-1|')+' has no derivative equal to its secant slope on[0,3].',[formula(r'{f(3)-f(0)\over3}={-3-1\over3}=-{4\over3}'),('도함수는 x<1/2에서 2, x>1/2에서 −2이고 1/2에서는 존재하지 않는다.','The derivative equals2 for x<1/2 and−2 for x>1/2, and is undefined at1/2.')],'c 없음; x=1/2에서 미분 불가능.','No such c; differentiability fails at1/2.')
for n,F,br,df in [(23,r'2x+\cos x',r'F(-1)=-2+\cos1<0<F(0)=1',r'F^{\prime}(x)=2-\sin x\ge1'),(24,r'2x-1-\sin x',r'F(0)=-1<0<F(1)=1-\sin1',r'F^{\prime}(x)=2-\cos x\ge1')]:
 add(n,m(F+'=0')+'의 실근이 정확히 하나임을 증명하라.','Prove that '+m(F+'=0')+' has exactly one real root.',[('좌변을 F라고 하면 연속이다.','Let F denote the continuous left side.'),formula(br),('중간값 정리로 적어도 한 근이 존재한다.','The intermediate value theorem supplies at least one root.'),formula(df),('평균값 정리에 의해 엄격히 증가하므로 서로 다른 두 근을 가질 수 없다.','The MVT makes F strictly increasing, so two distinct roots are impossible.')],'실근은 정확히 하나.','Exactly one real root.')
add(25,m(r'x^3-15x+c=0')+'가 [−2,2]에서 많아야 하나의 근을 갖는 이유를 증명하라.','Prove that '+m(r'x^3-15x+c=0')+' has at most one root in[−2,2].',[formula(r'F^{\prime}(x)=3x^2-15\le-3<0\quad(-2\le x\le2)'),('두 근이 있다면 롤의 정리에 의해 그 사이에서 F′=0이어야 하므로 모순이다.','Two roots would force a zero of F′ between them by Rolle’s theorem, a contradiction.')],'모든 상수 c에 대해 많아야 한 근.','At most one root for any constant c.')
add(26,m(r'x^4+4x+c=0')+'의 실근이 많아야 두 개임을 증명하라.','Prove that '+m(r'x^4+4x+c=0')+' has at most two real roots.',[formula(r'F^{\prime}(x)=4(x^3+1)=0\iff x=-1'),('서로 다른 세 근이 있다면 두 인접 구간에 각각 도함수의 근이 생겨, 도함수의 유일한 근과 모순이다.','Three distinct roots would force derivative zeros in two disjoint intervening intervals, contradicting the unique derivative zero.')],'서로 다른 실근은 많아야 두 개.','At most two distinct real roots.')
add(27,'삼차다항식의 서로 다른 실근이 많아야 세 개임을 롤의 정리로 증명하고 일반화하라.','Use Rolle’s theorem to bound the number of distinct real roots of a cubic and generalize.', [('서로 다른 네 근을 가정하면 1계, 2계, 3계 도함수에 각각 적어도 3,2,1개의 근이 생긴다.','Four distinct roots would give at least3,2,1 roots in the first, second and third derivatives.'),('그러나 삼차식의 3계 도함수는 0이 아닌 상수이다. 같은 논리로 차수 n인 다항식의 n계 도함수는 0이 아닌 상수이므로 서로 다른 근은 n개 이하이다.','The third derivative of a cubic is a nonzero constant. More generally the nth derivative of a degree n polynomial is nonzero constant, bounding its distinct roots by n.')],'차수 n의 0이 아닌 다항식은 서로 다른 실근을 n개 이하로 갖는다.','A nonzero degree n polynomial has at most n distinct real roots.')
add(28,'롤의 정리를 사용하여 (a)f의 두 근 사이에 f′의 근, (b)f의 세 근 사이에 f″의 근이 있음을 보이고 (c)일반화하라.','Use Rolle’s theorem to show(a)two zeros of f force a zero of f′,(b)three zeros force a zero of f″,and(c)generalize.', [('(a)두 근을 끝점으로 하는 구간에 롤의 정리를 적용한다.','(a)Apply Rolle’s theorem on the interval between the two zeros.'),('(b)세 근 사이 두 구간에 f′의 서로 다른 두 근이 생기고, 그 두 근 사이에 다시 롤의 정리를 적용한다.','(b)The two intervening intervals give distinct zeros of f′; apply Rolle’s theorem again between those zeros.'),('(c)필요한 차수까지 미분 가능하면, f의 n개의 서로 다른 근은 k계 도함수의 적어도 n−k개의 서로 다른 근을 강제한다 (k<n). 특히 n+1개의 근은 n계 도함수의 근을 하나 이상 강제한다.','(c)With the required differentiability, n distinct zeros force at least n−k distinct zeros of the kth derivative for k<n. In particular,n+1 zeros force a zero of the nth derivative.')],'롤의 정리를 반복 적용한다.','Iterate Rolle’s theorem.',list('abc'))
add(29,'f(1)=10이고 [1,4]에서 f′≥2일 때 f(4)의 가능한 최솟값을 구하라.','Given f(1)=10 and f′≥2 on[1,4],find the smallest possible f(4).',[formula(r'f(4)-10=3f^{\prime}(c)\ge6'),('f(x)=2x+8이면 가정을 만족하면서 f(4)=16을 달성한다.','The function f(x)=2x+8 satisfies the assumptions and attains f(4)=16.')],m('16'))
add(30,'모든 x에서 3≤f′(x)≤5라면 f(8)−f(2)의 범위를 증명하라.','If 3≤f′(x)≤5 for every x,prove bounds for f(8)−f(2).',[formula(r'f(8)-f(2)=6f^{\prime}(c),\quad2<c<8'),('도함수의 양쪽 부등식에 양수 6을 곱한다.','Multiply both derivative bounds by the positive number6.')],m(r'18\le f(8)-f(2)\le30'))
add(31,'f(0)=−1,f(2)=4이고 모든 x에서 f′(x)≤2인 함수가 존재하는가?','Can f(0)=−1,f(2)=4 and f′(x)≤2 everywhere hold simultaneously?',[formula(r'f^{\prime}(c)={4-(-1)\over2}={5\over2}>2'),('평균값 정리의 결론이 도함수의 상한과 모순이다.','The MVT conclusion contradicts the derivative bound.')],'존재하지 않는다.','No such function exists.')
add(32,'f,g가 [a,b]에서 연속이고 내부에서 미분 가능하며 f(a)=g(a),f′<g′일 때 f(b)<g(b)를 증명하라.','Suppose f,g are continuous on[a,b],differentiable inside,f(a)=g(a),and f′<g′.Prove f(b)<g(b).',[formula(r'h=f-g,\quad h(a)=0,\quad h^{\prime}<0'),formula(r'h(b)-h(a)=h^{\prime}(c)(b-a)<0'),('따라서 f(b)−g(b)<0이다.','Therefore f(b)−g(b)<0.')],m(r'f(b)<g(b)'))
add(33,'0<x<2π이면 sin x<x임을 평균값 정리로 증명하라.','Use the MVT to prove sin x<x for0<x<2π.',[formula(r'\sin x-\sin0=x\cos c,\quad0<c<x<2\pi'),('0<c<2π에서는 cos c<1이고 x>0이므로 부등호가 엄격하다.','For0<c<2π,cos c<1; multiplying by x>0 preserves strictness.')],m(r'\sin x=x\cos c<x'))
add(34,'미분 가능한 홀함수 f와 b>0에 대해 f′(c)=f(b)/b인 c∈(−b,b)가 있음을 증명하라.','For a differentiable odd function f and b>0,prove some c∈(−b,b)satisfies f′(c)=f(b)/b.',[('홀함수이므로 f(−b)=−f(b)이다. [−b,b]에 평균값 정리를 적용한다.','Oddness gives f(−b)=−f(b). Apply the MVT on[−b,b].'),formula(r'f^{\prime}(c)={f(b)-f(-b)\over2b}={f(b)\over b}')],m(r'\exists c\in(-b,b):\ f^{\prime}(c)=f(b)/b'))
add(35,'모든 실수 a,b에 대해 |sin a−sin b|≤|a−b|를 증명하라.','Prove |sin a−sin b|≤|a−b| for all real a,b.', [('a=b이면 두 변 모두 0이다. 서로 다르면 두 수 사이에 평균값 정리를 적용한다.','If a=b both sides vanish. Otherwise apply the MVT between them.'),formula(r'|\sin a-\sin b|=|\cos c|\,|a-b|\le|a-b|')],m(r'|\sin a-\sin b|\le|a-b|'))
add(36,'구간에서 f′(x)=c가 상수이면 f(x)=cx+d임을 증명하라.','Prove that a function with constant derivative c on an interval has the form f(x)=cx+d.',[formula(r'h(x)=f(x)-cx,\qquad h^{\prime}(x)=0'),('구간의 임의의 두 점 사이에 평균값 정리를 적용하면 h의 값이 같으므로 h=d이다.','The MVT between arbitrary points of the interval shows equal h values; hence h=d.')],m('f(x)=cx+d'))
add(37,m(r'f(x)=1/x,\quad g(x)=\begin{cases}1/x&x>0\\1+1/x&x<0\end{cases}')+'의 도함수를 비교하고 f−g가 상수인지 판단하라.','Compare derivatives of '+m(r'f(x)=1/x,\quad g(x)=\begin{cases}1/x&x>0\\1+1/x&x<0\end{cases}')+' and determine whether f−g is constant.',[formula(r'f^{\prime}(x)=g^{\prime}(x)=-1/x^2\quad(x\ne0)'),formula(r'f(x)-g(x)=\begin{cases}0&x>0\\-1&x<0\end{cases}'),('정의역은 하나의 구간이 아니다. 각 연결된 구간에서는 차가 상수이지만 전체에 공통된 상수는 없다.','The domain is not one interval. The difference is constant on each component but not globally.')],'도함수는 같지만 f−g는 전체 정의역에서 상수가 아니다.','The derivatives agree,but f−g is not constant over the whole domain.')
add(38,'오후 2시에 속력이 30mi/h, 2시10분에 50mi/h인 자동차가 그 사이에 가속도 120mi/h²를 갖는 순간이 있음을 보여라.','A car’s speed changes from30mi/h at2:00to50mi/h at2:10. Show it has acceleration120mi/h² at some intermediate time.', [('시간을 시 단위로 재고 미분 가능한 속력 모형에 평균값 정리를 적용한다.','Measure time in hours and apply the MVT to the differentiable speed model.'),formula(r'v^{\prime}(c)={50-30\over10/60}=120\ \mathrm{mi/h^2}'),('이는 속력의 변화율이며 직선 진행 모형에서 진행 방향의 가속도이다.','This is the rate of change of speed,or the along-track acceleration in the straight-line model.')],m(r'120\ \mathrm{mi/h^2}'))
add(39,'동시에 출발하여 동시에 결승선을 통과한 두 주자가 중간 어느 순간 같은 속력을 가짐을 증명하라.','Prove that two runners starting together and finishing tied have equal speeds at some intermediate instant.', [('진행 방향 위치를 g(t),h(t)라 하고 연속·미분 가능한 경주 모형을 사용한다. 차 F=g−h의 시작값과 끝값은 모두 0이다.','Use continuous,differentiable along-track positions g(t),h(t).Their difference F=g−h has value0 at both start and finish.'),formula(r'F^{\prime}(c)=0\Longrightarrow g^{\prime}(c)=h^{\prime}(c)'),('롤의 정리로 얻은 같은 순간의 진행 속도가 같으므로 속력도 같다.','Rolle’s theorem gives equal along-track velocities at the same instant,hence equal speeds.')],'롤의 정리로 같은 속력의 순간이 존재한다.','Rolle’s theorem guarantees such an instant.')
add(40,'모든 실수에서 f′(x)≠1이면 f의 고정점 f(a)=a가 많아야 하나임을 증명하라.','Prove that if f′(x)≠1 for every real x,then f has at most one fixed point.',[formula(r'h(x)=f(x)-x,\qquad h^{\prime}(x)=f^{\prime}(x)-1\ne0'),('고정점이 서로 다른 두 개라면 h의 두 근 사이에 롤의 정리를 적용하여 h′=0을 얻으므로 모순이다. 존재 자체를 주장하는 결론은 아니다.','Two distinct fixed points would be two zeros of h.Rolle’s theorem would then force h′=0 between them,a contradiction.This does not assert existence.')],'고정점은 많아야 하나.','At most one fixed point.')
def norm(v):
 if isinstance(v,str):
  chunks=re.split(r'(\\\(.*?\\\)|\\\[.*?\\\])',v,flags=re.S)
  return ''.join(z if i%2 else z.replace('<',r'\(\lt\)') for i,z in enumerate(chunks))
 if isinstance(v,list):return[norm(z)for z in v]
 if isinstance(v,dict):return{k:norm(z)for k,z in v.items()}
 return v
assert sorted(b.E)==list(range(1,41));b.E=norm(b.E);b.save()
Path(__file__).with_name('s3-2-report.json').write_text(json.dumps({'section':'3.2','exercises':40,'exactChecks':checks,'sourcePdfPages':[262,263],'graphReadings':'1:1,5;3:2.2,6.4 and3.7,5.5;7:3.8; compared visually and Appendix.'},indent=2)+'\n')
print('3.2:',len(b.E),'exercises;',len(checks),'exact checks')
