from calc1_core import *
import mpmath as mp
mp.mp.dps=50
D=CalcDoc('1.7',[81,82],lambda n:81 if n<=9 else 82)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('ε–δ 정의와 엄밀한 극한 증명','Epsilon–delta definitions and rigorous limit proofs'),st,('출력 오차를 입력 거리로 제어하고, 선택한 δ가 모든 해당 입력에 적용됨을 보인다.','Control output error by input distance and show that the chosen delta works for every eligible input.'),steps,ans,check,parts)
def bandfig(n,fn,a,L,eps,delta,width=None):
 w=width or delta*1.6
 curves=[samples(fn,a-w,a+w),[(a-w,L-eps),(a+w,L-eps)],[(a-w,L+eps),(a+w,L+eps)],[(a-delta,L-1.6*eps),(a-delta,L+1.6*eps)],[(a+delta,L-1.6*eps),(a+delta,L+1.6*eps)]]
 return panel(f'epsilon={eps:g}; delta={delta:.6g}',(a-w,a+w,L-1.6*eps,L+1.6*eps),curves,[(a,L)],xticks=[a-delta,a,a+delta],yticks=[L-eps,L,L+eps])
for n,a,L,lo,hi,eps in [(1,1,1,.7,1.1,.2),(2,3,2,2.6,3.8,.5)]:
 de=min(a-lo,hi-a)
 add(n,(f'원본 그래프는 {lo}<x<{hi}에서 {L-eps}<f(x)<{L+eps}임을 보여 준다'+(' (x=3은 제외). 'if n==2 else'. ')+f'|x−{a}|<δ'+('이고 x≠3일 때 'if n==2 else'이면 ')+f'|f(x)−{L}|<{eps}가 되는 δ를 구하라.',f'The source graph places f(x) between {L-eps} and {L+eps} when {lo}<x<{hi}'+(' except at x=3. 'if n==2 else'. ')+f'Find δ ensuring |f(x)−{L}|<{eps} whenever |x−{a}|<δ'+(' and x≠3.'if n==2 else'.')),[('중심에서 두 입력 경계까지의 거리 중 작은 값을 고른다.','Choose the smaller distance from the center to the two input boundaries.'),(d(r'\delta=\min\{'+f'{a}-{lo},{hi}-{a}'+r'\}='+f'{de:.1f}'),d(r'\delta=\min\{'+f'{a}-{lo},{hi}-{a}'+r'\}='+f'{de:.1f}'))],d(r'\delta='+f'{de:.1f}'),('이 대칭 구간은 그래프가 허용한 입력 구간에 완전히 포함된다. 2번의 중심점 지정값은 뚫린 근방 조건으로 제외된다.','The symmetric interval lies entirely inside the graph’s permitted input interval. In problem 2 the assigned central value is excluded by the punctured-neighborhood condition.'))
for n,fn,a,L,eps,lo,hi,form in [(3,math.sqrt,4,2,.4,1.6**2,2.4**2,r'\sqrt x'),(4,lambda x:x*x,1,1,.5,math.sqrt(.5),math.sqrt(1.5),r'x^2'),(5,lambda x:math.sqrt(x*x+5),2,3,.3,math.sqrt(2.7**2-5),math.sqrt(3.3**2-5),r'\sqrt{x^2+5}'),(6,lambda x:math.cos(x)**2,math.pi/6,.75,.1,math.acos(math.sqrt(.85)),math.acos(math.sqrt(.65)),r'\cos^2 x')]:
 de=min(a-lo,hi-a)
 center=r'\pi/6'if n==6 else str(a)
 add(n,('그래프를 이용해 '+m('|x-'+center+r'|<\delta\Longrightarrow|'+form+'-'+str(L)+'|<'+str(eps))+'를 보장하는 δ를 찾으라.','Use a graph to choose δ guaranteeing '+m('|x-'+center+r'|<\delta\Longrightarrow|'+form+'-'+str(L)+'|<'+str(eps))+'.'),[(f'중심 a={a:.10f}를 포함한 허용 입력 구간 (x₋,x₊)은 ({lo:.10f},{hi:.10f})이다.',f'For center a={a:.10f}, the permitted interval (x₋,x₊) is ({lo:.10f},{hi:.10f}).'),('두 경계는 출력 '+f'{L-eps:g}, {L+eps:g}'+'를 함수식에 대입하여 역으로 구한다. 가까운 경계까지의 거리를 δ로 택한다.','Find the boundaries by solving for outputs '+f'{L-eps:g}, {L+eps:g}'+', then choose the distance to the nearer boundary.')],d(r'\delta=\min\{a-x_-,x_+-a\}\approx'+f'{de:.10f}'),('표시한 소수는 정확한 경계 거리의 근삿값이다. 실제 사용할 때에는 그보다 조금 작은 값(예: '+f'{math.floor(de*1000)/1000:.3f}'+')도 안전하다.','The decimal approximates the exact boundary distance. A slightly smaller value, such as '+f'{math.floor(de*1000)/1000:.3f}'+', is also safe.'))
 D.fig(n,[bandfig(n,fn,a,L,eps,de,width=min(de*1.3,a*.9)if n==3 else None)])
for n,fn,a,L,epss in [(7,lambda z:z**3-3*z+4,2,6,[.2,.1]),(8,lambda z:(4*z+1)/(3*z-4),2,4.5,[.5,.1])]:
 ss=[];ans=[];panels=[]
 for eps in epss:
  roots=sorted(float(mp.findroot(lambda z:fn(z)-(L+sign*eps),(a-.01,a+.01)))for sign in [-1,1]);de=min(a-roots[0],roots[1]-a);safe=math.floor(de*1000000)/1000000
  ss.append((f'ε={eps}: 출력 경계의 교점 x≈{roots[0]:.10f},{roots[1]:.10f}; 가까운 거리≈{de:.10f}이므로 δ={safe:.6f}를 택한다.',f'ε={eps}: the output boundaries intersect at x≈{roots[0]:.10f},{roots[1]:.10f}. The nearer distance is ≈{de:.10f}; choose δ={safe:.6f}.'))
  ans.append(f'ε={eps} → δ={safe:.6f}');panels.append(bandfig(n,fn,a,L,eps,safe))
 add(n,('극한 '+m(r'\lim_{x\to2}'+(r'(x^3-3x+4)=6'if n==7 else r'\frac{4x+1}{3x-4}=4.5'))+'에서 ε='+','.join(map(str,epss))+'에 대응하는 δ를 그래프로 구하라.','For '+m(r'\lim_{x\to2}'+(r'(x^3-3x+4)=6'if n==7 else r'\frac{4x+1}{3x-4}=4.5'))+', use graphs to find δ for ε='+','.join(map(str,epss))+'.'),ss,('; '.join(ans),'; '.join(ans)),('각 선택 구간에서 함수가 단조임을 확인했다. δ는 계산된 최대 거리보다 작게 내려 반올림하여 출력 부등식이 유지된다.','Verified monotonicity on each chosen interval. The selected deltas are rounded downward from the limiting distances, preserving the strict output bounds.'))
 D.fig(n,panels)
add(9,('(a)4<x<4+δ이면 (x²+4)/√(x−4)>100이 되도록 그래프에서 δ를 정하고 (b)이 결과가 시사하는 극한을 쓰라.','(a)Use a graph to choose δ so that 4<x<4+δ implies (x²+4)/√(x−4)>100. (b)State the suggested limit.'),[('δ=0.04로 택하면 x²+4>20이고 √(x−4)<0.2이므로 비는 100보다 크다.','Choose δ=0.04. Then x²+4>20 and √(x−4)<0.2, so the quotient exceeds 100.'),('일반 M>0에도 δ=(20/M)²로 같은 부등식을 적용할 수 있다.','For any M>0, the same argument works with δ=(20/M)².')],d(r'\text{(a) }\delta=0.04;\qquad\text{(b) }\lim_{x\to4^+}\frac{x^2+4}{\sqrt{x-4}}=+\infty'),('그래프의 한 기준선 통과만으로 무한극한을 증명하지 않고, 임의 M에 대한 δ도 제시했다.','Beyond crossing a single graph threshold, the argument supplies a delta for every M, establishing the infinite limit.'),list('ab'))
D.fig(9,[panel('Right-hand blowup and threshold 100',(4,4.08,50,250),[samples(lambda z:(z*z+4)/math.sqrt(z-4),4.0001,4.08),[(4,100),(4.08,100)],[(4.04,50),(4.04,250)]],xticks=[4,4.04,4.08],yticks=[100,150,200])])
Ds=[math.asin(1/math.sqrt(M))for M in [500,1000]]
add(10,('lim(x→π)csc²x=∞에 대해 (a)M=500, (b)M=1000에 해당하는 δ를 구해 정의를 설명하라.','Illustrate lim(x→π)csc²x=∞ by finding δ for (a)M=500 and (b)M=1000.'),[('u=|x−π|라 놓으면 sin²x=sin²u이다. 0<u<arcsin(1/√M)<π/2에서 sin²u<1/M이다.','Set u=|x−π|, so sin²x=sin²u. For 0<u<arcsin(1/√M)<π/2, sin²u<1/M.'),('따라서 csc²x>M이다.','Therefore csc²x>M.')],d(r'\delta=\arcsin(1/\sqrt M)')+f'; (a){Ds[0]:.10f}, (b){Ds[1]:.10f}',('양쪽에서 제곱 사인을 사용하므로 부호 문제가 없고, 선택 경계에서는 csc²x=M으로 정확히 일치한다.','Squaring sine handles both sides without a sign issue; at the selected boundary csc²x equals M exactly.'),list('ab'))
# Two explicit threshold lines for the same curve.
D.fig(10,[panel('csc squared near pi',(math.pi-.07,math.pi+.07,0,1500),[samples(lambda z:1/math.sin(z)**2,math.pi-.07,math.pi-.0001),samples(lambda z:1/math.sin(z)**2,math.pi+.0001,math.pi+.07),[(math.pi-.07,500),(math.pi+.07,500)],[(math.pi-.07,1000),(math.pi+.07,1000)]],yticks=[0,500,1000,1500])])
r0=math.sqrt(1000/math.pi);rlo=math.sqrt(995/math.pi);rhi=math.sqrt(1005/math.pi);dr=rhi-r0
add(11,('반지름을 조절해 넓이 1000 cm²인 원판을 만든다. (a)이상적 반지름, (b)넓이 오차 ±5 cm²를 허용하는 반지름 범위·대칭 허용오차, (c)ε–δ 정의의 변수와 상수를 대응시켜라.','A circular disk is to have area 1000 cm². Find (a)the ideal radius, (b)the radius interval and symmetric tolerance for an area tolerance of ±5 cm², and (c)the corresponding variables and constants in the epsilon–delta definition.'),[(d(r'a=\sqrt{1000/\pi},\quad\sqrt{995/\pi}\le r\le\sqrt{1005/\pi}'),d(r'a=\sqrt{1000/\pi},\quad\sqrt{995/\pi}\le r\le\sqrt{1005/\pi}')),('대칭 허용오차는 두 끝점까지 거리 중 작은 쪽인 오른쪽 거리이다.','The symmetric tolerance is the smaller endpoint distance, which is the right-hand distance.')],(f'(a){r0:.8f} cm. (b)[{rlo:.8f},{rhi:.8f}] cm; δ=√(1005/π)−√(1000/π)≈{dr:.8f} cm. (c)x=r, f(x)=πx², a=√(1000/π), L=1000, ε=5.',f'(a){r0:.8f} cm. (b)[{rlo:.8f},{rhi:.8f}] cm; δ=√(1005/π)−√(1000/π)≈{dr:.8f} cm. (c)x=r, f(x)=πx², a=√(1000/π), L=1000, ε=5.'),('제조 허용범위는 끝점을 포함한다. 극한 정의의 엄격한 오차 <5에는 |r−a|<δ를 사용한다.','The manufacturing tolerance interval includes its endpoints. For the strict error <5 in the limit definition, use |r−a|<δ.'),list('abc'))
T=lambda w:.1*w*w+2.155*w+20
inv=lambda temp:(-2.155+math.sqrt(2.155**2+.4*(temp-20)))/.2
w0=inv(200);wlo=inv(199);whi=inv(201);dw=min(w0-wlo,whi-w0)
add(12,('온도 모형 T(w)=0.1w²+2.155w+20(°C), 입력 w≥0(W)이다. (a)200°C의 입력, (b)온도 199–201°C에 해당하는 입력 범위, (c)ε–δ 변수와 대칭 δ를 구하라.','The temperature model is T(w)=0.1w²+2.155w+20 °C for input power w≥0 W. Find (a)the input for 200°C, (b)the input range for 199–201°C, and (c)the epsilon–delta quantities and a symmetric delta.'),[('이차방정식의 음수 해는 입력 조건에서 제외하고 다음 역함수를 쓴다.','Discard the negative quadratic root because power is nonnegative, giving this inverse:'),(d(r'w(T)=\frac{-2.155+\sqrt{2.155^2+0.4(T-20)}}{0.2}'),d(r'w(T)=\frac{-2.155+\sqrt{2.155^2+0.4(T-20)}}{0.2}')),('w≥0에서 T′(w)=0.2w+2.155>0이므로 끝 온도에 대응하는 입력들이 전체 허용범위를 정한다.','For w≥0, T′(w)=0.2w+2.155>0, so the endpoint temperatures determine the whole allowed power interval.')],(f'(a){w0:.8f} W; (b)[{wlo:.8f},{whi:.8f}] W; (c)x=w,f(x)=T(x),a={w0:.8f},L=200,ε=1,δ≈{dw:.8f} W.',f'(a){w0:.8f} W; (b)[{wlo:.8f},{whi:.8f}] W; (c)x=w,f(x)=T(x),a={w0:.8f},L=200,ε=1,δ≈{dw:.8f} W.'),('세 입력을 원래 이차식에 대입해 199,200,201°C를 확인했다. 엄격한 ε–δ 조건에서는 입력 오차를 δ 미만으로 잡는다.','Substituted the three inputs into the original quadratic to recover 199,200,201°C. For the strict epsilon–delta statement, keep input error below delta.'),list('abc'))
D.fig(12,[bandfig(12,T,w0,200,1,dw)])
for n,slope,epss,a,L in [(13,4,[.1,.01],2,0),(14,5,[.1,.05,.01],2,3)]:
 fstr='4x−8'if n==13 else'5x−7'
 ans='; '.join(f'ε={e:g} → δ={e/abs(slope):g}'for e in epss)
 add(n,(f'|x−{a}|<δ이면 |{fstr}−({L})|<ε가 되도록 ε='+','.join(map(str,epss))+'에 대한 δ를 구하라.',f'Find δ ensuring |{fstr}−({L})|<ε whenever |x−{a}|<δ, for ε='+','.join(map(str,epss))+'.'),[(d(r'|f(x)-L|='+str(abs(slope))+r'|x-'+str(a)+r'|<'+str(abs(slope))+r'\delta'),d(r'|f(x)-L|='+str(abs(slope))+r'|x-'+str(a)+r'|<'+str(abs(slope))+r'\delta')),('따라서 δ=ε/'+str(abs(slope))+'로 선택한다.','Thus choose δ=ε/'+str(abs(slope))+'.')],(ans,ans),('선형식에서는 출력 오차가 입력 오차의 정확한 상수배이므로 이 δ는 최대 대칭 반경이다.','For a linear function the output error is exactly a constant multiple of the input error, making this delta the largest symmetric radius.'),list('ab')if n==13 else())
# Full epsilon-delta arguments for linear functions and cancelled rational forms.
linear=[(15,s.Rational(1,2),-1,4,1),(16,-3,2,2,-4),(17,-2,1,-2,5),(18,2,-5,1,-3),(19,-s.Rational(1,3),1,9,-2),(20,s.Rational(3,2),-s.Rational(1,2),5,7),(21,1,2,4,6),(22,-2,3,-s.Rational(3,2),6)]
x=s.symbols('x',real=True)
for n,b,c,a,L in linear:
 f=b*x+c;src=tex(f)
 if n==21:src=r'\frac{x^2-2x-8}{x-4}'
 if n==22:src=r'\frac{9-4x^2}{3+2x}'
 steps=[]
 if n in [21,22]:steps.append(('접근점 이외에서 원식은 '+m(tex(f))+'로 약분된다.','Away from the approach point, the original expression cancels to '+m(tex(f))+'.'))
 steps += [('임의의 ε>0에 대해 '+m(r'\delta=\varepsilon/'+tex(abs(b)))+'를 선택한다.','For any ε>0 choose '+m(r'\delta=\varepsilon/'+tex(abs(b)))+'.'),(d(r'0<|x-'+tex(a)+r'|<\delta\Longrightarrow|f(x)-'+tex(L)+'|='+tex(abs(b))+r'|x-'+tex(a)+r'|<'+tex(abs(b))+r'\delta=\varepsilon'),d(r'0<|x-'+tex(a)+r'|<\delta\Longrightarrow|f(x)-'+tex(L)+'|='+tex(abs(b))+r'|x-'+tex(a)+r'|<'+tex(abs(b))+r'\delta=\varepsilon'))]
 add(n,('ε–δ 정의로 '+d(r'\lim_{x\to'+tex(a)+'}'+src+'='+tex(L))+'을 증명하라.'+(' 도해도 제시하라.'if n<=18 else''),'Prove '+d(r'\lim_{x\to'+tex(a)+'}'+src+'='+tex(L))+' by the epsilon–delta definition.'+(' Include a diagram.'if n<=18 else'')),steps,d(r'\delta='+tex(1/abs(b))+r'\varepsilon\text{ works for every }\varepsilon>0'),('이 선택은 x에 의존하지 않으며 모든 뚫린 입력 구간에서 요구된 엄격한 출력 부등식을 준다.','The choice is independent of x and yields the required strict output inequality throughout the punctured input interval.'))
 if n<=18:D.fig(n,[bandfig(n,lambda z:float(b)*z+float(c),float(a),float(L),.5,.5/float(abs(b)))])
proofs=[
(23,r'\lim_{x\to a}x=a',r'\delta=\varepsilon',r'|x-a|<\delta=\varepsilon','입력 거리와 출력 오차가 동일하다.','Input distance and output error are identical.'),
(24,r'\lim_{x\to a}c=c',r'\delta=1',r'|c-c|=0<\varepsilon','어떤 양의 δ도 작동한다.','Any positive delta works.'),
(25,r'\lim_{x\to0}x^2=0',r'\delta=\sqrt\varepsilon',r'|x^2|=|x|^2<\delta^2=\varepsilon','제곱은 음이 아닌 입력에서 증가한다.','Squaring is increasing for nonnegative inputs.'),
(26,r'\lim_{x\to0}x^3=0',r'\delta=\sqrt[3]\varepsilon',r'|x^3|=|x|^3<\delta^3=\varepsilon','절댓값을 취하므로 음의 x도 포함된다.','Absolute values include negative x as well.'),
(27,r'\lim_{x\to0}|x|=0',r'\delta=\varepsilon',r'\big||x|-0\big|=|x|<\delta=\varepsilon','중첩 절댓값을 정확히 단순화한다.','The nested absolute value simplifies exactly.'),
(28,r'\lim_{x\to-6^+}\sqrt[8]{6+x}=0',r'\delta=\varepsilon^8',r'0<x+6<\delta\Longrightarrow\sqrt[8]{6+x}<\delta^{1/8}=\varepsilon','실수의 여덟제곱근은 x≥−6에서 정의되므로 오른쪽 접근을 사용한다.','The real eighth root is defined for x≥−6, so the approach is from the right.'),
(29,r'\lim_{x\to2}(x^2-4x+5)=1',r'\delta=\sqrt\varepsilon',r'|x^2-4x+5-1|=(x-2)^2<\delta^2=\varepsilon','완전제곱으로 오차가 정확히 입력 거리의 제곱이 된다.','Completing the square makes the error exactly the squared input distance.'),
(30,r'\lim_{x\to2}(x^2+2x-7)=1',r'\delta=\min\{1,\varepsilon/7\}',r'|x-2|<1\Longrightarrow1<x<3\Longrightarrow|x+4|<7;\quad|x^2+2x-8|=|x-2||x+4|<7\delta\le\varepsilon','δ≤1로 두 번째 인자를 먼저 유계로 만든다.','First bound the second factor by imposing δ≤1.'),
(31,r'\lim_{x\to-2}(x^2-1)=3',r'\delta=\min\{1,\varepsilon/5\}',r'|x+2|<1\Longrightarrow-3<x<-1\Longrightarrow|x-2|<5;\quad|x^2-4|=|x+2||x-2|<5\delta\le\varepsilon','−2 근방에서 인자 x−2의 절댓값을 5로 제한한다.','Bound |x−2| by 5 near −2.'),
(32,r'\lim_{x\to2}x^3=8',r'\delta=\min\{1,\varepsilon/19\}',r'|x-2|<1\Longrightarrow1<x<3\Longrightarrow x^2+2x+4<19;\quad|x^3-8|=|x-2|(x^2+2x+4)<19\delta\le\varepsilon','세제곱 차를 인수분해한 뒤 양의 이차 인자를 제한한다.','Factor the difference of cubes and bound the positive quadratic factor.')]
for n,claim,choice,work,ko,en in proofs:
 add(n,('ε–δ 정의로 다음을 증명하라. '+d(claim),'Prove the following using the epsilon–delta definition: '+d(claim)),[('임의의 ε>0에 대해 '+m(choice)+'를 선택한다.','For any ε>0 choose '+m(choice)+'.'),(ko,en),(d(work),d(work)),('따라서 요구된 뚫린 근방의 모든 x에서 출력 오차가 ε보다 작다.','Thus every eligible x in the punctured neighborhood has output error less than ε.')],d(choice),('δ는 ε와 고정된 중심에만 의존하며 x와 무관하다. 각 인수분해를 전개해 원식의 오차를 회복한다.','Delta depends only on epsilon and the fixed center, not on x. Expanding each factorization recovers the original error expression.'))
add(33,('lim(x→3)x²=9의 증명에서 δ=min{2,ε/8}도 유효함을 검증하라.','Verify that δ=min{2,ε/8} also works in the proof of lim(x→3)x²=9.'),[('0<|x−3|<δ≤2이면 1<x<5이고 |x+3|<8이다.','If 0<|x−3|<δ≤2, then 1<x<5 and |x+3|<8.'),(d(r'|x^2-9|=|x-3||x+3|<8\delta\le\varepsilon'),d(r'|x^2-9|=|x-3||x+3|<8\delta\le\varepsilon'))],('모든 ε>0에서 유효하다.','It works for every ε>0.'),('δ=2인 큰 ε의 경우에도 |x−3|<2가 엄격하므로 상계 8에 등호가 생기지 않는다.','Even when delta equals 2 for large epsilon, the strict input bound ensures that |x+3| stays strictly below 8.'))
add(34,('lim(x→3)x²=9에서 가능한 가장 큰 대칭 δ가 √(9+ε)−3임을 기하적으로 증명하라.','Show geometrically that the largest symmetric delta for lim(x→3)x²=9 is √(9+ε)−3.'),[('포물선과 위 경계 y=9+ε의 오른쪽 교점은 b=√(9+ε)이다. 중심 3에서 그 교점까지 거리를 d=b−3이라 하자.','The right intersection of the parabola with the upper boundary y=9+ε is b=√(9+ε). Let d=b−3 be its distance from the center.'),(d(r'|x-3|<d\Longrightarrow|x^2-9|\le|x-3|(|x-3|+6)<d(d+6)=\varepsilon'),d(r'|x-3|<d\Longrightarrow|x^2-9|\le|x-3|(|x-3|+6)<d(d+6)=\varepsilon')),('더 큰 δ는 경계점 b를 입력 구간 내부에 넣어 오차가 정확히 ε인 반례를 포함한다.','Any larger delta includes the boundary input b in its interior, where the error equals epsilon and violates the strict requirement.')],d(r'\delta_{\max}=\sqrt{9+\varepsilon}-3'),('ε≥9에서는 아래 출력 경계가 음수가 될 수 있지만 절댓값 인수 상계는 모든 ε>0에 그대로 작동한다.','For ε≥9 the lower output boundary can be negative; the absolute-value factor bound still works for every ε>0.'))
D.fig(34,[bandfig(34,lambda z:z*z,3,9,2,math.sqrt(11)-3)])
def cubic_inverse(e):
 A=1+e/2;B=math.sqrt(A*A+1/27)
 return math.copysign(abs(A+B)**(1/3),A+B)+math.copysign(abs(A-B)**(1/3),A-B)
r35=cubic_inverse(.4);de35=r35-1
add(35,('lim(x→1)(x³+x+1)=3에 대해 (a)ε=0.4의 δ를 그래프로 찾고, (b)임의 ε>0의 최대 δ를 삼차방정식으로 구하며 (c)ε=0.4를 대입해 비교하라.','For lim(x→1)(x³+x+1)=3, (a)find delta graphically for ε=0.4, (b)solve the cubic for the largest delta for any ε>0, and (c)substitute ε=0.4 and compare.'),[('f′(x)=3x²+1>0이므로 각 출력 경계의 교점은 하나이다. d>0에 대해 오른쪽 오차는 d³+3d²+4d, 왼쪽 오차는 d³−3d²+4d로 오른쪽이 크다.','Since f′(x)=3x²+1>0, each output boundary has one intersection. At distance d>0 the right error is d³+3d²+4d and the left error is d³−3d²+4d, so the right side controls.'),('오른쪽 교점 b는 b³+b=2+ε를 만족한다. 실수 세제곱근으로 Cardano 식을 쓴다.','The right intersection b satisfies b³+b=2+ε. Use real cube roots in Cardano’s formula.'),(d(r'A=1+\varepsilon/2,\quad b=\sqrt[3]{A+\sqrt{A^2+1/27}}+\sqrt[3]{A-\sqrt{A^2+1/27}},\quad\delta_{\max}=b-1'),d(r'A=1+\varepsilon/2,\quad b=\sqrt[3]{A+\sqrt{A^2+1/27}}+\sqrt[3]{A-\sqrt{A^2+1/27}},\quad\delta_{\max}=b-1'))],(f'(a)δ=0.093을 택할 수 있다. (b)위의 b−1. (c)δ최대≈{de35:.10f}.',f'(a)δ=0.093 works. (b)b−1 as above. (c)δmax≈{de35:.10f}.'),('오른쪽 경계 입력은 오차 ε를 주므로 더 큰 δ는 불가능하다. 두 실수 세제곱근의 합을 원래 삼차식에 대입해 확인했다.','The right boundary gives error epsilon, excluding every larger delta. Substituted the sum of the two real cube roots into the original cubic.'),list('abc'))
D.fig(35,[bandfig(35,lambda z:z**3+z+1,1,3,.4,de35)])
add(36,('ε–δ 정의를 써서 lim(x→2)1/x=1/2를 증명하라.','Prove lim(x→2)1/x=1/2 using the epsilon–delta definition.'),[('임의 ε>0에 δ=min{1,2ε}를 택한다. |x−2|<δ≤1이면 x>1이다.','For any ε>0 choose δ=min{1,2ε}. If |x−2|<δ≤1, then x>1.'),(d(r'\left|\frac1x-\frac12\right|=\frac{|x-2|}{2|x|}<\frac{|x-2|}{2}<\frac\delta2\le\varepsilon'),d(r'\left|\frac1x-\frac12\right|=\frac{|x-2|}{2|x|}<\frac{|x-2|}{2}<\frac\delta2\le\varepsilon'))],d(r'\delta=\min\{1,2\varepsilon\}'),('첫 제한 δ≤1이 분모를 0에서 멀리 유지하므로 모든 해당 입력에 동일한 상계를 적용할 수 있다.','The preliminary restriction δ≤1 keeps the denominator away from zero, making the bound uniform over all eligible inputs.'))
add(37,('a>0일 때 lim(x→a)√x=√a를 ε–δ로 증명하라.','For a>0, prove lim(x→a)√x=√a by an epsilon–delta argument.'),[('임의 ε>0에 δ=min{a/2,ε√a}를 선택한다. |x−a|<δ이면 x>a/2>0이다.','For any ε>0 choose δ=min{a/2,ε√a}. Then |x−a|<δ implies x>a/2>0.'),(d(r'|\sqrt x-\sqrt a|=\frac{|x-a|}{\sqrt x+\sqrt a}\le\frac{|x-a|}{\sqrt a}<\frac\delta{\sqrt a}\le\varepsilon'),d(r'|\sqrt x-\sqrt a|=\frac{|x-a|}{\sqrt x+\sqrt a}\le\frac{|x-a|}{\sqrt a}<\frac\delta{\sqrt a}\le\varepsilon'))],d(r'\delta=\min\{a/2,\varepsilon\sqrt a\}'),('a>0이므로 √a로 나눌 수 있고 선택 δ도 양수이다. 근호의 정의역 역시 보장한다.','Since a>0, division by √a is valid and the chosen delta is positive. The same choice ensures the square-root domain.'))
for n,st,ko,en in [(38,('H(t)=0(t<0), H(t)=1(t≥0)인 계단함수의 t→0 극한이 없음을 정의로 증명하라.','For H(t)=0 when t<0 and H(t)=1 when t≥0, prove directly from the definition that its limit at zero fails.'),'주어진 δ>0에 −δ/2와 δ/2를 택하면 둘 다 0과 다른 입력이고 값은 0,1이다.','For a proposed δ>0, select −δ/2 and δ/2; both inputs are nonzero and their values are 0 and 1.'),(39,('유리수에서 f=0, 무리수에서 f=1인 함수의 x→0 극한이 없음을 증명하라.','Prove that the function equal to 0 at rational inputs and 1 at irrational inputs has no limit at zero.'),'유리수와 무리수의 조밀성으로 0<|x|<δ 안에서 각각 한 입력을 고르면 값이 0,1이다.','By density of rational and irrational numbers, choose one of each with 0<|x|<δ; their values are 0 and 1.')]:
 add(n,st,[('극한 L이 있다고 가정하고 ε=1/2를 택한다.','Assume a limit L exists and set ε=1/2.'),(ko,en),(d(r'|L|<1/2,\quad|1-L|<1/2\Longrightarrow1\le|L|+|1-L|<1'),d(r'|L|<1/2,\quad|1-L|<1/2\Longrightarrow1\le|L|+|1-L|<1')),('모순이므로 어떤 실수 L도 극한이 될 수 없다.','This contradiction excludes every real candidate L.')],('극한은 존재하지 않는다.','The limit does not exist.'),('선택한 ε는 후보 L과 무관하며 모든 δ에 대해 모순을 만드는 입력이 존재하므로 정의의 부정이 완성된다.','The chosen epsilon is independent of L, and every proposed delta admits contradictory inputs, completing the negation of the definition.'))
add(40,('lim(x→a)f(x)=L과 두 한쪽 극한이 모두 L이라는 조건이 동치임을 ε–δ 정의로 증명하라.','Prove from the epsilon–delta definitions that lim(x→a)f(x)=L is equivalent to both one-sided limits equaling L.'),[('정방향: 양쪽 정의가 주는 δ는 0<a−x<δ인 왼쪽 입력과 0<x−a<δ인 오른쪽 입력에 각각 그대로 적용된다.','Forward: the delta in the two-sided definition applies separately to inputs with 0<a−x<δ and to those with 0<x−a<δ.'),('역방향: ε>0에 대해 두 한쪽 정의의 δ₋,δ₊를 얻고 δ=min{δ₋,δ₊}로 둔다.','Conversely, for ε>0 obtain δ₋ and δ₊ from the two one-sided definitions and set δ=min{δ₋,δ₊}.'),('0<|x−a|<δ이면 x<a 또는 x>a 중 하나이며 해당 정의로 |f(x)−L|<ε이다.','Whenever 0<|x−a|<δ, either x<a or x>a, and the corresponding definition gives |f(x)−L|<ε.')],d(r'\lim_{x\to a}f(x)=L\iff\lim_{x\to a^-}f(x)=\lim_{x\to a^+}f(x)=L'),('두 한쪽 δ가 같을 필요는 없으며 양수의 최솟값 역시 양수이므로 하나의 공통 근방을 얻는다.','The one-sided deltas need not agree; the minimum of two positive values remains positive and gives a common neighborhood.'))
add(41,('1/(x+3)⁴>10000이 되려면 x를 −3에 얼마나 가깝게 잡아야 하는가?','How close must x be to −3 to ensure 1/(x+3)⁴>10000?'),[(d(r'\frac1{(x+3)^4}>10^4\iff0<|x+3|<10^{-1}'),d(r'\frac1{(x+3)^4}>10^4\iff0<|x+3|<10^{-1}'))],d(r'0<|x+3|<0.1\quad(\delta=0.1)'),('x=−3은 정의되지 않아 제외하고, 거리 0.1에서는 등호 10000이므로 엄격한 부등식에서 경계도 제외한다.','Exclude x=−3 because the function is undefined. At distance 0.1 the value equals 10000, so the boundary is excluded from the strict inequality.'))
add(42,('무한극한의 정의로 lim(x→−3)1/(x+3)⁴=∞를 증명하라.','Use the infinite-limit definition to prove lim(x→−3)1/(x+3)⁴=∞.'),[('임의 M>0에 δ=M⁻¹ᐟ⁴를 택한다.','For any M>0 choose δ=M⁻¹ᐟ⁴.'),(d(r'0<|x+3|<\delta\Longrightarrow0<(x+3)^4<\delta^4=1/M\Longrightarrow\frac1{(x+3)^4}>M'),d(r'0<|x+3|<\delta\Longrightarrow0<(x+3)^4<\delta^4=1/M\Longrightarrow\frac1{(x+3)^4}>M'))],d(r'\delta=M^{-1/4}\quad\Longrightarrow\quad\lim_{x\to-3}\frac1{(x+3)^4}=+\infty'),('양수의 역수를 취하면 부등호 방향이 뒤집히며, 네제곱 덕분에 좌우 접근에 모두 같은 δ가 적용된다.','Taking reciprocals of positive quantities reverses the inequality; the fourth power makes the same delta work on both sides.'))
add(43,('한쪽 무한극한 정의로 lim(x→−1⁻)5/(x+1)³=−∞를 증명하라.','Use a one-sided infinite-limit definition to prove lim(x→−1⁻)5/(x+1)³=−∞.'),[('임의 음수 N에 K=−N>0, δ=(5/K)¹ᐟ³을 택한다. x<−1이며 −δ<x+1<0일 때 t=−(x+1)은 (0,δ)에 있다.','For any N<0, let K=−N>0 and δ=(5/K)¹ᐟ³. For x<−1 with −δ<x+1<0, set t=−(x+1), so 0<t<δ.'),(d(r'\frac5{(x+1)^3}=-\frac5{t^3}<-\frac5{\delta^3}=-K=N'),d(r'\frac5{(x+1)^3}=-\frac5{t^3}<-\frac5{\delta^3}=-K=N'))],d(r'\delta=\sqrt[3]{5/(-N)}'),('x+1<0인 왼쪽에서만 이 부호가 성립한다. 오른쪽은 +∞이므로 한쪽 조건을 유지해야 한다.','The negative sign holds only on the left, where x+1<0. The right side tends to +∞, so the one-sided restriction is essential.'))
add(44,('f(x)→∞, g(x)→c∈ℝ (x→a)이다. (a)f+g→∞, (b)c>0이면 fg→∞, (c)c<0이면 fg→−∞를 정의로 증명하라.','Assume f(x)→∞ and g(x)→c∈ℝ as x→a. Prove from the definitions: (a)f+g→∞; (b)fg→∞ if c>0; (c)fg→−∞ if c<0.'),[
('(a)ε=1로 얻은 근방에서 g>c−1이다. 임의 M>0에 f>max{1,M−c+1}인 근방과 교차시키면 f+g>M이다.','(a)On a neighborhood obtained with ε=1, g>c−1. Intersect it with one where f>max{1,M−c+1} for an arbitrary M>0; then f+g>M.'),
('(b)ε=c/2로 g>c/2>0을 보장한다. f>2M/c인 근방과 교차시키면 fg>M이다.','(b)Use ε=c/2 to ensure g>c/2>0. Intersect with a neighborhood where f>2M/c; then fg>M.'),
('(c)임의 N<0에 K=−N>0이라 하자. ε=−c/2로 g<c/2<0이고 f>2K/(−c)>0인 공통 근방을 택하면 fg<f·c/2<−K=N이다.','(c)For any N<0 put K=−N>0. Use ε=−c/2 to obtain g<c/2<0 and choose a common neighborhood with f>2K/(−c)>0. Then fg<f·c/2<−K=N.'),
('각 교차 근방은 두 양의 δ 중 작은 값을 사용하여 얻는다.','Each common neighborhood is obtained by taking the smaller of the two positive deltas.')],('(a)+∞; (b)c>0에서 +∞; (c)c<0에서 −∞.','(a)+∞; (b)+∞ when c>0; (c)−∞ when c<0.'),('곱의 증명에서는 f의 양수 조건을 함께 확보해 음수 g를 곱할 때 부등호 방향이 정확하게 유지되도록 했다.','The product proofs also ensure f>0, so inequalities involving a negative g have the correct direction.'),list('abc'))
normalize_prose_inequalities(D)
D.save(44)
