"""General Exercises3.9, visually compared against PDF327–329."""
from early_helpers import Book
from pathlib import Path
import sympy as s,json,re,math
x=s.symbols('x',positive=True);R=s.Rational;C=s.symbols('C');b=Book('3.9',[290,291,292]);checks=[]
def m(t):return r'\('+t+r'\)'
def tx(t):return s.latex(t)
def F(t):return(m(t),m(t))
def eq(name,z):assert s.simplify(s.trigsimp(z))==0,(name,z);checks.append(name)
def add(n,k,e,steps,ak,ae=None,parts=[]):
 b.add(n,290 if n<=45 else 291 if n<=70 else 292,('원시함수','Antiderivatives'),(k,e),steps,(ak,ak if ae is None else ae),parts,check=('결과를 미분하여 주어진 함수·속도·가속도로 돌아가는지 확인하고 모든 초기조건과 단위를 대입한다.','Differentiate back to the supplied function,velocity,or acceleration,and substitute every initial condition with units.'));b.E[n]['conceptHref']='../../calc1/index.html'
for n,fs,As in[(1,[6,3*x*x],[6*x,x**3]),(2,[2*x,-1/x**2],[x*x,1/x]),(3,[s.cos(x),s.sec(x)*s.tan(x)],[s.sin(x),s.sec(x)]),(4,[s.sin(x),s.sec(x)**2],[-s.cos(x),s.tan(x)])]:
 st=[]
 for tag,f,A in zip('ab',fs,As):
  eq(f'{n}{tag} derivative',s.diff(A,x)-f);st.append(F('('+tag+r')\ f(x)='+tx(f)+r'\Longrightarrow F(x)='+tx(A)))
 st.append(('하나의 원시함수만 요구하므로 적분상수를 0으로 골랐다. 변수 이름을 x로 통일했다.','One antiderivative is requested,so choose integration constant0.Variable names are standardized to x.'))
 add(n,'(a)(b)의 각 함수에 대해 원시함수 하나를 구하라: '+m(',\quad '.join(tx(f)for f in fs)),'Find one antiderivative of each function(a)(b): '+m(',\quad '.join(tx(f)for f in fs)),st,m(r'(a)\ '+tx(As[0])+r';\quad(b)\ '+tx(As[1])),parts=list('ab'))
D={5:4*x+7,6:x*x-3*x+2,7:2*x**3-R(2,3)*x*x+5*x,8:6*x**5-8*x**4-9*x*x,9:x*(12*x+8),10:(x-5)**2,11:4*x**(-R(2,3))-2*x**R(5,3),12:3*x**R(4,5)+x**(-R(5,2)),13:3*s.sqrt(x)-2*x**R(1,3),14:s.sqrt(x)*(2-x+6*x*x),15:(2*x-4+3*s.sqrt(x))/s.sqrt(x),16:s.root(5,4)+x**R(1,4),17:10/x**9,18:(5-4*x**3+2*x**6)/x**6,19:2*s.sin(x)-3*s.sec(x)*s.tan(x),20:3*s.cos(x)-4*s.sin(x),21:2*s.sin(x)-s.sec(x)**2,22:s.sec(x)**2+s.pi*s.cos(x),23:x**R(2,3)-2*s.sec(x)**2,24:1+2*s.sin(x)+3/s.sqrt(x)}
manual={19:-2*s.cos(x)-3*s.sec(x),20:3*s.sin(x)+4*s.cos(x),21:-2*s.cos(x)-s.tan(x),22:s.tan(x)+s.pi*s.sin(x),23:R(3,5)*x**R(5,3)-2*s.tan(x)}
for n,f in D.items():
 A=manual[n]if n in manual else s.integrate(s.expand(f),x);eq(str(n)+' derivative',s.diff(A,x)-f)
 add(n,m('f(x)='+tx(f))+'의 가장 일반적인 원시함수를 구하고 미분으로 검산하라.','Find the general antiderivative of '+m('f(x)='+tx(f))+' and check by differentiation.',[('곱과 분수를 항별 거듭제곱으로 정리하고 멱함수·삼각함수의 미분공식을 거꾸로 적용한다.','Expand products or split quotients into powers,and reverse power/trigonometric differentiation rules.'),F(r'\int x^p\,dx={x^{p+1}\over p+1}+C\quad(p\ne-1)'),F('F(x)='+tx(A)+r'+C'),('정의역의 각 연결구간에서 임의상수 C를 독립적으로 정한다. 홀수근은 실수근으로 해석한다.','The arbitrary constant may differ on disconnected domain intervals.Odd roots mean real roots.')],m('F(x)='+tx(A)+r'+C'))
for n,f,ic in[(25,5*x**4-2*x**5,4),(26,x+2*s.sin(x),-6)]:
 A=s.integrate(f,x);A=s.simplify(A+ic-A.subs(x,0));eq(str(n)+' derivative',s.diff(A,x)-f);eq(str(n)+' initial',A.subs(x,0)-ic)
 add(n,m('f(x)='+tx(f)+',\ F(0)='+str(ic))+'를 만족하는 원시함수 F를 구하고 f와 F의 그래프를 비교하라.','Find the antiderivative for '+m('f(x)='+tx(f)+',\ F(0)='+str(ic))+' and compare graphs of f and F.',[('먼저 항별로 적분하여 임의상수를 둔다. F(0)을 대입하여 상수를 결정한다.','Integrate term by term with a constant,then use F(0)to determine it.'),F('F(x)='+tx(A)),('f가 양수일 때 F는 증가하고 음수일 때 감소한다. F′=f를 미분으로 확인한다.','F increases where f is positive and decreases where f is negative.Differentiation verifies F′=f.')],m('F(x)='+tx(A)))
# Higher derivatives and initial/boundary values. Variable names standardized to x.
higher={27:(2,24*x,[]),28:(2,x*x-4,[]),29:(2,4*x**3+24*x-1,[]),30:(2,6*x-x**4+3*x**5,[]),31:(2,4-x**R(1,3),[]),32:(2,x**R(2,3)+x**(-R(2,3)),[]),33:(3,12+s.sin(x),[]),34:(3,s.sqrt(x)-2*s.cos(x),[]),35:(1,5*x**4-3*x*x+4,[(0,-1,2)]),36:(1,s.sqrt(x)-2,[(0,9,4)]),37:(1,5*x**R(2,3),[(0,8,21)]),38:(1,x+x**-3,[(0,1,6)]),39:(1,s.sec(x)*(s.sec(x)+s.tan(x)),[(0,s.pi/4,-1)]),40:(1,(x+1)/s.sqrt(x),[(0,1,5)]),41:(2,-2+12*x-12*x*x,[(0,0,4),(1,0,12)]),42:(2,8*x**3+5,[(0,1,0),(1,1,8)]),43:(2,s.sin(x)+s.cos(x),[(0,0,3),(1,0,4)]),44:(2,4-6/x**4,[(0,1,6),(1,2,9)]),45:(2,4+6*x+24*x*x,[(0,0,3),(0,1,10)]),46:(2,20*x**3+12*x*x+4,[(0,0,8),(0,1,5)]),47:(2,x**R(1,3)-s.cos(x),[(0,0,2),(0,1,2)]),48:(3,s.cos(x),[(0,0,1),(1,0,2),(2,0,3)])}
for n,(order,source,ics)in higher.items():
 A=source;constants=s.symbols('C1:'+str(order+1));st=[]
 for j,c in enumerate(constants):
  A=(s.tan(x)+s.sec(x)if n==39 and j==0 else s.integrate(A,x))+c
  st.append(F('f^{('+str(order-j-1)+')}(x)='+tx(A)))
 if ics:
  sol=s.solve([s.diff(A,x,k).subs(x,t)-v for k,t,v in ics],constants,dict=True)[0];A=s.simplify(A.subs(sol));st.append(('주어진 값들을 대입하여 적분상수의 연립방정식을 푼다.','Substitute the given values and solve the linear equations for integration constants.'));st.append(F('f(x)='+tx(A)))
 eq(str(n)+' higher derivative',s.diff(A,x,order)-source)
 for k,t,v in ics:eq(str(n)+f' condition{k},{t}',s.diff(A,x,k).subs(x,t)-v)
 conditions=',\quad '.join('f^{('+str(k)+')}('+tx(s.sympify(t))+')='+tx(s.sympify(v))for k,t,v in ics)
 given=m('f^{('+str(order)+')}(x)='+tx(source)+(r',\quad '+conditions if ics else''))
 if n==39:st.append(('tan과 sec가 정의된 −π/2<x<π/2에서 해를 사용한다.','Use the solution on−π/2<x<π/2,where tan and sec are defined.'))
 if n in[38,44]:st.append(('주어진 정의역 x>0에서 해를 사용한다.','Use the solution on the stated domain x>0.'))
 add(n,given+'에서 f를 구하라.','Find f from '+given+'.',st,m('f(x)='+tx(A)))
add(49,'곡선이(2,5)를 지나고 접선 기울기가 3−4x일 때 f(1)을 구하라.','A curve passes through(2,5)and has tangent slope3−4x.Find f(1).',[F(r'f^{\prime}=3-4x\Longrightarrow f=3x-2x^2+C'),F(r'f(2)=5\Longrightarrow C=7'),F(r'f(1)=3-2+7=8')],m('f(1)=8'))
add(50,'f′(x)=x³이고 직선 x+y=0이 접선인 f를 구하라.','Find f with f′(x)=x³ and tangent line x+y=0.',[F(r'f=x^4/4+C'),('접선 기울기 −1=x³이므로 접점은 x=−1, 직선 위의 높이는1이다.','The tangent slope−1=x³ forces x=−1,with height1 on the line.'),F(r'f(-1)=1/4+C=1\Longrightarrow C=3/4')],m('f(x)=x^4/4+3/4'))
for n,ans,k,e in[(51,'b','f가 처음 음수, 이후 양수이므로 원시함수는 처음 감소한 뒤 증가해야 한다. f=0인 곳에서 수평접선을 갖는 b가 맞다.','Since f is initially negative and later positive,its antiderivative first decreases then increases.Curve b has the required horizontal tangent at the zero of f.'),(52,'a','f가 처음 양수, 이후 음수이므로 원시함수는 증가한 뒤 감소한다. f=0에서 국소최대를 갖는 a가 맞다.','Since f is initially positive and later negative,its antiderivative increases then decreases.Curve a has the required local maximum at the zero of f.')]:
 add(n,'그림의 a,b,c 중 f의 원시함수를 고르고 이유를 설명하라.','Choose the antiderivative of f among curves a,b,c and explain.',[(k,e)],ans)
add(53,'주어진 f의 그래프를 보고 F(0)=1인 원시함수 F를 개략적으로 그려라.','Sketch an antiderivative F of the supplied f graph with F(0)=1.', [('(0,1)에서 수평접선으로 시작한다. f<0인(0,2)에서 감소하고 f>0인(2,3)에서 증가한 뒤 x>3에서 다시 감소한다.','Start at(0,1)with a horizontal tangent.Decrease on(0,2),increase on(2,3),then decrease after3.'),('x≈2는 국소최소, x≈3은 국소최대이다. f의 골짜기·봉우리가 F의 오목성 전환을 결정하고, 오른쪽에서 f→0이면 F의 접선은 점점 수평이 된다.','There is a local minimum near2 and maximum near3.Extrema of f determine concavity changes of F;as f tends to0 on the right,the tangent to F becomes flatter.')],'F(0)=1; 감소→증가→감소, 전환점 x≈2,3.','F(0)=1;decrease→increase→decrease,turning near x≈2,3.')
add(54,'주어진 속도 그래프에 대응하는 위치함수의 개형을 그려라.','Sketch a position function corresponding to the supplied velocity graph.', [('양의 속도가 커질 때 위치는 위로 오목하게 증가한다. 양의 일정속도 구간에서는 직선으로 증가하고 속도가0으로 줄 때 아래로 오목해진다.','As positive velocity grows,position increases concave upward.Constant positive velocity gives a rising line;as velocity falls to0,the curve becomes concave downward.'),('속도가0인 구간에서는 위치가 일정하다. 음의 속도 구간에서는 위치가 감소하고, 속도가 다시0으로 돌아오면 다시 수평 구간이 된다.','Zero velocity gives a horizontal position segment.Negative velocity makes position decrease;return to zero velocity gives another horizontal segment.'),('초기 위치가 주어지지 않아 수직 평행이동은 자유롭다.','The unspecified initial position permits any vertical translation.')],'증가→정지→감소→정지의 위치 곡선.','Position rises,holds,falls,then holds.')
add(55,'도함수가 (0,1)에서2,(1,2)에서1,(2,3)에서−1이고 f는[0,3]에서 연속이며 f(0)=−1이다. f를 그려라.','The derivative equals2 on(0,1),1 on(1,2),and−1 on(2,3).Given continuity and f(0)=−1,sketch f.',[('각 구간에서 직선을 적분하고 접합점에서 연속성을 적용한다.','Integrate to a line on each interval and enforce continuity at the joins.'),F(r'f(x)=\begin{cases}2x-1&0\le x\le1\\x&1\le x\le2\\4-x&2\le x\le3\end{cases}')],m(r'(0,-1)\to(1,1)\to(2,2)\to(3,1)'))
add(56,'f(x)=2x−3√x를 그리고 F(0)=1인 원시함수를 (a)(b)개형으로,(c)식으로,(d)그 식의 그래프로 비교하라.','Graph f(x)=2x−3√x;sketch its antiderivative with F(0)=1,derive its formula,and compare the plots.',[F(r'F(x)=x^2-2x^{3/2}+C,\quad C=1'),F(r'f(x)=\sqrt{x}(2\sqrt{x}-3)'),('0<x<9/4에서 F는 감소하고 x>9/4에서 증가한다. 따라서 x=9/4에서 최솟값−11/16을 갖는다.','F decreases on(0,9/4)and increases afterward,so its minimum is−11/16 at x=9/4.')],m(r'F(x)=x^2-2x^{3/2}+1,\quad x\ge0'),parts=list('abcd'))
for n,expr,description,english in[(57,r'{\sin x\over1+x^2}','[−2π,2π]에서 f를 그리고 원점을 지나는 원시함수를 그려라.','Plot f on[−2π,2π]and sketch the antiderivative through the origin.'),(58,r'\sqrt{x^4-2x^2+2}-2','[−3,3]에서 f를 그리고 원점을 지나는 원시함수를 그려라.','Plot f on[−3,3]and sketch the antiderivative through the origin.')]:
 steps=[F(r'F(x)=\int_0^x f(t)\,dt')]
 if n==57:steps += [('f는 홀함수이므로 이 F는 짝함수이다. 도함수의 부호는 sin x와 같아 증가(−2π,−π),(0,π), 감소(−π,0),(π,2π)이다.','Odd f makes this F even.Its derivative has the sign of sin x:increasing on(−2π,−π),(0,π),decreasing on(−π,0),(π,2π).')]
 else:steps += [F(r'f(x)=0\iff x=\pm a,\quad a=\sqrt{1+\sqrt3}'),('f는 짝함수이므로 F는 홀함수이다. |x|<a에서 감소, |x|>a에서 증가한다. −a는 국소최대, a는 국소최소이다.','Even f makes F odd.F decreases for|x|<a and increases for|x|>a.Thus−a is a local maximum and a a local minimum.')]
 steps.append(('닫힌 형태를 억지로 구할 필요 없이 부호와 누적 면적으로 개형을 정한다. 그림의 원시함수는 수치 적분으로 그렸다.','Use signs and accumulated area without requiring an elementary closed form.The antiderivative plot uses numerical integration.'))
 add(n,m('f(x)='+expr)+'; '+description,m('f(x)='+expr)+'; '+english,steps,m(r'F(x)=\int_0^x f(t)\,dt,\quad F(0)=0'))
# Motion data: integrate the given derivative and solve all supplied conditions.
motion={59:(1,2*s.cos(x)+4*s.sin(x),[(0,0,3)]),60:(1,x*x-3*s.sqrt(x),[(0,4,8)]),61:(2,2*x+1,[(0,0,3),(1,0,-2)]),62:(2,3*s.cos(x)-2*s.sin(x),[(0,0,0),(1,0,4)]),63:(2,s.sin(x)-s.cos(x),[(0,0,0),(0,s.pi,6)]),64:(2,x*x-4*x+6,[(0,0,0),(0,1,20)])}
for n,(order,der,ics)in motion.items():
 A=der;cs=s.symbols('C1:'+str(order+1));steps=[]
 for j,c in enumerate(cs):A=s.integrate(A,x)+c;steps.append(F(('v(t)='if order-j==2 else's(t)=')+tx(A).replace('x','t')))
 sol=s.solve([s.diff(A,x,k).subs(x,t)-v for k,t,v in ics],cs,dict=True)[0];A=s.simplify(A.subs(sol));eq(str(n)+' motion derivative',s.diff(A,x,order)-der)
 for k,t,v in ics:eq(str(n)+f' initial{k},{t}',s.diff(A,x,k).subs(x,t)-v)
 given=m(('v(t)='if order==1 else's a(t)=').replace('s a','a')+tx(der).replace('x','t'))+'; '+m(',\quad '.join(('s'if k==0 else'v')+'('+tx(s.sympify(t))+')='+tx(s.sympify(v))for k,t,v in ics))
 steps.append(('초기값 또는 경계값을 대입하여 상수를 정한다.','Determine the constants from the initial or boundary values.'));steps.append(F('s(t)='+tx(A).replace('x','t')))
 add(n,given+'를 만족하는 위치함수를 구하라.','Find position satisfying '+given+'.',steps,m('s(t)='+tx(A).replace('x','t')))
# Physical models: units and time origins remain explicit.
add(65,'높이450m에서 돌을 놓는다. (a)높이,(b)낙하시간,(c)충돌속도,(d)아래로5m/s로 던졌을 때 낙하시간을 구하라.','Drop a stone from450m.Find(a)height,(b)impact time,(c)impact velocity,and(d)impact time with initial downward speed5m/s.',[('위쪽을 양으로 잡고 공기저항을 무시하여 가속도−9.8m/s²를 두 번 적분한다.','Take upward as positive and neglect air resistance,integrating acceleration−9.8m/s² twice.'),F(r'(a)\ s(t)=450-4.9t^2'),F(r'(b)\ t=\sqrt{450/4.9}\approx9.583\ \mathrm{s}'),F(r'(c)\ v=-9.8t\approx-93.915\ \mathrm{m/s}'),F(r'(d)\ 450-5t-4.9t^2=0\Longrightarrow t={-5+\sqrt{8845}\over9.8}\approx9.087\ \mathrm{s}')],m(r'(a)450-4.9t^2;\ (b)9.583\mathrm{s};\ (c)-93.915\mathrm{m/s};\ (d)9.087\mathrm{s}'),parts=list('abcd'))
add(66,'일정 가속도 a,초기속도 v₀,초기위치 s₀일 때 위치공식을 유도하라.','Derive position under constant acceleration a with initial velocity v₀ and position s₀.',[F(r'v^{\prime}=a\Longrightarrow v=at+C,\quad C=v_0'),F(r's^{\prime}=at+v_0\Longrightarrow s=at^2/2+v_0t+D,\quad D=s_0')],m(r's(t)=at^2/2+v_0t+s_0'))
add(67,'높이 s₀에서 초기속도 v₀로 위로 던진 물체에 대해 속도제곱과 높이의 관계를 증명하라.','For upward launch with initial velocity v₀ from height s₀,derive the squared-velocity relation.',[F(r'v=v_0-9.8t,\quad s-s_0=v_0t-4.9t^2'),F(r'v^2-v_0^2=-19.6v_0t+96.04t^2=-19.6(s-s_0)')],m(r'v^2=v_0^2-19.6(s-s_0)'))
add(68,'높이432ft 절벽에서 공1을48ft/s로 위로 던지고 1초 뒤 공2를24ft/s로 던진다. 서로 지나치는지 구하라.','From a432ft cliff,launch ball1 upward at48ft/s and ball2 one second later at24ft/s.Do they pass?', [F(r's_1(t)=432+48t-16t^2'),F(r's_2(t)=432+24(t-1)-16(t-1)^2\quad(t\ge1)'),F(r's_1-s_2=40-8t=0\Longrightarrow t=5,\quad s_1(5)=272'),('공2 발사4초 뒤인 t=5초에 두 공 모두 지면 위272ft에 있으므로 실제로 지나친다.','At t=5s,which is4s after the second launch,both are272ft above ground,so they do pass.')],m(r't=5\ \mathrm{s},\quad s=272\ \mathrm{ft}'))
add(69,'절벽에서 놓은 돌의 지면 충돌 속력이120ft/s이다. 절벽 높이를 구하라.','A dropped stone hits the ground at120ft/s.Find the cliff height.',[F(r'v=-32t=-120\Longrightarrow t=15/4'),F(r'H=16t^2=225\ \mathrm{ft}')],m(r'225\ \mathrm{ft}'))
add(70,'길이 L,선밀도 ρ인 다이빙대 끝에 질량 m의 사람이 있다. EI y″=mg(L−x)+(ρg/2)(L−x)², g<0에서 (a)곡선,(b)끝의 처짐 거리를 구하라.','For a diving board of length L,densityρ,and end mass m,suppose EI y″=mg(L−x)+(ρg/2)(L−x)² with g<0.Find(a)the curve and(b)end deflection.', [('고정단에서 f(0)=f′(0)=0이다. 우변을 전개하고 두 번 적분해 상수를 이 경계조건으로 정한다.','At the clamped end,f(0)=f′(0)=0.Expand the right side,integrate twice,and use these boundary conditions.'),F(r'f(x)={g\over EI}\left[m\left({Lx^2\over2}-{x^3\over6}\right)+\rho\left({L^2x^2\over4}-{Lx^3\over6}+{x^4\over24}\right)\right]'),F(r'f(L)={g\over EI}\left({mL^3\over3}+{\rho L^4\over8}\right)'),('g<0이므로 끝의 높이는 음수이며 아래로 처진 거리는 −f(L)이다.','Since g<0,the tip height is negative;the downward distance is−f(L).')],m(r'\text{deflection}={-g\over EI}\left({mL^3\over3}+{\rho L^4\over8}\right)'),parts=list('ab'))
add(71,'한계비용이1.92−0.002x달러/개이고 1개 생산비가562달러일 때 100개 생산비를 구하라.','Marginal cost is1.92−0.002x dollars/item and one item costs562 dollars.Find the cost of100 items.',[F(r'C(x)=1.92x-0.001x^2+K'),F(r'K=562-1.92+0.001=560.081'),F(r'C(100)=192-10+560.081=742.081')],'약 $742.08.','Approximately $742.08.')
add(72,'길이1m 막대의 선밀도는 ρ(x)=1/√x g/cm이며 x는 cm이다. 전체 질량을 구하라.','A1m rod has densityρ(x)=1/√x g/cm,with x in centimeters.Find total mass.', [('길이를100cm로 바꾸고,0의 특이점에서는 양의 ε에서 시작한 극한을 취한다.','Convert the length to100cm;handle the singularity at0 by starting atε>0 and taking a limit.'),F(r'M=\lim_{\varepsilon\to0^+}\int_{\varepsilon}^{100}x^{-1/2}\,dx=\lim_{\varepsilon\to0^+}(20-2\sqrt\varepsilon)=20\ \mathrm{g}')],m(r'20\ \mathrm{g}'))
add(73,'지면500m 위 빗방울의 초기 하강속도는10m/s,하강가속도는0≤t≤10에서9−0.9t,그 뒤0이다. 낙하시간을 구하라.','A raindrop starts500m above ground with downward speed10m/s.Its downward acceleration is9−0.9t for0≤t≤10,and0 thereafter.Find fall time.',[F(r'v(t)=10+9t-0.45t^2,\quad d(t)=10t+4.5t^2-0.15t^3\quad(0\le t\le10)'),F(r'v(10)=55,\quad d(10)=400'),('10초 뒤에는55m/s를 유지하고 남은100m를 이동한다.','After10s it keeps speed55m/s through the remaining100m.'),F(r'T=10+100/55=130/11\approx11.818\ \mathrm{s}')],m(r'130/11\ \mathrm{s}\approx11.818\ \mathrm{s}'))
add(74,'50mi/h로 가던 차가22ft/s²로 일정하게 감속할 때 정지거리를 구하라.','Find stopping distance from50mi/h with constant deceleration22ft/s².',[F(r'v_0=50(5280/3600)=220/3\ \mathrm{ft/s}'),F(r'0=v_0^2-44d\Longrightarrow d=1100/9\approx122.22\ \mathrm{ft}')],m(r'122.22\ \mathrm{ft}'))
add(75,'5초 동안30mi/h에서50mi/h로 증가시키는 일정 가속도를 구하라.','Find constant acceleration from30mi/h to50mi/h in5s.',[F(r'a={(50-30)(5280/3600)\over5}={88\over15}\ \mathrm{ft/s^2}')],m(r'a\approx5.867\ \mathrm{ft/s^2}'))
add(76,'감속도16ft/s²로 제동하여200ft를 미끄러진 뒤 멈춘 차의 초기속력을 구하라.','A car stops over200ft under constant deceleration16ft/s².Find initial speed.',[F(r'0=v_0^2-2(16)(200)'),F(r'v_0=80\ \mathrm{ft/s}=600/11\ \mathrm{mi/h}')],m(r'80\ \mathrm{ft/s}\approx54.55\ \mathrm{mi/h}'))
add(77,'100km/h로 가는 차가80m 앞에서 멈추려면 필요한 일정 감속도를 구하라.','Find constant deceleration needed to stop within80m from100km/h.',[F(r'v_0=250/9\ \mathrm{m/s},\quad0=v_0^2+2a(80)'),F(r'a=-{3125\over648}\approx-4.823\ \mathrm{m/s^2}')],'감속 크기는 최소4.823m/s²이다.','Deceleration magnitude must be at least4.823m/s².')
add(78,'로켓이 정지 출발하여 첫3초 a=60t(ft/s²),그 뒤14초 자유비행한다. 낙하산이 열려5초 동안 속도가 선형으로−18ft/s가 되고 이후 그 속도로 내려온다. (a)s,v와 그래프,(b)최고점,(c)착지시간을 구하라.','A rocket starts from rest with a=60t(ft/s²)for3s,then flies freely14s.A parachute then changes velocity linearly to−18ft/s over5s;that speed persists.Find(a)s,v and plots,(b)maximum height,and(c)landing time.',[F(r'v(t)=\begin{cases}30t^2&0\le t\le3\\270-32(t-3)&3\le t\le17\\-178+32(t-17)&17\le t\le22\\-18&22\le t\le410/9\end{cases}'),F(r's(t)=\begin{cases}10t^3&0\le t\le3\\270+270(t-3)-16(t-3)^2&3\le t\le17\\914-178(t-17)+16(t-17)^2&17\le t\le22\\424-18(t-22)&22\le t\le410/9\end{cases}'),('각 구간 경계에서 위치와 속도를 연속으로 맞췄다. 지상 출발을 s(0)=0으로 두었다.','Position and velocity match at every join,with ground launch s(0)=0.'),F(r'v=0\Longrightarrow t=3+270/32=183/16=11.4375'),F(r's_{\max}=22545/16=1409.0625\ \mathrm{ft}'),F(r's=0\Longrightarrow t=22+424/18=410/9\approx45.556\ \mathrm{s}')],m(r'(b)\ t=11.4375\mathrm{s},\ s=1409.0625\mathrm{ft};\quad(c)\ t=45.556\mathrm{s}'),parts=list('abc'))
add(79,'열차의 가감속도 크기는2.4ft/s²,최고속력180mi/h이다. (a)정지에서 최고속력 도달 후20분 순항한 거리,(b)출발·정지 포함20분 최대거리,(c)60mi 역간 최소시간,(d)37.5분 역간 거리를 구하라.','A train accelerates/decelerates at2.4ft/s² with top speed180mi/h.Find(a)distance after acceleration plus20min cruising,(b)maximum rest-to-rest distance in20min,(c)minimum rest-to-rest time over60mi,(d)station distance for a37.5min fastest trip.',[F(r'V=264\ \mathrm{ft/s},\quad t_a=V/2.4=110\ \mathrm{s},\quad d_a=Vt_a/2=14520\ \mathrm{ft}=2.75\ \mathrm{mi}'),F(r'(a)\ d=2.75+180(20/60)=62.75\ \mathrm{mi}'),F(r'(b)\ d=V(1200-110)=287760\ \mathrm{ft}=54.5\ \mathrm{mi}'),('출발과 정지의 삼각형 면적 두 개를 합치면 최고속력으로110초 달린 면적 하나만큼 줄어든다.','Together,the acceleration and braking triangles lose the area of110s at full speed.'),F(r'(c)\ T={60(5280)\over264}+110=1310\ \mathrm{s}=21\mathrm{min}\ 50\mathrm{s}'),F(r'(d)\ d={264(2250-110)\over5280}=107\ \mathrm{mi}')],m(r'(a)62.75\mathrm{mi};\ (b)54.5\mathrm{mi};\ (c)1310\mathrm{s};\ (d)107\mathrm{mi}'),parts=list('abcd'))
assert sorted(b.E)==list(range(1,80))
def norm(v):
 if isinstance(v,str):
  chunks=re.split(r'(\\\(.*?\\\)|\\\[.*?\\\])',v,flags=re.S);return ''.join(z if i%2 else z.replace('<',r'\(\lt\)')for i,z in enumerate(chunks))
 if isinstance(v,list):return[norm(z)for z in v]
 if isinstance(v,dict):return{k:norm(z)for k,z in v.items()}
 return v
b.E=norm(b.E);b.save();Path(__file__).with_name('s3-9-report.json').write_text(json.dumps({'section':'3.9','exercises':79,'checks':checks,'sourcePdfPages':[327,328,329]},ensure_ascii=False,indent=2)+'\n');print('3.9:',len(checks),'exact derivative and initial-condition checks')
