"""Original worked solutions, visually checked against Calculus 9e pp.873–874."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1];E=[]
def add(n,ko,en,stepsko,stepsen,ans,checkko,checken,subs=None):
 E.append(dict(id=f'stewart9-exercise-12.1-{n}',number=n,subparts=subs or [],source=dict(printedPage=873 if n<=45 else 874,pdfPage=910 if n<=45 else 911),topic=dict(ko='공간좌표와 거리',en='Coordinates and distance'),statement=dict(ko=ko,en=en),hint=dict(ko='좌표의 의미와 두 점 사이 거리 공식을 사용한다.',en='Use the coordinate interpretation and the distance formula.'),steps=dict(ko=stepsko,en=stepsen),answer=dict(ko=ans[0] if isinstance(ans,tuple) else ans,en=ans[1] if isinstance(ans,tuple) else ans),check=dict(ko=checkko,en=checken),conceptHref='../../calc1/index.html',status='math-verified'))
add(1,'원점에서 양의 x방향으로 4, 아래로 3 이동한 점을 구하라.','Locate the point after moving 4 along positive x and 3 downward from the origin.',['x는 4가 되고 y는 변하지 않는다. 아래 방향은 음의 z방향이다.'],['The x-coordinate becomes 4; y stays zero. Downward means negative z.'],r'\((4,0,-3)\)','변위의 길이는 5이다.','The displacement has length 5.')
add(2,r'한 좌표계에 \((1,5,3),(0,2,-3),(-3,0,2),(2,-2,-1)\)을 표시하라.',r'Plot \((1,5,3),(0,2,-3),(-3,0,2),(2,-2,-1)\) on one coordinate system.',['각 점의 x,y 위치를 먼저 잡고 z만큼 수직 이동한다. 두 번째 점은 yz평면, 세 번째 점은 xz평면에 놓인다.'],['First locate x and y, then move vertically by z. The second point lies in the yz-plane and the third in the xz-plane.'],('첨부 좌표 그림 참조.','See the coordinate plot.'),'좌표가 0이면 그 좌표에 수직인 좌표평면 위의 점이다.','A zero coordinate places a point on the corresponding coordinate plane.')
add(3,r'\(A=(-4,0,-1),B=(3,1,-5),C=(2,4,6)\) 중 yz평면에 가장 가까운 점과 xz평면 위의 점을 찾아라.',r'For \(A=(-4,0,-1),B=(3,1,-5),C=(2,4,6)\), find the point closest to the yz-plane and the point in the xz-plane.',[r'yz평면까지 거리는 \(|x|=4,3,2\)이다. xz평면의 조건은 \(y=0\)이다.'],[r'The yz-plane distances are \(|x|=4,3,2\). Membership in the xz-plane requires \(y=0\).'],('각각 C, A.','C and A, respectively.'),'C의 거리는2이며 A의 y좌표는0이다.','C has distance 2 and A has y-coordinate zero.')
add(4,r'\((2,3,5)\)의 세 좌표평면 위 정사영과 원점을 마주 보는 꼭짓점으로 하는 직육면체의 모든 꼭짓점 및 대각선 길이를 구하라.',r'Find the coordinate-plane projections of \((2,3,5)\), all vertices of the axis-aligned box opposite the origin, and its diagonal.',[r'정사영은 해당 평면에 수직인 좌표만 0으로 바꾼다. 꼭짓점은 \(x\in\{0,2\},y\in\{0,3\},z\in\{0,5\}\)의 모든 조합이다.',r'대각선 길이는 \(\sqrt{2^2+3^2+5^2}=\sqrt{38}\)이다.'],[r'For each projection, set only the normal coordinate to zero. Vertices are all combinations of \(x\in\{0,2\},y\in\{0,3\},z\in\{0,5\}\).',r'The diagonal has length \(\sqrt{2^2+3^2+5^2}=\sqrt{38}\).'],r'\(P_{xy}=(2,3,0),P_{yz}=(0,3,5),P_{xz}=(2,0,5);\quad d=\sqrt{38}\). \((0,0,0),(2,0,0),(0,3,0),(0,0,5),(2,3,0),(2,0,5),(0,3,5),(2,3,5)\).','꼭짓점은2×2×2=8개이다.','There are 2×2×2=8 vertices.')
for n,formula,ko,en,reasonko,reasonen in [
(5,'x=4','평면에서는 y축 평행 직선, 공간에서는 yz평면 평행 평면.','A line parallel to y in the plane; a plane parallel to yz in space.','x만 고정하고 나머지 좌표는 자유롭게 둔다.','Only x is fixed; the other coordinates are free.'),
(6,r'y=3;\quad z=5;\quad y=3,z=5','각각 xz평면 평행 평면, xy평면 평행 평면, 두 평면의 교선인 x축 평행 직선.','A plane parallel to xz, a plane parallel to xy, and their intersection line parallel to x.','동시에 두 조건을 적용하면 x만 자유롭다.','Imposing both conditions leaves only x free.'),
(7,'x+y=2','z축 평행 평면.','A plane parallel to the z-axis.','xy평면의 직선 y=2−x를 z방향으로 늘인다.','Extend the xy-plane line y=2−x along z.'),
(8,'x^2+z^2=9','y축을 축으로 하는 반지름3인 원기둥면.','A circular cylinder of radius 3 around the y-axis.','y가 고정된 단면은 반지름3인 원이며 y는 자유롭다.','Each constant-y section is a radius-3 circle; y is free.')]:
 add(n,r'식을 기하적으로 해석하고 그려라: \('+formula+r'\).',r'Interpret geometrically and sketch: \('+formula+r'\).',[reasonko],[reasonen],(ko,en),'그림에서 자유좌표 방향으로 이동해도 식이 유지된다.','Moving along the free-coordinate direction preserves the equation.')
for n,a,b in [(9,(3,5,-2),(-1,1,-4)),(10,(-6,-3,0),(2,4,5))]:
 q=sum((x-y)**2 for x,y in zip(a,b));ans='6' if n==9 else r'\sqrt{138}'
 add(n,fr'두 점 \({a},{b}\) 사이 거리를 구하라.',fr'Find the distance between \({a},{b}\).',[fr'좌표 차를 제곱하여 더하면 \(d^2={q}\)이다.'],[fr'Summing the squared coordinate differences gives \(d^2={q}\).'],fr'\(d={ans}\)','거리는 순서를 바꾸어도 같다.','Reversing the points gives the same distance.')
for n,points,squared,answer in [(11,'P=(3,-2,-3),Q=(7,0,1),R=(1,2,1)',(36,40,36),r'PQ=6,QR=2\sqrt{10},RP=6'),(12,'P=(2,-1,0),Q=(4,1,1),R=(4,-5,4)',(9,45,36),r'PQ=3,QR=3\sqrt5,RP=6')]:
 yes=n==12
 add(n,fr'\({points}\)의 세 변 길이를 구하고 직각·이등변 여부를 판정하라.',fr'Find the side lengths for \({points}\); test whether the triangle is right or isosceles.',[fr'각 차벡터의 제곱합은 \((PQ^2,QR^2,RP^2)={squared}\)이다.',('9+36=45이므로 직각이며 같은 길이의 변은 없다.' if yes else '두 변 길이는 같지만36+36≠40이므로 직각은 아니다.')],[fr'The squared lengths are \((PQ^2,QR^2,RP^2)={squared}\).',('Since 9+36=45 it is right; all side lengths differ.' if yes else 'Two sides agree, but 36+36≠40, so it is not right.')],(fr'\({answer}\). '+('직각, 이등변 아님.' if yes else '이등변, 직각 아님.'),fr'\({answer}\). '+('Right, not isosceles.' if yes else 'Isosceles, not right.')),'가장 큰 제곱길이를 나머지 둘의 합과 비교했다.','The largest squared length was compared with the sum of the other two.')
add(13,r'(a) \((2,4,2),(3,7,-2),(1,3,3)\), (b) \((0,-5,5),(1,-2,4),(3,4,2)\)가 각각 한 직선에 있는가?',r'Are the triples (a) \((2,4,2),(3,7,-2),(1,3,3)\), (b) \((0,-5,5),(1,-2,4),(3,4,2)\) collinear?',[r'(a) 차벡터 \((1,3,-4),(-1,-1,1)\)은 배수가 아니다.',r'(b) 차벡터는 \((1,3,-1),(3,9,-3)\)로 두 번째가 첫 번째의3배이다.'],[r'(a) The differences \((1,3,-4),(-1,-1,1)\) are not proportional.',r'(b) The differences \((1,3,-1),(3,9,-3)\) have ratio3.'],('(a) 아니오. (b) 예.','(a) No. (b) Yes.'),'배수 여부를 세 성분 모두에서 확인한다.','Proportionality must hold in all three coordinates.',list('ab'))
add(14,r'\((4,-2,6)\)에서 (a–c) xy,yz,xz평면, (d–f) x,y,z축까지의 거리를 구하라.',r'Find distances from \((4,-2,6)\) to (a–c) the xy,yz,xz planes and (d–f) the x,y,z axes.',[r'평면까지의 거리는 수직좌표의 절댓값이다. 축까지는 나머지 두 좌표에 피타고라스를 적용한다.',r'\(d_x=\sqrt{(-2)^2+6^2},d_y=\sqrt{4^2+6^2},d_z=\sqrt{4^2+(-2)^2}\).'],[r'A plane distance is the absolute normal coordinate. An axis distance uses the other two coordinates.',r'\(d_x=\sqrt{(-2)^2+6^2},d_y=\sqrt{4^2+6^2},d_z=\sqrt{4^2+(-2)^2}\).'],r'\((a)\ 6,\ (b)\ 4,\ (c)\ 2,\ (d)\ 2\sqrt{10},\ (e)\ 2\sqrt{13},\ (f)\ 2\sqrt5\).','축 위 최근접점은 축 방향 좌표를 그대로 보존한다.','The closest axis point preserves the coordinate along that axis.',list('abcdef'))
add(15,r'중심 \((-3,2,5)\), 반지름4인 구와 yz평면의 교선을 구하라.',r'Find the sphere with center \((-3,2,5)\), radius4, and its yz-plane intersection.',[r'중심으로부터의 거리 제곱을16으로 둔다. \(x=0\)을 대입하면 우변에서9가 빠진다.'],[r'Set squared distance from the center to16. Substituting \(x=0\) removes9 from the right side.'],r'\((x+3)^2+(y-2)^2+(z-5)^2=16;\quad x=0,\ (y-2)^2+(z-5)^2=7\).','교선은 중심(0,2,5), 반지름√7인 원이다.','The intersection is a circle centered at (0,2,5), with radius √7.')
add(16,r'중심 \((2,-6,4)\), 반지름5인 구의 식과 세 좌표평면과의 교선을 구하라.',r'Find the sphere centered at \((2,-6,4)\) with radius5 and its intersections with the coordinate planes.',[r'\((x-2)^2+(y+6)^2+(z-4)^2=25\)에서 순서대로 z,x,y를0으로 둔다.',r'y=0이면 좌변에36이 포함되어25가 될 수 없다.'],[r'In \((x-2)^2+(y+6)^2+(z-4)^2=25\), set z,x,y to zero in turn.',r'At y=0 the left side is at least36, so no intersection exists.'],(r'\((x-2)^2+(y+6)^2+(z-4)^2=25\). xy: \((x-2)^2+(y+6)^2=9,z=0\). yz: \((y+6)^2+(z-4)^2=21,x=0\). xz: 공집합.',r'\((x-2)^2+(y+6)^2+(z-4)^2=25\). xy: \((x-2)^2+(y+6)^2=9,z=0\). yz: \((y+6)^2+(z-4)^2=21,x=0\). xz: empty.'),'중심과 각 평면의 거리4,2,6을 반지름5와 비교해도 일치한다.','Center-to-plane distances4,2,6 give the same result against radius5.')
for n,center,pt,formula,q in [(17,'(3,8,1)','(4,3,-1)','(x-3)^2+(y-8)^2+(z-1)^2',30),(18,'(1,2,3)','(0,0,0)','(x-1)^2+(y-2)^2+(z-3)^2',14)]:
 add(n,fr'중심 \({center}\)이고 \({pt}\)를 지나는 구의 식을 구하라.',fr'Find the sphere centered at \({center}\) through \({pt}\).',[fr'주어진 점과 중심 사이 거리 제곱은 \(r^2={q}\)이다.'],[fr'The squared distance from center to point is \(r^2={q}\).'],fr'\({formula}={q}\)','주어진 점을 대입하면 양변이 같다.','Substituting the given point verifies the equation.')
for n,raw,form,center,rad in [(19,'x^2+y^2+z^2+8x-2z=8','(x+4)^2+y^2+(z-1)^2=25','(-4,0,1)','5'),(20,'x^2+y^2+z^2=6x-4y-10z','(x-3)^2+(y+2)^2+(z+5)^2=38','(3,-2,-5)',r'\sqrt{38}'),(21,'2x^2+2y^2+2z^2-2x+4y+1=0','(x-1/2)^2+(y+1)^2+z^2=3/4','(1/2,-1,0)',r'\sqrt3/2'),(22,'4x^2+4y^2+4z^2=16x-6y-12','(x-2)^2+(y+3/4)^2+z^2=25/16','(2,-3/4,0)','5/4')]:
 add(n,fr'구임을 보이고 중심·반지름을 구하라: \({raw}\).',fr'Show this is a sphere and find its center and radius: \({raw}\).',[fr'이차항 계수를1로 만든 뒤 각 좌표에 대해 완전제곱을 만들면 \({form}\).'],[fr'Normalize the quadratic coefficient, then complete squares: \({form}\).'],fr'\(C={center},\quad r={rad}\)','완전제곱식을 전개하면 원래 식이 복원된다.','Expanding the completed squares recovers the original equation.')
add(23,r'두 점 \(P_1=(x_1,y_1,z_1),P_2=(x_2,y_2,z_2)\)의 중점 공식을 증명하라.',r'Prove the midpoint formula for \(P_1=(x_1,y_1,z_1),P_2=(x_2,y_2,z_2)\).',[r'선분을 \(P(t)=P_1+t(P_2-P_1),0\le t\le1\)로 나타낸다. \(t=1/2\)이면 양 끝으로 가는 변위가 서로 반대이며 길이가 같다.'],[r'Parametrize the segment as \(P(t)=P_1+t(P_2-P_1),0\le t\le1\). At \(t=1/2\), displacements to the endpoints are opposite and equal in length.'],r'\(M=\left(\frac{x_1+x_2}{2},\frac{y_1+y_2}{2},\frac{z_1+z_2}{2}\right)\).','M은 선분 위에 있고 두 끝점과의 거리가 같으므로 중점이다.','M lies on the segment and is equally distant from its endpoints.')
add(24,r'지름의 양 끝이 \((5,4,3),(1,6,-9)\)인 구의 중심과 식을 구하라.',r'Find the center and equation of the sphere with diameter endpoints \((5,4,3),(1,6,-9)\).',[r'중점은 \((3,5,-3)\)이며 반지름 제곱은 \(2^2+(-1)^2+6^2=41\)이다.'],[r'The midpoint is \((3,5,-3)\), and the squared radius is \(2^2+(-1)^2+6^2=41\).'],r'\(C=(3,5,-3),\quad (x-3)^2+(y-5)^2+(z+3)^2=41\).','두 끝점 모두 이 구 위에 있고 중심을 사이에 둔다.','Both endpoints lie on the sphere on opposite sides of the center.')
add(25,r'중심 \((-1,4,5)\)이고 (a)xy,(b)yz,(c)xz평면에 접하는 구를 구하라.',r'Find spheres centered at \((-1,4,5)\) tangent to (a)xy,(b)yz,(c)xz.',[r'반지름은 중심과 평면 사이 거리이므로 각각5,1,4이다.'],[r'Tangency requires radius equal to center-to-plane distance:5,1,4.'],r'\((x+1)^2+(y-4)^2+(z-5)^2=\begin{cases}25&(a)\\1&(b)\\16&(c)\end{cases}\)','각 경우 평면과의 교집합은 최근접점 하나이다.','In each case the plane meets the sphere only at the closest point.',list('abc'))
add(26,r'\((7,3,8)\)에 가장 가까운 좌표평면과 그 점을 중심으로 그 평면에 접하는 구를 구하라.',r'Find the coordinate plane nearest \((7,3,8)\) and the sphere centered there tangent to that plane.',['세 평면까지의 거리는 xy:8, yz:7, xz:3이다. 가장 작은 값3을 반지름으로 택한다.'],['Distances to xy,yz,xz are8,7,3. The smallest,3, is the radius.'],(r'xz평면; \((x-7)^2+(y-3)^2+(z-8)^2=9\).',r'The xz-plane; \((x-7)^2+(y-3)^2+(z-8)^2=9\).'),'접점은(7,0,8)이다.','The tangent point is(7,0,8).')
regions=[(27,'z=-2','xy평면 아래2만큼의 수평평면.','A horizontal plane2 below xy.','z만 고정된다.','Only z is fixed.'),(28,'x=3','yz평면과 평행한 평면.','A plane parallel to yz.','x만3으로 고정된다.','Only x is fixed at3.'),(29,r'y\ge1','평면y=1과 y가 더 큰 쪽의 닫힌 반공간.','The closed half-space on the larger-y side of y=1.','등호가 있어 경계를 포함한다.','Equality includes the boundary.'),(30,'x<4','평면x=4에서 x가 작은 쪽의 열린 반공간.','The open half-space on the smaller-x side of x=4.','엄격부등식은 경계를 제외한다.','The strict inequality excludes the boundary.'),(31,r'-1\le x\le2','평면x=−1과x=2 사이의 닫힌 띠 공간.','The closed slab between x=−1 and x=2.','y,z에는 제한이 없다.','There is no restriction on y or z.'),(32,'z=y','x축을 포함하며 xy평면과45°를 이루는 평면.','A plane containing the x-axis and making45° with xy.','yz단면이 직선z=y이다.','Its yz-trace is the line z=y.'),(33,r'x^2+y^2=4,\ z=-1','중심(0,0,−1), 반지름2의 수평 원.','A horizontal radius-2 circle centered at(0,0,−1).','z가 고정되어 원기둥의 한 단면만 남는다.','Fixing z selects one cylinder cross-section.'),(34,'x^2+y^2=4','z축 중심 반지름2의 무한 원기둥면.','An infinite radius-2 cylindrical surface around z.','z는 자유롭다.','z is free.'),(35,r'y^2+z^2\le25','x축 중심 반지름5의 속이 찬 무한 원기둥.','A solid infinite radius-5 cylinder around x.','각 yz단면은 닫힌 원판이다.','Each yz-section is a closed disk.'),(36,r'x^2+z^2\le25,\ 0\le y\le2','y축 방향 길이2, 반지름5의 닫힌 원기둥.','A closed radius-5 cylinder of length2 along y.','밑면과 옆면 모두 포함된다.','Both end disks and the lateral boundary are included.'),(37,'x^2+y^2+z^2=4','원점 중심 반지름2의 구면.','The radius-2 sphere centered at the origin.','원점까지 거리를2로 고정한다.','Distance from the origin is fixed at2.'),(38,r'x^2+y^2+z^2\le4','원점 중심 반지름2의 닫힌 공.','The closed radius-2 ball centered at the origin.','원점까지 거리의 상한이2이다.','Distance from the origin is at most2.'),(39,r'1\le x^2+y^2+z^2\le5','원점 중심 반지름1과√5 사이의 닫힌 구각.','The closed spherical shell between radii1 and√5.','거리 제곱의 경계를 제곱근으로 바꾼다.','Take square roots of the squared-distance bounds.'),(40,r'1\le x^2+y^2\le5','z축 중심 반지름1과√5 사이의 닫힌 무한 원통 띠.','The closed infinite cylindrical shell about z between radii1 and√5.','z가 없으므로 구각이 아니라 원통 띠이다.','The absence of z gives a cylindrical shell.'),(41,r'0\le x\le3,\ 0\le y\le3,\ 0\le z\le3','원점과(3,3,3)을 마주 보는 꼭짓점으로 하는 닫힌 정육면체.','The closed cube with opposite vertices at the origin and(3,3,3).','각 좌표 구간의 길이는3이다.','Each coordinate interval has length3.'),(42,'x^2+y^2+z^2>2z','중심(0,0,1), 반지름1인 구의 외부(구면 제외).','The exterior of the radius-1 sphere centered at(0,0,1), excluding its boundary.','완전제곱하면 x²+y²+(z−1)²>1이다.','Completing the square gives x²+y²+(z−1)²>1.')]
for n,f,ko,en,sk,se in regions:add(n,fr'영역을 말로 설명하라: \({f}\).',fr'Describe the region: \({f}\).',[sk],[se],(ko,en),'등호 유무와 자유로운 좌표를 확인했다.','Boundary inclusion and free coordinates have been checked.')
for n,ko,en,ans,sk,se in [(43,'yz평면과 x=5평면 사이 영역을 부등식으로 나타내라.','Write inequalities for the region between the yz-plane and x=5.','0<x<5','두 경계 사이이므로 x가0보다 크고5보다 작다. 경계 포함을 요구하면 비엄격부등식을 쓴다.','Between the planes means x lies strictly between0 and5. Use non-strict inequalities if boundaries are included.'),(44,'xy평면의 원점 중심 반지름2 원판 위, z=8평면 아래의 속이 찬 원기둥을 나타내라.','Describe the solid cylinder above the radius-2 disk at the origin in xy and below z=8.',r'x^2+y^2\le4,\quad0\le z\le8','밑면 조건과 높이 구간을 동시에 적용한다.','Impose the base-disk condition and height interval together.'),(45,'원점 중심 반지름r,R인 두 구면 사이에서 두 경계를 제외한 영역을 나타내라(r<R).','Describe the region strictly between concentric spheres of radii r<R.','r^2<x^2+y^2+z^2<R^2','원점까지의 거리가 두 반지름 사이이다.','Distance from the origin lies strictly between the radii.'),(46,'원점 중심 반지름2인 공의 위쪽 절반을 나타내라.','Describe the solid upper half of the radius-2 ball centered at the origin.',r'x^2+y^2+z^2\le4,\quad z\ge0','공의 내부 조건에 z가음수가 아니라는 조건을 더한다.','Add nonnegative z to the ball condition.')]:add(n,ko,en,[sk],[se],fr'\({ans}\)','경계 포함 조건을 문장의 조건과 대조했다.','Boundary inclusion matches the stated region.')
add(47,'원본 그림의 공간직선 L₁과 xy정사영 L₂에서 (a)P의 좌표, (b)L₁이 xy,yz,xz평면을 만나는 점 A,B,C를 표시하라.','Using the source diagram of L₁ and its xy-projection L₂, (a) locate P and (b) mark the xy,yz,xz intersections A,B,C.',[r'(a) P를 xy평면에 내리면 x=2,y=1이고 높이는z=4이다.',r'(b) A는 L₁과 L₂의 교점이다. B는 L₂가 y축을 만나는 점의 수직 위·아래에서 L₁과 만나는 점이고, C는 L₂의 x절편 위·아래의 L₁ 점이다.'],[r'(a) P projects to x=2,y=1 and has height z=4.',r'(b) A is where L₁ meets L₂. B is on L₁ vertically above/below the y-intercept of L₂; C is on L₁ above/below its x-intercept.'],(r'\(P=(2,1,4)\). A: z=0, B: x=0, C: y=0인 L₁의 점.',r'\(P=(2,1,4)\). A,B,C are the points of L₁ with z=0,x=0,y=0, respectively.'),'그림에서 B는 xy평면 아래, C는 P보다 위에 있다.','In the diagram B lies below xy, and C lies above P.',list('ab'))
add(48,r'\(A=(-1,5,3),B=(6,2,-2)\)에 대해 \(|P-A|=2|P-B|\)인 자취가 구임을 보이고 중심과 반지름을 구하라.',r'Show that \(|P-A|=2|P-B|\), where \(A=(-1,5,3),B=(6,2,-2)\), defines a sphere; find its center and radius.',[r'제곱하여 전개하면 \(3(x^2+y^2+z^2)-50x-6y+22z+141=0\).',r'3으로 나누어 완전제곱하면 \((x-25/3)^2+(y-1)^2+(z+11/3)^2=332/9\).'],[r'Square and expand to obtain \(3(x^2+y^2+z^2)-50x-6y+22z+141=0\).',r'Divide by3 and complete squares: \((x-25/3)^2+(y-1)^2+(z+11/3)^2=332/9\).'],r'\(C=(25/3,1,-11/3),\quad r=2\sqrt{83}/3\).','양쪽 거리가 음수가 아니므로 제곱에 의한 가짜 해가 없다.','Both distances are nonnegative, so squaring introduces no extraneous locus.')
add(49,r'\(A=(-1,5,3),B=(6,2,-2)\)에서 같은 거리에 있는 점의 자취를 구하라.',r'Find the locus equidistant from \(A=(-1,5,3),B=(6,2,-2)\).',[r'\(|P-A|^2=|P-B|^2\)를 전개하면 이차항이 소거되어 평면이 남는다.'],[r'Expanding \(|P-A|^2=|P-B|^2\) cancels the quadratic terms, leaving a plane.'],(r'\(14x-6y-10z=9\), 선분AB의 수직이등분면.',r'\(14x-6y-10z=9\), the perpendicular-bisector plane of AB.'),'중점(5/2,7/2,1/2)을 대입하면9이고 법선은AB와 평행하다.','The midpoint(5/2,7/2,1/2) gives9, and the normal is parallel to AB.')
add(50,r'두 구 \(x^2+y^2+z^2+4x-2y+4z+5=0\), \(x^2+y^2+z^2=4\) 내부의 공통 부분 부피를 구하라.',r'Find the overlap volume of \(x^2+y^2+z^2+4x-2y+4z+5=0\) and \(x^2+y^2+z^2=4\).',[r'두 반지름은2, 중심은 \((-2,1,-2),(0,0,0)\)로 중심거리는3이다. 공통영역은 높이1/2인 같은 구모자2개이다.',r'각 모자 부피는 \(\int_{3/2}^{2}\pi(4-t^2)\,dt=11\pi/24\)이다.'],[r'Both radii are2 and the centers \((-2,1,-2),(0,0,0)\) are3 apart. The overlap consists of two congruent caps of height1/2.',r'Each cap has volume \(\int_{3/2}^{2}\pi(4-t^2)\,dt=11\pi/24\).'],r'\(V=11\pi/12\).','중심을 잇는 축의 수직이등분면이 공통 원을 포함한다.','The plane bisecting the center segment contains the intersection circle.')
add(51,r'\(x^2+y^2+z^2=4\), \(x^2+y^2+z^2=4x+4y+4z-11\)인 두 구면 사이 최소거리를 구하라.',r'Find the minimum separation of \(x^2+y^2+z^2=4\) and \(x^2+y^2+z^2=4x+4y+4z-11\).',[r'중심과 반지름은 \(C_1=(0,0,0),r_1=2;\ C_2=(2,2,2),r_2=1\)이다.',r'중심거리 \(2\sqrt3>3\)이므로 서로 떨어져 있고, 최소거리는 중심거리에서 두 반지름을 뺀 값이다.'],[r'The centers and radii are \(C_1=(0,0,0),r_1=2;\ C_2=(2,2,2),r_2=1\).',r'The center distance \(2\sqrt3>3\) makes them disjoint; subtract both radii to obtain their separation.'],r'\(2\sqrt3-3\).','중심을 잇는 선 위에서 삼각부등식의 등호가 달성된다.','Equality in the triangle inequality is attained along the line of centers.')
add(52,'z방향 그림자가 원판, y방향 그림자가 정사각형, x방향 그림자가 이등변삼각형인 입체를 하나 구성하고 그려라.','Construct and sketch a solid whose projections along z,y,x are respectively a disk, a square, and an isosceles triangle.',[r'원기둥을 지붕 모양 평면으로 자른 \(E=\{(x,y,z):x^2+y^2\le1,\ 0\le z\le2(1-|y|)\}\)를 택한다.',r'xy정사영은 단위원판이다. xz정사영은 \([-1,1]\times[0,2]\): 모든 x,z에 대해 y=0을 택하면 된다. yz정사영은 꼭짓점 \((-1,0),(1,0),(0,2)\)의 삼각형이며 x=0으로 모든 점을 얻는다.'],[r'Take a cylinder cut by a roof: \(E=\{(x,y,z):x^2+y^2\le1,\ 0\le z\le2(1-|y|)\}\).',r'The xy-projection is the unit disk. The xz-projection is \([-1,1]\times[0,2]\), attained with y=0. The yz-projection is the triangle with vertices \((-1,0),(1,0),(0,2)\), attained with x=0.'],r'\(x^2+y^2\le1,\quad0\le z\le2(1-|y|)\).','xz직사각형의 가로와 세로가 모두2라서 정사각형이고 yz삼각형의 빗변 길이가 같다.','Both xz side lengths are2, and the two sloping yz sides have equal lengths.')
assert [e['number'] for e in E]==list(range(1,53))
doc=dict(section='12.1',source=dict(title='Calculus',edition=9,language='en',printedPages=[873,874],pdfPages=[910,911]),scope=dict(kind='exercise',numbers=list(range(1,53)),total=52,note=dict(ko='일반 Exercises 1–52 및 모든 소문항. 원본의 조건을 대조하고 독자적으로 풀이했다.',en='General Exercises1–52, including all subparts. Conditions were checked against the source and solutions independently developed.')),exercises=E)
(R/'exercise-content/s12-1.json').write_text(json.dumps(doc,ensure_ascii=False,indent=2)+'\n')
