from calc1_core import *
import mpmath as mp
mp.mp.dps=60
D=CalcDoc('1.5',[60,61,62],lambda n:60 if n<=8 else 61 if n<=32 else 62)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('극한·한쪽 극한·무한극한','Limits,one-sided limits,and infinite limits'),st,('점의 실제 함수값과 주변에서 접근하는 값을 구분한다.','Distinguish the value at a point from values approached nearby.'),steps,ans,check,parts)
def vals(fn,items,digits=6):
 pairs=[(str(z),mp.mpf(fn(mp.mpf(str(z)))))for z in items]
 return '; '.join(z+' → '+f'{float(v):.{digits}f}'for z,v in pairs)
add(1,('lim(x→2)f(x)=5의 의미를 설명하라. 동시에 f(2)=3일 수 있는가?','Explain lim(x→2)f(x)=5.Can f(2)=3 nevertheless?'),[('2와 다른 입력을2에 충분히 가까이 고르면 함수값을 원하는 만큼5 가까이 만들 수 있다는 뜻이다.','Inputs distinct from2 can be chosen sufficiently close to2 so that their outputs are as close to5 as desired.'),('극한은 x=2 자체의 값을 사용하지 않는다.','The limit does not use the value at x=2 itself.')],('가능하다. 예:f(x)=5(x≠2),f(2)=3.','Yes.For example f(x)=5 for x≠2 and f(2)=3.'),('이 예에서 모든 뚫린 근방의 함수값은 정확히5이지만 지정점의 값은3이다.','Every punctured neighborhood has output exactly5,while the assigned value at the point is3.'))
add(2,('x→1⁻에서 f→3,x→1⁺에서 f→7이라는 말의 의미와 양쪽 극한 존재 여부를 설명하라.','Explain what f→3 as x→1⁻ and f→7 as x→1⁺ mean,and whether the two-sided limit exists.'),[('1보다 작은 입력으로 접근하면3,큰 입력으로 접근하면7에 가까워진다.','Approaching with inputs below1 gives outputs near3;approaching from above gives outputs near7.'),('양쪽 극한이 존재하려면 두 한쪽 극한이 같은 값이어야 한다.','A two-sided limit requires the one-sided limits to agree.')],('3≠7이므로 lim(x→1)f(x)는 존재하지 않는다.','Since3≠7,the two-sided limit does not exist.'),('서로 다른 두 접근 수열이 다른 출력 극한을 주므로 하나의 공통값을 정할 수 없다.','Two sequences approaching from opposite sides yield different output limits,excluding a common value.'))
add(3,('(a)lim(x→−3)f(x)=∞,(b)lim(x→4⁺)f(x)=−∞의 의미를 설명하라.','Explain(a)lim(x→−3)f(x)=∞ and(b)lim(x→4⁺)f(x)=−∞.'),[('(a)−3의 양쪽에서 충분히 가까운 입력을 택하면 함수값이 임의의 큰 양수보다 커진다.','(a)For inputs sufficiently close to−3 from either side,outputs exceed any prescribed positive bound.'),('(b)4보다 큰 입력을4에 충분히 가깝게 택하면 함수값이 임의의 큰 음수보다 작아진다.','(b)For inputs sufficiently close to4 from above,outputs fall below any prescribed negative bound.')],('무한대는 실제 실수 함수값이 아니라 제한 없이 증가하거나 감소하는 행동을 뜻한다.','Infinity describes unbounded increase or decrease,not an ordinary real function value.'),('두 경우 모두 해당 접근 방향에서 수직점근선이 생기지만 f(−3),f(4)의 정의 여부는 별개이다.','Both imply vertical-asymptotic behavior in the indicated directions,but do not determine whether f(−3) or f(4) is defined.'),list('ab'))
add(4,('그래프의 x=2에서 왼쪽 가지는 닫힌(2,3),오른쪽 가지는 열린(2,1)이고 x=4에서는 열린(4,4)로 양쪽이 이어진다.(a)2왼쪽,(b)2오른쪽,(c)2양쪽 극한,(d)f(2),(e)4양쪽 극한,(f)f(4)를 구하라.','At x=2 the graph has filled(2,3) on the left branch and open(2,1) on the right.At x=4 both sides approach open(4,4).Find(a)left limit at2,(b)right limit at2,(c)two-sided limit at2,(d)f(2),(e)limit at4,(f)f(4).'),[('2에서는 두 접근 높이3과1이 다르다.4에서는 양쪽 높이는4이지만 그 점은 제외된다.','At2,the approaching heights3 and1 differ.At4,both sides approach4,but the point itself is excluded.')],('(a)3,(b)1,(c)없음,(d)3,(e)4,(f)정의되지 않음.','(a)3,(b)1,(c)does not exist,(d)3,(e)4,(f)undefined.'),('닫힌 점은 함수값에만 적용하고 열린 점의 높이는 극한 판독에 사용했다.','Filled points determine function values;open-point heights can still determine limits.'),list('abcdef'))
D.fig(4,[panel('Jump at2;hole at4',(-2,6,0,5),[[(-2,1.7),(-1,2.6),(0,3.2),(1,3.3),(2,3)],[(2,1),(3,2),(4,4),(4.5,4),(5,3.5),(6,1.8)]],[(2,3),(2,1,'open'),(4,4,'open')],xticks=[0,2,4,6])])
add(5,('그래프는 x=1에서 높이2로 이어진다.x=3에서 왼쪽 열린점(3,1),오른쪽 열린점(3,4),별도 닫힌점(3,3)이 있다.(a)1의 극한,(b)3왼쪽,(c)3오른쪽,(d)3양쪽 극한,(e)f(3)를 구하라.','The graph passes continuously through height2 at x=1.At x=3 it has left open point(3,1),right open point(3,4),and isolated filled point(3,3).Find(a)limit at1,(b)left limit at3,(c)right limit at3,(d)two-sided limit at3,(e)f(3).'),[('x=3에서는 왼쪽이1,오른쪽이4로 접근하며 값3은 접근값을 바꾸지 않는다.','At3,the left approach is1 and right approach is4;the assigned value3 does not change these limits.')],('(a)2,(b)1,(c)4,(d)없음,(e)3.','(a)2,(b)1,(c)4,(d)does not exist,(e)3.'),('양쪽 극한이 같지 않아 f(3)의 값을 어떻게 바꾸어도 그 극한은 생기지 않는다.','Because the one-sided limits disagree,no choice of f(3) creates a two-sided limit.'),list('abcde'))
D.fig(5,[panel('One-sided limits and assigned value',(-2,6,0,5),[[(-2,3.8),(-1,3.5),(0,3),(1,2),(2,.9),(2.5,.8),(3,1)],[(3,4),(4,3.7),(5,2.8),(6,1)]],[(3,1,'open'),(3,4,'open'),(3,3)],xticks=[0,1,2,3,4,5,6])])
add(6,('h의 그래프에서 x=−3에는 열린 높이4, x=0에는 왼쪽 닫힌 높이1과 오른쪽 열린 높이−1, x=2에는 열린 높이2가 있다.5의 왼쪽에서는 높이2~4로 계속 진동하고 오른쪽은 높이3에서 시작한다.(a,b,c)−3의 왼쪽·오른쪽·양쪽 극한,(d)h(−3),(e,f,g)0의 세 극한,(h)h(0),(i)2의 극한,(j)h(2),(k)5오른쪽,(l)5왼쪽 극한을 구하라.','The graph h has an open point at height4 for x=−3;at0,it has left filled height1 and right open height−1;at2,it has open height2.To the left of5 it oscillates between2 and4,while the right branch starts at height3.Find(a,b,c)left,right,two-sided limits at−3,(d)h(−3),(e,f,g)the three limits at0,(h)h(0),(i)limit at2,(j)h(2),(k)right and(l)left limit at5.'),[('−3과2의 구멍에서는 양쪽 접근값이 같아 극한이 있다.0에서는 한쪽 높이가 달라 양쪽 극한이 없다.','The holes at−3 and2 have matching one-sided limits.At0 the unequal approaching heights prevent a two-sided limit.'),('5왼쪽의 진동 폭은 줄어들지 않으므로 하나의 수에 가까워지지 않는다.','The oscillation amplitude on the left of5 does not shrink,so it does not approach one number.')],('(a)4,(b)4,(c)4,(d)정의되지 않음,(e)1,(f)−1,(g)없음,(h)1,(i)2,(j)정의되지 않음,(k)3,(l)없음.','(a)4,(b)4,(c)4,(d)undefined,(e)1,(f)−1,(g)does not exist,(h)1,(i)2,(j)undefined,(k)3,(l)does not exist.'),('h(0)은 닫힌 점1이다.5왼쪽은 유한 범위 안에서 진동하므로∞나−∞로도 발산하지 않는다.','h(0) is the filled value1.The bounded left oscillation at5 tends to neither∞ nor−∞.'),list('abcdefghijkl'))
D.fig(6,[panel('Holes,jump,and nonshrinking oscillation',(-5,9,-2,6),[[(-5,0),(-4,2.7),(-3,4),(-2,2),(-1,1.3),(0,1)],[(0,-1),(1,0),(2,2),(2.8,4)],samples(lambda z:3+math.sin(5/(5-z)),2.8,4.97,1500),[(5,3),(6,4.5),(7,4.8),(8,4.3),(9,3)]], [(-3,4,'open'),(0,1),(0,-1,'open'),(2,2,'open')],xticks=[-4,-3,-2,0,2,4,5,6,8],yticks=[-1,0,1,2,3,4,5])],('특이점과 진동 범위를 보존한 개략도.','Schematic preserving the special points and oscillation range.'))
add(7,('g의 그래프는 x=2에서 두 다른 열린 높이로 갈라지고 값은 없으며,x=4에서 서로 다른 한쪽 높이를 갖고 오른쪽 가지 시작은 닫힌 점이다.x=5에는 양쪽으로 이어지는 열린 구멍이 있다.(a)극한은 없고 g(a)는 있음,(b)극한은 있고 g(a)는 없음,(c)두 유한 한쪽 극한은 있지만 양쪽 극한은 없음,(d)오른쪽 극한=g(a),왼쪽 극한≠g(a)인 a를 각각 구하라.','At x=2,g has two different open approaching heights and no value.At4,it has different one-sided limits and a filled right-branch starting point.At5,it has a hole on an otherwise continuous branch.Find a for(a)no limit but defined g(a),(b)a limit but undefined g(a),(c)two finite one-sided limits but no two-sided limit,(d)right limit=g(a) but left limit≠g(a).'),[('각 후보2,4,5에서 극한의 일치 여부와 실제 닫힌 점 여부를 따로 확인한다.','For2,4,5,separately check agreement of the limits and presence of a filled point.')],('(a)4,(b)5,(c)2 또는4,(d)4.','(a)4,(b)5,(c)2 or4,(d)4.'),('2에서는 값 자체가 없어(a),(d)에 쓸 수 없고5에서는 한쪽 극한이 같아(c)에 쓸 수 없다.','At2 there is no function value,excluding(a),(d);at5 the one-sided limits agree,excluding(c).'),list('abcd'))
D.fig(7,[panel('Candidate inputs2,4,5',(-1,7,-2,4),[[(-1,-1),(0,-.5),(1,1.5),(2,2.8)],[(2,1.8),(3,1),(4,.5)],[(4,2.3),(5,1.7),(6,.6),(7,-1.2)]],[(2,2.8,'open'),(2,1.8,'open'),(4,.5,'open'),(4,2.3),(5,1.7,'open')],xticks=[0,2,4,5,6])])
add(8,('A의 그래프는 x=−3에서 양쪽 위로 발산,x=−1에서 양쪽 아래로 발산,x=2에서 왼쪽 아래·오른쪽 위로 발산한다.(a)−3의 극한,(b)2왼쪽,(c)2오른쪽,(d)−1의 극한,(e)수직점근선을 구하라.','The graph A diverges upward on both sides of−3,downward on both sides of−1,and downward on the left/upward on the right of2.Find(a)limit at−3,(b)left at2,(c)right at2,(d)limit at−1,(e)vertical asymptotes.'),[('위로 제한 없이 올라가면+∞,아래로 내려가면−∞로 표시한다.','Unbounded upward behavior is+∞;unbounded downward behavior is−∞.')],('(a)+∞,(b)−∞,(c)+∞,(d)−∞,(e)x=−3,−1,2.','(a)+∞,(b)−∞,(c)+∞,(d)−∞,(e)x=−3,−1,2.'),('수직점근선은 적어도 한쪽의 무한극한으로 확인하며 x축 교점은 점근선과 관계없다.','A vertical asymptote requires an infinite limit from at least one side;ordinary x-intercepts are irrelevant.'),list('abcde'))
add(9,('f의 그래프는 x=−7에서 양쪽 아래로,x=−3과0에서 양쪽 위로,x=6에서 왼쪽 아래·오른쪽 위로 발산한다.(a)−7,(b)−3,(c)0의 극한,(d)6왼쪽,(e)6오른쪽 극한,(f)수직점근선을 구하라.','The graph f diverges down on both sides of−7,up on both sides of−3 and0,and down on the left/up on the right of6.Find(a)limit at−7,(b)at−3,(c)at0,(d)left at6,(e)right at6,(f)vertical asymptotes.'),[('각 수직선의 양쪽에서 곡선이 향하는 위·아래 방향을 따로 읽는다.','Read the upward or downward direction separately on each side of every vertical line.')],('(a)−∞,(b)+∞,(c)+∞,(d)−∞,(e)+∞,(f)x=−7,−3,0,6.','(a)−∞,(b)+∞,(c)+∞,(d)−∞,(e)+∞,(f)x=−7,−3,0,6.'),('6에서는 서로 다른 부호의 발산으로 양쪽 무한극한은 하나로 정할 수 없지만 수직점근선은 존재한다.','At6 the opposite divergence signs prevent a common two-sided infinite limit,but there is still a vertical asymptote.'),list('abcdef'))
add(10,('교재의 약물 그래프에서4시간마다150 mg을 추가하며,t=12 직전 곡선은150 mg,직후 곡선은300 mg에서 시작한다.12의 왼쪽·오른쪽 극한과 의미를 구하라.','In the textbook drug-level graph,150 mg is added every4 hours.The curve approaches150 mg just before t=12 and starts at300 mg just afterward.Find and interpret the one-sided limits at12.'),[('왼쪽 극한은 새 주입 직전 남은 양,오른쪽 극한은 주입 직후의 양이다.','The left limit is the amount remaining before the injection;the right limit is the amount immediately afterward.')],d(r'\lim_{t\to12^-}f(t)=150\ \mathrm{mg},\quad\lim_{t\to12^+}f(t)=300\ \mathrm{mg}'),('두 접근값의 차300−150=150 mg이 주어진 추가량과 일치한다.','The jump300−150=150 mg agrees with the stated added amount.'))
D.fig(10,[panel('Drug amount near the12-hour jump',(8,16,0,330),[[(8,262),(9,226),(10,194),(11,170),(12,150)],[(12,300),(13,262),(14,230),(15,205),(16,187)]],[(12,150),(12,300,'open')],xticks=[8,10,12,14,16],yticks=[0,150,300],xlabel='hours',ylabel='mg')],('12시간의 한쪽 극한을 강조한 교재 자료 개략도.','Schematic of the textbook data emphasizing the one-sided limits at12 hours.'))
for n,expr,ko,en,excluded,curves,dots,bounds in [(11,r'\begin{cases}\cos x&x\le0\\1-x&0<x<1\\1/x&x\ge1\end{cases}','0では左右とも1で一致する。1では左0、右1で不一致である。','At0 both sides approach1.At1 the left limit0 differs from the right limit1.',1,[samples(math.cos,-4,0),[(0,1),(1,0)],samples(lambda z:1/z,1,4)],[(0,1),(1,0,'open'),(1,1)],(-4,4,-1.5,2)),(12,r'\begin{cases}\sqrt[3]x&x\le-1\\x&-1<x\le2\\(x-1)^2&x>2\end{cases}','−1では左右とも−1で一致する。2では左2、右1で不一致である。','At−1 both sides approach−1.At2 the left limit2 differs from the right limit1.',2,[samples(lambda z:math.copysign(abs(z)**(1/3),z),-4,-1),[(-1,-1),(2,2)],samples(lambda z:(z-1)**2,2,4)],[(-1,-1),(2,2),(2,1,'open')],(-4,4,-3,10))]:
 add(n,('함수 '+m('f(x)='+expr)+'를 그리고 lim(x→a)f(x)가 존재하는 a를 구하라.','Sketch '+m('f(x)='+expr)+' and determine all a for which lim(x→a)f(x) exists.'),[('각 조각 내부에서는 연속이므로 접합점의 한쪽 극한만 추가로 검사한다.','Each piece is continuous on its interior,so only junctions require additional one-sided checks.'),(ko,en)],d(r'a\in\mathbb R\setminus\{'+str(excluded)+r'\}'),('각 접합점에서 실제 지정값과 무관하게 두 조각의 접근값을 계산했다.','At each junction the limits of both formulas were evaluated independently of the assigned point value.'))
 D.fig(n,[panel('Piecewise limits',bounds,curves,dots)])
add(13,('f(x)=x√(1+x⁻²)의 그래프에서(a)0왼쪽,(b)0오른쪽,(c)양쪽 극한을 구하라.','Use the graph of f(x)=x√(1+x⁻²) to determine(a)the left limit at0,(b)the right limit,and(c)the two-sided limit.'),[(d(r'x\sqrt{1+x^{-2}}=\frac{x}{|x|}\sqrt{x^2+1}=\begin{cases}-\sqrt{x^2+1}&x<0\\\sqrt{x^2+1}&x>0\end{cases}'),d(r'x\sqrt{1+x^{-2}}=\frac{x}{|x|}\sqrt{x^2+1}=\begin{cases}-\sqrt{x^2+1}&x<0\\\sqrt{x^2+1}&x>0\end{cases}'))],('(a)−1,(b)1,(c)없음.','(a)−1,(b)1,(c)does not exist.'),('√(x²)=|x|이므로 x로 잘못 약분하면 왼쪽 부호를 잃는다.','Since√(x²)=|x|,canceling it as x would incorrectly lose the left-hand sign.'),list('abc'))
D.fig(13,[panel('Opposite limiting heights',(-3,3,-4,4),[samples(lambda z:-math.sqrt(z*z+1),-3,0),samples(lambda z:math.sqrt(z*z+1),0,3)],[(0,-1,'open'),(0,1,'open')])])
add(14,('f(x)=(3^(1/x)−2)/(3^(1/x)+1)의 그래프에서(a)0왼쪽,(b)0오른쪽,(c)양쪽 극한을 구하라.','For f(x)=(3^(1/x)−2)/(3^(1/x)+1),use its graph to find(a)left limit at0,(b)right limit,(c)two-sided limit.'),[('왼쪽에서는1/x→−∞라3^(1/x)→0,오른쪽에서는3^(1/x)→∞이다.','On the left,1/x→−∞ and3^(1/x)→0;on the right,3^(1/x)→∞.'),('u=3^(1/x)로 쓰면 f=(u−2)/(u+1)=1−3/(u+1)이다.','With u=3^(1/x),write f=(u−2)/(u+1)=1−3/(u+1).')],('(a)−2,(b)1,(c)없음.','(a)−2,(b)1,(c)does not exist.'),('분모 u+1은 양수라 다른 특이점은 없고, 두 유한 접근값이 다르다.','The denominator u+1 is positive,and the two finite approaching values differ.'),list('abc'))
def stable14(z):
 if z>0:return 1-3*math.exp(-math.log(3)/z)/(1+math.exp(-math.log(3)/z))
 return 1-3/(1+math.exp(math.log(3)/z))
D.fig(14,[panel('Exponential composition near0',(-2,2,-2.5,1.5),[samples(stable14,-2,-.001),samples(stable14,.001,2)],[(0,-2,'open'),(0,1,'open')])])
construct=[(15,'1의 왼쪽 극한3,오른쪽0, f(1)=2','left limit3 and right limit0 at1,with f(1)=2',r'\begin{cases}3&x<1\\2&x=1\\0&x>1\end{cases}',[[(-2,3),(1,3)],[(1,0),(4,0)]],[(1,3,'open'),(1,0,'open'),(1,2)],(-2,4,-1,4),'1의 각 방향에서 상수값이 곧 극한이며 점값2를 별도로 둔다.','The constant on each side gives its limit;assign2 separately at the point.'),(16,'0의 양쪽 극한4,8의 왼쪽1·오른쪽−3,f(0)=6,f(8)=−1','limit4 at0,left limit1 and right limit−3 at8,with f(0)=6,f(8)=−1',r'\begin{cases}6&x=0\\4-3x/8&x<8,\ x\ne0\\-1&x=8\\-3&x>8\end{cases}',[[(-2,4.75),(8,1)],[(8,-3),(10,-3)]],[(0,4,'open'),(0,6),(8,1,'open'),(8,-3,'open'),(8,-1)],(-2,10,-4,7),'직선4−3x/8은0에서4,8에서1로 접근하며 지정점만 바꾼다.','The line4−3x/8 approaches4 at0 and1 at8;modify only the assigned point values.'),(17,'−1의 왼쪽 극한0·오른쪽1,2의 양쪽 극한3,f(−1)=2,f(2)=1','left limit0 and right limit1 at−1,limit3 at2,with f(−1)=2,f(2)=1',r'\begin{cases}0&x<-1\\2&x=-1\\(2x+5)/3&x>-1,\ x\ne2\\1&x=2\end{cases}',[[(-3,0),(-1,0)],[(-1,1),(4,13/3)]],[(-1,0,'open'),(-1,1,'open'),(-1,2),(2,3,'open'),(2,1)],(-3,4,-1,5),'오른쪽 직선은−1에서1,2에서3의 높이를 갖고 두 점의 지정값은 별도로 둔다.','The right line has heights1 at−1 and3 at2;assign the two point values separately.'),(18,'−3의 왼쪽 극한3·오른쪽2,3의 왼쪽−1·오른쪽2,f(−3)=2,f(3)=0','left/right limits3/2 at−3 and−1/2 at3,with f(−3)=2,f(3)=0',r'\begin{cases}3&x<-3\\(1-x)/2&-3\le x<3\\0&x=3\\2&x>3\end{cases}',[[(-5,3),(-3,3)],[(-3,2),(3,-1)],[(3,2),(5,2)]],[(-3,3,'open'),(-3,2),(3,-1,'open'),(3,2,'open'),(3,0)],(-5,5,-2,4),'중간 직선(1−x)/2의 끝 접근값은2와−1이다.','The middle line(1−x)/2 has endpoint limits2 and−1.')]
for n,st,se,expr,curves,dots,bounds,ko,en in construct:
 add(n,('조건 '+st+'을 모두 만족하는 함수의 예를 그려라.','Sketch an example satisfying '+se+'.'),[(ko,en)],d('f(x)='+expr),('제시한 조각식을 각 경계의 왼쪽·오른쪽과 지정점에 대입해 모든 조건을 개별 확인했다. 예는 유일하지 않다.','Checked every condition separately using the left piece,right piece,and assigned point at each boundary. The example is not unique.'))
 D.fig(n,[panel('Constructed example',bounds,curves,dots)])
x19=['3.1','3.05','3.01','3.001','3.0001','2.9','2.95','2.99','2.999','2.9999'];x20=['-2.5','-2.9','-2.95','-2.99','-2.999','-2.9999','-3.5','-3.1','-3.05','-3.01','-3.001','-3.0001']
for n,at,items,ans,anse,ko,en in [(19,3,x19,'1/2','1/2','x=3の前後で値は0.5に近づく。','Values on both sides of3 approach0.5.'),(20,-3,x20,'양쪽 극한 없음;왼쪽+∞,오른쪽−∞.','No two-sided limit;left+∞,right−∞.','x+3의 부호가 바뀌므로 음수인 분자 x와의 비가 반대 부호로 발산한다.','The denominator x+3 changes sign,so the negative numerator x gives divergences of opposite signs.')]:
 tab=vals(lambda z:z/(z+3),items)
 if n==19:ko='x=3의 양쪽에서 값이0.5로 가까워진다.'
 add(n,('함수 (x²−3x)/(x²−9)를 x='+','.join(items)+'에서6자리로 계산하여 x→'+str(at)+'의 극한을 추정하라.','Evaluate(x²−3x)/(x²−9) at x='+','.join(items)+' to6 decimals and estimate the limit as x→'+str(at)+'.'),[(d(r'\frac{x^2-3x}{x^2-9}=\frac{x}{x+3}\quad(x\ne\pm3)'),d(r'\frac{x^2-3x}{x^2-9}=\frac{x}{x+3}\quad(x\ne\pm3)')),(tab,tab),(ko,en)],(ans,anse),('계산은 약분식으로 수행하되 x=±3의 원래 제외조건을 보존했다.','Used the canceled expression for calculation while retaining the original exclusions x=±3.'))
items21=[sign*mp.mpf(q)for q in ['1','.5','.2','.1','.05','.01']for sign in [1,-1]];tab21=vals(lambda z:mp.sin(z)/(z+mp.tan(z)),items21)
add(21,('sin x/(x+tan x)를 x=±1,±0.5,±0.2,±0.1,±0.05,±0.01에서6자리로 계산해0의 극한을 추정하라(라디안).','Evaluate sin x/(x+tan x) at x=±1,±0.5,±0.2,±0.1,±0.05,±0.01 to6 decimals and estimate the limit at0(radians).'),[(tab21,tab21),(d(r'\frac{\sin x}{x+\tan x}=\frac{\sin x/x}{1+\tan x/x}\longrightarrow\frac1{1+1}'),d(r'\frac{\sin x}{x+\tan x}=\frac{\sin x/x}{1+\tan x/x}\longrightarrow\frac1{1+1}'))],d('1/2'),('분자와 분모가 모두 홀수여서 비는 짝함수이다. ±x의 표값이 일치하는 것도 확인했다.','Both numerator and denominator are odd,so their ratio is even;the tabulated values at±x agree.'))
items22=[sign*mp.mpf(q)for q in ['.5','.1','.01','.001','.0001']for sign in [1,-1]];tab22=vals(lambda z:((2+z)**5-32)/z,items22)
add(22,('((2+h)⁵−32)/h를 h=±0.5,±0.1,±0.01,±0.001,±0.0001에서6자리로 계산해0의 극한을 추정하라.','Evaluate((2+h)⁵−32)/h for h=±0.5,±0.1,±0.01,±0.001,±0.0001 to6 decimals and estimate the limit at0.'),[(tab22,tab22),(d(r'\frac{(2+h)^5-32}h=80+80h+40h^2+10h^3+h^4\quad(h\ne0)'),d(r'\frac{(2+h)^5-32}h=80+80h+40h^2+10h^3+h^4\quad(h\ne0)'))],d('80'),('이항전개에서 상수32가 상쇄되고 h를 약분한 식을 다시 곱해 원분자를 확인했다.','The binomial expansion cancels32;multiplication by h restores the original numerator.'))
for n,expr,approach,fn,items,res,ko,en in [(23,r'\sin(3\theta)/\tan(2\theta)',r'\theta\to0',lambda z:mp.sin(3*z)/mp.tan(2*z),['-.1','-.01','-.001','.001','.01','.1'],'3/2','sin(3θ)/(3θ)와 tan(2θ)/(2θ)가 각각1로 가므로 비의 계수는3/2이다.','Both sin(3θ)/(3θ) and tan(2θ)/(2θ) tend to1,leaving the factor3/2.'),(24,r'(1+p^9)/(1+p^{15})',r'p\to-1',lambda z:(1+z**9)/(1+z**15),['-1.1','-1.01','-1.001','-.999','-.99','-.9'],'3/5','분자·분모의 공통인수 p+1을 없앤 뒤 p=−1을 넣으면 각각9와15이다.','Cancel the common factor p+1;at p=−1 the remaining sums evaluate to9 and15.'),(25,'x^x',r'x\to0^+',lambda z:z**z,['.1','.01','.001','.0001','.00001'],'1','xˣ=exp(x ln x)이고 x ln x→0이므로1에 접근한다.','Since xˣ=exp(x ln x) and x ln x→0,the limit is1.'),(26,r'(5^t-1)/t',r't\to0',lambda z:mp.expm1(z*mp.log(5))/z,['-.1','-.01','-.001','.001','.01','.1'],r'\ln5\approx1.609437912','밑5의 지수함수에서0 근처의 변화율은 ln5이다. 표는 약1.60944로 양쪽에서 접근한다.','The local rate of the base5 exponential at0 is ln5.The table approaches approximately1.60944 from both sides.')]:
 tab=vals(fn,items,9)
 add(n,('함수 '+m(expr)+'의 '+m(approach)+' 극한을 수치표로 추정하고 그래프로 확인하라.','Estimate the limit of '+m(expr)+' as '+m(approach)+' using a value table and confirm graphically.'),[(tab,tab),(ko,en)],d(res),('60자리 계산으로 작은 차의 소거오차를 줄였고, 양쪽이 필요한 경우 두 방향을 모두 검사했다.','Used60-digit arithmetic to reduce cancellation error and checked both directions where required.'))
 if n==24:curves=[samples(lambda z:float(fn(mp.mpf(z))),-1.1,-1.00001),samples(lambda z:float(fn(mp.mpf(z))),-.99999,-.9)];bounds=(-1.1,-.9,.3,.9)
 elif n==25:curves=[samples(lambda z:z**z,.000001,.2)];bounds=(0,.2,.6,1.05)
 else:curves=[samples(lambda z:float(fn(mp.mpf(z))),-.1,-.00001),samples(lambda z:float(fn(mp.mpf(z))),.00001,.1)];bounds=(-.1,.1,1.2,1.9)
 D.fig(n,[panel('Numerical limit check',bounds,curves)])
x=s.symbols('x',real=True)
infs=[(27,(x+1)/(x-5),5,'+',s.oo,'분자→6>0,분모→0⁺.','Numerator→6>0,denominator→0⁺.'),(28,(x+1)/(x-5),5,'-',-s.oo,'분자→6>0,분모→0⁻.','Numerator→6>0,denominator→0⁻.'),(29,x*x/(x-2)**2,2,'+-',s.oo,'분자→4>0이고 제곱 분모는 양쪽에서0⁺.','Numerator→4>0;the squared denominator tends to0⁺ from both sides.'),(30,s.sqrt(x)/(x-3)**5,3,'-',-s.oo,'분자는 양수,홀수 거듭제곱 분모는 왼쪽에서0⁻.','The numerator is positive;the odd-power denominator tends to0⁻ on the left.'),(31,(x-1)/(x*x*(x+2)),-2,'+',-s.oo,'분자→−3,분모 x²(x+2)→0⁺.','Numerator→−3;denominator x²(x+2)→0⁺.'),(32,(x-1)/(x*x*(x+2)),0,'+-',-s.oo,'분자→−1,분모는 양쪽에서0⁺.','Numerator→−1;the denominator tends to0⁺ on both sides.'),(33,s.sec(x)/x,s.pi/2,'-',None,'','')]
# Source33 is the RIGHT-HAND limit at pi/2.
infs[-1]=(33,s.sec(x)/x,s.pi/2,'+',-s.oo,'cos x→0⁻,1/x→2/π>0.','cos x→0⁻ while1/x→2/π>0.')
infs += [(34,x*s.cot(x),s.pi,'-',-s.oo,'cos x→−1,sin x→0⁺,x→π>0.','cos x→−1,sin x→0⁺,x→π>0.'),(35,(x*x+2*x)/(x*x-2*x+1),1,'+-',s.oo,'分母は(x−1)²、分子は3に近づく。','The denominator is(x−1)² and the numerator approaches3.'),(36,(x*x+4*x)/(x*x-2*x-3),3,'-',-s.oo,'분모(x−3)(x+1)→0⁻,분자→21.','Denominator(x−3)(x+1)→0⁻;numerator→21.')]
for n,f,a,side,value,ko,en in infs:
 if n==35:ko='분모는(x−1)²이고 분자는3에 가까워진다.'
 lim=d(r'\lim_{x\to '+tex(a)+('^'+side if side!='+-'else'')+r'}'+tex(f))
 for direct in (['-','+']if side=='+-'else[side]):
  got=s.limit(f,x,a,dir=direct);assert got==value,(n,got,value)
 D.checks.append({'number':n,'method':'independent symbolic one-sided limit','value':str(value)})
 add(n,('무한극한 '+lim+'을 구하라.','Determine the infinite limit '+lim+'.'),[(ko,en),('0에 가까운 분모의 부호와 0이 아닌 분자의 부호를 곱해 발산 방향을 정한다.','Combine the denominator’s near-zero sign with the nonzero numerator’s sign to determine divergence.')],d(tex(value)),('원식의 한쪽 기호극한을 별도로 계산해 같은 발산 방향을 확인했다.','A separate symbolic one-sided limit confirms the divergence direction.'))
add(37,('f(x)=(x−1)/(2x+4)의 수직점근선을 구하라.','Find the vertical asymptote of f(x)=(x−1)/(2x+4).'),[('분모2(x+2)가0인 x=−2에서 분자는−3으로0이 아니다.','The denominator2(x+2) vanishes at−2 while the numerator is−3,not zero.')],d('x=-2'),('x→−2⁻에서는+∞,x→−2⁺에서는−∞로 발산하므로 단순 구멍이 아니다.','The limits are+∞ from the left and−∞ from the right,so this is not a removable hole.'))
add(38,('(a)y=(x²+1)/(3x−2x²)의 수직점근선을 구하고(b)그래프로 확인하라.','(a)Find the vertical asymptotes of y=(x²+1)/(3x−2x²);(b)confirm with a graph.'),[('분모는 x(3−2x)이고 분자 x²+1은 모든 실수에서 양수이다.','The denominator is x(3−2x),while x²+1 is positive for all real x.')],d(r'x=0,\quad x=3/2'),('0에서는 왼쪽−∞·오른쪽+∞,3/2에서는 왼쪽+∞·오른쪽−∞이다.','At0 the limits are−∞ on the left and+∞ on the right;at3/2 they are+∞ on the left and−∞ on the right.'),list('ab'))
D.fig(38,[panel('Vertical asymptotes0 and1.5',(-3,4,-10,10),[samples(lambda z:(z*z+1)/(3*z-2*z*z),lo,hi)for lo,hi in [(-3,-.01),(.01,1.49),(1.51,4)]],xticks=[-3,-1,0,1.5,3,4])])
xs39=['.9','.99','.999','1.001','1.01','1.1'];tab39=vals(lambda z:1/(z**3-1),xs39)
add(39,('1/(x³−1)의 x→1⁻,x→1⁺ 극한을(a)수치표,(b)부호 논리,(c)그래프로 구하라.','Determine the left and right limits of1/(x³−1) at1 using(a)a value table,(b)sign reasoning,(c)a graph.'),[(tab39,tab39),(d(r'x^3-1=(x-1)(x^2+x+1),\quad x^2+x+1>0'),d(r'x^3-1=(x-1)(x^2+x+1),\quad x^2+x+1>0')),('따라서 분모 부호는 x−1과 같고 크기는0으로 간다.','Thus the denominator has the sign of x−1 and tends to zero in magnitude.')],d(r'\lim_{x\to1^-}\frac1{x^3-1}=-\infty,\quad\lim_{x\to1^+}\frac1{x^3-1}=+\infty'),('양의 이차식은(x+1/2)²+3/4로 다시 써서 모든 실수에서 양수임을 확인한다.','Writing the quadratic as(x+1/2)²+3/4 confirms strict positivity for every real input.'),list('abc'))
D.fig(39,[panel('Reciprocal cubic near1',(-1,3,-10,10),[samples(lambda z:1/(z**3-1),-1,.99),samples(lambda z:1/(z**3-1),1.01,3)],xticks=[-1,0,1,2,3])])
xs40=['-.1','-.01','-.001','.001','.01','.1'];fn40=lambda z:-2*mp.sin(3*z/2)*mp.sin(z/2)/(z*z);tab40=vals(fn40,xs40,9)
add(40,('(a)f(x)=(cos2x−cos x)/x²를 그려0근처를 확대하여 극한을 추정하고(b)작은 양·음 입력의 표로 확인하라.','(a)Graph f(x)=(cos2x−cos x)/x² and zoom near0 to estimate the limit;(b)check with small positive and negative inputs.'),[(tab40,tab40),(d(r'\frac{\cos2x-\cos x}{x^2}=-\frac32\frac{\sin(3x/2)}{3x/2}\frac{\sin(x/2)}{x/2}\longrightarrow-\frac32'),d(r'\frac{\cos2x-\cos x}{x^2}=-\frac32\frac{\sin(3x/2)}{3x/2}\frac{\sin(x/2)}{x/2}\longrightarrow-\frac32'))],d('-3/2'),('차가 작은 두 코사인을 직접 빼는 대신 곱 공식으로 계산하여 소거오차를 줄였다. f(0)은 원식에서 정의되지 않는다.','Used a product identity instead of subtracting nearly equal cosines to reduce cancellation.The original f(0) is undefined.'),list('ab'))
D.fig(40,[panel('Limit of cosine difference',(-1,1,-1.6,-.9),[samples(lambda z:float(fn40(mp.mpf(z))),-1,-.0001),samples(lambda z:float(fn40(mp.mpf(z))),.0001,1)],[(0,-1.5,'open')]),panel('Zoom near0',(-.05,.05,-1.5001,-1.498),[samples(lambda z:float(fn40(mp.mpf(z))),-.05,-.00001),samples(lambda z:float(fn40(mp.mpf(z))),.00001,.05)],[(0,-1.5,'open')])])
xa41=['1','.8','.6','.4','.2','.1','.05'];xb41=['.04','.02','.01','.005','.003','.001'];fn41=lambda z:z*z-mp.power(2,z)/1000
add(41,('f(x)=x²−2ˣ/1000에 대해(a)x=1,0.8,0.6,0.4,0.2,0.1,0.05의 값을 계산해0의 극한을 추정하고,(b)x=0.04,0.02,0.01,0.005,0.003,0.001로 다시 판단하라.','For f(x)=x²−2ˣ/1000,(a)evaluate x=1,0.8,0.6,0.4,0.2,0.1,0.05 and guess the limit at0;(b)reconsider using x=0.04,0.02,0.01,0.005,0.003,0.001.'),[('(a)'+vals(fn41,xa41,9),'(a)'+vals(fn41,xa41,9)),('처음 표만 보면0으로 오해하기 쉽지만 충분히 작은 입력에서 음수값이 나타난다.','The first table can misleadingly suggest0,but sufficiently small inputs produce negative values.'),('(b)'+vals(fn41,xb41,9),'(b)'+vals(fn41,xb41,9)),('연속식에0을 대입하면0−1/1000이다.','Substitution into the continuous expression at0 gives0−1/1000.')],d('-1/1000=-0.001'),('2ˣ→1이므로 작은 보정항은0이 아니라−0.001로 남는다.','Since2ˣ→1,the small correction term remains−0.001 rather than vanishing.'),list('ab'))
xa42=['1','.5','.1','.05','.01','.005'];fn42=lambda z:(mp.tan(z)-z)/(z**3);small42=[10.0**(-k)for k in range(3,13)];double42=[(z,(math.tan(z)-z)/z**3)for z in small42];firstzero=next(z for z,v in double42 if v==0)
add(42,('h(x)=(tan x−x)/x³에 대해(a)x=1,0.5,0.1,0.05,0.01,0.005의 값,(b)0의 극한 추정,(c)작은 입력에서 기계계산이0이 되는 이유,(d)[−1,1]×[0,1] 그래프와 확대 시 왜곡을 조사하라.','For h(x)=(tan x−x)/x³,investigate(a)values at1,0.5,0.1,0.05,0.01,0.005,(b)the limit at0,(c)why small-input machine calculations eventually give zero,and(d)the graph on[−1,1]×[0,1] and distortions under zooming.'),[('(a)'+vals(fn42,xa42,9),'(a)'+vals(fn42,xa42,9)),('(b)값은1/3에 가까워진다. 독립 검산으로 tan x=x+x³/3+O(x⁵)를 쓰면1/3이 확인된다.','(b)The values approach1/3.As an independent check,tan x=x+x³/3+O(x⁵) confirms that limit.'),('(c)실제로 이 환경의 배정밀도 직접 계산은 '+str(double42)+f'를 주며 처음0인 예는 x={firstzero:g}이다.','(c)Actual double-precision direct evaluations in this environment are '+str(double42)+f';the first zero in this sequence occurs at x={firstzero:g}.'),('tan x와 x의 차는 약x³/3으로 매우 작다. 반올림으로 두 값이 같아지면 차가0이 되고,x³으로 나누어도0이다. 확대 그래프의 평탄화·튀는 값은 같은 수치오차이다.','The difference tan x−x is only about x³/3.Rounding can make the two terms equal,so their difference and the quotient become zero.Flattening or spikes in the zoomed graph reflect the same numerical error.')],d(r'\lim_{x\to0}h(x)=1/3'),('60자리 계산과 급수 계수는1/3에 일치한다. 기계에서0이 되는 임계값은 구현·정밀도에 따라 달라지며 실제 극한이 바뀌는 것은 아니다.','The60-digit calculation and series coefficient agree at1/3.The machine-zero threshold depends on implementation and precision;it does not change the true limit.'),list('abcd'))
D.fig(42,[panel('High-precision h(x)',(-1,1,0,1),[samples(lambda z:float(fn42(mp.mpf(z))),-1,-.0001),samples(lambda z:float(fn42(mp.mpf(z))),.0001,1)],[(0,1/3,'open')]),panel('Direct double precision: zoomed cancellation',(-1e-7,1e-7,-.1,1),[samples(lambda z:(math.tan(z)-z)/z**3,-1e-7,-1e-10,500),samples(lambda z:(math.tan(z)-z)/z**3,1e-10,1e-7,500)])])
alpha=math.asin(math.pi/4);asym=[-math.pi+alpha,-alpha,alpha,math.pi-alpha]
add(43,('y=tan(2sin x),−π≤x≤π의 그래프에서 모든 수직점근선을 추정하고 정확한 식을 구하라.','Use the graph of y=tan(2sin x),−π≤x≤π,to estimate all vertical asymptotes and then find their exact equations.'),[('탄젠트가 발산하려면2sin x=π/2+kπ이다. 범위가[−2,2]이므로 가능한 값은±π/2뿐이다.','Tangent has poles when2sin x=π/2+kπ.With2sin x in[−2,2],only±π/2 are possible.'),(d(r'\sin x=\pm\pi/4,\quad\alpha=\arcsin(\pi/4)'),d(r'\sin x=\pm\pi/4,\quad\alpha=\arcsin(\pi/4)'))],d(r'x=-\pi+\alpha,\ -\alpha,\ \alpha,\ \pi-\alpha')+'; '+', '.join(f'{z:.6f}'for z in asym),('각 점에서 cos x≠0이어서2sin x가 탄젠트의 극점을 실제로 통과하므로 수직점근선이 된다.','At each point cos x≠0,so2sin x crosses a tangent pole,producing a vertical asymptote.'))
cuts=[-math.pi]+asym+[math.pi]
D.fig(43,[panel('tan(2 sin x)',(-math.pi,math.pi,-10,10),[samples(lambda z:math.tan(2*math.sin(z)),lo+.001,hi-.001)for lo,hi in zip(cuts,cuts[1:])],xticks=[-math.pi,-alpha,0,alpha,math.pi])])
add(44,('f(x)=tan(1/x)에 대해(a)x=1/π,1/(2π),1/(3π),…에서0,(b)x=4/π,4/(5π),4/(9π),…에서1임을 보이고(c)x→0⁺의 극한을 판단하라.','For f(x)=tan(1/x),show(a)it is zero at1/π,1/(2π),1/(3π),…,(b)it is one at4/π,4/(5π),4/(9π),…;then(c)determine whether the right-hand limit at0 exists.'),[(d(r'x_n=1/(n\pi)\Longrightarrow f(x_n)=\tan(n\pi)=0'),d(r'x_n=1/(n\pi)\Longrightarrow f(x_n)=\tan(n\pi)=0')),(d(r'y_n=4/((4n+1)\pi)\Longrightarrow f(y_n)=\tan(n\pi+\pi/4)=1'),d(r'y_n=4/((4n+1)\pi)\Longrightarrow f(y_n)=\tan(n\pi+\pi/4)=1')),('두 양의 수열은0으로 가지만 함수값의 극한이0과1로 다르다.','Both positive sequences approach0,but their function values tend to0 and1.')],('오른쪽 극한은 존재하지 않는다.','The right-hand limit does not exist.'),('첫 수열은 n≥1,두 번째는 n≥0로 정의한다. 모든 항에서 탄젠트가 정의되어 수열 반례가 유효하다.','Use n≥1 for the first sequence and n≥0 for the second.Tangent is defined at every selected input,so both sequences are valid counterexamples.'),list('abc'))
add(45,('주어진 상대론 모형 m=m₀/√(1−v²/c²)에서 양의 정지질량 m₀를 갖는 입자의 v→c⁻일 때 m의 거동을 구하라.','In the given relativistic model m=m₀/√(1−v²/c²),determine the behavior as v→c⁻ for a particle with positive rest mass m₀.'),[('v<c에서 근호 내부는 양수이고 v→c⁻일 때0⁺로 간다. 분자 m₀는 고정 양수이다.','For v<c the radicand is positive and approaches0⁺ as v→c⁻.The numerator m₀ is fixed and positive.')],d(r'\lim_{v\to c^-}m=+\infty'),('v=c에서는 분모가0이라 식이 정의되지 않으며 무한극한은 그 값에 접근할 때 제한 없이 증가함을 뜻한다.','At v=c the denominator is zero and the expression is undefined;the infinite limit describes unbounded growth while approaching that speed.'))
D.save(45)
