"""Source-checked arc length, curvature, moving frames, and torsion: Exercises 1–78."""
from early_helpers import Book
from pathlib import Path
import sympy as s, mpmath as mp, json
b=Book('13.3',[951,952,953,954]);t=s.symbols('t',real=True);x=t;M=s.Matrix;R=s.Rational;checks=[]
def tex(z):return s.latex(s.simplify(z))
def v(z):return r'\langle '+','.join(tex(a) for a in z)+r'\rangle'
def m(z):return r'\('+z+r'\)'
def eq(label,z):
 assert all(s.simplify(a)==0 for a in z) if isinstance(z,s.MatrixBase) else (s.simplify(z)==0 or s.simplify(z.rewrite(s.exp))==0),(label,z)
 checks.append(label)
def add(n,k,e,ks,es,ans,ae=None,parts=[]):
 b.add(n,951 if n<=27 else 952 if n<=54 else 953 if n<=76 else 954,('호의 길이와 곡률','Arc length and curvature'),(k,e),list(zip(ks,es)),(ans,ans if ae is None else ae),parts,check=('도함수·벡터곱·적분 또는 증명의 각 등식을 원래 조건과 대조했다. 수치값은 정밀도를 높여 재계산했다.','Checked derivatives, cross products, integrals, or each proof identity against the original conditions. Numerical values were recomputed at higher precision.'));b.E[n]['conceptHref']='../../calc1/index.html'
def numeric(f,a,c):
 ff=s.lambdify(t,f,'mpmath');vals=[]
 for dps in [30,50]:
  with mp.workdps(dps):
   lo=mp.mpf(str(s.N(a,55)));hi=mp.mpf(str(s.N(c,55)));vals.append(mp.quad(ff,[lo+(hi-lo)*j/64 for j in range(65)]))
 assert abs(vals[0]-vals[1])<mp.mpf('1e-20');checks.append('quadrature precision agreement');return float(vals[-1])
rows=[(1,[3-t,2*t,4*t+1],1,3,2*s.sqrt(21)),(2,[t+2,-t,3*t-5],-1,2,3*s.sqrt(11)),(3,[t,3*s.cos(t),3*s.sin(t)],-5,5,10*s.sqrt(10)),(4,[2*t,t*t,t**3/3],0,1,R(7,3)),(5,[s.sqrt(2)*t,s.exp(t),s.exp(-t)],0,1,s.E-1/s.E),(6,[s.cos(t),s.sin(t),s.log(s.cos(t))],0,s.pi/4,s.log(1+s.sqrt(2))),(7,[1,t*t,t**3],0,1,(13**R(3,2)-8)/27),(8,[t*t,9*t,4*t**R(3,2)],1,4,42),(9,[t*t,t**3,t**4],0,2,None),(10,[t,s.exp(-t),t*s.exp(-t)],1,3,None),(11,[s.cos(s.pi*t),2*t,s.sin(2*s.pi*t)],0,2,None),(12,[s.sin(t),s.sin(2*t),s.sin(3*t)],0,2*s.pi,None),(14,[s.cos(t),2*s.sin(t),2-s.cos(t)-2*s.sin(t)],0,2*s.pi,None)]
for n,ff,lo,hi,answer in rows:
 r=M(ff);d=r.diff(t);q=s.trigsimp(d.dot(d));speed=s.sqrt(q)
 if n==4:speed=t*t+2
 if n==5:speed=s.exp(t)+s.exp(-t)
 if n==6:speed=s.sec(t)
 if n==7:speed=t*s.sqrt(4+9*t*t)
 if n==8:speed=2*t+9
 val=numeric(speed,lo,hi)
 if answer is not None:assert abs(float(answer)-val)<1e-9;checks.append(f'{n} exact length vs quadrature')
 ans=m('L='+tex(answer)) if answer is not None else m(rf'L\approx{val:.4f}')
 statement=m('r(t)='+v(r)+r',\quad '+tex(lo)+r'\le t\le '+tex(hi))
 k=statement+'의 호의 길이를 구하라.';e='Find the arc length of '+statement+'.'
 if n<=2:k+=' (a)속력 적분과(b)끝점 거리로 각각 계산하라.';e+=' (a)Integrate speed and(b)use endpoint distance.'
 if n in [9,10,11,12,14]:k+=' 소수 넷째 자리까지 구하라.';e+=' Give four decimal places.'
 if n==12:k+=' 곡선도 그려라.';e+=' Also graph the curve.'
 if n==14:k='원기둥4x²+y²=4와 평면x+y+z=2의 교선 길이를 소수 넷째 자리까지 구하라.';e='Find the length of the intersection of4x²+y²=4 and x+y+z=2 to four decimal places.'
 ks=[m(r"r^{\prime}(t)="+v(d)),m(r'|r^{\prime}(t)|='+tex(speed)),m(r'L=\int_{'+tex(lo)+'}^{'+tex(hi)+'}'+tex(speed)+r'\,dt')];es=ks.copy()
 if n in [3,4,5,6,7,8]:
  anti={3:s.sqrt(10)*t,4:t**3/3+2*t,5:s.exp(t)-s.exp(-t),6:s.log(s.sec(t)+s.tan(t)),7:(4+9*t*t)**R(3,2)/27,8:t*t+9*t}[n]
  eq(f'{n} antiderivative',s.trigsimp(s.diff(anti,t)-speed));ks.append(m('F(t)='+tex(anti)));es.append(m('F(t)='+tex(anti)))
 if n<=2:
  dist=s.simplify((r.subs(t,hi)-r.subs(t,lo)).norm());eq(f'{n} distance',dist-answer);ks+=['(b)끝점 차의 길이도 '+m(tex(dist))+'로 같으며 선분은 한 번만 지난다.'];es+=['(b)The norm of the endpoint difference is also '+m(tex(dist))+'. The segment is traversed once.']
 if n==12:ks+=['세 성분의 공통 주기는2π이다. 이 구간에서 유한개의 자기교차는 길이를 중복시키는 구간을 만들지 않는다.'];es+=['The common period is2π. The finitely many self-intersections do not create a retraced arc.']
 if n==14:ks.insert(0,'타원에 x=cos t,y=2sin t를 넣고 평면에서z를 구하면 위 매개식이 얻어진다.');es.insert(0,'Set x=cos t,y=2sin t on the ellipse and solve the plane equation for z to obtain this parametrization.')
 add(n,k,e,ks,es,ans,parts=list('ab')if n<=2 else[])
add(13,'x²=2y,3z=xy의 교선을 원점부터(6,18,36)까지 따라간 길이를 구하라.','Find the length along x²=2y,3z=xy from the origin to(6,18,36).',[m(r'r(t)=\langle t,t^2/2,t^3/6\rangle,\quad0\le t\le6'),m(r'|r^{\prime}|=\sqrt{1+t^2+t^4/4}=1+t^2/2'),m(r'L=\int_0^6(1+t^2/2)\,dt=[t+t^3/6]_0^6')],[m(r'r(t)=\langle t,t^2/2,t^3/6\rangle,\quad0\le t\le6'),m(r'|r^{\prime}|=\sqrt{1+t^2+t^4/4}=1+t^2/2'),m(r'L=\int_0^6(1+t^2/2)\,dt=[t+t^3/6]_0^6')],m('L=42'))
add(15,'r(t)=(5−t,4t−3,3t),P=(4,1,3). (a)P에서 증가하는t방향의 호길이s로 재매개화하고(b)4단위 뒤의 점을 구하라.','For r(t)=(5−t,4t−3,3t),P=(4,1,3), (a)reparametrize by arc length from P toward increasing t;(b)find the point4 units later.',[m(r't_P=1,\quad|r^{\prime}|=\sqrt{26},\quad s=\sqrt{26}(t-1)'),m(r't=1+s/\sqrt{26}'),'(b)재매개식에s=4를 넣는다.'],[m(r't_P=1,\quad|r^{\prime}|=\sqrt{26},\quad s=\sqrt{26}(t-1)'),m(r't=1+s/\sqrt{26}'),'(b)Set s=4 in the reparametrization.'],m(r'r(s)=\langle4,1,3\rangle+\frac{s}{\sqrt{26}}\langle-1,4,3\rangle')+'; '+m(r'P_4=(4-4/\sqrt{26},1+16/\sqrt{26},3+12/\sqrt{26})'),parts=list('ab'))
add(16,'r(t)=eᵗ(sin t,cos t,√2),P=(0,1,√2). (a)P에서 증가하는t방향의 호길이s로 재매개화하고(b)4단위 뒤의 점을 구하라.','For r(t)=eᵗ(sin t,cos t,√2),P=(0,1,√2), (a)reparametrize by arc length from P toward increasing t;(b)find the point4 units later.',[m(r't_P=0,\quad |r^{\prime}|=2e^t,\quad s=2(e^t-1)'),m(r'u=\ln(1+s/2),\quad t=u'),'(b)s=4이면eᵗ=3,t=ln3이다.'],[m(r't_P=0,\quad |r^{\prime}|=2e^t,\quad s=2(e^t-1)'),m(r'u=\ln(1+s/2),\quad t=u'),'(b)At s=4, eᵗ=3 and t=ln3.'],m(r'r(s)=(1+s/2)\langle\sin u,\cos u,\sqrt2\rangle')+'; '+m(r'P_4=(3\sin\ln3,3\cos\ln3,3\sqrt2)'),parts=list('ab'))
add(17,'(3sin t,4t,3cos t)를(0,0,3)에서 양의 방향으로5단위 따라간 점을 구하라.','Move5 units in the positive direction along(3sin t,4t,3cos t)starting at(0,0,3). Find the endpoint.',[m(r't_0=0,\quad|r^{\prime}|=\sqrt{9\cos^2t+16+9\sin^2t}=5'),m(r'5=\int_0^t5\,du\Rightarrow t=1')],[m(r't_0=0,\quad|r^{\prime}|=\sqrt{9\cos^2t+16+9\sin^2t}=5'),m(r'5=\int_0^t5\,du\Rightarrow t=1')],m(r'(3\sin1,4,3\cos1)'))
add(18,m(r'r(t)=\langle2/(1+t^2)-1,2t/(1+t^2)\rangle')+'를(1,0)에서 증가하는t방향의 호길이로 재매개화하고 곡선을 설명하라.','Reparametrize '+m(r'r(t)=\langle2/(1+t^2)-1,2t/(1+t^2)\rangle')+' by arc length from(1,0)toward increasing t, and identify the curve.',[m(r'|r^{\prime}|=2/(1+t^2),\quad s=\int_0^t\frac2{1+u^2}\,du=2\arctan t'),m(r't=\tan(s/2),\quad-\pi<s<\pi'),'반각공식을 대입한다. 실수t전체는(-1,0)을 제외한 단위원을 한 번 지난다.'],[m(r'|r^{\prime}|=2/(1+t^2),\quad s=\int_0^t\frac2{1+u^2}\,du=2\arctan t'),m(r't=\tan(s/2),\quad-\pi<s<\pi'),'Substitute the half-angle identities. Real t traverses the unit circle once, omitting(-1,0).'],m(r'r(s)=\langle\cos s,\sin s\rangle,\quad-\pi<s<\pi'))
# Frame calculations use the perpendicular acceleration, avoiding expensive radical derivatives.
frame_rows=[(19,[t*t,s.sin(t)-t*s.cos(t),s.cos(t)+t*s.sin(t)]),(20,[5*s.sin(t),t,5*s.cos(t)]),(21,[t,t*t,4]),(22,[t,t,t*t/2]),(23,[t,t*t/2,t*t]),(24,[s.sqrt(2)*t,s.exp(t),s.exp(-t)])]
for n,ff in frame_rows:
 r=M(ff);d=r.diff(t);a=d.diff(t);q=s.trigsimp(d.dot(d));per=s.simplify(a-d*d.dot(a)/q)
 if n==19:T=M([2,s.sin(t),s.cos(t)])/s.sqrt(5);N=M([0,s.cos(t),-s.sin(t)]);kap=1/(5*t)
 elif n==24:T=d/(s.exp(t)+s.exp(-t));N=M([-s.sqrt(2)*s.sinh(t),1,1])/(s.sqrt(2)*s.cosh(t));kap=1/(2*s.sqrt(2)*s.cosh(t)**2)
 else:T=s.simplify(d/s.sqrt(q));N=s.simplify(per/s.sqrt(s.trigsimp(per.dot(per))));kap=s.simplify(s.sqrt(s.trigsimp(d.cross(a).dot(d.cross(a))))/q**R(3,2))
 eq(f'{n} unit T',s.trigsimp(T.dot(T)-1));eq(f'{n} unit N',s.trigsimp(N.dot(N)-1));eq(f'{n} orthogonality',s.trigsimp(T.dot(N)));eq(f'{n} curvature identity',s.trigsimp(T.diff(t).dot(T.diff(t))-kap**2*q))
 add(n,m('r(t)='+v(r))+('，t>0'if n==19 else'')+'에 대해(a)T,N을 구하고(b)κ=|T′|/|r′|로 곡률을 구하라.','For '+m('r(t)='+v(r))+(', t>0'if n==19 else'')+', (a)find T,N;(b)use κ=|T′|/|r′| to find curvature.',[m(r'v=|r^{\prime}|=\sqrt{'+tex(q)+'}'),m(r'T=r^{\prime}/v,\quad N=T^{\prime}/|T^{\prime}|'),m(r'\kappa=|T^{\prime}|/v')],[m(r'v=|r^{\prime}|=\sqrt{'+tex(q)+'}'),m(r'T=r^{\prime}/v,\quad N=T^{\prime}/|T^{\prime}|'),m(r'\kappa=|T^{\prime}|/v')],m('T='+v(T))+'; '+m('N='+v(N))+'; '+m(r'\kappa='+tex(kap)),parts=list('ab'))
curve_rows=[(25,[0,t**3,t*t],None),(26,[t,t*t,s.exp(t)],None),(27,[s.sqrt(6)*t*t,2*t,2*t**3],None),(28,[t*t,s.log(t),t*s.log(t)],1),(29,[t,t*t,t**3],1),(30,[s.cos(t),s.sin(t),s.sin(5*t)],0)]
for n,ff,at in curve_rows:
 r=M(ff);d=r.diff(t);a=d.diff(t);cr=s.simplify(d.cross(a));q=s.trigsimp(d.dot(d));h=s.trigsimp(cr.dot(cr));kap=s.simplify(s.sqrt(h)/q**R(3,2));out=s.simplify(kap.subs(t,at))if at is not None else kap
 k=m('r(t)='+v(r))+'의 곡률을 '+(m('t='+tex(at))+'에서 'if at is not None else'')+'구하라.';e='Find the curvature of '+m('r(t)='+v(r))+(' at '+m('t='+tex(at))if at is not None else'')+'.'
 if n==30:k+=' 곡선도 그려라.';e+=' Also graph the curve.'
 ks=[m(r'r^{\prime}\times r^{\prime\prime}='+v(cr)),m(r'|r^{\prime}|^2='+tex(q)),m(r'\kappa=\frac{|r^{\prime}\times r^{\prime\prime}|}{|r^{\prime}|^3}')];es=ks.copy()
 if n==25:ks+=['t=0에서는속력이0이므로이매개식의곡률공식은정의되지않는다.'];es+=['At t=0 the speed vanishes, so this parametrized curvature formula is undefined.']
 add(n,k,e,ks,es,m(r'\kappa='+tex(out)))
for n,f in [(31,t**4),(32,s.tan(t)),(33,t*s.exp(t)),(34,s.log(t)),(35,s.exp(t)),(38,t**4-2*t*t),(39,t**-2)]:
 p=s.diff(f,t);pp=s.diff(p,t);kap=s.Abs(pp)/(1+p*p)**R(3,2)
 k=m('y='+tex(f.subs(t,s.Symbol('x',real=True))))+'의 곡률을 구하라.';e='Find the curvature of '+m('y='+tex(f.subs(t,s.Symbol('x',real=True))))+'.'
 ks=[m(r"f^{\prime}(x)="+tex(p.subs(t,s.Symbol('x',real=True)))),m(r"f^{\prime\prime}(x)="+tex(pp.subs(t,s.Symbol('x',real=True)))),m(r'\kappa(x)=\frac{|f^{\prime\prime}(x)|}{(1+f^{\prime}(x)^2)^{3/2}}')];es=ks.copy();ans=m(r'\kappa(x)='+tex(kap.subs(t,s.Symbol('x',real=True))))
 # Replace standalone parameter symbols without corrupting tan/left in TeX.
 for arr in [ks,es]:
  for j,z in enumerate(arr):arr[j]=z.replace(r'\\xan',r'\\tan').replace(r'\\lefx',r'\\left').replace(r'\\righx',r'\\right')
 ans=ans.replace(r'\\xan',r'\\tan').replace(r'\\lefx',r'\\left').replace(r'\\righx',r'\\right')
 if n in [34,35]:
  k='곡선'+m(r'y=\ln x'if n==34 else'y=e^x')+'의 곡률이 최대인 점과x→∞에서 곡률의 극한을 구하라.';e='Find where '+m(r'y=\ln x'if n==34 else'y=e^x')+' has maximum curvature and its curvature limit as x→∞.'
  form=r'\kappa=x/(1+x^2)^{3/2},\quad\kappa^{\prime}=(1-2x^2)/(1+x^2)^{5/2}'if n==34 else r'\kappa=e^x/(1+e^{2x})^{3/2},\quad\kappa^{\prime}=e^x(1-2e^{2x})/(1+e^{2x})^{5/2}'
  ks+=[m(form),'도함수가 양에서 음으로 바뀌므로 전역 최대이다. 양 끝에서 곡률은0으로 간다.'];es+=[m(form),'The derivative changes from positive to negative, giving the global maximum. Curvature tends to zero at both ends of the domain.']
  ans+= '; '+m(r'(x,y)=(1/\sqrt2,-\tfrac12\ln2),\quad\kappa_{max}=2/(3\sqrt3),\quad\lim_{x\to\infty}\kappa=0' if n==34 else r'(x,y)=(-\tfrac12\ln2,1/\sqrt2),\quad\kappa_{max}=2/(3\sqrt3),\quad\lim_{x\to\infty}\kappa=0')
 if n in [38,39]:
  k+=' 곡선과곡률을같은화면에그리고형태를설명하라.';e+=' Plot the curve and curvature on the same screen and explain the shape.'
  ks+=['곡률은기울기만의크기가아니라접선방향의변화율이다. '+('x=±1/√3인변곡점에서0이고원점은κ=4이다.'if n==38 else'x=0은정의되지않는다. x→0과|x|→∞에서곡률은모두0이고, 그사이에봉우리가있다.')];es+=['Curvature measures change of tangent direction, not slope alone. '+('It vanishes at the inflections x=±1/√3 and equals4 at the origin.'if n==38 else'x=0 is excluded. Curvature tends to zero as x→0 and as |x|→∞, with peaks between.')]
 add(n,k,e,ks,es,ans)
add(36,'원점에서곡률이4인포물선의방정식하나를구하라.','Give a parabola with curvature4 at the origin.',[m(r'y=ax^2\Rightarrow\kappa(0)=|2a|'),m(r'|a|=2')],[m(r'y=ax^2\Rightarrow\kappa(0)=|2a|'),m(r'|a|=2')],m('y=2x^2')+' (또는 '+m('y=-2x^2')+')',m('y=2x^2')+' (or '+m('y=-2x^2')+')')
add(37,'제시된곡선의봉우리P와골짜기Q에서(a)어느곡률이더큰지설명하고(b)접촉원을그려곡률을추정하라.','For the displayed curve at its peak P and trough Q, (a)compare curvature;(b)estimate it with osculating circles.',['(a)P쪽이더촘촘하게굽으므로곡률이더크다.','(b)눈금에맞춰곡선의오목한쪽에접하는원을그린다. 대략반지름R_P≈0.77,R_Q≈1.43이므로κ=1/R를쓴다.','원그리기로읽은근삿값이다. 정확한함수식이나정확한좌표가주어지지않았으므로추정의정밀도를과장하지않는다.'],['(a)The tighter bend at P gives larger curvature.','(b)Fit circles on the concave side using the graph scale. Approximate radii R_P≈0.77,R_Q≈1.43 give κ=1/R.','These are graphical estimates. No exact function or coordinates are supplied, so additional numerical precision is not justified.'],m(r'\kappa(P)\approx1.3,\quad\kappa(Q)\approx0.7'),parts=list('ab'))
complex_rows=[(40,[t-s.sin(t),1-s.cos(t),4*s.cos(t/2)]),(41,[t*s.exp(t),s.exp(-t),s.sqrt(2)*t]),(44,[s.sin(3*t),s.sin(2*t),s.sin(3*t)]),(45,[t-R(3,2)*s.sin(t),1-R(3,2)*s.cos(t),t])]
for n,ff in complex_rows:
 r=M(ff);d=r.diff(t);a=d.diff(t);q=s.trigsimp(d.dot(d));h=s.trigsimp(d.cross(a).dot(d.cross(a)))
 if n==40:q=4-4*s.cos(t);h=2*(s.cos(t)-1)**2;kap=1/(8*s.Abs(s.sin(t/2)))
 elif n==41:q=(t+1)**2*s.exp(2*t)+2+s.exp(-2*t);h=2*(t+2)**2*s.exp(2*t)+(2*t+3)**2+2*s.exp(-2*t);kap=s.sqrt(h)/q**R(3,2)
 elif n==44:q=18*s.cos(3*t)**2+4*s.cos(2*t)**2;h=72*s.sin(t)**2*(8*s.sin(t)**4-10*s.sin(t)**2+5)**2;kap=s.sqrt(h)/q**R(3,2)
 else:q=R(17,4)-3*s.cos(t);h=(36*s.cos(t)**2-108*s.cos(t)+117)/16;kap=s.sqrt(h)/q**R(3,2)
 eq(f'{n} speed identity',s.trigsimp(s.expand_trig(d.dot(d)-q)));eq(f'{n} cross identity',s.trigsimp(s.expand_trig(d.cross(a).dot(d.cross(a))-h)))
 ks=[m(r'|r^{\prime}|^2='+tex(q)),m(r'|r^{\prime}\times r^{\prime\prime}|^2='+tex(h)),m(r'\kappa=\sqrt{'+tex(h)+'}/('+tex(q)+r')^{3/2}')];es=ks.copy()
 k=m('r(t)='+v(r))+'의곡선과곡률을그리고곡률의특징을설명하라.';e='Plot the curve '+m('r(t)='+v(r))+' and its curvature, and explain the curvature behavior.'
 ans=m(r'\kappa(t)='+tex(kap))
 if n==40:
  k+=' 범위는0≤t≤8π이다.';e+=' Use0≤t≤8π.'
  ks+=['t=2πk에서는r′=0이므로곡률이정의되지않는다. 가까이갈수록κ→∞이고각구간가운데t=(2k+1)π에서는최소1/8이다. 첨점근처의급격한방향변화를반영한다.'];es+=['At t=2πk the velocity vanishes and curvature is undefined. Curvature diverges near these cusps and has minimum1/8 at t=(2k+1)π between them.']
 if n==41:
  k+=' 범위는−5≤t≤5이다.';e+=' Use−5≤t≤5.'
  ks+=['양끝에서는한지수성분의방향으로거의곧게뻗어곡률이작다. 가운데굽은전이구간에서곡률이커진다.'];es+=['At either end one exponential component dominates, producing nearly straight motion with small curvature. Curvature rises in the central bending transition.']
 if n==44:
  k+=' (a)곡률의극대점개수를예측하고(b)곡률그래프로확인하라.';e+=' (a)Predict the number of curvature maxima;(b)check with the curvature plot.'
  ks+=['한주기0≤t<2π에서여섯개의굽은끝부분이보인다. u=cos²t로κ²을미분하면내부정지값은u≈0.2779065,0.7323180이다. 첫째는극소,둘째는극대이다.','α≈0.54378647일때t=α,π−α,π+α,2π−α의네점은κ≈14.1896인전역최대이다. t=π/2,3π/2의두점도κ=9√2/4인국소최대이다. 이여섯점은서로다른곡선위점이다.'];es+=['One period0≤t<2π shows six sharply curved tips. Differentiating κ² with u=cos²t gives interior stationary values u≈0.2779065,0.7323180. The first is a minimum and the second a maximum.','For α≈0.54378647, the four values t=α,π−α,π+α,2π−α give global maxima κ≈14.1896. The two values t=π/2,3π/2 give local maxima9√2/4. These correspond to six distinct curve points.'];ans+='; 극대점6개';ae=m(r'\kappa(t)='+tex(kap))+'; six maxima'
 else:ae=None
 if n==45:
  c=s.symbols('c',real=True);rat=4*(36*c*c-108*c+117)/(17-12*c)**3;der=s.factor(s.diff(rat,c));ks +=[m(r'c=\cos t,\quad\kappa^2=\frac{4(36c^2-108c+117)}{(17-12c)^3}'),m(r'\frac{d(\kappa^2)}{dc}='+tex(der)),'−1≤c≤1에서분모가양수이고분자도양수이다. 따라서c=1에서가장크다.'];es +=[m(r'c=\cos t,\quad\kappa^2=\frac{4(36c^2-108c+117)}{(17-12c)^3}'),m(r'\frac{d(\kappa^2)}{dc}='+tex(der)),'Both numerator and denominator are positive on−1≤c≤1. The maximum therefore occurs at c=1.'];ans+='; '+m(r't=2\pi k,\quad\kappa_{max}=6/5,\quad k\in\mathbb Z')
 add(n,k,e,ks,es,ans,ae,parts=list('ab')if n==44 else[])
for n,ans,why,whye in [(42,'a:κ, b:f','a는b의두변곡점에서0이고,가운데에서b의굽힘을반영해양수봉우리를만든다.','Curve a vanishes at the two inflections of b and has a positive central peak reflecting its bend.'),(43,'a:f, b:κ','a의평평해지는양끝에서는곡률이작고,가운데둥근봉우리부근에서b가크다. a의큰기울기만으로곡률을판단하면안된다.','The flattened ends of a have small curvature, while b is larger around the rounded central peak. Large slope alone does not mean large curvature.')]:
 add(n,'그림의a,b중함수f의그래프와곡률κ의그래프를구분하고이유를설명하라.','Identify which displayed curve a or b is f and which is its curvature κ, explaining the choice.',[why,m(r'\kappa=|f^{\prime\prime}|/(1+(f^{\prime})^2)^{3/2}')],[whye,m(r'\kappa=|f^{\prime\prime}|/(1+(f^{\prime})^2)^{3/2}')],ans)
add(46,'평면매개곡선x=f(t),y=g(t)의곡률공식을벡터곱공식에서증명하라.','Derive the planar parametric curvature formula from the cross-product formula.',[m(r'r=\langle x,y,0\rangle,\quad r^{\prime}\times r^{\prime\prime}=\langle0,0,x^{\prime}y^{\prime\prime}-y^{\prime}x^{\prime\prime}\rangle'),m(r'|r^{\prime}|^3=((x^{\prime})^2+(y^{\prime})^2)^{3/2}'),'속력이0이아닌정칙점에서두식을나눈다.'],[m(r'r=\langle x,y,0\rangle,\quad r^{\prime}\times r^{\prime\prime}=\langle0,0,x^{\prime}y^{\prime\prime}-y^{\prime}x^{\prime\prime}\rangle'),m(r'|r^{\prime}|^3=((x^{\prime})^2+(y^{\prime})^2)^{3/2}'),'Divide at a regular point, where speed is nonzero.'],m(r'\kappa=\frac{|x^{\prime}y^{\prime\prime}-y^{\prime}x^{\prime\prime}|}{((x^{\prime})^2+(y^{\prime})^2)^{3/2}}'))
for n,ff in [(47,[t*t,t**3]),(48,[s.Symbol('a',positive=True)*s.cos(s.Symbol('w',nonzero=True,real=True)*t),s.Symbol('b',positive=True)*s.sin(s.Symbol('w',nonzero=True,real=True)*t)]),(49,[s.exp(t)*s.cos(t),s.exp(t)*s.sin(t)])]:
 xx,yy=ff;dx=s.diff(xx,t);dy=s.diff(yy,t);det=s.simplify(dx*s.diff(dy,t)-dy*s.diff(dx,t));q=s.trigsimp(dx*dx+dy*dy);kap=s.simplify(s.Abs(det)/q**R(3,2))
 add(n,m('x='+tex(xx)+r',\ y='+tex(yy))+'의곡률을구하라.'+(' a,b>0,w≠0으로둔다.'if n==48 else''),'Find the curvature of '+m('x='+tex(xx)+r',\ y='+tex(yy))+'.'+(' Assume a,b>0 and w≠0.'if n==48 else''),[m(r'x^{\prime}y^{\prime\prime}-y^{\prime}x^{\prime\prime}='+tex(det)),m(r'(x^{\prime})^2+(y^{\prime})^2='+tex(q))]+(['t=0에서는정칙매개화가아니다.']if n==47 else[]),[m(r'x^{\prime}y^{\prime\prime}-y^{\prime}x^{\prime\prime}='+tex(det)),m(r'(x^{\prime})^2+(y^{\prime})^2='+tex(q))]+(['The parametrization is not regular at t=0.']if n==47 else[]),m(r'\kappa='+tex(kap)))
add(50,'f(x)=eᶜˣ가x=0에서갖는곡률이최대가되는c를구하라.','Which functions f(x)=eᶜˣ maximize curvature at x=0?',[m(r'\kappa(0)=c^2/(1+c^2)^{3/2}'),m(r'\frac{d}{dc}\kappa(0)=c(2-c^2)/(1+c^2)^{5/2}'),'c=0은최소이고|c|→∞에서도0으로가므로±√2가최대이다.'],[m(r'\kappa(0)=c^2/(1+c^2)^{3/2}'),m(r'\frac{d}{dc}\kappa(0)=c(2-c^2)/(1+c^2)^{5/2}'),'c=0 is a minimum and the expression tends to zero as |c|→∞, so ±√2 give the maxima.'],m(r'c=\pm\sqrt2,\quad\kappa_{max}=2/(3\sqrt3)'))
def atframe(ff,at):
 r=M(ff);d=r.diff(t);a=d.diff(t);D=s.simplify(d.subs(t,at));A=s.simplify(a.subs(t,at));T=s.simplify(D/D.norm());B=s.simplify(D.cross(A)/D.cross(A).norm());N=s.simplify(B.cross(T));return r,d,a,T,N,B
for n,ff,at in [(51,[t*t,R(2,3)*t**3,t],1),(52,[s.cos(t),s.sin(t),s.log(s.cos(t))],0)]:
 r,d,a,T,N,B=atframe(ff,at)
 for lab,z in [('T unit',T.dot(T)-1),('N unit',N.dot(N)-1),('B unit',B.dot(B)-1),('orientation',T.cross(N)-B)]:eq(f'{n} {lab}',z)
 add(n,m('r(t)='+v(r))+'의점'+m(v(r.subs(t,at)))+'에서T,N,B를구하라.','Find T,N,B for '+m('r(t)='+v(r))+' at '+m(v(r.subs(t,at)))+'.',[m('t_0='+tex(at)+r',\quad r^{\prime}(t_0)='+v(d.subs(t,at))),m(r'T=r^{\prime}/|r^{\prime}|,\quad B=\frac{r^{\prime}\times r^{\prime\prime}}{|r^{\prime}\times r^{\prime\prime}|},\quad N=B\times T')],[m('t_0='+tex(at)+r',\quad r^{\prime}(t_0)='+v(d.subs(t,at))),m(r'T=r^{\prime}/|r^{\prime}|,\quad B=\frac{r^{\prime}\times r^{\prime\prime}}{|r^{\prime}\times r^{\prime\prime}|},\quad N=B\times T')],m('T='+v(T))+'; '+m('N='+v(N))+'; '+m('B='+v(B)))
xyz=M(s.symbols('x y z',real=True))
for n,ff,at in [(53,[s.sin(2*t),-s.cos(2*t),4*t],s.pi/2),(54,[s.log(t),2*t,t*t],1),(59,[t*t,t,t**4],1)]:
 r,d,a,T,N,B=atframe(ff,at);P=s.simplify(r.subs(t,at));D=s.simplify(d.subs(t,at));C=s.simplify(d.cross(a).subs(t,at));np=s.expand(D.dot(xyz-P));op=s.expand(C.dot(xyz-P))
 k=m('r(t)='+v(r))+'의점'+m(v(P))+'에서법평면과접촉평면을구하라.';e='Find the normal and osculating planes for '+m('r(t)='+v(r))+' at '+m(v(P))+'.'
 if n==59:k='x=y²,z=x²의교선에서(1,1,1)의법평면과접촉평면을구하라.';e='Find the normal and osculating planes at(1,1,1)on x=y²,z=x².'
 add(n,k,e,[m('t_0='+tex(at)+r',\quad r^{\prime}='+v(D)),m(r'r^{\prime}\times r^{\prime\prime}='+v(C)),'법평면의법선은r′,접촉평면의법선은r′×r″이다. 각각P를지나게한다.'],[m('t_0='+tex(at)+r',\quad r^{\prime}='+v(D)),m(r'r^{\prime}\times r^{\prime\prime}='+v(C)),'Use r′ as the normal-plane normal and r′×r″ as the osculating-plane normal; both planes pass through P.'], '법평면 '+m(tex(np)+'=0')+'; 접촉평면 '+m(tex(op)+'=0'),'Normal plane '+m(tex(np)+'=0')+'; osculating plane '+m(tex(op)+'=0'))
for n,k,e,ks,es,ans in [
(55,'타원9x²+4y²=36의(2,0),(0,3)에서접촉원을구하고타원과두원을함께그려라.','Find the osculating circles of9x²+4y²=36 at(2,0),(0,3), and plot the ellipse with both circles.',[m(r'r(t)=\langle2\cos t,3\sin t\rangle,\quad\kappa=6/(4\sin^2t+9\cos^2t)^{3/2}'),'t=0에서R=9/2,N=(-1,0),중심(-5/2,0). t=π/2에서R=4/3,N=(0,-1),중심(0,5/3).'],[m(r'r(t)=\langle2\cos t,3\sin t\rangle,\quad\kappa=6/(4\sin^2t+9\cos^2t)^{3/2}'),'At t=0, R=9/2,N=(-1,0),center(-5/2,0). At t=π/2, R=4/3,N=(0,-1),center(0,5/3).'],m(r'(x+5/2)^2+y^2=81/4,\quad x^2+(y-5/3)^2=16/9')),
(56,'y=x²/2의(0,0),(1,1/2)에서접촉원을구하고포물선과함께그려라.','Find and plot the osculating circles of y=x²/2 at(0,0),(1,1/2).',[m(r'\kappa=(1+x^2)^{-3/2},\quad N=\langle-x,1\rangle/\sqrt{1+x^2}'),m(r'C=(x,x^2/2)+\kappa^{-1}N=(-x^3,1+3x^2/2)'),'각각C=(0,1),R=1및C=(-1,5/2),R=2√2이다.'],[m(r'\kappa=(1+x^2)^{-3/2},\quad N=\langle-x,1\rangle/\sqrt{1+x^2}'),m(r'C=(x,x^2/2)+\kappa^{-1}N=(-x^3,1+3x^2/2)'),'The circles have C=(0,1),R=1 and C=(-1,5/2),R=2√2.'],m(r'x^2+(y-1)^2=1,\quad(x+1)^2+(y-5/2)^2=8')),
(57,'r(t)=(t³,3t,t⁴)의법평면이6x+6y−8z=1과평행한점을구하라.','Where is the normal plane to r(t)=(t³,3t,t⁴)parallel to6x+6y−8z=1?',[m(r'r^{\prime}=\langle3t^2,3,4t^3\rangle=\lambda\langle6,6,-8\rangle'),m(r'\lambda=1/2,\quad t^2=1,\quad t^3=-1\Rightarrow t=-1')],[m(r'r^{\prime}=\langle3t^2,3,4t^3\rangle=\lambda\langle6,6,-8\rangle'),m(r'\lambda=1/2,\quad t^2=1,\quad t^3=-1\Rightarrow t=-1')],m('(-1,-3,1)')),
(58,'r(t)=(t³,3t,t⁴)의접촉평면이x+y+z=1과평행한점이있는가?','Does r(t)=(t³,3t,t⁴)have an osculating plane parallel to x+y+z=1?',[m(r'r^{\prime}\times r^{\prime\prime}=\langle36t^2,12t^4,-18t\rangle'),'t=0이면벡터곱이0이어서프레네접촉평면이정의되지않는다. t≠0이면세성분이같아야한다.',m(r'36t^2=-18t\Rightarrow t=-1/2,\quad36t^2=12t^4\Rightarrow t^2=3'),'두조건이모순이다.'],[m(r'r^{\prime}\times r^{\prime\prime}=\langle36t^2,12t^4,-18t\rangle'),'At t=0 the cross product vanishes, so the Frenet osculating plane is undefined. For t≠0 all three components must be equal.',m(r'36t^2=-18t\Rightarrow t=-1/2,\quad36t^2=12t^4\Rightarrow t^2=3'),'The two conditions are incompatible.'],'그런점은없다.'),
(60,'r(t)=(t+2,1−t,t²/2)의접촉평면이모든점에서같음을보이고곡선에대해결론내려라.','Show that r(t)=(t+2,1−t,t²/2)has the same osculating plane everywhere and interpret this.',[m(r'r^{\prime}=\langle1,-1,t\rangle,\quad r^{\prime\prime}=\langle0,0,1\rangle,\quad r^{\prime}\times r^{\prime\prime}=\langle-1,-1,0\rangle'),'모든점에서x+y=3이므로같은법선과같은평면을갖는다.'],[m(r'r^{\prime}=\langle1,-1,t\rangle,\quad r^{\prime\prime}=\langle0,0,1\rangle,\quad r^{\prime}\times r^{\prime\prime}=\langle-1,-1,0\rangle'),'Every curve point satisfies x+y=3, giving the same normal and plane everywhere.'],m('x+y=3')+'; 평면곡선이다.')]:
 ae='No such point exists.'if n==58 else m('x+y=3')+'; the curve is planar.'if n==60 else None
 add(n,k,e,ks,es,ans,ae)
r=M([s.exp(t)*s.cos(t),s.exp(t)*s.sin(t),s.exp(t)]);d=r.diff(t);T=s.simplify(d/(s.sqrt(3)*s.exp(t)));N=s.simplify(T.diff(t)/s.sqrt(R(2,3)));B=s.simplify(T.cross(N));eq('61 B z',B[2]-s.sqrt(R(2,3)))
add(61,'r(t)=eᵗ(cos t,sin t,1)의T,N,B가z축과이루는각이각각일정함을보여라.','Show that T,N,B for r(t)=eᵗ(cos t,sin t,1)each make a constant angle with the z-axis.',[m('T='+v(T)),m('N='+v(N)),m('B='+v(B)),'각단위벡터의z성분이z축방향단위벡터와의내적,즉각의코사인이다.'],[m('T='+v(T)),m('N='+v(N)),m('B='+v(B)),'Each unit vector’s z-component is its dot product with the positive z-axis unit vector, hence the cosine of the angle.'],m(r'\theta_T=\arccos(1/\sqrt3),\quad\theta_N=\pi/2,\quad\theta_B=\arccos\sqrt{2/3}'))
r,d,a,T,N,B=atframe([s.sin(t),s.cos(t),s.tan(t)],s.pi/4);P=s.simplify(r.subs(t,s.pi/4));normal=M([-13,3,4*s.sqrt(2)]);plane=s.simplify(normal.dot(xyz-P))
add(62,'T와B를포함하는평면을rectifying plane이라한다. r(t)=(sin t,cos t,tan t)의(√2/2,√2/2,1)에서이평면을구하라.','The rectifying plane contains T and B. Find it for r(t)=(sin t,cos t,tan t)at(√2/2,√2/2,1).',[m(r't_0=\pi/4,\quad N='+v(N)),'T와B에모두수직인N을법선으로삼고주어진점을지나게한다.'],[m(r't_0=\pi/4,\quad N='+v(N)),'Use N, perpendicular to both T and B, as the normal through the given point.'],m(tex(plane)+'=0'))
add(63,'호길이s에대해dT/ds=κN임을보여라.','Show that dT/ds=κN for arc length s.',[m(r'\frac{dT}{ds}=\frac{T^{\prime}(t)}{ds/dt}=\frac{|T^{\prime}|}{|r^{\prime}|}\frac{T^{\prime}}{|T^{\prime}|}=\kappa N'),'속력과곡률이0이아닌점에서정의에따라계산했다.'],[m(r'\frac{dT}{ds}=\frac{T^{\prime}(t)}{ds/dt}=\frac{|T^{\prime}|}{|r^{\prime}|}\frac{T^{\prime}}{|T^{\prime}|}=\kappa N'),'This uses the definitions where speed and curvature are nonzero.'],m(r'dT/ds=\kappa N'))
add(64,'평면곡선의접선기울기각φ에대해κ=|dφ/ds|임을보여라.','Show that a plane curve with tangent inclination φ has κ=|dφ/ds|.',[m(r'T=\langle\cos\phi,\sin\phi\rangle'),m(r'\frac{dT}{ds}=\frac{d\phi}{ds}\langle-\sin\phi,\cos\phi\rangle'),'오른쪽두번째벡터는단위벡터이므로양변의길이를취한다.'],[m(r'T=\langle\cos\phi,\sin\phi\rangle'),m(r'\frac{dT}{ds}=\frac{d\phi}{ds}\langle-\sin\phi,\cos\phi\rangle'),'The second vector on the right is a unit vector; take norms.'],m(r'\kappa=|dT/ds|=|d\phi/ds|'))
add(65,'(a)dB/ds가B와수직,(b)T와수직임을보이고(c)N과평행임을결론내려라.','Show that dB/ds is perpendicular to(a)B and(b)T, and conclude(c)it is parallel to N.',[m(r'B\cdot B=1\Rightarrow2B\cdot B_s=0'),m(r'B\cdot T=0\Rightarrow B_s\cdot T+B\cdot(\kappa N)=0'),'B·N=0이므로B_s·T=0이다. 직교기저T,N,B에서B_s는N성분만가진다. 영벡터인경우도포함한다.'],[m(r'B\cdot B=1\Rightarrow2B\cdot B_s=0'),m(r'B\cdot T=0\Rightarrow B_s\cdot T+B\cdot(\kappa N)=0'),'Since B·N=0, B_s·T=0. In the orthonormal frame T,N,B, only the N-component remains, including the zero-vector case.'],m(r'B_s\parallel N'),parts=list('abc'))
for n,ff,at in [(66,[s.sin(t),3*t,s.cos(t)],s.pi/2),(67,[t*t/2,2*t,t],1),(68,[t,t*t/2,t**3/3],0),(69,[s.exp(t),s.exp(-t),t],0),(70,[s.cos(t),s.sin(t),s.sin(t)],0)]:
 r=M(ff);d=r.diff(t);a=d.diff(t);c=s.simplify(d.cross(a));h=s.trigsimp(c.dot(c));tr=s.simplify(c.dot(a.diff(t)));tau=s.simplify(tr/h)
 ks=[m(r'r^{\prime}\times r^{\prime\prime}='+v(c))];es=ks.copy()
 if n<=67:
  B=s.simplify(c/s.sqrt(h));T=s.simplify(d/s.sqrt(s.trigsimp(d.dot(d))));N=s.simplify(B.cross(T));out=s.simplify(-B.diff(t).dot(N)/s.sqrt(s.trigsimp(d.dot(d))));eq(f'{n} torsion two formulas',s.trigsimp(out-tau))
  ks +=[m('B='+v(B)),m('N='+v(N)),m(r'\tau=-B^{\prime}\cdot N/|r^{\prime}|')];es=ks.copy()
 else:ks +=[m(r'(r^{\prime}\times r^{\prime\prime})\cdot r^{\prime\prime\prime}='+tex(tr)),m(r'\tau=\frac{(r^{\prime}\times r^{\prime\prime})\cdot r^{\prime\prime\prime}}{|r^{\prime}\times r^{\prime\prime}|^2}')];es=ks.copy()
 ans=m(r'\tau('+tex(at)+')='+tex(tau.subs(t,at))) if n<=67 else m(r'\tau(t)='+tex(tau)+r',\quad\tau(0)='+tex(tau.subs(t,0)))
 add(n,m('r(t)='+v(r))+'의비틀림을'+(m('t='+tex(at))+'에서식τ=−B′·N/|r′|로구하라.'if n<=67 else'벡터삼중곱공식으로일반t와t=0에서구하라.'),'Find the torsion of '+m('r(t)='+v(r))+(' at '+m('t='+tex(at))+' using τ=−B′·N/|r′|.'if n<=67 else' at general t and t=0 using the scalar triple-product formula.'),ks,es,ans)
add(71,'N=B×T와프레네공식T_s=κN,B_s=−τN으로N_s=−κT+τB를증명하라.','Use N=B×T, T_s=κN and B_s=−τN to prove N_s=−κT+τB.',[m(r'N_s=B_s\times T+B\times T_s=(-\tau N)\times T+B\times(\kappa N)'),m(r'N\times T=-B,\quad B\times N=-T')],[m(r'N_s=B_s\times T+B\times T_s=(-\tau N)\times T+B\times(\kappa N)'),m(r'N\times T=-B,\quad B\times N=-T')],m(r'N_s=-\kappa T+\tau B'))
add(72,'프레네–세레공식으로(a)r″의T,N전개,(b)r′×r″,(c)r‴의T,N,B전개,(d)비틀림의삼중곱공식을증명하라.','Using the Frenet–Serret formulas, derive(a)r″ in T,N;(b)r′×r″;(c)r‴ in T,N,B;(d)the scalar triple-product formula for torsion.',[m(r'v=s^{\prime}>0,\quad r^{\prime}=vT,\quad T^{\prime}=v\kappa N,\quad N^{\prime}=v(-\kappa T+\tau B)'),m(r'(a)\quad r^{\prime\prime}=v^{\prime}T+\kappa v^2N'),m(r'(b)\quad r^{\prime}\times r^{\prime\prime}=\kappa v^3B'),m(r'(c)\quad r^{\prime\prime\prime}=(v^{\prime\prime}-\kappa^2v^3)T+(3\kappa vv^{\prime}+\kappa^{\prime}v^2)N+\kappa\tau v^3B'),'(c)는(a)를t로미분하고위의T′,N′를대입해성분별로모은것이다.',m(r'(d)\quad(r^{\prime}\times r^{\prime\prime})\cdot r^{\prime\prime\prime}=\kappa^2\tau v^6,\quad|r^{\prime}\times r^{\prime\prime}|^2=\kappa^2v^6')],[m(r'v=s^{\prime}>0,\quad r^{\prime}=vT,\quad T^{\prime}=v\kappa N,\quad N^{\prime}=v(-\kappa T+\tau B)'),m(r'(a)\quad r^{\prime\prime}=v^{\prime}T+\kappa v^2N'),m(r'(b)\quad r^{\prime}\times r^{\prime\prime}=\kappa v^3B'),m(r'(c)\quad r^{\prime\prime\prime}=(v^{\prime\prime}-\kappa^2v^3)T+(3\kappa vv^{\prime}+\kappa^{\prime}v^2)N+\kappa\tau v^3B'),'(c)follows by differentiating(a)with respect to t, substituting T′,N′ and collecting components.',m(r'(d)\quad(r^{\prime}\times r^{\prime\prime})\cdot r^{\prime\prime\prime}=\kappa^2\tau v^6,\quad|r^{\prime}\times r^{\prime\prime}|^2=\kappa^2v^6')],m(r'\tau=\frac{(r^{\prime}\times r^{\prime\prime})\cdot r^{\prime\prime\prime}}{|r^{\prime}\times r^{\prime\prime}|^2}')+'; 위(a)–(c), v=s′. ',m(r'\tau=\frac{(r^{\prime}\times r^{\prime\prime})\cdot r^{\prime\prime\prime}}{|r^{\prime}\times r^{\prime\prime}|^2}')+'; (a)–(c)above, with v=s′.',parts=list('abcd'))
add(73,'a,b>0인나선r(t)=(a cos t,a sin t,bt)의곡률과비틀림이상수임을보여라.','Show that r(t)=(a cos t,a sin t,bt),a,b>0, has constant curvature and torsion.',[m(r'|r^{\prime}|=\sqrt{a^2+b^2},\quad r^{\prime}\times r^{\prime\prime}=\langle ab\sin t,-ab\cos t,a^2\rangle'),m(r'|r^{\prime}\times r^{\prime\prime}|=a\sqrt{a^2+b^2},\quad(r^{\prime}\times r^{\prime\prime})\cdot r^{\prime\prime\prime}=a^2b')],[m(r'|r^{\prime}|=\sqrt{a^2+b^2},\quad r^{\prime}\times r^{\prime\prime}=\langle ab\sin t,-ab\cos t,a^2\rangle'),m(r'|r^{\prime}\times r^{\prime\prime}|=a\sqrt{a^2+b^2},\quad(r^{\prime}\times r^{\prime\prime})\cdot r^{\prime\prime\prime}=a^2b')],m(r'\kappa=a/(a^2+b^2),\quad\tau=b/(a^2+b^2)'))
add(74,'(sinh t,cosh t,t)의(0,1,0)에서곡률과비틀림을구하라.','Find curvature and torsion of(sinh t,cosh t,t)at(0,1,0).',[m(r't=0,\quad r^{\prime}=\langle1,0,1\rangle,\quad r^{\prime\prime}=\langle0,1,0\rangle,\quad r^{\prime\prime\prime}=\langle1,0,0\rangle'),m(r'r^{\prime}\times r^{\prime\prime}=\langle-1,0,1\rangle'),m(r'\kappa=\sqrt2/(\sqrt2)^3,\quad\tau=-1/2')],[m(r't=0,\quad r^{\prime}=\langle1,0,1\rangle,\quad r^{\prime\prime}=\langle0,1,0\rangle,\quad r^{\prime\prime\prime}=\langle1,0,0\rangle'),m(r'r^{\prime}\times r^{\prime\prime}=\langle-1,0,1\rangle'),m(r'\kappa=\sqrt2/(\sqrt2)^3,\quad\tau=-1/2')],m(r'\kappa=1/2,\quad\tau=-1/2'))
add(75,'곡률중심의자취를축폐선(evolute)이라한다. (a)r_e=r+N/κ를설명하고(b)나선(cos t,sin t,t),(c)포물선y=x²의축폐선을구하라.','An evolute is the locus of centers of curvature. (a)Explain r_e=r+N/κ;(b)find it for(cos t,sin t,t);(c)find it for y=x².',['(a)접촉원중심은곡선의점에서주법선N방향으로반지름R=1/κ만큼이동한점이다. κ≠0에서정의된다.',m(r'(b)\quad\kappa=1/2,\quad N=\langle-\cos t,-\sin t,0\rangle'),m(r'(c)\quad r=\langle t,t^2\rangle,\quad\kappa=2/(1+4t^2)^{3/2},\quad N=\langle-2t,1\rangle/\sqrt{1+4t^2}')],['(a)The osculating-circle center lies a radius R=1/κ from the curve point in the principal-normal direction N, where κ≠0.',m(r'(b)\quad\kappa=1/2,\quad N=\langle-\cos t,-\sin t,0\rangle'),m(r'(c)\quad r=\langle t,t^2\rangle,\quad\kappa=2/(1+4t^2)^{3/2},\quad N=\langle-2t,1\rangle/\sqrt{1+4t^2}')],m(r'(b)\ r_e=\langle-\cos t,-\sin t,t\rangle;\quad(c)\ r_e=\langle-4t^3,3t^2+1/2\rangle'),parts=list('abc'))
add(76,'평면곡선에대해(a)ax(t)+by(t)+cz(t)=d라는상수관계와의동치를보이고(b)B가평면에수직,(c)τ=0임을보여라. (d)r(t)=(t,2t,t²)의평면과B를구하라.','For planar curves, (a)prove equivalence with a constant relation ax(t)+by(t)+cz(t)=d;(b)show B is normal to the plane;(c)show τ=0. (d)Find the plane and B for(t,2t,t²).',['(a)평면은0이아닌법선(a,b,c)과상수d로정의된다. 역으로이관계를만족하면그평면에놓인다. 계수a,b,c,d가모두0이아니고관계가성립한다면(a,b,c)도0일수없다.','(b)관계를두번미분하면법선은r′,r″에모두수직이다. r′×r″≠0인곳에서B는이법선의단위벡터±방향이다.','(c)연결된정칙구간에서κ≠0이면연속인B의부호가변하지않으므로B_s=0,따라서τ=−B_s·N=0이다.',m(r'(d)\quad2x-y=0,\quad r^{\prime}\times r^{\prime\prime}=\langle4,-2,0\rangle')],['(a)A plane is specified by a nonzero normal(a,b,c)and a constant d. Conversely, the relation puts the curve in that plane. If a,b,c,d are not all zero and the relation holds, (a,b,c)cannot be zero.','(b)Differentiate twice: the normal is perpendicular to r′ and r″. Where r′×r″≠0, B is one of the two unit-normal directions.','(c)On a connected regular interval with κ≠0, continuity prevents the sign of B from changing. Thus B_s=0 and τ=−B_s·N=0.',m(r'(d)\quad2x-y=0,\quad r^{\prime}\times r^{\prime\prime}=\langle4,-2,0\rangle')],m(r'(d)\quad B=\langle2,-1,0\rangle/\sqrt5,\quad2x-y=0')+'; τ=0은프레네벡터가정의되는곳에서성립한다.',m(r'(d)\quad B=\langle2,-1,0\rangle/\sqrt5,\quad2x-y=0')+'; τ=0 wherever the Frenet frame is defined.',parts=list('abcd'))
L=2.9e8*( (20*float(s.pi))**2+34**2)**.5
add(77,'DNA각나선의반지름은약10Å,한회전의상승량은34Å,회전수는2.9×10⁸이다. 각나선의길이를추정하라(1Å=10⁻⁸cm).','Each DNA helix has radius about10Å, rise34Å per turn and2.9×10⁸ turns. Estimate each helix’s length(1Å=10⁻⁸cm).',[m(r'r(t)=\langle10\cos t,10\sin t,\tfrac{34}{2\pi}t\rangle'),m(r'L_{turn}=\sqrt{(20\pi)^2+34^2}\ \text{Å}'),m(r'L=(2.9\times10^8)\sqrt{(20\pi)^2+34^2}\ \text{Å}'),'1Å=10⁻¹⁰m로환산한다. 두가닥을합한길이가아닌각가닥의길이이다.'],[m(r'r(t)=\langle10\cos t,10\sin t,\tfrac{34}{2\pi}t\rangle'),m(r'L_{turn}=\sqrt{(20\pi)^2+34^2}\ \text{Å}'),m(r'L=(2.9\times10^8)\sqrt{(20\pi)^2+34^2}\ \text{Å}'),'Convert with1Å=10⁻¹⁰m. This is the length of each strand, not the sum of both.'],m(rf'L\approx{L/1e10:.3f}\times10^{{10}}\ \text{{Å}}\approx{L*1e-10:.2f}\ \mathrm{{m}}'))
P=6*t**5-15*t**4+10*t**3
for at,target in [(0,0),(1,1)]:
 eq(f'78 value{at}',P.subs(t,at)-target)
 for order in [1,2]:eq(f'78 derivative{order}at{at}',s.diff(P,t,order).subs(t,at))
add(78,'철도를y=0(x≤0)에서y=1(x≥1)로잇는다. (a)0<x<1에서함수값·기울기·곡률이연속이되도록5차다항식P를구하고(b)연결함수F를그려라.','Join railway tracks y=0 for x≤0 and y=1 for x≥1. (a)Find a quintic P on0<x<1 giving continuous value, slope and curvature;(b)graph the joined function F.',[m(r'P(0)=0,\ P(1)=1,\ P^{\prime}(0)=P^{\prime}(1)=0'),'직선부분의곡률은0이다. 끝점기울기가0이므로곡률연속성은P″(0)=P″(1)=0이다.',m(r'P=ax^5+bx^4+cx^3,\quad a+b+c=1,\quad5a+4b+3c=0,\quad20a+12b+6c=0'),m(r'(a,b,c)=(6,-15,10),\quad P^{\prime}=30x^2(x-1)^2\ge0')],[m(r'P(0)=0,\ P(1)=1,\ P^{\prime}(0)=P^{\prime}(1)=0'),'The straight sections have zero curvature. With zero endpoint slopes, curvature continuity requires P″(0)=P″(1)=0.',m(r'P=ax^5+bx^4+cx^3,\quad a+b+c=1,\quad5a+4b+3c=0,\quad20a+12b+6c=0'),m(r'(a,b,c)=(6,-15,10),\quad P^{\prime}=30x^2(x-1)^2\ge0')],m(r'P(x)=6x^5-15x^4+10x^3,\quad F(x)=\begin{cases}0&x\le0\\P(x)&0<x<1\\1&x\ge1\end{cases}'),parts=list('ab'))
assert sorted(b.E)==list(range(1,79))
b.save();Path(__file__).with_name('s13-3-report.json').write_text(json.dumps({'section':'13.3','count':78,'sourcePdfPages':[988,989,990,991],'checks':checks,'status':'passed'},indent=2)+'\n');print('Saved 78;',len(checks),'checks')
