"""Original vector solutions checked against Calculus9e pp.881–883."""
from early_helpers import Book,fs,same
import sympy as S,math
b=Book('12.2',[881,882,883])
def add(n,k,e,ks,es,a,ae=None,parts=[],ck='계산 결과를 주어진 벡터 조건에 대입해 확인한다.',ce='Substitute the result into the stated vector conditions.'):
 if isinstance(a,tuple): a,ae=a
 b.add(n,881 if n<=2 else 882 if n<=30 else 883,('벡터의 표현과 연산','Vector representations and operations'),(k,e),list(zip(ks,es)),(a,a if ae is None else ae),parts,check=(ck,ce));b.E[n]['conceptHref']='../../calc1/index.html'
def v(t):return r'\langle '+','.join(S.latex(S.sympify(x))for x in t)+r'\rangle'
def m(s):return r'\('+s+r'\)'
add(1,'(a)극장표 가격, (b)강의 흐름, (c)휴스턴에서 댈러스로 출발하는 비행 경로, (d)세계 인구를 스칼라 또는 벡터로 분류하라.','Classify (a)a theater-ticket price, (b)a river current, (c)the initial Houston-to-Dallas flight path, (d)world population as scalar or vector.',['가격과 인구는 수치 하나로 나타낸다. 흐름과 비행의 초기 이동은 크기와 방향이 필요하다.'],['Price and population require only a number. Current and initial flight displacement require magnitude and direction.'],'(a)스칼라 (b)벡터 (c)벡터 (d)스칼라.','(a)Scalar (b)Vector (c)Vector (d)Scalar.',list('abcd'),ck='방향 정보의 필요 여부로 구별한다.',ce='The criterion is whether direction is required.')
add(2,m('(4,7)')+'이라는 점과 '+m(r'\langle4,7\rangle')+'이라는 벡터의 관계를 설명하고 그려라.','Relate and sketch the point '+m('(4,7)')+' and vector '+m(r'\langle4,7\rangle')+'.',['점은 위치를, 벡터는 변위를 나타낸다. 벡터를 원점에 붙이면 끝점이(4,7)이다.'],['A point specifies position; a vector specifies displacement. Placed at the origin, this vector ends at(4,7).'],m(r'\overrightarrow{OP}=\langle4,7\rangle,\quad P=(4,7)'),ck='같은 벡터는 평행이동하여 다른 시작점에서도 표현할 수 있다.',ce='The same vector can be represented from any translated initial point.')
add(3,'원본 평행사변형 ABCD에서 대각선 교점을 E라 하자. 그림에 표시된 같은 벡터를 모두 찾아라.','In the source parallelogram ABCD, E is the diagonal intersection. Find all equal directed vectors shown.',['마주 보는 변은 방향과 길이가 같고, 대각선은 서로 이등분한다.'],['Opposite sides have equal direction and length, and the diagonals bisect each other.'],m(r'\overrightarrow{AB}=\overrightarrow{DC},\ \overrightarrow{DA}=\overrightarrow{CB},\ \overrightarrow{DE}=\overrightarrow{EB},\ \overrightarrow{EA}=\overrightarrow{CE}'),ck='벡터는 길이가 같아도 방향이 반대이면 서로 같지 않다.',ce='Equal length alone is insufficient when directions are opposite.')
add(4,'그림의 A,B,C,D에 대해 (a)AB+BC, (b)CD+DB, (c)DB−AB, (d)DC+CA+AB를 단일 유향선분으로 나타내라(모두 벡터).','Reduce (a)AB+BC, (b)CD+DB, (c)DB−AB, (d)DC+CA+AB to one directed segment, treating every segment as a vector.',[m(r'(B-A)+(C-B)=C-A'),m(r'(D-C)+(B-D)=B-C'),m(r'(B-D)-(B-A)=A-D'),m(r'(C-D)+(A-C)+(B-A)=B-D')],[m(r'(B-A)+(C-B)=C-A'),m(r'(D-C)+(B-D)=B-C'),m(r'(B-D)-(B-A)=A-D'),m(r'(C-D)+(A-C)+(B-A)=B-D')],m(r'(a)\ \overrightarrow{AC},\ (b)\ \overrightarrow{CB},\ (c)\ \overrightarrow{DA},\ (d)\ \overrightarrow{DB}'),parts=list('abcd'))
add(5,'그림의 a(위쪽),b(왼쪽),c(오른쪽 위)를 사용해 (a)a+b,(b)b+c,(c)a+c,(d)a−c,(e)b+a+c,(f)a−b−c를 그려라.','Using the displayed a(up),b(left),c(up-right), draw (a)a+b,(b)b+c,(c)a+c,(d)a−c,(e)b+a+c,(f)a−b−c.',['합은 첫 벡터의 끝에 다음 벡터의 시작을 붙인다. 빼는 벡터는 먼저 방향을 반대로 바꾼다.','각 소문항의 그림에서 검은 화살표가 시작점부터 마지막 끝점까지의 합이다.'],['For a sum, place each next tail at the preceding tip. Reverse a vector before subtracting it.','The black arrow in each panel runs from the first tail to the final tip.'],'첨부한 여섯 머리–꼬리 작도 참조.','See the six head-to-tail constructions.',list('abcdef'),ck='벡터의 위치만 평행이동하고 길이와 방향은 보존한다.',ce='Translations preserve each vector’s length and direction.')
add(6,'그림의 u(오른쪽 위),v(오른쪽 아래)로 (a)u+v,(b)u−v,(c)2u,(d)−v/2,(e)3u+v,(f)v−2u를 그려라.','For u(up-right) and v(down-right), construct (a)u+v,(b)u−v,(c)2u,(d)−v/2,(e)3u+v,(f)v−2u.',['배수는 길이를 해당 절댓값만큼 바꾸고 음수이면 방향을 뒤집는다. 그런 뒤 머리–꼬리 법칙으로 더한다.'],['Scale lengths by the absolute coefficient and reverse directions for negative coefficients; then use head-to-tail addition.'],'첨부한 여섯 작도 참조.','See the six constructions.',list('abcdef'),ck='2u와−v/2는 각각 원벡터와 평행이다.',ce='Both2u and−v/2 remain parallel to their original vectors.')
add(7,'삼각형PQR에서 a=PQ,b=PR이고 M은 QR의 중점이다. c=PM,d=MR를 a,b로 나타내라(모두 벡터).','In triangle PQR let a=PQ,b=PR, M the midpoint of QR, c=PM,d=MR (directed vectors). Express c,d using a,b.',[m(r'M=(Q+R)/2,\quad M-P=((Q-P)+(R-P))/2'),m(r'R-M=(R-Q)/2')],[m(r'M=(Q+R)/2,\quad M-P=((Q-P)+(R-P))/2'),m(r'R-M=(R-Q)/2')],m(r'c=\frac{a+b}{2},\quad d=\frac{b-a}{2}'),ck='c+d=b가 되어 PM+MR=PR와 일치한다.',ce='c+d=b agrees with PM+MR=PR.')
add(8,m(r'|u|=|v|=1,\ u\perp v,\ u+v+w=0')+'일 때 |w|를 구하라.','Find |w| if '+m(r'|u|=|v|=1,\ u\perp v,\ u+v+w=0')+'.',[m(r'w=-(u+v),\quad |w|^2=|u|^2+|v|^2=2')],[m(r'w=-(u+v),\quad |w|^2=|u|^2+|v|^2=2')],m(r'|w|=\sqrt2'),ck='두 단위 직각변을 가진 직각삼각형의 빗변이다.',ce='This is the hypotenuse for perpendicular unit legs.')
for n,A,B in [(9,(-2,1),(1,2)),(10,(-5,-1),(-3,3)),(11,(3,-1),(2,3)),(12,(3,2),(1,0)),(13,(1,-2,4),(-2,3,0)),(14,(3,0,-2),(0,5,0))]:
 q=tuple(y-x for x,y in zip(A,B));add(n,m(f'A={A},B={B}')+'에서 AB벡터를 구하고 원점에서 시작하는 같은 벡터를 그려라.','Find AB for '+m(f'A={A},B={B}')+' and draw its equivalent from the origin.',[m(r'\overrightarrow{AB}=B-A='+v(q))],[m(r'\overrightarrow{AB}=B-A='+v(q))],m('a='+v(q)),ck='A에 이 벡터를 더하면 B가 된다.',ce='Adding this vector to A recovers B.')
for n,a,c in [(15,(-1,4),(6,-2)),(16,(3,-1),(-1,5)),(17,(3,0,1),(0,8,0)),(18,(1,3,-2),(0,0,6))]:
 q=tuple(x+y for x,y in zip(a,c));add(n,m(v(a)+r',\ '+v(c))+'의 합을 구하고 기하적으로 나타내라.','Add and illustrate '+m(v(a)+r',\ '+v(c))+'.',['대응 성분을 더한다. 그림에서는 첫 화살표 끝에 두 번째를 붙인다.'],['Add corresponding coordinates; in the diagram place the second arrow at the first tip.'],m(v(q)),ck='합에서 두 번째 벡터를 빼면 첫 벡터를 얻는다.',ce='Subtracting the second vector from the sum recovers the first.')
for n,a,c in [(19,(-3,4),(9,-1)),(20,(5,3),(-1,-2)),(21,(4,-3,2),(2,0,-4)),(22,(8,1,-4),(5,-2,1))]:
 av=S.Matrix(a);bv=S.Matrix(c);ans=[v(av+bv),v(4*av+2*bv),S.latex(S.sqrt(av.dot(av))),S.latex(S.sqrt((av-bv).dot(av-bv)))];add(n,m('a='+v(a)+r',\ b='+v(c))+'에 대해 a+b,4a+2b,|a|,|a−b|를 구하라.','For '+m('a='+v(a)+r',\ b='+v(c))+', find a+b,4a+2b,|a|,|a−b|.',[m('a-b='+v(av-bv)),m(r'|a|^2='+S.latex(av.dot(av))+r',\ |a-b|^2='+S.latex((av-bv).dot(av-bv)))],[m('a-b='+v(av-bv)),m(r'|a|^2='+S.latex(av.dot(av))+r',\ |a-b|^2='+S.latex((av-bv).dot(av-bv)))],m(r'a+b='+ans[0]+r',\ 4a+2b='+ans[1]+r',\ |a|='+ans[2]+r',\ |a-b|='+ans[3]))
for n,a,length in [(23,(6,-2),1),(24,(-5,3,-1),1),(25,(8,-1,4),1),(26,(6,2,-3),4)]:
 av=S.Matrix(a);norm=S.sqrt(av.dot(av));q=length*av/norm;add(n,m(v(a))+'와 같은 방향이고 길이가 '+str(length)+'인 벡터를 구하라.','Find the vector in the direction of '+m(v(a))+' with length '+str(length)+'.',[m(r'|a|='+S.latex(norm)+r',\ u='+str(length)+r'\frac{a}{|a|}')],[m(r'|a|='+S.latex(norm)+r',\ u='+str(length)+r'\frac{a}{|a|}')],m('u='+v(q)),ck='양의 배수이며 계산한 길이가 요구한 값이다.',ce='The multiple is positive and its length equals the requested value.')
for n,a,ans in [(27,r'\langle1,\sqrt3\rangle',r'\theta=\pi/3=60^\circ'),(28,r'\langle8,6\rangle',r'\theta=\arctan(3/4)\approx36.87^\circ')]:add(n,m(a)+'와 양의 x축 사이 각을 구하라.','Find the angle between '+m(a)+' and the positive x-axis.',['두 성분이 양수이므로 제1사분면이며 각의 탄젠트는 y성분/x성분이다.'],['Both components are positive, so the direction lies in quadrantI and its tangent is y/x.'],m(ans),ck='각이0°와90°사이에 있다.',ce='The angle lies between0° and90°.')
add(29,'원점에서 시작해 제3사분면을 향하는 길이4의 벡터가 양의 x축과5π/6의 각을 이룬다. 성분을 구하라.','A length-4 vector from the origin ends in quadrantIII and makes an angle5π/6 with the positive x-axis. Find its components.',['제3사분면 조건 때문에 방향각은 반시계방향5π/6이 아니라7π/6이다. 문제의5π/6은 두 방향 사이의 작은 각이다.',m(r'v=4\langle\cos(7\pi/6),\sin(7\pi/6)\rangle')],['QuadrantIII requires standard direction7π/6, not counterclockwise5π/6. The stated5π/6 is the smaller angle between the directions.',m(r'v=4\langle\cos(7\pi/6),\sin(7\pi/6)\rangle')],m(r'v=\langle-2\sqrt3,-2\rangle'),ck='두 성분이 음수이고 길이는√(12+4)=4이다.',ce='Both components are negative and the length is√(12+4)=4.')
for n,mag,deg,unit,ko,en in [(30,50,38,'N','수평보다38°위로50N 힘으로 썰매를 당긴다. 수평·수직 성분을 구하라.','A sled is pulled with50N at38° above horizontal. Find both components.'),(31,60,40,'ft/s','풋볼을40°상방으로60ft/s로 던진다. 속도의 수평·수직 성분을 구하라.','A football is thrown at60ft/s and elevation40°. Find the horizontal and vertical components.')]:
 xx=mag*math.cos(math.radians(deg));yy=mag*math.sin(math.radians(deg));add(n,ko,en,[m(fr'v_x={mag}\cos{deg}^\circ,\quad v_y={mag}\sin{deg}^\circ')],[m(fr'v_x={mag}\cos{deg}^\circ,\quad v_y={mag}\sin{deg}^\circ')],m(fr'({xx:.3f},{yy:.3f})')+' '+unit,ck='두 성분 제곱의 합은 원래 크기의 제곱이다.',ce='The sum of squared components equals the squared magnitude.')
for n,x,y,k,e,unit in [(32,20/math.sqrt(2)+8*math.sqrt(3),20/math.sqrt(2)-8,'양의x축에서45°의20lb 힘과 −30°의16lb 힘의 합력 크기·방향을 구하라.','Find the resultant magnitude and direction for20lb at45° and16lb at−30°.','lb'),(33,-200,100*math.sqrt(3),'왼쪽300N 힘과 양의x축에서60°인200N 힘의 합력 크기·방향을 구하라.','Find the resultant magnitude and direction for300N leftward plus200N at60°.','N')]:
 mag=math.hypot(x,y);ang=math.degrees(math.atan2(y,x));add(n,k,e,[m(fr'R=\langle{x:.6f},{y:.6f}\rangle'),m(r'|R|=\sqrt{R_x^2+R_y^2},\quad\theta=\operatorname{atan2}(R_y,R_x)')],[m(fr'R=\langle{x:.6f},{y:.6f}\rangle'),m(r'|R|=\sqrt{R_x^2+R_y^2},\quad\theta=\operatorname{atan2}(R_y,R_x)')],m(fr'|R|\approx{mag:.3f},\quad\theta\approx{ang:.3f}^\circ')+'; '+unit,ck='성분의 부호에 맞는 사분면을 선택했다.',ce='The quadrant agrees with the component signs.')
add(34,'500lb 수평 강철빔의 양 끝에서 수평과60°를 이루는 두 케이블이 빔을 지탱한다. 각 장력벡터와 크기를 구하라.','Two cables at60° above horizontal support opposite ends of a horizontal500lb beam. Find their tension vectors and magnitudes.',[m(r'T_L=\langle T\cos60^\circ,T\sin60^\circ\rangle,\quad T_R=\langle-T\cos60^\circ,T\sin60^\circ\rangle'),m(r'2T\sin60^\circ=500')],[m(r'T_L=\langle T\cos60^\circ,T\sin60^\circ\rangle,\quad T_R=\langle-T\cos60^\circ,T\sin60^\circ\rangle'),m(r'2T\sin60^\circ=500')],m(r'T_L=\langle250/\sqrt3,250\rangle,\quad T_R=\langle-250/\sqrt3,250\rangle,\quad |T_L|=|T_R|=500/\sqrt3\approx288.675')+' lb',ck='두 장력의 합은(0,500)lb이며 무게를 상쇄한다.',ce='The tensions sum to(0,500)lb and balance the weight.')
L=350*math.cos(math.radians(38))/math.sin(math.radians(88));RR=350*math.cos(math.radians(50))/math.sin(math.radians(88));xx=L*math.cos(math.radians(50));yl=L*math.sin(math.radians(50));yr=RR*math.sin(math.radians(38))
add(35,'350N 도르래가 왼쪽2m·50°, 오른쪽3m·38°(수평 기준)의 줄에 매달려 있다. 두 장력벡터와 크기를 구하라.','A350N hoist hangs from a left2m rope at50° and a right3m rope at38° to horizontal. Find both tension vectors and magnitudes.',[m(r'-T_L\cos50^\circ+T_R\cos38^\circ=0,\quad T_L\sin50^\circ+T_R\sin38^\circ=350'),m(r'T_L=\frac{350\cos38^\circ}{\sin88^\circ},\quad T_R=\frac{350\cos50^\circ}{\sin88^\circ}')],[m(r'-T_L\cos50^\circ+T_R\cos38^\circ=0,\quad T_L\sin50^\circ+T_R\sin38^\circ=350'),m(r'T_L=\frac{350\cos38^\circ}{\sin88^\circ},\quad T_R=\frac{350\cos50^\circ}{\sin88^\circ}')],m(fr'\mathbf T_L\approx\langle{-xx:.3f},{yl:.3f}\rangle,\quad\mathbf T_R\approx\langle{xx:.3f},{yr:.3f}\rangle,\quad T_L\approx{L:.3f},\ T_R\approx{RR:.3f}')+' N',ck='수평 성분은 상쇄되고 수직 성분 합은350N이다. 길이는 주어진 각도 이후 평형식에 필요하지 않다.',ce='Horizontal components cancel and vertical components total350N. Once angles are known, rope lengths do not enter equilibrium.')
add(36,'양 끝 장력이각25N이며 수평과37°를 이루는 사슬의 무게를 구하라.','Find the weight of a chain with25N tension at each end, directed37° above horizontal.',[m(r'W=25\sin37^\circ+25\sin37^\circ')],[m(r'W=25\sin37^\circ+25\sin37^\circ')],m(fr'W=50\sin37^\circ\approx{50*math.sin(math.radians(37)):.3f}')+' N',ck='두 수평성분은 반대이므로 상쇄된다.',ce='The opposite horizontal components cancel.')
add(37,'25N과12N 힘이100°를 이루고4N 힘이 그 평면에 수직이다. 세 힘을 상쇄할 힘의 크기를 구하라.','Forces of25N and12N form100°, and a4N force is perpendicular to their plane. Find the balancing-force magnitude.',[m(r'|R|^2=25^2+12^2+2(25)(12)\cos100^\circ+4^2')],[m(r'|R|^2=25^2+12^2+2(25)(12)\cos100^\circ+4^2')],m(fr'|F|=\sqrt{{785+600\cos100^\circ}}\approx{math.sqrt(785+600*math.cos(math.radians(100))):.3f}')+' N',ck='상쇄력은 합력과 크기는 같고 방향은 반대이다.',ce='The balancing force has the resultant magnitude and the opposite direction.')
# x across the channel, y upstream; current=(0,-3).
t=(4800+math.sqrt(4800**2+4*40*2600000))/80;vx=1400/t;vy=800/t+3;ang=math.degrees(math.atan2(vy,vx))
add(38,'폭1400ft 수로를 건너 출발점보다800ft 상류에 도착하려 한다. 정수에서 속력7ft/s, 흐름3ft/s일 때 (a)조향 방향 (b)소요시간을 구하라.','Cross a1400ft channel to a point800ft upstream. With still-water speed7ft/s and current3ft/s, find(a)heading and(b)travel time.',[m(r'v_{\rm water}=\langle1400/t,800/t+3\rangle,\quad (1400/t)^2+(800/t+3)^2=49'),m(r'40t^2-4800t-2600000=0')],[m(r'v_{\rm water}=\langle1400/t,800/t+3\rangle,\quad (1400/t)^2+(800/t+3)^2=49'),m(r'40t^2-4800t-2600000=0')],(m(fr'\theta\approx{ang:.3f}^\circ,\quad t\approx{t:.3f}\ \mathrm{{s}}')+' (맞은편을 향한 수직 방향에서 상류 쪽 각도).',m(fr'\theta\approx{ang:.3f}^\circ,\quad t\approx{t:.3f}\ \mathrm{{s}}')+' (heading upstream from straight across).'),list('ab'),ck='양의 이차방정식 근을 선택해야 한다. 물에 대한 속도의 크기는7이다.',ce='Choose the positive quadratic root; the water-relative speed is7.')
# Correct positive root for 40t²−4800t−2600000=0.
east=-180/math.sqrt(2)+35/2;north=180/math.sqrt(2)-35*math.sqrt(3)/2;speed=math.hypot(east,north);angle=math.degrees(math.atan2(-east,north))
add(39,'비행기가 N45°W로 대기속력180mi/h로 가고 바람은 S30°E 방향35mi/h이다. 실제 진로와 지상속력을 구하라.','A plane heads N45°W at180mi/h; wind blows toward S30°E at35mi/h. Find its track and ground speed.',[m(r'v=\langle-180/\sqrt2+35/2,\ 180/\sqrt2-35\sqrt3/2\rangle')],[m(r'v=\langle-180/\sqrt2+35/2,\ 180/\sqrt2-35\sqrt3/2\rangle')],m(fr'\mathrm{{N}}{angle:.3f}^\circ\mathrm{{W}},\quad |v|\approx{speed:.3f}\ \mathrm{{mi/h}}'),ck='바람은 S30°E로 향하는 것으로 주어졌다. 출발 방향을 뜻하는 기상식표현과 구별한다.',ce='The wind is specified as blowing toward S30°E, not from that direction.')
add(40,'배는서쪽32km/h, 개는갑판 위에서북쪽4km/h로 달린다. 수면에 대한 개의 속력·방향을 구하라.','A ship moves west32km/h; a dog runs north4km/h on deck. Find the dog’s speed and direction relative to the water.',[m(r'v=\langle-32,4\rangle,\quad |v|=\sqrt{32^2+4^2}=4\sqrt{65}')],[m(r'v=\langle-32,4\rangle,\quad |v|=\sqrt{32^2+4^2}=4\sqrt{65}')],m(r'|v|=4\sqrt{65}\approx32.249\ \mathrm{km/h},\quad\mathrm{N}82.875^\circ\mathrm{W}'),ck='서쪽에서 북쪽으로7.125°와 같은 방향이다.',ce='Equivalently, the direction is7.125° north of west.')
add(41,m('y=x^2')+'의(2,4)에서 접선과 평행한 단위벡터들을 구하라.','Find unit vectors parallel to the tangent of '+m('y=x^2')+' at(2,4).',[m(r'y\prime(2)=4,\quad d=\langle1,4\rangle,\quad|d|=\sqrt{17}')],[m(r'y\prime(2)=4,\quad d=\langle1,4\rangle,\quad|d|=\sqrt{17}')],m(r'\pm\frac{1}{\sqrt{17}}\langle1,4\rangle'),ck='서로 반대인 두 방향 모두 접선과 평행하다.',ce='Both opposite directions are parallel to the tangent.')
add(42,m(r'y=2\sin x')+'의 '+m(r'(\pi/6,1)')+'에서(a)접선에 평행한 단위벡터들,(b)수직인 단위벡터들,(c)모두 그 점에서 시작하는 그림을 구하라.','At '+m(r'(\pi/6,1)')+' on '+m(r'y=2\sin x')+', find(a)parallel tangent unit vectors,(b)perpendicular unit vectors,(c)draw all starting at the point.',[m(r'y\prime(\pi/6)=2\cos(\pi/6)=\sqrt3'),m(r'd=\langle1,\sqrt3\rangle,\quad n=\langle-\sqrt3,1\rangle,\quad |d|=|n|=2')],[m(r'y\prime(\pi/6)=2\cos(\pi/6)=\sqrt3'),m(r'd=\langle1,\sqrt3\rangle,\quad n=\langle-\sqrt3,1\rangle,\quad |d|=|n|=2')],m(r'(a)\ \pm\langle1/2,\sqrt3/2\rangle,\quad(b)\ \pm\langle-\sqrt3/2,1/2\rangle'),parts=list('abc'),ck='두 대표 벡터의 내적은0이고 각 길이는1이다.',ce='The representative vectors have zero dot product and unit lengths.')
add(43,'삼각형ABC의 AB+BC+CA를 구하라(유향선분).','Find AB+BC+CA for triangle ABC using directed segments.',[m(r'(B-A)+(C-B)+(A-C)=0')],[m(r'(B-A)+(C-B)+(A-C)=0')],m(r'\overrightarrow{AB}+\overrightarrow{BC}+\overrightarrow{CA}=\mathbf0'),ck='출발점으로 돌아오는 전체 변위는0이다.',ce='A closed trip has zero displacement.')
add(44,'C는 선분AB 위에서 B까지 거리가 A까지 거리의2배인 점이다. 위치벡터a,b,c에 대해 c=(2a+b)/3임을 보여라.','C lies on segment AB with distance to B twice its distance to A. Prove the position-vector formula c=(2a+b)/3.',[m(r'AC:CB=1:2,\quad c=a+\frac13(b-a)')],[m(r'AC:CB=1:2,\quad c=a+\frac13(b-a)')],m(r'c=\frac23a+\frac13b'),ck='c−a=(b−a)/3, b−c=2(b−a)/3이다.',ce='c−a=(b−a)/3 and b−c=2(b−a)/3.')
add(45,m(r'a=\langle3,2\rangle,b=\langle2,-1\rangle,c=\langle7,1\rangle')+'를(a)그리고(b)c=sa+tb를 그림으로 설명하고(c)s,t를 추정한 뒤(d)정확히 구하라.','For '+m(r'a=\langle3,2\rangle,b=\langle2,-1\rangle,c=\langle7,1\rangle')+', (a)plot the vectors,(b)illustrate c=sa+tb,(c)estimate s,t,(d)find exact values.',[m(r'3s+2t=7,\quad2s-t=1'),m(r't=2s-1,\quad7s=9,\quad s=9/7,\ t=11/7')],[m(r'3s+2t=7,\quad2s-t=1'),m(r't=2s-1,\quad7s=9,\quad s=9/7,\ t=11/7')],m(r's=9/7\approx1.286,\quad t=11/7\approx1.571'),parts=list('abcd'),ck='선형결합의 성분은(27/7+22/7,18/7−11/7)=(7,1)이다.',ce='The combination is(27/7+22/7,18/7−11/7)=(7,1).')
add(46,'0이 아니고 평행하지 않은 a,b가 만드는 평면의 임의벡터c가 sa+tb로 표현됨을 기하·성분 두 방법으로 설명하라.','Give geometric and component arguments that nonparallel nonzero vectors a,b span every c in their plane.',['기하: c의 끝점을 지나 a,b에 각각 평행한 직선을 그리면 a,b방향의 두 변으로 된 평행사변형을 얻는다. 변들의 부호있는 배수를 s,t로 둔다.',m(r'\det\begin{pmatrix}a_1&b_1\\a_2&b_2\end{pmatrix}\ne0'),'성분: 평면 안에 직교좌표를 잡으면 위 행렬식이0이 아니므로 두 성분의 연립방정식은 유일한 해를 갖는다.'],['Geometrically, lines through the tip of c parallel to a and b complete a parallelogram with signed side multiples s,t.',m(r'\det\begin{pmatrix}a_1&b_1\\a_2&b_2\end{pmatrix}\ne0'),'In orthonormal coordinates within the plane, the nonzero determinant gives a unique solution for the two components.'],m(r'c=sa+tb'),ck='비평행 조건이 행렬식이0이 아니라는 조건과 동치이다.',ce='Nonparallelism is equivalent to the nonzero determinant.')
add(47,m(r'r=\langle x,y,z\rangle,r_0=\langle x_0,y_0,z_0\rangle,\quad|r-r_0|=1')+'의 자취를 설명하라.','Describe the locus '+m(r'r=\langle x,y,z\rangle,r_0=\langle x_0,y_0,z_0\rangle,\quad|r-r_0|=1')+'.',[m(r'(x-x_0)^2+(y-y_0)^2+(z-z_0)^2=1')],[m(r'(x-x_0)^2+(y-y_0)^2+(z-z_0)^2=1')],'중심(x₀,y₀,z₀), 반지름1인 구면.','The sphere centered at(x₀,y₀,z₀) with radius1.',ck='고정점까지의 거리를1로 고정한 자취이다.',ce='Distance to the fixed center is exactly1.')
add(48,m(r'r=\langle x,y\rangle,\quad |r-r_1|+|r-r_2|=k>|r_1-r_2|')+'의 자취를 설명하라.','Describe '+m(r'r=\langle x,y\rangle,\quad |r-r_1|+|r-r_2|=k>|r_1-r_2|')+'.',[r'두 고정점까지 거리의 합이 일정하므로 타원이다. 장반경은k/2이다.',m(r'a=k/2,\quad c=|r_1-r_2|/2,\quad b=\tfrac12\sqrt{k^2-|r_1-r_2|^2}')],[r'A constant sum of distances to two fixed foci defines an ellipse with semimajor axis k/2.',m(r'a=k/2,\quad c=|r_1-r_2|/2,\quad b=\tfrac12\sqrt{k^2-|r_1-r_2|^2}')],'초점r₁,r₂인 타원. 초점이 같으면 반지름k/2인 원이다.','An ellipse with foci r₁,r₂; coincident foci give a radius-k/2 circle.',ck='k가 초점거리보다 커서 단반경이 양수이다.',ce='k exceeds focal separation, so the semiminor axis is positive.')
assert len(b.E)==48
b.save()
