from calc1_core import *
D=CalcDoc('2.3',[143,144,145,146,147],lambda n:143 if n<=32 else 144 if n<=73 else 145 if n<=90 else 146 if n<=110 else 147)
x,h=s.symbols('x h',real=True);a,b,c,dd,A,B,C=s.symbols('a b c d A B C',real=True)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('미분 공식과 접선','Differentiation rules and tangents'),st,('거듭제곱·합·곱·몫 법칙 중 식에 맞는 규칙을 고르고 정의역을 유지한다.','Choose the appropriate power, sum, product, or quotient rule, preserving the domain.'),steps,ans,check,parts)
def same(q):return(d(q),d(q))
def fmt(f,var='x'):return tex(f).replace('x',var)
# Expressions independently transcribed from visually inspected PDF180–181.
forms={1:4*x+7,2:5*x+4*x*x,3:x**75-x+3,4:s.Rational(7,4)*x*x-3*x+12,5:s.Rational(18,10)*x**-3,6:x**-5-s.sqrt(x),7:x**s.Rational(3,2)+x**-3,8:x**s.Rational(-3,5)+x**4,9:1/x+1/x**2,10:a/x**2+b/x**4,11:2*x+s.sqrt(x),12:s.sqrt(2)*x-s.sqrt(2),13:1/s.sqrt(x)+x**s.Rational(1,4),14:4*s.pi*x*x,15:x**3*(x+3),16:(2*x-3)**2,17:(3*x*x+x**3)/x,18:(s.sqrt(x)+x)/x**2,19:(1+1/x)**2,20:s.sqrt(5*x)+s.sqrt(7)/x,21:(3*x**s.Rational(3,2)+x**s.Rational(5,2))/x,22:(A+B*x+C*x*x)/x**2,23:(2*x*x-x+4)/s.sqrt(x),24:(1+16*x*x)/(4*x)**3,
37:5*x/(x**3-x-1),38:1/(2*x**3-6*x*x+5),39:(x-s.sqrt(x))/x**2,40:s.sqrt(x)/(s.sqrt(x)+1),41:(2*x**5+x**4-6*x)/x**3,42:(x+2)**2/(1-x),43:(x-s.sqrt(x))*(x+s.sqrt(x)),44:x**s.Rational(2,3)*(2*x*x+1-x**-2),45:(1/x+1/x**2)*(x+1/x),46:(x*x+3*x)*(x**-1-x**-4),47:x**s.Rational(1,3)/(x-3),48:c*x/(1+c*x),49:B/(A*x**3+B),50:A*x/(B*x*x+C*x**3),51:x/(x+c/x),52:(a*x+b)/(c*x+dd)}
vars={2:'t',5:'v',6:'z',8:'t',9:'t',10:'t',12:'w',14:'R',16:'t',19:'q',20:'t',21:'r',22:'z',23:'w',24:'t',37:'t',39:'s',42:'u',43:'u',44:'v',45:'u',46:'w',47:'t',49:'y',50:'t'}
for n,f in forms.items():
 var=vars.get(n,'x');expanded=s.expand(f);de=s.factor(s.diff(f,x));steps=[]
 if n<=24 or n in[39,41,43,44,45,46]:
  if n>=15:steps.append(same('f('+var+')='+fmt(expanded,var)))
  terms=s.Add.make_args(expanded)
  for term in terms:
   steps.append(same(r'\frac{d}{d'+var+r'}\left('+fmt(term,var)+r'\right)='+fmt(s.diff(term,x),var)))
 else:
  U,V=s.fraction(f);steps.append(same('U='+fmt(U,var)+r',\ U\prime='+fmt(s.diff(U,x),var)+r',\ V='+fmt(V,var)+r',\ V\prime='+fmt(s.diff(V,x),var)))
  steps.append(same(r'f\prime=\frac{VU\prime-UV\prime}{V^2}=\frac{('+fmt(V,var)+')('+fmt(s.diff(U,x),var)+')-('+fmt(U,var)+')('+fmt(s.diff(V,x),var)+')}{('+fmt(V,var)+')^2}'))
 extra='';extraen=''
 if n in[8,44,47]:extra=' 유리 지수의 홀수근은 실수근으로 해석한다.';extraen=' Odd roots in rational powers are interpreted as real roots.'
 if n==43:extra+=' 원래 근호 조건 u≥0을 유지한다. 내부 u>0의 도함수는2u−1이고 경계0의 오른쪽 미분값도−1이다.';extraen+=' Preserve the original radical restriction u≥0. The interior derivative is2u−1; the right derivative at the endpoint0 is also−1.'
 if n==51:extra+=' 약분 후에도 원식의 x≠0 조건을 유지한다.';extraen+=' Retain the original restriction x≠0 after simplification.'
 ask='먼저 전개하거나 거듭제곱 합으로 바꾼 뒤 곱·몫 법칙 없이 미분하라.'if 15<=n<=24 else'미분하라.'
 asken='First expand or rewrite as a sum of powers, then differentiate without product or quotient rules.'if 15<=n<=24 else'Differentiate.'
 stmath=fmt(f,var)
 if n==20:stmath=r'\sqrt{5t}+\frac{\sqrt7}t'
 add(n,('함수 '+m('f('+var+')='+stmath)+'를 '+ask,'For '+m('f('+var+')='+stmath)+', '+asken),steps,d(r'f\prime('+var+')='+fmt(de,var)),('각 항 또는 분자·분모를 별도로 미분한 결과를 기호 미분과 대조했다. 식은 원함수가 정의되고 유한 도함수가 존재하는 점에서 사용한다.'+extra,'Checked termwise or separate numerator/denominator derivatives against symbolic differentiation. The formula applies where the original function is defined and its derivative is finite.'+extraen))
# Two independent variables: differentiate with the other held constant.
t=s.symbols('t',real=True)
for n,f in[(25,t*x*x+t**3*x),(26,t/x**2+x/t)]:
 dx=s.diff(f,x);dt=s.diff(f,t)
 add(n,('식 '+m('y='+tex(f))+'에서 다른 변수를 상수로 보아 dy/dx와 dy/dt를 구하라.','For '+m('y='+tex(f))+', find dy/dx and dy/dt, holding the other variable constant.'),[('x로 미분할 때 t는 상수이고,t로 미분할 때 x는 상수이다.','Treat t as constant when differentiating with respect to x, and x as constant when differentiating with respect to t.'),same(r'\frac{dy}{dx}='+tex(dx)),same(r'\frac{dy}{dt}='+tex(dt))],d(r'\frac{dy}{dx}='+tex(dx)+r',\quad\frac{dy}{dt}='+tex(dt)),('각 편미분에서 고정한 변수의 거듭제곱을 계수로 유지했다.'+(' x,t 모두0을 제외한다.'if n==26 else''),'Kept powers of the fixed variable as coefficients.'+(' Both x and t must be nonzero.'if n==26 else'')))
for n,U,V in[(27,1+2*x*x,x-x*x),(29,3*x*x-5*x,x*x),(30,10*x*x+7*x-2,2-x*x),(31,4*x*x+3,2*x+5),(32,s.sqrt(x),x+2*s.sqrt(x))]:
 f=U*V;rule=U*s.diff(V,x)+V*s.diff(U,x);de=s.expand(rule);steps=[same('U='+tex(U)+r',\ U\prime='+tex(s.diff(U,x))+r';\quad V='+tex(V)+r',\ V\prime='+tex(s.diff(V,x))),same(r'f\prime=UV\prime+VU\prime=('+tex(U)+')('+tex(s.diff(V,x))+')+('+tex(V)+')('+tex(s.diff(U,x))+')')]
 if n==27:steps.append(same('f='+tex(s.expand(f))+r'\ \Longrightarrow\ f\prime='+tex(s.diff(s.expand(f),x))))
 add(n,('함수 '+m('f(x)=('+tex(U)+')('+tex(V)+')')+'를 '+('곱 법칙과 먼저 전개하는 두 방법으로 미분하고 비교하라.'if n==27 else'곱 법칙으로 미분하라.'),'Differentiate '+m('f(x)=('+tex(U)+')('+tex(V)+')')+(' both with the product rule and by expanding first, then compare.'if n==27 else' using the product rule.')),steps,d(r'f\prime(x)='+tex(de)),('먼저 곱을 전개하여 얻은 도함수와 같음을 확인했다.'+(' x=0에서는 곱 법칙의 √x 미분을 직접 쓸 수 없지만,간단한 식 x^(3/2)+2x의 오른쪽 미분은2이다.'if n==32 else''),'Expansion before differentiation gives the same result.'+(' At x=0 the product-rule derivative of √x is unavailable, but the simplified expression x^(3/2)+2x has right derivative2.'if n==32 else'')))
for n,U,V in[(28,x**4-5*x**3+s.sqrt(x),x*x),(33,5*x,1+x),(34,x*x,1-x),(35,3-2*x,5*x+1),(36,6*x**4-5*x,x+1)]:
 var={35:'t',36:'u'}.get(n,'x');de=s.factor((V*s.diff(U,x)-U*s.diff(V,x))/V**2)
 steps=[same('U='+fmt(U,var)+r',\ U\prime='+fmt(s.diff(U,x),var)+r',\ V='+fmt(V,var)+r',\ V\prime='+fmt(s.diff(V,x),var)),same(r'f\prime=\frac{VU\prime-UV\prime}{V^2}=\frac{('+fmt(V,var)+')('+fmt(s.diff(U,x),var)+')-('+fmt(U,var)+')('+fmt(s.diff(V,x),var)+')}{('+fmt(V,var)+')^2}')]
 if n==28:steps.append(same(r'f=x^2-5x+x^{-3/2}\ \Longrightarrow\ f\prime=2x-5-\frac3{2x^{5/2}}'))
 add(n,('함수 '+m('f('+var+')='+fmt(U/V,var))+'를 '+('몫 법칙과 먼저 나누어 정리하는 두 방법으로 미분하고 비교·선호를 설명하라.'if n==28 else'몫 법칙으로 미분하라.'),'Differentiate '+m('f('+var+')='+fmt(U/V,var))+(' by the quotient rule and by simplifying first; compare and state a preference.'if n==28 else' using the quotient rule.')),steps,d(r'f\prime('+var+')='+fmt(de,var)),('분모0은 제외하고 독립 기호 미분과 대조했다.'+('28번은 거듭제곱 세 항으로 먼저 나누면 연산이 짧아져 더 편리하다.'if n==28 else''),'Excluded zeros of the denominator and compared against independent symbolic differentiation.'+('For28, dividing into three powers first is shorter and more convenient.'if n==28 else'')))
add(53,('일반 다항식 '+m(r'P(x)=a_nx^n+a_{n-1}x^{n-1}+\cdots+a_1x+a_0,\ a_n\ne0')+'의 도함수를 구하라.','Differentiate the general polynomial '+m(r'P(x)=a_nx^n+a_{n-1}x^{n-1}+\cdots+a_1x+a_0,\ a_n\ne0')+'.'),[('합을 항별로 미분한다. 각 a_k는 상수이고 x^k의 도함수는 kx^(k−1)이며 상수항은0이 된다.','Differentiate term by term. Each a_k is constant, the derivative of x^k is kx^(k−1), and the constant term vanishes.')],d(r'P\prime(x)=\sum_{k=1}^n k a_kx^{k-1}=na_nx^{n-1}+\cdots+2a_2x+a_1'),('n≥1이면 최고차항 계수 na_n≠0이므로 도함수의 차수는 n−1이다.','For n≥1 the leading coefficient na_n is nonzero, giving degree n−1.'))
def plots(n,fs,bounds,segments=None,title=None):
 cs=[];colors=['#1d4ed8','#dc2626','#15803d','#9333ea']
 for i,f in enumerate(fs):
  fn=s.lambdify(x,f,'math')
  for lo,hi in segments or[(bounds[0],bounds[1])]:cs.append({'points':samples(fn,lo,hi,500),'color':colors[i]})
 D.fig(n,[panel(title or('Blue: f; red: f1'+('; green: f2'if len(fs)>2 else'')),bounds,cs)])
for n,f,bounds in[(54,x**4-2*x**3+x*x,(-.6,1.6,-1,2)),(55,3*x**15-5*x**3+3,(-1.2,1.2,-6,10)),(56,x+1/x,(-4,4,-6,6)),(57,x**4-3*x**3-6*x*x+7*x+30,(-3,5,-10,50)),(58,x*x/(1+x*x),(-4,4,-1,1.5))]:
 de=s.factor(s.diff(f,x));roots=s.solve(de,x);realroots=[z for z in roots if z.is_real];realroots=[s.re(z)for z in s.nroots(de)if abs(float(s.im(z)))<1e-12]if n==57 else realroots;approx=', '.join(f'{float(z):.4g}'for z in realroots)
 st=('함수 '+m('f(x)='+tex(f))+'의 도함수를 구하고 f,f′ 그래프로 결과가 타당한지 설명하라.','Differentiate '+m('f(x)='+tex(f))+' and explain consistency using graphs of f and f′.')
 if n in[57,58]:st=('함수 '+m('f(x)='+tex(f))+f'를 창 [{bounds[0]},{bounds[1]}]×[{bounds[2]},{bounds[3]}]에서(a)그리고(b)접선 기울기로 f′를 예상한 뒤(c)계산한 도함수 그래프와 비교하라.','For '+m('f(x)='+tex(f))+f', (a)plot in [{bounds[0]},{bounds[1]}]×[{bounds[2]},{bounds[3]}], (b)predict f′ from slopes, and(c)compare with the calculated derivative.')
 steps=[('거듭제곱 합을 미분한다.'if n in[54,55,57]else'분수를 거듭제곱으로 바꾸거나 몫 법칙을 적용한다.','Differentiate the power sum.'if n in[54,55,57]else'Rewrite inverse powers or apply the quotient rule.'),same(r'f\prime(x)='+tex(de)),('수평 접선 후보는 x≈'+approx+'이다. 도함수가 양수인 곳은 f가 증가하고 음수인 곳은 감소한다.','Horizontal-tangent candidates occur at x≈'+approx+'. Positive derivative intervals match increase of f, and negative intervals match decrease.')]
 add(n,st,steps,d(r'f\prime(x)='+tex(de)),('도함수 영점에 대응하는 원함수의 수평 접선과 구간별 부호를 도해에서 확인했다.'+(' x=0은 두 그래프 모두에서 제외한다.'if n==56 else''),'Checked horizontal tangents corresponding to derivative zeros and interval signs in the plots.'+('Exclude x=0 from both graphs.'if n==56 else'')),list('abc')if n in[57,58]else())
 if n==57:
  D.fig(n,[panel('Function in required viewing rectangle',bounds,[samples(s.lambdify(x,f,'math'),-3,5,600)]),panel('Calculated derivative and horizontal-tangent zeros',(-3,5,-60,100),[samples(s.lambdify(x,de,'math'),-3,5,600)],[(float(z),0)for z in realroots])])
 else:plots(n,[f,de],bounds,[(-4,-.04),(.04,4)]if n==56 else None)
for n,f,at,val in[(59,2*x/(x+1),1,1),(60,2*x**3-x*x+2,1,3),(61,x+s.sqrt(x),1,2),(62,x**s.Rational(3,2),1,1),(63,3*x/(1+5*x*x),1,s.Rational(1,2)),(64,s.sqrt(x)/(x+1),4,s.Rational(2,5)),(65,1/(1+x*x),-1,s.Rational(1,2)),(66,x/(1+x*x),3,s.Rational(3,10))]:
 de=s.factor(s.diff(f,x));slope=de.subs(x,at);line=s.expand(val+slope*(x-at));normal=s.expand(val-(x-at)/slope)
 add(n,('곡선 '+m('y='+tex(f))+f'의 점 ({at},'+str(val)+')에서 '+('접선과 법선 방정식을 구하라.'if 61<=n<=64 else'(a)접선식을 구하고(b)곡선과 접선을 함께 그려라.'if n>=65 else'접선 방정식을 구하라.'),'For '+m('y='+tex(f))+f' at({at},'+str(val)+'), '+('find tangent and normal equations.'if 61<=n<=64 else'(a)find the tangent and(b)plot it with the curve.'if n>=65 else'find the tangent equation.')),[same(r'y\prime='+tex(de)+r',\quad m_T='+tex(slope)),same('y-('+tex(val)+')=('+tex(slope)+')(x-('+str(at)+'))')]+([same(r'm_N=-1/m_T='+tex(-1/slope))]if 61<=n<=64 else[]),d('y_T='+tex(line)+(r',\quad y_N='+tex(normal)if 61<=n<=64 else'')),('원곡선과 직선에 접점이 들어맞고 접선 기울기는 도함수 값과 같다.'+(' 두 기울기의 곱은−1이다.'if 61<=n<=64 else''),'The point lies on the original curve and line, whose slope agrees with the derivative.'+(' The tangent and normal slopes multiply to−1.'if 61<=n<=64 else'')),list('ab')if n>=65 else())
 if n>=65:plots(n,[f,line],(-4,5,-1.5,2),'',title='Blue: curve; red: tangent')
for n,f in[(67,s.Rational(1,1000)*x**5-s.Rational(2,100)*x**3),(68,s.sqrt(x)+x**s.Rational(1,3)),(69,x*x/(1+2*x)),(70,1/(3-x)),(71,2*x-5*x**s.Rational(3,4)),(72,(x*x-1)/(x*x+1))]:
 de=s.factor(s.diff(f,x));dde=s.factor(s.diff(de,x));var='r'if n==68 else'x'
 add(n,('함수 '+m('f('+var+')='+fmt(f,var))+'의1계·2계 도함수를 구하라.'+(' f,f′,f″를 함께 그려 기하적으로 검토하라.'if n>=71 else''),'Find the first and second derivatives of '+m('f('+var+')='+fmt(f,var))+'.'+(' Plot f,f′,f″ together and assess their geometric consistency.'if n>=71 else'')),[same(r'f\prime('+var+')='+fmt(de,var)),('첫 도함수에 거듭제곱·몫 법칙을 다시 적용한다.','Apply the power or quotient rule again to the first derivative.'),same(r'f\prime\prime('+var+')='+fmt(dde,var))],d(r'f\prime='+fmt(de,var)+r',\quad f\prime\prime='+fmt(dde,var)),('독립2회 기호 미분과 비교했다.'+(' 두 도함수는 r>0에서 유한하다.'if n==68 else' 두 도함수는 x>0에서 유한하다.'if n==71 else' 분모가0인 점은 제외한다.'if n in[69,70]else' 전 실수에서 성립한다.'),'Compared with independent twice-repeated symbolic differentiation.'+(' Both derivatives are finite for r>0.'if n==68 else' Both derivatives are finite for x>0.'if n==71 else' Exclude zeros of the denominator.'if n in[69,70]else' Valid for every real argument.')))
 if n>=71:plots(n,[f,de,dde],(.01,20,-12,8)if n==71 else(-4,4,-2,5))
for n,f in[(73,x**3-3*x),(74,x**4-2*x**3+x*x-x)]:
 v=s.diff(f,x);acc=s.diff(v,x);at=2 if n==73 else 1;av=acc.subs(x,at)
 st=('위치 '+m('s(t)='+fmt(f,'t'))+'(m),시간 t(초)에 대해(a)속도·가속도 함수,(b)'+str(at)+'초 가속도,'+('(c)속도가0일 때 가속도를 구하라(t≥0).'if n==73 else'(c)위치·속도·가속도 그래프를 함께 그려라.'),'For position '+m('s(t)='+fmt(f,'t'))+' in meters and time t in seconds, find(a)velocity and acceleration,(b)acceleration at'+str(at)+' seconds,and'+('(c)acceleration when velocity is zero(t≥0).'if n==73 else'(c)plot position,velocity,and acceleration together.'))
 steps=[same('v(t)='+fmt(v,'t')+r',\quad a(t)='+fmt(acc,'t')),same('a('+str(at)+')='+tex(av))]
 if n==73:steps.append(('v=0의 해는 t=±1이지만 물리적 시간 t≥0에서는1초이고 a(1)=6m/s²이다. 음수 시각까지 허용하면 a(−1)=−6도 얻는다.','The equation v=0 gives t=±1. For physical time t≥0, t=1 and a(1)=6m/s²; the mathematical extension to negative time also gives a(−1)=−6.'))
 add(n,st,steps,d('v='+fmt(v,'t')+r',\ a='+fmt(acc,'t')+r',\ a('+str(at)+')='+tex(av))+('(c)6m/s²'if n==73 else''),('속도는m/s,가속도는m/s²이며 위치를 두 번 미분해 확인했다.','Velocity has units m/s and acceleration m/s²; checked by differentiating position twice.'),list('abc'))
 if n==74:plots(n,[f,v,acc],(0,3,-3,50),title='Blue: position; red: velocity; green: acceleration')
for n,f,at,var,uk,ue in[(75,s.Rational('0.0155')*x**3-s.Rational('0.372')*x*x+s.Rational('3.95')*x+s.Rational('1.21'),12,'A','인치/년','inches/year'),(76,s.Rational('0.882')*x**s.Rational('0.842'),100,'A','종/m²','species/m²')]:
 de=s.diff(f,x);value=de.subs(x,at)
 add(n,('모형 '+m(('L'if n==75 else'S')+'(A)='+tex(f).replace('x','A'))+'에서 '+('A는나이(년),L은물고기길이(인치)이다.12세의 성장률과 의미를 구하라.'if n==75 else'A는삼림면적(m²),S는수종 수이다.S′(100)과 의미를 구하라.'),'In '+m(('L'if n==75 else'S')+'(A)='+tex(f).replace('x','A'))+', '+('A is age in years and L fish length in inches. Find the growth rate at age12 and interpret it.'if n==75 else'A is forest area in m² and S the number of tree species. Find and interpret S′(100).')),[same(r'\frac{d'+('L'if n==75 else'S')+'}{dA}='+fmt(de,'A')),('A='+str(at)+'를 대입하면 '+f'{float(value):.6g}'+uk+'이다.','At A='+str(at)+' this is '+f'{float(value):.6g} '+ue+'.')],(f'약{float(value):.6g}{uk}. '+('12세 부근에서 매년 이만큼 길이가 증가한다.'if n==75 else'100m² 부근에서 면적1m² 증가당 수종 수의 기대 변화량이다.'),f'About{float(value):.6g} {ue}. '+('This is the annual length increase near age12.'if n==75 else'The predicted species-count change per additional m² near100m².')),('거듭제곱 계수와 지수를 직접 곱하고 접근점 근처 차분비와 부호를 대조했다.','Checked the coefficient-times-exponent calculation and the sign against nearby difference quotients.'))
add(77,('일정 온도에서 기체는PV=상수이다.25°C에서0.106m³ 기체의 압력이50kPa이다.(a)V(P)를 쓰고(b)P=50의 dV/dP,뜻과 단위를 구하라.','At fixed temperature a gas satisfies PV=constant. At25°C its volume is0.106m³ and pressure50kPa.(a)Find V(P).(b)Find dV/dP at50 and interpret its units.'),[same(r'k=50(0.106)=5.3,\quad V(P)=5.3/P'),same(r'V\prime(P)=-5.3/P^2,\quad V\prime(50)=-0.00212'),('50kPa 부근에서 압력이1kPa 증가하면 부피는 약0.00212m³ 감소한다.','Near50kPa a1kPa pressure increase reduces volume by about0.00212m³.')],d(r'V(P)=\frac{5.3}P,\quad V\prime(50)=-0.00212\ {\rm m^3/kPa}'),('PV=5.3에 원래 값을 대입하고 압력이 증가할 때 부피가 감소하는 음의 부호를 확인했다.','Substituted the original values into PV=5.3 and checked that increasing pressure decreases volume.'),list('ab'))
# Ordinary least squares is calculated from the source table, not a guessed parabola.
ps=list(map(s.Integer,[26,28,31,35,38,42,45]));ls=list(map(s.Integer,[50,66,78,81,74,70,59]));mat=s.Matrix([[z*z,z,1]for z in ps]);coef=(mat.T*mat).inv()*mat.T*s.Matrix(ls);fit=coef[0]*x*x+coef[1]*x+coef[2];de=s.diff(fit,x)
add(78,('타이어 수명 L(천mile),압력 P(lb/in²) 자료는 (26,50),(28,66),(31,78),(35,81),(38,74),(42,70),(45,59)이다.(a)이차 최소제곱 모형을 구하고(b)P=30,40의 dL/dP와 단위·부호를 해석하라.','Tire-life L(thousand miles) versus pressure P(lb/in²) data are(26,50),(28,66),(31,78),(35,81),(38,74),(42,70),(45,59).(a)Fit a least-squares quadratic.(b)Estimate dL/dP at30 and40; interpret units and signs.'),[('행렬 X의 각 행을(P²,P,1)로 두어 정규방정식 XᵀXβ=XᵀL을 푼다.','Use rows(P²,P,1) in the design matrix X and solve XᵀXβ=XᵀL.'),same(r'L(P)\approx'+tex(s.N(fit,7)).replace('x','P')),same(r'L\prime(P)\approx'+tex(s.N(de,7)).replace('x','P')),('30에서는 양수이므로 이 모형에서 압력 증가에 수명이 증가하고40에서는 음수라 감소한다. 표와 단순 회귀의 국소 해석이다.','At30 the positive derivative predicts increasing life with pressure; at40 the negative derivative predicts decreasing life. These are local interpretations of the supplied table and simple regression.')],(f'L′(30)≈{float(de.subs(x,30)):.4f}, L′(40)≈{float(de.subs(x,40)):.4f} 천mile/(lb/in²).',f'L′(30)≈{float(de.subs(x,30)):.4f}, L′(40)≈{float(de.subs(x,40)):.4f} thousand miles/(lb/in²).'),('잔차에 대한 Xᵀ(L−Xβ)=0을 정확한 유리수로 확인하여 최소제곱 해임을 검산했다.','Verified Xᵀ(L−Xβ)=0 in exact rational arithmetic, establishing the least-squares fit.'),list('ab'))
D.fig(78,[panel('Least-squares quadratic and source data',(25,46,40,90),[samples(s.lambdify(x,fit,'math'),25,46)],[(float(a),float(b))for a,b in zip(ps,ls)],xlabel='pressure (lb/in^2)',ylabel='thousand miles')])
add(79,('f(5)=1,f′(5)=6,g(5)=−3,g′(5)=2일 때(a)(fg)′(5),(b)(f/g)′(5),(c)(g/f)′(5)를 구하라.','Given f(5)=1,f′(5)=6,g(5)=−3,g′(5)=2,find(a)(fg)′(5),(b)(f/g)′(5),(c)(g/f)′(5).'),[same(r'(fg)\prime(5)=6(-3)+1(2)=-16'),same(r'(f/g)\prime(5)=\frac{6(-3)-1(2)}{(-3)^2}=-20/9'),same(r'(g/f)\prime(5)=\frac{2(1)-(-3)(6)}{1^2}=20')],d(r'\text{(a) }-16;\quad\text{(b) }-20/9;\quad\text{(c) }20'),('몫 두 식의 분자 부호와 분모가 서로 바뀌는 것을 별도로 확인했다.','Separately checked the numerator sign reversal and changed denominators in the two quotient derivatives.'),list('abc'))
add(80,('f(4)=2,g(4)=5,f′(4)=6,g′(4)=−3일 때 h′(4)를 구하라:(a)h=3f+8g,(b)h=fg,(c)h=f/g,(d)h=g/(f+g).','Given f(4)=2,g(4)=5,f′(4)=6,g′(4)=−3,find h′(4) for(a)h=3f+8g,(b)h=fg,(c)h=f/g,(d)h=g/(f+g).'),[same(r'\text{(a) }3(6)+8(-3)=-6'),same(r'\text{(b) }6(5)+2(-3)=24'),same(r'\text{(c) }\frac{6(5)-2(-3)}{25}=36/25'),same(r'\text{(d) }\frac{(-3)(2+5)-5(6-3)}{(2+5)^2}=-36/49')],d(r'-6,\quad24,\quad36/25,\quad-36/49'),('(d)를1−f/(f+g)로 바꾸어 미분해도 같은−36/49이다.','Rewriting(d)as1−f/(f+g) gives the same−36/49.'),list('abcd'))
add(81,('f(x)=√x·g(x),g(4)=8,g′(4)=7일 때 f′(4)를 구하라.','For f(x)=√x·g(x),g(4)=8,and g′(4)=7,find f′(4).'),[same(r'f\prime(x)=\frac{g(x)}{2\sqrt x}+\sqrt x\,g\prime(x)'),same(r'f\prime(4)=8/4+2(7)=16')],d(r'f\prime(4)=16'),('곱 법칙의 두 기여량은 각각2와14이며 합은16이다.','The two product-rule contributions are2 and14, summing to16.'))
add(82,('h(2)=4,h′(2)=−3일 때 (h(x)/x)의 x=2 미분계수를 구하라.','Given h(2)=4,h′(2)=−3,find the derivative of h(x)/x at x=2.'),[same(r'\left(\frac{h(x)}x\right)\prime=\frac{xh\prime(x)-h(x)}{x^2}'),same(r'\frac{2(-3)-4}{2^2}=-5/2')],d(r'-5/2'),('h(x)x⁻¹의 곱 법칙으로−3/2−1=−5/2를 얻는다.','The product rule on h(x)x⁻¹ gives−3/2−1=−5/2.'))
add(83,('원본 격자에서 파란 f는 필요한 구간에 직선으로 f(1)=2,f(4)=3,기울기1/3이다. 빨간 g는(−2,0),(2,4),(3,1),(7,5)를 잇는 직선 조각이다. u=fg,v=f/g일 때(a)u′(1),(b)v′(4)를 구하라.','On the source grid, blue f is linear over the required interval, with f(1)=2,f(4)=3 and slope1/3. Red g joins(−2,0),(2,4),(3,1),(7,5) by segments. For u=fg,v=f/g,find(a)u′(1),(b)v′(4).'),[('g(1)=3,g′(1)=1,g(4)=2,g′(4)=1을 각 직선에서 읽는다.','The segments give g(1)=3,g′(1)=1,g(4)=2,g′(4)=1.'),same(r'u\prime(1)=\tfrac13(3)+2(1)=3'),same(r'v\prime(4)=\frac{(1/3)(2)-3(1)}{2^2}=-7/12')],d(r'u\prime(1)=3,\quad v\prime(4)=-7/12'),('파란 선의(1,2),(4,3) 차분비는1/3이며 빨간 선은 해당 두 구간에서 기울기1이다.','The blue secant through(1,2),(4,3) has slope1/3; the relevant red segments both have slope1.'),list('ab'))
D.fig(83,[panel('Blue: f; red: g (source-grid reconstruction)',(-2,7,-1,5),[[(-2,3),(-1,4/3),(7,4)],[(-2,0),(2,4),(3,1),(7,5)]],xticks=list(range(-2,8)),yticks=list(range(-1,6)))])
add(84,('원본 격자에서 F는 x=2에 높이3의 수평 최소점, x≥3에서는(3,4),(7,5)를 지나는 직선이다. G는(0,1),(4,3),(8,1/3)을 잇는 직선 조각이다. P=FG,Q=F/G일 때(a)P′(2),(b)Q′(7)를 구하라.','On the source grid,F has a horizontal minimum at(2,3) and for x≥3 is the line through(3,4),(7,5). G joins(0,1),(4,3),(8,1/3). For P=FG,Q=F/G,find(a)P′(2),(b)Q′(7).'),[('F(2)=3,F′(2)=0,G(2)=2,G′(2)=1/2이다.','We read F(2)=3,F′(2)=0,G(2)=2,G′(2)=1/2.'),same(r'P\prime(2)=0(2)+3(1/2)=3/2'),('F(7)=5,F′(7)=1/4,G(7)=1,G′(7)=−2/3이다.','At7 the values are F=5,F′=1/4,G=1,G′=−2/3.'),same(r'Q\prime(7)=\frac{(1/4)(1)-5(-2/3)}1=43/12')],d(r'P\prime(2)=3/2,\quad Q\prime(7)=43/12'),('G의 하강 기울기는−2/3이며−1로 오독하지 않도록 세 격자 수평 이동과 두 격자 수직 이동을 대조했다.','Checked the descending slope of G as−2/3 using a three-grid horizontal run and two-grid vertical drop, rather than misreading it as−1.'),list('ab'))
D.fig(84,[panel('Red: F; blue: G (source reconstruction)',(0,8,0,6),[{'points':samples(lambda z:(z-2)**2+3,0,3)+[(8,5.25)],'color':'#dc2626'},{'points':[(0,1),(4,3),(8,1/3)],'color':'#1d4ed8'}],xticks=list(range(9)),yticks=list(range(7)))],caption=('필요한 격자값과 직선 기울기를 보존했다.F의 곡선 구간은 같은 최소점을 갖는 자체 예시이다.','Preserves the required grid values and line slopes. The curved portion of F is an original example with the same minimum.'))
for n,st,eqs in[(85,('미분 가능한 g에 대해(a)y=xg(x),(b)y=x/g(x),(c)y=g(x)/x의 도함수를 구하라.','For differentiable g,find derivatives of(a)y=xg(x),(b)y=x/g(x),(c)y=g(x)/x.'),[r'y\prime=g+xg\prime',r'y\prime=\frac{g-xg\prime}{g^2}',r'y\prime=\frac{xg\prime-g}{x^2}']), (86,('미분 가능한 f에 대해(a)y=x²f(x),(b)y=f(x)/x²,(c)y=x²/f(x),(d)y=(1+xf(x))/√x의 도함수를 구하라.','For differentiable f,find derivatives of(a)y=x²f(x),(b)y=f(x)/x²,(c)y=x²/f(x),(d)y=(1+xf(x))/√x.'),[r'y\prime=2xf+x^2f\prime',r'y\prime=\frac{xf\prime-2f}{x^3}',r'y\prime=\frac{2xf-x^2f\prime}{f^2}',r'y\prime=-\frac1{2x^{3/2}}+\frac{f}{2\sqrt x}+\sqrt x f\prime'])]:
 add(n,st,[('곱에서는 한 번에 한 인수씩 미분하여 더하고 몫에서는(분모×분자미분−분자×분모미분)/분모²를 쓴다.','For products differentiate one factor at a time and add; for quotients use(denominator×numerator derivative−numerator×denominator derivative)/denominator².')]+[same(r'\text{('+chr(97+i)+')} '+q)for i,q in enumerate(eqs)],'; '.join(d(q)for q in eqs),('분모가0인 점을 제외한다.'+('(d)는 x⁻¹/²+x¹/²f로 재정리해 같은 식을 얻으며 x>0이다.'if n==86 else''),'Exclude zeros of denominators.'+('For(d),rewriting as x⁻¹/²+x¹/²f gives the same result and requires x>0.'if n==86 else'')),list('abc'if n==85 else'abcd'))
for n,f in[(87,x**3+3*x*x-9*x+10),(88,x**3+3*x*x+x+3)]:
 de=s.diff(f,x);roots=s.solve(de,x);points=[(z,s.simplify(f.subs(x,z)))for z in roots]
 add(n,('곡선 '+m('y='+tex(f))+'에서 수평 접선의 '+('접점을 구하라.'if n==87 else'x좌표를 구하라.'),'For '+m('y='+tex(f))+', find '+('the points with horizontal tangents.'if n==87 else'the arguments of horizontal tangents.')),[same(r'y\prime='+tex(de)+'=0'),same(r'x\in'+tex(s.FiniteSet(*roots)))],'; '.join(m('('+tex(z)+','+tex(w)+')')for z,w in points)if n==87 else d('x='+r',\ '.join(tex(z)for z in roots)),('각 후보를 도함수에 대입하면0이며,원곡선에 대입해 높이를 검산했다.','Every candidate makes the derivative zero; substituting into the original curve checks the ordinate.'))
add(89,('곡선 y=6x³+5x−3에 기울기4의 접선이 없음을 보여라.','Show that y=6x³+5x−3 has no tangent of slope4.'),[same(r'y\prime=18x^2+5\ge5>4')],('모든 실수에서 접선 기울기가 최소5이므로 기울기4는 불가능하다.','Every tangent slope is at least5,so slope4 is impossible.'),('18x²+5=4라 두면 x²=−1/18로 실수 해가 없다.','Setting18x²+5=4 gives x²=−1/18,with no real solution.'))
for n,f,slope,label in[(90,x**4+1,32,'32x−y=15'),(91,x**3-3*x*x+3*x-3,3,'3x−y=15'),(92,(x-1)/(x+1),s.Rational(1,2),'x−2y=2')]:
 de=s.diff(f,x);roots=s.solve(s.Eq(de,slope),x);lines=[s.expand(f.subs(x,z)+slope*(x-z))for z in roots]
 add(n,('곡선 '+m('y='+tex(f))+'에 접하고 직선 '+label+'과 평행한 모든 직선의 방정식을 구하라.','Find every line tangent to '+m('y='+tex(f))+' and parallel to '+label+'.'),[('평행 조건으로 접선 기울기를 '+m(tex(slope))+'로 둔다.','Parallelism requires tangent slope '+m(tex(slope))+'.'),same(tex(de)+'='+tex(slope)+r'\quad\Longrightarrow\quad x='+r',\ '.join(tex(z)for z in roots)),('각 접점에서 y−f(a)=m(x−a)를 적용한다.','At each contact point use y−f(a)=m(x−a).')],'; '.join(d('y='+tex(line))for line in lines),('각 직선의 기울기와 접점 통과를 확인했고 미분 방정식의 모든 실수 해를 포함했다.','Checked every line’s slope and contact point and included all real solutions of the derivative equation.'))
add(93,('곡선 y=√x의 법선 중 직선2x+y=1과 평행한 법선을 구하라.','Find the normal to y=√x parallel to2x+y=1.'),[same(r'm_N=-2,\quad m_T=1/2,\quad\frac1{2\sqrt a}=1/2\Rightarrow a=1'),same(r'y-1=-2(x-1)')],d(r'y=-2x+3'),('접점(1,1)을 지나고 법선과 접선 기울기의 곱(−2)(1/2)=−1이다.','The line passes through(1,1) and its slope times the tangent slope is(−2)(1/2)=−1.'))
add(94,('y=x²−1의(−1,0)에서 법선을 그려,포물선과 두 번째로 만나는 점을 구하라.','Draw the normal to y=x²−1 at(−1,0) and find its second intersection with the parabola.'),[same(r'm_T=-2,\quad m_N=1/2,\quad y=(x+1)/2'),same(r'x^2-1=(x+1)/2\Rightarrow(2x-3)(x+1)=0')],d(r'(3/2,5/4)'),('해x=−1은 원래 접점이므로 다른 해3/2를 선택한다.두 식 모두 높이5/4를 준다.','The root−1 is the original contact; selecting3/2 gives height5/4 in both equations.'))
plots(94,[x*x-1,(x+1)/2],(-2.2,2.2,-1.5,4),title='Blue: parabola; red: normal')
add(95,('점(0,−4)을 지나 y=x²에 접하는 두 직선을 도해로 보여주고 각각의 접점을 구하라.','Illustrate the two tangents to y=x² through(0,−4) and find their contact points.'),[same(r'y=2ax-a^2'),same(r'-4=-a^2\Rightarrow a=\pm2')],d(r'\text{points }(-2,4),(2,4);\quad y=-4x-4,\ y=4x-4'),('각 직선은(0,−4)을 지나고 포물선과의 교점 방정식은 각각(x+2)²=0,(x−2)²=0의 중근이다.','Both lines pass through(0,−4); their intersection equations with the parabola have double roots(x+2)²=0 and(x−2)²=0.'))
plots(95,[x*x,-4*x-4,4*x-4],(-3,3,-5,10),title='Blue: parabola; red/green: tangents')
add(96,('포물선 y=x²+x에 대해(a)(2,−3)을 지나는 두 접선식,(b)(2,7)을 지나는 접선이 없다는 증명과 도해를 제시하라.','For y=x²+x,(a)find both tangents through(2,−3);(b)prove that none pass through(2,7) and illustrate why.'),[same(r'y=(2a+1)x-a^2'),same(r'\text{(a) }-3=2(2a+1)-a^2\Rightarrow(a-5)(a+1)=0'),same(r'\text{(b) }7=2(2a+1)-a^2\Rightarrow(a-2)^2=-1')],d(r'\text{(a) }y=11x-25,\ y=-x-1;\quad\text{(b) no real tangent}'),('볼록 포물선의 접선은 곡선 아래에 있다.x=2에서 곡선 높이6보다 높은7을 지날 수 없다.','A convex parabola lies above every tangent; at x=2 a tangent cannot reach7 above the curve’s height6.'),list('ab'))
D.fig(96,[panel('Tangents through(2,-3); point(2,7)above curve',(-2,5,-5,32),[samples(lambda z:z*z+z,-2,5),[(-2,-47),(5,30)],[(-2,1),(5,-6)]],[(2,-3),(2,7)])])
add(97,('직선2x+y=b가 x=2에서 포물선y=ax²에 접하도록 a,b를 구하라.','Find a,b so2x+y=b is tangent to y=ax² at x=2.'),[same(r'4a=-2\Rightarrow a=-1/2'),same(r'y(2)=4a=-2,\quad b=2(2)+(-2)=2')],d(r'a=-1/2,\quad b=2'),('y=−x²/2와 y=2−2x의 차이는−(x−2)²/2이므로 x=2에서 중근 접촉한다.','The difference between y=−x²/2 and y=2−2x is−(x−2)²/2,confirming double contact at2.'))
add(98,('몇 번 미분해 패턴을 찾아 n계 도함수를 구하라:(a)f(x)=xⁿ,(b)f(x)=1/x.','Observe the pattern of successive derivatives and find the nth derivative of(a)f(x)=xⁿ,(b)f(x)=1/x.'),[same(r'\text{(a) }nx^{n-1},\ n(n-1)x^{n-2},\ldots,\ n!'),same(r'\text{(b) }-x^{-2},\ 2x^{-3},\ -6x^{-4},\ldots,\ (-1)^n n!x^{-n-1}'),('각 단계에서 지수가1씩 줄고 새 지수를 곱하므로 귀납적으로 패턴이 유지된다.','Each step lowers the exponent by one and multiplies by the previous exponent,proving the pattern inductively.')],d(r'\text{(a) }f^{(n)}=n!;\quad\text{(b) }f^{(n)}=\frac{(-1)^n n!}{x^{n+1}}\ (x\ne0)'),('n=1,2,3을 직접 계산한 값과 일반식이 모두 일치한다.','The general formulas agree with direct calculations for n=1,2,3.'),list('ab'))
for n,st,f,steps in[(99,('P(2)=5,P′(2)=3,P″(2)=2인 이차다항식 P를 구하라.','Find the quadratic P satisfying P(2)=5,P′(2)=3,P″(2)=2.'),x*x-x+3,[r'P=A(x-2)^2+B(x-2)+C',r'2A=2,\ B=3,\ C=5']), (100,('y″+y′−2y=x²를 만족하는 y=Ax²+Bx+C의 A,B,C를 구하라.','Find A,B,C such that y=Ax²+Bx+C solves y″+y′−2y=x².'),-x*x/2-x/2-s.Rational(3,4),[r'2A+(2Ax+B)-2(Ax^2+Bx+C)=x^2',r'-2A=1,\ 2A-2B=0,\ 2A+B-2C=0',r'A=-1/2,\ B=-1/2,\ C=-3/4']), (101,('삼차함수 y=ax³+bx²+cx+d가(−2,6),(2,0)에서 수평 접선을 갖도록 구하라.','Find a cubic y=ax³+bx²+cx+d with horizontal tangents at(−2,6),(2,0).'),s.Rational(3,16)*x**3-s.Rational(9,4)*x+3,[r'12a-4b+c=0,\ 12a+4b+c=0\Rightarrow b=0,\ c=-12a',r'-8a-2c+d=6,\ 8a+2c+d=0\Rightarrow a=3/16,\ d=3']), (102,('포물선 y=ax²+bx+c는 x=1에서 기울기4,x=−1에서 기울기−8이고(2,15)를 지난다.식을 구하라.','Find y=ax²+bx+c with slope4 at1,slope−8 at−1,and passing through(2,15).'),3*x*x-2*x+7,[r'2a+b=4,\ -2a+b=-8\Rightarrow a=3,\ b=-2',r'4a+2b+c=15\Rightarrow c=7'])]:
 add(n,st,[same(q)for q in steps],d(('P(x)='if n==99 else'y=')+tex(f)),('구한 다항식과1·2계 도함수를 원래 값·기울기·방정식 조건에 모두 대입해 확인했다.','Substituted the polynomial and its first two derivatives into all original value,slope,or equation conditions.'))
value103=107350*2250+1960*60220
add(103,('2015년 Boulder의 인구는107350명,증가율1960명/년이고1인당 연간소득은60220달러,증가율2250달러/(명·년)이다.총 개인소득의 증가율을 곱 법칙으로 추정하고 두 항의 뜻을 설명하라.','In2015 Boulder had107350 residents,increasing by1960/year; annual per-capita income was$60220,increasing by$2250 per resident per year. Estimate the total-income growth rate using the product rule and interpret both terms.'),[same(r'I=NP,\quad I\prime=N\prime P+NP\prime'),same(r'I\prime=1960(60220)+107350(2250)='+str(value103)),('첫 항은 기존1인 소득 수준에서 인구 증가의 기여,둘째 항은 기존 인구에서1인 소득 상승의 기여이다.','The first term is the contribution from population growth at the existing per-capita income; the second is income growth across the existing population.')],(f'약{value103:,}달러/년.','Approximately$'+f'{value103:,}'+'/year.'),('각 기여액118031200과241537500의 합은359568700이다.단위는 총 연간소득 수준의 매년 변화이다.','The contributions118031200 and241537500 sum to359568700.The rate measures annual change in the total annual-income level.'))
add(104,('직물 가격 p(달러/yard)에 따른 판매량은q=f(p)yard이고 매출R(p)=pf(p)이다.(a)f(20)=10000,f′(20)=−350의 뜻,(b)R′(20)과 뜻을 구하라.','Fabric quantity is q=f(p)yards at price p dollars/yard,and revenue R(p)=pf(p).(a)Interpret f(20)=10000,f′(20)=−350.(b)Find and interpret R′(20).'),[('20달러/yard에서10000yard가 팔리며,그 부근에서 가격1달러/yard 상승당 판매량이 약350yard 감소한다.','At$20/yard,10000yards sell; near that price a$1/yard increase reduces sales by about350yards.'),same(r'R\prime=f+pf\prime,\quad R\prime(20)=10000+20(-350)=3000')],('R′(20)=3000:가격을1달러/yard 조금 올리면 매출은 약3000달러 증가한다.','R′(20)=3000:a small$1/yard price increase raises revenue by approximately$3000.'),('추가 단가의 기여10000에서 판매량 감소의 기여7000을 빼면3000이다.','The10000 contribution from the higher unit price minus7000 from reduced sales yields3000.'),list('ab'))
add(105,('효소 반응속도 모형 v=0.14[S]/(0.015+[S])에서 기질농도[S]에 대한 도함수와 의미를 구하라.','For the enzyme-rate model v=0.14[S]/(0.015+[S]),find the derivative with respect to substrate concentration[S] and interpret it.'),[same(r'\frac{dv}{d[S]}=\frac{0.14(0.015+[S])-0.14[S]}{(0.015+[S])^2}=\frac{0.0021}{(0.015+[S])^2}'),('농도가 증가하면 속도도 증가하지만 농도가 클수록 추가 농도 변화에 대한 민감도는 작아진다.','The rate increases with concentration,but the sensitivity to an additional concentration increase decreases at higher concentrations.')],d(r'\frac{dv}{d[S]}=\frac{0.0021}{(0.015+[S])^2}'),('물리적[S]≥0에서 도함수는양수이고 감소하며,[S]→∞에서0에 접근한다.','For physical[S]≥0 the derivative is positive,decreasing,and tends to zero as concentration tends to infinity.'))
add(106,('구피 생물량은B(t)=N(t)M(t)이다.4주 시점 N=820마리,N′=50마리/주,M=1.2g,M′=0.14g/주일 때 B′(4)를 구하라.','Guppy biomass is B(t)=N(t)M(t).At4weeks,N=820fish,N′=50fish/week,M=1.2g,and M′=0.14g/week.Find B′(4).'),[same(r'B\prime=N\prime M+NM\prime'),same(r'B\prime(4)=50(1.2)+820(0.14)=60+114.8=174.8')],('174.8g/주.','174.8g/week.'),('개체수 변화와 개체당 질량 변화의 두 기여를 모두 포함하고 각 항 단위가g/주임을 확인했다.','Included both population and individual-mass changes; each contribution has units g/week.'))
add(107,('(a)곱 법칙을 두 번 적용하여 세 인수의 곱 미분식을 증명하라.(b)f=g=h로 두어(f³)′=3f²f′를 보이고(c)y=(x⁴+3x³+17x+82)³를 미분하라.','(a)Prove the three-factor product rule by applying the two-factor rule twice.(b)Set f=g=h to obtain(f³)′=3f²f′.(c)Differentiate y=(x⁴+3x³+17x+82)³.'),[same(r'(fgh)\prime=(fg)\prime h+fgh\prime=f\prime gh+fg\prime h+fgh\prime'),same(r'(f^3)\prime=f\prime f^2+ff\prime f+f^2f\prime=3f^2f\prime'),same(r'y\prime=3(x^4+3x^3+17x+82)^2(4x^3+9x^2+17)')],d(r'y\prime=3(x^4+3x^3+17x+82)^2(4x^3+9x^2+17)'),('세 항 각각은 한 인수만 미분한 것이며 f=g=h로 치환하면 정확히 같은 항3개가 된다.','Each term differentiates exactly one factor; setting all factors equal produces three identical terms.'),list('abc'))
add(108,('(a)몫 법칙으로(1/g)′=−g′/g²를 증명하고(b)38번의 F(x)=1/(2x³−6x²+5)에 적용하라.','(a)Derive(1/g)′=−g′/g² from the quotient rule.(b)Apply it to F(x)=1/(2x³−6x²+5) from exercise38.'),[same(r'(1/g)\prime=\frac{g(0)-1(g\prime)}{g^2}=-\frac{g\prime}{g^2}'),same(r'F\prime(x)=-\frac{6x^2-12x}{(2x^3-6x^2+5)^2}')],d(r'F\prime(x)=\frac{12x-6x^2}{(2x^3-6x^2+5)^2}'),('g≠0인 점에서만 성립하며38번 직접 몫 계산과 같다.','Valid only where g≠0,and agrees with the direct quotient calculation in38.'),list('ab'))
add(109,('F=f/g의 도함수가 존재하고g≠0이라고 가정하여 f=Fg를 곱 법칙으로 미분해 몫 법칙을 유도하라.','Assuming F=f/g is differentiable and g≠0,derive the quotient rule by differentiating f=Fg with the product rule.'),[same(r'f\prime=F\prime g+Fg\prime'),same(r'F\prime=\frac{f\prime-Fg\prime}g=\frac{gf\prime-fg\prime}{g^2}')],d(r'(f/g)\prime=\frac{gf\prime-fg\prime}{g^2}'),('이 계산은 가정한 미분값의 식을 도출한다.F의 미분 가능성 자체를 증명한 것은 아니며 문제의 사전 가정을 유지했다.','This derives the formula for the assumed derivative; it does not itself prove differentiability of F,and retains the problem’s explicit assumption.'))
add(110,('모든 차수로 미분 가능한 f,g의 곱F=fg에 대해(a)F″=f″g+2f′g′+fg″를 증명하고(b)F‴,F⁽⁴⁾를 구한 뒤(c)일반 n계식을 추측하라.','For F=fg with derivatives of all orders,(a)prove F″=f″g+2f′g′+fg″,(b)find F‴ and F⁽⁴⁾,and(c)conjecture the nth-order formula.'),[same(r'F\prime\prime=(f\prime g+fg\prime)\prime=f\prime\prime g+2f\prime g\prime+fg\prime\prime'),same(r'F^{(3)}=f^{(3)}g+3f^{(2)}g\prime+3f\prime g^{(2)}+fg^{(3)}'),same(r'F^{(4)}=f^{(4)}g+4f^{(3)}g\prime+6f^{(2)}g^{(2)}+4f\prime g^{(3)}+fg^{(4)}'),('한 번 더 미분할 때 이웃 항의 계수가 더해지므로 파스칼 삼각형의 이항계수가 된다.','Each differentiation adds neighboring coefficients,producing the binomial coefficients of Pascal’s triangle.')],d(r'F^{(n)}=\sum_{k=0}^{n}\binom nk f^{(k)}g^{(n-k)}'),('n=2,3,4의 계수1,2,1;1,3,3,1;1,4,6,4,1을 일반식에서 재확인했다.','The general formula reproduces coefficients1,2,1;1,3,3,1;and1,4,6,4,1 at orders2,3,4.'),list('abc'))
add(111,('f(x)=x²+1(x<1),x+1(x≥1)이1에서 미분 가능한지 판단하고 f,f′를 그려라.','For f(x)=x²+1 when x<1 and x+1 when x≥1,decide differentiability at1 and plot f,f′.'),[('양쪽 함수값은2로 연결되어 연속이다. 왼쪽 미분값은2,오른쪽은1이므로 미분 가능하지 않다.','Both branches meet at2,so f is continuous. The left derivative is2 and the right derivative1,so f is not differentiable.')],d(r'f\prime(x)=\begin{cases}2x&x<1\\1&x>1\end{cases},\quad f\prime(1)\text{ undefined}'),('1의 좌우 차분몫은 각각2+h→2와1로 서로 다르다.','At1 the one-sided quotients are2+h→2 and1,respectively.'))
D.fig(111,[panel('Continuous function with a corner at1',(-2,3,-1,6),[samples(lambda z:z*z+1,-2,1),[(1,2),(3,4)]],[(1,2)]),panel('Derivative; x=1 excluded',(-2,3,-5,4),[[(-2,-4),(1,2)],[(1,1),(3,1)]],[(1,2,'open'),(1,1,'open')])])
add(112,('g(x)=2x(x≤0),2x−x²(0<x<2),2−x(x≥2)에서 미분 가능한 모든 점과 g′식을 구하고 g,g′를 그려라.','For g(x)=2x for x≤0,2x−x² for0<x<2,and2−x for x≥2,find all differentiability points and g′,then graph both.'),[('0에서는 양쪽 함수값0과 기울기2가 일치한다.2에서는 양쪽 값0은 같지만 기울기−2,−1이 다르다.','At zero both values are0 and both slopes2. At2 the values agree at0,but slopes−2 and−1 differ.')],d(r'g\prime(x)=\begin{cases}2&x\le0\\2-2x&0<x<2\\-1&x>2\end{cases},\quad D_{g\prime}=\mathbb R\setminus\{2\}'),('0에서 오른쪽 차분몫2−h→2이고2에서 왼쪽 차분몫−2−h→−2이므로 접합점 판단을 정의로 검산했다.','At0 the right quotient2−h tends to2; at2 the left quotient−2−h tends to−2,checking the junctions from the definition.'))
D.fig(112,[panel('Function',(-2,4,-4,2),[[(-2,-4),(0,0)],samples(lambda z:2*z-z*z,0,2),[(2,0),(4,-2)]]),panel('Derivative; only2 excluded',(-2,4,-3,3),[[(-2,2),(0,2)],[(0,2),(2,-2)],[(2,-1),(4,-1)]],[(0,2),(2,-2,'open'),(2,-1,'open')])])
add(113,('(a)f(x)=|x²−9|의 미분 가능점과 도함수를 구하고(b)f,f′를 그려라.','(a)Find where f(x)=|x²−9| is differentiable and give f′.(b)Graph both.'),[('x²−9는 |x|>3에서 양수,|x|<3에서 음수이므로 각각 x²−9,9−x²로 쓴다.','The inside is positive for|x|>3 and negative for|x|<3,giving branches x²−9 and9−x².'),('±3에서는 좌우 기울기가 각각 부호 반대로 달라 모서리이다.','At±3 the one-sided slopes have opposite signs,forming corners.')],d(r'f\prime(x)=\begin{cases}2x&|x|>3\\-2x&|x|<3\end{cases};\quad D_{f\prime}=\mathbb R\setminus\{-3,3\}'),('−3의 기울기는−6,6이고3의 기울기는−6,6으로 모두 불일치한다.','At−3 the slopes are−6,6,and at3 they are−6,6,so neither pair agrees.'),list('ab'))
D.fig(113,[panel('Absolute-value parabola',(-5,5,-1,17),[samples(lambda z:abs(z*z-9),-5,5,500)]),panel('Derivative with holes at +/-3',(-5,5,-11,11),[[(-5,-10),(-3,-6)],[(-3,6),(3,-6)],[(3,6),(5,10)]],[(-3,-6,'open'),(-3,6,'open'),(3,-6,'open'),(3,6,'open')])])
add(114,('h(x)=|x−1|+|x+2|의 미분 가능점과 h′식을 구하고 h,h′를 그려라.','Find where h(x)=|x−1|+|x+2| is differentiable,give h′,and graph both.'),[same(r'h(x)=\begin{cases}-2x-1&x<-2\\3&-2\le x\le1\\2x+1&x>1\end{cases}'),('−2에서 기울기가−2에서0으로,1에서0에서2로 바뀐다.','At−2 the slope jumps from−2 to0;at1 it jumps from0 to2.')],d(r'h\prime(x)=\begin{cases}-2&x<-2\\0&-2<x<1\\2&x>1\end{cases};\quad D_{h\prime}=\mathbb R\setminus\{-2,1\}'),('절댓값 안의 두 영점−2,1로 나누어 각 부호를 직접 확인했다.','Split at the two inside zeros−2,1 and checked each sign directly.'))
D.fig(114,[panel('Absolute-value sum',(-4,3,0,8),[[(-4,7),(-2,3),(1,3),(3,7)]]),panel('Derivative with two jumps',(-4,3,-3,3),[[(-4,-2),(-2,-2)],[(-2,0),(1,0)],[(1,2),(3,2)]],[(-2,-2,'open'),(-2,0,'open'),(1,0,'open'),(1,2,'open')])])
add(115,('f(x)=x²(x≤2),mx+b(x>2)가 모든 실수에서 미분 가능하도록 m,b를 구하라.','Find m,b making f(x)=x² for x≤2 and mx+b for x>2 differentiable everywhere.'),[same(r'2m+b=4\quad\text{(continuity)}'),same(r'm=2(2)=4\quad\text{(matching slopes)}'),same(r'b=4-2(4)=-4')],d(r'm=4,\quad b=-4'),('오른쪽 직선4x−4는 포물선의(2,4) 접선이고 양쪽 차분몫은4로 수렴한다.','The right line4x−4 is the parabola’s tangent at(2,4);both one-sided quotients tend to4.'))
add(116,('쌍곡선xy=c의 점P에 그은 접선에 대해(a)두 좌표축 절편을 잇는 선분의 중점이P임을 보이고(b)접선과 두 축이 만드는 삼각형 넓이가 일정함을 증명하라.','For a tangent to xy=c at P,(a)show P is the midpoint of the segment between its axis intercepts and(b)prove that the triangle formed with the axes has constant area.'),[same(r'P=(a,c/a),\quad y-c/a=-\frac c{a^2}(x-a)'),same(r'y=-\frac c{a^2}x+\frac{2c}a,\quad X=(2a,0),\quad Y=(0,2c/a)'),same(r'\frac{X+Y}2=(a,c/a)=P,\quad A=\frac12|2a|\left|\frac{2c}a\right|=2|c|')],d(r'\text{midpoint }P;\quad A=2|c|\ (c\ne0)'),('그림의 제1사분면 경우c>0에서는2c이다.절댓값으로 다른 가지에서도 같은 넓이를 얻는다.','In the depicted first-quadrant case c>0 the area is2c;absolute values give the same area on other branches.'),list('ab'))
D.fig(116,[panel('Example c=2: intercepts(4,0),(0,2),P=(2,1)',(0,5,0,4),[samples(lambda z:2/z,.5,5),[(0,2),(4,0)],[(0,0),(0,2),(4,0),(0,0)]],[(2,1),(0,2),(4,0)],xticks=[0,2,4])])
add(117,('점(0,c)을 지나 y=x²에 수직인 법선의 개수를 c>1/2인 경우와 c≤1/2인 경우로 나누어 구하라.','Count the normals to y=x² through(0,c),separately for c>1/2 and c≤1/2.'),[('원점의 법선x=0은 모든 c에 대해 존재한다.0이 아닌 접점 a에서 법선은 y−a²=−(x−a)/(2a)이다.','The normal x=0 at the origin always qualifies. At a nonzero contact argument a,the normal is y−a²=−(x−a)/(2a).'),same(r'x=0\Rightarrow c=a^2+1/2\Rightarrow a^2=c-1/2'),('c>1/2이면 서로 다른 두 비영 접점이 추가된다.c=1/2에서는a=0으로 이미 세었던 수직선과 중복하며,c<1/2에서는 추가 실수 접점이 없다.','For c>1/2 two nonzero contacts add two normals. At c=1/2 the root a=0 duplicates the already counted vertical line;for c<1/2 no additional real contact exists.')],('c>1/2:3개; c≤1/2:1개.','c>1/2:3 normals; c≤1/2:1 normal.'),('a=0을−1/(2a) 식에 넣지 않고 먼저 수직 법선으로 분리해 누락·중복을 피했다.','Handled a=0 separately as a vertical normal,avoiding division by zero,omission,or double counting.'))
add(118,('포물선 y=x²와 y=x²−2x+2를 그리고 공통 접선이 있는지 판단하여 있으면 방정식을 구하라.','Sketch y=x² and y=x²−2x+2,and determine whether they have a common tangent;if so,find it.'),[same(r'y=2ax-a^2\quad\text{(first parabola)}'),same(r'm=2b-2=2a\Rightarrow b=a+1'),same(r'\text{second intercept}=2-b^2=-a^2\Rightarrow a=1/2,\ b=3/2')],d(r'y=x-1/4'),('교점 방정식은 각각(x−1/2)²=0,(x−3/2)²=0으로 서로 다른 두 포물선 모두와 중근 접촉한다.','The intersection equations are(x−1/2)²=0 and(x−3/2)²=0,giving double contact with both parabolas.'))
plots(118,[x*x,x*x-2*x+2,x-s.Rational(1,4)],(-1,3,-1,6),title='Blue/red: parabolas; green: common tangent')
add(119,('극한 '+m(r'\lim_{x\to1}(x^{1000}-1)/(x-1)')+'을 구하라.','Evaluate '+m(r'\lim_{x\to1}(x^{1000}-1)/(x-1)')+'.'),[('이 식은 f(x)=x¹⁰⁰⁰의 x=1 미분계수 정의이다.','This is the defining quotient for f(x)=x¹⁰⁰⁰ at x=1.'),same(r'f\prime(1)=1000(1)^{999}=1000')],d('1000'),('x≠1에서 차분몫은1+x+⋯+x⁹⁹⁹이며1에 대입하면1이1000개 더해져 같은 값이다.','For x≠1 the quotient is1+x+⋯+x⁹⁹⁹;at1 the sum of1000ones gives the same value.'))
normalize_prose_inequalities(D)
D.save(119)
