"""Polar double integrals, complete51 exercises, original worked solutions."""
from core_15 import *
from planar_15 import *
from plot_15 import solid
import mpmath as mp
x,y,r,t=s.symbols('x y r theta',real=True);a,b,R=s.symbols('a b R',positive=True)
D=Doc('15.3',[1105,1106,1107],lambda n:1105 if n<=18 else (1106 if n<=42 else 1107))
def add(n,st,steps,ans,parts=(),check=('극좌표 경계를 직교좌표에 대입하고 야코비안 r을 확인했다.','The polar boundary was substituted into Cartesian equations and the Jacobian r was checked.')):
 return D.add(n,('극좌표 이중적분','Double integrals in polar coordinates'),st,('원을 극좌표 경계로 바꾸고 '+m(r'dA=r\,dr\,d\theta')+'를 사용한다.','Express circular boundaries in polar form and use '+m(r'dA=r\,dr\,d\theta')+'.'),steps,ans,check,parts)
def calc(n,st,f,lims,setup,parts=()):
 v,steps=D.evaluated(f,lims);steps.insert(0,(setup[0]+' '+d('I='+integral(f,lims)),setup[1]+' '+d('I='+integral(f,lims))));add(n,st,steps,d('I='+tex(v)),parts);return v
figures={}
def fig(n,polys,title,labels=()):
 name=f's15-3-{n}.svg';planar(name,f'15.3 / {n} - {title}',polys,labels);figures[n]=(name,title)
# Coordinate selection: preserve every region from the diagrams.
setups={1:(r'x^2+y^2\le16,\ 0\le\theta\le3\pi/2',r'\int_0^{3\pi/2}\int_0^4f(r\cos\theta,r\sin\theta)r\,dr\,d\theta','반지름4인 원판에서 제4사분면을 뺀 영역','A radius4 disk with the fourth quadrant removed'),2:(r'-1\le x\le1,\ -x\le y\le1',r'\int_{-1}^1\int_{-x}^1f(x,y)\,dy\,dx','꼭짓점(-1,1),(1,1),(1,-1)의 삼각형','The triangle with vertices(-1,1),(1,1),(1,-1)'),3:(r'1\le r\le3,\ 0\le\theta\le\pi',r'\int_0^\pi\int_1^3f(r\cos\theta,r\sin\theta)r\,dr\,d\theta','반지름1과3 사이의 위쪽 반원고리','The upper half-annulus with radii1 and3'),4:(r'0\le r\le3,\ -\pi/4\le\theta\le3\pi/4',r'\int_{-\pi/4}^{3\pi/4}\int_0^3f(r\cos\theta,r\sin\theta)r\,dr\,d\theta','반지름3인 원판에서 직선 y=-x 위쪽 부분','The part of the radius3 disk above y=-x'),5:(r'-2\le x\le2,\ 0\le y\le1-|x|/2',r'\int_{-2}^0\int_0^{1+x/2}f\,dy\,dx+\int_0^2\int_0^{1-x/2}f\,dy\,dx','꼭짓점(-2,0),(0,1),(2,0)의 삼각형','The triangle with vertices(-2,0),(0,1),(2,0)'),6:(r'8\le r\le10,\ 0\le\theta\le2\pi',r'\int_0^{2\pi}\int_8^{10}f(r\cos\theta,r\sin\theta)r\,dr\,d\theta','반지름8과10 사이의 원고리','The annulus with radii8 and10')}
for n,(desc,expr,ko,en) in setups.items():
 polar=n not in(2,5)
 add(n,(ko+'에 대해 직교좌표와 극좌표 중 편리한 것을 골라 일반 함수 f의 적분을 세워라.',en+': choose convenient coordinates and set up the integral of an arbitrary f.'),[(('원형 경계는 극좌표에서 상수 반지름이 된다.' if polar else '직선 경계는 직교좌표에서 간단한 일차 부등식이 된다.'),('Circular boundaries give simple radial limits.' if polar else 'Linear boundaries give simple Cartesian inequalities.')),('영역은 '+m(desc)+'이다.','The region is '+m(desc)+'.')],d(expr))
fig(1,[polar_polygon(0,1.5*math.pi,lambda t:0,lambda t:4)],'r ≤ 4; 0 ≤ θ ≤ 3π/2')
fig(2,[[(-1,1),(1,1),(1,-1)]],'Triangle',[(-1,1,'(-1,1)'),(1,1,'(1,1)'),(1,-1,'(1,-1)')])
fig(3,[polar_polygon(0,math.pi,lambda t:1,lambda t:3)],'1 ≤ r ≤ 3; 0 ≤ θ ≤ π')
fig(4,[polar_polygon(-math.pi/4,3*math.pi/4,lambda t:0,lambda t:3)],'r ≤ 3; y ≥ -x')
fig(5,[[(-2,0),(0,1),(2,0)]],'Triangle',[(-2,0,'(-2,0)'),(0,1,'(0,1)'),(2,0,'(2,0)')])
fig(6,[polar_polygon(0,2*math.pi,lambda t:8,lambda t:10)],'8 ≤ r ≤ 10')
for n,lims,desc in [(7,[(r,1,2),(t,s.pi/4,3*s.pi/4)],r'\pi/4\le\theta\le3\pi/4,\ 1\le r\le2'),(8,[(r,0,2*s.sin(t)),(t,s.pi/2,s.pi)],r'\pi/2\le\theta\le\pi,\ 0\le r\le2\sin\theta')]:
 calc(n,('주어진 극좌표 영역 '+m(desc)+'을 그리고 넓이를 구하라.','Sketch the polar region '+m(desc)+' and find its area.'),r,lims,('넓이 적분에서 함수는1이고 면적요소는 r이다.','For area the function is1 and the area element contributes r.'))
fig(7,[polar_polygon(math.pi/4,3*math.pi/4,lambda t:1,lambda t:2)],'Annular sector')
fig(8,[polar_polygon(math.pi/2,math.pi,lambda t:0,lambda t:2*math.sin(t))],'Left half of x² + (y - 1)² ≤ 1')
spec={9:(x*x*y,r**4*s.cos(t)**2*s.sin(t),[(r,0,5),(t,0,s.pi)],r'x^2+y^2\le25,\ y\ge0'),10:(2*x-y,r*r*(2*s.cos(t)-s.sin(t)),[(r,0,2),(t,s.pi/4,s.pi/2)],r'x^2+y^2\le4,\ 0\le x\le y'),11:(s.sin(x*x+y*y),r*s.sin(r*r),[(r,1,3),(t,0,s.pi/2)],r'1\le x^2+y^2\le9,\ x,y\ge0'),12:(y*y/(x*x+y*y),r*s.sin(t)**2,[(r,a,b),(t,0,2*s.pi)],r'a^2\le x^2+y^2\le b^2,\ 0<a<b'),13:(s.exp(-x*x-y*y),r*s.exp(-r*r),[(r,0,2),(t,-s.pi/2,s.pi/2)],r'x^2+y^2\le4,\ x\ge0'),14:(s.cos(s.sqrt(x*x+y*y)),r*s.cos(r),[(r,0,2),(t,0,2*s.pi)],r'x^2+y^2\le4'),15:(s.atan(y/x),r*t,[(r,1,2),(t,0,s.pi/4)],r'1\le x^2+y^2\le4,\ 0\le y\le x'),16:(x,r*r*s.cos(t),[(r,2*s.cos(t),2),(t,0,s.pi/2)],r'x,y\ge0,\ x^2+y^2\le4,\ x^2+y^2\ge2x')}
for n,(f,ff,lims,desc) in spec.items():calc(n,('영역 '+m(desc)+'에서 '+m(tex(f))+'의 이중적분을 극좌표로 계산하라.','Use polar coordinates to integrate '+m(tex(f))+' over '+m(desc)+'.'),ff,lims,('좌표식 '+m(r'x=r\cos\theta,y=r\sin\theta')+'을 대입하고 면적요소 r을 곱한다.','Substitute '+m(r'x=r\cos\theta,y=r\sin\theta')+' and multiply by the area factor r.'))
# Areas with nontrivial overlap: explicit symmetry and radial choices.
calc(17,('두 심장형 '+m(r'r=1+\cos\theta,\ r=1-\cos\theta')+'의 공통 내부 넓이를 구하라.','Find the area common to '+m(r'r=1+\cos\theta')+' and '+m(r'r=1-\cos\theta')+'.'),4*r,[(r,0,1-s.cos(t)),(t,0,s.pi/2)],('공통 내부는 작은 반지름 '+m(r'1-|\cos\theta|')+'를 택한다. 네 사분면이 대칭이다.','The overlap uses the smaller radius '+m(r'1-|\cos\theta|')+'. The four quadrants are symmetric.'))
fig(17,[polar_polygon(0,2*math.pi,lambda t:0,lambda t:1-abs(math.cos(t)))],'Intersection of r = 1 ± cos θ')
calc(18,('나선 '+m(r'r=\sqrt\theta')+'의 첫 회전 '+m(r'0\le\theta\le2\pi')+' 안쪽 넓이를 구하라.','Find the area inside the first turn of '+m(r'r=\sqrt\theta,\ 0\le\theta\le2\pi')+'.'),r,[(r,0,s.sqrt(t)),(t,0,2*s.pi)],('각 방향에서 반지름은0부터 나선까지이다.','Each radial slice runs from the origin to the spiral.'))
fig(18,[polar_polygon(0,2*math.pi,lambda t:0,lambda t:math.sqrt(t))],'First turn: r = √θ')
add(19,('두 원판 '+m(r'r\le\sin\theta')+'와 '+m(r'r\le\cos\theta')+'의 합집합 넓이를 구하라(겹친 부분도 포함).','Find the area of the union of the disks bounded by '+m(r'r=\sin\theta')+' and '+m(r'r=\cos\theta')+', including their overlap.'),[('각 원의 반지름은1/2이므로 면적 합은 '+m(r'\pi/2')+'이다.','Each circle has radius1/2, so their area sum is '+m(r'\pi/2')+'.'),('중복 계산한 제1사분면 교집합은 '+d(r'A_\cap=\frac12\int_0^{\pi/4}\sin^2\theta\,d\theta+\frac12\int_{\pi/4}^{\pi/2}\cos^2\theta\,d\theta=\frac\pi8-\frac14')+'이다.','The overlap, counted twice, is '+d(r'A_\cap=\frac12\int_0^{\pi/4}\sin^2\theta\,d\theta+\frac12\int_{\pi/4}^{\pi/2}\cos^2\theta\,d\theta=\frac\pi8-\frac14')),('포함배제 원리로 교집합을 한 번 뺀다.','Subtract the overlap once by inclusion-exclusion.')],d(r'A=\frac{3\pi}{8}+\frac14'))
fig(19,[polar_polygon(0,math.pi,lambda t:0,lambda t:math.sin(t)),polar_polygon(-math.pi/2,math.pi/2,lambda t:0,lambda t:math.cos(t))],'Union of the two disks')
calc(20,('렘니스케이트 '+m(r'r^2=\cos2\theta')+' 안이면서 원 '+m(r'r=1/\sqrt2')+' 밖인 양쪽 영역의 총넓이를 구하라.','Find the total area inside '+m(r'r^2=\cos2\theta')+' and outside '+m(r'r=1/\sqrt2')+', including both ends.'),2*r,[(r,1/s.sqrt(2),s.sqrt(s.cos(2*t))),(t,-s.pi/6,s.pi/6)],('교점은 '+m(r'\cos2\theta=1/2')+'이다. 오른쪽 각도구간을 적분하고 좌우대칭으로2배 한다.','Intersections satisfy '+m(r'\cos2\theta=1/2')+'. Integrate the right angular interval and double by symmetry.'))
fig(20,[polar_polygon(-math.pi/6,math.pi/6,lambda t:1/math.sqrt(2),lambda t:math.sqrt(math.cos(2*t))),polar_polygon(5*math.pi/6,7*math.pi/6,lambda t:1/math.sqrt(2),lambda t:math.sqrt(max(0,math.cos(2*t))))],'Lemniscate outside r = 1/√2')
calc(21,('장미곡선 '+m(r'r=\sin3\theta')+'의 제1사분면 잎의 넓이를 구하라.','Find the area of the first-quadrant petal of '+m(r'r=\sin3\theta')+'.'),r,[(r,0,s.sin(3*t)),(t,0,s.pi/3)],('한 잎은 연속한 영점 '+m(r'\theta=0,\pi/3')+' 사이에서 생긴다.','One petal runs between consecutive zeros '+m(r'\theta=0,\pi/3')+'.'))
calc(22,('원판 '+m(r'(x-1)^2+y^2\le1')+' 안이면서 단위원 밖인 영역의 넓이를 구하라.','Find the area inside '+m(r'(x-1)^2+y^2\le1')+' and outside the unit circle.'),r,[(r,1,2*s.cos(t)),(t,-s.pi/3,s.pi/3)],('이동된 원은 '+m(r'r=2\cos\theta')+'이다. '+m(r'2\cos\theta\ge1')+'에서 각도 경계를 정한다.','The shifted circle is '+m(r'r=2\cos\theta')+'. The condition '+m(r'2\cos\theta\ge1')+' sets the angular range.'))
# Volumes and integrals with diagram-defined projections.
volumes={23:(1+x*y,r*(1+r*r*s.cos(t)*s.sin(t)),[(r,0,2),(t,0,s.pi/2)],r'x^2+y^2\le4,\ x,y\ge0'),24:(x*x+y*y,r**3,[(r,1,2),(t,0,2*s.pi)],r'1\le x^2+y^2\le4'),26:(x*y*y,r**4*s.cos(t)*s.sin(t)**2,[(r,2,3),(t,0,s.pi/2)],r'4\le x^2+y^2\le9,\ x,y\ge0'),27:(x,r*r*s.cos(t),[(r,0,s.sin(t)),(t,0,s.pi/2)],r'x^2+y^2\le y,\ x\ge0'),28:(s.Integer(1),r,[(r,0,1+s.cos(t)),(t,0,s.pi)],r'0\le r\le1+\cos\theta,\ 0\le\theta\le\pi'),29:(x*x+y*y,r**3,[(r,0,5),(t,0,2*s.pi)],r'x^2+y^2\le25'),30:(s.sqrt(x*x+y*y),r*r,[(r,1,2),(t,0,2*s.pi)],r'1\le x^2+y^2\le4'),31:(4-2*x-y,r*(4-2*r*s.cos(t)-r*s.sin(t)),[(r,0,1),(t,0,2*s.pi)],r'x^2+y^2\le1')}
for n,(f,ff,lims,desc) in volumes.items():calc(n,('곡면 '+m('z='+tex(f))+' 아래, 영역 '+m(desc)+' 위의 부피를 '+('(a)적분으로 나타내고 (b)계산하라.' if n<=28 else '구하라.'),'Find the volume beneath '+m('z='+tex(f))+' over '+m(desc)+('. (a) Set up the integral; (b) evaluate it.' if n<=28 else '.')),ff,lims,('높이에 극좌표 면적요소 r을 곱한다.','Multiply the height by the polar area factor r.'),('a','b') if n<=28 else ())
# Exercise25 kept pending independent source/answer-key adjudication.
add(25,('반지름3인 원판에서 제4사분면을 뺀 영역 D와 '+m('f(x,y)=y')+'에 대해 (a)극좌표 적분을 세우고 (b)계산하라. 그래프와 xy평면 사이의 기하학적 부피도 구분하라.','For '+m('f(x,y)=y')+' on the radius3 disk with the fourth quadrant removed, (a) set up and (b) evaluate the polar integral. Distinguish the geometric volume between the graph and the xy-plane.'),[('도해의 각도구간은 '+m(r'0\le\theta\le3\pi/2')+'이다. 따라서 '+d(r'I=\int_0^{3\pi/2}\int_0^3r^2\sin\theta\,dr\,d\theta=9')+'이다.','The diagram gives '+m(r'0\le\theta\le3\pi/2')+', so '+d(r'I=\int_0^{3\pi/2}\int_0^3r^2\sin\theta\,dr\,d\theta=9')),('제3사분면에서는 높이 y가 음수다. 실제 부피를 뜻하면 절댓값을 사용한다. '+d(r'V=\int_0^{3\pi/2}\int_0^3r^2|\sin\theta|\,dr\,d\theta=27'),'In the third quadrant y is negative. Geometric volume uses its absolute value: '+d(r'V=\int_0^{3\pi/2}\int_0^3r^2|\sin\theta|\,dr\,d\theta=27'))],('부호 있는 이중적분9; 그래프와 평면 사이 실제 부피27.','Signed double integral9; geometric volume between graph and plane27.'),('a','b'))
fig(25,[polar_polygon(0,1.5*math.pi,lambda t:0,lambda t:3)],'r ≤ 3; 0 ≤ θ ≤ 3π/2')
for n,st,ff,lims,setup in [
(32,('반지름4 구 안이며 반지름2인 z축 원기둥 밖의 부피를 구하라.','Find the volume inside the sphere of radius4 and outside the z-axis cylinder of radius2.'),2*r*s.sqrt(16-r*r),[(r,2,4),(t,0,2*s.pi)],('구의 위아래 높이차는 '+m(r'2\sqrt{16-r^2}')+'이다.','The vertical height is '+m(r'2\sqrt{16-r^2}')+'.')),
(33,('반지름 a인 구의 부피를 극좌표 이중적분으로 구하라.','Use a polar double integral to find the volume of a sphere of radius a.'),2*r*s.sqrt(a*a-r*r),[(r,0,a),(t,0,2*s.pi)],('위아래 반구 사이 높이를 적분한다.','Integrate the height between the two hemispheres.')),
(34,('제1팔분공간에서 '+m('z=1+2(x^2+y^2)')+'와 '+m('z=7')+' 사이의 부피를 구하라.','Find the first-octant volume between '+m('z=1+2(x^2+y^2)')+' and '+m('z=7')+'.'),r*(6-2*r*r),[(r,0,s.sqrt(3)),(t,0,s.pi/2)],('교선은 '+m(r'r^2=3')+'이다. 높이는 '+m(r'6-2r^2')+'이다.','The intersection has '+m(r'r^2=3')+'; the height is '+m(r'6-2r^2')+'.')),
(35,('단위구 안에서 원뿔 '+m(r'z=\sqrt{x^2+y^2}')+' 위의 부피를 구하라.','Find the volume inside the unit sphere above '+m(r'z=\sqrt{x^2+y^2}')+'.'),r*(s.sqrt(1-r*r)-r),[(r,0,1/s.sqrt(2)),(t,0,2*s.pi)],('교선은 '+m(r'\sqrt{1-r^2}=r')+'이므로 '+m(r'r=1/\sqrt2')+'이다.','The intersection satisfies '+m(r'\sqrt{1-r^2}=r')+', giving '+m(r'r=1/\sqrt2')+'.')),
(36,('포물면 '+m(r'z=6-x^2-y^2,\ z=2x^2+2y^2')+' 사이 부피를 구하라.','Find the volume between '+m(r'z=6-x^2-y^2')+' and '+m(r'z=2x^2+2y^2')+'.'),r*(6-3*r*r),[(r,0,s.sqrt(2)),(t,0,2*s.pi)],('교선은 '+m(r'r^2=2')+', 높이차는 '+m(r'6-3r^2')+'이다.','The intersection has '+m(r'r^2=2')+' and the height is '+m(r'6-3r^2')+'.')),
(37,('원기둥 '+m(r'x^2+y^2=4')+'과 타원체 '+m(r'4x^2+4y^2+z^2=64')+'의 공통 내부 부피를 구하라.','Find the common volume inside '+m(r'x^2+y^2=4')+' and '+m(r'4x^2+4y^2+z^2=64')+'.'),2*r*s.sqrt(64-4*r*r),[(r,0,2),(t,0,2*s.pi)],('원기둥에서 '+m(r'r\le2')+', 타원체에서 높이차는 '+m(r'2\sqrt{64-4r^2}')+'이다.','The cylinder gives '+m(r'r\le2')+'; the ellipsoid height is '+m(r'2\sqrt{64-4r^2}')+'.'))]:calc(n,st,ff,lims,setup)
add(38,('반지름 '+m('r_2')+'인 구에 중심축을 따라 반지름 '+m('r_1<r_2')+'인 원통 구멍을 뚫었다. (a)남은 부피를 구하고 (b)남은 고리의 높이 h만으로 표현하라.','A cylindrical hole of radius '+m('r_1<r_2')+' is drilled through the center of a sphere of radius '+m('r_2')+'. (a) Find the remaining volume; (b) express it using only the ring height h.'),[('(a) 남는 반지름 구간은 '+m(r'r_1\le r\le r_2')+'이다. '+d(r'V=4\pi\int_{r_1}^{r_2}r\sqrt{r_2^2-r^2}\,dr=\frac{4\pi}{3}(r_2^2-r_1^2)^{3/2}'),'(a) Remaining radii satisfy '+m(r'r_1\le r\le r_2')+'. '+d(r'V=4\pi\int_{r_1}^{r_2}r\sqrt{r_2^2-r^2}\,dr=\frac{4\pi}{3}(r_2^2-r_1^2)^{3/2}')),('(b) 구와 원기둥 교점의 z좌표로부터 '+m(r'h=2\sqrt{r_2^2-r_1^2}')+'이다. 대입하면 구의 원래 반지름이 사라진다.','(b) The intersection heights give '+m(r'h=2\sqrt{r_2^2-r_1^2}')+'. Substitution eliminates the original sphere radius.')],d(r'(a)\ V=\frac{4\pi}{3}(r_2^2-r_1^2)^{3/2},\quad(b)\ V=\frac{\pi h^3}{6}'),('a','b'))
cart={39:(s.exp(-x*x-y*y),[(y,0,s.sqrt(4-x*x)),(x,0,2)],r*s.exp(-r*r),[(r,0,2),(t,0,s.pi/2)]),40:(2*x+y,[(x,-s.sqrt(a*a-y*y),s.sqrt(a*a-y*y)),(y,0,a)],r*r*(2*s.cos(t)+s.sin(t)),[(r,0,a),(t,0,s.pi)]),41:(x*y*y,[(x,s.sqrt(3)*y,s.sqrt(1-y*y)),(y,0,s.Rational(1,2))],r**4*s.cos(t)*s.sin(t)**2,[(r,0,1),(t,0,s.pi/6)]),42:(s.sqrt(x*x+y*y),[(y,0,s.sqrt(2*x-x*x)),(x,0,2)],r*r,[(r,0,2*s.cos(t)),(t,0,s.pi/2)])}
for n,(f,ll,ff,lims) in cart.items():calc(n,('적분 '+d(integral(f,ll))+'을 극좌표로 바꾸어 계산하라.','Convert and evaluate '+d(integral(f,ll))+' using polar coordinates.'),ff,lims,('원·직선 경계를 바꾸고 면적요소 r을 포함한다.','Transform the circular and linear boundaries and include r in the area element.'))
mp.mp.dps=35
for n,ff,one,desc in [(43,s.exp((x*x+y*y)**2),2*s.pi*r*s.exp(r**4),r'x^2+y^2\le1'),(44,x*y*s.sqrt(1+x*x+y*y),r**3*s.sqrt(1+r*r)/2,r'x,y\ge0,\ x^2+y^2\le1')]:
 fn=s.lambdify(r,one,'mpmath');v=mp.quad(fn,[0,1]);D.checks.append({'method':'mpmath35dps radial quadrature','integrand':str(one),'value':str(v)})
 add(n,('영역 '+m(desc)+'에서 '+m(tex(ff))+'의 적분을 일변수로 줄이고 소수 넷째 자리까지 구하라.','Reduce the integral of '+m(tex(ff))+' over '+m(desc)+' to one variable and evaluate to four decimals.'),[('극좌표로 바꾸면 각도 적분은 '+(m(r'2\pi') if n==43 else m(r'\int_0^{\pi/2}\cos\theta\sin\theta\,d\theta=1/2'))+'이다.','In polar coordinates the angular integral is '+(m(r'2\pi') if n==43 else m(r'\int_0^{\pi/2}\cos\theta\sin\theta\,d\theta=1/2'))+'.'),('남은 반지름 적분을 수치적으로 계산한다. '+d('I='+integral(one,[(r,0,1)])+'\\approx'+str(v)),'Evaluate the remaining radial integral numerically. '+d('I='+integral(one,[(r,0,1)])+'\\approx'+str(v)))],d('I\\approx'+f'{float(v):.4f}'))
add(45,('지름40피트의 원형 수영장 깊이는 남쪽 끝2피트에서 북쪽 끝7피트까지 선형으로 변한다. 물의 부피를 구하라.','A circular pool of diameter40feet has depth varying linearly from2feet at the south edge to7feet at the north edge. Find its water volume.'),[('중심을 원점, 북쪽을 y양의 방향으로 두면 깊이는 '+m(r'd(y)=9/2+y/8')+'이다.','Place the origin at the center with north as positive y. Depth is '+m(r'd(y)=9/2+y/8')+'.'),('원판의 y모멘트는 대칭으로0이다. 따라서 평균깊이9/2에 원판넓이를 곱한다. '+d(r'V=\iint_{r\le20}(9/2+y/8)dA=(9/2)\pi20^2'),'The disk has zero y moment by symmetry. Multiply mean depth9/2 by its area: '+d(r'V=\iint_{r\le20}(9/2+y/8)dA=(9/2)\pi20^2'))],d(r'V=1800\pi\ \mathrm{ft^3}'))
add(46,('스프링클러에서 거리 r피트인 곳의 물 공급깊이는 '+m(r'e^{-r}')+'피트/시간이고 물은100피트까지 도달한다. (a) '+m('0<R\\le100')+'인 반지름 R원판에 시간당 공급되는 물의 부피, (b)평균 공급깊이를 구하라.','A sprinkler deposits water at depth rate '+m(r'e^{-r}')+'feet/hour at distance rfeet and reaches100feet. For '+m('0<R\\le100')+', find (a) volume rate within radius R and (b) mean depth rate.'),[('(a) 면적요소를 곱하고 부분적분한다. '+d(r'Q(R)=2\pi\int_0^Rre^{-r}dr=2\pi[1-(R+1)e^{-R}]'),'(a) Include the area factor and integrate by parts: '+d(r'Q(R)=2\pi\int_0^Rre^{-r}dr=2\pi[1-(R+1)e^{-R}]')),('(b) 평균은 총부피를 원판넓이로 나눈 값이다.','(b) Divide the volume rate by the disk area.')],d(r'(a)\ Q=2\pi[1-(R+1)e^{-R}]\ \mathrm{ft^3/hr},\quad(b)\ \bar d=\frac{2[1-(R+1)e^{-R}]}{R^2}\ \mathrm{ft/hr}'),('a','b'))
for n,f,lims,area_,desc in [(47,s.Integer(1),[(r,a,b),(t,0,2*s.pi)],s.pi*(b*b-a*a),r'f=1/\sqrt{x^2+y^2},\ a^2\le x^2+y^2\le b^2,\ 0<a<b'),(48,r*r,[(r,0,a),(t,0,2*s.pi)],s.pi*a*a,r'f=\sqrt{x^2+y^2},\ x^2+y^2\le a^2')]:
 v,steps=D.evaluated(f,lims);ans=s.simplify(v/area_);add(n,('함수의 영역평균을 구하라: '+m(desc)+'.','Find the area average: '+m(desc)+'.'),[('평균은 적분을 면적으로 나눈다. 극좌표 야코비안을 포함한다.','Divide the integral by area, including the polar Jacobian.')]+steps+[('영역넓이 '+m(tex(area_))+'로 나눈다.','Divide by the region area '+m(tex(area_))+'.')],d(r'f_{\mathrm{avg}}='+tex(ans)))
calc(49,('다음 세 적분을 하나의 극좌표 적분으로 합쳐 계산하라. '+d(r'\int_{1/\sqrt2}^{1}\int_{\sqrt{1-x^2}}^xxy\,dy\,dx+\int_1^{\sqrt2}\int_0^xxy\,dy\,dx+\int_{\sqrt2}^2\int_0^{\sqrt{4-x^2}}xy\,dy\,dx'),'Combine into one polar integral and evaluate: '+d(r'\int_{1/\sqrt2}^{1}\int_{\sqrt{1-x^2}}^xxy\,dy\,dx+\int_1^{\sqrt2}\int_0^xxy\,dy\,dx+\int_{\sqrt2}^2\int_0^{\sqrt{4-x^2}}xy\,dy\,dx')),r**3*s.cos(t)*s.sin(t),[(r,1,2),(t,0,s.pi/4)],('세 세로조각은 '+m(r'1\le r\le2,\ 0\le\theta\le\pi/4')+'인 원고리 부채꼴을 이룬다.','The three vertical pieces form the annular sector '+m(r'1\le r\le2,\ 0\le\theta\le\pi/4')+'.'))
add(50,('가우스 적분을 증명하라. (a)원판을 확대하여 '+m(r'\iint_{\mathbb R^2}e^{-x^2-y^2}dA=\pi')+'를 보인다. (b)확대되는 정사각형과 원판을 비교한다. (c) '+m(r'\int_{-\infty}^{\infty}e^{-x^2}dx')+', (d) '+m(r'\int_{-\infty}^{\infty}e^{-x^2/2}dx')+'를 구하라.','Prove the Gaussian integral: (a) integrate over expanding disks to show '+m(r'\iint_{\mathbb R^2}e^{-x^2-y^2}dA=\pi')+'; (b) compare expanding squares with disks; (c) evaluate '+m(r'\int_{-\infty}^{\infty}e^{-x^2}dx')+'; (d) evaluate '+m(r'\int_{-\infty}^{\infty}e^{-x^2/2}dx')+'.'),[('(a) 반지름 a의 원판에서 '+d(r'2\pi\int_0^a re^{-r^2}dr=\pi(1-e^{-a^2})\longrightarrow\pi')+'이다.','(a) On a radius-a disk, '+d(r'2\pi\int_0^a re^{-r^2}dr=\pi(1-e^{-a^2})\longrightarrow\pi')),('(b) '+m(r'D_a\subset[-a,a]^2\subset D_{\sqrt2a}')+'이고 함수가 음이 아니므로 두 원판 적분 사이에 정사각형 적분이 끼어 있다. 그 극한도 π이다.','(b) Since '+m(r'D_a\subset[-a,a]^2\subset D_{\sqrt2a}')+' and the integrand is nonnegative, the square integral is squeezed between disk integrals and tends to π.'),('(c) 유한 정사각형에서는 Fubini로 적분이 '+m(r'(\int_{-a}^ae^{-x^2}dx)^2')+'이다. 양의 제곱근을 취하고 극한을 취하면 '+m(r'\sqrt\pi')+'이다.','(c) Fubini on each finite square gives '+m(r'(\int_{-a}^ae^{-x^2}dx)^2')+'. Taking the positive square root and the limit yields '+m(r'\sqrt\pi')+'.'),('(d) '+m(r'x=\sqrt2u')+'로 치환하면 '+m(r'\sqrt2\sqrt\pi')+'이다.','(d) Substitute '+m(r'x=\sqrt2u')+' to obtain '+m(r'\sqrt2\sqrt\pi')+'.')],d(r'(a),(b)\ \pi;\quad(c)\sqrt\pi;\quad(d)\sqrt{2\pi}'),('a','b','c','d'))
add(51,('가우스 적분을 이용하여 (a) '+m(r'\int_0^\infty x^2e^{-x^2}dx')+'와 (b) '+m(r'\int_0^\infty\sqrt{x}e^{-x}dx')+'를 구하라.','Use the Gaussian integral to evaluate (a) '+m(r'\int_0^\infty x^2e^{-x^2}dx')+' and (b) '+m(r'\int_0^\infty\sqrt{x}e^{-x}dx')+'.'),[('(a) 부분적분에서 '+m(r'u=x,\ dv=xe^{-x^2}dx')+'를 택한다. 경계항은0이다. '+d(r'\int_0^\infty x^2e^{-x^2}dx=\frac12\int_0^\infty e^{-x^2}dx=\frac{\sqrt\pi}{4}'),'(a) Integrate by parts with '+m(r'u=x,\ dv=xe^{-x^2}dx')+'. The boundary term vanishes. '+d(r'\int_0^\infty x^2e^{-x^2}dx=\frac12\int_0^\infty e^{-x^2}dx=\frac{\sqrt\pi}{4}')),('(b) '+m('x=u^2')+'이면 적분이 (a)의2배가 된다. '+d(r'\int_0^\infty\sqrt{x}e^{-x}dx=2\int_0^\infty u^2e^{-u^2}du=\frac{\sqrt\pi}{2}'),'(b) Substitute '+m('x=u^2')+' to obtain twice the integral in(a). '+d(r'\int_0^\infty\sqrt{x}e^{-x}dx=2\int_0^\infty u^2e^{-u^2}du=\frac{\sqrt\pi}{2}'))],d(r'(a)\sqrt\pi/4,\quad(b)\sqrt\pi/2'),('a','b'))
for n,(name,title) in figures.items():attach(next(e for e in D.items if e['number']==n),name,('경계 조건으로 직접 그린 평면영역','Original planar region drawn from its boundary conditions'),(title,title))
e=next(e for e in D.items if e['number']==25)
e['steps']['ko'].append('원문의 부피 표현은 음의 높이를 포함한 도해와 양립하지 않는다. z≥0이면서 그래프 아래인 부분만 취하는 또 다른 해석은 위쪽 반원판만 적분하여 부피18을 준다. 부호 있는 적분9와 구별해야 한다.')
e['steps']['en'].append('The source wording about volume is ambiguous because its diagram includes negative heights. If only points with z≥0 below the graph are retained, the upper half-disk gives volume18. This differs from the signed integral9.')
e['answer']['ko']+=' z≥0이고 그래프 아래인 부분만 취하면18.'
e['answer']['en']+=' Restricting to z≥0 below the graph gives18.'
D.save(51)

report_path=ROOT/"exercise-checks/s15-3-report.json"
report=json.loads(report_path.read_text());report["uncertainties"]=[{"exercise":25,"kind":"source wording ambiguity","note":"Source says volume but three-quarter disk includes negative y heights. Signed integral9; between graph and plane27; z>=0 below graph18. All three interpretations are explicitly distinguished."}];report_path.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n")
