"""Original bilingual derivations for every exercise in 15.4."""
from core_15 import *
x,y,r,t=s.symbols('x y r theta',real=True);a,b,h,k=s.symbols('a b h k',positive=True)
D=Doc('15.4',[1116,1117],lambda n:1116 if n<=16 else 1117)
def add(n,st,steps,ans,parts=(),topic=('이중적분의 응용','Applications of double integrals'),check=('적분영역과 단위를 확인하고 기호 계산으로 검산했다.','The region and units were checked, and the integrals were evaluated symbolically.')):
 return D.add(n,topic,st,('질량·모멘트·확률에 알맞은 적분함수를 정한 뒤 영역을 적분한다.','Choose the appropriate mass, moment, or probability integrand and integrate over the region.'),steps,ans,check,parts)
def calc(n,st,f,lims,label='Q'):
 v,steps=D.evaluated(f,lims);steps.insert(0,('밀도를 영역 전체에 적분한다. '+d(label+'='+integral(f,lims)),'Integrate the density over the region. '+d(label+'='+integral(f,lims))));add(n,st,steps,d(label+'='+tex(v)));return v
calc(1,('직사각형 '+m(r'0\le x\le5,\ 2\le y\le5')+'에서 전하밀도가 '+m(r'2x+4y\ \mathrm{C/m^2}')+'이다. 총전하를 구하라.','Find total charge on '+m(r'0\le x\le5,\ 2\le y\le5')+' with charge density '+m(r'2x+4y\ \mathrm{C/m^2}')+'.'),2*x+4*y,[(y,2,5),(x,0,5)])
calc(2,('단위원판의 전하밀도가 '+m(r'\sqrt{x^2+y^2}')+'일 때 총전하를 구하라.','Find the total charge on the unit disk with density '+m(r'\sqrt{x^2+y^2}')+'.'),r*r,[(r,0,1),(t,0,2*s.pi)])
regions={3:(x*x,[(y,0,1),(x,0,1)],r'[0,1]^2'),4:(x*y,[(y,0,1),(x,0,1)],r'[0,1]^2'),5:(k*y*y,[(y,1,4),(x,1,3)],r'[1,3]\times[1,4]'),6:(1+x*x+y*y,[(y,0,b),(x,0,a)],r'[0,a]\times[0,b]'),7:(x+y,[(y,x/2,3-x),(x,0,2)],r'0\le x\le2,\quad x/2\le y\le3-x'),8:(x,[(x,y/2,1-2*y),(y,0,s.Rational(2,5))],r'0\le y\le2/5,\quad y/2\le x\le1-2y'),9:(k*y,[(y,0,1-x*x),(x,-1,1)],r'-1\le x\le1,\quad0\le y\le1-x^2'),10:(k*x*x,[(y,x*x,x+2),(x,-1,2)],r'-1\le x\le2,\quad x^2\le y\le x+2'),11:(x*y,[(y,0,s.exp(-x)),(x,0,1)],r'0\le x\le1,\quad0\le y\le e^{-x}'),12:(y,[(y,0,s.cos(x)),(x,-s.pi/2,s.pi/2)],r'-\pi/2\le x\le\pi/2,\quad0\le y\le\cos x')}
cache={}
def moments(n,rho,lims,desc,polar=False,inertia=False,only_center=False,st=None):
 xx=r*s.cos(t) if polar else x;yy=r*s.sin(t) if polar else y;jac=r if polar else 1
 vals=[];steps=[]
 spec=[('m',rho*jac),('M_y',xx*rho*jac),('M_x',yy*rho*jac)]
 if inertia:spec += [('I_x',yy*yy*rho*jac),('I_y',xx*xx*rho*jac)]
 for label,f in spec:
  v,sub=D.evaluated(s.expand_trig(f),lims);vals.append(v)
  steps.append(('정의에 해당하는 적분을 계산한다. '+d(label+'='+integral(f,lims)+'='+tex(v)),'Evaluate the defining integral. '+d(label+'='+integral(f,lims)+'='+tex(v))))
 mass,my,mx=vals[:3];cx=s.simplify(my/mass);cy=s.simplify(mx/mass)
 eq=d(r'(\bar x,\bar y)=\left(\frac{M_y}{m},\frac{M_x}{m}\right)=('+tex(cx)+','+tex(cy)+')')
 steps.append(('모멘트를 질량으로 나눈다. '+eq,'Divide each first moment by the mass. '+eq))
 answer=(d('m='+tex(mass)) if not only_center else '')+eq
 if inertia:answer+=d('I_x='+tex(vals[3])+r',\quad I_y='+tex(vals[4]))
 if n in (3,4):steps.insert(0,('밀도가 '+('오른쪽으로 증가하므로 중심은 정사각형 중앙보다 오른쪽이고 높이는 절반이다.' if n==3 else '오른쪽 위로 증가하므로 두 좌표 모두 절반보다 크며 대각선 대칭이다.'),'The density '+('increases to the right, so the center lies right of the midpoint at half height.' if n==3 else 'increases toward the upper right; both coordinates exceed one half and symmetry places the center on the diagonal.')))
 if st is None:st=('영역 '+m(desc)+'에서 밀도 '+m(r'\rho='+tex(rho))+'인 얇은 판의 '+('무게중심을 먼저 예측하고 정확히 구하라.' if n in(3,4) else '질량과 무게중심을 구하라.'),'For a lamina on '+m(desc)+' with density '+m(r'\rho='+tex(rho))+', '+('predict the center from the density and then calculate it.' if n in(3,4) else 'find the mass and center of mass.'))
 add(n,st,steps,answer);cache[n]=(rho,lims,desc,polar,vals,cx,cy)
for n,args in regions.items():moments(n,*args)
polars={13:(k*r*s.sin(t),[(r,0,1),(t,0,s.pi/2)],r'0\le r\le1,\ 0\le\theta\le\pi/2'),14:(k*r*r,[(r,0,1),(t,0,s.pi/2)],r'0\le r\le1,\ 0\le\theta\le\pi/2'),15:(k*r,[(r,1,2),(t,0,s.pi)],r'1\le r\le2,\ 0\le\theta\le\pi'),16:(k/r,[(r,1,2),(t,0,s.pi)],r'1\le r\le2,\ 0\le\theta\le\pi'),18:(k/r,[(r,1,2*s.sin(t)),(t,s.pi/6,5*s.pi/6)],r'\pi/6\le\theta\le5\pi/6,\ 1\le r\le2\sin\theta')}
for n,args in polars.items():moments(n,*args,polar=True,only_center=True)
moments(17,k*(x*x+y*y),[(y,0,a-x),(x,0,a)],r'x,y\ge0,\ x+y\le a',only_center=True)
for n,ref in [(19,5),(20,8),(21,17)]:
 rho,lims,desc,pol,vs,cx,cy=cache[ref];ix,stx=D.evaluated(y*y*rho,lims);iy,sty=D.evaluated(x*x*rho,lims)
 add(n,('문항 '+str(ref)+'의 판에 대해 '+m(r'I_x,I_y,I_0')+'를 구하라. 영역 '+m(desc)+', 밀도 '+m(tex(rho))+'.','Find '+m(r'I_x,I_y,I_0')+' for the lamina of Exercise '+str(ref)+': region '+m(desc)+', density '+m(tex(rho))+'.'),[('회전축까지의 거리 제곱을 밀도에 곱한다. '+d('I_x='+integral(y*y*rho,lims)+',\quad I_y='+integral(x*x*rho,lims)),'Multiply density by squared distance from the axis. '+d('I_x='+integral(y*y*rho,lims)+',\quad I_y='+integral(x*x*rho,lims)))]+stx+sty+[('원점의 극관성모멘트는 두 축 관성모멘트의 합이다.','The polar moment equals the sum of the two axial moments.')],d('I_x='+tex(ix)+',\quad I_y='+tex(iy)+',\quad I_0='+tex(ix+iy)))
rho=1+x/10;lims=[(y,0,2),(x,0,2)];ix,stx=D.evaluated(y*y*rho,lims);iy,sty=D.evaluated(x*x*rho,lims)
add(22,('정사각형 '+m('[0,2]^2')+'의 밀도는 '+m(r'1+0.1x')+'이다. x축과 y축 중 어느 축으로 회전시키기가 더 어려운가?','A square lamina on '+m('[0,2]^2')+' has density '+m('1+0.1x')+'. Which axis, x or y, offers greater rotational inertia?'),[('각 축까지의 거리 제곱을 사용한다.','Use the squared distance from each axis.')]+stx+sty,(''+d('I_x='+tex(ix)+',\quad I_y='+tex(iy))+'이므로 y축이다.',d('I_x='+tex(ix)+',\quad I_y='+tex(iy))+'Thus the y-axis.'))
for n,lims,desc,polar in [(23,[(y,0,h),(x,0,b)],r'[0,b]\times[0,h]',False),(24,[(y,0,h*(1-x/b)),(x,0,b)],r'x,y\ge0,\ x/b+y/h\le1',False),(25,[(r,0,a),(t,0,s.pi/2)],r'0\le r\le a,\ 0\le\theta\le\pi/2',True),(26,[(y,0,s.sin(x)),(x,0,s.pi)],r'0\le x\le\pi,\ 0\le y\le\sin x',False)]:
 xx=r*s.cos(t) if polar else x;yy=r*s.sin(t) if polar else y;j=r if polar else 1
 mass,_=D.evaluated(k*j,lims);ix,_=D.evaluated(k*yy**2*j,lims);iy,_=D.evaluated(k*xx**2*j,lims)
 add(n,('균일한 밀도 '+m('k')+'의 영역 '+m(desc)+'에 대해 축 관성모멘트와 회전반경을 구하라.','Find axial moments of inertia and radii of gyration for uniform density '+m('k')+' on '+m(desc)+'.'),[('질량과 관성모멘트의 정의를 적용한다. '+d('m='+integral(k*j,lims)+'='+tex(mass)),'Apply the mass and inertia definitions. '+d('m='+integral(k*j,lims)+'='+tex(mass))),('각 축에서 거리 제곱을 적분한다. '+d('I_x='+integral(k*yy**2*j,lims)+'='+tex(ix))+d('I_y='+integral(k*xx**2*j,lims)+'='+tex(iy)),'Integrate squared distance from each axis. '+d('I_x='+integral(k*yy**2*j,lims)+'='+tex(ix))+d('I_y='+integral(k*xx**2*j,lims)+'='+tex(iy))),('회전반경은 해당 관성모멘트를 질량으로 나눈 값의 제곱근이다.','Each radius of gyration is the square root of the corresponding moment divided by mass.')],d('I_x='+tex(ix)+',\quad I_y='+tex(iy))+d(r'\bar{\bar x}=\sqrt{I_y/m}='+tex(s.simplify(s.sqrt(iy/mass)))+r',\quad\bar{\bar y}=\sqrt{I_x/m}='+tex(s.simplify(s.sqrt(ix/mass)))))
moments(27,r*r,[(r,0,s.cos(2*t)),(t,-s.pi/4,s.pi/4)],r'-\pi/4\le\theta\le\pi/4,\ 0\le r\le\cos2\theta',polar=True,inertia=True,st=('장미곡선 '+m(r'r=\cos2\theta')+'의 오른쪽 잎, 밀도 '+m(r'\rho=r^2')+'에 대해 CAS로 질량·무게중심·축 관성모멘트를 구하라.','Use a CAS to find mass, center of mass, and axial moments for the right petal of '+m(r'r=\cos2\theta')+' with '+m(r'\rho=r^2')+'.'))
moments(28,x*x*y*y,[(y,0,x*s.exp(-x)),(x,0,2)],r'0\le x\le2,\ 0\le y\le xe^{-x}',inertia=True,st=(''+m(r'0\le x\le2,\ 0\le y\le xe^{-x},\ \rho=x^2y^2')+'인 판의 질량·무게중심·축 관성모멘트를 CAS로 구하라.','Use a CAS to find mass, center of mass, and axial moments on '+m(r'0\le x\le2,\ 0\le y\le xe^{-x}')+' with '+m(r'\rho=x^2y^2')+'.'))
# Probability: every event, support, and expectation is stated explicitly.
f=x*(1+y)/2;norm,_=D.evaluated(x*(1+y),[(y,0,2),(x,0,1)]);p1,st1=D.evaluated(f,[(y,0,1),(x,0,1)]);p2,st2=D.evaluated(f,[(y,0,1-x),(x,0,1)])
add(29,('결합밀도 '+m(r'f(x,y)=Cx(1+y)')+'의 지지집합은 '+m('[0,1]\\times[0,2]')+'이다. (a) C, (b) '+m('P(X\\le1,Y\\le1)')+', (c) '+m('P(X+Y\\le1)')+'을 구하라.','The density '+m(r'f(x,y)=Cx(1+y)')+' is zero outside '+m('[0,1]\\times[0,2]')+'. Find (a) C, (b) '+m('P(X\\le1,Y\\le1)')+', and (c) '+m('P(X+Y\\le1)')+'.'),[('(a) 총확률은 1이다. '+d('1=C\\cdot'+tex(norm)+',\quad C=1/2'),'(a) Normalize the density. '+d('1=C\\cdot'+tex(norm)+',\quad C=1/2')),('(b) 직사각형 사건을 적분한다.','(b) Integrate over the rectangular event.')]+st1+[('(c) 삼각형 사건은 '+m(r'0\le y\le1-x,\ 0\le x\le1')+'이다.','(c) The triangular event is '+m(r'0\le y\le1-x,\ 0\le x\le1')+'.')]+st2,d('(a)\ C=1/2,\quad(b)\ '+tex(p1)+',\quad(c)\ '+tex(p2)),('a','b','c'))
for n,f,lims,events in [(30,4*x*y,[(y,0,1),(x,0,1)],[[(y,0,1),(x,s.Rational(1,2),1)],[(y,0,s.Rational(1,2)),(x,s.Rational(1,2),1)]]),(31,s.exp(-x/2-y/5)/10,[(y,0,s.oo),(x,0,s.oo)],[[(y,1,s.oo),(x,0,s.oo)],[(y,0,4),(x,0,2)]] )]:
 st=('밀도 '+m(tex(f))+'는 '+('단위 정사각형' if n==30 else '제1사분면')+' 밖에서 0이다. (a) 밀도를 검증하고, (b) '+(m(r'P(X\ge1/2),\ P(X\ge1/2,Y\le1/2)') if n==30 else m(r'P(Y\ge1),\ P(X\le2,Y\le4)'))+', (c) 두 기댓값을 구하라.','The density '+m(tex(f))+' vanishes outside the '+('unit square' if n==30 else 'first quadrant')+'. (a) Verify it is a density; (b) find '+(m(r'P(X\ge1/2),\ P(X\ge1/2,Y\le1/2)') if n==30 else m(r'P(Y\ge1),\ P(X\le2,Y\le4)'))+'; (c) find both expectations.')
 steps=[];results=[]
 for label,ff,ll in [('1',f,lims),('P_1',f,events[0]),('P_2',f,events[1]),('E[X]',x*f,lims),('E[Y]',y*f,lims)]:
  v,_=D.evaluated(ff,ll);results.append(v);eq=d(integral(ff,ll)+'='+tex(v));steps.append(('밀도는 음이 아니며, '+m(label)+'에 해당하는 적분은 '+eq,'The density is nonnegative; the integral for '+m(label)+' is '+eq))
 add(n,st,steps,d(r'\iint f=1,\quad P_1='+tex(results[1])+',\quad P_2='+tex(results[2])+',\quad E[X]='+tex(results[3])+',\quad E[Y]='+tex(results[4])),('a','b','c'))
add(32,('독립인 두 전구 수명은 평균1000시간인 지수분포이다. (a) 둘 다1000시간 이내에 고장 날 확률, (b) 하나가 고장 나면 다음 것을 사용하여 총 사용시간이1000시간 이내일 확률을 구하라.','Two independent bulb lifetimes are exponential with mean1000 hours. Find (a) the probability both fail within1000 hours, and (b) the probability sequential use of both lasts at most1000 hours.'),[('(a) 각 누적확률은 '+m('1-e^{-1}')+'이며 독립이므로 곱한다.','(a) Each marginal probability is '+m('1-e^{-1}')+'; independence allows multiplication.'),('(b) '+m('u=X/1000,v=Y/1000')+'이면 합 사건은 삼각형이다. '+d(r'\int_0^1\int_0^{1-u}e^{-u-v}\,dv\,du=\int_0^1(e^{-u}-e^{-1})\,du=1-2/e'),'(b) With '+m('u=X/1000,v=Y/1000')+', the sum event is triangular. '+d(r'\int_0^1\int_0^{1-u}e^{-u-v}\,dv\,du=\int_0^1(e^{-u}-e^{-1})\,du=1-2/e'))],d(r'(a)\ (1-e^{-1})^2\approx0.399576,\quad(b)\ 1-2/e\approx0.264241'),('a','b'))
add(33,('독립 정규변수는 '+m(r'X\sim N(45,0.5^2),\ Y\sim N(20,0.1^2)')+'이다. (a) '+m(r'40\le X\le50,\ 20\le Y\le25')+'일 확률과 (b) '+m(r'4(X-45)^2+100(Y-20)^2\le2')+'일 확률을 소수 셋째 자리까지 구하라.','Independent normal variables satisfy '+m(r'X\sim N(45,0.5^2),\ Y\sim N(20,0.1^2)')+'. Find to three decimals (a) '+m(r'P(40\le X\le50,\ 20\le Y\le25)')+' and (b) '+m(r'P(4(X-45)^2+100(Y-20)^2\le2)')+'.'),[('표준화 '+m(r'U=2(X-45),\ V=10(Y-20)')+'로 독립 표준정규변수를 얻는다.','Standardize to independent standard normals '+m(r'U=2(X-45),\ V=10(Y-20)')+'.'),('(a) 독립성으로 '+m(r'[\Phi(10)-\Phi(-10)][\Phi(50)-\Phi(0)]\approx1/2')+'이다.','(a) Independence gives '+m(r'[\Phi(10)-\Phi(-10)][\Phi(50)-\Phi(0)]\approx1/2')+'.'),('(b) 표준화 평면에서 반지름 '+m(r'\sqrt2')+'의 원판이다. '+d(r'\frac1{2\pi}\int_0^{2\pi}\int_0^{\sqrt2}e^{-r^2/2}r\,dr\,d\theta=1-e^{-1}'),'(b) The standardized event is a disk of radius '+m(r'\sqrt2')+'. '+d(r'\frac1{2\pi}\int_0^{2\pi}\int_0^{\sqrt2}e^{-r^2/2}r\,dr\,d\theta=1-e^{-1}'))],d(r'(a)\ 0.500,\quad(b)\ 0.632'),('a','b'))
add(34,('도착시각은 독립이며 X의 밀도는 '+m(r'e^{-x}\ (x\ge0)')+', Y의 밀도는 '+m(r'y/50\ (0\le y\le10)')+'이다(분). Y는30분 기다리고 X는 기다리지 않는다. 두 사람이 만날 확률은?','Independent arrival times in minutes have densities '+m(r'e^{-x}\ (x\ge0)')+' for X and '+m(r'y/50\ (0\le y\le10)')+' for Y. Y waits30 minutes; X does not wait. Find the probability they meet.'),[('Y가 먼저 와서 아직 기다리는 경우만 가능하므로 '+m(r'0\le y\le10,\ y\le x\le y+30')+'이다.','They meet exactly when Y has arrived and is still waiting: '+m(r'0\le y\le10,\ y\le x\le y+30')+'.'),('독립 결합밀도를 사건에 적분한다. '+d(r'P=\int_0^{10}\int_y^{y+30}\frac y{50}e^{-x}\,dx\,dy=\frac{1-e^{-30}}{50}\int_0^{10}ye^{-y}\,dy'), 'Integrate the independent joint density over this event. '+d(r'P=\int_0^{10}\int_y^{y+30}\frac y{50}e^{-x}\,dx\,dy=\frac{1-e^{-30}}{50}\int_0^{10}ye^{-y}\,dy')),('부분적분으로 '+m(r'\int_0^{10}ye^{-y}dy=1-11e^{-10}')+'을 얻는다.','Integration by parts gives '+m(r'\int_0^{10}ye^{-y}dy=1-11e^{-10}')+'.')],d(r'P=\frac{(1-e^{-30})(1-11e^{-10})}{50}\approx0.0199900'))
add(35,('반지름10마일인 원형 도시에서 감염자 밀도가 일정한 k명/제곱마일이다. 모형에서 A의 개인이 거리 r인 감염자로부터 감염될 확률은 '+m(r'(20-r)/20')+'이다. (a) 이 확률들의 총합인 노출량을 이중적분으로 나타내라. (b) 도시 중심과 경계 중 모형상 노출량이 작은 위치를 비교하라.','A circular city has radius10 miles and constant infected-person density k per square mile. In the model, an individual at A has infection probability '+m(r'(20-r)/20')+' from a source at distance r. (a) Express the sum of these probabilities as a double integral. (b) Compare exposure at the center and at the boundary.'),[('(a) 거리 함수로 '+d(r'E(A)=k\iint_D\left(1-\frac{|P-A|}{20}\right)dA_P')+'를 얻는다.','(a) In terms of distance, '+d(r'E(A)=k\iint_D\left(1-\frac{|P-A|}{20}\right)dA_P')),('(b) 중심에서 극좌표로 '+d(r'E_c=k\int_0^{2\pi}\int_0^{10}(1-r/20)r\,dr\,d\theta=\frac{200\pi k}{3}')+'이다.','(b) Polar coordinates centered in the city give '+d(r'E_c=k\int_0^{2\pi}\int_0^{10}(1-r/20)r\,dr\,d\theta=\frac{200\pi k}{3}')),('경계의 A를 원점으로 하고 도시 안쪽을 각도0으로 잡으면 '+m(r'0\le r\le20\cos\theta,\ |\theta|\le\pi/2')+'이다. '+d(r'E_b=k\int_{-\pi/2}^{\pi/2}\int_0^{20\cos\theta}(1-r/20)r\,dr\,d\theta=k(100\pi-1600/9)'), 'Put the polar origin at the boundary point A and point angle zero inward. The city is '+m(r'0\le r\le20\cos\theta,\ |\theta|\le\pi/2')+'. '+d(r'E_b=k\int_{-\pi/2}^{\pi/2}\int_0^{20\cos\theta}(1-r/20)r\,dr\,d\theta=k(100\pi-1600/9)')),('두 값은 각각 약209.440k와136.381k이므로 이 모형에서는 경계가 더 작다. 노출량은 확률들의 합이므로 자체가 1 이하일 필요는 없다.','The values are approximately209.440k and136.381k, so the boundary has lower exposure in this model. Exposure is a sum of probabilities and need not be at most one.')],('중심 '+m(r'200\pi k/3')+', 경계 '+m(r'(100\pi-1600/9)k')+'. 경계의 노출량이 작다.','Center: '+m(r'200\pi k/3')+'; boundary: '+m(r'(100\pi-1600/9)k')+'. Boundary exposure is smaller.'),('a','b'))
D.save(35)
