"""Space motion Exercises1–46; source notation and units checked visually."""
from early_helpers import Book
from pathlib import Path
import sympy as s,math,json
b=Book('13.4',[961,962,963]);t=s.symbols('t',real=True);M=s.Matrix;R=s.Rational;checks=[]
def tex(z):return s.latex(s.simplify(z))
def v(z):return r'\langle '+','.join(tex(a)for a in z)+r'\rangle'
def m(z):return r'\('+z+r'\)'
def eq(label,z):
 assert all(s.simplify(a)==0 for a in z)if isinstance(z,s.MatrixBase)else s.simplify(z)==0,(label,z)
 checks.append(label)
def add(n,k,e,ks,es,ans,ae=None,parts=[]):
 b.add(n,961 if n<=2 else 962 if n<=33 else 963,('공간운동: 속도와 가속도','Motion in space: velocity and acceleration'),(k,e),list(zip(ks,es)),(ans,ans if ae is None else ae),parts,check=('미분·초기조건·단위 및 경계값을 다시 대입해 확인했다. 그림에서 읽은 값은 근사임을 구분했다.','Checked derivatives, initial conditions, units and boundary substitutions. Values read from diagrams are identified as estimates.'));b.E[n]['conceptHref']='../../calc1/index.html'
table=r'\begin{array}{c|rrr}t&x&y&z\\0&2.7&9.8&3.7\\0.5&3.5&7.2&3.3\\1&4.5&6.0&3.0\\1.5&5.9&6.4&2.8\\2&7.3&7.8&2.7\end{array}'
add(1,'표'+m(table)+'에대해(a)[0,1],[0.5,1],[1,2],[1,1.5]의평균속도,(b)t=1의순간속도와속력을추정하라.','Using '+m(table)+', (a)find average velocities on[0,1],[0.5,1],[1,2],[1,1.5];(b)estimate velocity and speed at t=1.',[m(r'v_{avg}=\frac{r(b)-r(a)}{b-a}'),'(a)표의끝점차를각시간간격으로나누면순서대로아래네벡터이다.',m(r'(b)\quad v(1)\approx\frac{r(1.5)-r(0.5)}{1}=\langle2.4,-0.8,-0.5\rangle'),m(r'|v(1)|\approx\sqrt{2.4^2+0.8^2+0.5^2}=\sqrt{6.65}')],[m(r'v_{avg}=\frac{r(b)-r(a)}{b-a}'),'(a)Subtract endpoint coordinates and divide by the corresponding interval length to obtain the four vectors below.',m(r'(b)\quad v(1)\approx\frac{r(1.5)-r(0.5)}{1}=\langle2.4,-0.8,-0.5\rangle'),m(r'|v(1)|\approx\sqrt{2.4^2+0.8^2+0.5^2}=\sqrt{6.65}')],m(r'(a)\ \langle1.8,-3.8,-0.7\rangle,\ \langle2,-2.4,-0.6\rangle,\ \langle2.8,1.8,-0.3\rangle,\ \langle2.8,0.8,-0.4\rangle')+'; '+m(r'(b)\ v(1)\approx\langle2.4,-0.8,-0.5\rangle,\quad|v(1)|\approx2.58'),parts=list('ab'))
add(2,'경로그림의r(1.5),r(2),r(2.4)를사용하여(a)[2,2.4],(b)[1.5,2]의평균속도벡터를그리고(c)v(2)를극한으로써라. (d)순간속도를그리고속력을추정하라.','Using r(1.5),r(2),r(2.4)on the path diagram, draw average velocities on(a)[2,2.4]and(b)[1.5,2];(c)write v(2)as a limit;(d)draw an estimate of the velocity and estimate speed.',[m(r'(a)\quad\frac{r(2.4)-r(2)}{0.4}=2.5\overrightarrow{r(2)r(2.4)}'),m(r'(b)\quad\frac{r(2)-r(1.5)}{0.5}=2\overrightarrow{r(1.5)r(2)}'),m(r'(c)\quad v(2)=\lim_{h\to0}\frac{r(2+h)-r(2)}h'),'(d)r(2)에서왼쪽위로향하는접선벡터를그린다. 그림의눈금으로두할선속도를읽고그사이접선방향을추정하면대략v≈(-2,1.6),속력≈2.6이다. 그림읽기오차가있으며정확한수치성분이주어진것은아니다.'],[m(r'(a)\quad\frac{r(2.4)-r(2)}{0.4}=2.5\overrightarrow{r(2)r(2.4)}'),m(r'(b)\quad\frac{r(2)-r(1.5)}{0.5}=2\overrightarrow{r(1.5)r(2)}'),m(r'(c)\quad v(2)=\lim_{h\to0}\frac{r(2+h)-r(2)}h'),'(d)Draw a tangent at r(2)pointing up and left. Reading the secants against the graph scale and estimating the intermediate tangent gives roughly v≈(-2,1.6),speed≈2.6. These have graphical uncertainty; exact components are not supplied.'],m(r'v(2)\approx\langle-2,1.6\rangle,\quad|v(2)|\approx2.6'),parts=list('abcd'))
rows=[(3,[-t*t/2,t],2),(4,[t*t,t**-2],1),(5,[3*s.cos(t),2*s.sin(t)],s.pi/3),(6,[s.exp(t),s.exp(2*t)],0),(7,[t,t*t,2],1),(8,[t,2*s.cos(t),s.sin(t)],0),(9,[t*t+t,t*t-t,t**3],None),(10,[2*s.cos(t),3*t,2*s.sin(t)],None),(11,[s.sqrt(2)*t,s.exp(t),s.exp(-t)],None),(12,[t*t,2*t,s.log(t)],None),(13,[s.exp(t)*s.cos(t),s.exp(t)*s.sin(t),t*s.exp(t)],None),(14,[t*t,s.sin(t)-t*s.cos(t),s.cos(t)+t*s.sin(t)],None)]
for n,ff,at in rows:
 r=M(ff);vel=s.simplify(r.diff(t));acc=s.simplify(vel.diff(t));q=s.trigsimp(vel.dot(vel));speed=s.sqrt(q)
 if n==11:speed=s.exp(t)+s.exp(-t)
 if n==14:speed=s.sqrt(5)*t
 eq(f'{n} speed identity',s.trigsimp(speed**2-q))
 k=m('r(t)='+v(r))+'의속도·가속도·속력을구하라.';e='Find velocity, acceleration and speed for '+m('r(t)='+v(r))+'.'
 if n==12:k+=' t>0.';e+=' t>0.'
 if n==14:k+=' t≥0.';e+=' t≥0.'
 ks=[m(r'v=r^{\prime},\quad a=r^{\prime\prime},\quad|v|=\sqrt{v\cdot v}')];es=ks.copy();ans=m('v(t)='+v(vel))+'; '+m('a(t)='+v(acc))+'; '+m('|v(t)|='+tex(speed))
 if at is not None:
  P=r.subs(t,at);D=vel.subs(t,at);A=acc.subs(t,at);k+=' 경로를그리고'+m('t='+tex(at))+'에서속도와가속도벡터를표시하라.';e+=' Sketch the path and draw velocity and acceleration at '+m('t='+tex(at))+'.'
  ks +=[m('P='+v(P)+r',\quad v_0='+v(D)+r',\quad a_0='+v(A)),'두벡터의시작점을P에두고끝점을각각P+v₀,P+a₀에둔다.'];es +=[m('P='+v(P)+r',\quad v_0='+v(D)+r',\quad a_0='+v(A)),'Place both tails at P and their tips at P+v₀ and P+a₀.']
 add(n,k,e,ks,es,ans)
initial=[(15,[2,0,2*t],[3,-1,0],[0,1,1]),(16,[s.sin(t),2*s.cos(t),6*t],[0,0,-1],[0,1,-4]),(17,[2*t,s.sin(t),s.cos(2*t)],[1,0,0],[0,1,0]),(18,[t,s.exp(t),s.exp(-t)],[0,0,1],[0,1,1])]
for n,ff,v0,r0 in initial:
 a=M(ff);vi=a.applyfunc(lambda z:s.integrate(z,t));vel=s.simplify(vi-vi.subs(t,0)+M(v0));ri=vel.applyfunc(lambda z:s.integrate(z,t));r=s.simplify(ri-ri.subs(t,0)+M(r0))
 for label,z in [('acceleration',r.diff(t,2)-a),('velocity condition',r.diff(t).subs(t,0)-M(v0)),('position condition',r.subs(t,0)-M(r0))]:eq(f'{n} {label}',z)
 add(n,m('a(t)='+v(a)+r',\quad v(0)='+v(v0)+r',\quad r(0)='+v(r0))+'일때속도와위치를구하라.'+(' (a)위치를구한뒤(b)경로를그려라.'if n>=17 else''),'Find velocity and position given '+m('a(t)='+v(a)+r',\quad v(0)='+v(v0)+r',\quad r(0)='+v(r0))+'.'+(' (a)Find position and(b)graph the path.'if n>=17 else''),[m(r'v(t)=v(0)+\int_0^t a(u)\,du'),m('v(t)='+v(vel)),m(r'r(t)=r(0)+\int_0^t v(u)\,du')],[m(r'v(t)=v(0)+\int_0^t a(u)\,du'),m('v(t)='+v(vel)),m(r'r(t)=r(0)+\int_0^t v(u)\,du')],m('v(t)='+v(vel))+'; '+m('r(t)='+v(r)),parts=list('ab')if n>=17 else[])
add(19,'r(t)=(t²,5t,t²−16t)의속력이최소인시간을구하라.','When is the speed of r(t)=(t²,5t,t²−16t)minimal?',[m(r'v=\langle2t,5,2t-16\rangle'),m(r'|v|^2=8t^2-64t+281=8(t-4)^2+153'),'제곱근은증가함수이므로속력제곱을최소화하면된다.'],[m(r'v=\langle2t,5,2t-16\rangle'),m(r'|v|^2=8t^2-64t+281=8(t-4)^2+153'),'The square root is increasing, so minimize squared speed.'],m('t=4'))
add(20,'질량m의입자가r(t)=(t³,t²,t³)를따르는데필요한힘을구하라.','Find the force needed for a mass m to follow r(t)=(t³,t²,t³).',[m(r'a=r^{\prime\prime}=\langle6t,2,6t\rangle'),m('F=ma')],[m(r'a=r^{\prime\prime}=\langle6t,2,6t\rangle'),m('F=ma')],m(r'F(t)=m\langle6t,2,6t\rangle'))
add(21,'4kg물체에위쪽으로20N의힘이작용한다. r(0)=0,v(0)=(1,−1,0)일때위치와속력을구하라.','A20N upward force acts on a4kg object with r(0)=0,v(0)=(1,−1,0). Find position and speed.',[m(r'a=F/m=5k,\quad v=\langle1,-1,5t\rangle'),'주어진힘을운동방정식의알짜힘으로사용한다. 위치는초기위치를더해적분한다.'],[m(r'a=F/m=5k,\quad v=\langle1,-1,5t\rangle'),'Use the stated force as the net force in the motion equation and integrate with the initial position.'],m(r'r(t)=\langle t,-t,5t^2/2\rangle,\quad|v|=\sqrt{2+25t^2}'))
add(22,'속력이일정하면속도와가속도가직교함을보여라.','Show that constant speed implies perpendicular velocity and acceleration.',[m(r'v\cdot v=c^2\Rightarrow\frac{d}{dt}(v\cdot v)=2v\cdot v^{\prime}=0'),m(r'v^{\prime}=a')],[m(r'v\cdot v=c^2\Rightarrow\frac{d}{dt}(v\cdot v)=2v\cdot v^{\prime}=0'),m(r'v^{\prime}=a')],m(r'v\cdot a=0'))
# Standard textbook projectile model: no drag; SI g=9.8, imperial g=32.
g=R(49,5);angle=s.pi/3;ux=100;uz=100*s.sqrt(3)
for n,h in [(23,0),(24,100)]:
 hit=s.simplify((uz+s.sqrt(uz**2+2*g*h))/g);ran=s.simplify(ux*hit);height=s.simplify(h+uz**2/(2*g));impact=s.sqrt(40000+2*g*h);eq(f'{n} impact height',h+uz*hit-g*hit**2/2)
 add(n,'초속200m/s,발사각60°인투사체를지면에서'+(''if h==0 else'100m높이에서')+'발사한다. (a)수평도달거리,(b)최고높이,(c)충돌속력을구하라.','A projectile is launched at200m/s and60° from '+('ground level'if h==0 else'100m above ground')+'. Find(a)range,(b)maximum height,(c)impact speed.',[m(r'x(t)=100t,\quad y(t)='+str(h)+r'+100\sqrt3t-4.9t^2'),'공기저항을무시하고g=9.8m/s²를쓴다. 착지시간은y(t)=0의양의근이다.',m('t_{hit}='+tex(hit)),m(r'y_{max}=y_0+v_{0y}^2/(2g),\quad |v_{hit}|=\sqrt{v_0^2+2gy_0}')],[m(r'x(t)=100t,\quad y(t)='+str(h)+r'+100\sqrt3t-4.9t^2'),'Neglect drag and use g=9.8m/s². Landing time is the positive root of y(t)=0.',m('t_{hit}='+tex(hit)),m(r'y_{max}=y_0+v_{0y}^2/(2g),\quad |v_{hit}|=\sqrt{v_0^2+2gy_0}')],m(rf'(a)\ {float(ran):.2f}\,m;\quad(b)\ {float(height):.2f}\,m;\quad(c)\ {float(impact):.2f}\,m/s'),parts=list('abc'))
add(25,'45°로던진공이같은높이의지면90m앞에떨어졌다. 초기속력을구하라.','A ball thrown at45° lands90m away at the same height. Find its initial speed.',[m(r'R=\frac{v_0^2\sin2\theta}{g},\quad90=v_0^2/9.8'),'공기저항을무시한다.'],[m(r'R=\frac{v_0^2\sin2\theta}{g},\quad90=v_0^2/9.8'),'Neglect drag.'],m(r'v_0=\sqrt{882}=21\sqrt2\approx29.70\,m/s'))
a=math.asin(3000*9.8/400**2)/2
add(26,'초속400m/s의투사체가같은높이의3000m앞목표에도달하는두발사각을구하라.','Find the two launch angles for a400m/s projectile to reach a same-height target3000m away.',[m(r'3000=\frac{400^2\sin2\theta}{9.8}\Rightarrow\sin2\theta=0.18375'),'0<θ<90°에서2θ=arcsin(0.18375)또는π−arcsin(0.18375)이다. 공기저항은무시한다.'],[m(r'3000=\frac{400^2\sin2\theta}{9.8}\Rightarrow\sin2\theta=0.18375'),'For0<θ<90°, use2θ=arcsin(0.18375)orπ−arcsin(0.18375). Neglect drag.'],m(rf'\theta\approx{math.degrees(a):.2f}^\circ,\ {90-math.degrees(a):.2f}^\circ'))
speed=math.sqrt(2*32*1600)/math.sin(math.radians(36))
add(27,'발사각36°인투사체의최대상승높이가1600ft이다. 초기속력을구하라.','A projectile launched at36° rises1600ft. Find its initial speed.',[m(r'H=v_0^2\sin^2\theta/(2g),\quad g=32\,ft/s^2'),m(r'v_0=\sqrt{2(32)(1600)}/\sin36^\circ')],[m(r'H=v_0^2\sin^2\theta/(2g),\quad g=32\,ft/s^2'),m(r'v_0=\sqrt{2(32)(1600)}/\sin36^\circ')],m(rf'v_0\approx{speed:.1f}\,ft/s'))
tf=400/(115*math.cos(math.radians(50)));hf=3+115*math.sin(math.radians(50))*tf-16*tf*tf
add(28,'야구공이높이3ft에서115ft/s,50°로출발한다. 400ft앞높이10ft의담장을넘는가?','A baseball leaves a height of3ft at115ft/s and50°. Does it clear a10ft fence400ft away?',[m(r'x=115\cos50^\circ\,t,\quad y=3+115\sin50^\circ\,t-16t^2'),m(rf't_f=\frac{{400}}{{115\cos50^\circ}}\approx{tf:.4f}\,s'),m(rf'y(t_f)\approx{hf:.2f}\,ft>10\,ft')],[m(r'x=115\cos50^\circ\,t,\quad y=3+115\sin50^\circ\,t-16t^2'),m(rf't_f=\frac{{400}}{{115\cos50^\circ}}\approx{tf:.4f}\,s'),m(rf'y(t_f)\approx{hf:.2f}\,ft>10\,ft')],'공기저항을무시한모형에서는홈런이다. 약'+f'{hf-10:.2f}'+'ft의여유로넘는다.','In the drag-free model it is a home run, clearing the fence by about'+f'{hf-10:.2f}'+'ft.')
roots=[]
for dist in [100,600]:
 aa=9.8*dist*dist/(2*80**2);rr=[(dist-math.sqrt(dist**2-4*aa*(aa+15)))/(2*aa),(dist+math.sqrt(dist**2-4*aa*(aa+15)))/(2*aa)];roots.append([math.degrees(math.atan(z))for z in rr])
add(29,'교재의역사적투사체모형:변길이500m·높이15m의정사각형성벽에서100m떨어진곳에서80m/s로성벽에수직방향으로발사한다. 가까운벽을넘고먼벽밖으로나가지않는발사각범위를구하라.','In the textbook’s historical projectile model, a square enclosure has500m sides and15m walls. A projectile is launched at80m/s from100m away, perpendicular to a wall. Find angles that clear the near wall without passing beyond the far wall.',[m(r'y(x)=x\tan\theta-\frac{9.8x^2}{2(80)^2\cos^2\theta}'),'u=tanθ로놓으면y(x)=xu−0.000765625x²(1+u²)이다. 가까운벽을넘으려면y(100)>15,먼벽을넘어나가지않으려면y(600)<15이다. 후자는안쪽지면에도달하거나먼벽안쪽에부딪히는경우를포함한다.',m(r'7.65625u^2-100u+22.65625<0'),m(r'275.625u^2-600u+290.625>0'),'각이차식의근을구해0<θ<90°에서두조건의교집합을취한다. 공기저항이없는교재모형이다.'],[m(r'y(x)=x\tan\theta-\frac{9.8x^2}{2(80)^2\cos^2\theta}'),'Set u=tanθ, giving y(x)=xu−0.000765625x²(1+u²). Require y(100)>15 to clear the near wall and y(600)<15 to avoid clearing the far wall. The latter includes reaching the interior ground or striking the inside of the far wall.',m(r'7.65625u^2-100u+22.65625<0'),m(r'275.625u^2-600u+290.625>0'),'Solve the quadratics and intersect their angle intervals within0<θ<90°. This is the textbook’s drag-free model.'],m(rf'{roots[0][0]:.1f}^\circ<\theta<{roots[1][0]:.1f}^\circ\quad\text{{or}}\quad{roots[1][1]:.1f}^\circ<\theta<{roots[0][1]:.1f}^\circ'))
add(30,'투사체가최고점에도달하는시간의절반에서최대상승높이의3/4에도달함을보여라.','Show that a projectile reaches three-quarters of its maximum rise at half the time to the top.',[m(r'y(t)-y_0=ut-\tfrac12gt^2,\quad t_{top}=u/g,\quad H=u^2/(2g)'),m(r'y(t_{top}/2)-y_0=\frac{u^2}{2g}-\frac{u^2}{8g}=\frac{3u^2}{8g}')],[m(r'y(t)-y_0=ut-\tfrac12gt^2,\quad t_{top}=u/g,\quad H=u^2/(2g)'),m(r'y(t_{top}/2)-y_0=\frac{u^2}{2g}-\frac{u^2}{8g}=\frac{3u^2}{8g}')],m(r'y(t_{top}/2)-y_0=3H/4'))
for n,vel0,acc in [(31,[50,0,80],[0,-4,-32]),(32,[0,-15*s.sqrt(3),15],[5,0,-g])]:
 V=M(vel0);A=M(acc);pos=V*t+A*t*t/2;hit=s.simplify(-2*V[2]/A[2]);P=s.simplify(pos.subs(t,hit));Vi=s.simplify(V+A*hit);spd=s.simplify(Vi.norm());eq(f'{n} landing',P[2])
 if n==31:k='동쪽을x,북쪽을y,위를z라하자. 원점에서v₀=(50,0,80)ft/s,a=(0,−4,−32)ft/s²인공의착지점과착지속력을구하라.';e='Take x east,y north,z up. A ball starts at the origin with v₀=(50,0,80)ft/s and a=(0,−4,−32)ft/s². Find its landing point and speed.';unit='ft';us='ft/s'
 else:k='질량0.8kg의공을남쪽으로30m/s,30°로던진다. 동쪽으로일정한4N의바람힘이작용한다. 착지점과속력을구하라.';e='A0.8kg ball is thrown south at30m/s and30°. A steady4N wind force acts east. Find its landing point and speed.';unit='m';us='m/s'
 ks=['x는동쪽,y는북쪽,z는위쪽이고출발점은원점이다.',m('a='+v(A)+r',\quad v_0='+v(V)),m('r(t)='+v(pos)),m('t_{hit}='+tex(hit)+r',\quad v_{hit}='+v(Vi))];es=['Use east,north,up as x,y,z, with the launch point as origin.',m('a='+v(A)+r',\quad v_0='+v(V)),m('r(t)='+v(pos)),m('t_{hit}='+tex(hit)+r',\quad v_{hit}='+v(Vi))]
 if n==32:ks.insert(1,'동쪽가속도는F/m=4/0.8=5m/s²,위쪽가속도는−9.8m/s²이다.');es.insert(1,'Eastward acceleration is F/m=4/0.8=5m/s² and vertical acceleration is−9.8m/s².')
 add(n,k,e,ks,es,m('P='+v(P)+r'\,'+unit)+ '; '+m(rf'|v_{{hit}}|\approx{float(spd):.2f}\,{us}'))
add(33,'북쪽으로흐르는폭40m강의유속은서쪽둑에서거리x일때f(x)=3x(40−x)/400m/s이다. 물에대한속력5m/s로(a)둑에수직으로향할때표류거리와경로,(b)정면반대편에도착할일정선수각과실제경로를구하고그려라.','A40m-wide river flows north with speed f(x)=3x(40−x)/400m/s at distance x from the west bank. A boat moves at5m/s relative to water. (a)Find drift and path when heading perpendicular to the bank.(b)Find a constant heading landing directly opposite; graph and interpret the path.',[m(r'(a)\quad x^{\prime}=5,\quad y^{\prime}=f(x),\quad\frac{dy}{dx}=\frac{3x(40-x)}{2000}'),m(r'y(x)=\frac{60x^2-x^3}{2000},\quad y(40)=16'),'(b)동쪽에서남쪽으로θ만큼조종하면x′=5cosθ,y′=f(x)−5sinθ이다.',m(r'0=y(40)=\frac{\int_0^{40}f(x)\,dx-200\sin\theta}{5\cos\theta}=\frac{80-200\sin\theta}{5\cos\theta}'),m(r'\sin\theta=2/5,\quad\cos\theta=\sqrt{21}/5'),m(r'y(x)=\frac{3x^2/20-x^3/400-2x}{\sqrt{21}}'),'처음에는강물보다남쪽조종성분이커서상류로움직이고,중앙에서는유속이커져하류로돌아온다. 끝부분은다시상류쪽으로향해y(40)=0이된다. 이S자형경로는일정선수각과가변유속에맞는다.'],[m(r'(a)\quad x^{\prime}=5,\quad y^{\prime}=f(x),\quad\frac{dy}{dx}=\frac{3x(40-x)}{2000}'),m(r'y(x)=\frac{60x^2-x^3}{2000},\quad y(40)=16'),'(b)With heading θ south of east, x′=5cosθ and y′=f(x)−5sinθ.',m(r'0=y(40)=\frac{\int_0^{40}f(x)\,dx-200\sin\theta}{5\cos\theta}=\frac{80-200\sin\theta}{5\cos\theta}'),m(r'\sin\theta=2/5,\quad\cos\theta=\sqrt{21}/5'),m(r'y(x)=\frac{3x^2/20-x^3/400-2x}{\sqrt{21}}'),'Near the first bank the upstream heading dominates. The stronger central current turns the path downstream; near the final bank it turns upstream again to reach y(40)=0. This S-shaped path fits the constant heading and variable current.'],m(r'(a)\ 16\,m\text{ downstream};\quad(b)\ \theta=\arcsin(2/5)\approx23.58^\circ\text{ south of east}'),parts=list('ab'))
add(34,'33번의유속을f(x)=3sin(πx/40)로바꾼다. 속력5m/s·일정선수각으로정면반대편에도착할조종각을구하라.','Replace the river speed in33 by f(x)=3sin(πx/40). Find a constant heading at5m/s relative to water that lands directly opposite.',[m(r'x^{\prime}=5\cos\theta,\quad y^{\prime}=3\sin(\pi x/40)-5\sin\theta'),m(r'0=\int_0^{40}\frac{3\sin(\pi x/40)-5\sin\theta}{5\cos\theta}\,dx'),m(r'120(2)/\pi-200\sin\theta=0\Rightarrow\sin\theta=6/(5\pi)')],[m(r'x^{\prime}=5\cos\theta,\quad y^{\prime}=3\sin(\pi x/40)-5\sin\theta'),m(r'0=\int_0^{40}\frac{3\sin(\pi x/40)-5\sin\theta}{5\cos\theta}\,dx'),m(r'120(2)/\pi-200\sin\theta=0\Rightarrow\sin\theta=6/(5\pi)')],m(rf'\theta=\arcsin\frac6{{5\pi}}\approx{math.degrees(math.asin(6/(5*math.pi))):.2f}^\circ')+' 동쪽에서상류쪽(남쪽).',m(rf'\theta=\arcsin\frac6{{5\pi}}\approx{math.degrees(math.asin(6/(5*math.pi))):.2f}^\circ')+' south of east, toward upstream.')
add(35,'상수벡터c에대해r′=c×r일때입자의경로를설명하라.','Describe the path when r′=c×r for a constant vector c.',[m(r'\frac{d}{dt}|r|^2=2r\cdot(c\times r)=0'),m(r'\frac{d}{dt}(c\cdot r)=c\cdot(c\times r)=0'),'c≠0이면원점중심구와c에수직인평면의교선인원에놓인다. 중심은(c·r₀)c/|c|²로c축위에있다. 수직성분은각속력|c|로회전한다.','c=0이거나r₀가c와평행하면정지한다. 유한한시간구간만보면원의일부호만지난다.'],[m(r'\frac{d}{dt}|r|^2=2r\cdot(c\times r)=0'),m(r'\frac{d}{dt}(c\cdot r)=c\cdot(c\times r)=0'),'For c≠0 the path lies in the intersection of a sphere centered at the origin and a plane perpendicular to c: a circle centered at(c·r₀)c/|c|² on the c-axis. The perpendicular component rotates with angular speed|c|.','If c=0 or r₀ is parallel to c, the particle is stationary. A finite time interval may trace only part of the circle.'],'c축에수직인평면의원운동(퇴화하면정지점).','Circular motion in a plane perpendicular to c, degenerating to a stationary point.')
add(36,'(a)직선위를움직일때,(b)곡선위를일정한속력으로움직일때가속도방향을설명하라.','Describe acceleration for(a)motion along a straight line and(b)constant-speed motion along a curve.',[m(r'(a)\quad r(t)=p+u(t)d\Rightarrow a(t)=u^{\prime\prime}(t)d'),'따라서가속도는그직선과평행하거나0이다. 가속과감속에따라속도와같거나반대방향일수있다.',m(r'(b)\quad a_T=\frac{d|v|}{dt}=0,\quad a=\kappa|v|^2N'),'따라서가속도는속도에수직이고굽는쪽주법선방향이며곡률0에서는0이다.'],[m(r'(a)\quad r(t)=p+u(t)d\Rightarrow a(t)=u^{\prime\prime}(t)d'),'Acceleration is parallel to the line or zero; it can point with or against velocity depending on speeding up or slowing down.',m(r'(b)\quad a_T=\frac{d|v|}{dt}=0,\quad a=\kappa|v|^2N'),'Acceleration is perpendicular to velocity, toward the principal normal, and vanishes where curvature is zero.'],'(a)직선방향또는0. (b)법선방향또는0.','(a)Along the line or zero.(b)Normal to the path or zero.',parts=list('ab'))
for n,ff,at in [(37,[t*t+1,t**3,0],None),(38,[2*t*t,R(2,3)*t**3-2*t,0],None),(39,[s.cos(t),s.sin(t),t],None),(40,[t,2*s.exp(t),s.exp(2*t)],None),(41,[s.log(t),t*t+3*t,4*s.sqrt(t)],1),(42,[1/t,1/t**2,1/t**3],1)]:
 r=M(ff);vel=r.diff(t);acc=vel.diff(t);q=s.trigsimp(vel.dot(vel));prod=s.simplify(vel.dot(acc));cross=s.simplify(vel.cross(acc));atcomp=s.simplify(prod/s.sqrt(q));ancomp=s.simplify(s.sqrt(s.trigsimp(cross.dot(cross)))/s.sqrt(q))
 if n==37:atcomp=(4+18*t*t)/s.sqrt(4+9*t*t);ancomp=6*t/s.sqrt(4+9*t*t)
 if n==38:atcomp=4*t;ancomp=s.Integer(4)
 if n==40:atcomp=4*s.exp(2*t);ancomp=2*s.exp(t)
 if at is not None:outT=s.simplify(atcomp.subs(t,at));outN=s.simplify(ancomp.subs(t,at))
 else:outT,outN=atcomp,ancomp
 eq(f'{n} acceleration components',s.trigsimp(atcomp**2+ancomp**2-acc.dot(acc)))
 ks=[m(r'v='+v(vel)+r',\quad a='+v(acc)),m(r'a_T=\frac{v\cdot a}{|v|},\quad a_N=\frac{|v\times a|}{|v|}')];es=ks.copy()
 if n==37:ks+=['원문t≥0에서t=0은속력이0이다. 위의접선·법선공식은t>0에서쓰며t→0⁺의연속확장은(a_T,a_N)=(2,0)이다.'];es+=['The source includes t≥0, but speed vanishes at t=0. The tangent/normal formulas apply for t>0; their right-hand continuous extension is(a_T,a_N)=(2,0).']
 add(n,m('r(t)='+v(r))+'의접선·법선가속도성분을'+(m('t='+tex(at))+'에서'if at is not None else'')+'구하라.','Find tangential and normal acceleration components for '+m('r(t)='+v(r))+(' at '+m('t='+tex(at))if at is not None else'')+'.',ks,es,m('a_T='+tex(outT)+r',\quad a_N='+tex(outN)))
add(43,'그림의가속도벡터크기가10cm/s²일때접선성분과법선성분을추정하라.','Estimate tangential and normal acceleration from the diagram when |a|=10cm/s².',['진행방향의단위접선T를접점에그리고가속도와이루는각θ를잰다. 그림에서는약63°정도이다.',m(r'a_T=|a|\cos\theta,\quad a_N=|a|\sin\theta'),'접선과의각이예각이므로a_T는양수이다. 도형을읽은반올림근삿값이므로성분제곱의합은100과약간다를수있다.'],['Draw the forward unit tangent T and estimate its angle θ with acceleration, about63° in the diagram.',m(r'a_T=|a|\cos\theta,\quad a_N=|a|\sin\theta'),'The angle with the forward tangent is acute, so a_T is positive. Rounded graphical estimates need not have squared sum exactly100.'],m(r'a_T\approx4.5\,cm/s^2,\quad a_N\approx9.0\,cm/s^2'))
add(44,'질량m이일정할때각운동량L=mr×v,토크τ=mr×a라하자. L′=τ와토크0이면각운동량보존임을증명하라.','For constant mass m define angular momentum L=mr×v and torque τ=mr×a. Prove L′=τ and conservation of angular momentum when torque is zero.',[m(r'L^{\prime}=m(r^{\prime}\times v+r\times v^{\prime})=m(v\times v+r\times a)'),m(r'v\times v=0\Rightarrow L^{\prime}=mr\times a=\tau'),'연결시간구간에서τ=0이면각성분의도함수가0이므로L은상수이다.'],[m(r'L^{\prime}=m(r^{\prime}\times v+r\times v^{\prime})=m(v\times v+r\times a)'),m(r'v\times v=0\Rightarrow L^{\prime}=mr\times a=\tau'),'If τ=0 on a connected time interval, every component of L has zero derivative, so L is constant.'],m(r'L^{\prime}=\tau,\quad\tau\equiv0\Rightarrow L=\text{constant}'))
add(45,'우주선r(t)=(3+t,2+ln t,7−4/(1+t²))가(6,4,9)로관성비행하도록엔진을언제꺼야하는가?','When should the engines be cut for r(t)=(3+t,2+ln t,7−4/(1+t²))to coast into the station(6,4,9)?',[m(r'v(t)=\langle1,1/t,8t/(1+t^2)^2\rangle'),m(r'(6,4,9)=r(t)+\lambda v(t),\quad\lambda\ge0'),'x성분에서λ=3−t이므로0<t≤3이다. y성분에서ln t+3/t=3이다.',m(r'\frac{d}{dt}(\ln t+3/t)=\frac{t-3}{t^2}<0\quad(0<t<3)'),'이구간에서해는유일하고t=1이다. r(1)=(4,2,5),v(1)=(1,1,2)이므로λ=2를넣으면(6,4,9)가되어z도맞는다.'],[m(r'v(t)=\langle1,1/t,8t/(1+t^2)^2\rangle'),m(r'(6,4,9)=r(t)+\lambda v(t),\quad\lambda\ge0'),'The x-component gives λ=3−t and0<t≤3. The y-component requires ln t+3/t=3.',m(r'\frac{d}{dt}(\ln t+3/t)=\frac{t-3}{t^2}<0\quad(0<t<3)'),'The solution on this interval is unique and equals t=1. Since r(1)=(4,2,5),v(1)=(1,1,2), coasting forλ=2 reaches(6,4,9), satisfying z too.'],m('t=1'))
add(46,'로켓의속도v와질량m이m dv/dt=(dm/dt)v_e를만족하고상대배기속도벡터v_e는일정하다. (a)로켓방정식을적분하고(b)정지상태에서배기속력의2배에도달하기위해연소할초기질량비를구하라.','A rocket satisfies m dv/dt=(dm/dt)v_e with constant relative exhaust velocity v_e. (a)Integrate the rocket equation;(b)find the fraction of initial mass burned to reach twice the exhaust speed from rest.',[m(r'dv=\frac{dm}{m}v_e\Rightarrow v(t)-v(0)=\ln\frac{m(t)}{m(0)}v_e'),'(b)배기가비행반대방향이므로증가한속력은|v_e|ln(m₀/m)이다.',m(r'2|v_e|=|v_e|\ln(m_0/m)\Rightarrow m/m_0=e^{-2}')],[m(r'dv=\frac{dm}{m}v_e\Rightarrow v(t)-v(0)=\ln\frac{m(t)}{m(0)}v_e'),'(b)Exhaust points opposite the flight direction, so the speed gain is |v_e|ln(m₀/m).',m(r'2|v_e|=|v_e|\ln(m_0/m)\Rightarrow m/m_0=e^{-2}')],m(r'(a)\ v(t)=v(0)-\ln\frac{m(0)}{m(t)}v_e;\quad(b)\ 1-e^{-2}\approx0.8647=86.47\%'),parts=list('ab'))
assert sorted(b.E)==list(range(1,47));b.save();Path(__file__).with_name('s13-4-report.json').write_text(json.dumps({'section':'13.4','count':46,'sourcePdfPages':[998,999,1000],'checks':checks,'status':'passed'},indent=2)+'\n');print('Saved46;',len(checks),'checks')
