from calc1_core import *
D=CalcDoc('2.5',[162,163,164],lambda n:162 if n<=64 else 163 if n<=80 else 164)
x,u=s.symbols('x u',real=True);R,N,P=s.symbols('r n p',real=True)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('연쇄법칙','The chain rule'),st,('안쪽에서 바깥쪽으로 합성을 추적하고 각 층의 미분을 곱한다.곱과 몫은 별도의 법칙도 함께 쓴다.','Trace the composition from inner to outer layers and multiply their derivatives.Combine this with product or quotient rules when needed.'),steps,ans,check,parts)
def same(q):return(d(q),d(q))
def tx(f,var='x'):return tex(f).replace('x',var)
def plots(n,fs,bounds,segs=None,title='Blue: function; red: derivative'):
 cs=[]
 for f,c in zip(fs,['#1d4ed8','#dc2626','#15803d']):
  for lo,hi in segs or[(bounds[0],bounds[1])]:cs.append({'points':samples(s.lambdify(x,f,'math'),lo,hi,600),'color':c})
 D.fig(n,[panel(title,bounds,cs)])
for n,inner,outer in[(1,5-x**4,u**3),(2,x**3+2,s.sqrt(u)),(3,s.cos(x),s.sin(u)),(4,x*x,s.tan(u)),(5,s.sin(x),s.sqrt(u)),(6,s.sqrt(x),s.sin(u))]:
 f=outer.subs(u,inner);de=s.diff(outer,u).subs(u,inner)*s.diff(inner,x)
 add(n,('함수 '+m('y='+tex(f))+'에서 안쪽 u=g(x),바깥쪽 y=f(u)를 지정하고 dy/dx를 구하라.','For '+m('y='+tex(f))+',identify the inner u=g(x) and outer y=f(u),then find dy/dx.'),[same('u=g(x)='+tex(inner)+r',\quad y=f(u)='+tex(outer)),same(r'\frac{dy}{du}='+tex(s.diff(outer,u))+r',\quad\frac{du}{dx}='+tex(s.diff(inner,x))),same(r'\frac{dy}{dx}=\frac{dy}{du}\frac{du}{dx}')],d(r'\frac{dy}{dx}='+tex(de)),('바깥함수에 안쪽함수를 다시 대입하면 원식이며,직접 기호 미분과 같은 결과이다.','Substituting the inner into the outer recovers the source expression,and direct symbolic differentiation agrees.'))
forms={7:(2*x**3-5*x*x+4)**5,8:(x**5+3*x*x-x)**50,9:s.sqrt(5*x+1),10:(x*x-1)**s.Rational(-1,3),11:(2*x+1)**-2,12:(2*x+1)**-4,13:(s.cos(x)+s.tan(x))**-2,14:(2-s.sin(x))**s.Rational(3,2),15:s.cos(x*x),16:s.cos(x)**2,17:x*(1+x*x)**s.Rational(1,3),18:x*s.sin(s.pi*x),19:(4*x+5)**3*(x*x-2*x+5)**4,20:(1-4*x)**2*s.sqrt(x*x+1),21:(x+1)**s.Rational(2,3)*(2*x*x-1)**3,22:(3*x-1)**4*(2*x+1)**-3,23:s.sqrt(x/(x+1)),24:(x+1/x)**5,25:((x**3-1)/(x**3+1))**8,26:s.sqrt((1+s.sin(x))/(1+s.cos(x))),27:(x*x-1)**3/(2*x+1)**5,28:x*x/s.sqrt(x**3+1),29:s.cos(s.sec(4*x)),30:s.tan(N*x)**2,31:s.cos(x)/s.sqrt(1+s.sin(x)),32:s.tan(x*x*s.sin(x)),33:((1-s.cos(2*x))/(1+s.cos(2*x)))**4,34:x*s.sin(1/x),35:s.sin(x)*s.cos(1-x*x),36:s.sin(x+s.cos(s.sqrt(x))),37:s.tan(s.sqrt(1+x*x)),38:(1+s.cos(x)**2)**3,39:s.sin(x*x+1)**2,40:((x*x-1)**6-3*x)**4,41:s.cos(s.sin(x)**3)**4,42:s.sin(s.cos(x*x))**3,43:s.tan(s.sec(s.cos(x))),44:s.sqrt(x+s.sqrt(x+s.sqrt(x))),45:(2*R*s.sin(R*x)+N)**P,46:s.sin(x+s.tan(x+s.cos(x))),47:s.cos(s.sqrt(s.sin(s.tan(s.pi*x)))),48:(x+(x+s.sin(x)**2)**3)**4}
vars={11:'t',12:'t',13:'t',15:r'\theta',16:r'\theta',17:'v',18:'t',20:'z',21:'t',22:'t',25:'u',26:'t',27:'r',28:'t',30:r'\theta',32:r'\theta',36:'t',37:'t',38:'z',40:'u',43:'t',46:r'\theta'}
for n,f in forms.items():
 v=vars.get(n,'x');der=s.diff(f,x);inner=[];seen=set()
 for node in s.postorder_traversal(f):
  if node.func in[s.sin,s.cos,s.tan,s.sec,s.sqrt]or(node.is_Pow and node.exp!=1):
   arg=node.args[0]
   if arg.has(x)and arg!=x and str(arg)not in seen:inner.append(arg);seen.add(str(arg))
 steps=[('합성된 각 안쪽 식의 미분을 먼저 계산한다.','First calculate derivatives of the inner expressions in the composition.')]
 for j,arg in enumerate(inner):steps.append(same('u_{'+str(j+1)+'}='+tx(arg,v)+r',\quad u_{'+str(j+1)+r'}\prime='+tx(s.diff(arg,x),v)))
 steps.append(('바깥 삼각함수 또는 거듭제곱을 미분한 뒤 위 안쪽 미분을 곱한다.독립 인수들의 곱·몫에는 해당 법칙을 적용한다.','Differentiate each outer trigonometric function or power and multiply by its inner derivative.Apply the product or quotient rule to independent factors.'))
 # Atomic linear inner expressions sometimes have no nontrivial listed layer.
 if not inner:steps.append(same(r'f\prime='+tx(der,v)))
 extra=(' 홀수근은 실수근으로 해석한다.',' Odd roots are interpreted as real roots.')if n in[10,17,21]else('','')
 add(n,('함수 '+m('y='+tx(f,v))+'를 '+m(v)+'에 관해 미분하라.','Differentiate '+m('y='+tx(f,v))+' with respect to '+m(v)+'.'),steps,d(r'\frac{dy}{d'+v+'}='+tx(der,v)),('직접 기호 미분과 인수별 연쇄법칙 결과를 대조했다.원래 분모·근호·삼각함수의 정의역을 유지하고 유한 도함수가 존재하는 곳에서 식을 사용한다.'+extra[0],'Compared direct symbolic differentiation with the factorwise chain calculation.Preserve the original denominator,radical,and trigonometric restrictions and apply the formula where the derivative is finite.'+extra[1]))
for n,f in[(49,s.cos(s.sin(3*x))),(50,(1+s.sqrt(x))**3),(51,s.sqrt(s.cos(x))),(52,4*x/s.sqrt(x+1))]:
 de=s.diff(f,x);dde=s.diff(de,x);var=r'\theta'if n==49 else'x'
 add(n,('함수 '+m('y='+tx(f,var))+'의1계·2계 도함수를 구하라.','Find the first and second derivatives of '+m('y='+tx(f,var))+'.'),[same(r'y\prime='+tx(de,var)),('첫 도함수의 곱과 합성 층에 곱 법칙·연쇄법칙을 다시 적용한다.','Apply product and chain rules again to the factors and compositions in the first derivative.'),same(r'y\prime\prime='+tx(dde,var))],d(r'y\prime='+tx(de,var)+r',\quad y\prime\prime='+tx(dde,var)),('원식의2회 독립 기호 미분과 일치한다.근호가 분모가 되는 곳에서는 양의 근호 조건을 유지한다.','Agrees with twice-repeated independent symbolic differentiation;retain positive-radical restrictions where roots occur in denominators.'))
for n,f,at,val in[(53,(3*x-1)**-6,0,1),(54,s.sqrt(1+x**3),2,3),(55,s.sin(s.sin(x)),s.pi,0),(56,s.sin(x)**2*s.cos(x),s.pi/2,0),(57,s.tan(s.pi*x*x/4),1,1),(58,x/s.sqrt(2-x*x),1,1)]:
 de=s.diff(f,x);slope=s.simplify(de.subs(x,at));line=s.expand(val+slope*(x-at));shown=s.Abs(x)/s.sqrt(2-x*x)if n==58 else f
 add(n,('곡선 '+m('y='+tex(shown))+'의 점 '+m('('+tex(at)+','+tex(val)+')')+'에서 '+('(a)접선식을 구하고(b)곡선과 접선을 함께 그려라.'if n>=57 else'접선식을 구하라.'),'For '+m('y='+tex(shown))+' at '+m('('+tex(at)+','+tex(val)+')')+', '+('(a)find the tangent and(b)plot it with the curve.'if n>=57 else'find the tangent.')),[('접점 부근의 함수를 연쇄법칙으로 미분한다.'+('58은 x=1 부근에서 |x|=x이다.'if n==58 else''),'Differentiate locally using the chain rule.'+('In58,|x|=x near1.'if n==58 else'')),same(r'y\prime='+tex(de)+r',\quad m='+tex(slope)),same('y-('+tex(val)+')=('+tex(slope)+')(x-('+tex(at)+'))')],d('y='+tex(line)),('접점이 원곡선과 접선에 모두 들어맞고 직선 기울기는 국소 도함수 값과 일치한다.','The point lies on both curve and line,and the slope equals the local derivative.'),list('ab')if n>=57 else())
 if n>=57:plots(n,[shown,line],(-1.35,1.35,-5,5)if n==57 else(-1.4,1.4,-2,6),title='Blue: curve; red: tangent')
for n,f,bounds in[(59,x*s.sqrt(2-x*x),(-1.413,1.413,-4,4)),(60,s.sin(x+s.sin(2*x)),(0,math.pi,-3,3))]:
 de=s.diff(f,x)
 add(n,('함수 '+m('f(x)='+tex(f))+'에 대해 '+('(a)도함수를 구하고(b)함수·도함수 그래프로 타당성을 설명하라.'if n==59 else'0≤x≤π에서(a)함수 그래프의 기울기로 f′를 예상하고(b)계산식과 그래프를 비교하라.'),'For '+m('f(x)='+tex(f))+', '+('(a)find f′ and(b)compare function and derivative graphs.'if n==59 else'on0≤x≤π,(a)estimate f′ from the function’s slopes and(b)compare with the calculated derivative and graph.')),[('곱 법칙과 근호의 연쇄법칙을 적용한다.'if n==59 else'안쪽 u=x+sin2x의 도함수1+2cos2x를 바깥 cos u에 곱한다.','Apply the product rule and the radical chain rule.'if n==59 else'Multiply the outer derivative cos u by the inner derivative1+2cos2x.'),same(r'f\prime='+tex(s.simplify(de))),('도함수0은 원함수의 수평 접선이며,양·음 부호는 원함수의 증가·감소와 일치한다.','Derivative zeros correspond to horizontal tangents,and signs agree with increase/decrease of the function.')],d(r'f\prime='+tex(s.simplify(de))),('정확한 미분식으로 도해를 생성했고 원함수의 기울기 변화와 대조했다.'+('59의 유한 도함수 식은 |x|<√2에서 성립한다.'if n==59 else''),'Generated the plots from exact derivative formulas and compared against function slopes.'+('The finite derivative in59 requires|x|<√2.'if n==59 else'')),list('ab'))
 plots(n,[f,de],bounds)
add(61,('f(x)=2sin x+sin²x의 수평 접선 접점을 모두 구하라.','Find all horizontal-tangent points of f(x)=2sin x+sin²x.'),[same(r'f\prime=2\cos x(1+\sin x)=0'),('sin x=−1의 해도 cos x=0에 포함되므로 한 주기에 두 위치만 있다.','The solutions of sin x=−1 are already included among cos x=0,giving two positions per period.')],d(r'(\pi/2+2k\pi,3),\quad(3\pi/2+2k\pi,-1),\quad k\in\mathbb Z'),('sin x=±1을 원식에 대입하여 높이3,−1을 확인했고 중복 해를 제거했다.','Substituting sin x=±1 gives heights3,−1;duplicate roots were removed.'))
add(62,('곡선 y=√(1+2x)의 접선이 직선6x+2y=1과 수직인 접점을 구하라.','Find the point where the tangent to y=√(1+2x) is perpendicular to6x+2y=1.'),[same(r'm_{\rm line}=-3,\quad m_T=1/3'),same(r'y\prime=1/\sqrt{1+2x}=1/3\Rightarrow x=4,\ y=3')],d('(4,3)'),('접선 기울기1/3과 주어진 직선 기울기−3의 곱은−1이다.','The tangent slope1/3 times the line slope−3 equals−1.'))
add(63,('F=f∘g이며 f(−2)=8,f′(−2)=4,f′(5)=3,g(5)=−2,g′(5)=6이다.F′(5)를 구하라.','For F=f∘g,given f(−2)=8,f′(−2)=4,f′(5)=3,g(5)=−2,g′(5)=6,find F′(5).'),[same(r'F\prime(5)=f\prime(g(5))g\prime(5)=f\prime(-2)6=4(6)=24')],d('24'),('바깥 미분의 입력은5가 아닌 g(5)=−2이므로 f′(5)=3은 사용하지 않는다.','The outer derivative is evaluated at g(5)=−2 rather than5;f′(5)=3 is not used.'))
add(64,('h(x)=√(4+3f(x)),f(1)=7,f′(1)=4일 때 h′(1)를 구하라.','For h(x)=√(4+3f(x)),f(1)=7,f′(1)=4,find h′(1).'),[same(r'h\prime(x)=\frac{3f\prime(x)}{2\sqrt{4+3f(x)}}'),same(r'h\prime(1)=\frac{12}{2\sqrt{25}}=6/5')],d('6/5'),('안쪽 값25의 제곱근5와 안쪽 변화율12를 별도로 계산했다.','Computed the square root of the inner value25 as5 and the inner rate as12 separately.'))
for n,st,eqs in[(65,('표의(x,f,g,f′,g′)는(1,3,2,4,6),(2,1,8,5,7),(3,7,2,7,9)이다.(a)h=f∘g의 h′(1),(b)H=g∘f의 H′(1)를 구하라.','The table(x,f,g,f′,g′) has rows(1,3,2,4,6),(2,1,8,5,7),(3,7,2,7,9).Find(a)h′(1)for h=f∘g and(b)H′(1)for H=g∘f.'),[r'h\prime(1)=f\prime(2)g\prime(1)=5(6)=30',r'H\prime(1)=g\prime(3)f\prime(1)=9(4)=36']), (66,('65번 표의(x,f,g,f′,g′)=(1,3,2,4,6),(2,1,8,5,7),(3,7,2,7,9)를 사용하여(a)F=f∘f의 F′(2),(b)G=g∘g의 G′(3)를 구하라.','Use the table(x,f,g,f′,g′)=(1,3,2,4,6),(2,1,8,5,7),(3,7,2,7,9)to find(a)F′(2)for F=f∘f and(b)G′(3)for G=g∘g.'),[r'F\prime(2)=f\prime(f(2))f\prime(2)=f\prime(1)5=20',r'G\prime(3)=g\prime(g(3))g\prime(3)=g\prime(2)9=63'])]:
 add(n,st,[same(q)for q in eqs],d(r'\text{(a) }'+('30'if n==65 else'20')+r';\quad\text{(b) }'+('36'if n==65 else'63')),('안쪽 함수값을 먼저 읽어 바깥 미분의 표 행을 선택했다.','Read each inner function value first to select the correct row for the outer derivative.'),list('ab'))
add(67,('원본의 빨간 f는(−1,1),(0,0),(2,4) 이후 기울기−1/4의 직선이고,파란 g는(−1,2),(0,5),(3,2),(7,4)를 잇는다.u=f∘g,v=g∘f,w=g∘g에 대해(a)u′(1),(b)v′(1),(c)w′(1)를 구하고 존재 여부를 설명하라.','In the source,red f joins(−1,1),(0,0),(2,4),then follows slope−1/4;blue g joins(−1,2),(0,5),(3,2),(7,4).For u=f∘g,v=g∘f,w=g∘g,find(a)u′(1),(b)v′(1),(c)w′(1),explaining existence.'),[('f(1)=2,f′(1)=2,g(1)=4,g′(1)=−1이다.안쪽 결과2와4는 필요한 바깥 함수의 모서리가 아니다.','We read f(1)=2,f′(1)=2,g(1)=4,g′(1)=−1.The inner outputs2 and4 are not corners of the required outer functions.'),same(r'u\prime(1)=f\prime(4)g\prime(1)=(-1/4)(-1)=1/4'),same(r'v\prime(1)=g\prime(2)f\prime(1)=(-1)(2)=-2'),same(r'w\prime(1)=g\prime(4)g\prime(1)=(1/2)(-1)=-1/2')],d(r'1/4,\quad-2,\quad-1/2'),('각 적용점에서 좌우가 같은 직선 조각 안에 있어 세 미분값 모두 존재한다.','Each evaluation lies within one straight segment on both sides,so all three derivatives exist.'),list('abc'))
D.fig(67,[panel('Red:f;blue:g(source grid)',(-1,7,-1,6),[{'points':[(-1,1),(0,0),(2,4),(7,2.75)],'color':'#dc2626'},{'points':[(-1,2),(0,5),(3,2),(7,4)],'color':'#1d4ed8'}],xticks=list(range(-1,8)),yticks=list(range(-1,7)))])
add(68,('원본의 매끈한 f 그래프를 이용하여 (a)h(x)=f(f(x))의 h′(2), (b)g(x)=f(x²)의 g′(2)를 추정하라. 그래프에서 f(2)≈1이고 x=1,2,4의 접선 기울기는 각각 약−1,−1,2이다.','Use the source smooth graph of f to estimate (a)h′(2) for h(x)=f(f(x)) and (b)g′(2) for g(x)=f(x²). The graph gives f(2)≈1 and tangent slopes near−1,−1,2 at x=1,2,4 respectively.'),[same(r'h\prime(2)=f\prime(f(2))f\prime(2)\approx f\prime(1)(-1)\approx1'),same(r'g\prime(2)=f\prime(2^2)\cdot2(2)=4f\prime(4)\approx8')],d(r'\text{(a) }h\prime(2)\approx1;\qquad\text{(b) }g\prime(2)\approx8'),('원본 격자의 접선 기울기를 두 사람이 독립 판독했다. 정확한 함수식은 주어지지 않아 결과는 그래프 해상도에 따른 근삿값이다.','Two independent readings of the source grid agree on the tangent slopes. No exact formula is supplied, so the answers are graphical estimates limited by the image resolution.'),list('ab'))
add(69,('g(x)=√f(x)이고 원본 f 그래프의 x=3 접선은(0,4),(6,0)을 지나는 직선이며 접점 높이는2이다.g′(3)를 구하라.','For g(x)=√f(x),the source tangent to f at x=3 is the line through(0,4),(6,0),and the contact height is2.Find g′(3).'),[same(r'f(3)=2,\quad f\prime(3)=(0-4)/(6-0)=-2/3'),same(r'g\prime(3)=\frac{f\prime(3)}{2\sqrt{f(3)}}=-\frac1{3\sqrt2}=-\frac{\sqrt2}6')],d(r'-\sqrt2/6'),('접선 기울기를−2/3으로 읽고 근호의 입력값2와 구별했다.','Read the tangent slope as−2/3 and distinguished it from the radical input2.'))
add(70,('미분 가능한 f와 실수 상수α에 대해(a)F(x)=f(x^α),(b)G(x)=[f(x)]^α의 도함수를 구하라.','For differentiable f and real constantα,find derivatives of(a)F(x)=f(x^α),(b)G(x)=[f(x)]^α.'),[('(a)는 안쪽 x^α의 미분,(b)는 바깥 u^α의 미분을 적용한다.','In(a)differentiate the inner x^α;in(b)differentiate the outer u^α.'),same(r'F\prime(x)=\alpha x^{\alpha-1}f\prime(x^\alpha)'),same(r'G\prime(x)=\alpha[f(x)]^{\alpha-1}f\prime(x)')],d(r'F\prime=\alpha x^{\alpha-1}f\prime(x^\alpha),\quad G\prime=\alpha[f(x)]^{\alpha-1}f\prime(x)'),('실수 거듭제곱이 정의되고 미분 가능한 곳에서 성립한다.임의 실수α에는 각각 x>0,f(x)>0이 충분하며 특수 정수 지수는 더 넓은 정의역을 가질 수 있다.','Valid where the real powers are defined and differentiable.For arbitrary realα,x>0 and f(x)>0 respectively suffice;special integer powers may allow larger domains.'),list('ab'))
add(71,('r=f∘g∘h,h(1)=2,g(2)=3,h′(1)=4,g′(2)=5,f′(3)=6일 때 r′(1)를 구하라.','For r=f∘g∘h,given h(1)=2,g(2)=3,h′(1)=4,g′(2)=5,f′(3)=6,find r′(1).'),[same(r'r\prime(1)=f\prime(g(h(1)))g\prime(h(1))h\prime(1)=6(5)(4)=120')],d('120'),('입력 경로1→2→3에 맞춰 세 미분값을 읽었다.','Read the three derivatives along the input path1→2→3.'))
add(72,('두 번 미분 가능한 g에 대해 f(x)=xg(x²)의 f″를 g,g′,g″로 나타내라.','For twice-differentiable g,express f″ for f(x)=xg(x²) in terms of g,g′,g″.'),[same(r'f\prime=g(x^2)+2x^2g\prime(x^2)'),same(r'f\prime\prime=2xg\prime(x^2)+4xg\prime(x^2)+4x^3g\prime\prime(x^2)')],d(r'f\prime\prime=6xg\prime(x^2)+4x^3g\prime\prime(x^2)'),('각 g 또는 g′를 미분할 때 안쪽2x가 한 번씩 곱해지는지 확인했다.','Checked the inner factor2x each time g or g′ was differentiated.'))
add(73,('F(x)=f(3f(4f(x))),f(0)=0,f′(0)=2일 때 F′(0)를 구하라.','For F(x)=f(3f(4f(x))),f(0)=0,f′(0)=2,find F′(0).'),[same(r'F\prime=f\prime(3f(4f(x)))\,3f\prime(4f(x))\,4f\prime(x)'),('0에서 모든 안쪽 함수값은0이므로 각 f′의 값은2이다.','At zero every inner function value is zero,so each f′ contributes2.')],d(r'F\prime(0)=2\cdot3\cdot2\cdot4\cdot2=96'),('상수배3,4를 빠뜨리지 않고 세 층의 미분값2³과 곱했다.','Included both constants3,4 and all three derivative factors2³.'))
add(74,('F(x)=f(xf(xf(x))),f(1)=2,f(2)=3,f′(1)=4,f′(2)=5,f′(3)=6일 때 F′(1)를 구하라.','For F(x)=f(xf(xf(x))),given f(1)=2,f(2)=3,f′(1)=4,f′(2)=5,f′(3)=6,find F′(1).'),[same(r'u=xf(x),\quad u(1)=2,\quad u\prime(1)=2+4=6'),same(r'v=xf(u),\quad v(1)=3,\quad v\prime(1)=3+5(6)=33'),same(r'F\prime(1)=f\prime(v(1))v\prime(1)=6(33)=198')],d('198'),('각 x가 곱해진 두 단계에서는 연쇄법칙만 쓰지 않고 곱 법칙의 두 항을 모두 포함했다.','At both stages involving multiplication by x,included both product-rule terms as well as the chain factor.'))
add(75,('cos2x의103계 도함수를 구하라.','Find the103rd derivative of cos2x.'),[same(r'\cos2x\to-2\sin2x\to-4\cos2x\to8\sin2x\to16\cos2x'),same(r'103\equiv3\pmod4')],d(r'2^{103}\sin2x'),('미분마다 안쪽 계수2가 곱해져 계수2¹⁰³을 얻고 삼각함수 부호는4단계 주기로 확인했다.','Each differentiation multiplies by the inner factor2;the four-step cycle checks the sign and trigonometric function.'))
add(76,('x sinπx의35계 도함수를 구하라.','Find the35th derivative of x sinπx.'),[same(r'D^n(x\sin\pi x)=x\pi^n\sin(\pi x+n\pi/2)+n\pi^{n-1}\sin(\pi x+(n-1)\pi/2)'),same(r'35\equiv3\pmod4,\quad34\equiv2\pmod4')],d(r'-\pi^{35}x\cos\pi x-35\pi^{34}\sin\pi x'),('x의2계 이상 도함수가0이므로 고계 곱 법칙에서 정확히 두 항만 남는다.','Only two terms remain in the higher product rule because derivatives of x of order2 and above vanish.'))
add(77,('진동하는 줄의 변위 s(t)=10+(1/4)sin(10πt)(cm),t는초이다.속도를 구하라.','For string displacement s(t)=10+(1/4)sin(10πt) cm,with t in seconds,find velocity.'),[same(r'v(t)=\tfrac14\cos(10\pi t)\cdot10\pi')],d(r'v(t)=\frac{5\pi}2\cos(10\pi t)\ {\rm cm/s}'),('상수 평형 위치10은 미분하면0이며 진폭1/4에 각진동수10π가 곱해진다.','The constant equilibrium level10 differentiates to0;amplitude1/4 is multiplied by angular frequency10π.'))
add(78,('단순 조화운동 s=Acos(ωt+δ)에 대해(a)속도,(b)속도가0인 시각을 구하라.','For simple harmonic motion s=Acos(ωt+δ),find(a)velocity and(b)when it is zero.'),[same(r'v(t)=-A\omega\sin(\omega t+\delta)'),same(r'\sin(\omega t+\delta)=0\Rightarrow t=\frac{k\pi-\delta}\omega')],d(r'v=-A\omega\sin(\omega t+\delta);\quad t=(k\pi-\delta)/\omega,\ k\in\mathbb Z\ (A\omega\ne0)'),('물리적 시간이라면 t≥0만 고른다.Aω=0인 퇴화 경우에는 모든 시각에서 v=0이다.','For physical time retain t≥0.If Aω=0,the degenerate motion has v=0 at every time.'),list('ab'))
rate79=s.Rational('0.35')*2*s.pi/s.Rational('5.4');one79=rate79*s.cos(2*s.pi/s.Rational('5.4'))
add(79,('변광성 밝기 모형 B(t)=4+0.35sin(2πt/5.4),t는일이다.(a)밝기 변화율,(b)1일 후 증가율을 소수둘째 자리까지 구하라.','For variable-star brightness B(t)=4+0.35sin(2πt/5.4),with t in days,find(a)the rate of change and(b)the rate after1day to two decimals.'),[same(r'B\prime(t)=\frac{0.7\pi}{5.4}\cos(2\pi t/5.4)'),same(r'B\prime(1)='+tex(s.N(one79,8)))],('약0.16 밝기단위/일로 증가한다.','Increasing at about0.16 brightness units/day.'),('양의 코사인 값이므로 증가율이 양수이고 주기5.4일의 안쪽 각속도2π/5.4를 포함했다.','The cosine is positive at1day;included the inner angular rate2π/5.4 for the5.4-day period.'),list('ab'))
r80=2.8*2*math.pi/365;r141=r80*math.cos(2*math.pi*61/365)
add(80,('Philadelphia 낮 길이 L(t)=12+2.8sin[(2π/365)(t−80)](시간)모형을 사용하여3월21일(t=80)과5월21일(t=141)의 증가율을 비교하라.','Use the Philadelphia daylight model L(t)=12+2.8sin[(2π/365)(t−80)] hours to compare growth rates on March21(t=80) and May21(t=141).'),[same(r'L\prime(t)=\frac{5.6\pi}{365}\cos\left(\frac{2\pi}{365}(t-80)\right)'),(f'L′(80)≈{r80:.6f}시간/일={r80*60:.3f}분/일; L′(141)≈{r141:.6f}시간/일={r141*60:.3f}분/일.',f'L′(80)≈{r80:.6f}hours/day={r80*60:.3f}minutes/day; L′(141)≈{r141:.6f}hours/day={r141*60:.3f}minutes/day.')],('두 날 모두 증가하며3월21일은5월21일의 약2배 속도로 증가한다.','Daylight increases on both dates,about twice as fast on March21 as on May21.'),('시간/일에서 분/일로 바꿀 때60을 곱했고 두 코사인 값이 모두 양수임을 확인했다.','Multiplied by60 to convert hours/day to minutes/day and checked both cosines are positive.'))
add(81,('직선운동의 변위s(t),속도v(t),가속도a(t)에 대해 a=v·dv/ds를 보이고 dv/dt와 dv/ds의 뜻을 구별하라.','For displacement s(t),velocity v(t),and acceleration a(t),show a=v·dv/ds and distinguish dv/dt from dv/ds.'),[('속도를 위치의 미분 가능한 함수 v=V(s(t))로 국소 표현할 수 있는 구간에서 연쇄법칙을 쓴다.','On an interval where velocity can locally be expressed as a differentiable function v=V(s(t)),apply the chain rule.'),same(r'a=\frac{dv}{dt}=\frac{dv}{ds}\frac{ds}{dt}=v\frac{dv}{ds}'),('dv/dt는 시간에 따른 속도 변화율(가속도),dv/ds는 위치 변화에 따른 속도 변화율이다.방향 전환점에서는 위치로 나타낸 속도 함수가 미분 불가능할 수 있어 이 표현의 적용을 확인해야 한다.','dv/dt is velocity change per time(acceleration);dv/ds is velocity change per displacement.At a turning point the velocity-as-position function may fail to be differentiable,so the representation must be checked.')],d(r'a=v\,dv/ds'),('단위는 (길이/시간)×(1/시간)=길이/시간²로 가속도와 같다.','Units are(length/time)×(1/time)=length/time²,matching acceleration.'))
add(82,('구형 기상풍선의 부피V(t),반지름r(t)에 대해(a)dV/dr와 dV/dt의 뜻,(b)dV/dt를 dr/dt로 표현하라.','For a spherical balloon with volume V(t) and radius r(t),(a)interpret dV/dr and dV/dt,and(b)express dV/dt in terms of dr/dt.'),[same(r'V=\frac43\pi r^3,\quad\frac{dV}{dr}=4\pi r^2'),('dV/dr는 반지름 증가당 부피 변화,dV/dt는 시간 증가당 부피 변화이다.','dV/dr measures volume change per radius change;dV/dt measures volume change per time.'),same(r'\frac{dV}{dt}=4\pi r^2\frac{dr}{dt}')],d(r'dV/dt=4\pi r^2\,dr/dt'),('면적4πr²에 반지름 증가속도를 곱하면 부피/시간 단위가 된다.','Surface area4πr² times radius growth rate has units volume/time.'),list('ab'))
add(83,('연쇄법칙으로(a)짝함수의 도함수는 홀함수,(b)홀함수의 도함수는 짝함수임을 증명하라.','Use the chain rule to prove(a)the derivative of an even function is odd and(b)the derivative of an odd function is even.'),[same(r'\text{(a) }f(-x)=f(x)\Rightarrow-f\prime(-x)=f\prime(x)\Rightarrow f\prime(-x)=-f\prime(x)'),same(r'\text{(b) }f(-x)=-f(x)\Rightarrow-f\prime(-x)=-f\prime(x)\Rightarrow f\prime(-x)=f\prime(x)')],('(a)홀함수;(b)짝함수.','(a)Odd;(b)even.'),('안쪽−x를 미분하여 나오는−1을 양쪽 경우 모두 포함했다.','Included the inner derivative−1 from−x in both cases.'),list('ab'))
add(84,('f/g=f·g⁻¹로 써서 곱 법칙과 연쇄법칙으로 몫 법칙을 증명하라.','Write f/g=f·g⁻¹ and prove the quotient rule using product and chain rules.'),[same(r'(fg^{-1})\prime=f\prime g^{-1}+f(-g^{-2}g\prime)=\frac{gf\prime-fg\prime}{g^2}')],d(r'(f/g)\prime=\frac{gf\prime-fg\prime}{g^2}\quad(g\ne0)'),('역수의 바깥 미분−u⁻²와 안쪽 미분g′를 곱하여 유도했다.','Derived the reciprocal factor using outer derivative−u⁻² times inner derivative g′.'))
add(85,('θ를 도 단위로 잴 때 d(sinθ)/dθ=(π/180)cosθ임을 연쇄법칙으로 보여라.','Use the chain rule to show that,when θ is measured in degrees,d(sinθ)/dθ=(π/180)cosθ.'),[('도 단위 사인은 라디안 함수로 S(θ)=sin(πθ/180)이다.','The degree-based sine is S(θ)=sin(πθ/180) using the radian sine.'),same(r'S\prime(\theta)=\frac\pi{180}\cos(\pi\theta/180)')],('도 단위 표기로 S′(θ)=(π/180)cosθ.','In degree notation,S′(θ)=(π/180)cosθ.'),('1도 변화는π/180라디안 변화이므로 같은 접선 변화율에 그 환산계수가 필요하다.','A one-degree change equalsπ/180radians,so the conversion factor is required in the rate.'))
add(86,('(a)|x|=√x²에 연쇄법칙을 적용해 도함수를 구하라.(b)f=|sin x|,(c)g=sin|x|의 도함수·그래프와 미분 불가능한 곳을 구하라.','(a)Differentiate|x|=√x² with the chain rule.(b)For f=|sin x| and(c)g=sin|x|,find derivatives,plot each function and derivative,and locate nondifferentiability.'),[same(r'\text{(a) }\frac d{dx}|x|=\frac{2x}{2\sqrt{x^2}}=\frac x{|x|}\quad(x\ne0)'),same(r'\text{(b) }f\prime=\frac{\sin x}{|\sin x|}\cos x\quad(x\notin\pi\mathbb Z)'),('각 kπ에서 |sin x|는 |x−kπ|처럼 뾰족하므로 미분 불가능하다.','At each kπ,|sin x| behaves like|x−kπ| and has a corner.'),same(r'\text{(c) }g\prime=\cos|x|\frac x{|x|}=\begin{cases}-\cos x&x<0\\\cos x&x>0\end{cases}'),('g는0에서 좌우 기울기−1,1이 달라 미분 불가능하고 다른 곳에서는 매끈하다.','At0,g has unequal slopes−1 and1;elsewhere it is smooth.')],('(b)미분 불가:x=kπ,k∈ℤ;(c)미분 불가:x=0.','(b)Nondifferentiable at x=kπ,k∈ℤ;(c)only at x=0.'),('두 원함수는0 부근에서는 같지만 |x|가π보다 클 때 부호가 달라질 수 있어 전체 그래프를 구별했다.','The functions agree near0 but may have different signs beyond|x|=π,so their global graphs were distinguished.'),list('abc'))
lo=-2*math.pi;hi=2*math.pi;seg=[(k*math.pi+.0001,(k+1)*math.pi-.0001)for k in range(-2,2)]
D.fig(86,[panel('f=abs(sin x)',(lo,hi,-1.2,1.2),[samples(lambda z:abs(math.sin(z)),lo,hi,1000)]),panel('f derivative; all integer*pi excluded',(lo,hi,-1.2,1.2),[samples(lambda z:math.copysign(1,math.sin(z))*math.cos(z),aa,bb,250)for aa,bb in seg],[(k*math.pi,y,'open')for k in range(-2,3)for y in[-1,1]]),panel('g=sin(abs x)',(lo,hi,-1.2,1.2),[samples(lambda z:math.sin(abs(z)),lo,hi,1000)]),panel('g derivative; only0 excluded',(lo,hi,-1.2,1.2),[samples(lambda z:-math.cos(z),lo,-.0001),samples(math.cos,.0001,hi)],[(0,-1,'open'),(0,1,'open')])])
add(87,('F=f∘g∘h에 대해 F′(x)=f′(g(h(x)))g′(h(x))h′(x)를 연쇄법칙으로 증명하라.','Prove F′(x)=f′(g(h(x)))g′(h(x))h′(x) for F=f∘g∘h using the chain rule.'),[same(r'u(x)=g(h(x))\Rightarrow u\prime=g\prime(h(x))h\prime(x)'),same(r'F\prime=f\prime(u(x))u\prime(x)=f\prime(g(h(x)))g\prime(h(x))h\prime(x)')],d(r'F\prime(x)=f\prime(g(h(x)))g\prime(h(x))h\prime(x)'),('각 바깥 미분을 해당 안쪽 함수값에서 평가하도록 입력 순서를 유지했다.','Preserved the evaluation order so each outer derivative is evaluated at its inner function value.'))
add(88,('두 번 미분 가능한 f,g의 합성F=f∘g에 대해 F″=f″(g)(g′)²+f′(g)g″를 증명하라.','For twice-differentiable f,g and F=f∘g,prove F″=f″(g)(g′)²+f′(g)g″.'),[same(r'F\prime=f\prime(g(x))g\prime(x)'),same(r'F\prime\prime=[f\prime(g(x))]\prime g\prime(x)+f\prime(g(x))g\prime\prime(x)'),same(r'[f\prime(g(x))]\prime=f\prime\prime(g(x))g\prime(x)')],d(r'F\prime\prime(x)=f\prime\prime(g(x))[g\prime(x)]^2+f\prime(g(x))g\prime\prime(x)'),('곱의 첫 항에 두 g′가 생기는 이유와 둘째 항 g″를 모두 확인했다.','Checked why the first product term contains two g′ factors and why the second contains g″.'))

normalize_prose_inequalities(D)
D.save(88)
