"""Every general-region exercise, both orders and original diagrams."""
from core_15 import *
from planar_15 import *
from plot_15 import solid
import mpmath as mp
x,y,r,t,v,w=s.symbols('x y r theta v w',real=True);a,b,R=s.symbols('a b R',positive=True)
D=Doc('15.2',[1097,1098,1099,1100],lambda n:1097 if n<=15 else (1098 if n<=46 else (1099 if n<=76 else 1100)))
def add(n,st,steps,ans,parts=(),check=('경계 교점과 적분구간을 원식에 대입하고 계산을 검산했다.','Boundary intersections and integration limits were substituted into the original equations and calculations checked.')):
 return D.add(n,('일반 영역 위 이중적분','Double integrals over general regions'),st,('경계 교점을 구하고 수직 또는 수평 선분으로 영역을 기술한다.','Find intersections and describe the region using vertical or horizontal slices.'),steps,ans,check,parts)
def calc(n,f,lims,st=None,setup=None,parts=()):
 val,ss=D.evaluated(f,lims);ss.insert(0,setup or('반복적분으로 나타내고 안쪽부터 계산한다. '+d('I='+integral(f,lims)),'Write an iterated integral and evaluate from the inside out. '+d('I='+integral(f,lims))))
 add(n,st or('다음 적분을 계산하라. '+d(integral(f,lims)),'Evaluate '+d(integral(f,lims))),ss,d('I='+tex(val)),parts);return val
figures={}
def fig(n,poly,title,labels=(),curves=()):
 name=f's15-2-{n}.svg';planar(name,f'15.2 / {n} - {title}',poly,labels,curves);figures[n]=(name,title)
spec={1:(8*x-2*y,[(y,0,x),(x,1,5)]),2:(x*x*y,[(x,0,y*y),(y,0,2)]),3:(x*s.exp(y**3),[(x,0,y),(y,0,1)]),4:(x*s.sin(y),[(y,0,x),(x,0,s.pi/2)]),5:(s.cos(x**3),[(y,0,x*x),(x,0,1)]),6:(s.sqrt(1+s.exp(v)),[(w,0,s.exp(v)),(v,0,1)])}
for n,(f,ll) in spec.items():calc(n,f,ll)
regions={7:(2*y,[(y,x,3*x-x*x),(x,0,2)],r'x\le y\le3x-x^2,\ 0\le x\le2'),8:(x+y,[(x,y,2-y),(y,0,1)],r'0\le y\le1,\ y\le x\le2-y'),9:(x*y,[(x,y*y,y+2),(y,0,2)],r'0\le y\le2,\ y^2\le x\le y+2'),10:(x,[(y,x*x,6-x),(x,0,2)],r'0\le x\le2,\ x^2\le y\le6-x'),11:(y/(1+x*x),[(y,0,s.sqrt(x)),(x,0,4)],r'0\le x\le4,\ 0\le y\le\sqrt x'),12:(2*x+y,[(x,y-1,1),(y,1,2)],r'1\le y\le2,\ y-1\le x\le1'),13:(s.exp(-y*y),[(x,0,y),(y,0,3)],r'0\le y\le3,\ 0\le x\le y'),14:(y*s.sqrt(x*x-y*y),[(y,0,x),(x,0,2)],r'0\le x\le2,\ 0\le y\le x')}
for n,(f,ll,desc) in regions.items():calc(n,f,ll,('영역 '+m(desc)+'에서 '+m(tex(f))+'를 적분하라.','Integrate '+m(tex(f))+' over '+m(desc)+'.'))
# Type I/II examples have explicit disconnected slices in the other direction.
add(15,('(a)제I형이지만 제II형이 아닌 영역과 (b)제II형이지만 제I형이 아닌 영역을 각각 그려라.','Sketch (a) a Type I region that is not Type II and (b) a Type II region that is not Type I.'),[('(a) '+m(r'D_1=\{-2\le x\le2,\ x^2\le y\le x^2+1\}')+'를 택한다. 모든 수직 단면은 한 구간이나 y=2의 수평 단면은 '+m(r'[-\sqrt2,-1]\cup[1,\sqrt2]')+'로 나뉜다.','(a) Choose '+m(r'D_1=\{-2\le x\le2,\ x^2\le y\le x^2+1\}')+'. Vertical slices are intervals, but the y=2horizontal slice is '+m(r'[-\sqrt2,-1]\cup[1,\sqrt2]')+'.'),('(b) x,y를 교환하여 '+m(r'D_2=\{-2\le y\le2,\ y^2\le x\le y^2+1\}')+'로 잡으면 수평 단면은 한 구간이지만 x=2에서 수직 단면이 나뉜다.','(b) Exchange coordinates: '+m(r'D_2=\{-2\le y\le2,\ y^2\le x\le y^2+1\}')+'. Horizontal slices are intervals, while the x=2vertical slice is disconnected.')],('위의 D1,D2와 자체 도해가 예이다.','D1and D2above, shown in the original diagrams, are examples.'),('a','b'))
pol1=strip_polygon(-2,2,lambda x:x*x,lambda x:x*x+1);pol2=[(y+7,x) for x,y in pol1];fig(15,[pol1,pol2],'Left: Type I only; right: Type II only (shifted)')
add(16,('(a)제I형이면서 제II형인 영역, (b)어느 형도 아닌 영역을 그려라.','Sketch (a) a region that is both Type I and Type II and (b) a region that is neither.'),[('(a) 단위원판은 '+m(r'-1\le x\le1,\ -\sqrt{1-x^2}\le y\le\sqrt{1-x^2}')+'이며 x와 y를 바꿔도 같은 형태다.','(a) The unit disk is '+m(r'-1\le x\le1,\ -\sqrt{1-x^2}\le y\le\sqrt{1-x^2}')+' and has the same form after exchanging x and y.'),('(b) 원고리 '+m(r'1\le x^2+y^2\le4')+'는 x=0과 y=0에서 모두 단면이 두 구간이므로 어느 형도 아니다.','(b) The annulus '+m(r'1\le x^2+y^2\le4')+' has disconnected slices at x=0and y=0, so it is neither type.')],('단위원판; 반지름1과2 사이 원고리.','Unit disk; annulus with radii1and2.'),('a','b'))
fig(16,[polar_polygon(0,2*math.pi,lambda t:0,lambda t:1),[(x+5,y) for x,y in polar_polygon(0,2*math.pi,lambda t:1,lambda t:2)]],'Left: both types; right: neither (shifted for display)')
both={17:(x,[[(y,0,x),(x,0,1)],[(x,y,1),(y,0,1)]],r'y=0,\ y=x,\ x=1'),18:(x*y,[[(y,x*x,3*x),(x,0,3)],[(x,y/3,s.sqrt(y)),(y,0,9)]],r'y=x^2,\ y=3x'),19:(y,[[(x,y*y,y+2),(y,-1,2)],[(y,-s.sqrt(x),s.sqrt(x)),(x,0,1)]],r'y=x-2,\ x=y^2'),20:(y*y*s.exp(x*y),[[(x,0,y),(y,0,4)],[(y,x,4),(x,0,4)]],r'y=x,\ y=4,\ x=0'),21:(s.sin(x)**2,[[(y,0,s.cos(x)),(x,0,s.pi/2)],[(x,0,s.acos(y)),(y,0,1)]],r'y=\cos x,\ y=0,\ x=0,\ 0\le x\le\pi/2'),22:(6*x*x,[[(y,x**3,2*x+4),(x,0,2)],[(x,0,y**s.Rational(1,3)),(y,0,4)]],r'y=x^3,\ y=2x+4,\ x=0')}
for n,(f,orders,desc) in both.items():
 expr1=integral(f,orders[0]);expr2=integral(f,orders[1]);steps=[('경계 교점으로 영역을 두 방식으로 쓴다. '+d('I='+expr1)+' '+d('I='+expr2+(('+'+integral(f,[(y,x-2,s.sqrt(x)),(x,1,4)])) if n==19 else(('+'+integral(f,[(x,(y-4)/2,y**s.Rational(1,3)),(y,4,8)])) if n==22 else ''))),'Boundary intersections give two orders. '+d('I='+expr1)+' '+d('I='+expr2+(('+'+integral(f,[(y,x-2,s.sqrt(x)),(x,1,4)])) if n==19 else(('+'+integral(f,[(x,(y-4)/2,y**s.Rational(1,3)),(y,4,8)])) if n==22 else ''))))]
 val,ss=D.evaluated(f,orders[0]);steps+=ss
 if n<=18:
  v2,ss2=D.evaluated(f,orders[1]);assert s.simplify(val-v2)==0;steps.append(('반대 순서도 직접 계산한다.','Evaluate the opposite order directly as well.'));steps+=ss2
 else:steps.insert(1,('첫 번째 순서는 '+('안쪽 적분이 다항식이다.' if n in(19,22) else('x적분이 단순한 지수 적분이다.' if n==20 else 'y적분이 높이 cosx를 곱하는 것으로 끝난다.')),'The first order is simpler because '+('the inner integral is polynomial.' if n in(19,22) else('the xintegral is elementary exponential integration.' if n==20 else 'the yintegral simply multiplies by cosx.'))))
 add(n,(''+m(tex(f))+'를 경계 '+m(desc)+'의 영역에서 적분하라. 두 순서를 모두 세우고 '+('둘 다 계산하라.' if n<=18 else '쉬운 순서를 택하여 계산하고 이유를 설명하라.'),'Integrate '+m(tex(f))+' over the region bounded by '+m(desc)+'. Set up both orders and '+('evaluate both.' if n<=18 else 'evaluate the easier one, explaining why.')),steps,d('I='+tex(val)))
more={23:(x*s.cos(y),[(y,0,x*x),(x,0,1)],r'y=0,\ y=x^2,\ x=1'),24:(x*x+2*y,[(y,x**3,x),(x,0,1)],r'y=x^3,\ y=x,\ x\ge0'),25:(y*y,[(x,y-1,7-3*y),(y,1,2)],r'\text{triangle }(0,1),(1,2),(4,1)'),26:(x*y,[(y,0,s.sqrt(1-x*x)),(x,0,1)],r'x,y\ge0,\ x^2+y^2\le1'),27:(2*x-y,[(x,-s.sqrt(4-y*y),s.sqrt(4-y*y)),(y,-2,2)],r'x^2+y^2\le4'),28:(y,[(x,y,4-3*y),(y,0,1)],r'\text{triangle }(0,0),(1,1),(4,0)'),29:(1+x*y,[(x,0,y),(y,0,1)],r'0\le x\le y\le1'),30:(x*x+y*y,[(y,0,x*x),(x,0,1)],r'0\le x\le1,\ 0\le y\le x^2'),31:(3*x+2*y,[(y,x*x,s.sqrt(x)),(x,0,1)],r'y=x^2,\ x=y^2'),32:(1+x*x*y*y,[(x,y*y,4),(y,-2,2)],r'x=y^2,\ x=4'),33:(x*y,[(x,1,7-3*y),(y,1,2)],r'\text{triangle }(1,1),(4,1),(1,2)'),34:(x*x+y*y+1,[(y,0,2-x),(x,0,2)],r'x,y\ge0,\ x+y\le2'),35:(4-2*x-y,[(y,0,4-2*x),(x,0,2)],r'x,y,z\ge0,\ 2x+y+z=4'),36:(x,[(y,x,2-x),(x,0,1)],r'z=0,\ z=x,\ y=x,\ x+y=2'),37:(x*x,[(y,x*x,4),(x,-2,2)],r'z=0,\ z=x^2,\ y=x^2,\ y=4'),38:(s.sqrt(4-y*y),[(x,0,2*y),(y,0,2)],r'y^2+z^2=4,\ x=2y,\ x=0,\ z=0\ \text{(first octant)}'),39:(y,[(y,0,s.sqrt(1-x*x)),(x,0,1)],r'x^2+y^2=1,\ z=y,\ x=0,\ z=0\ \text{(first octant)}')}
for n,(f,ll,desc) in more.items():
 if n<=28:st=('영역 '+m(desc)+'에서 '+m(tex(f))+'의 적분을 구하라.','Integrate '+m(tex(f))+' over '+m(desc)+'.')
 else:st=('높이 '+m(tex(f))+', 경계/투영 '+m(desc)+'인 입체의 부피를 '+('(a)적분으로 나타내고 (b)계산하라.' if n in(29,30) else '구하라.'),'Find the volume with height '+m(tex(f))+' and boundary/projection '+m(desc)+('. (a) Set up; (b) evaluate.' if n in(29,30) else '.'))
 calc(n,f,ll,st,('경계 교점과 수직 높이를 사용한다. '+d('I='+integral(f,ll)),'Use the boundary intersections and vertical height. '+d('I='+integral(f,ll))),('a','b') if n in(29,30) else ())
calc(40,4*(R*R-y*y),[(y,-R,R)],('반지름 r인 두 직교 원기둥 '+m(r'x^2+y^2=r^2,\ y^2+z^2=r^2')+'의 공통 부피를 구하라.','Find the common volume of the perpendicular cylinders '+m(r'x^2+y^2=r^2')+' and '+m(r'y^2+z^2=r^2')+'.'),('반지름을 R로 쓰자. y고정 단면은 한 변 '+m(r'2\sqrt{R^2-y^2}')+'인 정사각형이다.','Write the radius as R. At fixed y, the section is a square of side '+m(r'2\sqrt{R^2-y^2}')+'.'))
mp.mp.dps=35
for n,root,lo,hi,f,desc in [(41,mp.findroot(lambda q:q**3+q-3,1.2),lambda q:q**4,lambda q:3*q-q*q,x,r'y=x^4,\ y=3x-x^2'),(42,mp.findroot(lambda q:mp.cos(q)-q,.7),lambda q:q,lambda q:mp.cos(q),x,r'y=x,\ y=\cos x,\ z=0,\ z=x\ \text{(first octant)}')]:
 root=float(root);ff=s.lambdify(x,(x*(3*x-x*x-x**4) if n==41 else x*(s.cos(x)-x)),'mpmath');val=mp.quad(ff,[0,root]);expr=r'\int_0^\alpha x(3x-x^2-x^4)dx' if n==41 else r'\int_0^\alpha x(\cos x-x)dx'
 add(n,('경계 '+m(desc)+'를 그리고 교점을 수치적으로 구하여 '+('영역에서 x의 적분' if n==41 else '부피')+'을 소수 넷째 자리까지 계산하라.','Graph '+m(desc)+', determine the intersection numerically, and evaluate '+('the integral of x over the region' if n==41 else 'the volume')+' to four decimals.'),[('영이 아닌 교점 '+m(r'\alpha')+'는 '+m(r'\alpha^3+\alpha-3=0' if n==41 else r'\cos\alpha=\alpha')+'을 풀어 '+m(f'{root:.12f}')+'이다.','The nonzero intersection '+m(r'\alpha')+' solves '+m(r'\alpha^3+\alpha-3=0' if n==41 else r'\cos\alpha=\alpha')+' and is '+m(f'{root:.12f}')+'.'),('안쪽 y적분은 두 경계의 차이에 x를 곱한다. '+d('I='+expr+'\\approx'+str(val)),'The inner yintegral multiplies x by the difference of boundaries. '+d('I='+expr+'\\approx'+str(val)))],d('I\\approx'+f'{float(val):.4f}'))
 fig(n,[strip_polygon(0,root,lambda q:float(lo(q)),lambda q:float(hi(q)))],('y = x⁴ and y = 3x - x²' if n==41 else 'y = x and y = cos x'))
for n,f,ll,st in [(43,3*x+3*y+8,[(y,x*x-1,1-x*x),(x,-1,1)],(m(r'y=1-x^2,y=x^2-1')+' 사이에서 두 평면 '+m(r'x+y+z=2,\ 2x+2y-z+10=0')+' 사이 부피를 구하라.','Find the volume between '+m(r'x+y+z=2')+' and '+m(r'2x+2y-z+10=0')+' over the region between '+m(r'y=1-x^2,y=x^2-1')+'.')),(44,2-2*y,[(y,x*x,1),(x,-1,1)],(m(r'y=x^2,\ z=3y,\ z=2+y')+'가 둘러싼 부피를 구하라.','Find the volume enclosed by '+m(r'y=x^2,\ z=3y,\ z=2+y')+'.')),(45,3-y,[(y,x*x,1-x*x),(x,-1/s.sqrt(2),1/s.sqrt(2))],(m(r'y=x^2,\ y=1-x^2,\ z=3,\ z=y')+'가 둘러싼 부피를 구하라.','Find the volume enclosed by '+m(r'y=x^2,\ y=1-x^2,\ z=3,\ z=y')+'.')),(46,(r*s.cos(t)+r*s.sin(t)-r*r*s.cos(t)*s.sin(t))*r,[(r,0,2),(t,0,s.pi/2)],('제1팔분공간, 원기둥 '+m(r'x^2+y^2=4')+' 안에서 '+m(r'z=x+y')+'와 '+m('z=xy')+' 사이 부피를 구하라.','Find the first-octant volume inside '+m(r'x^2+y^2=4')+' between '+m(r'z=x+y')+' and '+m('z=xy')+'.'))]:calc(n,f,ll,st,('교선으로 투영영역을 정하고 위 곡면에서 아래를 뺀다. '+d('V='+integral(f,ll)),'Use intersections for the projection and subtract lower surface from upper. '+d('V='+integral(f,ll))))
# Sketching solids: numerical value is not demanded for50, whose antiderivative is non-elementary.
sketches={47:(1-x-y,[(y,0,1-x),(x,0,1)],lambda u,v,w:(u,(1-u)*v,w*(1-u)*(1-v))),48:(1-x,[(y,0,1-x*x),(x,0,1)],lambda u,v,w:(u,(1-u*u)*v,w*(1-u))),49:(s.sqrt(9-x*x),[(x,0,y),(y,0,3)],lambda u,v,w:(3*u*v,3*v,w*math.sqrt(9-9*u*u*v*v))),50:(s.exp(-y),[(y,-1,3-x*x),(x,-2,2)],lambda u,v,w:(-2+4*u,-1+v*(4-(-2+4*u)**2),w*math.exp(1-v*(4-(-2+4*u)**2))))}
for n,(f,ll,fn) in sketches.items():
 desc=',\ '.join(tex(lo)+r'\le '+tex(vv)+r'\le '+tex(hi) for vv,lo,hi in ll)
 add(n,('다음 적분이 부피로 나타내는 입체를 그려라. '+d(integral(f,ll)),'Sketch the solid represented by '+d(integral(f,ll))),[('밑면은 '+m(desc)+'이고 높이는 '+m('z='+tex(f))+'이다.','The base is '+m(desc)+' and the roof is '+m('z='+tex(f))+'.'),('모든 밑면점에서 '+m('0\\le z\\le '+tex(f))+'인 선분을 세운다. 경계 교선과 좌표평면을 포함한 도해를 참조하라.','At each base point draw the segment '+m('0\\le z\\le '+tex(f))+'. The diagram includes the roof, boundary intersections, and base.')],m(desc)+r'; '+m('0\\le z\\le '+tex(f)))
 name=f's15-2-{n}.svg';solid(name,f'15.2 / {n} - Solid',fn,subtitle='The stated base with vertical segments from z = 0 to the roof',resolution=14);figures[n]=(name,'Solid generated from its bounds')
for n,f,ll,desc in [(51,x**3*y**4+x*y*y,[(y,x**3-x,x*x+x),(x,0,2)],r'z=x^3y^4+xy^2,\ y=x^3-x,\ y=x^2+x,\ x\ge0'),(52,(8-3*r*r)*r,[(r,0,1),(t,0,2*s.pi)],r'z=2x^2+y^2,\ z=8-x^2-2y^2,\ x^2+y^2\le1'),(53,(1-r*r)*r,[(r,0,1),(t,0,2*s.pi)],r'z=1-x^2-y^2,\ z=0'),(54,(2*r*s.sin(t)-r*r)*r,[(r,0,2*s.sin(t)),(t,0,s.pi)],r'z=x^2+y^2,\ z=2y')]:calc(n,f,ll,('경계 '+m(desc)+'의 입체 부피를 CAS로 정확히 계산하라.','Use a CAS to find the exact volume with boundaries '+m(desc)+'.'),('높이차와 교점을 이용한다. 원형 투영에서는 극좌표와 야코비안 r을 사용한다. '+d('V='+integral(f,ll)),'Use height differences and intersections; circular projections use polar coordinates and Jacobian r. '+d('V='+integral(f,ll))))
# Reverse order, with a separate, original region diagram for each prompt.
reverse={55:([[(x,0,y),(y,0,1)]],[[(y,x,1),(x,0,1)]],strip_polygon(0,1,lambda x:x,lambda x:1)),56:([[(y,x*x,4),(x,0,2)]],[[(x,0,s.sqrt(y)),(y,0,4)]],strip_polygon(0,2,lambda x:x*x,lambda x:4)),57:([[(y,s.sin(x),1),(x,0,s.pi/2)]],[[(x,0,s.asin(y)),(y,0,1)]],strip_polygon(0,math.pi/2,math.sin,lambda x:1)),58:([[(x,0,s.sqrt(4-y*y)),(y,-2,2)]],[[(y,-s.sqrt(4-x*x),s.sqrt(4-x*x)),(x,0,2)]],polar_polygon(-math.pi/2,math.pi/2,lambda t:0,lambda t:2)),59:([[(y,0,s.log(x)),(x,1,2)]],[[(x,s.exp(y),2),(y,0,s.log(2))]],strip_polygon(1,2,lambda x:0,math.log)),60:([[(y,s.atan(x),s.pi/4),(x,0,1)]],[[(x,0,s.tan(y)),(y,0,s.pi/4)]],strip_polygon(0,1,math.atan,lambda x:math.pi/4))}
for n,(old,new,poly) in reverse.items():
 expr=integral('f(x,y)',old[0]);ne=integral('f(x,y)',new[0]);desc=',\ '.join(tex(lo)+r'\le '+tex(vv)+r'\le '+tex(hi) for vv,lo,hi in new[0]);add(n,('영역을 그리고 적분순서를 바꾸어라. '+d(expr),'Sketch the region and reverse the order in '+d(expr)),[('원래 부등식에서 반대 변수에 대해 경계를 푼다. 새 단면은 '+m(desc)+'이다.','Solve the original boundary inequalities for the other variable. The new slices are '+m(desc)+'.'),('동일한 경계곡선과 끝점을 포함하므로 적분영역은 같다.','Both descriptions have the same boundary curves and endpoints, hence represent the same region.')],d(ne));fig(n,[poly],'Same region, opposite integration order')
revcalc={61:(s.exp(x*x),[(x,3*y,3),(y,0,1)],[(y,0,x/3),(x,0,3)]),62:(s.sqrt(y)*s.sin(y),[(y,x*x,1),(x,0,1)],[(x,0,s.sqrt(y)),(y,0,1)]),63:(s.sqrt(y**3+1),[(y,s.sqrt(x),1),(x,0,1)],[(x,0,y*y),(y,0,1)]),64:(y*s.cos(x**3-1),[(x,y/2,1),(y,0,2)],[(y,0,2*x),(x,0,1)]),65:(s.cos(x)*s.sqrt(1+s.cos(x)**2),[(x,s.asin(y),s.pi/2),(y,0,1)],[(y,0,s.sin(x)),(x,0,s.pi/2)]),66:(s.exp(x**4),[(x,y**s.Rational(1,3),2),(y,0,8)],[(y,0,x**3),(x,0,2)])}
for n,(f,old,new) in revcalc.items():calc(n,f,new,('적분순서를 바꾸어 계산하라. '+d(integral(f,old)),'Reverse the order to evaluate '+d(integral(f,old))),('반대 순서에서 안쪽 적분은 적분함수에 단면 길이를 곱한다. '+d('I='+integral(f,new)),'In the reversed order the inner integral multiplies the integrand by the slice length. '+d('I='+integral(f,new))))
add(67,('정사각형 '+m('[-1,1]^2')+'에서 열린 마름모 '+m(r'|x|+|y|<1')+'를 뺀 영역 D를 제I/II형 조각으로 나누고 '+m(r'\iint_Dx^2dA')+'를 계산하라.','Split the square '+m('[-1,1]^2')+' minus the open diamond '+m(r'|x|+|y|<1')+' into Type I/IIpieces and evaluate '+m(r'\iint_Dx^2dA')+'.'),[('제1사분면의 조각은 '+m(r'0\le x\le1,\ 1-x\le y\le1')+'인 삼각형이다. 나머지는 좌표반사로 얻으며 네 조각 모두 제I형·제II형이다.','The first-quadrant piece is the triangle '+m(r'0\le x\le1,\ 1-x\le y\le1')+'. Reflections give the other three; every piece is both Type Iand Type II.'),('적분함수는 두 반사에 불변이므로 '+d(r'I=4\int_0^1\int_{1-x}^1x^2\,dy\,dx=4\int_0^1x^3dx=1')+'이다.','The integrand is invariant under both reflections: '+d(r'I=4\int_0^1\int_{1-x}^1x^2\,dy\,dx=4\int_0^1x^3dx=1'))],d('I=1'))
fig(67,[[(sx*x,sy*y) for x,y in [(0,1),(1,0),(1,1)]] for sx in(-1,1) for sy in(-1,1)],'Four corner triangles')
v1,ss1=D.evaluated(y,[(x,-1,y-y**3),(y,-1,0)]);v2,ss2=D.evaluated(y,[(x,s.sqrt(y)-1,y-y**3),(y,0,1)])
add(68,('도해의 영역은 '+m(r'-1\le y\le0,\ -1\le x\le y-y^3')+'와 '+m(r'0\le y\le1,\ \sqrt y-1\le x\le y-y^3')+'의 합이다. 제I/II형 조각으로 표현하고 y를 적분하라.','The diagram consists of '+m(r'-1\le y\le0,\ -1\le x\le y-y^3')+' together with '+m(r'0\le y\le1,\ \sqrt y-1\le x\le y-y^3')+'. Express it in Type I/IIpieces and integrate y.'),[('왼쪽 경계가 y=0에서 바뀌므로 두 제II형 조각으로 나눈다.','The left boundary changes at y=0, giving two Type IIpieces.')]+ss1+ss2+[('두 적분을 더한다.','Add the two integrals.')],d('I='+tex(v1+v2)))
pol=strip_polygon(-1,0,lambda y:-1,lambda y:y-y**3);pol2=strip_polygon(0,1,lambda y:math.sqrt(y)-1,lambda y:y-y**3);fig(68,[[(y,x) for x,y in pol],[(y,x) for x,y in pol2]],'Two horizontal-slice pieces')
add(69,('Property10으로 '+m(r'\sqrt{4-x^2y^2}')+'의 단위 오른쪽 반원판 적분에 상하한을 주어라.','Use Property10 to bound the integral of '+m(r'\sqrt{4-x^2y^2}')+' over the unit right half-disk.'),[(''+m(r'4x^2y^2\le(x^2+y^2)^2\le1')+'이므로 '+m(r'\sqrt{15}/2\le f\le2')+'이다.','Since '+m(r'4x^2y^2\le(x^2+y^2)^2\le1')+', '+m(r'\sqrt{15}/2\le f\le2')+'.'),('영역넓이 '+m(r'\pi/2')+'를 두 끝값에 곱한다.','Multiply both bounds by area '+m(r'\pi/2')+'.')],d(r'\frac{\pi\sqrt{15}}4\le I\le\pi'))
add(70,('삼각형 '+m(r'y=0,\ y=2x,\ x=1')+'에서 '+m(r'\sin^4(x+y)')+'의 적분을 Property10으로 추정하라.','Use Property10 to bound the integral of '+m(r'\sin^4(x+y)')+' on the triangle bounded by '+m(r'y=0,\ y=2x,\ x=1')+'.'),[('모든 점에서 '+m(r'0\le\sin^4(x+y)\le1')+'이다. 삼각형의 밑변과 높이는1,2이므로 넓이는1이다.','Everywhere '+m(r'0\le\sin^4(x+y)\le1')+'. The triangle has base1and height2, hence area1.'),('최소·최대값에 영역넓이를 곱한다.','Multiply the pointwise bounds by the area.')],d(r'0\le I\le1'))
for n,f,ll,area_,desc in [(71,x*y,[(y,0,3*x),(x,0,1)],s.Rational(3,2),r'\text{triangle }(0,0),(1,0),(1,3)'),(72,x*s.sin(y),[(y,0,x*x),(x,0,1)],s.Rational(1,3),r'0\le x\le1,\ 0\le y\le x^2')]:
 vv,ss=D.evaluated(f,ll);add(n,('영역 '+m(desc)+'에서 '+m(tex(f))+'의 평균을 구하라.','Find the average of '+m(tex(f))+' over '+m(desc)+'.'),ss+[('영역넓이 '+m(tex(area_))+'로 나눈다.','Divide by area '+m(tex(area_))+'.')],d(r'f_{\rm avg}='+tex(s.simplify(vv/area_))))
add(73,('영역 D에서 '+m(r'm\le f\le M')+'일 때 Property10인 '+m(r'mA(D)\le\iint_Df\le MA(D)')+'를 증명하라.','Prove Property10: if '+m(r'm\le f\le M')+' on D, then '+m(r'mA(D)\le\iint_Df\le MA(D)')+'.'),[('적분의 순서보존을 상수함수 m,f,M에 적용한다. '+d(r'\iint_Dm\,dA\le\iint_Df\,dA\le\iint_DM\,dA'),'Apply monotonicity to the constant functions m,Mand to f: '+d(r'\iint_Dm\,dA\le\iint_Df\,dA\le\iint_DM\,dA')),('상수 적분은 상수×영역넓이이므로 양 끝을 각각 mA(D),MA(D)로 바꾼다.','A constant integrates to the constant times area, giving mA(D)and MA(D).')],d(r'mA(D)\le\iint_Df\,dA\le MA(D)'))
add(74,('영역을 그리고 다음 합을 순서를 바꾼 하나의 적분으로 써라. '+d(r'\int_0^1\int_0^{2y}f\,dx\,dy+\int_1^3\int_0^{3-y}f\,dx\,dy'),'Sketch the region and rewrite as one integral in the opposite order: '+d(r'\int_0^1\int_0^{2y}f\,dx\,dy+\int_1^3\int_0^{3-y}f\,dx\,dy')),[('두 조각은 꼭짓점(0,0),(2,1),(0,3)의 삼각형을 이룬다.','The two pieces form the triangle with vertices(0,0),(2,1),(0,3).'),('x는0부터2이고 세로단면은 '+m(r'x/2\le y\le3-x')+'이다.','The range is0≤x≤2and vertical slices satisfy '+m(r'x/2\le y\le3-x')+'.')],d(r'\int_0^2\int_{x/2}^{3-x}f\,dy\,dx'))
fig(74,[[(0,0),(2,1),(0,3)]],'Triangle formed by the two integrals')
add(75,('위쪽 반원판 '+m(r'x^2+y^2\le9,y\ge0')+'에서 '+m('x+2')+'의 적분을 기하·대칭으로 구하라.','Use geometry and symmetry to integrate '+m('x+2')+' on '+m(r'x^2+y^2\le9,y\ge0')+'.'),[('x항은 좌우대칭으로 상쇄된다.','The xterm cancels by left-right symmetry.'),('상수2에 반원넓이 '+m(r'9\pi/2')+'를 곱한다.','Multiply2by the semicircle area '+m(r'9\pi/2')+'.')],d('I=9\\pi'))
add(76,('반지름 R인 원판에서 '+m(r'\sqrt{R^2-x^2-y^2}')+'의 적분을 기하학적으로 구하라.','Use geometry to integrate '+m(r'\sqrt{R^2-x^2-y^2}')+' over the radius-Rdisk.'),[('함수는 반지름 R구의 위쪽 반구 높이다.','The graph is the upper hemisphere of a sphere of radius R.'),('적분은 반구부피이므로 구부피의 절반이다.','The integral is the hemisphere volume, half the sphere volume.')],d(r'I=\frac{2\pi R^3}{3}'))
calc(77,2*x+3*y,[(y,0,b),(x,0,a)],('직사각형 '+m('[0,a]\\times[0,b]')+'에서 '+m('2x+3y')+'를 적분하라.','Integrate '+m('2x+3y')+' on '+m('[0,a]\\times[0,b]')+'.'))
add(78,('마름모 '+m(r'|x|+|y|\le1')+'에서 '+m(r'2+x^2y^3-y^2\sin x')+'를 대칭으로 적분하라.','Use symmetry to integrate '+m(r'2+x^2y^3-y^2\sin x')+' on '+m(r'|x|+|y|\le1')+'.'),[('x²y³는 y반사에 홀함수이고 y²sinx는 x반사에 홀함수라 각각0이다.','The term x²y³is odd under yreflection, and y²sinxis odd under xreflection; both integrate to zero.'),('마름모의 두 대각선 길이는2이므로 넓이는2이다. 상수항 적분은2×2이다.','The diamond diagonals both have length2, so area is2. The constant term contributes2×2.')],d('I=4'))
add(79,('직사각형 '+m('[-a,a]\\times[-b,b]')+'에서 '+m(r'ax^3+by^3+\sqrt{a^2-x^2}')+'를 기하·대칭으로 적분하라.','Use geometry and symmetry to integrate '+m(r'ax^3+by^3+\sqrt{a^2-x^2}')+' on '+m('[-a,a]\\times[-b,b]')+'.'),[('두 세제곱항은 각각 홀대칭으로 소거된다.','Both cubic terms cancel by odd symmetry.'),('나머지는 반지름 a인 반원단면을 y방향 길이2b만큼 늘린 반원기둥 부피이다. '+d(r'I=2b\cdot\frac{\pi a^2}{2}'),'The remaining graph is a semicircular cylinder with radius aand length2b: '+d(r'I=2b\cdot\frac{\pi a^2}{2}'))],d(r'I=\pi a^2b'))
add(80,('유계 폐연결 영역 D의 연속함수 f에 대해 '+m(r'\iint_Df\,dA=f(x_0,y_0)A(D)')+'인 점이 D에 존재함을 보여라(적분 평균값 정리).','For continuous fon a bounded closed connected region D, prove there is a point satisfying '+m(r'\iint_Df\,dA=f(x_0,y_0)A(D)')+' (integral mean-value theorem).'),[('최대·최소 정리로 f는 m,M을 달성한다. 넓이가 양수이면 Property10을 넓이로 나누어 '+m(r'm\le f_{\rm avg}\le M')+'을 얻는다.','The extreme-value theorem gives attained minimum mand maximum M. For positive area, Property10yields '+m(r'm\le f_{\rm avg}\le M')+'.'),('연결집합의 연속상은 실수구간이므로 m과 M사이인 평균값도 어떤 점에서 달성된다. 넓이가0이면 양변이0이어서 임의의 점이 된다.','The continuous image of a connected set is an interval, so the mean is attained. If area is zero, both sides vanish and any point works.')],d(r'\exists(x_0,y_0)\in D:\quad\iint_Df=f(x_0,y_0)A(D)'))
add(81,('점(a,b)주변에서 연속인 f에 대해 중심(a,b),반지름 r원판 Dᵣ의 평균값이 r→0에서 f(a,b)로 수렴함을 보여라.','Show that for fcontinuous near(a,b), its average over the radius-rdisk Dᵣcentered at(a,b) tends to f(a,b) as r→0.'),[('연속성에 의해 임의의 ε>0에 대해 r이 충분히 작으면 원판 전체에서 '+m(r'|f(x,y)-f(a,b)|<\varepsilon')+'이다.','Continuity ensures that for any ε>0, sufficiently small rmakes '+m(r'|f(x,y)-f(a,b)|<\varepsilon')+' throughout the disk.'),('평균 오차는 '+d(r'\left|\frac1{\pi r^2}\iint_{D_r}f\,dA-f(a,b)\right|\le\frac1{\pi r^2}\iint_{D_r}|f-f(a,b)|\,dA<\varepsilon')+'이다.','The average error is '+d(r'\left|\frac1{\pi r^2}\iint_{D_r}f\,dA-f(a,b)\right|\le\frac1{\pi r^2}\iint_{D_r}|f-f(a,b)|\,dA<\varepsilon'))],d(r'\lim_{r\to0^+}\frac1{\pi r^2}\iint_{D_r}f\,dA=f(a,b)'))
add(82,('평면 '+m('x+y+z=1')+'과 포물면 '+m('z=4-x^2-y^2')+' 사이 입체를 그리고 CAS로 부피를 구하라.','Graph the solid between '+m('x+y+z=1')+' and '+m('z=4-x^2-y^2')+' and use a CAS to find its volume.'),[('높이차를 완전제곱하면 '+m(r'7/2-(x-1/2)^2-(y-1/2)^2')+'이므로 투영은 중심(1/2,1/2),반지름 '+m(r'\sqrt{7/2}')+'인 원판이다.','Completing squares gives height '+m(r'7/2-(x-1/2)^2-(y-1/2)^2')+', so the projection is a disk centered at(1/2,1/2)with radius '+m(r'\sqrt{7/2}')+'.'),('이동된 극좌표로 '+d(r'V=\int_0^{2\pi}\int_0^{\sqrt{7/2}}(7/2-r^2)r\,dr\,d\theta=\frac{49\pi}{8}')+'이다.','Shifted polar coordinates give '+d(r'V=\int_0^{2\pi}\int_0^{\sqrt{7/2}}(7/2-r^2)r\,dr\,d\theta=\frac{49\pi}{8}'))],d(r'V=49\pi/8'))
def fn82(u,v,w):
 rr=math.sqrt(3.5)*u;xx=.5+rr*math.cos(2*math.pi*v);yy=.5+rr*math.sin(2*math.pi*v);return(xx,yy,1-xx-yy+w*(3.5-rr*rr))
name='s15-2-82.svg';solid(name,'15.2 /82 - Plane and paraboloid',fn82,subtitle='x + y + z = 1; z = 4 - x² - y²');figures[82]=(name,'Plane and paraboloid with their circular intersection')
for n,(name,title) in figures.items():attach(next(e for e in D.items if e['number']==n),name,('경계 조건에서 직접 그린 도형','Original diagram from the boundary conditions'),(title,title))
D.save(82)
