"""Chapter15 Problems Plus: independent original proofs and verification."""
from core_15 import *
from planar_15 import *
import mpmath as mp
x,y,z,u,v,r,t=s.symbols('x y z u v r theta',real=True)
D=Doc('15.11',[1159,1160],lambda n:1159 if n<=7 else 1160)
def add(n,st,steps,ans,parts=(),check=('좌표변환의 경계·야코비안과 각 극한의 정당화 조건을 대조했다.','Transformation boundaries, Jacobians, and justification of limit operations were checked.')):
 return D.add(n,('15장 심화문제','Chapter15 Problems Plus'),st,('영역의 대칭, 적분순서 교환 또는 적절한 좌표변환을 찾는다.','Look for symmetry, a useful change of order, or an appropriate coordinate transformation.'),steps,ans,check,parts)
add(1,('최대정수함수 '+m(r'\lfloor\cdot\rfloor')+'에 대해 '+m(r'\iint_{[1,3]\times[2,5]}\lfloor x+y\rfloor\,dA')+'를 구하라.','Evaluate '+m(r'\iint_{[1,3]\times[2,5]}\lfloor x+y\rfloor\,dA')+', where the brackets denote the floor function.'),[('영역을 '+m(r'x=i+u,\ y=j+v,\ 0\le u,v\le1')+'인6개 단위정사각형으로 나눈다. '+m(r'i=1,2;\ j=2,3,4')+'이다.','Divide the region into sixunit squares with '+m(r'x=i+u,\ y=j+v,\ 0\le u,v\le1')+', where '+m(r'i=1,2;\ j=2,3,4')+'.'),('각 칸에서 바닥값은 i+j이고 '+m('u+v\\ge1')+'인 넓이1/2삼각형에서1만큼 증가한다. 경계선은 면적0이다. 따라서 각 칸의 적분은 '+m('i+j+1/2')+'이다.','On each square the base value is i+j, with an additional1on the half-square '+m('u+v\\ge1')+'. Boundary lines have area zero. Each integral is '+m('i+j+1/2')+'.'),('6개 값을 합친다. '+d(r'I=(3+4+5+4+5+6)+6/2=30'),'Sum the sixcontributions: '+d(r'I=(3+4+5+4+5+6)+6/2=30'))],d('I=30'))
add(2,(''+m(r'\int_0^1\int_0^1e^{\max\{x^2,y^2\}}\,dy\,dx')+'를 계산하라.','Evaluate '+m(r'\int_0^1\int_0^1e^{\max\{x^2,y^2\}}\,dy\,dx')+'.'),[('단위정사각형을 y=x로 나눈다. 두 삼각형은 좌표교환으로 같으므로2배를 쓴다. y≤x에서는 최댓값이 x²이다.','Split the square along y=x. The triangles are equal by coordinate symmetry; on y≤x the maximum is x².'),('안쪽 y적분 후 '+m('q=x^2')+'로 치환한다. '+d(r'I=2\int_0^1\int_0^xe^{x^2}\,dy\,dx=2\int_0^1xe^{x^2}dx=e-1'),'Integrate in ythen substitute '+m('q=x^2')+': '+d(r'I=2\int_0^1\int_0^xe^{x^2}\,dy\,dx=2\int_0^1xe^{x^2}dx=e-1'))],d('I=e-1'))
add(3,(''+m(r'f(x)=\int_x^1\cos(t^2)dt')+'의 '+m('[0,1]')+'에서의 평균을 구하라.','Find the average of '+m(r'f(x)=\int_x^1\cos(t^2)dt')+' on '+m('[0,1]')+'.'),[('구간길이가1이므로 평균은 '+m(r'\int_0^1\int_x^1\cos(t^2)dt\,dx')+'이다. 영역은 '+m(r'0\le x\le t\le1')+'이다.','The interval length is1, so the average is '+m(r'\int_0^1\int_x^1\cos(t^2)dt\,dx')+'. The region is '+m(r'0\le x\le t\le1')+'.'),('연속함수에 Fubini를 적용하여 순서를 바꾸면 '+d(r'f_{\rm avg}=\int_0^1\int_0^t\cos(t^2)dx\,dt=\int_0^1t\cos(t^2)dt=\frac{\sin1}{2}')+'이다.','Fubini for the continuous integrand gives '+d(r'f_{\rm avg}=\int_0^1\int_0^t\cos(t^2)dx\,dt=\int_0^1t\cos(t^2)dt=\frac{\sin1}{2}'))],d(r'f_{\rm avg}=\frac{\sin1}{2}'))
add(4,('좌표변환으로 '+m(r'\int_0^2\int_0^x2e^{x^2-y^2}\,dy\,dx=\int_0^2\int_y^{4-y}e^{xy}\,dx\,dy')+'를 증명하라.','Use a change of variables to prove '+m(r'\int_0^2\int_0^x2e^{x^2-y^2}\,dy\,dx=\int_0^2\int_y^{4-y}e^{xy}\,dx\,dy')+'.'),[('새 변수 '+m(r'u=x+y,\ v=x-y')+'이면 '+m(r'x=(u+v)/2,\ y=(u-v)/2')+'이고 '+m(r'x^2-y^2=uv,\ |\partial(x,y)/\partial(u,v)|=1/2')+'이다.','Let '+m(r'u=x+y,\ v=x-y')+'. Then '+m(r'x=(u+v)/2,\ y=(u-v)/2')+' and '+m(r'x^2-y^2=uv,\ |\partial(x,y)/\partial(u,v)|=1/2')+'.'),('원래 '+m(r'0\le y\le x\le2')+'는 '+m(r'0\le v\le2,\ v\le u\le4-v')+'로 바뀐다.','The original '+m(r'0\le y\le x\le2')+' becomes '+m(r'0\le v\le2,\ v\le u\le4-v')+'.'),('적분함수의2와 야코비안1/2가 소거된다. '+d(r'I=\int_0^2\int_v^{4-v}e^{uv}\,du\,dv')+'에서 더미변수를 바꾸면 원하는 식이다.','The factor2cancels the Jacobian1/2. Renaming the dummy variables in '+d(r'I=\int_0^2\int_v^{4-v}e^{uv}\,du\,dv')+' proves the identity.')],d(r'\int_0^2\int_0^x2e^{x^2-y^2}\,dy\,dx=\int_0^2\int_y^{4-y}e^{xy}\,dx\,dy'))
add(5,('단위정사각형에서 '+m(r'1/(1-xy)')+'의 이상적분을 '+m(r'[0,t]^2,\ t\to1^-')+'로 정의한다. 기하급수로 '+m(r'\iint(1-xy)^{-1}dA=\sum_{n=1}^\infty n^{-2}')+'임을 보여라.','Define the improper integral of '+m(r'1/(1-xy)')+' on the unit square through '+m(r'[0,t]^2,\ t\to1^-')+'. Use the geometric series to prove '+m(r'\iint(1-xy)^{-1}dA=\sum_{n=1}^\infty n^{-2}')+'.'),[('t<1인 절단정사각형에서는 '+m(r'\sum_{k=0}^\infty(xy)^k')+'가 균등수렴하므로 항별적분이 가능하다.','For t<1the geometric series '+m(r'\sum_{k=0}^\infty(xy)^k')+' converges uniformly on the truncated square, permitting termwise integration.'),('분리 적분으로 '+d(r'I(t)=\sum_{k=0}^\infty\left(\int_0^tx^kdx\right)^2=\sum_{n=1}^\infty\frac{t^{2n}}{n^2}')+'이다.','Separating the integrals gives '+d(r'I(t)=\sum_{k=0}^\infty\left(\int_0^tx^kdx\right)^2=\sum_{n=1}^\infty\frac{t^{2n}}{n^2}')),('모든 항이 음이 아니고 t가1로 증가한다. 단조수렴으로 합과 극한을 바꾸면 원하는 급수가 된다. p급수 p=2는 수렴하므로 이상적분도 유한하다.','All terms are nonnegative and increase as t→1. Monotone convergence interchanges sum and limit. The p-series with p=2converges, so the improper integral is finite.')],d(r'\iint_{[0,1]^2}\frac{dA}{1-xy}=\sum_{n=1}^\infty\frac1{n^2}'))
add(6,('문항5의 적분에 '+m(r'x=(u-v)/\sqrt2,\ y=(u+v)/\sqrt2')+'를 적용하여 '+m(r'\sum_{n=1}^\infty n^{-2}=\pi^2/6')+'을 증명하라. uv영역을 그려라.','Apply '+m(r'x=(u-v)/\sqrt2,\ y=(u+v)/\sqrt2')+' to the integral of Problem5to prove '+m(r'\sum_{n=1}^\infty n^{-2}=\pi^2/6')+'. Sketch the uvregion.'),[('회전의 야코비안은1이다. 단위정사각형은 꼭짓점 '+m(r'(0,0),(1/\sqrt2,\pm1/\sqrt2),(\sqrt2,0)')+'의 마름모이며 '+m(r'|v|\le h(u)=\min(u,\sqrt2-u)')+'이다.','The rotation has Jacobian1. The square becomes the diamond with vertices '+m(r'(0,0),(1/\sqrt2,\pm1/\sqrt2),(\sqrt2,0)')+', where '+m(r'|v|\le h(u)=\min(u,\sqrt2-u)')+'.'),('v에 짝대칭이고 '+m(r'xy=(u^2-v^2)/2')+'이므로 '+d(r'I=4\int_0^{\sqrt2}\frac1{\sqrt{2-u^2}}\arctan\frac{h(u)}{\sqrt{2-u^2}}\,du')+'이다. 끝점은 이상적분으로 해석한다.','Even symmetry in vand '+m(r'xy=(u^2-v^2)/2')+' give '+d(r'I=4\int_0^{\sqrt2}\frac1{\sqrt{2-u^2}}\arctan\frac{h(u)}{\sqrt{2-u^2}}\,du')+'. Interpret the endpoint improperly.'),(''+m(r'u=\sqrt2\sin\theta')+'로 두면 h가 바뀌는 '+m(r'u=1/\sqrt2')+'는 '+m(r'\theta=\pi/6')+'이다. 첫 구간의 역탄젠트는 θ, 두 번째는 '+m(r'\arctan\frac{1-\sin\theta}{\cos\theta}=\pi/4-\theta/2')+'이다.','Let '+m(r'u=\sqrt2\sin\theta')+'. The switch at '+m(r'u=1/\sqrt2')+' occurs at '+m(r'\theta=\pi/6')+'. The first arctangent equals θ; the second is '+m(r'\arctan\frac{1-\sin\theta}{\cos\theta}=\pi/4-\theta/2')+'.'),('따라서 '+d(r'I=4\left[\int_0^{\pi/6}\theta\,d\theta+\int_{\pi/6}^{\pi/2}(\pi/4-\theta/2)\,d\theta\right]=4\left(\frac{\pi^2}{72}+\frac{\pi^2}{36}\right)=\frac{\pi^2}{6}')+'이다. 문항5의 급수와 같다.','Therefore '+d(r'I=4\left[\int_0^{\pi/6}\theta\,d\theta+\int_{\pi/6}^{\pi/2}(\pi/4-\theta/2)\,d\theta\right]=4\left(\frac{\pi^2}{72}+\frac{\pi^2}{36}\right)=\frac{\pi^2}{6}')+', equal to the series in Problem5.')],d(r'\sum_{n=1}^\infty n^{-2}=\pi^2/6'))
name='s15-11-6.svg';planar(name,'15 Problems Plus /6 - Rotated unit square',[[(0,0),(1/math.sqrt(2),-1/math.sqrt(2)),(math.sqrt(2),0),(1/math.sqrt(2),1/math.sqrt(2))]],[(0,0,'(0,0)'),(1.20,0.08,'(√2,0)'),(1/math.sqrt(2),1/math.sqrt(2),'(1/√2,1/√2)')]);# Rename diagram coordinate axes, since this is the uvplane.
pth=ASSETS/name;txt=pth.read_text().replace('>x</text>','>u</text>').replace('>y</text>','>v</text>');pth.write_text(txt);attach(D.items[-1],name,('회전된 단위 정사각형의 uv영역','The unit square rotated into the uvplane'),('꼭짓점과 대칭 경계가 표시된 마름모','Diamond with its vertices and symmetric boundaries'))
add(7,('(a) '+m(r'\iiint_{[0,1]^3}(1-xyz)^{-1}dV=\sum_{n=1}^\infty n^{-3}')+'를 보인다. (b) '+m(r'\iiint_{[0,1]^3}(1+xyz)^{-1}dV=\sum_{n=1}^\infty(-1)^{n-1}n^{-3}')+'를 보이고 소수 둘째 자리까지 구하라.','Prove (a) '+m(r'\iiint_{[0,1]^3}(1-xyz)^{-1}dV=\sum_{n=1}^\infty n^{-3}')+' and (b) '+m(r'\iiint_{[0,1]^3}(1+xyz)^{-1}dV=\sum_{n=1}^\infty(-1)^{n-1}n^{-3}')+'. Evaluate(b)to two decimals.'),[('(a) 비음 기하급수와 단조수렴을 적용한다. '+d(r'\sum_{k=0}^\infty\iiint(xyz)^kdV=\sum_{k=0}^\infty\frac1{(k+1)^3}')+'이다. p=3급수가 수렴하여 특이점의 이상적분도 유한하다.','(a) Apply the nonnegative geometric series and monotone convergence: '+d(r'\sum_{k=0}^\infty\iiint(xyz)^kdV=\sum_{k=0}^\infty\frac1{(k+1)^3}')+'. The p=3series converges, making the improper integral finite.'),('(b) 유한 기하급수의 적분 나머지는 '+m(r'\iiint(xyz)^{N+1}/(1+xyz)dV\le1/(N+2)^3')+'이므로0으로 간다. 따라서 교대급수 적분식이 성립한다.','(b) The integrated remainder of a finite geometric sum is at most '+m(r'\iiint(xyz)^{N+1}/(1+xyz)dV\le1/(N+2)^3')+', tending to zero. Thus the alternating series identity holds.'),('처음10항의 합은 약0.901116이며 다음항이 '+m('1/11^3<0.000752')+'이다. 교대급수 오차범위 전체가0.90으로 반올림된다.','The first10terms sum to approximately0.901116and the next term is '+m('1/11^3<0.000752')+'. The entire alternating-series error interval rounds to0.90.')],d(r'(a)\zeta(3);\quad(b)\frac34\zeta(3)\approx0.90'),('a','b'))
add(8,('반복적분을 사용하여 '+m(r'\int_0^\infty\frac{\arctan(\pi x)-\arctan x}{x}dx=\frac\pi2\ln\pi')+'를 증명하라.','Use an iterated integral to prove '+m(r'\int_0^\infty\frac{\arctan(\pi x)-\arctan x}{x}dx=\frac\pi2\ln\pi')+'.'),[('매개변수 t에 대해 '+m(r'\partial_t\arctan(tx)=x/(1+t^2x^2)')+'이므로 x>0에서 '+m(r'[\arctan(\pi x)-\arctan x]/x=\int_1^\pi(1+t^2x^2)^{-1}dt')+'이다.','Since '+m(r'\partial_t\arctan(tx)=x/(1+t^2x^2)')+', for x>0the integrand equals '+m(r'\int_1^\pi(1+t^2x^2)^{-1}dt')+'.'),('비음 함수이므로 Tonelli로 순서를 바꿀 수 있다. '+d(r'I=\int_1^\pi\int_0^\infty\frac{dx\,dt}{1+t^2x^2}=\int_1^\pi\frac\pi{2t}dt'),'The function is nonnegative, so Tonelli permits exchange: '+d(r'I=\int_1^\pi\int_0^\infty\frac{dx\,dt}{1+t^2x^2}=\int_1^\pi\frac\pi{2t}dt')),('마지막 적분은 로그이며 유한하므로 원래 이상적분의 수렴도 함께 확인된다.','The remaining logarithmic integral is finite, also establishing convergence of the original improper integral.')],d(r'I=\frac\pi2\ln\pi'))
add(9,('Laplace 방정식 '+m(r'u_{xx}+u_{yy}+u_{zz}=0')+'을 (a)원기둥좌표와 (b)구면좌표로 유도하라. 구면좌표는 방위각 θ, 양의 z축에서 잰 각 φ를 사용한다.','Derive Laplace’s equation '+m(r'u_{xx}+u_{yy}+u_{zz}=0')+' in(a)cylindrical and(b)spherical coordinates, using azimuth θand polar angle φfrom the positive zaxis.'),[('(a) 연쇄법칙은 '+m(r'\partial_x=\cos\theta\partial_r-(\sin\theta/r)\partial_\theta,\ \partial_y=\sin\theta\partial_r+(\cos\theta/r)\partial_\theta')+'이다. 이 연산자를 한 번 더 적용할 때 계수도 미분한다.','(a) The chain rule gives '+m(r'\partial_x=\cos\theta\partial_r-(\sin\theta/r)\partial_\theta,\ \partial_y=\sin\theta\partial_r+(\cos\theta/r)\partial_\theta')+'. Applying them again also differentiates their coefficients.'),('두 식을 더하면 교차항이 소거되고 '+d(r'u_{xx}+u_{yy}=u_{rr}+r^{-1}u_r+r^{-2}u_{\theta\theta}')+'를 얻는다. z항은 그대로다.','Adding cancels mixed terms and gives '+d(r'u_{xx}+u_{yy}=u_{rr}+r^{-1}u_r+r^{-2}u_{\theta\theta}')+'. The zterm is unchanged.'),('(b) 구면좌표에서 미소변 길이는 '+m(r'd\rho,\rho\,d\phi,\rho\sin\phi\,d\theta')+'이다. 따라서 기울기의 정규직교 성분은 '+m(r'u_\rho,\ u_\phi/\rho,\ u_\theta/(\rho\sin\phi)')+'이다.','(b) Spherical coordinate edges have lengths '+m(r'd\rho,\rho\,d\phi,\rho\sin\phi\,d\theta')+'. Thus gradient components in the orthonormal directions are '+m(r'u_\rho,\ u_\phi/\rho,\ u_\theta/(\rho\sin\phi)')+'.'),('미소상자의 각 반대면 쌍을 지나는 기울기 유량 차이를 부피 '+m(r'\rho^2\sin\phi\,d\rho\,d\phi\,d\theta')+'로 나누면 '+d(r'\Delta u=\frac1{\rho^2}\partial_\rho(\rho^2u_\rho)+\frac1{\rho^2\sin\phi}\partial_\phi(\sin\phi\,u_\phi)+\frac1{\rho^2\sin^2\phi}u_{\theta\theta}')+'이다. 곱미분으로 전개한다.','Divide the net gradient flux through each pair of opposite infinitesimal faces by volume '+m(r'\rho^2\sin\phi\,d\rho\,d\phi\,d\theta')+' to get '+d(r'\Delta u=\frac1{\rho^2}\partial_\rho(\rho^2u_\rho)+\frac1{\rho^2\sin\phi}\partial_\phi(\sin\phi\,u_\phi)+\frac1{\rho^2\sin^2\phi}u_{\theta\theta}')+'. Expand by the product rule.'),('좌표식의 분모 때문에 원기둥식은 r>0, 구면식은 ρ>0,0<φ<π에서 직접 유효하다. 원점·축의 매끄러운 해는 직교좌표나 극한으로 해석한다.','The displayed coordinate formulas hold directly for r>0and for ρ>0,0<φ<π. Smooth solutions on axes or the origin are interpreted in Cartesian coordinates or by limits.')],d(r'(a)\ u_{rr}+\frac1r u_r+\frac1{r^2}u_{\theta\theta}+u_{zz}=0')+d(r'(b)\ u_{\rho\rho}+\frac2\rho u_\rho+\frac{\cot\phi}{\rho^2}u_\phi+\frac1{\rho^2}u_{\phi\phi}+\frac1{\rho^2\sin^2\phi}u_{\theta\theta}=0'),('a','b'))
add(10,('밀도ρ인 균일한 반지름 R원판이 xy평면에 있다. (a)(0,0,d),d>0에 있는 질량 m물체에 작용하는 중력의 크기를 유도하라. (b)R→∞로 무한평면의 힘을 구하라.','A uniform radius-Rdisk of surface density ρlies in the xyplane. (a) Derive the gravitational force magnitude on a mass mat(0,0,d),d>0. (b) Take R→∞to obtain the infinite-plane force.'),[('질량요소는 '+m(r'dM=\rho r\,dr\,d\theta')+'이고 물체까지 거리는 '+m(r'\sqrt{r^2+d^2}')+'이다. Newton 법칙의 힘 크기에 수직 성분비 '+m(r'd/\sqrt{r^2+d^2}')+'를 곱한다.','An element has mass '+m(r'dM=\rho r\,dr\,d\theta')+' and distance '+m(r'\sqrt{r^2+d^2}')+'. Multiply Newton’s force magnitude by the vertical projection factor '+m(r'd/\sqrt{r^2+d^2}')+'.'),('수평 성분은 원주대칭으로 상쇄된다. 아래 방향 힘의 크기는 '+d(r'F=2\pi Gm\rho d\int_0^R\frac{r}{(r^2+d^2)^{3/2}}dr=2\pi Gm\rho d\left(\frac1d-\frac1{\sqrt{R^2+d^2}}\right)')+'이다.','Horizontal components cancel around the disk. The downward force magnitude is '+d(r'F=2\pi Gm\rho d\int_0^R\frac{r}{(r^2+d^2)^{3/2}}dr=2\pi Gm\rho d\left(\frac1d-\frac1{\sqrt{R^2+d^2}}\right)')),('(b) R이 무한대로 가면 두 번째 항이0으로 가므로 힘은 거리 d에 무관해진다.','(b) As R→∞the second term vanishes, leaving a force independent of d.')],d(r'(a)\ F=2\pi Gm\rho\left(1-\frac d{\sqrt{R^2+d^2}}\right),\quad(b)\ F=2\pi Gm\rho'),('a','b'))
add(11,('연속함수 f에 대해 '+m(r'\int_0^x\int_0^y\int_0^zf(t)\,dt\,dz\,dy=\frac12\int_0^x(x-t)^2f(t)dt')+'를 증명하라.','For continuous f, prove '+m(r'\int_0^x\int_0^y\int_0^zf(t)\,dt\,dz\,dy=\frac12\int_0^x(x-t)^2f(t)dt')+'.'),[('x≥0이면 원래 영역은 '+m(r'0\le t\le z\le y\le x')+'이다. t를 바깥변수로 두면 '+m(r'0\le t\le x,\ t\le y\le x,\ t\le z\le y')+'이다.','For x≥0the region is '+m(r'0\le t\le z\le y\le x')+'. Taking toutermost gives '+m(r'0\le t\le x,\ t\le y\le x,\ t\le z\le y')+'.'),('f(t)를 고정한 yz삼각형의 넓이는 '+m(r'(x-t)^2/2')+'이다. '+d(r'\int_0^xf(t)\int_t^x\int_t^y dz\,dy\,dt=\frac12\int_0^x(x-t)^2f(t)dt'),'At fixed tthe yztriangle has area '+m(r'(x-t)^2/2')+': '+d(r'\int_0^xf(t)\int_t^x\int_t^y dz\,dy\,dt=\frac12\int_0^x(x-t)^2f(t)dt')),('x<0까지 포함하려면 양변을 x로 세 번 미분한다. 두 세 번째 도함수는 f(x)이고0에서 함수·첫째·둘째 도함수가 모두0이다. 따라서 양변의 차는 영인 이차다항식이다.','To include x<0, differentiate both sides three times. Each third derivative equals f(x), and each function plus its first two derivatives vanishes at0. Their difference is therefore the zero quadratic polynomial.')],d(r'\int_0^x\int_0^y\int_0^zf(t)\,dt\,dz\,dy=\frac12\int_0^x(x-t)^2f(t)dt'))
val,subs=D.evaluated(1/s.sqrt(1+x+y),[(y,0,1),(x,0,1)])
add(12,('극한 '+m(r'\lim_{n\to\infty}n^{-2}\sum_{i=1}^{n}\sum_{j=1}^{n^2}\frac1{\sqrt{n^2+ni+j}}')+'를 구하라.','Evaluate '+m(r'\lim_{n\to\infty}n^{-2}\sum_{i=1}^{n}\sum_{j=1}^{n^2}\frac1{\sqrt{n^2+ni+j}}')+'.'),[('분모에서 n을 꺼내면 각 항의 계수는 '+m('n^{-3}=(1/n)(1/n^2)')+'이다. 표본점 '+m(r'(i/n,j/n^2)')+'은 단위정사각형의 오른쪽 위 표본이고 함수는 '+m(r'(1+x+y)^{-1/2}')+'이다.','Factor nout of the denominator. The weight becomes '+m('n^{-3}=(1/n)(1/n^2)')+'. The points '+m(r'(i/n,j/n^2)')+' are upper-right samples on the unit square for '+m(r'(1+x+y)^{-1/2}')+'.'),('함수는 연속이고 두 격자폭이 모두0으로 가므로 Riemann합의 극한은 이중적분이다.','The function is continuous and both mesh widths tend to zero, so the Riemann sums converge to the double integral.')]+subs,d('L='+tex(val)))
add(13,('양수 a,b,c에 대해 평면 '+m(r'x/a+y/b+z/c=1')+'이 타원체 '+m(r'x^2/a^2+y^2/b^2+z^2/c^2\le1')+'를 나눈다. 작은 조각의 부피를 구하라.','For positive a,b,c, the plane '+m(r'x/a+y/b+z/c=1')+' cuts '+m(r'x^2/a^2+y^2/b^2+z^2/c^2\le1')+'. Find the smaller volume.'),[(''+m(r'u=x/a,\ v=y/b,\ w=z/c')+'로 단위구에 옮긴다. 부피 야코비안은 abc이고 평면은 '+m('u+v+w=1')+'이다.','Set '+m(r'u=x/a,\ v=y/b,\ w=z/c')+'. The ellipsoid becomes the unit ball, the volume Jacobian is abc, and the plane becomes '+m('u+v+w=1')+'.'),('평면 법선방향의 좌표를 '+m(r'q=(u+v+w)/\sqrt3')+'로 회전하면 작은 구면모자는 '+m(r'1/\sqrt3\le q\le1')+'이다. q고정 단면은 넓이 '+m(r'\pi(1-q^2)')+'인 원판이다.','Rotate to the normal coordinate '+m(r'q=(u+v+w)/\sqrt3')+'. The smaller spherical cap has '+m(r'1/\sqrt3\le q\le1')+', with cross-sectional area '+m(r'\pi(1-q^2)')+'.'),('회전은 부피를 보존하므로 원래 부피는 '+d(r'V=\pi abc\int_{1/\sqrt3}^1(1-q^2)dq=\pi abc\left(\frac23-\frac8{9\sqrt3}\right)')+'이다.','Rotation preserves volume, so the original volume is '+d(r'V=\pi abc\int_{1/\sqrt3}^1(1-q^2)dq=\pi abc\left(\frac23-\frac8{9\sqrt3}\right)'))],d(r'V=\pi abc\left(\frac23-\frac{8\sqrt3}{27}\right)'))
D.save(13)
p=ROOT/'exercise-content/s15-11.json';obj=json.loads(p.read_text());obj['scope']['kind']='problems-plus';obj['scope']['note']=pair('15장 Problems Plus의 모든13문항.','All13Problems Plus exercises in Chapter15.');
for e in obj['exercises']:e['conceptHref']='../s15-9.html'
p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
# Independent numerical and algebraic validation of nontrivial identities.
mp.mp.dps=35
checks=[]
def check(label,left,right):
 err=abs(left-right);assert err<mp.mpf('1e-25')*max(1,abs(left)),(label,left,right);checks.append({'exercise':label,'left':str(left),'right':str(right),'error':str(err)})
check(4,mp.quad(lambda xx:mp.quad(lambda yy:2*mp.exp(xx*xx-yy*yy),[0,xx]),[0,2]),mp.quad(lambda yy:mp.quad(lambda xx:mp.exp(xx*yy),[yy,4-yy]),[0,2]))
check(6,4*(mp.quad(lambda q:q,[0,mp.pi/6])+mp.quad(lambda q:mp.pi/4-q/2,[mp.pi/6,mp.pi/2])),mp.pi**2/6)
check(8,mp.quad(lambda xx:(mp.atan(mp.pi*xx)-mp.atan(xx))/xx,[0,1,mp.inf]),mp.pi*mp.log(mp.pi)/2)
check(12,mp.quad(lambda xx:mp.quad(lambda yy:1/mp.sqrt(1+xx+yy),[0,1]),[0,1]),mp.mpf(str(s.N(val,36))))
check(13,mp.pi*mp.quad(lambda q:1-q*q,[1/mp.sqrt(3),1]),mp.pi*(mp.mpf(2)/3-8/(9*mp.sqrt(3))))
report=json.loads((ROOT/'exercise-checks/s15-11-report.json').read_text());report['independentChecks']=checks;(ROOT/'exercise-checks/s15-11-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print('Independent Problems Plus checks passed',len(checks))
