from calc1_core import *
D=CalcDoc('2.2',list(range(128,134)),lambda n:128 if n<=2 else 129 if n<=14 else 130 if n<=34 else 131 if n<=47 else 132 if n<=61 else 133)
x,h=s.symbols('x h',real=True)
def add(n,st,steps,ans,check,parts=()):return D.add(n,('도함수와 고계도함수','The derivative as a function'),st,('접선 기울기의 부호·크기를 읽거나 차분몫의 극한을 계산한다.','Read the sign and size of tangent slopes, or calculate a difference-quotient limit.'),steps,ans,check,parts)
def same(z):return (d(z),d(z))
def fplot(n,fs,bounds,title='Blue: f; red: derivative'):
 D.fig(n,[panel(title,bounds,[samples(s.lambdify(x,f,'math'),bounds[0],bounds[1])for f in fs])])
for n,p,pts in [(17,2,[0,s.Rational(1,2),1,2]),(18,3,[0,s.Rational(1,2),1,2,3])]:
 f=x**p;der=p*x**(p-1);q=s.expand(((x+h)**p-x**p)/h)
 pos=', '.join(str(z)+': '+str(der.subs(x,z))for z in pts);neg=', '.join(str(-z)+': '+str(der.subs(x,-z))for z in pts[1:])
 add(n,('함수 '+m('f(x)=x^'+str(p))+'를 확대하여 (a)x='+','.join(map(str,pts))+'에서 기울기를 추정하고 (b)그 음수 위치의 기울기를 구하라. '+('(c)도함수 식을 추측하고 (d)정의로 증명하라.'if n==17 else'(c)추정 도함수 그래프를 그리고 (d)식을 추측하고 (e)정의로 증명하라.'),'Zoom into '+m('f(x)=x^'+str(p))+' to estimate slopes (a)at x='+','.join(map(str,pts))+' and (b)at the corresponding negative arguments. '+('(c)Conjecture a derivative formula and (d)prove it from the definition.'if n==17 else'(c)Sketch the derivative, (d)conjecture its formula, and (e)prove it from the definition.')),[(f'(a)위치:기울기는 {pos}. (b){neg}.',f'(a)Argument:slope pairs are {pos}. (b){neg}.'),same(r'\frac{f(x+h)-f(x)}h='+tex(q)+r'\longrightarrow'+tex(der))],d(r'f\prime(x)='+tex(der)),('확대 접선 '+m('y=a^'+str(p)+'+'+str(p)+'a^{'+str(p-1)+'}(x-a)')+'의 기울기와 차분몫 극한이 일치한다.','The zoomed tangent '+m('y=a^'+str(p)+'+'+str(p)+'a^{'+str(p-1)+'}(x-a)')+' has the same slope as the difference-quotient limit.'),list('abcd'if n==17 else'abcde'))
 panels=[panel('Blue: function; red: derivative',(-3.2,3.2,-5,15),[samples(s.lambdify(x,f,'math'),-3.2,3.2),samples(s.lambdify(x,der,'math'),-3.2,3.2)])]
 for z in pts:
  a=float(z);b=a**p;v=p*a**(p-1);w=.03;yr=max(.002,abs(v)*w*1.3)
  panels.append(panel(f'Zoom at x={a:g}: curve and tangent',(a-w,a+w,b-yr,b+yr),[samples(lambda t:t**p,a-w,a+w),[(a-w,b-v*w),(a+w,b+v*w)]]))
 D.fig(n,panels)
M,B=s.symbols('m b',real=True)
forms={19:3*x-8,20:M*x+B,21:s.Rational(5,2)*x*x+6*x,22:4+8*x-5*x*x,23:4*x**3+3*x,24:x**3-5*x+1,25:1/(x*x-4),26:x/(x+2),27:(x+1)/(4*x-1),28:x**4,29:1/s.sqrt(1+x),30:1/(1+s.sqrt(x))}
for n,f in forms.items():
 var={21:'t',23:'p',24:'t',26:'v',27:'u'}.get(n,'x');name={23:'A',24:'F',26:'F',27:'g',30:'g'}.get(n,'f');der=s.factor(s.diff(f,x));q=s.factor((f.subs(x,x+h)-f)/h)
 def tx(z):return tex(z).replace('x',var)
 if n==29:work=r'\frac{f(x+h)-f(x)}h=-\frac1{\sqrt{1+x+h}\sqrt{1+x}(\sqrt{1+x+h}+\sqrt{1+x})}'
 elif n==30:work=r'\frac{g(x+h)-g(x)}h=-\frac1{(\sqrt{x+h}+\sqrt x)(1+\sqrt{x+h})(1+\sqrt x)}'
 else:work=r'\frac{'+name+'('+var+'+h)-'+name+'('+var+r')}h='+tx(q)
 dom=r'\mathbb R';ddom=dom;extra=('이 다항식은 모든 실수에서 정의되고 차분몫 극한도 유한하다.','This polynomial and its finite difference-quotient limit are defined for every real argument.')
 if n in [25,26,27]:
  excluded={25:r'\{-2,2\}',26:r'\{-2\}',27:r'\{1/4\}'}[n];dom=ddom=r'\mathbb R\setminus'+excluded;extra=('분모가 0인 값은 원함수와 도함수에서 모두 제외한다.','Exclude zeros of the denominator from both the function and derivative domains.')
 if n==29:dom=ddom=r'(-1,\infty)';extra=('제곱근이 분모이므로 1+x>0이어야 한다.','The square root is in a denominator, requiring 1+x>0.')
 if n==30:dom=r'[0,\infty)';ddom=r'(0,\infty)';extra=('0에서 오른쪽 차분몫은 −1/[√h(1+√h)]→−∞이므로 유한 도함수가 없다.','At zero the right difference quotient is −1/[√h(1+√h)]→−∞, so no finite derivative exists.')
 add(n,('함수 '+m(name+'('+var+')='+tx(f))+'의 도함수를 정의로 구하고 함수와 도함수의 정의역을 각각 쓰라.','Use the definition to differentiate '+m(name+'('+var+')='+tx(f))+' and state the domains of both the function and its derivative.'),[same(work),('h→0으로 보내면 '+m(name+r'\prime('+var+')='+tx(der))+'이다.','Taking h→0 gives '+m(name+r'\prime('+var+')='+tx(der))+'.'),extra],d(name+r'\prime('+var+')='+tx(der)+r',\quad D_{'+name+'}='+dom+r',\quad D_{'+name+r'\prime}='+ddom),('정의의 극한과 독립 기호 미분이 일치하며 '+('근호·분모 조건도 별도로 확인했다.'if n>=25 else'전개한 차분몫에 h=0을 대입해 같은 식을 얻는다.'),'The defining limit agrees with independent symbolic differentiation; '+('radical and denominator restrictions were checked separately.'if n>=25 else'setting h=0 in the expanded quotient gives the same expression.')))
for n,f,bounds in [(31,1+s.sqrt(x+3),(-2.99,6,-.5,5)),(32,x+1/x,(-4,4,-6,6)),(33,x**4+2*x,(-2,2,-8,18))]:
 der=s.diff(f,x)
 if n==31:work=r'\frac{f(x+h)-f(x)}h=\frac1{\sqrt{x+h+3}+\sqrt{x+3}}\to\frac1{2\sqrt{x+3}}';domain=r'D_f=[-3,\infty),\ D_{f\prime}=(-3,\infty)';desc=('√x를 왼쪽 3, 위로 1만큼 평행이동하면 원함수이다. 증가하면서 오목 아래이고, 도함수는 양수이며 감소한다.','Translate √x three units left and one up. The function increases concave down; its derivative is positive and decreasing.')
 elif n==32:work=r'\frac{f(x+h)-f(x)}h=1-\frac1{x(x+h)}\to1-\frac1{x^2}';domain=r'D_f=D_{f\prime}=\mathbb R\setminus\{0\}';desc=('0 양쪽 점근선과 x=±1의 수평 접선을 먼저 표시한다. 도함수는 |x|>1에서 양수, 0<|x|<1에서 음수이다.','Mark the asymptote at zero and horizontal tangents at ±1. The derivative is positive for |x|>1 and negative for 0<|x|<1.')
 else:work=r'\frac{f(x+h)-f(x)}h=4x^3+6x^2h+4xh^2+h^3+2\to4x^3+2';domain=r'D_f=D_{f\prime}=\mathbb R';desc=('곡선의 최소점 x=−∛(1/2)에서 기울기가 0이고 왼쪽은 음수, 오른쪽은 양수이다.','The slope vanishes at the minimum x=−∛(1/2), is negative to its left, and positive to its right.')
 add(n,('함수 '+m('f(x)='+tex(f))+'에 대해 (a)함수 그래프, (b)기울기로 예상한 도함수 그래프, (c)정의로 구한 도함수와 두 정의역, (d)계산한 도함수 그래프와 예상의 비교를 제시하라.','For '+m('f(x)='+tex(f))+' give (a)a graph, (b)a derivative sketch inferred from slopes, (c)the derivative from its definition and both domains, and (d)a comparison of the calculated derivative graph with the prediction.'),[desc,same(work)],d(r'f\prime(x)='+tex(der)+r';\quad '+domain),('도함수의 영점·부호와 원함수의 수평 접선·증감을 대조했다.','Compared derivative zeros and signs with horizontal tangents and monotonicity of the original curve.'),list('abcd'))
 if n==32:D.fig(n,[panel('Blue: f; red: derivative',bounds,[{'points':samples(s.lambdify(x,z,'math'),a,b),'color':c}for z,c in [(f,'#1d4ed8'),(der,'#dc2626')]for a,b in [(-4,-.04),(.04,4)]])])
 else:fplot(n,[f,der],bounds)
for n,ts,ys,unit in [(34,[2000,2002,2004,2006,2008,2010,2012,2014],[5500,4897,7470,9138,10897,11561,13035,13945],'thousands/year'),(35,[14,21,28,35,42,49],[41,54,64,72,78,83],'ft/year'),(36,[15.5,17.7,20,22.4,24.4],[37.2,31,19.8,9.7,-9.8],'g/degree C')]:
 rates=[(ys[min(i+1,len(ts)-1)]-ys[max(i-1,0)])/(ts[min(i+1,len(ts)-1)]-ts[max(i-1,0)])for i in range(len(ts))]
 context={34:('연도별 성형시술 건수 N(천 건)','annual cosmetic-procedure count N (thousands)'),35:('소나무 나이 t(년)에 따른 높이 H(ft)','pine-tree height H (ft) at age t (years)'),36:('수온 x(°C)에 따른 24일간 송어 체중 증가량 W(g)','trout weight gain W (g) over 24 days at temperature x (°C)')}[n]
 table='; '.join(f'{a:g}: {b:g}'for a,b in zip(ts,ys));out='; '.join(f'{a:g}: {b:.3f}'for a,b in zip(ts,rates))
 st=(context[0]+' 자료(입력:출력)는 '+table+'이다. 변화율 표와 그래프를 구성하라.'+( '(a)N′의 의미, (b)추정 표, (c)N과 N′ 그래프, (d)정확도를 높이는 방법을 설명하라.'if n==34 else' 변화율의 단위도 쓰라.'), 'Data for '+context[1]+' (input:output) are '+table+'. Construct an estimated rate table and graph.'+(' Address (a)the meaning of N′, (b)estimates, (c)graphs of N and N′, and (d)how to improve the estimates.'if n==34 else' State the units of the rate.'))
 steps=[('내부 표점에는 양옆 표점의 할선 기울기, 양 끝에는 인접한 한 구간 기울기를 사용한다.','At interior entries use the secant through the two neighboring data points; use an adjacent secant at each endpoint.'),same(r'F\prime(t_i)\approx\frac{F(t_{i+1})-F(t_{i-1})}{t_{i+1}-t_{i-1}}'),('추정값(입력:변화율)은 '+out+'이다.','Estimated input:rate pairs are '+out+'.')]
 if n==34:steps.append(('N′은 연간 시술 건수의 변화율(천 건/년)이다. 더 촘촘하고 정확한 원자료를 얻으면 국소 변화율을 더 잘 추정한다.','N′ is the change in annual procedure count, in thousands per year. More closely spaced, accurate observations improve local rate estimates.'))
 if n==36:steps.append(('표 간격이 일정하지 않으므로 각 실제 온도차로 나눈다. 가운데 온도와 할선의 중점이 약간 다르므로 이는 단순 국소 근사이다.','The spacing is unequal, so divide by each actual temperature difference. An interior temperature is not exactly the midpoint of its two neighbors, making this a simple local approximation.'))
 add(n,st,steps,(out+'; 단위 '+unit+'.',out+'; units '+unit+'.'),('첫 구간의 차분비 '+f'({ys[1]}−({ys[0]}))/({ts[1]}−{ts[0]})≈{rates[0]:.3f}'+'를 직접 대조했다. 선분은 표점을 잇는 안내선이며 정확한 연속 모형을 뜻하지 않는다.','Directly checked the first secant '+f'({ys[1]}−({ys[0]}))/({ts[1]}−{ts[0]})≈{rates[0]:.3f}'+'. Connecting segments are visual guides, not an exact continuous model.'),list('abcd')if n==34 else())
 D.fig(n,[panel('Observed values (segments are guides)',(ts[0],ts[-1],min(0,min(ys)*1.2),max(ys)*1.1),[list(zip(ts,ys))],list(zip(ts,ys)),xticks=ts),panel('Estimated derivative (secant method)',(ts[0],ts[-1],min(0,min(rates)*1.2),max(0,max(rates)*1.2)),[list(zip(ts,rates))],list(zip(ts,rates)),xticks=ts,ylabel=unit)])
add(37,('P(t)는 2020년1월1일로부터 t년 후 도시 전력에서 태양광이 차지하는 백분율이다. (a)dP/dt의 뜻, (b)P′(2)=3.5의 의미를 설명하라.','P(t) is the percentage of a city’s electricity supplied by solar panels t years after January 1,2020. Interpret (a)dP/dt and (b)P′(2)=3.5.'),[('미분값은 태양광 비중 자체가 아니라 그 비중이 시간에 따라 변하는 속도이다.','The derivative measures how rapidly the solar share changes with time.'),('t=2는 2022년1월1일이며 그 순간 태양광 비중은 연간 약 3.5퍼센트포인트의 속도로 증가한다.','At t=2, January 1,2022, the solar share is increasing at about 3.5 percentage points per year.')],('(a)태양광 비중의 순간변화율; (b)2022년1월1일에 +3.5퍼센트포인트/년.','(a)The instantaneous rate of change of solar share; (b)+3.5 percentage points/year on January 1,2022.'),('P의 단위가 %이므로 변화 단위는 퍼센트포인트/년이다. 상대 증가율 3.5%/년과 구분했다.','Since P is a percentage, its change is measured in percentage points/year; this differs from a 3.5% relative annual growth rate.'),list('ab'))
add(38,('연간 평균 휘발유 가격이 p달러/갤런일 때 미국 내 다른 주로 자동차 휴가를 가는 사람 수를 N(p)라 한다. dN/dp의 예상 부호와 이유를 설명하라.','Let N(p) count people taking interstate car vacations when the annual average gasoline price is p dollars/gallon. What sign would you expect for dN/dp, and why?'),[('다른 조건이 같다면 연료 가격 상승은 자동차 여행 비용을 높여 수요를 줄이는 방향으로 작용한다.','With other conditions held equal, higher fuel prices raise trip costs and tend to reduce demand.')],('보통 dN/dp<0를 예상한다.','Usually one expects dN/dp<0.'),('이는 제시된 경제 모형에서의 방향 예측이며, 자료 없이 실제 연도별 인과관계나 필연적인 부호를 주장하지 않는다.','This is a directional expectation in the stated model, not a data-free claim about actual annual causality or an inevitable sign.'))
for n,f,order in [(51,3*x*x+2*x+1,2),(52,x**3-3*x,2),(53,2*x*x-x**3,4)]:
 fs=[f];steps=[]
 for k in range(1,order+1):
  q=s.expand((fs[-1].subs(x,x+h)-fs[-1])/h);der=s.limit(q,h,0);steps.append(same(r'\frac{f^{('+str(k-1)+r')}(x+h)-f^{('+str(k-1)+r')}(x)}h='+tex(q)+r'\longrightarrow '+tex(der)));fs.append(der)
 add(n,('함수 '+m('f(x)='+tex(f))+'에서 '+('정의를 반복 적용하여 f′,f″를 구하고 f,f′,f″를 같은 좌표계에 그려 타당성을 확인하라.'if n<53 else'f′,f″,f‴,f⁽⁴⁾를 구하라. f,f′,f″,f‴를 함께 그리고 기하 의미와 비교하라.'),'For '+m('f(x)='+tex(f))+', '+('use successive difference-quotient definitions to find f′ and f″, then graph f,f′,f″ together and assess consistency.'if n<53 else'find f′,f″,f‴,f⁽⁴⁾. Plot the first four functions and compare their geometric interpretations.')),steps, d(r',\quad '.join('f^{('+str(k)+')}(x)='+tex(fs[k])for k in range(1,len(fs)))),('각 다음 도함수의 영점은 이전 그래프의 수평 접선과 일치하고 부호는 이전 함수의 증감과 일치한다. 다항식 차분몫을 직접 전개했다.','Each successive derivative vanishes at horizontal tangents of the preceding curve, and its sign matches that curve’s monotonicity. Polynomial quotients were expanded directly.'))
 fplot(n,fs[:4],(-2.5,3,-15,20),'Blue: f; red: f1; green: f2'+('; purple: f3'if n==53 else''))
add(55,('f(x)=∛x에 대해 (a)a≠0에서 x→a 정의로 f′(a)를 구하고 (b)f′(0)이 없음을 보이며 (c)원점의 접선이 수직임을 설명하라.','For f(x)=∛x, (a)find f′(a) for a≠0 from the x→a definition, (b)show f′(0) does not exist, and (c)justify a vertical tangent at the origin.'),[same(r'\frac{\sqrt[3]x-\sqrt[3]a}{x-a}=\frac1{x^{2/3}+\sqrt[3]{xa}+a^{2/3}}\longrightarrow\frac1{3a^{2/3}}'),same(r'\frac{f(h)-f(0)}h=\frac1{h^{2/3}}\longrightarrow+\infty'),('양쪽 할선의 기울기가 +∞로 커지므로 유한 미분값은 없지만 접선의 방향은 수직 x=0이다.','Secant slopes tend to +∞ from both sides: there is no finite derivative, but the limiting tangent direction is vertical, x=0.')],d(r'f\prime(a)=\frac1{3a^{2/3}}\ (a\ne0);\quad f\prime(0)\text{ undefined};\quad x=0'),('세제곱 차 인수분해를 곱해 원래 분모 x−a가 되는지 확인했다.','Multiplying the cube-difference factorization recovers x−a.'),list('abc'))
D.fig(55,[panel('Cube root and vertical tangent',(-2,2,-2,2),[samples(lambda t:math.copysign(abs(t)**(1/3),t),-2,2),[(0,-2),(0,2)]])])
add(56,('g(x)=x^(2/3)에 대해 (a)g′(0)이 없음을 보이고 (b)a≠0의 g′(a)를 구하라. (c)원점의 수직 접선을 설명하고 (d)그래프로 확인하라.','For g(x)=x^(2/3), (a)show g′(0) is undefined, (b)find g′(a) for a≠0, (c)justify a vertical tangent at the origin, and (d)illustrate it graphically.'),[same(r'\frac{g(h)-g(0)}h=\frac1{\sqrt[3]h}\to-\infty\ (h\to0^-),\ +\infty\ (h\to0^+)'),same(r'\frac{x^{2/3}-a^{2/3}}{x-a}=\frac{\sqrt[3]x+\sqrt[3]a}{x^{2/3}+\sqrt[3]{xa}+a^{2/3}}\to\frac2{3\sqrt[3]a}'),('양쪽에서 기울기의 부호는 반대이지만 접선 직선의 방향은 모두 수직이다. 원점은 뾰족점이며 공통 접선 직선은 x=0이다.','The slopes have opposite infinite signs, but both tangent-line directions are vertical. The origin is a cusp with common tangent line x=0.')],d(r'g\prime(a)=\frac2{3\sqrt[3]a}\ (a\ne0);\quad g\prime(0)\text{ undefined};\quad x=0'),('h=±10⁻⁶의 차분몫은 각각 ±100으로 양쪽 발산 방향을 확인한다.','At h=±10⁻⁶ the quotients are respectively ±100, confirming the directions of divergence.'),list('abcd'))
D.fig(56,[panel('Cusp and vertical tangent',(-2,2,-.3,2),[samples(lambda t:abs(t)**(2/3),-2,2),[(0,-.3),(0,2)]])])
for n in [57,58,59,60]:
 if n==57:
  st=('f(x)=|x−6|이 6에서 미분 불가능함을 보이고 f′ 식과 그래프를 구하라.','Show f(x)=|x−6| is not differentiable at 6; find and graph f′.');steps=[same(r'\frac{f(6+h)-f(6)}h=\frac{|h|}h=\begin{cases}-1&h<0\\1&h>0\end{cases}'),('왼쪽 기울기는 −1, 오른쪽은 1이므로 같지 않다. 나머지 각 열린 구간에서는 직선이다.','The left slope is −1 and the right slope is 1, so they disagree. Each remaining open interval is linear.')];ans=d(r'f\prime(x)=\begin{cases}-1&x<6\\1&x>6\end{cases};\quad D_{f\prime}=\mathbb R\setminus\{6\}');cs=[[(2,-1),(6,-1)],[(6,1),(10,1)]];dots=[(6,-1,'open'),(6,1,'open')];bounds=(2,10,-2,2);fcs=[[(2,4),(6,0),(10,4)]];fb=(2,10,-.5,5);parts=()
 elif n==58:
  st=('최대정수 함수 f(x)=⌊x⌋의 미분 불가능한 곳을 찾고 도함수 식과 그래프를 구하라.','Locate all points where f(x)=⌊x⌋ is not differentiable, and find and graph its derivative.');steps=[('정수 사이에서는 상수이므로 차분몫이 작은 h에 대해 0이다.','Between consecutive integers the function is constant, so its quotient is zero for sufficiently small h.'),('정수 k에서는 왼쪽 극한 k−1과 f(k)=k가 달라 불연속이고 따라서 미분 불가능하다.','At an integer k the left limit k−1 differs from f(k)=k; discontinuity rules out differentiability.')];ans=d(r'f\prime(x)=0\ (x\notin\mathbb Z);\quad D_{f\prime}=\mathbb R\setminus\mathbb Z');cs=[[(i,0),(i+1,0)]for i in range(-3,3)];dots=[(i,0,'open')for i in range(-3,4)];bounds=(-3,3,-1,1);fcs=[[(i,i),(i+1,i)]for i in range(-3,3)];fb=(-3,3,-3,3);parts=()
 elif n==59:
  st=('f(x)=x|x|에 대해 (a)그래프, (b)미분 가능한 모든 x, (c)도함수 식을 구하라.','For f(x)=x|x|, (a)sketch its graph, (b)find where it is differentiable, and (c)give the derivative.');steps=[same(r'f(x)=\begin{cases}-x^2&x<0\\x^2&x\ge0\end{cases}'),same(r'\frac{f(h)-f(0)}h=|h|\to0'),('0 이외에서는 각 이차식의 도함수 −2x 또는 2x를 사용한다.','Away from zero differentiate the appropriate quadratic to obtain −2x or 2x.')];ans=d(r'D_{f\prime}=\mathbb R,\quad f\prime(x)=2|x|');cs=[[(-3,6),(0,0),(3,6)]];dots=[];bounds=(-3,3,-.5,7);fcs=[samples(lambda t:t*abs(t),-3,3)];fb=(-3,3,-10,10);parts=list('abc')
 else:
  st=('g(x)=x+|x|에 대해 (a)그래프, (b)미분 가능한 모든 x, (c)도함수 식을 구하라.','For g(x)=x+|x|, (a)sketch its graph, (b)find where it is differentiable, and (c)give the derivative.');steps=[same(r'g(x)=\begin{cases}0&x\le0\\2x&x>0\end{cases}'),('원점의 왼쪽 차분몫은 0, 오른쪽은 2여서 일치하지 않는다. 다른 점에서는 직선의 기울기를 쓴다.','At the origin the left quotient is zero and the right quotient is two, so they disagree. Elsewhere use each line’s slope.')];ans=d(r'g\prime(x)=\begin{cases}0&x<0\\2&x>0\end{cases},\quad D_{g\prime}=\mathbb R\setminus\{0\}');cs=[[(-3,0),(0,0)],[(0,2),(3,2)]];dots=[(0,0,'open'),(0,2,'open')];bounds=(-3,3,-.5,3);fcs=[[(-3,0),(0,0),(3,6)]];fb=(-3,3,-.5,7);parts=list('abc')
 add(n,st,steps,ans,('경계에서 좌우 차분몫을 별도로 비교했고 열린 구간에서는 직선·다항식 계산으로 확인했다.','Compared one-sided difference quotients at boundaries and checked the open pieces using line or polynomial calculations.'),parts)
 D.fig(n,[panel('Original function',fb,fcs,dots=[(i+1,i,'open')for i in range(-3,3)]+[(i,i)for i in range(-3,3)]if n==58 else[]),panel('Derivative; open circles excluded',bounds,cs,dots)])
add(61,('대칭 정의역에서 미분 가능한 함수에 대해 (a)짝함수의 도함수는 홀함수, (b)홀함수의 도함수는 짝함수임을 증명하라.','For a differentiable function on a symmetric domain, prove that (a)the derivative of an even function is odd and (b)the derivative of an odd function is even.'),[('(a)f(−x)=f(x)이고 h=−k로 치환한다.','(a)Use f(−x)=f(x) and substitute h=−k.'),same(r'f\prime(-x)=\lim_{h\to0}\frac{f(-x+h)-f(-x)}h=-\lim_{k\to0}\frac{f(x+k)-f(x)}k=-f\prime(x)'),('(b)f(−x)=−f(x)를 같은 치환에 적용하면 분자의 부호가 한 번 더 바뀐다.','(b)With f(−x)=−f(x), the same substitution produces an additional minus sign in the numerator.'),same(r'f\prime(-x)=\lim_{k\to0}\frac{-f(x+k)+f(x)}{-k}=f\prime(x)')],('(a)f′(−x)=−f′(x); (b)f′(−x)=f′(x).','(a)f′(−x)=−f′(x); (b)f′(−x)=f′(x).'),('x²→2x와 x³→3x²가 각각의 부호 관계를 예시하며 증명은 임의의 함수에 적용된다.','The examples x²→2x and x³→3x² illustrate each parity relation; the limit proof applies to any such function.'),list('ab'))
add(62,('각 함수에서 f′₋(0),f′₊(0)을 구하고 0에서 미분 가능한지 판단하라. (a)x≤0일 때 0, x>0일 때 x. (b)x≤0일 때 0, x>0일 때 x².','Find f′₋(0),f′₊(0) and decide differentiability at zero: (a)f=0 for x≤0 and f=x for x>0; (b)f=0 for x≤0 and f=x² for x>0.'),[('(a)음의 h에서 차분몫 0/h=0, 양의 h에서 h/h=1이다.','(a)For negative h the quotient is 0/h=0; for positive h it is h/h=1.'),('(b)음의 h에서 0, 양의 h에서 h²/h=h→0이다.','(b)For negative h the quotient is zero; for positive h it is h²/h=h→0.')],('(a)0,1: 미분 불가. (b)0,0: 미분 가능, f′(0)=0.','(a)0,1: not differentiable. (b)0,0: differentiable, f′(0)=0.'),('두 함수 모두 0에서 연속이지만 (a)는 좌우 기울기가 달라 연속성만으로 충분하지 않음을 확인한다.','Both functions are continuous at zero, but the unequal slopes in (a) show why continuity alone is insufficient.'),list('ab'))
add(63,('함수 '+m(r'f(x)=\begin{cases}0&x\le0\\5-x&0<x<4\\1/(5-x)&x\ge4\end{cases}')+'에 대해 (a)4의 좌우 미분계수, (b)그래프, (c)불연속 위치, (d)미분 불가능한 위치를 구하라.','For '+m(r'f(x)=\begin{cases}0&x\le0\\5-x&0<x<4\\1/(5-x)&x\ge4\end{cases}')+' find (a)the one-sided derivatives at 4, (b)a graph, (c)discontinuities, and (d)points of nondifferentiability.'),[('f(4)=1이고 왼쪽 조각도 4에서 극한 1이다. 왼쪽 차분몫은 −1이다.','We have f(4)=1 and the left branch also tends to one; its left difference quotient equals −1.'),same(r'\frac{f(4+h)-f(4)}h=\frac{1/(1-h)-1}h=\frac1{1-h}\to1\quad(h\to0^+)'),('0에서는 오른쪽 극한이 5이고 f(0)=0이어서 점프한다. 5에서는 분모가 0이라 함수가 정의되지 않고 수직 점근선이 있다. 4는 연속이지만 모서리이다.','At zero the right limit is five whereas f(0)=0, giving a jump. At five the denominator vanishes: the function is undefined with a vertical asymptote. At four it is continuous but has a corner.')],('(a)f′₋(4)=−1,f′₊(4)=1. (c)0은 불연속,5는 정의역에서 빠진 수직 특이점. (d)유한 도함수는0,4,5에서 없다(정의역 안에서는0,4).','(a)f′₋(4)=−1,f′₊(4)=1. (c)Discontinuous at zero; five is an excluded vertical singularity. (d)No finite derivative at0,4,5 (within the domain:0,4).'),('4에서 함수값 연결은 5−4=1/(5−4)=1이지만 기울기 −1과1은 다르다.','At four the values match, 5−4=1/(5−4)=1, but the slopes −1 and1 differ.'),list('abcd'))
D.fig(63,[panel('Jump at 0, corner at 4, pole at 5',(-2,8,-7,7),[[(-2,0),(0,0)],[(0,5),(4,1)],samples(lambda t:1/(5-t),4,4.97),samples(lambda t:1/(5-t),5.03,8)],[(0,0),(0,5,'open'),(4,1)],xticks=[0,4,5,8])])
add(64,('뜨거운 수도꼭지를 연 뒤 시간 t에 따른 물 온도를 T(t)라 한다(§1.1 예4). (a)시간에 따른 변화율을 설명하고 (b)T′의 가능한 그래프를 그려라.','Let T(t) be the water temperature after opening a hot-water tap (Example1.1.4). (a)Describe how its rate changes and (b)sketch a possible T′ graph.'),[('처음에는 관에 있던 물이 나와 온도가 거의 일정하므로 T′≈0이다. 뜨거운 물이 도착하면 온도가 올라 T′>0이고, 상승이 가장 빠를 때 T′가 최대이다.','Initially the water already in the pipe has nearly constant temperature, so T′≈0. As hot water arrives, T rises and T′>0, peaking when the warming is fastest.'),('이후 온도가 공급 온도에 가까워져 변화율은 다시 0에 접근한다. 정확한 시간·온도 자료가 없어 그림은 가능한 개략형이다.','As the water approaches the supply temperature, the rate returns toward zero. With no specified numerical data, the graph is qualitative.')],('T′: 거의0 → 양의 봉우리 → 거의0.','T′: near zero → a positive hump → near zero.'),('도함수 아래 넓이는 총 온도 상승과 같고 음의 구간이 없으므로 원함수가 감소하지 않는다.','The area under the derivative is the total temperature rise; a nonnegative derivative makes the temperature nondecreasing.'),list('ab'))
D.fig(64,[panel('Possible warming rate (illustrative time scale)',(0,10,-.1,1.1),[samples(lambda t:math.exp(-((t-4)/1.3)**2),0,10)],xlabel='time',ylabel='temperature / time')],caption=('정성적 변화율 모형이며 실제 초·온도 수치를 지정하지 않는다.','A qualitative rate model; the time and temperature scales are illustrative.'))
add(65,('Nick은 3분간 점점 빠르게 뛰고,5분 걷고,교차로에서2분 멈춘 뒤5분 빠르게 뛰고 마지막4분 걷는다. (a)누적거리 s(t)의 가능한 그래프와 (b)속도 ds/dt 그래프를 그려라.','Nick speeds up while jogging for3 minutes, walks for5, stops at an intersection for2, runs fairly fast for5, and walks for4. Sketch (a)a possible cumulative-distance graph s(t) and (b)its derivative.'),[('구간은[0,3],[3,8],[8,10],[10,15],[15,19]이다. 첫 구간은 양의 증가 속도, 걷기는 작은 양의 속도, 정지는0, 빠른 달리기는 큰 양의 속도로 잡는다.','The intervals are[0,3],[3,8],[8,10],[10,15],[15,19]. Choose increasing positive speed first, low positive speed for walking, zero at rest, and higher speed for the fast run.'),('예를 들어 임의 거리 단위로 속도를 1+t,1,0,4,1로 잡고 각 구간을 적분해 누적거리를 연결한다. 순간 전환은 이상화이며 실제로는 짧게 부드럽게 바뀐다.','For example, in arbitrary distance units choose speeds1+t,1,0,4,1 and integrate each segment to join the distance continuously. Instant changes idealize short smooth transitions.')],d(r's(t)=\begin{cases}t+t^2/2&0\le t\le3\\7.5+(t-3)&3<t\le8\\12.5&8<t\le10\\12.5+4(t-10)&10<t\le15\\32.5+(t-15)&15<t\le19\end{cases}'),('전환점의 누적거리는7.5,12.5,12.5,32.5이며 연속이다. 정지 구간의 거리 증가량은0이다.','The junction distances are7.5,12.5,12.5,32.5 and agree on both sides. Distance does not increase during the stop.'),list('ab'))
cs=[samples(lambda t:t+t*t/2,0,3),[(3,7.5),(8,12.5)],[(8,12.5),(10,12.5)],[(10,12.5),(15,32.5)],[(15,32.5),(19,36.5)]]
D.fig(65,[panel('One possible cumulative distance',(0,19,0,40),cs,xticks=[0,3,8,10,15,19],xlabel='minutes',ylabel='distance (arbitrary)'),panel('Corresponding speed; transition values omitted',(0,19,-.3,5),[[(0,1),(3,4)],[(3,1),(8,1)],[(8,0),(10,0)],[(10,4),(15,4)],[(15,1),(19,1)]],[(3,4,'open'),(3,1,'open'),(8,1,'open'),(8,0,'open'),(10,0,'open'),(10,4,'open'),(15,4,'open'),(15,1,'open')],xticks=[0,3,8,10,15,19],xlabel='minutes',ylabel='distance / minute')])
add(66,('포물선 y=x²의 (1,1) 접선이 양의 x축과 이루는 기울기각 φ를 가장 가까운 도로 구하라.','Find, to the nearest degree, the inclination angle φ of the tangent to y=x² at(1,1).'),[same(r'm=\lim_{h\to0}\frac{(1+h)^2-1}h=2'),same(r'\tan\phi=2,\quad\phi=\arctan2\approx63.435^\circ')],d(r'\phi\approx63^\circ'),('양의 기울기이므로 기울기각은0°와90° 사이에 있으며 tan(63.435°)≈2이다.','The positive slope places the inclination between0° and90°, and tan(63.435°)≈2.'))
# Smooth Hermite interpolation is used only for explicitly labelled graphical sketches.
def hermite(nodes,t,order=0):
 i=max(0,min(len(nodes)-2,next((j-1 for j,z in enumerate(nodes)if z[0]>=t),len(nodes)-2)))
 a,ya,ma=nodes[i];b,yb,mb=nodes[i+1];L=b-a;u=(t-a)/L
 if order==0:return (2*u**3-3*u*u+1)*ya+(u**3-2*u*u+u)*L*ma+(-2*u**3+3*u*u)*yb+(u**3-u*u)*L*mb
 if order==1:return ((6*u*u-6*u)*ya+(3*u*u-4*u+1)*L*ma+(-6*u*u+6*u)*yb+(3*u*u-2*u)*L*mb)/L
 if order==2:return ((12*u-6)*ya+(6*u-4)*L*ma+(-12*u+6)*yb+(6*u-2)*L*mb)/(L*L)
 return (12*ya+6*L*ma-12*yb+6*L*mb)/(L**3)
def hfig(n,nodes,fb,db,xticks=None):
 D.fig(n,[panel('Source-based sketch (approximate)',fb,[samples(lambda t:hermite(nodes,t),fb[0],fb[1],400)],xticks=xticks),panel('Derivative sketch from estimated slopes',db,[samples(lambda t:hermite(nodes,t,1),db[0],db[1],400)],xticks=xticks)],caption=('원본의 정성적 특징과 판독값을 보존한 자체 보간 도해. 정확한 원함수 식을 주장하지 않는다.','An original interpolated sketch preserving source features and readings, not an asserted exact source formula.'))
for n,ts,vals,slopes in [(1,list(range(9)),[2.15,2.45,2,.7,-.7,-1.25,-.8,.4,1.2],[.5,0,-1,-1.5,-1,0,1,1.2,.5]),(2,list(range(-4,5)),[.4,-1.25,-1.65,-1.4,-.55,1.65,3.45,2.65,1.2],[-2,-1,0,.4,1.3,3,0,-1.5,-1])]:
 targets=list(range(8))if n==1 else list(range(-3,4));ans=', '.join(f'f′({a})≈{slopes[ts.index(a)]:g}'for a in targets)
 add(n,('원본 격자 곡선에서 '+','.join('f′('+str(a)+')'for a in targets)+'를 순서대로 추정하고 f′ 그래프를 그려라. 자체 도해의 위 패널은 원본 곡선의 근사 재구성이다.','Estimate '+','.join('f′('+str(a)+')'for a in targets)+' in order from the source grid curve, then sketch f′. The upper panel reconstructs the source approximately.'),[('각 점의 접선에 작은 수평 이동을 잡고 그에 따른 수직 이동을 나눈다. 극대·극소점은 기울기0이다.','At each point divide the rise along the tangent by a small horizontal run. Slopes vanish at local maxima and minima.'),(ans,ans),('도함수 점들을 원함수의 증감·굽음에 맞춰 부드럽게 연결한다. 수치는 대략 ±0.2–0.3 수준의 그래프 추정이다.','Connect the derivative estimates smoothly while respecting the original monotonicity and curvature. Numerical slopes carry roughly ±0.2–0.3 graphical uncertainty.')],ans,('도함수 영점 '+('1,5'if n==1 else'−2,2')+'는 원본의 극값 위치와 일치하고 증가/감소 구간에서 도함수 부호도 일치한다.','The derivative zeros '+('1,5'if n==1 else'−2,2')+' match the original extrema, and derivative signs agree with increase/decrease.'),list('abcdefgh'if n==1 else'abcdefg'))
 hfig(n,list(zip(ts,vals,slopes)),(ts[0],ts[-1],-2,4),(ts[0],ts[-1],-2.5,3.5),ts)
add(3,('네 함수 그림을 네 도함수 그림I–IV와 연결하라. (a)감소–증가–감소인 삼차형, (b)상승–하강–상승의 직선 조각, (c)0 아래의 골짜기와 수평에 가까운 양끝, (d)양쪽 극대와 중앙 극소가 있는 뒤집힌 W형이다. 도함수 후보는I(음수 골–0–양수 봉),II(아래로 열린 포물선),III(세 영점의 음의 삼차형),IV(양·음·양 상수 조각)이다.','Match four function sketches with derivative sketches I–IV: (a)a decreasing–increasing–decreasing cubic shape, (b)rising–falling–rising line pieces, (c)a negative valley flattening at both ends, (d)an inverted W with two maxima and a central minimum. The candidates are I(negative trough then positive hump),II(downward parabola),III(negative cubic with three zeros),IV(positive–negative–positive constant pieces).'),[('(a)의 두 극값은II의 두 영점과 맞는다. (b)의 일정한 구간 기울기는IV이고 모서리에서는 빠진 점이다.','The two extrema of(a)match the two zeros ofII. Constant piecewise slopes in(b)giveIV, with corner arguments omitted.'),('(c)는 왼쪽 감소·오른쪽 증가이며 양끝 기울기0이므로I이다. (d)는 부호가 +,−,+,−로 바뀌므로III이다.','Curve(c)decreases left, increases right, and flattens at both ends, givingI. Curve(d)has derivative signs +,−,+,−, givingIII.')],('(a)II; (b)IV; (c)I; (d)III.','(a)II; (b)IV; (c)I; (d)III.'),('각 대응에서 함수 극값과 도함수 영점, 직선 모서리와 도함수 구멍을 함께 대조했다.','For every match, checked function extrema against derivative zeros, and line corners against missing derivative values.'),list('abcd'))
D.fig(3,[panel('a with II (red)',(-2,2,-3,3),[samples(lambda t:2*t-t**3,-2,2),samples(lambda t:2-3*t*t,-2,2)]),panel('b with IV (red)',(-2,2,-2,2),[[(-2,0),(-1,1),(1,-1),(2,0)],{'points':[(-2,1),(-1,1)],'color':'#dc2626'},{'points':[(-1,-1),(1,-1)],'color':'#dc2626'},{'points':[(1,1),(2,1)],'color':'#dc2626'}]),panel('c with I (red)',(-3,3,-1.2,1),[samples(lambda t:-1/(1+t*t),-3,3),samples(lambda t:2*t/(1+t*t)**2,-3,3)]),panel('d with III (red)',(-1.7,1.7,-3,3),[samples(lambda t:2*t*t-t**4,-1.7,1.7),samples(lambda t:4*t-4*t**3,-1.7,1.7)])],caption=('정성적 대응을 보여 주는 자체 예시 곡선이며 원본의 정확한 식은 아니다.','Original illustrative curves show the qualitative correspondence; they are not exact source formulas.'))
# The unticked source axes in 4–11 specify shapes, not unique analytic formulas.
shapes={
4:('원점을 중심으로 대칭인 완만한 골짜기: 왼쪽 감소, 원점 최소, 오른쪽 증가, 양끝은 거의 수평.','A symmetric smooth valley: decreasing on the left, minimal at zero, increasing on the right, and almost flat at both ends.','f′은 왼쪽 음수 봉우리 아래, 원점0, 오른쪽 양수 봉우리 위이며 양끝에서0에 접근한다.','The derivative has a negative trough left, zero at the origin, a positive hump right, and tends toward zero at the ends.'),
5:('두 골짜기와 중앙의 작은 봉우리가 있는 매끈한 W형.','A smooth W with two minima and a small central maximum.','세 극값에서 f′=0이고 부호는 차례로 −,+,−,+이다.','The derivative vanishes at the three extrema and has successive signs −,+,−,+.'),
6:('왼쪽 양의 봉우리, 원점 부근 급하강, 오른쪽 음의 골짜기, 양끝에서0에 접근.','A positive left hump, steep descent near zero, a negative right trough, and flattened tails approaching zero.','f′의 부호는 +,−,+이며 원함수의 두 극값에서0이다. 중앙에 음의 깊은 골이 생긴다.','Derivative signs are +,−,+ with zeros at the two extrema and a deep negative central trough.'),
7:('원점 중심의 위쪽 반원.','An upper semicircle centered at the origin.','반지름을 r라 하면 f′=−x/√(r²−x²). 왼쪽 양수, 중앙0, 오른쪽 음수이며 끝점에서 유한 도함수는 없다.','With radius r, f′=−x/√(r²−x²). It is positive left, zero centrally, negative right, and has no finite endpoint derivatives.'),
8:('왼쪽에서 증가하다 잠시 수평으로 평평해진 뒤 다시 증가하여 오른쪽 봉우리를 지나 감소하고 평평해진다.','Increasing from the left, flattening briefly at a stationary shoulder, increasing again to a right-hand maximum, then decreasing and flattening.','f′은 먼저 양의 봉우리, 어깨에서0, 다시 양의 봉우리, 최대점에서0, 이후 음의 골을 거쳐0에 접근한다.','The derivative forms a positive hump, touches zero at the shoulder, forms another positive hump, crosses zero at the maximum, then makes a negative trough approaching zero.'),
9:('왼쪽 포물선 모양 골짜기가 상승하여 모서리를 만든 뒤 일정 기울기로 하강하는 직선에 연결된다.','A left parabolic-looking valley rises to a corner, followed by a line descending at constant slope.','포물선 부분의 f′은 증가하여 최소점에서0을 통과한다. 모서리에서 정의되지 않고 이후 일정한 음수이다.','On the curved part f′ increases through zero at the minimum. It is undefined at the corner and constant negative thereafter.'),
10:('직선 조각이 하강–상승–수평–하강–상승–수평–하강의 순서로 연결된다.','Line segments follow descending–ascending–horizontal–descending–ascending–horizontal–descending in order.','구간별 도함수는 −,+,0,−,+,0,−의 상수이며 모든 연결 모서리에서 빠진다.','The derivative is piecewise constant with signs −,+,0,−,+,0,− and is undefined at every corner.'),
11:('양끝은 평평하고 오른쪽으로 조금 치우친 중앙에서 수직 방향으로 매우 가파르게 내려가는 곡선.','A decreasing curve with flat tails and an extremely steep vertical direction slightly right of the center.','f′은 음수이다. 수직 접선 위치 c에서 양쪽으로 −∞가 되어 유한 도함수가 없고 멀어질수록0에 접근한다.','The derivative is negative, tends to −∞ on both sides of the vertical tangent c, and tends toward zero away from it; no finite derivative exists at c.')}
for n,(ko,en,ak,ae) in shapes.items():
 add(n,('원본 모양: '+ko+' 같은 축척으로 f를 재구성하고 그 아래에 f′를 그려라.','Source shape: '+en+' Reconstruct f using equally scaled axes and sketch f′ below it.'),[('수평 접선의 x좌표를 도함수의 영점으로 옮기고 상승·하강 구간을 각각 양·음으로 표시한다. 모서리와 수직 접선에서는 유한 도함수를 지정하지 않는다.','Transfer horizontal-tangent arguments to derivative zeros and mark increasing/decreasing portions positive/negative. Do not assign finite derivatives at corners or vertical tangents.'),(ak,ae)],(ak,ae),('축에 수치가 없는 정성 문제이므로 자체 도해의 수치는 위치·크기를 정규화한 예시이다. 도함수 부호와 모든 극값/모서리를 원본과 대조했다.','The source axes have no numerical ticks, so numbers in the original illustration normalize position and scale. Checked derivative signs and all extrema/corners against the source.'))
 if n in [4,5,6,7]:
  f={4:-s.cos(x),5:x*x+s.exp(-4*x*x)-s.Rational(4,5),6:-x*s.exp(-x*x),7:s.sqrt(1-x*x)}[n];der=s.diff(f,x);lo,hi=(-math.pi,math.pi)if n==4 else(-2,2)if n in [5,6]else(-.999,.999);yb=(-1.5,3.5)if n==5 else(-1.5,1.5)
  D.fig(n,[panel('Qualitative function (normalized scale)',(lo,hi,*yb),[samples(s.lambdify(x,f,'math'),lo,hi,400)]),panel('Corresponding derivative',(lo,hi,-4,4),[samples(s.lambdify(x,der,'math'),lo,hi,400)])],caption=('원본의 정성적 모양을 따르는 자체 예시 함수와 그 도함수.','An original example matching the qualitative source shape, with its derivative.'))
 elif n==8:hfig(n,[(-3,-.6,0),(-1.2,.55,0),(.8,1.55,0),(3,.35,0)],(-3,3,-1,2),(-3,3,-1,1.5))
 elif n==9:D.fig(n,[panel('Function with a corner at x=1',(-3,3,-1,3),[samples(lambda t:(t+1)**2/2-.5,-3,1),[(1,1.5),(3,0)]]),panel('Derivative with excluded corner',(-3,3,-3,3),[[(-3,-2),(1,2)],[(1,-.75),(3,-.75)]],[(1,2,'open'),(1,-.75,'open')])])
 elif n==10:
  knots=[(-3,1),(-2.2,-.8),(-1.5,1),(-.5,1),(.35,-.8),(1.1,1),(2,1),(2.8,-.8)];cs=[];dots=[]
  for (a,b),(c,e)in zip(knots,knots[1:]):v=(e-b)/(c-a);cs.append([(a,v),(c,v)]);dots.extend([(a,v,'open'),(c,v,'open')])
  D.fig(n,[panel('Piecewise linear source shape',(-3,3,-1,1.5),[knots]),panel('Piecewise constant derivative',(-3,3,-3,3),cs,dots)])
 else:
  fn=lambda t:1-math.atan(math.copysign(abs(t-.3)**(1/3),t-.3));de=lambda t:-1/(3*abs(t-.3)**(2/3)*(1+abs(t-.3)**(2/3)))
  D.fig(n,[panel('Decreasing curve with vertical tangent',(-3,3,-.2,2.5),[samples(fn,-3,3,600)]),panel('Negative derivative; pole at c=0.3',(-3,3,-5,.2),[samples(de,-3,.299,300),samples(de,.301,3,300)])],caption=('수직 접선 c의 위치는 정규화한 자체 예시이다.','The vertical-tangent location c is normalized in this original example.'))
add(12,('배양 효모의 P(t) 그래프는 처음 느리게 증가하다 약6시간 부근에서 가장 가파르고,15시간 무렵 약700개로 평평해진다. P′ 그래프를 그리고 집단 성장의 의미를 설명하라.','The yeast population P(t) initially grows slowly, steepens most around6 hours, and levels off near700 cells by15 hours. Sketch P′ and interpret the population growth.'),[('P가 증가하므로 P′>0이다. 가장 가파른6시간 부근에서 성장률이 최대이며 양끝에서는 작은 양수이다.','Since P increases, P′ is positive. Its maximum occurs near the steepest ascent around6 hours, with small positive rates at either end.'),('따라서 P′은 한 개의 양의 종 모양 봉우리이다. 원본의 기울기 추정으로 최대 성장률은 대략100개/시간 정도이다.','Thus P′ has a single positive bell-shaped hump. Reading the source slopes gives a maximum rate on the order of100 cells/hour.')],('성장률은 증가하다 약6시간에서 최대, 이후 감소하여0에 접근한다.','The growth rate rises to a maximum near6 hours, then declines toward zero.'),('700개에 가까워질 때 인구가 감소하는 것이 아니라 증가 속도가 감소한다. 도함수 단위는 개/시간이다.','Near700 cells the population does not fall; its growth rate declines. The derivative has units cells/hour.'))
P=lambda t:700/(1+math.exp(-.6*(t-6)));Pd=lambda t:.6*P(t)*(1-P(t)/700)
D.fig(12,[panel('Illustrative population matching the source',(0,16,0,750),[samples(P,0,16)],xlabel='hours',ylabel='cells'),panel('Illustrative growth rate',(0,16,0,120),[samples(Pd,0,16)],xlabel='hours',ylabel='cells/hour')],caption=('정성적 원본 특징에 맞춘 로지스틱 예시. 정확한 원자료 적합식은 아니다.','A logistic illustration matching the qualitative source features, not an exact fit to source data.'))
add(13,('충전 비율 C(t)의 원본 그래프는0에서 시작해 처음 빠르게 증가하고,시간이 지나며 완만해져12시간 무렵100%에 접근한다. (a)C′의 의미, (b)C′ 그래프와 그 해석을 제시하라.','The charge percentage C(t) starts at zero, rises quickly, then flattens toward100% by about12 hours. Give (a)the meaning of C′ and (b)a derivative sketch with interpretation.'),[('C′은 충전 비율이 시간당 얼마나 증가하는지를 나타내며 단위는 퍼센트포인트/시간이다.','C′ measures how quickly the charge percentage increases, in percentage points/hour.'),('원본의 모든 접선은 양의 기울기이고 그 기울기가 줄어든다. 따라서 C′은 양수인 감소 곡선으로0에 접근한다.','All source tangents have positive but diminishing slopes, so C′ is a positive decreasing curve approaching zero.')],('C′>0, 시간이 지날수록 감소하여0에 접근: 처음 빠르게, 완충에 가까울수록 느리게 충전된다.','C′>0 and decreases toward zero: charging is fastest initially and slows near full capacity.'),('원본 C가 증가·오목 아래라는 두 특징이 각각 C′의 양수·감소에 대응한다.','The source’s increase and concavity down correspond respectively to positivity and decrease of C′.'),list('ab'))
D.fig(13,[panel('Possible charging rate (illustrative)',(0,12,0,45),[samples(lambda t:40*math.exp(-t/2.5),0,12)],xlabel='hours',ylabel='percentage points/hour')],caption=('원본 형태에 맞춘 지수 감소 도해이며 초기 속도40은 예시값이다.','An exponential-decay illustration of the source shape; the initial rate40 is illustrative.'))
add(14,('연비 F(v)(mi/gal) 그래프는 속도 약5mph에서11,30mph에서28.5,50mph에서최대30,75mph에서23 정도이다. (a)F′의 뜻, (b)도함수 그래프, (c)주어진 그래프에서 가장 효율적인 속도를 구하라.','The fuel-economy graph F(v)(mi/gal) gives roughly11 at5mph,28.5 at30mph, a maximum30 near50mph, and23 at75mph. Find (a)the meaning of F′, (b)a derivative sketch, and (c)the most efficient speed indicated by this graph.'),[('F′은 속도가1mph 변할 때 연비가 얼마나 변하는지 나타내는 국소 비율이다. 단위는 (mi/gal)/(mi/hour)=hour/gal이다.','F′ is the local change in mileage per1mph change in speed. Its units are(mi/gal)/(mi/hour)=hour/gal.'),('50mph 전에는 대체로 양수,50 근처에서는0,그 이후는 음수이다. 최대 연비의 위치를 읽는다.','It is positive before about50mph, zero near50, and negative afterward. Read the location of maximum mileage.')],('(c)교재 그래프에서 약50mph.','(c)About50mph according to the textbook graph.'),('최적 위치는 가장 큰 도함수가 아니라 도함수가 양에서 음으로 바뀌는 최대점이다.','The optimum occurs at the maximum where the derivative changes from positive to negative, not where the derivative is largest.'),list('abc'))
hfig(14,[(5,11,1.1),(20,25,.45),(30,28.5,.12),(50,30,0),(60,28.7,-.25),(75,23,-.35)],(5,75,0,35),(5,75,-.5,1.3),[10,20,30,40,50,60,70])
add(15,('미시간호 평균 표면 수온 f(t)(°F)의 연간 그래프에서 t=0은1월1일이다. 온도는 처음40에서 약2개월에35로 하락,약7.5개월에70까지 상승,12개월에40으로 감소한다. f′를 그리고 f′가 최대인 때를 추정하라.','For the annual Lake Michigan surface-temperature graph f(t)(°F), t=0 is January1. The curve falls from about40 to35 around month2, rises to70 near month7.5, then falls to40 by month12. Sketch f′ and estimate when it is largest.'),[('온도가 가장 낮은2개월 부근과 가장 높은7.5개월 부근에서 f′≈0이다. 그 사이는 양수이고 밖에서는 음수이다.','The rate is near zero at the temperature minimum around month2 and maximum around month7.5. It is positive between them and negative outside.'),('가장 가파른 상승은 약5.5개월,즉6월 중순 부근이다. 이는 최고 온도 시기보다 먼저이다.','The steepest rise is around month5.5, approximately mid-June, before the temperature maximum.')],('f′ 최대: t≈5.5개월(약6월 중순,그림 판독 ±0.5개월).','Maximum f′: t≈5.5 months (about mid-June, with roughly±0.5 month graphical uncertainty).'),('최대 온도에서 f′는0이고,가장 빠른 온도 상승 시기에서 f′가 양의 최대라는 구별을 확인했다.','Checked the distinction between zero rate at maximum temperature and a positive maximum rate during the fastest warming.'))
hfig(15,[(0,40,-4),(2,35,0),(4,39,5),(5.5,55,15),(7.5,70,0),(9,58,-10),(12,40,-3)],(0,12,30,75),(0,12,-12,18),list(range(0,13,2)))
add(16,('사인 함수의 그래프를 정확히 그리고 그 아래 접선 기울기로 도함수 그래프를 구성하라. 도함수의 식을 추측하라.','Carefully graph sine and construct its derivative graph below from tangent slopes. Conjecture the derivative formula.'),[('0의 기울기는1,π/2의 기울기는0,π의 기울기는−1,3π/2의 기울기는0이다. 이후2π마다 반복된다.','The slopes at0,π/2,π,3π/2 are1,0,−1,0, repeating every2π.'),same(r'\frac{\sin(x+h)-\sin x}h=\sin x\frac{\cos h-1}h+\cos x\frac{\sin h}h\to\cos x')],d(r'\frac{d}{dx}\sin x=\cos x'),('덧셈공식과 sin h/h→1,(cos h−1)/h→0으로 그래프 추측을 독립 검산했다.','The addition identity and standard sine/cosine limits independently verify the graphical conjecture.'))
D.fig(16,[panel('Sine',(-2*math.pi,2*math.pi,-1.2,1.2),[samples(math.sin,-2*math.pi,2*math.pi,400)],xlabel='radians'),panel('Derivative: cosine',(-2*math.pi,2*math.pi,-1.2,1.2),[samples(math.cos,-2*math.pi,2*math.pi,400)],xlabel='radians')])
for n,ko,en,ans in [(40,'x=−1에서 곡선 위 열린 점과 다른 높이의 채운 점이 있고 x=2에서 뾰족한 꼭짓점이 있다.','At x=−1 an open curve point is replaced by a filled point at another height; at x=2 the curve has a sharp peak.','-1,2'),(41,'x=1은 수직 점근선, x=5는 곡선이 수직으로 지나가는 접선 위치이다.','There is a vertical asymptote at x=1 and a vertical tangent through the curve at x=5.','1,5'),(42,'x=−2에서 수평 조각이 곡선과 모서리로 만나고 x=1에서 두 열린 가지와 별도 채운 값이 있으며 x=3에서 하강 곡선이 수평 조각과 모서리로 만난다.','A horizontal piece meets a curve at a corner at x=−2; at x=1 two open branches and a separate filled value differ; at x=3 a descending curve joins a horizontal piece with a corner.','-2,1,3')]:
 add(n,('원본 f의 특징: '+ko+' 미분 불가능한 x를 이유와 함께 쓰라.','The source graph has these features: '+en+' State the x-values where f is not differentiable and explain why.'),[('미분 가능하면 연속이어야 하므로 값의 점프·구멍·점근선에서는 유한 미분값이 없다. 모서리에서는 좌우 기울기가 다르고 수직 접선에서는 기울기가 무한대로 발산한다.','Differentiability implies continuity, excluding jumps, holes, and asymptotes. Corners have unequal one-sided slopes, while vertical tangents have unbounded slopes.'),(ko,en)],d('x='+ans),('원본의 이상 위치를 눈금에 맞춰 읽었다. '+('1은 정의역 밖이고5는 함수는 정의되지만 유한 도함수가 없다.'if n==41 else'다른 매끈한 부분에서는 유한 접선이 존재한다.'),'Read each exceptional location against the source ticks. '+('One is excluded from the domain, whereas five has a function value but no finite derivative.'if n==41 else'The remaining smooth portions have finite tangents.')))
for n in [43,44]:
 if n==43:
  st=('f(x)=x+√|x|를 그리고 (−1,0)과 원점을 차례로 확대하라. 두 곳의 국소 모양과 미분 가능성을 비교하라.','Graph f(x)=x+√|x| and zoom toward(−1,0) and the origin. Compare their local shapes and differentiability.');steps=[same(r'f\prime(x)=\begin{cases}1-1/(2\sqrt{-x})&x<0\\1+1/(2\sqrt x)&x>0\end{cases}'),('−1에서는 기울기1/2의 직선처럼 보인다. 0에서는 좌측 기울기가−∞,우측이+∞로 발산하는 뾰족점이 남는다.','Near−1 the curve resembles a line of slope1/2. At zero a cusp remains, with left slopes tending to−∞ and right slopes to+∞.')];ans=('x≠0에서 미분 가능, f′(−1)=1/2. 원점에서는 미분 불가능.','Differentiable for x≠0, with f′(−1)=1/2; not differentiable at zero.');fn=lambda t:t+math.sqrt(abs(t));ats=[(-1,0),(0,0)]
 else:
  st=('g(x)=(x²−1)^(2/3)의(1,0),(0,1),(−1,0)을 확대하고 국소 모양을 미분 가능성으로 설명하라.','Zoom into(1,0),(0,1),(−1,0) on g(x)=(x²−1)^(2/3), and explain the local shapes in terms of differentiability.');steps=[same(r'g\prime(x)=\frac{4x}{3\sqrt[3]{x^2-1}}\quad(x\ne\pm1)'),('0에서는 미분값0으로 수평 직선처럼 확대된다. ±1에서는 양쪽 기울기의 절댓값이 무한대로 커지는 뾰족점이 남아 미분 불가능하다.','At zero the derivative is zero and zooming gives a horizontal-line appearance. At±1 cusps remain with unbounded one-sided slopes, so the function is not differentiable.')];ans=('±1에서만 미분 불가능; g′(0)=0.','Nondifferentiable only at±1; g′(0)=0.');fn=lambda t:abs(t*t-1)**(2/3);ats=[(1,0),(0,1),(-1,0)]
 add(n,st,steps,ans,('특이점에서는 좌우 차분몫으로 확인하고,나머지에서는 근호의 실수 정의역과 미분식을 확인했다.','Checked singularities with one-sided quotients, and checked real radical domains and derivative formulas elsewhere.'))
 panels=[panel('Function',(-2,2,-1,4),[samples(fn,-2,2,600)])]
 for a,b in ats:
  for w in [.1,.005]:
   yr=max(abs(fn(a-w)-b),abs(fn(a+w)-b),w)*1.2;panels.append(panel(f'Zoom x={a}, half-width {w}',(a-w,a+w,b-yr,b+yr),[samples(fn,a-w,a+w,300)]))
 D.fig(n,panels)
add(45,('원본의 파란 곡선과 빨간 곡선은 f와 f′이다. 파란 곡선의 극값 위치에서 빨간 곡선이 x축을 지난다. 빨간 곡선은 x=−1에서 음수이고 x=1에서는 골짜기 직후로 상승한다. f′(−1)과 f″(1)을 비교하라.','The blue and red curves are f and f′. The red curve crosses the axis at extrema of the blue curve; it is negative at x=−1 and rising just past its trough at x=1. Compare f′(−1) and f″(1).'),[('극값–영점 대응으로 파란색=f,빨간색=f′이다.','The extrema-to-zeros correspondence identifies blue=f and red=f′.'),('f′(−1)은 빨간 곡선의 음의 높이이고 f″(1)은 빨간 곡선의 양의 기울기이다.','f′(−1) is the negative height of the red curve, while f″(1) is its positive slope.')],d(r'f\prime(-1)<f\prime\prime(1)'),('함수값과 기울기를 혼동하지 않고 부호만으로 엄밀히 비교했다.','Compared a curve height with a tangent slope correctly; the opposite signs settle the inequality.'))
add(46,('원본의 빨간 곡선과 파란 곡선은 f와 f′이다. 빨간 곡선의 극값에서 파란 곡선이0이고,파란 곡선은 x=−1에서 양수이며 x=1에서는 양의 봉우리 꼭대기에 가깝다. f′(−1)과 f″(1)을 비교하라.','The red and blue curves represent f and f′. The blue curve vanishes at extrema of the red curve, is positive at x=−1, and is near the top of a positive hump at x=1. Compare f′(−1) and f″(1).'),[('빨간색=f,파란색=f′이다. f′(−1)은 파란 곡선의 높이, f″(1)은 x=1의 파란 접선 기울기이다.','Red=f and blue=f′. The value f′(−1) is a blue-curve height, while f″(1) is its tangent slope at1.'),('동일 축척에서 x=−1의 양의 높이가 x=1의 거의 수평인 작은 양의 기울기보다 크다.','With equal axis scales, the positive height at−1 exceeds the small positive slope of the almost horizontal tangent at1.')],d(r'f\prime(-1)>f\prime\prime(1)'),('확대 원본에서 파란 봉우리 정점은1보다 약간 오른쪽이다. 따라서 f″(1)을0으로 단정하지 않고 높이와 접선 상승비를 비교했다.','In the enlarged source the blue peak is slightly right of1. Thus f″(1) was not assumed exactly zero; the height was compared with the tangent rise/run.'))
for n,ko,en,answer,parts in [
(47,'세 곡선 중 a는 증가하다 완만한 극대 후 조금 감소, b는 양의 봉우리 후 작은 음수, c는 b의 증가 구간에서 양수·감소 구간에서 음수이다.','Among three curves, a rises to a broad maximum then declines slightly; b has a positive hump and a small negative tail; c is positive while b rises and negative while b falls.',r'f=a,\quad f\prime=b,\quad f\prime\prime=c',()),
(48,'a는 원점에 닿는 위로 열린 포물선, b는 수평으로 원점을 지나는 증가 삼차형, c는 양끝 상승하며 중앙이 평평한 골, d는 왼쪽 극대·오른쪽 극소를 갖는 곡선이다.','Curve a is an upward parabola touching the origin; b is an increasing cubic shape with horizontal tangent at zero; c is a flat-bottomed valley with rising ends; d has a left maximum and right minimum.',r'f=d,\quad f\prime=c,\quad f\prime\prime=b,\quad f\prime\prime\prime=a',()),
(49,'위치·속도·가속도의 세 후보 중 c는 S자 증가 후 수평, b는 양의 종 모양, a는 양의 봉우리에서0을 지나 음의 골로 이어진다.','Among position, velocity, and acceleration candidates, c rises sigmoidally to a plateau, b is a positive bell, and a passes from a positive hump through zero to a negative trough.',r's=c,\quad v=b,\quad a_{\rm acceleration}=a',()),
(50,'위치·속도·가속도·jerk 후보 중 d는 증가하는 누적 곡선, c는 양의 완만한 봉우리, b는 먼저 양수이다가 약한 음수, a는 b의 상승 시 양수·하강 시 음수로 진동한다.','Among position, velocity, acceleration, and jerk candidates, d is a rising accumulated curve, c a broad positive hump, b initially positive then slightly negative, and a changes sign with increases and decreases of b.',r's=d,\quad v=c,\quad a_{\rm acceleration}=b,\quad j=a',())]:
 add(n,('원본 도형 설명: '+ko+' 각 곡선의 역할을 정하고 이유를 설명하라.','Source-figure description: '+en+' Identify each curve and explain.'),[('원함수가 증가하는 동안 도함수는 양수이고 극값에서0이다. 이 대응을 순서대로 반복한다.','A derivative is positive while its predecessor increases and vanishes at its extrema; apply this relation successively.'),('각 후보의 영점과 바로 이전 곡선의 수평 접선 위치를 맞춘다. '+('위치의 기울기가 속도,속도의 기울기가 가속도이다.'if n>=49 else'가장 높은 차수까지 부호 변화가 일관되는 순서를 선택한다.'),'Match each candidate’s zeros to horizontal tangents of its predecessor. '+('Position slope is velocity; velocity slope is acceleration.'if n>=49 else'Choose the order consistent with signs through the highest derivative.'))],d(answer),('단순 모양 유사성 외에 증가·감소 부호와 극값–영점의 위치를 두 가지 독립 기준으로 확인했다.','Checked two criteria beyond overall resemblance: monotonicity/sign agreement and matching extrema/zero locations.'),parts)
add(39,('원본 f에는 x=−4의 모서리와 x=0의 점프가 있다. 오른쪽 가지는 약2.5부근에서 매우 가파르게 하강한다. 미분 불가능한 x를 이유와 함께 찾아라.','The source graph has a corner at x=−4 and a jump at x=0; its right branch descends very steeply around2.5. Identify the points of nondifferentiability and explain.'),[('−4에서는 두 접선 기울기가 달라지고,0에서는 왼쪽의 채운 점과 오른쪽 가지의 열린 끝점 높이가 다르다.','At−4 the two one-sided slopes differ; at zero the filled left endpoint and open right-branch endpoint have different heights.'),('오른쪽의 급한 하강은 매끈한 유한 기울기로 그려져 있다. 가파르다는 이유만으로 수직 접선이나 미분 불가능점으로 추가하지 않는다.','The steep descent on the right is drawn smoothly with a finite slope. Steepness alone does not establish a vertical tangent or nondifferentiability.')],d(r'x=-4,\ 0'),('원본 확대 및 독립 교차 판독으로−4의 모서리와0의 불연속만 확인했다.','The enlarged source and independent cross-reading identify only the corner at−4 and discontinuity at zero.'))
add(54,('자동차 위치 s(t) 그래프에서 t는 초,s는ft이다. 곡선은(0,0)에서 완만하게 시작해10초에약150ft,11초에약210ft,15초에약360ft,20초에약490ft이다. (a)속도·가속도 그래프와10초 가속도를 추정하고 (b)10초 jerk와 그 단위를 구하라.','The car-position graph uses seconds for t and feet for s. It starts nearly flat at(0,0), reaching about150ft at10s,210ft at11s,360ft at15s, and490ft at20s. (a)Sketch velocity and acceleration and estimate acceleration at10s. (b)Estimate the jerk at10s and state its units.'),[('s의 접선 기울기를 읽으면 속도는 거의0에서 증가하여10–11초 부근에약55ft/s로 최대가 되고 이후약25–30ft/s로 낮아진다.','Reading tangents to s gives velocity rising from near zero to about55ft/s around10–11s, then dropping toward25–30ft/s.'),('10초는 최대 속도보다 조금 앞이라 가속도는 양수이지만 감소 중이다. 주변 기울기의 차이를 다시 나누면 a(10)≈10ft/s² 정도이다.','At10s velocity is still increasing slightly before its maximum, so acceleration is positive but falling. Differencing neighboring velocity slopes gives roughly a(10)≈10ft/s².'),('가속도의10초 접선 기울기를 추정하면 jerk는 음수이고 대략−10ft/s³ 정도이다. 원본 수작업 곡선을 세 번 미분해 읽는 값은 매우 불안정하므로 넓은 근사 범위만 의미 있다.','The tangent slope of acceleration at10s is negative, giving jerk on the order of−10ft/s³. Reading three derivatives from a hand-drawn curve is unstable, so only a broad estimate is meaningful.')],('(a)a(10)≈10ft/s²(대략5–15); (b)j(10)≈−10ft/s³(대략−20~−5). 정확한 값은 주어진 그림만으로 결정되지 않는다.','(a)a(10)≈10ft/s²(roughly5–15); (b)j(10)≈−10ft/s³(roughly−20 to−5). The drawing does not determine exact values.'),('원본 눈금으로 재보정한 국소4차 적합에서 반폭1.5–3초를 바꾸어 a≈8.5–11,j≈−17~−7을 얻었다. 이는 부호·규모의 검산이고 교재의 정확한 함수 추정은 아니다.','A locally calibrated quartic fit, varying the half-window from1.5 to3 seconds, gives a≈8.5–11 and j≈−17 to−7. This checks sign and scale, not an exact textbook function.'),list('ab'))
# A derivative sketch tied to the graphical estimate; integrate it numerically for position.
velnodes=[(0,0,0),(4,8,3),(7,20,5),(9,41,14),(11,57,-6),(13,43,-7),(16,28,-1),(20,26,0)]
D.fig(54,[panel('Estimated velocity (graphical interpolation)',(0,20,0,65),[samples(lambda t:hermite(velnodes,t),0,20,800)],xlabel='seconds',ylabel='ft/s'),panel('Estimated acceleration; qualitative sketch',(0,20,-12,18),[samples(lambda t:hermite(velnodes,t,1),0,20,800)],xlabel='seconds',ylabel='ft/s^2')],caption=('위치 그래프의 접선 판독을 보간한 예시이며 특히 고계도함수의 수치는 불확실하다.','An interpolation of tangent readings from the position graph; numerical higher derivatives are especially uncertain.'))
# Correct requested subpart scope for 32–33 (two parts, unlike the four-part 31).
for e in D.items:
 if e['number']in[32,33]:
  f=x+1/x if e['number']==32 else x**4+2*x
  e['subparts']=list('ab');e['statement']=pair('함수 '+m('f(x)='+tex(f))+'의(a)도함수를 구하고(b)함수와 도함수 그래프를 비교해 답을 검토하라.','For '+m('f(x)='+tex(f))+', (a)find the derivative and(b)compare the function and derivative graphs to assess the answer.')
# A true semicircle uses equal horizontal and vertical unit scales.
D.fig(7,[panel('Upper semicircle (equal unit scales)',(-52/27,52/27,-.2,1.8),[samples(lambda t:math.sqrt(max(0,1-t*t)),-1,1,400)],[(1,0),(-1,0)],xticks=[-1,0,1],yticks=[0,1]),panel('Derivative; endpoints excluded',(-52/27,52/27,-4,4),[samples(lambda t:-t/math.sqrt(1-t*t),-.999,.999,500)],xticks=[-1,0,1])],caption=('반지름1로 정규화한 반원과 그 도함수. 끝점에서 함수는 정의되지만 유한 도함수는 없다.','A semicircle normalized to radius1 and its derivative. The endpoints belong to the function but have no finite derivatives.'))
for e in D.items:
 if e['number']in[17,18]:
  e['steps']['ko'].insert(1,'원함수의 '+('y축 대칭에서 음수 위치의 접선 기울기는 부호가 반대이다.'if e['number']==17 else'원점 대칭에서 음수 위치의 접선 기울기는 같은 값이다.'))
  e['steps']['en'].insert(1,('The y-axis symmetry reverses the slope at opposite arguments.'if e['number']==17 else'The origin symmetry preserves tangent slopes at opposite arguments.'))
normalize_prose_inequalities(D)
D.save(66)
