"""Source-checked optimization exercises; models, feasible domains and global extrema."""
from early_helpers import Book
from pathlib import Path
import json,re,math
import sympy as s
import mpmath as mp
mp.mp.dps=40
b=Book('3.7',list(range(270,278)))
def m(v):return r'\('+v+r'\)'
def F(v):return(m(v),m(v))
def add(n,k,e,formula,reason,ans,parts=''):
 pg=270 if n==1 else 271 if n<=17 else 272 if n<=40 else 273 if n<=53 else 274 if n<=68 else 275 if n<=77 else 276 if n<=84 else 277
 steps=[F(v) for v in formula]+reason
 b.add(n,pg,('최적화 문제','Optimization Problems'),(k,e),steps,(ans,ans),list(parts),check=('정의역·단위·끝점과 도함수 부호를 함께 확인한다.','Check the feasible domain, units, endpoints and derivative signs.'));b.E[n]['conceptHref']='../../calc1/index.html'
maxquad=[('이차식의 도함수는 꼭짓점 전후에서 양수에서 음수로 바뀐다.','The quadratic derivative changes from positive to negative at its vertex.')]
minquad=[('이차식은 위로 오목하므로 임계점이 전역최소이다.','The quadratic is strictly convex, so its critical point is the global minimum.')]
endinf=[('양의 정의역 양끝에서 목적함수가 무한대로 가며, 유일한 임계점에서 감소에서 증가로 바뀐다.','At both ends of the positive domain the objective tends to infinity; its unique critical point changes decrease to increase.')]
add(1,'합이23인 두 수의 곱을 (a)표로 비교하고 (b)미분으로 최대화하라.','For two numbers summing to23,(a)compare products in a table and(b)maximize by differentiation.',[r'x(23-x)=132.25-(x-11.5)^2',r'1(22)=22,\ 5(18)=90,\ 10(13)=130,\ 11(12)=132',r'P^{\prime}=23-2x=0\iff x=11.5'],maxquad,m(r'(a)\ 11,12\text{ among integers};\quad(b)\ 11.5,11.5;\ P_{\max}=132.25'),'ab')
add(2,'차가100인 두 수의 곱을 최소화하라.','Minimize the product of two numbers differing by100.',[r'P=x(x+100)=(x+50)^2-2500'],minquad,m(r'-50,50;\quad P_{\min}=-2500'))
add(3,'곱이100인 두 양수의 합을 최소화하라.','Minimize the sum of positive numbers with product100.',[r'S=x+100/x,\ x>0',r'S^{\prime}=1-100/x^2=0\iff x=10'],endinf,m(r'10,10;\quad S_{\min}=20'))
add(4,'합이16인 두 양수의 제곱합을 최소화하라.','Minimize the sum of squares of positive numbers summing to16.',[r'S=x^2+(16-x)^2=2(x-8)^2+128'],minquad,m(r'8,8;\quad S_{\min}=128'))
add(5,'−1≤x≤2에서 y=x+2와 y=x²의 최대 수직 간격을 구하라.','Find the maximum vertical separation of y=x+2 and y=x² on[−1,2].',[r'D=x+2-x^2=9/4-(x-1/2)^2'],maxquad,m(r'D_{\max}=9/4\quad(x=1/2)'))
add(6,'y=x²+1과 y=x−x²의 최소 수직 간격을 구하라.','Find the minimum vertical separation of y=x²+1 and y=x−x².',[r'D=2x^2-x+1=2(x-1/4)^2+7/8'],minquad,m(r'D_{\min}=7/8\quad(x=1/4)'))
add(7,'둘레100m인 직사각형의 넓이를 최대화하라.','Maximize the area of a rectangle with perimeter100m.',[r'y=50-x,\quad A=x(50-x),\quad A^{\prime}=50-2x'],maxquad,m(r'25\mathrm{m}\times25\mathrm{m}'))
add(8,'넓이1000m²인 직사각형의 둘레를 최소화하라.','Minimize the perimeter of a rectangle of area1000m².',[r'P=2x+2000/x,\quad P^{\prime}=2-2000/x^2'],endinf,m(r'10\sqrt{10}\mathrm{m}\times10\sqrt{10}\mathrm{m}'))
add(9,'k>0,질소량N≥0일 때 Y=kN/(1+N²)를 최대화하라.','Maximize Y=kN/(1+N²) for nitrogen level N≥0 and k>0.',[r'Y^{\prime}=k(1-N^2)/(1+N^2)^2'],[('0≤N<1에서 증가하고 N>1에서 감소한다.','It increases for0≤N<1 and decreases for N>1.')],m(r'N=1,\quad Y_{\max}=k/2'))
add(10,'광도I≥0에서 P=100I/(I²+I+4)를 최대화하라.','Maximize P=100I/(I²+I+4) for light intensity I≥0.',[r'P^{\prime}=100(4-I^2)/(I^2+I+4)^2'],[('도함수 부호가 I=2에서 양에서 음으로 바뀐다. I의 단위는 천 foot-candle이다.','The derivative changes from positive to negative at I=2; intensity is measured in thousands of foot-candles.')],m(r'I=2,\quad P_{\max}=20'))
add(11,'750ft 울타리로 직사각형을 만들고 같은 방향의 내부 울타리3개로 네 우리를 만든다. (a)예시,(b)그림,(c)넓이,(d)제약,(e)일변수식,(f)최대 넓이를 구하라.','Use750ft of fencing for a rectangle with three parallel dividers.(a)Compare examples,(b)draw it,(c)write area,(d)constraint,(e)one-variable model and(f)maximize.',[r'5x+2y=750,\quad A=xy=375x-\tfrac52x^2,\quad0<x<150',r'(x,y,A)=(50,250,12500),(100,125,12500),(120,75,9000)',r'A^{\prime}=375-5x=0\iff x=75,\quad y=187.5'],maxquad,m(r'x=75\mathrm{ft},\ y=187.5\mathrm{ft};\ A_{\max}=14062.5\mathrm{ft}^2'),'abcdef')
add(12,'한 변3ft 정사각형에서 모서리 정사각형을 잘라 뚜껑 없는 상자를 만든다. (a)예시,(b)그림,(c)부피,(d)제약,(e)일변수식,(f)최대 부피를 구하라.','Cut equal corner squares from a3ft square and fold an open box.(a)Examples,(b)diagram,(c)volume,(d)constraint,(e)one-variable model,(f)maximum.',[r'y+2x=3,\quad V=xy^2=x(3-2x)^2,\quad0<x<1.5',r'V(.25)=1.5625,\ V(.5)=2,\ V(.75)=1.6875,\ V(1)=1',r'V^{\prime}=(3-2x)(3-6x)'],[('양끝 부피는0이고 내부에서 x=.5 전에는 증가, 후에는 감소한다.','Endpoint volumes are zero; the volume increases before .5 and decreases after it.')],m(r'2\mathrm{ft}\times2\mathrm{ft}\times0.5\mathrm{ft};\ V_{\max}=2\mathrm{ft}^3'),'abcdef')
add(13,'넓이1,500,000ft² 직사각형을 내부 울타리 하나로 나눌 때 총 울타리를 최소화하라.','Minimize fencing for a1,500,000ft² rectangle with one parallel interior divider.',[r'xy=1500000,\quad L=3x+2y=3x+3000000/x',r'L^{\prime}=3-3000000/x^2=0'],endinf,m(r'x=1000\mathrm{ft},\ y=1500\mathrm{ft}'))
add(14,'강변 사다리꼴의 평행한 두 울타리가3x,x,나머지 직각 방향 울타리가y이다. 총1200ft로 넓이를 최대화하라.','A riverside trapezoid has parallel fenced sides3x and x and a perpendicular fenced side y.Use1200ft to maximize area.',[r'4x+y=1200,\quad A=2xy=2400x-8x^2',r'A^{\prime}=2400-16x=0'],maxquad,m(r'x=150,\ 3x=450,\ y=600\mathrm{ft};\ A=180000\mathrm{ft}^2'))
for n in[15,16]:
 add(n,'북쪽은 헛간,서쪽 울타리는 비용 절반을 이웃과 분담한다. 나머지는 $20/ft이다. '+('$5000로 넓이를 최대화하라.'if n==15 else'넓이8000ft²의 비용을 최소화하라.'),'The north side is a barn; share half the west fence cost. Fencing is$20/ft. '+('Maximize area with$5000.'if n==15 else'Minimize cost for8000ft².'),[r'C=30x+20y',r'A=x(250-1.5x),\quad A^{\prime}=250-3x'if n==15 else r'C=30x+160000/x,\quad C^{\prime}=30-160000/x^2'],maxquad if n==15 else endinf,m(r'x=250/3,\ y=125\mathrm{ft}'if n==15 else r'x=40\sqrt{30}/3,\ y=20\sqrt{30}\mathrm{ft}'))
add(17,'정사각형이 (a)고정 넓이에서 최소 둘레,(b)고정 둘레에서 최대 넓이를 갖는다고 증명하라.','Prove a square has(a)least perimeter for fixed area and(b)greatest area for fixed perimeter.',[r'(a)\ P(x)=2x+2A/x,\quad P^{\prime}=2-2A/x^2,\quad x=y=\sqrt A',r'(b)\ A(x)=x(P/2-x),\quad A^{\prime}=P/2-2x,\quad x=y=P/4'],[('각각 감소→증가, 증가→감소이므로 전역 극값이다.','The respective sign changes are decrease-to-increase and increase-to-decrease, giving global extrema.')],m(r'(a),(b)\ x=y'),'ab')
add(18,'부피32000cm³인 정사각 밑면의 열린 상자 표면적을 최소화하라.','Minimize surface area of an open square-base box of volume32000cm³.',[r'h=32000/x^2,\quad S=x^2+128000/x',r'S^{\prime}=2x-128000/x^2=0\iff x^3=64000'],endinf,m(r'x=40\mathrm{cm},\ h=20\mathrm{cm}'))
add(19,'표면적1200cm²인 정사각 밑면의 열린 상자 부피를 최대화하라.','Maximize the volume of an open square-base box with surface area1200cm².',[r'x^2+4xh=1200,\quad V=(1200x-x^3)/4',r'V^{\prime}=(1200-3x^2)/4=0'],[('0<x<√1200이고 양끝에서 부피0, x=20에서 유일한 최대이다.','On0<x<√1200 the endpoint volumes are zero; x=20 is the unique maximum.')],m(r'x=20\mathrm{cm},\ h=10\mathrm{cm},\ V=4000\mathrm{cm}^3'))
add(20,'4ft×3ft 판을 접되 긴 변 하나를 두 번 접어 보강하는 열린 상자의 최대 부피를 구하라.','Fold a4ft×3ft sheet into an open box, doubling one long side.Find its greatest volume.',[r'V=x(4-2x)(3-3x)=12x-18x^2+6x^3,\quad0<x<1',r'V^{\prime}=6(3x^2-6x+2)=0\iff x=1-1/\sqrt3'],[('두 겹으로 접는 쪽 때문에 폭에서3x를 뺀다. 다른 근은 정의역 밖이고 끝점 부피는0이다.','The doubled side removes3x from the width.The other derivative root is outside the domain; endpoint volumes vanish.')],m(r'x=1-1/\sqrt3\mathrm{ft},\quad V_{\max}=4\sqrt3/3\mathrm{ft}^3'))
for n in[21,22]:
 a=20 if n==21 else 32
 add(n,'부피10m³,길이가 폭의2배인 용기에서 밑면$10/m²,옆면$6/m²'+('인 열린 용기의 최소 비용을 구하라.'if n==21 else',뚜껑$6/m²일 때 최소 비용을 구하라.'),'A10m³ container has length twice its width.Base material costs$10/m² and sides$6/m².'+('Minimize cost without a lid.'if n==21 else'Include a lid costing$6/m² and minimize cost.'),[r'h=5/w^2,\quad C='+str(a)+r'w^2+180/w',r'C^{\prime}='+str(2*a)+r'w-180/w^2=0\iff w^3='+('9/2'if n==21 else'45/16')],endinf,m(r'w=('+('9/2'if n==21 else'45/16')+r')^{1/3},\quad C_{\min}='+str(3*a)+r'('+('9/2'if n==21 else'45/16')+r')^{2/3}\ \mathrm{dollars}'))
add(23,'길이와 둘레의 합108in 제한에서 정사각 단면 우편 상자의 부피를 최대화하라.','Maximize a square-cross-section package subject to length plus girth108in.',[r'L+4x=108,\quad V=x^2(108-4x)',r'V^{\prime}=12x(18-x)'],[('양끝 부피는0이고 x=18에서 최대이다. 이때 L=36은 단면 변보다 길어 길이 조건에도 맞는다.','The interior maximum is x=18; L=36 exceeds the cross-section side, consistent with the length convention.')],m(r'x=18\mathrm{in},\ L=36\mathrm{in},\ V=11664\mathrm{in}^3'))
add(24,'길이와 둘레의 합108in 제한에서 원통 우편 용기의 부피를 최대화하라.','Maximize a cylindrical mailing tube with length plus girth108in.',[r'L+2\pi r=108,\quad V=\pi r^2(108-2\pi r)',r'V^{\prime}=6\pi r(36-\pi r)'],[('도함수는 r=36/π 전후에서 양→음이다. 길이36은 지름72/π보다 크다.','The derivative changes positive-to-negative at36/π.The length36 exceeds the diameter72/π.')],m(r'r=36/\pi,\ L=36\mathrm{in};\ V=46656/\pi\mathrm{in}^3'))
add(25,'직선 y=2x+3에서 원점에 가장 가까운 점을 구하라.','Find the nearest point to the origin on y=2x+3.',[r'D^2=x^2+(2x+3)^2,\quad (D^2)^{\prime}=10x+12=0'],minquad,m(r'(-6/5,3/5)'))
add(26,'y=√x에서(3,0)에 가장 가까운 점을 구하라.','Find the nearest point on y=√x to(3,0).',[r'D^2=(x-3)^2+x,\ x\ge0,\quad (D^2)^{\prime}=2x-5'],minquad,m(r'(5/2,\sqrt{10}/2)'))
add(27,'타원4x²+y²=4에서(1,0)에 가장 먼 점을 구하라.','Find the points of4x²+y²=4 farthest from(1,0).',[r'D^2=(x-1)^2+y^2=5-2x-3x^2,\quad -1\le x\le1',r'(D^2)^{\prime}=-2-6x=0\iff x=-1/3'],maxquad,m(r'(-1/3,\ \pm4\sqrt2/3)'))
f=lambda t:(t-4)+(mp.sin(t)-2)*mp.cos(t)
roots=[]
for i in range(60):
 a=1+i/10;c=a+.1
 if f(a)*f(c)<0:roots.append(mp.findroot(f,(a,c)))
r=min(roots,key=lambda t:(t-4)**2+(mp.sin(t)-2)**2)
add(28,'y=sin x에서(4,2)에 가장 가까운 점을 수치적으로 구하라.','Numerically find the nearest point on y=sin x to(4,2).',[r'D^2=(x-4)^2+(\sin x-2)^2',r'\tfrac12(D^2)^{\prime}=x-4+(\sin x-2)\cos x=0',r'x\approx'+r',\ '.join(f'{float(z):.6f}'for z in roots)], [('거리3 미만인 후보가 있으므로 |x−4|≥3인 부분은 제외한다. [1,7]의 임계점과 끝점의 거리를 비교해 가장 작은 것을 택한다.','A candidate has distance below3, excluding |x−4|≥3.Compare the critical points and endpoints on[1,7].')],m(f'({float(r):.6f},{float(mp.sin(r)):.6f})'))
add(29,'반지름r인 원에 내접하는 최대 넓이 직사각형을 구하라.','Find the largest rectangle inscribed in a circle of radius r.',[r'A=4x\sqrt{r^2-x^2},\quad A^2=16x^2(r^2-x^2)',r'(A^2)^{\prime}=32x(r^2-2x^2)=0'],[('0<x<r의 내부 임계점이 유일한 최대이며 끝점 넓이는0이다.','The sole interior critical point is the maximum; endpoint areas are zero.')],m(r'\sqrt2r\times\sqrt2r;\ A=2r^2'))
add(30,'타원x²/a²+y²/b²=1에 내접하고 좌표축에 평행한 최대 넓이 직사각형을 구하라.','Maximize an axis-aligned rectangle inscribed in x²/a²+y²/b²=1.',[r'A=4bx\sqrt{1-x^2/a^2},\quad A^2=16b^2x^2(1-x^2/a^2)',r'(A^2)^{\prime}=32b^2x(1-2x^2/a^2)'],[('끝점은 넓이0이고 내부 최대는 x=a/√2이다.','Endpoint areas vanish; the interior maximum is at x=a/√2.')],m(r'\sqrt2a\times\sqrt2b;\ A=2ab'))
add(31,'한 변L인 정삼각형에 밑변 하나를 공유하며 내접하는 최대 직사각형을 구하라.','Maximize a rectangle inscribed in an equilateral triangle of side L, with one side along its base.',[r'H=\sqrt3L/2,\quad w=L(1-h/H),\quad A=Lh-(L/H)h^2',r'A^{\prime}=L-2Lh/H=0'],maxquad,m(r'w=L/2,\ h=\sqrt3L/4'))
add(32,'반지름1인 반원에 지름을 한 밑변으로 하는 최대 넓이 사다리꼴을 구하라.','Maximize a trapezoid inscribed in a unit semicircle with the diameter as one base.',[r'A=(1+x)\sqrt{1-x^2},\quad0\le x\le1',r'A^{\prime}=(1-x-2x^2)/\sqrt{1-x^2}'],[('양의 도함수 근 x=1/2에서 증가→감소이다.','At x=1/2 the derivative changes from positive to negative.')],m(r'\text{bases }2,1;\ h=\sqrt3/2;\ A=3\sqrt3/4'))
add(33,'반지름r인 원에 내접하는 이등변삼각형의 최대 넓이를 구하라.','Maximize an isosceles triangle inscribed in a circle of radius r.',[r'A=h\sqrt{2rh-h^2},\quad0<h<2r',r'(A^2)^{\prime}=2h^2(3r-2h)'],[('h=3r/2에서 유일한 내부 최대이다. 세 변이 모두√3r이다.','The unique interior maximum is h=3r/2; all three sides equal√3r.')],m(r'\text{base}=\sqrt3r,\ h=3r/2;\ A=3\sqrt3r^2/4'))
add(34,'두 같은 변이a인 이등변삼각형의 최대 넓이를 구하라.','Maximize an isosceles triangle with equal sides a.',[r'A=\tfrac12a^2\sin\theta,\quad0<\theta<\pi',r'A^{\prime}=\tfrac12a^2\cos\theta=0'],[('sinθ는 π/2에서 최대1이다.','The sine reaches its maximum1 at π/2.')],m(r'\theta=\pi/2,\ \text{base}=\sqrt2a,\ A=a^2/2'))
add(35,'두 변의 길이가a,2a인 삼각형의 최대 넓이를 구하라.','Maximize a triangle with two sides a and2a.',[r'A=a^2\sin\theta\le a^2'],[('두 주어진 변 사이가 직각일 때 등호이다.','Equality holds when the given sides meet at a right angle.')],m(r'\theta=\pi/2,\ A=a^2'))
add(36,'y=4−x² 아래, x축 위에 놓인 최대 직사각형을 구하라.','Maximize a rectangle above the x-axis and below y=4−x².',[r'A=2x(4-x^2),\quad0<x<2,\quad A^{\prime}=8-6x^2'],[('도함수는 2/√3 전후에서 양→음이며 끝점 넓이는0이다.','The derivative changes positive-to-negative at2/√3; endpoint areas are zero.')],m(r'w=4/\sqrt3,\ h=8/3,\ A=32/(3\sqrt3)'))
add(37,'반지름r인 구에 내접하는 원기둥의 최대 부피를 구하라.','Maximize the volume of a cylinder inscribed in a sphere of radius r.',[r'R^2+z^2=r^2,\quad h=2z,\quad V=2\pi z(r^2-z^2)',r'V^{\prime}=2\pi(r^2-3z^2)=0'],[('0<z<r에서 유일한 내부 최대이며 양끝 부피는0이다.','There is one interior maximum on0<z<r; endpoint volumes vanish.')],m(r'R=r\sqrt{2/3},\ h=2r/\sqrt3,\ V=4\pi r^3/(3\sqrt3)'))
add(38,'밑면 반지름r,높이h인 원뿔에 내접하는 원기둥의 최대 부피를 구하라.','Maximize a cylinder inscribed in a cone of base radius r and height h.',[r'R=r(1-z/h),\quad V=\pi r^2z(1-z/h)^2',r'V^{\prime}=\pi r^2(1-z/h)(1-3z/h)'],[('닮음으로 반지름을 표현한다. 0<z<h에서 z=h/3이 최대이다.','Similarity gives the radius; z=h/3 maximizes volume on0<z<h.')],m(r'R=2r/3,\ z=h/3,\ V=4\pi r^2h/27'))
add(39,'반지름r인 구에 내접하는 원기둥의 전체 표면적을 최대화하라.','Maximize total surface area of a cylinder inscribed in a sphere of radius r.',[r'S=2\pi R^2+4\pi Rz,\quad R^2+z^2=r^2',r'R=r\cos t,\ z=r\sin t,\quad S/(\pi r^2)=1+\cos2t+2\sin2t\le1+\sqrt5'],[('Cauchy 부등식의 등호는 cos2t=1/√5,sin2t=2/√5일 때이며 허용 범위 안이다.','Equality in Cauchy occurs at cos2t=1/√5,sin2t=2/√5, within the feasible range.')],m(r'R^2=r^2(5+\sqrt5)/10,\ z^2=r^2(5-\sqrt5)/10,\ S_{\max}=\pi r^2(1+\sqrt5)'))
add(40,'둘레30ft인 직사각형 위 반원 모양 Norman 창의 넓이를 최대화하라.','Maximize a Norman window of perimeter30ft: a rectangle topped by a semicircle.',[r'2y+(2+\pi)r=30,\quad A=2ry+\pi r^2/2',r'A=30r-(2+\pi/2)r^2,\quad A^{\prime}=30-(4+\pi)r'],maxquad,m(r'r=y=30/(4+\pi)\mathrm{ft};\ \text{width}=\text{total height}=60/(4+\pi)\mathrm{ft}'))
add(41,'인쇄 넓이384cm²,위·아래 여백6cm씩,좌우4cm씩인 포스터의 종이 넓이를 최소화하라.','Minimize paper area for384cm² printing,6cm top/bottom and4cm side margins.',[r'xy=384,\quad A=(x+8)(y+12)=480+12x+3072/x',r'A^{\prime}=12-3072/x^2=0'],endinf,m(r'\text{print }16\times24;\ \text{paper }24\times36\mathrm{cm}'))
add(42,'넓이180in² 포스터에서 아래1in,위2in,좌우1in 여백을 빼고 인쇄 넓이를 최대화하라.','Maximize printing on180in² paper with bottom1in,top2in and side1in margins.',[r'wh=180,\quad A=(w-2)(h-3)=186-3w-360/w',r'A^{\prime}=-3+360/w^2=0,\quad A^{\prime\prime}=-720/w^3<0'],[],m(r'w=2\sqrt{30}\mathrm{in},\ h=3\sqrt{30}\mathrm{in}'))
for n in[43,44]:
 tri=n==43
 add(n,'10m 철사를 정사각형과 '+('정삼각형'if tri else'원')+'으로 나눠 만든다. 합한 넓이를 (a)최대화,(b)최소화하는 분할을 구하라.','Split10m of wire into a square and '+('an equilateral triangle'if tri else'a circle')+'.Find splits for(a)maximum and(b)minimum combined area.',[r'A=x^2/16+'+(r'\sqrt3(10-x)^2/36'if tri else r'(10-x)^2/(4\pi)'),r'A^{\prime}='+ (r'x/8-\sqrt3(10-x)/18'if tri else r'x/8-(10-x)/(2\pi)')],[('x는 정사각형에 쓰는 길이이다. 엄격히 위로 오목하므로 임계점이 최소이고 최대는 끝점 비교로 정한다. 두 조각이 꼭 양수여야 한다면 (a)는 최댓값 대신 상한만 존재한다.','x is the square portion.Strict convexity gives an interior minimum; compare endpoints for the maximum.If both pieces must be positive, (a)has only a supremum.')],m(r'(a)\ x='+('10'if tri else'0')+r';\quad(b)\ x='+ (r'40\sqrt3/(9+4\sqrt3)'if tri else r'40/(4+\pi)')+r'\mathrm{m}'),'ab')
add(45,'둘레32in인 부채꼴 피자 조각의 넓이가 최대가 되는 피자 지름을 구하라.','Find the pizza diameter maximizing a sector slice of perimeter32in.',[r'2r+r\theta=32,\quad A=\tfrac12r^2\theta=16r-r^2',r'A^{\prime}=16-2r=0'],maxquad,m(r'\text{diameter}=16\mathrm{in},\ \theta=2\mathrm{rad}'))
add(46,'벽에서4ft 떨어진 높이8ft 울타리를 넘어 벽에 닿는 최단 사다리 길이를 구하라.','Find the shortest ladder reaching a wall over an8ft fence4ft from the wall.',[r'L=8\csc\theta+4\sec\theta,\quad0<\theta<\pi/2',r'L^{\prime}=-8\csc\theta\cot\theta+4\sec\theta\tan\theta=0\iff\tan^3\theta=2'],endinf,m(r'L_{\min}=(8^{2/3}+4^{2/3})^{3/2}\mathrm{ft}'))
add(47,'반지름R 원판의 부채꼴을 잘라 접어 만든 원뿔의 최대 부피를 구하라.','Maximize the cone made by removing a sector from a disk of radius R and joining its edges.',[r'r^2+h^2=R^2,\quad V=\pi r^2h/3=\pi(R^2h-h^3)/3',r'V^{\prime}=\pi(R^2-3h^2)/3'],[('원판 반지름은 원뿔 모선이다. 양끝에서 부피0, 내부 임계점에서 최대이다.','The disk radius is the slant height.Endpoint volumes vanish; the interior critical point is the maximum.')],m(r'r=R\sqrt{2/3},\ h=R/\sqrt3,\ V=2\pi R^3/(9\sqrt3)'))
add(48,'부피27cm³ 원뿔 컵에 드는 종이(옆넓이)를 최소화하라.','Minimize lateral paper area of a cone-shaped cup of volume27cm³.',[r'h=81/(\pi r^2),\quad S^2=\pi^2r^4+6561/r^2',r'(S^2)^{\prime}=4\pi^2r^3-13122/r^3=0'],endinf,m(r'r=(81/(\pi\sqrt2))^{1/3}\mathrm{cm},\ h=\sqrt2r'))
add(49,'높이H,반지름R 원뿔 안에 거꾸로 내접한 원뿔의 부피를 최대화하라.','Maximize an inverted cone inscribed inside a cone of height H and radius R.',[r'r=R(1-z/H),\quad V=\pi R^2z(1-z/H)^2/3',r'V^{\prime}=\pi R^2(1-z/H)(1-3z/H)/3'],[('닮음에서 반지름을 얻는다. 끝점 부피0이고 z=H/3에서 증가→감소이다.','Similarity gives the radius; endpoint volumes vanish and the derivative changes positive-to-negative at H/3.')],m(r'z=H/3,\ r=2R/3'))
add(50,'마찰계수μ≥0,무게W인 물체를 당기는 힘 F=μW/(μsinθ+cosθ)를 최소화하라.','Minimize pulling force F=μW/(μsinθ+cosθ), with friction coefficient μ≥0 and weight W.',[r'\mu\sin\theta+\cos\theta\le\sqrt{1+\mu^2}',r'\tan\theta=\mu'],[('양의 분모를 최대화하면 힘이 최소이다. μ=0이면 힘0으로 각도는 유일하지 않다.','Maximizing the positive denominator minimizes force.For μ=0 the force is zero and the angle is not unique.')],m(r'\theta=\arctan\mu,\quad F_{\min}=\mu W/\sqrt{1+\mu^2}'))
add(51,'전력P=E²R/(R+r)²을 부하저항R≥0에 대해 최대화하라(r>0).','Maximize P=E²R/(R+r)² over load resistance R≥0, where r>0.',[r'P^{\prime}=E^2(r-R)/(R+r)^3'],[('R=r 이전에는 증가, 이후에는 감소한다.','It increases before R=r and decreases afterward.')],m(r'R=r,\quad P_{\max}=E^2/(4r)'))
add(52,'유속u를 거슬러 거리L을 가는 물고기의 에너지 E=aLv³/(v−u)를 v>u에서 최소화하고 그래프로 설명하라.','Minimize E=aLv³/(v−u) for swimming distance L against current u, with v>u, and illustrate graphically.',[r'E^{\prime}=aLv^2(2v-3u)/(v-u)^2',r'v=3u/2,\quad E_{\min}=27aLu^2/4'],endinf,m(r'v=3u/2'))
add(53,'벌집 표면적 S=6sh−(3/2)s²cotθ+(3√3/2)s²cscθ에서 (a)미분,(b)최소 각도,(c)최소 표면적을 구하라.','For honeycomb area S=6sh−(3/2)s²cotθ+(3√3/2)s²cscθ,find(a)derivative,(b)minimizing angle,(c)minimum area.',[r'S^{\prime}=\tfrac32s^2\csc\theta(\csc\theta-\sqrt3\cot\theta)',r'\cos\theta=1/\sqrt3,\quad \theta\approx54.7356^\circ',r'S_{\min}=6sh+3s^2/\sqrt2'],[('0<θ<π/2에서 도함수의 부호는 1−√3cosθ의 부호이므로 감소→증가이다.','On0<θ<π/2 the sign is that of1−√3cosθ, changing from negative to positive.')],m(r'(b)\ 54.7356^\circ;\quad(c)\ 6sh+3s^2/\sqrt2'),'abc')
add(54,'A는 오후2시에 부두에서 남쪽20km/h로 출발하고,동쪽15km/h로 가는 B는 오후3시에 부두를 지난다. 두 배가 가장 가까운 시각을 구하라.','Boat A leaves a dock southbound at20km/h at2PM.Boat B travels east at15km/h and passes the dock at3PM.Find their closest time.',[r't=\text{hours after 2PM},\quad D^2=(20t)^2+[15(t-1)]^2',r'(D^2)^{\prime}=1250t-450=0\iff t=0.36'],minquad,m(r'\text{2:21:36 PM}'))
add(55,'폭5km인 강 건너5km 하류 B로 간다. 노 젓기6km/h,달리기8km/h일 때 최단시간 경로를 구하라.','Cross a5km-wide river to B,5km downstream, rowing at6km/h and running at8km/h.Find the fastest route.',[r'T(x)=\sqrt{25+x^2}/6+(5-x)/8,\quad0\le x\le5',r'T^{\prime}=x/(6\sqrt{25+x^2})-1/8',r'T^{\prime}=0\iff x=15/\sqrt7>5'],[('허용 구간 전체에서 도함수가 음수이다. B보다 더 하류에 착륙하면 노 젓기와 달리기 시간이 모두 늘어난다.','The derivative is negative throughout the feasible interval.Landing beyond B increases both rowing and running time.')],m(r'\text{row directly to B};\quad T=5\sqrt2/6\mathrm{h}'))
add(56,'반지름2mi 호수의 맞은편으로 노 젓기2mph와 걷기4mph를 조합해 이동한다. 가장 빠른 경로를 구하라.','Travel between opposite points of a circular lake of radius2mi, rowing at2mph and walking at4mph.Find the fastest route.',[r'0\le\theta\le\pi/2,\quad AB=4\cos\theta,\quad\widehat{BC}=4\theta',r'T=2\cos\theta+\theta,\quad T^{\prime\prime}=-2\cos\theta\le0',r'T(0)=2,\quad T(\pi/2)=\pi/2'],[('아래로 오목하므로 최소는 끝점이다. θ=π/2는 노를 젓지 않고 반원 전체를 걷는 경우이다.','Concavity places the minimum at an endpoint.θ=π/2 means walking the entire semicircle without rowing.')],m(r'\text{walk all the way};\quad T=\pi/2\mathrm{h}'))
add(57,'강폭2km,건너 저장소는6km 하류이다. 육상관$400000/km,수중관$800000/km일 때 북쪽 강변에서 수중으로 들어갈 위치를 구하라.','A tank is across a2km-wide river and6km downstream.Land pipe costs$400000/km and underwater pipe$800000/km.Find the optimal entry point.',[r'C=400000x+800000\sqrt{(6-x)^2+4},\quad0\le x\le6',r'C^{\prime}=400000-800000(6-x)/\sqrt{(6-x)^2+4}=0',r'6-x=2/\sqrt3'],[('C″>0이므로 내부 임계점이 유일한 최소이다. x는 정유소에서 강변을 따라 잰 거리이다.','C″>0 gives the unique minimum.Here x is the distance along the bank from the refinery.')],m(r'x=6-2/\sqrt3\approx4.8453\mathrm{km}'))
r58=mp.findroot(lambda x:x/mp.sqrt(x*x+1)-2*(6-x)/mp.sqrt((6-x)**2+4),4.9)
add(58,'앞 문제에서 정유소가 강변에서 북쪽1km 떨어져 있을 때 최적 진입점을 수치적으로 구하라.','Move the refinery in the previous problem1km north of the river.Numerically find the best entry point.',[r'C=400000\sqrt{x^2+1}+800000\sqrt{(6-x)^2+4}',r'x/\sqrt{x^2+1}=2(6-x)/\sqrt{(6-x)^2+4}'],[('x는 정유소 바로 남쪽 강변점에서 동쪽으로 잰 거리이다. 두 제곱근 거리함수의 이계도함수가 양수이므로 근이 유일한 전역최소이다.','Measure x east from the point directly south of the refinery.Both distance functions have positive second derivatives, giving a unique global minimum.')],m(fr'x\approx{float(r58):.6f}\mathrm{{km}}'))
add(59,'10ft 떨어진 두 광원 중 하나가 다른 것의3배이다. 사이에서 조도가 최소인 점을 구하라.','Two lights10ft apart have strengths in ratio1:3.Find the least illuminated point between them.',[r'I=k/x^2+3k/(10-x)^2,\quad0<x<10',r'I^{\prime}=-2k/x^3+6k/(10-x)^3=0\iff10-x=\sqrt[3]3x'],endinf,m(r'x=10/(1+\sqrt[3]3)\mathrm{ft}\text{ from the weaker light}'))
add(60,'(3,5)를 지나는 양의 절편 직선이 좌표축과 만드는 삼각형의 넓이를 최소화하라.','Minimize the first-quadrant intercept triangle of a line through(3,5).',[r'3/a+5/b=1,\quad b=5a/(a-3),\quad a>3',r'A=5a^2/[2(a-3)],\quad A^{\prime}=5a(a-6)/[2(a-3)^2]'],[('a=6 전에는 감소, 후에는 증가한다.','It decreases before a=6 and increases after it.')],m(r'5x+3y=30;\quad A_{\min}=30'))
add(61,'(a,b),a,b>0를 지나는 직선의 제1사분면 절편 선분 중 최단 길이를 구하라.','Find the shortest first-quadrant intercept segment through(a,b), with a,b>0.',[r'\text{intercepts }L\cos\theta,L\sin\theta,\quad L=a\sec\theta+b\csc\theta',r'L^{\prime}=a\sec\theta\tan\theta-b\csc\theta\cot\theta=0\iff\tan^3\theta=b/a'],endinf,m(r'L_{\min}=(a^{2/3}+b^{2/3})^{3/2}'))
add(62,'y=1+40x³−3x⁵의 접선 기울기가 가장 큰 점을 구하라.','Find the points where y=1+40x³−3x⁵ has greatest tangent slope.',[r'y^{\prime}=120x^2-15x^4=240-15(x^2-4)^2\le240',r'x=\pm2'],[],m(r'(-2,-223),(2,225);\quad m_{\max}=240'))
add(63,'y=3/x의 제1사분면 접선이 두 축 사이에 만드는 선분의 최단 길이를 구하라.','Find the shortest intercept segment of a first-quadrant tangent to y=3/x.',[r'y=6/a-3x/a^2,\quad\text{intercepts }2a,6/a',r'L^2=4a^2+36/a^2,\quad(L^2)^{\prime}=8a-72/a^3=0'],endinf,m(r'a=\sqrt3,\quad L_{\min}=2\sqrt6'))
add(64,'y=4−x²의 접선과 양의 좌표축이 만드는 삼각형의 최소 넓이를 구하라.','Minimize the first-quadrant triangle formed by a tangent to y=4−x² and the axes.',[r'y=4+a^2-2ax,\quad a>0',r'A=(4+a^2)^2/(4a),\quad A^{\prime}=(4+a^2)(3a^2-4)/(4a^2)'],endinf,m(r'a=2/\sqrt3,\quad A_{\min}=32\sqrt3/9'))
add(65,'(a)평균비용 최소에서 한계비용과 평균비용이 같음을 보이라. (b)C=16000+200x+4x^(3/2)에 대해 x=1000의 비용·평균·한계비용,평균비용 최소 생산량과 그 비용을 구하라.','(a)Show that minimum average cost equals marginal cost.(b)For C=16000+200x+4x^(3/2),find cost,average and marginal cost at1000, then the minimizing output and minimum average cost.',[r'(C/x)^{\prime}=(xC^{\prime}-C)/x^2=0\Longrightarrow C^{\prime}=C/x',r'C(1000)=216000+4000\sqrt{1000},\quad\bar C(1000)=216+4\sqrt{1000},\quad C^{\prime}(1000)=200+6\sqrt{1000}',r'\bar C=16000/x+200+4\sqrt x,\quad\bar C^{\prime}=-16000/x^2+2/\sqrt x',r'x^{3/2}=8000\iff x=400,\quad\bar C(400)=320'],endinf,m(r'(b)\ 342491.106,\ 342.491,\ 389.737;\quad x=400,\ \bar C_{\min}=320'),'ab')
add(66,'(a)이익 최대의 내부점에서 한계수익=한계비용임을 보이라. (b)C=16000+500x−1.6x²+.004x³,p=1700−7x에서 이익을 최대화하라.','(a)Show marginal revenue equals marginal cost at an interior profit maximum.(b)Maximize profit for C=16000+500x−1.6x²+.004x³ and p=1700−7x.',[r'P=R-C,\quad P^{\prime}=0\Longrightarrow R^{\prime}=C^{\prime}',r'P=-16000+1200x-5.4x^2-.004x^3',r'P^{\prime}=1200-10.8x-.012x^2=-.012(x-100)(x+1000)'],[('x≥0에서100 전에는 이익 증가, 후에는 감소한다. 가격 비음수 조건 x≤1700/7에도 적합하다.','Profit increases up to100 and decreases afterward for x≥0.This is feasible under the nonnegative-price bound x≤1700/7.')],m(r'x=100'),'ab')
add(67,'55000석 경기장에 표$10이면27000명,$8이면33000명이 온다. 선형 수요에서 수입 최대 가격을 구하라.','A55000-seat stadium draws27000 at$10 and33000 at$8.Assuming linear demand,find the revenue-maximizing price.',[r'q=57000-3000p,\quad R=57000p-3000p^2',r'R^{\prime}=57000-6000p=0'],maxquad,m(r'p=9.50\text{ dollars},\quad q=28500<55000'))
add(68,'목걸이$10에서 하루20개 팔리고 가격$1 인상마다2개 감소한다. 재료비$6일 때 이익 최대 가격을 구하라.','Necklaces sell20 per day at$10; each$1 increase loses2 sales.With$6 material cost,find the best price.',[r'q=40-2p,\quad P=(p-6)(40-2p)',r'P^{\prime}=52-4p=0'],maxquad,m(r'p=13\text{ dollars},\quad q=14'))
add(69,'태블릿은$350에서 주1200개,$10 인하마다80개 추가 판매된다. (a)수요식,(b)최대 수입,(c)비용35000+120q일 때 최대 이익 가격을 구하라.','Tablets sell1200 weekly at$350, gaining80 sales per$10 discount.Find(a)demand,(b)revenue maximum,(c)profit-maximizing price with cost35000+120q.',[r'p=500-q/8,\quad R=500q-q^2/8,\quad R^{\prime}=500-q/4',r'P=380q-q^2/8-35000,\quad P^{\prime}=380-q/4'],maxquad,m(r'(a)\ p=500-q/8;\quad(b)\ q=2000,p=250;\quad(c)\ q=1520,p=310'),'abc')
add(70,'우물16개가 각각240단위를 생산한다. 한 개 추가할 때마다 모든 우물의 생산량이8씩 감소한다. 추가할 최적 개수를 구하라.','Sixteen wells each produce240 units.Each added well reduces every well’s yield by8.Find the optimal number of additional wells.',[r'Q(n)=(16+n)(240-8n)=3840+112n-8n^2',r'Q^{\prime}=112-16n=0\iff n=7'],maxquad,m(r'n=7;\quad23\text{ wells},\quad Q=4232'))
add(71,'둘레가 고정된 이등변삼각형 중 정삼각형의 넓이가 최대임을 증명하라.','Prove that the largest isosceles triangle of fixed perimeter is equilateral.',[r'\text{base}=b,\quad\text{equal sides}=(P-b)/2,\quad0<b<P/2',r'A^2=Pb^2(P-2b)/16,\quad(A^2)^{\prime}=Pb(P-3b)/8'],[('b=P/3에서 증가→감소하므로 최대이다. 같은 두 변도 P/3이다.','The sign changes positive-to-negative at b=P/3; the other two sides are also P/3.')],m(r'\text{all sides}=P/3'))
add(72,'57번에서 수중 비용이 아무리 커져도 강변을 끝까지 간 후 수직으로 건너는 경로가 최적이 아닌 이유를 설명하라.','Explain why in57, no finite underwater cost makes it optimal to run land pipe all6km before crossing perpendicularly.',[r'C(x)=cx+K\sqrt{(6-x)^2+4},\quad C^{\prime}(6)=c>0'],[('x=6에서 조금 왼쪽으로 옮기면 비용이 감소한다. 유한 K에서는 수중거리 증가가 이차 규모인 반면 육상거리 감소는 일차 규모이다. K→∞일 때만 최적점이6에 접근한다.','Moving slightly left from6 lowers cost.For finite K the underwater distance increase is second order, while the land saving is first order.Only as K→∞ does the optimal point approach6.')],m(r'x_{\min}<6\quad\text{for every finite }K'))
add(73,'타원x²/a²+y²/b²=1의 제1사분면(p,q)에서 (a)접선 절편,(b)최단 절편 선분,(c)최소 절편 삼각형 넓이를 구하라.','For the tangent at a first-quadrant point(p,q) on x²/a²+y²/b²=1,find(a)intercepts,(b)shortest segment,(c)smallest intercept triangle.',[r'px/a^2+qy/b^2=1\Longrightarrow A=a^2/p,\ B=b^2/q',r'u=p^2/a^2,\quad L^2=a^2/u+b^2/(1-u)\ge(a+b)^2',r'\text{equality: }u=a/(a+b)',r'T=a^2b^2/(2pq)\ge ab,\quad pq\le ab/2'],[('길이의 등호 조건과 넓이의 등호 조건은 다르다. 넓이는 p=a/√2,q=b/√2에서 최소이다.','The length and area equality conditions differ.Area is minimized at p=a/√2,q=b/√2.')],m(r'(a)\ a^2/p,b^2/q;\quad(b)\ a+b;\quad(c)\ ab'),'abc')
add(74,'연의 변 길이가a,a,b,b일 때 최대 넓이와 두 대각선을 구하라.','A kite has sides a,a,b,b.Find its maximum area and diagonals.',[r'A=2(\tfrac12ab\sin\theta)=ab\sin\theta\le ab',r'd_1=\sqrt{a^2+b^2},\quad d_2=2ab/\sqrt{a^2+b^2}'],[('a와 b가 만나는 위·아래 두 각을 직각으로 한다. 각 직각삼각형의 빗변은 첫 대각선이고 빗변에 내린 두 높이의 합이 둘째 대각선이다.','Make the two angles between a and b right angles.The shared hypotenuse is one diagonal; twice the altitude to it is the other.')],m(r'A_{\max}=ab,\quad d_1=\sqrt{a^2+b^2},\ d_2=2ab/\sqrt{a^2+b^2}'))
y75=mp.findroot(lambda y:y/mp.sqrt(y*y+4)+y/mp.sqrt(y*y+9)-1,1.4)
L75=5-y75+mp.sqrt(y75*y75+4)+mp.sqrt(y75*y75+9)
add(75,'지상5m의 A에서 아래 수직선상의 P로 케이블을 내리고,기준점의 왼쪽2m B와 오른쪽3m C로 갈라 연결한다. 총 길이를 최소화하라.','From A,5m above ground,run cable to P directly below A, then to ground points2m left and3m right.Find the minimizing AP.',[r'x=AP,\quad y=5-x,\quad L=5-y+\sqrt{y^2+4}+\sqrt{y^2+9}',r'L^{\prime}(y)=-1+y/\sqrt{y^2+4}+y/\sqrt{y^2+9}=0'],[('0≤y≤5에서 L″>0이고 도함수가 양끝에서 반대 부호이므로 유일한 최소이다.','On0≤y≤5, L″>0 and the derivative changes sign between endpoints, giving the unique minimum.')],m(fr'AP\approx{float(5-y75):.6f}\mathrm{{m}},\quad L\approx{float(L75):.6f}\mathrm{{m}}'))
add(76,'주어진 시간당 연료소비 c(v) 그래프에서 거리당 소비가 최소가 되는 속도를 추정하라.','From the supplied hourly fuel-use graph c(v),estimate the speed minimizing fuel per distance.',[r'G(v)=c(v)/v,\quad G^{\prime}(v)=[vc^{\prime}(v)-c(v)]/v^2',r'c^{\prime}(v)=c(v)/v'],[('원점에서 곡선에 그은 접선의 접점을 읽는다. 시간당 소비 최소점 약30mph와 다르며, 그림의 해상도에 따라 수 mph 정도 차이가 날 수 있다.','Read the contact point of a tangent from the origin.This differs from the hourly-use minimum near30mph; graphical readings may vary by several mph.')],m(r'v\approx50\mathrm{mph}'))
add(77,'두 매질에서 속도v₁,v₂로 이동하는 빛의 최소시간 경로가 Snell 법칙을 따른다고 증명하라.','Prove that the least-time light path through media of speeds v₁,v₂ obeys Snell’s law.',[r'T(x)=\sqrt{h_1^2+x^2}/v_1+\sqrt{h_2^2+(D-x)^2}/v_2',r'T^{\prime}=\sin\theta_1/v_1-\sin\theta_2/v_2=0'],[('각도는 경계면의 법선으로부터 잰다. 각 거리항의 이계도함수가 양수여서 정상점이 최소이다.','Measure angles from the interface normal.Each distance term has positive second derivative, so the stationary point is the minimum.')],m(r'\sin\theta_1/\sin\theta_2=v_1/v_2'))
add(78,'높이a,b인 두 기둥 사이 지상의 R을 거치는 최단 줄에서 지면과 이루는 두 각이 같음을 보이라.','Show that a shortest rope from poles of heights a,b via a ground point R makes equal ground angles.',[r'L=\sqrt{a^2+x^2}+\sqrt{b^2+(d-x)^2}',r'L^{\prime}=x/\sqrt{a^2+x^2}-(d-x)/\sqrt{b^2+(d-x)^2}=0',r'\cos\theta_1=\cos\theta_2,\quad x=ad/(a+b)'],[('두 각은 예각이므로 같고 L″>0이어서 최소이다. 한 기둥 꼭대기를 지면에 반사한 직선으로도 확인된다.','Both angles are acute, hence equal; L″>0 ensures a minimum.Reflection of one pole top across the ground gives the same result.')],m(r'\theta_1=\theta_2,\quad L_{\min}=\sqrt{d^2+(a+b)^2}'))
add(79,'12in×8in 종이의 오른쪽 위 모서리를 아래 변으로 접는다. 오른쪽 변의 접힌 길이를x,접는 선 길이를y라 할 때 (a)y² 식,(b)최소화하는 x,(c)최소 y를 구하라.','Fold the upper-right corner of a12in×8in sheet to the bottom edge.Let x be the folded portion of the right edge and y the crease length.Find(a)y²,(b)minimizing x,(c)minimum y.',[r'\delta^2+(8-x)^2=x^2\Longrightarrow\delta=4\sqrt{x-4}',r'(\delta-z)^2+64=z^2\Longrightarrow z=2x/\sqrt{x-4}',r'y^2=x^2+z^2=x^3/(x-4)',r'(y^2)^{\prime}=2x^2(x-6)/(x-4)^2'],[('δ는 모서리가 아래 변에서 왼쪽으로 이동한 거리, z는 위쪽 변에서 접힌 길이이다. x=6에서 z=6√2<12이고 δ=4√2<12이므로 종이 안에 들어간다.','δ is the horizontal displacement of the folded corner, and z is the folded top-edge portion.At x=6, z=6√2<12 and δ=4√2<12, so the fold fits the sheet.')],m(r'(a)\ y^2=x^3/(x-4);\quad(b)\ x=6;\quad(c)\ y=6\sqrt3\mathrm{in}'),'abc')
add(80,'폭9ft와6ft의 직각 복도를 수평으로 통과할 수 있는 가장 긴 파이프를 구하라.','Find the longest horizontal pipe that can turn through a right-angle corridor with widths9ft and6ft.',[r'L(\theta)=9\csc\theta+6\sec\theta',r'L^{\prime}=0\iff\tan^3\theta=9/6'],[('각 방향에서 허용되는 길이의 최소값이 모든 방향을 통과할 수 있는 최대 길이이다. 양끝에서 L→∞이고 유일한 내부 최소가 있다.','The minimum allowable length over orientations is the longest pipe that can complete the turn.The function diverges at both endpoints and has one interior minimum.')],m(r'L=(9^{2/3}+6^{2/3})^{3/2}\mathrm{ft}'))
add(81,'직선 트랙에서1만큼 떨어진 관찰자 앞에서 두 주자가 같은 점을 출발해 속도비1:3으로 달린다. 시야각의 최댓값을 구하라.','An observer is1 unit from a straight track.Two runners start abreast and move away at speed ratio1:3.Find the maximum angle between sightlines.',[r'\theta=\arctan(3x)-\arctan x,\quad x\ge0',r'\theta^{\prime}=3/(1+9x^2)-1/(1+x^2)=2(1-3x^2)/[(1+9x^2)(1+x^2)]',r'x=1/\sqrt3,\quad\tan\theta=2x/(1+3x^2)=1/\sqrt3'],[],m(r'\theta_{\max}=\pi/6=30^\circ'))
add(82,'폭30cm 판을 세 부분10cm씩 나눠 양쪽을 각θ만큼 올린 홈통의 단면적을 최대화하라.','Bend the outer thirds of a30cm-wide sheet upward by angle θ to make a gutter.Maximize its cross-sectional area.',[r'A=100\sin\theta(1+\cos\theta)',r'A^{\prime}=100(2\cos^2\theta+\cos\theta-1)=100(2\cos\theta-1)(\cos\theta+1)'],[('밑변10,윗변10+20cosθ,높이10sinθ인 사다리꼴이다. 허용 범위에서 cosθ=1/2가 최대이다.','The trapezoid has base10, top10+20cosθ and height10sinθ.The feasible maximum occurs at cosθ=1/2.')],m(r'\theta=60^\circ,\quad A_{\max}=75\sqrt3\mathrm{cm}^2'))
add(83,'L×W 직사각형을 감싸는 회전된 외접 직사각형의 최대 넓이를 구하라.','Find the greatest area of a rotated rectangle circumscribed about an L×W rectangle.',[r'A=(L\cos\theta+W\sin\theta)(L\sin\theta+W\cos\theta)',r'A=LW+\tfrac12(L^2+W^2)\sin2\theta'],[('0≤θ≤π/2에서 sin2θ≤1이고 θ=π/4에서 등호이다. 외접 직사각형은 이때 정사각형이다.','On0≤θ≤π/2, sin2θ≤1 with equality at π/4.The outer rectangle is then a square.')],m(r'A_{\max}=(L+W)^2/2,\quad\theta=45^\circ'))
add(84,'혈관 저항이 길이/반지름⁴에 비례한다. (a)분기각θ의 저항식,(b)최소각 조건,(c)반지름비2/3의 각도를 구하라.','Vascular resistance is proportional to length/radius⁴.Find(a)resistance as a function of branch angle θ,(b)the minimizing condition,(c)the angle for radius ratio2/3.',[r'R=C[(a-b\cot\theta)/r_1^4+b\csc\theta/r_2^4]',r'R^{\prime}=Cb[\csc^2\theta/r_1^4-\csc\theta\cot\theta/r_2^4]',r'\cos\theta=r_2^4/r_1^4,\quad\theta=\arccos(16/81)'],[('도함수 부호는 r₂⁴−r₁⁴cosθ의 부호로 감소→증가이다. 이 내부해는 분기점이 허용 구간에 있을 때,즉 a−b cotθ≥0일 때 적용한다. 그렇지 않으면 경계 분기점을 비교한다.','The derivative sign is that of r₂⁴−r₁⁴cosθ, changing negative-to-positive.This interior solution assumes the branch is feasible: a−b cotθ≥0.Otherwise compare the boundary branch point.')],m(r'(b)\ \cos\theta=(r_2/r_1)^4;\quad(c)\ \theta\approx79^\circ'),'abc')
add(85,'새가 해안에서5km 떨어진 섬에서,최근접점B로부터13km 떨어진 D로 간다. 물 위·육지 비행 단위 에너지는 W,L이다. (a)W/L=1.4의 착륙점,(b)비율 효과,(c)B 또는 D에 바로 가는 조건,(d)BC=4일 때 비율을 구하라.','A bird starts5km offshore and heads to D,13km alongshore from the nearest point B.With water/land energy rates W,L,find(a)landing point for W/L=1.4,(b)ratio effects,(c)conditions for direct B or D,(d)ratio for BC=4.',[r'E(x)=W\sqrt{25+x^2}+L(13-x),\quad0\le x\le13',r'E^{\prime}=Wx/\sqrt{25+x^2}-L,\quad E^{\prime\prime}=25W/(25+x^2)^{3/2}>0',r'x=5/\sqrt{(W/L)^2-1}\quad\text{when interior}',r'(a)\ x=25/\sqrt{24}\approx5.1031',r'(c)\ x=13\iff W/L\le\sqrt{194}/13',r'(d)\ W/L=\sqrt{41}/4'],[('W/L가 커지면 B 쪽, 작아지면 D 쪽으로 착륙한다. L>0이면 E′(0)=−L<0이므로 어떤 유한 비율도 B 직행을 정확한 최소로 만들지 않는다. B는 비율→∞의 극한이며 L=0이면 직접 B가 최소이다.','Larger W/L moves landing toward B; smaller ratios move it toward D.For L>0, E′(0)=−L<0, so no finite ratio makes direct B optimal.B is approached as the ratio tends to infinity; if L=0, direct B is optimal.')],m(r'(a)\ 5.1031\mathrm{km};\quad(c)\ D:\ W/L\le\sqrt{194}/13,\ B:\ W/L\to\infty;\quad(d)\sqrt{41}/4'),'abcd')
add(86,'10m 떨어진 같은 광원 둘에 평행하고 거리d인 선 위의 조도를 분석하라. (a)식,(b)d=5,(c)d=10의 최소 위치,(d)최소 위치가 바뀌는 d를 구하라.','Analyze illumination on a parallel line at distance d from two equal lights10m apart.Find(a)the formula,(b)minimum for d=5,(c)for d=10,(d)the transition in minimizing position.',[r'I(x)=k/(x^2+d^2)+k/[(10-x)^2+d^2]',r'D=d^2,\quad z=(x-5)^2,\quad I/k=2(z+D+25)/[(z+D+25)^2-100z]',r'\operatorname{sgn}(dI/dz)=\operatorname{sgn}[100(D+25)-(z+D+25)^2]',r'I(5)=2k/(D+25),\quad I(0)=I(10)=k/D+k/(D+100)',r'I(5)=I(0)\iff D=50'],[('그림의 두 광원 수직투영 사이인 0≤x≤10을 비교 범위로 해석한다. 선 전체를 뜻한다면 |x|→∞에서 I→0이므로 최소점은 존재하지 않는다.','Interpret the intended comparison as0≤x≤10, between the lights’ perpendicular projections.If the entire infinite line is intended, I→0 at infinity and no minimum is attained.'),('0≤z≤25에서 도함수의 내부 부호 변화는 양→음뿐이므로 내부 z는 최소가 아니다. 따라서 중심 z=0과 양끝 z=25만 비교하면 된다.','On0≤z≤25 the only possible interior derivative sign change is positive-to-negative, so an interior z cannot minimize.Compare the center z=0 with the endpoints z=25.')],m(r'(b)\ x=5;\quad(c)\ x=0,10;\quad(d)\ d<5\sqrt2:x=5;\ d=5\sqrt2:x=0,5,10;\ d>5\sqrt2:x=0,10'),'abcd')
assert sorted(b.E)==list(range(1,87))
def norm(v):
 if isinstance(v,str):
  chunks=re.split(r'(\\\(.*?\\\)|\\\[.*?\\\])',v,flags=re.S);return ''.join(z if i%2 else z.replace('<',r'\(\lt\)')for i,z in enumerate(chunks))
 if isinstance(v,list):return[norm(z)for z in v]
 if isinstance(v,dict):return{k:norm(z)for k,z in v.items()}
 return v
b.E=norm(b.E);b.save()
Path(__file__).with_name('s3-7-report.json').write_text(json.dumps({'section':'3.7','exercises':86,'sourcePdfPages':list(range(307,315)),'numericalChecks':{'28':list(map(str,roots)),'58':str(r58),'75height':str(y75),'75length':str(L75)},'boundaryNotes':['43/44 endpoint maxima require zero-length component allowed','84 interior vascular angle requires feasible branch','85 direct B requires infinite W/L or L=0','86 bounded projection interval; infinite line has no attained minimum']},indent=2)+'\n')
print('3.7 authored:',len(b.E))
