from calc1_helpers import *
x=s.symbols('x',real=True);P=s.pi;R=s.Rational;b=CalcBook('5.5',[403,404]);records={1:(3*x*x+8*x,-1,2),2:(s.sqrt(x),0,4),3:(3*s.cos(x),-P/2,P/2),4:(x/s.sqrt(3+x*x),1,3),5:(x*x*(1+x**3)**4,0,2),6:(x*x/(x**3+3)**2,-1,1),7:(s.cos(x)**4*s.sin(x),0,P),8:((1+s.sin(x))**2*s.cos(x),P/2,3*P/2),9:(x**-2,1,3),10:((x+1)**3,0,2),11:(2*s.sin(x)-s.sin(2*x),0,P),12:(x*s.sqrt(4-x*x),0,2)}
checks=[]
def add(n,st,steps,ans,check,parts=[]):
 b.add(n,403 if n<=17 else 404,('함수의 평균값','Average value of a function'),st,steps,ans,parts=parts);b.verify(n,*check);b.save()
def avgplot(n,f,lo,hi,av,roots=[]):
 fun=s.lambdify(x,f,'math');a=float(lo);z=float(hi);v=float(av);pts=[(a+(z-a)*i/240,fun(a+(z-a)*i/240))for i in range(241)];bottom=min(0,min(q[1]for q in pts),v);top=max(max(q[1]for q in pts),v);dy=(top-bottom) or 1
 def xy(p):return(55+480*(p[0]-a)/(z-a),315-250*(p[1]-bottom)/(dy*1.08))
 def path(ps):return' '.join(f'{xy(p)[0]:.2f},{xy(p)[1]:.2f}'for p in ps)
 out=['<svg xmlns="http://www.w3.org/2000/svg" width="600" height="390" viewBox="0 0 600 390"><rect width="100%" height="100%" fill="#f8fafc"/>',f'<text x="300" y="25" text-anchor="middle" font-family="sans-serif" font-size="15">5.5.{n}  Function and equal-integral rectangle</text>',f'<polygon points="{path([(a,0)]+pts+[(z,0)])}" fill="#dbeafe"/>',f'<polygon points="{path([(a,0),(z,0),(z,v),(a,v)])}" fill="#a855f7" fill-opacity=".12" stroke="#9333ea" stroke-width="2"/>',f'<polyline points="{path(pts)}" fill="none" stroke="#0284c7" stroke-width="2"/>']
 for c in roots:
  xx,yy=xy((float(c),v));out.append(f'<circle cx="{xx}" cy="{yy}" r="4" fill="#e11d48"/>')
 for label,X,Y in[(f'a={a:.4g}',55,338),(f'b={z:.4g}',485,338),(f'Average = {v:.6g}; red points: f(c) = average',55,361),('Blue: f(x). Purple: rectangle with the same signed integral.',55,382)]:out.append(f'<text x="{X}" y="{Y}" font-family="sans-serif" font-size="12">{html.escape(label)}</text>')
 out.append('</svg>');fn=f's5-5-{n}.svg';(ROOT/'assets'/fn).write_text(''.join(out));b.E[n]['figure']={'src':'../exercise-content/assets/'+fn,'alt':pair('함수와 같은 적분값을 가진 직사각형','Function and equal-integral rectangle'),'caption':pair('밑변은 원래 구간, 직사각형 높이는 평균값이다. 빨간 점은 f(c)가 평균값과 같아지는 위치이다.','The rectangle uses the original interval as base and the average value as height. Red points mark f(c) equal to the average.')}
for n,(f,lo,hi)in records.items():
 exact=s.simplify(s.integrate(f,(x,lo,hi)));av=s.simplify(exact/(hi-lo));q=mp.quad(s.lambdify(x,f,'mpmath'),[float(lo),float(hi)])/(float(hi)-float(lo));assert abs(float(av)-float(q))<1e-8*max(1,abs(float(q)));checks.append([n,str(av)])
 st=M('f(x)='+tex(f)+r',\quad x\in['+tex(lo)+','+tex(hi)+']');steps=fs(r'f_{avg}=\frac1{b-a}\int_a^bf(x)dx',r'\int_{'+tex(lo)+'}^{'+tex(hi)+'}f(x)dx='+tex(exact),r'f_{avg}='+tex(av));ans=same(M(r'f_{avg}='+tex(av)));parts=[];roots=[]
 if n>=9:
  parts=list('abc');st=(st+'(a)평균값,(b)f(c)=평균값인 c를 모두 구하고,(c)같은 넓이의 직사각형을 그려라.',st+'Find(a)the average,(b)all c in the interval with f(c) equal to it,and(c)an equal-area rectangle.')
  roots={9:[s.sqrt(3)],10:[10**R(1,3)-1],12:[s.sqrt(2-2*s.sqrt(5)/3),s.sqrt(2+2*s.sqrt(5)/3)]}.get(n,[])
  if n==11:roots=[s.Float(str(mp.findroot(lambda z:2*mp.sin(z)-mp.sin(2*z)-4/mp.pi,q)),30)for q in[1.2,2.8]]
  for c in roots:assert abs(float(f.subs(x,c)-av))<1e-10 and float(lo)<float(c)<float(hi)
  steps+=fs(r'f(c)='+tex(av))+[('구간 안의 해만 남긴다. 직사각형의 넓이는 (b-a)favg로 원래 적분과 같다.','Retain only solutions inside the interval. The rectangle area(b-a)favg equals the original integral.')]
  if n==12:steps+=fs(r'c^2(4-c^2)=16/9\Rightarrow c^2=2\pm2\sqrt5/3')
  if n==11:steps+=[('도함수의 부호로 한 번 증가 후 감소하는 양의 봉우리임을 확인하므로 두 교점이 전부이다.','The derivative shows a single positive hump, increasing then decreasing, so these two intersections are all solutions.')]
  rootsTex=r',\ '.join((f'{float(c):.8f}'if n==11 else tex(c))for c in roots);ans=same(M(r'f_{avg}='+tex(av)+r',\quad c'+(r'\approx'if n==11 else'=')+rootsTex))
 else:st=(st+'평균값을 구하라.',st+'Find the average value.')
 add(n,st,steps,ans,('평균값에 구간 길이를 곱하면 원래 정적분이 되고, 독립 수치구적으로 대조했다.','Multiplying the average by interval length reproduces the integral; independent numerical quadrature checks it.'),parts)
 if n>=9:avgplot(n,f,lo,hi,av,roots);b.save()
add(13,('연속함수 f에 대해 ∫₁³f(x)dx=8이다. [1,3]에서 f가4를 적어도 한 번 취함을 보여라.','A continuous f satisfies ∫₁³f(x)dx=8. Show that f takes the value4 at least once on[1,3].'),fs(r'f_{avg}=\frac1{3-1}\int_1^3f(x)dx=4')+[('적분의 평균값 정리에 의해 c∈(1,3)가 존재하여 f(c)=favg=4이다.','The integral mean value theorem supplies c∈(1,3) with f(c)=favg=4.')],same(M(r'\exists c\in(1,3):f(c)=4')),('연속성이 있어야 중간값을 실제로 취한다는 결론이 보장된다.','Continuity ensures that the average value is actually attained.'))
add(14,('f(x)=2+6x-3x²의 [0,b] 평균이3이 되게 하는 b>0을 모두 구하라.','Find all b>0 for which f(x)=2+6x-3x² has average3 on[0,b].'),fs(r'f_{avg}=\frac1b[2x+3x^2-x^3]_0^b=2+3b-b^2',r'2+3b-b^2=3\Rightarrow b^2-3b+1=0'),same(M(r'b=(3\pm\sqrt5)/2')),('두 해가 모두 양수이고 평균식에 대입하면 각각3이다.','Both roots are positive and each gives3 in the average formula.'))
knots=[(0,-1),(2,1),(3,0),(4,2),(6,2),(7,1),(8,3)];f15=s.Piecewise(*[((v+(w-v)*(x-a)/(z-a)),x<=z)for (a,v),(z,w)in zip(knots,knots[1:])]);area15=sum((z-a)*(v+w)/2 for (a,v),(z,w)in zip(knots,knots[1:]));assert area15==9
add(15,('그래프는 점(0,-1),(2,1),(3,0),(4,2),(6,2),(7,1),(8,3)을 차례로 잇는 선분들이다. [0,8] 평균값을 구하라.','The graph joins(0,-1),(2,1),(3,0),(4,2),(6,2),(7,1),(8,3) by consecutive line segments. Find its average on[0,8].'),fs(r'\int_0^8f(x)dx=0+\frac12+1+4+\frac32+2=9',r'f_{avg}=9/8'),same(M(r'f_{avg}=9/8')),('0≤x≤2의 양·음 삼각형 넓이가 상쇄되며 사다리꼴 공식으로 전체 적분9를 확인했다.','Positive and negative triangles cancel on0≤x≤2; trapezoid areas independently give total integral9.'))
avgplot(15,f15,0,8,R(9,8));b.save()
readings=[10.8,29.1,44.1,55.5,63.6,68.6];av16=sum(readings)/6
add(16,('원본 자동차 속도 그래프의 t=1,3,5,7,9,11초 판독값은 약10.8,29.1,44.1,55.5,63.6,68.6 km/h이다. (a)중점법으로 처음12초 평균속도를 추정하고,(b)순간속도가 이 평균과 같아지는 시간을 그래프로 추정하라.','The source car-velocity graph gives approximately10.8,29.1,44.1,55.5,63.6,68.6 km/h at t=1,3,5,7,9,11 seconds. (a)Estimate average velocity over12 seconds by midpoints. (b)Estimate when instantaneous velocity equals it.'),fs(r'v_{avg}\approx\frac1{12}\sum_{i=1}^6v(t_i^*)\cdot2=\frac16\sum_i v(t_i^*)')+[('평균 높이 약45.28 km/h의 수평선을 그래프와 만나게 하면 약5.2초이다.','Intersecting the curve with the horizontal level about45.28 km/h gives about5.2 seconds.')],same(M(r'(a)\ v_{avg}\approx'+f'{av16:.3f}'+r'\ \mathrm{km/h};\qquad(b)\ t\approx5.2\ \mathrm s')),('초 단위 구간 길이가 분자·분모에서 상쇄되어 평균속도 단위는 km/h로 남는다. 원본 곡선을 독립 수치 판독했다.','The time units cancel between numerator and denominator, leaving km/h. Readings were independently digitized from the source.'),['a','b'])
add(17,('9 am 이후 t시간의 온도가 T(t)=50+14sin(πt/12) °F이다.9 am부터9 pm까지 평균온도를 구하라.','At t hours after9 am, T(t)=50+14sin(πt/12) °F. Find average temperature from9 am to9 pm.'),fs(r'T_{avg}=\frac1{12}\int_0^{12}[50+14\sin(\pi t/12)]dt',r'T_{avg}=50+\frac{14}{12}\frac{24}{\pi}=50+28/\pi'),same(M(r'T_{avg}=50+28/\pi\approx58.913\ ^\circ\mathrm F')),('사인항은 이 구간에서 음이 아니므로 평균은50°F와64°F 사이에 있다.','The sine term is nonnegative here, so the average lies between50°F and64°F.'))
east=[61,60,65,65,75,70,65,70,55,65,60,55];west=[65,55,50,55,60,65,80,65,60,55,50,50]
add(18,('24시간 기온 그래프에서 동부 도시 최고는약75°F,서부는약80°F이다. t=1,3,…,23시의 동부 판독값은61,60,65,65,75,70,65,70,55,65,60,55°F이고 서부는65,55,50,55,60,65,80,65,60,55,50,50°F이다. 최고 기온을 비교하고 n=12 중점법 평균 및 하루 전체의 따뜻함을 해석하라.','In the24-hour source graph, the East Coast city peaks near75°F and the West near80°F. At t=1,3,…,23 hours, East readings are61,60,65,65,75,70,65,70,55,65,60,55°F; West readings are65,55,50,55,60,65,80,65,60,55,50,50°F. Compare peaks, estimate averages using n=12 midpoints, and interpret overall warmth.'),fs(r'T_{avg}\approx\frac1{24}\sum_iT(t_i^*)\cdot2=\frac1{12}\sum_iT(t_i^*)',r'T_{East}\approx'+f'{sum(east)/12:.4f}'+r',\quad T_{West}\approx'+f'{sum(west)/12:.4f}')+[('최고는 서부가 더 높지만 높은 온도를 더 오래 유지한 동부가 평균적으로 더 따뜻했다.','The West had the higher peak, but the East was warmer on average because it maintained higher temperatures longer.')],('서부의 최고기온 약80°F가 높다. 평균은 동부 약63.83°F,서부 약59.17°F여서 동부가 하루 전체로 더 따뜻했다.','The West’s peak near80°F was higher. Averages are about63.83°F East and59.17°F West, so the East was warmer overall.'),('동일 간격 중점의 산술평균으로 확인했으며 두 도시 곡선을 색과 레이블로 원본 대조했다.','Checked as arithmetic means of equally spaced midpoints; source curves were identified by color and labels.'))
add(19,('길이8 m 막대의 선밀도는ρ(x)=12/√(x+1) kg/m이다. 평균 선밀도를 구하라.','An8-m rod has linear densityρ(x)=12/√(x+1) kg/m. Find its average density.'),fs(r'\rho_{avg}=\frac18\int_0^8\frac{12}{\sqrt{x+1}}dx=\frac18[24\sqrt{x+1}]_0^8=6'),same(M(r'\rho_{avg}=6\ \mathrm{kg/m}')),('총질량48 kg를 길이8 m로 나눈 값과 일치한다.','Agrees with total mass48 kg divided by length8 m.'))
add(20,('원통 혈관 모형 v(r)=P(R²-r²)/(4ηl)에 대해 0≤r≤R에서 반지름 r에 관한 평균속도를 구하고 최대속도와 비교하라.','For the cylindrical-vessel model v(r)=P(R²-r²)/(4ηl), average velocity with respect to radius r on0≤r≤R and compare with the maximum.'),fs(r'v_{avg}=\frac1R\int_0^R\frac{P}{4\eta l}(R^2-r^2)dr=\frac{PR^2}{6\eta l}',r'v_{max}=v(0)=\frac{PR^2}{4\eta l}\Rightarrow v_{avg}=\frac23v_{max}'),same(M(r'v_{avg}=PR^2/(6\eta l)=\frac23v_{max}')),('문제에서 지정한 dr 평균을 계산했다. 면적 가중 평균을 취하는 별도 질문과 구별된다.','Used the specified dr average, which differs from a separate area-weighted average question.'))
add(21,('호흡 유량 모형 q(t)=½sin(2πt/5) L/s, V(0)=0에 따른 흡입 공기 부피를5초 주기에서 평균하라(4.5.57의 모형).','Average the inhaled-air volume over a5-second cycle for q(t)=½sin(2πt/5) L/s with V(0)=0, the model from4.5.57.'),fs(r'V(t)=\int_0^t\frac12\sin(2\pi u/5)du=\frac5{4\pi}[1-\cos(2\pi t/5)]',r'V_{avg}=\frac15\int_0^5V(t)dt=\frac5{4\pi}'),same(M(r'V_{avg}=5/(4\pi)\approx0.397887\ \mathrm L')),('한 주기에서 코사인의 적분은0이며 V′=q,V(0)=V(5)=0을 확인했다.','The cosine integrates to zero over a cycle; checked V′=q and V(0)=V(5)=0.'))
add(22,('정지에서 자유낙하하여 s=½gt²이고 시간T에서 속도vT이다. t에 관한 평균속도는½vT, s에 관한 평균속도는⅔vT임을 보여라.','A body falls from rest with s=½gt² and terminal-time velocity vT at t=T. Show that averaging with respect to time gives½vT and with respect to displacement gives⅔vT.'),fs(r'v(t)=gt,\quad v_T=gT,\quad S=\frac12gT^2',r'\langle v\rangle_t=\frac1T\int_0^Tgt\,dt=\frac12gT=\frac12v_T',r'v(s)=\sqrt{2gs},\quad\langle v\rangle_s=\frac1S\int_0^S\sqrt{2gs}\,ds=\frac23\sqrt{2gS}=\frac23v_T'),same(M(r'\langle v\rangle_t=\frac12v_T,\qquad\langle v\rangle_s=\frac23v_T')),('각 평균의 분모가 각각 총시간T와 총거리S여야 함을 확인했다. 거리 기준은 더 빠른 구간에 더 큰 가중을 준다.','The denominators are total time T and total distance S respectively; distance averaging weights faster portions more.'))
add(23,('f가 [a,b]에서 엄격히 오목 위로일 때 평균값이 중점 함수값보다 큼을 접선 그림으로 보여라.','Using the tangent-line diagram, show that a strictly concave-up f on[a,b] has average greater than its midpoint value.'),fs(r'm=(a+b)/2,\quad L(x)=f(m)+f\prime(m)(x-m)')+[('오목 위로인 그래프는 중점 접선 위에 있고, 엄격한 경우 양의 길이 구간에서 실제로 더 높다.','A concave-up graph lies above its midpoint tangent, strictly above on a positive-length set in the strict case.')]+fs(r'\int_a^bf(x)dx>\int_a^bL(x)dx=(b-a)f(m)',r'f_{avg}>f((a+b)/2)')+[('약한 볼록성만 가정하면 ≥이며, 직선 함수에서는 등호이다.','Under weak convexity the conclusion is ≥, with equality for affine functions.')],same(M(r'f_{avg}>f((a+b)/2)')),('접선의 기울기 항은 중점 양쪽에서 적분이 상쇄된다. 엄격성 조건도 구분했다.','The tangent-slope term cancels on the symmetric interval, and the strictness condition is distinguished.'))
add(24,('a<c<b일 때 전체 구간의 평균은 두 부분구간 평균을 길이로 가중한 값임을 증명하라.','For a<c<b, prove that the whole-interval average is the length-weighted combination of the two subinterval averages.'),fs(r'f_{avg}[a,b]=\frac1{b-a}\left(\int_a^cf+\int_c^bf\right)',r'\int_a^cf=(c-a)f_{avg}[a,c],\quad\int_c^bf=(b-c)f_{avg}[c,b]'),same(M(r'f_{avg}[a,b]=\frac{c-a}{b-a}f_{avg}[a,c]+\frac{b-c}{b-a}f_{avg}[c,b]')),('두 가중치는 양수이고 합이1이며 상수함수에 대해 원래 상수를 준다.','Weights are positive and sum to1; constant functions return the same constant.'))
add(25,('연속함수 f에 대해 lim(h→0⁺)favg[a,a+h]=f(a)임을 증명하라.','For continuous f, prove lim(h→0⁺)favg[a,a+h]=f(a).'),fs(r'\left|\frac1h\int_a^{a+h}f(x)dx-f(a)\right|\le\frac1h\int_a^{a+h}|f(x)-f(a)|dx')+[('연속성으로 주어진 ε>0에 대해 0<h<δ이면 구간 전체에서 |f(x)-f(a)|<ε이다. 따라서 오른쪽은 ε보다 작다.','By continuity, for any ε>0 there is δ>0 such that0<h<δ makes |f(x)-f(a)|<ε throughout the interval. The right side is then less than ε.')],same(M(r'\lim_{h\to0^+}f_{avg}[a,a+h]=f(a)')),('절댓값 오차를 임의의 ε로 눌러 우극한 정의를 직접 충족시켰다.','Bounded absolute error by arbitrary ε, directly meeting the right-limit definition.'))
add(26,('연속함수 f에 대해 F(x)=∫ₐˣf(t)dt에 미분 평균값 정리를 적용해 적분 평균값 정리를 증명하라.','Apply the derivative mean value theorem to F(x)=∫ₐˣf(t)dt for continuous f to prove the integral mean value theorem.'),[('미적분 기본정리에 의해 F는 닫힌 구간에서 연속이고 열린 구간에서 미분 가능하며 F′=f이다.','The fundamental theorem gives continuity of F on the closed interval, differentiability inside, and F′=f.')]+fs(r'\exists c\in(a,b):\quad F\prime(c)=\frac{F(b)-F(a)}{b-a}',r'f(c)=\frac1{b-a}\int_a^bf(t)dt'),same(M(r'\int_a^bf(t)dt=f(c)(b-a)\quad\text{for some }c\in(a,b)')),('F(a)=0과 미분 평균값 정리의 연속·미분 조건을 각각 확인했다.','Checked F(a)=0 and the continuity/differentiability hypotheses of the derivative mean value theorem.'))
assert sorted(b.E)==list(range(1,27));b.save();print('5.5 COMPLETE',len(b.E))
(ROOT.parent/'exercise-checks/calc1-s5-5-integral-checks.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2)+'\n')
def chart(n,curves,xrange,yrange,title,xlabel,ylabel,avg=[]):
 a,z=xrange;c,d=yrange
 def xy(t,v):return(65+470*(t-a)/(z-a),325-250*(v-c)/(d-c))
 def path(ps):return' '.join(f'{xy(t,v)[0]:.2f},{xy(t,v)[1]:.2f}'for t,v in ps)
 out=['<svg xmlns="http://www.w3.org/2000/svg" width="610" height="430" viewBox="0 0 610 430"><rect width="100%" height="100%" fill="#f8fafc"/>',f'<text x="305" y="25" text-anchor="middle" font-family="sans-serif" font-size="15">{html.escape(title)}</text>']
 for i in range(5):
  xx=65+470*i/4;yy=325-250*i/4;out.extend([f'<path d="M{xx},75V325M65,{yy}H535" stroke="#cbd5e1"/>',f'<text x="{xx}" y="348" text-anchor="middle" font-family="sans-serif" font-size="12">{a+(z-a)*i/4:g}</text>',f'<text x="54" y="{yy+4}" text-anchor="end" font-family="sans-serif" font-size="12">{c+(d-c)*i/4:g}</text>'])
 for color,pts,label in curves:out.append(f'<polyline points="{path(pts)}" fill="none" stroke="{color}" stroke-width="2.2"/>')
 for val,color in avg:out.append(f'<polyline points="{path([(a,val),(z,val)])}" stroke="{color}" fill="none" stroke-dasharray="6 5"/>')
 for j,(color,_,label)in enumerate(curves):out.append(f'<text x="{65+160*j}" y="397" fill="{color}" font-family="sans-serif" font-size="13">{html.escape(label)}</text>')
 out.extend([f'<text x="535" y="375" text-anchor="end" font-family="sans-serif" font-size="13">{html.escape(xlabel)}</text>',f'<text x="65" y="58" font-family="sans-serif" font-size="13">{html.escape(ylabel)}</text>','<text x="65" y="419" font-family="sans-serif" font-size="11">Original redraw; dashed lines indicate the stated average/reference levels.</text></svg>'])
 fn=f's5-5-{n}.svg';(ROOT/'assets'/fn).write_text(''.join(out));b.E[n]['figure']={'src':'../exercise-content/assets/'+fn,'alt':pair('평균값 해석을 위한 자체 제작 그래프','Original graph illustrating the average-value interpretation'),'caption':pair('해설의 자료와 함수로 직접 그린 그래프. 원본 판독 자료를 사용하는 기온·속도 곡선은 근사도이다.','Original graph from the stated data/functions. Temperature and velocity curves based on source-graph readings are approximate.')}
chart(16,[('#e11d48',[(0,0)]+list(zip([1,3,5,7,9,11],readings))+[(12,70)],'Velocity')],(0,12),(0,80),'5.5.16  Velocity and its time average','t (seconds)','v (km/h)',[(av16,'#9333ea')])
chart(18,[('#0284c7',[(0,58)]+list(zip(range(1,24,2),east))+[(24,57)],'East Coast'),('#e11d48',[(0,53)]+list(zip(range(1,24,2),west))+[(24,46)],'West Coast')],(0,24),(40,85),'5.5.18  Different peaks and daily averages','t (hours)','T (degrees F)',[(sum(east)/12,'#0284c7'),(sum(west)/12,'#e11d48')])
chart(23,[('#0284c7',[(i/100,1+(i/100)**2)for i in range(201)],'Convex f(x)'),('#e11d48',[(0,0),(2,4)],'Midpoint tangent')],(0,2),(0,5),'5.5.23  Graph above its midpoint tangent','x','Illustration: f(x)=1+x²',[(2,'#9333ea')])
b.E[23]['figure']['caption']=pair('증명 구조를 보여 주는 예시 f(x)=1+x², [0,2]. 빨간 중점 접선은 y=2x이고 보라 기준 높이는 f(1)=2이다.','Illustration of the proof with f(x)=1+x² on[0,2]. The red midpoint tangent is y=2x; the purple reference height is f(1)=2.')
b.save()
b.E[19]['steps']['ko'].insert(0,'평균 선밀도는 막대 전체 질량을 전체 길이8 m로 나눈 값이다.')
b.E[19]['steps']['en'].insert(0,'Average linear density equals the total rod mass divided by its full8-m length.')
b.save()
