from calc1_inverse_helpers import *
from calc1_plot_helpers import plots
x,t,z,theta=s.symbols('x t z theta',real=True);a=s.symbols('a',nonzero=True,real=True);P=s.pi;R=s.Rational;b=CalcBook('6.6',[493,494,495])
def add(n,st,steps,ans,ck,parts=[]):
 b.add(n,493 if n<=44 else 494 if n<=80 else 495,('역삼각함수','Inverse trigonometric functions'),st,steps,ans,parts=parts);b.verify(n,*ck);b.save()
vals={1:[(r'\arcsin(1/2)',P/6,r'\sin(\pi/6)=1/2'),(r'\arccos(-1)',P,r'\cos\pi=-1')],2:[(r'\arctan\sqrt3',P/3,r'\tan(\pi/3)=\sqrt3'),(r'\operatorname{arcsec}2',P/3,r'\sec(\pi/3)=2')],3:[(r'\operatorname{arccsc}\sqrt2',P/4,r'\csc(\pi/4)=\sqrt2'),(r'\arccos(\sqrt3/2)',P/6,r'\cos(\pi/6)=\sqrt3/2')],4:[(r'\operatorname{arccot}(-\sqrt3)',5*P/6,r'\cot(5\pi/6)=-\sqrt3,\quad0<5\pi/6<\pi'),(r'\arcsin1',P/2,r'\sin(\pi/2)=1')],5:[(r'\tan(\arctan10)',10,r'\tan\circ\arctan=\operatorname{id}'),(r'\arcsin(\sin(5\pi/4))',-P/4,r'\sin(5\pi/4)=-1/\sqrt2=\sin(-\pi/4)')],6:[(r'\arctan(\tan(3\pi/4))',-P/4,r'\tan(3\pi/4)=-1=\tan(-\pi/4)'),(r'\cos(\arcsin(1/2))',s.sqrt(3)/2,r'\arcsin(1/2)=\pi/6')],7:[(r'\tan(\arcsin(2/3))',2/s.sqrt(5),r'\sin\alpha=2/3,\quad\cos\alpha=\sqrt5/3')],8:[(r'\csc(\arccos(3/5))',R(5,4),r'\cos\alpha=3/5,\quad\sin\alpha=4/5')],9:[(r'\cos(2\arcsin(5/13))',R(119,169),r'\cos2\alpha=1-2\sin^2\alpha=1-2(5/13)^2')],10:[(r'\cos(\arctan2+\arctan3)',-1/s.sqrt(2),r'\cos(\alpha+\beta)=\frac1{\sqrt5\sqrt{10}}-\frac{2\cdot3}{\sqrt5\sqrt{10}}') ]}
for n,data in vals.items():
 st=r';\quad'.join((f'({chr(97+i)})\ 'if len(data)>1 else'')+q[0]for i,q in enumerate(data));steps=fs(*[q[2]for q in data])+[('역삼각함수의 지정된 주값 범위에서 각을 고른다.','Choose the angle in the prescribed principal range of each inverse function.')];answer=r';\quad'.join((f'({chr(97+i)})\ 'if len(data)>1 else'')+s.latex(s.sympify(q[1]))for i,q in enumerate(data))
 add(n,(M(st)+'정확한 값을 구하라.',M(st)+'Find the exact values.'),steps,same(M(answer)),('원래 삼각함수값과 주값 범위를 함께 확인했다. 합성역함수라도 입력 각이 주값 밖이면 원래 각을 그대로 반환하지 않는다.','Checked both the original trigonometric value and the principal range;an inverse composition need not return an angle outside that range.'),['a','b']if n<=6 else[])
add(11,('cos(arcsinx)=√(1-x²)를 증명하라.','Prove cos(arcsinx)=√(1-x²).'),fs(r'\alpha=\arcsin x\in[-\pi/2,\pi/2],\quad\sin\alpha=x',r'\cos\alpha\ge0\Rightarrow\cos\alpha=\sqrt{1-\sin^2\alpha}=\sqrt{1-x^2}'),same(M(r'\cos(\arcsin x)=\sqrt{1-x^2},\quad|x|\le1')),('코사인의 비음수 부호가 양의 제곱근을 정하며 양 끝점x=±1도 성립한다.','Nonnegative cosine selects the positive root,and the identity also holds atx=±1.'))
for n,eq,ans,dom,steps in[(12,r'\tan(\arcsin x)',r'x/\sqrt{1-x^2}',r'-1<x<1',fs(r'\sin\alpha=x,\quad\cos\alpha=\sqrt{1-x^2}',r'\tan\alpha=\sin\alpha/\cos\alpha')),(13,r'\sin(\arctan x)',r'x/\sqrt{1+x^2}',r'x\in\mathbb R',fs(r'\tan\alpha=x,\quad\cos\alpha=1/\sqrt{1+x^2}',r'\sin\alpha=\tan\alpha\cos\alpha')),(14,r'\sin(2\arccos x)',r'2x\sqrt{1-x^2}',r'-1\le x\le1',fs(r'\cos\alpha=x,\quad\sin\alpha=\sqrt{1-x^2}',r'\sin2\alpha=2\sin\alpha\cos\alpha'))]:
 add(n,(M(eq)+'간단히 하라.',M(eq)+'Simplify.'),steps,same(M(ans+r',\quad '+dom)),('주값 구간에서 삼각함수의 부호를 확인하고 분모가0이 되는 끝점은 필요한 경우 제외했다.','Checked trigonometric signs on the principal range and excluded zero-denominator endpoints where required.'))
for n,name,fn,lo,hi,eq in[(15,'sin',math.sin,-math.pi/2,math.pi/2,r'\sin x,\ -\pi/2\le x\le\pi/2;\quad\arcsin x;\quad y=x'),(16,'tan',math.tan,-1.35,1.35,r'\tan x,\ -\pi/2<x<\pi/2;\quad\arctan x;\quad y=x')]:
 add(n,(M(eq)+'함수들을 함께 그리고 관계를 설명하라.',M(eq)+'Graph together and explain the relationship.'),[('제한된 원래 삼각함수는 일대일이고 역함수는 입력·출력을 바꾼다.','The restricted trigonometric function is one-to-one and its inverse swaps input and output.'),('따라서 두 그래프는 같은 축척에서 y=x에 대해 대칭이다.','Thus the two graphs reflect acrossy=x on equal-scale axes.')],('원래 함수와 역함수는y=x에 대한 반사이다.','The function and inverse are reflections acrossy=x.'),('표시된 각 점을(x,y)에서(y,x)로 바꾸어 역함수를 직접 생성했다.','Generated each inverse point by swapping(x,y) to(y,x).'))
 planeplot(b,n,points(fn,lo,hi),reflect=True,title=f'6.6.{n} Restricted {name} and its inverse');b.save()
add(17,('음함수 미분으로arccosx의 도함수 공식을 증명하라.','Prove the derivative formula forarccosx by implicit differentiation.'),fs(r'y=\arccos x\Rightarrow\cos y=x,\quad0<y<\pi',r'-\sin y\,y\prime=1,\quad\sin y=\sqrt{1-x^2}',r'y\prime=-1/\sqrt{1-x^2}'),same(M(r'(\arccos x)\prime=-1/\sqrt{1-x^2},\quad|x|<1')),('주값 구간에서 siny>0이므로 제곱근의 부호가 정해진다.','The principal interval hassiny>0,fixing the square-root sign.'))
add(18,('(a)arcsinx+arccosx=π/2를 증명하고,(b)이것으로arccos의 도함수를 구하라.','(a)Provearcsinx+arccosx=π/2.(b)Use it to derive the derivative ofarccos.'),fs(r'\alpha=\arcsin x,\quad\cos(\pi/2-\alpha)=x,\quad0\le\pi/2-\alpha\le\pi',r'\arccos x=\pi/2-\arcsin x',r'(\arccos x)\prime=-1/\sqrt{1-x^2}'),same(M(r'(a)\ \arcsin x+\arccos x=\pi/2;\quad(b)\ -1/\sqrt{1-x^2}')),('항등식은|x|≤1에서,유한 도함수는|x|<1에서 성립한다.','The identity holds for|x|≤1 and the finite derivative for|x|<1.'),['a','b'])
add(19,('arccot의 주값을(0,π)로 정했을 때 도함수를 증명하라.','Prove the derivative ofarccot with principal range(0,π).'),fs(r'\cot y=x\Rightarrow-\csc^2y\,y\prime=1',r'\csc^2y=1+\cot^2y=1+x^2',r'y\prime=-1/(1+x^2)'),same(M(r'(\operatorname{arccot}x)\prime=-1/(1+x^2)')),('주값 범위에서sin y≠0이며 분모1+x²는 모든 실수에서 양수이다.','The principal range hassiny≠0 and denominator1+x² is positive for all realx.'))
for n,name,interval,start,aux,answer in[(20,'arcsec',r'[0,\pi/2)\cup[\pi,3\pi/2)',r'\sec y=x\Rightarrow\sec y\tan y\,y\prime=1',r'\tan y=\sqrt{x^2-1}',r'1/(x\sqrt{x^2-1})'),(21,'arccsc',r'(0,\pi/2]\cup(\pi,3\pi/2]',r'\csc y=x\Rightarrow-\csc y\cot y\,y\prime=1',r'\cot y=\sqrt{x^2-1}',r'-1/(x\sqrt{x^2-1})')]:
 add(n,('이 책의'+name+' 주값 범위'+M(interval)+'를 사용해 도함수를 증명하라.','Using this book’s'+name+' principal range'+M(interval)+',prove its derivative.'),fs(start,aux,r'y\prime='+answer)+[('책의 두 사분면에서 해당 tan 또는cot는 비음수이다. 음수 입력도x자체의 부호를 유지하므로 절댓값을 넣지 않는다.','On the book’s two quadrants,the relevanttan orcot is nonnegative.Negative inputs retain the sign ofx,so no absolute value is inserted.')],same(M(r'y\prime='+answer+r',\quad|x|>1')),('본문PDF527의 주값을 직접 대조했다.83번의 다른arcsec규약은 다른 도함수를 만들므로 여기와 구별한다.','Directly checked the principal ranges on sourcePDF527;the alternativearcsec convention in83 yields a different derivative.'))
print('6.6 authored',len(b.E))
D={22:(x,s.atan(x*x),None),23:(x,s.asin(5*x),None),24:(x,s.acos(s.sqrt(x)),None),25:(x,s.atan(x)**2,None),26:(x,s.acos(s.exp(-x)),1/s.sqrt(s.exp(2*x)-1)),27:(x,s.atan(s.sqrt(x-1)),1/(2*x*s.sqrt(x-1))),28:(t,s.log(s.atan(t**4)),None),29:(theta,s.atan(s.cos(theta)),None),30:(x,s.atan(x-s.sqrt(1+x*x)),1/(2*(1+x*x))),31:(z,s.exp(s.asin(z*z)),None),32:(t,s.asin(1/t),-1/(s.Abs(t)*s.sqrt(t*t-1))),33:(t,P/2-s.atan(t)+P/2-s.atan(1/t),s.Integer(0)),34:(t,s.acos(s.asin(t)),None),35:(x,x*s.asin(x)+s.sqrt(1-x*x),s.asin(x)),36:(x,s.atan(s.sqrt((1-x)/(1+x))),-1/(2*s.sqrt(1-x*x))),37:(x,s.atan(x/a)+s.log((x-a)/(x+a))/2,2*a*x*x/(x**4-a**4))}
for n,(v,f,manual)in D.items():
 df=s.diff(f,v)if manual is None else manual;sub={a:R(1,10)};ff=s.lambdify(v,f.subs(sub),'mpmath');dd=s.lambdify(v,df.subs(sub),'mpmath');samples=[mp.mpf('2.1'),mp.mpf('2.3')]if n in[27,32]else[mp.mpf('.1'),mp.mpf('.15')]if n==23 else[mp.mpf('.2'),mp.mpf('.4')]
 for q in samples:assert abs(mp.diff(ff,q)-dd(q))<1e-14,(n,q)
 eq=r'\operatorname{arcsec}(e^x)'if n==26 else r'\operatorname{arccot}t+\operatorname{arccot}(1/t)'if n==33 else s.latex(f)
 steps=fs(r'(\arcsin u)\prime=\frac{u\prime}{\sqrt{1-u^2}},\quad(\arctan u)\prime=\frac{u\prime}{1+u^2}')+[('연쇄법칙과 필요한 곱·몫 법칙을 적용하고 실수 미분 가능한 구간에서 단순화한다.','Apply the chain rule and product/quotient rules as needed,then simplify on real differentiability intervals.')]+fs(r'f\prime('+s.latex(v)+')='+s.latex(s.simplify(df)))
 if n==30:steps+=fs(r'\arctan(x-\sqrt{1+x^2})=\tfrac12\arctan x-\pi/4')
 if n==33:steps+=fs(r'h(t)=\pi/2\ (t>0),\quad h(t)=3\pi/2\ (t<0)')
 if n==36:steps+=fs(r'\arctan\sqrt{(1-x)/(1+x)}=\tfrac12\arccos x')
 if n==37:steps+=fs(r'a\ne0,\quad (x-a)/(x+a)>0')
 add(n,(M('f('+s.latex(v)+')='+eq)+'미분하고 단순화하라.',M('f('+s.latex(v)+')='+eq)+'Differentiate and simplify.'),steps,same(M(s.latex(s.simplify(df)))),('원래 함수의 수치 미분과 결과를 두 허용 입력에서 비교했다.32에서는음수t도 포함하므로절댓값을유지한다.','Compared the result against numerical differentiation at two admissible inputs.In32,the absolute value is retained to include negativet.'))
add(38,('f(x)=arcsin(eˣ)의 도함수와 원래 함수·도함수의 정의역을 구하라.','Find the derivative of f(x)=arcsin(eˣ),and the domains of the function and derivative.'),fs(r'0<e^x\le1\Longleftrightarrow x\le0',r'f\prime(x)=\frac{e^x}{\sqrt{1-e^{2x}}}',r'D_f=(-\infty,0],\quad D_{f\prime}=(-\infty,0)'),same(M(r'f\prime=\frac{e^x}{\sqrt{1-e^{2x}}};\quad D_f=(-\infty,0],\ D_{f\prime}=(-\infty,0)')),('x=0에서 함수값π/2는 존재하지만 도함수 분모가0이므로 유한 도함수는 없다.','Atx=0 the function valueπ/2 exists,but the derivative denominator vanishes,so no finite derivative exists.'))
add(39,('g(x)=arccos(3-2x)의 도함수와 원래 함수·도함수의 정의역을 구하라.','Find the derivative ofg(x)=arccos(3-2x),and the domains of the function and derivative.'),fs(r'-1\le3-2x\le1\Longleftrightarrow1\le x\le2',r'g\prime(x)=\frac2{\sqrt{1-(3-2x)^2}}=\frac1{\sqrt{(x-1)(2-x)}}'),same(M(r'D_g=[1,2],\quad D_{g\prime}=(1,2);\quad g\prime=1/\sqrt{(x-1)(2-x)}')),('두 끝점의 arccos값은 정의되지만 내부에서만 분모가 양수여서 도함수가 유한하다.','The arccos endpoint values are defined,but only interior inputs give a positive denominator and finite derivative.'))
add(40,('arctan(x²y)=x+xy²에서y′을 구하라.','Findy′ fromarctan(x²y)=x+xy².'),fs(r'\frac{2xy+x^2y\prime}{1+x^4y^2}=1+y^2+2xyy\prime',r'[x^2-2xy(1+x^4y^2)]y\prime=(1+y^2)(1+x^4y^2)-2xy'),same(M(r'y\prime=\frac{(1+y^2)(1+x^4y^2)-2xy}{x^2-2xy(1+x^4y^2)}')),('음함수F=arctan(x²y)-x-xy²의-Fx/Fy와 비교했다. 분모가0이 아닌 정칙점에서 적용한다.','Compared with-Fx/Fy forF=arctan(x²y)-x-xy²,valid at regular points with nonzero denominator.'))
add(41,('g(x)=xarcsin(x/4)+√(16-x²)일 때g′(2)를 구하라.','For g(x)=xarcsin(x/4)+√(16-x²),findg′(2).'),fs(r'g\prime=\arcsin(x/4)+\frac{x}{\sqrt{16-x^2}}-\frac{x}{\sqrt{16-x^2}}',r'g\prime(2)=\arcsin(1/2)=\pi/6'),same(M(r'\pi/6')),('합성함수의1/4인자를 포함하면 두 유리항이 정확히 상쇄된다.','Including the inner factor1/4 makes the two radical-denominator terms cancel exactly.'))
add(42,('y=3arccos(x/2)의(1,π)에서 접선을 구하라.','Find the tangent toy=3arccos(x/2) at(1,π).'),fs(r'y\prime=-3/\sqrt{4-x^2},\quad y\prime(1)=-\sqrt3',r'y-\pi=-\sqrt3(x-1)'),same(M(r'y=\pi-\sqrt3(x-1)')),('3arccos(1/2)=π이고 직선은 지정 점과 해당 기울기를 모두 만족한다.','3arccos(1/2)=π,and the line satisfies the specified point and derivative slope.'))
for n,f,df,window in[(43,s.sqrt(1-x*x)*s.asin(x),1-x*s.asin(x)/s.sqrt(1-x*x),(-.99,.99,-3,2)),(44,s.atan(x*x-x),(2*x-1)/(1+(x*x-x)**2),(-2,3,-2,2))]:
 assert s.simplify(s.diff(f,x)-df)==0
 add(n,(M('f(x)='+s.latex(f))+'f′을 구하고 두 그래프를 비교하라.',M('f(x)='+s.latex(f))+'Findf′ and compare their graphs.'),fs(r'f\prime(x)='+s.latex(df))+[('f′가 양수이면 원래 함수는 증가하고 음수이면 감소한다. 도함수 영점과 원래 곡선의 수평접선을 대응시킨다.','Positivef′ gives increasingf and negativef′ decreasingf;match derivative zeros with horizontal tangents.')],same(M(s.latex(df))),('기호미분식을 독립 단순화했고 그래프에서 도함수의 부호와 함수의 증감 관계를 대조했다.','Independently simplified the symbolic derivative and compared derivative signs with monotonicity in the graph.'))
 plots(b,n,[(f'6.6.{n} Function and derivative',*window,[('f(x)',s.lambdify(x,f,'math')),('f prime',s.lambdify(x,df,'math'))])])
for n,expr,at,direction,answer,why in[(45,s.asin(x),-1,'+',-P/2,('arcsin은닫힌정의역에서도연속이다.','arcsin is continuous at its domain endpoints.')),(46,s.acos((1+x*x)/(1+2*x*x)),s.oo,'-',P/3,('안쪽유리함수의극한은1/2이다.','The inner rational function tends to1/2.')),(47,s.atan(s.exp(x)),s.oo,'-',P/2,('지수입력이∞로가면arctan은π/2로간다.','As the exponential input tends to∞,arctan tends toπ/2.')),(48,s.atan(s.log(x)),0,'+',-P/2,('lnx→-∞이므로arctan은-π/2로간다.','lnx tends to-∞,soarctan tends to-π/2.'))]:
 assert s.limit(expr,x,at,dir=direction)==answer
 eq=r'\lim_{x\to'+s.latex(at)+('^+'if n in[45,48]else'')+'}'+s.latex(expr)
 add(n,(M(eq)+'극한을구하라.',M(eq)+'Find the limit.'),[why]+fs(eq+'='+s.latex(answer)),same(M(s.latex(answer))),('안쪽극한의방향과역삼각함수주값범위를확인했다.','Checked the inner-limit direction and the inverse function’s principal range.'))
print('6.6 authored',len(b.E))
p49=5-2*s.sqrt(5);ang49=s.atan((3-p49)/2)+s.atan(p49/5)
add(49,('A=(0,0),B=(0,3),오른쪽끝점C=(2,3),D=(5,0)이다.P를AB위에서골라각CPD를최대화하라.','LetA=(0,0),B=(0,3),C=(2,3),D=(5,0).ChooseP onAB to maximizeangleCPD.'),fs(r'P=(0,p),\quad0\le p\le3,\quad\theta=\arctan\frac{3-p}{2}+\arctan\frac p5',r'\theta\prime=-\frac2{4+(3-p)^2}+\frac5{25+p^2}',r'\theta\prime=0\Rightarrow p^2-10p+5=0\Rightarrow p=5-2\sqrt5'),same(M(r'AP=5-2\sqrt5\approx0.527864')),('다른근5+2√5는선분밖이고유효근의앞에서θ′>0,뒤에서θ′<0이므로최대이다.','The other root5+2√5 lies outside the segment;θ′ is positive before the admissible root and negative after it.'))
plots(b,49,[('6.6.49 Angle along AB',0,3,.5,1.2,[('theta(p), radians',lambda q:math.atan((3-q)/2)+math.atan(q/5))])])
add(50,('그림의아래끝은눈높이보다d>0높고그림높이는h>0이다.벽까지거리x에서시야각을최대화하는x를구하라.','A painting’s lower edge isd>0 above eye level and its height ish>0.Find wall distancex that maximizes the viewing angle.'),fs(r'\theta(x)=\arctan\frac{d+h}{x}-\arctan\frac d x',r'\theta\prime=\frac{h[d(d+h)-x^2]}{(x^2+d^2)(x^2+(d+h)^2)}',r'\theta\prime=0\Rightarrow x=\sqrt{d(d+h)}'),same(M(r'x=\sqrt{d(d+h)}')),('도함수분모는양수이고분자는근전후로양수에서음수로바뀐다.x→0⁺와∞에서는시야각이0으로간다.','The denominator is positive and the numerator changes from positive to negative;the angle tends to0 asx→0⁺ or∞.'))
plots(b,50,[('6.6.50 Example d=1,h=2',.01,6,0,.6,[('viewing angle',lambda q:math.atan(3/q)-math.atan(1/q))])])
add(51,('길이10ft사다리의아래끝이벽에서2ft/s로멀어진다.벽까지6ft일때사다리와벽사이각의변화율을구하라.','A10ft ladder’s foot moves away from a wall at2ft/s.Find the rate of change of the angle between ladder and wall when the foot is6ft away.'),fs(r'\sin\theta=x/10\Rightarrow\theta=\arcsin(x/10)',r'\frac{d\theta}{dt}=\frac{x\prime}{\sqrt{100-x^2}}=\frac2{\sqrt{100-36}}=1/4'),same(M(r'1/4\text{ rad/s, increasing}')),('벽과사다리사이각이므로아래끝이멀어질때각이증가한다.지면과의각과부호가반대이다.','The angle with the wall increases as the foot moves away;its sign is opposite the angle with the ground.'))
add(52,('등대는직선해안에서3km떨어져있고빛은분당4회전한다.최근접해안점P에서1km떨어진곳을비출때빛점의해안상속력을구하라.','A lighthouse is3km from a straight shore and rotates4times per minute.Find the shore-spot speed when it is1km from the nearest shore pointP.'),fs(r'x=3\tan\theta,\quad|\theta\prime|=8\pi\text{ rad/min}',r'|x\prime|=3\sec^2\theta\,8\pi=24\pi(1+x^2/9)',r'|x\prime|_{x=1}=80\pi/3\approx83.7758\text{ km/min}'),same(M(r'80\pi/3\text{ km/min}')),('한회전은2π라디안이고거리조건은tanθ=1/3이다.부호없는속력을계산했다.','One revolution is2πradians andtanθ=1/3 at the stated location;computed the unsigned speed.'))
for n,eq,df,dd,ans,panels in[(53,r'\arcsin\frac{x}{x+1}',r'\frac1{(x+1)\sqrt{2x+1}}',r'-\frac{3x+2}{(x+1)^2(2x+1)^{3/2}}',('정의역[-1/2,∞),원점이절편,전체에서증가·아래로오목.끝점최소-π/2는x=-1/2.변곡점없음,수평점근선y=π/2.','Domain[-1/2,∞),intercept(0,0),increasing and concave down throughout.Endpoint minimum-π/2 atx=-1/2.No inflections;horizontal asymptotey=π/2.'),[('6.6.53 Rational-input arcsine',-.5,8,-1.7,1.7,[('f(x)',lambda q:math.asin(q/(q+1)))])]),(54,r'\arctan\frac{x-1}{x+1}',r'1/(1+x^2)',r'-2x/(1+x^2)^2',('정의역x≠-1,절편(1,0),(0,-π/4),각정의구간에서증가·극값없음.위로오목(-∞,-1),(-1,0),아래로오목(0,∞),변곡점(0,-π/4).수평점근선y=π/4.x=-1의양쪽극한π/2,-π/2는유한하므로수직점근선이아니다.','Domainx≠-1,intercepts(1,0),(0,-π/4),increasing on each domain interval,no extrema.Concave up(-∞,-1),(-1,0),down(0,∞),inflection(0,-π/4).Horizontal asymptotey=π/4.The finite one-sided limitsπ/2,-π/2 atx=-1 are not vertical asymptotes.'),[('6.6.54 Left branch',-6,-1.01,0,1.7,[('f(x)',lambda q:math.atan((q-1)/(q+1)))]),('6.6.54 Right branch',-.99,6,-1.7,1.7,[('f(x)',lambda q:math.atan((q-1)/(q+1)))])]),(55,r'x-\arctan x',r'x^2/(1+x^2)',r'2x/(1+x^2)^2',('정의역ℝ,기함수,유일절편원점,전체증가·극값없음.아래로오목(-∞,0),위로오목(0,∞),변곡점원점.오른쪽사선점근선y=x-π/2,왼쪽y=x+π/2.','Domainℝ,odd,only intercept(0,0),increasing throughout,no extrema.Concave down(-∞,0),up(0,∞),inflection(0,0).Right slant asymptotey=x-π/2,lefty=x+π/2.'),[('6.6.55 Function and slant asymptotes',-6,6,-6,6,[('x-arctanx',lambda q:q-math.atan(q)),('x-pi/2',lambda q:q-math.pi/2),('x+pi/2',lambda q:q+math.pi/2)])]),(56,r'e^{\arctan x}',r'e^{\arctan x}/(1+x^2)',r'e^{\arctan x}(1-2x)/(1+x^2)^2',('정의역ℝ,치역(e^(-π/2),e^(π/2)),y절편1,x절편없음.전체증가·극값없음.위로오목(-∞,1/2),아래로오목(1/2,∞),변곡점(1/2,e^(arctan(1/2))).수평점근선y=e^(±π/2).','Domainℝ,range(e^(-π/2),e^(π/2)),y-intercept1,no x-intercept.Increasing throughout,no extrema.Concave up(-∞,1/2),down(1/2,∞),inflection(1/2,e^(arctan(1/2))).Horizontal asymptotesy=e^(±π/2).'),[('6.6.56 Exponential of arctangent',-10,10,0,5,[('exp(arctanx)',lambda q:math.exp(math.atan(q)))])])]:
 add(n,(M('y='+eq)+'정의역,절편,점근선,증감,극값,오목성에따라분석하고그려라.',M('y='+eq)+'Analyze and sketch using domain,intercepts,asymptotes,monotonicity,extrema,and concavity.'),fs(r'f\prime='+df,r'f\prime\prime='+dd)+[('정의역을먼저나누고도함수부호와무한대·경계극한을조합한다.','First split the domain,then combine derivative signs with end and boundary limits.')],ans,('주값범위에서끝점과점근선값을확인하고2계도함수부호변화를변곡점과대조했다.','Checked endpoints and asymptote values in the principal range,and matched second-derivative sign changes with inflections.'))
 plots(b,n,panels)
# Triple-angle identity removes nested inverse functions while preserving the full domain.
u57=s.sqrt(1-x*x)*(1-4*x*x);f57=s.atan(u57);d57=s.diff(f57,x);dd57=s.diff(f57,x,2)
# Because f is even, only a positive inflection root needs numerical refinement.
q57=float(mp.findroot(s.lambdify(x,dd57,'mpmath'),(.5,.55)));root57=math.sqrt(3)/2
add(57,('f(x)=arctan(cos(3arcsinx))의f′,f″를CAS로구하고그래프로최대·최소점과변곡점의x좌표를추정하라.','Use a CAS to findf′,f″ forf(x)=arctan(cos(3arcsinx));graph to estimate x-coordinates of maxima,minima,and inflections.'),fs(r'u(x)=(1-4x^2)\sqrt{1-x^2},\quad f=\arctan u',r'f\prime=\frac{u\prime}{1+u^2},\quad f\prime\prime=\frac{u\prime\prime(1+u^2)-2u(u\prime)^2}{(1+u^2)^2}',r'u\prime=\frac{3x(4x^2-3)}{\sqrt{1-x^2}}',r'u\prime\prime='+s.latex(s.factor(s.diff(u57,x,2))))+[('f는우함수이다.도함수영점은0,±√3/2이며2계도함수의내부영점은약±'+f'{q57:.6f}'+'이다.끝점f(±1)=0도비교한다.','f is even.Derivative zeros are0,±√3/2;interior second-derivative zeros are about±'+f'{q57:.6f}'+'.Also compare endpoint valuesf(±1)=0.')],same(M(r'\text{global max: }x=0,\ f=\pi/4;\quad\text{global min: }x=\pm\sqrt3/2,\ f=-\pi/4;\quad\text{inflections: }x\approx\pm'+f'{q57:.6f}')),('삼중각항등식으로원래중첩식을독립변환하고우함수대칭과임계점함수값을대조했다.','Independently transformed the nested expression by a triple-angle identity,then checked even symmetry and critical values.'))
plots(b,57,[('6.6.57 Function',-1,1,-1,1,[('f',s.lambdify(x,f57,'math'))]),('6.6.57 First derivative',-.99,.99,-8,8,[('f prime',s.lambdify(x,d57,'math'))]),('6.6.57 Second derivative',-.95,.95,-25,25,[('f second derivative',s.lambdify(x,dd57,'math'))])])
add(58,('함수족f(x)=x-c arcsinx를조사하라.c에따른극대·극소개수변화를분석하고여러그래프를그려라.','Investigatef(x)=x-c arcsinx.How do numbers of maxima and minima change withc?Graph several members.'),fs(r'D=[-1,1],\quad f\prime=1-\frac c{\sqrt{1-x^2}},\quad f\prime\prime=-\frac{cx}{(1-x^2)^{3/2}}')+[('c≤0이면엄격히증가하여내부극값이없다.c≥1이면엄격히감소하여내부극값이없다(c=1에서0의수평접선은극값이아니다).','Forc≤0 it strictly increases with no interior extrema.Forc≥1 it strictly decreases with no interior extrema;atc=1,the horizontal tangent at0 is not an extremum.'),('0<c<1이면a=√(1-c²)라할때x=-a에서내부극소,x=a에서내부극대가한개씩생긴다.닫힌구간의절대극값은이두점과끝점±1도비교한다.','For0<c<1,leta=√(1-c²):there is one interior local minimum at-a and one interior local maximum ata.Absolute extrema on the closed interval also require endpoint comparison.')]+fs(r'f(a)=a-c\arccos c,\quad f(1)=1-c\pi/2,\quad f(-x)=-f(x)',r'\max_{[-1,1]}f=\max\{|1-c\pi/2|,\ a-c\arccos c\}\quad(0<c<1),\quad\min f=-\max f'),('내부극값은0<c<1에서극대1개·극소1개이며그밖에는없다. 절대극값에는끝점도포함한다.','There is one interior maximum and one interior minimum exactly when0<c<1,and none otherwise.Absolute extrema also include endpoints.'),('f′=0은√(1-x²)=c이므로0<c≤1만가능하며c=1에서는부호가바뀌지않는다.','f′=0 requires√(1-x²)=c,possible only for0<c≤1;atc=1 the derivative does not change sign.'))
plots(b,58,[('6.6.58 Varying c',-1,1,-3,3,[(f'c={c}',lambda q,c=c:q-c*math.asin(q))for c in[-1,0,.5,1,2]])])
print('6.6 authored',len(b.E))
add(59,('f(x)=(2x²+5)/(x²+1)의가장일반적인원시함수를구하라.','Find the most general antiderivative off(x)=(2x²+5)/(x²+1).'),fs(r'f(x)=2+3/(1+x^2)',r'F(x)=2x+3\arctan x+C'),same(M(r'2x+3\arctan x+C')),('원시함수를미분하면2+3/(1+x²)가되고원래유리함수와같다.','Differentiation gives2+3/(1+x²),equal to the original rational function.'))
add(60,('g′(t)=2/√(1-t²),g(1)=5인g를구하라.','Findg ifg′(t)=2/√(1-t²) andg(1)=5.'),fs(r'g(t)=2\arcsin t+C',r'5=2\arcsin1+C=\pi+C\Rightarrow C=5-\pi'),same(M(r'g(t)=2\arcsin t+5-\pi')),('미분공식은-1<t<1에서사용하고끝점조건은t=1로의연속연장값으로적용한다.','The derivative applies for-1<t<1;the endpoint condition uses the continuous extension tot=1.'))
I={61:(x,8/(1+x*x),1/s.sqrt(3),s.sqrt(3),8*s.atan(x)),62:(t,6/s.sqrt(1-t*t),-1/s.sqrt(2),1/s.sqrt(2),6*s.asin(t)),63:(x,s.asin(x)/s.sqrt(1-x*x),0,R(1,2),s.asin(x)**2/2),64:(x,1/(1+16*x*x),0,s.sqrt(3)/4,s.atan(4*x)/4),65:(x,(1+x)/(1+x*x),None,None,s.atan(x)+s.log(1+x*x)/2),66:(x,s.sin(x)/(1+s.cos(x)**2),0,P/2,-s.atan(s.cos(x))),67:(x,s.atan(x)**2/(1+x*x),None,None,s.atan(x)**3/3),68:(x,1/((1+x*x)*s.atan(x)),None,None,s.log(s.Abs(s.atan(x)))),69:(x,s.exp(s.asin(x))/s.sqrt(1-x*x),None,None,s.exp(s.asin(x))),70:(x,1/(x*s.sqrt(x*x-4)),None,None,None),71:(t,t*t/s.sqrt(1-t**6),None,None,s.asin(t**3)/3),72:(x,s.exp(x)/(1+s.exp(2*x)),0,1,s.atan(s.exp(x))),73:(x,1/(s.sqrt(x)*(1+x)),None,None,2*s.atan(s.sqrt(x))),74:(x,x/(1+x**4),None,None,s.atan(x*x)/2)}
for n,(v,f,lo,hi,F)in I.items():
 if n==70:
  add(n,(M(r'\int\frac{dx}{x\sqrt{x^2-4}}')+'적분하라.',M(r'\int\frac{dx}{x\sqrt{x^2-4}}')+'Evaluate.'),fs(r'u=x/2,\quad\int\frac{dx}{x\sqrt{x^2-4}}=\frac12\int\frac{du}{u\sqrt{u^2-1}}',r'=\tfrac12\operatorname{arcsec}(x/2)+C'),same(M(r'\tfrac12\operatorname{arcsec}(x/2)+C')),('이책의제3사분면음수주값arcsec규약을사용했다.|x|>2의각구간에서20번공식과연쇄법칙으로원래피적분함수를얻는다.','Uses this book’s third-quadrant negativearcsec branch;Exercise20 and the chain rule recover the integrand on each interval|x|>2.'));continue
 if n!=68:assert s.simplify(s.trigsimp(s.diff(F,v)-f))==0,(n,s.diff(F,v)-f)
 ans=F if lo is None else s.simplify(F.subs(v,hi)-F.subs(v,lo));integ=s.Integral(f,v)if lo is None else s.Integral(f,(v,lo,hi))
 if lo is not None:assert abs(mp.quad(s.lambdify(v,f,'mpmath'),[float(lo),float(hi)])-float(ans))<1e-10
 add(n,(M(s.latex(integ))+'적분하라.',M(s.latex(integ))+'Evaluate.'),[('역삼각함수의도함수형태를사용하고필요한안쪽치환을적용한다.','Use an inverse-trigonometric derivative form and the appropriate inner substitution.')]+fs('F('+s.latex(v)+')='+s.latex(F),s.latex(integ)+'='+s.latex(ans)+('+C'if lo is None else'')),same(M(s.latex(ans)+('+C'if lo is None else''))),('원시함수를미분하여피적분함수를복원했고정적분은독립수치적분도확인했다.','Differentiated the antiderivative to recover the integrand and also checked definite integrals by independent quadrature.'))
add(75,('a>0일때∫dx/√(a²-x²)=arcsin(x/a)+C를치환으로증명하라.','Fora>0,prove∫dx/√(a²-x²)=arcsin(x/a)+C by substitution.'),fs(r'u=x/a,\quad dx=a\,du,\quad\sqrt{a^2-x^2}=a\sqrt{1-u^2}',r'\int\frac{dx}{\sqrt{a^2-x^2}}=\int\frac{du}{\sqrt{1-u^2}}=\arcsin u+C'),same(M(r'\arcsin(x/a)+C,\quad|x|<a')),('a>0조건덕분에√a²=a로단순화되며도함수의1/a와분모축척이상쇄된다.','The conditiona>0 gives√a²=a,and the derivative’s1/a factor cancels the denominator scaling.'))
add(76,('0≤x≤2에서y=1/√(x²+4)아래영역을x축회전한부피를구하라.','Rotate the region under y=1/√(x²+4) on0≤x≤2 about the x-axis.Find the volume.'),fs(r'V=\pi\int_0^2\frac{dx}{x^2+4}=\frac\pi2[\arctan(x/2)]_0^2',r'V=\pi^2/8'),same(M(r'\pi^2/8')),('원판반지름을제곱하면1/(x²+4)이고적분경계x=2에서arctan1=π/4이다.','Squaring the disk radius gives1/(x²+4),and atx=2 we usearctan1=π/4.'))
add(77,('∫₀¹arcsinx dx를넓이로해석하고y에대해적분하라.','Interpret∫₀¹arcsinx dx as an area and integrate with respect toy.'),fs(r'0\le y\le\pi/2,\quad\sin y\le x\le1',r'A=\int_0^{\pi/2}(1-\sin y)\,dy=[y+\cos y]_0^{\pi/2}=\pi/2-1'),same(M(r'\pi/2-1')),('수평절편의오른쪽끝은x=1,왼쪽끝은x=siny이며전체직사각형면적에서sin의적분을뺀값과일치한다.','Each horizontal strip runs fromx=siny tox=1;the result also equals rectangle area minus the integral ofsiny.'))
y=s.symbols('y',real=True);area_svg(b,77,[(0,P/2,s.Integer(1),s.sin(y))],y,'6.6.77 Horizontal strips for inverse-sine area');b.save()
add(78,('xy≠1이고arctanx+arctany가(-π/2,π/2)안에있을때덧셈공식을증명하라.','Forxy≠1 and arctanx+arctany in(-π/2,π/2),prove the arctangent addition formula.'),fs(r'\alpha=\arctan x,\quad\beta=\arctan y',r'\tan(\alpha+\beta)=\frac{x+y}{1-xy}',r'\alpha+\beta\in(-\pi/2,\pi/2)\Rightarrow\alpha+\beta=\arctan\frac{x+y}{1-xy}'),same(M(r'\arctan x+\arctan y=\arctan\frac{x+y}{1-xy}')),('tan의주값구간에서일대일성을사용했다.주값조건을빼면π의보정이필요하므로그조건을유지했다.','Used one-to-one tangent on its principal interval;outside it aπ correction may be needed,so the stated condition is retained.'))
add(79,('덧셈공식으로(a)arctan(1/2)+arctan(1/3)=π/4,(b)2arctan(1/3)+arctan(1/7)=π/4를증명하라.','Use the addition formula to prove(a)arctan(1/2)+arctan(1/3)=π/4,(b)2arctan(1/3)+arctan(1/7)=π/4.'),fs(r'(a)\ \frac{1/2+1/3}{1-(1/2)(1/3)}=1',r'(b)\ \frac{1/3+1/7}{1-(1/3)(1/7)}=1/2',r'2\arctan(1/3)+\arctan(1/7)=\arctan(1/3)+\arctan(1/2)=\pi/4'),same(M(r'(a)\pi/4;\quad(b)\pi/4')),('모든각은양수이고각덧셈의탄젠트분모가양수이므로합이주값범위(0,π/2)에있다.','All angles are positive and each tangent-addition denominator is positive,so the relevant sums stay in(0,π/2).'),['a','b'])
add(80,('(a)sin(arcsinx),(b)g(x)=arcsin(sinx)를그려라.(c)g′=cosx/|cosx|를보이고,(d)h(x)=arccos(sinx)의그래프와도함수를구하라.','Graph(a)sin(arcsinx),(b)g(x)=arcsin(sinx).(c)Showg′=cosx/|cosx|.(d)Graphh(x)=arccos(sinx) and find its derivative.'),fs(r'(a)\ f(x)=x,\quad-1\le x\le1',r'(b)\ g(x)=(-1)^k(x-k\pi),\quad k\pi-\pi/2\le x\le k\pi+\pi/2',r'(c)\ g\prime(x)=\frac{\cos x}{\sqrt{1-\sin^2x}}=\frac{\cos x}{|\cos x|}',r'(d)\ h(x)=\pi/2-g(x),\quad h\prime(x)=-\frac{\cos x}{|\cos x|}')+[('두삼각파는cosx=0인점에서뾰족하게꺾여미분가능하지않다.그밖의기울기는±1이다.','Both triangular waves have corners and are nondifferentiable wherecosx=0;elsewhere the slopes are±1.')],same(M(r'f(x)=x\ (|x|\le1);\quad g\prime=\cos x/|\cos x|;\quad h\prime=-\cos x/|\cos x|\quad(\cos x\ne0)')),('주값범위[-π/2,π/2]와[0,π]로반사되는구간을구성했고접합점좌우기울기가서로다름을확인했다.','Constructed reflected intervals within principal ranges[-π/2,π/2] and[0,π],and checked distinct one-sided slopes at joins.'),list('abcd'))
plots(b,80,[('6.6.80a Identity on restricted domain',-1,1,-1,1,[('sin(arcsinx)=x',lambda q:q)]),('6.6.80b Principal arcsine of sine',-3*math.pi,3*math.pi,-2,2,[('g(x)',lambda q:math.asin(math.sin(q)))]),('6.6.80d Principal arccosine of sine',-3*math.pi,3*math.pi,0,3.5,[('h(x)',lambda q:math.acos(math.sin(q)))])])
# Exercise80 extends to the next printed page.
b.E[80]['source']['printedPages']=[494,495] if 'source'in b.E[80] else [494,495]
add(81,('공통실수정의역0≤x≤1에서2arcsinx=arccos(1-2x²)를증명하라.','Prove2arcsinx=arccos(1-2x²) on the common real domain0≤x≤1.'),fs(r'\alpha=\arcsin x\in[0,\pi/2],\quad2\alpha\in[0,\pi]',r'\cos2\alpha=1-2\sin^2\alpha=1-2x^2',r'\arccos(1-2x^2)=2\alpha=2\arcsin x'),same(M(r'2\arcsin x=\arccos(1-2x^2),\quad0\le x\le1')),('2α가arccos주값범위안에있기때문에추가절댓값이나π보정이없다.','Because2α lies in thearccos principal range,no extra absolute value orπ correction is needed.'))
add(82,('arcsin((x-1)/(x+1))=2arctan√x-π/2를증명하라.','Provearcsin((x-1)/(x+1))=2arctan√x-π/2.'),fs(r'x\ge0,\quad\beta=\arctan\sqrt x\in[0,\pi/2)',r'\sin(2\beta-\pi/2)=-\cos2\beta=\frac{\tan^2\beta-1}{1+\tan^2\beta}=\frac{x-1}{x+1}',r'-\pi/2\le2\beta-\pi/2<\pi/2'),same(M(r'\arcsin\frac{x-1}{x+1}=2\arctan\sqrt x-\pi/2,\quad x\ge0')),('양변의공통실수정의역은x≥0이며오른쪽각이arcsin주값에속한다.x=0에서도양변=-π/2이다.','The common real domain isx≥0 and the right-side angle lies in thearcsin principal range;both sides equal-π/2 atx=0.'))
add(83,('다른arcsec정의y∈[0,π/2)∪(π/2,π]를사용하면도함수가1/(|x|√(x²-1))임을증명하라.','Using the alternativearcsec range[0,π/2)∪(π/2,π],prove its derivative is1/(|x|√(x²-1)).'),fs(r'\sec y=x\Rightarrow y\prime=1/(\sec y\tan y)',r'x>1:\ \tan y=\sqrt{x^2-1};\quad x<-1:\ \tan y=-\sqrt{x^2-1}',r'\sec y\tan y=|x|\sqrt{x^2-1}'),same(M(r'y\prime=\frac1{|x|\sqrt{x^2-1}},\quad|x|>1')),('대안정의의제2사분면에서tan이음수이므로두음수의곱이양수이다.20번의제3사분면규약과다르다.','In the alternative second-quadrant branch,tan is negative and the product of two negatives is positive,unlike the third-quadrant convention in20.'))
add(84,('x≠0에서f(x)=xarctan(1/x),f(0)=0이다.(a)0에서연속성,(b)미분가능성을판정하라.','Letf(x)=xarctan(1/x) forx≠0 andf(0)=0.Determine(a)continuity,(b)differentiability at0.'),fs(r'|f(x)|\le(\pi/2)|x|\to0=f(0)',r'\frac{f(h)-f(0)}h=\arctan(1/h)',r'\lim_{h\to0^+}\arctan(1/h)=\pi/2,\quad\lim_{h\to0^-}\arctan(1/h)=-\pi/2'),('(a)연속이다.(b)좌우도함수가달라미분가능하지않다.','(a)Continuous.(b)Not differentiable because the one-sided derivatives differ.'),('함수값의극한과차분몫의극한을분리했다.연속성이미분가능성을보장하지않는꼭짓점이다.','Separated the function limit from the difference-quotient limit;this corner is continuous without being differentiable.'),['a','b'])
print('6.6 COMPLETE',len(b.E))
