from calc1_inverse_helpers import *
from calc1_plot_helpers import plots
x,t,u,th=s.symbols('x t u theta',real=True);P=s.pi;R=s.Rational;b=CalcBook('6.8',[511,512,513,514,515])
def add(n,st,steps,ans,ck,parts=[]):
 b.add(n,511 if n<=4 else 512 if n<=70 else 513 if n<=91 else 514 if n<=103 else 515,('부정형과 로피탈 법칙','Indeterminate forms and l’Hospital’s rule'),st,steps,ans,parts=parts);b.verify(n,*ck);b.save()
def ma(n,eq,ss,ans,ck,parts=[]):add(n,(M(eq)+'극한을 구하거나 명제를 증명하라.',M(eq)+'Evaluate the limit or prove the assertion.'),fs(*ss),same(M(ans)),ck,parts)
giv=M(r'x\to a:\ f\to0,\ g\to0,\ h\to1,\ p\to+\infty,\ q\to+\infty')
classes={1:(r'(a)f/g;\ (b)f/p;\ (c)h/p;\ (d)p/f;\ (e)p/q',['a','b','c','d','e'],('a,e는 부정형. b,c는0. d는 부정형이 아니지만 f의 부호에 따라 +∞, −∞ 또는 양쪽 극한 없음이다.','a,e are indeterminate. b,c equal0. d is not indeterminate, but its sign depends on f: +∞, −∞, or no two-sided limit.'),[r'(a)\ 0/0;\quad(b)\ 0/\infty=0;\quad(c)\ 1/\infty=0',r'(d)\ |p/f|\to\infty\ \text{where defined};\quad(e)\ \infty/\infty']),2:(r'(a)fp;\ (b)hp;\ (c)pq',list('abc'),('a는 부정형0·∞. b,c는+∞.','a is indeterminate0·∞. b,c equal+∞.'),[r'(a)\ 0\cdot\infty',r'(b)\ 1\cdot\infty=\infty;\quad(c)\ \infty\cdot\infty=\infty']),3:(r'(a)f-p;\ (b)p-q;\ (c)p+q',list('abc'),('a는−∞, b는 부정형∞−∞, c는+∞.','a equals−∞, b is indeterminate∞−∞, c equals+∞.'),[r'(a)\ 0-\infty=-\infty',r'(b)\ \infty-\infty;\quad(c)\ \infty+\infty=\infty']),4:(r'(a)f^g;\ (b)f^p;\ (c)h^p;\ (d)p^f;\ (e)p^q;\ (f)\sqrt[q]p',list('abcdef'),('실수 거듭제곱이 정의되는 양의 밑에서 a,c,d,f는 부정형, b는0, e는+∞이다.','For positive bases defining real powers, a,c,d,f are indeterminate, b equals0 and e equals+∞.'),[r'(a)\ 0^0;\quad(b)\ 0^\infty=0;\quad(c)\ 1^\infty',r'(d)\ \infty^0;\quad(e)\ \infty^\infty=\infty;\quad(f)\ p^{1/q}:\ \infty^0'])}
for n,(eq,parts,ans,ss)in classes.items():add(n,(giv+M(eq)+'각 형태가 부정형인지 판단하고 가능하면 극한값을 구하라.',giv+M(eq)+'Classify indeterminate forms and evaluate determined limits.'),fs(*ss)+[('부정형은 개별 극한값만으로 결과를 정할 수 없다는 뜻이다.','An indeterminate form means the individual limits do not determine the result.')],ans,('유한값·무한대·부호 및 거듭제곱의 실수 정의 조건을 구별했다.','Distinguished finite values, infinities, signs and the real-domain condition for powers.'),parts)
for n,m1,m2 in[(5,R(9,5),R(4,5)),(6,R(3,2),-1)]:
 add(n,(M(fr'f(2)=g(2)=0,\quad f\prime(2)={s.latex(m1)},\quad g\prime(2)={s.latex(m2)}')+'그림의 접선 기울기가 주어졌다. limₓ→₂ f(x)/g(x)를 구하라.',M(fr'f(2)=g(2)=0,\quad f\prime(2)={s.latex(m1)},\quad g\prime(2)={s.latex(m2)}')+'Given these tangent slopes from the graph, find limₓ→₂ f(x)/g(x).'),fs(r'\frac{f(x)}{g(x)}=\frac{f(x)/(x-2)}{g(x)/(x-2)}',r'\lim_{x\to2}\frac{f(x)}{g(x)}=\frac{f\prime(2)}{g\prime(2)}='+s.latex(m1/m2)),same(M(s.latex(m1/m2))),('분모 접선 기울기가0이 아니므로 도함수 정의에 의한 비율 극한이 성립한다.','The denominator tangent slope is nonzero, so the ratio limit follows from the derivative definition.'))
add(7,('원점에서 f의 접선이 y=x이다. limₓ→₀ f(x)/(eˣ−1)을 구하라.','The tangent to f at the origin is y=x. Find limₓ→₀ f(x)/(eˣ−1).'),fs(r'f(0)=0,\quad f\prime(0)=1',r'\frac{f(x)}{e^x-1}=\frac{f(x)/x}{(e^x-1)/x}\to1/1'),same(M('1')),('접선의 절편과 기울기를 함께 사용했고 지수함수의 원점 도함수는1이다.','Used both tangent intercept and slope, together with the derivative of the exponential at zero.'))
# Quotient limits; preserve numerator and denominator before automatic simplification.
quot={8:(x-3,x*x-9,x,3,''),9:(x*x-2*x-8,x-4,x,4,''),10:(x**3+8,x+2,x,-2,''),11:(x**7-1,x**3-1,x,1,''),12:(s.sqrt(x)-2,x-4,x,4,''),13:(s.sin(x)-s.cos(x),s.tan(x)-1,x,P/4,''),14:(s.tan(3*x),s.sin(2*x),x,0,''),15:(s.exp(2*t)-1,s.sin(t),t,0,''),16:(x*x,1-s.cos(x),x,0,''),17:(s.sin(x-1),x**3+x-2,x,1,''),18:(1+s.cos(th),1-s.cos(th),th,P,''),19:(s.sqrt(x),1+s.exp(x),x,s.oo,''),20:(x+x*x,1-2*x*x,x,s.oo,''),21:(s.log(x),x,x,0,'+'),22:(s.log(s.sqrt(x)),x*x,x,s.oo,''),23:(s.log(x/3),3-x,x,3,''),24:(8**t-5**t,t,t,0,''),25:(s.sqrt(1+2*x)-s.sqrt(1-4*x),x,x,0,''),26:(s.exp(u/10),u**3,u,s.oo,''),27:(s.exp(x)+s.exp(-x)-2,s.exp(x)-x-1,x,0,''),28:(s.sinh(x)-x,x**3,x,0,''),29:(s.tanh(x),s.tan(x),x,0,''),30:(x-s.sin(x),x-s.tan(x),x,0,''),31:(s.asin(x),x,x,0,''),32:(s.log(x)**2,x,x,s.oo,''),33:(x*3**x,3**x-1,x,0,''),34:(s.exp(x)+s.exp(-x)-2*s.cos(x),x*s.sin(x),x,0,''),35:(s.log(1+x),s.cos(x)+s.exp(x)-1,x,0,''),36:(x*s.sin(x-1),2*x*x-x-1,x,1,''),37:(s.atan(2*x),s.log(x),x,0,'+'),38:(x*x*s.sin(x),s.sin(x)-x,x,0,''),40:(s.exp(-x),P/2-s.atan(x),x,s.oo,''),41:(s.cos(x)-1+x*x/2,x**4,x,0,''),42:(x-s.sin(x),x*s.sin(x*x),x,0,''),43:(s.sin(P/x),1/x,x,s.oo,''),44:(s.sqrt(x),s.exp(x/2),x,s.oo,''),45:(s.sin(5*x),s.sin(3*x),x,0,''),46:(s.log(1-1/x),1/x,x,-s.oo,''),47:(x**3,s.exp(x*x),x,s.oo,''),48:(s.sin(1/x),x**(-R(3,2)),x,s.oo,''),49:(s.log(x),1/s.tan(P*x/2),x,1,'+'),50:(s.cos(x),s.cos(5*x),x,P/2,'-'),51:(x*s.log(x)-(x-1),(x-1)*s.log(x),x,1,''),52:(1-s.cos(x),s.sin(x),x,0,''),53:(s.exp(x)-1-x,x*(s.exp(x)-1),x,0,'+'),54:(s.atan(x)-x,x*s.atan(x),x,0,'+'),55:(s.tan(x)-x,x*s.tan(x),x,0,'+')}
orig={43:x*s.sin(P/x),44:s.sqrt(x)*s.exp(-x/2),45:s.sin(5*x)/s.sin(3*x),46:x*s.log(1-1/x),47:x**3*s.exp(-x*x),48:x**R(3,2)*s.sin(1/x),49:s.log(x)*s.tan(P*x/2),50:s.cos(x)*s.sec(5*x),51:x/(x-1)-1/s.log(x),52:s.csc(x)-s.cot(x),53:1/x-1/(s.exp(x)-1),54:1/x-1/s.atan(x),55:1/x-1/s.tan(x)}
limits={}
for n,(N,D,z,q,di) in quot.items():
 expr=orig.get(n,N/D);side='^'+di if di else'';head=r'\lim_{'+s.latex(z)+r'\to '+s.latex(q)+side+'}';ans=s.limit(N/D,z,q,dir=di or '+');limits[n]=ans
 if not di and q not in[s.oo,-s.oo]:assert s.limit(N/D,z,q,dir='-')==ans,(n,'sides')
 steps=[]
 if n in orig:steps+=fs(s.latex(expr)+'='+s.latex(N/D))
 nn,dd=N,D
 for count in range(5):
  ln=s.limit(nn,z,q,dir=di or '+');ld=s.limit(dd,z,q,dir=di or '+')
  eligible=(ln==0 and ld==0)or(ln in[s.oo,-s.oo]and ld in[s.oo,-s.oo])
  if not eligible:
   steps.append(('현재 비율은 부정형이 아니므로 직접 극한·부호를 적용한다.','The current ratio is not indeterminate; use direct limits and signs.'));break
  steps.append(('분자와 분모가 모두0 또는 모두 무한대로 가므로 로피탈 법칙을 적용한다.','Both numerator and denominator tend to zero or both diverge, so apply l’Hospital’s rule.'))
  nn=s.diff(nn,z);dd=s.diff(dd,z);steps+=fs(head+s.latex(N/D)+r'\overset{\mathrm H}{=}'+head+s.latex(nn/dd))
  if not (s.limit(nn,z,q,dir=di or '+')==0 and s.limit(dd,z,q,dir=di or '+')==0):break
 steps+=fs(head+s.latex(nn/dd)+'='+s.latex(ans))
 add(n,(M(head+s.latex(expr))+'극한을 구하고 로피탈 법칙을 적용할 수 있는지 설명하라.',M(head+s.latex(expr))+'Evaluate and explain whether l’Hospital’s rule applies.'),steps,same(M(s.latex(ans))),('원 비율의 기호 극한 및 필요한 좌우 극한을 독립적으로 계산하여 결과를 대조했다.','Independently evaluated the original symbolic ratio and the required one-sided limits.'))
 print('limit',n,ans)
a,bb=s.symbols('a b',real=True)
ma(39,r'\lim_{x\to1}\frac{x^a-1}{x^b-1},\quad b\ne0',[r'0/0:\quad\lim_{x\to1}\frac{ax^{a-1}}{bx^{b-1}}',r'=a/b'],r'a/b',('x는1 근처 양수이고 b≠0이어서 미분된 분모의 극한이0이 아니다.','Near1 the input is positive and b≠0 makes the differentiated denominator limit nonzero.'))
ma(56,r'\lim_{x\to\infty}(x-\ln x)',[r'x-\ln x=x\left(1-\frac{\ln x}{x}\right)',r'\lim_{x\to\infty}\frac{\ln x}{x}=\lim_{x\to\infty}1/x=0',r'x(1-o(1))\to\infty'],r'+\infty',('차에 직접 로피탈을 적용하지 않고 비율로 바꾸어 선형항이 지배함을 확인했다.','Converted to a ratio rather than applying l’Hospital directly to a difference, confirming linear growth dominates.'))
powers={57:(x,s.sqrt(x),0,'+',0,[r'\ln y=\sqrt x\ln x=\frac{\ln x}{x^{-1/2}}',r'\lim\ln y=\lim\frac{1/x}{-\tfrac12x^{-3/2}}=\lim(-2\sqrt x)=0']),58:(s.tan(2*x),x,0,'+',0,[r'\ln y=x\ln(\tan2x)=\frac{\ln(\tan2x)}{1/x}',r'\lim\ln y=\lim\frac{2\sec^2(2x)/\tan2x}{-1/x^2}=0']),59:(1-2*x,1/x,0,'',-2,[r'\ln y=\ln(1-2x)/x',r'\lim\ln y=\lim[-2/(1-2x)]=-2']),61:(x,1/(1-x),1,'+',-1,[r'\ln y=\ln x/(1-x)',r'\lim\ln y=\lim(1/x)/(-1)=-1']),62:(s.exp(x)+10,1/x,s.oo,'',1,[r'\ln y=\ln(e^x+10)/x',r'\lim\ln y=\lim e^x/(e^x+10)=1']),63:(x,1/x,s.oo,'',0,[r'\ln y=(\ln x)/x',r'\lim\ln y=\lim1/x=0']),64:(x,s.exp(-x),s.oo,'',0,[r'\ln y=(\ln x)/e^x',r'\lim\ln y=\lim1/(xe^x)=0']),65:(1+4*x,s.cot(x),0,'+',4,[r'\ln y=\ln(1+4x)/\tan x',r'\lim\ln y=\lim\frac{4/(1+4x)}{\sec^2x}=4']),66:(1-s.cos(x),s.sin(x),0,'+',0,[r'\ln y=\frac{\ln(1-\cos x)}{\csc x}',r'\lim\ln y=\lim\frac{\sin x/(1-\cos x)}{-\csc x\cot x}=\lim\frac{-\sin^3x}{(1-\cos x)\cos x}=0']),67:(1+s.sin(3*x),1/x,0,'+',3,[r'\ln y=\ln(1+\sin3x)/x',r'\lim\ln y=\lim3\cos3x/(1+\sin3x)=3']),68:(s.cos(x),1/(x*x),0,'',-R(1,2),[r'\ln y=(\ln\cos x)/x^2',r'\lim\ln y=\lim-\tan x/(2x)=\lim-\sec^2x/2=-1/2']),70:((2*x-3)/(2*x+5),2*x+1,s.oo,'',-8,[r'\ln y=(2x+1)\ln(1-8/(2x+5))',r'u=1/(2x+5)\to0^+,\quad\ln y=(1/u-4)\ln(1-8u)',r'\ln(1-8u)/u\to-8,\quad\ln(1-8u)\to0'])}
for n,(base,exponent,q,di,L,ss)in powers.items():
 lg=exponent*s.log(base);actual=s.limit(lg,x,q,dir=di or '+');assert actual==L,(n,actual,L)
 if not di and q not in[s.oo,-s.oo]:assert s.limit(lg,x,q,dir='-')==L
 head=r'\lim_{x\to '+s.latex(q)+('^'+di if di else'')+'}';ans=s.exp(L)
 add(n,(M(head+s.latex(s.Pow(base,exponent,evaluate=False)))+'극한을 구하라.',M(head+s.latex(s.Pow(base,exponent,evaluate=False)))+'Evaluate the limit.'),[('밑이 양수인 근방에서 y의 로그를 취한 뒤, 부정형 비율에 로피탈 법칙을 적용한다.','Take the logarithm where the base is positive, then apply l’Hospital to the indeterminate ratio.')]+fs(*ss,r'\lim y=\exp(\lim\ln y)='+s.latex(ans)),same(M(s.latex(ans))),('로그 극한을 독립 기호 계산으로 검산하고 지수함수의 연속성으로 원 극한을 복원했다.','Checked the logarithmic limit independently and recovered the original limit by continuity of the exponential.'))
ma(60,r'\lim_{x\to\infty}(1+a/x)^{bx}',[r'\ln y=ab\frac{\ln(1+a/x)}{a/x}\quad(a\ne0)',r'\lim_{u\to0}\ln(1+u)/u=1\Rightarrow\ln y\to ab',r'a=0\text{ or }b=0:\ y=1=e^{ab}'],r'e^{ab}',('유한 실수 a,b에 대해 x가 충분히 크면 밑이 양수이며 영 매개변수도 별도로 처리했다.','For finite real a,b the base is eventually positive; zero parameters are handled separately.'))
ma(69,r'\lim_{x\to0^+}\frac{x^x-1}{\ln x+x-1}',[r'x\ln x\to0\Rightarrow x^x=e^{x\ln x}\to1',r'x^x-1\to0,\quad\ln x+x-1\to-\infty'],r'0',('0/−∞ 형태이므로 이 단계에서 로피탈 법칙은 적용 대상이 아니다.','The form0/−∞ is not an indeterminate form requiring l’Hospital.'))
ma(71,r'\lim_{x\to\infty}(1+2/x)^x',[r'\ln y=\frac{\ln(1+2/x)}{1/x}',r'\lim\ln y=\lim\frac{-2/[x^2(1+2/x)]}{-1/x^2}=2',r'\lim y=e^2'],r'e^2\approx7.3890561',('그래프의 접근값과 로그극한의 정확한 값이 일치한다.','The graphical approach agrees with the exact logarithmic limit.'))
plots(b,71,[('Power limit',1,100,2,8,[('(1+2/x)^x',lambda q:math.exp(q*math.log1p(2/q))),('e^2',lambda q:math.exp(2))])])
ma(72,r'\lim_{x\to0}\frac{5^x-4^x}{3^x-2^x}',[r'0/0:\quad\lim_{x\to0}\frac{5^x\ln5-4^x\ln4}{3^x\ln3-2^x\ln2}',r'=\frac{\ln(5/4)}{\ln(3/2)}'],r'\frac{\ln(5/4)}{\ln(3/2)}\approx0.55033971',('분모 도함수의 원점 값 ln(3/2)>0이며 그래프의 좌우 접근이 일치한다.','The differentiated denominator has positive value ln(3/2) at zero and both graphical approaches agree.'))
plots(b,72,[('Exponential ratio near zero',-.5,.5,.2,.9,[('ratio',lambda q:(5**q-4**q)/(3**q-2**q))])])
for n,f,g,ans in[(73,s.exp(x)-1,x**3+4*x,R(1,4)),(74,2*x*s.sin(x),s.sec(x)-1,4)]:
 df=s.diff(f,x);dg=s.diff(g,x)
 add(n,(M('f(x)='+s.latex(f)+r',\quad g(x)='+s.latex(g))+'원점 근처 f/g와 f′/g′를 함께 그리고 공통 극한을 구하라.',M('f(x)='+s.latex(f)+r',\quad g(x)='+s.latex(g))+'Graph f/g and f′/g′ near zero and find their common limit.'),fs(r'\lim_{x\to0}\frac{f(x)}{g(x)}\overset{\mathrm H}{=}\lim_{x\to0}'+s.latex(df/dg),r'\lim_{x\to0}'+s.latex(df/dg)+'='+s.latex(s.sympify(ans))),same(M(s.latex(s.sympify(ans)))),('원 비율과 도함수 비율의 양쪽 극한을 각각 계산했고 수치 그래프로 대조했다.','Computed the two-sided limits of both ratios independently and checked the numerical plots.'))
 assert s.limit(f/g,x,0)==ans and s.limit(df/dg,x,0)==ans
 plots(b,n,[(f'Ratios near zero: {n}',-.4,.4,float(ans)*.4,float(ans)*1.6,[('f/g',s.lambdify(x,f/g,'math')),("fprime/gprime",s.lambdify(x,df/dg,'math'))])])
ma(75,r'\lim_{x\to\infty}e^x/x^n=\infty,\quad n\in\mathbb N,\ n>0',[r'\infty/\infty:\quad \lim\frac{e^x}{x^n}=\lim\frac{e^x}{nx^{n-1}}=\cdots',r'=\lim_{x\to\infty}\frac{e^x}{n!}=\infty'],r'+\infty',('정확히 n회 미분하면 양의 상수 분모가 되며 각 중간 분모 도함수는 충분히 큰 x에서0이 아니다.','After exactly n differentiations the denominator is a positive constant; intermediate denominator derivatives are nonzero for large x.'))
ma(76,r'\lim_{x\to\infty}\frac{\ln x}{x^p}=0,\quad p>0',[r'\infty/\infty:\quad \lim\frac{\ln x}{x^p}=\lim\frac{1/x}{px^{p-1}}',r'=\lim\frac1{px^p}=0'],r'0',('정수뿐 아니라 모든 양의 실수 p에 적용되는 한 번의 미분이다.','One differentiation works for every positive real p, not only integers.'))
ma(77,r'\lim_{x\to\infty}\frac{x}{\sqrt{x^2+1}}',[r'\text{L’Hospital:}\quad\frac{1}{x/\sqrt{x^2+1}}=\frac{\sqrt{x^2+1}}x',r'\text{Instead:}\quad\frac{x}{\sqrt{x^2+1}}=\frac1{\sqrt{1+x^{-2}}}\to1'],r'1',('로피탈 적용은 원 비율의 역수로 돌아가 순환한다. 양의 x로 직접 나누어 극한을 확정했다.','L’Hospital produces the reciprocal ratio and leads to a cycle; dividing by positive x directly resolves the limit.'))
ma(78,r'\lim_{x\to(\pi/2)^-}\frac{\sec x}{\tan x}',[r'\text{L’Hospital:}\quad\frac{\sec x\tan x}{\sec^2x}=\frac{\tan x}{\sec x}',r'\text{Instead:}\quad\frac{\sec x}{\tan x}=\frac1{\sin x}\to1'],r'1',('도함수 비율은 다시 역비율로 바뀐다. 삼각함수 항등식은 바로 연속함수의 극한을 준다.','The derivative ratio becomes the reciprocal again; the trigonometric identity immediately gives a continuous-function limit.'))
print('6.8 THROUGH78',len(b.E))
curves={79:(x*s.exp(-x),(-3,8,-5,1),('정의역은 실수 전체, 원점이 유일한 절편이다. x→−∞에서−∞, x→∞에서0으로 가며 오른쪽 수평점근선은 y=0이다. x<1에서 증가, x>1에서 감소하고 (1,1/e)가 절대최대점이다. x<2에서 아래로 오목, x>2에서 위로 오목이며 변곡점은(2,2/e²)이다.','Domain R; the only intercept is the origin. Limits are−∞ on the left and0 on the right, giving right horizontal asymptote y=0. Increasing for x<1 and decreasing for x>1; absolute maximum(1,1/e). Concave down for x<2, up for x>2, with inflection(2,2/e²).')),80:(s.log(x)/x**2,(.15,5,-5,.3),('정의역 x>0, 절편(1,0). x→0⁺에서−∞, x→∞에서0⁺이므로 점근선은 x=0,y=0이다. √e까지 증가한 뒤 감소하고 절대최대점은(√e,1/(2e))이다. e^(5/6) 전에는 아래로, 후에는 위로 오목하며 그 x에서 변곡한다.','Domain x>0; intercept(1,0). Limits−∞ at0⁺ and0⁺ at∞ give asymptotes x=0,y=0. Increases to√e then decreases, with absolute maximum(√e,1/(2e)). Concave down before e^(5/6), up after it; that x is the inflection abscissa.')),81:(x*s.exp(-x*x),(-3,3,-.5,.5),('실수 전체에 정의된 홀함수이며 절편은 원점, 양끝 수평점근선은 y=0이다. |x|<1/√2에서 증가하고 그 밖에서는 감소한다. 절대최소점은(−1/√2,−1/√(2e)), 절대최대점은(1/√2,1/√(2e))이다. 변곡 x는−√(3/2),0,√(3/2)이며 이들을 지날 때 오목성이 아래·위·아래·위 순으로 바뀐다.','An odd function on R, with origin intercept and horizontal asymptote y=0 at both ends. Increasing for |x|<1/√2 and decreasing elsewhere. Absolute minimum(−1/√2,−1/√(2e)) and maximum(1/√2,1/√(2e)). Inflection abscissas−√(3/2),0,√(3/2), with successive concavity down,up,down,up.')),82:(s.exp(x)/x,(-4,4,-10,15),('정의역 x≠0, 절편 없음. −∞에서0⁻, 0⁻에서−∞, 0⁺와+∞에서+∞이다. x=0은 수직점근선이고 왼쪽 수평점근선은 y=0이다. (−∞,0),(0,1)에서 감소, (1,∞)에서 증가하며(1,e)는 국소최소점이다. 음수 가지는 아래로, 양수 가지는 위로 오목하고 변곡점은 없다.','Domain x≠0 and no intercepts. Limits0⁻ at−∞,−∞ at0⁻, and+∞ at0⁺ and+∞. Vertical asymptote x=0; left horizontal asymptote y=0. Decreases on(−∞,0),(0,1), increases on(1,∞);(1,e) is a local minimum. Negative branch is concave down, positive branch up, with no inflection point.')),83:(1/x+s.log(x),(.1,8,0,6),('정의역 x>0이고 양끝에서+∞이다. (0,1)에서 감소, (1,∞)에서 증가하며 절대최소점은(1,1)이므로 절편은 없다. x=0은 수직점근선이다. (0,2)에서 위로, (2,∞)에서 아래로 오목하고 변곡점은(2,1/2+ln2)이다.','Domain x>0, tending to+∞ at both ends. Decreases on(0,1), increases on(1,∞), and has absolute minimum(1,1), so no intercepts. Vertical asymptote x=0. Concave up on(0,2), down on(2,∞), with inflection(2,1/2+ln2).')),84:((x*x-3)*s.exp(-x),(-2,8,-6,8),('정의역은 실수 전체, x절편은±√3, y절편은−3이다. −∞에서+∞, +∞에서0⁺이다. (−∞,−1)에서 감소, (−1,3)에서 증가, (3,∞)에서 감소한다. (−1,−2e)는 절대최소점, (3,6/e³)는 국소최대점이다. 변곡 x는2±√5이고 이 두 값 사이에서 아래로, 바깥에서 위로 오목하다.','Domain R; x-intercepts±√3 and y-intercept−3. Limits+∞ at−∞ and0⁺ at+∞. Decreases on(−∞,−1), increases on(−1,3), decreases on(3,∞). Absolute minimum(−1,−2e), local maximum(3,6/e³). Inflection abscissas2±√5; concave down between them and up outside.'))}
for n,(f,window,desc)in curves.items():
 df=s.factor(s.diff(f,x));dd=s.factor(s.diff(f,x,2));add(n,(M('y='+s.latex(f))+'극한·증가감소·극값·오목성·변곡점을 조사하고 그래프를 그려라.',M('y='+s.latex(f))+'Analyze limits, monotonicity, extrema, concavity and inflections, then sketch.'),fs(r'y\prime='+s.latex(df),r'y\prime\prime='+s.latex(dd))+[desc],desc,('도함수·이계도함수의 영점과 각 사이 구간의 부호를 대조했다. 정의역 밖의 점은 변곡점으로 세지 않았다.','Checked derivative zeros and signs on intervening intervals; excluded points outside the domain from inflections.'))
 plots(b,n,[(f'Curve analysis {n}',*window,[('f',s.lambdify(x,f,'math'))])])
for n,f,window,limdesc,extdesc in[(85,x**(-x),(.002,4,0,1.7),('0⁺에서1, ∞에서0이다.','Limits are1 at0⁺ and0 at∞.'),('x<1/e에서 증가, x>1/e에서 감소하며 절대최대 e^(1/e)를 x=1/e에서 갖는다. 최솟값은 없고 하한은0이다. 변곡점은 정확히(1,1)이다.','Increases before1/e, decreases after1/e, with absolute maximum e^(1/e) at1/e. There is no minimum; the infimum is0. The exact inflection point is(1,1).')),(86,s.sin(x)**s.sin(x),(.001,float(P)-.001,.6,1.1),('실수 가변 거듭제곱의 양의 밑 구간0<x<π에서 양끝 극한은1이다. 같은 형태가2π 주기로 반복된다.','On the positive-base interval0<x<π, both endpoint limits are1. The same shape repeats with period2π.'),('α=arcsin(1/e)라 두면 α와π−α에서 절대최소 e^(−1/e), π/2에서 절대최대1이다. 감소·증가·감소·증가 구간은 α,π/2,π−α로 나뉜다. 변곡 x≈0.94396459,2.19762807이다.','Let α=arcsin(1/e). Absolute minima e^(−1/e) occur at α andπ−α; absolute maximum1 atπ/2. The intervals split by α,π/2,π−α have monotonicity decrease,increase,decrease,increase. Inflection abscissas≈0.94396459,2.19762807.')),(87,x**(1/x),(.04,10,0,1.7),('0⁺에서0, ∞에서1이다.','Limits are0 at0⁺ and1 at∞.'),('e까지 증가한 뒤 감소하며 절대최대 e^(1/e)를 x=e에서 갖는다. 최솟값은 없고 하한은0이다. 변곡 x≈0.58193271,4.36777097이며 오목성은 위·아래·위 순서이다.','Increases to e then decreases, attaining absolute maximum e^(1/e) at x=e. No minimum; infimum0. Inflection abscissas≈0.58193271,4.36777097, with successive concavity up,down,up.'))]:
 df=s.simplify(s.diff(f,x));dd=s.simplify(s.diff(f,x,2));add(n,(M('f(x)='+s.latex(f))+'(a) 그래프, (b) 경계 극한, (c) 극값의 추정과 정확한 계산, (d) CAS 이계도함수와 변곡점을 구하라.',M('f(x)='+s.latex(f))+'Find(a)graph,(b)boundary limits,(c)estimated and exact extrema,(d)CAS second derivative and inflections.'),[('로그미분으로 도함수를 구하고, 첫 도함수의 부호로 극값을 분류한다. 이계도함수의 부호 변화가 변곡을 판정한다.','Use logarithmic differentiation and derivative signs to classify extrema. Sign changes of the second derivative identify inflections.')]+fs(r'f\prime='+s.latex(df),r'f\prime\prime='+s.latex(dd))+[limdesc,extdesc],(limdesc[0]+' '+extdesc[0],limdesc[1]+' '+extdesc[1]),('도함수식을 CAS로 계산하고 이계도함수의 영점 양쪽 부호를 수치로 확인했다.','Computed derivatives with CAS and checked second-derivative signs on both sides of the roots.'),list('abcd'))
 lo,hi,yl,yh=window;plots(b,n,[(f'Function {n}',lo,hi,yl,yh,[('f',s.lambdify(x,f,'math'))]),(f'Second derivative {n}',lo,hi,-5,5,[('f second',s.lambdify(x,dd,'math'))])])
add(88,('양의 정수 n에 대한 f_n(x)=xⁿe⁻ˣ의 공통 성질과 차이를 조사하라. 특히 극값·변곡점의 n에 따른 이동을 설명하고 여러 그래프를 그려라.','Investigate f_n(x)=xⁿe⁻ˣ for positive integers n. Compare common features and differences, track extrema and inflections as n grows, and graph several members.'),fs(r'f_n\prime=x^{n-1}e^{-x}(n-x)',r'f_n\prime\prime=x^{n-2}e^{-x}[(x-n)^2-n]\quad(n\ge2)',r'f_n(n)=n^ne^{-n},\quad x_{\mathrm{inflection}}=n\pm\sqrt n\quad(n\ge2)',r'n=1:\ f_1\prime\prime=e^{-x}(x-2)')+[('모두 원점을 지나며 +∞에서0으로 간다. 음의 무한대에서는 n이 짝수면+∞, 홀수면−∞이다. 양수 가지는 n까지 증가한 뒤 감소하며 최대점의 x=n과 높이(n/e)ⁿ은 n이 커질 때 증가한다.','All pass through the origin and tend to0 at+∞. At−∞ the limit is+∞ for even n and−∞ for odd n. The positive branch rises to n then falls; both x=n and peak height(n/e)ⁿ increase with n.'),('짝수 n은 원점에서 국소최소0, x=n에서 국소최대가 있다. 홀수 n은 x=n에서 절대최대, 원점에는 극값이 없다. n≥3인 홀수 n은 원점이 추가 변곡점이다. 양수 변곡점 n±√n은 오른쪽으로 이동하고 간격2√n이 커진다. n=1은 x=2만 변곡한다.','Even n has local minimum0 at the origin and a local maximum at n. Odd n has an absolute maximum at n and no extremum at zero. For odd n≥3 the origin is an additional inflection. Positive inflections n±√n move right and separate by2√n; for n=1 the sole inflection is x=2.')],('도함수의 인수와 n의 홀짝에 따른 분류 및 첨부 그래프와 같다.','See the derivative factorization, parity classification and attached graphs.'),('원점을 포함한 실수 전체에서 부호를 확인했다. n=1에서 n−√n=0을 가짜 변곡점으로 세지 않았다.','Checked signs on the entire real line, including zero. For n=1, did not count n−√n=0 as a false inflection.'))
plots(b,88,[('Polynomial times exponential',-2,10,-10,25,[(f'n={nn}',lambda q,nn=nn:q**nn*math.exp(-q))for nn in[1,2,3,4,5]])])
add(89,('f(x)=eˣ−cx의 곡선족을 조사하라. 양끝 극한, 절대최소를 갖는 c의 조건 및 c가 증가할 때 최소점의 이동을 설명하라.','Investigate f(x)=eˣ−cx: limits at both infinities, which c give an absolute minimum, and how minimum points move as c increases.'),fs(r'f\prime=e^x-c,\quad f\prime\prime=e^x>0',r'c>0:\ x_{\min}=\ln c,\quad f_{\min}=c(1-\ln c)',r'\lim_{x\to+\infty}f=\infty,\quad\lim_{x\to-\infty}f=\begin{cases}\infty&c>0\\0&c=0\\-\infty&c<0\end{cases}')+[('c>0일 때만 절대최소를 가지며 그 x좌표는 오른쪽으로 이동한다. 최소 높이는 0＜c＜1에서 증가하고 c>1에서 감소하며 c=1에서 최대 높이1을 갖는다. c≤0이면 항상 증가하며 최소는 없다.','An absolute minimum exists exactly for c>0, and its x-coordinate moves right. The minimum height increases for0＜c＜1 and decreases for c>1, reaching height1 at c=1. For c≤0 the function is strictly increasing with no minimum.')],same(M(r'c>0:\ (\ln c,c(1-\ln c))')),('최소 높이를 c로 미분하면−ln c이고 x좌표를 미분하면1/c>0이다.','The derivatives of the minimum height and its x-coordinate are−ln c and1/c>0.'))
plots(b,89,[('Exponential minus linear term',-3,3,-5,15,[(f'c={c}',lambda q,c=c:math.exp(q)-c*q)for c in[-1,0,.5,1,3]])])
add(90,('질량 m인 낙하 물체의 속력 모형 v=(mg/c)(1−e^(−ct/m)), c>0에 대해 (a) t→∞ 극한과 의미, (b) 고정 t에서 c→0⁺ 극한과 진공에서의 속력을 구하라.','For the falling-object speed model v=(mg/c)(1−e^(−ct/m)), c>0, find(a)the limit as t→∞ and its meaning,(b)the limit as c→0⁺ at fixed t and the vacuum speed.'),fs(r'(a)\ e^{-ct/m}\to0\Rightarrow v\to mg/c',r'(b)\ \lim_{c\to0^+}mg\frac{1-e^{-ct/m}}c=mg\lim_{c\to0^+}\frac tm e^{-ct/m}=gt'),('(a)종단속력 mg/c. (b) gt, 즉 저항 없는 정지 출발 낙하의 속력이다.','(a)Terminal speed mg/c.(b)gt, the speed of free fall from rest without resistance.'),('m,g는 양수로 고정하고 b에서는 t도 고정했다. c=0을 원래0/0 모형에 직접 대입하지 않았다.','Held m,g positive and t fixed in part b; avoided substituting c=0 into the original0/0 formula.'),['a','b'])
ma(91,r'A_n=A_0(1+r/n)^{nt}\Rightarrow\lim_{n\to\infty}A_n=A_0e^{rt}',[r'\ln(A_n/A_0)=t\frac{\ln(1+r/n)}{1/n}',r'\lim\ln(A_n/A_0)=t\lim\frac{-r/[n^2(1+r/n)]}{-1/n^2}=rt',r'A_n\to A_0e^{rt}'],r'A_0e^{rt}',('연속변수 n의 극한을 구한 뒤 정수 n 수열에도 같은 극한이 성립함을 사용했다.','Computed the continuous-variable limit, which also gives the limit along integer compounding frequencies.'))
rho=mp.mpf('.05');perc=lambda r:100*(1-mp.power(10,-rho*r*r))/(rho*r*r*mp.log(10))
add(92,('눈의 광량 감지 비율 모형 P=(1−10^(−ρr²))/(ρr²ln10), ρ=0.05이다. (a) r=3mm, (b) r=2mm의 백분율과 차이의 의미, (c) r→0⁺ 극한 및 물리적 의미를 설명하라.','For the sensed-light fraction P=(1−10^(−ρr²))/(ρr²ln10),ρ=0.05, find(a)the percentage at r=3mm,(b)at r=2mm and explain the difference,(c)the limit as r→0⁺ and its physical interpretation.'),fs(r'P(3)=\frac{1-10^{-0.45}}{0.45\ln10},\quad P(2)=\frac{1-10^{-0.20}}{0.20\ln10}',r'\lim_{r\to0^+}P=\lim_{r\to0^+}\frac{2\rho r\ln10\,10^{-\rho r^2}}{2\rho r\ln10}=1')+[('작은 동공에서는 가장자리 빛의 비중이 줄어 감지 비율이 커진다. 극한100%는 중심으로 들어오는 빛의 상대 효율에 관한 이상화이다. 반지름0인 실제 동공으로 빛이 들어온다는 뜻은 아니며 총 입사 광량도0으로 간다.','A smaller pupil reduces the proportion of peripheral light, raising the sensed fraction. The100% limit is an idealization of central-ray relative efficiency; it does not mean light enters a pupil of zero radius, and total incident light tends to zero.')],same(M(fr'(a)\ {float(perc(3)):.5f}\%;\quad(b)\ {float(perc(2)):.5f}\%;\quad(c)\ 100\%')),('P식은0과1 사이 비율이므로 백분율을 표시할 때100을 곱했다. 극한 비율과 실제 총광량을 구별했다.','P is a fraction between0 and1, so multiplied by100 for percentages; distinguished limiting fraction from total light.'),list('abc'))
add(93,('P(t)=M/(1+Ae⁻ᵏᵗ), A=(M−P₀)/P₀, M,A,k>0인 로지스틱 모형에서 (a) t→∞, (b) P₀,k,t를 고정한 M→∞ 극한을 구하고 해석하라.','For P(t)=M/(1+Ae⁻ᵏᵗ), A=(M−P₀)/P₀, M,A,k>0, evaluate and interpret(a)t→∞,(b)M→∞ with P₀,k,t fixed.'),fs(r'(a)\ e^{-kt}\to0\Rightarrow P(t)\to M',r'(b)\ P(t)=\frac1{1/M+(1/P_0-1/M)e^{-kt}}\to P_0e^{kt}'),('(a)환경수용력 M으로 수렴한다.(b)제한 없는 지수성장 P₀eᵏᵗ이다.','(a)Approaches carrying capacity M.(b)Unrestricted exponential growth P₀eᵏᵗ.'),('M을 바꿀 때 A도 함께 바뀌므로 A를 고정하지 않고 원 정의를 먼저 대입했다.','Since A changes with M, substituted its definition before taking the limit.'),['a','b'])
add(94,('케이블 반지름 r, 절연체 바깥 반지름 R에 대한 v=−c(r/R)²ln(r/R), c>0,0<r<R이다. (a) 고정 r에서 R→r⁺, (b) 고정 R에서 r→0⁺ 극한을 구하고 해석하라.','For v=−c(r/R)²ln(r/R), c>0 and0<r<R, find and interpret(a)R→r⁺ with r fixed,(b)r→0⁺ with R fixed.'),fs(r'u=r/R,\quad(a)\ u\to1^-:\ -cu^2\ln u\to0',r'(b)\ u\to0^+:\quad\lim u^2\ln u=\lim\frac{\ln u}{u^{-2}}=\lim\frac{1/u}{-2u^{-3}}=0'),('(a),(b)모두0이다. 이 모형에서는 절연 두께가 사라지거나 도체 반지름이 사라지는 극한에서 전달 속력이0으로 간다.','Both limits are0. In this model, speed tends to zero as either insulation thickness or conductor radius vanishes.'),('두 물리적 극한이 비율 u의 서로 다른 끝점1과0에 해당함을 구별했다.','Distinguished the two physical limits as the different endpoints1 and0 of the ratio u.'),['a','b'])
ma(95,r'\lim_{x\to0}\frac1{x^2}\int_0^x\frac{2t}{\sqrt{t^3+1}}\,dt',[r'0/0:\quad\frac{d}{dx}\int_0^x\frac{2t}{\sqrt{t^3+1}}\,dt=\frac{2x}{\sqrt{x^3+1}}',r'\lim_{x\to0}\frac{2x/\sqrt{x^3+1}}{2x}=\lim_{x\to0}\frac1{\sqrt{x^3+1}}=1'],r'1',('원점 근방에서 피적분함수는 연속이며 미적분 기본정리를 먼저 적용했다.','The integrand is continuous near zero, permitting the Fundamental Theorem before l’Hospital.'))
ma(96,r'\lim_{x\to\infty}\frac1{x^2}\int_0^x\ln(1+e^t)\,dt',[r'\ln(1+e^t)\ge t\ (t\ge0)\Rightarrow\int_0^x\ln(1+e^t)dt\to\infty',r'\lim\frac{\int_0^x\ln(1+e^t)dt}{x^2}=\lim\frac{\ln(1+e^x)}{2x}',r'=\lim\frac{e^x/(1+e^x)}2=1/2'],r'1/2',('첫 단계의∞/∞ 조건을 하한 x²/2로 확인하고 두 번째도∞/∞임을 확인했다.','Verified the first∞/∞ form using the lower bound x²/2 and checked the second∞/∞ form.'))
ma(97,r'S(x)=\int_0^x\sin(\pi t^2/2)\,dt,\quad\lim_{x\to0}S(x)/x^3',[r'0/0:\quad\lim S(x)/x^3=\lim\frac{\sin(\pi x^2/2)}{3x^2}',r'=\frac\pi6\lim\frac{\sin(\pi x^2/2)}{\pi x^2/2}=\pi/6'],r'\pi/6',('FTC의 도함수와 sin u/u→1을 사용했다. 세제곱의 부호는 좌우 적분 방향과 일치한다.','Used the FTC derivative and sin u/u→1; the cube’s sign matches the integration orientation on both sides.'))
ma(98,r'T(x,t)=\frac C{a\sqrt{4\pi kt}}\int_0^ae^{-(x-u)^2/(4kt)}\,du,\quad\lim_{a\to0}T(x,t)',[r'k,t>0:\quad\lim_{a\to0}\frac{\int_0^ae^{-(x-u)^2/(4kt)}du}{a}',r'\overset{\mathrm H}{=}\lim_{a\to0}e^{-(x-a)^2/(4kt)}=e^{-x^2/(4kt)}'],r'\frac C{\sqrt{4\pi kt}}e^{-x^2/(4kt)}',('x,k,t는 고정하고 a에 대해 미분했다. 이 극한은 주어진 온도 모형의 핵심인 초기 열점의 가우스 분포이다.','Held x,k,t fixed and differentiated with respect to a; the limit is the Gaussian distribution of the model’s initial heat spot.'))
ma(99,r'\lim_{x\to a}\frac{\sqrt{2a^3x-x^4}-a\sqrt[3]{a^2x}}{a-\sqrt[4]{ax^3}},\quad a>0',[r'x=a:\quad N=D=0',r'N\prime=\frac{2a^3-4x^3}{2\sqrt{2a^3x-x^4}}-\frac{a^3}{3(a^2x)^{2/3}},\quad D\prime=-\frac{3ax^2}{4(ax^3)^{3/4}}',r'N\prime(a)=-a-a/3=-4a/3,\quad D\prime(a)=-3/4'],r'16a/9',('a>0에서 근호의 주값과 도함수가 a 근처에 실수로 정의되며 분모 도함수가0이 아니다.','For a>0 the principal radicals and derivatives are real near a, with nonzero denominator derivative.'))
add(100,('반지름 r인 원에서 O=(0,0), R=(r,0), P=(r cosθ,r sinθ), Q=(r cosθ,0)이다. A는 현 PR과 호 PR 사이 넓이, B는 삼각형 PQR의 넓이이다. θ→0⁺에서 A/B를 구하라.','For a circle of radius r, let O=(0,0), R=(r,0), P=(r cosθ,r sinθ), Q=(r cosθ,0). A is the area between chord PR and arc PR, and B is the area of triangle PQR. Find A/B as θ→0⁺.'),fs(r'A=\tfrac12r^2(\theta-\sin\theta),\quad B=\tfrac12r^2\sin\theta(1-\cos\theta)',r'\frac AB=\frac{\theta-\sin\theta}{\sin\theta(1-\cos\theta)}',r'\theta-\sin\theta\sim\theta^3/6,\quad\sin\theta(1-\cos\theta)\sim\theta^3/2',r'\lim A/B=(1/6)/(1/2)=1/3'),same(M('1/3')),('삼각형 B의 밑변은 r(1−cosθ), 높이는 r sinθ이다. 세 번 미분해도 같은 비율1/3을 얻는다.','Triangle B has base r(1−cosθ) and height r sinθ. Three differentiations give the same ratio1/3.'))
ma(101,r'\lim_{x\to\infty}\left[x-x^2\ln\frac{1+x}{x}\right]',[r'u=1/x\to0^+:\quad x-x^2\ln(1+1/x)=\frac{u-\ln(1+u)}{u^2}',r'\overset{\mathrm H}{\longrightarrow}\lim\frac{1-1/(1+u)}{2u}=\lim\frac1{2(1+u)}=1/2'],r'1/2',('공통인수 x²로 직접∞−∞를 처리하지 않고 u치환 후0/0의 비율로 만들었다.','Substitution u converts the∞−∞ expression to a0/0 ratio.'))
add(102,('f>0, f(x)→0, g(x)→+∞일 때 f(x)^{g(x)}→0임을 증명하라.','Prove f(x)^{g(x)}→0 when f>0, f(x)→0 and g(x)→+∞.'),fs(r'x\text{ sufficiently near }a:\quad0<f(x)<1,\quad g(x)>1',r'0<f(x)^{g(x)}\le f(x)\to0'),same(M(r'\lim_{x\to a}f(x)^{g(x)}=0')),('조임정리는 밑이 양수라는 가정을 사용하며0^∞가 부정형이 아님을 직접 증명한다.','The squeeze theorem uses the positive-base assumption and directly proves that0^∞ is not indeterminate.'))
ma(103,r'f(x),g(x)\to\infty\ (x\to0):\quad(a)\ f/g\to7;\quad(b)\ f-g\to7',[r'(a)\ f(x)=7/x^2,\quad g(x)=1/x^2\Rightarrow f/g=7',r'(b)\ f(x)=7+1/x^2,\quad g(x)=1/x^2\Rightarrow f-g=7'],r'(a)\ (f,g)=(7/x^2,1/x^2);\quad(b)\ (f,g)=(7+1/x^2,1/x^2)',('1/x²는 양쪽에서+∞로 가므로 단측 극한에만 맞는 예가 아니다.','Since1/x² tends to+∞ from both sides, these examples satisfy two-sided limits.'),['a','b'])
ma(104,r'\lim_{x\to0}\left(\frac{\sin2x}{x^3}+a+\frac b{x^2}\right)=0',[r'\sin2x=2x-\tfrac43x^3+O(x^5)',r'\frac{\sin2x}{x^3}+a+\frac b{x^2}=\frac{2+b}{x^2}+a-\tfrac43+O(x^2)',r'2+b=0,\quad a-4/3=0'],r'a=4/3,\quad b=-2',('발산항 계수와 상수항을 각각0으로 만들었다. 이 값들을 대입하면 남은 항이 O(x²)이다.','Set the divergent coefficient and constant term to zero separately; substitution leaves O(x²).'))
add(105,('x≠0에서 f(x)=e^(−1/x²), f(0)=0이다. (a) 정의로 f′(0)을 구하고 (b) 실수 전체에서 모든 차수 도함수가 존재함을 증명하라.','Let f(x)=e^(−1/x²) for x≠0 and f(0)=0. (a) Find f′(0) from the definition; (b) prove derivatives of every order exist on R.'),fs(r'(a)\ f\prime(0)=\lim_{h\to0}\frac{e^{-1/h^2}}h=0',r'\forall m\ge0:\quad |h|^{-m}e^{-1/h^2}\to0\quad(u=1/h^2,\ u^{m/2}e^{-u}\to0)',r'(b)\ f^{(n)}(x)=P_n(1/x)e^{-1/x^2}\quad(x\ne0),\quad P_0(u)=1',r'P_{n+1}(u)=-u^2P_n\prime(u)+2u^3P_n(u)',r'f^{(n+1)}(0)=\lim_{h\to0}\frac{P_n(1/h)e^{-1/h^2}}h=0')+[('귀납적으로 P_n은 다항식이고 모든 거듭제곱보다 빠른 지수 감쇠가 각 차분몫을0으로 보낸다. 같은 추정이 f⁽ⁿ⁾(x)→0도 주어 각 도함수는 원점에서 연속이다.','Inductively P_n is a polynomial, and exponential decay faster than every power sends each difference quotient to0. The same bound gives f⁽ⁿ⁾(x)→0, so every derivative is continuous at the origin.')],same(M(r'f\in C^\infty(\mathbb R),\quad f^{(n)}(0)=0\ \text{for all }n\ge0')),('원점 밖 미분 공식만으로 끝내지 않고 원점의 차분몫을 각 귀납 단계에서 확인했다.','At every induction step verified the derivative definition at zero, not only formulas away from it.'),['a','b'])
add(106,('x≠0에서 f(x)=|x|ˣ, f(0)=1이다. (a)0에서 연속성을 증명하고 (b)원점 근처를 여러 번 확대해 미분가능성을 추정한 뒤 (c)미분불가능을 증명하고 그래프와의 관계를 설명하라.','Let f(x)=|x|ˣ for x≠0 and f(0)=1. (a) Prove continuity at0, (b) inspect successive zooms to assess differentiability, and (c) prove nondifferentiability and reconcile it with the graphs.'),fs(r'(a)\ \ln f(x)=x\ln|x|\to0\Rightarrow f(x)\to1',r'(c)\ u=h\ln|h|\to0:\quad\frac{|h|^h-1}h=\frac{e^u-1}u\ln|h|\to-\infty')+[('양쪽 차분몫이 모두−∞로 가므로 유한 도함수는 없다. 그래프는 수직 접선 x=0을 가진다. 확대 그림이 매끈하거나 거의 직선처럼 보이더라도 유한한 기울기를 보장하지 않는다. 확대할수록 겉보기 기울기의 절댓값이 계속 커지며 축 눈금의 비율에도 주의해야 한다.','Both difference quotients tend to−∞, so there is no finite derivative. The graph has vertical tangent x=0. A smooth-looking or nearly straight zoom does not guarantee a finite slope; the apparent slope magnitude keeps growing, and axis scales matter.')],('(a)연속.(b)확대 그래프 참조.(c)미분불가능하며 수직 접선 x=0을 갖는다.','(a)Continuous.(b)See zoomed graphs.(c)Not differentiable; vertical tangent x=0.'),('양쪽에서 h ln|h|→0이지만 ln|h|→−∞임을 구별하여 연속성과 미분가능성을 따로 검산했다.','Distinguished h ln|h|→0 from ln|h|→−∞ to verify continuity separately from differentiability.'),list('abc'))
plots(b,106,[(f'Zoom |x| <= {eps}',-eps,eps,1-5*eps,1+5*eps,[('|x|^x',lambda q:math.exp(q*math.log(abs(q)))if q else 1)])for eps in[.1,.01,.001]])
# Clear prompts for equations that ask for unknown parameters or examples.
for n,ko,en in[(95,'극한을 구하라.','Evaluate the limit.'),(96,'극한을 구하라.','Evaluate the limit.'),(97,'S(x)/x³의 극한을 구하라.','Find the limit of S(x)/x³.'),(98,'a→0의 극한을 구하라.','Find the limit as a→0.'),(103,'조건을 만족하는 함수 f,g의 예를 각각 찾아라.','Find example functions f,g satisfying each condition.'),(104,'조건을 만족하는 실수 a,b를 구하라.','Find real a,b satisfying the condition.')]:
 b.E[n]['statement']['ko']=b.E[n]['statement']['ko'].replace('극한을 구하거나 명제를 증명하라.',ko);b.E[n]['statement']['en']=b.E[n]['statement']['en'].replace('Evaluate the limit or prove the assertion.',en)
b.save();print('6.8 COMPLETE',len(b.E))
# Keep the derivations within the methods introduced in this section.
b.E[100]['steps']=pair(*[[] for _ in range(2)])
for ko,en in fs(r'A=\tfrac12r^2(\theta-\sin\theta),\quad B=\tfrac12r^2\sin\theta(1-\cos\theta)',r'\lim\frac AB=\lim\frac{1-\cos\theta}{\cos\theta(1-\cos\theta)+\sin^2\theta}',r'\overset{\mathrm H}{=}\lim\frac{\sin\theta}{\sin\theta(4\cos\theta-1)}=\lim\frac1{4\cos\theta-1}=1/3'):
 b.E[100]['steps']['ko'].append(ko);b.E[100]['steps']['en'].append(en)
b.E[104]['steps']=pair(*[[] for _ in range(2)])
for ko,en in fs(r'\text{A finite limit requires }\lim_{x\to0}x^2\left(\frac{\sin2x}{x^3}+a+\frac b{x^2}\right)=2+b=0',r'b=-2:\quad\lim\frac{\sin2x-2x}{x^3}\overset{\mathrm H}{=}\lim\frac{2\cos2x-2}{3x^2}',r'\overset{\mathrm H}{=}\lim\frac{-4\sin2x}{6x}\overset{\mathrm H}{=}\lim\frac{-8\cos2x}{6}=-4/3',r'a-4/3=0\Rightarrow a=4/3'):
 b.E[104]['steps']['ko'].append(ko);b.E[104]['steps']['en'].append(en)
for ko,en in fs(r'\lim_{u\to\infty}\frac{e^{u/10}}{u^3}\overset{\mathrm H}{=}\lim\frac{e^{u/10}}{30u^2}\overset{\mathrm H}{=}\lim\frac{e^{u/10}}{600u}\overset{\mathrm H}{=}\lim\frac{e^{u/10}}{6000}=\infty'):
 b.E[26]['steps']['ko'].append(ko);b.E[26]['steps']['en'].append(en)
b.E[100]['check']=pair('밑변 r(1−cosθ)와 높이 r sinθ로 B를 계산하고 로피탈을 두 번 적용해1/3을 확인했다.','Computed B from base r(1−cosθ) and height r sinθ, then used l’Hospital twice to confirm1/3.')
b.E[104]['check']=pair('발산항을 없애는 필요조건 b=−2를 먼저 얻고 세 번 미분하여 남은 상수 a를 결정했다.','First obtained the necessary cancellation b=−2, then used three differentiations to determine a.')
b.save()
