from calc1_inverse_helpers import *
from calc1_plot_helpers import plots
x,t,u,z=s.symbols('x t u z',real=True);a,c,C=s.symbols('a c C',real=True);R=s.Rational;P=s.pi;b=CalcBook('6.4',[448,449,450])
def add(n,st,steps,ans,ck,parts=[]):
 b.add(n,448 if n<=24 else 449 if n<=74 else 450,('로그함수의 도함수','Derivatives of logarithmic functions'),st,steps,ans,parts=parts);b.verify(n,*ck);b.save()
add(1,('미적분에서 다른 밑의 로그보다 자연로그를 자주 사용하는 이유를 설명하라.','Explain why the natural logarithm is used more often than other logarithms in calculus.'),fs(r'\frac{d}{dx}\ln x=\frac1x',r'\frac{d}{dx}\log_bx=\frac1{x\ln b}')+[('밑e에서는 추가 상수1/lnb가1이 되어 미분·적분식이 간단하다.','For basee,the extra constant1/lnb equals1,simplifying differentiation and integration.')],('자연로그의 도함수가1/x로 가장 간단하기 때문이다.','Its derivative1/x has the simplest form.'),('ln e=1을 일반 밑의 미분 공식에 대입했다.','Substituted ln e=1 into the general-base derivative formula.'))
D={2:(t,s.log(3+t*t)),3:(x,s.log(x*x+3*x+5)),4:(x,x*s.log(x)-x),5:(x,s.sin(s.log(x))),6:(x,s.log(s.sin(x)**2)),7:(x,s.log(1/x)),8:(x,1/s.log(x)),9:(x,s.log(x*s.exp(-2*x))),10:(t,s.sqrt(1+s.log(t))),11:(t,s.log(t)**2*s.sin(t)),12:(t,s.log(s.sqrt(t*t+1))),13:(x,s.log(x*x+3*x)/s.log(8)),14:(x,s.log(s.sec(x))/s.log(10)),15:(u,s.log(u)/(1+s.log(2*u))),16:(x,s.log(s.csc(x)-s.cot(x))),17:(x,x**5+5**x),18:(x,x*s.sin(2**x)),19:(z,2**z*s.log(z)/s.log(2)),20:(x,s.exp(x*x*s.log(x))),21:(t,s.log(t*(t*t+1)**4/(2*t-1)**R(1,3))),22:(x,s.log(s.sqrt((1+2*x)/(1-2*x)))),23:(x,s.log(s.Abs(3-2*x**5))),24:(x,s.log(s.exp(-x)+x*s.exp(-x))),25:(x,s.tan(s.log(a*x+c))),26:(x,s.log(x*s.log(x)/s.log(5))/s.log(2)),27:(x,4**(C/x)),28:(t,3**s.cos(2*t))}
manual={16:s.csc(x),21:1/t+8*t/(t*t+1)-2/(3*(2*t-1)),23:-10*x**4/(3-2*x**5)}
for n,(v,f)in D.items():
 df=manual.get(n,s.diff(f,v));sub={a:R(2,3),c:2,C:R(3,4)};ff=s.lambdify(v,f.subs(sub),'mpmath');dd=s.lambdify(v,df.subs(sub),'mpmath');vals=[mp.mpf('2.1'),mp.mpf('2.3')]if n in[10,21,26]else[mp.mpf('.2'),mp.mpf('.4')]
 for q in vals:assert abs(mp.diff(ff,q)-dd(q))<mp.mpf('1e-15'),(n,q)
 add(n,(M('f('+s.latex(v)+')='+s.latex(f))+'미분하라.',M('f('+s.latex(v)+')='+s.latex(f))+'Differentiate.'),fs(r'(\ln h)\prime=h\prime/h,\quad(b^h)\prime=b^h\ln(b)h\prime')+[('합성함수의 안쪽 도함수를 곱하고 필요한 곱·몫의 미분법을 적용한다. 원래 함수가 실수로 미분 가능한 구간에서 계산한다.','Multiply by the inner derivative and apply product/quotient rules as needed,working on intervals where the original real function is differentiable.')]+fs(r'f\prime('+s.latex(v)+')='+s.latex(s.simplify(df))),same(M(s.latex(s.simplify(df)))),('원래 함수의 수치 미분과 도함수를 허용 입력 두 개에서 독립 대조했다. 상수 매개변수는 대표값에서도 확인했다.','Independently compared the derivative with numerical differentiation at two admissible inputs,also using representative values for constant parameters.'))
add(29,('ln(x+√(x²+1))의 도함수가1/√(x²+1)임을 보여라.','Show that the derivative ofln(x+√(x²+1)) is1/√(x²+1).'),fs(r'\frac{d}{dx}\ln(x+\sqrt{x^2+1})=\frac{1+x/\sqrt{x^2+1}}{x+\sqrt{x^2+1}}',r'=\frac{\sqrt{x^2+1}+x}{\sqrt{x^2+1}(x+\sqrt{x^2+1})}=\frac1{\sqrt{x^2+1}}'),same(M(r'\frac1{\sqrt{x^2+1}}')),('√(x²+1)>|x|이므로 약분한 인자와 로그 입력이 항상 양수이다.','Since√(x²+1)>|x|,the canceled factor and logarithm argument are always positive.'))
add(30,('ln√((1-cosx)/(1+cosx))의 도함수가cscx임을 보여라.','Show that the derivative ofln√((1-cosx)/(1+cosx)) iscscx.'),fs(r'y=\tfrac12[\ln(1-\cos x)-\ln(1+\cos x)]',r'y\prime=\tfrac12\left[\frac{\sin x}{1-\cos x}+\frac{\sin x}{1+\cos x}\right]=\frac{\sin x}{1-\cos^2x}=\csc x'),same(M(r'\csc x,\quad x\ne k\pi')),('원래 식의 정의역은sinx≠0이며 그 위에서는 두 로그 입력이 모두 양수이다.','The original domain issinx≠0,and both logarithm arguments are positive there.'))
for n,f,first,second in[(31,s.sqrt(x)*s.log(x),(s.log(x)+2)/(2*s.sqrt(x)),-s.log(x)/(4*x**R(3,2))),(32,s.log(x)/(1+s.log(x)),1/(x*(1+s.log(x))**2),-(s.log(x)+3)/(x*x*(1+s.log(x))**3)),(33,s.log(s.Abs(s.sec(x))),s.tan(x),s.sec(x)**2),(34,s.log(1+s.log(x)),1/(x*(1+s.log(x))),-(s.log(x)+2)/(x*x*(1+s.log(x))**2))]:
 if n!=33:
  assert s.simplify(s.diff(f,x)-first)==0 and s.simplify(s.diff(first,x)-second)==0
 add(n,(M('y='+s.latex(f))+'1계·2계 도함수를 구하라.',M('y='+s.latex(f))+'Find the first and second derivatives.'),fs(r'y\prime='+s.latex(first),r'y\prime\prime='+s.latex(second))+[('첫 도함수에 곱·연쇄법칙을 다시 적용하여 두 번째 도함수를 얻는다.','Apply product and chain rules again to the first derivative to obtain the second.')],same(M(r'y\prime='+s.latex(first)+r',\quad y\prime\prime='+s.latex(second))),('1계 도함수를 다시 미분하여2계 식과 비교했다. 절댓값 로그는 내부함수가0이 아닌 구간에서 h′/h를 사용한다.','Differentiated the first derivative again and compared;for an absolute-value logarithm,use h′/h where its argument is nonzero.'))
for n,f,dom in[(35,x/(1-s.log(x-1)),r'(1,1+e)\cup(1+e,\infty)'),(36,s.sqrt(2+s.log(x)),r'[e^{-2},\infty)'),(37,s.log(x*x-2*x),r'(-\infty,0)\cup(2,\infty)'),(38,s.log(s.log(x)),r'(1,\infty)')]:
 df=s.simplify(s.diff(f,x));add(n,(M('f(x)='+s.latex(f))+'정의역과 도함수를 구하라.',M('f(x)='+s.latex(f))+'Find the domain and derivative.'),fs(r'D_f='+dom,r'f\prime='+s.latex(df))+[('로그 입력은 양수,제곱근 입력은 비음수,분모는0이 아니어야 한다.36의 왼쪽 끝점에는 유한 도함수가 없다.','Logarithm arguments must be positive,radicands nonnegative,and denominators nonzero.The left endpoint in36 has no finite derivative.')],same(M(r'D_f='+dom+r';\quad f\prime='+s.latex(df))),('원래 식의 각 층에서 정의역 조건을 적용한 뒤 도함수는 미분 가능한 내부점에서만 사용했다.','Applied domain restrictions layer by layer and used the derivative only at differentiable interior points.'))
for n,f in[(39,s.log(x+s.log(x))),(40,s.cos(s.log(x*x)))]:
 val=s.diff(f,x).subs(x,1);add(n,(M('f(x)='+s.latex(f))+'f′(1)을 구하라.',M('f(x)='+s.latex(f))+'Findf′(1).'),fs(r'f\prime(x)='+s.latex(s.diff(f,x)),r'f\prime(1)='+s.latex(val)),same(M(s.latex(val))),('미분 후x=1을 대입했고 원래 함수가1 근처에서 정의됨을 확인했다.','Differentiated before substitutingx=1 and checked the function is defined near1.'))
for n,f,q in[(41,s.log(x*x-3*x+1),3),(42,x*x*s.log(x),1)]:
 slope=s.diff(f,x).subs(x,q);add(n,(M('y='+s.latex(f)+r',\quad('+str(q)+',0)')+'접선을 구하라.',M('y='+s.latex(f)+r',\quad('+str(q)+',0)')+'Find the tangent line.'),fs(r'y\prime='+s.latex(s.diff(f,x)),r'm='+s.latex(slope),'y='+s.latex(slope*(x-q))),same(M('y='+s.latex(slope*(x-q)))),('주어진 점의 함수값0과 접선 기울기를 원래 식에서 다시 확인했다.','Rechecked function value0 and tangent slope at the given point.'))
print('6.4 first42',len(b.E))
add(43,('f(x)=sinx+lnx의 도함수를 구하고 두 그래프를 비교해 타당성을 확인하라.','Differentiate f(x)=sinx+lnx and compare the function and derivative graphs to check plausibility.'),fs(r'f\prime(x)=\cos x+1/x,\quad x>0')+[('f′가 양수인 구간에서f가 증가하고 음수인 구간에서 감소한다. 큰x에서는1/x가 작아져 도함수가cosx에 가까워진다.','f increases where f′ is positive and decreases where it is negative.For large x,the1/x term shrinks andf′ approachescosx.')],same(M(r'f\prime(x)=\cos x+1/x')),('원래 함수를 수치 미분해 cosx+1/x와 여러 양의x에서 대조했다.','Compared numerical derivatives of the original function withcosx+1/x at several positive inputs.'))
plots(b,43,[('6.4.43 Function and derivative',.1,12,-3,5,[('f=sinx+lnx',lambda q:math.sin(q)+math.log(q)),('derivative',lambda q:math.cos(q)+1/q)])])
add(44,('y=lnx/x의(1,0),(e,1/e)에서 접선을 구하고 곡선과 함께 그려라.','Find tangents toy=lnx/x at(1,0) and(e,1/e),then graph them with the curve.'),fs(r'y\prime=(1-\ln x)/x^2',r'y\prime(1)=1,\quad y\prime(e)=0',r'y=x-1;\quad y=1/e'),same(M(r'y=x-1,\quad y=1/e')),('두 접선은 지정 점을 지나며 각각의 기울기가 도함수값1과0이다.','Both lines pass through the specified points with derivative slopes1 and0.'))
plots(b,44,[('6.4.44 Curve and two tangents',.2,5,-1.5,1,[('lnx/x',lambda q:math.log(q)/q),('x-1',lambda q:q-1),('1/e',lambda q:1/math.e)])])
add(45,('f(x)=cx+ln(cosx)이고 f′(π/4)=6일 때c를 구하라.','Find c if f(x)=cx+ln(cosx) andf′(π/4)=6.'),fs(r'f\prime=c-\tan x',r'c-1=6\Rightarrow c=7'),same(M('c=7')),('cos(π/4)>0이므로 점에서 원래 로그가 정의되며c=7을 도함수 조건에 대입했다.','cos(π/4)>0 ensures the original logarithm is defined,andc=7 satisfies the derivative condition.'))
add(46,('f(x)=log_b(3x²-2)이고f′(1)=3일 때b를 구하라.','Find b if f(x)=log_b(3x²-2) andf′(1)=3.'),fs(r'f\prime(x)=\frac{6x}{(3x^2-2)\ln b}',r'6/\ln b=3\Rightarrow\ln b=2\Rightarrow b=e^2'),same(M(r'b=e^2')),('구한 밑은 양수이고1이 아니며 x=1의 로그 입력은1이다.','The base is positive and unequal to1,and the logarithm argument atx=1 is1.'))
LD={47:((x*x+2)**2*(x**4+4)**4,2*s.log(x*x+2)+4*s.log(x**4+4),r'\mathbb R'),48:(s.exp(-x)*s.cos(x)**2/(x*x+x+1),-x+2*s.log(s.Abs(s.cos(x)))-s.log(x*x+x+1),r'\mathbb R'),49:(s.sqrt((x-1)/(x**4+1)),(s.log(x-1)-s.log(x**4+1))/2,r'[1,\infty)'),50:(s.sqrt(x)*s.exp(x*x-x)*(x+1)**R(2,3),s.log(x)/2+x*x-x+R(2,3)*s.log(x+1),r'(0,\infty)'),51:(x**x,x*s.log(x),r'(0,\infty)'),52:(x**(1/x),s.log(x)/x,r'(0,\infty)'),53:(x**s.sin(x),s.sin(x)*s.log(x),r'(0,\infty)'),54:((s.sqrt(x))**x,x*s.log(x)/2,r'(0,\infty)'),55:(s.cos(x)**x,x*s.log(s.cos(x)),r'\cos x>0'),56:(s.sin(x)**s.log(x),s.log(x)*s.log(s.sin(x)),r'x>0,\ \sin x>0'),57:(x**s.log(x),s.log(x)**2,r'(0,\infty)'),58:(s.log(x)**s.cos(x),s.cos(x)*s.log(s.log(x)),r'x>1')}
for n,(f,lf,dom)in LD.items():
 dl=-1-2*s.tan(x)-(2*x+1)/(x*x+x+1)if n==48 else s.diff(lf,x);df=s.diff(f,x)if n==48 else f*dl
 ff=s.lambdify(x,f,'mpmath');dd=s.lambdify(x,df,'mpmath')
 for q in([mp.mpf('1.2'),mp.mpf('1.3')]if n in[49,58]else[mp.mpf('.3'),mp.mpf('.5')]):assert abs(mp.diff(ff,q)-dd(q))<1e-15,(n,q)
 add(n,(M('y='+s.latex(f))+'로그미분법으로 미분하라.',M('y='+s.latex(f))+'Differentiate using logarithmic differentiation.'),fs(r'\ln y='+s.latex(lf),r'y\prime/y='+s.latex(dl),r'y\prime='+s.latex(df))+[('로그를 취하는 구간에서는 원래 밑이 양수여야 한다.48에서는cosx=0인 점의 도함수도 원래 곱·몫식으로 연장하여0이다.49의x=1에는 유한 도함수가 없다.','On logarithmic-differentiation intervals,the original base must be positive.In48,the derivative extends to0 atcosx=0 using the original product/quotient formula.In49,x=1 has no finite derivative.')],same(M(s.latex(df))),('원래 함수의 수치 미분과 결과를 두 허용 입력에서 독립 대조했다.','Independently compared the result with numerical differentiation of the original function at two admissible inputs.'))
add(59,('y=ln(x²+y²)일 때y′을 구하라.','Find y′ wheny=ln(x²+y²).'),fs(r'y\prime=\frac{2x+2yy\prime}{x^2+y^2}',r'(x^2+y^2-2y)y\prime=2x',r'y\prime=\frac{2x}{x^2+y^2-2y}'),same(M(r'\frac{2x}{x^2+y^2-2y}')),('F=y-ln(x²+y²)에 대해-Fx/Fy를 계산하면 같은 식이며 분모가0이 아닌 정칙점에 적용한다.','ForF=y-ln(x²+y²),-Fx/Fy gives the same expression,applicable at regular points with nonzero denominator.'))
add(60,('x^y=y^x에서양의x,y에 대해y′을 구하라.','Forx^y=y^x with positivex,y,findy′.'),fs(r'y\ln x=x\ln y',r'y\prime\ln x+y/x=\ln y+(x/y)y\prime',r'y\prime=\frac{\ln y-y/x}{\ln x-x/y}'),same(M(r'\frac{\ln y-y/x}{\ln x-x/y}')),('분모가0이 아닌 정칙점에 사용한다.x=y인 가지에서는x≠e일 때1이 되어 항등 가지의 기울기와 같다.','Use at regular points with nonzero denominator.On thex=y branch it equals1 whenx≠e,matching that branch’s slope.'))
add(61,('f(x)=ln(x-1)의n계 도함수 공식을 구하라.','Find a formula for the nth derivative off(x)=ln(x-1).'),fs(r'f\prime=\frac1{x-1},\quad f\prime\prime=-\frac1{(x-1)^2},\quad f^{(3)}=\frac2{(x-1)^3}',r'f^{(n)}(x)=\frac{(-1)^{n-1}(n-1)!}{(x-1)^n},\quad n\ge1,\ x>1'),same(M(r'\frac{(-1)^{n-1}(n-1)!}{(x-1)^n}')),('n=1에서 성립하며 한 번 미분하면 분자에-n을 곱해 n+1 공식으로 바뀐다.','It holds forn=1;one derivative multiplies by-n and gives the n+1 formula.'))
add(62,('x⁸lnx의9계 도함수를 구하라.','Find the ninth derivative ofx⁸lnx.'),fs(r'D^8(x^8\ln x)=8![\ln x+H_8],\quad H_8=1+1/2+\cdots+1/8',r'D^9(x^8\ln x)=8!/x=40320/x'),same(M(r'40320/x,\quad x>0')),('곱의 고계 미분에서8계 도함수의 비로그 항은 상수가 되어9계에서 사라진다. 기호적으로9회 미분한 결과도40320/x이다.','In the higher product derivative,the nonlogarithmic part after eight derivatives is constant and vanishes on the ninth;direct symbolic differentiation also gives40320/x.'))
add(63,('f(x)=lnx/√x의 오목성 구간과 변곡점을 구하라.','Find concavity intervals and inflection points off(x)=lnx/√x.'),fs(r'f\prime=x^{-3/2}(1-\tfrac12\ln x)',r'f\prime\prime=\frac{3\ln x-8}{4x^{5/2}}',r'3\ln x-8=0\Rightarrow x=e^{8/3}'),same(M(r'\text{down: }(0,e^{8/3});\quad\text{up: }(e^{8/3},\infty);\quad\text{inflection: }(e^{8/3},\tfrac83e^{-4/3})')),('정의역x>0에서 분모가 양수이며3lnx-8이 유일한 영점을 지나 증가한다.','Onx>0 the denominator is positive,and3lnx-8 increases through its only zero.'))
add(64,('f(x)=xlnx의 절대 최솟값을 구하라.','Find the absolute minimum off(x)=xlnx.'),fs(r'f\prime=1+\ln x=0\Rightarrow x=e^{-1}',r'f\prime<0\ (0<x<e^{-1}),\quad f\prime>0\ (x>e^{-1})',r'f(e^{-1})=-1/e'),same(M(r'\min f=-1/e\quad(x=1/e)')),('정의역의 왼쪽에서 감소하고 오른쪽에서 증가하므로 유일한 임계점이 전체 최솟값이다.','The function decreases to and increases from its sole critical point,giving the global minimum.'))
print('6.4 authored',len(b.E))
I={75:(x,3/x,2,4,3*s.log(x)),76:(x,1/(5*x+1),0,3,s.log(5*x+1)/5),77:(t,1/(8-3*t),1,2,-s.log(8-3*t)/3),78:(x,(s.sqrt(x)+1/s.sqrt(x))**2,4,9,x*x/2+2*x+s.log(x)),79:(x,(3*x*x+4*x+1)/x,1,3,R(3,2)*x*x+4*x+s.log(x)),80:(t,s.cos(s.log(t))/t,None,None,s.sin(s.log(t))),81:(x,s.log(x)**2/x,None,None,s.log(x)**3/3),82:(z,z*z/(z**3+1),None,None,s.log(s.Abs(z**3+1))/3),83:(x,s.sin(2*x)/(1+s.cos(x)**2),None,None,-s.log(1+s.cos(x)**2)),84:(x,s.exp(x)/(s.exp(x)+1),None,None,s.log(s.exp(x)+1)),85:(t,2**t,0,4,2**t/s.log(2)),86:(x,x*2**(x*x),None,None,2**(x*x)/(2*s.log(2)))}
for n,(v,f,lo,hi,F)in I.items():
 if n!=82:assert s.simplify(s.trigsimp(s.diff(F,v)-f))==0,(n,s.diff(F,v)-f)
 ans=F if lo is None else s.simplify(F.subs(v,hi)-F.subs(v,lo));integ=s.Integral(f,v)if lo is None else s.Integral(f,(v,lo,hi))
 if lo is not None:assert abs(mp.quad(s.lambdify(v,f,'mpmath'),[lo,hi])-float(ans))<1e-10
 add(n,(M(s.latex(integ))+'적분하라.',M(s.latex(integ))+'Evaluate the integral.'),[('로그 미분형 h′/h를 찾거나 간단한 치환·전개로 원시함수를 구한다.','Identify a logarithmic derivative h′/h,or use a simple substitution/expansion to find an antiderivative.')]+fs('F('+s.latex(v)+')='+s.latex(F),s.latex(integ)+'='+s.latex(ans)+('+C'if lo is None else'')),same(M(s.latex(ans)+('+C'if lo is None else''))),('원시함수의 도함수로 피적분함수를 복원했다. 정적분은 독립 수치 적분도 대조했으며 로그 절댓값은 각 연결된 정의구간에서 적용한다.','Differentiation recovers the integrand;definite cases also match independent quadrature.Absolute-value logarithms apply on each connected domain interval.'))
add(87,('∫cotx dx=ln|sinx|+C를(a)미분,(b)치환으로 보여라.','Show∫cotx dx=ln|sinx|+C by(a)differentiation and(b)substitution.'),fs(r'(a)\ \frac{d}{dx}\ln|\sin x|=\frac{\cos x}{\sin x}=\cot x',r'(b)\ u=\sin x,\quad du=\cos x\,dx',r'\int\frac{\cos x}{\sin x}\,dx=\int\frac{du}{u}=\ln|u|+C'),same(M(r'\int\cot x\,dx=\ln|\sin x|+C')),('sinx=0인 점을 제외한 각 구간에서 두 방법 모두 같은 원시함수를 준다.','Both methods give the same antiderivative on each interval excludingsinx=0.'),['a','b'])
add(88,('y=lnx/x와y=(lnx)²/x 사이에 둘러싸인 영역을 그리고 넓이를 구하라.','Sketch the region enclosed byy=lnx/x andy=(lnx)²/x and find its area.'),fs(r'\ln x=(\ln x)^2\Rightarrow x=1,e',r'A=\int_1^e\frac{\ln x-(\ln x)^2}{x}\,dx=\int_0^1(u-u^2)\,du',r'A=1/2-1/3=1/6'),same(M(r'A=1/6')),('1<x<e에서0<lnx<1이므로 위쪽은lnx/x이다. 치환u=lnx의 양 끝도0,1이다.','On1<x<e,we have0<lnx<1,so lnx/x is upper;u=lnx maps the bounds to0,1.'))
area_svg(b,88,[(1,s.E,s.log(x)/x,s.log(x)**2/x)],x,'6.4.88 Enclosed area');b.save()
for n,st,f,lo,hi in[(89,('0≤x≤1에서y=1/√(x+1) 아래 영역을x축 회전한 부피를 구하라.','Rotate the region under y=1/√(x+1) on0≤x≤1 about the x-axis.Find the volume.'),P/(x+1),0,1),(90,('0≤x≤3에서y=1/(x²+1) 아래 영역을y축 회전한 부피를 구하라.','Rotate the region under y=1/(x²+1) on0≤x≤3 about the y-axis.Find the volume.'),2*P*x/(x*x+1),0,3)]:
 val=s.integrate(f,(x,lo,hi));assert abs(mp.quad(s.lambdify(x,f,'mpmath'),[lo,hi])-float(val))<1e-10
 method=('원판 면적πy²를 적분한다.','Integrate disk areaπy².')if n==89 else('반지름x,높이1/(x²+1)의 원통껍질을 적분한다.','Integrate shells of radiusx and height1/(x²+1).')
 add(n,st,[method]+fs('V='+s.latex(s.Integral(f,(x,lo,hi)))+'='+s.latex(val)),same(M('V='+s.latex(val))),('원판·껍질의 치수를 원래 영역에서 확인하고 독립 수치 적분과 비교했다.','Checked disk/shell dimensions against the region and compared independent numerical quadrature.'))
add(91,('보일 법칙PV=C인 기체가 초기600cm³,150kPa에서1000cm³로 등온 팽창한다. ∫P dV로 기체가 한 일을 구하라.','A gas obeyingPV=C expands isothermally from600cm³ at150kPa to1000cm³.Compute the work∫P dV.'),fs(r'C=P_1V_1=(150000)(600\times10^{-6})=90\text{ J}',r'W=C\int_{V_1}^{V_2}\frac{dV}{V}=90\ln(1000/600)=90\ln(5/3)\approx45.9743\text{ J}'),same(M(r'90\ln(5/3)\approx45.974\text{ J}')),('Pa·m³가J임을 적용하고 부피 비는 같은 단위끼리 나누어 무차원 로그 입력으로 사용했다.','UsedPa·m³=J and a dimensionless volume ratio formed from matching units.'))
add(92,('f″(x)=x⁻²,x>0,f(1)=f(2)=0일 때f를 구하라.','Find f iff″(x)=x⁻²,x>0,andf(1)=f(2)=0.'),fs(r'f\prime=-1/x+C_1,\quad f=-\ln x+C_1x+C_2',r'C_1+C_2=0,\quad-\ln2+2C_1+C_2=0',r'C_1=\ln2,\quad C_2=-\ln2'),same(M(r'f(x)=(x-1)\ln2-\ln x')),('두 번 미분하면x⁻²가 되고x=1,2에서 함수값이 각각0이다.','The second derivative isx⁻² and both boundary values at1,2 are0.'))
for n,f,q,target in[(93,2*x+s.log(x),1,2),(94,s.exp(x)+s.log(x),1,s.E)]:
 val=1/s.diff(f,x).subs(x,q);assert s.simplify(f.subs(x,q)-target)==0
 add(n,(M('f(x)='+s.latex(f))+'역함수g의g′('+s.latex(target)+')를 구하라.',M('f(x)='+s.latex(f))+'Find g′('+s.latex(target)+') for inverseg.'),fs('f(1)='+s.latex(target),r'f\prime(x)='+s.latex(s.diff(f,x)),r'g\prime('+s.latex(target)+')=1/f\prime(1)='+s.latex(val)),same(M(s.latex(val))),('정의역x>0에서f′>0이므로 역함수가 존재하고 원상1의 도함수는0이 아니다.','Onx>0,f′>0 guarantees an inverse,and its derivative at preimage1 is nonzero.'))
add(95,('직선y=mx와곡선y=x/(x²+1)가 유한한 영역을 둘러싸는m 범위와 넓이를 구하라.','Find the values ofm for whichy=mx andy=x/(x²+1) enclose bounded regions,and find their area.'),fs(r'x=0\quad\text{or}\quad m=1/(x^2+1)',r'0<m<1,\quad a=\sqrt{1/m-1},\quad x=0,\pm a',r'A_{right}=\int_0^a\left(\frac{x}{1+x^2}-mx\right)dx=\tfrac12[-\ln m-(1-m)]',r'A_{total}=m-1-\ln m'),same(M(r'0<m<1;\quad A_{total}=m-1-\ln m;\quad A_{each}=\tfrac12(m-1-\ln m)')),('양쪽 영역은 원점 대칭이며0<m<1에서lnm<m-1이므로 넓이가 양수이다.m=1에서는 영역이 퇴화한다.','The two lobes are centrally symmetric,andlnm<m-1 for0<m<1 gives positive area.The region degenerates atm=1.'))
area_svg(b,95,[(-1,0,x/2,x/(1+x*x)),(0,1,x/(1+x*x),x/2)],x,'6.4.95 Two lobes, example m=1/2');b.save()
add(96,('고정된x>0에 대해limₙ→∞(1+x/n)^n=eˣ임을 보여라.','Showlimₙ→∞(1+x/n)^n=eˣ for fixedx>0.'),fs(r'u=x/n\to0^+,\quad(1+x/n)^n=[(1+u)^{1/u}]^x',r'\lim_{u\to0^+}(1+u)^{1/u}=e\Rightarrow\lim_{n\to\infty}(1+x/n)^n=e^x'),same(M(r'e^x')),('x는 고정 상수이며 양의 밑에서t↦tˣ의 연속성으로 극한을 거듭제곱 밖으로 옮겼다.','x is fixed;continuity oft↦tˣ for positive bases allows passage of the limit through the power.'))
add(97,('도함수 정의로limₓ→₀ln(1+x)/x=1을 증명하라.','Use the derivative definition to provelimₓ→₀ln(1+x)/x=1.'),fs(r'F(t)=\ln t,\quad F(1)=0',r'\lim_{x\to0}\frac{\ln(1+x)}x=\lim_{x\to0}\frac{F(1+x)-F(1)}x=F\prime(1)=1'),same(M('1')),('차분몫이t=1에서의 도함수 정의이며1+x>0인 양쪽 근방에서 정의된다.','The quotient is the derivative definition att=1 and is defined in a two-sided neighborhood with1+x>0.'))
add(98,('표적 획득 난이도I=log₂(2D/W),D,W>0이다.(a)W 고정 시D에 따른 변화율과 그 증감,(b)D 고정 시W 변화율·부호·증감,(c)직관과의 관계를 설명하라.','Target-acquisition difficulty isI=log₂(2D/W),D,W>0.(a)WithW fixed,find the rate inD and its monotonicity.(b)WithD fixed,find the rate inW,its sign and monotonicity.(c)Explain the intuition.'),fs(r'(a)\ \frac{dI}{dD}=\frac1{D\ln2}>0,\quad\frac{d^2I}{dD^2}=-\frac1{D^2\ln2}<0',r'(b)\ \frac{dI}{dW}=-\frac1{W\ln2}<0,\quad\frac{d^2I}{dW^2}=\frac1{W^2\ln2}>0')+[('멀어질수록 어려워지지만 추가 거리의 효과는 줄어든다. 넓어질수록 쉬워지고 음의 변화율은0을 향해 증가하여 감소 효과의 크기는 작아진다.','More distant targets are harder,but each extra unit of distance has less effect.Wider targets are easier;the negative rate increases toward0,so the magnitude of its effect shrinks.')],('(a)1/(Dln2),감소.(b)-1/(Wln2),음수이고증가.(c)먼 표적은 더 어렵고 큰 표적은 더 쉽다.','(a)1/(Dln2),decreasing.(b)-1/(Wln2),negative and increasing.(c)More distant targets are harder;larger targets are easier.'),('부호 있는 변화율의 증가와 절댓값의 감소를 구별하고 각각을2계 도함수로 확인했다.','Distinguished increase of the signed rate from decrease of its magnitude,and checked each by second derivatives.'),list('abc'))
add(99,('y=bˣ,b>0,b≠1의(a,b^a)에서 접선의x절편을c라 하자.|a-c|가a와 무관함을 보여라.','For y=bˣ,b>0,b≠1,letc be the x-intercept of the tangent at(a,b^a).Show|a-c| is independent ofa.'),fs(r'y-b^a=b^a\ln b(x-a)',r'0=b^a[1+\ln b(c-a)]\Rightarrow c=a-1/\ln b',r'|a-c|=1/|\ln b|'),same(M(r'|a-c|=1/|\ln b|')),('밑이1보다 작은 경우lnb가 음수이므로 실제 거리에 절댓값을 사용했다.','For bases below1,lnb is negative,so the geometric distance uses its absolute value.'))
add(100,('y=bˣ,b>0,b≠1에서 원점을 지나는 접선의 접점이 유일하고 그y좌표는e임을 보여라.','Show that y=bˣ,b>0,b≠1 has exactly one tangent passing through the origin,and its contact point has y-coordinatee.'),fs(r'0-b^{x_0}=b^{x_0}\ln b(0-x_0)',r'x_0\ln b=1\Rightarrow x_0=1/\ln b',r'y_0=b^{1/\ln b}=e'),same(M(r'(x_0,y_0)=(1/\ln b,e)')),('lnb≠0이므로 선형 조건이 유일한x0를 주며b=e^(lnb)로 바꿔y0=e를 확인했다.','lnb≠0 makes the linear condition yield a unique x0,andb=e^(lnb) givesy0=e.'))
print('6.4 authored',len(b.E))
add(65,('y=ln(sinx)의 정의역·절편·주기·점근선·증감·극값·오목성을 분석하고 그려라.','Analyze and graphy=ln(sinx):domain,intercepts,period,asymptotes,monotonicity,extrema,and concavity.'),fs(r'D=\bigcup_{k\in\mathbb Z}(2k\pi,(2k+1)\pi)',r'f\prime=\cot x,\quad f\prime\prime=-\csc^2x<0')+[('각 정의구간의 중점π/2+2kπ까지 증가,이후 감소하며 최댓값0을 가진다. 중점은x절편이다. 정의구간 양 끝에서-∞로 가며 수직점근선은x=kπ이다.','On each domain interval the curve increases toπ/2+2kπ,then decreases,with maximum0 there,also an x-intercept.It tends to-∞ at both ends;vertical asymptotes arex=kπ.')],('주기2π. 각 구간에서 아래로 오목,변곡점 없음. 극대0은x=π/2+2kπ. y절편 없음.','Period2π.Concave down on every domain interval,no inflections.Local maximum0 atx=π/2+2kπ.No y-intercept.'),('sinx>0인 구간만 포함하고 f″가 항상 음수임을 확인했다.','Included only intervals withsinx>0 and verifiedf″ is negative throughout.'))
plots(b,65,[('6.4.65 Positive-sine intervals',-2*math.pi,4*math.pi,-4,.3,[('ln(sinx)',lambda q:math.log(math.sin(q)))])])
add(66,('y=ln(tan²x)의 정의역·절편·주기·점근선·증감·극값·오목성·변곡점을 분석하고 그려라.','Analyze and graphy=ln(tan²x):domain,intercepts,period,asymptotes,monotonicity,extrema,concavity,and inflections.'),fs(r'D=\mathbb R\setminus\{k\pi/2:k\in\mathbb Z\},\quad f\prime=4\csc2x,\quad f\prime\prime=-\frac{8\cos2x}{\sin^22x}')+[('각 주기(kπ,(k+1)π)에서 왼쪽 반구간은 증가,오른쪽 반구간은 감소한다. kπ에서는-∞,kπ+π/2에서는+∞로 가며 두 종류 모두 수직점근선이다.','In each period(kπ,(k+1)π),the left half increases and the right half decreases.At kπ the limit is-∞;at kπ+π/2 it is+∞;both are vertical asymptotes.'),('cos2x>0이면 아래로 오목,cos2x<0이면 위로 오목이다. 따라서 한 주기에서 아래로 오목한 부분은(kπ,kπ+π/4),(kπ+3π/4,(k+1)π)이고 나머지 두 정의구간은 위로 오목하다.','Concavity is down wherecos2x>0 and up wherecos2x<0.Thus within a period it is down on(kπ,kπ+π/4) and(kπ+3π/4,(k+1)π),and up on the remaining two domain intervals.')]+fs(r'\text{inflections and zeros: }(\pi/4+k\pi/2,0)'),('주기π,변곡점이자 영점(π/4+kπ/2,0),극값 없음,y절편 없음.','Periodπ;inflections and zeros(π/4+kπ/2,0);no extrema or y-intercept.'),('2계 도함수의 분모가 양수이므로-cos2x 부호로 오목성을 독립 확인하고 제외된 점에는 극값을 부여하지 않았다.','The second-derivative denominator is positive,so its sign is-cos2x;excluded points are not extrema.'))
plots(b,66,[('6.4.66 One period, left branch',.005,math.pi/2-.005,-8,8,[('ln(tan^2x)',lambda q:math.log(math.tan(q)**2))]),('6.4.66 One period, right branch',math.pi/2+.005,math.pi-.005,-8,8,[('ln(tan^2x)',lambda q:math.log(math.tan(q)**2))])])
for n,f,st,ans,window in[(67,s.log(1+x*x),('y=ln(1+x²)를 곡선 분석 기준으로 조사하고 그려라.','Analyze and graphy=ln(1+x²) using curve-sketching criteria.'),('정의역ℝ,원점이 유일한 절편,우함수,점근선 없음. 감소(-∞,0),증가(0,∞),최솟값0. 위로 오목(-1,1),아래로 오목(-∞,-1),(1,∞). 변곡점(±1,ln2).','Domainℝ,only intercept(0,0),even,no asymptotes.Decreasing(-∞,0),increasing(0,∞),minimum0.Concave up(-1,1),down(-∞,-1),(1,∞).Inflections(±1,ln2).'),(-4,4,0,3)),(68,s.log(1+x**3),('y=ln(1+x³)를 곡선 분석 기준으로 조사하고 그려라.','Analyze and graphy=ln(1+x³) using curve-sketching criteria.'),('정의역(-1,∞),유일한 절편(0,0),수직점근선x=-1. 전체에서 증가하며극값 없음. 아래로 오목(-1,0),(∛2,∞),위로 오목(0,∛2). 변곡점(0,0),(∛2,ln3).','Domain(-1,∞),only intercept(0,0),vertical asymptote x=-1.Increasing throughout,no extrema.Concave down(-1,0),(∛2,∞),up(0,∛2).Inflections(0,0),(∛2,ln3).'),(-.99,4,-4,5))]:
 add(n,st,fs(r'f\prime='+s.latex(s.factor(s.diff(f,x))),r'f\prime\prime='+s.latex(s.factor(s.diff(f,x,2))))+[('정의역 경계와 도함수 영점에서 구간을 나누고 부호표를 만든다.','Split intervals at domain boundaries and derivative zeros,and form sign charts.')],ans,('변곡 후보 양쪽의2계 도함수 부호 변화를 확인했다.68의x=0은 증가 방향이 바뀌지 않아 극값이 아니다.','Checked second-derivative sign changes across inflection candidates.In68,x=0 does not reverse monotonicity and is not an extremum.'))
 plots(b,n,[(f'6.4.{n} Curve analysis',*window,[('f(x)',s.lambdify(x,f,'math'))])])
def roots_scan(fn,lo,hi,count=1800):
 roots=[];prev=lo;pv=fn(prev)
 for i in range(1,count+1):
  q=lo+(hi-lo)*i/count;val=fn(q)
  if val*pv<0:
   root=float(mp.findroot(fn,(prev,q)))
   if not roots or abs(root-roots[-1])>1e-6:roots.append(root)
  prev,pv=q,val
 return roots
f69=lambda q:mp.log(2*q+q*mp.sin(q));d69=lambda q:1/q+mp.cos(q)/(2+mp.sin(q));dd69=lambda q:-1/q**2-(1+2*mp.sin(q))/(2+mp.sin(q))**2
r69=roots_scan(d69,.001,15);i69=roots_scan(dd69,.001,15);assert len(r69)==5 and len(i69)==4
add(69,('f(x)=ln(2x+xsinx)의f′,f″를 CAS로 구하고0<x≤15에서 그래프로 증가구간과 변곡점을 추정하라.','Use a CAS to findf′ andf″ forf(x)=ln(2x+xsinx),then graph to estimate increasing intervals and inflections on0<x≤15.'),fs(r'f\prime=\frac1x+\frac{\cos x}{2+\sin x}',r'f\prime\prime=-\frac1{x^2}-\frac{1+2\sin x}{(2+\sin x)^2}')+[('f′의 영점: '+', '.join(f'{q:.6f}'for q in r69),'Zeros off′: '+', '.join(f'{q:.6f}'for q in r69)),('f″의 영점: '+', '.join(f'{q:.6f}'for q in i69),'Zeros off″: '+', '.join(f'{q:.6f}'for q in i69))],same(M(r'\text{increasing: }(0,'+f'{r69[0]:.3f}'+r'),('+f'{r69[1]:.3f},{r69[2]:.3f}'+r'),('+f'{r69[3]:.3f},{r69[4]:.3f}'+r');\quad\text{inflections: }'+','.join(f'({q:.3f},{float(f69(q)):.3f})'for q in i69))),('도함수 영점 사이의 부호와2계 도함수 각 근의 부호 변화를 확인했다. 전체0~15 구간을 촘촘히 탐색한 뒤 각 근을 고정밀도로 재계산했다.','Checked derivative signs between zeros and second-derivative sign changes;densely scanned the entire0–15interval,then refined every root at high precision.'))
assert s.simplify(s.diff(s.log(2*x+x*s.sin(x)),x)-(1/x+s.cos(x)/(2+s.sin(x))))==0
assert s.simplify(s.diff(1/x+s.cos(x)/(2+s.sin(x)),x)-(-1/x**2-(1+2*s.sin(x))/(2+s.sin(x))**2))==0
plots(b,69,[('6.4.69 Function',.1,15,-2,4,[('f',lambda q:float(f69(q)))]),('6.4.69 First derivative',.1,15,-1.5,2,[('f prime',lambda q:float(d69(q)))]),('6.4.69 Second derivative',.1,15,-2,2,[('f second derivative',lambda q:float(dd69(q)))])])
add(70,('함수족f(x)=ln(x²+c)의c에 따른 변곡점·점근선 변화를 분석하고 여러c를 그려라.','Investigate how inflections and asymptotes of f(x)=ln(x²+c) change withc,and graph several members.'),fs(r'f\prime=\frac{2x}{x^2+c},\quad f\prime\prime=\frac{2(c-x^2)}{(x^2+c)^2}')+[('c>0이면 정의역ℝ,수직점근선 없음,변곡점(±√c,ln2c)이다.c가 커질수록 두 점은 바깥쪽·위쪽으로 간다.','Forc>0,the domain isℝ,there are no vertical asymptotes,and inflections are(±√c,ln2c);they move outward and upward asc increases.'),('c=0이면x=0이 수직점근선이고 변곡점이 없다.c<0이면정의역|x|>√(-c),수직점근선x=±√(-c),변곡점 없음. 두 경우 모두 각 정의구간에서 아래로 오목하다.','Forc=0,x=0 is a vertical asymptote and there are no inflections.Forc<0,the domain is|x|>√(-c),asymptotes arex=±√(-c),and there are no inflections.Both cases are concave down on their domain intervals.')],('(c>0)변곡점2개,수직점근선0개.(c=0)변곡점0개,점근선1개.(c<0)변곡점0개,점근선2개.','Forc>0:two inflections,no vertical asymptotes.Forc=0:no inflections,one asymptote.Forc<0:no inflections,two asymptotes.'),('로그의 양수 조건과 f″의 분자 c-x²를 함께 적용하여 정의역 밖의 형식적 근을 제외했다.','Combined the positive logarithm-argument condition with numeratorc-x² to exclude formal roots outside the domain.'))
plots(b,70,[(f'6.4.70 c={cc}',-4,4,-4,4,[(f'ln(x^2+({cc}))',lambda q,cc=cc:math.log(q*q+cc))])for cc in[-1,0,1,4]])
for n,f,guesses,window,curves in[(71,(x-4)**2-s.log(x),[3.,5.3],(.2,7,-1,10),[('(x-4)^2',lambda q:(q-4)**2),('lnx',math.log)]),(72,s.log(4-x*x)-x,[-2+0.05,1.1],(-1.99,1.99,-4,2),[('ln(4-x^2)',lambda q:math.log(4-q*q)),('x',lambda q:q)])]:
 ff=s.lambdify(x,f,'mpmath');df=s.lambdify(x,s.diff(f,x),'mpmath');histories=[];roots=[]
 for start in guesses:
  q=mp.mpf(str(start));hist=[float(q)]
  for k in range(10):q=q-ff(q)/df(q);hist.append(float(q))
  assert abs(ff(q))<mp.mpf('1e-25');roots.append(float(q));histories.append(hist)
 steps=fs(r'x_{n+1}=x_n-\frac{F(x_n)}{F\prime(x_n)}',r'F(x)='+s.latex(f),r'F\prime(x)='+s.latex(s.diff(f,x)))
 for hist in histories:steps.append(('뉴턴 반복: '+', '.join(f'{q:.8f}'for q in hist[:5]),'Newton iterates: '+', '.join(f'{q:.8f}'for q in hist[:5])))
 add(n,(M('F(x)='+s.latex(f)+'=0')+'그래프로 근을 소수1자리까지 추정한 뒤 뉴턴법으로 소수6자리까지 구하라.',M('F(x)='+s.latex(f)+'=0')+'Estimate roots graphically to one decimal place,then refine by Newton’s method to six decimal places.'),steps,same(M(r'x\approx'+','.join(f'{q:.6f}'for q in roots))),('각 최종근의 잔차는10⁻²⁵보다 작다.71은F″>0,72는F″<0인 형태로 각각 실근이 많아야2개임도 확인했다.','Every final residual is below10⁻²⁵;the strict convexity in71 and strict concavity in72 also show at most two real roots.'))
 plots(b,n,[(f'6.4.{n} Root intersections',*window,curves)])
l73=float(mp.findroot(lambda q:q-1-mp.log(q)-.1,(.6,.7)));h73=float(mp.findroot(lambda q:q-1-mp.log(q)-.1,(1.4,1.6)))
add(73,('(a)x=1 근처에서lnx의 선형근사를 구하고,(b)그래프로 나타내며,(c)오차0.1 이내인x를 구하라.','(a)Find the linear approximation tolnx near1,(b)graph it,and(c)find x where the error is at most0.1.'),fs(r'L(x)=\ln1+(x-1)/1=x-1',r'E(x)=L(x)-\ln x=x-1-\ln x\ge0',r'E\prime(x)=1-1/x')+[('오차는1까지 감소하고 그 뒤 증가하므로 E(x)=0.1의 두 근 사이가 답이다.','The error decreases to1 then increases,so the answer lies between the two roots ofE(x)=0.1.')],same(M(r'L(x)=x-1;\quad'+f'{l73:.6f}'+r'\le x\le'+f'{h73:.6f}')),('lnx의 아래로 오목함으로 접선이 위에 있음을 확인하고 두 경계의 실제 오차를0.1과 대조했다.','Concavity oflnx places its tangent above the curve;checked actual error0.1 at both endpoints.'),list('abc'))
plots(b,73,[('6.4.73 Logarithm and tangent',.3,2,-1.3,1,[('lnx',math.log),('L=x-1',lambda q:q-1)]),('6.4.73 Error',.3,2,0,.6,[('x-1-lnx',lambda q:q-1-math.log(q)),('0.1',lambda q:.1)])])
years=list(range(1790,1861,10));counts=[3929000,5308000,7240000,9639000,12861000,17063000,23192000,31443000];times=[q-1790 for q in years];mean=sum(times)/8;lm=sum(math.log(q)for q in counts)/8;k74=sum((q-mean)*(math.log(N)-lm)for q,N in zip(times,counts))/sum((q-mean)**2 for q in times);a74=math.exp(lm-k74*mean);sec1800=(counts[2]-counts[0])/20;sec1850=(counts[7]-counts[5])/20;rate1800=k74*a74*math.exp(k74*10);rate1850=k74*a74*math.exp(k74*60);pred=a74*math.exp(k74*80);rel=max(abs(a74*math.exp(k74*q)-N)/N for q,N in zip(times,counts))
add(74,('1790~1860년10년 간격 인구는3929000,5308000,7240000,9639000,12861000,17063000,23192000,31443000이다.(a)지수모형과그래프·적합도,(b)인접 할선 평균으로1800·1850년 성장률,(c)모형의 성장률과 비교,(d)1870년 예측을 실제38558000과 비교·설명하라.','At ten-year intervals1790–1860,the populations are3929000,5308000,7240000,9639000,12861000,17063000,23192000,31443000.(a)Fit and graph an exponential and assess fit.(b)Estimate growth rates in1800 and1850 by averaging neighboring secant slopes.(c)Compare model rates.(d)Predict1870 and compare with actual38558000.'),[('t=연도-1790으로 두고 lnP=lnA+kt에 최소제곱 직선을 맞춘다.','Set t=year-1790 and fit the least-squares line lnP=lnA+kt.')]+fs(r'P(t)\approx'+f'{a74:.4f}'+r'e^{'+f'{k74:.9f}'+r't}',r'P\prime(t)=kP(t)',r'\text{secants: }\frac{7240000-3929000}{20}='+f'{sec1800:.0f}'+r',\quad\frac{31443000-17063000}{20}='+f'{sec1850:.0f}',r'P\prime(10)\approx'+f'{rate1800:.0f}'+r',\quad P\prime(60)\approx'+f'{rate1850:.0f}',r'P(80)\approx'+f'{pred:.0f}')+[('표의 각 시각에서 모형 상대오차는 최대약'+f'{100*rel:.2f}'+'%이다.1870년은 과대예측한다. 일정 비율 성장 가정이1860년대에 유지되지 않았음을 보여주며 남북전쟁 같은 시기적 교란이 가능한 설명이다. 자료만으로 원인을 분리할 수는 없다.','At the tabulated times,the largest relative model error is about'+f'{100*rel:.2f}'+'%.It overpredicts1870,showing that constant relative growth did not persist through the1860s.Period disruptions such as the Civil War are a possible explanation;the data alone cannot isolate causes.')],same(M(r'(b)\ 165550,719000\text{ persons/year};\quad(c)\ '+f'{rate1800:.0f},{rate1850:.0f}'+r';\quad(d)\ '+f'{pred:.0f}'+r'\text{ persons}')),('양쪽 할선 평균이 중앙차분과 같음을 확인하고 로그 회귀의 두 정규방정식과P′=kP를 독립 대조했다.','Checked that averaging neighboring secants equals the central difference,and verified the two log-regression normal equations andP′=kP.'),list('abcd'))
plots(b,74,[('6.4.74 Population data and exponential model',0,85,0,4.5e7,[('P(t), t=year-1790',lambda q:a74*math.exp(k74*q))],list(zip(times,counts))+[(80,38558000)])])
print('6.4 COMPLETE',len(b.E))

b.E[71]['steps']['ko'].insert(0,'그래프의 소수1자리 근 추정은3.0,5.3이다.')
b.E[71]['steps']['en'].insert(0,'Graph estimates to one decimal place are3.0 and5.3.')
b.E[72]['steps']['ko'].insert(0,'그래프의 소수1자리 추정은-2.0,1.1이다. -2는 로그 정의역 경계라 뉴턴법을 시작할 수 없어 안쪽의-1.95로 조정한다.')
b.E[72]['steps']['en'].insert(0,'One-decimal graph estimates are-2.0 and1.1. Because-2 is a logarithmic domain boundary,adjust the Newton starting value inward to-1.95.')
b.E[91]['steps']['ko'].append('부록은45,974J라고 쓰지만 주어진kPa·cm³ 단위에서1000배 크다. 1kPa·cm³=0.001J이므로 위의45.974J를 사용한다.')
b.E[91]['steps']['en'].append('The appendix prints45,974J,which is1000times too large for the statedkPa andcm³ units. Since1kPa·cm³=0.001J,the consistent result is45.974J.')
b.save()
