from calc1_inverse_helpers import *
from calc1_plot_helpers import plots
x,t,y,v,u,th=s.symbols('x t y v u theta',real=True);R=s.Rational;b=CalcBook('6.7',[501,502,503])
def add(n,st,steps,ans,ck,parts=[]):
 b.add(n,501 if n<=51 else 502 if n<=68 else 503,('쌍곡함수','Hyperbolic functions'),st,steps,ans,parts=parts);b.verify(n,*ck);b.save()
def mathadd(n,eq,steps,ans,ck=('지수함수 정의에 대입하여 양변을 대조했다.','Substituted exponential definitions to check both sides.'),parts=[]):add(n,(M(eq)+'계산하거나 증명하라.',M(eq)+'Evaluate or prove.'),fs(*steps),same(M(ans)),ck,parts)
vals={1:[s.sinh(0),s.cosh(0)],2:[s.tanh(0),s.tanh(1)],3:[s.cosh(s.log(5)),s.cosh(5)],4:[s.sinh(4),s.sinh(s.log(4))],5:[s.sech(0),s.acosh(1)],6:[s.sinh(1),s.asinh(1)]}
exprs={1:r'(a)\ \sinh0;\quad(b)\ \cosh0',2:r'(a)\ \tanh0;\quad(b)\ \tanh1',3:r'(a)\ \cosh(\ln5);\quad(b)\ \cosh5',4:r'(a)\ \sinh4;\quad(b)\ \sinh(\ln4)',5:r'(a)\ \operatorname{sech}0;\quad(b)\ \operatorname{arcosh}1',6:r'(a)\ \sinh1;\quad(b)\ \operatorname{arsinh}1'}
for n,vals1 in vals.items():
 ans=r';\quad'.join(fr'({chr(97+i)})\ '+tex(q.rewrite(s.exp))+r'\approx'+str(round(float(q),7))for i,q in enumerate(vals1))
 mathadd(n,exprs[n],[r'\sinh z=(e^z-e^{-z})/2,\quad\cosh z=(e^z+e^{-z})/2',r'\tanh z=\sinh z/\cosh z,\quad\operatorname{arsinh}z=\ln(z+\sqrt{1+z^2})',ans],ans,parts=['a','b'])
for n,eq,ss,ans in[(7,r'8\sinh x+5\cosh x',[r'4(e^x-e^{-x})+\tfrac52(e^x+e^{-x})'],r'\tfrac{13}2e^x-\tfrac32e^{-x}'),(8,r'2e^{2x}+3e^{-2x}',[r'e^{2x}=\cosh2x+\sinh2x,\quad e^{-2x}=\cosh2x-\sinh2x'],r'5\cosh2x-\sinh2x'),(9,r'\sinh(\ln x)',[r'x>0,\quad(e^{\ln x}-e^{-\ln x})/2=(x-x^{-1})/2'],r'(x^2-1)/(2x)'),(10,r'\cosh(4\ln x)',[r'x>0,\quad(e^{4\ln x}+e^{-4\ln x})/2=(x^4+x^{-4})/2'],r'(x^8+1)/(2x^4)')]:mathadd(n,eq,ss+[eq+'='+ans],ans)
ident={11:(r'\sinh(-x)=-\sinh x',[r'\sinh(-x)=(e^{-x}-e^x)/2',r'=-(e^x-e^{-x})/2']),12:(r'\cosh(-x)=\cosh x',[r'\cosh(-x)=(e^{-x}+e^x)/2',r'=(e^x+e^{-x})/2']),13:(r'\cosh x+\sinh x=e^x',[r'[(e^x+e^{-x})+(e^x-e^{-x})]/2',r'=2e^x/2=e^x']),14:(r'\cosh x-\sinh x=e^{-x}',[r'[(e^x+e^{-x})-(e^x-e^{-x})]/2',r'=2e^{-x}/2=e^{-x}']),15:(r'\sinh(x+y)=\sinh x\cosh y+\cosh x\sinh y',[r'4\mathrm{RHS}=(e^x-e^{-x})(e^y+e^{-y})+(e^x+e^{-x})(e^y-e^{-y})',r'\mathrm{RHS}=(e^{x+y}-e^{-(x+y)})/2']),16:(r'\cosh(x+y)=\cosh x\cosh y+\sinh x\sinh y',[r'4\mathrm{RHS}=(e^x+e^{-x})(e^y+e^{-y})+(e^x-e^{-x})(e^y-e^{-y})',r'\mathrm{RHS}=(e^{x+y}+e^{-(x+y)})/2']),17:(r'\coth^2x-1=\operatorname{csch}^2x',[r'\coth^2x-1=(\cosh^2x-\sinh^2x)/\sinh^2x',r'=1/\sinh^2x,\quad x\ne0']),18:(r'\tanh(x+y)=\frac{\tanh x+\tanh y}{1+\tanh x\tanh y}',[r'\tanh(x+y)=\frac{\sinh x\cosh y+\cosh x\sinh y}{\cosh x\cosh y+\sinh x\sinh y}',r'\cosh x\cosh y>0:\ \text{divide numerator and denominator}']),19:(r'\sinh2x=2\sinh x\cosh x',[r'\sinh(x+x)=\sinh x\cosh x+\cosh x\sinh x',r'=2\sinh x\cosh x']),20:(r'\cosh2x=\cosh^2x+\sinh^2x',[r'\cosh(x+x)=\cosh x\cosh x+\sinh x\sinh x',r'=\cosh^2x+\sinh^2x']),21:(r'\tanh(\ln x)=\frac{x^2-1}{x^2+1}',[r'x>0,\quad\tanh\ln x=(x-x^{-1})/(x+x^{-1})',r'=(x^2-1)/(x^2+1)']),22:(r'\frac{1+\tanh x}{1-\tanh x}=e^{2x}',[r'\frac{1+\tanh x}{1-\tanh x}=\frac{\cosh x+\sinh x}{\cosh x-\sinh x}',r'=e^x/e^{-x}=e^{2x}']),23:(r'(\cosh x+\sinh x)^n=\cosh(nx)+\sinh(nx)',[r'(\cosh x+\sinh x)^n=(e^x)^n=e^{nx}',r'\cosh(nx)+\sinh(nx)=e^{nx},\quad n\in\mathbb R'])}
for n,(eq,ss)in ident.items():mathadd(n,eq,ss,eq)
mathadd(24,r'\tanh x=12/13',[r'\operatorname{sech}^2x=1-144/169=25/169,\quad\cosh x>0',r'\cosh x=13/5,\quad\sinh x=\tanh x\cosh x=12/5'],r'\sinh x=12/5,\ \cosh x=13/5,\ \operatorname{sech}x=5/13,\ \operatorname{csch}x=5/12,\ \coth x=13/12')
mathadd(25,r'\cosh x=5/3,\quad x>0',[r'\sinh^2x=25/9-1=16/9,\quad\sinh x>0',r'\sinh x=4/3,\quad\tanh x=(4/3)/(5/3)'],r'\sinh x=4/3,\ \tanh x=4/5,\ \operatorname{sech}x=3/5,\ \operatorname{csch}x=3/4,\ \coth x=5/4')
add(26,('(a) csch, sech, coth의 그래프를 역수 관계로 그리고 (b) 수치 그래프로 확인하라.','(a) Sketch csch, sech and coth from reciprocal relations, and (b) check numerically.'),[('csch는 홀함수이고 원점에 수직점근선, 양쪽 무한대에서 수평점근선 y=0을 가진다.','csch is odd, has a vertical asymptote at zero and horizontal asymptote y=0.'),('sech는 짝함수로 최대값1을 원점에서 가지며 양끝에서0으로 간다. coth는 홀함수이고 원점에서 발산하며 양끝 극한은 ±1이다.','sech is even with maximum1 at zero and tends to0 at either end. coth is odd, diverges at zero and tends to ±1 at the two infinities.')],('첨부한 세 그래프와 같다.','See the three attached graphs.'),('수치 역수값과 함수의 대칭·점근선·부호를 함께 확인했다.','Checked numerical reciprocals against symmetry, asymptotes and signs.'),['a','b'])
plots(b,26,[(name,-4,4,-4,4,[(name,fn)])for name,fn in [('csch',lambda q:1/math.sinh(q)),('sech',lambda q:1/math.cosh(q)),('coth',lambda q:1/math.tanh(q))]])
lims=[(s.tanh(x),s.oo,'',1),(s.tanh(x),-s.oo,'',-1),(s.sinh(x),s.oo,'',s.oo),(s.sinh(x),-s.oo,'',-s.oo),(s.sech(x),s.oo,'',0),(s.coth(x),s.oo,'',1),(s.coth(x),0,'+',s.oo),(s.coth(x),0,'-',-s.oo),(s.csch(x),-s.oo,'',0),(s.sinh(x)/s.exp(x),s.oo,'',R(1,2))]
ss=[];qq=[];aa=[]
for i,(f,q,d,val)in enumerate(lims):
 assert s.limit(f.rewrite(s.exp),x,q,dir=d or '+')==val
 eq=r'\lim_{x\to '+s.latex(q)+d+'}'+s.latex(f);qq.append(fr'({chr(97+i)})\ '+eq);ss.append(eq+'='+s.latex(s.sympify(val)));aa.append(fr'({chr(97+i)})\ '+s.latex(s.sympify(val)))
mathadd(27,r';\quad'.join(qq),[r'\tanh x=\frac{1-e^{-2x}}{1+e^{-2x}},\quad\coth x=\frac{e^{2x}+1}{e^{2x}-1}']+ss,r';\quad'.join(aa),parts=list('abcdefghij'))
mathadd(28,r'(a)\cosh x,\ (b)\tanh x,\ (c)\operatorname{csch}x,\ (d)\operatorname{sech}x,\ (e)\coth x',[r'(\cosh x)\prime=(e^x-e^{-x})/2=\sinh x',r'(\tanh x)\prime=(\cosh^2x-\sinh^2x)/\cosh^2x=\operatorname{sech}^2x',r'(1/\sinh x)\prime=-\cosh x/\sinh^2x=-\operatorname{csch}x\coth x',r'(1/\cosh x)\prime=-\sinh x/\cosh^2x=-\operatorname{sech}x\tanh x',r'(\coth x)\prime=(\sinh^2x-\cosh^2x)/\sinh^2x=-\operatorname{csch}^2x'],r'\sinh x;\ \operatorname{sech}^2x;\ -\operatorname{csch}x\coth x;\ -\operatorname{sech}x\tanh x;\ -\operatorname{csch}^2x',parts=list('abcde'))
mathadd(29,r'\operatorname{arsinh}x=\ln(x+\sqrt{1+x^2})',[r'y=\operatorname{arsinh}x\Rightarrow\sinh y=x,\quad\cosh y=\sqrt{1+x^2}',r'e^y=\cosh y+\sinh y=\sqrt{1+x^2}+x>0',r'y=\ln(x+\sqrt{1+x^2})'],r'\operatorname{arsinh}x=\ln(x+\sqrt{1+x^2}),\quad x\in\mathbb R')
mathadd(30,r'\operatorname{arcosh}x=\ln(x+\sqrt{x^2-1})',[r'y=\operatorname{arcosh}x\ge0,\quad e^{2y}-2xe^y+1=0',r'e^y=x\pm\sqrt{x^2-1};\quad e^y\ge1\Rightarrow e^y=x+\sqrt{x^2-1}',r'y=\ln(x+\sqrt{x^2-1})'],r'\operatorname{arcosh}x=\ln(x+\sqrt{x^2-1}),\quad x\ge1')
mathadd(31,r'\operatorname{artanh}x=\tfrac12\ln\frac{1+x}{1-x}',[r'(a)\ x=(e^{2y}-1)/(e^{2y}+1)\Rightarrow e^{2y}=(1+x)/(1-x)',r'(b)\ \tanh y=x,\quad(1+\tanh y)/(1-\tanh y)=e^{2y}',r'2y=\ln((1+x)/(1-x)),\quad |x|<1'],r'\operatorname{artanh}x=\tfrac12\ln\frac{1+x}{1-x},\quad|x|<1',parts=['a','b'])
add(32,('(a) arccsch, (b) arcsech, (c) arccoth의 역함수 정의·그래프·로그 공식을 구하라.','For (a) arccsch, (b) arcsech and (c) arccoth, give the inverse definition, graph and logarithmic formula.'),[('arccsch는 csch의 두 가지 전체를 역으로 한다. arcsech는 sech를 입력 y≥0에 제한하여 역으로 한다. arccoth는 coth의 두 가지 전체를 역으로 한다.','arccsch inverts both branches of csch. arcsech inverts sech restricted to inputs y≥0. arccoth inverts both branches of coth.')]+fs(r'y=\operatorname{arccsch}x\iff\sinh y=1/x\Rightarrow y=\ln(1/x+\sqrt{1+x^{-2}}),\quad x\ne0',r'y=\operatorname{arcsech}x\iff\cosh y=1/x,\ y\ge0\Rightarrow y=\ln((1+\sqrt{1-x^2})/x),\quad0<x\le1',r'y=\operatorname{arccoth}x\iff\tanh y=1/x\Rightarrow y=\tfrac12\ln((x+1)/(x-1)),\quad |x|>1'),same(M(r'(a)\ \ln(1/x+\sqrt{1+x^{-2}}),\ D=\mathbb R\setminus\{0\},\ R=\mathbb R\setminus\{0\};\quad(b)\ \ln((1+\sqrt{1-x^2})/x),\ D=(0,1],\ R=[0,\infty);\quad(c)\ \tfrac12\ln((x+1)/(x-1)),\ D=(-\infty,-1)\cup(1,\infty),\ R=\mathbb R\setminus\{0\}')),('로그 인수가 양수인 범위를 확인하고 역합성을 대조했다. 음수 x에서 arccsch도 음수여야 한다.','Checked positive logarithm arguments and inverse compositions. arccsch must be negative for negative x.'),['a','b','c'])
plots(b,32,[('arccsch',-4,4,-4,4,[('asinh(1/x)',lambda q:math.asinh(1/q))]),('arcsech',0,1,0,5,[('acosh(1/x)',lambda q:math.acosh(1/q))]),('arccoth',-4,4,-3,3,[('atanh(1/x)',lambda q:math.atanh(1/q))])])
mathadd(33,r'(a)\operatorname{arcosh}x,\ (b)\operatorname{artanh}x,\ (c)\operatorname{arccoth}x',[r'(a)\cosh y=x,\ y>0\Rightarrow\sinh y\,y\prime=1\Rightarrow y\prime=1/\sqrt{x^2-1},\ x>1',r'(b)\tanh y=x\Rightarrow(1-x^2)y\prime=1,\quad |x|<1',r'(c)\coth y=x\Rightarrow-(x^2-1)y\prime=1,\quad |x|>1'],r'(a)\ 1/\sqrt{x^2-1};\quad(b),(c)\ 1/(1-x^2)',('역관계의 미분에서 sinh의 부호와 coth의 정의역을 보존했다.','Preserved the sign of sinh and the domain of coth when differentiating the inverse relations.'),list('abc'))
mathadd(34,r'(a)\operatorname{arcsech}x,\ (b)\operatorname{arccsch}x',[r'(a)\operatorname{sech}y=x,\ y>0:\ -x\sqrt{1-x^2}\,y\prime=1',r'(b)\operatorname{csch}y=x:\ -\operatorname{csch}y\coth y\,y\prime=1',r'\coth y=\operatorname{sgn}(x)\sqrt{1+x^2}\Rightarrow x\coth y=|x|\sqrt{1+x^2}'],same(M(r'(a)\ -1/(x\sqrt{1-x^2}),\ 0<x<1;\quad(b)\ -1/(|x|\sqrt{1+x^2}),\ x\ne0'))[0] if False else r'(a)\ -1/(x\sqrt{1-x^2}),\ 0<x<1;\quad(b)\ -1/(|x|\sqrt{1+x^2}),\ x\ne0',('arccsch의 음수 가지도 미분값이 음수여서 절댓값이 필요하다.','The negative arccsch branch also has negative derivative, requiring the absolute value.'),['a','b'])
derivs={35:(s.cosh(3*x),x),36:(s.exp(x)*s.cosh(x),x),37:(s.sinh(x*x),x),38:(s.sinh(x)**2,x),39:(s.sinh(s.log(t)),t),40:(s.log(s.sinh(t)),t),41:(s.tanh(s.sqrt(x)),x),42:(s.exp(s.tanh(2*v)),v),43:(s.sech(x)*s.tanh(x),x),44:(s.sech(s.tanh(x)),x),45:(t*s.coth(s.sqrt(t*t+1)),t),46:((1+s.sinh(t))/(1-s.sinh(t)),t),47:(s.asinh(-2*x),x),48:(s.atanh(x**3),x),49:(s.acosh(s.sec(th)),th),50:(s.acosh(1/s.sin(th)),th),51:(s.acosh(s.sqrt(1+u*u)),u),52:(x*s.atanh(x)+s.log(1-x*x)/2,x),53:(x*s.asinh(x/3)-s.sqrt(9+x*x),x)}
custom={36:s.exp(2*x),39:(t*t+1)/(2*t*t),46:2*s.cosh(t)/(1-s.sinh(t))**2,49:s.sec(th),50:-s.csc(th),51:1/s.sqrt(1+u*u),52:s.atanh(x),53:s.asinh(x/3)}
for n,(f,z) in derivs.items():
 df=s.diff(f,z);ans=custom.get(n,s.simplify(df));F=s.lambdify(z,f,'mpmath');DF=s.lambdify(z,ans,'mpmath')
 for vv in map(mp.mpf,['.2','.4']):assert abs(mp.diff(F,vv)-DF(vv))<mp.mpf('1e-25'),(n,vv)
 eq=s.latex(f);extra=''
 if n==49:extra=r',\quad0\le\theta<\pi/2'
 if n==50:extra=r',\quad0<\theta<\pi/2';eq=r'\operatorname{arcsech}(\sin\theta)'
 if n==51:extra=r',\quad u>0'
 add(n,(M('f='+eq+extra)+'도함수를 구하고 간단히 하라.',M('f='+eq+extra)+'Differentiate and simplify.'),[('합성함수의 바깥 미분에 안쪽 도함수를 곱하고, 곱·몫은 해당 미분법을 적용한다.','Multiply the outer derivative by the inner derivative; apply the product or quotient rule where needed.')]+fs(r'f\prime='+s.latex(df),r'f\prime='+s.latex(ans))+([('θ=0은 정의역 끝점으로 오른쪽 도함수가1이며 내부 도함수 secθ의 연속 확장과 일치한다.','At the endpoint θ=0, the right derivative is1, agreeing with the continuous extension of secθ.') ]if n==49 else[]),same(M(r'f\prime='+s.latex(ans))),('허용 입력0.2와0.4에서 원 함수의 독립 수치미분과 도함수식을 대조했다.','Compared independent numerical derivatives of the original function with the formula at admissible inputs0.2 and0.4.'))
mathadd(54,r'\frac d{dx}\sqrt[4]{\frac{1+\tanh x}{1-\tanh x}}=\tfrac12e^{x/2}',[r'\frac{1+\tanh x}{1-\tanh x}=e^{2x}>0',r'\sqrt[4]{e^{2x}}=e^{x/2}\Rightarrow\frac d{dx}e^{x/2}=\tfrac12e^{x/2}'],r'\tfrac12e^{x/2}')
mathadd(55,r'\frac d{dx}\arctan(\tanh x)=\operatorname{sech}2x',[r'\frac{\operatorname{sech}^2x}{1+\tanh^2x}=\frac1{\cosh^2x+\sinh^2x}',r'=1/\cosh2x=\operatorname{sech}2x'],r'\operatorname{sech}2x')
A=mp.mpf('211.49');B=mp.mpf('20.96');k=mp.mpf('.03291765');xx=mp.acosh((A-100)/B)/k;slope=-B*k*mp.sinh(k*xx)
add(56,('아치 중심선 y=211.49−20.96cosh(0.03291765x), |x|≤91.20 (m)에 대해 (a) 그래프, (b) 중앙 높이, (c) 높이100m인 점, (d) 그 점의 기울기를 구하라.','For the arch centerline y=211.49−20.96cosh(0.03291765x), |x|≤91.20 in meters, find (a) its graph, (b) central height, (c) points at height100m and (d) slopes there.'),fs(r'y(0)=211.49-20.96=190.53',r'\cosh(0.03291765x)=(211.49-100)/20.96',r'x=\pm\operatorname{arcosh}(111.49/20.96)/0.03291765',r'y\prime=-20.96(0.03291765)\sinh(0.03291765x)'),same(M(fr'(b)\ 190.53\mathrm{{m}};\quad(c)\ (\pm{float(xx):.6f},100);\quad(d)\ y\prime(-{float(xx):.6f})={float(-slope):.6f},\ y\prime({float(xx):.6f})={float(slope):.6f}')),('역쌍곡코사인으로 구한 양쪽 x를 원 높이식에 대입하여100m를 확인했다. 기울기는 홀대칭이다.','Substituted both inverse-cosh solutions into the original height equation to confirm100m. Slopes have odd symmetry.'),list('abcd'))
plots(b,56,[('Arch centerline',-92,92,0,200,[('y(x)',lambda q:211.49-20.96*math.cosh(.03291765*q))])])
mathadd(57,r'v=\sqrt{\frac{gL}{2\pi}\tanh\frac{2\pi d}{L}}\approx\sqrt{\frac{gL}{2\pi}}',[r'd/L\gg1\Rightarrow z=2\pi d/L\gg1',r'\tanh z=\frac{1-e^{-2z}}{1+e^{-2z}}\to1',r'v/\sqrt{gL/(2\pi)}=\sqrt{\tanh z}\to1'],r'v\approx\sqrt{gL/(2\pi)}\quad(d/L\gg1)',('깊이 자체가 아니라 파장에 대한 깊이 비율이 큰 경우임을 명시했다.','Specified large depth relative to wavelength, not depth alone.'))
add(58,('a>0인 곡선족 y=a cosh(x/a)를 여러 a에 대해 그리고 변화를 설명하라.','Graph y=a cosh(x/a) for several a>0 and describe the changes.'),fs(r'f_a(0)=a,\quad f_a\prime(x)=\sinh(x/a),\quad f_a\prime\prime(x)=\cosh(x/a)/a>0',r'f_a\prime\prime(0)=1/a,\quad (x,y)=(au,a\cosh u)')+[('모두 짝함수이며 최저점은(0,a)이다. a가 커지면 최저점이 높아지고 중심 근처 곡률은 작아진다. 전체 곡선은 y=cosh x를 가로·세로 같은 비율 a로 확대한다.','All are even with minimum(0,a). Increasing a raises the minimum and decreases curvature near the center. The whole graph is a uniform scaling of y=cosh x by factor a.')],('첨부 그래프 및 확대 관계와 같다.','See the graph and uniform scaling relation.'),('상수 a의 변화가 단순 수직 평행이동이 아님을 매개좌표로 확인했다.','The parameterization confirms that changing a is more than a vertical translation.'))
plots(b,58,[('Catenary family',-4,4,0,15,[(f'a={a}',lambda q,a=a:a*math.cosh(q/a))for a in[.7,1,2,3]])])
sl=mp.sinh(mp.mpf('.35'));angle=90-mp.degrees(mp.atan(sl))
mathadd(59,r'y=20\cosh(x/20)-15,\quad -7\le x\le7',[r'y\prime=\sinh(x/20),\quad y\prime(7)=\sinh(7/20)',r'\theta=\pi/2-\arctan(\sinh(7/20))'],fr'(a)\ {float(sl):.7f};\quad(b)\ {float(angle):.5f}^\circ',('기둥은 수직이므로 수평선과의 접선각의 여각을 구했다.','The pole is vertical, so the required angle complements the tangent angle to the horizontal.'),['a','b'])
mathadd(60,r'y=\frac{T}{\rho g}\cosh\frac{\rho gx}{T},\quad y\prime\prime=\frac{\rho g}T\sqrt{1+(y\prime)^2}',[r'y\prime=\sinh(\rho gx/T),\quad y\prime\prime=(\rho g/T)\cosh(\rho gx/T)',r'\sqrt{1+(y\prime)^2}=\sqrt{1+\sinh^2(\rho gx/T)}=\cosh(\rho gx/T)>0'],r'y\prime\prime=(\rho g/T)\sqrt{1+(y\prime)^2}',('양의 물리 상수에서 cosh가 항상 양수여서 제곱근을 올바르게 제거했다.','For positive physical constants, cosh is positive, justifying removal of the square root.'))
mathadd(61,r'\rho=2\mathrm{kg/m},\quad\text{span}=200\mathrm m,\quad g=9.8\mathrm{m/s^2}',[r'(a)\ y(0)=T/(\rho g)=60\Rightarrow T=1176\mathrm N',r'y(100)=60\cosh(100/60)',r'(b)\ T_{\mathrm{new}}=2352\Rightarrow y_{\mathrm{new}}(0)=120,\quad y_{\mathrm{new}}(100)=120\cosh(100/120)'],fr'(a)\ T=1176\mathrm N,\ H={float(60*mp.cosh(mp.mpf(5)/3)):.5f}\mathrm m;\quad(b)\ y_{{\min}}=120\mathrm m,\ H={float(120*mp.cosh(mp.mpf(5)/6)):.5f}\mathrm m',('60번의 주어진 좌표·상수항 없는 모형을 적용했다. 새 장력에서 기둥 높이도 새로 정한다.','Used the specified coordinate convention and unshifted model of60; pole height is recomputed under the new tension.'),['a','b'])
mathadd(62,r'v(t)=\sqrt{mg/k}\tanh(t\sqrt{gk/m}),\quad m=60,\ g=9.8',[r'\lim_{t\to\infty}\tanh(t\sqrt{gk/m})=1\quad(m,g,k>0)',r'v_\infty=\sqrt{mg/k}',r'k_{\mathrm{belly}}=0.515,\quad k_{\mathrm{feet}}=0.067'],fr'(a)\ \sqrt{{mg/k}};\quad(b)\ {float(mp.sqrt(588/mp.mpf(".515"))):.5f}\mathrm{{m/s}},\ {float(mp.sqrt(588/mp.mpf(".067"))):.5f}\mathrm{{m/s}}',('문제에 제시된 모델 매개변수를 그대로 대입하였다. 작은 저항계수에서 종단속도가 더 크다.','Substituted the model parameters supplied in the problem. The smaller drag parameter yields the larger terminal velocity.'),['a','b'])
mathadd(63,r'(a)\ y=A\sinh(mx)+B\cosh(mx);\quad(b)\ y\prime\prime=9y,\ y(0)=-4,\ y\prime(0)=6',[r'y\prime=mA\cosh(mx)+mB\sinh(mx)',r'y\prime\prime=m^2[A\sinh(mx)+B\cosh(mx)]=m^2y',r'm=3,\quad B=-4,\quad3A=6\Rightarrow A=2'],r'(a)\ y\prime\prime=m^2y;\quad(b)\ y=2\sinh3x-4\cosh3x',('도함수와 초기값을 최종식에 직접 대입했다.','Substituted the final formula into the differential equation and both initial conditions.'),['a','b'])
mathadd(64,r'x=\ln(\sec\theta+\tan\theta)\Rightarrow\sec\theta=\cosh x',[r'e^x=\sec\theta+\tan\theta,\quad(\sec\theta+\tan\theta)(\sec\theta-\tan\theta)=1',r'e^{-x}=\sec\theta-\tan\theta',r'\cosh x=(e^x+e^{-x})/2=\sec\theta'],r'\sec\theta=\cosh x',('원 로그식이 실수로 정의되는 곳에서 두 합·차는 모두 양수이고 역수 관계이다.','Where the original real logarithm is defined, both the sum and difference are positive reciprocals.'))
mathadd(65,r'y=\cosh x,\quad y\prime=1',[r'y\prime=\sinh x=1\Rightarrow x=\ln(1+\sqrt2)',r'y=\sqrt{1+\sinh^2x}=\sqrt2'],r'(\ln(1+\sqrt2),\sqrt2)',('sinh가 엄격히 증가하므로 이 접점은 유일하다.','Strict increase of sinh makes this tangent point unique.'))
add(66,('양의 정수 n에 대해 f_n(x)=tanh(n sin x)의 그래프를 조사하고 n→∞의 변화를 설명하라.','Investigate f_n(x)=tanh(n sin x) for positive integers n and describe its behavior as n→∞.'),fs(r'\sin x>0\Rightarrow f_n(x)\to1,\quad\sin x<0\Rightarrow f_n(x)\to-1',r'\sin x=0\Rightarrow f_n(x)=0',r'f_n\prime(k\pi)=n(-1)^k')+[('영점 사이에서는 ±1인 사각파 모양에 가까워지고 kπ 근처 전이가 가팔라진다. 각 f_n은 연속이지만 불연속인 극한으로의 수렴은 영점을 포함하는 구간에서 균등하지 않다.','Between zeros the graphs approach levels ±1, with increasingly steep transitions near kπ. Each f_n is continuous, but convergence to the discontinuous limit is not uniform on intervals containing a zero.')],same(M(r'\lim_{n\to\infty}f_n(x)=\operatorname{sgn}(\sin x),\quad\operatorname{sgn}(0)=0')),('영점에서는 극한을 ±1로 임의 정의하지 않고 모든 n에서0인 값을 유지했다.','At the zeros, retained the value0 valid for every n instead of assigning ±1.'))
plots(b,66,[('Approach to a square wave',-2*math.pi,2*math.pi,-1.3,1.3,[(f'n={nn}',lambda q,nn=nn:math.tanh(nn*math.sin(q)))for nn in[1,3,10]])])
ints={67:(s.sinh(x)*s.cosh(x)**2,s.cosh(x)**3/3,r'u=\cosh x,\quad du=\sinh x\,dx'),68:(s.sinh(1+4*x),s.cosh(1+4*x)/4,r'u=1+4x,\quad dx=du/4'),69:(s.sinh(s.sqrt(x))/s.sqrt(x),2*s.cosh(s.sqrt(x)),r'u=\sqrt x,\quad dx=2u\,du'),70:(s.tanh(x),s.log(s.cosh(x)),r'u=\cosh x,\quad du=\sinh x\,dx'),71:(s.cosh(x)/(s.cosh(x)**2-1),-s.csch(x),r'\cosh^2x-1=\sinh^2x,\quad u=\sinh x'),72:(s.sech(x)**2/(2+s.tanh(x)),s.log(2+s.tanh(x)),r'u=2+\tanh x,\quad du=\operatorname{sech}^2x\,dx')}
for n,(f,F,sub)in ints.items():
 assert s.simplify(s.diff(F,x)-f)==0
 mathadd(n,s.latex(s.Integral(f,x)),[sub,r'\int '+s.latex(f)+r'\,dx='+s.latex(F)+'+C'],s.latex(F)+'+C',('최종 원시함수를 미분하여 피적분함수와 기호적으로 일치함을 확인했다.','Differentiated the final antiderivative and confirmed symbolic equality with the integrand.'))
mathadd(73,r'\int_4^6\frac{dt}{\sqrt{t^2-9}}',[r'F(t)=\operatorname{arcosh}(t/3)=\ln((t+\sqrt{t^2-9})/3)',r'F(6)-F(4)=\ln\frac{6+3\sqrt3}{4+\sqrt7}'],r'\ln\frac{6+3\sqrt3}{4+\sqrt7}',('적분구간 t≥4에서 양의 제곱근 가지를 사용하며 수치구적으로 대조했다.','Used the positive square-root branch on t≥4 and checked by numerical quadrature.'))
mathadd(74,r'\int_0^1\frac{dt}{\sqrt{16t^2+1}}',[r'u=4t,\quad dt=du/4',r'\tfrac14[\operatorname{arsinh}u]_0^4=\tfrac14\ln(4+\sqrt{17})'],r'\tfrac14\ln(4+\sqrt{17})',('대입변환의1/4 배율과 바뀐 상한4를 함께 확인했다.','Checked both the factor1/4 and the transformed upper limit4.'))
mathadd(75,r'\int\frac{e^x}{1-e^{2x}}\,dx',[r'u=e^x,\quad du=e^x\,dx',r'\frac1{1-u^2}=\tfrac12\left(\frac1{1+u}+\frac1{1-u}\right)',r'\int\frac{du}{1-u^2}=\tfrac12\ln\left|\frac{1+u}{1-u}\right|+C'],r'\tfrac12\ln\left|\frac{1+e^x}{1-e^x}\right|+C,\quad x\ne0',('x<0에서는 artanh(e^x)와 같지만 x>0에서도 원 적분이 실수로 정의되므로 절댓값 로그로 두 구간을 모두 표현했다.','For x<0 this equals artanh(e^x); the absolute-value logarithm also covers the original real integrand on x>0.'))
c=mp.findroot(lambda q:(mp.cosh(q)-1)/q-1,1.6)
add(76,('0≤x≤1에서 y=sinh(cx) 아래 넓이가1이 되도록 양의 c를 추정하라.','Estimate the positive c for which the area under y=sinh(cx) on0≤x≤1 equals1.'),fs(r'\int_0^1\sinh(cx)\,dx=(\cosh c-1)/c=1',r'F(c)=\cosh c-1-c,\quad F\prime(c)=\sinh c-1',r'c_{n+1}=c_n-\frac{\cosh c_n-1-c_n}{\sinh c_n-1},\quad c_0=1.6'),same(M(fr'c\approx{float(c):.10f}')),('c=0은 분모를 곱할 때 생기는 가짜 후보로 실제 넓이는0이다. 양의 c에서 넓이의 도함수는 ∫₀¹xcosh(cx)dx>0이므로 해가 유일하며 수치구적으로1을 확인했다.','c=0 is an extraneous candidate introduced by multiplying the denominator; its area is0. The area derivative ∫₀¹xcosh(cx)dx is positive for c>0, proving uniqueness, and numerical quadrature gives1.'))
plots(b,76,[('Area equation',0,3,0,3,[('area(c)',lambda q:(math.cosh(q)-1)/q if q else 0),('target 1',lambda q:1)])])
a=s.asinh(R(1,2));area=s.simplify(a+s.cosh(a)-s.sinh(2*a)/2-1)
add(77,('(a) cosh(2x)=1+sinh x의 교점을 수치적으로 구하고 (b) 두 곡선 사이 넓이를 추정하라.','(a) Numerically locate intersections of cosh(2x)=1+sinh x and (b) estimate the enclosed area.'),fs(r'\cosh2x=1+2\sinh^2x\Rightarrow\sinh x(2\sinh x-1)=0',r'x=0,\quad a=\operatorname{arsinh}(1/2)=\ln((1+\sqrt5)/2)',r'A=\int_0^a(1+\sinh x-\cosh2x)\,dx=[x+\cosh x-\tfrac12\sinh2x]_0^a'),same(M(fr'(a)\ x=0,\ {float(a):.8f};\quad(b)\ A=\ln\frac{{1+\sqrt5}}2+\frac{{\sqrt5}}4-1\approx{float(area):.10f}')),('交点 사이에서 sinh x∈[0,1/2]이므로 위−아래가 비음수이다. 정확한 이차방정식 해와 수치구적이 일치한다.','Between intersections, sinh x∈[0,1/2], so the upper-minus-lower difference is nonnegative. Exact quadratic roots and numerical quadrature agree.'),['a','b'])
area_svg(b,77,[(0,a,1+s.sinh(x),s.cosh(2*x))],x,'6.7.77 Enclosed hyperbolic region');b.save()
add(78,('단위 쌍곡선 x²−y²=1의 점(cosh t,sinh t), t≥0와 양의 x축 사이 쌍곡부채꼴 넓이가 t/2임을 증명하라.','Prove that the hyperbolic sector between the positive x-axis and(cosh t,sinh t) on x²−y²=1 has area t/2 for t≥0.'),fs(r'A(t)=\tfrac12\sinh t\cosh t-\int_1^{\cosh t}\sqrt{x^2-1}\,dx',r'A\prime(t)=\tfrac12(\cosh^2t+\sinh^2t)-\sqrt{\cosh^2t-1}\sinh t',r't\ge0\Rightarrow\sqrt{\cosh^2t-1}=\sinh t',r'A\prime(t)=\tfrac12(\cosh^2t-\sinh^2t)=\tfrac12,\quad A(0)=0'),same(M(r'A(t)=t/2,\quad t\ge0')),('양의 방향 매개변수 t를 사용했다. 음수 t까지 확장할 때 부호 없는 기하 넓이는 |t|/2이고 유향 넓이가 t/2이다.','Used the positive parameter orientation. For negative t, unsigned geometric area is |t|/2 while oriented area is t/2.'))
# Own sector at t=1; first strip is triangle above x-axis, second subtracts hyperbola.
area_svg(b,78,[(s.S(0),s.S(1),s.tanh(1)*x,s.S(0)),(1,s.cosh(1),s.tanh(1)*x,s.sqrt(x*x-1))],x,'6.7.78 Hyperbolic sector at t=1');b.save()
add(79,('0이 아닌 실수 a,b에 대해 aeˣ+be⁻ˣ가 αsinh(x+β) 또는 αcosh(x+β)로 표현됨을 증명하고 α,β를 구하라.','For nonzero real a,b, show that aeˣ+be⁻ˣ can be written as αsinh(x+β) or αcosh(x+β), and find α,β.'),fs(r'\beta=\tfrac12\ln|a/b|',r'ab>0:\ \alpha=2\operatorname{sgn}(a)\sqrt{ab},\quad\frac\alpha2e^\beta=a,\quad\frac\alpha2e^{-\beta}=b',r'ab<0:\ \alpha=2\operatorname{sgn}(a)\sqrt{-ab},\quad\frac\alpha2e^\beta=a,\quad-\frac\alpha2e^{-\beta}=b'),same(M(r'ab>0:\ ae^x+be^{-x}=2\operatorname{sgn}(a)\sqrt{ab}\cosh\left(x+\tfrac12\ln|a/b|\right);\quad ab<0:\ ae^x+be^{-x}=2\operatorname{sgn}(a)\sqrt{-ab}\sinh\left(x+\tfrac12\ln|a/b|\right)')),('같은 부호와 반대 부호의 두 경우 모두 지수의 계수를 비교했다. α에 a의 부호를 넣어 a<0인 경우도 포함한다.','Matched both exponential coefficients for equal and opposite signs. The sign of a in α also covers a<0.'))
# Explicit task verbs for the formula-led exercises.
requests={7:('지수함수 eˣ,e⁻ˣ의 일차결합으로 나타내라.','Express as a linear combination of eˣ and e⁻ˣ.'),8:('sinh(2x), cosh(2x)의 일차결합으로 나타내라.','Express as a linear combination of sinh(2x) and cosh(2x).'),9:('x의 유리함수로 나타내라.','Express as a rational function of x.'),10:('x의 유리함수로 나타내라.','Express as a rational function of x.'),24:('나머지 다섯 쌍곡함수값을 구하라.','Find the other five hyperbolic function values.'),25:('나머지 다섯 쌍곡함수값을 구하라.','Find the other five hyperbolic function values.'),59:('(a) 오른쪽 기둥 x=7에서의 기울기와 (b) 수직 기둥과 케이블 접선 사이 각을 구하라.','Find (a) the slope at the right pole x=7 and (b) the angle between the cable tangent and the vertical pole.'),61:('(a) 60번의 모형에서 최저 높이가60m일 때 장력과 기둥 높이를 구하라. (b) 장력을 두 배로 할 때 새 최저 높이와 기둥 높이를 구하라.','(a) Using the model in60, find tension and pole height for minimum height60m. (b) Double the tension and find the new minimum height and pole height.'),62:('(a) 종단속도 lim v(t)를 구하라. (b) k=0.515인 배를 아래로 한 자세와 k=0.067인 발을 아래로 한 자세의 값을 구하라.','(a) Find terminal velocity lim v(t). (b) Evaluate for the belly-to-earth parameter k=0.515 and feet-first parameter k=0.067.')}
for n,(ko,en)in requests.items():
 for lang,req in [('ko',ko),('en',en)]:b.E[n]['statement'][lang]=b.E[n]['statement'][lang].replace('계산하거나 증명하라.',req).replace('Evaluate or prove.',req)
b.E[77]['check']['ko']=b.E[77]['check']['ko'].replace('交点','교점')
b.save();print('6.7 COMPLETE',len(b.E))
