from calc1_helpers import *
from calc1_plot_helpers import plots
x,t=s.symbols('x t',real=True);R=s.Rational;oo=s.oo;pi=s.pi;log=s.log;exp=s.exp;sq=s.sqrt
b=CalcBook('7.8',[587,588,589,590]);checks=[]
def add(n,st,steps,ans,ck=None,parts=[]):
 b.add(n,587 if n<=10 else 588 if n<=68 else 589 if n<=82 else 590,('이상적분','Improper integrals'),st,steps,ans,parts=parts);b.verify(n,*(ck or('특이점과 양 끝의 극한을 별도로 확인하고 원시함수 미분 또는 독립 수치적분으로 대조했다.','Checked singularities and endpoint limits separately, and verified primitive derivatives or independent numerical integration.')));b.save()
def ma(n,eq,steps,ans,ck=None,parts=[]):add(n,(M(eq)+'판정하고 계산하거나 증명하라.',M(eq)+'Classify and evaluate, or prove.'),fs(*steps),same(M(ans)),ck,parts)
add(1,('다음 적분이 이상적분인 이유를 각각 설명하라: (a)∫₁⁴1/(x−3)dx (b)∫₃∞1/(x²−4)dx (c)∫₀¹tan(πx)dx (d)∫₋∞⁻¹eˣ/x dx.','Explain why each is improper: (a)∫₁⁴1/(x−3)dx (b)∫₃∞1/(x²−4)dx (c)∫₀¹tan(πx)dx (d)∫₋∞⁻¹eˣ/x dx.'),[('a는 내부 x=3에서 무한 불연속, c는 x=1/2에서 무한 불연속이다. 둘 다2종이다.','In a, x=3 is an infinite discontinuity; in c, x=1/2 is one. Both are Type2.'),('b는 오른쪽 끝이∞, d는 왼쪽 끝이−∞이므로1종이다.','In b the upper endpoint is∞; in d the lower endpoint is−∞. Both are Type1.')],('a,c:2종; b,d:1종.','a,c:Type2; b,d:Type1.'),parts=list('abcd'))
add(2,('이상적분인지 판정하고 이유를 쓰라: (a)∫₀πsec x dx (b)∫₀⁴1/(x−5)dx (c)∫₋₁³1/(x+x³)dx (d)∫₁∞1/(x+x³)dx.','Classify and explain: (a)∫₀πsec x dx (b)∫₀⁴1/(x−5)dx (c)∫₋₁³1/(x+x³)dx (d)∫₁∞1/(x+x³)dx.'),[('a는 x=π/2, c는 x=0에서 무한 불연속이므로2종이다.','a and c have infinite discontinuities at x=π/2 and x=0, respectively:Type2.'),('b는 [0,4]에서 연속이므로 보통 적분이다. x=5는 적분구간 밖이다. d는 무한구간의1종이다.','b is proper because its integrand is continuous on [0,4]; x=5 lies outside. d is Type1 because of its infinite interval.')],('a,c:2종; b:보통 적분; d:1종.','a,c:Type2; b:proper; d:Type1.'),parts=list('abcd'))
ma(3,r'A(t)=\int_1^tx^{-3}dx,\quad t=10,100,1000',[r'A(t)=[-1/(2x^2)]_1^t=\tfrac12(1-t^{-2})',r'A(10)=0.495,\quad A(100)=0.49995,\quad A(1000)=0.4999995',r'\lim_{t\to\infty}A(t)=1/2'],r'A(t)=\tfrac12(1-t^{-2});\quad A(\infty)=1/2')
ts=[10,100,10**4,10**6,10**10,10**20];rows=[str(z)+'&'+f'{10*(1-z**(-.1)):.8f}'+'&'+f'{10*(z**.1-1):.8f}'for z in ts]
add(4,(M(r'f=x^{-1.1},\quad g=x^{-0.9}')+'(a)[0,10]×[0,1]과 [0,100]×[0,1]에 함께 그려라. (b)1에서 t까지 넓이를 t=10,100,10⁴,10⁶,10¹⁰,10²⁰에 대해 구하라. (c)전체 넓이를 판정하라.',M(r'f=x^{-1.1},\quad g=x^{-0.9}')+'(a)Graph together in [0,10]×[0,1] and [0,100]×[0,1].(b)Find areas from1 to t for t=10,100,10⁴,10⁶,10¹⁰,10²⁰.(c)Find total areas.'),fs(r'A_f(t)=10(1-t^{-0.1}),\quad A_g(t)=10(t^{0.1}-1)',r'\begin{array}{r|rr}t&A_f&A_g\\\hline'+r'\\'.join(rows)+r'\end{array}',r'\lim A_f=10,\quad\lim A_g=\infty'),same(M(r'A_f(\infty)=10;\quad A_g(\infty)=\infty')),parts=list('abc'))
plots(b,4,[(f'7.8.4 Powers on [0,{v}]',0,v,0,1,[('x^-1.1',lambda x:x**-1.1),('x^-0.9',lambda x:x**-.9)])for v in[10,100]])
# Exact one-sided improper integrals. All finite endpoint singularities use limits, not direct substitution.
def imp(n,f,F,a,c,expected,extra=[]):
 f,F,a,c=map(s.sympify,[f,F,a,c]);delta=s.simplify(s.diff(F,x)-f)
 if delta!=0:
  ff=s.lambdify(x,f,'mpmath');FF=s.lambdify(x,F,'mpmath');pt=-2 if a==-oo else 2 if c==oo else float((a+c)/2)
  assert abs(mp.diff(FF,pt)-ff(pt))<mp.mpf('1e-20'),(n,delta)
 la=s.limit(F,x,a,dir='+')if a!=-oo else s.limit(F,x,-oo);lc=s.limit(F,x,c,dir='-')if c!=oo else s.limit(F,x,oo);val=s.simplify(lc-la);assert s.simplify(val-s.sympify(expected))==0 if val not in[oo,-oo]else val==expected,(n,val,expected)
 eq=s.latex(s.Integral(f,(x,a,c)));steps=list(extra)+fs('F(x)='+s.latex(F),r'\lim_{x\to '+s.latex(a)+r'^{'+('+'if a!=-oo else'')+r'}}F(x)='+s.latex(la),r'\lim_{x\to '+s.latex(c)+r'^{'+('-'if c!=oo else'')+r'}}F(x)='+s.latex(lc))
 ans=s.latex(val) if val not in[oo,-oo]else r'\text{Diverges }('+s.latex(val)+')'
 add(n,(M(eq)+'수렴·발산을 판정하고 수렴하면 값을 구하라.',M(eq)+'Determine convergence and evaluate if convergent.'),steps,same(M(ans)));checks.append({'number':n,'value':str(val)});return val
rows=[(5,2/x**3,-1/x**2,1,oo,1),(7,exp(-2*x),-exp(-2*x)/2,0,oo,R(1,2)),(8,3**(-x),-3**(-x)/log(3),1,oo,1/(3*log(3))),(9,1/(x+4),log(x+4),-2,oo,oo),(10,1/(x*x+4),s.atan(x/2)/2,1,oo,pi/4-s.atan(R(1,2))/2),(11,(x-2)**(-R(3,2)),-2/sq(x-2),3,oo,2),(12,(1+x)**(-R(1,4)),R(4,3)*(1+x)**R(3,4),0,oo,oo),(13,x/(x*x+1)**3,-1/(4*(x*x+1)**2),-oo,0,-R(1,4)),(14,x/(4-x*x),-log(x*x-4)/2,-oo,-3,oo),(15,(x*x+x+1)/x**4,-1/x-1/(2*x*x)-1/(3*x**3),1,oo,R(11,6)),(16,x/sq(x*x-1),sq(x*x-1),2,oo,oo),(17,exp(x)/(1+exp(x))**2,-1/(1+exp(x)),0,oo,R(1,2)),(18,(x*x+x)/x**3,log(-x)-1/x,-oo,-1,-oo),(22,exp(-1/x)/x**2,exp(-1/x),1,oo,1-exp(-1)),(23,s.sin(x)**2,x/2-s.sin(2*x)/4,0,oo,oo),(25,1/(x*x+x),log(x/(x+1)),1,oo,log(2)),(26,1/(x*x+2*x-3),log((x-1)/(x+3))/4,2,oo,log(5)/4),(27,x*exp(2*x),exp(2*x)*(x/2-R(1,4)),-oo,0,-R(1,4)),(28,x*exp(-3*x),-exp(-3*x)*(x/3+R(1,9)),2,oo,7*exp(-6)/9),(29,log(x)/x,log(x)**2/2,1,oo,oo),(30,log(x)/x**2,-(log(x)+1)/x,1,oo,1),(31,x/(x**4+4),s.atan(x*x/2)/4,-oo,0,-pi/8),(32,1/(x*log(x)**2),-1/log(x),s.E,oo,1),(33,exp(-sq(x)),-2*(sq(x)+1)*exp(-sq(x)),0,oo,2),(34,1/(sq(x)+x*sq(x)),2*s.atan(sq(x)),1,oo,pi/2),(35,1/x,log(x),0,1,oo),(36,(5-x)**(-R(1,3)),-R(3,2)*(5-x)**R(2,3),0,5,R(3,2)*5**R(2,3)),(37,(x+2)**(-R(1,4)),R(4,3)*(x+2)**R(3,4),-2,14,R(32,3)),(38,x/(x+1)**2,log(x+1)+1/(x+1),-1,2,-oo),(40,1/sq(1-x*x),s.asin(x),0,1,pi/2),(43,s.tan(x)**2,s.tan(x)-x,0,pi/2,oo),(45,x*log(x),x*x*log(x)/2-x*x/4,0,1,-R(1,4)),(46,s.cos(x)/sq(s.sin(x)),2*sq(s.sin(x)),0,pi/2,2),(47,exp(1/x)/x**3,exp(1/x)*(1-1/x),-1,0,-2/s.E),(48,exp(1/x)/x**3,exp(1/x)*(1-1/x),0,1,oo)]
for row in rows:imp(*row)
ma(6,r'\int_{-\infty}^{-1}\frac{dx}{\sqrt[3]x}',[r'F(x)=\tfrac32|x|^{2/3}\quad(x<0)',r'\int_{-A}^{-1}\frac{dx}{\sqrt[3]x}=\tfrac32(1-A^{2/3})\to-\infty'],r'\text{Diverges to }-\infty')
ma(19,r'\int_{-\infty}^{\infty}xe^{-x^2}dx',[r'F(x)=-\tfrac12e^{-x^2}',r'\int_{-\infty}^0xe^{-x^2}dx=-1/2,\quad\int_0^\infty xe^{-x^2}dx=1/2',r'\text{Both one-sided integrals converge; their sum is }0'],r'0')
ma(20,r'\int_{-\infty}^{\infty}\frac{x}{x^2+1}dx',[r'F(x)=\tfrac12\ln(x^2+1)',r'\int_{-\infty}^0f=-\infty,\quad\int_0^\infty f=+\infty',r'\int_{-A}^Af=0\text{ is only a principal value, not convergence}'],r'\text{Divergent}')
ma(21,r'\int_{-\infty}^{\infty}\cos(2t)dt',[r'\int_0^A\cos(2t)dt=\tfrac12\sin(2A)',r'A_k=\pi k\Rightarrow0;\quad B_k=\pi k+\pi/4\Rightarrow1/2',r'\text{The right-hand improper integral has no limit}'],r'\text{Divergent}')
ma(24,r'\int_0^\infty\sin\theta e^{\cos\theta}d\theta',[r'\int_0^A\sin\theta e^{\cos\theta}d\theta=e-e^{\cos A}',r'A=2k\pi\Rightarrow0,\quad A=(2k+1)\pi\Rightarrow e-e^{-1}'],r'\text{Divergent}')
ma(39,r'\int_{-2}^3x^{-4}dx',[r'\text{Split at }x=0',r'\int_{-2}^{-\varepsilon}x^{-4}dx=\frac1{3\varepsilon^3}-\frac1{24}\to\infty',r'\int_\varepsilon^3x^{-4}dx=\frac1{3\varepsilon^3}-\frac1{81}\to\infty'],r'\text{Diverges to }+\infty')
ma(41,r'\int_0^9\frac{dx}{\sqrt[3]{x-1}}',[r'\text{Split at }x=1;\quad F(x)=\tfrac32|x-1|^{2/3}',r'\int_0^1f=-3/2,\quad\int_1^9f=\tfrac32\cdot8^{2/3}=6',r'\text{Both one-sided limits are finite}'],r'9/2')
ma(42,r'\int_0^5\frac{w}{w-2}dw',[r'\frac w{w-2}=1+\frac2{w-2},\quad F(w)=w+2\ln|w-2|',r'\int_0^{2-\varepsilon}f\to-\infty,\quad\int_{2+\varepsilon}^5f\to+\infty',r'\text{These cannot be added as convergent improper integrals}'],r'\text{Divergent}')
ma(44,r'\int_0^4\frac{dx}{x^2-x-2}',[r'\frac1{(x-2)(x+1)}=\frac13\left(\frac1{x-2}-\frac1{x+1}\right)',r'F(x)=\tfrac13\ln\left|\frac{x-2}{x+1}\right|',r'\int_0^{2-\varepsilon}f\to-\infty,\quad\int_{2+\varepsilon}^4f\to+\infty'],r'\text{Divergent}')
b.save();print('7.8 authored',len(b.E))
regions=[(49,r'x\ge1,\ 0\le y\le e^{-x}',r'A=\int_1^\infty e^{-x}dx=[-e^{-x}]_1^\infty=e^{-1}',r'e^{-1}',1,7,exp(-x)),(50,r'x\le0,\ 0\le y\le e^x',r'A=\int_{-\infty}^0e^xdx=[e^x]_{-\infty}^0=1','1',-7,0,exp(x)),(51,r'x\ge1,\ 0\le y\le1/(x^3+x)',r'\int_1^t\frac{dx}{x^3+x}=[\ln x-\tfrac12\ln(1+x^2)]_1^t\to\tfrac12\ln2',r'\tfrac12\ln2',1,6,1/(x**3+x)),(52,r'x\ge0,\ 0\le y\le xe^{-x}',r'A=\int_0^\infty xe^{-x}dx=[-(x+1)e^{-x}]_0^\infty=1','1',0,9,x*exp(-x)),(53,r'0\le x<\pi/2,\ 0\le y\le\sec^2x',r'A=\lim_{t\to(\pi/2)^-}[\tan x]_0^t=\infty',r'\infty',0,R(14,10),s.sec(x)**2),(54,r'-2<x\le0,\ 0\le y\le1/\sqrt{x+2}',r'A=\lim_{a\to-2^+}[2\sqrt{x+2}]_a^0=2\sqrt2',r'2\sqrt2',-R(199,100),0,1/sq(x+2))]
for n,desc,calc,val,a,c,f in regions:
 add(n,(M(r'S=\{(x,y):'+desc+r'\}')+'영역을 스케치하고 유한하면 넓이를 구하라.',M(r'S=\{(x,y):'+desc+r'\}')+'Sketch the region and find its area if finite.'),fs(r'A=\int_{\text{x-range}}\text{upper boundary}\,dx',calc),same(M('A='+val)))
 area_svg(b,n,[(s.sympify(a),s.sympify(c),f,s.Integer(0))],x,f'7.8.{n} Visible portion of improper region');b.E[n]['figure']['caption']=pair('무한구간 또는 수직점근선 부근을 잘라 표시한 영역이다. 전체 넓이는 해설의 극한으로 계산한다.','The plot truncates an infinite interval or a vertical asymptote. The full area is computed by the stated limits.');b.save()
ts=[2,5,10,100,1000,10000];F55=lambda z:mp.si(2*z)+(mp.cos(2*z)-1)/(2*z);vals55=[F55(mp.mpf(z))-F55(1)for z in ts]
add(55,(M(r'g(x)=\sin^2x/x^2')+'(a)∫₁ᵗg를 t=2,5,10,100,1000,10000에서 표로 만들고 수렴을 추측하라. (b)1/x²와 비교하여 증명하라. (c)[1,10]에서 두 함수를 그려 설명하라.',M(r'g(x)=\sin^2x/x^2')+'(a)Tabulate ∫₁ᵗg for t=2,5,10,100,1000,10000 and conjecture convergence.(b)Prove using comparison with1/x².(c)Graph both on[1,10] and interpret.'),fs(r'\begin{array}{r|r}t&\int_1^tg\\\hline'+r'\\'.join(str(z)+'&'+f'{float(v):.10f}'for z,v in zip(ts,vals55))+r'\end{array}',r'0\le g(x)\le1/x^2,\quad\int_1^\infty x^{-2}dx=1')+[('g 아래 넓이는 넓이1인 상한 곡선 아래에 들어간다. 따라서 수치표의 안정화는 비교정리로 엄밀하게 뒷받침된다.','The area under g lies below an upper curve of total area1. The comparison theorem rigorously supports the stabilization in the table.')],('수렴한다. 표의 값은 약0.6735에 접근한다.','Convergent; the table approaches approximately0.6735.'),parts=list('abc'))
plots(b,55,[('7.8.55 Integrable upper bound',1,10,0,1,[('sin²(x)/x²',lambda x:math.sin(x)**2/x**2),('1/x²',lambda x:1/x**2)])])
ts56=[5,10,100,1000,10000];F56=lambda z:2*mp.sqrt(z)+2*mp.log(mp.sqrt(z)-1)
add(56,(M(r'g(x)=1/(\sqrt x-1)')+'(a)∫₂ᵗg를 t=5,10,100,1000,10000에서 계산하여 추측하라. (b)1/√x와 비교하여 증명하라. (c)[2,20]에서 둘을 그려 설명하라.',M(r'g(x)=1/(\sqrt x-1)')+'(a)Evaluate ∫₂ᵗg for t=5,10,100,1000,10000 and conjecture convergence.(b)Compare with1/√x.(c)Graph both on[2,20] and interpret.'),fs(r'u=\sqrt x\Rightarrow\int\frac{dx}{\sqrt x-1}=2\sqrt x+2\ln(\sqrt x-1)',r'\begin{array}{r|r}t&\int_2^tg\\\hline'+r'\\'.join(str(z)+'&'+f'{float(F56(z)-F56(2)):.8f}'for z in ts56)+r'\end{array}',r'g(x)>1/\sqrt x,\quad\int_2^\infty x^{-1/2}dx=\infty'),same(M(r'\text{Diverges to }+\infty')),parts=list('abc'))
plots(b,56,[('7.8.56 Divergent lower bound',2,20,0,2.6,[('1/(sqrt(x)-1)',lambda x:1/(math.sqrt(x)-1)),('1/sqrt(x)',lambda x:1/math.sqrt(x))])])
comp=[(57,r'\int_0^\infty\frac{x}{x^3+1}dx',[r'0\le x/(x^3+1)\le1/x^2\quad(x\ge1)',r'\int_1^\infty x^{-2}dx=1;\quad f\text{ is continuous on }[0,1]'],'Convergent'),(58,r'\int_1^\infty\frac{1+\sin^2x}{\sqrt x}dx',[r'\frac{1+\sin^2x}{\sqrt x}\ge x^{-1/2}',r'\int_1^\infty x^{-1/2}dx=\infty'],'Divergent'),(59,r'\int_2^\infty\frac{dx}{x-\ln x}',[r'0<x-\ln x<x\quad(x\ge2)',r'\frac1{x-\ln x}>\frac1x,\quad\int_2^\infty dx/x=\infty'],'Divergent'),(60,r'\int_0^\infty\frac{\arctan x}{2+e^x}dx',[r'0\le\frac{\arctan x}{2+e^x}\le\frac\pi2e^{-x}',r'\int_0^\infty(\pi/2)e^{-x}dx=\pi/2'],'Convergent'),(61,r'\int_1^\infty\frac{x+1}{\sqrt{x^4-x}}dx',[r'0<\sqrt{x^4-x}<x^2,\quad\frac{x+1}{\sqrt{x^4-x}}>\frac1x\quad(x>1)',r'\int_2^\infty dx/x=\infty\Rightarrow\text{tail already diverges}'],'Divergent'),(62,r'\int_1^\infty\frac{2+\cos x}{\sqrt{x^4+x^2}}dx',[r'0\le\frac{2+\cos x}{\sqrt{x^4+x^2}}\le\frac3{x^2}',r'\int_1^\infty3x^{-2}dx=3'],'Convergent'),(63,r'\int_0^1\frac{\sec^2x}{x\sqrt x}dx',[r'\sec^2x\ge1\Rightarrow\frac{\sec^2x}{x\sqrt x}\ge x^{-3/2}',r'\int_0^1x^{-3/2}dx=\infty'],'Divergent'),(64,r'\int_0^\pi\frac{\sin^2x}{\sqrt x}dx',[r'0\le\frac{\sin^2x}{\sqrt x}\le x^{-1/2}',r'\int_0^\pi x^{-1/2}dx=2\sqrt\pi'],'Convergent')]
for n,eq,st,ans in comp:ma(n,eq,st,r'\text{'+ans+'}',('양의 비교함수에 대한 부등식과 비교 적분의 수렴 조건을 확인했다.','Verified positive comparison inequalities and convergence conditions for the comparison integrals.'))
ma(65,r'\int_0^\infty x^{-2}dx',[r'\int_0^1x^{-2}dx=\lim_{a\to0^+}(1/a-1)=\infty',r'\int_1^\infty x^{-2}dx=1',r'\text{The lower endpoint prevents convergence}'],r'\text{Diverges to }+\infty')
ma(66,r'\int_0^\infty x^{-1/2}dx',[r'\int_0^1x^{-1/2}dx=2',r'\int_1^Ax^{-1/2}dx=2(\sqrt A-1)\to\infty',r'\text{The infinite tail prevents convergence}'],r'\text{Diverges to }+\infty')
ma(67,r'\int_0^\infty\frac{dx}{\sqrt x(1+x)}',[r'u=\sqrt x,\quad dx=2u\,du',r'\int\frac{dx}{\sqrt x(1+x)}=2\arctan\sqrt x',r'\lim_{a\to0^+}2\arctan\sqrt a=0,\quad\lim_{A\to\infty}2\arctan\sqrt A=\pi'],r'\pi')
ma(68,r'\int_2^\infty\frac{dx}{x\sqrt{x^2-4}}',[r'x=2\sec\theta,\quad0<\theta<\pi/2',r'\frac{dx}{x\sqrt{x^2-4}}=\tfrac12d\theta',r'\int_2^\infty\frac{dx}{x\sqrt{x^2-4}}=\tfrac12[\theta]_0^{\pi/2}'],r'\pi/4')
ma(69,r'\int_0^1x^{-p}dx',[r'p\ne1:\quad\int_a^1x^{-p}dx=\frac{1-a^{1-p}}{1-p}',r'a^{1-p}\to0\iff p<1;\quad p=1:\ -\ln a\to\infty'],r'p<1:\quad I=\frac1{1-p};\qquad p\ge1:\text{ divergent}')
ma(70,r'\int_e^\infty\frac{dx}{x(\ln x)^p}',[r'u=\ln x,\quad du=dx/x\Rightarrow I=\int_1^\infty u^{-p}du',r'p>1:\quad I=[u^{1-p}/(1-p)]_1^\infty=1/(p-1)',r'p\le1:\quad\text{the p-integral diverges}'],r'p>1:\quad I=\frac1{p-1};\qquad p\le1:\text{ divergent}')
ma(71,r'\int_0^1x^p\ln xdx',[r'u=-\ln x\Rightarrow I=-\int_0^\infty u e^{-(p+1)u}du',r'p>-1:\quad\int_0^\infty ue^{-au}du=1/a^2\quad(a=p+1>0)',r'p=-1:\ -\int_0^\infty udu=-\infty;\quad p<-1:\text{ exponential growth}'],r'p>-1:\quad I=-\frac1{(p+1)^2};\qquad p\le-1:\text{ divergent}')
ma(72,r'I_n=\int_0^\infty x^ne^{-x}dx;\quad n=0,1,2,3\text{ and general integer }n',[r'(a)\quad I_0=1,\ I_1=1,\ I_2=2,\ I_3=6',r'(b)\quad I_n=n!',r'(c)\quad\int_0^A x^ne^{-x}dx=[-x^ne^{-x}]_0^A+n\int_0^Ax^{n-1}e^{-x}dx',r'A^ne^{-A}\to0\Rightarrow I_n=nI_{n-1};\quad I_0=1\Rightarrow I_n=n!'],r'I_n=n!',parts=list('abc'))
ma(73,r'\operatorname{PV}\int_{-\infty}^\infty xdx=\lim_{A\to\infty}\int_{-A}^Axdx',[r'\int_{-\infty}^0xdx=-\infty,\quad\int_0^\infty xdx=+\infty',r'\int_{-A}^Axdx=[x^2/2]_{-A}^A=0',r'\text{The ordinary integral requires both one-sided integrals to converge}'],r'\text{Ordinary integral diverges; principal value}=0')
ma(74,r'\bar v=\frac4{\sqrt\pi}\left(\frac M{2RT}\right)^{3/2}\int_0^\infty v^3e^{-Mv^2/(2RT)}dv',[r'a=M/(2RT)>0,\quad u=av^2,\quad v^3dv=u\,du/(2a^2)',r'\int_0^\infty v^3e^{-av^2}dv=\frac1{2a^2}\int_0^\infty ue^{-u}du=\frac1{2a^2}',r'\bar v=\frac{2}{\sqrt{\pi a}}'],r'\bar v=\sqrt{\frac{8RT}{\pi M}}')
ma(75,r'\mathcal R=\{(x,y):x\ge1,\ 0\le y\le1/x\};\quad\text{rotate about x-axis}',[r'A=\int_1^\infty\frac{dx}x=\infty',r'V=\pi\int_1^\infty\frac{dx}{x^2}=\pi[-1/x]_1^\infty'],r'V=\pi\quad\text{although planar area is infinite}')
W=mp.mpf('6.67e-11')*mp.mpf('5.98e24')*1000/mp.mpf('6.37e6')
ma(76,r'\text{Earth escape work for mass }m=1000\ \mathrm{kg}',[r'G=6.67\cdot10^{-11},\ M=5.98\cdot10^{24}\ \mathrm{kg},\ R=6.37\cdot10^6\ \mathrm m',r'W=\int_R^\infty GMm/r^2\,dr=GMm/R',r'W=\frac{(6.67\cdot10^{-11})(5.98\cdot10^{24})(1000)}{6.37\cdot10^6}'],r'W\approx'+f'{float(W):.6e}'.replace('e+',r'\times10^{')+'}'+r'\ \mathrm J')
ma(77,r'\text{Escape speed for rocket mass }m\text{ from planet mass }M\text{ and radius }R',[r'W=\int_R^\infty\frac{GMm}{r^2}dr=GMm/R',r'\tfrac12mv_0^2=W\Rightarrow v_0^2=2GM/R',r'\text{Rocket mass }m\text{ cancels}'],r'v_0=\sqrt{2GM/R}')
ma(78,r'y(s)=\int_s^R\frac{2r\rho(r)}{\sqrt{r^2-s^2}}dr,\quad\rho(r)=\tfrac12(R-r)^2',[r'y(s)=\int_s^R\frac{r(R-r)^2}{\sqrt{r^2-s^2}}dr',r'u=\sqrt{r^2-s^2},\quad r\,dr/\sqrt{r^2-s^2}=du',r'q=\sqrt{R^2-s^2},\quad y(s)=\int_0^q[R^2+s^2+u^2-2R\sqrt{u^2+s^2}]du',r'\int\sqrt{u^2+s^2}du=\tfrac12[u\sqrt{u^2+s^2}+s^2\ln(u+\sqrt{u^2+s^2})]',r'y(s)=s^2q+q^3/3-Rs^2\ln((R+q)/s)\quad(0<s<R)',r'y(0)=\int_0^R(R-r)^2dr=R^3/3,\quad y(R)=0'],r'y(s)=\frac{R^2+2s^2}{3}\sqrt{R^2-s^2}-Rs^2\ln\frac{R+\sqrt{R^2-s^2}}s;\quad y(0)=R^3/3,\ y(R)=0',('원문의 실제 밀도 기호 x(r)를 ρ(r)로 바꿔 변수 혼동을 피했다. 치환 후 적분을 독립 수치구적으로 확인했다.','Renamed the source density x(r) as ρ(r) to avoid variable ambiguity; independently checked the transformed integral numerically.'))
add(79,('전구 수명 목표가 약700시간이고 F(t)는 t시간 전에 고장난 비율이다. (a)가능한 누적분포를 스케치하라. (b)r=F′의 뜻을 설명하라. (c)∫₀∞r을 구하고 이유를 쓰라.','Bulbs are intended to last about700hours; F(t) is the fraction failing before time t.(a)Sketch a possible cumulative distribution.(b)Interpret r=F′.(c)Find ∫₀∞r and explain.'),[('F는0에서 시작해 증가하며1로 접근한다. 한 가능한 모형은 F(t)=1−exp[−(t/700)⁶]이다. 이는 예시이며 자료로 정해진 유일한 분포가 아니다.','F starts at0, increases, and tends to1. One illustrative model is F(t)=1−exp[−(t/700)⁶]; this is not a uniquely determined distribution.'),('r(t)는 t 부근의 단위 시간당 고장 비율 밀도이다. 짧은 Δt 동안 약 r(t)Δt가 고장난다.','r(t) is the failure-fraction density per unit time near t; approximately r(t)Δt fail in a short interval Δt.')]+fs(r'\int_0^\infty r(t)dt=\lim_{A\to\infty}[F(A)-F(0)]=1'),('r은 고장 시점의 확률밀도이고 전체 적분은1이다.','r is the failure-time density; its integral is1.'),parts=list('abc'))
plots(b,79,[('7.8.79 One possible bulb-life CDF',0,1200,0,1.05,[('F(t)=1-exp(-(t/700)^6)',lambda t:1-math.exp(-(t/700)**6))])])
ma(80,r'M=-k\int_0^\infty te^{kt}dt,\quad k=-0.000121\ \mathrm{yr}^{-1}',[r'k<0:\quad\int_0^\infty te^{kt}dt=[e^{kt}(t/k-1/k^2)]_0^\infty=1/k^2',r'M=-1/k=1/0.000121'],r'M\approx8264.462810\ \mathrm{years}')
ma(81,r'\gamma=\int_0^\infty\frac{cN(1-e^{-kt})}{k}e^{-\lambda t}dt,\quad c,k,\lambda>0',[r'\gamma=\frac{cN}k\left(\int_0^\infty e^{-\lambda t}dt-\int_0^\infty e^{-(k+\lambda)t}dt\right)',r'=\frac{cN}k\left(\frac1\lambda-\frac1{k+\lambda}\right)'],r'\gamma=\frac{cN}{\lambda(k+\lambda)}')
add(82,(M(r'u(t)=\frac rV C_0e^{-rt/V},\quad r,V>0')+'배출률의 ∫₀∞u(t)dt를 구하고 해석하라. r은 mL/min, V는 mL, C₀는 초기 요소 mg이다.',M(r'u(t)=\frac rV C_0e^{-rt/V},\quad r,V>0')+'Evaluate and interpret ∫₀∞u(t)dt. Here r is in mL/min, V in mL, and C₀ is initial urea in mg.'),fs(r'\int_0^Au(t)dt=C_0(1-e^{-rA/V})',r'\lim_{A\to\infty}C_0(1-e^{-rA/V})=C_0')+[('이 모형에서 무한 시간 동안 제거되는 총량은 초기 요소량 C₀이다.','In this model the total removed over unlimited time equals the initial amount C₀.')],same(M(r'C_0\ \mathrm{mg}')))
ma(83,r'\int_a^\infty\frac{dx}{x^2+1}<0.001',[r'\int_a^\infty\frac{dx}{x^2+1}=\pi/2-\arctan a',r'\arctan a>\pi/2-0.001\iff a>\cot(0.001)',r'\cot(0.001)\approx999.999666667'],r'a>\cot(0.001);\quad a=1000\text{ suffices}')
f=lambda z:mp.exp(-z*z);h=mp.mpf('.5');S=h/3*(f(0)+f(4)+4*sum(f(h*j)for j in[1,3,5,7])+2*sum(f(h*j)for j in[2,4,6]))
ma(84,r'I=\int_0^\infty e^{-x^2}dx=\int_0^4e^{-x^2}dx+\int_4^\infty e^{-x^2}dx',[r'h=1/2,\quad S_8=\frac16[1+e^{-16}+4(e^{-1/4}+e^{-9/4}+e^{-25/4}+e^{-49/4})+2(e^{-1}+e^{-4}+e^{-9})]',r'S_8\approx'+f'{float(S):.10f}',r'x\ge4\Rightarrow x^2\ge4x\Rightarrow0\le\int_4^\infty e^{-x^2}dx\le\int_4^\infty e^{-4x}dx=e^{-16}/4<10^{-7}'],r'I\approx'+f'{float(S):.10f}',('꼬리오차의10⁻⁷ 상한은 Simpson 구간 오차를 포함하지 않는다. 요청한 n=8 근삿값이며 전체 오차가10⁻⁷이라는 뜻은 아니다.','The10⁻⁷ tail bound does not include Simpson’s finite-interval error. This is the requested n=8 estimate, not a claim of10⁻⁷ total accuracy.'))
ma(85,r'F(s)=\int_0^\infty f(t)e^{-st}dt;\quad(a)f=1,\ (b)f=e^t,\ (c)f=t',[r'(a)\quad F(s)=[-e^{-st}/s]_0^\infty=1/s\quad(s>0)',r'(b)\quad F(s)=\int_0^\infty e^{-(s-1)t}dt=1/(s-1)\quad(s>1)',r'(c)\quad F(s)=[-e^{-st}(t/s+1/s^2)]_0^\infty=1/s^2\quad(s>0)',r'\text{At or below each threshold the nonnegative integral diverges}'],r'(a)1/s,\ s>0;\quad(b)1/(s-1),\ s>1;\quad(c)1/s^2,\ s>0',parts=list('abc'))
ma(86,r'0\le f(t)\le Me^{at},\quad t\ge0:\quad F(s)\text{ exists for }s>a',[r'0\le f(t)e^{-st}\le Me^{-(s-a)t}',r'\int_0^\infty Me^{-(s-a)t}dt=M/(s-a)<\infty\quad(s>a)',r'\text{Comparison proves convergence}'],r'F(s)\text{ exists for every }s>a')
ma(87,r'0\le f\le Me^{at},\quad0\le f^\prime\le Ke^{at},\quad G=\mathcal L(f^\prime),\ F=\mathcal L(f)',[r'\int_0^Af^\prime(t)e^{-st}dt=f(A)e^{-sA}-f(0)+s\int_0^Af(t)e^{-st}dt',r'0\le f(A)e^{-sA}\le Me^{-(s-a)A}\to0\quad(s>a)',r'\text{Both transforms converge by comparison with }e^{-(s-a)t}',r'A\to\infty:\quad G(s)=sF(s)-f(0)'],r'G(s)=sF(s)-f(0),\quad s>a')
ma(88,r'\int_{-\infty}^{\infty}f\text{ converges; show splitting at }a\text{ or }b\text{ gives the same sum}',[r'\text{Assume }a<b:\quad\int_{-\infty}^bf=\int_{-\infty}^af+\int_a^bf',r'\int_a^\infty f=\int_a^bf+\int_b^\infty f',r'\text{Substitute the second identity into the sum split at }a',r'\int_{-\infty}^af+\int_a^\infty f=\int_{-\infty}^bf+\int_b^\infty f',r'\text{The case }b<a\text{ follows by exchanging the labels}'],r'\text{The value is independent of the finite splitting point}')
ma(89,r'\int_0^\infty x^2e^{-x^2}dx=\tfrac12\int_0^\infty e^{-x^2}dx',[r'u=x,\quad dv=xe^{-x^2}dx\Rightarrow v=-\tfrac12e^{-x^2}',r'\int_0^Ax^2e^{-x^2}dx=[-\tfrac12xe^{-x^2}]_0^A+\tfrac12\int_0^Ae^{-x^2}dx',r'Ae^{-A^2}\to0;\quad\int_0^\infty e^{-x^2}dx\text{ converges by comparison}'],r'\int_0^\infty x^2e^{-x^2}dx=\tfrac12\int_0^\infty e^{-x^2}dx')
add(90,(M(r'\int_0^\infty e^{-x^2}dx=\int_0^1\sqrt{-\ln y}\,dy')+'두 적분을 같은 영역의 넓이로 해석하여 증명하라.',M(r'\int_0^\infty e^{-x^2}dx=\int_0^1\sqrt{-\ln y}\,dy')+'Prove by interpreting both as the area of one region.'),fs(r'S=\{(x,y):x\ge0,\ 0<y\le e^{-x^2}\}',r'y\le e^{-x^2}\iff\ln y\le-x^2\iff0\le x\le\sqrt{-\ln y}',r'\text{Vertical strips: }A=\int_0^\infty e^{-x^2}dx',r'\text{Horizontal strips: }A=\int_0^1\sqrt{-\ln y}\,dy'),('같은 유한 넓이를 수직 띠와 수평 띠로 계산했으므로 같다.','Vertical and horizontal slicing compute the same finite area.'))
area_svg(b,90,[(s.Integer(0),s.Integer(3),exp(-x*x),s.Integer(0))],x,'7.8.90 Same area, two slicing directions');b.save()
ma(91,r'\int_0^\infty\left(\frac1{\sqrt{x^2+4}}-\frac C{x+2}\right)dx',[r'x\left(\frac1{\sqrt{x^2+4}}-\frac C{x+2}\right)\to1-C',r'C\ne1:\quad\text{nonzero harmonic tail causes divergence}',r'C=1:\quad F(x)=\ln(x+\sqrt{x^2+4})-\ln(x+2)',r'F(0)=0,\quad\lim_{x\to\infty}F(x)=\ln2'],r'C=1,\quad I=\ln2')
ma(92,r'\int_0^\infty\left(\frac{x}{x^2+1}-\frac C{3x+1}\right)dx',[r'x\left(\frac{x}{x^2+1}-\frac C{3x+1}\right)\to1-C/3',r'\text{Convergence requires }C=3',r'C=3:\quad F(x)=\tfrac12\ln(x^2+1)-\ln(3x+1)',r'F(0)=0,\quad\lim_{x\to\infty}F(x)=-\ln3'],r'C=3,\quad I=-\ln3')
ma(93,r'f\text{ continuous on }[0,\infty),\quad\lim_{x\to\infty}f(x)=1',[r'\exists A:\quad|f(x)-1|<1/2\quad(x\ge A)',r'f(x)>1/2\Rightarrow\int_A^Bf(x)dx>(B-A)/2\to\infty',r'\int_0^Af(x)dx\text{ is finite by continuity}'],r'\int_0^\infty f(x)dx\text{ cannot converge; it diverges to }+\infty')
ma(94,r'a>-1,\quad b>a+1:\quad\int_0^\infty\frac{x^a}{1+x^b}dx\text{ converges}',[r'b>a+1>0',r'0<x\le1:\quad0\le\frac{x^a}{1+x^b}\le x^a,\quad\int_0^1x^adx=1/(a+1)',r'x\ge1:\quad0\le\frac{x^a}{1+x^b}\le x^{a-b},\quad a-b<-1',r'\int_1^\infty x^{a-b}dx=1/(b-a-1)<\infty'],r'\text{Convergent by comparison at both endpoints}')
# Book serialization sorts exercise numbers and synchronizes scope.
(Path(__file__).parent/'calc1-s7-8-symbolic-results.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2)+'\n')
b.save();print('7.8 COMPLETE',len(b.E))
