from calc1_inverse_helpers import *
x,y=s.symbols('x y',real=True);P=s.pi;R=s.Rational;b=CalcBook('6.1',[418,419]);checks=[]
def add(n,st,steps,ans,check,parts=[]):
 b.add(n,418 if n<=21 else 419,('역함수와 미분','Inverse functions and derivatives'),st,steps,ans,parts=parts);b.verify(n,*check);b.save()
add(1,('(a)일대일 함수의 뜻을 설명하고,(b)그래프로 판별하는 기준을 말하라.','(a)Define a one-to-one function and(b)state its graphical test.'),fs(r'f(a)=f(b)\Rightarrow a=b')+[('서로 다른 입력이 같은 출력을 만들지 않는다. 따라서 각 수평선은 그래프와 많아야 한 번 만난다.','Distinct inputs cannot have the same output, so every horizontal line meets the graph at most once.')],('입력의 중복 없는 출력 대응이며 수평선 판별법을 만족한다.','Distinct inputs give distinct outputs; the graph passes the horizontal-line test.'),('수평선 y=k의 두 교점은 서로 다른 입력에서 같은 출력k를 갖는 것과 정확히 같다.','Two intersections with y=k are exactly two distinct inputs with the same output k.'),['a','b'])
add(2,('정의역A·치역B인 일대일 함수 f에 대해 (a)역함수의 정의·정의역·치역,(b)식 구하는 절차,(c)그래프 구하는 방법을 설명하라.','For one-to-one f with domain A and range B, explain(a)the inverse definition/domain/range,(b)how to obtain its formula,(c)how to obtain its graph.'),fs(r'f^{-1}(y)=x\Longleftrightarrow f(x)=y,\quad f^{-1}:B\to A')+[('y=f(x)를 x에 대해 풀고 변수 이름을 바꾼다. 가지는 원래 정의역을 보존하도록 선택한다.','Solve y=f(x) for x and rename variables, preserving the original domain when choosing branches.'),('점(x,y)를(y,x)로 바꾸므로 y=x에 대해 반사한다.','Swap(x,y) with(y,x), reflecting across y=x.')],('역함수는 출력에서 원래 입력을 되찾는다. 정의역B,치역A이고, 식을 풀거나 y=x 대칭을 사용한다.','The inverse recovers the original input from the output, with domain B and range A; solve algebraically or reflect across y=x.'),('f⁻¹∘f는A에서, f∘f⁻¹는B에서 각각 항등함수이다.','f⁻¹∘f is the identity on A, and f∘f⁻¹ is the identity on B.'),list('abc'))
for n,vals in[(3,[1.5,2,3.6,5.3,2.8,2]),(4,[1,1.9,2.8,3.5,3.1,2.9])]:
 yes=len(set(vals))==len(vals);why=('2번과6번 입력에서 출력2가 반복된다.','Outputs at inputs2 and6 both equal2.')if n==3 else('주어진 여섯 출력이 모두 서로 다르다. 증가 순서일 필요는 없다.','All six listed outputs are distinct; they need not occur in increasing order.')
 add(n,(M(r'x=1,2,3,4,5,6;\quad f(x)='+','.join(map(str,vals)))+'주어진 유한 함수가 일대일인지 판별하라.',M(r'x=1,2,3,4,5,6;\quad f(x)='+','.join(map(str,vals)))+'Determine whether this finite function is one-to-one.'),[why,('같은 값이 반복되는 출력이 있는지 비교한다.','Compare outputs for repetitions.')],('예.'if yes else'아니오.','Yes.'if yes else'No.'),('정의역의 모든 출력 쌍을 비교했다.','Compared all output pairs over the stated finite domain.'))
shapes={5:(lambda t:math.exp(-t*t)+.3,(-2,2),False,('왼쪽에서 증가하여 봉우리를 지난 뒤 감소하는 곡선','a curve increasing to a peak then decreasing')),6:(lambda t:math.exp(t)-2,(-1.5,1.5),True,('전체 표시 구간에서 엄격히 증가하는 곡선','a curve strictly increasing throughout its displayed interval')),7:(lambda t:math.exp(-t)-1,(-1,2),True,('전체 표시 구간에서 엄격히 감소하는 곡선','a curve strictly decreasing throughout its displayed interval')),8:(lambda t:t/(1+t*t),(-2.5,2.5),False,('왼쪽의 작은 극소와 오른쪽의 극대를 가지는 곡선','a curve with a small left local minimum and a right local maximum'))}
for n,(fn,(lo,hi),yes,description)in shapes.items():
 why=('각 수평선과 많아야 한 번 만나므로 서로 다른 입력의 출력이 다르다.','Each horizontal line meets at most once, giving distinct outputs for distinct inputs.')if yes else('극값 근처에서 같은 높이의 수평선이 두 번 이상 만나므로 출력이 반복된다.','A horizontal line near an extremum meets more than once, so an output repeats.')
 add(n,('원본은 '+description[0]+'이다. 일대일인지 판별하라.','The source shows '+description[1]+'. Determine whether it is one-to-one.'),[why,('수평선 판별법을 적용한다.','Apply the horizontal-line test.')],('예.'if yes else'아니오.','Yes.'if yes else'No.'),('원본 곡선의 증가·감소 구간을 시각 대조했다.','Visually checked the increasing/decreasing portions of the source graph.'))
 planeplot(b,n,points(fn,lo,hi),title=f'6.1.{n}  Horizontal-line behavior',caption=('원본의 증가·감소 및 수평선 판별 특성을 보존한 자체 개략도이다. 수치 식이 주어지지 않은 그림이다.','Original qualitative redraw preserving the source’s monotonicity and horizontal-line behavior; the source supplies no numerical formula.'));b.save()
classify={9:(r'f(x)=2x-3',True,('기울기2>0인 직선이므로 엄격히 증가한다.','A line of slope2>0 is strictly increasing.'),r'f(a)=f(b)\Rightarrow2a-3=2b-3\Rightarrow a=b'),10:(r'f(x)=x^4-16',False,('서로 다른 입력1,-1의 출력이 같다.','Distinct inputs1 and-1 have the same output.'),r'f(1)=f(-1)=-15'),11:(r'f(t)=t^3+4',True,('세제곱 함수는 실수 전체에서 엄격히 증가한다.','The cube function is strictly increasing on the real line.'),r'a^3+4=b^3+4\Rightarrow a=b'),12:(r'f(x)=\sqrt[3]x',True,('실수 세제곱근은 엄격히 증가한다.','The real cube-root function is strictly increasing.'),r'\sqrt[3]a=\sqrt[3]b\Rightarrow a=b'),13:(r'f(x)=1-\sin x',False,('주기성 때문에 같은 값이 반복된다.','Periodicity repeats output values.'),r'f(0)=f(\pi)=1'),14:(r'f(x)=x^4-1,\quad0\le x\le10',True,('비음수 구간에서는 네제곱이 엄격히 증가한다.','The fourth power is strictly increasing on the nonnegative interval.'),r'0\le a<b\Rightarrow a^4<b^4')}
for n,(eq,yes,why,formula)in classify.items():add(n,(M(eq)+'일대일인지 판별하라.',M(eq)+'Determine whether the function is one-to-one.'),[why]+fs(formula),('예.'if yes else'아니오.','Yes.'if yes else'No.'),('정의역을 반영한 단조성 또는 서로 다른 입력의 구체적 반례로 확인했다.','Checked using domain-specific monotonicity or an explicit repeated-output counterexample.'))
add(15,('축구공을 찬 뒤 시간t에 따른 높이 f(t)는 전체 비행에서 일대일인가?','Is the height f(t) of a kicked football one-to-one over the whole flight?'),[('공은 먼저 올라갔다가 내려오므로 같은 중간 높이를 서로 다른 두 시각에 지난다.','The ball rises then falls, passing an intermediate height at two different times.'),('그 높이의 수평선이 높이 그래프와 두 번 만난다.','A horizontal line at that height meets the height graph twice.')],('아니오.','No.'),('상승·하강 양쪽을 포함하는 전체 비행을 정의역으로 사용했다.','Used the entire flight, including ascent and descent, as the domain.'))
add(16,('나이t에 따른 사람의 키 f(t)는 일반적으로 일대일인가?','Is a person’s height f(t) as a function of age generally one-to-one?'),[('서로 다른 나이에 같은 키를 가질 수 있으며 성인기의 키는 일정하거나 반복될 수 있다.','The same height can occur at different ages, including repeated or unchanged adult heights.'),('한 키에서 원래 나이를 하나로 결정할 수 없다.','One height does not uniquely determine the original age.')],('일반적으로 아니다.','Generally no.'),('성장기 일부만으로 제한하지 않고 나이 전체를 고려했다.','Considered the full age range rather than only a strictly growing subinterval.'))
add(17,('일대일 f에 대해 (a)f(6)=17이면 f⁻¹(17),(b)f⁻¹(3)=2이면 f(2)를 구하라.','For one-to-one f, find(a)f⁻¹(17) if f(6)=17 and(b)f(2) if f⁻¹(3)=2.'),fs(r'f^{-1}(f(x))=x,\quad f(f^{-1}(y))=y',r'(a)\ f^{-1}(17)=6;\qquad(b)\ f(2)=3'),same('(a)6; (b)3.'),('역함수의 입력·출력 맞바꿈 정의를 두 방향으로 적용했다.','Applied the input/output reversal definition in both directions.'),['a','b'])
add(18,('f(x)=x⁵+x³+x일 때 f⁻¹(3)와 f(f⁻¹(2))를 구하라.','For f(x)=x⁵+x³+x, find f⁻¹(3) and f(f⁻¹(2)).'),fs(r'f\prime(x)=5x^4+3x^2+1>0,\quad f(1)=3',r'f^{-1}(3)=1,\quad f(f^{-1}(2))=2'),same(M(r'f^{-1}(3)=1,\quad f(f^{-1}(2))=2')),('함수가 엄격히 증가하고 실수 전체를 치역으로 가지므로 두 역함수 값이 정의된다.','Strict increase and full real range ensure both inverse expressions are defined.'))
add(19,('h(x)=x+√x일 때 h⁻¹(6)을 구하라.','For h(x)=x+√x, find h⁻¹(6).'),fs(r'u=\sqrt x\ge0,\quad u^2+u=6\Rightarrow(u+3)(u-2)=0',r'u=2\Rightarrow x=4'),same(M(r'h^{-1}(6)=4')),('h(4)=4+2=6이고 x≥0에서 엄격히 증가하므로 해가 유일하다.','h(4)=6 and strict increase on x≥0 makes the solution unique.'))
pts20=[(-3,-1),(-2,-.35),(-1.7,0),(-1,1),(0,2),(1,2.6),(2,2.9),(3,3)]
add(20,('원본 f는(-3,-1)에서(3,3)까지 엄격히 증가하며(0,2)를 지난다. x절편은약-1.7이다. (a)일대일 이유,(b)역함수 정의역·치역,(c)f⁻¹(2),(d)f⁻¹(0)를 구하라.','The source f increases strictly from(-3,-1) to(3,3), passes(0,2), and has x-intercept about-1.7. Give(a)the one-to-one reason,(b)inverse domain/range,(c)f⁻¹(2),(d)f⁻¹(0).'),[('엄격한 증가로 수평선 판별법을 통과한다. 원래 치역이 역함수 정의역으로, 원래 정의역이 역함수 치역으로 바뀐다.','Strict increase passes the horizontal-line test. Original range/domain become inverse domain/range.')]+fs(r'D_{f^{-1}}=[-1,3],\quad R_{f^{-1}}=[-3,3]',r'f^{-1}(2)=0,\quad f^{-1}(0)\approx-1.7'),same(M(r'D=[-1,3],\quad R=[-3,3];\quad f^{-1}(2)=0,\ f^{-1}(0)\approx-1.7')),('원본 격자의 끝점, y절편, x절편을 따로 시각 대조했다.','Separately checked endpoints and both intercepts on the source grid.'),list('abcd'))
planeplot(b,20,pts20,reflect=True,caption=('원본 격자에서 읽은 점들을 잇는 근사도와 좌표를 맞바꾼 역함수.','Approximate polyline through source-grid readings and its coordinate-swapped inverse.'));b.save()
add(21,('C=5(F-32)/9, F≥-459.67인 온도 변환의 역함수와 뜻,정의역을 구하라.','Find and interpret the inverse of C=5(F-32)/9 for F≥-459.67, including its domain.'),fs(r'9C/5=F-32\Rightarrow F(C)=9C/5+32',r'C_{min}=\frac59(-459.67-32)=-273.15')+[('섭씨 온도를 넣어 화씨 온도를 얻는 함수이다.','It takes a Celsius temperature and returns Fahrenheit.')],same(M(r'F(C)=9C/5+32,\quad C\ge-273.15')),('두 변환을 합성하면 원래 온도가 되고 경계 온도도 서로 대응한다.','Composing the conversions returns the original temperature, including the boundary value.'))
add(22,('모형 m=f(v)=m0/√(1-v²/c²),\\(0\\le v\\lt c\\)에서 m0>0은 정지질량이다. 역함수를 구하고 해석하라.','In the model m=f(v)=m0/√(1-v²/c²),\\(0\\le v\\lt c\\) with m0>0, find and interpret the inverse.'),fs(r'1-v^2/c^2=(m_0/m)^2',r'v=f^{-1}(m)=c\sqrt{1-(m_0/m)^2},\quad m\ge m_0')+[('주어진 상대론적 질량으로부터 비음수 속력을 구한다. 속력이라는 조건이 제곱근의 양의 가지를 정한다.','It recovers nonnegative speed from the model mass; the speed condition selects the nonnegative square-root branch.')],same(M(r'f^{-1}(m)=c\sqrt{1-(m_0/m)^2},\quad D=[m_0,\infty),\ R=[0,c)')),('m=m0이면 v=0이고 m→∞이면 v→c⁻이다.','At m=m0 speed is zero; as m→∞, speed tends to c from below.'))
print('6.1 first22',len(b.E))
realpow=lambda a,n:math.copysign(abs(a)**(1/n),a)
inverse_records={
23:(r'f(x)=5-4x',r'(5-x)/4',r'\mathbb R',r'\mathbb R',r'y=5-4x\Rightarrow x=(5-y)/4',lambda t:5-4*t,lambda t:(5-t)/4,[-2,0,2]),
24:(r'h(x)=(6-3x)/(5x+7)',r'(6-7x)/(5x+3)',r'\mathbb R\setminus\{-3/5\}',r'\mathbb R\setminus\{-7/5\}',r'y(5x+7)=6-3x\Rightarrow x(5y+3)=6-7y',lambda t:(6-3*t)/(5*t+7),lambda t:(6-7*t)/(5*t+3),[-3,0,2]),
25:(r'f(x)=1-x^2,\quad x\ge0',r'\sqrt{1-x}',r'(-\infty,1]',r'[0,\infty)',r'y=1-x^2\Rightarrow x=\sqrt{1-y}\quad(x\ge0)',lambda t:1-t*t,lambda t:math.sqrt(1-t),[0,1,3]),
26:(r'g(x)=x^2-2x,\quad x\ge1',r'1+\sqrt{x+1}',r'[-1,\infty)',r'[1,\infty)',r'y=(x-1)^2-1\Rightarrow x=1+\sqrt{y+1}',lambda t:t*t-2*t,lambda t:1+math.sqrt(t+1),[1,2,4]),
27:(r'g(x)=2+\sqrt{x+1}',r'(x-2)^2-1',r'[2,\infty)',r'[-1,\infty)',r'y-2=\sqrt{x+1}\Rightarrow x=(y-2)^2-1,\ y\ge2',lambda t:2+math.sqrt(t+1),lambda t:(t-2)**2-1,[-1,0,3]),
28:(r'f(x)=1+\sqrt{2+3x}',r'((x-1)^2-2)/3',r'[1,\infty)',r'[-2/3,\infty)',r'y-1=\sqrt{2+3x}\Rightarrow x=((y-1)^2-2)/3,\ y\ge1',lambda t:1+math.sqrt(2+3*t),lambda t:((t-1)**2-2)/3,[-2/3,0,3]),
29:(r'y=(2+\sqrt[3]x)^5',r'(\sqrt[5]x-2)^3',r'\mathbb R',r'\mathbb R',r'\sqrt[5]y=2+\sqrt[3]x\Rightarrow x=(\sqrt[5]y-2)^3',lambda t:(2+realpow(t,3))**5,lambda t:(realpow(t,5)-2)**3,[-27,-8,0,8]),
30:(r'y=(1-\sqrt x)/(1+\sqrt x)',r'((1-x)/(1+x))^2',r'(-1,1]',r'[0,\infty)',r'\sqrt x=(1-y)/(1+y)\Rightarrow x=((1-y)/(1+y))^2,\ -1<y\le1',lambda t:(1-math.sqrt(t))/(1+math.sqrt(t)),lambda t:((1-t)/(1+t))**2,[0,1,9]),
31:(r'f(x)=\sqrt{4x+3}',r'(x^2-3)/4',r'[0,\infty)',r'[-3/4,\infty)',r'y=\sqrt{4x+3}\Rightarrow x=(y^2-3)/4,\ y\ge0',lambda t:math.sqrt(4*t+3),lambda t:(t*t-3)/4,[-.75,0,2]),
32:(r'f(x)=2-x^4,\quad x\ge0',r'\sqrt[4]{2-x}',r'(-\infty,2]',r'[0,\infty)',r'y=2-x^4\Rightarrow x=\sqrt[4]{2-y}\quad(x\ge0)',lambda t:2-t**4,lambda t:(2-t)**.25,[0,1,2])}
for n,(eq,inv,dom,ran,algebra,f,fi,samples)in inverse_records.items():
 for u in samples:assert abs(fi(f(u))-u)<1e-9,(n,u,fi(f(u)))
 steps=fs(algebra,r'f^{-1}(x)='+inv,r'D_{f^{-1}}='+dom+r',\quad R_{f^{-1}}='+ran)+[('원래 정의역에 들어가는 가지를 선택하고 입력·출력의 범위를 맞바꾼다.','Choose the branch lying in the original domain, then exchange input/output ranges.')]
 task=('역함수 식을 구하라.','Find the inverse formula.')if n<31 else('역함수 식을 구하고 f,역함수,y=x를 같은 좌표에 그려라.','Find the inverse and plot f,its inverse,and y=x together.')
 add(n,(M(eq)+task[0],M(eq)+task[1]),steps,same(M(r'f^{-1}(x)='+inv+r',\quad D='+dom+r',\ R='+ran)),('방정식을 되풀어 얻은 가지의 정의역을 확인하고 여러 허용 입력에서 역합성을 검산했다.','Checked the solved branch’s domain and verified inverse composition at multiple admissible inputs.'))
 if n>=31:planeplot(b,n,points(f,-.75,3)if n==31 else points(f,0,1.6),reflect=True);b.save()
pts33=[(-1,-2),(1,-1),(2,2),(3,3)];pts34=[(0,1),(1,.7),(2,0),(3,-.7),(4,-1)]
add(33,('원본의 꺾은선은(-1,-2),(1,-1),(2,2),(3,3)을 순서대로 잇는다. 역함수 그래프를 그려라.','The source polyline connects(-1,-2),(1,-1),(2,2),(3,3). Sketch its inverse.'),[('각 꼭짓점의 x,y좌표를 서로 바꾼 뒤 대응하는 선분을 연결한다.','Swap the coordinates of every vertex, then connect corresponding segments.')]+fs(r'(-2,-1),\ (-1,1),\ (2,2),\ (3,3)'),('(-2,-1),(-1,1),(2,2),(3,3)을 잇는 꺾은선.','The polyline through(-2,-1),(-1,1),(2,2),(3,3).'),('한 번 더 반사하면 원래 네 꼭짓점으로 돌아온다.','Reflecting once more returns all four original vertices.'))
planeplot(b,33,pts33,reflect=True);b.save()
add(34,('원본 곡선은(0,1)에서 시작해(2,0)를 지나며 오른쪽 아래로 엄격히 감소한다. 역함수 그래프를 그려라.','The source curve starts at(0,1),passes(2,0),and decreases strictly to the right. Sketch its inverse.'),fs(r'(0,1)\mapsto(1,0),\quad(2,0)\mapsto(0,2)')+[('y=x에 반사한 감소 곡선이다. 원래 완만한 접선은 역함수에서 가파르게 보인다.','It is the decreasing reflection across y=x; shallow original tangents become steep inverse tangents.')],('(1,0),(0,2)를 지나는 감소 곡선으로 y=x 대칭이다.','A decreasing reflected curve through(1,0) and(0,2).'),('원본의 표시된 두 점과 전체 단조 방향을 좌표 교환으로 확인했다.','Checked the two labeled source points and overall monotonic direction by swapping coordinates.'))
planeplot(b,34,pts34,reflect=True,caption=('표시된 점을 보존한 원본 곡선의 개략도와 반사도이다. 중간 점은 형태를 나타내는 근사값이다.','Qualitative redraw and reflection preserving the labeled points; intermediate samples approximate the shape.'));b.save()
add(35,('f(x)=√(1-x²),0≤x≤1이다. (a)역함수와 f의 관계,(b)그래프의 종류로 그 이유를 설명하라.','For f(x)=√(1-x²),0≤x≤1,find(a)the inverse and its relation to f,and(b)explain via the graph.'),fs(r'y^2=1-x^2\Rightarrow x=\sqrt{1-y^2}\quad(x,y\ge0)',r'f^{-1}(x)=\sqrt{1-x^2}=f(x),\quad0\le x\le1')+[('그래프는 단위원의 제1사분면 사분원이며 x,y를 바꿔도 같은 원호이다.','The graph is the first-quadrant quarter of the unit circle,unchanged by swapping x and y.')],same(M(r'f^{-1}=f,\quad D=R=[0,1]')),('합성하면 √(1-(√(1-x²))²)=x가 되어 비음수 정의역에서 항등함수이다.','Composition gives √(1-(√(1-x²))²)=x on the nonnegative domain.'),['a','b'])
planeplot(b,35,points(lambda t:math.sqrt(max(0,1-t*t)),0,1),reflect=True);b.save()
add(36,('g(x)=∛(1-x³)이다. (a)역함수와g의 관계,(b)그래프가 이 관계를 갖는 이유를 설명하라.','For g(x)=∛(1-x³),find(a)the inverse and its relation to g,and(b)explain the graphical symmetry.'),fs(r'y^3=1-x^3\Longleftrightarrow x^3+y^3=1',r'x=\sqrt[3]{1-y^3}\Rightarrow g^{-1}=g')+[('실수 세제곱근을 사용한다. 식 x³+y³=1이 x,y 교환에 불변이므로 그래프가 y=x 대칭이다.','Use real cube roots. The equation x³+y³=1 is unchanged by swapping coordinates,so the graph is symmetric about y=x.')],same(M(r'g^{-1}(x)=\sqrt[3]{1-x^3}=g(x),\quad D=R=\mathbb R')),('g(g(x))의 세제곱이 x³이고 실수 세제곱은 일대일이므로 합성은x이다.','The cube of g(g(x)) is x³; uniqueness of real cube roots gives composition x.'),['a','b'])
planeplot(b,36,points(lambda t:realpow(1-t**3,3),-2,9**(1/3)),reflect=True);b.save()
full={
37:(x**3,8,2,r'\sqrt[3]x',r'\mathbb R',r'\mathbb R',r'\frac1{3(\sqrt[3]x)^2}\quad(x\ne0)',('세제곱은 실수 전체에서 엄격히 증가한다.','The cube function is strictly increasing on the real line.'),lambda t:t**3,-2,2),
38:(s.sqrt(x-2),2,6,r'x^2+2',r'[0,\infty)',r'[2,\infty)',r'2x',('x≥2에서 제곱근이 엄격히 증가한다.','The square root is strictly increasing for x≥2.'),lambda t:math.sqrt(t-2),2,6),
39:(9-x*x,8,1,r'\sqrt{9-x}',r'[0,9]',r'[0,3]',r'-\frac1{2\sqrt{9-x}}',('0≤x≤3에서9-x²는 엄격히 감소한다.','9-x² is strictly decreasing on0≤x≤3.'),lambda t:9-t*t,0,3),
40:(1/(x-1),2,R(3,2),r'1+1/x',r'(0,\infty)',r'(1,\infty)',r'-1/x^2',('x>1에서 f′=-1/(x-1)²<0이므로 엄격히 감소한다.','On x>1,f′=-1/(x-1)²<0,so f is strictly decreasing.'),lambda t:1/(t-1),1.2,6)}
for n,(f,a,u,fi,dom,ran,fid,why,fn,lo,hi)in full.items():
 derivative=s.diff(f,x);value=s.simplify(1/derivative.subs(x,u));assert s.simplify(f.subs(x,u)-a)==0
 inverse_expr={37:x**R(1,3),38:x*x+2,39:s.sqrt(9-x),40:1+1/x}[n];v2=s.diff(inverse_expr,x).subs(x,a);assert s.simplify(value-v2)==0;checks.append([n,str(value)])
 eq='f(x)='+tex(f)+r',\quad a='+str(a)
 if n==39:eq+=r',\ 0\le x\le3'
 if n==40:eq+=r',\ x>1'
 steps=[('(a) '+why[0],'(a) '+why[1])]+fs(r'(b)\ f('+tex(u)+')='+str(a)+r'\Rightarrow(f^{-1})\prime('+str(a)+r')=\frac1{f\prime('+tex(u)+')}='+tex(value),r'(c)\ f^{-1}(x)='+fi+r',\quad D='+dom+r',\ R='+ran,r'(d)\ (f^{-1})\prime(x)='+fid,r'(f^{-1})\prime('+str(a)+')='+tex(v2))+[('(e) 좌표를 바꾼 그래프를 원래 그래프와 같은 축척에 표시한다.','(e) Plot the coordinate-swapped graph on the same scale as the original.')]
 add(n,(M(eq)+'(a)일대일성,(b)역함수 미분 공식,(c)역함수 식·정의역·치역,(d)직접 미분 검산,(e)두 그래프를 구하라.',M(eq)+'Give(a)one-to-one justification,(b)inverse derivative via the theorem,(c)inverse formula/domain/range,(d)direct derivative check,(e)both graphs.'),steps,same(M(r'f^{-1}(x)='+fi+r',\quad D='+dom+r',\ R='+ran+r';\quad(f^{-1})\prime('+str(a)+')='+tex(value))),('f(u)=a를 확인한 뒤 1/f′(u)와 명시적 역함수의 도함수 값을 비교하여 일치함을 검산했다.','Checked f(u)=a,then compared1/f′(u) with the derivative of the explicit inverse.'),list('abcde'))
 planeplot(b,n,points(fn,lo,hi),reflect=True);b.save()
for n,f,a,u in[(41,3*x**3+4*x*x+6*x+5,5,0),(42,x**3+3*s.sin(x)+2*s.cos(x),2,0),(43,3+x*x+s.tan(P*x/2),3,0),(44,s.sqrt(x**3+4*x+4),3,1)]:
 df=s.diff(f,x);v=s.simplify(1/df.subs(x,u));assert s.simplify(f.subs(x,u)-a)==0
 add(n,(M('f(x)='+tex(f)+r',\ a='+str(a)+(r',\ -1<x<1'if n==43 else''))+'에서 (f⁻¹)′(a)를 구하라.',M('f(x)='+tex(f)+r',\ a='+str(a)+(r',\ -1<x<1'if n==43 else''))+'Find (f⁻¹)′(a).'),fs(r'f('+str(u)+')='+str(a)+r'\Rightarrow f^{-1}('+str(a)+')='+str(u),r'f\prime(x)='+tex(df),r'(f^{-1})\prime('+str(a)+r')=\frac1{f\prime('+str(u)+')}='+tex(v)),same(M(r'(f^{-1})\prime('+str(a)+')='+tex(v))),('대응 입력을 원 함수에 대입하고 두 접선 기울기의 곱이1임을 확인했다.','Substituted the corresponding input in f and checked that the two tangent slopes multiply to1.'))
add(45,('f(4)=5,f′(4)=2/3이고 미분 가능한 역함수가 있다. (f⁻¹)′(5)를 구하라.','Given f(4)=5 and f′(4)=2/3 with a differentiable inverse,find (f⁻¹)′(5).'),fs(r'f^{-1}(5)=4',r'(f^{-1})\prime(5)=1/f\prime(4)=3/2'),same(M(r'(f^{-1})\prime(5)=3/2')),('원문 분수2/3을 시각 확인했고 (2/3)(3/2)=1로 검산했다.','Visually checked the source fraction2/3 and verified(2/3)(3/2)=1.'))
add(46,('증가함수 g에 대해 g(2)=8,g′(2)=5이다. (g⁻¹)′(8)을 구하라.','An increasing g satisfies g(2)=8,g′(2)=5. Find (g⁻¹)′(8).'),fs(r'g^{-1}(8)=2',r'(g^{-1})\prime(8)=1/g\prime(2)=1/5'),same(M(r'(g^{-1})\prime(8)=1/5')),('기울기5의 역수이며 증가 역함수에 맞게 양수이다.','It is the reciprocal of5 and positive,consistent with an increasing inverse.'))
add(47,('f(x)=∫₃ˣ√(1+t³)dt일 때 (f⁻¹)′(0)를 구하라.','For f(x)=∫₃ˣ√(1+t³)dt,find (f⁻¹)′(0).'),fs(r'f(3)=0\Rightarrow f^{-1}(0)=3',r'f\prime(x)=\sqrt{1+x^3}',r'(f^{-1})\prime(0)=1/\sqrt{28}=1/(2\sqrt7)'),same(M(r'(f^{-1})\prime(0)=1/(2\sqrt7)')),('기본정리로 구한 f′(3)=√28은0이 아니어서 역함수 미분 공식을 적용할 수 있다.','The FTC gives f′(3)=√28≠0,validating inverse differentiation.'))
add(48,('G(x)=1/f⁻¹(x), f(3)=2,f′(3)=1/9이다. G′(2)를 구하라.','Given G(x)=1/f⁻¹(x),f(3)=2,and f′(3)=1/9,find G′(2).'),fs(r'f^{-1}(2)=3,\quad(f^{-1})\prime(2)=9',r'G\prime(x)=-\frac{(f^{-1})\prime(x)}{[f^{-1}(x)]^2}',r'G\prime(2)=-9/3^2=-1'),same(M(r'G\prime(2)=-1')),('역함수와 역수함수를 구별해 연쇄법칙의 두 인자를 확인했다.','Distinguished inverse function from reciprocal function and checked both chain-rule factors.'))
# Cardano inversion, with real cube roots explicitly specified.
A=r'A(x)=\frac{x^2}{2}-\frac{10}{27}';D=r'D(x)=\sqrt{A(x)^2+\frac8{729}}';inv49=r'\sqrt[3]{A(x)+D(x)}+\sqrt[3]{A(x)-D(x)}-\frac13'
for yy in[0,R(1,10),1,2,5]:
 aa=mp.mpf(str(yy.evalf(30)))**2/2-mp.mpf(10)/27 if isinstance(yy,s.Basic)else mp.mpf(yy)**2/2-mp.mpf(10)/27;dd=mp.sqrt(aa*aa+mp.mpf(8)/729);cb=lambda q:mp.sign(q)*abs(q)**(mp.mpf(1)/3);xx=cb(aa+dd)+cb(aa-dd)-mp.mpf(1)/3;assert abs(xx**3+xx*xx+xx+1-mp.mpf(str(float(yy)))**2)<mp.mpf('1e-15')
add(49,(M(r'f(x)=\sqrt{x^3+x^2+x+1}')+'그래프로 일대일성을 설명하고 CAS 방식으로 역함수를 명시하라. 세 대수적 해 중 두 해가 부적절한 이유도 설명하라.',M(r'f(x)=\sqrt{x^3+x^2+x+1}')+'Explain one-to-one behavior graphically and obtain an explicit CAS-style inverse. Explain why two of the three algebraic roots are irrelevant.'),fs(r'x^3+x^2+x+1=(x+1)(x^2+1)\Rightarrow D_f=[-1,\infty)',r'(x^3+x^2+x+1)\prime=3(x+1/3)^2+2/3>0')+[('양의 제곱근도 증가함수이므로 f는 일대일이고 치역은[0,∞)이다.','The nonnegative square root is increasing,so f is one-to-one with range[0,∞).')]+fs(r'y^2=u^3+u^2+u+1,\quad u=z-1/3\Rightarrow z^3+\frac23z+\frac{20}{27}-y^2=0',A,D,r'f^{-1}(x)='+inv49)+[('모든 세제곱근은 실수 세제곱근이다. Cardano 판별식 A²+8/729가 항상 양수여서 실근은 하나이고 나머지 둘은 비실수 복소근이다. 또한 역함수 입력은 x≥0이다.','All cube roots are real cube roots. The Cardano discriminant A²+8/729 is positive,so exactly one root is real and the other two are nonreal. Inverse inputs must also satisfy x≥0.')],same(M(r'f^{-1}(x)='+inv49+r',\quad x\ge0')+M(A+r',\quad '+D)),('선택한 실근을 여러 비음수 입력에서 원래 삼차식에 대입해 잔차를 검산했다.','Checked residuals by substituting the selected real root into the original cubic at several nonnegative inputs.'))
planeplot(b,49,points(lambda t:math.sqrt(max(0,t**3+t*t+t+1)),-1,2),reflect=True);b.save()
add(50,('sin x는 실수 전체에서 일대일이 아니지만 [-π/2,π/2]로 제한하면 일대일임을 보여라. 이 제한의 역함수 arcsin의 도함수를 구하라.','Show sin x is not one-to-one on R but becomes one-to-one on[-π/2,π/2],then differentiate its inverse arcsin.'),fs(r'\sin0=\sin\pi=0',r'\cos x>0\quad(-\pi/2<x<\pi/2)')+[('제한 구간에서는 엄격히 증가한다. y=arcsin x라 두면 sin y=x이고 cos y는 내부에서 양수이다.','The restriction is strictly increasing. With y=arcsin x,sin y=x and cos y is positive in the interior.')]+fs(r'\cos y\,y\prime=1,\quad y\prime=\frac1{\cos y}=\frac1{\sqrt{1-x^2}},\quad-1<x<1'),same(M(r'\frac d{dx}\arcsin x=\frac1{\sqrt{1-x^2}},\quad-1<x<1')),('제한 치역의 코사인 부호가 양수이므로 제곱근에 음의 가지를 쓰지 않는다.','The cosine sign on the restricted output range selects the positive square root.'))
planeplot(b,50,points(math.sin,-math.pi/2,math.pi/2),reflect=True);b.save()
add(51,('(a)그래프를 왼쪽으로c만큼 옮길 때 y=x 반사도는 어떻게 변하는가? g(x)=f(x+c)의 역함수를 구하라. (b)h(x)=f(cx),c≠0의 역함수를 구하라.','(a)How does reflection across y=x transform a left shift by c? Find the inverse of g(x)=f(x+c). (b)Find the inverse of h(x)=f(cx),c≠0.'),fs(r'(a)\ y=f(x+c)\Rightarrow x=f^{-1}(y)-c',r'(b)\ y=f(cx)\Rightarrow x=f^{-1}(y)/c')+[('왼쪽 이동은 반사 후 아래 이동이 된다. 가로 입력 배율c는 역함수에서 세로 배율1/c가 된다.','A left shift becomes a downward shift after reflection. Input scaling by c becomes vertical scaling by1/c in the inverse.')],same(M(r'g^{-1}(x)=f^{-1}(x)-c,\qquad h^{-1}(x)=f^{-1}(x)/c')),('g와h에 각각 합성하면 f(f⁻¹(x))=x로 돌아온다. c가 음수여도 식은 성립한다.','Composition in each case returns f(f⁻¹(x))=x; the scaling formula also holds for negative c.'),['a','b'])
add(52,('일대일·두 번 미분 가능한 f의 역함수를g라 하자. (a)f′(g(x))≠0인 곳에서 g″=-f″(g)/(f′(g))³을 증명하고,(b)f가 증가하고 오목 위로이면g는 오목 아래임을 보이라.','Let g invert a one-to-one twice-differentiable f. (a)Where f′(g(x))≠0,prove g″=-f″(g)/(f′(g))³. (b)Show that an increasing concave-up f has a concave-down inverse.'),fs(r'f(g(x))=x\Rightarrow f\prime(g(x))g\prime(x)=1',r'g\prime(x)=\frac1{f\prime(g(x))}',r'g\prime\prime(x)=-\frac{f\prime\prime(g(x))g\prime(x)}{[f\prime(g(x))]^2}=-\frac{f\prime\prime(g(x))}{[f\prime(g(x))]^3}',r'f\prime>0,\quad f\prime\prime>0\Rightarrow g\prime\prime<0')+[('분모가0인 점에서는 이 미분 공식의 적용을 따로 검토해야 한다. 예를 들어 f(x)=x³의 역함수는0에서 미분 가능하지 않다.','At a zero denominator the differentiation formula requires separate analysis;for example the inverse of f(x)=x³ is not differentiable at0.')],same(M(r'g\prime\prime(x)=-\frac{f\prime\prime(g(x))}{[f\prime(g(x))]^3};\quad f\prime,f\prime\prime>0\Rightarrow g\prime\prime<0')),('연쇄법칙의 g′ 인자를 포함해 분모가 세제곱이 되는지 확인했고 역함수 미분의 비영 조건을 명시했다.','Included the chain-rule g′ factor,checking the cubed denominator,and stated the nonzero-derivative condition.'),['a','b'])
assert sorted(b.E)==list(range(1,53));b.save();print('6.1 COMPLETE',len(b.E))
