from calc1_inverse_helpers import *
x,t,r,u,z,theta=s.symbols('x t r u z theta',real=True);a,bb=s.symbols('a b',real=True);P=s.pi;R=s.Rational;b=CalcBook('6.2',[429,430,431,432,433])
def page(n):return 429 if n<=4 else 430 if n<=56 else 431 if n<=75 else 432 if n<=100 else 433
def add(n,st,steps,ans,ck,parts=[]):
 b.add(n,page(n),('지수함수와 미분','Exponential functions and derivatives'),st,steps,ans,parts=parts);b.verify(n,*ck);b.save()
D={31:(t,-2*s.exp(t)),32:(r,s.exp(r)+r**s.E),33:(x,(3*x*x-5*x)*s.exp(x)),34:(x,s.exp(x)/(1-s.exp(x))),35:(x,s.exp(a*x**3)),36:(x,s.exp(x*x-x)),37:(theta,s.exp(s.tan(theta))),38:(x,(s.exp(x)+1)**R(1,3)),39:(x,x*x*s.exp(x)/(x*x+s.exp(x))),40:(r,s.sqrt(r)*s.exp(r*r+1)),41:(x,x*x*s.exp(-3*x)),42:(t,s.tan(1+s.exp(2*t))),43:(t,s.exp(a*t)*s.sin(bb*t)),44:(z,s.exp(z/(z-1))),45:(t,s.exp(t*s.sin(2*t))),46:(x,s.exp(s.sin(2*x))+s.sin(s.exp(2*x))),47:(u,s.exp(s.sqrt(s.sec(u*u)))),48:(t,s.exp(1/t)*s.sqrt(t*t-1)),49:(x,s.sin(s.exp(x)/(1+s.exp(x)))),50:(x,s.exp(s.sin(x*x)**2))}
for n,(v,f)in D.items():
 df=s.diff(f,v);rules=('곱·몫의 미분법과 연쇄법칙을 적용한다. 지수함수의 바깥 미분은 그대로이고 안쪽 도함수를 곱한다.','Apply the product/quotient and chain rules. Differentiating an exponential preserves it and multiplies by the inner derivative.')
 # A separate numerical derivative compares function values to the symbolic answer.
 subs={a:R(2,3),bb:R(3,4)};ff=s.lambdify(v,f.subs(subs),'mpmath');dd=s.lambdify(v,df.subs(subs),'mpmath')
 vals=[mp.mpf('2.1'),mp.mpf('2.3')]if n==48 else [mp.mpf('.2'),mp.mpf('.4')]
 for q in vals:assert abs(mp.diff(ff,q)-dd(q))<1e-8,(n,q)
 add(n,(M('f('+s.latex(v)+')='+s.latex(f))+'미분하라.',M('f('+s.latex(v)+')='+s.latex(f))+'Differentiate.'),[rules]+fs(r'\frac{d}{d'+s.latex(v)+r'}e^{h('+s.latex(v)+r')}=e^{h('+s.latex(v)+r')}h\prime('+s.latex(v)+')',r'f\prime('+s.latex(v)+')='+s.latex(s.factor(df))),same(M(s.latex(df))),('허용 구간의 두 입력에서 원래 함수의 수치 미분과 얻은 도함수를 비교했다. 매개변수 a,b는 상수로 취급했다.','Compared numerical derivatives of the original function with the result at two admissible inputs, treating a,b as constants.'))
for n,f,x0,y0 in [(51,s.exp(x)*s.cos(x)+s.sin(x),0,1),(52,(1+x)/(1+s.exp(x)),0,R(1,2))]:
 slope=s.diff(f,x).subs(x,x0);assert f.subs(x,x0)==y0;line=y0+slope*(x-x0)
 add(n,(M('y='+s.latex(f)+r',\quad('+str(x0)+','+s.latex(y0)+')')+'접선의 방정식을 구하라.',M('y='+s.latex(f)+r',\quad('+str(x0)+','+s.latex(y0)+')')+'Find the tangent line.'),fs(r'y\prime='+s.latex(s.diff(f,x)),r'm='+s.latex(slope),r'y-'+s.latex(y0)+'='+s.latex(slope)+'(x-'+str(x0)+')'),same(M('y='+s.latex(line))),('접선은 주어진 점을 지나며 그 기울기는 해당 점의 도함수와 같다.','The line passes through the given point and its slope equals the derivative there.'))
add(53,('e^(x/y)=x-y일 때 y의 도함수를 구하라.','Find y′ when e^(x/y)=x-y.'),fs(r'e^{x/y}\frac{y-xy\prime}{y^2}=1-y\prime',r'(y^2-xe^{x/y})y\prime=y^2-ye^{x/y}',r'y\prime=\frac{y^2-ye^{x/y}}{y^2-xe^{x/y}}'),same(M(r'y\prime=\frac{y^2-ye^{x/y}}{y^2-xe^{x/y}}')),('F=e^(x/y)-x+y로 놓으면 -Fx/Fy가 같은 식을 준다. y≠0이고 분모가 0이 아닌 정칙점에 적용한다.','For F=e^(x/y)-x+y, -Fx/Fy gives the same result, at regular points with y≠0 and nonzero denominator.'))
add(54,('xe^y+ye^x=1의(0,1)에서 접선을 구하라.','Find the tangent to xe^y+ye^x=1 at(0,1).'),fs(r'e^y+xe^yy\prime+y\prime e^x+ye^x=0',r'y\prime=-\frac{e^y+ye^x}{xe^y+e^x},\quad m=-(e+1)',r'y=1-(e+1)x'),same(M(r'y=1-(e+1)x')),('원래 방정식에(0,1)을 대입하면1이고 음함수 기울기의 분모는1이다.','The original equation gives1 at(0,1), and the implicit-slope denominator equals1.'))
for n,f,ode in [(55,s.exp(x)+s.exp(-x/2),lambda f:2*s.diff(f,x,2)-s.diff(f,x)-f),(56,a*s.exp(-x)+bb*x*s.exp(-x),lambda f:s.diff(f,x,2)+2*s.diff(f,x)+f)]:
 assert s.simplify(ode(f))==0
 eq=r'2y\prime\prime-y\prime-y=0'if n==55 else r'y\prime\prime+2y\prime+y=0'
 add(n,(M('y='+s.latex(f)+r',\quad '+eq)+'미분방정식을 만족함을 보여라.',M('y='+s.latex(f)+r',\quad '+eq)+'Verify the differential equation.'),fs(r'y\prime='+s.latex(s.diff(f,x)),r'y\prime\prime='+s.latex(s.diff(f,x,2)),eq)+[('도함수를 대입하면 모든 항이 상쇄된다.','Substituting the derivatives cancels every term.')],('주어진 미분방정식을 만족한다.','It satisfies the stated differential equation.'),('도함수를 독립적으로 계산하여 방정식 좌변을 기호적으로 0으로 단순화했다.','Independently differentiated and symbolically simplified the equation’s left side to zero.'))
print('6.2 authored',len(b.E))
for n,poly,eq in[(57,r*r+6*r+8,r'y\prime\prime+6y\prime+8y=0'),(58,r*r-r-1,r'y+y\prime=y\prime\prime')]:
 roots=s.solve(poly,r)
 add(n,(M(r'y=e^{rx},\quad '+eq)+'만족하는 상수r을 구하라.',M(r'y=e^{rx},\quad '+eq)+'Find the constants r that satisfy the equation.'),fs(r'y\prime=re^{rx},\quad y\prime\prime=r^2e^{rx}',s.latex(poly)+r'=0\quad(e^{rx}>0)',r'r\in\{'+','.join(s.latex(q)for q in roots)+r'\}'),same(M(r'r\in\{'+','.join(s.latex(q)for q in roots)+r'\}')),('각 근을 특성다항식에 대입하여 0임을 확인했다.','Substituting each root into the characteristic polynomial gives zero.'))
add(59,('f(x)=e^(2x)의 n계 도함수 공식을 구하라.','Find the nth derivative of f(x)=e^(2x).'),fs(r'f\prime=2e^{2x},\quad f\prime\prime=4e^{2x}',r'f^{(n)}=2^ne^{2x}')+[('한 번 더 미분할 때마다2를 곱하므로 수학적 귀납법으로 성립한다.','Each further derivative multiplies by2, proving the formula by induction.')],same(M(r'f^{(n)}(x)=2^ne^{2x}')),('n=0 및 귀납 단계 n→n+1을 직접 확인했다.','Checked n=0 and the induction step n→n+1.'))
add(60,('f(x)=xe^(-x)의1000계 도함수를 구하라.','Find the thousandth derivative of f(x)=xe^(-x).'),fs(r'f^{(n)}(x)=(-1)^nxe^{-x}+n(-1)^{n-1}e^{-x}',r'f^{(n)}(x)=(-1)^n(x-n)e^{-x}',r'f^{(1000)}(x)=(x-1000)e^{-x}')+[('곱의 n계 미분에서 x의 2계 이상 도함수가0이라 두 항만 남는다.','In the nth product derivative, derivatives of x beyond the first vanish, leaving two terms.')],same(M(r'(x-1000)e^{-x}')),('일반식을 한 번 미분하면 n+1 공식이 되며 n=0도 원래 함수와 같다.','One derivative of the general formula gives its n+1 version, and n=0 recovers the original function.'))
for n,f,lo,hi,critical in[(67,s.exp(x)/(1+x*x),0,3,[1]),(68,x*s.exp(x/2),-3,1,[-2])]:
 vals=[(q,s.simplify(f.subs(x,q)))for q in[lo,*critical,hi]];mn=min(vals,key=lambda p:float(p[1]));mx=max(vals,key=lambda p:float(p[1]))
 add(n,(M('f(x)='+s.latex(f)+r',\quad x\in['+str(lo)+','+str(hi)+']')+'절대 최댓값·최솟값을 구하라.',M('f(x)='+s.latex(f)+r',\quad x\in['+str(lo)+','+str(hi)+']')+'Find the absolute maximum and minimum.'),fs(r'f\prime(x)='+s.latex(s.factor(s.diff(f,x))))+fs(*['f('+str(q)+')='+s.latex(v)for q,v in vals]),same(M(r'\min f='+s.latex(mn[1])+'\ (x='+str(mn[0])+r');\quad\max f='+s.latex(mx[1])+'\ (x='+str(mx[0])+')')),('도함수 영점과 닫힌 구간의 양 끝점을 모두 비교했다.','Compared every derivative zero and both endpoints of the closed interval.'))
add(69,('f(x)=x-e^x의 절대 최댓값을 구하라.','Find the absolute maximum of f(x)=x-e^x.'),fs(r'f\prime=1-e^x=0\Longleftrightarrow x=0',r'f\prime>0\ (x<0),\quad f\prime<0\ (x>0)',r'f(0)=-1'),same(M(r'\max f=-1\quad(x=0)')),('e^x≥1+x라는 접선 부등식도 f(x)≤-1을 준다.','The tangent inequality e^x≥1+x independently gives f(x)≤-1.'))
add(70,('g(x)=e^x/x,x>0의 절대 최솟값을 구하라.','Find the absolute minimum of g(x)=e^x/x for x>0.'),fs(r'g\prime(x)=\frac{e^x(x-1)}{x^2}',r'g\prime<0\ (0<x<1),\quad g\prime>0\ (x>1)',r'g(1)=e'),same(M(r'\min g=e\quad(x=1)')),('양 끝 x→0⁺,∞에서 모두∞로 가며 유일한 도함수 영점1에서 감소가 증가로 바뀐다.','The function tends to∞ at both ends and switches from decreasing to increasing at its only derivative zero,1.'))
add(71,('f(x)=xe^(2x)의(a)증감,(b)오목·볼록 구간,(c)변곡점을 구하라.','For f(x)=xe^(2x), find(a)monotonicity,(b)concavity intervals,(c)inflection points.'),fs(r'f\prime=e^{2x}(1+2x),\quad f\prime\prime=4e^{2x}(1+x)')+[('도함수의 부호는 각각1+2x와1+x의 부호이다.','The derivative signs equal the signs of1+2x and1+x.')]+fs(r'f(-1)=-e^{-2}'),('(a)감소(-∞,-1/2), 증가(-1/2,∞). (b)아래로 오목(-∞,-1), 위로 오목(-1,∞). (c)(-1,-e⁻²).','(a)Decreasing(-∞,-1/2), increasing(-1/2,∞). (b)Concave down(-∞,-1), up(-1,∞). (c)(-1,-e⁻²).'),('양의 지수 인자는 부호를 바꾸지 않으며 x=-1 양쪽에서2계 도함수 부호가 바뀐다.','The positive exponential factor preserves signs, and the second derivative changes sign across x=-1.'),list('abc'))
add(72,('f(x)=e^x/x²의(a)증감,(b)오목·볼록 구간,(c)변곡점을 구하라.','For f(x)=e^x/x², find(a)monotonicity,(b)concavity intervals,(c)inflection points.'),fs(r'f\prime=\frac{e^x(x-2)}{x^3},\quad f\prime\prime=\frac{e^x(x^2-4x+6)}{x^4}',r'x^2-4x+6=(x-2)^2+2>0')+[('정의되지 않은 x=0에서 구간을 나누어 부호를 조사한다.','Split the sign chart at the excluded input x=0.')],('(a)증가(-∞,0),(2,∞), 감소(0,2). (b)정의역의 두 구간(-∞,0),(0,∞)에서 위로 오목. (c)변곡점 없음.','(a)Increasing(-∞,0),(2,∞); decreasing(0,2). (b)Concave up on(-∞,0) and(0,∞). (c)No inflection points.'),('x=0은 그래프의 점이 아니며2계 도함수가 항상 양수라 변곡점이 생기지 않는다.','x=0 is not a graph point, and the second derivative is positive everywhere in the domain.'),list('abc'))
I={81:(x,x**s.E+s.exp(x),0,1),82:(x,s.E,-5,5),83:(x,s.exp(-P*x),0,2),84:(t,t**3*s.exp(-t**4),None,None),85:(x,s.exp(x)*s.sqrt(1+s.exp(x)),None,None),86:(x,(1+s.exp(x))**2/s.exp(x),None,None),87:(x,(s.exp(x)+s.exp(-x))**2,None,None),88:(x,s.exp(x)*(4+s.exp(x))**5,None,None),89:(u,s.exp(u)/(1-s.exp(u))**2,None,None),90:(theta,s.exp(s.sin(theta))*s.cos(theta),None,None),91:(x,s.exp(1/x)/x**2,1,2),92:(x,s.sqrt(1+s.exp(-x))*s.exp(-x),0,1)}
primitives={81:x**(s.E+1)/(s.E+1)+s.exp(x),82:s.E*x,83:-s.exp(-P*x)/P,84:-s.exp(-t**4)/4,85:R(2,3)*(1+s.exp(x))**R(3,2),86:-s.exp(-x)+2*x+s.exp(x),87:s.exp(2*x)/2+2*x-s.exp(-2*x)/2,88:(4+s.exp(x))**6/6,89:1/(1-s.exp(u)),90:s.exp(s.sin(theta)),91:-s.exp(1/x),92:-R(2,3)*(1+s.exp(-x))**R(3,2)}
for n,(v,f,lo,hi)in I.items():
 F=primitives[n];assert s.simplify(s.diff(F,v)-f)==0
 integral=s.Integral(f,v)if lo is None else s.Integral(f,(v,lo,hi));ans=F if lo is None else s.simplify(F.subs(v,hi)-F.subs(v,lo))
 steps=fs(r'F('+s.latex(v)+')='+s.latex(F),r'F\prime('+s.latex(v)+')='+s.latex(f))
 if lo is not None:
  q=mp.quad(s.lambdify(v,f,'mpmath'),[lo,hi]);assert abs(q-float(ans))<1e-8;steps+=fs(s.latex(integral)+'='+s.latex(ans))
 else:steps+=[('치환 또는 항별 적분으로 얻은 원시함수에 적분상수를 더한다.','Add an integration constant to the antiderivative obtained by substitution or termwise integration.')]
 add(n,(M(s.latex(integral))+'적분을 계산하라.',M(s.latex(integral))+'Evaluate the integral.'),steps,same(M(s.latex(ans)+(' + C'if lo is None else''))),('원시함수를 미분하면 원래 피적분함수가 된다. 정적분은 경계값 차와 독립 수치 적분도 비교했다.','Differentiating the antiderivative recovers the integrand; definite cases also match independent numerical quadrature.'))
add(93,('f(x)=2xe^(-x²)의[0,2]에서 평균값을 구하라.','Find the average value of f(x)=2xe^(-x²) on[0,2].'),fs(r'f_{ave}=\frac12\int_0^2 2xe^{-x^2}\,dx',r'=\frac12[-e^{-x^2}]_0^2=\frac{1-e^{-4}}2'),same(M(r'\frac{1-e^{-4}}2')),('치환 u=-x²의 미분 du=-2x dx를 사용하고 평균값에는 구간 길이2를 나눈다.','Used du=-2x dx for u=-x² and divided the integral by interval length2.'))
add(96,('f″(x)=3e^x+5sinx,f(0)=1,f′(0)=2를 만족하는 f를 구하라.','Find f satisfying f″(x)=3e^x+5sinx,f(0)=1,f′(0)=2.'),fs(r'f\prime=3e^x-5\cos x+C_1,\quad C_1=4',r'f=3e^x-5\sin x+4x+C_2,\quad C_2=-2'),same(M(r'f(x)=3e^x-5\sin x+4x-2')),('두 번 미분한 식과 두 초기값을 모두 다시 대입했다.','Checked the second derivative and both initial conditions directly.'))
for n,st,rate,lo,hi,initial in [(100,('400마리에서 시작하며 r(t)=450.268e^(1.12567t)마리/시간으로 증가한다.3시간 뒤 개체 수를 구하라.','Starting with400 bacteria, growth is r(t)=450.268e^(1.12567t) bacteria/hour. Find the population after3hours.'),R(450268,1000)*s.exp(R(112567,100000)*t),0,3,400),(101,('기름 유출률이 r(t)=100e^(-0.01t)L/분이다. 처음1시간의 총 유출량을 구하라.','Oil leaks at r(t)=100e^(-0.01t)L/min. Find the total leaked in the first hour.'),100*s.exp(-t/100),0,60,0),(102,('2000년 생체량25000kg, 이후 성장률G(t)=60000e^(-0.6t)/(1+5e^(-0.6t))²kg/년이다.2020년 생체량을 구하라.','Biomass is25000kg in2000 and grows at G(t)=60000e^(-0.6t)/(1+5e^(-0.6t))²kg/year. Predict biomass in2020.'),60000*s.exp(-R(3,5)*t)/(1+5*s.exp(-R(3,5)*t))**2,0,20,25000)]:
 F=s.integrate(rate,t);val=s.simplify(initial+F.subs(t,hi)-F.subs(t,lo));num=float(val);assert abs(mp.quad(s.lambdify(t,rate,'mpmath'),[lo,hi])+initial-num)<1e-7
 unit=r'\text{ bacteria}'if n==100 else r'\mathrm{L}'if n==101 else r'\mathrm{kg}'
 add(n,st,fs(r'Q='+str(initial)+'+'+s.latex(s.Integral(rate,(t,lo,hi))),r'\int r(t)\,dt='+s.latex(F)+'+C',r'Q='+s.latex(val)+r'\approx'+f'{num:.3f}'+unit),same(M(f'{num:.3f}'+unit)),('적분을 독립 수치 적분과 비교하고 시간 단위를 경계와 맞췄다. 개체 수·생체량에는 초기량을 더했다.','Compared against independent numerical quadrature, matched time units to the bounds, and added the initial population/biomass.'))
add(103,('요소 제거율u(t)=(r/V)C0e^(-rt/V)에서 r,V>0이며 C0는 초기 요소량mg이다.0~30분의 적분을 계산하고 뜻을 설명하라.','Urea removal is u(t)=(r/V)C0e^(-rt/V),r,V>0, with initial amount C0mg. Evaluate and interpret the integral over the first30minutes.'),fs(r'\int_0^{30}\frac rV C_0e^{-rt/V}\,dt=[-C_0e^{-rt/V}]_0^{30}',r'=C_0(1-e^{-30r/V})')+[('처음30분 동안 혈액에서 제거된 요소의 총량이다.','This is the total urea removed from the blood during the first30minutes.')],same(M(r'C_0(1-e^{-30r/V})\ \mathrm{mg}')),('양의 r,V에서 결과는0과C0 사이이며 시간이 늘면 초기량C0에 접근한다.','For positive r,V the result lies between0 andC0, approaching the initial amount as time grows.'))
add(104,('erf(x)=(2/√π)∫₀ˣe^(-t²)dt라 하자.(a)구간[a,b]의 가우스 적분을 erf 차로 나타내고,(b)y=e^(x²)erf(x)가 y′=2xy+2/√π를 만족함을 보여라.','Let erf(x)=(2/√π)∫₀ˣe^(-t²)dt.(a)Express the Gaussian integral over[a,b] by an erf difference.(b)Verify that y=e^(x²)erf(x) satisfies y′=2xy+2/√π.'),fs(r'\operatorname{erf}(b)-\operatorname{erf}(a)=\frac2{\sqrt\pi}\int_a^b e^{-t^2}\,dt',r'\operatorname{erf}\prime(x)=\frac2{\sqrt\pi}e^{-x^2}',r'y\prime=2xe^{x^2}\operatorname{erf}(x)+e^{x^2}\frac2{\sqrt\pi}e^{-x^2}=2xy+\frac2{\sqrt\pi}'),same(M(r'(a)\ \int_a^b e^{-t^2}\,dt=\frac{\sqrt\pi}2[\operatorname{erf}(b)-\operatorname{erf}(a)];\quad(b)\ y\prime=2xy+\frac2{\sqrt\pi}')),('적분의 가법성과 미적분 기본정리를 사용하고 e^(x²)e^(-x²)=1을 적용했다.','Used integral additivity and the fundamental theorem, then e^(x²)e^(-x²)=1.'),['a','b'])
add(105,('f(x)=3+x+e^x일 때(f⁻¹)′(4)를 구하라.','For f(x)=3+x+e^x, find(f⁻¹)′(4).'),fs(r'f(0)=4,\quad f\prime(x)=1+e^x>0',r'(f^{-1})\prime(4)=\frac1{f\prime(0)}=\frac12'),same(M(r'\frac12')),('f가 엄격히 증가하여 역함수가 있고 원상0에서 도함수2가0이 아니다.','Strict increase gives an inverse and its original derivative at preimage0 is the nonzero value2.'))
add(106,('x→π에서(e^(sinx)-1)/(x-π)의 극한을 구하라.','Find the limit of(e^(sinx)-1)/(x-π) as x→π.'),fs(r'F(x)=e^{\sin x},\quad F(\pi)=1',r'\lim_{x\to\pi}\frac{F(x)-F(\pi)}{x-\pi}=F\prime(\pi)=e^{\sin\pi}\cos\pi=-1'),same(M('-1')),('차분몫이 x=π에서 도함수 정의와 정확히 일치한다.','The difference quotient is exactly the derivative definition at x=π.'))
print('6.2 authored',len(b.E))
from calc1_plot_helpers import plots
add(1,('밑b>0인 지수함수의(a)식,(b)정의역,(c)b≠1일 때 치역,(d)b>1,b=1,0<b<1인 그래프를 설명하라.','For an exponential function with base b>0, give(a)its equation,(b)domain,(c)range when b≠1,and(d)graphs for b>1,b=1,0<b<1.'),fs(r'f(x)=b^x,\quad D=\mathbb R,\quad R=(0,\infty)\ (b\ne1)')+[('b>1이면 증가,0<b<1이면 감소하며(0,1)을 지난다. b=1이면 상수함수1이다.','For b>1 it increases; for0<b<1 it decreases; both pass(0,1). For b=1 it is constantly1.')],('식bˣ, 정의역ℝ; b≠1이면 치역(0,∞). b>1 증가,b=1 상수,0<b<1 감소.','Formula bˣ,domainℝ; range(0,∞) for b≠1. Increasing for b>1,constant for b=1,decreasing for0<b<1.'),('b⁰=1과 b^(-x)=1/bˣ로 절편과 반사 관계를 확인한다.','b⁰=1 and b^(-x)=1/bˣ confirm the intercept and reflection relation.'),list('abcd'))
plots(b,1,[('6.2.1 Three base cases',-3,3,0,8,[('b=2',lambda q:2**q),('b=1',lambda q:1),('b=1/2',lambda q:2**(-q))])])
add(2,('(a)수e의 정의,(b)근삿값,(c)자연지수함수를 설명하라.','Explain(a)the definition of e,(b)its approximate value,(c)the natural exponential function.'),fs(r'\lim_{h\to0}\frac{e^h-1}{h}=1',r'e\approx2.718281828459,\quad f(x)=e^x')+[('x=0에서 접선 기울기가1인 지수함수의 밑이e이다.','e is the base whose exponential graph has tangent slope1 at x=0.')],same(M(r'(a)\ \lim_{h\to0}(e^h-1)/h=1;\quad(b)\ 2.718281828459\ldots;\quad(c)\ e^x')),('정의에서 f′(0)=1이며 지수법칙으로 f′(x)=eˣ가 된다.','The definition gives f′(0)=1, and the exponential law yields f′(x)=eˣ.'),list('abc'))
for n,bases in[(3,[2,math.e,5,20]),(4,[math.e,1/math.e,8,1/8]),(5,[3,10,1/3,.1]),(6,[.9,.6,.3,.1])]:
 labels={3:['2^x','e^x','5^x','20^x'],4:['e^x','e^(-x)','8^x','8^(-x)'],5:['3^x','10^x','(1/3)^x','(1/10)^x'],6:['0.9^x','0.6^x','0.3^x','0.1^x']}[n]
 explain=('모두 증가한다. x>0에서는 밑이 클수록 높고 x<0에서는 순서가 반대이다.','All increase; for x>0 larger bases give higher values, with reversed ordering for x<0.')if n==3 else('서로 역수인 밑의 곡선은 y축 대칭이다. 밑이1보다 크면 증가하고 작으면 감소한다.','Reciprocal-base curves reflect across the y-axis; bases above1 increase and bases below1 decrease.')if n in[4,5]else('모두 감소한다. x>0에서 작은 밑일수록 빠르게0으로 가고 x<0에서는 더 높다.','All decrease; for x>0 smaller bases decay faster toward0, while they lie higher for x<0.')
 add(n,('함수 '+', '.join(labels)+'를 같은 화면에 그리고 관계를 설명하라.','Graph '+', '.join(labels)+' on common axes and describe their relationship.'),[('모든 곡선은(0,1)을 지나며 양수이다.','Every curve is positive and passes through(0,1).'),explain],explain,('지수의 부호와 밑의 대소를 비교하고 각 곡선을 원래 식에서 직접 계산했다.','Compared exponent signs and base ordering and computed every curve from its defining formula.'))
 plots(b,n,[(f'6.2.{n} Base comparison',-2,2,0,10,[(label,lambda q,base=base:base**q)for label,base in zip(labels,bases)])])
G={7:(3**x+1,(-3,2,-1,11),r'y=1',r'(0,2)'),8:(2*R(1,2)**x-3,(-3,4,-4,14),r'y=-3',r'(0,-1)'),9:(-s.exp(-x),(-3,3,-21,1),r'y=0',r'(0,-1)'),10:(4**(x+2),(-5,0,-1,17),r'y=0',r'(-2,1),\ (0,16)'),11:(1-s.exp(-x)/2,(-3,3,-10,2),r'y=1',r'(0,1/2)'),12:(s.exp(s.Abs(x)),(-3,3,0,21),r'\text{none}',r'(0,1)')}
for n,(f,window,asym,pt)in G.items():
 add(n,(M('y='+s.latex(f))+'기본 지수 그래프의 변환으로 개형을 그려라.',M('y='+s.latex(f))+'Sketch using transformations of basic exponential graphs.'),fs('y='+s.latex(f),r'\text{Key points: }'+pt,r'\text{Horizontal asymptote: }'+asym)+[('식을 구성하는 이동·반사를 적용한다. 절댓값 지수는 오른쪽 부분을 y축에 대칭시킨다.','Apply the shifts and reflections in the formula; an absolute-value exponent mirrors the right half across the y-axis.')],same(M(r'\text{Key points: }'+pt+r';\quad\text{horizontal asymptote: }'+asym)),('절편을 대입하고 무한대 극한으로 점근선을 확인했다. 그래프는 원래 함수값을 사용한다.','Checked intercepts by substitution and asymptotes by limits; the graph uses the original function values.'))
 plots(b,n,[(f'6.2.{n} Transformed exponential',*window,[('y='+str(f),s.lambdify(x,f,'math'))])])
for n,st,eqs in[(13,('e^x를(a)아래2,(b)오른쪽2 이동,(c)x축 대칭,(d)y축 대칭,(e)x축 뒤 y축 대칭한 식을 구하라.','Transform e^x by(a)down2,(b)right2,(c)x-axis reflection,(d)y-axis reflection,(e)x-then-y reflection.'),[r'e^x-2',r'e^{x-2}',r'-e^x',r'e^{-x}',r'-e^{-x}']),(14,('e^x를(a)y=4,(b)x=2에 대칭한 식을 구하라.','Reflect e^x across(a)y=4,(b)x=2.') ,[r'8-e^x',r'e^{4-x}'])]:
 add(n,st,[('수평 이동은 입력을 바꾸고 수직 이동은 출력에 더한다. y=k 대칭은 y→2k-y,x=k 대칭은 x→2k-x이다.','Horizontal shifts change the input, vertical shifts add to the output. Reflection across y=k sends y to2k-y; across x=k sends x to2k-x.')]+fs(*[f'({chr(97+i)})\ y='+eq for i,eq in enumerate(eqs)]),same(M(r';\quad '.join(f'({chr(97+i)})\ y='+eq for i,eq in enumerate(eqs)))),('원래 기준점(0,1)에 변환을 적용하면 각 새 식의 해당 점과 일치한다.','Transforming the original reference point(0,1) agrees with the corresponding point in each new formula.'),list('abcde'if n==13 else'ab'))
add(15,('정의역을 구하라.(a)(1-e^(x²))/(1-e^(1-x²)),(b)(1+x)/e^(cosx).','Find the domains:(a)(1-e^(x²))/(1-e^(1-x²)),(b)(1+x)/e^(cosx).'),fs(r'(a)\ 1-e^{1-x^2}\ne0\Longleftrightarrow x\ne\pm1',r'(b)\ e^{\cos x}>0\quad(x\in\mathbb R)'),same(M(r'(a)\ \mathbb R\setminus\{-1,1\};\quad(b)\ \mathbb R')),('실수 지수함수에는 입력 제한이 없으므로 분모의 영점만 제외한다.','Real exponential functions have no input restriction, so only denominator zeros are excluded.'),['a','b'])
add(16,('정의역을 구하라.(a)√(10^t-100),(b)sin(e^t-1).','Find the domains:(a)√(10^t-100),(b)sin(e^t-1).'),fs(r'(a)\ 10^t\ge100=10^2\Longleftrightarrow t\ge2',r'(b)\ t\in\mathbb R'),same(M(r'(a)\ [2,\infty);\quad(b)\ \mathbb R')),('제곱근 안의 비음수 조건만(a)에 필요하고 sin과exp의 합성은 모든 실수에 정의된다.','Only(a) needs a nonnegative radicand; the sine-exponential composition is defined for all real inputs.'),['a','b'])
for n,eq,pts in[(17,3*2**x,[(1,6),(3,24)]),(18,2*R(1,3)**x,[(0,2),(2,R(2,9))])]:
 algebra=r'Cb=6,\ Cb^3=24\Rightarrow b^2=4\Rightarrow b=2,C=3'if n==17 else r'C=2,\ Cb^2=2/9\Rightarrow b=1/3'
 add(n,('지수곡선 Cb^x가'+str(pts)+'를 지난다. C와b를 구하라.','The exponential curve Cb^x passes through'+str(pts)+'. Find C and b.'),fs(algebra,'f(x)='+s.latex(eq)),same(M('f(x)='+s.latex(eq))),('두 주어진 점을 새 식에 대입하면 모두 일치하며 지수함수의 밑은 양수 가지를 택한다.','Both given points satisfy the formula; the exponential base uses the positive root.'))
 plots(b,n,[(f'6.2.{n} Exponential through given points',-1,4,0,50 if n==17 else 7,[('f(x)',s.lambdify(x,eq,'math'))],[(float(a),float(c))for a,c in pts])])
add(19,('눈금1단위가1인치일 때 x²와2^x의 그래프에서 원점 오른쪽2ft 지점의 높이를 각각ft,mi로 구하라.','With one unit equal to one inch, find the heights of x² and2^x two feet to the right of the origin, in feet and miles respectively.'),fs(r'x=24,\quad x^2=576\text{ in}=48\text{ ft}',r'2^{24}=16777216\text{ in}=\frac{16777216}{12\cdot5280}\text{ mi}\approx264.79\text{ mi}'),('48ft,약265mi.','48ft,about265mi.'),('수평거리도24인치로 먼저 변환하고 수직거리에는1마일=63360인치를 사용했다.','First converted the horizontal distance to24inches, then used63360inches per mile for the vertical distance.'))
for n,expr,limpt,direction,ans,reason in[(23,R(1001,1000)**x,s.oo,'-',s.oo,('밑이1보다 크므로 오른쪽에서 무한히 증가한다.','A base above1 grows without bound to the right.')),(24,R(1001,1000)**x,-s.oo,'+',0,('음의 지수에서 양의 거듭제곱의 역수로 쓴다.','For negative exponents, use the reciprocal of a positive power.')),(25,(s.exp(3*x)-s.exp(-3*x))/(s.exp(3*x)+s.exp(-3*x)),s.oo,'-',1,('분자와 분모를e^(3x)로 나누면(1-e^(-6x))/(1+e^(-6x))이다.','Divide numerator and denominator by e^(3x) to get(1-e^(-6x))/(1+e^(-6x)).')),(26,s.exp(-x*x),s.oo,'-',0,('지수-x²가-∞로 간다.','The exponent -x² tends to-∞.')),(27,s.exp(3/(2-x)),2,'+',0,('2-x→0⁻이므로 지수가-∞로 간다.','2-x→0⁻, so the exponent tends to-∞.')),(28,s.exp(3/(2-x)),2,'-',s.oo,('2-x→0⁺이므로 지수가+∞로 간다.','2-x→0⁺, so the exponent tends to+∞.')),(29,s.exp(-2*x)*s.cos(x),s.oo,'-',0,('절댓값이 e^(-2x) 이하이므로 조임정리를 쓴다.','Its absolute value is bounded by e^(-2x), so apply the squeeze theorem.')),(30,s.exp(s.sec(x)),P/2,'+',0,('오른쪽에서 cosx→0⁻, secx→-∞이다.','From the right, cosx→0⁻ and secx→-∞.'))]:
 side=''if limpt in[s.oo,-s.oo]else('^+'if direction=='+'else'^-');formula=r'\lim_{x\to '+s.latex(limpt)+side+'}'+s.latex(expr)
 if n!=29:assert s.limit(expr.rewrite(s.exp),x,limpt,dir=direction)==ans,(n,s.limit(expr.rewrite(s.exp),x,limpt,dir=direction),ans)
 add(n,(M(formula)+'극한을 구하라.',M(formula)+'Find the limit.'),[reason]+fs(formula+'='+s.latex(ans)),same(M(s.latex(ans))),('지수의 극한과 접근 방향을 따로 확인한 뒤 지수함수의 연속성 또는 무한대 성질을 적용했다.','Checked the exponent limit and approach direction before applying exponential continuity or end behavior.'))
print('6.2 authored',len(b.E))
q20=float(mp.findroot(lambda q:5*mp.log(q)-q*mp.log(5),(1,2)));q21=float(mp.findroot(lambda q:q-10*mp.log(q),(35,36)))
add(20,('x⁵와5ˣ를 여러 창에서 비교하여 모든 교점을 소수1자리로 구하고 큰x에서 어느 쪽이 더 빠르게 증가하는지 설명하라.','Compare x⁵ and5ˣ in several windows, find every intersection to one decimal place,and identify the faster growth for large x.'),fs(r'x>0,\quad 5\ln x=x\ln5',r'x\approx'+f'{q20:.8f}'+r',\quad x=5')+[('5lnx-xln5는 엄격히 아래로 오목하므로 영점이 많아야2개이다. 음의x에서는 x⁵<0<5ˣ이다.','5lnx-xln5 is strictly concave down and has at most two zeros; for negative x,x⁵<0<5ˣ.'),('지수함수5ˣ가 큰x에서 더 빠르게 증가한다.','The exponential5ˣ grows faster for large x.')],same(M(r'(1.8,17.3),\ (5.0,3125.0);\quad 5^x\text{ eventually grows faster}')),('두 양의 근을 원래 방정식에 대입하고 로그 차 함수의 단조 구간으로 다른 근이 없음을 확인했다.','Substituted both positive roots and used the log-difference monotonicity intervals to rule out other roots.'))
# Coordinate ordinate is rounded from the computed root, not from rounded x.
b.E[20]['answer']=pair(*same(M(f'({q20:.1f},{q20**5:.1f}),\ (5.0,3125.0);\quad 5^x'+r'\text{ grows faster}')))
plots(b,20,[('6.2.20 Near first intersection',0,3,0,250,[('x^5',lambda q:q**5),('5^x',lambda q:5**q)]),('6.2.20 Eventual exponential dominance',3,8,0,50000,[('x^5',lambda q:q**5),('5^x',lambda q:5**q)])])
add(21,('x¹⁰과eˣ를 여러 창에서 비교하라. eˣ가 최종적으로 앞서기 시작하는x를 추정하라.','Compare x¹⁰ andeˣ in several windows. Estimate where eˣ finally overtakes x¹⁰.'),fs(r'x=10\ln x\quad(x>0)',r'x\approx'+f'{q21:.8f}')+[('큰 교점 이후 x-10lnx는 증가하므로 eˣ가 다시 뒤처지지 않는다.','Beyond the larger crossing,x-10lnx increases,so eˣ never falls behind again.')],same(M(r'x>'+f'{q21:.3f}'+r'\quad(\text{about }35.8)')),('q-10lnq의 근을 계산하고 x>10에서 그 도함수1-10/x가 양수임을 확인했다.','Solved q-10lnq=0 and checked its derivative1-10/x is positive for x>10.'))
plots(b,21,[('6.2.21 Small-scale comparison',0,4,0,200,[('x^10',lambda q:q**10),('e^x',math.exp)]),('6.2.21 Final crossing',32,39,0,4e16,[('x^10',lambda q:q**10),('e^x',math.exp)])])
cut=math.log(1e9)
add(22,('eˣ>10⁹인x를 그래프로 추정하라.','Use a graph to estimate x for which eˣ>10⁹.'),fs(r'e^x=10^9\Longleftrightarrow x=9\ln10\approx'+f'{cut:.6f}')+[('eˣ가 엄격히 증가하므로 교점 오른쪽에서 부등식이 성립한다.','Since eˣ strictly increases,the inequality holds to the right of the crossing.')],same(M(r'x>9\ln10\approx20.723266')),('경계값을 지수에 대입하면10⁹가 되고 양쪽 부호도 일치한다.','Substitution at the threshold gives10⁹ and signs on either side agree.'))
plots(b,22,[('6.2.22 Billion threshold',18,23,0,6e9,[('e^x',math.exp),('10^9',lambda q:1e9)])])
q=0.;iterations=[q]
for i in range(5):q=q-(math.exp(q)+q)/(math.exp(q)+1);iterations.append(q)
add(61,('(a)eˣ+x=0의 해 존재를 중간값정리로 보이고,(b)뉴턴법으로 소수6자리까지 구하라.','(a)Use the intermediate value theorem to show eˣ+x=0 has a solution.(b)Find it to six decimal places by Newton’s method.'),fs(r'F(-1)=e^{-1}-1<0<F(0)=1',r'x_{n+1}=x_n-\frac{e^{x_n}+x_n}{e^{x_n}+1}')+[('x0=0의 반복값: '+', '.join(f'{v:.9f}'for v in iterations),'Iterates from x0=0: '+', '.join(f'{v:.9f}'for v in iterations))],same(M(r'x\approx-0.567143')),('F′=eˣ+1>0이므로 해가 유일하며 최종 반복값의 잔차는10⁻¹⁴보다 작다.','F′=eˣ+1>0 gives uniqueness,and the final residual is below10⁻¹⁴.'),['a','b'])
r62=float(mp.findroot(lambda q:q/2-mp.tanh(q/2)-mp.mpf('.1'),1.5))
add(62,('x=0에서2/(1+eˣ)≈1-x/2를 확인하고 오차가0.1 이내인x 구간을 구하라.','Verify2/(1+eˣ)≈1-x/2 at x=0 and find where the error is at most0.1.'),fs(r'f(0)=1,\quad f\prime(0)=-1/2,\quad L(x)=1-x/2',r'f(x)-L(x)=x/2-\tanh(x/2)',r'E\prime(x)=\tfrac12\tanh^2(x/2)\ge0')+[('오차함수는 홀함수이므로 양의 경계에서E(x)=0.1을 풀어 대칭시킨다.','The error is odd; solve E(x)=0.1 for the positive endpoint and reflect it.')],same(M(r'|x|\le '+f'{r62:.6f}')),('경계의 오차를0.1과 비교하고 도함수 비음수로 구간 전체를 확인했다.','Checked endpoint error0.1 and nonnegative derivative to verify the full interval.'))
plots(b,62,[('6.2.62 Linear approximation',-2,2,0,2,[('f',lambda q:2/(1+math.exp(q))),('L=1-x/2',lambda q:1-q/2)]),('6.2.62 Absolute error',-2,2,0,.3,[('|f-L|',lambda q:abs(q/2-math.tanh(q/2))),('0.1',lambda q:.1)])])
t63=math.log(38/96.39785)/math.log(.818656)
add(63,('1일째 바이러스량은76.0이었다. 예제의 그래프 모형V(t)=96.39785(0.818656)^t에서38.0으로 줄기까지 추가 시간을 추정하라.','The viral load at day1 was76.0. Using the example’s graphed model V(t)=96.39785(0.818656)^t,estimate the additional time to reach38.0.'),fs(r'96.39785(0.818656)^t=38',r't=\frac{\ln(38/96.39785)}{\ln(0.818656)}\approx'+f'{t63:.3f}',r'\Delta t=t-1\approx'+f'{t63-1:.3f}'),('추가로약3.7일.','About3.7 additional days.'),('목표량은 관측값76의 절반38이고 추가 시간에서는 시작시각1일을 뺀다. 모형 자체의 반감기와 구별했다.','The target is half the observed76,namely38; subtract day1 for additional time,distinguishing this from the model’s own half-life.'))
plots(b,63,[('6.2.63 Viral-load model',0,10,0,100,[('V(t)',lambda q:96.39785*.818656**q),('Target38',lambda q:38)],[(1,76),(t63,38)])])
data64=list(zip(range(0,25,4),[37,47,63,78,105,130,173]));mt=sum(q for q,c in data64)/7;ml=sum(math.log(c)for q,c in data64)/7;k64=sum((q-mt)*(math.log(c)-ml)for q,c in data64)/sum((q-mt)**2 for q,c in data64);a64=math.exp(ml-k64*mt);b64=math.exp(k64);double=math.log(2)/k64
add(64,('시간0,4,8,12,16,20,24시간의 개체 수는37,47,63,78,105,130,173이다.(a)산점도,(b)ab^t 지수회귀,(c)모형과 자료를 함께 그리고 배가시간을 추정하라.','Counts at0,4,8,12,16,20,24hours are37,47,63,78,105,130,173.(a)Plot the data.(b)Fit ab^t.(c)Plot model with data and estimate doubling time.'),[('lnN=ln a+t ln b에 최소제곱 직선을 맞추는 지수회귀를 사용한다.','Use exponential regression by fitting the least-squares line lnN=ln a+t ln b.')]+fs(r'\ln b=\frac{\sum(t_i-\bar t)(\ln N_i-\overline{\ln N})}{\sum(t_i-\bar t)^2}',r'f(t)\approx'+f'{a64:.6f}'+f'({b64:.8f})^t',r'T_2=\frac{\ln2}{\ln b}\approx'+f'{double:.3f}'+r'\text{ h}'),same(M(r'f(t)\approx'+f'{a64:.4f}'+fr'({b64:.6f})^t;\quad T_2\approx{double:.2f}'+r'\text{ h}')),('로그 잔차의 합과 시간 가중 잔차의 합이0인 회귀 정규방정식을 확인하고 b^T=2를 대입했다.','Checked the log-regression normal equations and substituted b^T=2.'),list('abc'))
plots(b,64,[('6.2.64 Data and exponential fit',0,28,0,240,[('Exponential regression',lambda q:a64*b64**q)],data64)])
add(65,('소문을 들은 비율p(t)=1/(1+ae^(-kt)),a,k>0이다.(a)장기 극한과 뜻,(b)전파율,(c)a=10,k=0.5에서 그래프와80% 도달시간을 구하라.','The informed proportion is p(t)=1/(1+ae^(-kt)),a,k>0.(a)Find and interpret its long-term limit.(b)Find the spread rate.(c)Graph a=10,k=0.5 and estimate time to80%.'),fs(r'\lim_{t\to\infty}p(t)=1',r'p\prime(t)=\frac{ake^{-kt}}{(1+ae^{-kt})^2}=kp(1-p)',r'\frac1{1+10e^{-t/2}}=0.8\Rightarrow t=2\ln40\approx7.378')+[('이 모형에서는 장기적으로 인구 전체가 소문을 듣는다.','In this model,eventually the whole population hears the rumor.')],('(a)1,전체 인구.(b)ake^(-kt)/(1+ae^(-kt))².(c)약7.38시간.','(a)1,the whole population.(b)ake^(-kt)/(1+ae^(-kt))².(c)About7.38hours.'),('t=2ln40을 p에 넣으면0.8이고 p′=kp(1-p)와도 대수적으로 일치한다.','Substitution of t=2ln40 gives0.8 and the derivative equals kp(1-p).'),list('abc'))
plots(b,65,[('6.2.65 Rumor spread',0,15,0,1,[('p(t)',lambda q:1/(1+10*math.exp(-q/2))),('80%',lambda q:.8)])])
tmax=math.atan(8)/4;ymax=8*math.exp(-tmax/2)*math.sin(4*tmax);last66=float(mp.findroot(lambda q:8*mp.exp(-q/2)*mp.sin(4*q)+2,(2.75,2.8)))
add(66,('질량의 변위y=8e^(-t/2)sin4t(cm),t≥0이다.(a)±8e^(-t/2)와 함께 그래프를 그리고 관계,(b)최대 변위와 포락선 접촉 여부,(c)처음 평형 복귀 속도,(d)이후 항상|y|≤2인 시간을 구하라.','Displacement is y=8e^(-t/2)sin4t(cm),t≥0.(a)Graph with±8e^(-t/2) and explain.(b)Find the maximum and whether it occurs at an envelope contact.(c)Find velocity at the first return to equilibrium.(d)Find when |y| remains≤2 thereafter.'),fs(r'|y|\le8e^{-t/2},\quad y\prime=8e^{-t/2}(4\cos4t-\tfrac12\sin4t)',r't_{max}=\tfrac14\arctan8\approx'+f'{tmax:.6f}'+r',\quad y_{max}\approx'+f'{ymax:.4f}',r't_{return}=\pi/4,\quad v=-32e^{-\pi/8}\approx'+f'{-32*math.exp(-math.pi/8):.4f}')+[('최대는 sin4t=1인 포락선 접촉보다 먼저 생긴다. 마지막으로y=-2를 지나는 시각 뒤에는 모든 진폭이2 이하이다.','The maximum occurs before sin4t=1 envelope contact. After the last crossing of y=-2,all subsequent extrema have magnitude below2.')]+fs(r't_{last}\approx'+f'{last66:.6f}'),same(M(r'(b)\ '+f'{ymax:.3f}'+r'\text{ cm at }'+f'{tmax:.3f}'+r'\text{ s};\ (c)\ -32e^{-\pi/8}\text{ cm/s};\ (d)\ t\ge'+f'{last66:.3f}'+r'\text{ s}')),('극값 시각은(arctan8+nπ)/4이며 크기는 e^(-nπ/8)배로 줄어든다. 마지막2cm 교점과 다음 극값의 크기를 비교했다.','Extrema occur at(arctan8+nπ)/4 and shrink by e^(-nπ/8); checked the last2cm crossing against the next extremum.'),list('abcd'))
plots(b,66,[('6.2.66 Damped displacement and envelopes',0,7,-8,8,[('y(t)',lambda q:8*math.exp(-q/2)*math.sin(4*q)),('Upper envelope',lambda q:8*math.exp(-q/2)),('Lower envelope',lambda q:-8*math.exp(-q/2)),('2cm',lambda q:2),('-2cm',lambda q:-2)])])
print('6.2 authored',len(b.E))
for n,f,st,ans,explan,window in[(73,s.exp(-1/(x+1)),('y=e^(-1/(x+1))를 정의역·절편·점근선·증감·극값·오목성으로 분석하고 그려라.','Analyze and sketch y=e^(-1/(x+1)):domain,intercepts,asymptotes,monotonicity,extrema,and concavity.'),('정의역ℝ\{-1},y절편e⁻¹,x절편 없음. 점근선x=-1,y=1. 두 정의역 구간에서 증가,극값 없음. 위로 오목(-∞,-1),(-1,-1/2),아래로 오목(-1/2,∞). 변곡점(-1/2,e⁻²).','Domainℝ\{-1};y-intercept e⁻¹,no x-intercept. Asymptotes x=-1,y=1. Increasing on both domain intervals,no extrema. Concave up(-∞,-1),(-1,-1/2);down(-1/2,∞). Inflection(-1/2,e⁻²).'),fs(r'\lim_{x\to-1^-}f=\infty,\quad\lim_{x\to-1^+}f=0,\quad\lim_{x\to\pm\infty}f=1'),(-4,3,0,5)),(74,s.exp(-x)*s.sin(x),('y=e^(-x)sinx,0≤x≤2π를 분석하고 그려라.','Analyze and sketch y=e^(-x)sinx on0≤x≤2π.'),('영점0,π,2π. 증가(0,π/4),(5π/4,2π),감소(π/4,5π/4). 최대 e^(-π/4)/√2,최소 -e^(-5π/4)/√2. 아래로 오목(0,π/2),(3π/2,2π),위로 오목(π/2,3π/2). 변곡점(π/2,e^(-π/2)),(3π/2,-e^(-3π/2)).','Zeros0,π,2π. Increasing(0,π/4),(5π/4,2π);decreasing(π/4,5π/4). Maximum e^(-π/4)/√2,minimum -e^(-5π/4)/√2. Concave down(0,π/2),(3π/2,2π);up(π/2,3π/2). Inflections(π/2,e^(-π/2)),(3π/2,-e^(-3π/2)).'),fs(r'\cos x-\sin x=0\Rightarrow x=\pi/4,5\pi/4',r'\cos x=0\Rightarrow x=\pi/2,3\pi/2'),(0,2*math.pi,-.1,.4)),(75,1/(1+s.exp(-x)),('y=1/(1+e^(-x))를 분석하고 그려라.','Analyze and sketch y=1/(1+e^(-x)).'),('정의역ℝ,치역(0,1),y절편1/2,x절편 없음. 수평점근선y=0,1. 전체에서 증가,극값 없음. 위로 오목(-∞,0),아래로 오목(0,∞). 변곡점(0,1/2),그 점에 대한 점대칭.','Domainℝ,range(0,1),y-intercept1/2,no x-intercept. Horizontal asymptotes y=0,1. Increasing everywhere,no extrema. Concave up(-∞,0),down(0,∞). Inflection(0,1/2),also a center of symmetry.'),fs(r'\lim_{x\to-\infty}f=0,\quad\lim_{x\to\infty}f=1,\quad f(-x)=1-f(x)'),(-6,6,0,1))]:
 add(n,st,fs(r'f\prime='+s.latex(s.factor(s.diff(f,x))),r'f\prime\prime='+s.latex(s.factor(s.diff(f,x,2))))+explan+[('도함수와2계 도함수의 영점 및 정의되지 않는 입력에서 구간을 나누고 부호를 조사한다.','Split intervals at derivative zeros and excluded inputs,then inspect first- and second-derivative signs.')],ans,('절편과 극값·변곡점 후보를 원래 함수에 대입하고 각 구간에서 도함수의 부호를 확인했다.','Substituted intercepts and extremum/inflection candidates into the function and checked derivative signs on every interval.'))
 fn=s.lambdify(x,f,'math')
 if n==73:
  plots(b,n,[('6.2.73 Left branch',-4,-1.05,0,5,[('f(x)',fn),('y=1',lambda q:1)]),('6.2.73 Right branch',-.99,3,0,1,[('f(x)',fn),('y=1',lambda q:1)])])
 else:plots(b,n,[(f'6.2.{n} Curve analysis',*window,[('f(x)',fn)])])
alpha=math.acos((math.sqrt(5)-1)/2)
add(76,('f(x)=e^(cosx)를 그리고 극대·극소를 추정한 뒤 정확히 구하라.f″ 그래프로 변곡점을 추정하라.','Graph f(x)=e^(cosx),estimate and then calculate local extrema exactly.Use f″ to estimate inflections.'),fs(r'f\prime=-e^{\cos x}\sin x,\quad f\prime\prime=e^{\cos x}(\sin^2x-\cos x)',r'\sin^2x-\cos x=0\Longleftrightarrow\cos x=\frac{\sqrt5-1}{2}',r'\alpha=\arccos\frac{\sqrt5-1}{2}\approx'+f'{alpha:.6f}'),same(M(r'\max f=e\ (x=2k\pi);\ \min f=e^{-1}\ (x=(2k+1)\pi);\quad\text{inflections }(2k\pi\pm\alpha,e^{(\sqrt5-1)/2}),\ k\in\mathbb Z')),('cos의 범위[-1,1]로 극값을 재확인하고 다른 이차근(-1-√5)/2는 범위 밖이라 제외했다.','Rechecked extrema using cos∈[-1,1] and excluded the other quadratic root(-1-√5)/2 outside that range.'))
plots(b,76,[('6.2.76 Function',-2*math.pi,2*math.pi,0,3,[('e^(cosx)',lambda q:math.exp(math.cos(q)))]),('6.2.76 Second derivative',-2*math.pi,2*math.pi,-3,2,[('f second derivative',lambda q:math.exp(math.cos(q))*(math.sin(q)**2-math.cos(q)))])])
roots77=sorted(float(s.re(q))for q in s.nroots((3*x*x-1)**2+6*x)if abs(float(s.im(q)))<1e-10)
add(77,('f(x)=e^(x³-x)를 그리고 극대·극소를 추정한 뒤 정확히 구하라.f″ 그래프로 변곡점을 추정하라.','Graph f(x)=e^(x³-x),estimate and then calculate local extrema exactly.Use f″ to estimate inflections.'),fs(r'f\prime=e^{x^3-x}(3x^2-1)',r'f\prime\prime=e^{x^3-x}[(3x^2-1)^2+6x]',r'f\prime=0\Longleftrightarrow x=\pm1/\sqrt3')+[('2계 도함수의 실근은 '+', '.join(f'{q:.6f}'for q in roots77)+'이고 각각 부호가 바뀐다.','The real second-derivative zeros are '+', '.join(f'{q:.6f}'for q in roots77)+',with a sign change at each.')],same(M(r'\text{local max }e^{2/(3\sqrt3)}\ (x=-1/\sqrt3);\quad\text{local min }e^{-2/(3\sqrt3)}\ (x=1/\sqrt3);\quad\text{inflections }'+','.join(f'({q:.5f},{math.exp(q**3-q):.5f})'for q in roots77))),('4차 다항식의 모든 근을 계산해 실근을 고르고 각 근 앞뒤의2계 도함수 부호 변화를 확인했다.','Computed all quartic roots,selected the real ones,and checked second-derivative sign changes around each.'))
plots(b,77,[('6.2.77 Function',-1.5,1.5,0,7,[('f',lambda q:math.exp(q**3-q))]),('6.2.77 Second derivative near inflections',-1.3,.3,-6,8,[('f second derivative',lambda q:math.exp(q**3-q)*((3*q*q-1)**2+6*q))])])
add(78,('약물 농도 모형S(t)=At^p e^(-kt),A=0.01,p=4,k=0.07에서t의 단위는 분이다. 변곡 시각과 뜻을 구하고 그래프를 그려라.','For surge model S(t)=At^p e^(-kt),A=0.01,p=4,k=0.07 and t in minutes,find and interpret inflection times and graph the curve.'),fs(r'S\prime=At^{p-1}e^{-kt}(p-kt)',r'S\prime\prime=At^{p-2}e^{-kt}[(kt-p)^2-p]',r't=\frac{p\pm\sqrt p}{k}=\frac2{0.07},\frac6{0.07}\approx28.571,85.714')+[('처음 변곡은 증가율이 최대인 때, 두 번째는 감소율의 크기가 최대인 때이다. 최대 농도는t=p/k≈57.143분이다.','The first inflection gives the greatest increase rate,the second the greatest decrease rate in magnitude.The peak concentration occurs at t=p/k≈57.143minutes.')],same(M(r't\approx28.571,85.714\text{ min}')),('t=0은 끝점이므로 S″=0이어도 변곡점이 아니다. 내부 두 시각 양쪽의 오목성이 실제로 바뀐다.','t=0 is an endpoint rather than an inflection despite S″=0; concavity genuinely changes at both interior times.'))
plots(b,78,[('6.2.78 Drug-response model',0,160,0,2100,[('S(t)',lambda q:.01*q**4*math.exp(-.07*q))])])
t79=1/2.802;max79=.135*t79/math.e
add(79,('모형C(t)=0.135te^(-2.802t)g/dL에서 처음3시간의 최대 평균 혈중알코올농도와 시각을 구하라.','For model C(t)=0.135te^(-2.802t)g/dL,find the maximum mean blood-alcohol concentration during the first3hours and when it occurs.'),fs(r'C\prime(t)=0.135e^{-2.802t}(1-2.802t)',r't_{max}=1/2.802\approx'+f'{t79:.6f}'+r'\text{ h}',r'C_{max}=\frac{0.135}{2.802e}\approx'+f'{max79:.6f}'+r'\text{ g/dL}'),same(M(f'{max79:.6f}'+r'\text{ g/dL at }'+f'{t79:.6f}'+r'\text{ h}')),('닫힌 구간의 끝점0,3과 내부 임계점1/2.802의 함수값을 비교했다.','Compared values at endpoints0,3 and the interior critical point1/2.802.'))
add(80,('축척을 조정한 정규곡선f(x)=e^(-x²/(2σ²)),σ>0에 대해(a)점근선·최대·변곡점,(b)σ의 효과,(c)4개 σ의 그래프를 구하라.','For scaled normal curve f(x)=e^(-x²/(2σ²)),σ>0,find(a)asymptote,maximum,inflections;(b)the effect ofσ;(c)graphs for fourσ values.'),fs(r'f\prime=-\frac{x}{\sigma^2}f,\quad f\prime\prime=\frac{x^2-\sigma^2}{\sigma^4}f',r'\lim_{x\to\pm\infty}f=0,\quad f(0)=1,\quad f(\pm\sigma)=e^{-1/2}')+[('σ가 커지면 수평으로 넓어지지만 이 축척에서는 최대 높이1이 유지된다.','Largerσ stretches the curve horizontally while this scaling keeps its peak height1.')],same(M(r'(a)\ y=0;\ \max f=1\text{ at }0;\ \text{inflections }(\pm\sigma,e^{-1/2});\quad(b)\ x\text{-stretch by }\sigma')),('σ>0이므로 f″의 부호는 x²-σ²가 결정하며 변곡의 두 근 모두 단순하다.','Forσ>0,the sign of f″ is determined by x²-σ²,and both inflection roots are simple.'),list('abc'))
plots(b,80,[('6.2.80 Width controlled by sigma',-6,6,0,1.05,[(f'sigma={sig}',lambda q,sig=sig:math.exp(-q*q/(2*sig*sig)))for sig in[.5,1,1.5,2]])])
# Integrals for the remaining geometric applications, with independent quadrature.
y=s.symbols('y',real=True)
for n,st,v,f,lo,hi in[(94,('x=y²-2와x=e^y 사이에서-1≤y≤1인 영역의 넓이를 구하라.','Find the area between x=y²-2 andx=e^y for-1≤y≤1.'),y,s.exp(y)-(y*y-2),-1,1),(95,('y=eˣ,y=e^(3x),x=1로 둘러싸인 영역의 넓이를 소수3자리까지 구하라.','Find the area bounded by y=eˣ,y=e^(3x),andx=1 to three decimal places.'),x,s.exp(3*x)-s.exp(x),0,1),(97,('y=eˣ,y=0,x=0,x=1로 둘러싸인 영역을x축 회전한 부피를 구하라.','Find the volume obtained by rotating the region under y=eˣ over0≤x≤1 around the x-axis.'),x,P*s.exp(2*x),0,1),(98,('y=e^(-x²),y=0,x=0,x=1의 영역을y축 회전한 부피를 구하라.','Find the volume obtained by rotating the region under y=e^(-x²) over0≤x≤1 around the y-axis.'),x,2*P*x*s.exp(-x*x),0,1)]:
 val=s.simplify(s.integrate(f,(v,lo,hi)));assert abs(mp.quad(s.lambdify(v,f,'mpmath'),[lo,hi])-float(val))<1e-9
 method=('수평 절편의 오른쪽 끝에서 왼쪽 끝을 뺀 폭을 적분한다.','Integrate horizontal width,right minus left.')if n==94 else('곡선 교점x=0에서1까지 위쪽 함수에서 아래쪽 함수를 뺀 높이를 적분한다.','Integrate upper minus lower from the intersectionx=0 tox=1.')if n==95 else('원판 넓이π(eˣ)²를 적분한다.','Integrate disk areaπ(eˣ)².')if n==97 else('반지름x,높이e^(-x²)인 원통껍질을 적분한다.','Integrate cylindrical shells of radiusx and heighte^(-x²).')
 add(n,st,[method]+fs(s.latex(s.Integral(f,(v,lo,hi)))+'='+s.latex(val)),same(M(s.latex(val)+r'\approx'+f'{float(val):.3f}')),('적분 영역의 폭 또는 반지름·높이가 비음수임을 확인하고 독립 수치 적분과 비교했다.','Checked nonnegative widths or radii/heights,and matched independent numerical quadrature.'))
 if n==94:area_svg(b,n,[(-1,1,s.exp(y),y*y-2)],y,'6.2.94 Horizontal area strips')
 elif n==95:area_svg(b,n,[(0,1,s.exp(3*x),s.exp(x))],x,'6.2.95 Bounded area')
 else:area_svg(b,n,[(0,1,s.exp(x)if n==97 else s.exp(-x*x),s.Integer(0))],x,'6.2.'+str(n)+' Generating region')
 b.save()
add(99,('곡선 아래 넓이를 비교하라.e^(√x)와2xeˣ는0≤x≤1,e^(sinx)sin2x는0≤x≤π/2이다.','Compare the areas under e^(√x) and2xeˣ on0≤x≤1,and under e^(sinx)sin2x on0≤x≤π/2.'),fs(r'\int_0^1 e^{\sqrt x}\,dx=\int_0^1 2ue^u\,du\quad(u=\sqrt x)',r'\int_0^{\pi/2}e^{\sin x}\sin2x\,dx=\int_0^1 2ue^u\,du\quad(u=\sin x)',r'\int_0^1 2ue^u\,du=[2(u-1)e^u]_0^1=2'),('세 넓이가 모두2로 같다.','All three areas equal2.'),('두 치환 모두 경계가0과1이고 세 피적분함수는 지정 구간에서 비음수이다.','Both substitutions give bounds0 and1,and all integrands are nonnegative on their intervals.'))
plots(b,99,[('6.2.99 First region profile',0,1,0,3,[('exp(sqrt x)',lambda q:math.exp(math.sqrt(q)))]),('6.2.99 Second region profile',0,1,0,6,[('2x expx',lambda q:2*q*math.exp(q))]),('6.2.99 Third region profile',0,math.pi/2,0,3,[('exp(sinx)sin2x',lambda q:math.exp(math.sin(q))*math.sin(2*q))])])
add(107,('f(x)=(1-e^(1/x))/(1+e^(1/x))를 그리고 기함수임을 증명하라.','Graph f(x)=(1-e^(1/x))/(1+e^(1/x)) and prove it is odd.'),fs(r'f(-x)=\frac{1-e^{-1/x}}{1+e^{-1/x}}=\frac{e^{1/x}-1}{e^{1/x}+1}=-f(x)',r'D=\mathbb R\setminus\{0\}')+[('정의역이 원점 대칭이며 대응하는 함수값의 부호가 반대이다.','The domain is symmetric about0 and the function values reverse sign.')],('기함수이다(x≠0).','It is odd on x≠0.'),('분자·분모에 양수e^(1/x)를 곱한 항등변형이며 정의역을 바꾸지 않았다.','Multiplication by the positive e^(1/x) is an identity that preserves the domain.'))
plots(b,107,[('6.2.107 Negative branch',-5,-.01,-1,1,[('f',lambda q:-math.tanh(1/(2*q)))]),('6.2.107 Positive branch',.01,5,-1,1,[('f',lambda q:-math.tanh(1/(2*q)))])])
add(108,('a>0인 함수족f(x)=1/(1+ae^(bx))의 여러 그래프를 그리고a,b의 효과를 설명하라.','Graph several members of f(x)=1/(1+ae^(bx)),a>0,and explain the effects ofa andb.'),fs(r'f\prime(x)=-\frac{abe^{bx}}{(1+ae^{bx})^2}',r'f(x)=\frac1{1+e^{b(x+\ln(a)/b)}}\quad(b\ne0)',r'x_{inflection}=-\ln(a)/b,\quad f(x_{inflection})=1/2')+[('b가 양수이면 감소,음수이면 증가한다. b의 부호 반전은y축 반사이고 |b|가 클수록 수평 폭이 좁다.b=0이면 상수1/(1+a)이다.','For b>0 curves decrease,for b<0 they increase; changing the sign reflects across the y-axis.Larger|b| compresses the width.For b=0 the function is constant1/(1+a).'),('b를 고정하고a를 늘리면 모든 점의 높이가 내려가며 b가 양수이면 왼쪽,음수이면 오른쪽 평행이동이 된다.','At fixedb,increasinga lowers every value and shifts the curve left forb>0 or right forb<0.')],('b는 방향·폭을,a는 고정된b≠0에서 수평 위치를 결정한다.b=0이면 상수이다.','b controls orientation and width;at fixed nonzero b,a controls horizontal position.b=0 gives a constant.'),('중점 조건ae^(bx)=1,기울기 부호,a에 대한 음의 변화율로 각 효과를 따로 확인했다.','Checked effects separately using ae^(bx)=1,the slope sign,and∂f/∂a<0.'))
plots(b,108,[('6.2.108 Vary b, a=1',-5,5,0,1,[(f'b={k}',lambda q,k=k:1/(1+math.exp(k*q)))for k in[-2,-1,.5,2]]),('6.2.108 Vary a, b=1',-5,5,0,1,[(f'a={c}',lambda q,c=c:1/(1+c*math.exp(q)))for c in[.2,1,5]])])
print('6.2 COMPLETE',len(b.E))

b.E[63]["steps"]["ko"].append("그래프의 거친 눈금 읽기로는 약3.5일로 추정할 수 있다. 위 계산은 인쇄된 회귀 모형을 사용하여 약3.7일을 얻는다.")
b.E[63]["steps"]["en"].append("A rough reading of the graph gives about3.5 additional days. The calculation above uses the printed fitted model and gives about3.7days.")
b.save()
