from calc1_alt_helpers import *
from calc1_plot_helpers import plots
x,t,v,u,th=s.symbols('x t v u theta',real=True);R=s.Rational;b=AltBook('6.4*',[476,477,478])
def pg(n):return 476 if n<=42 else 477 if n<=64 else 478
def add(n,st,steps,ans,ck,parts=[]):
 b.add(n,pg(n),('일반 로그·지수함수','General logarithmic and exponential functions'),st,steps,ans,parts=parts);b.verify(n,*ck);b.save()
def ma(n,eq,ss,ans,ck,parts=[]):add(n,(M(eq)+'계산하거나 증명하라.',M(eq)+'Evaluate or prove.'),fs(*ss),same(M(ans)),ck,parts)
for n,old in[(1,1),(11,3),(12,5),(17,17),(18,18),(20,20),(21,23),(22,24),(63,63),(64,64)]:b.reuse(n,'6.2',old,pg(n))
for n,old in[(7,3),(14,14),(15,15),(16,16),(55,50),(57,33),(58,34)]:b.reuse(n,'6.3',old,pg(n))
for n,old in[(25,17),(26,18),(27,27),(28,28),(31,13),(34,26),(45,85),(48,86),(54,60),(61,98),(65,74),(66,96),(67,99),(68,100)]+[(n,n+16)for n in range(35,43)]:b.reuse(n,'6.4',old,pg(n))
b.E[1]['steps']['ko'].insert(0,M(r'b^x=e^{x\ln b},\quad b>0'));b.E[1]['steps']['en'].insert(0,M(r'b^x=e^{x\ln b},\quad b>0'))
add(2,('b>0,b≠1에서 (a)log_b x의 정의, (b)정의역, (c)치역을 쓰고 (d)b>1인 로그함수와 지수함수를 한 좌표계에 그려라.','For b>0,b≠1, give(a)the definition of log_b x,(b)domain,(c)range,and(d)graphs of logarithm and exponential on common axes for b>1.'),fs(r'y=\log_bx\iff b^y=x',r'D=(0,\infty),\quad R=\mathbb R')+[('두 함수는 서로 역함수이므로 y=x에 대해 반사된다. 로그함수는(1,0), 지수함수는(0,1)을 지나며 b>1에서는 둘 다 증가한다.','They are inverses and reflect across y=x. The logarithm passes through(1,0), the exponential through(0,1), and both increase when b>1.')],same(M(r'\log_bx=y\iff b^y=x;\quad D=(0,\infty),\ R=\mathbb R')),('대응 점(x,y),(y,x)과 두 함수의 양수 입력·출력 조건을 확인했다.','Checked corresponding points(x,y),(y,x) and the positive-input/output restrictions.'),list('abcd'))
plots(b,2,[('Inverse logarithm and exponential: b=2',-2,5,-1,137/45,[('2^x',lambda q:2**q),('log2 x',lambda q:math.log(q,2)),('y=x',lambda q:q)])])
for n,eq,ans,dom in[(3,r'4^{-\pi}',r'e^{-\pi\ln4}',r'4>0'),(4,r'x^{\sqrt5}',r'e^{\sqrt5\ln x}',r'x>0'),(5,r'10^{x^2}',r'e^{x^2\ln10}',r'x\in\mathbb R'),(6,r'(\tan x)^{\sec x}',r'e^{\sec x\ln(\tan x)}',r'\tan x>0')]:ma(n,eq,[r'b^r=e^{r\ln b},\quad b>0',eq+'='+ans+r',\quad '+dom],ans,('밑을 양수로 둔 실수 지수함수의 정의를 그대로 적용했다.','Applied the definition of real exponentiation with a positive base.'))
ma(8,r'(a)\log_{10}\sqrt{10};\quad(b)\log_{10}40+\log_{10}2.5;\quad(c)\log_230-\log_215',[r'(a)\log_{10}(10^{1/2})=1/2',r'(b)\log_{10}(40\cdot2.5)=\log_{10}100=2',r'(c)\log_2(30/15)=\log_22=1'],r'(a)1/2;\quad(b)2;\quad(c)1',('곱·몫 로그법칙을 적용한 뒤 밑의 정수·분수 거듭제곱으로 확인했다.','Applied product/quotient laws and recognized integer or fractional powers of the base.'),list('abc'))
ma(9,r'(a)\log_310-\log_35-\log_318;\quad(b)2\log_5100-4\log_550',[r'(a)\log_3(10/(5\cdot18))=\log_3(1/9)=-2',r'(b)\log_5(100^2/50^4)=\log_5(1/625)=-4'],r'(a)-2;\quad(b)-4',('통합한 로그 입력을 각각3⁻²,5⁻⁴로 확인했다.','Checked the combined arguments as3⁻² and5⁻⁴.'),['a','b'])
ma(10,r'(a)\log_a(1/a);\quad(b)10^{\log_{10}4+\log_{10}7}',[r'(a)\log_a(a^{-1})=-1,\quad a>0,\ a\ne1',r'(b)10^{\log_{10}28}=28'],r'(a)-1;\quad(b)28',('밑 a의 조건을 보존하고 지수·로그의 역관계를 사용했다.','Preserved the base conditions and used the inverse exponential/logarithmic relation.'),['a','b'])
ma(13,r'(a)\log_510;\quad(b)\log_312;\quad(c)\log_{12}6',[r'\log_ba=\ln a/\ln b',r'(a)\ln10/\ln5;\quad(b)\ln12/\ln3;\quad(c)\ln6/\ln12'],fr'(a){float(mp.log(10)/mp.log(5)):.6f};\quad(b){float(mp.log(12)/mp.log(3)):.6f};\quad(c){float(mp.log(6)/mp.log(12)):.6f}',('밑변환을 고정밀 로그로 계산하여 마지막에만 소수점6자리로 반올림했다.','Used high-precision change of base and rounded to six decimal places only at the end.'),list('abc'))
ma(19,r'\text{One coordinate unit}=1\mathrm{in}',[r'(a)\ 2\mathrm{ft}=24\mathrm{in}:\quad24^2\mathrm{in}=48\mathrm{ft}',r'2^{24}\mathrm{in}=2^{24}/63360\mathrm{mi}\approx264.79\mathrm{mi}',r'(b)\ 3\mathrm{ft}=36\mathrm{in}:\quad\log_2x=36\Rightarrow x=2^{36}\mathrm{in}',r'x=2^{36}/63360\mathrm{mi}\approx1084587.701\mathrm{mi}'],r'(a)48\mathrm{ft},\ 264.79\mathrm{mi};\quad(b)1084587.701\mathrm{mi}',('가로축과 세로축 모두 인치 단위이며1마일=63360인치로 변환했다.','Both axes use inches; converted with1mile=63360inches.'),['a','b'])
ma(23,r'\lim_{t\to\infty}2^{-t^2}',[r'2^{-t^2}=e^{-t^2\ln2}',r'-t^2\ln2\to-\infty\Rightarrow2^{-t^2}\to0'],r'0',('ln2>0이므로 지수는 음의 무한대로 간다.','Since ln2>0, the exponent tends to negative infinity.'))
ma(24,r'\lim_{x\to3^+}\log_{10}(x^2-5x+6)',[r'x^2-5x+6=(x-2)(x-3)\to0^+',r'\log_{10}u\to-\infty\quad(u\to0^+)'],r'-\infty',('오른쪽 접근이 로그 입력을 양수로 유지함을 확인했다.','The right-hand approach keeps the logarithm argument positive.'))
for n,f,zz in[(29,s.tan(4**(v*v)),v),(30,(1+10**s.log(u))**6,u),(32,s.log(s.sqrt(x))/s.log(10),x),(33,x*s.log(s.sin(x))/s.log(4),x)]:
 df=s.simplify(s.diff(f,zz));F=s.lambdify(zz,f,'mpmath');DF=s.lambdify(zz,df,'mpmath')
 for q in map(mp.mpf,['.2','.4']):assert abs(mp.diff(F,q)-DF(q))<mp.mpf('1e-20')
 add(n,(M('f='+s.latex(f))+'미분하라.',M('f='+s.latex(f))+'Differentiate.'),fs(r'(b^h)\prime=b^h\ln(b)h\prime,\quad(\log_bh)\prime=h\prime/(h\ln b)',r'f\prime='+s.latex(df)),same(M(s.latex(df))),('원 함수의 독립 수치미분과 결과를 두 허용 입력에서 비교했다.','Compared the result with independent numerical derivatives at two admissible inputs.'))
ma(43,r'y=10^x,\quad(1,10)',[r'y\prime=10^x\ln10\Rightarrow y\prime(1)=10\ln10',r'y-10=10\ln10(x-1)'],r'y=10+10\ln10(x-1)',('접점의 값과 기울기를 각각 대입하여 확인했다.','Verified the contact value and slope separately.'))
f=x**s.cos(x);df=f*(-s.sin(x)*s.log(x)+s.cos(x)/x)
add(44,('f(x)=x^(cosx)의 도함수를 구하고 f,f′의 그래프로 타당성을 확인하라.','Differentiate f(x)=x^(cosx) and compare the graphs of f and f′.'),fs(r'\ln f=\cos x\ln x,\quad x>0',r'f\prime/f=-\sin x\ln x+\cos x/x',r'f\prime=x^{\cos x}(-\sin x\ln x+\cos x/x)'),same(M(s.latex(df))),('로그미분의 두 항은 각각 지수 변화와 밑 변화에서 나온다. 도함수의 부호와 원곡선 증가감소를 비교했다.','The two logarithmic-derivative terms come from changes in exponent and base; compared derivative signs with the original curve’s monotonicity.'))
plots(b,44,[('Variable exponent and derivative',.1,8,-8,8,[('f',s.lambdify(x,f,'math')),('derivative',s.lambdify(x,df,'math'))])])
for n,f,F,zz in[(46,x**5+5**x,x**6/6+5**x/s.log(5),x),(47,s.log(x)/(x*s.log(10)),s.log(x)**2/(2*s.log(10)),x),(49,3**s.sin(th)*s.cos(th),3**s.sin(th)/s.log(3),th),(50,2**x/(2**x+1),s.log(2**x+1)/s.log(2),x)]:
 assert s.simplify(s.diff(F,zz)-f)==0
 ma(n,s.latex(s.Integral(f,zz)),[r'\frac{d}{d'+s.latex(zz)+'}'+s.latex(F)+'='+s.latex(f),r'\int '+s.latex(f)+r'\,d'+s.latex(zz)+'='+s.latex(F)+'+C'],s.latex(F)+'+C',('원시함수를 미분하여 피적분함수와 기호적으로 일치함을 확인했다.','Differentiated the antiderivative and verified symbolic equality with the integrand.'))
add(51,('y=2ˣ, y=5ˣ, x=−1, x=1로 둘러싸인 영역의 넓이를 구하라.','Find the area bounded by y=2ˣ, y=5ˣ, x=−1 and x=1.'),fs(r'2^x=5^x\iff x=0',r'A=\int_{-1}^0(2^x-5^x)dx+\int_0^1(5^x-2^x)dx',r'A=\frac{16}{5\ln5}-\frac1{2\ln2}'),same(M(r'\frac{16}{5\ln5}-\frac1{2\ln2}')),('음수와 양수 구간에서 위아래 곡선이 바뀌므로 원점에서 나누고 수치구적으로 대조했다.','The upper/lower order reverses at zero, so split there and checked numerical quadrature.'))
area_svg(b,51,[(s.S(-1),s.S(0),2**x,5**x),(s.S(0),s.S(1),5**x,2**x)],x,'6.4*.51 Area with reversed boundaries');b.save()
ma(52,r'y=10^{-x},\quad0\le x\le1\quad\text{rotated about the }x\text{-axis}',[r'V=\pi\int_0^1(10^{-x})^2dx=\pi\int_0^1 10^{-2x}\,dx',r'V=\pi\left[\frac{10^{-2x}}{-2\ln10}\right]_0^1=\frac{99\pi}{200\ln10}'],r'99\pi/(200\ln10)',('반지름의 제곱으로 지수가−2x가 됨을 확인하고 수치적분과 비교했다.','Squaring the radius gives exponent−2x; numerical integration agrees.'))
root=mp.findroot(lambda q:2**q-1-3**(-q),mp.mpf('.6'))
add(53,('2ˣ=1+3⁻ˣ의 해를 그래프로 소수점1자리까지 추정하고 그 값을 초기값으로 뉴턴법을 써6자리까지 구하라.','Estimate the solution of2ˣ=1+3⁻ˣ graphically to one decimal place, then use it as the Newton starting value and refine to six decimal places.'),fs(r'F(x)=2^x-1-3^{-x},\quad F\prime=2^x\ln2+3^{-x}\ln3>0',r'x_0=0.6,\quad x_{n+1}=x_n-\frac{2^{x_n}-1-3^{-x_n}}{2^{x_n}\ln2+3^{-x_n}\ln3}',fr'x\approx{float(root):.10f}'),same(M(fr'x\approx{float(root):.6f}')),('F가 엄격히 증가하고0,1에서 부호가 바뀌므로 근은 유일하다. 최종 근을 원 방정식에 대입해 확인했다.','Strict increase and opposite signs at0,1 prove uniqueness; substituted the final root into the original equation.'))
plots(b,53,[('Intersection and Newton seed',0,1,0,2.5,[('2^x',lambda q:2**q),('1+3^-x',lambda q:1+3**(-q))])])
ma(56,r'\lim_{x\to0^+}x^{-\ln x}',[r'x^{-\ln x}=e^{-(\ln x)^2}',r'\ln x\to-\infty\Rightarrow-(\ln x)^2\to-\infty'],r'0',('로그의 제곱 앞 음수 부호를 보존하여 지수의 방향을 확인했다.','Preserved the negative sign before the squared logarithm to determine the exponent’s direction.'))
ma(59,r'L=10\log_{10}(I/I_0),\quad I_0=10^{-12},\quad L=50',[r'I=I_0\cdot10^{L/10}=10^{-12}\cdot10^5=10^{-7}\mathrm{W/m^2}',r'\frac{dL}{dI}=\frac{10}{I\ln10}',r'\left.\frac{dL}{dI}\right|_{L=50}=10^8/\ln10'],r'\frac{10^8}{\ln10}\approx4.3429448\times10^7\ \mathrm{dB}/(\mathrm{W/m^2})',('50dB를 먼저 강도로 바꾼 뒤 미분식에 대입했다. 로그의 기준강도는 상수이다.','First converted50dB to intensity, then substituted into the derivative; the reference intensity is constant.'))
rate=8*mp.mpf('.38')**20*mp.log(mp.mpf('.38'));av=8*(mp.mpf('.38')**20-1)/(20*mp.log(mp.mpf('.38')))
add(60,('광감쇠 모형 I(x)=I₀aˣ,0<a<1이다.(a)I′을 I로 표현하라.(b)I₀=8,a=0.38일 때 깊이20m에서 변화율,(c)표면부터20m까지 평균광도를 구하라.','For I(x)=I₀aˣ,0<a<1,(a)express I′ in terms of I.(b)For I₀=8,a=0.38, find the rate at depth20m.(c)Find average intensity from the surface to20m.'),fs(r'(a)\ I\prime=I_0a^x\ln a=I(x)\ln a',r'(b)\ I\prime(20)=8(0.38)^{20}\ln0.38',r'(c)\ I_{\mathrm{avg}}=\frac1{20}\int_0^{20}8(0.38)^xdx=\frac{8[(0.38)^{20}-1]}{20\ln0.38}'),same(M(fr'(a)I\ln a;\quad(b){float(rate):.8g};\quad(c){float(av):.8f}')),('ln a<0이므로 광도 변화율은 음수이고 평균광도는 두 끝점 값 사이의 양수이다.','Since ln a<0, the intensity rate is negative, and average intensity is positive and between endpoint values.'),list('abc'))
base=mp.mpf('1.01395');coef=mp.mpf('1.43653e9');rates=[coef*base**t*mp.log(base)for t in[20,50,100]]
add(62,('1900년을 t=0으로 둔 역사적 인구 모형 P(t)=1.43653×10⁹·1.01395ᵗ에서1920,1950,2000년의 인구 증가율을 구하라.','For the historical population model P(t)=1.43653×10⁹·1.01395ᵗ with t=0 in1900, find growth rates in1920,1950 and2000.'),fs(r'P\prime(t)=(1.43653\times10^9)(1.01395)^t\ln(1.01395)',r't=20,50,100')+[(f'각 시점의 P′값은 {float(rates[0]):.2f}, {float(rates[1]):.2f}, {float(rates[2]):.2f} 명/년이다.',f'The derivative values are {float(rates[0]):.2f}, {float(rates[1]):.2f}, {float(rates[2]):.2f} people/year.')],same(M(r'1920:\ '+f'{float(rates[0]):.2f}'+r';\quad1950:\ '+f'{float(rates[1]):.2f}'+r';\quad2000:\ '+f'{float(rates[2]):.2f}'+r'\quad\mathrm{people/year}')),('실제 연도를 지수에 넣지 않고1900 이후 경과 연수로 바꾸었다. 이는 주어진 역사적 적합 모형의 변화율이다.','Converted calendar years to years after1900; these are rates of the specified historical fitted model.'))
ma(69,r'b^{x-y}=b^x/b^y,\quad b>0',[r'b^{x-y}=e^{(x-y)\ln b}',r'=e^{x\ln b}/e^{y\ln b}=b^x/b^y'],r'b^{x-y}=b^x/b^y',('양의 밑에 대한 정의와 자연지수함수의 지수법칙을 사용했다.','Used the positive-base definition and the natural exponential law.'))
ma(70,r'(ab)^x=a^xb^x,\quad a,b>0',[r'(ab)^x=e^{x\ln(ab)}=e^{x(\ln a+\ln b)}',r'=e^{x\ln a}e^{x\ln b}=a^xb^x'],r'(ab)^x=a^xb^x',('두 밑의 양수 조건이 로그의 곱 법칙과 실수 거듭제곱을 보장한다.','Positive bases justify the logarithm product law and real exponentiation.'))
ma(71,r'(a)\log_b(xy)=\log_bx+\log_by;\quad(b)\log_b(x/y)=\log_bx-\log_by;\quad(c)\log_b(x^r)=r\log_bx',[r'b>0,\ b\ne1,\ x,y>0;\quad u=\log_bx,\ v=\log_by\Rightarrow x=b^u,y=b^v',r'(a)\ xy=b^{u+v}\Rightarrow\log_b(xy)=u+v',r'(b)\ x/y=b^{u-v}\Rightarrow\log_b(x/y)=u-v',r'(c)\ x^r=(b^u)^r=b^{ru}\Rightarrow\log_b(x^r)=ru\quad(r\in\mathbb R)'],r'\log_b(xy)=u+v,\quad\log_b(x/y)=u-v,\quad\log_b(x^r)=ru',('각 지수법칙을 로그의 역관계로 되돌렸다. 세 번째 법칙의 지수 r는 임의의 실수이다.','Translated each exponent law through the inverse logarithm relation; r in the third law is any real number.'),list('abc'))
# Remove irrelevant old exercise-number boilerplate from the repeated logarithmic-differentiation block.
for n in range(35,43):
 for lang in['ko','en']:b.E[n]['steps'][lang]=[v for v in b.E[n]['steps'][lang]if ('48에서는'not in v if lang=='ko'else'In48'not in v)]
# Complete prompts for the applications introduced as formulas.
b.E[19]['statement']=pair('눈금1단위가1인치이다.(a)x²와2ˣ의 그래프에서 원점 오른쪽2ft의 높이를 각각ft,mi로 구하라.(b)log₂x의 그래프 높이가3ft에 도달하는 가로 거리를mi로 구하라.','One coordinate unit is one inch.(a)For x² and2ˣ, find the heights two feet right of the origin in feet and miles respectively.(b)For log₂x, find the horizontal distance in miles when the height is three feet.')
for n,ko,en in[(3,'e의 거듭제곱으로 나타내라.','Write as a power of e.'),(4,'e의 거듭제곱으로 나타내라.','Write as a power of e.'),(5,'e의 거듭제곱으로 나타내라.','Write as a power of e.'),(6,'e의 거듭제곱으로 나타내라.','Write as a power of e.'),(43,'접선 방정식을 구하라.','Find the tangent line.'),(52,'회전체 부피를 구하라.','Find the volume of revolution.'),(59,'강도에 대한 음량 변화율을 구하라.','Find the rate of loudness change with respect to intensity.')]:
 b.E[n]['statement']['ko']=b.E[n]['statement']['ko'].replace('계산하거나 증명하라.',ko);b.E[n]['statement']['en']=b.E[n]['statement']['en'].replace('Evaluate or prove.',en)
b.save();print('6.4* COMPLETE',len(b.E))
