from calc1_inverse_helpers import *
from calc1_plot_helpers import plots
x=s.symbols('x',real=True);P=s.pi;R=s.Rational;b=CalcBook('6.3',[438,439,440])
def add(n,st,steps,ans,ck,parts=[]):
 b.add(n,438 if n<=17 else 439 if n<=50 else 440,('로그함수','Logarithmic functions'),st,steps,ans,parts=parts);b.verify(n,*ck);b.save()
add(1,('로그함수의(a)정의,(b)정의역,(c)치역,(d)밑b>1인 그래프를 설명하라.','Explain the logarithmic function’s(a)definition,(b)domain,(c)range,and(d)graph for base b>1.'),fs(r'\log_bx=y\Longleftrightarrow b^y=x,\quad b>0,\ b\ne1',r'D=(0,\infty),\quad R=\mathbb R')+[('b>1이면 증가하며(1,0)을 지난다.x=0은 수직점근선이고 그래프는 아래로 오목하다.','For b>1 it increases through(1,0),has vertical asymptote x=0,and is concave down.')],('bˣ의 역함수이며 정의역(0,∞),치역ℝ이다. 밑이1보다 크면 증가한다.','It is the inverse of bˣ,with domain(0,∞),rangeℝ,and increasing graph when the base exceeds1.'),('지수함수의 정의역과 치역을 교환하고(0,1)을(1,0)으로 반사했다.','Exchanged the exponential domain/range and reflected(0,1) to(1,0).'),list('abcd'))
plots(b,1,[('6.3.1 A logarithm with base greater than1',.01,5,-5,3,[('log2x',lambda q:math.log(q,2))])])
add(2,('(a)자연로그,(b)상용로그를 정의하고(c)자연로그와 자연지수함수를 함께 그려라.','Define(a)the natural logarithm,(b)the common logarithm,and(c)graph the natural logarithm with the natural exponential.'),fs(r'\ln x=\log_ex,\quad\log_{10}x\text{ is the common logarithm}')+[('lnx와eˣ는 역함수이므로 같은 축척에서 y=x에 대해 반사된다.','lnx andeˣ are inverses and reflect across y=x on equal-scale axes.')],('(a)밑e의 로그,(b)밑10의 로그.(c)y=x 대칭인 역함수 그래프.','(a)Logarithm with basee.(b)Logarithm with base10.(c)Inverse graphs reflected across y=x.'),('ln(eˣ)=x,e^(lnx)=x(x>0)를 확인했다.','Checked ln(eˣ)=x ande^(lnx)=x for x>0.'),list('abc'))
planeplot(b,2,points(math.exp,-2,2),reflect=True,title='6.3.2 Exponential and natural logarithm');b.save()
exact={3:[(r'\log_3 81',r'\log_3 3^4',4),(r'\log_3(1/81)',r'\log_3 3^{-4}',-4),(r'\log_9 3',r'9^{1/2}=3',R(1,2))],4:[(r'\ln(1/e^2)',r'\ln(e^{-2})',-2),(r'\ln\sqrt e',r'\ln(e^{1/2})',R(1,2)),(r'\ln(\ln(e^{e^{50}}))',r'\ln(e^{50})',50)],5:[(r'\log_2 30-\log_2 15',r'\log_2(30/15)',1),(r'\log_3 10-\log_3 5-\log_3 18',r'\log_3(10/(5\cdot18))=\log_3(1/9)',-2),(r'2\log_5 100-4\log_5 50',r'\log_5(100^2/50^4)=\log_5(5^{-4})',-4)],6:[(r'e^{3\ln2}',r'e^{\ln8}',8),(r'e^{-2\ln5}',r'e^{\ln(1/25)}',R(1,25)),(r'e^{\ln(\ln e^3)}',r'\ln(e^3)',3)]}
for n,parts in exact.items():
 st=r';\quad'.join(f'({chr(97+i)})\ '+p[0]for i,p in enumerate(parts));ans=r';\quad'.join(f'({chr(97+i)})\ '+s.latex(s.sympify(p[2]))for i,p in enumerate(parts))
 add(n,(M(st)+'정확한 값을 구하라.',M(st)+'Find the exact values.'),fs(*[f'({chr(97+i)})\ '+v[0]+'='+v[1]+'='+s.latex(s.sympify(v[2]))for i,v in enumerate(parts)]),same(M(ans)),('지수·로그의 역함수 관계와 곱·몫·거듭제곱 법칙을 적용하고 로그 입력이 양수임을 확인했다.','Used inverse,product,quotient,and power laws and checked positive logarithm arguments.'),list('abc'))
for n,statements,results,domains in[(7,[r'\log_{10}(x^2y^3z)',r'\ln\frac{x^4}{\sqrt{x^2-4}}'],[r'2\log_{10}|x|+3\log_{10}|y|+\log_{10}|z|',r'4\ln|x|-\tfrac12\ln|x-2|-\tfrac12\ln|x+2|'],[r'x\ne0,\ yz>0',r'|x|>2']),(8,[r'\ln\sqrt{\frac{3x}{x-3}}',r'\log_2[(x^3+1)\sqrt[3]{(x-3)^2}]'],[r'\tfrac12\ln3+\tfrac12\ln|x|-\tfrac12\ln|x-3|',r'\log_2(x+1)+\log_2(x^2-x+1)+\tfrac23\log_2|x-3|'],[r'x<0\text{ or }x>3',r'x>-1,\ x\ne3'])]:
 add(n,(M(r';\quad'.join(f'({chr(97+i)})\ '+q for i,q in enumerate(statements)))+'로그 법칙으로 전개하라.',M(r';\quad'.join(f'({chr(97+i)})\ '+q for i,q in enumerate(statements)))+'Expand using logarithm laws.'),[('원래 식의 전체 실수 정의역을 보존하도록 절댓값을 사용한다. 변수가 양수이면 절댓값을 생략할 수 있다.','Use absolute values to preserve the original full real domain; they may be omitted when variables are positive.')]+fs(*[f'({chr(97+i)})\ '+statements[i]+'='+results[i]+r',\quad '+domains[i]for i in range(2)]),same(M(r';\quad'.join(f'({chr(97+i)})\ '+q for i,q in enumerate(results)))),('로그를 다시 합치면 원래 양의 입력이 되며 x²-4=(x-2)(x+2),x³+1=(x+1)(x²-x+1)을 사용했다.','Recombining the logs recovers the original positive arguments,using x²-4=(x-2)(x+2) andx³+1=(x+1)(x²-x+1).'),['a','b'])
for n,st,ans,why in[(9,[r'\log_{10}20-\tfrac13\log_{10}1000',r'\ln a-2\ln b+3\ln c'],[r'\log_{10}2',r'\ln(ac^3/b^2)'],r'1000^{1/3}=10;\quad a,b,c>0'),(10,[r'\ln10+2\ln5',r'\log_{10}4+\log_{10}a-\tfrac13\log_{10}(a+1)'],[r'\ln250',r'\log_{10}\frac{4a}{\sqrt[3]{a+1}}'],r'10\cdot5^2=250;\quad a>0'),(11,[r'3\ln(x-2)-\ln(x^2-5x+6)+2\ln(x-3)',r'c\log_ax-d\log_ay+\log_az'],[r'\ln[(x-2)^2(x-3)]',r'\log_a(x^cz/y^d)'],r'(a)\ x>3;\quad(b)\ x,y,z>0,\ a>0,\ a\ne1')]:
 add(n,(M(r';\quad'.join(f'({chr(97+i)})\ '+q for i,q in enumerate(st)))+'각각 하나의 로그로 합쳐라.',M(r';\quad'.join(f'({chr(97+i)})\ '+q for i,q in enumerate(st)))+'Combine each as one logarithm.'),[('계수를 지수로 옮기고 덧셈을 곱셈,뺄셈을 나눗셈으로 바꾼다.','Move coefficients to exponents,then turn sums into products and differences into quotients.')]+fs(why,*[f'({chr(97+i)})\ '+st[i]+'='+ans[i]for i in range(2)]),same(M(r';\quad'.join(f'({chr(97+i)})\ '+q for i,q in enumerate(ans)))),('합친 식에는 원래 로그식의 정의역을 유지한다. 특히11(a)는 x>3을 보존한다.','The combined expression retains the original logarithmic domain;in particular11(a) keeps x>3.'),['a','b'])
for n,data in[(12,[(5,10),(15,12)]),(13,[(3,12),(12,6)])]:
 vals=[math.log(q)/math.log(base)for base,q in data];add(n,(M(r';\quad'.join(f'({chr(97+i)})\\log_{{{base}}}{q}'for i,(base,q)in enumerate(data)))+'밑변환으로 소수6자리까지 구하라.',M(r';\quad'.join(f'({chr(97+i)})\\log_{{{base}}}{q}'for i,(base,q)in enumerate(data)))+'Use change of base to six decimal places.'),fs(r'\log_ba=\ln a/\ln b',*[fr'({chr(97+i)})\ \ln({q})/\ln({base})\approx{vals[i]:.6f}'for i,(base,q)in enumerate(data)]),same(M(r';\quad'.join(f'({chr(97+i)})\ {val:.6f}'for i,val in enumerate(vals)))),('반올림 전 결과를 밑의 지수에 대입하면 원래 입력이 복원된다.','Raising the base to the unrounded result recovers the original argument.'),['a','b'])
for n,bases in[(14,[2,4,6,8]),(15,[1.5,math.e,10,50])]:
 add(n,('밑이'+str(bases)+'인 로그함수를 같은 좌표에 그리고 관계를 설명하라.','Graph logarithms with bases'+str(bases)+' on common axes and describe their relation.'),fs(r'\log_bx=\ln x/\ln b')+[('모두(1,0)을 지나며 증가한다.x>1에서 밑이 클수록 낮고0<x<1에서 순서가 반대이다.','All increase through(1,0);for x>1 larger bases lie lower,with reversed ordering for0<x<1.')],('자연로그의 수직 축척 변환이며 밑이 클수록 기울기가 작다.','They are vertical rescalings of the natural logarithm;larger bases give smaller slopes.'),('각 함수의 ln x 계수1/ln b가 양수이고 밑이 클수록 작아짐을 비교했다.','Compared the positive coefficient1/ln b,which decreases as the base increases.'))
 plots(b,n,[(f'6.3.{n} Logarithm base comparison',.01,6,-4,4,[(f'base={base:.4g}',lambda q,base=base:math.log(q)/math.log(base))for base in bases])])
add(16,('lnx,log₈x,eˣ,8ˣ를 함께 그리고 관계를 설명하라.','Graph lnx,log₈x,eˣ,and8ˣ together and describe their relationships.'),fs(r'\log_8x=\ln x/\ln8',r'\ln(e^x)=x,\quad\log_8(8^x)=x')+[('같은 밑의 로그와 지수는 y=x에 대칭이다. ln8>1이므로 log₈x는lnx를 수직 축소한 것이다.','Each same-base logarithm/exponential pair reflects across y=x;because ln8>1,log₈x is a vertical compression of lnx.')],('lnx↔eˣ,log₈x↔8ˣ가 각각 역함수이다.','lnx↔eˣ andlog₈x↔8ˣ are inverse pairs.'),('두 합성의 항등관계를 대입하고 기준점(1,0),(0,1)을 확인했다.','Checked both identity compositions and reference points(1,0),(0,1).'))
plots(b,16,[('6.3.16 Logarithms and exponentials',-2,6,-1,-1+8*260/450,[('lnx',math.log),('log8x',lambda q:math.log(q,8)),('expx',math.exp),('8^x',lambda q:8**q),('y=x',lambda q:q)])])
add(17,('좌표1단위가1인치인 y=log₂x의 높이가3ft가 되는 수평거리를 마일로 구하라.','On y=log₂x with one unit equal to one inch,find the horizontal distance in miles when height reaches3ft.'),fs(r'\log_2x=36\Rightarrow x=2^{36}\text{ in}',r'\frac{2^{36}}{12\cdot5280}\approx1084587.73\text{ mi}'),('약1,084,588마일.','About1,084,588miles.'),('높이3ft를36인치로 먼저 바꾼 뒤 x에 해당하는 인치 거리를 마일로 환산했다.','First converted3ft to36inches,then converted the horizontal distance from inches to miles.'))
print('6.3 first17',len(b.E))
t18=float(mp.findroot(lambda q:mp.exp(q/10)-q,(35,36)));x18=math.exp(t18)
add(18,('x^0.1과lnx를 여러 창에서 비교하라.x^0.1이 최종적으로lnx를 앞서는x를 추정하라.','Compare x^0.1 andlnx in several windows and estimate where x^0.1 finally overtakes lnx.'),fs(r't=\ln x,\quad e^{t/10}=t',r't\approx'+f'{t18:.8f}'+r',\quad x=e^t\approx'+f'{x18:.6g}')+[('큰 교점 이후 e^(t/10)-t의 도함수는 양수이고 계속 증가한다.','After the larger crossing,the derivative of e^(t/10)-t is positive and increasing.')],same(M(r'x\gtrsim'+f'{x18:.4g}')),('큰 근의 방정식 잔차를 확인하고 그 오른쪽의 단조성으로 최종 교점임을 확인했다.','Checked the root residual and monotonicity to its right to establish the final crossing.'))
plots(b,18,[('6.3.18 Small window',.01,10,-5,3,[('x^0.1',lambda q:q**.1),('lnx',math.log)]),('6.3.18 Final crossover',1e15,6e15,34,38,[('x^0.1',lambda q:q**.1),('lnx',math.log)])])
for n,st,ans,panels in[(19,('y=log₁₀(x+5)와y=-lnx의 개형을 그려라.','Sketch y=log₁₀(x+5) andy=-lnx.'),('(a)x절편-4,수직점근선x=-5,증가.(b)x절편1,점근선x=0,감소.','(a)x-intercept-4,vertical asymptote x=-5,increasing.(b)x-intercept1,asymptote x=0,decreasing.'),[('6.3.19a Shifted common log',-4.99,5,-2,2,[('log10(x+5)',lambda q:math.log10(q+5))]),('6.3.19b Reflected natural log',.01,5,-2,5,[('-lnx',lambda q:-math.log(q))])]),(20,('y=ln(-x)와y=ln|x|의 개형을 그려라.','Sketch y=ln(-x) andy=ln|x|.'),('(a)lnx를y축 반사,정의역x<0.(b)양쪽 반사를 합친 우함수,정의역x≠0. 둘 다 수직점근선x=0.','(a)Reflect lnx across the y-axis,domain x<0.(b)Combine both reflected branches,an even function on x≠0.Both have vertical asymptote x=0.'),[('6.3.20a Negative-input logarithm',-5,-.01,-5,2,[('ln(-x)',lambda q:math.log(-q))]),('6.3.20b Even logarithm',-5,5,-5,2,[('ln|x|',lambda q:math.log(abs(q)))])])]:
 add(n,st,[('입력 이동 또는 부호 반전과 출력 부호 반전을 기본ln 그래프에 적용한다.','Apply input shifts/sign changes or output sign changes to a basic logarithm graph.'),ans],ans,('로그 입력이 양수인 구간과 입력이1인 영점,0⁺로 가는 점근선을 확인했다.','Checked positive-argument domains,zeros where the argument is1,and asymptotes where it tends to0⁺.'),['a','b']);plots(b,n,panels)
for n,expr,domain,root,lo,hi in[(21,s.log(x)+2,r'(0,\infty)',s.exp(-2),.01,5),(22,s.log(x-1)-1,r'(1,\infty)',1+s.E,1.01,7)]:
 add(n,(M('f(x)='+s.latex(expr))+'(a)정의역·치역,(b)x절편,(c)개형을 구하라.',M('f(x)='+s.latex(expr))+'Find(a)domain/range,(b)x-intercept,(c)graph.'),fs(r'D='+domain+r',\quad R=\mathbb R',r'f(x)=0\Longleftrightarrow x='+s.latex(root))+[('자연로그를 식에 주어진 만큼 평행이동한다.','Translate the natural logarithm as indicated in the formula.')],same(M(r'D='+domain+r',\ R=\mathbb R;\quad x='+s.latex(root))),('계산한 절편을 원래 함수에 대입하면0이고 로그 입력도 양수이다.','Substitution of the intercept yields0 with a positive logarithm argument.'),list('abc'))
 plots(b,n,[(f'6.3.{n} Shifted logarithm',lo,hi,-5,4,[('f(x)',s.lambdify(x,expr,'math'))])])
solves={23:[(r'\ln(4x+2)=3',r'4x+2=e^3',[(s.E**3-2)/4]),(r'e^{2x-3}=12',r'2x-3=\ln12',[(3+s.log(12))/2])],24:[(r'\log_2(x^2-x-1)=2',r'x^2-x-1=4',[(1-s.sqrt(21))/2,(1+s.sqrt(21))/2]),(r'1+e^{4x+1}=20',r'4x+1=\ln19',[(s.log(19)-1)/4])],25:[(r'\ln x+\ln(x-1)=0',r'x(x-1)=1,\quad x>1',[(1+s.sqrt(5))/2]),(r'5^{1-2x}=9',r'(1-2x)\ln5=\ln9',[(1-s.log(9)/s.log(5))/2])],26:[(r'\ln(\ln x)=0',r'\ln x=1',[s.E]),(r'60/(1+e^{-x})=4',r'e^{-x}=14',[-s.log(14)])],27:[(r'e^{2x}-3e^x+2=0',r'(e^x-1)(e^x-2)=0',[0,s.log(2)]),(r'e^{e^x}=10',r'e^x=\ln10',[s.log(s.log(10))])],29:[(r'\ln(1+x^3)-4=0',r'x^3=e^4-1',[(s.E**4-1)**R(1,3)]),(r'2e^{1/x}=42',r'1/x=\ln21',[1/s.log(21)])],30:[(r'2^{1-3x}=99',r'(1-3x)\ln2=\ln99',[(1-s.log(99)/s.log(2))/3]),(r'\ln((x+1)/x)=2',r'1+1/x=e^2',[1/(s.E**2-1)])]}
for n,data in solves.items():
 dec=4 if n>=29 else 3;step=[];answers=[]
 for i,(eq,mid,roots)in enumerate(data):
  label=f'({chr(97+i)})';sol=','.join(s.latex(s.sympify(q))for q in roots);approx=','.join(f'{float(q):.{dec}f}'for q in roots);step+=fs(label+r'\ '+eq+r'\Rightarrow '+mid,label+r'\ x\in\{'+sol+r'\}');answers.append(label+r'\ x='+sol+(r'\approx'+approx if n!=27 else''))
 add(n,(M(r';\quad'.join(f'({chr(97+i)})\ '+d[0]for i,d in enumerate(data)))+'실수 해를 구하라. 필요한 근삿값도 제시하라.',M(r';\quad'.join(f'({chr(97+i)})\ '+d[0]for i,d in enumerate(data)))+'Solve over the reals and provide the requested decimal approximations.'),step,same(M(r';\quad'.join(answers))),('지수·로그의 일대일 성질로 식을 되풀고 원래 로그의 양의 입력 조건을 적용해 허근을 제외했다.','Used one-to-one exponential/logarithmic identities and enforced the original positive-argument conditions to remove extraneous roots.'),['a','b'])
add(28,('(a)e^(3x+1)=k,(b)log₂(mx)=c를 실수에서 풀고 매개변수 조건을 적어라.','Solve(a)e^(3x+1)=k and(b)log₂(mx)=c over the reals,including parameter conditions.'),fs(r'(a)\ 3x+1=\ln k\Rightarrow x=(\ln k-1)/3\quad(k>0)',r'(b)\ mx=2^c\Rightarrow x=2^c/m\quad(m\ne0)')+[('k≤0 또는m=0이면 해당 방정식의 실수 해가 없다.','There is no real solution in the respective case k≤0 orm=0.')],same(M(r'(a)\ (\ln k-1)/3\ (k>0);\quad(b)\ 2^c/m\ (m\ne0)')),('지수함수의 출력은 양수이며(b)의 해는 m이 음수여도 mx=2^c>0을 만족한다.','Exponential outputs are positive,and the solution in(b) satisfies mx=2^c>0 even for negative m.'),['a','b'])
add(31,('(a)lnx<0,(b)eˣ>5를 풀어라.','Solve(a)lnx<0 and(b)eˣ>5.'),fs(r'(a)\ \ln x<\ln1\Rightarrow0<x<1',r'(b)\ e^x>e^{\ln5}\Rightarrow x>\ln5'),same(M(r'(a)\ 0<x<1;\quad(b)\ x>\ln5')),('ln과exp는 엄격히 증가하며(a)에는 정의역x>0을 함께 적용한다.','Both ln andexp strictly increase,and(a) also enforces x>0.'),['a','b'])
add(32,('(a)1<e^(3x-1)<2,(b)1-2lnx<3를 풀어라.','Solve(a)1<e^(3x-1)<2 and(b)1-2lnx<3.'),fs(r'(a)\ 0<3x-1<\ln2\Rightarrow\tfrac13<x<\tfrac{1+\ln2}3',r'(b)\ -2\ln x<2\Rightarrow\ln x>-1\Rightarrow x>e^{-1}'),same(M(r'(a)\ (1/3,(1+\ln2)/3);\quad(b)\ (e^{-1},\infty)')),('음수-2로 나누는 단계에서 부등호 방향을 뒤집고 열린 경계를 유지했다.','Reversed the inequality when dividing by-2 and retained open endpoints.'),['a','b'])
print('6.3 authored',len(b.E))
add(33,('리히터 규모M=log₁₀(I/S)이다. 규모7.1 지진보다16배 강한 지진의 규모를 구하라.','Richter magnitude is M=log₁₀(I/S).Find the magnitude of an earthquake16times as intense as one of magnitude7.1.'),fs(r'M_2-M_1=\log_{10}(I_2/I_1)=\log_{10}16',r'M_2=7.1+\log_{10}16\approx8.30412'),('약8.3.','About8.3.'),('같은 기준강도S가 비에서 소거되고 규모 차는 강도 비의 상용로그이다.','The common reference S cancels,and the magnitude difference is the common logarithm of the intensity ratio.'))
add(34,('소리 크기L=10log₁₀(I/I0)이다.120dB 음악과106dB 기계 소음의 강도 비를 구하라.','Sound level is L=10log₁₀(I/I0).Find the intensity ratio of120dB music to106dB machinery noise.'),fs(r'120-106=10\log_{10}(I_1/I_2)',r'I_1/I_2=10^{14/10}=10^{1.4}\approx25.1189'),('약25.1배.','About25.1times.'),('비의 로그를10배하면 원래14dB 차이가 복원된다.','Ten times the logarithm of the ratio reproduces the14dB difference.'))
add(35,('n=100·2^(t/3),t≥0인 세균 모형의(a)역함수와 뜻,(b)50000마리 도달시간을 구하라.','For bacteria model n=100·2^(t/3),t≥0,find(a)the inverse and its meaning,(b)time to50000bacteria.'),fs(r'n/100=2^{t/3}\Rightarrow t=3\log_2(n/100),\quad n\ge100',r't(50000)=3\log_2 500\approx26.89735\text{ h}')+[('역함수는 주어진 개체 수까지 걸린 시간을 반환한다.','The inverse returns elapsed time to a specified population.')],same(M(r't(n)=3\ln(n/100)/\ln2;\quad t(50000)\approx26.897\text{ h}')),('역함수를 원래 식에 넣으면n이 복원되며 t=0에서n=100이다.','Substituting the inverse into the original model recovers n,andt=0 givesn=100.'),['a','b'])
add(36,('재충전 모형Q(t)=Q0(1-e^(-t/a)),t≥0,a>0에 대해(a)역함수와 뜻,(b)a=50에서90% 충전시간을 구하라.','For recharge model Q(t)=Q0(1-e^(-t/a)),t≥0,a>0,find(a)the inverse and interpretation,(b)time to90% when a=50.'),fs(r'1-Q/Q_0=e^{-t/a}\Rightarrow t=-a\ln(1-Q/Q_0),\quad0\le Q<Q_0',r't(0.9Q_0)=-50\ln0.1=50\ln10\approx115.1293\text{ s}')+[('목표 전하까지 필요한 시간을 나타낸다. 용량Q0에는 유한 시간에 도달하지 않는다.','It gives the time needed to reach a target charge;full capacityQ0 is approached only asymptotically.')],same(M(r't(Q)=-a\ln(1-Q/Q_0);\quad t_{90\%}=50\ln10\approx115.129\text{ s}')),('계산한 시간을 넣으면 e^(-t/50)=0.1이므로 정확히Q=0.9Q0이다.','Substitution gives e^(-t/50)=0.1,soQ=0.9Q0 exactly.'),['a','b'])
for n,expr,at,direction,ans,why in[(37,s.log(s.sqrt(x)-1),1,'+',-s.oo,('로그 입력이0⁺로 접근한다.','The logarithm argument approaches0⁺.')),(38,s.log(8*x-x**4)/s.log(5),2,'-',-s.oo,('8x-x⁴=x(2-x)(x²+2x+4)가 왼쪽에서0⁺로 간다.','8x-x⁴=x(2-x)(x²+2x+4) tends to0⁺ from the left.')),(39,s.log(s.cos(x)),0,'+',0,('cosx→1이며0 근처에서 양수이다.','cosx tends to1 and is positive near0.')),(40,s.log(s.sin(x)),0,'+',-s.oo,('sinx→0⁺이므로 로그는-∞로 간다.','sinx tends to0⁺,so its logarithm tends to-∞.')),(41,s.log(1+x*x)-s.log(1+x),s.oo,'-',s.oo,('로그를 합친 입력(1+x²)/(1+x)가∞로 간다.','The combined logarithm argument(1+x²)/(1+x) tends to∞.')),(42,s.log(2+x)-s.log(1+x),s.oo,'-',0,('로그를 합친 입력(2+x)/(1+x)가1로 간다.','The combined logarithm argument(2+x)/(1+x) tends to1.'))]:
 assert s.limit(expr,x,at,dir=direction)==ans
 side=''if n in[39,41,42]else('^+'if direction=='+'else'^-');eq=r'\lim_{x\to'+s.latex(at)+side+'}'+s.latex(expr)
 add(n,(M(eq)+'극한을 구하라.',M(eq)+'Find the limit.'),[why]+fs(eq+'='+s.latex(ans)),same(M(s.latex(ans))),('로그 입력의 부호와 접근 방향을 먼저 확인하고 독립 기호 극한으로 대조했다.','Checked the logarithm argument’s sign and approach direction,then compared an independent symbolic limit.'))
for n,eq,condition,domain in[(43,r'f(x)=\ln(4-x^2)',r'4-x^2>0\Longleftrightarrow-2<x<2',r'(-2,2)'),(44,r'g(x)=\log_2(x^2+3x)',r'x(x+3)>0\Longleftrightarrow x<-3\text{ or }x>0',r'(-\infty,-3)\cup(0,\infty)')]:
 add(n,(M(eq)+'정의역을 구하라.',M(eq)+'Find the domain.'),[('로그의 입력이 엄격히 양수인 조건을 푼다.','Solve the condition that the logarithm argument is strictly positive.')]+fs(condition),same(M(domain)),('입력이0인 경계는 제외하고 각 인수의 부호표로 허용 구간을 확인했다.','Excluded zero-argument endpoints and checked admissible intervals using factor signs.'))
invrecords={45:(r'\sqrt{3-e^{2x}}',r'(-\infty,\tfrac12\ln3]',r'\tfrac12\ln(3-x^2)',r'[0,\sqrt3)',r'y^2=3-e^{2x}\Rightarrow e^{2x}=3-y^2',lambda q:math.sqrt(3-math.exp(2*q)),lambda q:math.log(3-q*q)/2,[-1,0,.4]),46:(r'\ln(2+\ln x)',r'(e^{-2},\infty)',r'e^{e^x-2}',r'\mathbb R',r'e^y=2+\ln x\Rightarrow x=e^{e^y-2}',lambda q:math.log(2+math.log(q)),lambda q:math.exp(math.exp(q)-2),[.2,1,4]),47:(r'\ln(e^x-3)',r'(\ln3,\infty)',r'\ln(e^x+3)',r'\mathbb R',r'e^y=e^x-3\Rightarrow x=\ln(e^y+3)',lambda q:math.log(math.exp(q)-3),lambda q:math.log(math.exp(q)+3),[1.2,2,3]),49:(r'3\ln(x-2)',r'(2,\infty)',r'2+e^{x/3}',r'\mathbb R',r'y/3=\ln(x-2)\Rightarrow x=2+e^{y/3}',lambda q:3*math.log(q-2),lambda q:2+math.exp(q/3),[2.2,3,4]),50:(r'\log_4(x^3+2)',r'(-\sqrt[3]2,\infty)',r'\sqrt[3]{4^x-2}',r'\mathbb R',r'4^y=x^3+2\Rightarrow x=\sqrt[3]{4^y-2}',lambda q:math.log(q**3+2,4),lambda q:math.copysign(abs(4**q-2)**(1/3),4**q-2),[-1,0,2]),51:(r'e^{1-x}',r'\mathbb R',r'1-\ln x',r'(0,\infty)',r'\ln y=1-x\Rightarrow x=1-\ln y',lambda q:math.exp(1-q),lambda q:1-math.log(q),[-2,0,3]),52:(r'(\ln x)^2,\quad x\ge1',r'[1,\infty)',r'e^{\sqrt x}',r'[0,\infty)',r'\ln x\ge0\Rightarrow\ln x=\sqrt y\Rightarrow x=e^{\sqrt y}',lambda q:math.log(q)**2,lambda q:math.exp(math.sqrt(q)),[1,2,4]),53:(r'3^{2x-4}',r'\mathbb R',r'2+\tfrac12\log_3x',r'(0,\infty)',r'\log_3y=2x-4\Rightarrow x=2+\tfrac12\log_3y',lambda q:3**(2*q-4),lambda q:2+math.log(q,3)/2,[-1,0,2]),54:(r'\frac{1-e^{-x}}{1+e^{-x}}',r'\mathbb R',r'\ln\frac{1+x}{1-x}',r'(-1,1)',r'e^{-x}=\frac{1-y}{1+y}\Rightarrow x=\ln\frac{1+y}{1-y}',lambda q:math.tanh(q/2),lambda q:math.log((1+q)/(1-q)),[-2,0,2])}
for n,(eq,dom,inv,idom,alg,f,g,samples)in invrecords.items():
 for q in samples:assert abs(g(f(q))-q)<1e-8,(n,q)
 add(n,(M('f(x)='+eq)+'역함수를 구하라. 원래 함수와 역함수의 정의역도 적어라.',M('f(x)='+eq)+'Find the inverse,including the original and inverse domains.'),fs(r'D_f='+dom,alg,r'f^{-1}(x)='+inv+r',\quad D_{f^{-1}}='+idom)+[('원래 치역이 역함수 정의역이다. 제곱근이나 세제곱근은 원래 정의역에 맞는 실수 가지를 선택한다.','The original range is the inverse domain;choose the real root branch consistent with the original domain.')],same(M(r'D_f='+dom+r';\quad f^{-1}(x)='+inv+r',\ D_{f^{-1}}='+idom)),('서로 다른 허용 입력 세 개에서 g(f(x))=x를 검산하고 경계값의 포함 여부도 확인했다.','Verified g(f(x))=x at three distinct admissible inputs and checked endpoint inclusion.'),['a','b']if n<=47 else[])
add(48,('(a)e^(ln300),ln(e^300)의 정확한 값,(b)계산기 결과와 유한 정밀도·범위의 영향을 설명하라.','Find(a)the exact values ofe^(ln300) andln(e^300),(b)explain calculator output and finite-precision/range effects.'),fs(r'e^{\ln300}=300,\quad\ln(e^{300})=300',r'e^{300}\approx1.942426395\times10^{130}')+[('첫 식은 반올림으로300과 아주 조금 다를 수 있다. 둘째 식은 지수 범위가 작은 계산기에서 중간값e^300이 넘쳐 오류가 날 수 있지만, 이를 지원하는 계산기는300을 돌려준다.','The first may differ minutely from300 by rounding.The second may overflow at intermediatee^300 on a limited-range calculator;one that supports it returns300.')],('(a)둘 다300.(b)기기에 따라 반올림 또는 중간 계산 범위 초과가 생길 수 있다.','(a)Both equal300.(b)Depending on the device,rounding or intermediate overflow may occur.'),('수학적 역함수 항등식과 기계의 중간값 범위 제한을 구별했다.e^300은 임의 정밀도 계산에서 정상 계산된다.','Distinguished exact inverse identities from machine intermediate-range limits;e^300 is computable in arbitrary precision.'),['a','b'])
add(55,('f(x)=e^(3x)-eˣ가 증가하는 구간을 구하라.','Find where f(x)=e^(3x)-eˣ is increasing.'),fs(r'f\prime(x)=e^x(3e^{2x}-1)',r'f\prime>0\Longleftrightarrow e^{2x}>1/3\Longleftrightarrow x>-\tfrac12\ln3'),same(M(r'(-\tfrac12\ln3,\infty)')),('양의 인자eˣ로 나누어 부호를 보존했고 경계 양쪽의 도함수 부호를 확인했다.','Dividing by positiveeˣ preserves the sign;checked derivative signs across the boundary.'))
add(56,('y=2eˣ-e^(-3x)가 아래로 오목한 구간을 구하라.','Find where y=2eˣ-e^(-3x) is concave down.'),fs(r'y\prime\prime=2e^x-9e^{-3x}',r'y\prime\prime<0\Longleftrightarrow e^{4x}<9/2\Longleftrightarrow x<\tfrac14\ln(9/2)'),same(M(r'(-\infty,\tfrac14\ln(9/2))')),('양의e^(3x)를 곱하여 부등식 방향을 유지했고2계 도함수의 영점을 재확인했다.','Multiplied by positivee^(3x),preserving the inequality,and rechecked the second-derivative zero.'))
add(57,('f(x)=ln(x+√(x²+1))의(a)기함수 성질을 보이고,(b)역함수를 구하라.','For f(x)=ln(x+√(x²+1)),(a)prove oddness,(b)find the inverse.'),fs(r'(\sqrt{x^2+1}+x)(\sqrt{x^2+1}-x)=1',r'f(-x)=\ln\frac1{x+\sqrt{x^2+1}}=-f(x)',r'e^y=x+\sqrt{x^2+1},\quad e^{-y}=\sqrt{x^2+1}-x',r'x=(e^y-e^{-y})/2'),same(M(r'(a)\ f(-x)=-f(x);\quad(b)\ f^{-1}(x)=\frac{e^x-e^{-x}}2,\quad D=\mathbb R')),('√(x²+1)>|x|이므로 로그 입력이 항상 양수이다. 두 지수식의 차로 제곱에서 생길 허근 없이 역함수를 구했다.','Since√(x²+1)>|x|,the logarithm argument is always positive.Subtracting the exponential identities finds the inverse without introducing squared-equation extraneous roots.'),['a','b'])
add(58,('y=e^(-x)의 접선 중 직선2x-y=8과 수직인 것을 구하라.','Find the tangent toe^(-x) perpendicular to2x-y=8.'),fs(r'm_{given}=2\Rightarrow m_{tangent}=-1/2',r'-e^{-x}=-1/2\Rightarrow x=\ln2,\quad y=1/2',r'y-1/2=-\tfrac12(x-\ln2)'),same(M(r'y=-\frac{x}{2}+\frac{1+\ln2}{2}')),('두 기울기 곱이-1이고 접점(ln2,1/2)은 원래 지수곡선 위에 있다.','The slopes multiply to-1,and the contact point(ln2,1/2) lies on the exponential curve.'))
add(59,('x^(1/lnx)=2가 해를 갖지 않음을 보이고 f(x)=x^(1/lnx)를 설명하라.','Show x^(1/lnx)=2 has no solution and describe f(x)=x^(1/lnx).'),fs(r'D=(0,1)\cup(1,\infty)',r'x^{1/\ln x}=e^{(1/\ln x)\ln x}=e\ne2'),('해 없음. 정의역 전체에서 상수e이며x=1에는 구멍이 있다.','No solution.The function is constantlye on its domain,with a hole atx=1.'),('로그 입력x>0과 분모lnx≠0을 먼저 적용했다. 상수로 단순화해도 원래 제외된1은 복원되지 않는다.','First enforcedx>0 andlnx≠0;constant simplification does not restore the excluded input1.'))
add(60,('e의 거듭제곱으로 바꾸어 극한을 구하라.(a)x→∞에서x^(lnx),(b)x→0⁺에서x^(-lnx),(c)x→0⁺에서x^(1/x),(d)x→∞에서(ln2x)^(-lnx).','Rewrite as powers ofe and find limits:(a)x^(lnx) asx→∞,(b)x^(-lnx) asx→0⁺,(c)x^(1/x) asx→0⁺,(d)(ln2x)^(-lnx) asx→∞.'),fs(r'(a)\ e^{(\ln x)^2}\to\infty',r'(b)\ e^{-(\ln x)^2}\to0',r'(c)\ e^{(\ln x)/x}\to0',r'(d)\ e^{-(\ln x)\ln(\ln2x)}\to0'),same(M(r'(a)\ \infty;\quad(b)\ 0;\quad(c)\ 0;\quad(d)\ 0')),('각 접근 구간에서 밑이 양수이고 지수가 각각+∞,-∞,-∞,-∞로 감을 확인했다.','Checked positive bases near each limit and exponent limits+∞,-∞,-∞,-∞ respectively.'),list('abcd'))
add(61,('b>1일 때 극한의 정의로(a)x→-∞에서bˣ→0,(b)x→∞에서bˣ→∞를 증명하라.','For b>1,use limit definitions to prove(a)bˣ→0 asx→-∞ and(b)bˣ→∞ asx→∞.'),fs(r'(a)\ \varepsilon>0:\quad N=\log_b\varepsilon,\quad x<N\Rightarrow0<b^x<\varepsilon',r'(b)\ M>0:\quad N=\log_bM,\quad x>N\Rightarrow b^x>M')+[('밑b>1인 지수함수의 단조성으로 정의에 요구된 임계값N을 직접 구성했다.','Constructed each thresholdN explicitly using monotonicity of the exponential withb>1.')],same(M(r'(a)\ \lim_{x\to-\infty}b^x=0;\quad(b)\ \lim_{x\to\infty}b^x=\infty')),('ε와M이 임의의 양수라는 양화 조건을 유지하고 각각 필요한 방향의x 경계를 제시했다.','Keptε andM arbitrary positive and supplied the required x threshold in each direction.'),['a','b'])
add(62,('속도v(t)=ce^(-kt),c,k>0이다.(a)가속도가 속도에 비례함,(b)c의 뜻,(c)초기 속도의 절반이 되는 시각을 구하라.','Velocity isv(t)=ce^(-kt),c,k>0.(a)Show acceleration is proportional to velocity.(b)Interpret c.(c)Find the half-initial-velocity time.'),fs(r'a(t)=v\prime(t)=-kce^{-kt}=-kv(t)',r'v(0)=c',r'ce^{-kt}=c/2\Rightarrow t=\ln2/k'),same(M(r'(a)\ a=-kv;\quad(b)\ c=v(0);\quad(c)\ t=\ln2/k')),('t=ln2/k를 넣으면 e^(-kt)=1/2이고 음의 비례계수-k는 감속 방향을 나타낸다.','At t=ln2/k,the factor e^(-kt)=1/2,and the negative proportionality constant-k gives deceleration.'),list('abc'))
add(63,('ln(x²-2x-2)≤0을 풀어라.','Solve ln(x²-2x-2)≤0.'),fs(r'0<x^2-2x-2\le1',r'3<(x-1)^2\le4',r'x\in[-1,1-\sqrt3)\cup(1+\sqrt3,3]'),same(M(r'[-1,1-\sqrt3)\cup(1+\sqrt3,3]')),('안쪽 경계는 로그 입력0이라 제외하고 바깥 경계는 로그 입력1이라 포함한다.','The inner endpoints give logarithm argument0 and are excluded;outer endpoints give argument1 and are included.'))
prime100=list(s.primerange(1,101));assert len(prime100)==25 and len([q for q in prime100 if q<=25])==9
pndata=[(100,25),(1000,168),(10000,1229),(100000,9592),(1000000,78498),(10000000,664579)];ratios=[c*math.log(n)/n for n,c in pndata];estimate=1e9/math.log(1e9)
add(64,('π(n)을n 이하 소수의 개수라 하자.(a)π(25),π(100),(b)n=100,1000,10⁴,10⁵,10⁶,10⁷에서π(n)/(n/lnn),(c)10⁹ 이하 소수 개수를 소수정리로 추정하라. (b)의 소수 개수는25,168,1229,9592,78498,664579이다.','Letπ(n) count primes≤n.(a)Computeπ(25),π(100).(b)Computeπ(n)/(n/lnn) forn=100,1000,10⁴,10⁵,10⁶,10⁷,using counts25,168,1229,9592,78498,664579.(c)Estimate the count up to10⁹ by the prime number theorem.'),[('100 이하 소수: '+', '.join(map(str,prime100)),'Primes up to100: '+', '.join(map(str,prime100)))]+fs(r'\pi(25)=9,\quad\pi(100)=25')+[('비율: '+', '.join(f'{q:.6f}'for q in ratios)+'. 1에 가까워지는 수치 증거이며 증명은 아니다.','Ratios: '+', '.join(f'{q:.6f}'for q in ratios)+'. These approach1 numerically;this is evidence,not a proof.')]+fs(r'\pi(10^9)\approx\frac{10^9}{\ln(10^9)}\approx'+f'{estimate:.0f}'),same(M(r'(a)\ 9,25;\quad(b)\ '+','.join(f'{q:.6f}'for q in ratios)+r';\quad(c)\ '+f'{estimate:.0f}')),('에라토스테네스의 체 결과와 소수 개수를 대조하고 모든 비율을 개수·lnn/n으로 따로 계산했다.','Crosschecked the sieve and prime counts and independently calculated each ratio as count·lnn/n.'),list('abc'))
print('6.3 COMPLETE',len(b.E))
