from calc1_alt_helpers import *
from calc1_plot_helpers import plots
x,t,y,z,a,u=s.symbols('x t y z a u',real=True);R=s.Rational;b=AltBook('6.2*',[458,459])
def add(n,st,steps,ans,ck,parts=[]):
 b.add(n,458 if n<=59 else 459,('자연로그함수','The natural logarithmic function'),st,steps,ans,parts=parts);b.verify(n,*ck);b.save()
def ma(n,eq,ss,ans,ck,parts=[]):add(n,(M(eq)+'계산하거나 증명하라.',M(eq)+'Evaluate or prove.'),fs(*ss),same(M(ans)),ck,parts)
# Identical exercises in the standard development, individually compared with PDF495–496.
mp4={16:4,17:3,18:2,19:5,21:7,22:8,24:10,25:11,26:12,29:15,31:21,32:22,33:23,34:16,35:29,36:30,37:31,38:32,39:33,40:34,41:35,42:36,43:37,45:39,47:43,51:59,53:61,54:62,55:65,56:66,57:67,58:68,59:69,60:70,61:71,62:72,63:47,65:49,67:75,68:76,69:77,70:78,71:79,73:81,74:82,75:83,76:80,77:87,78:88,79:89,80:90,81:91,82:92,83:93,84:73,89:95,91:97}
for n,old in mp4.items():b.reuse(n,'6.4',old,458 if n<=59 else 459)
b.reuse(90,'6.3',18,459)
ma(1,r'(a)\ln\sqrt{ab};\quad(b)\ln\frac{x^4}{\sqrt{x^2-4}}',[r'(a)\ ab>0:\ \ln\sqrt{ab}=\tfrac12\ln(ab)=\tfrac12\ln|a|+\tfrac12\ln|b|',r'(b)\ |x|>2:\ \ln(x^4)-\tfrac12\ln(x^2-4)=4\ln|x|-\tfrac12\ln(x^2-4)'],r'(a)\tfrac12\ln|a|+\tfrac12\ln|b|;\quad(b)\ 4\ln|x|-\tfrac12\ln(x^2-4)',('원래 실수 정의역을 보존했다. a,b>0을 가정하면 a,b의 절댓값은 생략할 수 있다.','Preserved the original real domain; if a,b>0 are assumed, their absolute values may be omitted.'),['a','b'])
ma(2,r'(a)\ln\frac{x^2}{y^3z^4};\quad(b)\ln\sqrt{\frac{3x}{x-3}}',[r'(a)\ xz\ne0,\ y>0:\ 2\ln|x|-3\ln y-4\ln|z|',r'(b)\ x<0\text{ or }x>3:\ \tfrac12[\ln3+\ln|x|-\ln|x-3|]'],r'(a)\ 2\ln|x|-3\ln y-4\ln|z|;\quad(b)\tfrac12[\ln3+\ln|x|-\ln|x-3|]',('제곱과 짝수 거듭제곱의 로그에서 절댓값을 유지해 음수 입력 가지를 잃지 않았다.','Kept absolute values for even powers to preserve negative-input branches.'),['a','b'])
for n,eq,ss,ans in[(3,r'(a)\ln a-2\ln b+3\ln c;\quad(b)\ln4+\ln a-\tfrac13\ln(a+1)',[r'(a)\ \ln a-\ln b^2+\ln c^3=\ln(ac^3/b^2),\quad a,b,c>0',r'(b)\ \ln(4a)-\ln\sqrt[3]{a+1}=\ln\frac{4a}{\sqrt[3]{a+1}},\quad a>0'],r'(a)\ln(ac^3/b^2);\quad(b)\ln\frac{4a}{\sqrt[3]{a+1}}'),(4,r'(a)\ln10+2\ln5;\quad(b)\ 3\ln(x-2)-\ln(x^2-5x+6)+2\ln(x-3)',[r'(a)\ \ln(10\cdot25)=\ln250',r'(b)\ x>3:\quad x^2-5x+6=(x-2)(x-3)',r'\ln\frac{(x-2)^3(x-3)^2}{(x-2)(x-3)}=\ln[(x-2)^2(x-3)]'],r'(a)\ln250;\quad(b)\ln[(x-2)^2(x-3)]'),(5,r'(a)\ln3+\tfrac13\ln8;\quad(b)\tfrac13\ln(x+2)^3+\tfrac12[\ln x-\ln(x^2+3x+2)^2]',[r'(a)\ln(3\cdot2)=\ln6',r'(b)\ x>0:\quad x^2+3x+2=(x+1)(x+2)',r'\ln(x+2)+\ln\sqrt x-\ln[(x+1)(x+2)]=\ln\frac{\sqrt x}{x+1}'],r'(a)\ln6;\quad(b)\ln\frac{\sqrt x}{x+1}')]:ma(n,eq,ss,ans,('각 원 로그의 정의역에서 곱·몫·거듭제곱 법칙을 적용한 뒤 인수를 약분했다.','Applied product, quotient and power laws on the original logarithmic domain, then canceled factors.'),['a','b'])
for n,formula,fn,window,desc in[(6,r'\ln(-x)',lambda q:math.log(-q),(-6,-.01,-4,2),('y=lnx를 y축에 반사한다. 정의역 x<0, 치역 R, 절편(−1,0), 점근선 x=0이다.','Reflect y=lnx across the y-axis. Domain x<0, range R, intercept(−1,0), asymptote x=0.')),(7,r'-\ln x',lambda q:-math.log(q),(.01,6,-2,4),('y=lnx를 x축에 반사한다. 정의역 x>0, 치역 R, 절편(1,0), 점근선 x=0이다.','Reflect y=lnx across the x-axis. Domain x>0, range R, intercept(1,0), asymptote x=0.')),(8,r'\ln|x|',lambda q:math.log(abs(q)),(-6,6,-4,2),('양수 쪽 y=lnx와 그 y축 반사를 합친 짝함수이다. 정의역 x≠0, 치역 R, 절편(±1,0), 점근선 x=0이다.','Combine positive-side y=lnx with its y-axis reflection to get an even function. Domain x≠0, range R, intercepts(±1,0), asymptote x=0.')),(9,r'\ln(x+3)',lambda q:math.log(q+3),(-2.99,4,-4,2),('y=lnx를 왼쪽3만큼 평행이동한다. 정의역 x>−3, 치역 R, 절편(−2,0), 점근선 x=−3이다.','Shift y=lnx left3 units. Domain x>−3, range R, intercept(−2,0), asymptote x=−3.'))]:
 add(n,(M('y='+formula)+'변환으로 개형을 그려라.',M('y='+formula)+'Sketch using transformations.'),[desc,('로그 입력을1로 놓아 영점을 확인하고 입력이0⁺으로 갈 때의 수직점근선을 표시한다.','Set the logarithm argument to1 to check the zero and mark the vertical asymptote as the argument tends to0⁺.')],desc,('변환 후 정의역과 특징점을 원래 식에 대입하여 확인했다.','Checked transformed domains and characteristic points by substitution.'));plots(b,n,[(f'Natural logarithm {n}',*window,[('y',fn)])])
for n,f,at,di,ans,why in[(10,s.log(s.sqrt(x)-1),1,'+',-s.oo,r'\sqrt x-1\to0^+'),(11,s.log(s.cos(x)),0,'',0,r'\cos x\to1'),(12,s.log(s.sin(x)),0,'+',-s.oo,r'\sin x\to0^+'),(13,s.log(1+x*x)-s.log(1+x),s.oo,'',s.oo,r'\ln\frac{1+x^2}{1+x},\quad\frac{1+x^2}{1+x}\to\infty'),(14,s.log(2+x)-s.log(1+x),s.oo,'',0,r'\ln\frac{x+2}{x+1},\quad\frac{x+2}{x+1}\to1')]:
 assert s.limit(f,x,at,dir=di or '+')==ans
 ma(n,r'\lim_{x\to '+s.latex(at)+('^'+di if di else'')+'}'+s.latex(f),[why,r'\lim f(x)='+s.latex(s.sympify(ans))],s.latex(s.sympify(ans)),('로그의 양수 입력 조건과 연속성 또는0⁺에서의 발산을 확인했다.','Checked the positive-input condition and either continuity or divergence as the input tends to0⁺.'))
for n,f,zz in[(15,x**3*s.log(x),x),(20,s.log(s.cos(x)),x),(23,s.sin(x)*s.log(5*x),x),(27,s.log(s.tan(x))**2,x),(28,s.log(s.tan(x)**2),x),(30,s.log((a-x)/(a+x)),x)]:
 df=s.simplify(s.diff(f,zz));F=s.lambdify(zz,f.subs(a,2),'mpmath');DF=s.lambdify(zz,df.subs(a,2),'mpmath')
 for q in map(mp.mpf,['.2','.4']):assert abs(mp.diff(F,q)-DF(q))<mp.mpf('1e-25')
 add(n,(M('f='+s.latex(f))+'미분하라.',M('f='+s.latex(f))+'Differentiate.'),[('로그 미분법 h′/h와 곱·연쇄법칙을 사용한다.','Use the logarithmic derivative h′/h with product and chain rules.')]+fs(r'f\prime='+s.latex(df)),same(M(s.latex(df))),('원 함수의 수치미분과 두 허용 입력에서 대조했다. 매개변수는 로그 비율이 양수인 영역에서 사용한다.','Compared numerical derivatives at two admissible inputs. Parameters are used where the logarithmic ratio is positive.'))
f=s.log(s.log(s.log(x)));df=1/(x*s.log(x)*s.log(s.log(x)))
ma(44,r'f(x)=\ln\ln\ln x',[r'\ln\ln x>0\Rightarrow\ln x>1\Rightarrow x>e',r'f\prime(x)=1/[x\ln x\ln\ln x]'],r'D_f=(e,\infty),\quad f\prime(x)=\frac1{x\ln x\ln\ln x}',('바깥 로그부터 안으로 양수 조건을 적용했고 세 겹의 연쇄법칙을 확인했다.','Applied positivity from the outer logarithm inward and checked the three-layer chain rule.'))
ma(46,r'f(x)=\ln x/x,\quad f\prime\prime(e)',[r'f\prime=(1-\ln x)/x^2',r'f\prime\prime=(2\ln x-3)/x^3',r'f\prime\prime(e)=(2-3)/e^3'],r'-e^{-3}',('기호적으로 두 번 미분하고 ln e=1을 대입했다.','Differentiated twice symbolically and substituted ln e=1.'))
add(48,('f(x)=ln(x²+x+1)의 도함수를 구하고 f,f′의 그래프를 비교하라.','Differentiate f(x)=ln(x²+x+1) and compare the graphs of f and f′.'),fs(r'x^2+x+1=(x+1/2)^2+3/4>0',r'f\prime=(2x+1)/(x^2+x+1)')+[('x<−1/2에서는 감소, x>−1/2에서는 증가하고 도함수의 부호가 이 모양과 일치한다.','The function decreases for x<−1/2 and increases for x>−1/2, matching the derivative signs.')],same(M(r'(2x+1)/(x^2+x+1)')),('정의역은 실수 전체이며 −1/2의 도함수0과 함수의 최저점을 함께 확인했다.','The domain is R; checked derivative0 and the function minimum at−1/2.'))
plots(b,48,[('Logarithm and its derivative',-4,4,-2,4,[('f',lambda q:math.log(q*q+q+1)),('derivative',lambda q:(2*q+1)/(q*q+q+1))])])
for n,f,q in[(49,s.sin(2*s.log(x)),1),(50,s.log(x**3-7),2)]:
 df=s.diff(f,x);m=df.subs(x,q);assert f.subs(x,q)==0
 ma(n,'y='+s.latex(f)+r',\quad('+str(q)+',0)',[r'y\prime='+s.latex(df),r'y\prime('+str(q)+')='+s.latex(m),r'y='+s.latex(m*(x-q))],r'y='+s.latex(m*(x-q)),('주어진 점을 지나고 기울기가 그 점의 도함수와 같은 접선이다.','The tangent passes through the given point and has the derivative slope there.'))
ma(52,r'\ln(xy)=y\sin x',[r'\frac{y+xy\prime}{xy}=y\prime\sin x+y\cos x',r'y\prime(1/y-\sin x)=y\cos x-1/x'],r'y\prime=\frac{y\cos x-1/x}{1/y-\sin x}',('xy>0과 미분 결과의 분모가0이 아닌 정칙점을 가정했다. −Fx/Fy 계산으로도 같은 식이다.','Assumed xy>0 and a regular point with nonzero derivative denominator;−Fx/Fy gives the same expression.'))
f=(x+1)**4*(x-5)**3/(x-3)**8;ld=4/(x+1)+3/(x-5)-8/(x-3)
ma(64,'y='+s.latex(f),[r'\ln|y|=4\ln|x+1|+3\ln|x-5|-8\ln|x-3|',r'y\prime/y=4/(x+1)+3/(x-5)-8/(x-3)',r'y\prime='+s.latex(s.factor(s.diff(f,x)))],s.latex(s.factor(s.diff(f,x))),('로그미분식은 y≠0에서 사용하고 원 곱·몫 미분으로 x=−1,5까지 연장하면 도함수0이다. x=3은 원래 제외된다.','Use logarithmic differentiation where y≠0; direct product/quotient differentiation extends the derivative to0 at x=−1,5. The original excludes x=3.'))
add(66,(M(r'y=\frac{(x^3+1)^4\sin^2x}{\sqrt[3]x}')+'로그미분법으로 도함수를 구하라.',M(r'y=\frac{(x^3+1)^4\sin^2x}{\sqrt[3]x}')+'Find the derivative using logarithmic differentiation.'),fs(r'\ln|y|=4\ln|x^3+1|+2\ln|\sin x|-\tfrac13\ln|x|',r'\frac{y\prime}y=\frac{12x^2}{x^3+1}+2\cot x-\frac1{3x}',r'y\prime=\frac{(x^3+1)^4\sin^2x}{\sqrt[3]x}\left(\frac{12x^2}{x^3+1}+2\cot x-\frac1{3x}\right)')+[('x≠0에서 실수 세제곱근을 사용한다. x=−1 또는 sinx=0인 영점에는 원래 곱의 미분으로 도함수를0으로 연장한다.','Use the real cube root for x≠0. At zeros x=−1 or sinx=0, extend the derivative to0 by differentiating the original product.')],same(M(r'y\prime=y\left(\frac{12x^2}{x^3+1}+2\cot x-\frac1{3x}\right)\ \text{where }y\ne0;\quad y\prime=0\ \text{at zeros of }y')),('음수 x에서도 ln|x|를 사용해 실수 정의역을 보존했다. x=0은 정의되지 않는다.','The use of ln|x| preserves the real domain for negative x; x=0 remains undefined.'))
ma(72,r'\int_e^6\frac{dx}{x\ln x}',[r'u=\ln x,\quad du=dx/x,\quad u:1\to\ln6',r'\int_1^{\ln6}du/u=[\ln u]_1^{\ln6}=\ln\ln6'],r'\ln\ln6',('적분구간에서 ln x>0이므로 로그 특이점을 지나지 않으며 수치구적으로도 같은 값이다.','The interval has ln x>0 and crosses no logarithmic singularity; numerical quadrature agrees.'))
mid=sum(mp.mpf('.05')/(1+(mp.mpf(i)+mp.mpf('.5'))*mp.mpf('.05'))for i in range(10))
ma(85,r'(a)\ \tfrac13<\ln1.5<\tfrac5{12};\quad(b)\ M_{10}',[r'\ln1.5=\int_1^{3/2}dt/t',r'\tfrac12\cdot\tfrac23<\int_1^{3/2}dt/t<\tfrac12\cdot\tfrac{1+2/3}2',r'M_{10}=0.05\sum_{i=0}^9\frac1{1+0.05(i+1/2)}'],fr'(a)\tfrac13<\ln1.5<\tfrac5{{12}};\quad(b)\ {float(mid):.10f}',('1/t가 엄격히 감소하고 위로 오목하므로 오른쪽 직사각형은 아래, 양끝을 잇는 사다리꼴은 위에 놓인다.','Strict decrease and convexity of1/t place the right rectangle below and the endpoint trapezoid above the curve.'),['a','b'])
ma(86,r'y=1/t:\quad A=(1,1),\ D=(2,1/2)',[r'm_{AD}=(1/2-1)/(2-1)=-1/2',r'y\prime=-1/t^2=-1/2\Rightarrow t=\sqrt2',r'(a)\ y-1/\sqrt2=-\tfrac12(t-\sqrt2)\Rightarrow y=\sqrt2-t/2',r'(b)\ \ln2=\int_1^2\frac{dt}t>\int_1^2(\sqrt2-t/2)dt=\sqrt2-3/4>0.66'],r'(a)\ y=\sqrt2-t/2;\quad(b)\ln2>\sqrt2-3/4\approx0.66421356>0.66',('위로 엄격히 오목한1/t는 접선 위에 있으므로 접선 아래 사다리꼴 넓이가 엄밀한 하한이다.','Strict convexity of1/t places it above its tangent, so the area under the tangent is a strict lower bound.'),['a','b'])
ma(87,r'\sum_{k=2}^n\frac1k<\ln n<\sum_{k=1}^{n-1}\frac1k,\quad n\ge2',[r'\frac1{k+1}<\int_k^{k+1}\frac{dt}t<\frac1k\quad(k=1,\ldots,n-1)',r'\sum_{k=1}^{n-1}\frac1{k+1}<\int_1^n\frac{dt}t<\sum_{k=1}^{n-1}\frac1k'],r'\sum_{k=2}^n1/k<\ln n<\sum_{k=1}^{n-1}1/k',('감소함수1/t의 단위 폭 직사각형을 양쪽에서 비교하여 각 구간 부등식을 합했다.','Compared unit-width rectangles on either side of decreasing1/t and summed the interval inequalities.'))
ma(88,r'\ln(x^r)=r\ln x,\quad x>0',[r'\frac d{dx}\ln(x^r)=rx^{r-1}/x^r=r/x',r'\frac d{dx}(r\ln x)=r/x\Rightarrow\ln(x^r)-r\ln x=C',r'x=1:\quad C=\ln1-r\ln1=0'],r'\ln(x^r)=r\ln x',('양수인 연결 정의역에서 도함수가 같은 함수의 차는 상수이며 x=1로 상수를 결정했다.','On the connected positive domain, equal derivatives imply a constant difference, fixed at x=1.'))
# Remove numbering-dependent boilerplate from reused ordinary-section solutions.
for n in[41,42,43]:
 b.E[n]['steps']['ko']=[v.replace('36의 왼쪽 끝점에는 유한 도함수가 없다.','42번의 왼쪽 끝점에는 유한 도함수가 없다.'if n==42 else'')for v in b.E[n]['steps']['ko']]
 b.E[n]['steps']['en']=[v.replace('The left endpoint in36 has no finite derivative.','The left endpoint has no finite derivative.'if n==42 else'')for v in b.E[n]['steps']['en']]
for n in[63,65]:
 b.E[n]['steps']['ko']=[v for v in b.E[n]['steps']['ko']if '48에서는'in v];b.E[n]['steps']['en']=[v for v in b.E[n]['steps']['en']if 'In48'in v] if False else b.E[n]['steps']['en']
# Restore the mathematical steps, retaining only a relevant domain explanation.
for n in[63,65]:
 src=json.loads((ROOT/'s6-4.json').read_text());old=next(e for e in src['exercises']if e['number']==mp4[n]);b.E[n]['steps']=copy.deepcopy(old['steps'])
 for lang in['ko','en']:b.E[n]['steps'][lang]=[v for v in b.E[n]['steps'][lang]if ('48에서는'not in v if lang=='ko'else 'In48'not in v)]
 if n==65:
  b.E[n]['steps']['ko'].append('정의역은 x≥1이며 x=1에는 유한 도함수가 없다.');b.E[n]['steps']['en'].append('The domain is x≥1; there is no finite derivative at x=1.')
# Use task-specific verbs where formulas alone would omit the instruction.
for n,ko,en in[(44,'정의역과 도함수를 구하라.','Find the domain and derivative.'),(46,'f″(e)를 구하라.','Find f″(e).'),(49,'접선 방정식을 구하라.','Find the tangent equation.'),(50,'접선 방정식을 구하라.','Find the tangent equation.'),(52,'y′을 구하라.','Find y′.'),(64,'로그미분법으로 미분하라.','Differentiate using logarithmic differentiation.'),(72,'적분하라.','Evaluate the integral.'),(85,'(a)넓이를 비교해 부등식을 증명하고 (b)중점법 n=10으로 ln1.5를 추정하라.','(a)Prove by area comparison and (b)estimate ln1.5 using the Midpoint Rule with n=10.'),(86,'(a)할선 AD와 평행한 접선을 구하고 (b)이 접선으로 ln2>0.66을 증명하라.','(a)Find a tangent parallel to secant AD and (b)use it to prove ln2>0.66.')]:
 b.E[n]['statement']['ko']=b.E[n]['statement']['ko'].replace('계산하거나 증명하라.',ko);b.E[n]['statement']['en']=b.E[n]['statement']['en'].replace('Evaluate or prove.',en)
b.save();print('6.2* COMPLETE',len(b.E))
plots(b,85,[('Area bounds for ln(1.5)',1,1.5,.6,1.1,[('1/t',lambda q:1/q),('lower rectangle',lambda q:2/3),('upper secant',lambda q:5/3-2*q/3)])])
plots(b,86,[('A tangent lower bound for ln 2',1,2,.35,1.1,[('1/t',lambda q:1/q),('tangent',lambda q:math.sqrt(2)-q/2),('secant AD',lambda q:1.5-q/2)])])
b.E[1]['answer']=pair(M(r'(a)\tfrac12\ln|a|+\tfrac12\ln|b|;\quad(b)\ 4\ln|x|-\tfrac12\ln|x-2|-\tfrac12\ln|x+2|'))
for ko,en in fs(r'x^2-4=(x-2)(x+2)\Rightarrow\ln(x^2-4)=\ln|x-2|+\ln|x+2|\quad(|x|>2)'):
 b.E[1]['steps']['ko'].append(ko);b.E[1]['steps']['en'].append(en)
b.save()
