"""Complete ordinary exercises continuing above the next section heading.
Run after legacy section author scripts; preserves existing figures and content.
"""
from early_helpers import Book
from pathlib import Path
import json,sympy as s
R=Path(__file__).resolve().parents[1];books={sec:Book(sec,[pg])for sec,pg in [('12.2',884),('15.6',1133),('16.5',1208)]};checks=[]
def m(x):return r'\('+x+r'\)'
def add(sec,n,k,e,ks,es,ans,ae=None,parts=[]):
 b=books[sec];b.add(n,b.pages[0],('벡터와 기하'if sec=='12.2'else'적분과 벡터해석','Vectors and geometry'if sec=='12.2'else'Integration and vector calculus'),(k,e),list(zip(ks,es)),(ans,ans if ae is None else ae),parts,check=('성분 항등식 또는 독립 적분으로 검산했다.','Checked by coordinate identities or independent integration.'));b.E[n]['conceptHref']='../../calc1/index.html'if sec=='12.2'else'../s'+sec.replace('.','-')+'.html'
add('12.2',49,'평면벡터 a,b,c에 대해 결합법칙 a+(b+c)=(a+b)+c를 성분으로 증명하라.','Prove a+(b+c)=(a+b)+c in two dimensions using components.',[m(r'a+(b+c)=\langle a_1+(b_1+c_1),a_2+(b_2+c_2)\rangle'),m(r'=\langle(a_1+b_1)+c_1,(a_2+b_2)+c_2\rangle=(a+b)+c')],[m(r'a+(b+c)=\langle a_1+(b_1+c_1),a_2+(b_2+c_2)\rangle'),m(r'=\langle(a_1+b_1)+c_1,(a_2+b_2)+c_2\rangle=(a+b)+c')],m('a+(b+c)=(a+b)+c'))
add('12.2',50,'공간벡터 a,b와 스칼라 c에 대해 c(a+b)=ca+cb를 성분과 닮은삼각형으로 각각 증명하라.','Prove c(a+b)=ca+cb for spatial vectors by components and similar triangles.',[m(r'[c(a+b)]_i=c(a_i+b_i)=ca_i+cb_i=[ca+cb]_i,\quad i=1,2,3'),'기하적으로 a,b를 이어 만든 삼각형의 세 변을 c>0배 확대하면 닮음에 의해 합벡터도 c배이다.','c<0이면 |c|배 확대 뒤 모든 화살표를 반대로 돌린다. c=0이면 모두0이다.'],[m(r'[c(a+b)]_i=c(a_i+b_i)=ca_i+cb_i=[ca+cb]_i,\quad i=1,2,3'),'Geometrically scale all sides of the head-to-tail triangle by c>0. Similarity scales the resultant by c.','For c<0 scale by |c| then reverse every arrow. For c=0 all vectors vanish.'],m('c(a+b)=ca+cb'))
add('12.2',51,'삼각형의 두 변 중점을 잇는 선분이 나머지 변에 평행하고 길이는 절반임을 벡터로 증명하라.','Use vectors to prove that the segment joining two side midpoints is parallel to the third side and half as long.',[m(r'M=(A+B)/2,\quad N=(A+C)/2'),m(r'\overrightarrow{MN}=N-M=(C-B)/2=\tfrac12\overrightarrow{BC}')],[m(r'M=(A+B)/2,\quad N=(A+C)/2'),m(r'\overrightarrow{MN}=N-M=(C-B)/2=\tfrac12\overrightarrow{BC}')],m(r'MN\parallel BC,\quad|MN|=|BC|/2'))
add('12.2',52,'세 좌표평면이 거울이다. 방향a=(a₁,a₂,a₃)의 광선이 먼저xz평면에서 반사될 때 방향b를 구하고, 세 거울에서 한 번씩 반사되면 초기광선과 평행해짐을 보여라.','The coordinate planes are mirrors. A ray with direction a=(a₁,a₂,a₃)first reflects in xz. Find b and prove that after reflecting once in each mirror the final ray is parallel to the original.', ['입사각과 반사각이 같으므로 거울의 접선성분은 유지되고 법선성분의 부호만 바뀐다.',m(r'b=\langle a_1,-a_2,a_3\rangle'),'나머지 두 거울은 각각x성분과z성분의 부호를 바꾼다.',m(r'a_{\rm final}=\langle-a_1,-a_2,-a_3\rangle=-a')],['Equal incidence and reflection angles preserve tangential components and reverse the normal component.',m(r'b=\langle a_1,-a_2,a_3\rangle'),'The other mirrors reverse the x and z components.',m(r'a_{\rm final}=\langle-a_1,-a_2,-a_3\rangle=-a')],m(r'b=\langle a_1,-a_2,a_3\rangle,\quad a_{\rm final}=-a')+'; 반대 방향으로 평행.',m(r'b=\langle a_1,-a_2,a_3\rangle,\quad a_{\rm final}=-a')+'; antiparallel.')
add('15.6',56,'x,y,z≥0에서 결합밀도 f=Ce^{−(0.5x+0.2y+0.1z)}이고 그 밖에서는0이다. (a)C,(b)P(X≤1,Y≤1),(c)P(X≤1,Y≤1,Z≤1)을 구하라.','A joint density is f=Ce^{−(0.5x+0.2y+0.1z)} for x,y,z≥0 and zero elsewhere. Find(a)C,(b)P(X≤1,Y≤1),(c)P(X≤1,Y≤1,Z≤1).',[m(r'1=C\left(\frac1{0.5}\right)\left(\frac1{0.2}\right)\left(\frac1{0.1}\right)=100C'),m(r'f=(0.5e^{-0.5x})(0.2e^{-0.2y})(0.1e^{-0.1z})'),'세 성분은 독립 지수밀도로 분리된다. 각 구간[0,1]확률은1−e^{−rate}이다.'],[m(r'1=C\left(\frac1{0.5}\right)\left(\frac1{0.2}\right)\left(\frac1{0.1}\right)=100C'),m(r'f=(0.5e^{-0.5x})(0.2e^{-0.2y})(0.1e^{-0.1z})'),'The density factors into independent exponential densities. Each[0,1]probability is1−e^{−rate}.'],m(r'(a)\ C=0.01;\quad(b)\ (1-e^{-1/2})(1-e^{-1/5})')+'; '+m(r'(c)\ (1-e^{-1/2})(1-e^{-1/5})(1-e^{-1/10})'),parts=list('abc'))
add('15.6',57,'제1팔분공간의 축에 평행한 정육면체[0,L]³에서 f(x,y,z)=xyz의 평균값을 구하라.','Find the average of f(x,y,z)=xyz on the axis-aligned cube[0,L]³ in the first octant.',[m(r'f_{\rm avg}=\frac1{L^3}\int_0^L\int_0^L\int_0^L xyz\,dx\,dy\,dz'),m(r'=\frac1{L^3}\left(\frac{L^2}{2}\right)^3')],[m(r'f_{\rm avg}=\frac1{L^3}\int_0^L\int_0^L\int_0^L xyz\,dx\,dy\,dz'),m(r'=\frac1{L^3}\left(\frac{L^2}{2}\right)^3')],m(r'f_{\rm avg}=L^3/8\quad(L>0)'))
add('15.6',58,'위쪽 단위 입체반구 x²+y²+z²≤1,z≥0의 점들의 평균 높이를 구하라.','Find the average height over the upper solid unit hemisphere x²+y²+z²≤1,z≥0.',[m(r'V=2\pi/3'),m(r'\iiint_E z\,dV=\int_0^1 z\,\pi(1-z^2)\,dz=\pi/4'),m(r'z_{\rm avg}=\frac{\pi/4}{2\pi/3}')],[m(r'V=2\pi/3'),m(r'\iiint_E z\,dV=\int_0^1 z\,\pi(1-z^2)\,dz=\pi/4'),m(r'z_{\rm avg}=\frac{\pi/4}{2\pi/3}')],m('3/8'))
add('15.6',59,'(a)∭E(1−x²−2y²−3z²)dV를 최대화하는 영역E를 구하고(b)그 최댓값을 구하라.','(a)Find a region E maximizing ∭E(1−x²−2y²−3z²)dV and(b)compute the maximum.', ['양의 피적분함수 영역은 모두 포함하고 음의 영역은 제외해야 한다. 영인 경계의 포함 여부는 적분에 영향을 주지 않는다.',m(r'E=\{x^2+2y^2+3z^2\le1\}'),m(r'u=x,\quad v=\sqrt2y,\quad w=\sqrt3z,\quad dV=du\,dv\,dw/\sqrt6'),m(r'I_{\max}=\frac{4\pi}{\sqrt6}\int_0^1(1-\rho^2)\rho^2\,d\rho')],['Include all points with positive integrand and exclude the negative region. Boundary points where it vanishes do not affect the integral.',m(r'E=\{x^2+2y^2+3z^2\le1\}'),m(r'u=x,\quad v=\sqrt2y,\quad w=\sqrt3z,\quad dV=du\,dv\,dw/\sqrt6'),m(r'I_{\max}=\frac{4\pi}{\sqrt6}\int_0^1(1-\rho^2)\rho^2\,d\rho')],m(r'(a)\ E=\{x^2+2y^2+3z^2\le1\};\quad(b)\frac{8\pi}{15\sqrt6}'),parts=list('ab'))
add('16.5',39,'z축 주위 각속도 w=ωk로 회전하는 강체의 위치벡터를 r=(x,y,z)라 하자. (a)v=w×r,(b)v=(−ωy,ωx,0),(c)curl v=2w임을 보여라.','A rigid body rotates about z with angular velocity w=ωk and position r=(x,y,z). Prove(a)v=w×r,(b)v=(−ωy,ωx,0),(c)curl v=2w.', ['회전축에서 거리d=|r|sinθ인 점의 속력은ωd이다. w×r의 크기가ω|r|sinθ이고 방향은 회전의 접선 방향이다.',m(r'w\times r=\langle0,0,\omega\rangle\times\langle x,y,z\rangle=\langle-\omega y,\omega x,0\rangle'),m(r'\nabla\times v=\langle0,0,\partial_x(\omega x)-\partial_y(-\omega y)\rangle=\langle0,0,2\omega\rangle')],['At distance d=|r|sinθ from the axis, the speed isωd. The vector w×r has magnitudeω|r|sinθ and the correct tangential direction.',m(r'w\times r=\langle0,0,\omega\rangle\times\langle x,y,z\rangle=\langle-\omega y,\omega x,0\rangle'),m(r'\nabla\times v=\langle0,0,\partial_x(\omega x)-\partial_y(-\omega y)\rangle=\langle0,0,2\omega\rangle')],m(r'v=w\times r=\langle-\omega y,\omega x,0\rangle,\quad\nabla\times v=2w'),parts=list('abc'))
add('16.5',40,'전하·전류가 없는 영역에서 divE=divH=0,curlE=−Hₜ/c,curlH=Eₜ/c이다. (a,b)각 장의 이중회전과(c,d)각 장의 파동방정식을 유도하라.','In a charge-free,current-free region, divE=divH=0,curlE=−Hₜ/c,curlH=Eₜ/c. Derive(a,b)the double curls and(c,d)the wave equations.', ['시간·공간 미분을 교환할 수 있는 매끄러운 장을 가정한다.',m(r'\nabla\times(\nabla\times E)=-\frac1c\partial_t(\nabla\times H)=-\frac1{c^2}E_{tt}'),m(r'\nabla\times(\nabla\times H)=\frac1c\partial_t(\nabla\times E)=-\frac1{c^2}H_{tt}'),m(r'\nabla\times(\nabla\times F)=\nabla(\nabla\cdot F)-\nabla^2F'),'발산이0이므로 마지막 항등식에서 이중회전은−∇²F이다.'],['Assume sufficiently smooth fields so temporal and spatial derivatives commute.',m(r'\nabla\times(\nabla\times E)=-\frac1c\partial_t(\nabla\times H)=-\frac1{c^2}E_{tt}'),m(r'\nabla\times(\nabla\times H)=\frac1c\partial_t(\nabla\times E)=-\frac1{c^2}H_{tt}'),m(r'\nabla\times(\nabla\times F)=\nabla(\nabla\cdot F)-\nabla^2F'),'Zero divergence makes the double curl equal−∇²F.'],m(r'(a,b)\ \nabla\times(\nabla\times F)=-F_{tt}/c^2;\quad(c,d)\ \nabla^2F=F_{tt}/c^2\quad(F=E,H)'),parts=list('abcd'))
add('16.5',41,'R³의 모든 연속함수 f가 어떤 벡터장의 발산으로 나타남을 보여라.','Show that every continuous function f on R³ is the divergence of some vector field.',[m(r'G(x,y,z)=\left\langle\int_0^x f(t,y,z)\,dt,0,0\right\rangle'),'y,z를 고정하고 미적분학의 기본정리를 적용한다.',m(r'\nabla\cdot G=\frac\partial{\partial x}\int_0^x f(t,y,z)\,dt=f(x,y,z)'),'이 발산에 필요한 대각 편미분들이 존재한다. f가 연속이라는 가정만으로 G의 모든 다른 편미분까지 존재한다고 주장할 필요는 없다.'],[m(r'G(x,y,z)=\left\langle\int_0^x f(t,y,z)\,dt,0,0\right\rangle'),'Fix y,z and apply the Fundamental Theorem of Calculus.',m(r'\nabla\cdot G=\frac\partial{\partial x}\int_0^x f(t,y,z)\,dt=f(x,y,z)'),'The diagonal partial derivatives needed for this divergence exist. Continuity of f alone need not guarantee every other partial derivative of G.'],m(r'G=\left\langle\int_0^x f(t,y,z)\,dt,0,0\right\rangle,\quad\operatorname{div}G=f'))
x,y,z,rho=s.symbols('x y z rho',real=True)
assert s.integrate(s.pi*z*(1-z*z),(z,0,1))==s.pi/4
assert s.simplify(4*s.pi/s.sqrt(6)*s.integrate((1-rho*rho)*rho*rho,(rho,0,1))-8*s.pi/(15*s.sqrt(6)))==0
assert s.prod([s.integrate(rate*s.exp(-rate*x),(x,0,s.oo))for rate in[s.Rational(1,2),s.Rational(1,5),s.Rational(1,10)]])==1
for sec,b in books.items():
 p=R/'exercise-content'/('s'+sec.replace('.','-')+'.json');doc=json.loads(p.read_text());old={e['number']:e for e in doc['exercises']};old.update(b.E);nums=sorted(old);doc['exercises']=[old[n]for n in nums];doc['scope']['numbers']=nums;doc['scope']['total']=len(nums);doc['scope']['note']={'ko':'이 절의 모든 일반 Exercises와 소문항.','en':'All ordinary Exercises and subparts in this section.'};doc['source']['printedPages']=sorted(set(doc['source']['printedPages']+b.pages));doc['source']['pdfPages']=[v+37 for v in doc['source']['printedPages']];p.write_text(json.dumps(doc,ensure_ascii=False,indent=2)+'\n');print(sec,'completed',len(nums))
(R/'exercise-checks/boundary-addenda-report.json').write_text(json.dumps({'sourceVisualPdfPages':[921,1170,1245],'additions':{'12.2':[49,50,51,52],'15.6':[56,57,58,59],'16.5':[39,40,41]},'checks':['density normalization','hemisphere moment','ellipsoid maximum integral','coordinate algebra and vector identities']},indent=2)+'\n')
