import json,math,html,sys,ast
from pathlib import Path
import sympy as S
BASE=Path(__file__).resolve().parents[1];items=[];t=S.symbols('t',real=True)
def M(s):return r'\('+str(s)+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(n,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=717 if n<=4 else 718 if n<=34 else 719 if n<=45 else 720 if n<=66 else 721 if n<=84 else 722
 items.append(dict(id=f'stewart9-exercise-10.2-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('매개변수 곡선의 미적분','Calculus with parametric curves'),statement=bi(sk,se),hint=bi('매개변수 도함수와 실제로 한 번 지나는 구간을 먼저 구한다.','First find parameter derivatives and an interval tracing the relevant curve once.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
source=(BASE/'exercise-checks/s10-1-author.py').read_text()
for node in ast.parse(source).body:
 if isinstance(node,ast.FunctionDef) and node.name in ['sample','svg','multi']:exec(ast.get_source_segment(source,node).replace('s10-1-','s10-2-'))
def calc(n,eq,taskk,taske,lines,ans,detailk='',detaile='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if detailk:steps.append((detailk,detaile))
 add(n,M(eq)+' '+taskk,M(eq)+' '+taske,steps,M(ans),M(ans),'도함수·적분과 해당 매개변수의 정의역을 원래 좌표식에서 확인했다.','Derivatives, integrals, and the relevant parameter domain were checked against the original coordinates.',sub)
def lx(x):return S.latex(S.factor(x))
base={1:(2*t**3+3*t,4*t-5*t**2),2:(t-S.log(t),t**2-t**-2),3:(t*S.exp(t),t+S.sin(t)),4:(t+S.sin(t*t+2),S.tan(t*t+2))}
for n,(x,y) in base.items():
 dx=S.diff(x,t);dy=S.diff(y,t)
 calc(n,rf'x={S.latex(x)},\ y={S.latex(y)}','두 매개변수 도함수와 접선 기울기를 구하라.','Find both parameter derivatives and the tangent slope.',[r'\frac{dy}{dx}=\frac{y\prime(t)}{x\prime(t)}'],rf'\frac{{dx}}{{dt}}={lx(dx)},\quad\frac{{dy}}{{dt}}={lx(dy)},\quad\frac{{dy}}{{dx}}={lx(dy/dx)}','기울기 식은 가로좌표 도함수가 영이 아니고 원래 함수가 정의되는 곳에서 쓴다.','The slope formula applies where the horizontal derivative is nonzero and the original functions are defined.')
calc(5,r'x=t^2+2t,\ y=2^t-2t;\ (15,2)','지정된 점의 접선 기울기를 구하라.','Find the tangent slope at the specified point.',[r't^2+2t=15\Rightarrow t=3,-5;\quad y(3)=2,\ y(-5)=321/32',r'x\prime=2t+2,\quad y\prime=2^t\ln2-2'],r'm=\ln2-1/4')
calc(6,r'x=t+\cos\pi t,\ y=-t+\sin\pi t;\ (3,-2)','지정된 점의 접선 기울기를 구하라.','Find the tangent slope at the specified point.',[r't=2,\quad x\prime=1-\pi\sin\pi t,\quad y\prime=-1+\pi\cos\pi t'],r'm=\pi-1','가로좌표 식에서 가능한 매개변수는 이 이상 사 이하이다. 세로좌표 조건을 함께 만족하는 값은 이이다.','The horizontal equation restricts the parameter to between two and four; the vertical equation leaves only two.')
for n,x,y,v in [(7,t**3+1,t**4+t,-1),(8,S.sqrt(t),t*t-2*t,4),(9,S.sin(2*t)+S.cos(t),S.cos(2*t)-S.sin(t),S.pi),(10,S.exp(t)*S.sin(S.pi*t),S.exp(2*t),0)]:
 X=x.subs(t,v);Y=y.subs(t,v);s=S.simplify(S.diff(y,t).subs(t,v)/S.diff(x,t).subs(t,v));line=S.expand(Y+s*(S.Symbol('x')-X))
 calc(n,rf'x={S.latex(x)},\ y={S.latex(y)},\ t={S.latex(v)}','接線の式を求めよ。'.replace('接線の式を求めよ。','접선 방정식을 구하라.'),'Find the tangent equation.',[rf'(x_0,y_0)=({S.latex(X)},{S.latex(Y)}),\quad m={S.latex(s)}',r'y-y_0=m(x-x_0)'],rf'y={S.latex(line)}')
calc(11,r'x=\sin t,\ y=\cos^2t;\ (1/2,3/4)','매개변수를 유지한 방법과 제거한 방법으로 접선을 구하라.','Find the tangent both parametrically and by eliminating the parameter.',[r'\text{(a)}\quad y_x=(-2\cos t\sin t)/\cos t=-2\sin t=-1',r'\text{(b)}\quad y=1-x^2,\quad y_x=-2x=-1'],r'y=5/4-x',sub='ab')
calc(12,r'x=\sqrt{t+4},\ y=1/(t+4);\ (2,1/4)','매개변수를 유지한 방법과 제거한 방법으로 접선을 구하라.','Find the tangent both parametrically and by eliminating the parameter.',[r'\text{(a)}\quad t=0,\quad y_x=-2(t+4)^{-3/2}=-1/4',r'\text{(b)}\quad y=x^{-2},\quad y_x=-2x^{-3}=-1/4'],r'y=3/4-x/4',sub='ab')
calc(13,r'x=t^2-t,\ y=t^2+t+1;\ (0,3)','접선을 구하고 곡선과 함께 그려라.','Find the tangent and graph it with the curve.',[r't=1,\quad m=(2t+1)/(2t-1)=3'],r'y=3x+3')
svg(13,'Curve and tangent',[('curve',sample(lambda t:t*t-t,lambda t:t*t+t+1,-2,2)),('y=3x+3',[(-2,-3),(4,15)])])
calc(14,r'x=\sin\pi t,\ y=t^2+t;\ (0,2)','지정점의 접선을 구하고 곡선과 함께 그려라.','Find the tangent at the specified point and graph it with the curve.',[r't^2+t=2\Rightarrow t=1,-2',r'm(1)=3/(-\pi)=-3/\pi,\quad m(-2)=-3/\pi'],r'y=2-3x/\pi','같은 점을 두 번 지나지만 두 기울기는 일치한다.','The point is reached twice, but the two tangent slopes coincide.')
svg(14,'Two visits, same tangent',[('curve',sample(lambda t:math.sin(math.pi*t),lambda t:t*t+t,-3,2)),('tangent',[(-2,2+6/math.pi),(2,2-6/math.pi)])])
for n,x,y,up in [(15,t*t+1,t*t+t,r't<0'),(16,t**3+1,t*t-t,r'0<t<1'),(17,S.exp(t),t*S.exp(-t),r't>3/2'),(18,t*t+1,S.exp(t)-1,r't<0\ \text{or}\ t>1'),(19,t-S.log(t),t+S.log(t),r'0<t<1'),(20,S.cos(t),S.sin(2*t),r'\pi/2<t<\pi')]:
 m=S.simplify(S.diff(y,t)/S.diff(x,t));dd=S.simplify(S.diff(m,t)/S.diff(x,t));eq=rf'x={S.latex(x)},\ y={S.latex(y)}'+(r',\ 0<t<\pi' if n==20 else '')
 calc(n,eq,'일계·이계 도함수와 위로 오목한 매개변수 구간을 구하라.','Find the first and second derivatives and the parameter intervals of upward concavity.',[r'y_x=y\prime/x\prime,\quad y_{xx}=(dy_x/dt)/x\prime',rf'y_{{xx}}>0\iff {up}'],rf'y_x={S.latex(m)},\quad y_{{xx}}={S.latex(dd)};\quad\text{{concave up: }}{up}','분모가 영인 매개변수는 그래프 도함수의 정의역에서 제외한다. 로그가 있으면 매개변수는 양수이다.','Exclude zero denominators from the graph derivative domain; logarithms require a positive parameter.')
calc(21,r'x=t^3-3t,\ y=t^2-3','수평·수직 접점들을 구하라.','Find all horizontal and vertical tangency points.',[r'x\prime=3(t^2-1),\quad y\prime=2t',r'\text{H}:t=0;\quad\text{V}:t=\pm1'],r'\text{H}:(0,-3);\quad\text{V}:(-2,-2),(2,-2)')
calc(22,r'x=t^3-3t,\ y=t^3-3t^2','수평·수직 접점들을 구하라.','Find all horizontal and vertical tangency points.',[r'x\prime=3(t^2-1),\quad y\prime=3t(t-2)',r'\text{H}:t=0,2;\quad\text{V}:t=\pm1'],r'\text{H}:(0,0),(2,-4);\quad\text{V}:(-2,-2),(2,-4)')
calc(23,r'x=\cos\theta,\ y=\cos3\theta','수평·수직 접점들을 구하라.','Find all horizontal and vertical tangency points.',[r'y=4x^3-3x,\quad -1\le x\le1',r'y_x=12x^2-3=0\iff x=\pm1/2'],r'\text{H}:(1/2,-1),(-1/2,1);\quad\text{V}:\varnothing','양끝에서는 두 매개변수 도함수가 모두 영이다. 직교좌표 도함수가 구이므로 수직 접선이 아니다.','At each endpoint both parameter derivatives vanish, but the Cartesian slope is nine, so neither tangent is vertical.')
calc(24,r'x=e^{\sin\theta},\ y=e^{\cos\theta}','수평·수직 접점들을 구하라.','Find all horizontal and vertical tangency points.',[r'x\prime=e^{\sin\theta}\cos\theta,\quad y\prime=-e^{\cos\theta}\sin\theta'],r'\text{H}:(1,e),(1,e^{-1});\quad\text{V}:(e,1),(e^{-1},1)')
q=6**(-.2)
calc(25,r'x=t-t^6,\ y=e^t','그래프로 가장 오른쪽 점을 추정한 다음 정확히 구하라.','Estimate the rightmost point graphically, then find it exactly.',[r'x\prime=1-6t^5=0\iff t=6^{-1/5}',r'x\prime>0\ (t<6^{-1/5}),\quad x\prime<0\ (t>6^{-1/5})'],rf'(x,y)=(5\cdot6^{{-6/5}},e^{{6^{{-1/5}}}})\approx({5*q/6:.4f},{math.exp(q):.4f})')
svg(25,'Global rightmost point',[('curve',sample(lambda t:t-t**6,math.exp,-1,1.1))])
u=4**(-1/3);v=2**(-1/3)
calc(26,r'x=t^4-2t,\ y=t+t^4','가장 아래·왼쪽 점을 그래프로 추정하고 정확히 구하라.','Estimate the lowest and leftmost points graphically and then find them exactly.',[r'y\prime=1+4t^3=0\Rightarrow t=-4^{-1/3}',r'x\prime=4t^3-2=0\Rightarrow t=2^{-1/3}'],rf'\text{{lowest}}:(9\cdot4^{{-4/3}},-3\cdot4^{{-4/3}})\approx({9*u/4:.4f},{-3*u/4:.4f});\quad\text{{leftmost}}:(-3\cdot2^{{-4/3}},3\cdot2^{{-4/3}})\approx({-3*v/2:.4f},{3*v/2:.4f})','두 좌표의 도함수는 각각 음수에서 양수로 바뀌며 양끝에서는 좌표가 무한대로 간다.','Each coordinate derivative changes from negative to positive, and both coordinates tend to positive infinity at either parameter end.')
svg(26,'Lowest and leftmost points',[('curve',sample(lambda t:t**4-2*t,lambda t:t+t**4,-1.5,1.5))])
for n,x,y,a,b,bounds in [(27,t**4-2*t**3-2*t*t,t**3-t,-1.6,3.2,(-12,25,-5,30)),(28,t**4+4*t**3-8*t*t,2*t*t-t,-6,2.5,(-145,50,-1,90))]:
 calc(n,rf'x={S.latex(x)},\ y={S.latex(y)}','중요한 굴곡·교차가 보이는 표시창으로 곡선을 그려라.','Graph in a viewing window showing the important turns and crossings.',[rf'x\prime={lx(S.diff(x,t))},\quad y\prime={lx(S.diff(y,t))}',rf't\in[{a},{b}],\quad x\in[{bounds[0]},{bounds[1]}],\quad y\in[{bounds[2]},{bounds[3]}]'],rf'\text{{window}}=[{bounds[0]},{bounds[1]}]\times[{bounds[2]},{bounds[3]}]','도함수 영점을 포함하는 넓은 구간과 조밀한 표본으로 자체 그림을 그렸다. 곡선은 표시창 밖으로 계속된다.','The original plot uses a dense parameter sample over an interval containing derivative zeros; the curve continues outside the window.')
 svg(n,'Polynomial curve: finite viewing window',[('curve',sample(S.lambdify(t,x,'math'),S.lambdify(t,y,'math'),a,b,6000))],bounds)
multi(27,[('Overview',[('curve',sample(lambda t:t**4-2*t**3-2*t*t,lambda t:t**3-t,-1.6,3.2,6000))],(-12,25,-5,30)),('Detail near the origin',[('curve',sample(lambda t:t**4-2*t**3-2*t*t,lambda t:t**3-t,-1.3,1.3,4000))],(-3.5,2,-1,1))])
multi(28,[('Overview',[('curve',sample(lambda t:t**4+4*t**3-8*t*t,lambda t:2*t*t-t,-6,2.5,6000))],(-145,50,-1,90)),('Small loop detail',[('curve',sample(lambda t:t**4+4*t**3-8*t*t,lambda t:2*t*t-t,-1.0,1.6,4000))],(-6,2,-.5,4))])
calc(29,r'x=\cos t,\ y=\sin t\cos t','원점에 서로 다른 두 접선이 있음을 보이고 곡선을 그려라.','Show that the origin has two distinct tangents and graph the curve.',[r't=\pi/2,3\pi/2,\quad y_x=\cos2t/(-\sin t)',r'm(\pi/2)=1,\quad m(3\pi/2)=-1'],r'y=x,\quad y=-x')
svg(29,'Crossing and two tangents',[('curve',sample(math.cos,lambda t:math.sin(t)*math.cos(t),0,2*math.pi)),('y=x',[(-1,-1),(1,1)]),('y=-x',[(-1,1),(1,-1)])])
calc(30,r'x=-2\cos t,\ y=\sin t+\sin2t','곡선을 그려 자기 교차점을 찾고 그 점의 두 접선을 구하라.','Graph the curve, locate its self-intersection, and find both tangents there.',[r'y=\sin t(1+2\cos t)=0,\quad t=2\pi/3,4\pi/3\Rightarrow(x,y)=(1,0)',r'm=\frac{\cos t+2\cos2t}{2\sin t}=\mp\sqrt3/2'],r'(1,0);\quad y=\pm\frac{\sqrt3}{2}(x-1)')
svg(30,'Self-intersection at (1,0)',[('curve',sample(lambda t:-2*math.cos(t),lambda t:math.sin(t)+math.sin(2*t),0,2*math.pi))])
calc(31,r'x=r\theta-d\sin\theta,\ y=r-d\cos\theta,\quad r,d>0','(a) 접선 기울기를 구하고 (b) 작은 추적 반지름일 때 수직 접선이 없음을 보여라.','(a) Find the tangent slope; (b) show that the trochoid with tracing distance smaller than the rolling radius has no vertical tangent.',[r'x\prime=r-d\cos\theta,\quad y\prime=d\sin\theta',r'd<r\Rightarrow x\prime\ge r-d>0'],r'\text{(a)}\quad y_x=\frac{d\sin\theta}{r-d\cos\theta};\quad\text{(b)}\quad d<r\Rightarrow\text{no vertical tangent}',sub='ab')
calc(32,r'x=a\cos^3\theta,\ y=a\sin^3\theta,\quad a>0','(a) 기울기 (b) 수평·수직 접점 (c) 기울기가 양일 또는 음일인 점들을 구하라.','Find (a) the slope, (b) horizontal and vertical tangencies, and (c) points with slope plus or minus one.',[r'y_x=\frac{3a\sin^2\theta\cos\theta}{-3a\cos^2\theta\sin\theta}=-\tan\theta',r'\lim_{\theta\to0,\pi}y_x=0,\quad |y_x|\to\infty\ (\theta\to\pi/2,3\pi/2)',r'|\tan\theta|=1\Rightarrow|x|=|y|=a/(2\sqrt2)'],r'\text{(a)}\ -\tan\theta;\quad\text{(b) H}:(\pm a,0),\ \text{V}:(0,\pm a);\quad\text{(c)}\ m=1:(\pm a/(2\sqrt2),\mp a/(2\sqrt2)),\ m=-1:(\pm a/(2\sqrt2),\pm a/(2\sqrt2))','첨점에서는 매개변수 속도가 영이므로 기울기의 극한으로 접선을 구한다.','At cusps the parameter velocity vanishes, so use limiting slopes.',sub='abc')
calc(33,r'x=3t^2+1,\ y=t^3-1','기울기가 이분의 일인 접점을 구하라.','Find the point whose tangent slope is one half.',[r'y_x=3t^2/(6t)=t/2,\quad t/2=1/2\Rightarrow t=1'],r'(4,0)')
calc(34,r'x=3t^2+1,\ y=2t^3+1','점 '+M('(4,3)')+'을 지나는 이 곡선의 접선을 모두 구하라.','Find all tangents to the curve passing through '+M('(4,3)')+'.',[r'm=t,\quad y=t x-t^3-t+1',r'3=4t-t^3-t+1\Rightarrow(t-1)^2(t+2)=0'],r'y=x-1,\quad y=-2x+11','첨점의 접선은 가로선 일이므로 지정된 점을 지나지 않는다.','The cusp tangent is the horizontal line at height one and does not pass through the given point.')
calc(35,r'x=t^3+1,\ y=2t-t^2','곡선과 가로축 사이의 유계 넓이를 구하라.','Find the bounded area between the curve and the horizontal axis.',[r'y=0\Rightarrow t=0,2,\quad x\prime=3t^2\ge0',r'A=\int_0^2(2t-t^2)3t^2\,dt'],r'A=24/5')
calc(36,r'x=\sin t,\ y=\sin t\cos t,\quad0\le t\le\pi/2','곡선 아래 가로축 위의 넓이를 구하라.','Find the area under the curve and above the horizontal axis.',[r'A=\int_0^{\pi/2}\sin t\cos^2t\,dt',r'u=\cos t'],r'A=1/3')
calc(37,r'x=\sin^2t,\ y=\cos t','곡선과 세로축 사이의 유계 넓이를 구하라.','Find the bounded area between the curve and the vertical axis.',[r'x=1-y^2,\quad-1\le y\le1',r'A=\int_{-1}^{1}(1-y^2)\,dy'],r'A=4/3')
calc(38,r'x=t^2-2t,\ y=\sqrt t','곡선과 세로축 사이의 유계 넓이를 구하라.','Find the bounded area between the curve and the vertical axis.',[r'x=0\Rightarrow t=0,2;\quad x\le0\ (0\le t\le2)',r'A=\int_0^2(2t-t^2)\frac{dt}{2\sqrt t}'],r'A=8\sqrt2/15')
calc(39,r'x=a\cos\theta,\ y=b\sin\theta,\quad0\le\theta\le2\pi,\ a,b>0','매개식을 이용해 타원의 넓이를 구하라.','Use the parameterization to derive the ellipse area.',[r'A=4\int_0^{\pi/2}ab\sin^2\theta\,d\theta'],r'A=\pi ab')
calc(40,r'x=1-t^2,\ y=t-t^3','고리 내부의 넓이를 구하라.','Find the area enclosed by the loop.',[r't=\pm1\Rightarrow(x,y)=(0,0),\quad t=0\Rightarrow(1,0)',r'A=-\int_{-1}^1y x\prime\,dt=2\int_{-1}^1(t^2-t^4)\,dt'],r'A=8/15')
calc(41,r'x=r\theta-d\sin\theta,\ y=r-d\cos\theta,\quad0<d<r','한 주기 아치 아래 넓이를 구하라.','Find the area under one periodic arch.',[r'0\le\theta\le2\pi,\quad x\prime=r-d\cos\theta=y>0',r'A=\int_0^{2\pi}(r-d\cos\theta)^2\,d\theta'],r'A=2\pi r^2+\pi d^2')
calc(42,r'x=t^2,\ y=t^3-3t','고리 영역의 (a) 넓이 (b) 가로축 회전 부피 (c) 도심을 구하라.','Find the loop region’s (a) area, (b) volume when revolved about the horizontal axis, and (c) centroid.',[r'0\le x\le3,\quad y=\pm\sqrt x(3-x)',r'\text{(a)}\ A=2\int_0^3\sqrt x(3-x)\,dx=24\sqrt3/5',r'\text{(b)}\ V=\pi\int_0^3x(3-x)^2\,dx=27\pi/4',r'\text{(c)}\ \bar y=0,\quad\bar x=\frac{2\int_0^3x^{3/2}(3-x)\,dx}{A}=9/7'],r'A=24\sqrt3/5,\quad V=27\pi/4,\quad(\bar x,\bar y)=(9/7,0)',sub='abc')
# Numerical quadrature is independently repeated at increased precision.
import mpmath as mp
mp.mp.dps=35
numeric=[]
def quad(expr,a,b):
 f=S.lambdify(t,expr,'mpmath');aa=mp.mpf(str(S.N(a,35)));bb=mp.mpf(str(S.N(b,35)))
 v=mp.quad(f,[aa+(bb-aa)*i/24 for i in range(25)])
 with mp.workdps(50):
  w=mp.quad(f,[aa+(bb-aa)*i/48 for i in range(49)])
 assert abs(v-w)<mp.mpf('1e-18'),(v,w)
 return float(v)
for n,x,y,a,b in [(43,3*t*t-t**3,t*t-2*t,-1,3),(44,t+S.exp(-t),t*t+t,-2,2),(45,t-2*S.sin(t),1-2*S.cos(t),0,4*S.pi),(46,t*S.cos(t),t-5*S.sin(t),-S.pi,S.pi)]:
 speed=S.sqrt(S.diff(x,t)**2+S.diff(y,t)**2);v=quad(speed,a,b);numeric.append((n,v))
 calc(n,rf'x={S.latex(x)},\ y={S.latex(y)}','원문 그림의 양끝을 포함한 곡선 길이를 적분으로 나타내고 소수 넷째 자리까지 구하라.','Set up the arc-length integral for the displayed curve, including its two endpoints, and evaluate to four decimal places.',[rf't\in[{S.latex(a)},{S.latex(b)}],\quad ds=\sqrt{{(x\prime)^2+(y\prime)^2}}\,dt'],rf'L=\int_{{{S.latex(a)}}}^{{{S.latex(b)}}}{S.latex(speed)}\,dt\approx{v:.4f}','첨부한 자체 그림은 원문에서 표시된 끝점에 대응하는 매개변수 구간을 사용한다. 수치 적분의 정밀도와 분할을 늘려 소수 자릿수를 확인했다.','The original plot uses the parameter interval corresponding to the marked source endpoints. Increased precision and subdivision confirm the rounded quadrature.')
 svg(n,'Arc segment used in the integral',[('segment',sample(S.lambdify(t,x,'math'),S.lambdify(t,y,'math'),float(a),float(b)))])
calc(47,r'x=\frac23t^3,\ y=t^2-2,\quad0\le t\le3','곡선의 정확한 길이를 구하라.','Find the exact curve length.',[r'ds=2t\sqrt{1+t^2}\,dt',r'L=\int_0^3 2t\sqrt{1+t^2}\,dt=\frac23[(1+t^2)^{3/2}]_0^3'],r'L=\frac23(10\sqrt{10}-1)')
calc(48,r'x=e^t-t,\ y=4e^{t/2},\quad0\le t\le2','곡선의 정확한 길이를 구하라.','Find the exact curve length.',[r'(x\prime)^2+(y\prime)^2=(e^t-1)^2+4e^t=(e^t+1)^2',r'L=\int_0^2(e^t+1)\,dt'],r'L=e^2+1')
calc(49,r'x=t\sin t,\ y=t\cos t,\quad0\le t\le1','곡선의 정확한 길이를 구하라.','Find the exact curve length.',[r'(x\prime)^2+(y\prime)^2=1+t^2',r'L=\int_0^1\sqrt{1+t^2}\,dt'],r'L=\frac12[\sqrt2+\ln(1+\sqrt2)]')
calc(50,r'x=3\cos t-\cos3t,\ y=3\sin t-\sin3t,\quad0\le t\le\pi','곡선의 정확한 길이를 구하라.','Find the exact curve length.',[r'(x\prime)^2+(y\prime)^2=36\sin^2t',r'L=\int_0^\pi6\sin t\,dt'],r'L=12')
calc(51,r'x=e^t\cos t,\ y=e^t\sin t,\quad0\le t\le\pi','곡선을 그리고 정확한 길이를 구하라.','Graph the curve and find its exact length.',[r'(x\prime)^2+(y\prime)^2=2e^{2t}',r'L=\sqrt2\int_0^\pi e^t\,dt'],r'L=\sqrt2(e^\pi-1)','반지름이 지수적으로 증가하는 반 바퀴 나선이다.','The curve is a half-turn spiral with exponentially increasing radius.')
svg(51,'Expanding spiral',[('curve',sample(lambda t:math.exp(t)*math.cos(t),lambda t:math.exp(t)*math.sin(t),0,math.pi))])
calc(52,r'x=\cos t+\ln\tan(t/2),\ y=\sin t,\quad\pi/4\le t\le3\pi/4','곡선을 그리고 정확한 길이를 구하라.','Graph the curve and find its exact length.',[r'x\prime=\cos^2t/\sin t,\quad y\prime=\cos t,\quad ds=|\cot t|\,dt',r'L=2\int_{\pi/4}^{\pi/2}\cot t\,dt'],r'L=\ln2','중간에서 두 속도 성분이 영이지만 길이는 양쪽 구간 적분의 합으로 계산한다.','Both velocity components vanish at the middle cusp; the length is the sum of the two side integrals.')
svg(52,'Symmetric cusp arc',[('curve',sample(lambda t:math.cos(t)+math.log(math.tan(t/2)),math.sin,math.pi/4,3*math.pi/4))])
expr=S.sqrt((S.cos(t)+S.Rational(3,2)*S.cos(3*t/2))**2+S.sin(t)**2);v=quad(expr,0,4*S.pi)
calc(53,r'x=\sin t+\sin(3t/2),\ y=\cos t','전체 곡선을 그리고 길이를 소수 넷째 자리까지 구하라.','Graph the complete curve and find its length to four decimal places.',[r'T=4\pi,\quad ds=\sqrt{(\cos t+\frac32\cos(3t/2))^2+\sin^2t}\,dt'],rf'L=\int_0^{{4\pi}}\sqrt{{(\cos t+\frac32\cos(3t/2))^2+\sin^2t}}\,dt\approx{v:.4f}','두 주파수의 공통 주기를 사용한다. 고립된 교차는 길이를 중복하는 구간이 아니다.','Use the common period of both frequencies; isolated crossings do not duplicate an arc segment.')
svg(53,'Complete curve over 4 pi',[('curve',sample(lambda t:math.sin(t)+math.sin(1.5*t),math.cos,0,4*math.pi))])
calc(54,r'x=3t-t^3,\ y=3t^2','고리의 길이를 구하라.','Find the length of the loop.',[r't=\pm\sqrt3\Rightarrow(x,y)=(0,9)',r'ds=\sqrt{(3-3t^2)^2+36t^2}\,dt=3(1+t^2)\,dt',r'L=\int_{-\sqrt3}^{\sqrt3}3(1+t^2)\,dt'],r'L=12\sqrt3')
calc(55,r'x=\sin^2t,\ y=\cos^2t,\quad0\le t\le3\pi','입자의 총 이동거리와 기하학적 곡선 길이를 비교하라.','Compare the particle’s traveled distance with the geometric curve length.',[r'x+y=1,\quad0\le x,y\le1,\quad L=\sqrt2',r'v=\sqrt2|\sin2t|,\quad D=\int_0^{3\pi}\sqrt2|\sin2t|\,dt'],r'D=6\sqrt2,\quad L=\sqrt2','같은 선분을 여섯 번 통과한다.','The same segment is traversed six times.')
calc(56,r'x=\cos^2t,\ y=\cos t,\quad0\le t\le4\pi','입자의 총 이동거리와 기하학적 곡선 길이를 비교하라.','Compare the particle’s traveled distance with the geometric curve length.',[r'x=y^2,\quad-1\le y\le1',r'L=\int_{-1}^1\sqrt{1+4y^2}\,dy=\sqrt5+\frac12\ln(2+\sqrt5)',r'D=4L'],r'L=\sqrt5+\frac12\ln(2+\sqrt5),\quad D=4\sqrt5+2\ln(2+\sqrt5)','포물선 조각을 네 번 통과한다.','The parabola segment is traversed four times.')
for n,eq,der,ans in [(57,r'x=2t-3,\ y=2t^2-3t+6,\quad t=5',r'v=\sqrt{2^2+(4t-3)^2}',r'v=\sqrt{293}\ \mathrm{m/s}'),(58,r'x=2+5\cos(\pi t/3),\ y=-2+7\sin(\pi t/3),\quad t=3',r'v=\frac\pi3\sqrt{25\sin^2(\pi t/3)+49\cos^2(\pi t/3)}',r'v=7\pi/3\ \mathrm{m/s}'),(59,r'x=e^t,\ y=te^t;\quad(e,e)',r't=1,\quad v=e^t\sqrt{1+(t+1)^2}',r'v=e\sqrt5\ \mathrm{m/s}'),(60,r'x=t^2+1,\ y=t^4+2t^2+1;\quad(2,4)',r't=\pm1,\quad v=\sqrt{4t^2+16t^2(t^2+1)^2}',r'v=2\sqrt{17}\ \mathrm{m/s}')]:
 calc(n,eq,'지정 시각 또는 점에서 속력을 구하라. 좌표 단위는 미터, 시간 단위는 초이다.','Find the speed at the specified time or point; coordinates are in meters and time in seconds.',[r'v=\sqrt{(x\prime)^2+(y\prime)^2}',der],ans)
calc(61,r'x=v_0\cos\alpha\,t,\ y=v_0\sin\alpha\,t-\frac12gt^2,\quad g=9.8,\ 0<\alpha<\pi/2','공기저항 없는 투사체의 (a) 지면 도달 속력 (b) 최고점 속력을 구하라.','For a projectile without air resistance, find its speed (a) upon returning to ground and (b) at the highest point.',[r'v(t)=\sqrt{(v_0\cos\alpha)^2+(v_0\sin\alpha-gt)^2}',r't_{\rm ground}=2v_0\sin\alpha/g,\quad t_{\rm top}=v_0\sin\alpha/g'],r'\text{(a)}\ v_0;\quad\text{(b)}\ v_0\cos\alpha',sub='ab')
calc(62,r'x=a\sin\theta,\ y=b\cos\theta,\quad a>b>0,\ e=\sqrt{a^2-b^2}/a','이심률을 이용한 타원 둘레 적분을 유도하라.','Derive the ellipse perimeter integral using eccentricity.',[r'ds=\sqrt{a^2\cos^2\theta+b^2\sin^2\theta}\,d\theta=a\sqrt{1-e^2\sin^2\theta}\,d\theta',r'L=4\int_0^{\pi/2}ds'],r'L=4a\int_0^{\pi/2}\sqrt{1-e^2\sin^2\theta}\,d\theta')
val=quad(11*S.sqrt(5-4*S.cos(9*t/2)),0,4*S.pi)
calc(63,r'x=11\cos t-4\cos(11t/2),\ y=11\sin t-4\sin(11t/2)','(a) 전체 에피트로코이드를 그릴 매개변수 구간을 정하고 그림을 그려라. (b) 길이를 근사하라.','(a) Determine an interval for the complete epitrochoid and graph it. (b) Approximate its length.',[r'T=4\pi,\quad v=11\sqrt{5-4\cos(9t/2)}',r'L=11\int_0^{4\pi}\sqrt{5-4\cos(9t/2)}\,dt'],rf'\text{{(a)}}\ 0\le t\le4\pi;\quad\text{{(b)}}\ L\approx{val:.4f}',sub='ab')
svg(63,'Complete epitrochoid',[('curve',sample(lambda t:11*math.cos(t)-4*math.cos(5.5*t),lambda t:11*math.sin(t)-4*math.sin(5.5*t),0,4*math.pi,4000))])
calc(64,r'x=C(t)=\int_0^t\cos(\pi u^2/2)\,du,\ y=S(t)=\int_0^t\sin(\pi u^2/2)\,du','(a) 코르뉘 나선을 그리고 양방향 극한을 설명하라. (b) 원점부터 지정된 매개변수 점까지의 호의 길이를 구하라.','(a) Graph Cornu’s spiral and describe both infinite-parameter limits. (b) Find its arc length from the origin to the point at the specified parameter.',[r'x\prime=\cos(\pi t^2/2),\quad y\prime=\sin(\pi t^2/2),\quad v=1',r'\lim_{t\to\infty}(C(t),S(t))=(1/2,1/2),\quad\lim_{t\to-\infty}(C(t),S(t))=(-1/2,-1/2)'],r'\text{(a)}\ (1/2,1/2),\ (-1/2,-1/2);\quad\text{(b)}\ L=|t|','프레넬 적분의 극한으로 두 중심에 감겨 들어간다. 곡선은 한없이 감기므로 전체 길이는 무한대다.','Fresnel integral limits give two spiral centers; the indefinitely winding full curve has infinite length.',sub='ab')
svg(64,'Cornu spiral, -5 <= t <= 5',[('spiral',sample(lambda t:float(mp.fresnelc(t)),lambda t:float(mp.fresnels(t)),-5,5,2500))])
calc(65,r'x=a\cos^3\theta,\ y=a\sin^3\theta,\quad a>0','아스트로이드의 넓이를 구하라.','Find the area of the astroid.',[r'A=4\int_0^{\pi/2}3a^2\sin^4\theta\cos^2\theta\,d\theta',r'\int_0^{\pi/2}\sin^4\theta\cos^2\theta\,d\theta=\pi/32'],r'A=3\pi a^2/8')
calc(66,r'x=a\cos^3\theta,\ y=a\sin^3\theta,\quad a>0','아스트로이드의 둘레를 구하라.','Find the perimeter of the astroid.',[r'ds=3a|\sin\theta\cos\theta|\,d\theta',r'L=4\int_0^{\pi/2}3a\sin\theta\cos\theta\,d\theta'],r'L=6a')
for n,x,y,a,b in [(67,t*S.sin(t),t*S.cos(t),0,S.pi/2),(68,S.sin(t),S.sin(2*t),0,S.pi/2),(69,t+S.exp(t),S.exp(-t),0,1),(70,t*t-t**3,t+t**4,0,1)]:
 speed=S.sqrt(S.diff(x,t)**2+S.diff(y,t)**2);expr=2*S.pi*y*speed;v=quad(expr,a,b)
 calc(n,rf'x={S.latex(x)},\ y={S.latex(y)},\quad {S.latex(a)}\le t\le {S.latex(b)}','가로축 회전 곡면의 넓이 적분을 세우고 소수 넷째 자리까지 계산하라.','Set up the surface area integral for revolution about the horizontal axis and evaluate to four decimal places.',[r'S=\int 2\pi y\,ds,\quad ds=\sqrt{(x\prime)^2+(y\prime)^2}\,dt'],rf'S=\int_{{{S.latex(a)}}}^{{{S.latex(b)}}}{S.latex(expr)}\,dt\approx{v:.4f}','세로좌표가 음이 아닌 구간이며, 수치 적분의 정밀도와 분할을 늘려 결과를 대조했다.','The vertical coordinate is nonnegative; increased quadrature precision and subdivision confirm the result.')
calc(71,r'x=t^3,\ y=t^2,\quad0\le t\le1','가로축 회전 곡면의 정확한 넓이를 구하라.','Find the exact surface area upon rotation about the horizontal axis.',[r'ds=t\sqrt{9t^2+4}\,dt',r'S=2\pi\int_0^1t^3\sqrt{9t^2+4}\,dt,\quad u=9t^2+4'],r'S=\frac{\pi}{1215}(494\sqrt{13}+128)')
calc(72,r'x=2t^2+1/t,\ y=8\sqrt t,\quad1\le t\le3','가로축 회전 곡면의 정확한 넓이를 구하라.','Find the exact surface area upon rotation about the horizontal axis.',[r'(x\prime)^2+(y\prime)^2=(4t-t^{-2})^2+16/t=(4t+t^{-2})^2',r'S=16\pi\int_1^3(4t^{3/2}+t^{-3/2})\,dt'],r'S=\frac{32\pi}{15}(103\sqrt3+3)')
calc(73,r'x=a\cos^3\theta,\ y=a\sin^3\theta,\quad0\le\theta\le\pi/2,\ a>0','가로축 회전 곡면의 정확한 넓이를 구하라.','Find the exact surface area upon rotation about the horizontal axis.',[r'ds=3a\sin\theta\cos\theta\,d\theta',r'S=6\pi a^2\int_0^{\pi/2}\sin^4\theta\cos\theta\,d\theta'],r'S=6\pi a^2/5')
calc(74,r'x=2\cos\theta-\cos2\theta,\ y=2\sin\theta-\sin2\theta','곡선을 그리고 가로축 회전 곡면의 정확한 넓이를 구하라.','Graph the curve and find the exact area of the surface generated about the horizontal axis.',[r'y=2\sin\theta(1-\cos\theta)\ge0\quad(0\le\theta\le\pi)',r'ds=4\sin(\theta/2)\,d\theta',r'S=16\pi\int_0^\pi\sin\theta(1-\cos\theta)\sin(\theta/2)\,d\theta=128\pi\int_0^1u^4\,du'],r'S=128\pi/5','상하 대칭이므로 위쪽 반곡선만 회전한다. 두 반곡선을 모두 적분하면 같은 곡면을 두 번 세게 된다.','By reflection symmetry, revolve only the upper half; integrating both halves would count the same surface twice.')
svg(74,'Upper half generates the surface once',[('upper half',sample(lambda t:2*math.cos(t)-math.cos(2*t),lambda t:2*math.sin(t)-math.sin(2*t),0,math.pi)),('lower reflection',sample(lambda t:2*math.cos(t)-math.cos(2*t),lambda t:2*math.sin(t)-math.sin(2*t),math.pi,2*math.pi))])
calc(75,r'x=3t^2,\ y=2t^3,\quad0\le t\le5','세로축 회전 곡면의 넓이를 구하라.','Find the surface area generated about the vertical axis.',[r'ds=6t\sqrt{1+t^2}\,dt',r'S=\int_0^5 2\pi(3t^2)6t\sqrt{1+t^2}\,dt'],r'S=\frac{24\pi}{5}(949\sqrt{26}+1)')
calc(76,r'x=e^t-t,\ y=4e^{t/2},\quad0\le t\le1','세로축 회전 곡면의 넓이를 구하라.','Find the surface area generated about the vertical axis.',[r'ds=(e^t+1)\,dt,\quad x>0',r'S=2\pi\int_0^1(e^t-t)(e^t+1)\,dt'],r'S=\pi(e^2+2e-6)')
calc(77,r'x=f(t),\ y=g(t),\quad a\le t\le b,\quad f\prime\text{ continuous},\quad f\prime(t)\ne0','곡선이 가로좌표의 함수로 표현됨을 증명하라.','Prove that the curve is the graph of a function of the horizontal coordinate.',[r'f\prime\ne0\ \text{and continuity}\Rightarrow f\prime>0\ \text{everywhere or}\ f\prime<0\ \text{everywhere}',r'f\ \text{strictly monotone}\Rightarrow f^{-1}\ \text{exists}',r'F=g\circ f^{-1}'],r'y=F(x)=g(f^{-1}(x)),\quad x\in f([a,b])','연속인 도함수가 부호를 바꾸면 중간값정리에 의해 영이 되어 모순이다. 평균값정리가 엄격한 단조성을 준다.','A sign change would force a zero by the intermediate value theorem; the mean value theorem then yields strict monotonicity.')
calc(78,r'x=f(t),\ y=g(t)\ge0,\quad y=F(x)','함수 그래프의 회전넓이 공식으로부터 매개변수 회전넓이 공식을 유도하라.','Derive the parametric surface area formula from the formula for a function graph.',[r'S=\int2\pi F(x)\sqrt{1+(F\prime(x))^2}\,|dx|',r'F\prime(x)=g\prime(t)/f\prime(t),\quad |dx|=|f\prime(t)|\,dt',r'\sqrt{1+(g\prime/f\prime)^2}|f\prime|=\sqrt{(f\prime)^2+(g\prime)^2}'],r'S=\int_\alpha^\beta2\pi g(t)\sqrt{(f\prime(t))^2+(g\prime(t))^2}\,dt','구간에서 곡선이 한 번만 그려진다고 가정한다. 가로좌표 감소 시에도 절댓값으로 면적이 양수임을 유지한다. 필요하면 단조 구간으로 나눈다.','Assume the curve is traced once; the absolute value retains positive area when the horizontal coordinate decreases. Split into monotone intervals if necessary.')
calc(79,r'x=x(t),\ y=y(t),\quad\kappa=|d\phi/ds|','정칙 매개변수 곡선의 곡률 공식을 유도하라.','Derive the curvature formula for a regular parametric curve.',[r'\tan\phi=y\prime/x\prime,\quad\phi\prime=\frac{x\prime y\prime\prime-y\prime x\prime\prime}{(x\prime)^2+(y\prime)^2}',r'\frac{ds}{dt}=\sqrt{(x\prime)^2+(y\prime)^2}'],r'\kappa=\frac{|x\prime y\prime\prime-y\prime x\prime\prime|}{[(x\prime)^2+(y\prime)^2]^{3/2}}','속력이 양수인 정칙점에서 성립한다. 수직 접점에서는 다른 각도 좌표를 쓰거나 연속성으로 같은 식을 얻는다.','The formula holds at regular points with positive speed; at a vertical tangent use another angle chart or continuity.')
calc(80,r'y=f(x)','가로좌표를 매개변수로 삼아 함수 그래프의 곡률 공식을 유도하라.','Use the horizontal coordinate as parameter to derive graph curvature.',[r'(x(t),y(t))=(t,f(t)),\quad x\prime=1,\ x\prime\prime=0,\ y\prime=f\prime,\ y\prime\prime=f\prime\prime'],r'\kappa=\frac{|f\prime\prime(x)|}{[1+(f\prime(x))^2]^{3/2}}')
calc(81,r'x=\theta-\sin\theta,\ y=1-\cos\theta','사이클로이드 아치의 가장 높은 점에서 곡률을 구하라.','Find curvature at the top of a cycloid arch.',[r'\theta=\pi:\quad(x\prime,y\prime)=(2,0),\quad(x\prime\prime,y\prime\prime)=(0,-1)',r'\kappa=|2(-1)-0|/4^{3/2}'],r'\kappa=1/4')
calc(82,r'y=x^2','(a) 점 '+M('(1,1)')+'에서 곡률을 구하라. (b) 곡률이 최대인 점을 찾아라.','(a) Find curvature at '+M('(1,1)')+'. (b) Find the point of maximum curvature.',[r'\kappa(x)=2/(1+4x^2)^{3/2}',r'1+4x^2\ge1\quad\text{with equality only at }x=0'],r'\text{(a)}\ \kappa(1)=2/(5\sqrt5);\quad\text{(b)}\ (0,0),\ \kappa_{\max}=2',sub='ab')
calc(83,r'r>0','(a) 직선의 곡률은 영임을 증명하라. (b) 주어진 반지름 원의 곡률을 구하라.','(a) Prove a straight line has zero curvature. (b) Find the curvature of a circle of the given radius.',[r'\text{(a)}\ (x,y)=(x_0,y_0)+t(a,b),\quad(a,b)\ne(0,0)\Rightarrow x\prime\prime=y\prime\prime=0',r'\text{(b)}\ (x,y)=(r\cos t,r\sin t),\quad |x\prime y\prime\prime-y\prime x\prime\prime|=r^2,\quad v=r'],r'\text{(a)}\ \kappa=0;\quad\text{(b)}\ \kappa=1/r',sub='ab')
calc(84,r'r>0','반지름이 주어진 원형 사일로의 한 점에 소를 묶었다. 줄은 사일로 표면을 따라 정반대 점까지 닿는 길이이다. 소가 풀을 먹을 수 있는 평면 넓이를 구하라.','A cow is tied at a point on a circular silo of the given radius. The rope just reaches the opposite point along the silo surface. Find the accessible grazing area.',[r'\ell=\pi r,\quad A_{\rm free}=\frac12\pi(\pi r)^2',r'\text{wrap angle }\theta\in[0,\pi]:\quad\ell_{\rm free}=r(\pi-\theta)',r'A_{\rm wrapped}=2\int_0^\pi\frac12r^2(\pi-\theta)^2\,d\theta=\pi^3r^2/3'],r'A=\frac56\pi^3r^2','묶인 점 바깥쪽의 반원과 사일로의 양쪽을 감아 도달하는 두 부채 모양 영역을 합한다. 가느다란 부채의 넓이는 남은 줄 길이 제곱에 각도 증가량의 절반을 곱한 값이다. 경계에서만 만나는 영역이므로 중복 넓이는 없다.','Add the outward semicircle centered at the tether and the two regions reached by wrapping around either side. An infinitesimal sector has area half the squared free length times the angle increment; these regions meet only along boundaries.')
calc(85,r'r>0,\quad P(0)=(r,0)','원에 감긴 실을 팽팽하게 풀 때 끝점이 그리는 인벌류트의 매개식을 유도하라. 매개변수는 접촉점 반지름의 반시계 회전각이다.','Derive the involute traced by the taut end of a string unwound from a circle. The parameter is the counterclockwise angle of the radius to the contact point.',[r'T=(r\cos\theta,r\sin\theta),\quad |TP|=r\theta',r'\widehat{TP}=(\sin\theta,-\cos\theta),\quad P=T+r\theta\widehat{TP}'],r'x=r(\cos\theta+\theta\sin\theta),\quad y=r(\sin\theta-\theta\cos\theta)','실의 직선 부분은 접촉점의 반지름에 수직이고 그 길이는 풀린 원호 길이와 같다. 초기 좌표도 일치한다.','The straight string is perpendicular to the contact radius and equals the unwound arc length; the initial coordinates also agree.')
svg(85,'Circle and its involute (r=1)',[('circle',sample(math.cos,math.sin,0,2*math.pi)),('involute',sample(lambda t:math.cos(t)+t*math.sin(t),lambda t:math.sin(t)-t*math.cos(t),0,2.5))])
# Final structure and independent mathematical checks.
items.sort(key=lambda e:e['number'])
raw={'section':'10.2','source':{'title':'Calculus','edition':'9','language':'en','printedPages':list(range(717,723)),'pdfPages':list(range(754,760))},'scope':{'kind':'exercise','numbers':list(range(1,86)),'total':85,'note':bi('일반 연습문제 전체. 원문 도형은 함수로부터 자체 재작성했다.','All ordinary exercises. Figures are original plots from the mathematical functions.')},'exercises':items}
assert [e['number'] for e in items]==list(range(1,86))
import re,xml.etree.ElementTree as ET
for e in items:
 for f in ['statement','answer']:
  assert re.findall(r'\\\((.*?)\\\)',e[f]['ko'])==re.findall(r'\\\((.*?)\\\)',e[f]['en']),(e['number'],f)
 if 'figure' in e:ET.parse(BASE/'exercise-content'/e['figure']['src'].replace('../exercise-content/',''))
def clean(x):
 if isinstance(x,str):assert not any(ord(c)<32 and c!='\n' for c in x),repr(x)
 elif isinstance(x,dict):
  for v in x.values():clean(v)
 elif isinstance(x,list):
  for v in x:clean(v)
clean(raw)
path=BASE/'exercise-content/s10-2.json';sys.path.insert(0,str(BASE));import build_exercises as build
build.validate_document(raw,path)
path.write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
assert S.integrate((2*t-t*t)*3*t*t,(t,0,2))==S.Rational(24,5)
assert S.integrate(2*(t*t-t**4),(t,-1,1))==S.Rational(8,15)
assert S.integrate(2*t*(t**3-3*t)**2,(t,0,S.sqrt(3)))==S.Rational(27,4)
assert S.simplify((S.diff(S.exp(t)-t,t)**2+S.diff(4*S.exp(t/2),t)**2)-(S.exp(t)+1)**2)==0
print('10.2:',len(items),'cards;',sum('figure' in e for e in items),'SVG; bilingual math, XML, quadrature repetition and symbolic checks passed')
