import json,math,html,sys
from pathlib import Path
BASE=Path(__file__).resolve().parents[1];items=[]
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':e if e is not None else k}
def add(n,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=706 if n<=15 else 707 if n<=34 else 708 if n<=50 else 709 if n<=56 else 710
 items.append(dict(id=f'stewart9-exercise-10.1-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('매개변수 곡선','Parametric curves'),statement=bi(sk,se),hint=bi('같은 매개변수 값을 두 좌표에 넣고 정의역과 진행 방향을 유지한다.','Pair coordinates at the same parameter, retaining domain and orientation.'),steps={'ko':[x[0] for x in steps],'en':[x[1] for x in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def sample(f,g,a,b,N=1200):
 out=[]
 for i in range(N+1):
  t=a+(b-a)*i/N
  try:out.append((f(t),g(t)))
  except(ValueError,ZeroDivisionError,OverflowError):out.append((math.nan,math.nan))
 return out
def svg(n,title,curves,bounds=None,arrows=True):
 valid=[(x,y) for label,pts in curves for x,y in pts if math.isfinite(x) and math.isfinite(y)]
 if bounds:xl,xh,yl,yh=bounds
 else:
  xl=min(x for x,y in valid);xh=max(x for x,y in valid);yl=min(y for x,y in valid);yh=max(y for x,y in valid)
  d=max(xh-xl,yh-yl,1)*.08;xl-=d;xh+=d;yl-=d;yh+=d
 scale=500/max(xh-xl,yh-yl);mx=(xl+xh)/2;my=(yl+yh)/2;X=lambda x:310+(x-mx)*scale;Y=lambda y:310-(y-my)*scale
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 665"><rect width="100%" height="100%" fill="white"/>',f'<text x="35" y="25" font-size="15" fill="#172b4d">{html.escape(title)}</text>','<rect x="45" y="45" width="530" height="530" fill="#f6f8fc" stroke="#c5cfdd"/>']
 if yl<=0<=yh:out.append(f'<path d="M45 {Y(0):.2f}H575" stroke="#7e8a9d"/><text x="580" y="{Y(0):.2f}" font-size="12">x</text>')
 if xl<=0<=xh:out.append(f'<path d="M{X(0):.2f} 45V575" stroke="#7e8a9d"/><text x="{X(0)+5:.2f}" y="55" font-size="12">y</text>')
 for z,(label,pts) in enumerate(curves):
  col=['#1463c2','#c44933','#17926f','#8953b4','#bf8800','#444'][z%6];path='';paths=[]
  for x,y in pts:
   if math.isfinite(x) and math.isfinite(y) and xl<=x<=xh and yl<=y<=yh:path+=('M' if not path else 'L')+f'{X(x):.2f},{Y(y):.2f}'
   elif path:paths.append(path);path=''
  if path:paths.append(path)
  for path in paths:out.append(f'<path d="{path}" stroke="{col}" stroke-width="2" fill="none"/>')
  if arrows:
   for frac in [.2,.55,.8]:
    i=min(int(len(pts)*frac),len(pts)-2);a,b=pts[i],pts[i+1]
    if not(all(math.isfinite(v) for v in (*a,*b)) and xl<a[0]<xh and yl<a[1]<yh):continue
    ux,uy=X(b[0])-X(a[0]),Y(b[1])-Y(a[1]);mag=math.hypot(ux,uy)
    if mag<1e-8:continue
    ux,uy=ux/mag,uy/mag;px,py=X(b[0]),Y(b[1]);out.append(f'<path d="M{px-8*ux+3*uy:.2f},{py-8*uy-3*ux:.2f}L{px:.2f},{py:.2f}L{px-8*ux-3*uy:.2f},{py-8*uy+3*ux:.2f}" stroke="{col}" stroke-width="2" fill="none"/>')
  out.append(f'<text x="{45+(z%2)*280}" y="{600+18*(z//2)}" font-size="11" fill="{col}">{html.escape(label)}</text>')
 out.append(f'<text x="45" y="650" font-size="10">Equal axis scale; x: {xl:.3g} .. {xh:.3g}; y: {yl:.3g} .. {yh:.3g}</text></svg>');p=BASE/f'exercise-content/assets/s10-1-{n}.svg';p.write_text(''.join(out));next(e for e in items if e['number']==n)['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('직접 계산한 매개변수 곡선과 진행 방향','Computed parametric curves and orientation'),'caption':bi('자체 도해. 축의 단위 길이는 같으며 화살표는 매개변수 증가 방향이다.','Original plot with equal axis scale; arrows indicate increasing parameter.')}
for n,eq,points in [(1,r'x=t^2+t,\quad y=3^{t+1}',r'(2,1/3),(0,1),(0,3),(2,9),(6,27)'),(2,r'x=\ln(t^2+1),\quad y=t/(t+4)',r'(\ln5,-1),(\ln2,-1/3),(0,0),(\ln2,1/5),(\ln5,1/3)')]:
 add(n,M(eq)+'에서 '+M(r't=-2,-1,0,1,2')+'에 대응하는 점을 순서대로 구하라.','For '+M(eq)+', list the points at '+M(r't=-2,-1,0,1,2')+' in order.', [('각 매개변수 값을 두 식에 동시에 대입한다.','Substitute each parameter into both equations.'),('좌표쌍의 순서는 지정된 매개변수 순서를 따른다.','Coordinate pairs follow the specified parameter order.')],M(points),M(points),'분모와 로그의 정의 조건을 모든 지정 입력에서 확인했다.','Denominator and logarithm domains were checked at each specified input.')
# Every basic sketch includes the parameter domain and a directed original plot.
rows=[
(3,r'x=1-t^2,\ y=2t-t^2,\ -1\le t\le2',lambda t:1-t*t,lambda t:2*t-t*t,-1,2,r'(x-y-1)^2=4(1-x),\quad -1\le t\le2','표본 점은 영·음삼, 일·영, 영·일, 음삼·영 순이다.','Sample points are (0,-3), (1,0), (0,1), and (-3,0), in that order.'),
(4,r'x=t^3+t,\ y=t^2+2,\ -2\le t\le2',lambda t:t**3+t,lambda t:t*t+2,-2,2,r'x^2=(y-2)(y-1)^2,\quad2\le y\le6','가로좌표는 엄격히 증가한다. 왼쪽 위에서 영·이를 거쳐 오른쪽 위로 간다.','The horizontal coordinate strictly increases, moving from upper left through (0,2) to upper right.'),
(5,r'x=2^t-t,\ y=2^{-t}+t,\ -3\le t\le3',lambda t:2**t-t,lambda t:2**(-t)+t,-3,3,r't=-3,0,3:\quad(25/8,5),(1,1),(5,25/8)','매개변수 부호를 바꾸면 두 좌표가 교환되어 대각선 대칭이다. 도중에 원점 가까운 작은 고리를 만든다.','Reversing the parameter swaps coordinates, giving diagonal symmetry; a small loop occurs near the central portion.'),
(6,r'x=\cos^2t,\ y=1+\cos t,\ 0\le t\le\pi',lambda t:math.cos(t)**2,lambda t:1+math.cos(t),0,math.pi,r'x=(y-1)^2,\quad0\le y\le2','일·이에서 영·일을 지나 일·영으로 내려간다.','It descends from (1,2) through (0,1) to (1,0).'),
(7,r'x=2t-1,\ y=t/2+1',lambda t:2*t-1,lambda t:t/2+1,-3,3,r'y=x/4+5/4','두 좌표가 함께 증가하므로 왼쪽 아래에서 오른쪽 위로 간다.','Both coordinates increase, moving from lower left to upper right.'),
(8,r'x=3t+2,\ y=2t+3',lambda t:3*t+2,lambda t:2*t+3,-3,3,r'y=2x/3+5/3','두 좌표가 함께 증가한다.','Both coordinates increase.'),
(9,r'x=t^2-3,\ y=t+2,\ -3\le t\le3',lambda t:t*t-3,lambda t:t+2,-3,3,r'x=(y-2)^2-3,\quad-1\le y\le5','육·음일부터 왼쪽 꼭짓점 음삼·이를 거쳐 육·오로 올라간다.','It rises from (6,-1) through the left vertex (-3,2) to (6,5).'),
(10,r'x=\sin t,\ y=1-\cos t,\ 0\le t\le2\pi',math.sin,lambda t:1-math.cos(t),0,2*math.pi,r'x^2+(y-1)^2=1','원점에서 오른쪽으로 출발해 반시계 방향으로 한 바퀴 돈다.','Starting at the origin, it initially moves right and makes one counterclockwise revolution.'),
(11,r'x=\sqrt t,\ y=1-t',math.sqrt,lambda t:1-t,0,4,r'y=1-x^2,\quad x\ge0','매개변수는 음이 아니며 영·일에서 오른쪽 아래로 간다.','The parameter is nonnegative; motion goes from (0,1) down and right.'),
(12,r'x=t^2,\ y=t^3',lambda t:t*t,lambda t:t**3,-2,2,r'y^2=x^3,\quad x\ge0','아래 가지에서 원점 첨점으로 접근한 뒤 위 가지를 따라 나간다.','The lower branch approaches the origin cusp, then exits along the upper branch.'),
(13,r'x=3\cos t,\ y=3\sin t,\ 0\le t\le\pi',lambda t:3*math.cos(t),lambda t:3*math.sin(t),0,math.pi,r'x^2+y^2=9,\quad y\ge0','삼·영에서 음삼·영까지 위 반원을 반시계로 돈다.','It traces the upper semicircle counterclockwise from (3,0) to (-3,0).'),
(14,r'x=\sin4\theta,\ y=\cos4\theta,\ 0\le\theta\le\pi/2',lambda t:math.sin(4*t),lambda t:math.cos(4*t),0,math.pi/2,r'x^2+y^2=1','영·일에서 시계 방향으로 한 바퀴 돈다.','It makes one clockwise revolution starting at (0,1).'),
(15,r'x=\cos\theta,\ y=\sec^2\theta,\ 0\le\theta<\pi/2',math.cos,lambda t:1/math.cos(t)**2,0,1.35,r'y=1/x^2,\quad0<x\le1','일·일에서 왼쪽 위로 이동하며 세로축에 점근한다.','It moves up and left from (1,1), approaching the vertical axis.'),
(16,r'x=\csc t,\ y=\cot t,\ 0<t<\pi',lambda t:1/math.sin(t),lambda t:1/math.tan(t),.15,math.pi-.15,r'x^2-y^2=1,\quad x\ge1','오른쪽 쌍곡선 가지를 위에서 일·영을 거쳐 아래로 내려간다.','It descends the right hyperbola branch through (1,0).'),
(17,r'x=e^{-t},\ y=e^t',lambda t:math.exp(-t),math.exp,-2,2,r'xy=1,\quad x>0,\ y>0','입력이 증가하면 가로좌표는 감소하고 세로좌표는 증가한다.','Increasing the parameter decreases the horizontal coordinate and increases the vertical coordinate.'),
(18,r'x=t+2,\ y=1/t,\ t>0',lambda t:t+2,lambda t:1/t,.15,6,r'y=1/(x-2),\quad x>2','오른쪽 아래 방향으로 가며 수직선 이와 가로축에 점근한다.','It moves down and right with asymptotes at horizontal coordinate two and the horizontal axis.'),
(19,r'x=\ln t,\ y=\sqrt t,\ t\ge1',math.log,math.sqrt,1,10,r'y=e^{x/2},\quad x\ge0','영·일부터 오른쪽 위로 간다.','It starts at (0,1) and moves up and right.'),
(20,r'x=|t|,\ y=|1-|t||',abs,lambda t:abs(1-abs(t)),-3,3,r'y=|1-x|,\quad x\ge0','음의 매개변수에서는 오른쪽에서 영·일로 들어오고 양의 매개변수에서는 같은 궤적을 되짚어 나간다.','For negative parameter it moves from the right toward (0,1), then retraces outward for positive parameter.'),
(21,r'x=\sin^2t,\ y=\cos^2t',lambda t:math.sin(t)**2,lambda t:math.cos(t)**2,0,math.pi,r'x+y=1,\quad0\le x,y\le1','영·일과 일·영 사이의 선분을 계속 왕복한다.','It repeatedly traverses the segment between (0,1) and (1,0).'),
(22,r'x=\sinh t,\ y=\cosh t',math.sinh,math.cosh,-2,2,r'y^2-x^2=1,\quad y\ge1','위쪽 쌍곡선 가지를 왼쪽에서 오른쪽으로 간다.','It traverses the upper hyperbola branch from left to right.')]
for n,eq,f,g,a,b,ans,k,e in rows:
 if n<=6:sk='점을 찍어 곡선과 진행 방향을 그려라.';se='Plot points and sketch the curve with orientation.';sub=''
 elif n<=12:sk='(a) 곡선과 방향을 그리고 (b) 매개변수를 제거하라.';se='(a) Sketch with orientation and (b) eliminate the parameter.';sub='ab'
 else:sk='(a) 매개변수를 제거하고 (b) 곡선과 방향을 그려라.';se='(a) Eliminate the parameter and (b) sketch with orientation.';sub='ab'
 add(n,M(eq)+' '+sk,M(eq)+' '+se,[('좌표의 공통 매개변수를 대수적으로 소거하거나 기본 항등식을 사용한다.','Eliminate the common parameter algebraically or use a standard identity.'),(k,e)],M(ans),M(ans),'원래 매개식에 대입한 점들이 직교좌표 식과 정의역을 만족한다. 무한 곡선은 유한 표시창에 그렸다.','Points from the parameterization satisfy the Cartesian relation and domain. Infinite curves are shown in a finite window.',sub)
 svg(n,f'Exercise {n}: increasing parameter',[('parametric curve',sample(f,g,a,b))])
for n,eq,ans,k,e,f,g,a,b in [(23,r'x=5\cos t,\ y=-5\sin t',r'T=2\pi\ \mathrm s','오른쪽 끝에서 아래로 출발하므로 시계 방향이다.','Starting at the rightmost point and moving downward gives clockwise motion.',lambda t:5*math.cos(t),lambda t:-5*math.sin(t),0,2*math.pi),(24,r'x=3\sin(\pi t/4),\ y=3\cos(\pi t/4)',r'T=8\ \mathrm s','위쪽 끝에서 오른쪽으로 출발하므로 시계 방향이다.','Starting at the top and moving right gives clockwise motion.',lambda t:3*math.sin(math.pi*t/4),lambda t:3*math.cos(math.pi*t/4),0,8)]:
 add(n,M(eq)+'인 원운동의 한 바퀴 시간과 방향을 구하라.','Find the revolution time and direction for '+M(eq)+'.',[('각도의 변화가 한 바퀴에 해당하는 시간을 계산한다.','Find the time for the angle to increase through one full turn.'),(k,e)],M(ans)+'; 시계 방향.',M(ans)+'; clockwise.','시작점의 속도벡터와 주기 복귀를 확인했다.','Checked the starting velocity and return after one period.')
 svg(n,'Circular motion',[('one revolution',sample(f,g,a,b))])
for n,eq,ans,k,e,f,g,a,b in [
(25,r'x=5+2\cos\pi t,\ y=3+2\sin\pi t,\ 1\le t\le2',r'(x-5)^2+(y-3)^2=4','삼·삼에서 오·일을 거쳐 칠·삼으로, 아래 반원을 반시계 방향으로 간다.','It moves counterclockwise along the lower semicircle from (3,3) through (5,1) to (7,3).',lambda t:5+2*math.cos(math.pi*t),lambda t:3+2*math.sin(math.pi*t),1,2),
(26,r'x=2+\sin t,\ y=1+3\cos t,\ \pi/2\le t\le2\pi',r'(x-2)^2+(y-1)^2/9=1','삼·일부터 이·음이, 일·일을 거쳐 이·사로 시계 방향 사분의 삼 바퀴 간다.','It moves clockwise three quarters of a revolution from (3,1) through (2,-2) and (1,1) to (2,4).',lambda t:2+math.sin(t),lambda t:1+3*math.cos(t),math.pi/2,2*math.pi),
(27,r'x=5\sin t,\ y=2\cos t,\ -\pi\le t\le5\pi',r'x^2/25+y^2/4=1','영·음이에서 시작하여 시계 방향 세 바퀴 돈다.','It starts at (0,-2) and makes three clockwise revolutions.',lambda t:5*math.sin(t),lambda t:2*math.cos(t),-math.pi,5*math.pi),
(28,r'x=\sin t,\ y=\cos^2t,\ -2\pi\le t\le2\pi',r'y=1-x^2,\quad-1\le x\le1','영·일에서 일·영, 영·일, 음일·영, 영·일의 순서를 두 번 반복한다.','It repeats twice the sequence (0,1), (1,0), (0,1), (-1,0), (0,1).',math.sin,lambda t:math.cos(t)**2,-2*math.pi,2*math.pi)]:
 add(n,M(eq)+'인 입자의 움직임을 설명하라.','Describe the particle motion for '+M(eq)+'.',[('중심 이동을 제거하고 삼각항등식을 적용한다.','Remove the center translation and use a trigonometric identity.'),(k,e)],M(ans)+'; '+k,M(ans)+'; '+e,'매개변수 구간의 양끝과 사분주기 지점의 좌표를 대입 확인했다.','Endpoint and quarter-period coordinates were checked.')
 svg(n,'Directed motion over the stated interval',[('path',sample(f,g,a,b))])
add(29,M(r'x=f(t),\ y=g(t),\quad\mathrm{range}(f)=[1,4],\quad\mathrm{range}(g)=[2,3]')+'에서 곡선의 위치에 대해 무엇을 말할 수 있는가?','What can be concluded about a curve with '+M(r'x=f(t),\ y=g(t),\quad\mathrm{range}(f)=[1,4],\quad\mathrm{range}(g)=[2,3]')+'?', [('각 좌표의 범위가 곡선을 직사각형 안에 가둔다.','The coordinate ranges constrain the curve to a rectangle.'),('각 범위의 끝값은 어딘가에서 달성하지만 두 끝값이 같은 매개변수에서 달성될 필요는 없다.','Each coordinate endpoint is achieved somewhere, but two endpoints need not occur at the same parameter.')],M(r'\text{curve}\subset[1,4]\times[2,3]')+'; 네 변에는 각각 닿지만 꼭짓점을 지날 필요는 없다.',M(r'\text{curve}\subset[1,4]\times[2,3]')+'; it meets each side but need not pass through a corner.','두 좌표의 값 범위만으로 곡선 모양이나 내부 전체를 채우는지는 결정할 수 없다.','Coordinate ranges alone do not determine shape or whether the interior is filled.')
add(30,'좌표 그래프 쌍을 원문의 곡선 I–IV와 대응시켜라. (a) 가로좌표는 일에서 이로 올라갔다 일로, 세로좌표는 영→양→영→음→영. (b) 두 좌표는 각각 두 번·세 번 진동. (c) 가로좌표는 홀함수 삼차형, 세로좌표는 위 반원. (d) 가로좌표는 깊은 최소 뒤 평평해지고 세로좌표는 가운데 봉우리이다.','Match coordinate-graph pairs to source curves I–IV. (a) Horizontal coordinate rises from one to two and returns; vertical coordinate cycles zero-positive-zero-negative-zero. (b) Coordinates oscillate two and three times. (c) Horizontal coordinate is an odd cubic shape, vertical coordinate an upper semicircle. (d) Horizontal coordinate has a deep minimum then a plateau; vertical coordinate has a central peak.', [('(a)는 첫사분면과 넷째사분면에 걸친 오른쪽 고리이다. (b)는 다중 교차 Lissajous 도형이다.','(a) is a right-side loop across the first and fourth quadrants. (b) is a multiply crossing Lissajous figure.'),('(c)는 세로좌표가 음이 아니고 가운데 교차를 갖는다. 남은 완만한 삼각 고리는 (d)이다.','(c) stays above the horizontal axis with a central crossing. The remaining rounded triangular loop belongs to (d).')],M(r'\text{(a) III, (b) I, (c) IV, (d) II}'),M(r'\text{(a) III, (b) I, (c) IV, (d) II}'),'동일 매개변수의 좌표를 짝지어 원문 개형·범위와 맞추었다.','Paired equal-parameter coordinates match the source shapes and ranges.','abcd')
# Four original schematic panels for the graph-matching exercise.
def multi(n,configs):
 p=BASE/f'exercise-content/assets/s10-1-{n}.svg';parts=[]
 for title,curves,bounds in configs:
  svg(n,title,curves,bounds);s=p.read_text();parts.append(s[s.index('>')+1:s.rindex('</svg>')])
 p.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 {665*len(parts)}">'+''.join(f'<g transform="translate(0,{665*i})">{s}</g>' for i,s in enumerate(parts))+'</svg>')
multi(30,[('a -> III: representative pair',[('x=1+sin(pi t), y=sin(2pi t)',sample(lambda t:1+math.sin(math.pi*t),lambda t:math.sin(2*math.pi*t),0,1))],None),('b -> I: representative pair',[('two vs three oscillations',sample(lambda t:2*math.sin(4*math.pi*t),lambda t:2*math.sin(6*math.pi*t),0,1))],None),('c -> IV: representative pair',[('cubic and semicircle',sample(lambda t:t**3-3*t,lambda t:math.sqrt(4-t*t),-2,2))],None),('d -> II: representative pair',[('minimum and central peak',sample(lambda t:2-3*math.exp(-(t+1)**2/.2),lambda t:-2+4*math.exp(-t*t/.3),-2,2))],None)])
for n,sk,se,ans,k,e,f,g,a,b in [(31,'가로좌표 그래프는 꼭짓점이 원점인 위로 열린 포물선, 세로좌표 그래프는 원점을 지나는 감소 직선이다.','The horizontal-coordinate graph is an upward parabola with vertex at zero; the vertical-coordinate graph is a decreasing line through zero.',r'x=y^2','위 오른쪽에서 원점으로 들어와 아래 오른쪽으로 나간다.','It enters from upper right, reaches the origin, and exits lower right.',lambda t:t*t,lambda t:-t,-1.5,1.5),(32,'가로좌표는 음일부터 일까지 끝값 영·중앙 일인 아래로 열린 포물선이다. 세로좌표는 앞 절반 음수, 뒤 절반 양수인 한 번의 사인형 진동이다.','The horizontal coordinate is a downward parabola on minus one to one with zero endpoints and unit middle value. The vertical coordinate is negative on the first half and positive on the second, completing one sine-like cycle.',r'0\le x\le1,\quad-1\le y\le1','원점에서 오른쪽 아래로 나가 일·영을 지나 왼쪽 위로 원점에 돌아오는 반시계 고리이다.','It leaves the origin down and right, passes (1,0), then returns up and left in a counterclockwise loop.',lambda t:1-t*t,lambda t:math.sin(math.pi*t),-1,1),(33,'가로좌표는 음일·영에서 영·일을 거쳐 일·영으로 가는 삼각형 그래프, 세로좌표는 원점 꼭짓점의 위로 열린 포물선이다.','The horizontal-coordinate graph is a triangular tent from (-1,0) through (0,1) to (1,0); the vertical coordinate is an upward parabola with vertex at zero.',r'y=(1-x)^2,\quad0\le x\le1','영·일부터 일·영까지 곡선을 간 뒤 같은 부분을 되짚는다.','It moves from (0,1) to (1,0), then retraces the same arc.',lambda t:1-abs(t),lambda t:t*t,-1,1)]:
 add(n,sk+' 두 좌표의 매개변수 곡선을 방향과 함께 그려라.',se+' Sketch the parametric curve with orientation.', [('같은 시간의 좌표를 대응시키며 끝점·극값·중간점을 이용한다.','Pair coordinates at equal times, using endpoints, extrema, and the midpoint.'),(k,e)],M(ans)+'; '+k,M(ans)+'; '+e,'도해의 단위 포물선·직선 또는 대표 사인형 보간을 사용한 개형이다.','The sketch uses the unit parabolas and lines, or a representative sine-shaped interpolation shown by the source.')
 svg(n,'Curve inferred from coordinate graphs',[('representative paired graphs',sample(f,g,a,b))])
match=[('a',r'x=t^4-t+1,\ y=t^2','V',lambda t:t**4-t+1,lambda t:t*t,-1.8,1.8),('b',r'x=t^2-2t,\ y=\sqrt t','I',lambda t:t*t-2*t,math.sqrt,0,3),('c',r'x=t^3-2t,\ y=t^2-t','II',lambda t:t**3-2*t,lambda t:t*t-t,-1.8,2),('d',r'x=\cos5t,\ y=\sin2t','VI',lambda t:math.cos(5*t),lambda t:math.sin(2*t),0,2*math.pi),('e',r'x=t+\sin4t,\ y=t^2+\cos3t','IV',lambda t:t+math.sin(4*t),lambda t:t*t+math.cos(3*t),-3,3),('f',r'x=t+\sin2t,\ y=t+\sin3t','III',lambda t:t+math.sin(2*t),lambda t:t+math.sin(3*t),-6,6)]
st34='; '.join('('+letter+') '+M(eq) for letter,eq,*_ in match)
add(34,st34+'을 원문의 그래프 I–VI와 대응시키고 이유를 설명하라.', 'Match '+st34+' to source graphs I–VI and explain.', [('제곱근 식은 위쪽만 그리며 시작점에서 왼쪽으로 휘므로 I이다. 사차 가로좌표와 제곱 세로좌표는 V의 두 위쪽 가지를 준다.','The square-root equation stays above the axis and initially bends left, giving I. Quartic horizontal and squared vertical coordinates give V’s two upper branches.'),('삼차식은 II의 고리, 두 유계 삼각함수는 VI이다. 세로방향 제곱 성장은 IV, 두 좌표의 선형 추세는 III을 준다.','The cubic equation gives II’s loop; the two bounded trigonometric coordinates give VI. Quadratic vertical growth gives IV, and two linear trends give III.')],M(r'\text{a V; b I; c II; d VI; e IV; f III}'),M(r'\text{a V; b I; c II; d VI; e IV; f III}'),'각 매개식을 직접 샘플링한 자체 그림으로 대칭성·유계성·교차를 원문과 대조했다.','Directly sampled plots match source symmetry, boundedness, and intersections.','abcdef')
multi(34,[(f'{letter} -> {label}',[(eq,sample(f,g,a,b))],None) for letter,eq,label,f,g,a,b in match])
add(35,M(r'x=y-2\sin(\pi y)')+'를 그려라.','Graph '+M(r'x=y-2\sin(\pi y)')+'.',[('세로좌표를 매개변수로 둔다.','Use the vertical coordinate as parameter.'),(M(r'x=t-2\sin\pi t,\ y=t')+'을 같은 시간 간격으로 찍는다.',M(r'x=t-2\sin\pi t,\ y=t')+' is sampled at shared parameter values.')],M(r'x=t-2\sin\pi t,\quad y=t,\quad t\in\mathbb R'),M(r'x=t-2\sin\pi t,\quad y=t,\quad t\in\mathbb R'),'가로좌표는 대각선에서 최대 이만큼 옆으로 진동하며 세로좌표는 계속 증가한다.','The horizontal coordinate oscillates at most two units from the diagonal while the vertical coordinate increases.')
svg(35,'x=y-2sin(pi y)',[('t=y',sample(lambda t:t-2*math.sin(math.pi*t),lambda t:t,-4,4))])
add(36,M(r'y=x^3-4x,\quad x=y^3-4y')+'를 그리고 모든 교점을 소수 첫째 자리까지 구하라.','Plot '+M(r'y=x^3-4x,\quad x=y^3-4y')+' and find all intersections to one decimal place.', [('두 식의 차와 합을 인수분해하면 '+M(r'(x-y)(x^2+xy+y^2-3)=0,\quad(x+y)(x^2-xy+y^2-5)=0')+'.','Subtracting and adding gives '+M(r'(x-y)(x^2+xy+y^2-3)=0,\quad(x+y)(x^2-xy+y^2-5)=0')+'.'),('대각선에서는 영과 제곱근 오, 반대각선에서는 제곱근 삼을 얻는다. 나머지는 '+M(r'xy=-1,\ x^2+y^2=4')+'이다.','The diagonal gives zero and square roots of five; the opposite diagonal gives square roots of three. Remaining points satisfy '+M(r'xy=-1,\ x^2+y^2=4')+'.')],M(r'(0,0),(2.2,2.2),(-2.2,-2.2),(1.7,-1.7),(-1.7,1.7),(1.9,-0.5),(-0.5,1.9),(0.5,-1.9),(-1.9,0.5)'),M(r'(0,0),(2.2,2.2),(-2.2,-2.2),(1.7,-1.7),(-1.7,1.7),(1.9,-0.5),(-0.5,1.9),(0.5,-1.9),(-1.9,0.5)'),'인수분해의 모든 경우를 조사해 아홉 교점을 얻었고 정확한 근으로 원식을 검증했다.','All factor cases give nine intersections; exact roots verify the original equations.')
svg(36,'Intersections of reflected cubics',[('y=x^3-4x',sample(lambda t:t,lambda t:t**3-4*t,-3,3)),('x=y^3-4y',sample(lambda t:t**3-4*t,lambda t:t,-3,3))],(-3,3,-3,3))
add(37,'(a) '+M(r'(x,y)=(1-t)(x_1,y_1)+t(x_2,y_2),\quad0\le t\le1')+'이 두 점 사이 선분을 나타냄을 보이고 (b) '+M(r'(-2,7),(3,-1)')+'에 적용하라.','(a) Show '+M(r'(x,y)=(1-t)(x_1,y_1)+t(x_2,y_2),\quad0\le t\le1')+' describes their joining segment and (b) apply it to '+M(r'(-2,7),(3,-1)')+'.',[('초기 매개변수에서 첫 점, 마지막에서 둘째 점이 되며 변위는 고정 방향벡터의 상수배이다.','The endpoints give the first and second point, and displacement is a scalar multiple of a fixed direction vector.'),('두 끝점의 좌표 차는 '+M(r'(5,-8)')+'이다.','The endpoint difference is '+M(r'(5,-8)')+'.')],M(r'x=-2+5t,\quad y=7-8t,\quad0\le t\le1'),M(r'x=-2+5t,\quad y=7-8t,\quad0\le t\le1'),'가중치가 음이 아니고 합이 일이므로 선분 밖으로 벗어나지 않는다.','The weights are nonnegative and sum to one, keeping the point on the segment.','ab')
add(38,M(r'A=(1,1),\ B=(4,2),\ C=(1,5)')+'인 삼각형을 매개변수 선분으로 그려라.','Draw the triangle '+M(r'A=(1,1),\ B=(4,2),\ C=(1,5)')+' using parametric segments.', [('각 변을 시작점과 끝점의 선형보간으로 나타낸다.','Represent each edge by linear interpolation of its endpoints.'),('각 매개변수를 영부터 일까지 움직여 세 변을 연결한다.','Move each parameter from zero to one to join the three edges.')],M(r'AB:(1+3t,1+t);\quad BC:(4-3t,2+3t);\quad CA:(1,5-4t),\quad0\le t\le1'),M(r'AB:(1+3t,1+t);\quad BC:(4-3t,2+3t);\quad CA:(1,5-4t),\quad0\le t\le1'),'세 변의 끝점이 다음 변의 시작점과 일치한다.','Each edge endpoint equals the next edge’s start.')
svg(38,'Triangle ABC',[('AB',sample(lambda t:1+3*t,lambda t:1+t,0,1)),('BC',sample(lambda t:4-3*t,lambda t:2+3*t,0,1)),('CA',sample(lambda t:1,lambda t:5-4*t,0,1))])
for n,sk,se,ans in [(39,'원점 중심 반지름 오의 원을 시계 방향으로 돌며 한 바퀴에 사 파이 초 걸리는 운동을 나타내라.','Parameterize clockwise motion on a radius-five circle centered at the origin with a revolution taking four pi seconds.',r'x=5\cos(t/2),\quad y=-5\sin(t/2)'),(40,'중심 일·삼, 반지름 일의 원을 반시계 방향으로 돌며 한 바퀴에 삼 초 걸리는 운동을 나타내라.','Parameterize counterclockwise motion on the unit circle centered at (1,3) with a three-second revolution.',r'x=1+\cos(2\pi t/3),\quad y=3+\sin(2\pi t/3)')]:
 add(n,sk,se,[('각속도는 한 바퀴 각도를 주기로 나눈 값이다.','Angular speed is one full-turn angle divided by the period.'),('중심과 반지름을 적용하고 사인항의 부호로 방향을 정한다.','Apply center and radius, using the sine sign for orientation.')],M(ans),M(ans),'주기만큼 시간이 증가하면 같은 점으로 돌아오고 초기 속도는 요청된 방향이다.','One period returns the point, and initial velocity has the requested orientation.')
add(41,M(r'x^2+(y-1)^2=4')+'에서 (a) '+M(r'(2,1)')+'부터 시계 한 바퀴, (b) '+M(r'(2,1)')+'부터 반시계 세 바퀴, (c) '+M(r'(0,3)')+'부터 반시계 반 바퀴를 나타내라.','On '+M(r'x^2+(y-1)^2=4')+', parameterize (a) one clockwise turn from '+M(r'(2,1)')+', (b) three counterclockwise turns from '+M(r'(2,1)')+', and (c) half a counterclockwise turn from '+M(r'(0,3)')+'.', [('중심은 영·일이고 반지름은 이이다. 시작 각도와 매개변수 구간을 바꾼다.','The center is (0,1) and radius two. Adjust starting angle and parameter interval.'),('마지막 경우에는 시작 각도를 파이의 절반으로 둔다.','For the last case use a starting angle of half pi.')],M(r'\text{(a) }(2\cos t,1-2\sin t),\ 0\le t\le2\pi;\quad\text{(b) }(2\cos t,1+2\sin t),\ 0\le t\le6\pi;\quad\text{(c) }(-2\sin t,1+2\cos t),\ 0\le t\le\pi'),M(r'\text{(a) }(2\cos t,1-2\sin t),\ 0\le t\le2\pi;\quad\text{(b) }(2\cos t,1+2\sin t),\ 0\le t\le6\pi;\quad\text{(c) }(-2\sin t,1+2\cos t),\ 0\le t\le\pi'),'초기점과 총 각도 변화가 각각 조건과 일치한다.','Starting points and total angle changes satisfy all cases.','abc')
add(42,'(a) '+M(r'x^2/a^2+y^2/b^2=1')+'을 매개화하고 (b) '+M(r'a=3,\ b=1,2,4,8')+'을 그려 (c) 높이 매개변수의 효과를 설명하라.','(a) Parameterize '+M(r'x^2/a^2+y^2/b^2=1')+', (b) plot '+M(r'a=3,\ b=1,2,4,8')+', and (c) describe the vertical parameter’s effect.', [('단위원의 두 좌표를 각 축 반경만큼 확대한다.','Scale unit-circle coordinates by each semiaxis.'),('가로 폭은 육으로 일정하고 세로 높이는 매개변수의 두 배이다.','Width stays six while height is twice the vertical semiaxis.')],M(r'x=a\cos t,\quad y=b\sin t,\quad0\le t\le2\pi')+'; 높이가 증가하며 두 반경이 같을 때 원이다.',M(r'x=a\cos t,\quad y=b\sin t,\quad0\le t\le2\pi')+'; increasing height gives a circle when semiaxes agree.','삼각항등식으로 원래 타원식이 정확히 성립한다.','The trigonometric identity verifies the ellipse equation.','abc')
svg(42,'Ellipses with a=3',[('b='+str(b),sample(lambda t:3*math.cos(t),lambda t:b*math.sin(t),0,2*math.pi)) for b in [1,2,4,8]])
add(43,'중심 이·이, 반지름 이의 얼굴 윤곽, 위쪽 두 눈과 아래쪽 반원 미소로 이루어진 그림을 매개변수 곡선으로 재현하라.','Reproduce a face with center (2,2), radius two, two upper eyes, and a lower semicircular smile using parametric curves.', [('윤곽과 눈은 중심 이동한 원으로, 입은 아래 반원으로 나타낸다.','Use translated circles for the outline and eyes and a lower semicircle for the mouth.'),('눈의 작은 반지름은 영점일로 선택하면 원문의 모양을 재현한다.','Choosing eye radius 0.1 reproduces the source appearance.')],M(r'\text{outline: }(2+2\cos t,2+2\sin t);\ \text{eyes: }(1+0.1\cos t,3+0.1\sin t),(3+0.1\cos t,3+0.1\sin t),\ 0\le t\le2\pi;\ \text{mouth: }(2+\cos t,2+\sin t),\ \pi\le t\le2\pi'),M(r'\text{outline: }(2+2\cos t,2+2\sin t);\ \text{eyes: }(1+0.1\cos t,3+0.1\sin t),(3+0.1\cos t,3+0.1\sin t),\ 0\le t\le2\pi;\ \text{mouth: }(2+\cos t,2+\sin t),\ \pi\le t\le2\pi'),'윤곽은 두 축에 접하고 입의 양끝은 얼굴 중앙 높이에 놓인다.','The outline is tangent to both axes and the mouth endpoints lie at the center height.')
svg(43,'Parametric smiley',[('outline',sample(lambda t:2+2*math.cos(t),lambda t:2+2*math.sin(t),0,2*math.pi)),('left eye',sample(lambda t:1+.1*math.cos(t),lambda t:3+.1*math.sin(t),0,2*math.pi)),('right eye',sample(lambda t:3+.1*math.cos(t),lambda t:3+.1*math.sin(t),0,2*math.pi)),('smile',sample(lambda t:2+math.cos(t),lambda t:2+math.sin(t),math.pi,2*math.pi))],arrows=False)
add(44,'바퀴 중심의 가로좌표가 삼과 팔인 수레 그림을 재현하라. 바닥, 왼쪽 짧은 수직선, 오른쪽 수직선과 오른쪽 위 손잡이를 선분으로, 바퀴를 원호로 구성하라.','Reproduce a cart with wheel centers at horizontal coordinates three and eight. Use segments for its base, short left side, right vertical side and upward-right handle, and circular arcs for wheels.', [('기준점을 정해 각 선분을 두 끝점의 선형보간으로 만든다.','Choose reference points and linearly interpolate each segment’s endpoints.'),('바퀴 윗부분은 수레 밑판에 가려지도록 아래 원호만 표시한다.','Show lower wheel arcs so their tops are hidden behind the cart base.')],M(r'\text{body vertices }(1,4),(1,1.5),(10,1.5),(10,4),(13,7);\quad\text{wheels }(3+\cos t,1+\sin t),(8+\cos t,1+\sin t),\quad5\pi/6\le t\le13\pi/6'),M(r'\text{body vertices }(1,4),(1,1.5),(10,1.5),(10,4),(13,7);\quad\text{wheels }(3+\cos t,1+\sin t),(8+\cos t,1+\sin t),\quad5\pi/6\le t\le13\pi/6'),'그림 재현은 눈금 사이 위치의 한 가능한 선택이며 선분 끝점과 원호가 같은 바닥 높이에서 만난다.','This reproduction is one possible placement between tick marks; segments and wheel arcs meet the same base height.')
body=[(1,4),(1,1.5),(10,1.5),(10,4),(13,7)];svg(44,'Cart built from segments and circular arcs',[('body',body)]+[(f'wheel at x={c}',sample(lambda t:c+math.cos(t),lambda t:1+math.sin(t),5*math.pi/6,13*math.pi/6)) for c in [3,8]],arrows=False)
add(45,'(a) '+M(r'\text{(i) }x=t^2,y=t;\ \text{(ii) }x=t,y=\sqrt t;\ \text{(iii) }x=\cos^2t,y=\cos t;\ \text{(iv) }x=3^{2t},y=3^t')+'의 공통 직교좌표식을 찾고 (b) 각 곡선을 그려 차이를 설명하라.','(a) Find the common Cartesian equation for '+M(r'\text{(i) }x=t^2,y=t;\ \text{(ii) }x=t,y=\sqrt t;\ \text{(iii) }x=\cos^2t,y=\cos t;\ \text{(iv) }x=3^{2t},y=3^t')+' and (b) plot and distinguish the curves.', [('모든 식에서 가로좌표가 세로좌표의 제곱이다.','In every case the horizontal coordinate is the square of the vertical coordinate.'),('첫째는 전체 포물선, 둘째는 꼭짓점 포함 위쪽 절반, 셋째는 제한된 중앙 부분의 왕복, 넷째는 꼭짓점 제외 위쪽 절반이다.','The first traces the whole parabola, the second its upper half including the vertex, the third repeatedly traces a bounded middle portion, and the fourth traces the upper half excluding the vertex.')],M(r'x=y^2;\quad\text{(i) }y\in\mathbb R;\ \text{(ii) }y\ge0;\ \text{(iii) }-1\le y\le1;\ \text{(iv) }y>0'),M(r'x=y^2;\quad\text{(i) }y\in\mathbb R;\ \text{(ii) }y\ge0;\ \text{(iii) }-1\le y\le1;\ \text{(iv) }y>0'),'같은 대수식이라도 매개변수 범위에 따라 실제 점 집합과 진행 방식이 달라진다.','The same algebraic equation can have different traced sets and traversal patterns because of parameter ranges.','ab')
multi(45,[('i: full parabola',[('all real t',sample(lambda t:t*t,lambda t:t,-2,2))],None),('ii: upper half including vertex',[('t>=0',sample(lambda t:t,math.sqrt,0,4))],None),('iii: bounded portion retraced',[('periodic',sample(lambda t:math.cos(t)**2,math.cos,0,2*math.pi))],None),('iv: positive branch, no vertex',[('all real t',sample(lambda t:3**(2*t),lambda t:3**t,-2,1))],None)])
add(46,'곡선 '+M(r'\text{(a) }x=t,y=t^{-2};\ \text{(b) }x=\cos t,y=\sec^2t;\ \text{(c) }x=e^t,y=e^{-2t}')+'를 비교하라.','Compare '+M(r'\text{(a) }x=t,y=t^{-2};\ \text{(b) }x=\cos t,y=\sec^2t;\ \text{(c) }x=e^t,y=e^{-2t}')+'.', [('모든 경우에 '+M(r'y=1/x^2')+'이다. 실제 가로좌표 범위를 따로 구한다.','All satisfy '+M(r'y=1/x^2')+'. Determine the actual horizontal ranges separately.'),('둘째는 코사인의 왕복 때문에 제한된 두 가지를 반복한다. 셋째는 오른쪽 가지를 오른쪽 아래로 한 번 따라간다.','The cosine case retraces two restricted branches. The exponential case traverses the right branch down and right once.')],M(r'\text{(a) }x\ne0;\quad\text{(b) }0<|x|\le1;\quad\text{(c) }x>0'),M(r'\text{(a) }x\ne0;\quad\text{(b) }0<|x|\le1;\quad\text{(c) }x>0'),'세 경우 모두 입력이 영인 점은 곡선에 포함되지 않는다.','Zero horizontal coordinate is excluded in all three cases.','abc')
add(47,'곡선 '+M(r'\text{(a) }x=t^3,y=t^2;\ \text{(b) }x=t^6,y=t^4;\ \text{(c) }x=e^{-3t},y=e^{-2t}')+'를 비교하라.','Compare '+M(r'\text{(a) }x=t^3,y=t^2;\ \text{(b) }x=t^6,y=t^4;\ \text{(c) }x=e^{-3t},y=e^{-2t}')+'.', [('세 경우 모두 '+M(r'y^3=x^2,\quad y\ge0')+'을 만족한다.','All satisfy '+M(r'y^3=x^2,\quad y\ge0')+'.'),('첫째는 왼쪽 가지에서 원점을 거쳐 오른쪽으로 간다. 둘째는 오른쪽 가지를 원점까지 갔다 되짚는다. 셋째는 원점을 포함하지 않는 오른쪽 가지를 원점 쪽으로 간다.','The first moves from the left through the origin to the right. The second traces the right branch to the origin and back. The third approaches the excluded origin along the right branch.')],M(r'\text{(a) }x\in\mathbb R;\quad\text{(b) }x\ge0;\quad\text{(c) }x>0'),M(r'\text{(a) }x\in\mathbb R;\quad\text{(b) }x\ge0;\quad\text{(c) }x>0'),'지수함수는 영이 되지 않고 짝수 거듭제곱은 음수가 되지 않는다는 조건을 유지했다.','The exponential never vanishes and even powers never become negative.','abc')
add(48,'반지름이 '+M(r'r')+'인 원이 가로축을 미끄럼 없이 굴러갈 때 원주 위 점의 cycloid 공식을 '+M(r'\pi/2<\theta<\pi')+'에서도 유도하라.','Derive the cycloid formulas for a radius '+M(r'r')+' circle rolling without slipping along the horizontal axis in the case '+M(r'\pi/2<\theta<\pi')+'.', [('굴러간 거리는 회전 호길이이므로 중심 좌표는 '+M(r'(r\theta,r)')+'이다.','No slip makes travel distance equal the rotated arc length, so the center is '+M(r'(r\theta,r)')+'.'),('점은 중심 왼쪽 위에 있고 중심으로부터의 변위는 '+M(r'(-r\sin\theta,-r\cos\theta)')+'이다. 이 구간에서는 코사인이 음수라 세로변위가 양수이다.','The point is above-left of the center with displacement '+M(r'(-r\sin\theta,-r\cos\theta)')+'. Cosine is negative here, giving positive vertical displacement.')],M(r'x=r(\theta-\sin\theta),\quad y=r(1-\cos\theta)'),M(r'x=r(\theta-\sin\theta),\quad y=r(1-\cos\theta)'),'사분면에 따른 부호를 포함하므로 첫 사분면 공식과 같은 식이 연속적으로 이어진다.','The quadrant signs make the same formulas continue consistently from the first quadrant.')
add(49,'반지름 '+M(r'r')+'의 구르는 원 중심에서 거리 '+M(r'd')+'인 점이 가장 낮을 때 회전각을 영으로 둔다. trochoid 식을 유도하고 중심거리의 두 경우를 그려라.','A circle of radius '+M(r'r')+' rolls with a point at distance '+M(r'd')+' from its center. Set angle zero at its lowest position, derive the trochoid equations, and plot the two distance regimes.', [('중심은 가로방향으로 반지름 곱 회전각만큼 이동한다. 점의 상대 변위는 회전된 아래쪽 반지름 벡터이다.','The center moves horizontally by radius times angle. The point’s relative displacement is the rotated downward radius vector.'),('중심거리가 반지름보다 작으면 가로속도가 항상 양수이다. 더 크면 가로속도가 잠시 음수가 되어 고리가 생긴다.','When the point distance is smaller than radius, horizontal velocity stays positive; a larger distance gives temporary backward motion and loops.')],M(r'x=r\theta-d\sin\theta,\quad y=r-d\cos\theta;\quad d<r:\ \text{no loops};\quad d>r:\ \text{loops}'),M(r'x=r\theta-d\sin\theta,\quad y=r-d\cos\theta;\quad d<r:\ \text{no loops};\quad d>r:\ \text{loops}'),'거리가 반지름과 같으면 원주 위의 cycloid 첨점이 된다.','Equality gives the cycloid with its cusps.')
multi(49,[(f'r=1, d={d}',[(f'd={d}',sample(lambda t:t-d*math.sin(t),lambda t:1-d*math.cos(t),0,4*math.pi))],None) for d in [.5,1,1.5]])
add(50,'중심이 세로축 위 높이 a에 있고 반지름 '+M(r'a')+'인 원이 원점에 접한다. 원점에서 각도 '+M(r'\theta')+'의 반직선이 원과 만나는 점을 Q, 직선 '+M(r'y=2a')+'와 만나는 점을 R이라 한다. Q와 R의 중점 궤적을 매개화하라.','A radius '+M(r'a')+' circle centered at (0,a) touches the origin. A ray at angle '+M(r'\theta')+' meets the circle at Q and the line '+M(r'y=2a')+' at R. Parameterize the midpoint of QR.', [('원 위의 점까지 반지름 방향 거리는 '+M(r'OQ=2a\sin\theta')+'이다.','The radial distance to the circle is '+M(r'OQ=2a\sin\theta')+'.'),(M(r'Q=(2a\sin\theta\cos\theta,2a\sin^2\theta),\quad R=(2a\cot\theta,2a)')+'의 좌표를 평균한다.','Average coordinates of '+M(r'Q=(2a\sin\theta\cos\theta,2a\sin^2\theta),\quad R=(2a\cot\theta,2a)')+'.')],M(r'x=a(\sin\theta\cos\theta+\cot\theta),\quad y=a(1+\sin^2\theta),\quad0<\theta<\pi'),M(r'x=a(\sin\theta\cos\theta+\cot\theta),\quad y=a(1+\sin^2\theta),\quad0<\theta<\pi'),'중앙 각도에서 두 교점이 같아져 중점은 원의 꼭대기이다. 양끝 각도는 수평 점근 높이로 간다.','At the middle angle the intersections coincide at the circle’s top. At the limiting angles the curve approaches a horizontal asymptotic height.')
add(51,'동심원의 반지름은 '+M(r'a>b>0')+'이다. 원점의 각도 반직선과 큰 원의 교점에서 가로좌표를, 작은 원의 교점에서 세로좌표를 취한 점의 매개식과 직교좌표식을 구하라.','Two concentric circles have radii '+M(r'a>b>0')+'. Take the horizontal coordinate from the large-circle intersection of an angular ray and the vertical coordinate from the small-circle intersection. Find the parameterization and Cartesian curve.', [('큰 원의 가로좌표와 작은 원의 세로좌표는 같은 각도에 대한 코사인·사인이다.','The large-circle horizontal and small-circle vertical coordinates use cosine and sine of the same angle.'),('각 반지름으로 나누어 제곱하고 더한다.','Divide by the respective radius, square, and add.')],M(r'x=a\cos\theta,\quad y=b\sin\theta;\quad x^2/a^2+y^2/b^2=1'),M(r'x=a\cos\theta,\quad y=b\sin\theta;\quad x^2/a^2+y^2/b^2=1'),'가로 반경과 세로 반경이 다른 타원이다.','This is an ellipse with the two stated semiaxes.')
add(52,'반지름 '+M(r'a>b>0')+'의 동심원에서 큰 원의 각도 교점 A에 접선을 그어 가로축 교점 B를 얻는다. 점 P는 B의 가로좌표와 같은 각도 작은 원 점의 세로좌표를 갖는다. P를 매개화하라.','For concentric radii '+M(r'a>b>0')+', the tangent at the large-circle angular point A meets the horizontal axis at B. Point P uses B’s horizontal coordinate and the small-circle angular point’s vertical coordinate. Parameterize P.', [('접선 방정식은 '+M(r'x\cos\theta+y\sin\theta=a')+'이다.','The tangent equation is '+M(r'x\cos\theta+y\sin\theta=a')+'.'),('가로축에서는 세로좌표가 영이므로 가로 교점을 구할 수 있다.','Set the vertical coordinate to zero to find the horizontal intercept.')],M(r'x=a\sec\theta,\quad y=b\sin\theta,\quad\cos\theta\ne0'),M(r'x=a\sec\theta,\quad y=b\sin\theta,\quad\cos\theta\ne0'),'가로축과 평행한 접선은 유한 교점이 없으므로 해당 각도를 제외했다.','Angles giving a tangent parallel to the horizontal axis have no finite intercept and are excluded.')
add(53,'원점에 접하는 중심 '+M(r'(0,a)')+', 반지름 '+M(r'a')+'의 원에서 원점의 각도 반직선이 원과 만나는 A와 직선 '+M(r'y=2a')+'와 만나는 C를 잡는다. A의 높이와 C의 가로좌표를 갖는 점의 식을 유도하고 곡선을 그려라.','For a circle centered at '+M(r'(0,a)')+' with radius '+M(r'a')+' and tangent to the origin, an angular ray meets the circle at A and the line '+M(r'y=2a')+' at C. Derive and plot the point with A’s height and C’s horizontal coordinate.', [('반직선과 수평선의 교점은 가로좌표가 '+M(r'2a\cot\theta')+'이다.','The horizontal-line intersection has horizontal coordinate '+M(r'2a\cot\theta')+'.'),('원 교점의 반지름 방향 거리는 '+M(r'2a\sin\theta')+'이므로 그 높이는 사인 제곱에 비례한다.','The radial circle intersection distance is '+M(r'2a\sin\theta')+', making its height proportional to sine squared.')],M(r'x=2a\cot\theta,\quad y=2a\sin^2\theta,\quad0<\theta<\pi;\quad y=\frac{8a^3}{x^2+4a^2}'),M(r'x=2a\cot\theta,\quad y=2a\sin^2\theta,\quad0<\theta<\pi;\quad y=\frac{8a^3}{x^2+4a^2}'),'곡선은 세로축 대칭이며 최고 높이는 두 배 반지름이고 양끝에서 영으로 간다.','The curve is symmetric about the vertical axis, peaks at twice the radius, and tends to zero at both ends.')
svg(53,'Witch of Agnesi: a=1',[('x=2cot(theta), y=2sin^2(theta)',sample(lambda t:2/math.tan(t),lambda t:2*math.sin(t)**2,.12,math.pi-.12))],(-8,8,-.2,2.3))
add(54,'중심 '+M(r'(a,0)')+', 반지름 '+M(r'a')+'의 원과 직선 '+M(r'x=2a')+'를 원점에서 같은 반직선으로 만나 각각 A,B를 얻는다. '+M(r'OP=AB')+'인 같은 반직선 위 점의 (a) 매개식과 (b) 곡선을 구하라.','A ray from the origin meets the circle centered at '+M(r'(a,0)')+' with radius '+M(r'a')+' at A and the line '+M(r'x=2a')+' at B. Find (a) a parameterization and (b) the curve for the point on the ray satisfying '+M(r'OP=AB')+'.', [(M(r'OA=2a\cos\theta,\quad OB=2a\sec\theta')+'이므로 두 거리의 차를 좌표방향으로 분해한다.',M(r'OA=2a\cos\theta,\quad OB=2a\sec\theta')+' gives the radial difference to resolve into coordinates.'),(M(r't=\tan\theta')+'를 써서 유리 매개식으로 만들 수 있다.',M(r't=\tan\theta')+' converts it into a rational parameterization.')],M(r'x=\frac{2at^2}{1+t^2},\quad y=\frac{2at^3}{1+t^2};\quad y^2=\frac{x^3}{2a-x},\quad0\le x<2a'),M(r'x=\frac{2at^2}{1+t^2},\quad y=\frac{2at^3}{1+t^2};\quad y^2=\frac{x^3}{2a-x},\quad0\le x<2a'),'원점 첨점에서 두 대칭 가지가 뻗으며 오른쪽 수직선에 점근한다.','Two symmetric branches emerge from the origin cusp and approach the right vertical asymptote.','ab')
svg(54,'Cissoid: a=1',[('rational parameterization',sample(lambda t:2*t*t/(1+t*t),lambda t:2*t**3/(1+t*t),-5,5))],(-.2,2.2,-6,6))
add(55,'빨강 입자 '+M(r'(x,y)=(t+5,t^2+4t+6)')+', 파랑 입자 '+M(r'(x,y)=(2t+1,2t+6)')+'에 대해 (a) '+M(r'(1,6),(6,11)')+'의 경로 교차와 충돌을 구분하라. (b) 초록 입자 '+M(r'(x,y)=(2t+4,2t+9)')+'의 경로와 빨강과의 충돌을 구하라.','For red '+M(r'(x,y)=(t+5,t^2+4t+6)')+' and blue '+M(r'(x,y)=(2t+1,2t+6)')+', (a) distinguish path intersections at '+M(r'(1,6),(6,11)')+' from collisions. (b) Find the path of green '+M(r'(x,y)=(2t+4,2t+9)')+' and its collisions with red.', [('빨강 경로는 '+M(r'y=(x-3)^2+2')+', 파랑과 초록 경로는 '+M(r'y=x+5')+'이다. 두 식의 교점에서 시간을 따로 계산한다.','The red path is '+M(r'y=(x-3)^2+2')+' and blue and green follow '+M(r'y=x+5')+'. Compute each particle’s time at the intersections.'),('첫 교점에서 빨강·파랑 시간은 음사·영, 둘째에서는 일·이점오로 서로 다르다. 초록과 빨강의 가로좌표를 같은 시간에 같게 놓으면 시간 일이 나온다.','At the first intersection red and blue arrive at minus four and zero; at the second, one and 2.5. Equal-time horizontal coordinates for green and red give time one.')],M(r'\text{red-blue: no collision};\quad\text{red-green: }t=1,\ (x,y)=(6,11)'),M(r'\text{red-blue: no collision};\quad\text{red-green: }t=1,\ (x,y)=(6,11)'),'초록과 빨강은 그 시간에 세로좌표도 같음을 확인했다. 경로 교점만으로 충돌을 주장하지 않았다.','Green and red also have the same vertical coordinate at that time; path intersection alone does not establish collision.','ab')
add(56,'입자 일의 '+M(r'x=3\sin t,y=2\cos t')+'와 입자 이의 '+M(r'x=-3+\cos t,y=1+\sin t,\quad0\le t\le2\pi')+'에 대해 (a) 경로 그림과 교점 수, (b) 충돌, (c) 둘째 경로를 '+M(r'x=3+\cos t,y=1+\sin t')+'로 바꾼 결과를 구하라.','For particle one '+M(r'x=3\sin t,y=2\cos t')+' and particle two '+M(r'x=-3+\cos t,y=1+\sin t,\quad0\le t\le2\pi')+', find (a) path plots and intersection count, (b) collisions, and (c) the result of changing the second path to '+M(r'x=3+\cos t,y=1+\sin t')+'.', [('타원과 왼쪽 원의 경로 교점은 두 개이다. 같은 시간 충돌에는 '+M(r'3\sin t=-3+\cos t,\quad2\cos t=1+\sin t')+'가 동시에 필요하다.','The ellipse and left circle have two path intersections. Collision requires '+M(r'3\sin t=-3+\cos t,\quad2\cos t=1+\sin t')+' simultaneously.'),('연립하면 코사인 영·사인 음일이다. 오른쪽 원으로 바꾸면 같은 시간 조건이 코사인 값이 일점이여야 하므로 불가능하다.','The system gives cosine zero and sine minus one. For the right circle equal-time conditions would require cosine six fifths, which is impossible.')],M(r'\text{(a) }2\ \text{intersections};\quad\text{(b) }t=3\pi/2,\ (-3,0);\quad\text{(c) }2\ \text{path intersections, no collisions}'),M(r'\text{(a) }2\ \text{intersections};\quad\text{(b) }t=3\pi/2,\ (-3,0);\quad\text{(c) }2\ \text{path intersections, no collisions}'),'왼쪽 교점 높이는 영과 약 일점사삼이고 오른쪽 원은 이를 세로축 대칭한 경로이다.','The left intersection heights are zero and about 1.43; the right-circle paths are the vertical-axis reflection.','abc')
svg(56,'Ellipse and two possible circular paths',[('ellipse',sample(lambda t:3*math.sin(t),lambda t:2*math.cos(t),0,2*math.pi)),('left circle',sample(lambda t:-3+math.cos(t),lambda t:1+math.sin(t),0,2*math.pi)),('right circle',sample(lambda t:3+math.cos(t),lambda t:1+math.sin(t),0,2*math.pi))])
add(57,'자기 교차점과 서로 다른 매개변수 값을 구하라: (a) '+M(r'x=1-t^2,y=t-t^3')+', (b) '+M(r'x=2t-t^3,y=t-t^2')+'.','Find self-intersections and distinct parameter values for (a) '+M(r'x=1-t^2,y=t-t^3')+' and (b) '+M(r'x=2t-t^3,y=t-t^2')+'.', [('(a) 가로좌표가 같으려면 두 매개변수는 반대 부호이다. 세로좌표까지 같으려면 영이 아닌 값에서 제곱이 일이다.','(a) Equal horizontal coordinates require opposite parameters. Equal vertical coordinates then require unit square for nonzero parameters.'),('(b) 서로 다른 매개변수를 써서 두 좌표 차를 인수분해하면 '+M(r't+s=1,\quad ts=-1')+'을 얻는다.','(b) Factoring coordinate differences for distinct parameters yields '+M(r't+s=1,\quad ts=-1')+'.')],M(r'\text{(a) }(0,0),\ t=\pm1;\quad\text{(b) }(-1,-1),\ t=(1\pm\sqrt5)/2'),M(r'\text{(a) }(0,0),\ t=\pm1;\quad\text{(b) }(-1,-1),\ t=(1\pm\sqrt5)/2'),'두 시간 값을 각각 원래 두 좌표식에 넣어 같은 점을 얻었다.','Both distinct parameter values were substituted into both coordinates to recover the same point.','ab')
v=500;g=9.8;alpha=math.pi/6;T58=2*v*math.sin(alpha)/g;D58=v*v*math.sin(2*alpha)/g;H58=(v*math.sin(alpha))**2/(2*g)
add(58,'공기저항을 무시한 운동 '+M(r'x=(v_0\cos\alpha)t,\ y=(v_0\sin\alpha)t-gt^2/2')+'에서 (a) '+M(r'v_0=500,\alpha=30^\circ,g=9.8')+'의 착지 시간·거리·최고 높이, (b) 여러 각도 그래프와 비교, (c) 포물선 식을 구하라.','For motion neglecting air resistance '+M(r'x=(v_0\cos\alpha)t,\ y=(v_0\sin\alpha)t-gt^2/2')+', find (a) flight time, range and peak height for '+M(r'v_0=500,\alpha=30^\circ,g=9.8')+', (b) plots for several angles and comparisons, and (c) its parabolic equation.', [('양의 착지 시간은 높이의 두 번째 영점이고 최고점은 세로속도가 영인 시점이다.','The positive flight time is the second height zero; the maximum occurs when vertical velocity vanishes.'),(M(r'T=2v_0\sin\alpha/g,\quad D=v_0^2\sin2\alpha/g,\quad H=v_0^2\sin^2\alpha/(2g)')+'이다. 여각끼리는 거리가 같고 사십오 도에서 거리가 최대이다.',M(r'T=2v_0\sin\alpha/g,\quad D=v_0^2\sin2\alpha/g,\quad H=v_0^2\sin^2\alpha/(2g)')+'. Complementary angles give equal range, maximized at forty-five degrees.')],M(rf'T={T58:.6f}\ \mathrm s,\quad D={D58:.6f}\ \mathrm m,\quad H={H58:.6f}\ \mathrm m;\quad y=x\tan\alpha-\frac{{gx^2}}{{2v_0^2\cos^2\alpha}}'),M(rf'T={T58:.6f}\ \mathrm s,\quad D={D58:.6f}\ \mathrm m,\quad H={H58:.6f}\ \mathrm m;\quad y=x\tan\alpha-\frac{{gx^2}}{{2v_0^2\cos^2\alpha}}'),'높이 영 조건과 최고점의 도함수 영을 수치와 대수식에서 함께 확인했다.','Height zeros and the zero derivative at the maximum were verified numerically and algebraically.','abc')
svg(58,'Ideal projectile paths; meters',[(f'angle={deg} degrees',sample(lambda t:v*math.cos(a)*t,lambda t:v*math.sin(a)*t-g*t*t/2,0,2*v*math.sin(a)/g)) for deg in [15,30,45,60,75] for a in [math.radians(deg)]])
add(59,M(r'x=t^2,\ y=t^3-ct')+'에서 매개상수를 늘릴 때 모양 변화를 여러 그래프로 조사하라.','Investigate '+M(r'x=t^2,\ y=t^3-ct')+' for increasing parameter values, using several plots.', [('매개변수 부호를 바꾸면 세로좌표 부호만 바뀐다. 제거식은 '+M(r'y^2=x(x-c)^2')+'이다.','Reversing the parameter flips the vertical coordinate. Elimination gives '+M(r'y^2=x(x-c)^2')+'.'),('음의 상수에서는 매끄러운 오른쪽 곡선, 영에서는 첨점, 양수에서는 원점과 자기 교차점 사이에 고리가 생긴다.','Negative constants give a smooth right-side curve, zero gives a cusp, and positive constants create a loop between the origin and a self-intersection.')],M(r'c<0:\ \text{no loop};\ c=0:\ y^2=x^3;\ c>0:\ \text{crossing }(c,0),\ t=\pm\sqrt c')+'; 양의 상수가 커지면 고리의 폭과 높이가 커진다.',M(r'c<0:\ \text{no loop};\ c=0:\ y^2=x^3;\ c>0:\ \text{crossing }(c,0),\ t=\pm\sqrt c')+'; increasing positive values enlarge loop width and height.','두 좌표가 같은 서로 다른 매개변수가 존재하는 조건으로 고리 생성 여부를 검증했다.','Loop onset was checked by the existence of distinct parameters giving the same coordinates.')
multi(59,[(f'c={c}',[(f'c={c}',sample(lambda t:t*t,lambda t:t**3-c*t,-2.5,2.5))],None) for c in [-1,0,1,2,4]])
add(60,M(r'x=2ct-4t^3,\ y=-ct^2+3t^4')+'의 여러 그래프를 그리고 공통점과 상수 증가의 영향을 조사하라.','Plot several curves '+M(r'x=2ct-4t^3,\ y=-ct^2+3t^4')+' and investigate common features and increasing parameter values.', [('가로좌표는 홀함수, 세로좌표는 짝함수라 세로축 대칭이고 모두 원점을 지난다.','Horizontal coordinate is odd and vertical coordinate even, giving vertical-axis symmetry and passage through the origin.'),(M(r'x^{\prime}=2c-12t^2,\quad y^{\prime}=-t x^{\prime}')+'에서 양의 상수일 때 두 첨점이 생긴다. 음수에서는 가로좌표가 단조이며 교차가 없다.',M(r'x^{\prime}=2c-12t^2,\quad y^{\prime}=-t x^{\prime}')+' yields two cusps for positive constants. Negative constants give monotone horizontal coordinate and no crossing.')],M(r'c>0:\ t_{cusp}=\pm\sqrt{c/6},\quad(x,y)=(\pm\tfrac43c\sqrt{c/6},-c^2/12);\quad\text{crossing }(0,c^2/4),\ t=\pm\sqrt{c/2}'),M(r'c>0:\ t_{cusp}=\pm\sqrt{c/6},\quad(x,y)=(\pm\tfrac43c\sqrt{c/6},-c^2/12);\quad\text{crossing }(0,c^2/4),\ t=\pm\sqrt{c/2}'),'양의 상수 족은 매개변수를 제곱근 상수로 재척도하면 가로는 상수의 삼의 이분의 일승, 세로는 제곱에 비례해 확대된다.','Rescaling the parameter by the square root of a positive constant scales horizontal size by its three-halves power and vertical size by its square.')
multi(60,[(f'c={c}',[(f'c={c}',sample(lambda t:2*c*t-4*t**3,lambda t:-c*t*t+3*t**4,-1.5,1.5))],None) for c in [-2,0,1,2,4]])
add(61,M(r'x=t+a\cos t,\ y=t+a\sin t,\quad a>0')+'의 모양과 고리 발생 조건을 여러 그래프로 조사하라.','Investigate shape and loop onset for '+M(r'x=t+a\cos t,\ y=t+a\sin t,\quad a>0')+' with several plots.', [('좌표를 대각선 방향으로 회전하면 일정한 전진에 원운동을 더한 trochoid 꼴이 된다.','Rotating coordinates along the diagonal turns the curve into constant translation plus circular motion, a trochoid form.'),('접선벡터가 영이 되려면 '+M(r'1-a\sin t=0,\quad1+a\cos t=0')+'이므로 임계 크기는 제곱근 이이다. 이보다 커지면 회전 좌표의 진행방향 속도가 뒤집힌다.','Zero tangent requires '+M(r'1-a\sin t=0,\quad1+a\cos t=0')+', giving threshold square root of two. Larger values reverse the forward velocity in rotated coordinates.')],M(r'0<a<\sqrt2:\ \text{no loops};\quad a=\sqrt2:\ \text{cusps};\quad a>\sqrt2:\ \text{loops}'),M(r'0<a<\sqrt2:\ \text{no loops};\quad a=\sqrt2:\ \text{cusps};\quad a>\sqrt2:\ \text{loops}'),'한 주기 뒤 두 좌표는 각각 두 파이만큼 평행이동되어 같은 모양이 반복된다.','After one period both coordinates translate by two pi, repeating the shape.')
multi(61,[(f'a={a:.4f}',[(f'a={a:.4f}',sample(lambda t:t+a*math.cos(t),lambda t:t+a*math.sin(t),-2*math.pi,2*math.pi))],None) for a in [.5,1,math.sqrt(2),2,3]])
add(62,M(r'x=\sin t+\sin nt,\ y=\cos t+\cos nt,\quad n\in\mathbb N')+'의 여러 곡선을 그리고 정수 증가에 따른 공통점과 변화를 조사하라.','Plot and investigate '+M(r'x=\sin t+\sin nt,\ y=\cos t+\cos nt,\quad n\in\mathbb N')+' as the positive integer increases.', [('합차공식으로 '+M(r'x=2\cos\frac{(n-1)t}2\sin\frac{(n+1)t}2,\quad y=2\cos\frac{(n-1)t}2\cos\frac{(n+1)t}2')+'이다.','Sum formulas give '+M(r'x=2\cos\frac{(n-1)t}2\sin\frac{(n+1)t}2,\quad y=2\cos\frac{(n-1)t}2\cos\frac{(n+1)t}2')+'.'),('모든 곡선은 세로축 대칭이고 반지름 이 원판 안에 있다. 일에서는 원이며 큰 정수일수록 원점 통과와 감기는 구조가 많아진다.','All curves are symmetric about the vertical axis and lie in the radius-two disk. Integer one gives a circle; larger integers increase origin passages and the winding structure.')],M(r'x^2+y^2=4\cos^2((n-1)t/2);\quad n=1:\ x^2+y^2=4;\quad n>1:\ t=(2j+1)\pi/(n-1)\ \text{gives the origin}'),M(r'x^2+y^2=4\cos^2((n-1)t/2);\quad n=1:\ x^2+y^2=4;\quad n>1:\ t=(2j+1)\pi/(n-1)\ \text{gives the origin}'),'고리 수를 그림만 보고 단정하지 않고 정확한 원점 통과식과 유계·대칭성을 사용했다.','The classification uses exact origin passages, bounds, and symmetry, rather than inferring loop counts from an image alone.')
multi(62,[(f'n={n}',[(f'n={n}',sample(lambda t:math.sin(t)+math.sin(n*t),lambda t:math.cos(t)+math.cos(n*t),0,2*math.pi,2400))],(-2.2,2.2,-2.2,2.2)) for n in [1,2,3,4,5,6]])
add(63,M(r'x=a\sin nt,\ y=b\cos t,\quad a,b>0,\ n\in\mathbb N')+'인 Lissajous 곡선을 그리고 세 매개변수의 효과를 조사하라.','Plot the Lissajous family '+M(r'x=a\sin nt,\ y=b\cos t,\quad a,b>0,\ n\in\mathbb N')+' and investigate the three parameters.', [('두 양의 실수는 가로·세로 크기를 독립적으로 확대한다. 정수는 세로좌표가 한 주기 도는 동안 가로좌표의 진동 수이다.','The positive real parameters independently scale horizontal and vertical size. The integer counts horizontal oscillations during one vertical cycle.'),('위쪽 끝에서 아래쪽 끝까지 가는 동안 세로좌표는 단조이며 가로좌표는 정수 개의 반파를 만든다. 돌아오는 부분은 세로축 반사이므로 세로로 쌓인 고리가 만들어진다.','From top to bottom the vertical coordinate is monotone while the horizontal coordinate makes the specified number of half-waves. The return is its vertical-axis reflection, producing vertically stacked lobes.')],M(r'|x|\le a,\ |y|\le b;\quad n=1:\ x^2/a^2+y^2/b^2=1;\quad n\ \text{stacked lobes},\quad x=0,\ y=b\cos(j\pi/n),\ j=1,\ldots,n-1\ \text{internal crossings}'),M(r'|x|\le a,\ |y|\le b;\quad n=1:\ x^2/a^2+y^2/b^2=1;\quad n\ \text{stacked lobes},\quad x=0,\ y=b\cos(j\pi/n),\ j=1,\ldots,n-1\ \text{internal crossings}'),'두 좌표축에 대한 대칭성과 교차 높이는 삼각함수의 영점으로 검증된다.','Symmetry about both coordinate axes and crossing heights follow from trigonometric zeros.')
multi(63,[(f'a={a}, b={b}, n={n}',[(f'({a},{b},{n})',sample(lambda t:a*math.sin(n*t),lambda t:b*math.cos(t),0,2*math.pi,2400))],None) for a,b,n in [(1,1,1),(1,1,2),(1,1,3),(1,1,4),(2,1,3),(1,2,3)]])
add(64,M(r'x=\cos t,\ y=\sin t-\sin ct,\quad c>0')+'을 양의 정수와 분수에서 그려 변화 양상을 조사하라.','Plot '+M(r'x=\cos t,\ y=\sin t-\sin ct,\quad c>0')+' for positive integers and fractions and investigate changing shapes.', [('항상 가로좌표는 음일부터 일, 세로좌표는 음이부터 이 사이이다. 매개변수 부호를 바꾸면 세로좌표 부호가 바뀌어 가로축 대칭이다.','Horizontal coordinates always lie between minus one and one and vertical coordinates between minus two and two. Reversing the parameter reverses vertical sign, giving horizontal-axis symmetry.'),('정수 일에서는 세로좌표가 항상 영이다. 정수 이·삼의 제거식은 '+M(r'c=2:\ y^2=(1-x^2)(1-2x)^2;\quad c=3:\ y^2=4(1-x^2)(1-2x^2)^2')+'로 교차·접촉 위치를 설명한다.','For integer one the vertical coordinate is identically zero. Integer two and three satisfy '+M(r'c=2:\ y^2=(1-x^2)(1-2x)^2;\quad c=3:\ y^2=4(1-x^2)(1-2x^2)^2')+', locating intersections and contacts.'),('정수가 커지면 빠른 사인항이 더 많은 굴곡을 만든다. 기약 분수에서는 두 진동이 함께 닫힐 때까지 더 긴 구간을 그려야 한다.','Larger integers add bends through the faster sine term. Reduced fractions require a longer interval for the two oscillations to close together.')],M(r'c=1:\ y=0,\ -1\le x\le1;\quad c=p/q\ \text{in lowest terms}:\ 0\le t\le2\pi q\ \text{is a full closing interval}'),M(r'c=1:\ y=0,\ -1\le x\le1;\quad c=p/q\ \text{in lowest terms}:\ 0\le t\le2\pi q\ \text{is a full closing interval}'),'분수 예시는 분모만큼 긴 매개변수 구간을 사용하여 일부 궤적을 전체로 잘못 보지 않도록 했다.','Fractional examples use the denominator-scaled interval, avoiding mistaking a partial trace for the whole curve.')
multi(64,[(f'c={p}/{q}',[(f'c={p}/{q}',sample(math.cos,lambda t:math.sin(t)-math.sin(p/q*t),0,2*math.pi*q,2400*q))],(-1.2,1.2,-2.2,2.2)) for p,q in [(1,1),(2,1),(3,1),(4,1),(1,2),(3,2),(2,3)]])
assert len(items)==64
raw=dict(section='10.1',source=dict(title='Calculus',edition='9',language='en',printedPages=[706,707,708,709,710],pdfPages=[743,744,745,746,747]),scope=dict(kind='exercise',numbers=list(range(1,65)),total=64,note=bi('전체 64문항과 모든 소문항.','All 64 exercises and every subpart.')),exercises=items)
p=BASE/'exercise-content/s10-1.json';p.write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n');sys.path.insert(0,str(BASE));import build_exercises as b;b.validate_document(raw,p)
print('10.1:64 cards; assets',len(list((BASE/'exercise-content/assets').glob('s10-1-*.svg'))))
