import json,math,html,sys,ast,re
from pathlib import Path
import sympy as S
import mpmath as mp
BASE=Path(__file__).resolve().parents[1];items=[];t=S.symbols('t',real=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(n,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=737 if n<=4 else 738 if n<=44 else 739 if n<=62 else 740
 items.append(dict(id=f'stewart9-exercise-10.4-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('극좌표의 미적분','Calculus in polar coordinates'),statement=bi(sk,se),hint=bi('원점을 따로 확인하고 실제 영역을 한 번만 세는 각도 구간을 정한다.','Check the pole separately and choose angular intervals that count the actual region once.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
for file,names in [('s10-1-author.py',['sample','svg','multi']),('s10-3-author.py',['polar'])]:
 source=(BASE/'exercise-checks'/file).read_text()
 for node in ast.parse(source).body:
  if isinstance(node,ast.FunctionDef) and node.name in names:exec(ast.get_source_segment(source,node).replace('s10-1-','s10-4-'))
def calc(n,eq,tk,te,lines,ans,k='',e='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if k:steps.append((k,e))
 add(n,M(eq)+' '+tk,M(eq)+' '+te,steps,M(ans),M(ans),'영점·교점과 각도 구간을 확인하고 적분 또는 도함수를 원래 식에서 검산했다.','Zeros, intersections, and angular intervals were checked, and integrals or derivatives verified against the original equations.',sub)
def area(n,eq,tk,te,expr,a,b,factor=1,detailk='',detaile=''):
 v=S.simplify(factor*S.integrate(expr,(t,a,b)))
 integral=rf'A={S.latex(S.sympify(factor))}\int_{{{S.latex(S.sympify(a))}}}^{{{S.latex(S.sympify(b))}}}{S.latex(expr)}\,dt'
 calc(n,eq,tk,te,[r'A=\frac12\int(r_{\rm outer}^2-r_{\rm inner}^2)\,d\theta',integral],rf'A={S.latex(v)}',detailk,detaile)
 return v
for n,eq,expr,a,b in [(1,r'r=\sqrt{2\theta},\quad0\le\theta\le\pi/2',t,0,S.pi/2),(2,r'r=e^\theta,\quad3\pi/4\le\theta\le3\pi/2',S.exp(2*t)/2,3*S.pi/4,3*S.pi/2),(4,r'r=1/\theta,\quad\pi/2\le\theta\le2\pi',1/(2*t*t),S.pi/2,2*S.pi)]:area(n,eq,'지정된 부채꼴 안의 넓이를 구하라.','Find the area in the specified sector.',expr,a,b)
calc(3,r'r=\sin\theta+\cos\theta,\quad0\le\theta\le\pi','지정된 부채꼴, 즉 위쪽 반평면에 놓인 원 내부의 넓이를 구하라.','Find the area inside the circle lying in the specified sector, namely the upper half-plane.',[r'(x-1/2)^2+(y-1/2)^2=1/2',r'r\ge0\ \text{on}\ 0\le\theta\le3\pi/4',r'A=\frac12\int_0^{3\pi/4}(\sin\theta+\cos\theta)^2\,d\theta'],r'A=3\pi/8+1/4','원문의 부채꼴 조건을 실제 점의 방향으로 해석했다. 남은 각도 구간은 반지름이 음수여서 아래 반평면을 그린다. 지정된 매개변수 구간 전체를 적분한 값인 이분의 파이는 원 전체의 넓이이며 요청된 위쪽 부분과 다르다.','The source sector condition is interpreted by the actual point direction. The remaining angular interval has negative radius and traces the lower half-plane. Integrating the entire stated parameter interval gives half pi, the full circle area, rather than the requested upper part.')
area(5,r'r^2=\sin2\theta','첫째사분면의 고리만 음영 처리되어 있다. 그 넓이를 구하라.','Only the first-quadrant loop is shaded; find its area.',S.sin(2*t)/2,0,S.pi/2)
area(6,r'r=2+\cos\theta','둘째사분면에 놓인 내부 부분의 넓이를 구하라.','Find the interior area lying in the second quadrant.',(2+S.cos(t))**2/2,S.pi/2,S.pi)
area(7,r'r=4+3\sin\theta','첫째사분면에 놓인 내부 부분의 넓이를 구하라.','Find the interior area lying in the first quadrant.',(4+3*S.sin(t))**2/2,0,S.pi/2)
area(8,r'r=\sqrt{\ln\theta},\quad1\le\theta\le2\pi','나선과 마지막 반지름으로 둘러싸인 음영 넓이를 구하라.','Find the shaded area enclosed by the spiral and its final radial segment.',S.log(t)/2,1,2*S.pi)
for n,eq,r,a,b in [(9,r'r=4\cos\theta',4*S.cos(t),-S.pi/2,S.pi/2),(10,r'r=2+2\cos\theta',2+2*S.cos(t),0,2*S.pi),(11,r'r=3-2\sin\theta',3-2*S.sin(t),0,2*S.pi),(12,r'r=2\sin3\theta',2*S.sin(3*t),0,S.pi),(13,r'r=2+\sin4\theta',2+S.sin(4*t),0,2*S.pi),(14,r'r=3-2\cos4\theta',3-2*S.cos(4*t),0,2*S.pi),(15,r'r=\sqrt{1+\cos^2(5\theta)}',S.sqrt(1+S.cos(5*t)**2),0,2*S.pi),(16,r'r=1+5\sin6\theta',1+5*S.sin(6*t),0,2*S.pi)]:
 area(n,eq,'곡선을 그리고 둘러싸인 전체 넓이를 구하라.','Sketch the curve and find its total enclosed area.',r*r/2,a,b,detailk='선택한 구간이 각 고리를 한 번씩 그린다. 음의 반지름은 반대 방향의 고리를 나타낸다.',detaile='The chosen interval traces each loop once; negative radii represent loops in the opposite direction.')
 svg(n,'Curve over the area interval',[('curve',polar(S.lambdify(t,r,'math'),float(a),float(b),5000))])
for n,eq,expr,a,b in [(17,r'r=4\cos3\theta',8*S.cos(3*t)**2,-S.pi/6,S.pi/6),(18,r'r^2=4\cos2\theta',2*S.cos(2*t),-S.pi/4,S.pi/4),(19,r'r=\sin4\theta',S.sin(4*t)**2/2,0,S.pi/4),(20,r'r=2\sin5\theta',2*S.sin(5*t)**2,0,S.pi/5),(21,r'r=1+2\sin\theta', (1+2*S.sin(t))**2/2,7*S.pi/6,11*S.pi/6),(22,r'r=2\cos\theta-\sec\theta',(2*S.cos(t)-1/S.cos(t))**2/2,-S.pi/4,S.pi/4)]:
 area(n,eq,'고리 하나의 넓이를 구하라.'+(' 안쪽 고리를 선택한다.' if n==21 else ''),'Find the area of one loop.'+(' Use the inner loop.' if n==21 else ''),expr,a,b,detailk='연속한 두 원점 통과 사이에서 해당 고리만 그려지는 구간을 사용한다.',detaile='Use an interval between consecutive pole crossings that traces exactly the desired loop.')
for n,eq,expr,a,b,mult in [(23,r'r=4\sin\theta,\quad r=2',((4*S.sin(t))**2-4)/2,S.pi/6,5*S.pi/6,1),(24,r'r=1-\sin\theta,\quad r=1',((1-S.sin(t))**2-1)/2,S.pi,2*S.pi,1),(25,r'r^2=8\cos2\theta,\quad r=2',(8*S.cos(2*t)-4)/2,-S.pi/6,S.pi/6,2),(26,r'r=1+\cos\theta,\quad r=2-\cos\theta',((1+S.cos(t))**2-(2-S.cos(t))**2)/2,-S.pi/3,S.pi/3,1),(27,r'r=3\cos\theta,\quad r=1+\cos\theta',((3*S.cos(t))**2-(1+S.cos(t))**2)/2,-S.pi/3,S.pi/3,1),(28,r'r=3\sin\theta,\quad r=2-\sin\theta',((3*S.sin(t))**2-(2-S.sin(t))**2)/2,S.pi/6,5*S.pi/6,1)]:
 area(n,eq,'첫 곡선의 안쪽이면서 둘째 곡선의 바깥인 넓이를 구하라.','Find the area inside the first curve and outside the second.',expr,a,b,mult,detailk='두 양의 반지름이 같아지는 각도를 경계로 삼고 바깥 반지름이 더 큰 구간만 적분한다.',detaile='Bound intervals by equality of the positive radii and integrate only where the first radius is larger.')
area(29,r'r=3\sin\theta,\quad r=3\cos\theta','두 곡선 내부의 공통 넓이를 구하라.','Find the common interior area.',9*S.sin(t)**2/2,0,S.pi/4,2)
area(30,r'r=1+\cos\theta,\quad r=1-\cos\theta','두 곡선 내부의 공통 넓이를 구하라.','Find the common interior area.',(1-S.cos(t))**2/2,0,S.pi/2,4)
area(31,r'r=\sin2\theta,\quad r=\cos2\theta','두 곡선 내부의 공통 넓이를 구하라.','Find the common interior area.',S.sin(2*t)**2/2,0,S.pi/8,16,detailk='기하학적 반지름은 각각 삼각함수의 절댓값이다. 여덟분의 파이 구간을 대칭 복제한다.',detaile='The geometric radii are the absolute trigonometric values; replicate a pi-over-eight sector by symmetry.')
area(32,r'r=3+2\cos\theta,\quad r=3+2\sin\theta','두 곡선 내부의 공통 넓이를 구하라.','Find the common interior area.',(3+2*S.cos(t))**2/2,S.pi/4,5*S.pi/4,2)
calc(33,r'r^2=2\sin2\theta,\quad r=1','두 곡선 내부의 공통 넓이를 구하라.','Find the common interior area.',[r'2\sin2\theta=1\Rightarrow\theta=\pi/12,5\pi/12\quad(0\le\theta\le\pi/2)',r'A=2\left[\int_0^{\pi/12}\sin2\theta\,d\theta+\frac12\int_{\pi/12}^{5\pi/12}1\,d\theta+\int_{5\pi/12}^{\pi/2}\sin2\theta\,d\theta\right]'],r'A=2-\sqrt3+\pi/3')
calc(34,r'r=a\sin\theta,\quad r=b\cos\theta,\quad a,b>0','두 곡선 내부의 공통 넓이를 구하라.','Find the common interior area.',[r'\alpha=\arctan(b/a),\quad0<\alpha<\pi/2',r'A=\frac12\int_0^\alpha a^2\sin^2\theta\,d\theta+\frac12\int_\alpha^{\pi/2}b^2\cos^2\theta\,d\theta',r'\sin2\alpha=2ab/(a^2+b^2)'],r'A=\frac14\left[a^2\alpha+b^2(\pi/2-\alpha)-ab\right],\quad\alpha=\arctan(b/a)')
calc(35,r'r=1/2+\cos\theta','큰 고리 내부에서 작은 고리 내부를 뺀 넓이를 구하라.','Find the area inside the larger loop but outside the smaller loop.',[r'r=0\Rightarrow\theta=2\pi/3,4\pi/3',r'A_{\rm small}=\frac12\int_{2\pi/3}^{4\pi/3}(1/2+\cos\theta)^2\,d\theta=\pi/4-3\sqrt3/8',r'A_{\rm large}+A_{\rm small}=3\pi/4,\quad A=A_{\rm large}-A_{\rm small}'],r'A=\pi/4+3\sqrt3/4')
calc(36,r'r=1+2\cos3\theta','큰 고리 하나와 그 안의 작은 고리 사이 넓이를 구하라.','Find the area between one large loop and its enclosed small loop.',[r'u=3\theta,\quad d\theta=du/3',r'A=\frac13\left[(3\pi)-(2)(\pi-3\sqrt3/2)\right]'],r'A=\pi/3+\sqrt3','한 큰 고리와 그 안의 작은 고리에 해당하는 반지름 제곱 적분을 각각 구해 뺀다. 세 개의 큰 고리 전체를 합하지 않는다.','Subtract the small-loop area from the corresponding large-loop area; do not sum all three large loops.')
for n,eq,lines,ans,k,e in [(37,r'r=\sin\theta,\quad r=1-\sin\theta',[r'\sin\theta=1-\sin\theta\Rightarrow\theta=\pi/6,5\pi/6',r'r=0\ \text{occurs on both curves at different angles}'],r'O,\quad(1/2,\pi/6),(1/2,5\pi/6)','답의 순서쌍은 극좌표이다. 원점은 반지름을 같게 놓는 계산에서 빠지므로 따로 넣는다.','Answer pairs are polar coordinates; the pole must be added separately.'),(38,r'r=1+\cos\theta,\quad r=1-\sin\theta',[r'\cos\theta=-\sin\theta\Rightarrow\theta=3\pi/4,7\pi/4'],r'O,\quad(1-\sqrt2/2,3\pi/4),(1+\sqrt2/2,7\pi/4)','원점도 두 곡선에 속한다.','The pole belongs to both curves.'),(39,r'r=2\sin2\theta,\quad r=1',[r'|2\sin2\theta|=1'],r'(1,\pi/12+k\pi/2),(1,5\pi/12+k\pi/2),\quad k=0,1,2,3','음의 반지름이 만드는 꽃잎도 포함해 여덟 점이다.','Including negative-radius petals gives eight points.'),(40,r'r=\cos\theta,\quad r=\sin2\theta',[r'\cos\theta=|\sin2\theta|,\quad\cos\theta>0\Rightarrow|\sin\theta|=1/2'],r'O,\quad(\sqrt3/2,\pi/6),(\sqrt3/2,11\pi/6)','반지름의 부호를 바꿔 표현되는 아래 교점도 포함한다.','Include the lower intersection represented by a negative radius.'),(41,r'r^2=2\cos2\theta,\quad r=1',[r'\cos2\theta=1/2'],r'(1,\pi/6),(1,5\pi/6),(1,7\pi/6),(1,11\pi/6)','단위원에는 원점이 없으므로 추가하지 않는다.','The unit circle does not contain the pole.'),(42,r'r^2=\sin2\theta,\quad r^2=\cos2\theta',[r'\sin2\theta=\cos2\theta\ge0\Rightarrow\theta=\pi/8,9\pi/8'],r'O,\quad(2^{-1/4},\pi/8),(2^{-1/4},9\pi/8)','두 렘니스케이트 모두 원점을 포함한다.','Both lemniscates contain the pole.')]:
 calc(n,eq,'서로 다른 교점을 모두 극좌표로 구하라.','Find all distinct intersections in polar coordinates.',lines,ans,k,e)
calc(43,r'r=3+2\cos\theta,\quad r=\sin2\theta','리마송 내부에서 장미곡선의 네 꽃잎 내부를 뺀 음영 넓이를 구하라.','Find the shaded area inside the limaçon excluding the interiors of all four rose petals.',[r'r_{\rm limacon}\ge1\ge|r_{\rm rose}|',r'A_{\rm limacon}=11\pi,\quad A_{\rm rose}=\pi/2'],r'A=21\pi/2')
calc(44,r'r^2=\sqrt3\sin2\theta,\quad r=\sqrt2\cos\theta','첫째사분면의 두 곡선 공통 내부에 음영이 있다. 넓이를 구하라.','The common interior in the first quadrant is shaded; find its area.',[r'\sqrt3\sin2\theta=2\cos^2\theta\Rightarrow\theta=\pi/6',r'A=\frac12\int_0^{\pi/6}\sqrt3\sin2\theta\,d\theta+\frac12\int_{\pi/6}^{\pi/2}2\cos^2\theta\,d\theta'],r'A=\pi/6')
calc(45,r'r=1+\cos\theta,\quad r=3\cos\theta','가로축 위에서 카디오이드 내부이면서 원 외부인 음영 넓이를 구하라.','Find the shaded area above the horizontal axis, inside the cardioid and outside the circle.',[r'1+\cos\theta=3\cos\theta\Rightarrow\theta=\pi/3',r'A=\frac12\int_{\pi/3}^{\pi/2}[(1+\cos\theta)^2-9\cos^2\theta]\,d\theta+\frac12\int_{\pi/2}^\pi(1+\cos\theta)^2\,d\theta'],r'A=\pi/8')
calc(46,r'r=1-2\sin\theta','큰 고리 내부에서 작은 고리를 뺀 음영 넓이를 구하라.','Find the shaded area inside the large loop but outside the small loop.',[r'A_{\rm small}=\frac12\int_{\pi/6}^{5\pi/6}(1-2\sin\theta)^2\,d\theta=\pi-3\sqrt3/2',r'A_{\rm large}+A_{\rm small}=3\pi'],r'A=\pi+3\sqrt3')
mp.mp.dps=40
alpha=mp.findroot(lambda x:2*x-1-mp.sin(x),.9);av=4*alpha**3/3+mp.quad(lambda x:(1+mp.sin(x))**2,[alpha,mp.pi/2])
calc(47,r'r=1+\sin\theta,\quad r=2\theta,\quad-\pi/2\le\theta\le\pi/2','그래프로 교점을 근사하고 두 내부의 공통 넓이를 추정하라.','Estimate intersections graphically and calculate the common interior area.',[r'\text{physical angle }\phi\in[0,\pi]:\quad R_{\rm spiral}=2\min(\phi,\pi-\phi)',rf'2\alpha=1+\sin\alpha,\quad\alpha\approx{float(alpha):.10f}',r'A=\int_0^\alpha4\theta^2\,d\theta+\int_\alpha^{\pi/2}(1+\sin\theta)^2\,d\theta'],rf'\theta_{{\rm spiral}}\approx\pm{float(alpha):.8f};\quad\phi_{{\rm cardioid}}\approx{float(alpha):.8f},\ {float(mp.pi-alpha):.8f};\quad A\approx{float(av):.8f}','두 교점의 물리적 각도는 위쪽 반평면에서 서로 보각이다. 원점도 양쪽 경계에 속하며, 음의 나선 반지름을 양의 반지름 각도로 옮겨 넓이를 계산했다.','The two nonzero intersections have supplementary physical angles in the upper half-plane. The pole also lies on both boundaries; negative spiral radii were converted to positive-radius directions before computing area.')
svg(47,'Cardioid and spiral loop',[('cardioid',polar(lambda t:1+math.sin(t))),('spiral loop',polar(lambda t:2*t,-math.pi/2,math.pi/2))])
beta=mp.asin((mp.sqrt(3)-1)/2);stage=mp.quad(lambda x:64*(1+mp.sin(x))**2-16/mp.sin(x)**2,[beta,mp.pi/2])
calc(48,r'r=8+8\sin\theta','마이크가 무대 앞 가장자리에서 사 미터 떨어져 있다. 마이크를 원점으로 두고 무대가 '+M(r'y\ge4')+'일 때 최적 수음 영역 안의 무대 넓이를 구하라.','A microphone is four meters in front of the stage edge. With the microphone at the pole and the stage given by '+M(r'y\ge4')+', find the stage area within the optimal pickup cardioid.',[r'8(1+\sin\theta)\sin\theta=4\Rightarrow\sin\alpha=(\sqrt3-1)/2',r'A=\frac12\int_\alpha^{\pi-\alpha}\left[64(1+\sin\theta)^2-16\csc^2\theta\right]d\theta'],rf'A=48\pi-96\alpha+128\cos\alpha+16\sin2\alpha-16\cot\alpha\approx{float(stage):.4f}\ \mathrm{{m}}^2,\quad\alpha=\arcsin((\sqrt3-1)/2)','무대의 아래 경계까지의 반지름을 빼야 한다. 카디오이드 전체 넓이는 무대 아래 관객 쪽도 포함한다.','Subtract the radial distance to the stage edge; the full cardioid area also includes audience-side space below the stage.')
svg(48,'Stage starts at y=4 m',[('pickup boundary',polar(lambda t:8+8*math.sin(t))),('stage edge',[(-12,4),(12,4)])])
calc(49,r'r=2\cos\theta,\quad0\le\theta\le\pi','정확한 곡선 길이를 구하라.','Find the exact curve length.',[r'\sqrt{r^2+(r\prime)^2}=2',r'L=\int_0^\pi2\,d\theta'],r'L=2\pi')
calc(50,r'r=e^{\theta/2},\quad0\le\theta\le\pi/2','정확한 곡선 길이를 구하라.','Find the exact curve length.',[r'\sqrt{r^2+(r\prime)^2}=\frac{\sqrt5}{2}e^{\theta/2}',r'L=\frac{\sqrt5}{2}\int_0^{\pi/2}e^{\theta/2}\,d\theta'],r'L=\sqrt5(e^{\pi/4}-1)')
calc(51,r'r=\theta^2,\quad0\le\theta\le2\pi','정확한 곡선 길이를 구하라.','Find the exact curve length.',[r'\sqrt{r^2+(r\prime)^2}=\theta\sqrt{\theta^2+4}',r'L=\frac13[(\theta^2+4)^{3/2}]_0^{2\pi}'],r'L=\frac83[(\pi^2+1)^{3/2}-1]')
calc(52,r'r=2(1+\cos\theta)','전체 곡선의 정확한 길이를 구하라.','Find the exact length of the complete curve.',[r'0\le\theta\le2\pi,\quad\sqrt{r^2+(r\prime)^2}=4|\cos(\theta/2)|',r'L=8\int_0^\pi\cos(\theta/2)\,d\theta'],r'L=16')
calc(53,r'r=3+3\sin\theta','원문 파란 부분은 왼쪽 아래 작은 호를 제외한 나머지이다. 그 정확한 길이를 구하라.','The blue source arc is the whole curve except the small lower-left arc; find its exact length.',[r'-\pi/2\le\theta\le\pi,\quad\sqrt{r^2+(r\prime)^2}=6\sin(\theta/2+\pi/4)',r'L=\int_{-\pi/2}^\pi6\sin(\theta/2+\pi/4)\,d\theta'],r'L=12+6\sqrt2')
svg(53,'Requested arc blue; excluded arc orange',[('requested',polar(lambda t:3+3*math.sin(t),-math.pi/2,math.pi)),('excluded',polar(lambda t:3+3*math.sin(t),math.pi,3*math.pi/2))])
calc(54,r'r=\theta+2','원문 파란 부분은 양의 가로축에서 시작해 한 바퀴 반을 돌아 음의 가로축에 도달한다. 그 길이를 구하라.','The blue arc starts on the positive horizontal axis and turns one and a half revolutions to the negative axis; find its length.',[r'0\le\theta\le3\pi,\quad L=\int_0^{3\pi}\sqrt{(\theta+2)^2+1}\,d\theta',r'F(u)=\frac12[u\sqrt{u^2+1}+\ln(u+\sqrt{u^2+1})]'],r'L=F(3\pi+2)-F(2),\quad F(u)=\frac12[u\sqrt{u^2+1}+\ln(u+\sqrt{u^2+1})]')
svg(54,'Requested one-and-a-half turns',[('requested',polar(lambda t:t+2,0,3*math.pi)),('continuation',polar(lambda t:t+2,3*math.pi,3.4*math.pi))])
calc(55,r'r=\cos^4(\theta/4)','전체 곡선을 그려 구간을 정하고 정확한 길이를 구하라.','Graph the whole curve, choose an interval, and find its exact length.',[r'0\le\theta\le4\pi,\quad r\prime=-\cos^3(\theta/4)\sin(\theta/4)',r'\sqrt{r^2+(r\prime)^2}=|\cos^3(\theta/4)|',r'L=4\int_0^\pi|\cos^3u|\,du'],r'L=16/3')
svg(55,'Full curve over four pi',[('curve',polar(lambda t:math.cos(t/4)**4,0,4*math.pi))])
calc(56,r'r=\cos^2(\theta/2)','전체 곡선을 그려 구간을 정하고 정확한 길이를 구하라.','Graph the whole curve, choose an interval, and find its exact length.',[r'r=(1+\cos\theta)/2,\quad0\le\theta\le2\pi',r'\sqrt{r^2+(r\prime)^2}=|\cos(\theta/2)|'],r'L=\int_0^{2\pi}|\cos(\theta/2)|\,d\theta=4')
svg(56,'Cardioid with scale one half',[('curve',polar(lambda t:math.cos(t/2)**2))])
calc(57,r'r=\cos(\theta/5)','원문 파란 부분은 바깥 고리를 제외한 안쪽 경로이다. 길이 적분만 세우고 계산하지 말라.','The blue source portion is the inner trace excluding the outer loop. Set up, but do not evaluate, its length integral.',[r'\text{blue interval}:\quad\pi\le\theta\le4\pi',r'r\prime=-\frac15\sin(\theta/5)'],r'L=\int_\pi^{4\pi}\sqrt{\cos^2(\theta/5)+\frac1{25}\sin^2(\theta/5)}\,d\theta')
svg(57,'Blue inner trace',[('requested',polar(lambda t:math.cos(t/5),math.pi,4*math.pi)),('outer arc part 1',polar(lambda t:math.cos(t/5),0,math.pi)),('outer arc part 2',polar(lambda t:math.cos(t/5),4*math.pi,5*math.pi))])
calc(58,r'r=\sin\theta/\theta','원문 파란 부분은 큰 호의 양의 세로축 교점부터 시작해 원점을 지나 다음 오른쪽 작은 고리를 완주한다. 길이 적분만 세워라.','The blue portion starts where the large arc meets the positive vertical axis, passes through the pole, and completes the next small right loop. Set up its length integral only.',[r'\pi/2\le\theta\le2\pi',r'r\prime=(\theta\cos\theta-\sin\theta)/\theta^2'],r'L=\int_{\pi/2}^{2\pi}\sqrt{\left(\frac{\sin\theta}{\theta}\right)^2+\left(\frac{\theta\cos\theta-\sin\theta}{\theta^2}\right)^2}\,d\theta')
svg(58,'Blue requested arc and small right loop',[('requested',polar(lambda t:math.sin(t)/t,math.pi/2,2*math.pi)),('earlier arc',polar(lambda t:1 if t==0 else math.sin(t)/t,0,math.pi/2)),('later loops',polar(lambda t:math.sin(t)/t,2*math.pi,5*math.pi))])
def quad(expr,a,b):
 f=S.lambdify(t,expr,'mpmath');aa=mp.mpf(str(S.N(a,40)));bb=mp.mpf(str(S.N(b,40)))
 v=mp.quad(f,[aa+(bb-aa)*i/80 for i in range(81)])
 with mp.workdps(55):w=mp.quad(f,[aa+(bb-aa)*i/160 for i in range(161)])
 assert abs(v-w)<mp.mpf('1e-15'),(v,w)
 return float(v)
for n,eq,r,a,b in [(59,r'r=\cos2\theta',S.cos(2*t),-S.pi/4,S.pi/4),(60,r'r=\tan\theta,\quad\pi/6\le\theta\le\pi/3',S.tan(t),S.pi/6,S.pi/3),(61,r'r=\sin(6\sin\theta)',S.sin(6*S.sin(t)),0,S.pi),(62,r'r=\sin(\theta/4)',S.sin(t/4),0,8*S.pi)]:
 expr=S.sqrt(r*r+S.diff(r,t)**2);v=quad(expr,a,b)
 calc(n,eq,'곡선 길이를 소수 넷째 자리까지 구하라.'+(' 고리 하나만 계산한다.' if n==59 else ''),'Find the curve length to four decimal places.'+(' Use only one loop.' if n==59 else ''),[rf'{S.latex(a)}\le\theta\le{S.latex(b)}',rf'L=\int_{{{S.latex(a)}}}^{{{S.latex(b)}}}{S.latex(expr.subs(t,S.Symbol(r'\theta')))}\,d\theta'],rf'L\approx{v:.4f}','정밀도와 분할을 늘린 수치 적분을 대조했다. 반복되는 궤적은 한 번만 센다.','Quadrature was repeated with greater precision and subdivision; repeated traces are counted once.')
 if n>=61:svg(n,'Complete trace for numerical arc length',[('curve',polar(S.lambdify(t,r,'math'),float(a),float(b),6000))])
for n,eq,r,a in [(63,r'r=2\cos\theta,\quad\theta=\pi/3',2*S.cos(t),S.pi/3),(64,r'r=2+\sin3\theta,\quad\theta=\pi/4',2+S.sin(3*t),S.pi/4),(65,r'r=1/\theta,\quad\theta=\pi',1/t,S.pi),(66,r'r=\sin\theta+2\cos\theta,\quad\theta=\pi/2',S.sin(t)+2*S.cos(t),S.pi/2),(67,r'r=\cos2\theta,\quad\theta=\pi/4',S.cos(2*t),S.pi/4),(68,r'r=1+2\cos\theta,\quad\theta=\pi/3',1+2*S.cos(t),S.pi/3)]:
 dx=S.diff(r*S.cos(t),t);dy=S.diff(r*S.sin(t),t);v=S.simplify(dy.subs(t,a)/dx.subs(t,a))
 calc(n,eq,'지정된 각도에서 접선 기울기를 구하라.','Find the tangent slope at the specified angle.',[r'\frac{dy}{dx}=\frac{r\prime\sin\theta+r\cos\theta}{r\prime\cos\theta-r\sin\theta}',rf'x\prime={S.latex(S.simplify(dx.subs(t,a)))},\quad y\prime={S.latex(S.simplify(dy.subs(t,a)))}'],rf'm={S.latex(v)}')
calc(69,r'r=\sin\theta','수평·수직 접점들을 직교좌표로 구하라.','Find the horizontal and vertical tangency points in Cartesian coordinates.',[r'x^2+(y-1/2)^2=1/4',r'x\prime=\cos2\theta,\quad y\prime=\sin2\theta'],r'\text{H}:\ (0,0),(0,1);\quad\text{V}:\ (1/2,1/2),(-1/2,1/2)')
calc(70,r'r=1-\sin\theta','수평·수직 접점들을 직교좌표로 구하라.','Find the horizontal and vertical tangency points in Cartesian coordinates.',[r'x\prime=(2\sin\theta+1)(\sin\theta-1),\quad y\prime=\cos\theta(1-2\sin\theta)',r'\theta=\pi/2:\quad x\prime=y\prime=0,\quad |dy/dx|\to\infty'],r'\text{H}:\ (0,-2),(\pm\sqrt3/4,1/4);\quad\text{V}:\ (0,0),(\pm3\sqrt3/4,-3/4)','원점 첨점의 수직 접선도 기울기의 극한으로 포함했다.','The cusp at the pole has a vertical tangent, obtained by a limiting slope.')
calc(71,r'r=1+\cos\theta','수평·수직 접점들을 직교좌표로 구하라.','Find the horizontal and vertical tangency points in Cartesian coordinates.',[r'x\prime=-\sin\theta(1+2\cos\theta),\quad y\prime=(2\cos\theta-1)(\cos\theta+1)',r'\theta=\pi:\quad x\prime=y\prime=0,\quad dy/dx\to0'],r'\text{H}:\ (0,0),(3/4,\pm3\sqrt3/4);\quad\text{V}:\ (2,0),(-1/4,\pm\sqrt3/4)','원점 첨점에는 수평 접선이 있다.','The cusp at the pole has a horizontal tangent.')
calc(72,r'r=e^\theta','수평·수직 접점들을 극좌표로 구하라.','Find the horizontal and vertical tangency points in polar coordinates.',[r'x\prime=e^\theta(\cos\theta-\sin\theta),\quad y\prime=e^\theta(\sin\theta+\cos\theta)'],r'\text{H}:\ (e^\theta,\theta),\ \theta=-\pi/4+k\pi;\quad\text{V}:\ (e^\theta,\theta),\ \theta=\pi/4+k\pi;\quad k\in\mathbb Z')
calc(73,r'r=f(\theta),\quad r\ne0','반지름선에서 접선으로 재는 방향 있는 각도의 탄젠트 공식을 증명하라.','Prove the tangent formula for the oriented angle from the radial line to the tangent.',[r'\mathbf v=r\prime\mathbf e_r+r\mathbf e_\theta',r'\tan\psi=\frac{\text{transverse component}}{\text{radial component}}'],r'\tan\psi=\frac r{dr/d\theta}','분모가 영이면 접선은 반지름선에 수직이다. 방향 없는 예각만 원하면 비의 절댓값을 쓴다.','If the denominator is zero, the tangent is perpendicular to the radius; use an absolute value if only the unoriented acute angle is wanted.')
calc(74,r'r=e^\theta','(a) 접선과 반지름선 사이 각도를 구하라. (b) 영과 이분의 파이에서 접선을 함께 그려라. (c) 이 각도가 일정한 정칙 극곡선의 형태를 증명하라.','(a) Find the angle between tangent and radius. (b) Graph tangents at zero and half pi. (c) Derive the form of regular polar curves with constant such angle.',[r'\text{(a)}\ \tan\psi=r/r\prime=1\Rightarrow\psi=\pi/4',r'\text{(b)}\ \theta=0:\ (x,y)=(1,0),\ m=1;\quad\theta=\pi/2:\ (x,y)=(0,e^{\pi/2}),\ m=-1',r'\text{(c)}\ r\prime/r=\cot\psi=k\Rightarrow\ln|r|=k\theta+C_0'],r'\text{(a)}\ \psi=\pi/4;\quad\text{(b)}\ y=x-1,\ y=-x+e^{\pi/2};\quad\text{(c)}\ r=Ce^{k\theta},\ k=\cot\psi','원점을 지나지 않는 정칙 구간에서 유도한다. 직각인 경우 상수 반지름 원이 되고, 반지름이 영이 아닌 극함수 그래프에서는 영 각도가 발생하지 않는다.','Work on a regular interval away from the pole; a right angle gives a constant-radius circle, while zero angle cannot occur on a nonzero regular polar-function graph.',sub='abc')
svg(74,'Equiangular spiral and two tangents',[('spiral',polar(math.exp,-1,2)),('tangent at 0',[(-1,-2),(4,3)]),('tangent at pi/2',[(-2,math.exp(math.pi/2)+2),(4,math.exp(math.pi/2)-4)])])
calc(75,r'r=f(\theta),\quad a\le\theta\le b,\quad0\le a<b\le\pi','(a) 극축 회전 곡면 넓이 공식을 유도하라. (b) '+M(r'r^2=\cos2\theta')+'의 전체 회전 곡면 넓이를 구하라.','(a) Derive the surface area formula for revolution about the polar axis. (b) Apply it to the full surface generated by '+M(r'r^2=\cos2\theta')+'.',[r'\text{(a)}\ y=r\sin\theta,\quad ds=\sqrt{r^2+(r\prime)^2}\,d\theta',r'\text{(b)}\ r=\sqrt{\cos2\theta},\quad\sqrt{r^2+(r\prime)^2}=1/\sqrt{\cos2\theta}',r'S=2\int_0^{\pi/4}2\pi\sin\theta\,d\theta'],r'\text{(a)}\ S=\int_a^b2\pi r\sin\theta\sqrt{r^2+(r\prime)^2}\,d\theta;\quad\text{(b)}\ S=2\pi(2-\sqrt2)','공식은 반지름이 음이 아니고 생성 곡면을 한 번만 세는 경우이다. 일반적으로 축까지 거리에 절댓값이 필요하다. 렘니스케이트의 위쪽 두 반고리를 회전하면 두 곡면을 각각 한 번 얻는다.','The displayed formula assumes nonnegative radius and a single count of the generated surface; in general use absolute distance to the axis. Rotating the two upper half-loops of the lemniscate produces its two surface pieces once each.',sub='ab')
calc(76,r'r=f(\theta),\quad a\le\theta\le b,\quad0\le a<b\le\pi','(a) 세로축 회전 곡면 넓이 공식을 구하라. (b) '+M(r'r^2=\cos2\theta')+'의 전체 회전 곡면 넓이를 구하라.','(a) Derive surface area for rotation about the vertical axis. (b) Find the full surface generated by '+M(r'r^2=\cos2\theta')+'.',[r'\text{(a)}\ \text{distance to axis}=|r\cos\theta|,\quad ds=\sqrt{r^2+(r\prime)^2}\,d\theta',r'\text{(b)}\ S=\int_{-\pi/4}^{\pi/4}2\pi\cos\theta\,d\theta'],r'\text{(a)}\ S=\int_a^b2\pi|r\cos\theta|\sqrt{r^2+(r\prime)^2}\,d\theta;\quad\text{(b)}\ S=2\sqrt2\pi','공식은 생성 곡면을 중복하지 않는 조각에 적용한다. 렘니스케이트의 오른쪽 고리만 회전하면 전체 곡면이 생기고 왼쪽 고리는 같은 곡면을 다시 만든다.','Apply the formula to pieces that do not duplicate surface area. Revolving the right lemniscate loop gives the whole surface; the left loop generates the same surface again.',sub='ab')
def shaded(n,title,curves,loops,bounds):
 svg(n,title,curves,bounds,False);p=BASE/f'exercise-content/assets/s10-4-{n}.svg';content=p.read_text();xl,xh,yl,yh=bounds;scale=500/max(xh-xl,yh-yl);mx=(xl+xh)/2;my=(yl+yh)/2
 paths=[]
 for pts in loops:paths.append('M'+'L'.join(f'{310+(x-mx)*scale:.3f},{310-(y-my)*scale:.3f}' for x,y in pts if math.isfinite(x) and math.isfinite(y))+'Z')
 fill=f'<path d="{"".join(paths)}" fill="#b8d8fa" fill-rule="evenodd" fill-opacity=".7"/>'
 at=content.index('<path');content=content[:at]+fill+content[at:];p.write_text(content)
 ex=next(e for e in items if e['number']==n);ex['figure']['caption']=bi('원래 함수에서 직접 계산한 경계와 음영 영역이다.','Boundaries and shaded regions computed directly from the original functions.')
shaded(3,'Specified upper-half-plane area',[('circle',polar(lambda t:math.sin(t)+math.cos(t),0,math.pi))],[[(0,0)]+polar(lambda t:math.sin(t)+math.cos(t),0,3*math.pi/4)],(-.4,1.4,-.4,1.4))
f=lambda t:math.sqrt(max(0,math.sin(2*t)))
shaded(5,'Only the upper-right loop',[('lemniscate',polar(f)),('opposite',polar(lambda t:-f(t)))],[[(0,0)]+polar(f,0,math.pi/2)],(-1.2,1.2,-1.2,1.2))
for n,f,a,b,bounds in [(6,lambda t:2+math.cos(t),math.pi/2,math.pi,(-1.6,3.4,-2.7,2.7)),(7,lambda t:4+3*math.sin(t),0,math.pi/2,(-5,5,-2,8)),(8,lambda t:math.sqrt(math.log(t)),1,2*math.pi,(-1.6,1.6,-1.6,1.6))]:
 curves=[('boundary',polar(f,1 if n==8 else 0,2*math.pi))]
 shaded(n,'Requested shaded region',curves,[[(0,0)]+polar(f,a,b)],bounds)
outer=polar(lambda t:3+2*math.cos(t));rose=polar(lambda t:abs(math.sin(2*t)))
shaded(43,'Limacon excluding four petals',[('limacon',outer),('rose',rose)],[outer,rose],(-2,5.5,-4.2,4.2))
lem=lambda t:math.sqrt(max(0,math.sqrt(3)*math.sin(2*t)));circle=lambda t:math.sqrt(2)*math.cos(t)
shaded(44,'Common first-quadrant region',[('lemniscate',polar(lem)),('circle',polar(circle))],[[(0,0)]+polar(lambda t:min(lem(t),circle(t)),0,math.pi/2)],(-1.5,1.7,-1.5,1.7))
outer=lambda t:1+math.cos(t);inner=lambda t:max(0,3*math.cos(t));outline=polar(outer,math.pi/3,math.pi)+polar(inner,math.pi,math.pi/3)
shaded(45,'Upper cardioid region outside circle',[('cardioid',polar(outer)),('circle',polar(lambda t:3*math.cos(t)))],[outline],(-.6,3.4,-1.8,1.8))
f=lambda t:1-2*math.sin(t);large=polar(f,5*math.pi/6,13*math.pi/6);small=polar(f,math.pi/6,5*math.pi/6)
shaded(46,'Large loop excluding the small loop',[('curve',polar(f))],[large,small],(-2.5,2.5,-3.4,.7))
items.sort(key=lambda e:e['number']);assert [e['number'] for e in items]==list(range(1,77))
raw={'section':'10.4','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[737,738,739,740],'pdfPages':[774,775,776,777]},'scope':{'kind':'exercise','numbers':list(range(1,77)),'total':76,'note':bi('일반 연습문제 전체. 지정 영역과 실제 추적 범위를 구분했다.','All ordinary exercises; specified physical regions are distinguished from parameter tracing intervals.')},'exercises':items}
import xml.etree.ElementTree as ET
for ex in items:
 for field in ['statement','answer']:
  assert re.findall(r'\\\((.*?)\\\)',ex[field]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[field]['en']),(ex['number'],field)
 if 'figure' in ex:ET.parse(BASE/'exercise-content'/ex['figure']['src'].replace('../exercise-content/',''))
def clean(x):
 if isinstance(x,str):assert not any(ord(c)<32 and c!='\n' for c in x),repr(x)
 elif isinstance(x,dict):
  for v in x.values():clean(v)
 elif isinstance(x,list):
  for v in x:clean(v)
clean(raw)
path=BASE/'exercise-content/s10-4.json';sys.path.insert(0,str(BASE));import build_exercises as build
build.validate_document(raw,path)
# Independent exact region integrals and surface symmetry checks.
assert S.simplify(S.integrate((S.sin(t)+S.cos(t))**2/2,(t,0,3*S.pi/4))-(3*S.pi/8+S.Rational(1,4)))==0
assert S.simplify(S.integrate(((1+S.cos(t))**2-9*S.cos(t)**2)/2,(t,S.pi/3,S.pi/2))+S.integrate((1+S.cos(t))**2/2,(t,S.pi/2,S.pi))-S.pi/8)==0
assert abs(2*alpha-1-mp.sin(alpha))<mp.mpf('1e-35')
assert abs(stage-(48*mp.pi-96*beta+128*mp.cos(beta)+16*mp.sin(2*beta)-16/mp.tan(beta)))<mp.mpf('1e-30')
path.write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('10.4:',len(items),'cards;',sum('figure' in e for e in items),'SVG; exact regions, numerical quadrature, bilingual math and XML checked')
