import json,math,html,sys,re
from pathlib import Path
import sympy as S
BASE=Path(__file__).resolve().parents[1];items=[];n=S.symbols('n',integer=True,positive=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(q,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=810 if q<=20 else 811 if q<=51 else 812
 items.append(dict(id=f'stewart9-exercise-11.5-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('교대급수와 절대수렴','Alternating series and absolute convergence'),statement=bi(sk,se),hint=bi('일반항과 부분합을 구별하고 등비급수·소거합·일반항의 영 수렴 조건을 살펴본다.','Distinguish terms from partial sums and examine geometric sums, telescoping, and the zero-term condition.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if k:steps.append((k,e))
 add(q,M(eq)+' '+tk,M(eq)+' '+te,steps,M(ans),M(ans),'초기항·정의역과 극한 논증의 조건을 확인했다.','Initial terms, domain, and conditions of the limit argument were checked.',sub)
def dots(q,sets,limit=None):
 pts=[(i,v) for label,values in sets for i,v in values];xmin=0;xmax=max(i for i,v in pts)+1;lo=min(v for i,v in pts);hi=max(v for i,v in pts)
 if limit is not None:lo=min(lo,limit);hi=max(hi,limit)
 pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad;X=lambda x:55+510*(x-xmin)/(xmax-xmin);Y=lambda y:300-250*(y-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 390"><rect width="620" height="390" fill="white"/><path d="M55 40V300H575" stroke="#8492a5" fill="none"/>',f'<text x="55" y="25" font-size="15">Sequence {q}: discrete terms</text>']
 for j,(label,values) in enumerate(sets):
  c=['#1463c2','#c64c38','#159568'][j%3]
  for i,v in values:out.append(f'<circle cx="{X(i):.3f}" cy="{Y(v):.3f}" r="3" fill="{c}"/>')
  out.append(f'<text x="55" y="{337+17*j}" fill="{c}" font-size="12">{html.escape(label)}</text>')
 if limit is not None:out.append(f'<path d="M55 {Y(limit)}H575" stroke="#65758d" stroke-dasharray="5 5"/><text x="570" y="{Y(limit)-5}" font-size="10">L={limit:.5g}</text>')
 for i in range(6):
  v=lo+(hi-lo)*i/5;out.append(f'<text x="5" y="{Y(v)+4}" font-size="10">{v:.4g}</text>')
 for i in [1,int(xmax/2),int(xmax)-1]:out.append(f'<text x="{X(i)}" y="318" font-size="11">{i}</text>')
 out.append('</svg>');p=BASE/f'exercise-content/assets/s11-5-{q}.svg';p.write_text(''.join(out));ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('정수 인덱스에 대응하는 수열의 점 그래프','Discrete sequence values at integer indices'),'caption':bi('자체 계산한 항을 점으로 표시했다. 선으로 연결하지 않았다.','Original computed terms shown as discrete points.')}
calc(1,r'\sum_{n=1}^\infty(-1)^{n-1}b_n,\quad b_n>0','(a) 교대급수의 뜻 (b) 수렴의 충분조건 (c) 조건이 성립할 때 나머지의 성질을 설명하라.','Explain (a) an alternating series, (b) sufficient conditions for convergence, and (c) the remainder under those conditions.',[r'\text{(a) successive signs alternate}',r'\text{(b)}\ b_{n+1}\le b_n,\quad b_n\to0',r'\text{(c)}\ |R_N|\le b_{N+1},\quad\operatorname{sgn}R_N=\operatorname{sgn}a_{N+1}\text{ unless }R_N=0'],r'\text{decreasing magnitudes tending to zero imply convergence and }|R_N|\le b_{N+1}',sub='abc')
rows=[(2,r'(-1)^{n-1}2/(2n+1)',1,[r'b_n=2/(2n+1)\downarrow0'],True),(3,r'(-1)^n2n/(n+4)',1,[r'b_n=2n/(n+4)\to2\ne0'],False),(4,r'(-1)^{n-1}/\ln(n+2)',1,[r'b_n=1/\ln(n+2)\downarrow0'],True),(5,r'(-1)^{n-1}/(3+5n)',1,[r'b_n=1/(3+5n)\downarrow0'],True),(6,r'(-1)^{n+1}/\sqrt{n+1}',0,[r'b_n=1/\sqrt{n+1}\downarrow0'],True),(7,r'(-1)^n(3n-1)/(2n+1)',1,[r'b_n\to3/2\ne0'],False),(8,r'(-1)^nn^2/(n^2+n+1)',1,[r'b_n\to1\ne0'],False),(9,r'(-1)^ne^{-n}',1,[r'b_n=e^{-n}\downarrow0'],True),(10,r'(-1)^n\sqrt n/(2n+3)',1,[r'b_n\to0',r'f^{\prime}(x)=(3-2x)/[2\sqrt x(2x+3)^2]<0\quad(x\ge2)'],True),(11,r'(-1)^{n+1}n^2/(n^3+4)',1,[r'b_n\to0',r'f^{\prime}(x)=x(8-x^3)/(x^3+4)^2\le0\quad(x\ge2)'],True),(12,r'(-1)^nn/2^n',1,[r'b_{n+1}/b_n=(n+1)/(2n)\le1',r'b_n\to0'],True),(13,r'(-1)^{n-1}e^{2/n}',1,[r'b_n\to1\ne0'],False),(14,r'(-1)^{n-1}\arctan n',1,[r'b_n\to\pi/2\ne0'],False),(15,r'\sin[(n+1/2)\pi]/(1+\sqrt n)',0,[r'\sin[(n+1/2)\pi]=(-1)^n',r'b_n=1/(1+\sqrt n)\downarrow0'],True),(16,r'n\cos(n\pi)/2^n',1,[r'\cos(n\pi)=(-1)^n',r'b_n=n/2^n\downarrow0\quad(n\ge1)'],True),(17,r'(-1)^n\sin(\pi/n)',1,[r'b_1=0,\quad b_n=\sin(\pi/n)\downarrow0\quad(n\ge2)'],True),(18,r'(-1)^n\cos(\pi/n)',1,[r'|a_n|\to1\ne0'],False),(19,r'(-1)^nn^2/5^n',1,[r'b_{n+1}/b_n=(1+1/n)^2/5\le4/5<1',r'b_n\to0'],True),(20,r'(-1)^n(\sqrt{n+1}-\sqrt n)',1,[r'b_n=1/(\sqrt{n+1}+\sqrt n)\downarrow0'],True)]
for q,term,start,lines,conv in rows:calc(q,rf'\sum_{{n={start}}}^\infty {term}','교대급수의 수렴·발산을 판정하라.','Determine convergence or divergence.',lines,r'\text{convergent}'if conv else r'\text{divergent}','감소 조건은 충분히 큰 인덱스부터 성립해도 된다. 항의 절댓값이 영으로 가지 않는 경우는 일반항 검사로 발산한다.','Eventual decrease suffices. If term magnitudes fail to tend to zero, the term test proves divergence.')
calc(21,r'\sum a_n','(a) 절대수렴 (b) 조건수렴을 정의하고 (c) 양의 항 급수가 수렴할 때 부호를 교대시킨 급수에 대해 설명하라.','Define (a) absolute and (b) conditional convergence, and (c) describe the alternating series formed from a convergent positive-term series.',[r'\text{(a)}\sum|a_n|<\infty',r'\text{(b)}\sum a_n\text{ converges but }\sum|a_n|\text{ diverges}',r'\text{(c)}\sum b_n<\infty\Rightarrow\sum|(-1)^nb_n|<\infty'],r'\text{(c) absolutely convergent}',sub='abc')
classify=[(22,r'(-1)^n/n^4',1,[r'\sum|a_n|=\sum n^{-4}\text{ converges}'],'absolutely convergent'),(23,r'(-1)^{n-1}/\sqrt[3]{n^2}',1,[r'b_n=n^{-2/3}\downarrow0',r'\sum b_n\text{ diverges }(p=2/3)'],'conditionally convergent'),(24,r'(-1)^{n+1}n^2/(n^2+1)',0,[r'|a_n|\to1\ne0'],'divergent'),(25,r'(-1)^n/(5n+1)',1,[r'b_n\downarrow0',r'\lim b_n/(1/n)=1/5'],'conditionally convergent'),(26,r'-n/(n^2+1)',1,[r'\lim|a_n|/(1/n)=1',r'\sum n/(n^2+1)=+\infty\Rightarrow\sum a_n=-\infty'],'divergent'),(27,r'(-1)^n/(n^2+1)',1,[r'|a_n|<1/n^2'],'absolutely convergent'),(28,r'\sin n/2^n',1,[r'|a_n|\le2^{-n}'],'absolutely convergent'),(29,r'(1+2\sin n)/n^3',1,[r'|a_n|\le3/n^3'],'absolutely convergent'),(30,r'(-1)^{n-1}n/(n^2+4)',1,[r'b_n\to0,\quad f^{\prime}(x)=(4-x^2)/(x^2+4)^2<0\quad(x>2)',r'\lim b_n/(1/n)=1'],'conditionally convergent'),(31,r'(-1)^n/\ln n',2,[r'b_n=1/\ln n\downarrow0',r'b_n>1/n'],'conditionally convergent'),(32,r'(-1)^nn/\sqrt{n^3+2}',1,[r'b_n\to0,\quad f^{\prime}(x)=(4-x^3)/[2(x^3+2)^{3/2}]<0\quad(x\ge2)',r'\lim b_n/(1/\sqrt n)=1'],'conditionally convergent'),(33,r'\cos(n\pi)/(3n+2)',1,[r'a_n=(-1)^n/(3n+2),\quad b_n\downarrow0',r'\lim b_n/(1/n)=1/3'],'conditionally convergent'),(34,r'(-1)^n/(n\ln n)',2,[r'b_n\downarrow0',r'\int_2^\infty dx/(x\ln x)=\infty'],'conditionally convergent')]
for q,term,start,lines,kind in classify:calc(q,rf'\sum_{{n={start}}}^\infty {term}','절대수렴·조건수렴·발산 중 하나로 분류하라.','Classify as absolutely convergent, conditionally convergent, or divergent.',lines,r'\text{'+kind+'}','조건수렴은 교대 판정으로 원급수 수렴을 보인 뒤 절댓값 급수의 발산을 따로 확인한다.','For conditional convergence, verify convergence by alternation and separately establish divergence of the absolute-value series.')
for q,eq,f,b,criterion in [(35,r'(-0.8)^n/n!',lambda j:(-.8)**j/math.factorial(j),lambda j:.8**j/math.factorial(j),r'b_{n+1}/b_n=0.8/(n+1)<1'),(36,r'(-1)^{n-1}n/8^n',lambda j:(-1)**(j-1)*j/8**j,lambda j:j/8**j,r'b_{n+1}/b_n=(n+1)/(8n)\le1/4')]:
 terms=[f(j)for j in range(1,21)];sums=[];sm=0
 for term in terms:sm+=term;sums.append(sm)
 N=1
 while True:
  sm=sum(f(j)for j in range(1,N+1));smnext=sm+f(N+1);lo,hi=sorted([sm,smnext])
  if hi-lo<.00005 and round(lo,4)==round(hi,4):break
  N+=1
 calc(q,rf'\sum_{{n=1}}^\infty {eq}','항과 부분합을 같은 그림에 그리고 합을 대략 읽은 뒤 교대 나머지로 소수 넷째 자리까지 구하라.','Plot terms and partial sums together, estimate the limit graphically, and certify the sum to four decimal places with the alternating remainder.',[criterion,r'b_n\to0',rf's_{{{N}}}={sm:.12f},\quad |R_{{{N}}}|\le b_{{{N+1}}}={b(N+1):.12f}',rf'{lo:.12f}\le S\le{hi:.12f}'],rf'S\approx{sm:.4f}')
 dots(q,[('terms',list(enumerate(terms,1))),('partial sums',list(enumerate(sums,1)))],sm)
for q,term,b,eps,criterion in [(37,r'(-1)^{n+1}/n^6',lambda j:j**-6,.00005,r'b_n=n^{-6}\downarrow0'),(38,r'(-1/3)^n/n',lambda j:3**(-j)/j,.0005,r'b_{n+1}/b_n=n/[3(n+1)]<1/3'),(39,r'(-1)^{n-1}/(n^22^n)',lambda j:1/(j*j*2**j),.0005,r'b_{n+1}/b_n=n^2/[2(n+1)^2]<1/2'),(40,r'(-1/n)^n',lambda j:j**(-j),.00005,r'\ln b_n=-n\ln n\downarrow-\infty')]:
 N=1
 while b(N+1)>=eps:N+=1
 calc(q,rf'\sum_{{n=1}}^\infty {term},\quad\varepsilon={eps}','수렴을 증명하고 교대 나머지 정리로 지정 오차를 보장하는 항 수를 구하라.','Prove convergence and find a term count guaranteeing the target error by the alternating remainder theorem.',[criterion,r'b_n\to0',rf'|R_N|\le b_{{N+1}},\quad b_{{{N+1}}}={b(N+1):.12f}<{eps}',rf'b_{{{N}}}={b(N):.12f}\ge{eps}'],rf'N={N}\text{{ terms suffice}}','인접한 경계값으로 이 정리의 상계를 만족하는 최소 항 수를 확인한다. 실제 오차의 최소 항 수와는 구별한다.','The neighboring bounds certify the smallest count satisfying this theorem’s bound, which need not be the minimum based on the actual error.')
for q,eq,f,b,criterion in [(41,r'(-1)^n/(2n)!',lambda j:(-1)**j/math.factorial(2*j),lambda j:1/math.factorial(2*j),r'b_{n+1}/b_n=1/[(2n+1)(2n+2)]<1'),(42,r'(-1)^{n+1}/n^6',lambda j:(-1)**(j+1)/j**6,lambda j:j**-6,r'b_n=n^{-6}\downarrow0'),(43,r'(-1)^nne^{-2n}',lambda j:(-1)**j*j*math.exp(-2*j),lambda j:j*math.exp(-2*j),r'b_{n+1}/b_n=(1+1/n)e^{-2}\le2e^{-2}<1'),(44,r'(-1)^{n-1}/(n4^n)',lambda j:(-1)**(j-1)/(j*4**j),lambda j:1/(j*4**j),r'b_{n+1}/b_n=n/[4(n+1)]<1/4')]:
 N=1
 while True:
  sm=sum(f(j)for j in range(1,N+1));lo,hi=sorted([sm,sm+f(N+1)])
  if hi-lo<.00005 and round(lo,4)==round(hi,4):break
  N+=1
 calc(q,rf'\sum_{{n=1}}^\infty {eq}','합을 소수 넷째 자리까지 근사하라.','Approximate the sum to four decimal places.',[criterion,r'b_n\to0',rf's_{{{N}}}={sm:.12f},\quad |R_{{{N}}}|\le b_{{{N+1}}}={b(N+1):.12f}',rf'{lo:.12f}\le S\le{hi:.12f}'],rf'S\approx{sm:.4f}','서로 이웃한 두 부분합이 주는 경계의 반올림이 일치한다.','The bounds from consecutive partial sums round to the same value.')
calc(45,r'\sum_{n=1}^\infty(-1)^{n-1}/n','오십 번째 부분합이 과대·과소 근사 중 어느 것인지 설명하라.','Explain whether the fiftieth partial sum overestimates or underestimates the sum.',[r'a_{51}=1/51>0',r'0<S-s_{50}\le1/51'],r's_{50}<S\quad\text{(underestimate)}')
calc(46,r'\sum_{n=1}^\infty(-1)^{n-1}/n^p','수렴하는 매개변수를 구하라.','Find all parameters giving convergence.',[r'p>0:\quad n^{-p}\downarrow0',r'p\le0:\quad|a_n|=n^{-p}\not\to0'],r'p>0;\quad\text{absolute for }p>1,\text{ conditional for }0<p\le1')
calc(47,r'\sum_{n=1}^\infty(-1)^n/(n+p)','수렴하는 실수 매개변수를 구하되 분모가 영인 경우를 처리하라.','Find real parameters giving convergence, accounting for zero denominators.',[r'p\in\{-1,-2,\ldots\}\Rightarrow\text{an undefined term occurs}',r'p\notin\{-1,-2,\ldots\}:\quad n+p>0\text{ eventually},\quad1/(n+p)\downarrow0',r'\lim[1/|n+p|]/(1/n)=1'],r'p\in\mathbb R\setminus\{-1,-2,\ldots\};\quad\text{conditionally convergent}')
calc(48,r'\sum_{n=2}^\infty(-1)^{n-1}(\ln n)^p/n','수렴하는 실수 매개변수를 구하라.','Find all real parameters giving convergence.',[r'(\ln n)^p/n\to0\quad\text{for every real }p',r'f^{\prime}(x)=(\ln x)^{p-1}(p-\ln x)/x^2<0\text{ eventually}',r'\int_2^\infty(\ln x)^p/x\,dx=\int_{\ln2}^\infty u^p\,du'],r'p\in\mathbb R;\quad\text{absolute if }p<-1,\text{ conditional if }p\ge-1')
calc(49,r'\sum_{n=1}^\infty(-1)^{n-1}b_n,\quad b_n=\begin{cases}1/n&n\text{ odd}\\ 1/n^2&n\text{ even}\end{cases}','발산을 증명하고 교대급수 판정법이 적용되지 않는 조건을 설명하라.','Prove divergence and identify the failed alternating-test condition.',[r's_{2N}=\sum_{k=1}^N1/(2k-1)-\sum_{k=1}^N1/(2k)^2',r'\sum1/(2k-1)=\infty,\quad\sum1/(2k)^2<\infty',r'b_{2k+1}=1/(2k+1)>1/(2k)^2=b_{2k}'],r's_N\to+\infty;\quad b_n\text{ is not eventually decreasing}','홀수 부분합은 바로 전 짝수 부분합보다 크므로 전체 부분합도 양의 무한대로 간다.','Each odd partial sum exceeds the preceding even one, so the full partial-sum sequence tends to positive infinity.')
calc(50,r'h_n=\sum_{k=1}^n1/k,\quad s_n=\sum_{k=1}^n(-1)^{k-1}/k','(a) 짝수 부분합의 항등식을 보이고 (b) 조화 부분합의 로그 차 극한으로 급수 합을 구하라.','(a) Establish an identity for even partial sums and (b) derive the series sum from the harmonic-minus-log limit.',[r'\text{(a)}\ s_{2n}=h_{2n}-2\sum_{k=1}^n1/(2k)=h_{2n}-h_n',r'\text{(b)}\ h_n-\ln n\to\gamma',r's_{2n}=[h_{2n}-\ln(2n)]-[h_n-\ln n]+\ln2\to\ln2',r's_{2n+1}-s_{2n}=1/(2n+1)\to0'],r'\sum_{n=1}^\infty(-1)^{n-1}/n=\ln2',sub='ab')
calc(51,r'a_n^+=(a_n+|a_n|)/2,\quad a_n^-=(a_n-|a_n|)/2','(a) 원급수가 절대수렴하면 양·음 부분 급수가 모두 수렴함을, (b) 조건수렴하면 두 부분 급수가 모두 발산함을 증명하라.','Prove that the positive- and negative-part series (a) both converge under absolute convergence and (b) both diverge under conditional convergence.',[r'P_N=\sum_{n=1}^Na_n^+,\quad M_N=\sum_{n=1}^Na_n^-,\quad s_N=P_N+M_N,\quad A_N=P_N-M_N',r'\text{(a)}\ P_N=(s_N+A_N)/2,\quad M_N=(s_N-A_N)/2\text{ have finite limits}',r'\text{(b)}\ s_N\to S,\quad A_N\to\infty\Rightarrow P_N\to\infty,\quad M_N\to-\infty'],r'\text{(a) both convergent; (b)}\sum a_n^+=+\infty,\quad\sum a_n^-=-\infty',sub='ab')
calc(52,r'\sum a_n\text{ conditionally convergent},\quad r\in\mathbb R','항을 재배열하여 합이 임의의 지정 실수가 되도록 만들 수 있음을 증명하라.','Prove that a rearrangement can have any prescribed real sum.',[r'\sum a_n^+=+\infty,\quad\sum a_n^-=-\infty,\quad a_n\to0'],r'\exists\text{ permutation }\sigma:\quad\sum_{n=1}^\infty a_{\sigma(n)}=r','사용하지 않은 양의 항을 원래 순서대로 더해 처음으로 목표를 넘고, 다음에는 음의 항을 원래 순서대로 더해 처음으로 목표 아래로 간다. 각 부호 부분합이 무한히 발산하므로 각 단계는 유한 번 안에 끝난다. 위·아래 초과량은 그 단계 마지막 항의 절댓값 이하라 영으로 간다. 한 묶음 안의 부분합은 앞뒤 교차값 사이에 있으므로 모든 부분합이 목표로 간다. 각 부호의 항을 순서대로 무한히 소비하므로 모든 비영 항이 결국 한 번씩 사용된다. 영인 항은 사이에 삽입한다.','Take unused positive terms in their original order until first crossing above the target, then unused negative terms until first crossing below it. Divergence of each signed subseries makes every stage finite. Each overshoot is bounded by the magnitude of the last term of its block, hence tends to zero. Intermediate sums lie between the adjacent crossing values, so all partial sums approach the target. Both ordered sign lists are consumed indefinitely, using every nonzero term once; insert zero terms between blocks.')
calc(53,r'\sum a_n\text{ conditionally convergent}','(a) 항에 인덱스 제곱을 곱한 급수의 발산을 증명하라. (b) 인덱스만 곱한 급수는 수렴하는 예와 발산하는 예를 각각 제시하라.','(a) Prove divergence after multiplying terms by the squared index. (b) Give examples where multiplying by the index produces convergence and divergence.',[r'\text{(a)}\sum n^2a_n\text{ converges}\Rightarrow n^2a_n\to0\Rightarrow|a_n|\le1/n^2\text{ eventually}',r'\sum|a_n|<\infty\quad\text{contradiction}',r'\text{(b)(convergent)}\ a_1=0,\quad a_n=(-1)^n/(n\ln n)\ (n\ge2)',r'\sum a_n\text{ conditional};\quad\sum na_n=\sum_{n=2}^\infty(-1)^n/\ln n\text{ converges}',r'\text{(b)(divergent)}\ a_n=(-1)^{n-1}/n,\quad na_n=(-1)^{n-1}\not\to0'],r'\text{(a) divergent; (b) either behavior is possible}',sub='ab')
items.sort(key=lambda e:e['number']);assert [e['number']for e in items]==list(range(1,54))
raw={'section':'11.5','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[810,811,812],'pdfPages':[847,848,849]},'scope':{'kind':'exercise','numbers':list(range(1,54)),'total':53,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s11-5.json')
for ex in items:
 for key in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[key]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[key]['en']),(ex['number'],key)
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
for b,eps in [(lambda j:j**-6,.00005),(lambda j:3**(-j)/j,.0005),(lambda j:1/(j*j*2**j),.0005),(lambda j:j**(-j),.00005)]:assert b(6)<eps<=b(5)
(BASE/'exercise-content/s11-5.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('11.5: 53 cards, 2 SVG; source, schema, bilingual formulas, alternating remainder brackets and threshold checks passed')
