import json,math,html,sys,re
from pathlib import Path
import sympy as S
BASE=Path(__file__).resolve().parents[1];items=[];n=S.symbols('n',integer=True,positive=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(q,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=796 if q<=16 else 797 if q<=46 else 798
 items.append(dict(id=f'stewart9-exercise-11.3-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('적분 판정법과 오차','Integral test and errors'),statement=bi(sk,se),hint=bi('일반항과 부분합을 구별하고 등비급수·소거합·일반항의 영 수렴 조건을 살펴본다.','Distinguish terms from partial sums and examine geometric sums, telescoping, and the zero-term condition.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if k:steps.append((k,e))
 add(q,M(eq)+' '+tk,M(eq)+' '+te,steps,M(ans),M(ans),'초기항·정의역과 극한 논증의 조건을 확인했다.','Initial terms, domain, and conditions of the limit argument were checked.',sub)
def dots(q,sets,limit=None):
 pts=[(i,v) for label,values in sets for i,v in values];xmin=0;xmax=max(i for i,v in pts)+1;lo=min(v for i,v in pts);hi=max(v for i,v in pts)
 if limit is not None:lo=min(lo,limit);hi=max(hi,limit)
 pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad;X=lambda x:55+510*(x-xmin)/(xmax-xmin);Y=lambda y:300-250*(y-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 390"><rect width="620" height="390" fill="white"/><path d="M55 40V300H575" stroke="#8492a5" fill="none"/>',f'<text x="55" y="25" font-size="15">Sequence {q}: discrete terms</text>']
 for j,(label,values) in enumerate(sets):
  c=['#1463c2','#c64c38','#159568'][j%3]
  for i,v in values:out.append(f'<circle cx="{X(i):.3f}" cy="{Y(v):.3f}" r="3" fill="{c}"/>')
  out.append(f'<text x="55" y="{337+17*j}" fill="{c}" font-size="12">{html.escape(label)}</text>')
 if limit is not None:out.append(f'<path d="M55 {Y(limit)}H575" stroke="#65758d" stroke-dasharray="5 5"/><text x="570" y="{Y(limit)-5}" font-size="10">L={limit:.5g}</text>')
 for i in range(6):
  v=lo+(hi-lo)*i/5;out.append(f'<text x="5" y="{Y(v)+4}" font-size="10">{v:.4g}</text>')
 for i in [1,int(xmax/2),int(xmax)-1]:out.append(f'<text x="{X(i)}" y="318" font-size="11">{i}</text>')
 out.append('</svg>');p=BASE/f'exercise-content/assets/s11-3-{q}.svg';p.write_text(''.join(out));ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('정수 인덱스에 대응하는 수열의 점 그래프','Discrete sequence values at integer indices'),'caption':bi('자체 계산한 항을 점으로 표시했다. 선으로 연결하지 않았다.','Original computed terms shown as discrete points.')}
x=S.symbols('x',positive=True)
calc(1,r'\sum_{n=2}^\infty n^{-3/2}<\int_1^\infty x^{-3/2}\,dx','직사각형 그림으로 부등식과 급수에 대한 결론을 설명하라.','Use rectangles to illustrate the inequality and conclude something about the series.',[r'\int_{n-1}^n x^{-3/2}\,dx>n^{-3/2}',r'\int_1^\infty x^{-3/2}\,dx=[-2x^{-1/2}]_1^\infty=2'],r'\sum_{n=2}^\infty n^{-3/2}\text{ converges and is less than }2','양의 부분합이 적분값으로 위에서 유계이다. 첫 직사각형에서 생긴 양의 넓이 차가 엄격한 부등식을 유지한다.','Positive partial sums are bounded by the integral; the positive first-rectangle gap preserves strictness.')
calc(2,r'f>0\text{ continuous and decreasing on }[1,\infty),\quad a_i=f(i)','그림을 이용하여 적분과 좌·우 끝점 합을 작은 순서로 정렬하라.','Use a diagram to order the integral and left- and right-endpoint sums.',[r'f(i+1)\le f(x)\le f(i)\quad(i\le x\le i+1)',r'\sum_{i=1}^5 f(i+1)\le\int_1^6 f(x)\,dx\le\sum_{i=1}^5f(i)'],r'\sum_{i=2}^6a_i\le\int_1^6f(x)\,dx\le\sum_{i=1}^5a_i','엄격히 감소하면 양쪽 부등식도 엄격하다. 도해는 감소함수의 한 예를 나타낸다.','Both inequalities are strict for a strictly decreasing function. The illustration uses a representative decreasing function.')
integ=[(3,x**-3,1,r'-1/(2x^2)',r'1/2',True,r'f\text{ positive, continuous, decreasing for }x\ge1'),(4,x**(-S.Rational(3,10)),1,r'x^{0.7}/0.7',r'+\infty',False,r'f\text{ positive, continuous, decreasing for }x\ge1'),(5,2/(5*x-1),1,r'(2/5)\ln(5x-1)',r'+\infty',False,r'f\text{ positive, continuous, decreasing for }x\ge1'),(6,(3*x-1)**-4,1,r'-1/[9(3x-1)^3]',r'1/72',True,r'f\text{ positive, continuous, decreasing for }x\ge1'),(7,x*x/(x**3+1),2,r'\ln(x^3+1)/3',r'+\infty',False,r'f^{\prime}(x)=x(2-x^3)/(x^3+1)^2<0\quad(x\ge2)'),(8,x*x*S.exp(-x**3),1,r'-e^{-x^3}/3',r'1/(3e)',True,r'f^{\prime}(x)=xe^{-x^3}(2-3x^3)<0\quad(x\ge1)'),(9,1/(x*S.log(x)**3),2,r'-1/[2(\ln x)^2]',r'1/[2(\ln2)^2]',True,r'f\text{ positive, continuous, decreasing for }x\ge2'),(10,S.atan(x)/(1+x*x),1,r'(\arctan x)^2/2',r'3\pi^2/32',True,r'f^{\prime}(x)=[1-2x\arctan x]/(1+x^2)^2<0\quad(x\ge1)')]
for q,expr,start,F,I,conv,condition in integ:
 calc(q,rf'\sum_{{n={start}}}^\infty {S.latex(expr.subs(x,n))}','적분 판정법으로 수렴·발산을 결정하라.','Apply the Integral Test to determine convergence or divergence.',[condition,rf'\int f(x)\,dx={F}',rf'\int_{{{start}}}^\infty f(x)\,dx={I}'],r'\text{convergent}'if conv else r'\text{divergent}','표시한 구간에서 함수가 양수·연속이고 감소하므로 적분 판정법의 조건을 만족한다.','The function is positive, continuous and decreasing on the stated interval, satisfying the Integral Test.')
judgments=[(11,r'1/n^{\sqrt2}',1,[r'p=\sqrt2>1'],True),(12,r'n^{-0.9999}',3,[r'p=0.9999<1'],False),(13,r'1/n^3',1,[r'p=3>1'],True),(14,r'1/(2n+3)',1,[r'\int_1^t dx/(2x+3)=\tfrac12\ln[(2t+3)/5]\to\infty'],False),(15,r'1/(4n-1)',1,[r'\int_1^t dx/(4x-1)=\tfrac14\ln[(4t-1)/3]\to\infty'],False),(16,r'1/(n\sqrt n)',1,[r'p=3/2>1'],True),(17,r'(\sqrt n+4)/n^2',1,[r'a_n=n^{-3/2}+4n^{-2};\quad p=3/2,2>1'],True),(18,r'\sqrt n/(1+n^{3/2})',1,[r'f^{\prime}(x)=[1-2x^{3/2}]/[2\sqrt x(1+x^{3/2})^2]<0\quad(x\ge1)',r'\int_1^t\frac{\sqrt x}{1+x^{3/2}}\,dx=\tfrac23\ln[(1+t^{3/2})/2]\to\infty'],False),(19,r'1/(n^2+4)',1,[r'\int_1^\infty dx/(x^2+4)=\pi/4-\tfrac12\arctan(1/2)<\infty'],True),(20,r'1/(n^2+2n+2)',1,[r'\int_1^\infty dx/[(x+1)^2+1]=\pi/2-\arctan2<\infty'],True),(21,r'n^3/(n^4+4)',1,[r'f^{\prime}(x)=x^2(12-x^4)/(x^4+4)^2<0\quad(x\ge2)',r'\int_2^t\frac{x^3}{x^4+4}\,dx=\tfrac14\ln[(t^4+4)/20]\to\infty'],False),(22,r'(3n-4)/(n^2-2n)',3,[r'\frac{3x-4}{x(x-2)}=2/x+1/(x-2)',r'\int_3^t f(x)\,dx=2\ln(t/3)+\ln(t-2)\to\infty'],False),(23,r'1/(n\ln n)',2,[r'\int_2^t dx/(x\ln x)=\ln\ln t-\ln\ln2\to\infty'],False),(24,r'\ln n/n^2',2,[r'f^{\prime}(x)=(1-2\ln x)/x^3<0\quad(x\ge2)',r'\int_2^\infty\ln x/x^2\,dx=(\ln2+1)/2<\infty'],True),(25,r'ne^{-n}',1,[r'f^{\prime}(x)=(1-x)e^{-x}\le0\quad(x\ge1)',r'\int_1^\infty xe^{-x}\,dx=2/e'],True),(26,r'ne^{-n^2}',1,[r'f^{\prime}(x)=(1-2x^2)e^{-x^2}<0\quad(x\ge1)',r'\int_1^\infty xe^{-x^2}\,dx=1/(2e)'],True),(27,r'1/(n^2+n^3)',1,[r'0<a_n\le1/n^3,\quad p=3>1'],True),(28,r'n/(n^4+1)',1,[r'f^{\prime}(x)=(1-3x^4)/(x^4+1)^2<0\quad(x\ge1)',r'\int_1^\infty x/(x^4+1)\,dx=\pi/8'],True)]
for q,term,start,lines,conv in judgments:calc(q,rf'\sum_{{n={start}}}^\infty {term}','수렴·발산을 판정하라.','Determine convergence or divergence.',lines,r'\text{convergent}'if conv else r'\text{divergent}','적분을 쓴 경우 양수·연속·최종 감소 조건을 확인하며, 유한한 초기 항은 판정에 영향을 주지 않는다.','Integral arguments use positivity, continuity and eventual decrease; finitely many initial terms do not affect convergence.')
calc(29,r'\sum_{n=1}^\infty\cos(\pi n)/\sqrt n','주어진 항의 실수 함수에 적분 판정법을 적용할 수 없는 이유를 설명하라.','Explain why the corresponding real function does not meet the Integral Test conditions.',[r'\cos(\pi n)=(-1)^n',r'f(x)=\cos(\pi x)/\sqrt x\text{ changes sign infinitely often}'],r'\text{positivity and monotone decrease fail}')
calc(30,r'\sum_{n=1}^\infty\cos^2n/(1+n^2)','주어진 항의 실수 함수에 적분 판정법을 적용할 수 없는 이유를 설명하라.','Explain why the corresponding real function does not meet the Integral Test conditions.',[r'f(\pi/2+k\pi)=0,\quad f(\pi+k\pi)>0',r'\text{such increases occur arbitrarily far out}'],r'\text{the function is not eventually decreasing}','적분 판정법이 실패한다는 사실 자체는 급수의 발산을 뜻하지 않는다.','Failure of the Integral Test conditions does not itself imply divergence.')
calc(31,r'\sum_{n=2}^\infty1/[n(\ln n)^p]','수렴하는 매개변수를 모두 구하라.','Find all parameter values giving convergence.',[r'u=\ln x:\quad\int_2^\infty\frac{dx}{x(\ln x)^p}=\int_{\ln2}^\infty u^{-p}\,du',r'f^{\prime}(x)=-[\ln x+p]/[x^2(\ln x)^{p+1}]<0\text{ eventually}'],r'p>1')
calc(32,r'\sum_{n=3}^\infty1/[n\ln n(\ln\ln n)^p]','수렴하는 매개변수를 모두 구하라.','Find all parameter values giving convergence.',[r'u=\ln\ln x:\quad\int_3^\infty\frac{dx}{x\ln x(\ln\ln x)^p}=\int_{\ln\ln3}^\infty u^{-p}\,du',r'(\ln f)^{\prime}=-\frac1x-\frac1{x\ln x}-\frac p{x\ln x\ln\ln x}<0\text{ eventually}'],r'p>1')
calc(33,r'\sum_{n=1}^\infty n(1+n^2)^p','수렴하는 매개변수를 모두 구하라.','Find all parameter values giving convergence.',[r'u=1+x^2:\quad\int_1^\infty x(1+x^2)^p\,dx=\tfrac12\int_2^\infty u^p\,du',r'p<-1\Rightarrow f^{\prime}(x)=(1+x^2)^{p-1}[1+(1+2p)x^2]<0\quad(x\ge1)',r'p\ge-1\Rightarrow n(1+n^2)^p\ge n/(1+n^2)\ge1/(2n)'],r'p<-1')
calc(34,r'\sum_{n=1}^\infty\ln n/n^p','수렴하는 매개변수를 모두 구하라.','Find all parameter values giving convergence.',[r'p>1:\quad\int_1^\infty\frac{\ln x}{x^p}\,dx=1/(p-1)^2',r'f^{\prime}(x)=x^{-p-1}(1-p\ln x)<0\text{ eventually}',r'p\le1,\ n\ge3:\quad\ln n/n^p\ge1/n'],r'p>1')
calc(35,r'\zeta(x)=\sum_{n=1}^\infty n^{-x}','주어진 급수 정의가 성립하는 실수 입력을 구하라.','Find the real inputs where the displayed series definition converges.',[r'\sum n^{-p}\text{ converges iff }p>1'],r'x>1','이 문제는 급수로 주어진 정의역을 묻는다.','This asks for the domain of the displayed series definition.')
calc(36,r'\zeta(2)=\pi^2/6','(a) 둘째 항부터의 역제곱합 (b) 인덱스 삼부터 다음 정수의 역제곱합 (c) 양의 짝수들의 역제곱합을 구하라.','Find (a) the inverse-square sum from the second term, (b) the sum of inverse squares of the next integer starting at index three, and (c) the inverse-square sum of positive even integers.',[r'\text{(a)}\sum_{n=2}^\infty n^{-2}=\zeta(2)-1',r'\text{(b)}\sum_{n=3}^\infty(n+1)^{-2}=\zeta(2)-1-1/4-1/9',r'\text{(c)}\sum_{n=1}^\infty(2n)^{-2}=\zeta(2)/4'],r'\text{(a)}\pi^2/6-1;\quad\text{(b)}\pi^2/6-49/36;\quad\text{(c)}\pi^2/24',sub='abc')
calc(37,r'\zeta(4)=\pi^4/90','(a) 삼을 양의 정수로 나눈 값들의 네제곱합 (b) 인덱스 오부터 인덱스 빼기 이의 역네제곱합을 구하라.','Find (a) the sum of fourth powers of three divided by positive integers and (b) inverse fourth powers of index minus two starting at index five.',[r'\text{(a)}\sum_{n=1}^\infty(3/n)^4=81\zeta(4)',r'\text{(b)}\sum_{k=5}^\infty(k-2)^{-4}=\zeta(4)-1-1/16'],r'\text{(a)}\ 9\pi^4/10;\quad\text{(b)}\pi^4/90-17/16',sub='ab')
for q,p,eps,cut,den in [(38,4,1e-5,33,90),(39,2,.001,1001,6)]:
 sm=sum(j**(-p)for j in range(1,11));lo=sm+11**(1-p)/(p-1);hi=sm+10**(1-p)/(p-1);mid=(lo+hi)/2;exact=math.pi**p/den
 calc(q,rf'\sum_{{n=1}}^\infty1/n^{p},\quad\varepsilon={eps}','(a) 열 부분합과 오차 상계 (b) 양쪽 적분 경계로 개선한 근사 (c) 정확한 합과 비교 (d) 지정 오차를 보장하는 항 수를 구하라.','Find (a) the ten-term sum and error bound, (b) an improved estimate using both integral bounds, (c) comparison with the exact sum, and (d) a term count guaranteeing the specified error.',[rf'\text{{(a)}}\ s_{{10}}={sm:.12f},\quad R_{{10}}<1/[{p-1}\cdot10^{{{p-1}}}]',rf'\text{{(b)}}\ s_N+1/[{p-1}(N+1)^{{{p-1}}}]<S<s_N+1/[{p-1}N^{{{p-1}}}]',rf'{lo:.12f}<S<{hi:.12f},\quad S\approx{mid:.12f}\quad(|\text{{error}}|<{(hi-lo)/2:.12f})',rf'\text{{(c)}}\ S=\pi^{p}/{den}={exact:.12f},\quad |\text{{midpoint error}}|={abs(mid-exact):.12f}',rf'\text{{(d)}}\ R_N<1/[{p-1}N^{{{p-1}}}]<{eps}\quad(N={cut})'],rf's_{{10}}={sm:.12f};\quad S\approx{mid:.12f};\quad N={cut}\text{{ suffices for error }}{eps}',sub='abcd')
for q,expr,fun,start,N,tail,places in [(40,r'ne^{-2n}',lambda j:j*math.exp(-2*j),1,8,lambda j:math.exp(-2*j)*(j/2+1/4),4),(41,r'(2n+1)^{-6}',lambda j:(2*j+1)**-6,1,10,lambda j:1/(10*(2*j+1)**5),5)]:
 sm=sum(fun(j)for j in range(start,N+1));upper=sm+tail(N);assert round(sm,places)==round(upper,places)
 calc(q,rf'\sum_{{n=1}}^\infty {expr},\quad d={places}','지정한 소수 자리수까지 합을 구하고 나머지 적분으로 반올림을 보장하라.','Find the sum to the specified number of decimal places and certify its rounding with an integral tail bound.',[rf's_{{{N}}}={sm:.12f},\quad0<R_{{{N}}}<{tail(N):.12f}',rf'{sm:.12f}<S<{upper:.12f}'],rf'S\approx{sm:.{places}f}','구간 양 끝이 같은 요청 자리 값으로 반올림된다.','Both interval endpoints round to the same requested value.')
calc(42,r'\sum_{n=2}^\infty1/[n(\ln n)^2],\quad\varepsilon=0.01','오차를 보장하려면 몇 항을 더하면 되는지 구하라.','Find a term count guaranteeing the required accuracy.',[r'R_N<\int_N^\infty dx/[x(\ln x)^2]=1/\ln N',r'N>e^{100}\Rightarrow R_N<0.01',r'N=\lfloor e^{100}\rfloor+1,\quad\text{number of terms}=N-1'],r'\lfloor e^{100}\rfloor\text{ terms suffice }(\approx2.6881\times10^{43})','합이 인덱스 이에서 시작하므로 마지막 인덱스와 항의 개수는 하나 차이 난다. 이 값은 적분 상계로 보장한 충분한 개수이다.','Because the sum starts at index two, the term count is one less than the last index. This is a sufficient count certified by the integral bound.')
calc(43,r'\sum_{n=1}^\infty n^{-1.001},\quad\varepsilon=5\times10^{-9}','지정한 오차를 얻으려면 엄청나게 많은 항이 필요함을 적분 하계로 보여라.','Use the integral lower bound to show how many terms are necessarily required for the target error.',[r'R_N>\int_{N+1}^\infty x^{-1.001}\,dx=1000/(N+1)^{0.001}',r'R_N<5\times10^{-9}\Rightarrow N+1>(2\times10^{11})^{1000}',r'\log_{10}[(2\times10^{11})^{1000}]=11301.029995\ldots'],r'N>10^{11301}','충분조건만으로 필요 항 수를 주장하지 않고 나머지의 하계를 사용했다.','The necessary count follows from a lower bound on the remainder, not merely a sufficient upper-bound criterion.')
B=lambda j:(math.log(j)**2+2*math.log(j)+2)/j
cut=3
while B(cut)>=.05:cut+=1
sm=sum(math.log(j)**2/j**2 for j in range(1,cut+1))
calc(44,r'\sum_{n=1}^\infty(\ln n)^2/n^2,\quad\varepsilon=0.05','(a) 수렴 (b) 나머지 상계 (c) 상계가 지정 오차보다 작은 최소 인덱스 (d) 그 부분합을 구하라.','Find (a) convergence, (b) a remainder upper bound, (c) the smallest index making the bound less than five hundredths, and (d) that partial sum.',[r'f^{\prime}(x)=2\ln x(1-\ln x)/x^3<0\quad(x>e)',r'\int_N^\infty(\ln x)^2/x^2\,dx=[(\ln N)^2+2\ln N+2]/N=B(N)',rf'B(1372)={B(1372):.12f}>0.05,\quad B(1373)={B(1373):.12f}<0.05',rf's_{{1373}}={sm:.12f}'],rf'\text{{(a) convergent; (b)}}\ R_N<B(N)\ (N\ge3);\quad\text{{(c)}}\ N=1373;\quad\text{{(d)}}\ s_{{1373}}\approx{sm:.12f}','상계는 인덱스 삼부터 엄격히 감소하므로 인접한 두 값으로 최소성을 검증한다.','The bound strictly decreases from index three, so the two neighboring values certify minimality.',sub='abcd')
calc(45,r'H_n=\sum_{k=1}^n1/k','(a) 적분으로 로그 상계를 구하고 (b) 백만 항과 십억 항의 합이 각각 십오와 이십이보다 작음을 보여라.','(a) Derive a logarithmic integral bound and (b) show that the first million and billion terms sum to less than fifteen and twenty-two.',[r'\sum_{k=2}^n1/k\le\int_1^n dx/x=\ln n',r'H_n\le1+\ln n',rf'1+\ln10^6={1+math.log(1e6):.9f}<15',rf'1+\ln10^9={1+math.log(1e9):.9f}<22'],r'\text{(a)}\ H_n\le1+\ln n;\quad\text{(b)}\ H_{10^6}<15,\ H_{10^9}<22',sub='ab')
calc(46,r't_n=H_n-\ln n','(a) 넓이 비교로 양수임을 (b) 두 넓이의 차로 감소함을 (c) 극한 존재를 증명하라.','Prove (a) positivity by areas, (b) decrease by a difference of areas, and (c) existence of the limit.',[r'\text{(a)}\ln n=\int_1^n dx/x\le H_{n-1}<H_n\Rightarrow t_n>0',r'\text{(b)}\ t_n-t_{n+1}=\int_n^{n+1}dx/x-1/(n+1)>0',r'\text{(c)}\ t_n\text{ decreases and is bounded below by }0'],r't_n\to\gamma\ge0','감소하는 곡선과 오른쪽 끝점 직사각형 사이의 양의 넓이가 두 이웃 항의 차이다.','The positive area between the decreasing curve and its right-endpoint rectangle equals the difference of neighboring terms.',sub='abc')
calc(47,r'\sum_{n=1}^\infty b^{\ln n},\quad b>0','수렴하는 모든 양의 매개변수를 구하라.','Find all positive parameter values giving convergence.',[r'b^{\ln n}=e^{\ln b\ln n}=n^{\ln b}=1/n^{-\ln b}',r'-\ln b>1\iff b<e^{-1}'],r'0<b<1/e')
calc(48,r'\sum_{n=1}^\infty[c/n-1/(n+1)]','수렴하는 모든 실수 매개변수를 구하라.','Find every real parameter giving convergence.',[r's_N=(c-1)H_N+1-1/(N+1)',r'H_N\to\infty\Rightarrow c-1=0\text{ is necessary}'],r'c=1,\quad S=1')
def rectplot(q,power,mode):
 X=lambda x:55+80*(x-1);Y=lambda y:340-270*y;parts=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 410"><rect width="620" height="410" fill="white"/><path d="M55 40V340H570" fill="none" stroke="#64748b"/>']
 for k in range(1,7):
  height=k**(-power)if mode=='left'else(k+1)**(-power);parts.append(f'<rect x="{X(k)}" y="{Y(height)}" width="80" height="{270*height}" fill="#dbeafe" stroke="#3266a1"/>')
 pts=' '.join(f'{X(1+j*6/300):.3f},{Y((1+j*6/300)**(-power)):.3f}'for j in range(301));parts.append(f'<polyline points="{pts}" fill="none" stroke="#c34e29" stroke-width="3"/>')
 if q==2:
  for k in range(1,6):parts.append(f'<rect x="{X(k)}" y="{Y(k**-power)}" width="80" height="{270*k**-power}" fill="none" stroke="#17866c" stroke-dasharray="5 4"/>')
 for k in range(1,8):parts.append(f'<text x="{X(k)-3}" y="362" font-size="12">{k}</text>')
 title={1:'Right rectangles lie below y=x^(-3/2)',2:'Left (dashed) and right rectangles bracket the integral',46:'Left rectangles above y=1/x; right rectangles below'}[q];parts.extend([f'<text x="45" y="390" font-size="14">{title}</text>','</svg>']);p=BASE/f'exercise-content/assets/s11-3-{q}.svg';p.write_text(''.join(parts));ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('감소 곡선과 끝점 직사각형의 넓이 비교',title),'caption':bi('대표 감소함수의 자체 계산 그림.','Original computed illustration using a representative decreasing function.')}
rectplot(1,1.5,'right');rectplot(2,1,'right');rectplot(46,1,'left')
items.sort(key=lambda e:e['number']);assert [e['number']for e in items]==list(range(1,49))
raw={'section':'11.3','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[796,797,798],'pdfPages':[833,834,835]},'scope':{'kind':'exercise','numbers':list(range(1,49)),'total':48,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s11-3.json')
for ex in items:
 for key in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[key]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[key]['en']),(ex['number'],key)
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
# Antiderivatives independently differentiated against the source functions.
Fs=[-1/(2*x*x),x**S.Rational(7,10)/S.Rational(7,10),S.Rational(2,5)*S.log(5*x-1),-1/(9*(3*x-1)**3),S.log(x**3+1)/3,-S.exp(-x**3)/3,-1/(2*S.log(x)**2),S.atan(x)**2/2]
for row,F in zip(integ,Fs):assert S.simplify(S.diff(F,x)-row[1])==0
assert cut==1373 and B(cut)<.05<=B(cut-1)
assert 1/(3*33**3)<1e-5
assert 1/1001<.001
assert abs(sum(j*math.exp(-2*j)for j in range(1,100))-math.exp(-2)/(1-math.exp(-2))**2)<1e-15
(BASE/'exercise-content/s11-3.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('11.3: 48 cards, 3 SVG; schema, bilingual formulas, XML, integral derivatives and certified error bounds passed')
