import json,math,html,sys,re
from pathlib import Path
import sympy as S
import mpmath as mp
BASE=Path(__file__).resolve().parents[1];items=[];mp.mp.dps=60
x,h=S.symbols('x h',real=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 p=856 if q<=32 else 857 if q<=38 else 858
 steps=[M(t)for t in lines];ek=steps+([k]if k else[]);ee=steps+([e]if e else[])
 items.append(dict(id=f'stewart9-exercise-11.11-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('테일러 다항식의 응용','Applications of Taylor polynomials'),statement=bi(M(eq)+' '+tk,M(eq)+' '+te),hint=bi('중심에서 도함수를 구하고 다음 도함수의 상계나 교대급수의 첫 생략항으로 나머지를 제어한다.','Compute derivatives at the center and control the remainder by a derivative bound or the first omitted alternating term.'),steps=bi(ek,ee),answer=bi(M(ans)),check=bi('도함수 계수와 나머지 부등식의 가정을 확인하고 수치값을 독립 대조했다.','Derivative coefficients and remainder hypotheses were checked, with numerical values independently compared.'),conceptHref='../../calc1/index.html',status='math-verified'))
def poly(f,a,n):return S.expand(sum(S.simplify(S.diff(f,x,j).subs(x,a))*h**j/S.factorial(j)for j in range(n+1)))
def plt(q,curves,xlim,ylim,caption=None):
 xa,xb=map(float,xlim);ya,yb=map(float,ylim);X=lambda z:60+555*(z-xa)/(xb-xa);Y=lambda z:345-300*(z-ya)/(yb-ya)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 660 470"><defs><clipPath id="v"><rect x="60" y="45" width="555" height="300"/></clipPath></defs><rect width="660" height="470" fill="white"/>']
 out.append(f'<path d="M60 {Y(max(ya,min(yb,0)))}H615M{X(max(xa,min(xb,0)))} 45V345" stroke="#9aa5b2" fill="none"/>')
 for j,(name,fn)in enumerate(curves):
  c=['#152238','#d5553c','#147cc1','#23865f','#9556b0','#b17b23'][j%6];points=[]
  for i in range(601):
   z=xa+(xb-xa)*i/600;v=float(fn(z));assert math.isfinite(v);points.append(f'{X(z):.3f},{Y(v):.3f}')
  out.append(f'<polyline points="{" ".join(points)}" fill="none" stroke="{c}" stroke-width="2.1" clip-path="url(#v)"/><text x="65" y="{390+15*j}" fill="{c}" font-size="12">{html.escape(name)}</text>')
 for i in range(5):
  z=xa+(xb-xa)*i/4;v=ya+(yb-ya)*i/4;out.append(f'<text x="{X(z)-12}" y="367" font-size="11">{z:.4g}</text><text x="3" y="{Y(v)+4}" font-size="11">{v:.4g}</text>')
 out.append('</svg>');path=BASE/f'exercise-content/assets/s11-11-{q}.svg';path.write_text(''.join(out));ex=next(t for t in items if t['number']==q);ex['figure']={'src':f'../exercise-content/assets/{path.name}','alt':bi('함수·테일러 근사 또는 실제 절대오차의 자체 그래프','Original plot of the function, Taylor approximations, or actual absolute error'),'caption':caption or bi('표시한 식을 직접 계산한 그래프. 오차 상계의 증명은 풀이에 있다.','Plots computed directly from the displayed formulas. The solution proves each error bound.')}
for q,f,degrees,points,xlim,ylim in [(1,S.sin(x),[0,1,3,5],[S.pi/4,S.pi/2,S.pi],[-4,4],[-3,3]),(2,S.tan(x),[0,1,3],[S.pi/6,S.pi/4,S.pi/3],[-1.3,1.3],[-4,4])]:
 ps={j:poly(f,0,j).subs(h,x)for j in degrees};lines=[rf'T_{{{j}}}(x)={S.latex(p)}'for j,p in ps.items()]
 lines+=([r'T_2=T_1,\quad T_4=T_3']if q==1 else[r'T_2=T_1'])
 for z in points:lines.append(rf'x={S.latex(z)}:\quad f={float(f.subs(x,z)):.9f};\quad '+r',\quad '.join(rf'T_{{{j}}}={float(p.subs(x,z)):.9f}'for j,p in ps.items()))
 calc(q,'f(x)='+S.latex(f)+rf',\quad a=0,\quad n\le{max(degrees)},\quad x\in\{{'+','.join(S.latex(z)for z in points)+r'\}','(a) 지정 차수까지의 테일러 다항식과 함수 그래프 (b) 제시한 입력에서의 수치값 (c) 수렴 양상을 구하라.','Find (a) the Taylor polynomials through the given degree and a shared plot, (b) values at the stated inputs, and (c) a convergence description.',lines,r'T_n\to\sin x\text{ for all }x'if q==1 else r'T_n\to\tan x\quad(|x|<\pi/2)','사인 급수는 모든 유계 구간에서 균등 수렴하지만 먼 입력에는 더 높은 차수가 필요하다.'if q==1 else'원점의 탄젠트 급수는 가장 가까운 극점까지의 거리 안에서 수렴한다. 극점에 가까울수록 같은 정확도에 더 많은 항이 필요하다.','The sine series converges uniformly on every bounded interval; more distant inputs require higher degree.'if q==1 else'The tangent series converges up to the nearest poles. More terms are needed near a pole for a given accuracy.',sub='abc')
 plt(q,[('f',S.lambdify(x,f,'math'))]+[(f'T{j}',S.lambdify(x,p,'math'))for j,p in ps.items()],xlim,ylim)
rows=[(3,S.exp(x),S.Integer(1),[0,2],[0,8]),(4,S.sin(x),S.pi/6,[-1,2],[-1.3,1.3]),(5,S.cos(x),S.pi/2,[0,3.2],[-1.4,1.4]),(6,S.exp(-x)*S.sin(x),S.Integer(0),[-1.1,2],[-3,1]),(7,S.log(x),S.Integer(1),[.2,2.4],[-2,2]),(8,x*S.cos(x),S.Integer(0),[-2,2],[-2,2]),(9,x*S.exp(-2*x),S.Integer(0),[-.7,1.5],[-3,2]),(10,S.atan(x),S.Integer(1),[-.2,2.5],[-.5,1.6])]
for q,f,a,xlim,ylim in rows:
 p=poly(f,a,3);calc(q,rf'f(x)={S.latex(f)},\quad a={S.latex(a)}','삼차 테일러 다항식을 구하고 함수와 함께 그려라.','Find the cubic Taylor polynomial and plot it together with the function.',[r'T_3(x)=\sum_{j=0}^3f^{(j)}(a)(x-a)^j/j!',rf'h=x-({S.latex(a)})',rf'(f(a),f^{{\prime}}(a),f^{{\prime\prime}}(a),f^{{(3)}}(a))={S.latex(S.Tuple(*[S.simplify(S.diff(f,x,j).subs(x,a))for j in range(4)]))}'],rf'T_3={S.latex(p)},\quad h=x-({S.latex(a)})');plt(q,[('f',S.lambdify(x,f,'math')),('T3',S.lambdify(x,p.subs(h,x-a),'math'))],xlim,ylim)
for q,f,a,xlim,ylim in [(11,S.cot(x),S.pi/4,[.18,1.45],[-1,6]),(12,(1+x*x)**S.Rational(1,3),S.Integer(0),[-1.5,1.5],[.6,2])]:
 ps={j:poly(f,a,j)for j in range(2,6)};calc(q,rf'f(x)={S.latex(f)},\quad a={S.latex(a)}','컴퓨터 대수로 2차부터 5차까지 테일러 다항식을 구하고 함수와 함께 그려라.','Use a computer algebra system to find Taylor polynomials of degrees two through five and plot them with the function.',[r'T_n=\sum_{j=0}^n f^{(j)}(a)h^j/j!,\quad h=x-a']+[rf'T_{{{j}}}={S.latex(p)}'for j,p in ps.items()],r';\quad '.join(rf'T_{{{j}}}={S.latex(p)}'for j,p in ps.items())+rf',\quad h=x-({S.latex(a)})','SymPy로 도함수 계수를 계산하고 독립 급수 전개와 대조했다.','SymPy derivative coefficients were compared with an independent series expansion.');plt(q,[('f',S.lambdify(x,f,'math'))]+[(f'T{j}',S.lambdify(x,p.subs(h,x-a),'math'))for j,p in ps.items()],xlim,ylim)
# Derivative bounds valid on each entire interval, not merely sampled maxima.
thirdsec=S.sec(S.Rational(1,5))*S.tan(S.Rational(1,5))**3+5*S.sec(S.Rational(1,5))**3*S.tan(S.Rational(1,5))
boundrows=[(13,1/x,1,2,S.Rational(7,10),S.Rational(13,10),6/S.Rational(7,10)**4,'The magnitude 6/x^4 decreases.'),(14,x**S.Rational(-1,2),4,2,S.Rational(7,2),S.Rational(9,2),S.Rational(15,8)*S.Rational(7,2)**S.Rational(-7,2),'The magnitude (15/8)x^(-7/2) decreases.'),(15,x**S.Rational(2,3),1,3,S.Rational(4,5),S.Rational(6,5),S.Rational(56,81)*S.Rational(4,5)**S.Rational(-10,3),'The magnitude (56/81)x^(-10/3) decreases.'),(16,S.sin(x),S.pi/6,4,0,S.pi/3,1,'The absolute cosine is at most one.'),(17,S.sec(x),0,2,-S.Rational(1,5),S.Rational(1,5),thirdsec,'The absolute third derivative is increasing with |x| on this interval.'),(18,S.log(1+2*x),1,3,S.Rational(1,2),S.Rational(3,2),6,'The magnitude 96/(1+2x)^4 decreases.'),(19,S.exp(x*x),0,3,0,S.Rational(1,10),(12+48*S.Rational(1,100)+16*S.Rational(1,10000))*S.exp(S.Rational(1,100)),'The positive polynomial times exp(x^2) increases on this nonnegative interval.'),(20,x*S.log(x),1,3,S.Rational(1,2),S.Rational(3,2),16,'The magnitude 2/x^3 decreases.'),(21,x*S.sin(x),0,4,-1,1,6,'Use |x cos(x)+5 sin(x)| <= |x|+5 <= 6.'),(22,S.sinh(2*x),0,5,-1,1,64*S.sinh(2),'Use |64 sinh(2x)| <= 64 sinh(2).')]
for q,f,a,degree,lo,hi,bound,why in boundrows:
 p=poly(f,a,degree);rad=max(abs(S.sympify(lo)-a),abs(S.sympify(hi)-a));B=S.simplify(bound*rad**(degree+1)/S.factorial(degree+1));der=S.simplify(S.diff(f,x,degree+1))
 calc(q,rf'f(x)={S.latex(f)},\quad a={S.latex(a)},\quad n={degree},\quad {S.latex(lo)}\le x\le {S.latex(hi)}','(a) 지정 테일러 다항식 (b) 구간 전체에서의 테일러 부등식 오차 상계 (c) 절대오차 그래프를 구하라.','Find (a) the specified Taylor polynomial, (b) a Taylor-inequality error bound over the full interval, and (c) the absolute-error graph.',[rf'T_{{{degree}}}={S.latex(p)},\quad h=x-({S.latex(a)})',rf'f^{{({degree+1})}}(x)={S.latex(der)}',rf'|f^{{({degree+1})}}(x)|\le M={S.latex(bound)}',rf'|R_{{{degree}}}(x)|\le\frac{{M|x-a|^{{{degree+1}}}}}{{{degree+1}!}}\le {S.latex(B)}\approx {float(B):.10f}'],rf'T_{{{degree}}}={S.latex(p)},\ h=x-({S.latex(a)});\quad |R_{{{degree}}}|\le {S.latex(B)}','도함수의 단조성 또는 삼각함수의 절댓값 상계로 구간 전체의 상계를 얻는다. 그래프의 실제 오차는 보증 상계 이하이다.',why+' The plot shows the actual error below the certified bound.',sub='abc')
 fn=S.lambdify(x,f,'mpmath');pn=S.lambdify(x,p.subs(h,x-a),'mpmath');af=float(a);bf=float(bound)
 err=lambda z,fn=fn,pn=pn:float(abs(fn(mp.mpf(z))-pn(mp.mpf(z))))
 env=lambda z,af=af,bf=bf,degree=degree:bf*abs(z-af)**(degree+1)/math.factorial(degree+1)
 for z in [float(lo)+(float(hi)-float(lo))*i/300 for i in range(301)]:assert err(z)<=env(z)+1e-14
 plt(q,[('|f - Tn|',err),('Taylor bound M |x-a|^(n+1)/(n+1)!',env)],(lo,hi),(0,max(float(B)*1.05,1e-8)))
for q,f,a,z,n,err in [(23,S.cos(x),S.pi/2,4*S.pi/9,3,(S.pi/18)**5/120),(24,S.sin(x),S.pi/6,19*S.pi/90,4,(2*S.pi/45)**5/120)]:
 p=poly(f,a,n);v=S.N(p.subs(h,z-a),50);actual=S.N(f.subs(x,z),50);assert abs(v-actual)<err
 lo,hi=(v,v+err)if q==23 else(v-err,v+err);assert round(float(lo),5)==round(float(hi),5)
 calc(q,rf'{S.latex(f.subs(x,z))},\quad a={S.latex(a)}','앞 문항의 중심과 테일러 다항식을 사용하여 소수 다섯째 자리까지 구하고 정확도를 보증하라.','Use the earlier center and Taylor polynomial to compute five decimal places and certify the accuracy.',[rf'h={S.latex(z-a)},\quad T_{{{n}}}={S.latex(p)}',rf'T_{{{n}}}={float(v):.12f},\quad |R|\le {S.latex(err)}<{float(err)*1.0001:.12f}',rf'{float(lo):.12f}\le f\le {float(hi):.12f}'],rf'f\approx {float(v):.5f}','양쪽 경계가 모두 같은 다섯 자리 값으로 반올림된다. 코사인 문항은 중심 이동 후 사인 교대급수로 오차 부호까지 결정한다.','Both endpoints round to the same five-decimal value. In the cosine exercise, the shifted sine alternating series also determines the error sign.')
calc(25,r'e^{0.1},\quad \varepsilon=10^{-5}','테일러 부등식으로 충분한 매클로린 항 수를 정하라.','Use Taylor’s inequality to determine a sufficient number of Maclaurin terms.',[r'0\le t\le0.1:\quad e^t\le e^{0.1}',r'|R_n(0.1)|\le e^{0.1}(0.1)^{n+1}/(n+1)!',r'n=2:\quad e^{0.1}10^{-3}/6>10^{-5};\quad n=3:\quad e^{0.1}10^{-4}/24<4.61\times10^{-6}',r'T_3(0.1)=1+0.1+0.1^2/2+0.1^3/6'],r'4\text{ terms, through degree }3')
calc(26,r'\ln1.4,\quad\varepsilon=0.001','로그의 매클로린 급수에서 오차를 보증하는 항 수를 정하라.','Determine a term count in the logarithm Maclaurin series that guarantees the error.',[r'\ln1.4=\sum_{n=1}^\infty(-1)^{n-1}(0.4)^n/n',r'|R_N|\le(0.4)^{N+1}/(N+1)',r'N=4:\quad0.4^5/5=0.002048;\quad N=5:\quad0.4^6/6=0.000682666\ldots',r's_5=0.336981333\ldots'],r'5\text{ terms suffice}')
for q,f,p,power,den,tol in [(27,S.sin(x),x-x**3/6,5,120,mp.mpf('.01')),(28,S.cos(x),1-x*x/2+x**4/24,6,720,mp.mpf('.005')),(29,S.atan(x),x-x**3/3+x**5/5,7,7,mp.mpf('.05'))]:
 rad=(tol*den)**(mp.mpf(1)/power);fn=S.lambdify(x,f,'mpmath');pn=S.lambdify(x,p,'mpmath');err=lambda z,fn=fn,pn=pn:abs(fn(z)-pn(z));actual=mp.findroot(lambda z:err(z)-tol,(rad,rad*mp.mpf('1.15')))
 calc(q,rf'{S.latex(f)}\approx{S.latex(p)},\quad |R|<{str(tol)}','교대급수 나머지나 테일러 부등식으로 보증되는 입력 범위를 구하고 실제 오차 그래프로 확인하라.','Find an input range guaranteed by the alternating-series remainder or Taylor’s inequality and check the actual error graph.',[rf'|R|\le |x|^{power}/{den}',rf'|x|<({str(tol)}\cdot{den})^{{1/{power}}}={float(rad):.10f}',rf'\text{{Numerical actual-error crossing: }}|x|\approx{float(actual):.10f}'],rf'|x|<({str(tol)}\cdot{den})^{{1/{power}}}\approx {float(rad):.8f}','보증 구간은 충분조건이다. 그림의 실제 오차가 허용치에 처음 닿는 입력은 조금 더 크다. 사용 구간에서 교대항 크기가 감소하며 역탄젠트는 단위 수렴 구간 안에 있다.','The certified interval is sufficient. The graph reaches the actual tolerance slightly farther out. Alternating magnitudes decrease on the stated range; the arctangent range lies within its unit convergence interval.')
 plt(q,[('|f - polynomial|',err),('allowed absolute error',lambda z,tol=tol:tol)],[-float(actual)*1.1,float(actual)*1.1],[0,float(tol)*1.7])
calc(30,r'f^{(n)}(4)=(-1)^nn!/[3^n(n+1)]','테일러 급수가 수렴 구간에서 함수를 나타낸다고 가정한다. 5차 테일러 다항식으로 입력 오의 값을 근사할 때 오차가 영점영영영이보다 작음을 보여라.','Assume the Taylor series represents the function on its interval. Show that the degree-five polynomial approximates the value at five with error below 0.0002.',[r'T_5(5)=\sum_{n=0}^5\frac{(-1)^n}{3^n(n+1)}',r'|R_5(5)|\le\frac1{3^6\cdot7}=\frac1{5103}=0.000195963\ldots<0.0002'],r'|f(5)-T_5(5)|<0.0002','양의 항 크기가 감소하며 영으로 가는 교대급수의 첫 생략항을 쓴다.','Use the first omitted term of an alternating series whose positive magnitudes decrease to zero.')
calc(31,r's^{\prime}(0)=20\ \mathrm{m/s},\quad s^{\prime\prime}(0)=2\ \mathrm{m/s^2}','이차 테일러 근사로 다음 일 초 동안의 이동거리를 구하고, 같은 다항식을 일 분에 적용하는 타당성을 논하라.','Estimate the next one-second displacement by a quadratic Taylor polynomial and discuss extending it to a full minute.',[r's(t)-s(0)\approx20t+\tfrac12(2)t^2=20t+t^2',r't=1:\quad\Delta s\approx21\ \mathrm m',r't=60:\quad20t+t^2=4800\ \mathrm m\quad\text{(formal extrapolation only)}'],r'\Delta s(1)\approx21\ \mathrm m','순간 가속도만 알려져 있으므로 일 분 동안 일정 가속도를 가정할 근거가 없다. 고계 도함수 또는 운동 모형 없이는 긴 시간의 오차를 보증할 수 없다.','The instantaneous acceleration alone does not justify constant acceleration for a minute. A higher-derivative bound or motion model is required to guarantee long-time accuracy.')
u1=mp.findroot(lambda u:(1+u)*mp.exp(-u)-mp.mpf('.99'),(-.2,-.1));u2=mp.findroot(lambda u:(1+u)*mp.exp(-u)-mp.mpf('.99'),(.1,.2));temp1=20+u1/mp.mpf('.0039');temp2=20+u2/mp.mpf('.0039')
calc(32,r'\rho(t)=\rho_{20}e^{\alpha(t-20)},\quad\alpha=0.0039/{}^\circ\mathrm C,\quad\rho_{20}=1.7\times10^{-8}\ \Omega\mathrm m','(a) 온도 이십에서 선형·이차 근사 (b) 구리의 섭씨 영하 이백오십부터 천까지 세 그래프 (c) 선형 근사의 상대오차가 일 퍼센트 이하인 온도를 구하라.','Find (a) linear and quadratic approximations at twenty degrees, (b) plots for copper from minus two hundred fifty to one thousand degrees Celsius, and (c) temperatures with at most one percent relative error in the linear approximation.',[r'u=\alpha(t-20),\quad T_1=\rho_{20}(1+u),\quad T_2=\rho_{20}(1+u+u^2/2)',r'\frac{|T_1-\rho|}{\rho}=1-(1+u)e^{-u}\le0.01',rf'(1+u)e^{{-u}}=0.99:\quad u={float(u1):.10f},\ {float(u2):.10f}'],rf'T_1=\rho_{{20}}[1+\alpha(t-20)],\quad T_2=\rho_{{20}}[1+\alpha(t-20)+\alpha^2(t-20)^2/2];\quad {float(temp1):.6f}\le t\le{float(temp2):.6f}\ ({{}}^\circ\mathrm C)','상대오차의 분모는 주어진 지수 모형의 정확한 저항률이다. 그래프 세로축은 이십 도 저항률의 배수이며, 온도 구간의 먼 부분에서는 근사의 상대오차가 커진다.','Relative error is measured against the exact exponential-model resistivity. The plotted vertical axis is a multiple of the resistivity at twenty degrees; the approximations become inaccurate far from that temperature.',sub='abc')
plt(32,[('exact rho / rho20',lambda t:math.exp(.0039*(t-20))),('linear / rho20',lambda t:1+.0039*(t-20)),('quadratic / rho20',lambda t:1+.0039*(t-20)+(.0039*(t-20))**2/2)],[-250,1000],[-1,49])
calc(33,r'E=q/D^2-q/(D+d)^2,\quad d,D>0','크기가 같고 부호가 반대인 두 전하와 같은 직선 위의 관찰점을 생각한다. 양전하까지 거리는 대문자 거리, 전하 간격은 소문자 거리이다. 멀리서 전기장이 거리의 세제곱에 반비례함을 보여라.','Consider an observation point collinear with opposite equal charges, at distance D from the positive charge and D+d from the negative charge. Show the inverse-cube far-field behavior.',[r'E=\frac q{D^2}[1-(1+d/D)^{-2}]',r'(1+z)^{-2}=1-2z+3z^2-4z^3+\cdots',r'E=2qd/D^3-3qd^2/D^4+O(d^3/D^5)'],r'E\sim2qd/D^3\quad(d/D\to0)')
calc(34,r'\frac{n_1}{\ell_o}+\frac{n_2}{\ell_i}=\frac1R\left(\frac{n_2s_i}{\ell_i}-\frac{n_1s_o}{\ell_o}\right),\quad \ell_o^2=R^2+(s_o+R)^2-2R(s_o+R)\cos\phi,\quad\ell_i^2=R^2+(s_i-R)^2+2R(s_i-R)\cos\phi,\quad h=R\sin\phi','구면 굴절면의 식에서 (a) 코사인의 일차 근사로 가우스 광학 식 (b) 삼차 테일러 근사와 역제곱근 이항 전개로 삼차 광학 식을 유도하라. 거리는 양수이다.','For the spherical-interface equations, derive (a) Gaussian optics using the linear cosine approximation and (b) third-order optics using the cubic cosine Taylor polynomial and inverse-square-root expansion. Distances are positive.',[r'\text{(a)}\quad\cos\phi\approx1\Rightarrow\ell_o\approx s_o,\quad\ell_i\approx s_i',r'n_1/s_o+n_2/s_i=(n_2-n_1)/R',r'\text{(b)}\quad\cos\phi\approx1-\phi^2/2,\quad\phi^2\approx h^2/R^2',r'\ell_o^2\approx s_o^2+(s_o+R)h^2/R,\quad\ell_i^2\approx s_i^2-(s_i-R)h^2/R',r'\ell_o^{-1}\approx\frac1{s_o}-\frac{(s_o+R)h^2}{2Rs_o^3},\quad\ell_i^{-1}\approx\frac1{s_i}+\frac{(s_i-R)h^2}{2Rs_i^3}',r'\frac{n_1(R+s_o)}{R\ell_o}+\frac{n_2(R-s_i)}{R\ell_i}=0',r'\text{Insert the inverse-distance expansions and collect the }h^2\text{ terms.}'],r'\text{(a)}\quad\frac{n_1}{s_o}+\frac{n_2}{s_i}=\frac{n_2-n_1}R;\quad\text{(b)}\quad\frac{n_1}{s_o}+\frac{n_2}{s_i}\approx\frac{n_2-n_1}R+h^2\left[\frac{n_1}{2s_o}\left(\frac1{s_o}+\frac1R\right)^2+\frac{n_2}{2s_i}\left(\frac1R-\frac1{s_i}\right)^2\right]','이차 높이항까지 유지하며 생략항은 높이의 사차 이상이다. 중심축 근방에서 각 거리의 이항 전개 인수가 작아야 한다.','Terms through second order in height are retained; omitted terms begin at fourth order. Each binomial expansion parameter must be small near the optical axis.',sub='ab')
calc(35,r'v^2=\frac{gL}{2\pi}\tanh\left(\frac{2\pi d}L\right),\quad g,L,d>0','(a) 깊은 물 (b) 얕은 물에서 파동 속도를 근사하고 (c) 파장이 수심의 열 배보다 클 때 속도 제곱의 얕은물 근사 오차를 보증하라.','Approximate wave speed in (a) deep and (b) shallow water, and (c) bound the shallow-water squared-speed error when wavelength exceeds ten times depth.',[r'z=2\pi d/L',r'\text{(a)}\quad z\to\infty:\quad\tanh z\to1,\quad v\sim\sqrt{gL/(2\pi)}',r'\text{(b)}\quad z\to0:\quad\tanh z=z-z^3/3+2z^5/15-\cdots,\quad v^2\sim gd',r'\text{(c)}\quad L>10d\Rightarrow0<z<\pi/5',r'0\le z-\tanh z\le z^3/3',r'0\le gd-v^2\le\frac{gL}{6\pi}z^3<\frac{\pi^2}{750}gL<0.014gL'],r'\text{(a)}\quad v\approx\sqrt{gL/(2\pi)};\quad\text{(b)}\quad v\approx\sqrt{gd};\quad\text{(c)}\quad|v^2-gd|<0.014gL','이 구간에서 쌍곡탄젠트 급수의 교대항 크기가 감소하므로 첫 생략항을 쓸 수 있다. 별도로 tanh의 도함수로 tanh z≤z를 얻고, z−tanh z의 도함수 tanh²z≤z²를 적분해 같은 상계를 독립 확인한다.','The alternating tanh terms decrease on this interval, so the first omitted term bounds the tail. Independently, its derivative gives tanh z≤z; integrating (z−tanh z)′=tanh²z≤z² confirms the same bound.',sub='abc')
calc(36,r'V=2\pi k_e\sigma(\sqrt{d^2+R^2}-d),\quad d,R>0','반지름과 표면 전하밀도가 주어진 원판의 수직 중심축 위 전위를 먼 거리에서 근사하라.','Approximate the potential far along the perpendicular central axis of a uniformly charged disk.',[r'V=2\pi k_e\sigma d[\sqrt{1+(R/d)^2}-1]',r'\sqrt{1+z}=1+z/2-z^2/8+O(z^3)',r'V=\pi k_e\sigma R^2/d-\pi k_e\sigma R^4/(4d^3)+O(d^{-5})'],r'V\sim\pi k_e\sigma R^2/d\quad(d/R\to\infty)','원판 전체 전하는 원주율 곱하기 반지름 제곱 곱하기 표면밀도이므로 점전하의 먼거리 전위와도 일치한다.','The leading term also equals the distant point-charge potential for the disk’s total charge.')
R=mp.mpf(6370);L=mp.mpf(100);cor=R*(1/mp.cos(L/R)-1);approx=L*L/(2*R)+5*L**4/(24*R**3)
calc(37,r'C=R\sec(L/R)-R,\quad R=6370\ \mathrm{km},\quad L=100\ \mathrm{km}','(a) 지구 중심의 직각삼각형으로 곡률 보정식을 유도하고 (b) 사차 테일러 근사 (c) 주어진 도로 길이에 대한 정확식과 근사식을 비교하라.','(a) Derive the curvature correction from the center-based right triangle, (b) obtain the fourth-order Taylor approximation, and (c) compare both formulas for the specified road.',[r'\theta=L/R,\quad\cos\theta=R/(R+C)\Rightarrow C=R\sec\theta-R',r'\sec z=1+z^2/2+5z^4/24+O(z^6)',r'C=L^2/(2R)+5L^4/(24R^3)+O(L^6/R^5)',rf'C_{{\rm exact}}={float(cor*1000):.9f}\ \mathrm m,\quad C_{{\rm Taylor}}={float(approx*1000):.9f}\ \mathrm m',rf'C_{{\rm exact}}-C_{{\rm Taylor}}={float((cor-approx)*1000):.12f}\ \mathrm m'],r'C\approx\frac{L^2}{2R}+\frac{5L^4}{24R^3}\approx785.009957\ \mathrm m','도로 길이를 지표면의 호 길이로 사용한다. 최종 근삿값의 오차는 약 여덟 마이크로미터이다.','Road length is the surface arc length. The final approximation error is about eight micrometers.',sub='abc')
pendlines=[r'c_n=\binom{2n}n/4^n,\quad(1-k^2\sin^2x)^{-1/2}=\sum_{n=0}^\infty c_nk^{2n}\sin^{2n}x',r'\int_0^{\pi/2}\sin^{2n}x\,dx=(\pi/2)c_n',r'T=2\pi\sqrt{L/g}\sum_{n=0}^\infty c_n^2k^{2n}=2\pi\sqrt{L/g}[1+k^2/4+9k^4/64+25k^6/256+\cdots]',r'c_{n+1}/c_n=(2n+1)/(2n+2)<1,\quad0<c_n^2\le1/4\quad(n\ge1)',r'1+k^2/4\le\sum c_n^2k^{2n}\le1+\frac14\sum_{n=1}^\infty k^{2n}=\frac{4-3k^2}{4-4k^2}']
T0=2*mp.pi/mp.sqrt(mp.mpf('9.8'));pendlines.append(rf'g=9.8\ \mathrm{{m/s^2}},\ L=1\ \mathrm m:\quad T_0={float(T0):.9f}\ \mathrm s')
for angle in [10,42]:
 k=mp.sin(mp.radians(angle)/2);low=T0*(1+k*k/4);upper=T0*(4-3*k*k)/(4-4*k*k);exact=4/mp.sqrt(mp.mpf('9.8'))*mp.ellipk(k*k);assert low<exact<upper
 pendlines.append(rf'\theta_0={angle}^\circ:\quad{float(low):.9f}\le T\le{float(upper):.9f}\ \mathrm s,\quad\frac{{T}}{{T_0}}-1\in[{float(low/T0-1):.8f},{float(upper/T0-1):.8f}]')
calc(38,r'T=4\sqrt{L/g}\int_0^{\pi/2}(1-k^2\sin^2x)^{-1/2}\,dx,\quad k=\sin(\theta_0/2),\quad0\le k<1','(a) 이항급수와 짝수 사인 적분으로 주기 급수 (b) 등비급수로 양쪽 상계 (c) 길이 일 미터, 진폭 십 도와 사십이 도의 수치 구간을 구하고 소각 근사와 비교하라.','Find (a) a period series using the binomial series and even sine integrals, (b) two-sided geometric-series bounds, and (c) numerical intervals for a one-meter pendulum at ten and forty-two degrees, compared with the small-angle estimate.',pendlines,r'2\pi\sqrt{L/g}(1+k^2/4)\le T\le2\pi\sqrt{L/g}\frac{4-3k^2}{4-4k^2}','모든 항이 양수이고 계수가 감소한다. 소각 근사값 대비 주기의 증가는 십 도에서 약 영점이 퍼센트, 사십이 도에서 약 삼점이에서 삼점칠 퍼센트로 진폭 보정의 영향이 커진다.','All terms are positive with decreasing coefficients. Relative to the small-angle baseline, the period increases about 0.2 percent at ten degrees and about 3.2–3.7 percent at forty-two degrees, so amplitude correction matters more.',sub='abc')
calc(39,r'f(r)=0,\quad x_{n+1}=x_n-f(x_n)/f^{\prime}(x_n),\quad |f^{\prime\prime}(x)|\le M,\quad |f^{\prime}(x)|\ge K>0\quad(x\in I)','세 점을 포함하는 구간에서 주어진 도함수 조건이 성립할 때 뉴턴 반복의 다음 오차가 현재 오차 제곱에 비례하는 상계로 제어됨을 증명하라.','Assuming the derivative bounds on an interval containing the three points, prove a quadratic upper bound for the next Newton error.',[r'f(r)=f(x_n)+f^{\prime}(x_n)(r-x_n)+R_1(r),\quad|R_1(r)|\le(M/2)|r-x_n|^2',r'0=f^{\prime}(x_n)(r-x_{n+1})+R_1(r)',r'x_{n+1}-r=R_1(r)/f^{\prime}(x_n)'],r'|x_{n+1}-r|\le\frac M{2K}|x_n-r|^2','도함수의 양의 하한이 분모를 제어한다. 이 부등식만으로 임의의 초기값에서 반복이 항상 같은 구간에 머문다고 결론내리지는 않는다.','The positive derivative lower bound controls division. This estimate alone does not guarantee that iterations from an arbitrary initial point remain in the same interval.')
items.sort(key=lambda e:e['number']);assert [e['number']for e in items]==list(range(1,40))
raw={'section':'11.11','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[856,857,858],'pdfPages':[893,894,895]},'scope':{'kind':'exercise','numbers':list(range(1,40)),'total':39,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s11-11.json')
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
 for field in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[field]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[field]['en'])
# Independent series-versus-derivative checks at rational centers.
for q,f,a,xlim,ylim in rows:
 expected=S.series(f.subs(x,h+a),h,0,4).removeO();assert S.simplify(expected-poly(f,a,3))==0
for q,f,a,n,lo,hi,bound,why in boundrows:
 expected=S.series(f.subs(x,h+a),h,0,n+1).removeO();assert S.simplify(expected-poly(f,a,n))==0
assert 0<cor-approx<mp.mpf('0.00000003')
assert abs((1+u1)*mp.exp(-u1)-mp.mpf('.99'))<mp.mpf('1e-55');assert abs((1+u2)*mp.exp(-u2)-mp.mpf('.99'))<mp.mpf('1e-55')
(BASE/'exercise-content/s11-11.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('11.11: 39 cards, 26 SVG; derivative/series identities, interval remainder bounds, relative-error roots, elliptic-integral enclosure, schema/XML verified')
