import json,math,html,sys,re
from pathlib import Path
import sympy as S
BASE=Path(__file__).resolve().parents[1];items=[];n=S.symbols('n',integer=True,positive=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(q,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=773 if q<=28 else 774 if q<=77 else 775 if q<=98 else 776
 items.append(dict(id=f'stewart9-exercise-11.1-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('수열','Sequences'),statement=bi(sk,se),hint=bi('일반항·점화식을 정리하고 극한 법칙, 끼워넣기 또는 단조유계 정리를 적용한다.','Simplify the term or recurrence and apply limit laws, squeezing, or bounded monotone convergence.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if k:steps.append((k,e))
 add(q,M(eq)+' '+tk,M(eq)+' '+te,steps,M(ans),M(ans),'초기항·정의역과 극한 논증의 조건을 확인했다.','Initial terms, domain, and conditions of the limit argument were checked.',sub)
def dots(q,sets,limit=None):
 pts=[(i,v) for label,values in sets for i,v in values];xmin=0;xmax=max(i for i,v in pts)+1;lo=min(v for i,v in pts);hi=max(v for i,v in pts)
 if limit is not None:lo=min(lo,limit);hi=max(hi,limit)
 pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad;X=lambda x:55+510*(x-xmin)/(xmax-xmin);Y=lambda y:300-250*(y-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 390"><rect width="620" height="390" fill="white"/><path d="M55 40V300H575" stroke="#8492a5" fill="none"/>',f'<text x="55" y="25" font-size="15">Sequence {q}: discrete terms</text>']
 for j,(label,values) in enumerate(sets):
  c=['#1463c2','#c64c38','#159568'][j%3]
  for i,v in values:out.append(f'<circle cx="{X(i):.3f}" cy="{Y(v):.3f}" r="3" fill="{c}"/>')
  out.append(f'<text x="55" y="{337+17*j}" fill="{c}" font-size="12">{html.escape(label)}</text>')
 if limit is not None:out.append(f'<path d="M55 {Y(limit)}H575" stroke="#65758d" stroke-dasharray="5 5"/><text x="570" y="{Y(limit)-5}" font-size="10">L={limit:.5g}</text>')
 for i in range(6):
  v=lo+(hi-lo)*i/5;out.append(f'<text x="5" y="{Y(v)+4}" font-size="10">{v:.4g}</text>')
 for i in [1,int(xmax/2),int(xmax)-1]:out.append(f'<text x="{X(i)}" y="318" font-size="11">{i}</text>')
 out.append('</svg>');p=BASE/f'exercise-content/assets/s11-1-{q}.svg';p.write_text(''.join(out));ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('정수 인덱스에 대응하는 수열의 점 그래프','Discrete sequence values at integer indices'),'caption':bi('자체 계산한 항을 점으로 표시했다. 선으로 연결하지 않았다.','Original computed terms shown as discrete points.')}
calc(1,r'\{a_n\}','(a) 수열의 정의 (b) 극한이 팔이라는 뜻 (c) 양의 무한대로 간다는 뜻을 설명하라.','Explain (a) a sequence, (b) having limit eight, and (c) tending to positive infinity.',[r'\text{(a)}\ a:\mathbb N\to\mathbb R',r'\text{(b)}\ \forall\varepsilon>0\ \exists N:\ n>N\Rightarrow|a_n-8|<\varepsilon',r'\text{(c)}\ \forall M\in\mathbb R\ \exists N:\ n>N\Rightarrow a_n>M'],r'\text{(a) indexed function; (b) arbitrary closeness to 8; (c) eventual exceedance of every bound}','수열은 순서를 가진 항들의 함수이다. 유한한 초기 항은 극한 정의에 영향을 주지 않는다.','A sequence is a function giving ordered terms; finitely many initial terms do not affect these definitions.',sub='abc')
calc(2,r'\{a_n\}','(a) 수렴수열 (b) 발산수열을 정의하고 각각 예를 두 개 들어라.','Define (a) a convergent sequence and (b) a divergent sequence, giving two examples of each.',[r'\text{convergent: a finite real limit exists}',r'1/n\to0,\quad2+1/n\to2',r'n\to+\infty,\quad(-1)^n\text{ oscillates}'],r'\text{(a)}\ 1/n,\ 2+1/n;\quad\text{(b)}\ n,\ (-1)^n','양의 무한대로 가는 경우도 실수 극한은 없으므로 발산으로 분류한다.','Tending to positive infinity is divergent because it has no finite real limit.',sub='ab')
initial=[(3,n**3-1,1),(4,1/(3**n+1),1),(5,2**n+n,2),(6,(n*n-1)/(n*n+1),3),(7,(-1)**(n-1)/n**2,1),(8,(-1)**n/4**n,1),(9,S.cos(n*S.pi),1),(10,1+(-1)**n,1),(11,(-2)**n/S.factorial(n+1),1),(12,(2*n+1)/(S.factorial(n)+1),1)]
for q,expr,start in initial:
 vals=[S.simplify(expr.subs(n,j)) for j in range(start,start+5)]
 calc(q,rf'a_n={S.latex(expr)},\quad n\ge{start}','처음 다섯 항을 나열하라.','List the first five terms.',[rf'n={start},{start+1},{start+2},{start+3},{start+4}'],' ,\ '.join(S.latex(v) for v in vals))
for q,eq,vals in [(13,r'a_1=1,\quad a_{n+1}=2a_n+1',[1,3,7,15,31]),(14,r'a_1=6,\quad a_{n+1}=a_n/n',[6,6,3,1,S.Rational(1,4)]),(15,r'a_1=2,\quad a_{n+1}=a_n/(1+a_n)',[2,S.Rational(2,3),S.Rational(2,5),S.Rational(2,7),S.Rational(2,9)]),(16,r'a_1=2,\quad a_2=1,\quad a_{n+1}=a_n-a_{n-1}',[2,1,-1,-2,-1])]:
 calc(q,eq,'처음 다섯 항을 나열하라.','List the first five terms.',[r'\text{Apply the recurrence successively from its initial data.}'],',\ '.join(S.latex(v) for v in vals))
for q,eq,lines,ans in [(17,r'1/2,1/4,1/6,1/8,1/10,\ldots',[r'\text{denominator}=2n'],r'a_n=1/(2n)'),(18,r'4,-1,1/4,-1/16,1/64,\ldots',[r'a_{n+1}/a_n=-1/4'],r'a_n=4(-1/4)^{n-1}'),(19,r'-3,2,-4/3,8/9,-16/27,\ldots',[r'a_{n+1}/a_n=-2/3'],r'a_n=-3(-2/3)^{n-1}'),(20,r'5,8,11,14,17,\ldots',[r'a_{n+1}-a_n=3'],r'a_n=3n+2'),(21,r'1/2,-4/3,9/4,-16/5,25/6,\ldots',[r'|a_n|=n^2/(n+1),\quad\text{sign}=(-1)^{n-1}'],r'a_n=(-1)^{n-1}n^2/(n+1)'),(22,r'1,0,-1,0,1,0,-1,0,\ldots',[r'\cos0=1,\ \cos(\pi/2)=0,\ \cos\pi=-1,\ \cos(3\pi/2)=0'],r'a_n=\cos((n-1)\pi/2)')]:
 calc(q,eq,'표시된 규칙이 계속된다고 가정해 일반항 하나를 구하라.','Give a general term assuming the displayed pattern continues.',lines,ans,'유한한 초기 항만으로 일반항이 유일해지는 것은 아니며, 제시한 식은 보이는 규칙을 따른다.','Finitely many initial terms do not determine a unique formula; this one follows the visible pattern.')
for q,expr,limit in [(23,3*n/(1+6*n),S.Rational(1,2)),(24,2+(-1)**n/n,2),(25,1+(-S.Rational(1,2))**n,1),(26,1+S.Rational(10,9)**n,S.oo)]:
 vals=[float(expr.subs(n,j)) for j in range(1,11)];ans=r'a_1,\ldots,a_{10}:\quad'+',\ '.join(f'{v:.4f}' for v in vals)+r';\quad\lim a_n='+S.latex(limit)
 calc(q,rf'a_n={S.latex(expr)}','처음 열 항을 소수 넷째 자리까지 계산해 점으로 그리고 극한을 판정하라.','Calculate the first ten terms to four decimal places, plot them as points, and determine the limit.',[r'n=1,\ldots,10',r'\text{Use a rational limit or the magnitude of the geometric factor.}'],ans,'무한대로 증가하는 경우는 유한한 극한이 없는 발산이다. 그래프의 추측을 일반항으로 확인한다.','Growth to infinity means divergence without a finite limit; the formula confirms the graphical prediction.')
 dots(q,[('first ten terms',list(enumerate(vals,1)))],None if limit==S.oo else float(limit))
limits=[(27,r'5/(n+2)',[r'0<a_n\le5/n\to0'],r'0'),(28,r'5\sqrt{n+2}',[r'a_n\ge5\sqrt n\to+\infty'],r'+\infty'),(29,r'(4n^2-3n)/(2n^2+1)',[r'a_n=(4-3/n)/(2+1/n^2)'],r'2'),(30,r'(4n^2-3n)/(2n+1)',[r'a_n/n=(4-3/n)/(2+1/n)\to2'],r'+\infty'),(31,r'n^4/(n^3-2n)',[r'a_n=n/(1-2/n^2)'],r'+\infty'),(32,r'2+(0.86)^n',[r'|0.86|<1\Rightarrow(0.86)^n\to0'],r'2'),(33,r'3^n7^{-n}',[r'a_n=(3/7)^n,\quad0<3/7<1'],r'0'),(34,r'3\sqrt n/(\sqrt n+2)',[r'a_n=3/(1+2/\sqrt n)'],r'3'),(35,r'e^{-1/\sqrt n}',[r'-1/\sqrt n\to0,\quad e^x\text{ is continuous}'],r'1'),(36,r'4^n/(1+9^n)',[r'0<a_n\le(4/9)^n\to0'],r'0'),(37,r'\sqrt{(1+4n^2)/(1+n^2)}',[r'a_n=\sqrt{(1/n^2+4)/(1/n^2+1)}'],r'2'),(38,r'\cos(n\pi/(n+1))',[r'n\pi/(n+1)\to\pi'],r'-1'),(39,r'n^2/\sqrt{n^3+4n}',[r'a_n=\sqrt n/\sqrt{1+4/n^2}'],r'+\infty'),(40,r'e^{2n/(n+2)}',[r'2n/(n+2)\to2'],r'e^2'),(41,r'(-1)^n/(2\sqrt n)',[r'|a_n|=1/(2\sqrt n)\to0'],r'0'),(43,r'(2n-1)!/(2n+1)!',[r'a_n=1/[(2n)(2n+1)]'],r'0'),(44,r'\ln n/\ln(2n)',[r'a_n=\ln n/(\ln n+\ln2)'],r'1'),(46,r'\arctan n/n',[r'0<a_n<\pi/(2n)\to0'],r'0'),(47,r'n^2e^{-n}',[r'\lim_{x\to\infty}x^2/e^x=\lim 2x/e^x=\lim 2/e^x=0'],r'0'),(48,r'\ln(n+1)-\ln n',[r'a_n=\ln(1+1/n)'],r'0'),(49,r'\cos^2n/2^n',[r'0\le a_n\le2^{-n}\to0'],r'0'),(50,r'\sqrt[n]{2^{1+3n}}',[r'a_n=2^{3+1/n}'],r'8'),(51,r'n\sin(1/n)',[r'a_n=\sin(1/n)/(1/n)'],r'1'),(52,r'2^{-n}\cos n\pi',[r'|a_n|\le2^{-n}\to0'],r'0'),(53,r'(1+2/n)^n',[r'\ln a_n=\frac{\ln(1+2/n)}{2/n}\,2\to2'],r'e^2'),(54,r'n^{1/n}',[r'\ln a_n=\ln n/n\to0'],r'1'),(55,r'\ln(2n^2+1)-\ln(n^2+1)',[r'a_n=\ln\frac{2+1/n^2}{1+1/n^2}'],r'\ln2'),(56,r'(\ln n)^2/n',[r'\lim_{x\to\infty}(\ln x)^2/x=\lim 2\ln x/x=0'],r'0'),(57,r'\arctan(\ln n)',[r'\ln n\to+\infty,\quad\arctan x\to\pi/2'],r'\pi/2'),(58,r'n-\sqrt{n+1}\sqrt{n+3}',[r'a_n=\frac{-4n-3}{n+\sqrt{n^2+4n+3}}=\frac{-4-3/n}{1+\sqrt{1+4/n+3/n^2}}'],r'-2'),(60,r'1,1/3,1/2,1/4,1/3,1/5,1/4,1/6,\ldots',[r'a_{2k-1}=1/k\to0,\quad a_{2k}=1/(k+2)\to0'],r'0'),(61,r'n!/2^n',[r'a_{n+1}/a_n=(n+1)/2\ge3/2\quad(n\ge2)'],r'+\infty'),(62,r'(-3)^n/n!',[r'|a_{n+1}|/|a_n|=3/(n+1)\le1/2\quad(n\ge5)'],r'0')]
for q,eq,lines,lim in limits:
 calc(q,'a_n='+eq,'수렴·발산을 판정하고 수렴하면 극한을 구하라.','Determine convergence or divergence and find the limit when convergent.',lines,r'\lim_{n\to\infty}a_n='+lim,'양의 무한대 표기는 발산을 뜻한다. 실수 함수에 사용한 로피탈 법칙은 정수 입력 부분수열로 전달한다.','Positive infinity denotes divergence. When l’Hôpital’s rule is used on a real-variable function, its limit passes to the integer inputs.')
calc(42,r'a_n=(-1)^{n+1}n/(n+\sqrt n)','수렴 여부를 판정하라.','Determine convergence.',[r'a_{2k}\to-1,\quad a_{2k-1}\to1'],r'\text{divergent}','두 부분수열의 극한이 다르다.','Two subsequences have different limits.')
calc(45,r'a_n=\sin n','수렴 여부를 판정하라.','Determine convergence.',[r'\sin(n+2)-\sin n=2\sin1\cos(n+1)',r'\sin n\to L\Rightarrow\cos n\to0\Rightarrow L^2=1',r'\sin(n+1)=\sin n\cos1+\cos n\sin1\Rightarrow L=L\cos1\Rightarrow L=0'],r'\text{divergent}','수렴한다고 가정하면 제곱이 일인 극한이 동시에 영이어야 한다는 모순이 생긴다.','Assuming convergence forces the limit to have square one and also be zero, a contradiction.')
calc(59,r'0,1,0,0,1,0,0,0,1,\ldots','영 묶음의 길이가 계속 하나씩 늘어나는 수열의 수렴 여부를 판정하라.','Determine convergence when each successive block of zeros increases in length by one.',[r'a_{k(k+3)/2}=1\quad(k\ge1)',r'\text{infinitely many zero terms also occur}'],r'\text{divergent}','영인 부분수열과 일인 부분수열이 모두 무한히 이어진다.','There are infinite constant-zero and constant-one subsequences.')
for q,eq,lines,ans,f,lim in [(63,r'a_n=(-1)^n n/(n+1)',[r'a_{2k}\to1,\quad a_{2k-1}\to-1'],r'\text{divergent}',lambda j:(-1)**j*j/(j+1),None),(64,r'a_n=\sin n/n',[r'|a_n|\le1/n\to0'],r'\lim a_n=0',lambda j:math.sin(j)/j,0),(65,r'a_n=\arctan(n^2/(n^2+4))',[r'n^2/(n^2+4)\to1'],r'\lim a_n=\pi/4',lambda j:math.atan(j*j/(j*j+4)),math.pi/4),(66,r'a_n=\sqrt[n]{3^n+5^n}',[r'5\le a_n\le5\cdot2^{1/n}\to5'],r'\lim a_n=5',lambda j:5*(1+(3/5)**j)**(1/j),5),(67,r'a_n=n^2\cos n/(1+n^2)',[r'n^2/(1+n^2)\to1',r'\cos n\to L\Rightarrow\sin n\to0\Rightarrow L^2=1',r'\cos(n+1)=\cos n\cos1-\sin n\sin1\Rightarrow L=L\cos1\Rightarrow L=0'],r'\text{divergent}',lambda j:j*j*math.cos(j)/(1+j*j),None),(68,r'a_n=\frac{1\cdot3\cdot5\cdots(2n-1)}{n!}',[r'a_{n+1}/a_n=(2n+1)/(n+1)\ge3/2\quad(n\ge1)',r'a_n\ge(3/2)^{n-1}\to+\infty'],r'a_n\to+\infty',lambda j:math.prod((2*k-1)/k for k in range(1,j+1)),None),(69,r'a_n=\frac{1\cdot3\cdot5\cdots(2n-1)}{(2n)^n}',[r'0<a_n=\prod_{k=1}^n\frac{2k-1}{2n}\le2^{-\lfloor n/2\rfloor}\to0'],r'\lim a_n=0',lambda j:math.prod((2*k-1)/(2*j) for k in range(1,j+1)),0)]:
 calc(q,eq,'점 그래프로 극한을 추측하고 수렴 여부와 추측을 증명하라.','Use a point plot to predict behavior and prove convergence or divergence.',lines,ans,'초기 점의 모습만으로 결론을 내리지 않고 일반항의 비교 또는 부분수열로 확인한다.','The conclusion follows from term comparison or subsequences, not just the finite plot.')
 N=15 if q==68 else 60;dots(q,[('sequence terms',[(j,f(j)) for j in range(1,N+1)])],lim)
calc(70,r'a_{n+1}=4-a_n','초기항이 (a) 일 (b) 이일 때 수렴 여부를 판정하라.','Determine convergence starting from (a) one and (b) two.',[r'\text{(a)}\ 1,3,1,3,\ldots',r'\text{(b)}\ 2,2,2,\ldots'],r'\text{(a) divergent};\quad\text{(b)}\ \lim a_n=2',sub='ab')
v=[1000*1.06**j for j in range(1,6)]
calc(71,r'a_n=1000(1.06)^n','연 복리 육 퍼센트 예금의 처음 다섯 연말 잔액을 구하고 수렴 여부를 판정하라.','Find the first five year-end balances of a deposit earning six percent annually and determine convergence.',[r'a_{n+1}=1.06a_n'],'a_1,\ldots,a_5='+r',\ '.join(f'{x:.2f}' for x in v)+r';\quad a_n\to+\infty')
from decimal import Decimal as D
interest=lambda j:100*((D('1.0025')**j-1)/D('.0025')-j)
calc(72,r'I_n=100\left[\frac{1.0025^n-1}{0.0025}-n\right]','(a) 매월 적립의 누적 이자 처음 여섯 항 (b) 이 년 후 이자를 구하라.','Find (a) the first six cumulative-interest values and (b) the interest after two years.',[r'n=1,\ldots,6;\quad 2\text{ years}=24\text{ months}'],r'\text{(a)}\ '+r',\ '.join(f'{interest(j):.2f}' for j in range(1,7))+rf';\quad\text{{(b)}}\ I_{{24}}={interest(24):.2f}',sub='ab')
calc(73,r'P_0=5000','매달 팔 퍼센트 증가한 뒤 삼백 마리를 수확한다. (a) 점화식 (b) 육 개월 뒤 개체수를 구하라.','The fish count grows eight percent each month before a harvest of three hundred. Find (a) a recurrence and (b) the count after six months.',[r'P_n=1.08P_{n-1}-300',r'P_n-3750=1.08(P_{n-1}-3750)',r'P_n=3750+1250(1.08)^n'],rf'\text{{(a)}}\ P_n=1.08P_{{n-1}}-300;\quad\text{{(b)}}\ P_6={3750+1250*1.08**6:.6f}\approx5734',sub='ab')
coll=[]
for initial in [11,25]:
 seq=[initial]
 for j in range(39):seq.append(seq[-1]//2 if seq[-1]%2==0 else 3*seq[-1]+1)
 coll.append(rf'a_1={initial}:\quad'+','.join(map(str,seq)))
calc(74,r'a_{n+1}=\begin{cases}a_n/2&a_n\text{ even}\\3a_n+1&a_n\text{ odd}\end{cases}','초기값 십일과 이십오 각각의 처음 사십 항을 계산하고 추측을 제시하라.','Compute forty terms for each initial value eleven and twenty-five and state a conjecture.',coll,r'\text{conjecture: every positive integer start eventually enters }4,2,1','두 경우 모두 같은 삼항 순환에 들어간다. 이 유한 계산은 모든 초기값에 대한 증명이 아니다.','Both starts reach the same three-term cycle; these finite computations do not prove the statement for every start.')
calc(75,r'a_n=nr^n,\quad r\in\mathbb R','수렴하게 하는 모든 매개변수를 구하라.','Find every parameter value giving convergence.',[r'0<|r|<1:\quad |a_{n+1}|/|a_n|=|r|(1+1/n)\to|r|<1',r'r=0:\ a_n=0;\quad |r|\ge1:\ |a_n|\ge n'],r'-1<r<1,\quad\lim a_n=0')
calc(76,r'a_1=1,\quad a_{n+1}=1/(1+a_n)','(a) 수렴수열의 인덱스를 하나 이동해도 극한이 같음을 보이고 (b) 주어진 수열이 수렴한다는 가정 아래 극한을 구하라.','(a) Prove that shifting a convergent sequence by one preserves its limit; (b) assuming convergence of the given recurrence, find its limit.',[r'|a_n-L|<\varepsilon\ (n>N)\Rightarrow |a_{n+1}-L|<\varepsilon\ (n>N)',r'1/2\le a_n\le1,\quad L=1/(1+L)',r'L^2+L-1=0,\quad L>0'],r'\text{(a)}\ \lim a_{n+1}=\lim a_n;\quad\text{(b)}\ L=(\sqrt5-1)/2',sub='ab')
calc(77,r'5\le a_n\le8,\quad a_{n+1}\le a_n','극한의 존재와 가능한 값을 설명하라.','Explain existence and possible values of the limit.',[r'\text{decreasing and bounded below}\Rightarrow\text{convergent}',r'5\le\lim a_n\le8'],r'L\in[5,8]','주어진 조건만으로 정확한 값을 정할 수 없다.','The conditions do not determine a unique value.')
for q,eq,lines,ans in [(78,r'\cos n',[r'\cos1>\cos2>\cos3<\cos4',r'-1\le\cos n\le1'],r'\text{not monotonic; bounded}'),(79,r'1/(2n+3)',[r'a_{n+1}-a_n=-2/[(2n+5)(2n+3)]<0',r'0<a_n\le1/5'],r'\text{strictly decreasing; bounded}'),(80,r'(1-n)/(2+n)',[r'a_n=-1+3/(n+2)',r'-1<a_n\le0'],r'\text{strictly decreasing; bounded}'),(81,r'n(-1)^n',[r'a_{2k}=2k\to+\infty,\quad a_{2k-1}=-(2k-1)\to-\infty'],r'\text{not monotonic; unbounded}'),(82,r'2+(-1)^n/n',[r'a_1=1<a_2=5/2>a_3=5/3',r'1\le a_n\le5/2'],r'\text{not monotonic; bounded}'),(83,r'3-2ne^{-n}',[r"(xe^{-x})'=e^{-x}(1-x)<0\quad(x>1)",r'3-2/e\le a_n<3'],r'\text{strictly increasing; bounded}'),(84,r'n^3-3n+3',[r'a_{n+1}-a_n=3n^2+3n-2>0\quad(n\ge1)',r'a_1=1,\quad a_n\to+\infty'],r'\text{strictly increasing; unbounded above}')]:
 calc(q,'a_n='+eq,'증가·감소·비단조 중 하나로 분류하고 유계 여부를 판정하라.','Classify monotonicity and determine boundedness.',lines,ans)
calc(85,r'\sqrt2,\ \sqrt{2\sqrt2},\ \sqrt{2\sqrt{2\sqrt2}},\ldots','극한을 구하라.','Find the limit.',[r'a_1=\sqrt2,\quad a_{n+1}=\sqrt{2a_n}',r'a_n=2^{1-2^{-n}}\to2'],r'2','지수의 점화식으로 일반항을 귀납 확인한다.','Induction verifies the explicit formula through its exponent recurrence.')
calc(86,r'a_1=\sqrt2,\quad a_{n+1}=\sqrt{2+a_n}','(a) 증가하며 삼으로 위에서 유계임을 보여 수렴을 증명하고 (b) 극한을 구하라.','(a) Prove the sequence increases and is bounded above by three, hence converges; (b) find the limit.',[r'a_1<2,\quad a_n<2\Rightarrow a_{n+1}<2<3',r'a_2>a_1;\quad a_n>a_{n-1}\Rightarrow\sqrt{2+a_n}>\sqrt{2+a_{n-1}}',r'L=\sqrt{2+L},\quad L^2-L-2=0,\quad L>0'],r'\text{(a) increasing and bounded; (b)}\ L=2',sub='ab')
calc(87,r'a_1=1,\quad a_{n+1}=3-1/a_n','증가성과 삼보다 작음을 증명하고 수렴 및 극한을 구하라.','Prove increase and the upper bound three, then establish convergence and find the limit.',[r'1\le a_n<3\Rightarrow2\le a_{n+1}<3',r'a_2=2>a_1,\quad a_{n+1}-a_n=(a_n-a_{n-1})/(a_na_{n-1})>0',r'L=3-1/L,\quad L\ge1'],r'L=(3+\sqrt5)/2')
calc(88,r'a_1=2,\quad a_{n+1}=1/(3-a_n)','양수이며 이 이하인 감소수열임을 보이고 극한을 구하라.','Prove it is decreasing, positive and at most two, and find its limit.',[r'0<a_n\le2\Rightarrow1/3<a_{n+1}\le1',r'f(x)=1/(3-x)\text{ increases on }[0,2];\quad a_2=1<a_1',r'L=1/(3-L),\quad0\le L\le2'],r'L=(3-\sqrt5)/2')
calc(89,r'f_1=f_2=1,\quad a_n=f_{n+1}/f_n','(a) 첫 달 갓 태어난 한 쌍으로 시작하고 두 달 된 각 쌍부터 매달 새 한 쌍을 낳으며 죽지 않는 토끼 수를 피보나치 점화식으로 설명하라. (b) 비율의 점화식과 수렴을 가정한 극한을 구하라.','(a) Starting with one newborn pair, each pair breeds monthly from age two months and never dies. Explain the Fibonacci recurrence for the pair count. (b) Derive a ratio recurrence and its limit assuming convergence.',[r'\text{(a)}\ f_n=f_{n-1}+f_{n-2}',r'\text{(b)}\ a_{n-1}=1+1/a_{n-2}',r'1\le a_n\le2,\quad L=1+1/L'],r'\text{(a)}\ f_n=f_{n-1}+f_{n-2};\quad\text{(b)}\ L=(1+\sqrt5)/2','기존 쌍 수에 두 달 전부터 살아 있던 번식 가능한 쌍의 새끼 수를 더한다.','Add the previous population to the offspring from pairs already present two months earlier.',sub='ab')
x=1.
for j in range(100):x=math.cos(x)
calc(90,r'a_{n+1}=f(a_n),\quad f\text{ continuous}','(a) 수렴하면 극한은 고정점임을 증명하고 (b) 코사인 함수와 초기값 일로 그 극한을 소수 다섯 자리까지 구하라.','(a) Prove any limit is a fixed point; (b) illustrate using cosine with initial value one, finding the limit to five decimal places.',[r'a_n\to L\Rightarrow a_{n+1}\to L,\quad f(a_n)\to f(L)',r'f(x)=\cos x:\quad f([0,1])\subset[0,1],\quad |f^{\prime}(x)|\le\sin1<1'],rf'\text{{(a)}}\ f(L)=L;\quad\text{{(b)}}\ L\approx{x:.5f}','코사인 반복은 해당 구간에서 축소사상이라 실제 수렴한다.','Cosine iteration is a contraction on this interval, establishing convergence.',sub='ab')
calc(91,r'a_n=n^5/n!','(a) 그래프로 극한을 추측하고 (b) 오차 허용치가 각각 십분의 일과 천분의 일일 때 정의의 가장 작은 정수 기준을 구하라.','(a) Use a plot to predict the limit; (b) find the smallest integer cutoffs for tolerances one tenth and one thousandth.',[r'a_{n+1}/a_n=(1+1/n)^5/(n+1)<1/2\quad(n\ge5)',rf'a_9={9**5/math.factorial(9):.6f}>0.1>a_{{10}}={10**5/math.factorial(10):.6f}',rf'a_{{11}}={11**5/math.factorial(11):.6f}>0.001>a_{{12}}={12**5/math.factorial(12):.6f}',r'n>N\Rightarrow|a_n-0|<\varepsilon'],r'\text{(a)}\ 0;\quad\text{(b)}\ N=9\ (\varepsilon=0.1),\quad N=11\ (\varepsilon=0.001)',sub='ab')
dots(91,[('n^5/n!',[(j,j**5/math.factorial(j)) for j in range(1,19)])],0)
calc(92,r'|r|<1','엡실론 정의로 거듭제곱 수열의 영 수렴을 직접 증명하라.','Prove directly from the epsilon definition that the powers tend to zero.',[r'r=0\Rightarrow r^n=0',r'0<q=|r|<1,\quad N=\max\{0,\lceil\ln\varepsilon/\ln q\rceil\}',r'n>N\Rightarrow n\ln q<\ln\varepsilon\Rightarrow|r^n|<\varepsilon'],r'\lim r^n=0')
calc(93,r'\lim|a_n|=0','절댓값 수열이 영으로 수렴하면 원 수열도 영으로 수렴한다는 정리를 증명하라.','Prove that convergence of the absolute values to zero implies convergence of the sequence to zero.',[r'-|a_n|\le a_n\le|a_n|',r'\lim(-|a_n|)=\lim|a_n|=0'],r'\lim a_n=0','끼워넣기 정리의 두 경계 극한이 일치한다.','The two bounding limits coincide, so the squeeze theorem applies.')
calc(94,r'a_n>0,\quad a_n\to L,\quad p>0','연속함수에 대한 극한 정리를 이용해 거듭제곱 법칙을 증명하라.','Use the continuous-function limit theorem to prove the power law.',[r'L\ge0,\quad f(x)=|x|^p\text{ is continuous on }\mathbb R',r'f(a_n)=a_n^p\to f(L)=L^p'],r'\lim a_n^p=(\lim a_n)^p','절댓값 함수로 영인 극한과 비정수 지수도 포함한다.','Using the absolute-value function includes zero limits and noninteger powers.')
calc(95,r'a_n\to0,\quad\{b_n\}\text{ bounded}','곱 수열이 영으로 수렴함을 증명하라.','Prove that the product tends to zero.',[r'\exists M\ge1:\ |b_n|\le M',r'\forall\varepsilon>0\ \exists N:\ n>N\Rightarrow|a_n|<\varepsilon/M',r'n>N\Rightarrow|a_nb_n|\le M|a_n|<\varepsilon'],r'\lim a_nb_n=0')
calc(96,r'a_n=(1+1/n)^n','(a) 양수 두 수의 거듭제곱 차 몫을 위에서 평가하고 (b) 재배열한 부등식을 유도하라. (c) 적절한 대입으로 증가성을, (d) 짝수 항이 사 미만임을, (e) 모든 항이 사 미만임을 증명하고 (f) 극한 존재를 결론내려라.','(a) Bound a quotient of powers for two positive ordered numbers and (b) rearrange the inequality. (c) Substitute to establish increase, (d) bound the even terms by four, (e) bound all terms by four, and (f) conclude existence of the limit.',[r'\text{(a)}\ 0<a<b:\quad\frac{b^{n+1}-a^{n+1}}{b-a}=\sum_{j=0}^n a^jb^{n-j}<(n+1)b^n',r'\text{(b)}\ b^n[(n+1)a-nb]<a^{n+1}',r'\text{(c)}\ a=1+1/(n+1),\ b=1+1/n:\quad(n+1)a-nb=1\Rightarrow a_n<a_{n+1}',r'\text{(d)}\ a=1,\ b=1+1/(2n):\quad b^n/2<1\Rightarrow a_{2n}=b^{2n}<4',r'\text{(e)}\ a_n\le a_{2n}<4',r'\text{(f) increasing and bounded implies convergence}'],r'\lim_{n\to\infty}(1+1/n)^n\text{ exists }(=e)','거듭제곱 차 전개에서 첫 항만 상계와 같고 나머지는 작아서 엄격한 부등식이다.','In the power-difference sum only the first term equals its bound; all others are smaller.',sub='abcdef')
calc(97,r'a>b>0,\quad a_1=(a+b)/2,\ b_1=\sqrt{ab},\quad a_{n+1}=(a_n+b_n)/2,\ b_{n+1}=\sqrt{a_nb_n}','(a) 두 수열 사이의 엄격한 부등식 (b) 각각의 수렴 (c) 극한의 일치를 증명하라.','Prove (a) the strict ordering of successive means, (b) convergence of both sequences, and (c) equality of their limits.',[r'a_n>b_n>0\Rightarrow a_n>(a_n+b_n)/2>\sqrt{a_nb_n}>b_n',r'a_n\downarrow A\ge b_1,\quad b_n\uparrow B\le a_1',r'A=(A+B)/2\Rightarrow A=B'],r'\text{(a)}\ a_n>a_{n+1}>b_{n+1}>b_n;\quad\text{(b,c)}\ a_n,b_n\to\operatorname{AGM}(a,b)','산술·기하 평균 부등식과 단조유계 정리를 적용한다.','Apply the strict arithmetic-geometric mean inequality and bounded monotone convergence.',sub='abc')
pell=[S.Integer(1)]
for j in range(7):pell.append(1+1/(1+pell[-1]))
calc(98,r'a_1=1,\quad a_{n+1}=1+1/(1+a_n)','(a) 짝수·홀수 부분수열의 극한이 같으면 전체 수열도 같은 값으로 수렴함을 증명하라. (b) 주어진 점화식의 처음 여덟 항을 구하고 그 사실로 제곱근 이의 연분수를 정당화하라.','(a) Prove that equal limits of the even and odd subsequences imply the same limit for the full sequence. (b) Find eight terms of the recurrence and use part (a) to justify its continued fraction for the square root of two.',[r'\text{(a)}\ k>K\Rightarrow|a_{2k}-L|,|a_{2k+1}-L|<\varepsilon;\quad n>2K+2\Rightarrow|a_n-L|<\varepsilon',r'\text{(b)}\ '+r',\ '.join(S.latex(v) for v in pell),r'f(x)=(x+2)/(x+1),\quad f^2(x)=(3x+4)/(2x+3)',r'f^2(x)-x=2(2-x^2)/(2x+3)',r'a_{2k-1}\uparrow\sqrt2,\quad a_{2k}\downarrow\sqrt2'],r'\text{(a)}\ a_n\to L;\quad\text{(b)}\ a_n\to\sqrt2=1+\frac1{2+\frac1{2+\cdots}}','합성함수는 양의 구간에서 증가하며 제곱근 이의 양쪽을 보존한다. 각 단조 부분수열의 양의 고정점은 제곱근 이이다.','The composite map increases on the positive interval and preserves each side of the square root of two. Each monotone subsequence must converge to its positive fixed point.',sub='ab')
calc(99,r'p_{n+1}=bp_n/(a+p_n),\quad a,b,p_0>0','(a) 수렴할 경우 가능한 극한 (b) 기하급수 비교 부등식 (c) 첫 매개변수가 더 클 때 멸종 (d) 둘째 매개변수가 더 클 때 평형 양쪽에서의 단조성과 장기 극한을 증명하라.','Prove (a) the possible limits under convergence, (b) a geometric comparison, (c) extinction when the first parameter is larger, and (d) monotonicity on each side of the positive equilibrium and the long-term limit when the second parameter is larger.',[r'\text{(a)}\ L=bL/(a+L)\Rightarrow L=0\text{ or }b-a',r'\text{(b)}\ p_{n+1}<(b/a)p_n',r'\text{(c)}\ a>b:\quad0<p_n<(b/a)^np_0\to0',r'\text{(d)}\ K=b-a>0,\quad F(p)-p=p(K-p)/(a+p),\quad F(p)-K=a(p-K)/(a+p)',r'0<p_0<K\Rightarrow p_n\uparrow L\in[p_0,K];\quad p_0>K\Rightarrow p_n\downarrow L\ge K',r'L>0\Rightarrow L=K;\quad p_0=K\Rightarrow p_n=K'],r'\text{(a)}\ L\in\{0,b-a\};\quad\text{(b)}\ p_{n+1}<(b/a)p_n;\quad\text{(c)}\ L=0;\quad\text{(d)}\ L=b-a','양수 영역을 보존하므로 모든 분모가 양수이다. 평형 아래에서 시작해도 극한이 초기값 이상이어서 영인 후보를 제외한다.','Positivity is preserved, so all denominators remain positive. Starting below equilibrium still gives a limit at least the initial value, excluding zero.',sub='abcd')
items.sort(key=lambda e:e['number']);assert [e['number'] for e in items]==list(range(1,100))
raw={'section':'11.1','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[773,774,775,776],'pdfPages':[810,811,812,813]},'scope':{'kind':'exercise','numbers':list(range(1,100)),'total':99,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s11-1.json')
for ex in items:
 for key in ['statement','answer']:
  assert re.findall(r'\\\((.*?)\\\)',ex[key]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[key]['en']),(ex['number'],key)
 for field in ['statement','hint','steps','answer','check']:
  st=json.dumps(ex[field],ensure_ascii=False);assert not any(ord(c)<32 for c in st)
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure' in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
assert S.limit(n-S.sqrt(n+1)*S.sqrt(n+3),n,S.oo)==-2
assert S.simplify(pell[-1]-S.Rational(577,408))==0
for eps,cut in [(.1,9),(.001,11)]:
 assert cut**5/math.factorial(cut)>=eps
 assert all(j**5/math.factorial(j)<eps for j in range(cut+1,60))
assert abs(x-math.cos(x))<1e-15
(BASE/'exercise-content/s11-1.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('11.1:',len(items),'cards;',sum('figure'in e for e in items),'SVG; schema, formulas, XML, recurrence and limit checks passed')
