import json,math,html,sys,re
from pathlib import Path
import sympy as S
BASE=Path(__file__).resolve().parents[1];items=[];n=S.symbols('n',integer=True,positive=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(q,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=802 if q<=24 else 803
 items.append(dict(id=f'stewart9-exercise-11.4-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('비교 판정법','Comparison tests'),statement=bi(sk,se),hint=bi('일반항과 부분합을 구별하고 등비급수·소거합·일반항의 영 수렴 조건을 살펴본다.','Distinguish terms from partial sums and examine geometric sums, telescoping, and the zero-term condition.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if k:steps.append((k,e))
 add(q,M(eq)+' '+tk,M(eq)+' '+te,steps,M(ans),M(ans),'초기항·정의역과 극한 논증의 조건을 확인했다.','Initial terms, domain, and conditions of the limit argument were checked.',sub)
def dots(q,sets,limit=None):
 pts=[(i,v) for label,values in sets for i,v in values];xmin=0;xmax=max(i for i,v in pts)+1;lo=min(v for i,v in pts);hi=max(v for i,v in pts)
 if limit is not None:lo=min(lo,limit);hi=max(hi,limit)
 pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad;X=lambda x:55+510*(x-xmin)/(xmax-xmin);Y=lambda y:300-250*(y-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 390"><rect width="620" height="390" fill="white"/><path d="M55 40V300H575" stroke="#8492a5" fill="none"/>',f'<text x="55" y="25" font-size="15">Sequence {q}: discrete terms</text>']
 for j,(label,values) in enumerate(sets):
  c=['#1463c2','#c64c38','#159568'][j%3]
  for i,v in values:out.append(f'<circle cx="{X(i):.3f}" cy="{Y(v):.3f}" r="3" fill="{c}"/>')
  out.append(f'<text x="55" y="{337+17*j}" fill="{c}" font-size="12">{html.escape(label)}</text>')
 if limit is not None:out.append(f'<path d="M55 {Y(limit)}H575" stroke="#65758d" stroke-dasharray="5 5"/><text x="570" y="{Y(limit)-5}" font-size="10">L={limit:.5g}</text>')
 for i in range(6):
  v=lo+(hi-lo)*i/5;out.append(f'<text x="5" y="{Y(v)+4}" font-size="10">{v:.4g}</text>')
 for i in [1,int(xmax/2),int(xmax)-1]:out.append(f'<text x="{X(i)}" y="318" font-size="11">{i}</text>')
 out.append('</svg>');p=BASE/f'exercise-content/assets/s11-4-{q}.svg';p.write_text(''.join(out));ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('정수 인덱스에 대응하는 수열의 점 그래프','Discrete sequence values at integer indices'),'caption':bi('자체 계산한 항을 점으로 표시했다. 선으로 연결하지 않았다.','Original computed terms shown as discrete points.')}
calc(1,r'a_n,b_n>0,\quad\sum b_n\text{ converges}','(a) 첫 수열의 항이 더 클 때 (b) 더 작을 때 급수에 대해 무엇을 결론낼 수 있는지 설명하라.','Explain the conclusion for the first series when its terms are (a) larger and (b) smaller.',[r'\text{(a)}\ b_n=1/(2n^2):\quad a_n=1/n^2\text{ converges},\quad a_n=1/n\text{ diverges}',r'\text{(b)}\ 0<a_n<b_n\Rightarrow\sum a_n\text{ converges}'],r'\text{(a) inconclusive; (b) convergent}',sub='ab')
calc(2,r'a_n,b_n>0,\quad\sum b_n\text{ diverges}','(a) 첫 수열의 항이 더 클 때 (b) 더 작을 때 급수에 대해 무엇을 결론낼 수 있는지 설명하라.','Explain the conclusion for the first series when its terms are (a) larger and (b) smaller.',[r'\text{(a)}\ a_n>b_n>0\Rightarrow\sum a_n\text{ diverges}',r'\text{(b)}\ b_n=2/n:\quad a_n=1/n\text{ diverges},\quad a_n=1/n^2\text{ converges}'],r'\text{(a) divergent; (b) inconclusive}',sub='ab')
calc(3,r'\text{(a)}\sum_{n=2}^\infty\frac n{n^3+5};\quad\text{(b)}\sum_{n=2}^\infty\frac n{n^3-5}','역제곱 급수와 비교하여 (a) 직접 비교 (b) 극한 비교로 수렴을 증명하라.','Compare with the inverse-square series using (a) direct comparison and (b) limit comparison.',[r'\text{(a)}\ 0<n/(n^3+5)<1/n^2',r'\text{(b)}\ a_n>0\ (n\ge2),\quad\lim\frac{n/(n^3-5)}{1/n^2}=\lim\frac{n^3}{n^3-5}=1'],r'\text{both converge}',sub='ab')
calc(4,r'\text{(a)}\sum_{n=2}^\infty\frac{n^2+n}{n^3-2};\quad\text{(b)}\sum_{n=2}^\infty\frac{n^2-n}{n^3+2}','조화급수와 비교하여 (a) 직접 비교 (b) 극한 비교로 발산을 증명하라.','Compare with the harmonic series using (a) direct comparison and (b) limit comparison.',[r'\text{(a)}\ (n^2+n)/(n^3-2)>1/n\quad(n\ge2)',r'\text{(b)}\lim\frac{(n^2-n)/(n^3+2)}{1/n}=\lim\frac{n^3-n^2}{n^3+2}=1'],r'\text{both diverge}',sub='ab')
calc(5,r'a_n=n/(n^3+1)','다음 비교 중 수렴을 증명하는 것을 고르라: (a) 분자 일을 가진 같은 분모보다 큼 (b) 조화급수 항보다 작음 (c) 역제곱 항보다 작음.','Choose the comparison that proves convergence: (a) larger than the same denominator with unit numerator, (b) smaller than a harmonic term, or (c) smaller than an inverse-square term.',[r'\text{(a)}\ a_n\ge1/(n^3+1);\quad\text{(b)}\ a_n\le1/n;\quad\text{(c)}\ a_n\le1/n^2',r'\sum1/n^2\text{ converges}'],r'\text{(c)}','수렴급수의 항보다 작다는 방향이 필요하다.','The useful direction is an upper bound by a convergent series.',sub='abc')
calc(6,r'a_n=n/(n^2+1)','다음 비교 중 발산을 증명하는 것을 고르라: (a) 분자 일을 가진 같은 분모보다 큼 (b) 조화급수 항보다 작음 (c) 조화급수 항의 절반보다 큼.','Choose the comparison proving divergence: (a) larger than the same denominator with unit numerator, (b) smaller than a harmonic term, or (c) larger than half a harmonic term.',[r'\text{(a)}\ a_n\ge1/(n^2+1);\quad\text{(b)}\ a_n\le1/n;\quad\text{(c)}\ a_n\ge1/(2n)',r'n^2+1\le2n^2\quad(n\ge1)'],r'\text{(c)}','발산급수의 양의 항보다 크다는 방향이 필요하다.','Use a lower bound by a divergent positive series.',sub='abc')
rows=[(7,r'1/(n^3+8)',1,[r'0<a_n\le1/n^3,\quad p=3>1'],True),(8,r'1/(\sqrt n-1)',2,[r'a_n>1/\sqrt n,\quad p=1/2<1'],False),(9,r'(n+1)/(n\sqrt n)',1,[r'a_n\ge1/\sqrt n,\quad p=1/2<1'],False),(10,r'(n-1)/(n^3+1)',1,[r'0\le a_n\le1/n^2,\quad p=2>1'],True),(11,r'9^n/(3+10^n)',1,[r'0<a_n<(9/10)^n,\quad9/10<1'],True),(12,r'6^n/(5^n-1)',1,[r'a_n>(6/5)^n\to\infty'],False),(13,r'1/\ln n',2,[r'\ln n<n\Rightarrow a_n>1/n'],False),(14,r'n\sin^2n/(1+n^3)',1,[r'0\le a_n\le n/n^3=1/n^2'],True),(15,r'\sqrt[3]n/\sqrt{n^3+4n+3}',1,[r'0<a_n\le n^{1/3}/n^{3/2}=n^{-7/6},\quad7/6>1'],True),(16,r'(2n-1)(n^2-1)/[(n+1)(n^2+4)^2]',1,[r'a_1=0,\quad a_n>0\ (n\ge2)',r'\lim a_n/(1/n^2)=2'],True),(17,r'(1+\cos n)/e^n',1,[r'0\le a_n\le2e^{-n}'],True),(18,r'1/\sqrt[3]{3n^4+1}',1,[r'a_n\le3^{-1/3}n^{-4/3},\quad4/3>1'],True),(19,r'4^{n+1}/(3^n-2)',1,[r'a_n>4(4/3)^n\to\infty'],False),(20,r'1/n^n',1,[r'n\ge2\Rightarrow0<a_n\le2^{-n}'],True),(21,r'1/\sqrt{n^2+1}',1,[r'\lim a_n/(1/n)=\lim1/\sqrt{1+1/n^2}=1'],False),(22,r'2/(\sqrt n+2)',1,[r'\lim a_n/(1/\sqrt n)=2'],False),(23,r'(n+1)/(n^3+n)',1,[r'\lim a_n/(1/n^2)=1'],True),(24,r'(n^2+n+1)/(n^4+n^2)',1,[r'\lim a_n/(1/n^2)=1'],True),(25,r'\sqrt{1+n}/(2+n)',1,[r'\lim a_n/(1/\sqrt n)=1'],False),(26,r'(n+2)/(n+1)^3',3,[r'\lim a_n/(1/n^2)=1'],True),(27,r'(5+2n)/(1+n^2)^2',1,[r'\lim a_n/(1/n^3)=2'],True),(28,r'(n+3^n)/(n+2^n)',1,[r'a_n/(3/2)^n=[1+n/3^n]/[1+n/2^n]\to1',r'a_n\to\infty'],False),(29,r'(e^n+1)/(ne^n+1)',1,[r'\lim a_n/(1/n)=\lim(n+ne^{-n})/(n+e^{-n})=1'],False),(30,r'1/[n\sqrt{n^2-1}]',2,[r'\lim a_n/(1/n^2)=\lim1/\sqrt{1-1/n^2}=1'],True),(31,r'(2+\sin n)/n^2',1,[r'0<a_n\le3/n^2'],True),(32,r'(n^2+\cos^2n)/n^3',1,[r'a_n\ge1/n'],False),(33,r'(1+1/n)^2e^{-n}',1,[r'0<a_n\le4e^{-n}'],True),(34,r'e^{1/n}/n',1,[r'a_n>1/n'],False),(35,r'1/n!',1,[r'n!\ge2^{n-1}\quad(n\ge1)',r'1/n!\le2^{1-n}'],True),(36,r'n!/n^n',1,[r'a_n=\prod_{k=1}^n(k/n)\le2^{-\lfloor n/2\rfloor}',r'\sum_{n=1}^\infty2^{-\lfloor n/2\rfloor}=1+2\sum_{k=1}^\infty2^{-k}=3'],True),(37,r'\sin(1/n)',1,[r'\lim\sin(1/n)/(1/n)=1'],False),(38,r'\sin^2(1/n)',1,[r'0<\sin^2(1/n)\le1/n^2'],True),(39,r'\tan(1/n)/n',1,[r'\lim a_n/(1/n^2)=\lim\tan(1/n)/(1/n)=1'],True),(40,r'1/n^{1+1/n}',1,[r'\lim a_n/(1/n)=\lim n^{-1/n}=1'],False)]
for q,term,start,lines,conv in rows:calc(q,rf'\sum_{{n={start}}}^\infty {term}','수렴·발산을 판정하고 비교 근거를 제시하라.','Determine convergence or divergence and provide the comparison.',lines,r'\text{convergent}'if conv else r'\text{divergent}','직접 비교는 유한한 초기 항을 제외한 비음수 항에, 극한 비교는 양의 항과 양의 유한 비율 극한에 적용한다.','Direct comparisons use nonnegative tails; limit comparisons use positive tails and a positive finite ratio limit.')
for q,eq,fun,bound,line in [(41,r'1/(5+n^5)',lambda j:1/(5+j**5),1/(4*10**4),r'a_n<n^{-5}\Rightarrow R_{10}<\int_{10}^\infty x^{-5}\,dx=1/(4\cdot10^4)'),(42,r'e^{1/n}/n^4',lambda j:math.exp(1/j)/j**4,math.exp(.1)/(3*10**3),r'n>10:\ e^{1/n}<e^{1/10}\Rightarrow R_{10}<e^{1/10}\int_{10}^\infty x^{-4}\,dx=e^{1/10}/3000'),(43,r'5^{-n}\cos^2n',lambda j:5**(-j)*math.cos(j)**2,1/(4*5**10),r'R_{10}\le\sum_{n=11}^\infty5^{-n}=1/(4\cdot5^{10})'),(44,r'1/(3^n+4^n)',lambda j:1/(3**j+4**j),1/(3*4**10),r'R_{10}<\sum_{n=11}^\infty4^{-n}=1/(3\cdot4^{10})')]:
 sm=sum(fun(j)for j in range(1,11));calc(q,rf'\sum_{{n=1}}^\infty {eq}','처음 열 항의 합으로 근사하고 오차를 평가하라.','Approximate with the first ten terms and estimate the error.',[rf's_{{10}}={sm:.12f}',line],rf'S\approx{sm:.12f},\quad0<R_{{10}}\le{bound:.12f}','표시한 오차 상계는 정확식으로 해석한다. 양수 항이므로 부분합은 참합보다 작다.','Use the displayed exact bound in the derivation; positive terms make the partial sum an underestimate.')
calc(45,r'\sum_{n=1}^\infty d_n/10^n,\quad d_n\in\{0,1,\ldots,9\}','모든 십진 숫자 선택에 대해 급수가 수렴함을 증명하라.','Prove convergence for every choice of decimal digits.',[r'0\le d_n/10^n\le9/10^n',r'\sum_{n=1}^\infty9/10^n=1'],r'\text{convergent with sum in }[0,1]')
calc(46,r'\sum_{n=2}^\infty1/(n^p\ln n)','수렴하는 모든 실수 매개변수를 구하라.','Find all real parameter values giving convergence.',[r'p>1,\ n\ge3:\quad1/(n^p\ln n)\le1/n^p',r'p\le1:\quad1/(n^p\ln n)\ge1/(n\ln n)',r'\int_2^\infty dx/(x\ln x)=\infty'],r'p>1')
calc(47,r'\sum_{n=2}^\infty1/(\ln n)^{\ln\ln n}','로그·지수 표현으로 조화급수와 비교하여 발산을 증명하라.','Use logarithmic and exponential forms to compare with the harmonic series and prove divergence.',[r'(\ln n)^{\ln\ln n}=e^{(\ln\ln n)^2}',r'\ln y<\sqrt y\quad(y\ge1)',r'n\ge3:\quad0<\ln\ln n<\sqrt{\ln n}\Rightarrow e^{(\ln\ln n)^2}<n',r'a_n>1/n\quad(n\ge3)'],r'\text{divergent}')
calc(48,r'a_n,b_n>0,\quad\sum b_n\text{ converges},\quad a_n/b_n\to0','(a) 첫 급수의 수렴을 증명하고 (b) 로그 나누기 세제곱 급수 및 일 빼기 역제곱의 코사인 급수에 적용하라.','(a) Prove convergence of the first series, then (b) apply the result to logarithm over a cube and one minus the cosine of an inverse square.',[r'\text{(a)}\ a_n/b_n<1\text{ eventually}\Rightarrow a_n<b_n',r'\text{(b)(i)}\ a_n=\ln n/n^3,\ b_n=1/n^2:\quad a_n/b_n=\ln n/n\to0',r'\text{(b)(ii)}\ a_n=1-\cos(1/n^2),\ b_n=1/n^2',r'a_n/b_n=n^2\cdot2\sin^2(1/(2n^2))\le1/(2n^2)\to0'],r'\text{(a) theorem proved; (b)(i),(ii) convergent}','첫 로그 항이 영인 경우는 유한한 예외로 제외하고 양의 꼬리에 정리를 적용한다.','Discard the single zero logarithm term and apply the theorem to the positive tail.',sub='ab')
calc(49,r'a_n,b_n>0,\quad\sum b_n\text{ diverges},\quad a_n/b_n\to+\infty','(a) 첫 급수의 발산을 증명하고 (b) 로그의 역수 급수 및 로그 나누기 인덱스 급수에 적용하라.','(a) Prove divergence of the first series, then (b) apply the result to reciprocal logarithms and logarithm divided by the index.',[r'\text{(a)}\ a_n/b_n>1\text{ eventually}\Rightarrow a_n>b_n',r'\text{(b)(i)}\ a_n=1/\ln n,\ b_n=1/n:\quad n/\ln n\to\infty',r'\text{(b)(ii)}\ a_n=\ln n/n,\ b_n=1/n:\quad\ln n\to\infty'],r'\text{(a) theorem proved; (b)(i),(ii) divergent}',sub='ab')
calc(50,r'a_n,b_n>0,\quad a_n/b_n\to0','두 번째 급수는 발산하지만 첫 번째는 수렴하는 예를 들어라.','Give an example where the second series diverges but the first converges.',[r'a_n=1/n^2,\quad b_n=1/n',r'a_n/b_n=1/n\to0;\quad p_a=2>1,\quad p_b=1'],r'a_n=1/n^2,\quad b_n=1/n')
calc(51,r'a_n>0,\quad\lim na_n=L\ne0','급수의 발산을 증명하라.','Prove divergence of the series.',[r'L>0:\quad\lim a_n/(1/n)=L\Rightarrow\text{limit comparison}',r'L=+\infty:\quad a_n>1/n\text{ eventually}'],r'\sum a_n\text{ diverges}','가정의 극한은 존재한다고 읽으며 무한대인 경우도 별도로 포함한다.','The stated limit is assumed to exist; the positive-infinity case is included separately.')
calc(52,r'a_n>0,\quad\sum a_n\text{ converges}','일 더하기 항의 로그 급수가 수렴함을 증명하라.','Prove convergence of the series of logarithms of one plus the terms.',[r'0<\ln(1+x)=\int_0^xdt/(1+t)\le x\quad(x>0)',r'0<\ln(1+a_n)\le a_n'],r'\sum\ln(1+a_n)\text{ converges}')
calc(53,r'a_n>0,\quad\sum a_n\text{ converges}','항의 사인으로 만든 급수도 수렴하는지 판정하라.','Determine whether the series of sines of the terms also converges.',[r'|\sin a_n|\le a_n',r'\sum|\sin a_n|\le\sum a_n<\infty'],r'\text{yes, absolutely convergent}','초기 항의 사인이 음수여도 절댓값 비교가 성립한다.','Absolute-value comparison remains valid even if some initial sine values are negative.')
calc(54,r'a_n\ge0,\quad\sum a_n\text{ converges}','항 제곱의 급수가 수렴함을 증명하라.','Prove convergence of the squared-term series.',[r'a_n\to0\Rightarrow0\le a_n\le1\text{ eventually}',r'0\le a_n^2\le a_n\text{ eventually}'],r'\sum a_n^2\text{ converges}')
calc(55,r'a_n,b_n>0','항별 곱 급수에 대해 판정하라: (a) 두 원래 급수가 발산하면 곱도 발산한다 (b) 첫째 수렴·둘째 발산이면 곱도 발산한다 (c) 둘 다 수렴하면 곱도 수렴한다. 거짓이면 반례를 제시하라.','Decide the claims for the termwise-product series: (a) two divergent series give a divergent product, (b) one convergent and one divergent series give a divergent product, and (c) two convergent series give a convergent product. Give counterexamples to false claims.',[r'\text{(a)}\ a_n=b_n=1/n:\quad\sum a_nb_n=\sum1/n^2\text{ converges}',r'\text{(b)}\ a_n=1/n^2,\ b_n=1:\quad\sum a_nb_n=\sum1/n^2\text{ converges}',r'\text{(c)}\ b_n\to0\Rightarrow b_n\le1\text{ eventually}\Rightarrow0<a_nb_n\le a_n'],r'\text{(a) false; (b) false; (c) true}',sub='abc')
items.sort(key=lambda e:e['number']);assert [e['number']for e in items]==list(range(1,56))
raw={'section':'11.4','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[802,803],'pdfPages':[839,840]},'scope':{'kind':'exercise','numbers':list(range(1,56)),'total':55,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s11-4.json')
for ex in items:
 for key in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[key]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[key]['en']),(ex['number'],key)
for expr,b,lim in [((2*n-1)*(n*n-1)/((n+1)*(n*n+4)**2),1/n**2,2),((n+1)/(n**3+n),1/n**2,1),((n*n+n+1)/(n**4+n*n),1/n**2,1),((5+2*n)/(1+n*n)**2,1/n**3,2),((S.exp(n)+1)/(n*S.exp(n)+1),1/n,1)]:assert S.limit(expr/b,n,S.oo)==lim
for j in range(1,40):assert math.factorial(j)/j**j<=2**(-math.floor(j/2))+1e-15
(BASE/'exercise-content/s11-4.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('11.4: 55 cards; source, schema, bilingual formulas, comparison ratios and factorial bounds verified')
