import json,math,html,sys,re
from pathlib import Path
import sympy as S
BASE=Path(__file__).resolve().parents[1];items=[];n=S.symbols('n',integer=True,positive=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(q,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=785 if q<=8 else 786 if q<=55 else 787 if q<=78 else 788 if q<=93 else 789
 items.append(dict(id=f'stewart9-exercise-11.2-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('급수','Series'),statement=bi(sk,se),hint=bi('일반항과 부분합을 구별하고 등비급수·소거합·일반항의 영 수렴 조건을 살펴본다.','Distinguish terms from partial sums and examine geometric sums, telescoping, and the zero-term condition.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if k:steps.append((k,e))
 add(q,M(eq)+' '+tk,M(eq)+' '+te,steps,M(ans),M(ans),'초기항·정의역과 극한 논증의 조건을 확인했다.','Initial terms, domain, and conditions of the limit argument were checked.',sub)
def dots(q,sets,limit=None):
 pts=[(i,v) for label,values in sets for i,v in values];xmin=0;xmax=max(i for i,v in pts)+1;lo=min(v for i,v in pts);hi=max(v for i,v in pts)
 if limit is not None:lo=min(lo,limit);hi=max(hi,limit)
 pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad;X=lambda x:55+510*(x-xmin)/(xmax-xmin);Y=lambda y:300-250*(y-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 390"><rect width="620" height="390" fill="white"/><path d="M55 40V300H575" stroke="#8492a5" fill="none"/>',f'<text x="55" y="25" font-size="15">Sequence {q}: discrete terms</text>']
 for j,(label,values) in enumerate(sets):
  c=['#1463c2','#c64c38','#159568'][j%3]
  for i,v in values:out.append(f'<circle cx="{X(i):.3f}" cy="{Y(v):.3f}" r="3" fill="{c}"/>')
  out.append(f'<text x="55" y="{337+17*j}" fill="{c}" font-size="12">{html.escape(label)}</text>')
 if limit is not None:out.append(f'<path d="M55 {Y(limit)}H575" stroke="#65758d" stroke-dasharray="5 5"/><text x="570" y="{Y(limit)-5}" font-size="10">L={limit:.5g}</text>')
 for i in range(6):
  v=lo+(hi-lo)*i/5;out.append(f'<text x="5" y="{Y(v)+4}" font-size="10">{v:.4g}</text>')
 for i in [1,int(xmax/2),int(xmax)-1]:out.append(f'<text x="{X(i)}" y="318" font-size="11">{i}</text>')
 out.append('</svg>');p=BASE/f'exercise-content/assets/s11-2-{q}.svg';p.write_text(''.join(out));ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('정수 인덱스에 대응하는 수열의 점 그래프','Discrete sequence values at integer indices'),'caption':bi('자체 계산한 항을 점으로 표시했다. 선으로 연결하지 않았다.','Original computed terms shown as discrete points.')}
calc(1,r'\{a_n\},\quad\sum_{n=1}^\infty a_n','(a) 수열과 급수의 차이 (b) 급수의 수렴과 발산을 정의하라.','Define (a) the difference between a sequence and a series and (b) convergence and divergence of a series.',[r'\{a_n\}:\text{ ordered terms};\quad s_N=\sum_{n=1}^N a_n',r'\sum a_n\text{ converges iff }s_N\to S\in\mathbb R'],r'\text{series convergence means a finite limit of partial sums}','항 수열 자체의 극한과 부분합 수열의 극한을 구별한다.','Distinguish the limit of individual terms from the limit of their partial sums.',sub='ab')
calc(2,r'\sum_{n=1}^\infty a_n=5','이 등식의 뜻을 정의로 설명하라.','Explain this equality using the definition.',[r's_N=a_1+\cdots+a_N',r'\forall\varepsilon>0\ \exists K:\ N>K\Rightarrow|s_N-5|<\varepsilon'],r'\lim_{N\to\infty}s_N=5')
for q,eq,line,ans in [(3,r's_n=2-3(0.8)^n',r'(0.8)^n\to0','2'),(4,r's_n=(n^2-1)/(4n^2+1)',r's_n=(1-1/n^2)/(4+1/n^2)','1/4')]:calc(q,eq,'주어진 부분합으로 급수의 합을 구하라.','Find the series sum from its partial sums.',[line],r'\sum a_n='+ans)
for q,expr,conclusion,proof in [(5,1/n**3,'convergent',r'0<1/n^3\le1/[n(n-1)]\quad(n\ge2)'),(6,n**(-S.Rational(1,3)),'divergent',r'n^{-1/3}\ge1/n'),(7,S.sin(n),'divergent',r'\sin n\not\to0'),(8,(-1)**n*n,'divergent',r'|a_n|=n\not\to0'),(9,1/(n**4+n*n),'convergent',r'0<a_n\le1/n^2\le1/[n(n-1)]\quad(n\ge2)'),(10,(-1)**(n-1)/S.factorial(n),'convergent',r'|a_{n+1}|/|a_n|=1/(n+1)\le1/2')]:
 vals=[];su=0.
 for j in range(1,9):su+=float(expr.subs(n,j));vals.append(su)
 calc(q,rf'\sum_{{n=1}}^\infty {S.latex(expr)}','처음 여덟 부분합을 소수 넷째 자리까지 계산하고 수렴·발산을 예상하라.','Compute eight partial sums to four decimal places and predict convergence or divergence.',[r's_k=\sum_{n=1}^ka_n',r's_1,\ldots,s_8='+r',\ '.join(f'{v:.4f}'for v in vals),proof],r'\text{'+conclusion+r'}','유한 부분합은 추측을 제공하며 마지막 비교 또는 일반항 검사로 이를 뒷받침한다.','Finite sums suggest behavior; the final comparison or term check supports that prediction.')
for q,expr,lines,ans,lim in [(11,6/(-3)**n,[r'a_1=-2,\quad r=-1/3,\quad s_N=-\frac32[1-(-1/3)^N]'],r'-3/2',-1.5),(12,S.cos(n),[r'\cos n\not\to0'],r'\text{divergent}',None),(13,n/S.sqrt(n*n+4),[r'a_n=1/\sqrt{1+4/n^2}\to1\ne0'],r'\text{divergent}',None),(14,7**(n+1)/10**n,[r'a_1=49/10,\quad r=7/10,\quad s_N=\frac{49}3[1-(7/10)^N]'],r'49/3',49/3)]:
 vals=[float(expr.subs(n,j))for j in range(1,21)];partial=[];su=0
 for v in vals:su+=v;partial.append(su)
 calc(q,rf'\sum_{{n=1}}^\infty {S.latex(expr)}','최소 열 부분합을 계산하고 항과 부분합을 같은 그림에 나타내어 수렴 여부 및 가능한 합을 구하라.','Calculate at least ten partial sums, plot terms and sums together, and determine convergence and any sum.',[r's_1,\ldots,s_{10}='+r',\ '.join(f'{v:.4f}'for v in partial[:10])]+lines,ans,'일반항이 영으로 가지 않으면 급수는 발산한다. 등비급수는 공비의 절댓값이 일보다 작아야 한다.','A series diverges if its terms fail to tend to zero. A geometric series requires ratio magnitude less than one.')
 dots(q,[('terms',list(enumerate(vals,1))),('partial sums',list(enumerate(partial,1)))],lim)
calc(15,r'a_n=2n/(3n+1)','(a) 항 수열과 (b) 급수의 수렴을 각각 판정하라.','Determine convergence of (a) the term sequence and (b) its series.',[r'a_n=2/(3+1/n)\to2/3\ne0'],r'\text{(a) converges to }2/3;\quad\text{(b) divergent}',sub='ab')
calc(16,r'\text{(a)}\ \sum_{i=1}^na_i,\ \sum_{j=1}^na_j;\quad\text{(b)}\ \sum_{i=1}^na_i,\ \sum_{i=1}^na_j','각 쌍의 차이를 설명하라.','Explain the difference within each pair.',[r'\text{(a) both equal }a_1+\cdots+a_n',r'\text{(b)}\ \sum_{i=1}^na_j=na_j\quad(j\text{ fixed})'],r'\text{(a) identical; (b) varying-index sum versus }na_j','합의 인덱스는 묶인 변수이지만 다른 첨자는 외부의 고정된 변수이다.','The summation index is a bound variable; a different subscript is fixed externally.',sub='ab')
tele=[(17,r'\sum_{n=1}^\infty(1/(n+2)-1/n)',[r's_N=-1-1/2+1/(N+1)+1/(N+2)'],r'-3/2'),(18,r'\sum_{n=4}^\infty(1/\sqrt n-1/\sqrt{n+1})',[r'\sum_{n=4}^N a_n=1/2-1/\sqrt{N+1}'],r'1/2'),(19,r'\sum_{n=1}^\infty3/[n(n+3)]',[r'a_n=1/n-1/(n+3)',r's_N=1+1/2+1/3-1/(N+1)-1/(N+2)-1/(N+3)'],r'11/6'),(20,r'\sum_{n=1}^\infty\ln[n/(n+1)]',[r's_N=\ln\prod_{n=1}^Nn/(n+1)=-\ln(N+1)\to-\infty'],r'\text{divergent}'),(21,r'\sum_{n=1}^\infty(e^{1/n}-e^{1/(n+1)})',[r's_N=e-e^{1/(N+1)}'],r'e-1'),(22,r'\sum_{n=2}^\infty1/(n^3-n)',[r'\frac1{n^3-n}=\frac12\left[\frac1{n(n-1)}-\frac1{n(n+1)}\right]',r'\sum_{n=2}^N a_n=1/4-1/[2N(N+1)]'],r'1/4')]
for q,eq,lines,ans in tele:calc(q,eq,'부분합의 상쇄로 수렴·발산을 판정하고 수렴하면 합을 구하라.','Telescope partial sums to determine convergence and any sum.',lines,ans)
geo=[(23,r'3-4+16/3-64/9+\cdots',S.Integer(3),-S.Rational(4,3)),(24,r'4+3+9/4+27/16+\cdots',S.Integer(4),S.Rational(3,4)),(25,r'10-2+0.4-0.08+\cdots',S.Integer(10),-S.Rational(1,5)),(26,r'2+0.5+0.125+0.03125+\cdots',S.Integer(2),S.Rational(1,4)),(27,r'\sum_{n=1}^\infty12(0.73)^{n-1}',S.Integer(12),S.Rational(73,100)),(28,r'\sum_{n=1}^\infty5/\pi^n',5/S.pi,1/S.pi),(29,r'\sum_{n=1}^\infty(-3)^{n-1}/4^n',S.Rational(1,4),-S.Rational(3,4)),(30,r'\sum_{n=0}^\infty3^{n+1}/(-2)^n',S.Integer(3),-S.Rational(3,2)),(31,r'\sum_{n=1}^\infty e^{2n}/6^{n-1}',S.exp(2),S.exp(2)/6),(32,r'\sum_{n=1}^\infty6\cdot2^{2n-1}/3^n',S.Integer(4),S.Rational(4,3))]
for q,eq,a,r in geo:
 conv=abs(float(r))<1;calc(q,eq,'등비급수의 수렴 여부와 합을 구하라.','Determine convergence and the sum of the geometric series.',[rf'a={S.latex(a)},\quad r={S.latex(r)}',r'|r|<1\Rightarrow s_N=a(1-r^N)/(1-r)\to a/(1-r)' if conv else r'|r|>1\Rightarrow ar^{n-1}\not\to0'],S.latex(S.simplify(a/(1-r)))if conv else r'\text{divergent}')
other=[(33,r'\sum_{n=1}^\infty1/(3n)',[r's_N=H_N/3\to+\infty'],r'\text{divergent}'),(34,r'\sum_{n=1}^\infty n/(n+1)',[r'n/(n+1)\to1\ne0'],r'\text{divergent}'),(35,r'\sum_{n=1}^\infty(2/5)^n',[r'r=2/5,\quad S=(2/5)/(1-2/5)'],r'2/3'),(36,r'1/3+2/9+1/27+2/81+\cdots',[r'S=\sum_{k=0}^\infty(1/3+2/9)(1/9)^k=(5/9)/(1-1/9)'],r'5/8'),(37,r'\sum_{n=1}^\infty(2+n)/(1-2n)',[r'a_n\to-1/2\ne0'],r'\text{divergent}'),(38,r'\sum_{k=1}^\infty k^2/(k^2-2k+5)',[r'a_k\to1\ne0'],r'\text{divergent}'),(39,r'\sum_{n=1}^\infty3^{n+1}4^{-n}',[r'S=3\sum_{n=1}^\infty(3/4)^n=3(3/4)/(1-3/4)'],r'9'),(40,r'\sum_{n=1}^\infty[(-0.2)^n+(0.6)^{n-1}]',[r'S=(-1/5)/(1+1/5)+1/(1-3/5)=-1/6+5/2'],r'7/3'),(41,r'\sum_{n=1}^\infty1/(4+e^{-n})',[r'a_n\to1/4\ne0'],r'\text{divergent}'),(42,r'\sum_{n=1}^\infty(2^n+4^n)/e^n',[r'a_n\ge(4/e)^n\to+\infty'],r'\text{divergent}'),(43,r'\sum_{k=1}^\infty(\sin100)^k',[r'|\sin100|<1\quad(100\text{ radians})'],r'\sin100/(1-\sin100)'),(44,r'\sum_{n=1}^\infty1/[1+(2/3)^n]',[r'a_n\to1\ne0'],r'\text{divergent}'),(45,r'\sum_{n=1}^\infty\ln[(n^2+1)/(2n^2+1)]',[r'a_n\to\ln(1/2)\ne0'],r'\text{divergent}'),(46,r'\sum_{k=0}^\infty(\sqrt2)^{-k}',[r'r=1/\sqrt2,\quad S=1/(1-1/\sqrt2)'],r'2+\sqrt2'),(47,r'\sum_{n=1}^\infty\arctan n',[r'a_n\to\pi/2\ne0'],r'\text{divergent}'),(48,r'\sum_{n=1}^\infty(3/5^n+2/n)',[r's_N=3(1-5^{-N})/4+2H_N\to+\infty'],r'\text{divergent}'),(49,r'\sum_{n=1}^\infty[e^{-n}+1/(n(n+1))]',[r'S=(1/e)/(1-1/e)+1'],r'e/(e-1)'),(50,r'\sum_{n=1}^\infty e^n/n^2',[r'a_n\to+\infty'],r'\text{divergent}')]
for q,eq,lines,ans in other:calc(q,eq,'수렴·발산을 판정하고 수렴하면 합을 구하라.','Determine convergence or divergence and any sum.',lines,ans)
calc(51,r'x=0.99999\ldots','(a) 일과 비교하고 (b) 등비급수로 값을 구하라. (c) 일의 소수 표현 수와 (d) 복수 표현을 갖는 수를 설명하라.','(a) Compare with one, (b) evaluate a geometric series, (c) count the decimal representations of one, and (d) characterize numbers with multiple decimal representations.',[r'x=\sum_{n=1}^\infty9/10^n=(9/10)/(1-1/10)=1',r'1=1.000\ldots=0.999\ldots',r'0.d_1\cdots d_k000\ldots=0.d_1\cdots(d_k-1)999\ldots\quad(d_k>0)'],r'\text{(a,b)}\ x=1;\quad\text{(c) two; (d) nonzero terminating decimals}','부호와 선행 영의 자명한 차이를 제외한 통상적인 십진 전개를 센다. 영 자체는 반복 구로 끝나는 다른 비음수 전개가 없다.','Count usual decimal expansions, ignoring signs on zero and leading-zero variants. Zero itself has no distinct nonnegative expansion ending in repeated nines.',sub='abcd')
calc(52,r'a_1=1,\quad a_n=(5-n)a_{n-1}','급수의 합을 구하라.','Find the sum of the series.',[r'a_1,a_2,a_3,a_4,a_5=1,3,6,6,0',r'a_n=0\quad(n\ge5)'],r'\sum_{n=1}^\infty a_n=16')
for q,eq,whole,prefix,repeat in [(53,r'0.\overline8',0,'','8'),(54,r'0.\overline{46}',0,'','46'),(55,r'2.\overline{516}',2,'','516'),(56,r'10.1\overline{35}',10,'1','35'),(57,r'1.234\overline{567}',1,'234','567'),(58,r'5.\overline{71358}',5,'','71358')]:
 m=len(prefix);k=len(repeat);v=S.Integer(whole)+S.Rational(int(prefix or'0'),10**m)+S.Rational(int(repeat),10**m*(10**k-1))
 calc(q,eq,'두 정수의 비로 나타내라.','Express as a ratio of integers.',[rf'x={whole}+\frac{{{int(prefix or'0')}}}{{10^{{{m}}}}}+\frac{{{repeat}}}{{10^{{{m+k}}}}}\sum_{{j=0}}^\infty10^{{-{k}j}}',rf'\sum_{{j=0}}^\infty10^{{-{k}j}}=1/(1-10^{{-{k}}})'],S.latex(v))
for q,eq,ratio,domain,ans in [(59,r'\sum_{n=1}^\infty(-5)^nx^n',r'-5x',r'-1/5<x<1/5',r'-5x/(1+5x)'),(60,r'\sum_{n=1}^\infty(x+2)^n',r'x+2',r'-3<x<-1',r'(x+2)/(-x-1)'),(61,r'\sum_{n=0}^\infty(x-2)^n/3^n',r'(x-2)/3',r'-1<x<5',r'3/(5-x)'),(62,r'\sum_{n=0}^\infty(-4)^n(x-5)^n',r'-4(x-5)',r'19/4<x<21/4',r'1/(4x-19)'),(63,r'\sum_{n=0}^\infty2^n/x^n',r'2/x',r'x<-2\text{ or }x>2',r'x/(x-2)'),(64,r'\sum_{n=0}^\infty x^n/2^n',r'x/2',r'-2<x<2',r'2/(2-x)'),(65,r'\sum_{n=0}^\infty e^{nx}',r'e^x',r'x<0',r'1/(1-e^x)'),(66,r'\sum_{n=0}^\infty\sin^nx/3^n',r'\sin x/3',r'x\in\mathbb R',r'3/(3-\sin x)')]:
 calc(q,eq,'수렴하는 실수 입력과 그때의 합을 구하라.','Find real inputs giving convergence and the corresponding sum.',[rf'r={ratio},\quad |r|<1',r'S=a/(1-r)'],domain+r';\quad S='+ans,'경계에서 공비가 양·음의 일이면 항이 영으로 가지 않는다. 분모에 입력이 있는 경우 영은 정의역에서 제외한다.','At ratio plus or minus one the terms fail to vanish. A zero input is excluded when it appears in a denominator.')
N=S.symbols('N',integer=True,positive=True)
f67=(3*n*n+3*n+1)/(n*n+n)**3;f68=1/(n**5-5*n**3+4*n)
for q,expr,start,partial,answer in [(67,f67,1,1-1/(N+1)**3,S.Integer(1)),(68,f68,3,(N-2)*(N+3)*(N*N+N+4)/(96*N*(N-1)*(N+1)*(N+2)),S.Rational(1,96))]:
 pf=S.apart(expr,n);assert S.simplify(pf-expr)==0;assert S.summation(expr,(n,start,S.oo))==answer
 calc(q,rf'\sum_{{n={start}}}^\infty {S.latex(expr)}','CAS 부분분수로 부분합을 만들고 합을 구한 뒤 직접 급수 합산과 대조하라.','Use CAS partial fractions to obtain a finite-sum formula and its limit, and compare with direct CAS summation.',[rf'a_n={S.latex(pf)}',rf'\sum_{{n={start}}}^N a_n={S.latex(partial)}',rf'\lim_{{N\to\infty}}\sum_{{n={start}}}^N a_n={S.latex(answer)}'],S.latex(answer),'SymPy 부분분수 항등식과 무한급수 직접 합산이 일치한다.','SymPy verifies the partial-fraction identity and agrees with direct infinite summation.')
calc(69,r's_n=(n-1)/(n+1)','일반항과 급수의 합을 구하라.','Find the terms and the series sum.',[r'a_1=s_1=0',r'a_n=s_n-s_{n-1}=2/[n(n+1)]\quad(n\ge2)',r's_n\to1'],r'a_1=0,\quad a_n=2/[n(n+1)]\ (n\ge2);\quad\sum a_n=1','첫 항에는 부분합 차 공식을 임의로 영 인덱스까지 연장하지 않는다.','The difference formula must not extend the given partial-sum expression to index zero.')
calc(70,r's_n=3-n2^{-n}','일반항과 급수의 합을 구하라.','Find the terms and the series sum.',[r'a_1=s_1=5/2',r'a_n=s_n-s_{n-1}=(n-2)/2^n\quad(n\ge2)',r'n2^{-n}\to0'],r'a_1=5/2,\quad a_n=(n-2)/2^n\ (n\ge2);\quad\sum a_n=3')
calc(71,r'Q_1=100\ \mathrm{mg},\quad r=1/4','팔 시간마다 백 밀리그램을 복용하며 사이에 칠십오 퍼센트가 제거된다. (a) 두 번째·세 번째 직후 양 (b) 점화식 (c) 투여 직후의 장기 양을 구하라.','A hundred milligrams is taken every eight hours, with seventy-five percent eliminated between doses. Find (a) amounts just after doses two and three, (b) a recurrence, and (c) the long-term post-dose amount.',[r'Q_2=100+100/4=125,\quad Q_3=100+125/4=131.25',r'Q_{n+1}=100+Q_n/4',r'Q_n=100\sum_{j=0}^{n-1}(1/4)^j=\frac{400}3(1-4^{-n})'],r'\text{(a)}\ 125,131.25\ \mathrm{mg};\quad\text{(b)}\ Q_{n+1}=100+Q_n/4;\quad\text{(c)}\ 400/3\ \mathrm{mg}',sub='abc')
calc(72,r'D=1.5\ \mathrm{mg/L},\quad r=0.1','십이 시간마다 농도가 주어진 양만큼 증가하고 사이에 구십 퍼센트가 사라진다. (a) 세 번 직후 (b) 일반항 (c) 장기 투여 직후 농도를 구하라.','Every twelve hours a dose raises concentration by the given amount, with ninety percent eliminated between doses. Find (a) concentration after three doses, (b) its formula, and (c) its limiting post-dose value.',[r'C_n=1.5\sum_{j=0}^{n-1}(0.1)^j=\frac53(1-10^{-n})',r'C_3=1.5(1+0.1+0.01)=1.665'],r'\text{(a)}\ 1.665\ \mathrm{mg/L};\quad\text{(b)}\ C_n=\frac53(1-10^{-n});\quad\text{(c)}\ 5/3\ \mathrm{mg/L}',sub='abc')
calc(73,r'D=150\ \mathrm{mg},\quad r=0.05','매일 같은 시각에 투여하고 하루 동안 구십오 퍼센트가 제거된다. (a) 세 번째 및 일반 투여 직후 양 (b) 장기 투여 직후 양을 구하라.','A daily dose is taken at the same time, with ninety-five percent eliminated per day. Find (a) the amount after the third and nth doses and (b) the limiting post-dose amount.',[r'Q_n=150\sum_{j=0}^{n-1}(0.05)^j=\frac{3000}{19}(1-20^{-n})',r'Q_3=150(1+0.05+0.0025)=157.875'],r'\text{(a)}\ Q_3=157.875\ \mathrm{mg},\quad Q_n=\frac{3000}{19}(1-20^{-n})\ \mathrm{mg};\quad\text{(b)}\ 3000/19\ \mathrm{mg}',sub='ab')
calc(74,r'De^{-at},\quad a,T,C>0','농도는 지수적으로 감소하며 일정 시간마다 같은 양을 더한다. (a) 다음 투여 직전 잔여 농도 (b) 장기 직전 농도 (c) 임계 농도 이상을 유지하는 최소 투여량을 구하고 초기 축적 조건을 구분하라.','Concentration decays exponentially and equal doses are added at fixed intervals. Find (a) the pre-dose residual concentration, (b) its limit, and (c) the minimum dose maintaining the threshold, distinguishing the initial accumulation condition.',[r'q=e^{-aT}\in(0,1),\quad R_n=D(q+\cdots+q^n)=Dq(1-q^n)/(1-q)',r'R_\infty=D/(e^{aT}-1)',r'R_\infty\ge C\iff D\ge C(e^{aT}-1)',r'R_1=Dq\ge C\iff D\ge Ce^{aT}'],r'\text{(a)}\ R_n=\frac{D(1-e^{-naT})}{e^{aT}-1};\quad\text{(b)}\frac D{e^{aT}-1};\quad\text{(c) steady state: }C(e^{aT}-1);\ \text{from first interval: }Ce^{aT}','정상상태 유지용량은 충분한 초기 부하가 있을 때 적용된다. 약물이 없는 상태에서 첫 투여부터 모든 투여 간격을 보장하려면 두 번째 투여 직전 최저 농도가 가장 작으므로 더 큰 두 번째 식이 필요하다.','The steady-state maintenance amount assumes sufficient initial loading. Starting without drug, the lowest trough is before the second dose, so guaranteeing every interval from the first dose requires the larger second expression.',sub='abc')
calc(75,r'D>0,\quad0\le c<1,\quad s=1-c','초기 지출 이후 각 수취인이 받은 돈의 같은 비율을 다시 지출한다. (a) 처음 정해진 횟수 거래의 누적 지출 (b) 장기 승수와 소비 성향 팔십 퍼센트의 승수를 구하라.','Following an initial expenditure, each recipient spends the same fraction again. Find (a) cumulative spending after a given number of transactions and (b) the limiting multiplier, including eighty-percent consumption.',[r'S_n=D+Dc+\cdots+Dc^{n-1}=D(1-c^n)/(1-c)',r'S_n\to D/s=kD,\quad k=1/s',r'c=0.8\Rightarrow s=0.2\Rightarrow k=5'],r'\text{(a)}\ S_n=D(1-c^n)/(1-c);\quad\text{(b)}\ k=1/s,\quad k|_{c=0.8}=5',sub='ab')
calc(76,r'H>0,\quad0<r<1,\quad g>0','공을 주어진 높이에서 놓고 매번 이전 높이의 일정 비율까지 튄다. (a) 총거리 (b) 총 비행시간 (c) 충돌 때 속도가 부호를 바꾸며 일정 비율로 줄어드는 경우의 정지까지 시간을 구하라.','Drop a ball from the given height, with rebound height a fixed fraction of the preceding height. Find (a) total distance, (b) total flight time, and (c) stopping time when each impact reverses and scales velocity by a fixed factor.',[r'\text{(a)}\ L=H+2H\sum_{n=1}^\infty r^n=H(1+r)/(1-r)',r'\text{(b)}\ t_0=\sqrt{2H/g},\quad t=t_0+2t_0\sum_{n=1}^\infty(\sqrt r)^n',r'\text{(c)}\ v\mapsto-kv,\quad0<k<1\Rightarrow r=k^2'],r'\text{(a)}\ H\frac{1+r}{1-r};\quad\text{(b)}\sqrt{\frac{2H}g}\frac{1+\sqrt r}{1-\sqrt r};\quad\text{(c)}\sqrt{\frac{2H}g}\frac{1+k}{1-k}','초기 낙하는 한 번만 세고 이후 각 반동에는 상승·하강 두 시간이 들어간다. 이상화 모형의 무한 충돌이 유한 시간에 누적된다.','Count the initial fall once and each subsequent rebound twice. In this idealized model infinitely many impacts accumulate in finite time.',sub='abc')
calc(77,r'\sum_{n=2}^\infty(1+c)^{-n}=2','실수 매개변수를 구하라.','Find the real parameter.',[r'r=1/(1+c),\quad |r|<1',r'r^2/(1-r)=2\Rightarrow r=-1\pm\sqrt3',r'r=\sqrt3-1'],r'c=(\sqrt3-1)/2','음의 후보 공비는 절댓값이 일보다 커서 제외한다.','The negative candidate ratio has magnitude exceeding one and is excluded.')
calc(78,r'\sum_{n=0}^\infty e^{nc}=10','매개변수를 구하라.','Find the parameter.',[r'1/(1-e^c)=10\Rightarrow e^c=9/10'],r'c=\ln(9/10)')
calc(79,r'H_N=\sum_{n=1}^N1/n','연속 두 항을 묶어 조화급수 수렴 가정의 모순을 보이라.','Group consecutive pairs to contradict assumed convergence of the harmonic series.',[r'H_{2N}-H_N=\sum_{k=1}^N[1/(2k-1)-1/(2k)]\ge1/2',r'H_N\to S\Rightarrow H_{2N}-H_N\to0'],r'\sum1/n\text{ diverges}','첫 묶음의 양의 차가 모든 유한 합에서 남으므로 극한에서 엄격성의 소실 문제도 피한다.','The first positive gap remains in every finite sum, making the contradiction rigorous after taking limits.')
calc(80,r'H_N=\sum_{n=1}^N1/n','첫 항 뒤로 세 항씩 묶어 조화급수의 발산을 증명하라.','Group triples after the first term to prove harmonic divergence.',[r'1/(m-1)+1/(m+1)-2/m=2/[m(m^2-1)]>0\quad(m>1)',r'H_{3N+1}=1+\sum_{k=1}^N[1/(3k-1)+1/(3k)+1/(3k+1)]>1+H_N',r'H_N\to S\Rightarrow S\ge1+S'],r'\sum1/n\text{ diverges}')
calc(81,r'H_N=\sum_{n=1}^N1/n','지수함수와 일차식의 부등식을 곱하여 조화급수의 발산을 증명하라.','Multiply an exponential-versus-linear inequality to establish harmonic divergence.',[r'e^x>1+x\quad(x>0)',r'e^{H_N}>\prod_{k=1}^N(1+1/k)=N+1',r'H_N>\ln(N+1)\to+\infty'],r'\sum1/n\text{ diverges}','지수함수의 접선 부등식은 도함수의 양수성으로도 얻는다.','The exponential tangent inequality also follows by differentiating the difference.')
calc(82,r'y=x^n,\quad0\le x\le1,\quad n=0,1,2,\ldots','곡선들을 같은 그림에 그리고 이웃 곡선 사이 넓이로 소거급수의 합을 설명하라.','Plot the curves together and use areas between neighbors to explain the telescoping sum.',[r'A_n=\int_0^1(x^{n-1}-x^n)\,dx=1/n-1/(n+1)=1/[n(n+1)]',r'\sum_{n=1}^NA_n=1-\int_0^1x^N\,dx=1-1/(N+1)'],r'\sum_{n=1}^\infty1/[n(n+1)]=1','남는 곡선 아래 넓이가 영으로 줄어들어 단위 정사각형 전체 넓이가 채워진다.','The residual area under the last curve tends to zero, filling the unit square in the limit.')
calc(83,r'R_C=R_D=1','서로 외접한 단위 원 두 개의 공통 수평 접선 위 틈에 작은 원을 넣고, 이후 두 큰 원과 직전 작은 원에 접하는 원을 접점 방향으로 계속 넣는다. 작은 원의 지름과 지름의 총합을 구하라.','In the gap above a common horizontal tangent to two touching unit circles, insert a circle tangent to both. Continue toward their contact point with each circle tangent to the large circles and its predecessor. Find the diameters and their sum.',[r'C=(-1,1),\quad D=(1,1),\quad P=(0,1)',r'r_n=1/[2n(n+1)],\quad y_n=1-(2n+1)/[2n(n+1)]',r'1+(1-y_n)^2=(1+r_n)^2,\quad y_{n+1}-y_n=r_n+r_{n+1}',r'd_n=2r_n=1/n-1/(n+1)'],r'd_n=1/[n(n+1)],\quad\sum_{n=1}^\infty d_n=1','첫 원은반지름 사분의 일로 바닥 접선에 닿는다. 연속 원의 수직 지름은 바닥부터 큰 원 접점까지 틈 없이 이어진다.','The first radius is one quarter and touches the baseline. Successive vertical diameters fill the interval from that baseline to the large-circle contact point.')
calc(84,r'\angle C=\pi/2,\quad\angle A=\theta,\quad AC=b','직각삼각형에서 꼭짓점으로부터 빗변과 밑변에 번갈아 수선을 내려 다른 꼭짓점 쪽으로 계속 진행할 때 수선 길이의 총합을 구하라.','Starting at the right-angle vertex, drop perpendiculars alternately to the hypotenuse and base, proceeding toward the remaining vertex. Find their total length.',[r'CD=b\sin\theta',r'DE=CD\sin\theta,\quad EF=DE\sin\theta',r'0<\theta<\pi/2\Rightarrow0<\sin\theta<1'],r'\sum\text{perpendicular lengths}=\frac{b\sin\theta}{1-\sin\theta}')
calc(85,r'0=(1-1)+(1-1)+\cdots=1+(-1+1)+(-1+1)+\cdots=1','이 형식적 계산에서 잘못된 단계를 설명하라.','Identify the error in this formal calculation.',[r's_{2n}=0,\quad s_{2n-1}=1',r'1-1+1-1+\cdots\text{ has no partial-sum limit}'],r'\text{invalid regrouping of a divergent series}','유한합의 결합법칙을 극한이 없는 무한합에 적용했다. 두 묶음은 서로 다른 부분합 부분수열을 선택한다.','Finite associativity was applied to an infinite series with no limit. The two groupings select different subsequences of partial sums.')
calc(86,r'\sum a_n\text{ converges},\quad a_n\ne0','역수 항으로 만든 급수가 발산함을 증명하라.','Prove divergence of the reciprocal-term series.',[r'a_n\to0\Rightarrow|1/a_n|\to+\infty',r'1/a_n\not\to0'],r'\sum1/a_n\text{ diverges}')
calc(87,r'\sum a_n=A,\quad\sum b_n=B,\quad c\in\mathbb R','급수 극한 법칙 중 (a) 상수배 (b) 차의 법칙을 증명하라.','Prove the series laws for (a) scalar multiplication and (b) subtraction.',[r'\sum_{n=1}^Nca_n=c\sum_{n=1}^Na_n\to cA',r'\sum_{n=1}^N(a_n-b_n)=\sum_{n=1}^Na_n-\sum_{n=1}^Nb_n\to A-B'],r'\text{(a)}\sum ca_n=cA;\quad\text{(b)}\sum(a_n-b_n)=A-B',sub='ab')
calc(88,r'\sum a_n\text{ diverges},\quad c\ne0','영이 아닌 상수배 급수도 발산함을 증명하라.','Prove divergence is preserved by a nonzero scalar multiple.',[r'\sum ca_n\text{ converges}\Rightarrow\sum a_n=(1/c)\sum ca_n\text{ converges}'],r'\sum ca_n\text{ diverges}','수렴을 가정하면 상수배 법칙으로 주어진 발산과 모순이다.','Assuming convergence contradicts the given divergence by the scalar law.')
calc(89,r'\sum a_n\text{ converges},\quad\sum b_n\text{ diverges}','두 항을 더한 급수의 발산을 증명하라.','Prove the sum-term series diverges.',[r'\sum(a_n+b_n)\text{ converges}\Rightarrow\sum b_n=\sum(a_n+b_n)-\sum a_n\text{ converges}'],r'\sum(a_n+b_n)\text{ diverges}')
calc(90,r'\sum a_n,\sum b_n\text{ both diverge}','두 항을 더한 급수도 반드시 발산하는지 판단하라.','Decide whether the sum-term series must diverge.',[r'a_n=1,\quad b_n=-1',r'\sum a_n,\sum b_n\text{ diverge};\quad\sum(a_n+b_n)=\sum0=0'],r'\text{no; counterexample }a_n=1,\ b_n=-1')
calc(91,r'a_n>0,\quad s_N\le1000\text{ for every }N','급수의 수렴을 설명하라.','Explain why the series converges.',[r's_{N+1}-s_N=a_{N+1}>0',r'\{s_N\}\text{ is increasing and bounded above}'],r'\sum a_n=S\le1000','단조유계 정리는 급수의 항이 아니라 부분합에 적용한다.','Apply bounded monotone convergence to the partial sums, rather than to the terms.')
calc(92,r'f_1=f_2=1,\quad f_n=f_{n-1}+f_{n-2}','피보나치 수를 이용해 (a) 인접 곱 역수의 차 항등식 (b) 이웃 항 곱 역수 급수의 합 (c) 같은 분모와 가운데 항 분자의 급수 합을 증명하라.','For Fibonacci numbers, prove (a) a difference identity for reciprocal adjacent products, (b) the reciprocal-neighbor-product sum, and (c) the sum with the middle Fibonacci term in the numerator.',[r'\text{(a)}\frac1{f_{n-1}f_n}-\frac1{f_nf_{n+1}}=\frac{f_{n+1}-f_{n-1}}{f_{n-1}f_nf_{n+1}}=\frac1{f_{n-1}f_{n+1}}',r'\text{(b)}\sum_{n=2}^N\frac1{f_{n-1}f_{n+1}}=1-\frac1{f_Nf_{N+1}}\to1',r'\text{(c)}\frac{f_n}{f_{n-1}f_{n+1}}=\frac1{f_{n-1}}-\frac1{f_{n+1}}',r'\sum_{n=2}^N\frac{f_n}{f_{n-1}f_{n+1}}=2-1/f_N-1/f_{N+1}\to2'],r'\text{(a) identity proved; (b)}\ 1;\quad\text{(c)}\ 2','피보나치 수는 양수이며 무한히 증가하므로 마지막 역수 항이 사라진다.','Fibonacci numbers are positive and grow without bound, so the final reciprocal terms vanish.',sub='abc')
calc(93,r'[0,1],\quad[0,1]^2','(a) 구간에서 매번 남은 각 구간의 열린 가운데 삼분의 일을 제거할 때 제거 길이의 합과 남는 점의 예를 구하라. (b) 정사각형에서 매번 각 남은 정사각형의 중앙 구분의 일을 제거할 때 제거 넓이의 합을 구하라.','(a) Repeatedly remove the open middle third of each surviving interval: find the total removed length and examples of surviving points. (b) Repeatedly remove the central ninth of each surviving square: find the total removed area.',[r'\text{(a)}\ L=\sum_{n=1}^\infty2^{n-1}/3^n=(1/3)/(1-2/3)=1',r'0,1,1/3,2/3,1/9,2/9,\ldots\text{ remain; all removal endpoints remain}',r'\text{(b)}\ A=\sum_{n=1}^\infty8^{n-1}/9^n=(1/9)/(1-8/9)=1'],r'\text{(a)}\ L=1\text{ with infinitely many surviving points};\quad\text{(b)}\ A=1,\quad A_{\mathrm{remaining}}=0','길이나 넓이가 영인 집합도 무한히 많은 점을 포함할 수 있다.','A set of zero length or area can still contain infinitely many points.',sub='ab')
calc(94,r'a_n=(a_{n-1}+a_{n-2})/2\quad(n\ge3)','(a) 여러 초기값으로 극한을 예상하고 (b) 이웃 항의 차를 급수로 합해 일반 극한을 구하라.','(a) Experiment with initial values to predict the limit, and (b) sum successive differences to find the limit in terms of the initial data.',[r'(a_1,a_2)=(0,1),(1,0),(2,5)\Rightarrow L\approx0.666667,0.333333,4',r'd_n=a_{n+1}-a_n=-\tfrac12d_{n-1}=(-1/2)^{n-1}(a_2-a_1)',r'a_n=a_1+(a_2-a_1)\sum_{k=0}^{n-2}(-1/2)^k',r'a_n=(a_1+2a_2)/3-\tfrac23(a_2-a_1)(-1/2)^{n-1}'],r'L=(a_1+2a_2)/3',sub='ab')
calc(95,r'\sum_{n=1}^\infty n/(n+1)!','(a) 처음 네 부분합과 일반항 추측 (b) 귀납 증명 (c) 수렴과 합을 구하라.','Find (a) four partial sums and a conjectured formula, (b) an induction proof, and (c) convergence and the sum.',[r'\text{(a)}\ s_1=1/2,\ s_2=5/6,\ s_3=23/24,\ s_4=119/120',r's_N=1-1/(N+1)!',r'\text{(b)}\ s_{N+1}=1-1/(N+1)!+(N+1)/(N+2)!=1-1/(N+2)!',r'\text{(c)}\ 1/(N+1)!\to0'],r's_N=1-1/(N+1)!,\quad\sum_{n=1}^\infty n/(n+1)!=1',sub='abc')
calc(96,r'\text{equilateral triangle side}=1','정삼각형의 내접원부터 각 꼭짓점 쪽으로 두 변과 직전 원에 접하는 원들을 무한히 넣는다. 모든 원이 차지하는 총넓이를 구하라.','Starting with the incircle, insert chains toward all three vertices, each new circle tangent to the two sides and preceding circle. Find the total area of all circles.',[r'R=\sqrt3/6,\quad\sin(\pi/6)=1/2',r'2R-2r=R+r\Rightarrow r=R/3',r'A=\pi R^2\left[1+3\sum_{n=1}^\infty(1/9)^n\right]=\frac\pi{12}(1+3/8)'],r'A=11\pi/96','중앙 내접원은 한 번만 세고 나머지 세 원 사슬은 각각 면적비 구분의 일을 갖는다.','Count the central incircle once; each of the three remaining chains has area ratio one ninth.')
def svg(q,parts,caption):
 p=BASE/f'exercise-content/assets/s11-2-{q}.svg';p.write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 420"><rect width="620" height="420" fill="white"/>'+''.join(parts)+'</svg>');ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi(caption,caption),'caption':bi('계산식에서 직접 생성한 자체 도해.','Original diagram generated from the derived formulas.')}
parts=['<path d="M65 45V350H560" stroke="#64748b" fill="none"/>']
for power in range(9):
 pts=' '.join(f'{65+480*j/100:.2f},{350-290*(j/100)**power:.2f}'for j in range(101));parts.append(f'<polyline points="{pts}" fill="none" stroke="hsl({210+power*14},65%,45%)" stroke-width="2"/>');parts.append(f'<text x="{85+55*(power%9)}" y="385" font-size="12">n={power}</text>')
parts.append('<text x="540" y="370">1</text><text x="42" y="65">1</text>');svg(82,parts,'Powers on the unit square, n=0 through 8')
# Equal coordinate scale for the mutually tangent circles.
X=lambda x:310+125*x;Y=lambda y:355-125*y
parts=['<path d="M35 355H590" stroke="#64748b"/><text x="555" y="380">T</text>']
for cx in [-1,1]:parts.append(f'<circle cx="{X(cx)}" cy="{Y(1)}" r="125" fill="none" stroke="#1765b4" stroke-width="2"/>')
for k in range(1,13):
 rr=1/(2*k*(k+1));yy=1-(2*k+1)/(2*k*(k+1));parts.append(f'<circle cx="310" cy="{Y(yy)}" r="{125*rr}" fill="#ffeadb" stroke="#c45124"/>')
parts.extend(['<text x="317" y="223">P</text>','<text x="320" y="327">C₁</text>']);svg(83,parts,'Tangent unit circles and the decreasing gap circles')
# Triangle with b=1 and theta=pi/3; orthogonal projections reproduce the construction.
A=(1.7,1);B=(0,0);C=(1.7,0);X=lambda x:60+280*x;Y=lambda y:355-280*y
parts=[f'<polygon points="{X(B[0])},{Y(B[1])} {X(A[0])},{Y(A[1])} {X(C[0])},{Y(C[1])}" stroke="#1765b4" fill="none" stroke-width="2"/>'];cur=C
for j in range(22):
 if j%2==0:
  t=(cur[0]*A[0]+cur[1]*A[1])/(A[0]**2+A[1]**2);nxt=(t*A[0],t*A[1])
 else:nxt=(cur[0],0)
 parts.append(f'<path d="M{X(cur[0])},{Y(cur[1])}L{X(nxt[0])},{Y(nxt[1])}" stroke="#c45124" fill="none"/>');cur=nxt
parts.extend(['<text x="35" y="373">B</text>','<text x="540" y="75">A</text>','<text x="540" y="373">C</text>','<text x="550" y="220">b</text>']);svg(84,parts,'Alternating orthogonal projections in a right triangle')
# Three constructive stages of the Sierpinski carpet.
parts=[]
def carpet(x,y,w,level):
 if level==0:parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{w}" fill="#1765b4"/>');return
 for a in range(3):
  for b in range(3):
   if (a,b)!=(1,1):carpet(x+a*w/3,y+b*w/3,w/3,level-1)
for j in range(1,4):carpet(25+(j-1)*200,115,170,j);parts.append(f'<text x="{65+(j-1)*200}" y="320">Stage {j}</text>')
svg(93,parts,'First three stages of the middle-ninth square removal')
# Equilateral geometry with true aspect ratio.
h=math.sqrt(3)/2;center=(.5,h/3);R=math.sqrt(3)/6;vertices=[(0,0),(1,0),(.5,h)];X=lambda x:105+410*x;Y=lambda y:390-410*y
parts=[f'<polygon points="'+ ' '.join(f'{X(x)},{Y(y)}'for x,y in vertices)+'" fill="none" stroke="#1765b4" stroke-width="2"/>',f'<circle cx="{X(center[0])}" cy="{Y(center[1])}" r="{410*R}" fill="#dbeafe" stroke="#1765b4"/>']
for vx,vy in vertices:
 for k in range(1,7):
  rat=3**(-k);cx=vx+(center[0]-vx)*rat;cy=vy+(center[1]-vy)*rat;parts.append(f'<circle cx="{X(cx)}" cy="{Y(cy)}" r="{410*R*rat}" fill="#dbeafe" stroke="#1765b4"/>')
svg(96,parts,'Incircle and three geometric chains in a unit equilateral triangle')
items.sort(key=lambda e:e['number']);assert [e['number']for e in items]==list(range(1,97))
raw={'section':'11.2','source':{'title':'Calculus','edition':'9','language':'en','printedPages':list(range(785,790)),'pdfPages':list(range(822,827))},'scope':{'kind':'exercise','numbers':list(range(1,97)),'total':96,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s11-2.json')
for ex in items:
 for key in ['statement','answer']:
  assert re.findall(r'\\\((.*?)\\\)',ex[key]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[key]['en']),(ex['number'],key)
def control(v):
 if isinstance(v,str):assert all(ord(c)>=32 or c=='\n'for c in v),repr(v)
 elif isinstance(v,dict):
  for x in v.values():control(x)
 elif isinstance(v,list):
  for x in v:control(x)
control(raw)
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
for j in range(1,12):
 rj=S.Rational(1,2*j*(j+1));yj=1-S.Rational(2*j+1,2*j*(j+1));rn=S.Rational(1,2*(j+1)*(j+2));yn=1-S.Rational(2*j+3,2*(j+1)*(j+2));assert 1+(1-yj)**2==(1+rj)**2;assert yn-yj==rj+rn
for expr,start,partial in [(f67,1,1-1/(N+1)**3),(f68,3,(N-2)*(N+3)*(N*N+N+4)/(96*N*(N-1)*(N+1)*(N+2)))]:
 for j in range(start,12):assert S.simplify(sum(expr.subs(n,k)for k in range(start,j+1))-partial.subs(N,j))==0
for a,b in [(0,1),(1,0),(2,5)]:
 vals=[a,b]
 for j in range(80):vals.append((vals[-1]+vals[-2])/2)
 assert abs(vals[-1]-(a+2*b)/3)<1e-12
(BASE/'exercise-content/s11-2.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('11.2:',len(items),'cards;',sum('figure'in e for e in items),'SVG; schema, math parity, XML, partial fractions, finite sums and tangencies passed')
