import json,math,html,sys,re
from pathlib import Path
import sympy as S
BASE=Path(__file__).resolve().parents[1];items=[];n=S.symbols('n',integer=True,positive=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(q,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=846 if q<=44 else 847 if q<=86 else 848
 items.append(dict(id=f'stewart9-exercise-11.10-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('테일러·매클로린 급수','Taylor and Maclaurin series'),statement=bi(sk,se),hint=bi('중심에서의 도함수 계수나 기본 급수의 치환을 사용하고 수렴 범위와 나머지를 확인한다.','Use derivatives at the center or substitutions into standard series, then check the convergence domain and remainder.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if k:steps.append((k,e))
 add(q,M(eq)+' '+tk,M(eq)+' '+te,steps,M(ans),M(ans),'초기항·정의역과 극한 논증의 조건을 확인했다.','Initial terms, domain, and conditions of the limit argument were checked.',sub)
def dots(q,sets,limit=None):
 pts=[(i,v) for label,values in sets for i,v in values];xmin=0;xmax=max(i for i,v in pts)+1;lo=min(v for i,v in pts);hi=max(v for i,v in pts)
 if limit is not None:lo=min(lo,limit);hi=max(hi,limit)
 pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad;X=lambda x:55+510*(x-xmin)/(xmax-xmin);Y=lambda y:300-250*(y-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 390"><rect width="620" height="390" fill="white"/><path d="M55 40V300H575" stroke="#8492a5" fill="none"/>',f'<text x="55" y="25" font-size="15">Sequence {q}: discrete terms</text>']
 for j,(label,values) in enumerate(sets):
  c=['#1463c2','#c64c38','#159568'][j%3]
  for i,v in values:out.append(f'<circle cx="{X(i):.3f}" cy="{Y(v):.3f}" r="3" fill="{c}"/>')
  out.append(f'<text x="55" y="{337+17*j}" fill="{c}" font-size="12">{html.escape(label)}</text>')
 if limit is not None:out.append(f'<path d="M55 {Y(limit)}H575" stroke="#65758d" stroke-dasharray="5 5"/><text x="570" y="{Y(limit)-5}" font-size="10">L={limit:.5g}</text>')
 for i in range(6):
  v=lo+(hi-lo)*i/5;out.append(f'<text x="5" y="{Y(v)+4}" font-size="10">{v:.4g}</text>')
 for i in [1,int(xmax/2),int(xmax)-1]:out.append(f'<text x="{X(i)}" y="318" font-size="11">{i}</text>')
 out.append('</svg>');p=BASE/f'exercise-content/assets/s11-10-{q}.svg';p.write_text(''.join(out));ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('정수 인덱스에 대응하는 수열의 점 그래프','Discrete sequence values at integer indices'),'caption':bi('자체 계산한 항을 점으로 표시했다. 선으로 연결하지 않았다.','Original computed terms shown as discrete points.')}
import mpmath as mp
mp.mp.dps=60
x,h=S.symbols('x h',real=True)
calc(1,r'f(x)=\sum_{n=0}^\infty b_n(x-5)^n\quad\text{for all }x','여덟 번째 계수를 도함수로 나타내라.','Express the eighth coefficient in terms of a derivative.',[r'f^{(8)}(5)=8!b_8'],r'b_8=f^{(8)}(5)/8!')
calc(2,r'\text{(a)}\ 1.1+0.7x^2+2.2x^3+\cdots;\quad\text{(b)}\ 1.6-0.8(x-1)+0.4(x-1)^2-0.1(x-1)^3+\cdots;\quad\text{(c)}\ 2.8+0.5(x-2)+1.5(x-2)^2-0.1(x-2)^3+\cdots','도해에서 원점의 함수값은 일보다 작고, 입력 일에서는 증가하며, 입력 이에서는 아래로 굽는다. 제시한 세 급수가 각 중심의 테일러 급수가 아닌 이유를 설명하라.','The graph has value below one at zero, increases at input one, and is concave down at input two. Explain why the three proposed series cannot be Taylor series at their indicated centers.',[r'\text{(a)}\ f(0)<1\ne1.1',r'\text{(b)}\ f^{\prime}(1)>0\ne-0.8',r'\text{(c)}\ f^{\prime\prime}(2)<0\ne2!\cdot1.5=3'],r'\text{(a) wrong constant; (b) wrong slope sign; (c) wrong concavity sign}','그림의 정확한 함숫값을 추정할 필요 없이 높이와 도함수 부호만으로 모순을 확인한다.','Only the displayed height and derivative signs are needed; exact values need not be inferred from the sketch.',sub='abc')
calc(3,r'f^{(n)}(0)=(n+1)!\quad(n\ge0)','매클로린 급수와 반지름을 구하라.','Find the Maclaurin series and its radius.',[r'c_n=f^{(n)}(0)/n!=n+1',r'\lim|(n+1)/(n+2)|=1'],r'\sum_{n=0}^\infty(n+1)x^n,\quad R=1')
calc(4,r'f^{(n)}(4)=\frac{(-1)^nn!}{3^n(n+1)}','주어진 중심의 테일러 급수와 반지름을 구하라.','Find the Taylor series about the specified center and its radius.',[r'c_n=f^{(n)}(4)/n!=(-1)^n/[3^n(n+1)]',r'|a_{n+1}/a_n|=|x-4|(n+1)/[3(n+2)]\to|x-4|/3'],r'\sum_{n=0}^\infty\frac{(-1)^n(x-4)^n}{3^n(n+1)},\quad R=3')
firstfour=[(5,x*S.exp(x),0),(6,1/(1+x),2),(7,x**S.Rational(1,3),8),(8,S.log(x),1),(9,S.sin(x),S.pi/6),(10,S.cos(x)**2,0)]
for q,f,a in firstfour:
 cs=[]
 for k in range(9):
  val=S.simplify(S.diff(f,x,k).subs(x,a)/S.factorial(k))
  if val!=0:cs.append((k,val))
  if len(cs)==4:break
 pol=sum(v*h**k for k,v in cs);form=S.latex(pol).replace('h',r'(x-'+S.latex(a)+')')if a!=0 else S.latex(pol.subs(h,x))
 calc(q,rf'f(x)={S.latex(f)},\quad a={S.latex(a)}','테일러 급수의 정의로 영이 아닌 첫 네 항을 구하라.','Use the Taylor definition to find the first four nonzero terms.',[r'c_k=f^{(k)}(a)/k!',r',\quad '.join(rf'c_{{{k}}}={S.latex(v)}'for k,v in cs)],form+r'+\cdots')
mac=[(11,r'(1-x)^{-2}',r'f^{(n)}(0)=(n+1)!',r'\sum_{n=0}^\infty(n+1)x^n',r'1'),(12,r'\ln(1+x)',r'f(0)=0,\quad f^{(n)}(0)=(-1)^{n-1}(n-1)!\ (n\ge1)',r'\sum_{n=1}^\infty(-1)^{n-1}x^n/n',r'1'),(13,r'\cos x',r'f^{(2n)}(0)=(-1)^n,\quad f^{(2n+1)}(0)=0',r'\sum_{n=0}^\infty(-1)^nx^{2n}/(2n)!',r'\infty'),(14,r'e^{-2x}',r'f^{(n)}(0)=(-2)^n',r'\sum_{n=0}^\infty(-2)^nx^n/n!',r'\infty'),(15,r'2x^4-3x^2+3',r'f(0)=3,\quad f^{(2)}(0)=-6,\quad f^{(4)}(0)=48;\quad\text{other nonzero-order derivatives vanish at zero}',r'3-3x^2+2x^4',r'\infty'),(16,r'\sin(3x)',r'f^{(2n+1)}(0)=(-1)^n3^{2n+1},\quad f^{(2n)}(0)=0',r'\sum_{n=0}^\infty(-1)^n3^{2n+1}x^{2n+1}/(2n+1)!',r'\infty'),(17,r'2^x',r'f^{(n)}(0)=(\ln2)^n',r'\sum_{n=0}^\infty(\ln2)^nx^n/n!',r'\infty'),(18,r'x\cos x',r'f^{(2n+1)}(0)=(-1)^n(2n+1),\quad f^{(2n)}(0)=0',r'\sum_{n=0}^\infty(-1)^nx^{2n+1}/(2n)!',r'\infty'),(19,r'\sinh x',r'f^{(2n+1)}(0)=1,\quad f^{(2n)}(0)=0',r'\sum_{n=0}^\infty x^{2n+1}/(2n+1)!',r'\infty'),(20,r'\cosh x',r'f^{(2n)}(0)=1,\quad f^{(2n+1)}(0)=0',r'\sum_{n=0}^\infty x^{2n}/(2n)!',r'\infty')]
for q,fun,derivs,rep,R in mac:calc(q,'f(x)='+fun,'도함수 정의로 매클로린 급수와 반지름을 구하라. 함수가 멱급수로 표현됨은 가정한다.','Use derivative coefficients to find the Maclaurin series and radius, assuming the function has a power-series representation.',[derivs,r'c_n=f^{(n)}(0)/n!',r'\text{Polynomial series are entire; factorial denominators give ratio limit zero, while the remaining geometric-scale cases have radius one.}'],r'f(x)='+rep+r',\quad R='+R)
for q,f,a in [(21,x**5+2*x**3+x,2),(22,x**6-x**4+2,-2)]:
 pol=S.expand(f.subs(x,h+a));coef=[S.expand(pol).coeff(h,k)for k in range(S.degree(f,x)+1)];rep='+'.join(rf'({S.latex(v)})(x-({a}))^{k}'for k,v in enumerate(coef)if v!=0)
 calc(q,rf'f(x)={S.latex(f)},\quad a={a}','지정한 중심의 테일러 급수와 반지름을 구하라.','Find the Taylor series at the given center and its radius.',[rf'h=x-({a}),\quad f(a+h)={S.latex(pol)}',r'\text{The polynomial expansion terminates.}'],rep+r',\quad R=\infty')
centered=[(23,r'\ln x',r'2',r'\ln x=\ln2+\ln[1+(x-2)/2]',r'\ln2+\sum_{n=1}^\infty\frac{(-1)^{n-1}(x-2)^n}{n2^n}',r'2'),(24,r'1/x',r'-3',r'1/x=-\frac13[1-(x+3)/3]^{-1}',r'-\sum_{n=0}^\infty(x+3)^n/3^{n+1}',r'3'),(25,r'e^{2x}',r'3',r'e^{2x}=e^6e^{2(x-3)}',r'e^6\sum_{n=0}^\infty2^n(x-3)^n/n!',r'\infty'),(26,r'1/x^2',r'1',r'x^{-2}=[1+(x-1)]^{-2}',r'\sum_{n=0}^\infty(-1)^n(n+1)(x-1)^n',r'1'),(27,r'\sin x',r'\pi',r'\sin(\pi+h)=-\sin h',r'-\sum_{n=0}^\infty(-1)^n(x-\pi)^{2n+1}/(2n+1)!',r'\infty'),(28,r'\cos x',r'\pi/2',r'\cos(\pi/2+h)=-\sin h',r'-\sum_{n=0}^\infty(-1)^n(x-\pi/2)^{2n+1}/(2n+1)!',r'\infty'),(29,r'\sin(2x)',r'\pi',r'\sin(2\pi+2h)=\sin(2h)',r'\sum_{n=0}^\infty(-1)^n2^{2n+1}(x-\pi)^{2n+1}/(2n+1)!',r'\infty'),(30,r'\sqrt x',r'16',r'\sqrt x=4[1+(x-16)/16]^{1/2}',r'4\sum_{n=0}^\infty\binom{1/2}{n}(x-16)^n/16^n',r'16')]
for q,fun,a,step,rep,R in centered:calc(q,rf'f(x)={fun},\quad a={a}','지정한 중심의 테일러 급수와 수렴 반지름을 구하라.','Find the Taylor series about the given center and its radius.',[step,r'f(x)=\sum_{n=0}^\infty f^{(n)}(a)(x-a)^n/n!'],r'f(x)='+rep+r',\quad R='+R)
for q,fun,a,bound,rep in [(31,r'\cos x',r'0',r'1',r'\sum_{n=0}^\infty(-1)^nx^{2n}/(2n)!'),(32,r'\sin x',r'\pi',r'1',r'-\sum_{n=0}^\infty(-1)^n(x-\pi)^{2n+1}/(2n+1)!'),(33,r'\sinh x',r'0',r'e^{|x|}',r'\sum_{n=0}^\infty x^{2n+1}/(2n+1)!'),(34,r'\cosh x',r'0',r'e^{|x|}',r'\sum_{n=0}^\infty x^{2n}/(2n)!')]:
 calc(q,rf'f(x)={fun},\quad a={a}','테일러 나머지를 평가하여 급수가 모든 실수에서 함수를 나타냄을 증명하라.','Use the Taylor remainder to prove that the series represents the function for all real inputs.',[rf'|f^{{(N+1)}}(t)|\le {bound}\quad(t\text{{ between }}a\text{{ and }}x)',rf'|R_N(x)|\le {bound}\frac{{|x-a|^{{N+1}}}}{{(N+1)!}}\to0'],r'f(x)='+rep+r'\quad(x\in\mathbb R)','각 입력을 고정하면 분자의 지수 성장보다 팩토리얼이 더 빨라 나머지가 영으로 간다.','For each fixed input, factorial growth dominates the exponential numerator, so the remainder tends to zero.')
for q,fun,p,u,scale,R in [(35,r'\sqrt[4]{1-x}',r'1/4',r'-x',r'1',r'1'),(36,r'\sqrt[3]{8+x}',r'1/3',r'x/8',r'2',r'8'),(37,r'1/(2+x)^3',r'-3',r'x/2',r'1/8',r'2'),(38,r'(1-x)^{3/4}',r'3/4',r'-x',r'1',r'1')]:
 calc(q,'f(x)='+fun,'이항급수로 전개하고 반지름을 구하라.','Expand by the binomial series and give its radius.',[r'(1+u)^p=\sum_{n=0}^\infty\binom pn u^n\quad(|u|<1)',rf'f(x)=({scale})(1+({u}))^{{{p}}}'],rf'f(x)=({scale})\sum_{{n=0}}^\infty\binom{{{p}}}n({u})^n,\quad R={R}')
substituted=[(39,r'\arctan(x^2)',r'\arctan u=\sum(-1)^nu^{2n+1}/(2n+1),\quad u=x^2',r'\sum_{n=0}^\infty(-1)^nx^{4n+2}/(2n+1)',r'1'),(40,r'\sin(\pi x/4)',r'\sin u=\sum(-1)^nu^{2n+1}/(2n+1)!,\quad u=\pi x/4',r'\sum_{n=0}^\infty\frac{(-1)^n(\pi/4)^{2n+1}x^{2n+1}}{(2n+1)!}',r'\infty'),(41,r'x\cos(2x)',r'\cos u=\sum(-1)^nu^{2n}/(2n)!,\quad u=2x',r'\sum_{n=0}^\infty(-1)^n2^{2n}x^{2n+1}/(2n)!',r'\infty'),(42,r'e^{3x}-e^{2x}',r'e^u=\sum u^n/n!',r'\sum_{n=1}^\infty(3^n-2^n)x^n/n!',r'\infty'),(43,r'x\cos(x^2/2)',r'u=x^2/2\text{ in the cosine series, then multiply by }x',r'\sum_{n=0}^\infty\frac{(-1)^nx^{4n+1}}{2^{2n}(2n)!}',r'\infty'),(44,r'x^2\ln(1+x^3)',r'u=x^3\text{ in }\ln(1+u),\text{ then multiply by }x^2',r'\sum_{n=1}^\infty(-1)^{n-1}x^{3n+2}/n',r'1'),(45,r'x/\sqrt{4+x^2}',r'f(x)=\frac x2(1+x^2/4)^{-1/2}',r'\frac x2\sum_{n=0}^\infty\binom{-1/2}n x^{2n}/4^n',r'2'),(46,r'x^2/\sqrt{2+x}',r'f(x)=\frac{x^2}{\sqrt2}(1+x/2)^{-1/2}',r'\frac{x^2}{\sqrt2}\sum_{n=0}^\infty\binom{-1/2}n x^n/2^n',r'2'),(47,r'\sin^2x',r'\sin^2x=(1-\cos2x)/2',r'\sum_{n=1}^\infty\frac{(-1)^{n-1}2^{2n-1}x^{2n}}{(2n)!}',r'\infty'),(48,r'f(x)=(x-\sin x)/x^3\ (x\ne0),\quad f(0)=1/6',r'x-\sin x=x^3/3!-x^5/5!+x^7/7!-\cdots',r'\sum_{n=0}^\infty(-1)^nx^{2n}/(2n+3)!',r'\infty')]
for q,fun,step,rep,R in substituted:calc(q,fun if q==48 else'f(x)='+fun,'기본 매클로린 급수를 변형하여 주어진 함수의 급수를 구하라.','Transform a standard Maclaurin series to represent the function.',[step],r'f(x)='+rep+r',\quad R='+R)
calc(49,r'\sinh x=(e^x-e^{-x})/2,\quad\cosh x=(e^x+e^{-x})/2','지수급수로부터 (a) 쌍곡사인 (b) 쌍곡코사인 급수를 유도하라.','Derive (a) the hyperbolic sine and (b) hyperbolic cosine series from the exponential series.',[r'e^{\pm x}=\sum_{n=0}^\infty(\pm1)^nx^n/n!',r'\text{Subtracting cancels even powers; adding cancels odd powers.}'],r'\text{(a)}\sinh x=\sum_{n=0}^\infty x^{2n+1}/(2n+1)!;\quad\text{(b)}\cosh x=\sum_{n=0}^\infty x^{2n}/(2n)!',sub='ab')
calc(50,r'\operatorname{arctanh}x=\frac12\ln\frac{1+x}{1-x},\quad|x|<1','로그급수로 역쌍곡탄젠트의 매클로린 급수를 유도하라.','Use logarithm series to derive the Maclaurin series for inverse hyperbolic tangent.',[r'\ln(1+x)=\sum_{n=1}^\infty(-1)^{n-1}x^n/n,\quad\ln(1-x)=-\sum_{n=1}^\infty x^n/n',r'\tfrac12[\ln(1+x)-\ln(1-x)]=x+x^3/3+x^5/5+\cdots'],r'\operatorname{arctanh}x=\sum_{n=0}^\infty x^{2n+1}/(2n+1),\quad|x|<1')
plotdata=[(51,r'\cos(x^2)',r'\sum_{n=0}^\infty(-1)^nx^{4n}/(2n)!',r'\infty',lambda z:math.cos(z*z),lambda z,j:(-1)**j*z**(4*j)/math.factorial(2*j),0,[-2.4,2.4],[-2,2]),(52,r'\ln(1+x^2)',r'\sum_{n=1}^\infty(-1)^{n-1}x^{2n}/n',r'1',lambda z:math.log1p(z*z),lambda z,j:(-1)**(j-1)*z**(2*j)/j,1,[-1.3,1.3],[-.5,2]),(53,r'xe^{-x}',r'\sum_{n=0}^\infty(-1)^nx^{n+1}/n!',r'\infty',lambda z:z*math.exp(-z),lambda z,j:(-1)**j*z**(j+1)/math.factorial(j),0,[-2,3],[-16,3]),(54,r'\arctan(x^3)',r'\sum_{n=0}^\infty(-1)^nx^{6n+3}/(2n+1)',r'1',lambda z:math.atan(z**3),lambda z,j:(-1)**j*z**(6*j+3)/(2*j+1),0,[-1.15,1.15],[-2,2])]
for q,fun,rep,R,f,term,start,xlim,ylim in plotdata:calc(q,'f(x)='+fun,'급수와 반지름을 구하고 함수와 여러 테일러 다항식을 같은 그림에 나타내어 관계를 설명하라.','Find the series and radius, plot the function with several Taylor polynomials, and describe their relation.',[r'\text{Substitute into a standard exponential, cosine, logarithm, or arctangent series.}',r'T_N(x)=\sum_{n=0}^N f^{(n)}(0)x^n/n!'],r'f(x)='+rep+r',\quad R='+R,'수렴 반지름 내부의 고정된 닫힌 구간에서 다항식이 함수에 균등하게 가까워진다. 더 높은 차수는 원점 밖에서도 더 넓은 구간을 잘 근사하지만 유한 반지름을 넘어 수렴하지는 않는다.','On each fixed closed interval inside the radius, the polynomials approach the function uniformly. Higher degree improves approximation farther from zero within that domain, but cannot extend convergence beyond a finite radius.')
def numerical(q,eq,series,term,start,places=None,eps=None):
 N=start;sm=mp.mpf(term(N));tol=mp.mpf(str(eps))if eps is not None else mp.mpf(10)**(-places)/2
 while True:
  nxt=mp.mpf(term(N+1));lo,hi=sorted([sm,sm+nxt])
  if abs(nxt)<tol and (places is None or round(float(lo),places)==round(float(hi),places)):break
  N+=1;sm+=term(N)
 ans=f'{float(sm):.{places}f}'if places is not None else f'{float(sm):.12f}'
 calc(q,eq,'지정한 정확도를 만족하도록 급수로 계산하고 나머지 상계를 제시하라.','Compute by a series to the requested accuracy and give a remainder bound.',[series,rf'\text{{sum through }}n={N}:\quad s={float(sm):.12f}',rf'|R|\le|a_{{{N+1}}}|={float(abs(nxt)):.12f}',rf'{float(lo):.12f}\le S\le{float(hi):.12f}'],rf'S\approx{ans}','사용한 꼬리는 크기가 감소하는 교대급수이다. 두 경계가 요청된 자리까지 동일하게 반올림되거나, 지정 절대오차보다 좁은 구간을 이룬다.','The tail used is alternating with decreasing magnitudes. Its bounds either round alike at the requested precision or enclose an interval narrower than the required absolute error.')
numerical(55,r'\cos5^\circ,\quad d=5',r'5^\circ=\pi/36,\quad\cos(\pi/36)=\sum_{n=0}^\infty(-1)^n(\pi/36)^{2n}/(2n)!',lambda j:(-1)**j*(mp.pi/36)**(2*j)/mp.factorial(2*j),0,places=5)
numerical(56,r'1/\sqrt[10]e,\quad d=5',r'e^{-1/10}=\sum_{n=0}^\infty(-1/10)^n/n!',lambda j:(-mp.mpf('.1'))**j/mp.factorial(j),0,places=5)
calc(57,r'\text{(a)}\ 1/\sqrt{1-x^2};\quad\text{(b)}\arcsin x','(a) 이항급수로 전개한 뒤 (b) 항별 적분으로 역삼각함수의 매클로린 급수를 구하라.','(a) Expand by the binomial series and (b) integrate termwise to find the inverse-sine Maclaurin series.',[r'\binom{-1/2}n(-1)^n=\frac{(2n)!}{4^n(n!)^2}',r'(1-x^2)^{-1/2}=\sum_{n=0}^\infty\frac{(2n)!x^{2n}}{4^n(n!)^2}\quad(|x|<1)',r'\arcsin x=\int_0^x(1-t^2)^{-1/2}\,dt'],r'\text{(a)}\sum_{n=0}^\infty\frac{(2n)!x^{2n}}{4^n(n!)^2};\quad\text{(b)}\arcsin x=\sum_{n=0}^\infty\frac{(2n)!x^{2n+1}}{4^n(n!)^2(2n+1)},\quad R=1',sub='ab')
v58=sum(mp.binomial(-mp.mpf('.25'),j)*mp.mpf('.1')**j for j in range(4));err58=abs(mp.binomial(-mp.mpf('.25'),4)*mp.mpf('.1')**4)
calc(58,r'\text{(a)}\ 1/\sqrt[4]{1+x};\quad\text{(b)}\ 1/\sqrt[4]{1.1}','(a) 이항급수를 구하고 (b) 이를 사용하여 소수 셋째 자리까지 계산하라.','(a) Find the binomial series and (b) use it to compute three decimal places.',[r'(1+x)^{-1/4}=\sum_{n=0}^\infty\binom{-1/4}n x^n=1-x/4+5x^2/32-15x^3/128+\cdots',rf'x=0.1:\quad s_3={float(v58):.12f},\quad|R_3|\le{float(err58):.12f}'],r'\text{(a)}\sum_{n=0}^\infty\binom{-1/4}n x^n,\ R=1;\quad\text{(b)} 0.976',sub='ab')
for q,integrand,step,ans,R in [(59,r'\sqrt{1+x^3}',r'(1+x^3)^{1/2}=\sum_{n=0}^\infty\binom{1/2}n x^{3n}',r'C+\sum_{n=0}^\infty\binom{1/2}n\frac{x^{3n+1}}{3n+1}',r'1'),(60,r'x^2\sin(x^2)',r'x^2\sin(x^2)=\sum_{n=0}^\infty\frac{(-1)^nx^{4n+4}}{(2n+1)!}',r'C+\sum_{n=0}^\infty\frac{(-1)^nx^{4n+5}}{(4n+5)(2n+1)!}',r'\infty'),(61,r'(\cos x-1)/x',r'(\cos x-1)/x=\sum_{n=1}^\infty\frac{(-1)^nx^{2n-1}}{(2n)!}',r'C+\sum_{n=1}^\infty\frac{(-1)^nx^{2n}}{(2n)(2n)!}',r'\infty'),(62,r'\arctan(x^2)',r'\arctan(x^2)=\sum_{n=0}^\infty\frac{(-1)^nx^{4n+2}}{2n+1}',r'C+\sum_{n=0}^\infty\frac{(-1)^nx^{4n+3}}{(4n+3)(2n+1)}',r'1')]:
 calc(q,rf'\int {integrand}\,dx','부정적분을 무한급수로 구하라.','Evaluate the antiderivative as an infinite series.',[step,r'\text{Integrate monomials term by term inside the radius.}'],ans+r',\quad R='+R)
numerical(63,r'\int_0^{1/2}x^3\arctan x\,dx,\quad d=4',r'\sum_{n=0}^\infty\frac{(-1)^n(1/2)^{2n+5}}{(2n+1)(2n+5)}',lambda j:(-1)**j*mp.mpf('.5')**(2*j+5)/((2*j+1)*(2*j+5)),0,places=4)
numerical(64,r'\int_0^1\sin(x^4)\,dx,\quad d=4',r'\sum_{n=0}^\infty\frac{(-1)^n}{(8n+5)(2n+1)!}',lambda j:(-1)**j/((8*j+5)*mp.factorial(2*j+1)),0,places=4)
numerical(65,r'\int_0^{0.4}\sqrt{1+x^4}\,dx,\quad\varepsilon=5\times10^{-6}',r'\sum_{n=0}^\infty\binom{1/2}n\frac{(0.4)^{4n+1}}{4n+1}',lambda j:mp.binomial(mp.mpf('.5'),j)*mp.mpf('.4')**(4*j+1)/(4*j+1),0,eps=.000005)
numerical(66,r'\int_0^{0.5}x^2e^{-x^2}\,dx,\quad\varepsilon=0.001',r'\sum_{n=0}^\infty\frac{(-1)^n(0.5)^{2n+3}}{(2n+3)n!}',lambda j:(-1)**j*mp.mpf('.5')**(2*j+3)/((2*j+3)*mp.factorial(j)),0,eps=.001)
limits=[(67,r'\lim_{x\to0}[x-\ln(1+x)]/x^2',r'x-\ln(1+x)=x^2/2-x^3/3+O(x^4)',r'1/2'),(68,r'\lim_{x\to0}(1-\cos x)/(1+x-e^x)',r'1-\cos x=x^2/2+O(x^4),\quad1+x-e^x=-x^2/2+O(x^3)',r'-1'),(69,r'\lim_{x\to0}[\sin x-x+x^3/6]/x^5',r'\sin x-x+x^3/6=x^5/120+O(x^7)',r'1/120'),(70,r'\lim_{x\to0}[\sqrt{1+x}-1-x/2]/x^2',r'\sqrt{1+x}=1+x/2-x^2/8+O(x^3)',r'-1/8'),(71,r'\lim_{x\to0}[x^3-3x+3\arctan x]/x^5',r'3\arctan x=3x-x^3+3x^5/5+O(x^7)',r'3/5'),(72,r'\lim_{x\to0}(\tan x-x)/x^3',r'\tan x=x+x^3/3+O(x^5)',r'1/3')]
for q,eq,expansion,ans in limits:calc(q,eq,'급수의 첫 비소거 항을 사용해 극한을 구하라.'+(' 반복 미분과 비교해 사용한 방법을 설명하라.'if q==72 else''),'Find the limit from the first surviving series term.'+(' Compare this method with repeated differentiation.'if q==72 else''),[expansion,r'\text{Divide by the leading power and let }x\to0.'],ans,'소거 뒤 선두계수를 읽을 수 있어 반복 미분보다 계산이 짧다.'if q==72 else'나머지 차수가 분모보다 높아 극한에 기여하지 않는다.','Reading the leading coefficient after cancellation is shorter than repeated differentiation.'if q==72 else'The remainder has higher order than the denominator and does not contribute to the limit.')
products=[(73,S.exp(-x*x)*S.cos(x)),(74,1/S.cos(x)),(75,x/S.sin(x)),(76,S.exp(x)*S.log(1+x)),(77,S.atan(x)**2),(78,S.exp(x)*S.sin(x)**2)]
for q,f in products:
 expanded=S.series(f,x,0,9).removeO().expand();cs=[(k,expanded.coeff(x,k))for k in range(9)if expanded.coeff(x,k)!=0][:3];poly=sum(v*x**k for k,v in cs)
 calc(q,rf'f(x)={S.latex(f)}','급수의 곱셈·나눗셈으로 영이 아닌 첫 세 항을 구하라.','Multiply or divide standard series to find the first three nonzero terms.',[r'e^u=1+u+u^2/2!+\cdots,\quad\sin x=x-x^3/6+x^5/120-\cdots',r'\cos x=1-x^2/2+x^4/24-\cdots,\quad\ln(1+x)=x-x^2/2+x^3/3-\cdots',r'\arctan x=x-x^3/3+x^5/5-\cdots',r'\text{Collect equal powers; for division, multiply the proposed quotient back into the denominator.}'],S.latex(poly)+r'+\cdots')
for q,series,f,I,why in [(79,r'\sum_{n=0}^\infty(-1)^nx^{4n}/n!',r'e^{-x^4}',r'\mathbb R',r'u=-x^4\text{ in }e^u'),(80,r'\sum_{n=1}^\infty(-1)^{n-1}x^{4n}/n',r'\ln(1+x^4)',r'[-1,1]',r'u=x^4\text{ in }\ln(1+u)'),(81,r'\sum_{n=0}^\infty\frac{(-1)^nx^{2n+1}}{2^{2n+1}(2n+1)}',r'\arctan(x/2)',r'[-2,2]',r'u=x/2\text{ in }\arctan u'),(82,r'\sum_{n=0}^\infty\frac{(-1)^nx^{2n+1}}{2^{2n+1}(2n+1)!}',r'\sin(x/2)',r'\mathbb R',r'u=x/2\text{ in }\sin u')]:calc(q,series,'급수가 나타내는 함수를 찾으라.','Identify the represented function.',[why],r'f(x)='+f+r',\quad x\in '+I)
for q,series,step,ans in [(83,r'\sum_{n=0}^\infty(-1)^n/n!',r'e^t=\sum t^n/n!,\quad t=-1',r'e^{-1}'),(84,r'\sum_{n=0}^\infty\frac{(-1)^n\pi^{2n}}{6^{2n}(2n)!}',r'\cos t=\sum(-1)^nt^{2n}/(2n)!,\quad t=\pi/6',r'\sqrt3/2'),(85,r'\sum_{n=1}^\infty\frac{(-1)^{n-1}3^n}{n5^n}',r'\ln(1+t)=\sum(-1)^{n-1}t^n/n,\quad t=3/5',r'\ln(8/5)'),(86,r'\sum_{n=0}^\infty3^n/(5^nn!)',r'e^t=\sum t^n/n!,\quad t=3/5',r'e^{3/5}'),(87,r'\sum_{n=0}^\infty\frac{(-1)^n\pi^{2n+1}}{4^{2n+1}(2n+1)!}',r'\sin t=\sum(-1)^nt^{2n+1}/(2n+1)!,\quad t=\pi/4',r'\sqrt2/2'),(88,r'1-\ln2+(\ln2)^2/2!-(\ln2)^3/3!+\cdots',r'e^{-\ln2}=1/2',r'1/2'),(89,r'3+9/2!+27/3!+81/4!+\cdots',r'\sum_{n=1}^\infty3^n/n!=e^3-1',r'e^3-1'),(90,r'1/(1\cdot2)-1/(3\cdot2^3)+1/(5\cdot2^5)-1/(7\cdot2^7)+\cdots',r'\arctan t=\sum(-1)^nt^{2n+1}/(2n+1),\quad t=1/2',r'\arctan(1/2)')]:calc(q,series,'기본 급수와 대조하여 합을 구하라.','Evaluate the sum by matching a standard series.',[step],ans)
calc(91,r'p\text{ is a polynomial of degree }n','입력을 일 증가시킨 다항식을 현재 입력에서의 도함수들로 나타내는 항등식을 증명하라.','Prove the identity expressing a unit shift of a polynomial in terms of derivatives at the current input.',[r'p(x+h)=\sum_{i=0}^n p^{(i)}(x)h^i/i!\quad\text{exactly}',r'p^{(n+1)}=0,\quad h=1'],r'p(x+1)=\sum_{i=0}^n p^{(i)}(x)/i!')
calc(92,r'f(x)=x/(1+x^2)','매클로린 계수로 원점의 백일계 도함수를 구하라.','Use the Maclaurin coefficient to find the derivative of order one hundred one at zero.',[r'f(x)=\sum_{n=0}^\infty(-1)^nx^{2n+1}',r'2n+1=101\Rightarrow n=50,\quad c_{101}=1'],r'f^{(101)}(0)=101!')
calc(93,r'f(x)=x\sin(x^2)','매클로린 계수로 원점의 이백삼계 도함수를 구하라.','Use the Maclaurin coefficient to find the derivative of order two hundred three at zero.',[r'f(x)=\sum_{n=0}^\infty(-1)^nx^{4n+3}/(2n+1)!',r'4n+3=203\Rightarrow n=50,\quad c_{203}=1/101!'],r'f^{(203)}(0)=203!/101!')
calc(94,r'f(x)=(1+x^3)^{30}','원점의 오십팔계 도함수를 구하라.','Find the derivative of order fifty-eight at zero.',[r'f(x)=\sum_{k=0}^{30}\binom{30}k x^{3k}',r'58\notin\{3k:k\in\mathbb Z\}\Rightarrow c_{58}=0'],r'f^{(58)}(0)=0')
calc(95,r'|f^{(3)}(t)|\le M\quad(|t-a|\le d)','이차 테일러 다항식의 나머지 부등식을 증명하라.','Prove the remainder inequality for the quadratic Taylor polynomial.',[r'x\ne a:\quad K=R_2(x)/(x-a)^3,\quad g(t)=f(t)-T_2(t)-K(t-a)^3',r'g(a)=g^{\prime}(a)=g^{\prime\prime}(a)=g(x)=0',r'\text{Three applications of Rolle imply }g^{(3)}(\xi)=0\text{ for some }\xi\text{ between }a,x',r'K=f^{(3)}(\xi)/6,\quad R_2(x)=f^{(3)}(\xi)(x-a)^3/6'],r'|R_2(x)|\le\frac M6|x-a|^3\quad(|x-a|\le d)','중심에서는 나머지가 영이다. 중심의 양쪽 모두 두 끝점 사이에 롤의 정리를 반복 적용하면 된다.','At the center the remainder is zero. On either side, repeated Rolle applications take place between the two endpoints.')
calc(96,r'f(x)=\begin{cases}e^{-1/x^2}&x\ne0\ 0&x=0\end{cases}','(a) 함수가 자신의 매클로린 급수와 같지 않음을 보이고 (b) 그래프와 원점 근방의 거동을 설명하라.','(a) Show that the function is not equal to its Maclaurin series and (b) graph it and describe its behavior near zero.',[r'f^{(n)}(x)=P_n(1/x)e^{-1/x^2}\quad(x\ne0)',r'\lim_{x\to0}|x|^{-m}e^{-1/x^2}=0\quad(m\ge0)',r'f^{(n)}(0)=0\text{ for every }n\text{ by induction, including the derivative difference quotient}',r'\sum_{n=0}^\infty f^{(n)}(0)x^n/n!=0,\quad f(x)>0\ (x\ne0)'],r'\text{Maclaurin series }0\text{ disagrees with }f\text{ at every }x\ne0','원점에 모든 차수로 평평하게 접하지만 주변에서는 양수이다. 영인 급수 자체의 반지름은 무한대이지만 그 합은 원래 함수와 다르다.','The graph is flat to every order at zero yet positive nearby. The zero series itself has infinite radius, but its sum differs from the original function.',sub='ab')
calc(97,r'g(x)=\sum_{n=0}^\infty\binom{k}n x^n,\quad k\in\mathbb R','(a) 급수 미분으로 일계 방정식 (b) 적절한 곱의 도함수가 영임을 보이고 (c) 이항급수 정리를 결론내려라.','(a) Differentiate to obtain a first-order equation, (b) show that a suitable product has zero derivative, and (c) conclude the binomial-series theorem.',[r'c_n=\binom{k}n,\quad(n+1)c_{n+1}=(k-n)c_n',r'|x|<1:\quad(1+x)g^{\prime}(x)=\sum_{n=0}^\infty[(n+1)c_{n+1}+nc_n]x^n=kg(x)',r'h(x)=(1+x)^{-k}g(x),\quad h^{\prime}(x)=(1+x)^{-k}[g^{\prime}-kg/(1+x)]=0',r'h(0)=1\Rightarrow h(x)=1'],r'\text{(a)} g^{\prime}=kg/(1+x);\quad\text{(b)} h^{\prime}=0;\quad\text{(c)} g(x)=(1+x)^k\quad(|x|<1)','계수비로 열린 단위 구간의 수렴과 항별 미분을 정당화한다. 지수가 비음의 정수이면 급수가 다항식으로 끝나 같은 결론을 바로 얻는다.','The coefficient ratio justifies convergence and differentiation inside the unit interval. For a nonnegative integer exponent the series terminates and the same conclusion follows directly.',sub='abc')
calc(98,r'L=4a\int_0^{\pi/2}\sqrt{1-e^2\sin^2\theta}\,d\theta,\quad e=\sqrt{a^2-b^2}/a,\quad a>b>0','이항급수와 짝수 사인 거듭제곱 적분을 사용하여 이심률 육제곱 항까지 타원 둘레를 전개하라.','Use the binomial series and even sine-power integrals to expand the ellipse circumference through the sixth power of eccentricity.',[r'\sqrt{1-u}=1-u/2-u^2/8-u^3/16+O(u^4),\quad u=e^2\sin^2\theta',r'\int_0^{\pi/2}\sin^{2n}\theta\,d\theta=\frac\pi2\frac{(2n)!}{2^{2n}(n!)^2}',r'\int\sin^2\theta=\pi/4,\quad\int\sin^4\theta=3\pi/16,\quad\int\sin^6\theta=5\pi/32\quad(0\le\theta\le\pi/2)'],r'L=2\pi a\left(1-\frac{e^2}4-\frac{3e^4}{64}-\frac{5e^6}{256}+O(e^8)\right)','이심률이 일보다 작아 이항급수를 전 구간에서 균등하게 적분할 수 있다. 영 이심률에서는 원의 둘레로 돌아간다.','Eccentricity below one permits uniform termwise integration over the interval. Zero eccentricity recovers the circle circumference.')


def overlay(q,f,term,start,xlim,ylim,Ns):
 xa,xb=xlim;ya,yb=ylim;X=lambda z:55+550*(z-xa)/(xb-xa);Y=lambda z:370-330*(z-ya)/(yb-ya)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 650 455"><defs><clipPath id="view"><rect x="55" y="40" width="550" height="330"/></clipPath></defs><rect width="650" height="455" fill="white"/>',f'<path d="M55 {Y(0)}H605M{X(0)} 40V370" stroke="#8491a3" fill="none"/>']
 grid=[xa+(xb-xa)*i/450 for i in range(451)]
 for j,N in enumerate(Ns):
  c=['#b16f22','#229364','#ce5276','#7953ba','#2984bb'][j%5];pts=' '.join(f'{X(z):.3f},{Y(sum(term(z,k)for k in range(start,N+1))):.3f}'for z in grid);out.append(f'<polyline points="{pts}" fill="none" stroke="{c}" stroke-width="1.8" clip-path="url(#view)"/><text x="{65+100*j}" y="414" fill="{c}" font-size="12">N={N}</text>')
 segment=[]
 for z in grid:
  v=f(z)
  if v is None:
   if segment:out.append('<polyline points="'+' '.join(segment)+'" fill="none" stroke="#111827" stroke-width="3" clip-path="url(#view)"/>');segment=[]
  else:segment.append(f'{X(z):.3f},{Y(float(v)):.3f}')
 if segment:out.append('<polyline points="'+' '.join(segment)+'" fill="none" stroke="#111827" stroke-width="3" clip-path="url(#view)"/>')
 for z in [xa,0,xb]:out.append(f'<text x="{X(z)-10}" y="390" font-size="12">{z:g}</text>')
 for v in [ya,0,yb]:out.append(f'<text x="8" y="{Y(v)+4}" font-size="12">{v:g}</text>')
 out.extend(['<text x="65" y="443" font-size="13">Black: function. Colors: partial sums through index N.</text>','</svg>']);path=BASE/f'exercise-content/assets/s11-10-{q}.svg';path.write_text(''.join(out));next(e for e in items if e['number']==q)['figure']={'src':f'../exercise-content/assets/{path.name}','alt':bi('함수와 여러 멱급수 부분합의 비교','Comparison of a function and several power-series partial sums'),'caption':bi('함수식과 계수로 직접 생성한 자체 그래프.','Original plots computed directly from the function and coefficients.')}

for q,fun,rep,R,f,term,start,xlim,ylim in plotdata:overlay(q,f,term,start,xlim,ylim,[start,start+1,start+3,start+7,start+15])
overlay(96,lambda z:math.exp(-1/z**2)if z else 0,lambda z,j:0,0,[-2,2],[-.03,.85],[0])
overlay(2,lambda z:.4+2.6*math.exp(-((z-2.4)/1.2)**2)+.1*z,lambda z,j:0,0,[-.35,5.2],[0,3.7],[])
ex=next(e for e in items if e['number']==2);ex['figure']['caption']=bi('원문 판단에 필요한 높이·기울기·오목성을 나타내는 자체 정성 도해.','Original qualitative illustration of the height, slope, and concavity needed for the decisions.')
path=BASE/'exercise-content/assets/s11-10-2.svg';path.write_text(path.read_text().replace('Black: function. Colors: partial sums through index N.','Qualitative sketch: f(0) &lt; 1, positive slope at 1, concave down at 2.'))
items.sort(key=lambda e:e['number']);assert [e['number']for e in items]==list(range(1,99))
raw={'section':'11.10','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[846,847,848],'pdfPages':[883,884,885]},'scope':{'kind':'exercise','numbers':list(range(1,99)),'total':98,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s11-10.json')
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
# Compare independent high-precision quadrature with integrated series.
quadrows=[(lambda z:z**3*mp.atan(z),mp.mpf('.5'),lambda j:(-1)**j*mp.mpf('.5')**(2*j+5)/((2*j+1)*(2*j+5))),(lambda z:mp.sin(z**4),mp.mpf(1),lambda j:(-1)**j/((8*j+5)*mp.factorial(2*j+1))),(lambda z:mp.sqrt(1+z**4),mp.mpf('.4'),lambda j:mp.binomial(mp.mpf('.5'),j)*mp.mpf('.4')**(4*j+1)/(4*j+1)),(lambda z:z*z*mp.exp(-z*z),mp.mpf('.5'),lambda j:(-1)**j*mp.mpf('.5')**(2*j+3)/((2*j+3)*mp.factorial(j)))]
for fn,end,term in quadrows:assert abs(mp.quad(fn,[0,end])-sum(term(j)for j in range(100)))<mp.mpf('1e-55')
assert abs(mp.mpf('1.1')**(-mp.mpf('.25'))-v58)<err58
assert round(float(mp.mpf('1.1')**(-mp.mpf('.25'))),3)==.976
assert S.expand(sum(S.binomial(S.Rational(1,2),j)*(-1)**j*h**j*S.factorial(2*j)/(4**j*S.factorial(j)**2)for j in range(4)))==1-h/4-3*h*h/64-5*h**3/256
(BASE/'exercise-content/s11-10.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('11.10: 98 cards, 6 SVG; schema, XML, quadrature and ellipse coefficients verified')
