import json,math,html,sys,re
from pathlib import Path
import sympy as S
BASE=Path(__file__).resolve().parents[1];items=[];n=S.symbols('n',integer=True,positive=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def add(q,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=831 if q<=37 else 832
 items.append(dict(id=f'stewart9-exercise-11.9-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('함수의 멱급수 표현','Functions represented by power series'),statement=bi(sk,se),hint=bi('일반항과 부분합을 구별하고 등비급수·소거합·일반항의 영 수렴 조건을 살펴본다.','Distinguish terms from partial sums and examine geometric sums, telescoping, and the zero-term condition.'),steps={'ko':[a for a,b in steps],'en':[b for a,b in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 steps=[(M(x),M(x)) for x in lines]
 if k:steps.append((k,e))
 add(q,M(eq)+' '+tk,M(eq)+' '+te,steps,M(ans),M(ans),'초기항·정의역과 극한 논증의 조건을 확인했다.','Initial terms, domain, and conditions of the limit argument were checked.',sub)
def dots(q,sets,limit=None):
 pts=[(i,v) for label,values in sets for i,v in values];xmin=0;xmax=max(i for i,v in pts)+1;lo=min(v for i,v in pts);hi=max(v for i,v in pts)
 if limit is not None:lo=min(lo,limit);hi=max(hi,limit)
 pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad;X=lambda x:55+510*(x-xmin)/(xmax-xmin);Y=lambda y:300-250*(y-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 620 390"><rect width="620" height="390" fill="white"/><path d="M55 40V300H575" stroke="#8492a5" fill="none"/>',f'<text x="55" y="25" font-size="15">Sequence {q}: discrete terms</text>']
 for j,(label,values) in enumerate(sets):
  c=['#1463c2','#c64c38','#159568'][j%3]
  for i,v in values:out.append(f'<circle cx="{X(i):.3f}" cy="{Y(v):.3f}" r="3" fill="{c}"/>')
  out.append(f'<text x="55" y="{337+17*j}" fill="{c}" font-size="12">{html.escape(label)}</text>')
 if limit is not None:out.append(f'<path d="M55 {Y(limit)}H575" stroke="#65758d" stroke-dasharray="5 5"/><text x="570" y="{Y(limit)-5}" font-size="10">L={limit:.5g}</text>')
 for i in range(6):
  v=lo+(hi-lo)*i/5;out.append(f'<text x="5" y="{Y(v)+4}" font-size="10">{v:.4g}</text>')
 for i in [1,int(xmax/2),int(xmax)-1]:out.append(f'<text x="{X(i)}" y="318" font-size="11">{i}</text>')
 out.append('</svg>');p=BASE/f'exercise-content/assets/s11-9-{q}.svg';p.write_text(''.join(out));ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('정수 인덱스에 대응하는 수열의 점 그래프','Discrete sequence values at integer indices'),'caption':bi('자체 계산한 항을 점으로 표시했다. 선으로 연결하지 않았다.','Original computed terms shown as discrete points.')}
import mpmath as mp
mp.mp.dps=60
x=S.symbols('x',real=True)
calc(1,r'\sum_{n=0}^\infty c_nx^n\text{ has radius }10','항별 미분한 급수의 반지름과 그 이유를 설명하라.','Give the radius after termwise differentiation and explain why.',[r'\left(\sum_{n=0}^\infty c_nx^n\right)^{\prime}=\sum_{n=1}^\infty nc_nx^{n-1}',r'\text{termwise differentiation preserves the radius}'],r'R=10')
calc(2,r'\sum_{n=0}^\infty b_nx^n\text{ converges for }|x|<2','항별 적분한 급수에 대해 보장되는 수렴 범위를 설명하라.','Describe the guaranteed convergence of the termwise integrated series.',[r'\int_0^x\sum_{n=0}^\infty b_nt^n\,dt=\sum_{n=0}^\infty\frac{b_n}{n+1}x^{n+1}',r'R_{\mathrm{integrated}}=R_{\mathrm{original}}\ge2'],r'\sum_{n=0}^\infty\frac{b_n}{n+1}x^{n+1}\text{ converges for }|x|<2','주어진 정보만으로 반지름이 정확히 이인지, 끝점에서 수렴하는지는 정할 수 없다.','The information does not determine whether the radius is exactly two or what happens at the endpoints.')
reps=[(3,r'1/(1+x)',r'1/(1-(-x))',r'\sum_{n=0}^\infty(-1)^nx^n',r'(-1,1)'),(4,r'x/(1+x)',r'x/(1-(-x))',r'\sum_{n=0}^\infty(-1)^nx^{n+1}',r'(-1,1)'),(5,r'1/(1-x^2)',r'u=x^2,\quad1/(1-u)=\sum_{n=0}^\infty u^n',r'\sum_{n=0}^\infty x^{2n}',r'(-1,1)'),(6,r'5/(1-4x^2)',r'u=4x^2',r'5\sum_{n=0}^\infty4^nx^{2n}',r'(-1/2,1/2)'),(7,r'2/(3-x)',r'f(x)=\frac23\frac1{1-x/3}',r'\sum_{n=0}^\infty2x^n/3^{n+1}',r'(-3,3)'),(8,r'4/(2x+3)',r'f(x)=\frac43\frac1{1+2x/3}',r'\sum_{n=0}^\infty4(-2)^nx^n/3^{n+1}',r'(-3/2,3/2)'),(9,r'x^2/(x^4+16)',r'f(x)=\frac{x^2}{16}\frac1{1+x^4/16}',r'\sum_{n=0}^\infty(-1)^nx^{4n+2}/16^{n+1}',r'(-2,2)'),(10,r'x/(2x^2+1)',r'f(x)=x/(1-(-2x^2))',r'\sum_{n=0}^\infty(-2)^nx^{2n+1}',r'(-1/\sqrt2,1/\sqrt2)'),(11,r'(x-1)/(x+2)',r'f(x)=1-\frac32\frac1{1+x/2}',r'1-\frac32\sum_{n=0}^\infty(-1)^nx^n/2^n',r'(-2,2)'),(12,r'(x+a)/(x^2+a^2),\quad a>0',r'f(x)=\left(\frac1a+\frac x{a^2}\right)\frac1{1+x^2/a^2}',r'\sum_{n=0}^\infty\frac{(-1)^nx^{2n}}{a^{2n+1}}+\sum_{n=0}^\infty\frac{(-1)^nx^{2n+1}}{a^{2n+2}}',r'(-a,a)'),(13,r'(2x-4)/(x^2-4x+3)',r'f(x)=1/(x-1)+1/(x-3)',r'-\sum_{n=0}^\infty(1+3^{-n-1})x^n',r'(-1,1)'),(14,r'(2x+3)/(x^2+3x+2)',r'f(x)=1/(x+1)+1/(x+2)',r'\sum_{n=0}^\infty(-1)^n(1+2^{-n-1})x^n',r'(-1,1)')]
for q,fun,transform,rep,interval in reps:
 calc(q,'f(x)='+fun,'원점 중심의 멱급수 표현과 수렴 구간을 구하라.'+(' 먼저 부분분수로 분해하라.'if q in[13,14]else''),'Find a power series about zero and its interval of convergence.'+(' Start with partial fractions.'if q in[13,14]else''),[transform,r'1/(1-u)=\sum_{n=0}^\infty u^n\quad(|u|<1)',r'\text{At each boundary a nonzero subsequence of individual power terms fails to tend to zero.}'],r'f(x)='+rep+r',\quad I='+interval,'거듭제곱별 항을 기준으로 경계를 검사한다. 여러 연속 항을 묶어 상쇄한 값으로 경계 수렴을 주장하지 않는다.','Check individual powers at the boundary, without using cancellation inside grouped consecutive terms to assert convergence.')
calc(15,r'\text{(a)}\frac1{(1+x)^2};\quad\text{(b)}\frac1{(1+x)^3};\quad\text{(c)}\frac{x^2}{(1+x)^3}','기하급수를 미분하여 차례로 멱급수를 구하고 반지름을 제시하라.','Differentiate the geometric series to obtain successive representations and their radii.',[r'\frac1{1+x}=\sum_{n=0}^\infty(-1)^nx^n',r'\text{(a)}\frac1{(1+x)^2}=\sum_{n=0}^\infty(-1)^n(n+1)x^n',r'\text{(b)}\frac1{(1+x)^3}=\frac12\sum_{n=0}^\infty(-1)^n(n+1)(n+2)x^n',r'\text{(c)}\frac{x^2}{(1+x)^3}=\frac12\sum_{n=0}^\infty(-1)^n(n+1)(n+2)x^{n+2}'],r'R=1\text{ in all three cases}',sub='abc')
calc(16,r'\text{(a)}\ln(1-x);\quad\text{(b)} x\ln(1-x)','(a) 기하급수를 적분하여 표현과 반지름을 구하고 (b) 입력을 곱한 표현 (c) 이분의 일을 대입한 자연로그 이의 급수를 구하라.','(a) Integrate a geometric series to find a representation and radius, (b) multiply by the input, and (c) substitute one half to obtain a series for the logarithm of two.',[r'\ln(1-x)=-\int_0^x\frac{dt}{1-t}=-\sum_{n=1}^\infty x^n/n',r'x\ln(1-x)=-\sum_{n=1}^\infty x^{n+1}/n',r'\ln(1-1/2)=-\ln2=-\sum_{n=1}^\infty1/(n2^n)'],r'\text{(a)}\ln(1-x)=-\sum_{n=1}^\infty x^n/n,\ R=1;\quad\text{(b)} -\sum_{n=1}^\infty x^{n+1}/n;\quad\text{(c)}\ln2=\sum_{n=1}^\infty1/(n2^n)',sub='abc')
for q,fun,lines,rep,R in [(17,r'x/(1+4x)^2',[r'(1-u)^{-2}=\sum_{n=0}^\infty(n+1)u^n,\quad u=-4x'],r'\sum_{n=0}^\infty(-4)^n(n+1)x^{n+1}',r'1/4'),(18,r'[x/(2-x)]^3',[r'f(x)=x^3(1-x/2)^{-3}/8',r'(1-u)^{-3}=\sum_{n=0}^\infty(n+1)(n+2)u^n/2'],r'\sum_{n=0}^\infty(n+1)(n+2)x^{n+3}/2^{n+4}',r'2'),(19,r'(1+x)/(1-x)^2',[r'f(x)=(1+x)\sum_{n=0}^\infty(n+1)x^n',r'(n+1)+n=2n+1\quad(n\ge1)'],r'\sum_{n=0}^\infty(2n+1)x^n',r'1'),(20,r'(x^2+x)/(1-x)^3',[r'\sum_{n=1}^\infty nx^n=x/(1-x)^2',r'x\frac d{dx}\frac{x}{(1-x)^2}=\frac{x+x^2}{(1-x)^3}'],r'\sum_{n=1}^\infty n^2x^n',r'1'),(21,r'\ln(5-x)',[r'\ln(5-x)=\ln5+\ln(1-x/5)'],r'\ln5-\sum_{n=1}^\infty x^n/(n5^n)',r'5'),(22,r'x^2\arctan(x^3)',[r'\arctan u=\sum_{n=0}^\infty(-1)^nu^{2n+1}/(2n+1)',r'u=x^3'],r'\sum_{n=0}^\infty(-1)^nx^{6n+5}/(2n+1)',r'1')]:
 calc(q,'f(x)='+fun,'멱급수 표현과 수렴 반지름을 구하라.','Find a power series representation and its radius.',lines,r'f(x)='+rep+r',\quad R='+R)
plotdata=[(23,r'x^2/(x^2+1)',r'\sum_{n=0}^\infty(-1)^nx^{2n+2}',r'(-1,1)',lambda z:z*z/(1+z*z),lambda z,j:(-1)**j*z**(2*j+2),0,[-1.2,1.2],[-.5,1.5]),(24,r'\ln(1+x^4)',r'\sum_{n=1}^\infty(-1)^{n-1}x^{4n}/n',r'[-1,1]',lambda z:math.log1p(z**4),lambda z,j:(-1)**(j-1)*z**(4*j)/j,1,[-1.15,1.15],[-.5,2]),(25,r'\ln[(1+x)/(1-x)]',r'2\sum_{n=0}^\infty x^{2n+1}/(2n+1)',r'(-1,1)',lambda z:math.log((1+z)/(1-z))if abs(z)<1 else None,lambda z,j:2*z**(2*j+1)/(2*j+1),0,[-1.05,1.05],[-5,5]),(26,r'\arctan(2x)',r'\sum_{n=0}^\infty(-1)^n(2x)^{2n+1}/(2n+1)',r'[-1/2,1/2]',lambda z:math.atan(2*z),lambda z,j:(-1)**j*(2*z)**(2*j+1)/(2*j+1),0,[-.65,.65],[-2,2])]
for q,fun,rep,I,f,term,start,xlim,ylim in plotdata:
 calc(q,'f(x)='+fun,'멱급수를 구하고 함수와 여러 부분합을 같은 그림에 나타내어 항 수 증가에 따른 변화를 설명하라.','Find a power series and plot the function with several partial sums, describing the effect of adding terms.',[r'1/(1-u)=\sum_{n=0}^\infty u^n;\quad\ln(1+u)=\sum_{n=1}^\infty(-1)^{n-1}u^n/n',r'\arctan u=\sum_{n=0}^\infty(-1)^nu^{2n+1}/(2n+1)',r'\text{Substitute the relevant power or scale and simplify.}'],r'f(x)='+rep+r',\quad I='+I,'수렴 구간 내부에서 항이 늘면 함수에 가까워지며, 반지름 안의 고정된 닫힌 부분구간에서는 균등 수렴한다. 경계 근처의 수렴은 더 느릴 수 있고 구간 밖에서는 수렴하지 않는다.','Within the convergence interval more terms approach the function, uniformly on each fixed closed subinterval inside the radius. Convergence can be slower near the boundary and fails outside the interval.')
for q,integrand,var,series,R,proof in [(27,r't/(1-t^8)','t',r'C+\sum_{n=0}^\infty t^{8n+2}/(8n+2)',r'1',r't/(1-t^8)=\sum_{n=0}^\infty t^{8n+1}'),(28,r't/(1+t^3)','t',r'C+\sum_{n=0}^\infty(-1)^nt^{3n+2}/(3n+2)',r'1',r't/(1+t^3)=\sum_{n=0}^\infty(-1)^nt^{3n+1}'),(29,r'x^2\ln(1+x)','x',r'C+\sum_{n=1}^\infty(-1)^{n-1}x^{n+3}/[n(n+3)]',r'1',r'x^2\ln(1+x)=\sum_{n=1}^\infty(-1)^{n-1}x^{n+2}/n'),(30,r'\arctan x/x','x',r'C+\sum_{n=0}^\infty(-1)^nx^{2n+1}/(2n+1)^2',r'1',r'\arctan x/x=\sum_{n=0}^\infty(-1)^nx^{2n}/(2n+1)')]:
 calc(q,rf'\int {integrand}\,d{var}','부정적분을 멱급수로 나타내고 반지름을 구하라.','Represent the antiderivative as a power series and give its radius.',[proof,r'\text{Integrate each monomial; the radius is unchanged.}'],series+r',\quad R='+R,'원점에서 제거 가능한 특이점은 연속 확장으로 해석한다. 적분상수는 자유롭게 더한다.','Interpret a removable singularity at zero by continuous extension, and include an arbitrary integration constant.')
# Numerical answers are enclosed between consecutive alternating partial sums.
numerics=[(31,r'\int_0^{0.3}\frac{x}{1+x^3}\,dx',r'\sum_{n=0}^\infty\frac{(-1)^n(0.3)^{3n+2}}{3n+2}',lambda j:(-1)**j*mp.mpf('.3')**(3*j+2)/(3*j+2),0,6),(32,r'\int_0^{1/2}\arctan(x/2)\,dx',r'\sum_{n=0}^\infty\frac{(-1)^n(1/2)^{2n+2}}{2^{2n+1}(2n+1)(2n+2)}',lambda j:(-1)**j*mp.mpf('.5')**(2*j+2)/(2**(2*j+1)*(2*j+1)*(2*j+2)),0,6),(33,r'\int_0^{0.2}x\ln(1+x^2)\,dx',r'\sum_{n=1}^\infty\frac{(-1)^{n-1}(0.2)^{2n+2}}{n(2n+2)}',lambda j:(-1)**(j-1)*mp.mpf('.2')**(2*j+2)/(j*(2*j+2)),1,6),(34,r'\int_0^{0.3}\frac{x^2}{1+x^4}\,dx',r'\sum_{n=0}^\infty\frac{(-1)^n(0.3)^{4n+3}}{4n+3}',lambda j:(-1)**j*mp.mpf('.3')**(4*j+3)/(4*j+3),0,6),(35,r'\arctan(0.2)',r'\sum_{n=0}^\infty\frac{(-1)^n(0.2)^{2n+1}}{2n+1}',lambda j:(-1)**j*mp.mpf('.2')**(2*j+1)/(2*j+1),0,5),(36,r'\ln(1.1)',r'\sum_{n=1}^\infty\frac{(-1)^{n-1}(0.1)^n}{n}',lambda j:(-1)**(j-1)*mp.mpf('.1')**j/j,1,4)]
for q,eq,series,term,start,d in numerics:
 N=start;sm=term(N)
 while True:
  lo,hi=sorted([sm,sm+term(N+1)])
  if round(float(lo),d)==round(float(hi),d) and hi-lo<mp.mpf(10)**(-d)/2:break
  N+=1;sm+=term(N)
 calc(q,eq+rf',\quad d={d}','멱급수를 사용하여 지정한 소수 자리까지 계산하고 나머지로 정확도를 확인하라.','Use a power series to compute the specified decimal precision and certify it by the remainder.',[series,rf'\text{{sum through }}n={N}:\quad s={float(sm):.12f}',rf'|R|\le|a_{{{N+1}}}|={float(abs(term(N+1))):.12f}',rf'{float(lo):.12f}\le S\le{float(hi):.12f}'],rf'S\approx{float(sm):.{d}f}','적분 구간은 멱급수의 수렴 반지름 안에 있으므로 항별 적분이 가능하다. 교대항의 크기가 감소하고 두 경계가 같은 값으로 반올림된다.','The integration interval lies inside the power-series radius, permitting termwise integration. Alternating magnitudes decrease and both bounds round to the same value.')
calc(37,r'f(x)=\sum_{n=0}^\infty x^n/n!','(a) 도함수가 원함수와 같음을 보이고 (b) 지수함수임을 증명하라.','(a) Show that the derivative equals the function and (b) identify it as the exponential.',[r'R=\infty,\quad f^{\prime}(x)=\sum_{n=1}^\infty x^{n-1}/(n-1)!=f(x)',r'f(0)=1,\quad(e^{-x}f(x))^{\prime}=e^{-x}(f^{\prime}-f)=0'],r'\text{(a)}\ f^{\prime}=f;\quad\text{(b)}\ f(x)=e^x',sub='ab')
calc(38,r'f(x)=\sum_{n=0}^\infty(-1)^nx^{2n}/(2n)!','주어진 이계 미분방정식을 만족함을 보여라.','Show that the function satisfies the stated second-order differential equation.',[r'R=\infty,\quad f^{\prime\prime}(x)=\sum_{n=1}^\infty(-1)^nx^{2n-2}/(2n-2)!',r'm=n-1:\quad f^{\prime\prime}(x)=-\sum_{m=0}^\infty(-1)^mx^{2m}/(2m)!=-f(x)'],r'f^{\prime\prime}(x)+f(x)=0')
j0=lambda j:(-1)**j/(mp.mpf(4)**j*mp.factorial(j)**2*(2*j+1))
j0sm=sum(j0(j)for j in range(3));j0err=abs(j0(3))
calc(39,r'J_0(x)=\sum_{n=0}^\infty\frac{(-1)^nx^{2n}}{2^{2n}(n!)^2}','(a) 베셀 미분방정식을 만족함을 보이고 (b) 영부터 일까지 적분을 소수 셋째 자리까지 구하라.','(a) Verify the Bessel differential equation and (b) integrate from zero to one to three decimal places.',[r'c_n=(-1)^n/[4^n(n!)^2],\quad4n^2c_n+c_{n-1}=0\quad(n\ge1)',r'x^2J_0^{\prime\prime}+xJ_0^{\prime}+x^2J_0=\sum_{n=1}^\infty(4n^2c_n+c_{n-1})x^{2n}=0',r'\int_0^1J_0(x)\,dx=\sum_{n=0}^\infty\frac{(-1)^n}{4^n(n!)^2(2n+1)}',rf's_2={float(j0sm):.12f},\quad|R_2|\le{float(j0err):.12f}'],r'\text{(a)} x^2J_0^{\prime\prime}+xJ_0^{\prime}+x^2J_0=0;\quad\text{(b)}\int_0^1J_0(x)\,dx\approx0.920','무한 반지름으로 미분과 유계 구간 적분이 허용된다. 인접 부분합이 모두 같은 소수 셋째 자리로 반올림된다.','Infinite radius permits differentiation and integration over the bounded interval. Consecutive partial sums round to the same three-decimal value.',sub='ab')
calc(40,r'J_1(x)=\sum_{n=0}^\infty\frac{(-1)^nx^{2n+1}}{n!(n+1)!2^{2n+1}}','(a) 정의역 (b) 일차 베셀 미분방정식 (c) 영차 베셀 함수의 도함수와의 관계를 구하고 증명하라.','Find and prove (a) the domain, (b) the order-one Bessel equation, and (c) the derivative relation with the order-zero function.',[r'|a_{n+1}/a_n|=x^2/[4(n+1)(n+2)]\to0',r'd_n=(-1)^n/[n!(n+1)!2^{2n+1}],\quad4n(n+1)d_n+d_{n-1}=0\quad(n\ge1)',r'x^2J_1^{\prime\prime}+xJ_1^{\prime}+(x^2-1)J_1=\sum_{n=1}^\infty[4n(n+1)d_n+d_{n-1}]x^{2n+1}=0',r'J_0^{\prime}=\sum_{n=1}^\infty\frac{(-1)^n2nx^{2n-1}}{2^{2n}(n!)^2}=-\sum_{m=0}^\infty\frac{(-1)^mx^{2m+1}}{2^{2m+1}m!(m+1)!}'],r'\text{(a)}\mathbb R;\quad\text{(b)} x^2J_1^{\prime\prime}+xJ_1^{\prime}+(x^2-1)J_1=0;\quad\text{(c)} J_0^{\prime}=-J_1',sub='abc')
airycoeff=lambda j:S.prod(1/(S.Integer(3*k-1)*3*k)for k in range(1,j+1))
airyexpr=S.gamma(S.Rational(2,3))/2*(3**S.Rational(2,3)*S.airyai(x)+3**S.Rational(1,6)*S.airybi(x));airyfun=S.lambdify(x,airyexpr,'mpmath')
calc(41,r'A(x)=1+\frac{x^3}{2\cdot3}+\frac{x^6}{2\cdot3\cdot5\cdot6}+\frac{x^9}{2\cdot3\cdot5\cdot6\cdot8\cdot9}+\cdots','(a) 정의역 (b) 여러 부분합의 그래프 (c) 내장 에어리 함수를 사용한 함수 그래프와 부분합의 비교를 수행하라.','Find (a) the domain, (b) plots of several partial sums, and (c) a comparison with a graph computed using built-in Airy functions.',[r'A(x)=\sum_{n=0}^\infty\frac{x^{3n}}{\prod_{k=1}^n(3k-1)(3k)}',r'|a_{n+1}/a_n|=|x|^3/[(3n+2)(3n+3)]\to0',r'A^{\prime\prime}=xA,\quad A(0)=1,\quad A^{\prime}(0)=0',r'A(x)=\frac{\Gamma(2/3)}2[3^{2/3}\operatorname{Ai}(x)+3^{1/6}\operatorname{Bi}(x)]'],r'\operatorname{domain}A=\mathbb R','SymPy의 내장 에어리 함수 표현을 mpmath로 계산하여 부분합과 함께 그렸다. 항 수가 늘면 모든 고정 유계 구간에서 함수에 가까워진다. 초기조건을 이용하면 통상적인 에어리 함수 두 개의 정확한 선형결합이 정해진다.','The SymPy built-in Airy expression is evaluated with mpmath and plotted alongside partial sums. Increasing the term count improves the approximation on every fixed bounded interval. The initial conditions determine the displayed exact linear combination of the standard Airy functions.',sub='abc')
calc(42,r'f(x)=\sum_{n=0}^\infty c_nx^n,\quad c_{n+4}=c_n\ (n\ge0)','수렴 구간과 함수 공식을 구하라.','Find the convergence interval and a formula for the function.',[r'P(x)=c_0+c_1x+c_2x^2+c_3x^3',r'f(x)=P(x)\sum_{k=0}^\infty x^{4k}=P(x)/(1-x^4)\quad(|x|<1)',r'(c_0,c_1,c_2,c_3)\ne(0,0,0,0):\quad x=\pm1\Rightarrow\text{terms do not tend to zero}'],r'f(x)=\frac{c_0+c_1x+c_2x^2+c_3x^3}{1-x^4},\quad I=(-1,1)\text{ unless all coefficients vanish};\quad f=0,\ I=\mathbb R\text{ in that case}','경계에서 묶은 항들의 합이 우연히 영이어도 원래 개별 항이 영으로 가지 않으면 급수는 발산한다.','Even if grouped boundary terms cancel, the original series diverges whenever its individual terms fail to vanish.')
calc(43,r'f(x)=1+2x+x^2+2x^3+x^4+\cdots','수렴 구간과 명시적 함수 공식을 구하라.','Find the convergence interval and explicit sum.',[r'f(x)=\sum_{n=0}^\infty x^{2n}+2\sum_{n=0}^\infty x^{2n+1}',r'f(x)=(1+2x)/(1-x^2)\quad(|x|<1)',r'x=\pm1:\quad|a_n|\in\{1,2\}\not\to0'],r'f(x)=(1+2x)/(1-x^2),\quad I=(-1,1)')
calc(44,r'f_n(x)=\sin(nx)/n^2','원급수는 모든 입력에서 수렴하지만 일계 도함수 급수는 짝수 원주율 배에서 발산함을 보여라. 이계 도함수 급수가 수렴하는 모든 입력을 구하라.','Show that the original series converges everywhere but the first-derivative series diverges at even multiples of pi. Find all inputs where the second-derivative series converges.',[r'|f_n(x)|\le1/n^2\Rightarrow\sum f_n(x)\text{ absolutely convergent for all }x',r'f_n^{\prime}(x)=\cos(nx)/n,\quad x=2k\pi\Rightarrow\sum f_n^{\prime}(x)=\sum1/n',r'f_n^{\prime\prime}(x)=-\sin(nx)',r'\sin(nx)\to0,\ \sin x\ne0\Rightarrow\cos(nx)=\frac{\sin((n+1)x)-\sin(nx)\cos x}{\sin x}\to0',r'\sin^2(nx)+\cos^2(nx)=1\quad\text{contradiction};\quad x=k\pi\Rightarrow\sin(nx)=0'],r'\sum f_n^{\prime\prime}(x)\text{ converges exactly when }x\in\pi\mathbb Z')
calc(45,r'f(x)=\sum_{n=1}^\infty x^n/n^2','원급수와 일계·이계 항별 도함수 급수의 수렴 구간을 각각 구하라.','Find the convergence intervals of the original series and its first and second termwise derivatives.',[r'f:\quad x=\pm1\text{ both absolutely convergent}',r'f^{\prime}(x)=\sum_{n=1}^\infty x^{n-1}/n:\quad x=-1\text{ alternating convergent},\ x=1\text{ divergent}',r'f^{\prime\prime}(x)=\sum_{n=2}^\infty(n-1)x^{n-2}/n:\quad x=\pm1\Rightarrow|a_n|\to1'],r'I_f=[-1,1],\quad I_{f^{\prime}}=[-1,1),\quad I_{f^{\prime\prime}}=(-1,1)')
calc(46,r'\sum_{n=0}^\infty x^n=1/(1-x),\quad|x|<1','(a) 한 번 미분한 급수 (b) 인덱스와 거듭제곱의 곱 급수 및 이분의 일 대입값 (c) 연속 정수 곱 급수, 그 이분의 일 대입값, 인덱스 제곱 급수의 이분의 일 대입값을 구하라.','Find (a) the differentiated series, (b) the index-times-power sum and its value at one half, and (c) the consecutive-index-product sum, its value at one half, and the squared-index sum at one half.',[r'\text{(a)}\sum_{n=1}^\infty nx^{n-1}=1/(1-x)^2',r'\text{(b)(i)}\sum_{n=1}^\infty nx^n=x/(1-x)^2;\quad\text{(ii)}\sum_{n=1}^\infty n/2^n=2',r'\text{(c)(i)}\sum_{n=2}^\infty n(n-1)x^n=2x^2/(1-x)^3;\quad\text{(ii)}\sum_{n=2}^\infty(n^2-n)/2^n=4',r'\text{(iii)}\sum_{n=1}^\infty n^2/2^n=4+2=6'],r'\text{(a)}\frac1{(1-x)^2};\quad\text{(b)}\frac{x}{(1-x)^2},2;\quad\text{(c)}\frac{2x^2}{(1-x)^3},4,6',sub='abc')
calc(47,r'f(x)=1/(1-x),\quad h(x)=xf^{\prime}(x)+x^2f^{\prime\prime}(x)','함수의 멱급수와 반지름을 구하고 인덱스 제곱 나누기 이의 거듭제곱 급수의 합을 구하라.','Find the power series and radius, then evaluate the squared-index over powers-of-two sum.',[r'h(x)=\sum_{n=1}^\infty[n+n(n-1)]x^n=\sum_{n=1}^\infty n^2x^n',r'h(x)=x/(1-x)^2+2x^2/(1-x)^3=x(1+x)/(1-x)^3',r'h(1/2)=6'],r'h(x)=\sum_{n=1}^\infty n^2x^n,\quad R=1,\quad\sum_{n=1}^\infty n^2/2^n=6')
calc(48,r'1/9801=1/99^2','역제곱 기하급수를 이용하여 두 자리 블록이 순서대로 나오되 구십팔이 빠진 순환소수임을 증명하라.','Use the differentiated geometric series to prove the repeating decimal whose two-digit blocks are ordered except for the missing ninety-eight.',[r'\frac1{9801}=\frac1{10000}(1-1/100)^{-2}=\sum_{n=1}^\infty\frac n{100^{n+1}}',r'B=100,\quad P=\sum_{j=0}^{97}jB^{98-j}+99',r'(B-1)^2P=B^{99}-1',r'0.\overline{00\ 01\ 02\ \cdots\ 96\ 97\ 99}=P/(B^{99}-1)=1/9801'],r'\frac1{9801}=0.\overline{00\ 01\ 02\ \cdots\ 96\ 97\ 99}','계수가 백 이상이 되면서 생기는 자리올림까지 포함해야 한다. 유한 블록의 정수 항등식으로 빠진 구십팔과 반복 주기를 검증한다.','Carries from coefficients at least one hundred must be included. The finite-block integer identity verifies the missing ninety-eight and the repeating block.')
calc(49,r'\arctan x=\sum_{n=0}^\infty(-1)^nx^{2n+1}/(2n+1)','역탄젠트 급수에 적절한 값을 넣어 원주율의 급수를 증명하라.','Substitute a suitable value into the arctangent series to prove a series for pi.',[r'x=1/\sqrt3,\quad\arctan(1/\sqrt3)=\pi/6',r'\pi/6=\frac1{\sqrt3}\sum_{n=0}^\infty\frac{(-1)^n}{(2n+1)3^n}'],r'\pi=2\sqrt3\sum_{n=0}^\infty\frac{(-1)^n}{(2n+1)3^n}')
calc(50,r'I=\int_0^{1/2}\frac{dx}{x^2-x+1}','(a) 완전제곱으로 적분을 계산하고 (b) 세제곱 합 인수분해와 멱급수로 원주율 급수를 유도하라.','(a) Evaluate the integral by completing the square and (b) use a sum-of-cubes factorization and a power series to derive a pi series.',[r'\text{(a)} x^2-x+1=(x-1/2)^2+3/4',r'I=\frac2{\sqrt3}\left[\arctan\frac{2x-1}{\sqrt3}\right]_0^{1/2}=\frac\pi{3\sqrt3}',r'\text{(b)} (x+1)(x^2-x+1)=x^3+1',r'I=\int_0^{1/2}\frac{1+x}{1+x^3}\,dx=\sum_{n=0}^\infty(-1)^n\left[\frac{(1/2)^{3n+1}}{3n+1}+\frac{(1/2)^{3n+2}}{3n+2}\right]'],r'\text{(a)} I=\pi/(3\sqrt3);\quad\text{(b)}\pi=\frac{3\sqrt3}4\sum_{n=0}^\infty\frac{(-1)^n}{8^n}\left(\frac2{3n+1}+\frac1{3n+2}\right)',sub='ab')
calc(51,r'\sum_{n=0}^\infty c_nx^n\text{ has radius }R','항별 미분·적분 급수의 반지름이 원래와 같음을 비율 계산으로 보이고 일반 경우의 논증을 보완하라.','Use ratio calculations to show radius invariance under termwise differentiation and integration, supplementing the argument for the general case.',[r'\rho=\lim|c_n/c_{n+1}|:\quad\lim\left|\frac{nc_n}{(n+1)c_{n+1}}\right|=\rho,\quad\lim\left|\frac{c_n/(n+1)}{c_{n+1}/(n+2)}\right|=\rho',r'\lim n^{1/n}=1,\quad\lim(n+1)^{-1/n}=1',r'\limsup\sqrt[n]{|nc_n|}=\limsup\sqrt[n]{|c_n|}=\limsup\sqrt[n]{|c_n/(n+1)|}',r'\text{A fixed shift in powers does not change the radius.}'],r'R_{\mathrm{derivative}}=R_{\mathrm{integral}}=R','비율 극한이 존재하면 첫 계산으로 끝난다. 임의의 멱급수에서는 그 극한이 없거나 계수가 영일 수 있으므로 근의 상극한 논증을 사용한다. 이는 영·무한 반지름도 포함한다.','The ratio calculation suffices when that limit exists. For an arbitrary power series the ratio may fail to exist or coefficients may vanish; the root-limsup argument handles these cases, including zero and infinite radii.')
def overlay(q,f,term,start,xlim,ylim,Ns):
 xa,xb=xlim;ya,yb=ylim;X=lambda z:55+550*(z-xa)/(xb-xa);Y=lambda z:370-330*(z-ya)/(yb-ya)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 650 455"><defs><clipPath id="view"><rect x="55" y="40" width="550" height="330"/></clipPath></defs><rect width="650" height="455" fill="white"/>',f'<path d="M55 {Y(0)}H605M{X(0)} 40V370" stroke="#8491a3" fill="none"/>']
 grid=[xa+(xb-xa)*i/450 for i in range(451)]
 for j,N in enumerate(Ns):
  c=['#b16f22','#229364','#ce5276','#7953ba','#2984bb'][j%5];pts=' '.join(f'{X(z):.3f},{Y(sum(term(z,k)for k in range(start,N+1))):.3f}'for z in grid);out.append(f'<polyline points="{pts}" fill="none" stroke="{c}" stroke-width="1.8" clip-path="url(#view)"/><text x="{65+100*j}" y="414" fill="{c}" font-size="12">N={N}</text>')
 segment=[]
 for z in grid:
  v=f(z)
  if v is None:
   if segment:out.append('<polyline points="'+' '.join(segment)+'" fill="none" stroke="#111827" stroke-width="3" clip-path="url(#view)"/>');segment=[]
  else:segment.append(f'{X(z):.3f},{Y(float(v)):.3f}')
 if segment:out.append('<polyline points="'+' '.join(segment)+'" fill="none" stroke="#111827" stroke-width="3" clip-path="url(#view)"/>')
 for z in [xa,0,xb]:out.append(f'<text x="{X(z)-10}" y="390" font-size="12">{z:g}</text>')
 for v in [ya,0,yb]:out.append(f'<text x="8" y="{Y(v)+4}" font-size="12">{v:g}</text>')
 out.extend(['<text x="65" y="443" font-size="13">Black: function. Colors: partial sums through index N.</text>','</svg>']);path=BASE/f'exercise-content/assets/s11-9-{q}.svg';path.write_text(''.join(out));next(e for e in items if e['number']==q)['figure']={'src':f'../exercise-content/assets/{path.name}','alt':bi('함수와 여러 멱급수 부분합의 비교','Comparison of a function and several power-series partial sums'),'caption':bi('함수식과 계수로 직접 생성한 자체 그래프.','Original plots computed directly from the function and coefficients.')}
for q,fun,rep,I,f,term,start,xlim,ylim in plotdata:overlay(q,f,term,start,xlim,ylim,[start,start+1,start+3,start+7,start+15])
aco=[float(airycoeff(j))for j in range(12)];overlay(41,airyfun,lambda z,j:aco[j]*z**(3*j),0,[-3,3],[-3,16],[1,2,3,5,10])
items.sort(key=lambda e:e['number']);assert [e['number']for e in items]==list(range(1,52))
raw={'section':'11.9','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[831,832],'pdfPages':[868,869]},'scope':{'kind':'exercise','numbers':list(range(1,52)),'total':51,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s11-9.json')
for ex in items:
 for key in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[key]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[key]['en']),(ex['number'],key)
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
# Independent high-precision quadrature agrees with each integrated series.
funints=[(lambda z:z/(1+z**3),mp.mpf('.3')),(lambda z:mp.atan(z/2),mp.mpf('.5')),(lambda z:z*mp.log(1+z*z),mp.mpf('.2')),(lambda z:z*z/(1+z**4),mp.mpf('.3'))]
for row,(fn,end) in zip(numerics[:4],funints):assert abs(mp.quad(fn,[0,end])-sum(row[3](j)for j in range(row[4],35)))<mp.mpf('1e-45')
assert abs(airyfun(0)-1)<mp.mpf('1e-55');assert abs(mp.diff(airyfun,0))<mp.mpf('1e-55')
for z in [-3,-1,1,3]:
 approx=sum(mp.mpf(str(airycoeff(j)))*mp.mpf(z)**(3*j)for j in range(35));assert abs(approx-airyfun(z))<mp.mpf('1e-45')
P=sum(j*100**(98-j)for j in range(98))+99;assert 9801*P==100**99-1
for j in range(1,9):
 c=lambda k:S.Rational((-1)**k,4**k*math.factorial(k)**2);d=lambda k:S.Rational((-1)**k,2**(2*k+1)*math.factorial(k)*math.factorial(k+1))
 assert 4*j*j*c(j)+c(j-1)==0;assert 4*j*(j+1)*d(j)+d(j-1)==0
(BASE/'exercise-content/s11-9.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('11.9: 51 cards, 5 SVG; schema, math parity, XML, quadrature, Airy/Bessel identities and repeating-decimal integer identity verified')
