from early_helpers import *
from math import sin,cos,sqrt,exp,sinh,cosh,pi
b=Book('12.6',[919,920,921])
def add(n,title,st,steps,ans,parts=[],check=None):b.add(n,919 if n<=22 else 920 if n<=50 else 921,title,st,steps,ans,parts,check=check)
def graph(n,f,ur,vr,title):b.plot(n,[(f,ur,vr,title)])
add(1,('평면곡선과 주면','Plane curves and cylinders'),('(a) '+r'\(y=x^2\)'+'을 평면에서, (b) 공간에서 해석하고 (c) '+r'\(z=y^2\)'+'의 공간곡면을 설명하라.','Interpret (a) '+r'\(y=x^2\)'+' in the plane, (b) in space, and (c) the surface '+r'\(z=y^2\)'+'.'),[('(a) 평면에서는 위로 열린 포물선이다.','(a) In the plane this is a parabola opening upward.'),('(b) z가 자유이므로 포물선을 z축 방향으로 늘인 주면이다. (c) x가 자유이므로 x축 평행 생성선을 가진 포물주면이다.','(b) Free z extends the parabola parallel to the z-axis. (c) Free x gives a parabolic cylinder with generators parallel to x.')],('(a) 포물선. (b) z축 평행 포물주면. (c) x축 평행 포물주면.','(a) Parabola. (b) Parabolic cylinder parallel to z. (c) Parabolic cylinder parallel to x.'),['a','b','c'])
b.plot(1,[(lambda u,v:(u,u*u,0),(-2,2),(0,1),'(a) y=x² in R²'),(lambda u,v:(u,u*u,v),(-2,2),(-2,2),'(b) z free'),(lambda u,v:(v,u,u*u),(-2,2),(-2,2),'(c) x free')])
add(2,('지수함수의 주면','Exponential cylinders'),('(a) '+r'\(y=e^x\)'+'의 평면곡선, (b) 공간곡면, (c) '+r'\(z=e^y\)'+'의 곡면을 그려 설명하라.','Sketch and describe (a) the plane curve '+r'\(y=e^x\)'+'; (b) its surface in space; (c) '+r'\(z=e^y\)'+'.'),[('(a) 양의 y값을 가지며 증가하는 지수곡선이다.','(a) It is an increasing exponential curve with positive y.'),('(b) z가 식에 없으므로 지수곡선을 z방향으로 평행이동한다. (c) x가 없으므로 yz평면 지수곡선을 x방향으로 늘인다.','(b) z is absent, so translate the exponential curve along z. (c) x is absent, so extend the yz-plane exponential along x.')],('(a) 지수곡선. (b) z축 평행 지수주면. (c) x축 평행 지수주면.','(a) Exponential curve. (b) Exponential cylinder parallel to z. (c) Exponential cylinder parallel to x.'),['a','b','c'])
b.plot(2,[(lambda u,v:(u,exp(u),0),(-2,2),(0,1),'(a) y=exp(x)'),(lambda u,v:(u,exp(u),v),(-2,2),(-2,2),'(b) z free'),(lambda u,v:(v,u,exp(u)),(-2,2),(-2,2),'(c) x free')])
data=[
(3,r'x^2+z^2=4','y축 평행 반지름 2의 원기둥','circular cylinder of radius 2 along y',r'y=k:\ x^2+z^2=4',lambda u,v:(2*cos(u),v,2*sin(u)),(0,2*pi),(-3,3)),
(4,r'y^2+9z^2=9','x축 평행 타원기둥(반축 3,1)','elliptic cylinder along x, with semiaxes 3 and 1',r'x=k:\ y^2/9+z^2=1',lambda u,v:(v,3*cos(u),sin(u)),(0,2*pi),(-3,3)),
(5,r'x^2+y+1=0','음의 y방향 포물주면, 생성선은 z축 평행','parabolic cylinder opening toward negative y, parallel to z',r'y=-x^2-1',lambda u,v:(u,-u*u-1,v),(-2,2),(-2,2)),
(6,r'z=-\sqrt x','x=z²의 z≤0 반쪽 포물주면','the z≤0 half of the parabolic cylinder x=z²',r'x=z^2,\quad z\le0,\quad y\in\mathbb R',lambda u,v:(u*u,v,-u),(0,2),(-2,2)),
(7,r'xy=1','z축 평행 쌍곡주면','hyperbolic cylinder parallel to z',r'y=1/x,\quad x\ne0', [lambda u,v:(u,1/u,v),lambda u,v:(-u,-1/u,v)],(.25,3),(-2,2)),
(8,r'z=\sin y','x축 평행 사인 주면','sinusoidal cylinder parallel to x',r'x=k:\ z=\sin y',lambda u,v:(v,u,sin(u)),(-2*pi,2*pi),(-2,2))]
for n,f,k,e,trace,fun,ur,vr in data:
 add(n,('주면의 분류','Classifying a cylinder'),('곡면을 설명하고 그려라. '+r'\('+f+r'\).','Describe and sketch '+r'\('+f+r'\).'),fs(trace)+[('식에 없는 좌표는 자유로워 그 축에 평행한 생성선을 만든다.','The missing coordinate is free and produces generators parallel to its axis.')],(k+'.',e+'.'));graph(n,fun,ur,vr,f.replace('\\',''))
add(9,('그림에서 곡면식 찾기','Equation from a surface sketch'),('x방향으로 사인파처럼 변하고 y방향으로 동일한 단면이 반복되는 원본 주면에 가능한 식을 쓰라.','Give a possible equation for the source sinusoidal cylinder varying along x and extending unchanged along y.'),[('y방향 생성선이 직선이므로 식은 y에 의존하지 않는다.','Straight generators along y mean that y does not appear.'),(r'원점에서 양의 x방향으로 내려가는 사인파에는 \(z=-\sin x\)를 선택할 수 있다.',r'A sine wave descending from the origin in the positive x-direction can be modeled by \(z=-\sin x\).')],same(r'\[z=-\sin x\quad\text{(one possible equation)}.\]'));graph(9,lambda u,v:(u,v,-sin(u)),(-2*pi,2*pi),(-2,2),'One possible sinusoidal cylinder')
add(10,('삼차곡선의 주면','A cubic cylinder'),('원본처럼 yz평면의 S자 곡선을 x방향으로 늘인 곡면의 가능한 식을 쓰라.','Give a possible equation for the source S-shaped yz-curve extended along x.'),[('x가 자유이므로 yz평면의 단면식만 정하면 된다.','Since x is free, determine only the yz cross-section.'),(r'원점을 지나 증가하는 S자 단면의 한 예는 \(z=y^3\)이다.',r'One increasing S-shaped section through the origin is \(z=y^3\).')],same(r'\[z=y^3\quad\text{(one possible equation)}.\]'));graph(10,lambda u,v:(v,u,u**3),(-1.4,1.4),(-2,2),'z=y³')
add(11,('일엽쌍곡면과 이동','One-sheeted hyperboloids and translation'),('(a) '+r'\(x^2+y^2-z^2=1\)'+'의 자취로 형태를 설명하고 (b) '+r'\(x^2-y^2+z^2=1\)'+'과 (c) '+r'\(x^2+y^2+2y-z^2=0\)'+'으로 바꾼 효과를 설명하라.','Use traces to explain (a) '+r'\(x^2+y^2-z^2=1\)'+' and describe the changes to (b) '+r'\(x^2-y^2+z^2=1\)'+' and (c) '+r'\(x^2+y^2+2y-z^2=0\)'+'.'),fs(r'(a)\ z=k:\ x^2+y^2=1+k^2;\quad x=k:\ y^2-z^2=1-k^2;\quad y=k:\ x^2-z^2=1-k^2')+[('(a) 수평 단면은 원, 수직 단면은 쌍곡선(특정 값에서 두 직선)이다. z축 둘레에서 끊기지 않는 일엽쌍곡면이다.','(a) Horizontal traces are circles; vertical traces are hyperbolas or pairs of lines. It is a connected one-sheeted hyperboloid about z.'),('(b) 음의 제곱항이 y로 바뀌어 축이 y축이 된다.','(b) The negative square moves to y, so the axis becomes y.'),same(r'(c) \(x^2+(y+1)^2-z^2=1\).')],('(a) z축 일엽쌍곡면. (b) y축으로 회전. (c) y방향으로 -1만큼 평행이동.','(a) One-sheeted hyperboloid along z. (b) Rotate the axis to y. (c) Translate by -1 in y.'),['a','b','c']);b.plot(11,[(lambda u,v:(cosh(u)*cos(v),cosh(u)*sin(v),sinh(u)),(-1.4,1.4),(0,2*pi),'(a) axis z'),(lambda u,v:(cosh(u)*cos(v),sinh(u),cosh(u)*sin(v)),(-1.4,1.4),(0,2*pi),'(b) axis y'),(lambda u,v:(cosh(u)*cos(v),-1+cosh(u)*sin(v),sinh(u)),(-1.4,1.4),(0,2*pi),'(c) center (0,-1,0)')])
add(12,('이엽쌍곡면의 자취','Traces of a two-sheeted hyperboloid'),('(a) '+r'\(-x^2-y^2+z^2=1\)'+'의 자취를 찾아 분류하고 (b) '+r'\(x^2-y^2-z^2=1\)'+'로 바꾼 곡면을 그려라.','Find traces and classify (a) '+r'\(-x^2-y^2+z^2=1\)'+'; (b) sketch the change to '+r'\(x^2-y^2-z^2=1\)'+'.'),fs(r'z=k:\ x^2+y^2=k^2-1;\quad x=k:\ z^2-y^2=1+k^2;\quad y=k:\ z^2-x^2=1+k^2')+[('|z|<1에서는 점이 없고 z=±1에서 꼭짓점이 생긴다. 양의 제곱항이 x로 바뀌면 분리된 두 잎의 축이 x축으로 옮겨간다.','There are no points for |z|<1, with vertices at z=±1. Moving the positive square to x makes x the axis of the two sheets.')],('(a) z축 이엽쌍곡면. (b) x축 이엽쌍곡면, 꼭짓점 (±1,0,0).','(a) Two-sheeted hyperboloid along z. (b) Two-sheeted hyperboloid along x, vertices (±1,0,0).'),['a','b']);b.plot(12,[([lambda u,v:(u*cos(v),u*sin(v),sqrt(1+u*u)),lambda u,v:(u*cos(v),u*sin(v),-sqrt(1+u*u))],(0,2),(0,2*pi),'(a) axis z'),([lambda u,v:(sqrt(1+u*u),u*cos(v),u*sin(v)),lambda u,v:(-sqrt(1+u*u),u*cos(v),u*sin(v))],(0,2),(0,2*pi),'(b) axis x')])
# Surface classification and a direct parametrization for every required graph.
rows=[
(13,r'x=y^2+4z^2',r'x=k:\ y^2+4z^2=k;\ y=k:\ x=k^2+4z^2;\ z=k:\ x=y^2+4k^2','양의 x방향 타원포물면','elliptic paraboloid opening in positive x',lambda u,v:(u*u,u*cos(v),u*sin(v)/2),(0,2),(0,2*pi)),
(14,r'4x^2+9y^2+9z^2=36',r'x^2/9+y^2/4+z^2/4=1','반축 3,2,2인 타원면','ellipsoid with semiaxes 3,2,2',lambda u,v:(3*sin(u)*cos(v),2*sin(u)*sin(v),2*cos(u)),(0,pi),(0,2*pi)),
(15,r'x^2=4y^2+z^2',r'x=k:\ 4y^2+z^2=k^2;\ y=k:\ x^2-z^2=4k^2;\ z=k:\ x^2-4y^2=k^2','x축 타원뿔','elliptic cone along x',lambda u,v:(u,u*cos(v)/2,u*sin(v)),(-2,2),(0,2*pi)),
(16,r'z^2-4x^2-y^2=4',r'z^2/4-x^2-y^2/4=1;\ z=k:\ 4x^2+y^2=k^2-4','z축 이엽쌍곡면, 꼭짓점 z=±2','two-sheeted hyperboloid along z, vertices z=±2',[lambda u,v:(u*cos(v),2*u*sin(v),2*sqrt(1+u*u)),lambda u,v:(u*cos(v),2*u*sin(v),-2*sqrt(1+u*u))],(0,1.5),(0,2*pi)),
(17,r'9y^2+4z^2=x^2+36',r'y^2/4+z^2/9-x^2/36=1;\ x=k:\ y^2/4+z^2/9=1+k^2/36','x축 일엽쌍곡면','one-sheeted hyperboloid along x',lambda u,v:(6*sinh(u),2*cosh(u)*cos(v),3*cosh(u)*sin(v)),(-1,1),(0,2*pi)),
(18,r'3x^2+y+3z^2=0',r'y=-3(x^2+z^2);\ y=k:\ x^2+z^2=-k/3','음의 y방향 원포물면','circular paraboloid opening in negative y',lambda u,v:(u*cos(v),-3*u*u,u*sin(v)),(0,1.5),(0,2*pi)),
(19,r'x^2/9+y^2/25+z^2/4=1',r'x=0:\ y^2/25+z^2/4=1;\ y=0:\ x^2/9+z^2/4=1;\ z=0:\ x^2/9+y^2/25=1','반축 3,5,2인 타원면','ellipsoid with semiaxes 3,5,2',lambda u,v:(3*sin(u)*cos(v),5*sin(u)*sin(v),2*cos(u)),(0,pi),(0,2*pi)),
(20,r'3x^2-y^2+3z^2=0',r'y^2=3(x^2+z^2);\ y=k:\ x^2+z^2=k^2/3','y축 원뿔','circular cone along y',lambda u,v:(u*cos(v)/sqrt(3),u,u*sin(v)/sqrt(3)),(-3,3),(0,2*pi)),
(21,r'y=z^2-x^2',r'x=k:\ y=z^2-k^2;\ z=k:\ y=k^2-x^2;\ y=k:\ z^2-x^2=k','쌍곡포물면','hyperbolic paraboloid',lambda u,v:(u,v*v-u*u,v),(-2,2),(-2,2)),
(22,r'x=y^2-z^2',r'y=k:\ x=k^2-z^2;\ z=k:\ x=y^2-k^2;\ x=k:\ y^2-z^2=k','쌍곡포물면','hyperbolic paraboloid',lambda u,v:(u*u-v*v,u,v),(-2,2),(-2,2)),
(23,r'x^2+4y^2+9z^2=1',r'(a_x,a_y,a_z)=(1,1/2,1/3)','그림 VII: x축이 가장 긴 타원면','Graph VII: an ellipsoid longest along x',lambda u,v:(sin(u)*cos(v),sin(u)*sin(v)/2,cos(u)/3),(0,pi),(0,2*pi)),
(24,r'9x^2+4y^2+z^2=1',r'(a_x,a_y,a_z)=(1/3,1/2,1)','그림 IV: z축이 가장 긴 타원면','Graph IV: an ellipsoid longest along z',lambda u,v:(sin(u)*cos(v)/3,sin(u)*sin(v)/2,cos(u)),(0,pi),(0,2*pi)),
(25,r'x^2-y^2+z^2=1',r'y=k:\ x^2+z^2=1+k^2','그림 II: y축 일엽쌍곡면','Graph II: one-sheeted hyperboloid along y',lambda u,v:(cosh(u)*cos(v),sinh(u),cosh(u)*sin(v)),(-1.4,1.4),(0,2*pi)),
(26,r'-x^2+y^2-z^2=1',r'y=k:\ x^2+z^2=k^2-1','그림 III: y축 이엽쌍곡면','Graph III: two-sheeted hyperboloid along y',[lambda u,v:(u*cos(v),sqrt(1+u*u),u*sin(v)),lambda u,v:(u*cos(v),-sqrt(1+u*u),u*sin(v))],(0,2),(0,2*pi)),
(27,r'y=2x^2+z^2',r'y=k:\ 2x^2+z^2=k','그림 VI: 양의 y방향 타원포물면','Graph VI: elliptic paraboloid opening in positive y',lambda u,v:(u*cos(v)/sqrt(2),u*u,u*sin(v)),(0,2),(0,2*pi)),
(28,r'y^2=x^2+2z^2',r'y=k:\ x^2+2z^2=k^2','그림 I: y축 타원뿔','Graph I: elliptic cone along y',lambda u,v:(u*cos(v),u,u*sin(v)/sqrt(2)),(-2,2),(0,2*pi)),
(29,r'x^2+2z^2=1',r'y=k:\ x^2+2z^2=1','그림 VIII: y축 타원기둥','Graph VIII: elliptic cylinder along y',lambda u,v:(cos(u),v,sin(u)/sqrt(2)),(0,2*pi),(-2,2)),
(30,r'y=x^2-z^2',r'x=0:\ y=-z^2;\ z=0:\ y=x^2','그림 V: 쌍곡포물면','Graph V: hyperbolic paraboloid',lambda u,v:(u,u*u-v*v,v),(-2,2),(-2,2)),
(33,r'y^2=x^2+z^2/9',r'y^2-x^2-z^2/9=0','y축 타원뿔','elliptic cone along y',lambda u,v:(u*cos(v),u,3*u*sin(v)),(-1,1),(0,2*pi)),
(34,r'4x^2-y+2z^2=0',r'y=4x^2+2z^2','양의 y방향 타원포물면','elliptic paraboloid opening in positive y',lambda u,v:(u*cos(v)/2,u*u,u*sin(v)/sqrt(2)),(0,2),(0,2*pi)),
(35,r'x^2+2y-2z^2=0',r'y=z^2-x^2/2','쌍곡포물면','hyperbolic paraboloid',lambda u,v:(u,v*v-u*u/2,v),(-2,2),(-2,2)),
(36,r'y^2=x^2+4z^2+4',r'y^2/4-x^2/4-z^2=1','y축 이엽쌍곡면, 꼭짓점 y=±2','two-sheeted hyperboloid along y, vertices y=±2',[lambda u,v:(2*u*cos(v),2*sqrt(1+u*u),u*sin(v)),lambda u,v:(2*u*cos(v),-2*sqrt(1+u*u),u*sin(v))],(0,1.5),(0,2*pi)),
(37,r'x^2+y^2-2x-6y-z+10=0',r'z=(x-1)^2+(y-3)^2','꼭짓점 (1,3,0)의 양의 z방향 원포물면','circular paraboloid opening in positive z, vertex (1,3,0)',lambda u,v:(1+u*cos(v),3+u*sin(v),u*u),(0,2),(0,2*pi)),
(38,r'x^2-y^2-z^2-4x-2z+3=0',r'(x-2)^2-y^2-(z+1)^2=0','꼭짓점 (2,0,-1), x축 방향 원뿔','circular cone along x with vertex (2,0,-1)',lambda u,v:(2+u,u*cos(v),-1+u*sin(v)),(-2,2),(0,2*pi)),
(39,r'x^2-y^2+z^2-4x-2z=0',r'(x-2)^2/5+(z-1)^2/5-y^2/5=1','중심 (2,0,1)의 y축 일엽쌍곡면','one-sheeted hyperboloid along y, center (2,0,1)',lambda u,v:(2+sqrt(5)*cosh(u)*cos(v),sqrt(5)*sinh(u),1+sqrt(5)*cosh(u)*sin(v)),(-1,1),(0,2*pi)),
(40,r'4x^2+y^2+z^2-24x-8y+4z+55=0',r'4(x-3)^2+(y-4)^2+(z+2)^2=1','중심 (3,4,-2), 반축 1/2,1,1인 타원면','ellipsoid centered at (3,4,-2), semiaxes 1/2,1,1',lambda u,v:(3+sin(u)*cos(v)/2,4+sin(u)*sin(v),-2+cos(u)),(0,pi),(0,2*pi)),
(41,r'-4x^2-y^2+z^2=1',r'z^2-4x^2-y^2=1','z축 이엽쌍곡면','two-sheeted hyperboloid along z',[lambda u,v:(u*cos(v)/2,u*sin(v),sqrt(1+u*u)),lambda u,v:(u*cos(v)/2,u*sin(v),-sqrt(1+u*u))],(0,2),(0,2*pi)),
(42,r'x^2-y^2-z=0',r'z=x^2-y^2','쌍곡포물면','hyperbolic paraboloid',lambda u,v:(u,v,u*u-v*v),(-2,2),(-2,2)),
(43,r'-4x^2-y^2+z^2=0',r'z^2=4x^2+y^2','z축 타원뿔','elliptic cone along z',lambda u,v:(u*cos(v)/2,u*sin(v),u),(-2,2),(0,2*pi)),
(44,r'x^2-6x+4y^2-z=0',r'z=(x-3)^2+4y^2-9','꼭짓점 (3,0,-9)의 타원포물면','elliptic paraboloid with vertex (3,0,-9)',lambda u,v:(3+u*cos(v),u*sin(v)/2,u*u-9),(0,3),(0,2*pi))]
for n,f,trace,k,e,fun,ur,vr in rows:
 instruction=('원본 I–VIII 그림과 대응시키고 이유를 설명하라.','Match to source graphs I–VIII and explain.') if 23<=n<=30 else ('자취와 표준형으로 분류하고 그려라.','Use traces and standard form to classify and sketch.')
 add(n,('이차곡면의 분류','Classifying quadrics'),(instruction[0]+r'\('+f+r'\).',instruction[1]+r'\('+f+r'\).'),fs(trace)+[('제곱항의 부호·계수와 빠진 변수에서 축, 크기 및 단면의 종류를 판정한다.','The signs and coefficients of squared terms and any missing variable determine the axis, scale, and trace types.')],(k+'.',e+'.'));graph(n,fun,ur,vr,e)
add(31,('자취에서 곡면 복원','Reconstructing a surface from traces'),('원본의 x=k 단면은 음의 y로 열린 포물선이며 y=k 단면은 k가 -2,-1,0,1로 증가할수록 줄어들어 마지막에 점이 되는 원이다. 가능한 이차곡면을 식별하고 그려라.','The source x=k sections are parabolas opening toward negative y; y=k sections shrink through k=-2,-1,0,1, ending at a point. Identify and sketch a compatible quadric.'),fs(r'y=1-x^2-z^2;\quad x=k:\ y=1-k^2-z^2;\quad y=k:\ x^2+z^2=1-k'),('꼭짓점 (0,1,0)에서 음의 y로 열린 원포물면. '+r'\[y=1-x^2-z^2.\]','Circular paraboloid opening in negative y from (0,1,0). '+r'\[y=1-x^2-z^2.\]'));graph(31,lambda u,v:(u*cos(v),1-u*u,u*sin(v)),(0,2),(0,2*pi),'y=1-x²-z²')
add(32,('타원·쌍곡선 자취 복원','Reconstructing elliptical and hyperbolic traces'),('원본의 x=k 단면은 |k|가 증가하면 커지는 타원이고, z=k 단면은 k=0에서 y방향 쌍곡선, k=1에서 두 직선, k=2에서 x방향 쌍곡선이다. 가능한 곡면을 찾고 그려라.','Source x=k traces are expanding ellipses as |k| grows. The z=k traces open along y at k=0, become two lines at k=1, and open along x at k=2. Identify and sketch a compatible surface.'),fs(r'y^2+z^2-x^2=1;\quad x=k:\ y^2+z^2=1+k^2;\quad z=k:\ y^2-x^2=1-k^2'),('x축 일엽쌍곡면의 한 예. '+r'\[y^2+z^2-x^2=1.\]','One example is a one-sheeted hyperboloid along x. '+r'\[y^2+z^2-x^2=1.\]'));graph(32,lambda u,v:(sinh(u),cosh(u)*cos(v),cosh(u)*sin(v)),(-1.5,1.5),(0,2*pi),'y²+z²-x²=1')
add(45,('원뿔과 원기둥 사이의 영역','Region between a cone and a cylinder'),('곡면 '+r'\(z=\sqrt{x^2+y^2},\ x^2+y^2=1,\ 1\le z\le2\)'+'로 둘러싸인 영역을 그려라.','Sketch the region bounded by '+r'\(z=\sqrt{x^2+y^2},\ x^2+y^2=1,\ 1\le z\le2\)'+'.'),fs(r'r=\sqrt{x^2+y^2},\quad r=1\text{ and }r=z',r'1\le z\le2,\quad1\le r\le z,\quad0\le\theta\le2\pi'),('각 높이의 단면이 안쪽 반지름 1, 바깥 반지름 z인 고리이다.','Each horizontal section is an annulus of inner radius 1 and outer radius z.'));graph(45,[lambda u,v:(u*cos(v),u*sin(v),u),lambda u,v:(cos(v),sin(v),u),lambda u,v:(u*cos(v),u*sin(v),2)],(1,2),(0,2*pi),'1 ≤ z ≤ 2; 1 ≤ r ≤ z')
add(46,('두 포물면 사이의 영역','Region between two paraboloids'),('다음 두 포물면이 둘러싸는 영역을 그려라. '+r'\(z=x^2+y^2,\quad z=2-x^2-y^2\).','Sketch the region enclosed by '+r'\(z=x^2+y^2,\quad z=2-x^2-y^2\).'),fs(r'r^2=2-r^2\implies r=1,\ z=1',r'0\le r\le1,\quad r^2\le z\le2-r^2'),('두 포물면은 높이1의 단위원에서 만난다. 그 사이의 회전대칭 렌즈형 입체이다.','The paraboloids meet on the unit circle at height1, enclosing a rotationally symmetric lens.'));graph(46,[lambda u,v:(u*cos(v),u*sin(v),u*u),lambda u,v:(u*cos(v),u*sin(v),2-u*u)],(0,1),(0,2*pi),'r² ≤ z ≤ 2-r²')
add(47,('회전으로 만드는 포물면','Paraboloid of revolution'),('곡선 '+r'\(y=\sqrt x\)'+'을 x축 둘레로 회전한 곡면의 식을 구하라.','Find the surface obtained by rotating '+r'\(y=\sqrt x\)'+' about x.'),fs(r'r=\sqrt{y^2+z^2}=\sqrt x',r'r^2=x'),same(r'\[x=y^2+z^2\quad(x\ge0).\]'))
add(48,('회전으로 만드는 원뿔','Cone of revolution'),('직선 '+r'\(z=2y\)'+'를 z축 둘레로 회전한 곡면의 식을 구하라.','Rotate the line '+r'\(z=2y\)'+' about z and find the surface equation.'),fs(r'z^2=4y^2,\quad y^2\longrightarrow x^2+y^2'),same(r'\[z^2=4(x^2+y^2).\]'))
add(49,('초점과 준평면','Focus and directrix plane'),('점 (-1,0,0)과 평면 x=1까지의 거리가 같은 점들의 곡면을 구하고 분류하라.','Find and classify the locus equidistant from (-1,0,0) and the plane x=1.'),fs(r'\sqrt{(x+1)^2+y^2+z^2}=|x-1|',r'(x+1)^2+y^2+z^2=(x-1)^2'),('음의 x방향 원포물면. '+r'\[y^2+z^2=-4x.\]','Circular paraboloid opening in negative x. '+r'\[y^2+z^2=-4x.\]'))
add(50,('거리비로 정하는 곡면','Surface defined by a distance ratio'),('x축까지의 거리가 yz평면까지 거리의 두 배인 점들의 곡면을 구하고 분류하라.','Find and classify points whose distance to the x-axis is twice their distance to the yz-plane.'),fs(r'd(P,x\text{-axis})=\sqrt{y^2+z^2},\quad d(P,yz\text{-plane})=|x|',r'\sqrt{y^2+z^2}=2|x|'),('x축 원뿔. '+r'\[y^2+z^2=4x^2.\]','Circular cone along x. '+r'\[y^2+z^2=4x^2.\]'))
add(51,('지구 타원면 모형','An ellipsoid model of Earth'),('교재가 제시한 극반지름 6356.523km, 적도반지름 6378.137km로 (a) 타원면 방정식을 구하고 (b) z=k인 위도선, (c) y=mx인 자오선의 모양을 설명하라.','Using the textbook’s polar radius6356.523km and equatorial radius6378.137km, find (a) the ellipsoid equation; describe (b) latitude traces z=k and (c) meridian traces y=mx.'),fs(r'a=6378.137,\quad c=6356.523',r'(a)\ (x^2+y^2)/a^2+z^2/c^2=1',r'(b)\ x^2+y^2=a^2(1-k^2/c^2)',r'(c)\ (1+m^2)x^2/a^2+z^2/c^2=1'),('(a) 위 타원면 식. (b) 원(극에서 점). (c) 타원. 수치는 교재에서 주어진 값을 그대로 사용했다.','(a) The displayed ellipsoid. (b) Circles, degenerating to points at the poles. (c) Ellipses. The constants are exactly those supplied by the textbook.'),['a','b','c'])
add(52,('냉각탑의 쌍곡면 모형','Hyperboloid model of a cooling tower'),('밑면 지름280m, 밑면에서500m 위의 최소지름200m인 일엽쌍곡면 냉각탑의 식을 구하라.','Model a one-sheeted hyperboloid cooling tower with base diameter280m and minimum diameter200m at height500m above the base.'),fs(r'\frac{x^2+y^2}{100^2}-\frac{(z-500)^2}{c^2}=1',r'\frac{140^2}{100^2}-\frac{500^2}{c^2}=1\implies c^2=\frac{781250}{3}'),same(r'\[\frac{x^2+y^2}{10000}-\frac{3(z-500)^2}{781250}=1,\quad z\ge0.\]'),check=('z=0에서 반지름140, z=500에서 최소반지름100이 복원된다.','At z=0 the radius is140; at z=500 the minimum radius is100.'))
add(53,('직선으로 생성되는 안장곡면','Rulings on a hyperbolic paraboloid'),('점 (a,b,c)가 '+r'\(z=y^2-x^2\)'+' 위에 있을 때 두 직선 '+r'\((x,y,z)=(a+t,b+t,c+2(b-a)t)\)'+'과 '+r'\((x,y,z)=(a+t,b-t,c-2(b+a)t)\)'+'이 곡면 위에 있음을 보이라.','For (a,b,c) on '+r'\(z=y^2-x^2\)'+' show the lines '+r'\((x,y,z)=(a+t,b+t,c+2(b-a)t)\)'+' and '+r'\((x,y,z)=(a+t,b-t,c-2(b+a)t)\)'+' lie entirely on the surface.'),fs(r'c=b^2-a^2',r'(b+t)^2-(a+t)^2=b^2-a^2+2(b-a)t=c+2(b-a)t',r'(b-t)^2-(a+t)^2=b^2-a^2-2(b+a)t=c-2(b+a)t'),('모든 실수 t에 대해 곡면 방정식을 만족하므로 두 직선이 모두 곡면에 포함된다.','Both parametrizations satisfy the surface equation for every real t, so both lines lie on it.'))
add(54,('교선이 놓인 평면','A plane containing an intersection curve'),('다음 두 곡면의 교선이 평면에 놓임을 보이라. '+r'\(x^2+2y^2-z^2+3x=1,\quad2x^2+4y^2-2z^2-5y=0\).','Show the intersection of '+r'\(x^2+2y^2-z^2+3x=1,\quad2x^2+4y^2-2z^2-5y=0\)'+' lies in a plane.'),[('첫 방정식을 두 배하여 둘째 방정식에서 빼면 모든 이차항이 소거된다.','Subtract twice the first equation from the second; every quadratic term cancels.')]+fs(r'-6x-5y=-2'),same(r'\[6x+5y=2.\]'))
add(55,('교선과 타원 투영','Intersection and elliptic projection'),('두 곡면 '+r'\(z=x^2+y^2,\ z=1-y^2\)'+'을 '+r'\(|x|,|y|\le1.2\)'+'에서 함께 그리고 교선의 xy평면 투영이 타원임을 보이라.','Graph '+r'\(z=x^2+y^2,\ z=1-y^2\)'+' together for '+r'\(|x|,|y|\le1.2\)'+' and prove the xy-projection of their intersection is an ellipse.'),fs(r'x^2+y^2=1-y^2\implies x^2+2y^2=1',r'x=\cos t,\quad y=\sin t/\sqrt2,\quad z=1-\sin^2t/2'),same(r'\[x^2+2y^2=1\quad\text{(semiaxes }1,1/\sqrt2\text{)}.\]'));graph(55,[lambda u,v:(u,v,u*u+v*v),lambda u,v:(u,v,1-v*v)],(-1.2,1.2),(-1.2,1.2),'Blue/purple: paraboloid; orange/green: cylinder')
assert sorted(b.E)==list(range(1,56));b.save()
print('12.6:55 complete')
