from early_helpers import *
from math import *
b=Book('12.8',[925,926])
def add(n,st,steps,ans,parts=[]):b.add(n,925 if n<=7 else 926,('심화 공간기하','Problems Plus: spatial geometry'),st,steps,ans,parts)
add(1,('한 변1 m인 정육면체에 같은 반지름의 구9개를 넣는다. 하나는 상자 중심에 있고 나머지8개와 접한다. 나머지는 각 꼭짓점 근처에서 세 면에 접한다. 반지름 r을 구하라.','Nine equal balls fit in a unit-meter cube. One is centered in the cube and touches the eight others; each outer ball touches three faces near a corner. Find their radius r.'),[('상자를 [0,1]³으로 놓으면 중앙 구 중심은(1/2,1/2,1/2), 한 모서리 구 중심은(r,r,r)이다.','Use the cube[0,1]³. The central ball is centered at(1/2,1/2,1/2), and one corner ball at(r,r,r).')]+fs(r'\sqrt3(1/2-r)=2r\Rightarrow r=\frac{\sqrt3}{2(2+\sqrt3)}=\sqrt3-\frac32'),(r'(r=sqrt3-3/2approx0.232051) m.',r'(r=sqrt3-3/2approx0.232051) m.'))
add(2,('가로 L,세로 W,높이 H의 닫힌 직육면체 B로부터 거리가1 이하인 점들의 집합 S의 부피를 구하라.','Find the volume of all points within distance1 of a closed box of dimensions L,W,H.'),[('원래 상자에 여섯 면의 두께1 프리즘, 열두 모서리의 반지름1인 1/4원기둥, 여덟 꼭짓점의 1/8구를 겹치지 않게 더한다.','Partition the enlargement into the box, six unit-thick face prisms, twelve quarter-cylinders of radius1 along edges, and eight spherical octants.')]+fs(r'V_{faces}=2(LW+LH+WH)',r'V_{edges}=4(\pi/4)(L+W+H)=\pi(L+W+H)',r'V_{corners}=8\cdot\frac18\frac{4\pi}3'),same(r'[V=LWH+2(LW+LH+WH)+pi(L+W+H)+4pi/3.]'))
add(3,(r'실수 c에 대해 두 평면 (cx+y+z=c, x-cy+cz=-1)의 교선을 L이라 하자. (a)L의 대칭식,(b)L이 쓸어가는 S의 z=t 단면,(c)z=0,1 사이에 둘러싸인 부피를 구하라.',r'Let L be the intersection of (cx+y+z=c, x-cy+cz=-1), for real c. Find(a)symmetric equations for L,(b)the trace z=t of the swept surface S,(c)the volume between z=0 and1.'),fs(r'P_c=\left(\frac{c^2-1}{1+c^2},\frac{2c}{1+c^2},0\right),\quad d_c=(2c,1-c^2,-1-c^2)',r'\frac{x-(c^2-1)/(1+c^2)}{2c}=\frac{y-2c/(1+c^2)}{1-c^2}=\frac z{-1-c^2}')+[('대칭식에서 분모가0인 좌표는 그 좌표가 P_c의 값으로 고정된다는 뜻이다. 모든 c에 대해 r=P_c+s d_c가 안전한 매개식이다.','A zero denominator in the symmetric form means that coordinate is fixed at its P_c value. The parametrization r=P_c+s d_c works for every c.')]+fs(r'c(x-1)=-(y+z),\quad c(z-y)=-(x+1)\Rightarrow x^2+y^2-z^2=1',r'z=t:\quad x^2+y^2=1+t^2',r'V=\int_0^1\pi(1+t^2)\,dt=4\pi/3')+[('유한 c만 허용하면 생성선 x=1,y=z가 빠진다. c→∞인 극한 생성선을 포함한 폐포가 표준 한 겹 쌍곡면이다. 단면에서는 점(1,t,t) 하나가 빠지며 부피 계산에는 영향이 없다.','For finite c the generator x=1,y=z is omitted. Including its c→∞ limit gives the standard one-sheet hyperboloid. A single point(1,t,t) is missing from each trace, which does not affect the enclosed volume.')],same(r'(a) (r=P_c+s d_c), 위 대칭식 / symmetric form above. (b) (x^2+y^2=1+t^2) (finite c excludes ((1,t,t))). (c) (4pi/3).'),list('abc'))
wx=160*sin(5*pi/180);wy=160*cos(5*pi/180)-180;speed=hypot(wx,wy);dir=degrees(atan2(wx,-wy));heading=degrees(asin(wx/180))
add(4,('정지 공기 속 비행속도180 km/h인 비행기가 나침반상 북쪽으로30분 비행한 뒤 N5°E 방향80 km 지점에 있다. (a)바람의 속도벡터와 방향,(b)목적지인 정북쪽으로 가기 위한 조종 방향을 구하라.','A plane with airspeed180 km/h heads due north for30 minutes and ends80 km away in direction N5°E. Find(a)the wind velocity and bearing,(b)the heading needed for a due-north ground track.'),fs(r'v_g=(160\sin5^\circ,160\cos5^\circ),\quad v_a=(0,180)',rf'w=v_g-v_a=({wx:.6f},{wy:.6f})\ \mathrm{{km/h}}',r'180\sin\alpha=w_x\Rightarrow\alpha=\arcsin(160\sin5^\circ/180)')+[('첫 성분은 동쪽, 둘째는 북쪽이다. 바람의 동쪽 성분을 상쇄하도록 기수를 서쪽으로 돌린다.','Components are east and north. Turn the nose west to cancel the eastward wind component.')],(f'(a)바람({wx:.3f},{wy:.3f}) km/h, 크기{speed:.3f}, S{dir:.2f}°E 쪽으로 분다. (b)N{heading:.3f}°W.',f'(a)Wind({wx:.3f},{wy:.3f}) km/h, speed{speed:.3f}, blowing toward S{dir:.2f}°E. (b)Head N{heading:.3f}°W.'),list('ab'))
add(5,(r'(|v_1|=2,|v_2|=3,v_1cdot v_2=5)이고 (v_3=operatorname{proj}_{v_1}v_2, v_4=operatorname{proj}_{v_2}v_3,ldots)이다. (sum_{n=1}^infty|v_n|)을 구하라.',r'Given (|v_1|=2,|v_2|=3,v_1cdot v_2=5), set (v_3=operatorname{proj}_{v_1}v_2, v_4=operatorname{proj}_{v_2}v_3,ldots). Find (sum_{n=1}^infty|v_n|).'),fs(r'\cos\theta=\frac5{2\cdot3}=5/6')+[('투영 결과의 방향은 v1,v2 방향을 번갈아 따른다. 두 방향 사이의 각은 항상 θ이므로 n≥2에서 다음 길이는 이전 길이의5/6이다.','The projections alternate between the v1 and v2 directions. Their angle remains θ, so from n=2 each next length is5/6 times the previous length.')]+fs(r'|v_1|=2,\quad |v_n|=3(5/6)^{n-2}\ (n\ge2)',r'\sum_{n=1}^\infty|v_n|=2+\frac3{1-5/6}=20'),same(r'[20.]'))
add(6,(r'점(-1,1,4)를 지나며 내부의 모든 점이 (x^2+y^2+z^2<136+2(x+2y+3z))를 만족하는 가장 큰 구를 구하라.',r'Find the largest sphere through(-1,1,4) whose interior lies within (x^2+y^2+z^2<136+2(x+2y+3z)).'),fs(r'|X-C|^2<150,\quad C=(1,2,3),\quad R=5\sqrt6,\quad P=(-1,1,4),\quad d=|P-C|=\sqrt6')+[('새 중심 Q와 반지름 ρ는 ρ=|Q-P|≤|Q-C|+d를 만족한다. 안쪽 포함 조건은 |Q-C|+ρ≤R이다. 두 부등식을 더하면2ρ≤R+d.','For the new center Q and radius ρ, ρ=|Q-P|≤|Q-C|+d. Containment requires |Q-C|+ρ≤R. Adding gives2ρ≤R+d.')]+fs(r'\rho_{max}=(R+d)/2=3\sqrt6',r'Q=C-\frac{R-d}{2d}(P-C)=C-2(P-C)=(5,4,1)'),same(r'[(x-5)^2+(y-4)^2+(z-1)^2=54.]'))
add(7,(r'경사각 θ인 면의 질량 m 블록은 중력 W, 수직항력 N(크기 n), 마찰력 F를 받는다. 미끄러지기 시작하는 각을 θs, 최대 정지마찰을 μs n이라 하자. (a)μs=tanθs를 보이라. (b)θ>θs에서 왼쪽에서 수평력 h를 가할 때 정지에 필요한 최소 h의 두 성분 평형식을 얻어라. (c)hmin=mg tan(θ-θs)를 유도하고 θ=θs,θ→90°를 해석하라. (d)최대 h와 마찰 방향을 조사하라.',r'A mass m rests on an incline θ with weight W, normal force N of magnitude n, and friction F. Sliding begins at θs and maximal static friction is μs n. (a)Prove μs=tanθs. (b)For θ>θs, add a rightward horizontal force h and derive equilibrium at the minimum h. (c)Derive hmin=mg tan(θ-θs) and interpret θ=θs and θ→90°. (d)Find the maximum h and friction direction.'),fs(r'(a)\ n=mg\cos\theta_s,\quad\mu_s n=mg\sin\theta_s\Rightarrow\mu_s=\tan\theta_s',r'(b)\ n=h_{min}\sin\theta+mg\cos\theta',r'h_{min}\cos\theta+\mu_s n=mg\sin\theta',r'(c)\ h_{min}=mg\frac{\sin\theta-\mu_s\cos\theta}{\cos\theta+\mu_s\sin\theta}=mg\tan(\theta-\theta_s)')+[('θ=θs에서는 수평력이0이면 충분하다. 수직벽 극한에서는 hmin→mg cotθs=mg/μs로, 벽을 누르는 힘이 만든 마찰이 무게를 받친다.','At θ=θs, no horizontal force is needed. At a vertical wall, hmin→mg cotθs=mg/μs: friction caused by pressing into the wall supports the weight.')]+fs(r'(d)\ h_{max}\cos\theta-\mu_s(h_{max}\sin\theta+mg\cos\theta)=mg\sin\theta',r'h_{max}=mg\frac{\sin\theta+\mu_s\cos\theta}{\cos\theta-\mu_s\sin\theta}=mg\tan(\theta+\theta_s)')+[('상한에서는 위로 미끄러지려 하므로 마찰은 경사면 아래쪽이다. 유한 양의 상한 공식은 θ+θs<90°일 때 적용된다. θ+θs≥90°이면 수평력을 늘릴수록 수직항력과 허용 마찰도 커져 위쪽 미끄러짐을 일으킬 유한 상한이 없다.','At the upper threshold the block tends to move uphill, so friction points downhill. The finite positive upper bound requires θ+θs<90°. If θ+θs≥90°, increasing horizontal force also increases normal force and available friction; no finite upper threshold for uphill slip exists.')],(r'(a)(mu_s=	an	heta_s). (b)위 평형식. (c)(h_{min}=mg	an(	heta-	heta_s)). (d)(h_{max}=mg	an(	heta+	heta_s)), 단 (	heta+	heta_s<90^circ); 그 밖에는 유한 상한 없음.',r'(a)(mu_s=	an	heta_s). (b)Equilibrium equations above. (c)(h_{min}=mg	an(	heta-	heta_s)). (d)(h_{max}=mg	an(	heta+	heta_s)) for (	heta+	heta_s<90^circ); otherwise no finite upper bound.'),list('abcd'))
add(8,('xy평면 그림자가 원판, xz평면 그림자가 한 변1인 정사각형, yz평면 그림자가 이등변삼각형인 입체를 생각하자(교재12.1.52의 세 투영). (a)가장 큰 부피,(b)가장 작은 부피의 존재를 조사하라.','Consider solids with a disk as xy-projection, a unit square as xz-projection, and an isosceles triangle as yz-projection, as in Exercise12.1.52. (a)Find the largest volume;(b)discuss the smallest volume.'),[('정사각형은 -1/2≤x≤1/2,0≤z≤1로 놓고, 원판은 x²+y²≤1/4, 삼각형은0≤z≤1-2|y|로 놓는다. 같은 세 투영을 갖는 모든 점은 이 세 기둥의 교집합 안에 있어야 한다.','Place the square at -1/2≤x≤1/2,0≤z≤1, the disk at x²+y²≤1/4, and the triangle at0≤z≤1-2|y|. Any point with these projections must lie in the intersection of their three projection cylinders.')]+fs(r'S_{max}=\{x^2+y^2\le1/4,\quad0\le z\le1-2|y|\}',r'V_{max}=\int_{-1/2}^{1/2}2\sqrt{1/4-y^2}(1-2|y|)\,dy',r'=4\int_0^{1/2}\sqrt{1/4-y^2}\,dy-8\int_0^{1/2}y\sqrt{1/4-y^2}\,dy=\frac\pi4-\frac13')+[('이 교집합의 각 투영이 요구된 원판·정사각형·삼각형 전체인지 확인하면 상한이 달성됨을 알 수 있다.','Check that the intersection projects onto the entire prescribed disk, square, and triangle; hence the bound is attained.'),('바깥 경계만 남겨도 세 그림자는 변하지 않는다. 경계의 얇은 내부 층은 같은 그림자를 가지며 부피를 임의로 작게 만들 수 있다. 따라서 내부가 있는 입체의 양의 최소부피는 없다. 영두께 집합도 허용하면 경계 자체가 부피0을 달성한다.','Keeping only the boundary preserves all three shadows. Arbitrarily thin inner boundary layers preserve the shadows while their volumes tend to0. Thus positive-volume solids have no positive minimum; if zero-thickness sets are allowed, the boundary attains volume0.')],(r'(a)(pi/4-1/3approx0.452065). (b)부피의 하한은0. 양의 부피를 갖는 입체의 최소값은 없으며 영두께 경계를 허용하면0이다.',r'(a)(pi/4-1/3approx0.452065). (b)The infimum is0; no minimum among positive-volume solids, but a zero-thickness boundary has volume0.'),list('ab'))
M=lambda f:fs(f)[0][0]
def answer(n,k,e=None):b.E[n]['answer']=pair(k,e)
answer(1,M(r'r=\sqrt3-3/2\approx0.232051\ \mathrm m'))
answer(2,M(r'V=LWH+2(LW+LH+WH)+\pi(L+W+H)+4\pi/3'))
answer(3,'(a) 위 대칭식 또는 '+M('r=P_c+s d_c')+'(b) '+M('x^2+y^2=1+t^2')+'유한 c에서는 (1,t,t)를 제외. (c) '+M(r'4\pi/3'),'(a) The symmetric form above or '+M('r=P_c+s d_c')+'(b) '+M('x^2+y^2=1+t^2')+'Finite c excludes (1,t,t). (c) '+M(r'4\pi/3'))
answer(5,M('20'))
answer(6,M('(x-5)^2+(y-4)^2+(z-1)^2=54'))
common=M(r'\mu_s=\tan\theta_s,\quad h_{min}=mg\tan(\theta-\theta_s),\quad h_{max}=mg\tan(\theta+\theta_s)')
answer(7,common+'최댓값 식은 θ+θs<90°에서 유한하다. 그 밖에는 유한 상한이 없다.',common+'The upper bound is finite only when θ+θs<90°. Otherwise there is no finite upper bound.')
answer(8,'(a) '+M(r'\pi/4-1/3\approx0.452065')+'(b) 하한0, 양의 부피 입체에는 최소값이 없다. 영두께 집합을 허용하면0.', '(a) '+M(r'\pi/4-1/3\approx0.452065')+'(b) Infimum0, no minimum among positive-volume solids; zero if zero-thickness sets are allowed.')
b.E[5]['statement']=pair('다음 벡터열의 길이 합을 구하라. '+M(r'|v_1|=2,\quad|v_2|=3,\quad v_1\cdot v_2=5,\quad v_n=\operatorname{proj}_{v_{n-2}}v_{n-1}\ (n\ge3),\quad\sum_{n=1}^\infty|v_n|'),'Find the sum of lengths for '+M(r'|v_1|=2,\quad|v_2|=3,\quad v_1\cdot v_2=5,\quad v_n=\operatorname{proj}_{v_{n-2}}v_{n-1}\ (n\ge3),\quad\sum_{n=1}^\infty|v_n|'))

b.save();p=ROOT/'s12-8.json';d=json.loads(p.read_text());d['scope']['kind']='problems-plus'
for e in d['exercises']:e['conceptHref']='../s12-6.html'
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
