from curve_figures import draw_curves
from pathlib import Path
import math,json
R=Path(__file__).resolve().parents[1];p=R/'exercise-content/s13-1.json';d=json.loads(p.read_text());pi=math.pi;sin=math.sin;cos=math.cos;exp=math.exp
figs={7:[('Sideways cosine',lambda t:(-cos(t),t),[(-2*pi,2*pi)],'xy')],8:[('Right-opening parabola',lambda t:(t*t-1,t),[(-2,2)],'xy')],9:[('Clockwise ellipse',lambda t:(3*sin(t),2*cos(t)),[(0,2*pi)],'xy')],10:[('Positive hyperbola',lambda t:(exp(t),exp(-t)),[(-2,2)],'xy')],11:[('Line through (0,2,0)',lambda t:(t,2-t,2*t),[(-1,2)],'xyz')],12:[('Helix about y',lambda t:(sin(pi*t),t,cos(pi*t)),[(-2,2)],'xyz')],13:[('Parabola in x=3',lambda t:(3,t,2-t*t),[(-2,2)],'xyz')],14:[('Circle in z=1',lambda t:(2*cos(t),2*sin(t),1),[(0,2*pi)],'xyz')],15:[('Same trace: inward, then outward',lambda t:(t*t,t**4,t**6),[(-1.3,0),(0,1.3)],'xyz')],16:[('Ellipse in y=-x',lambda t:(cos(t),-cos(t),sin(t)),[(0,2*pi)],'xyz')],17:[('yz projection: yz=1',lambda t:(t**3,t**-3),[(-1.6,-.63),(.63,1.6)],'yz')],18:[('xy projection: y=3x-2',lambda t:(t+1,3*t+1),[(-2,2)],'xy')],19:[('Spatial elliptical helix',lambda t:(t,sin(t),2*cos(t)),[(-2*pi,2*pi)],'xyz'),('xy: y=sin x',lambda t:(t,sin(t)),[(-2*pi,2*pi)],'xy'),('xz: z=2cos x',lambda t:(t,2*cos(t)),[(-2*pi,2*pi)],'xz'),('yz: ellipse',lambda t:(sin(t),2*cos(t)),[(0,2*pi)],'yz')],20:[('Spatial parabola',lambda t:(t,t,t*t),[(-2,2)],'xyz'),('xy: y=x',lambda t:(t,t),[(-2,2)],'xy'),('xz: z=x squared',lambda t:(t,t*t),[(-2,2)],'xz'),('yz: z=y squared',lambda t:(t,t*t),[(-2,2)],'yz')],25:[('II: growing spiral about y',lambda t:(t*cos(t),t,t*sin(t)),[(0,6*pi)],'xyz')],26:[('VI: coils toward z=0',lambda t:(cos(t),sin(t),1/(1+t*t)),[(-8*pi,8*pi)],'xyz')],27:[('V: two rising branches',lambda t:(t,1/(1+t*t),t*t),[(-3,3)],'xyz')],28:[('I: closed vertical oscillation',lambda t:(cos(t),sin(t),cos(2*t)),[(0,2*pi)],'xyz')],29:[('IV: increasing vertical gaps',lambda t:(cos(8*t),sin(8*t),exp(.8*t)),[(0,3)],'xyz')],30:[('III: wave in a vertical plane',lambda t:(cos(t)**2,sin(t)**2,t),[(-2*pi,2*pi)],'xyz')],35:[('Spiral on both cone nappes',lambda t:(t*cos(t),t*sin(t),t),[(-4*pi,4*pi)],'xyz')],36:[('Intersection: unit cylinder and z=x squared',lambda t:(sin(t),cos(t),sin(t)**2),[(0,2*pi)],'xyz')]}
f41=lambda t:(cos(t)*sin(2*t),sin(t)*sin(2*t),cos(2*t));f42=lambda t:(t*exp(t),exp(-t),t);f43=lambda t:(sin(3*t)*cos(t),t/4,sin(3*t)*sin(t));f44=lambda t:(cos(8*cos(t))*sin(t),sin(8*cos(t))*sin(t),cos(t));f45=lambda t:(cos(2*t),cos(3*t),cos(4*t));f46=lambda t:(sin(t),sin(2*t),cos(4*t));f47=lambda t:((1+cos(16*t))*cos(t),(1+cos(16*t))*sin(t),1+cos(16*t));f48=lambda t:(math.sqrt(1-.25*cos(10*t)**2)*cos(t),math.sqrt(1-.25*cos(10*t)**2)*sin(t),.5*cos(10*t));f59=lambda t:(27/26*sin(8*t)-8/39*sin(18*t),-27/26*cos(8*t)+8/39*cos(18*t),144/65*sin(5*t));knot=lambda t:((2+cos(1.5*t))*cos(t),(2+cos(1.5*t))*sin(t),sin(1.5*t))
for n,f,span,side,labels in [(41,f41,(0,2*pi),(0,1),'xy'),(42,f42,(-2,2),(1,2),'yz'),(43,f43,(0,4*pi),(0,2),'xz'),(44,f44,(0,2*pi),(0,1),'xy'),(45,f45,(0,pi),(0,1),'xy'),(47,f47,(0,2*pi),(0,1),'xy'),(48,f48,(0,2*pi),(0,1),'xy'),(59,f59,(0,2*pi),(0,1),'xy')]:
 figs[n]=[(f'Exercise13.1.{n}: spatial view',f,[span],'xyz'),(labels+' projection',lambda t,f=f,side=side:tuple(f(t)[i]for i in side),[span],labels)]
figs[46]=[('Spatial curve',f46,[(0,2*pi)],'xyz')]+[(lab+' projection',lambda t,idx=idx:tuple(f46(t)[i]for i in idx),[(0,2*pi)],lab)for lab,idx in [('xy',(0,1)),('xz',(0,2)),('yz',(1,2))]]
figs[55]=[('Cylinder x²+y²=4 with z=x²',lambda t:(2*cos(t),2*sin(t),4*cos(t)**2),[(0,2*pi)],'xyz')]
bound=math.sqrt((math.sqrt(257)-1)/8)
figs[56]=[('Upper ellipsoid / parabolic cylinder',lambda t:(t,t*t,.5*math.sqrt(max(0,16-t*t-4*t**4))),[(-bound,bound)],'xyz')]
figs[60]=[('Trefoil: spatial view',knot,[(0,4*pi)],'xyz'),('Side view xz',lambda t:(knot(t)[0],knot(t)[2]),[(0,4*pi)],'xz')]
for n,panels in figs.items():
 fn=f's13-1-{n}.svg';draw_curves(R/'exercise-content/assets'/fn,panels);d['exercises'][n-1]['figure']={'src':'../exercise-content/assets/'+fn,'alt':{'ko':f'13.1 {n}번의 곡선 및 사영도','en':f'Curve and projection diagrams for13.1.{n}'},'caption':{'ko':'주어진 식으로 직접 제작한 곡선. 화살표는 표시 매개변수의 증가 방향이고, 무한곡선은 표시 구간으로 잘랐다.','en':'Original curves calculated from the given equations. Arrows indicate increasing displayed parameter; unbounded curves are clipped to the stated intervals.'}}
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');print(len(figs),'original figures')
# Add a true top view with gaps under the three higher strands.
path=R/'exercise-content/assets/s13-1-60.svg';svg=path.read_text().replace('viewBox="0 0 1000 410"','viewBox="0 0 1000 920"');svg=svg[:-6]
def topxy(t):a,b,c=knot(t);return(500+60*a,660-60*b)
def poly(lo,hi,count=1600):return' '.join('%g,%g'%topxy(lo+(hi-lo)*j/count)for j in range(count+1))
svg+='<text x="500" y="455" text-anchor="middle" font-family="sans-serif" font-size="18">Top view: gaps mark the lower strand</text>'
svg+='<polyline points="'+poly(0,4*pi)+'" fill="none" stroke="#0284c7" stroke-width="3"/>'
for at in[pi/3,3*pi,5*pi/3]:
 points=poly(at-.07,at+.07,40);svg+='<polyline points="'+points+'" fill="none" stroke="#f8fafc" stroke-width="11"/><polyline points="'+points+'" fill="none" stroke="#0284c7" stroke-width="3"/>'
svg+='<text x="500" y="905" text-anchor="middle" font-family="sans-serif" font-size="15">At each crossing the upper strand has z=+1 and the lower strand z=-1.</text></svg>';path.write_text(svg)
