from early_helpers import *
import sympy as s
from math import sin,cos,sqrt,exp,pi
b=Book('14.3',[1007,1008,1009,1010,1011]);old=json.loads((ROOT/'s14-3.json').read_text());b.E={e['number']:e for e in old['exercises'] if e['number']in range(9,17)}
x,y,z,t,u,v,r,q,p,a,c,d,ss=s.symbols('x y z t u v r q p a c d s',real=True);aa,bb,gg,dd=s.symbols('alpha beta gamma delta',real=True);theta=s.symbols('theta',real=True)
def tex(e):return s.latex(s.factor(e))
def add(n,title,st,steps,ans,parts=[],check=None):b.add(n,1007 if n<=7 else 1008 if n<=68 else 1009 if n<=79 else 1010 if n<=92 else 1011,title,st,steps,ans,parts,check=check)
def calc(n,f,variables,name='f',orders=None,title=None):
 F=tex(f);wanted=[(i,)for i in variables]if orders is None else orders;derivs=[];steps=[('선택한 변수 이외에는 모두 상수로 두고 곱·몫·연쇄법칙을 적용한다.','Hold every variable except the selected one constant and apply the product, quotient, and chain rules.')]
 for order in wanted:
  res=s.diff(f,*order);label=name+'_{'+' '.join(s.latex(k)for k in order)+'}';derivs.append(label+'='+tex(res))
  if len(order)>1:steps+=fs(name+'_{'+' '.join(s.latex(k)for k in order[:-1])+'}='+tex(s.diff(f,*order[:-1])))
  steps+=fs(label+'='+tex(res))
 request='1계 편도함수를 모두 구하라.'if orders is None else'지정한 편도함수를 구하라.';en='Find all first partial derivatives.'if orders is None else'Find the indicated partial derivatives.'
 spec=''if orders is None else r'\('+',\ '.join(name+'_{'+' '.join(s.latex(k)for k in o)+'}'for o in wanted)+r'\).'
 add(n,title or('편도함수 계산','Computing partial derivatives'),(request+r'\('+name+'='+F+r'\).'+spec,en+r'\('+name+'='+F+r'\).'+spec),steps,same(r'\['+r',\qquad '.join(derivs)+r'.\]'),check=('독립적인 기호미분으로 각 결과를 대조했다. 식의 분모·로그·제곱근이 허용되는 미분 가능 영역에서의 공식이다.','Each result was cross-checked by symbolic differentiation. Formulas apply on the differentiable domain allowed by denominators, logarithms, and roots.'))
add(1,('체감온도의 편미분','Partial derivatives of heat index'),('교재 표에서 '+r'\(f_T(92,60),\ f_H(92,60)\)'+'을 근사하고 해석하라. 필요한 값은 f(90,60)=100, f(94,60)=111, f(92,55)=103, f(92,65)=108이다(T와 I는°F, H는%).','Estimate and interpret '+r'\(f_T(92,60),\ f_H(92,60)\)'+' using f(90,60)=100, f(94,60)=111, f(92,55)=103, f(92,65)=108 from the textbook table (T and I in°F; H in%).'),fs(r'f_T(92,60)\approx\frac{111-100}{94-90}=2.75',r'f_H(92,60)\approx\frac{108-103}{65-55}=0.5')+[('습도를60%로 고정하면 실제온도1°F 상승당 체감온도 약2.75°F 증가, 온도를92°F로 고정하면 습도1퍼센트포인트 상승당 약0.5°F 증가이다.','At60% humidity, a1°F rise in temperature increases heat index by about2.75°F. At92°F, a1-percentage-point rise in humidity increases it by about0.5°F.')],same(r'\[f_T\approx2.75\ \mathrm{^{\circ}F/^{\circ}F},\qquad f_H\approx0.5\ \mathrm{^{\circ}F/percentage\ point}.\]'))
add(2,('파고의 편미분','Partial derivatives of wave height'),('파고 h=f(v,t)(피트), 풍속 v(노트), 지속시간 t(시간)에 대해 (a) 두 편미분을 해석하고 (b) (40,15)에서 추정하며 (c) t→∞일 때 h_t의 경향을 구하라. 표에서 f(30,15)=16, f(50,15)=36, f(40,10)=21, f(40,20)=28이며 풍속40에서 t=30,40,50의 값은31,33,33이다.','For wave height h=f(v,t) in feet, speed v in knots and duration t in hours, (a) interpret the partials; (b) estimate at (40,15); (c) infer h_t as t→∞. Table entries are f(30,15)=16, f(50,15)=36, f(40,10)=21, f(40,20)=28; at speed40 the values for t=30,40,50 are31,33,33.'),[('(a) h_v는 시간을 고정한 풍속당 파고 변화, h_t는 풍속을 고정한 시간당 파고 변화이다.','(a) h_v measures height change per knot at fixed duration; h_t measures height change per hour at fixed wind speed.')]+fs(r'(b)\ f_v(40,15)\approx(36-16)/20=1,\quad f_t(40,15)\approx(28-21)/10=0.7')+[('(c) 장시간 후 높이가 포화되는 표의 경향에 따라 변화율은0으로 접근한다고 예상한다. 유한한 표만으로 증명한 극한은 아니다.','(c) The table suggests saturation and hence a rate tending to0; a finite table alone does not prove that limit.')],same(r'\[(b)\ f_v\approx1\ \mathrm{ft/knot},\quad f_t\approx0.7\ \mathrm{ft/h};\qquad(c)\ h_t\to0\ \text{(suggested)}.\]'),['a','b','c'])
add(3,('온도장의 방향과 시간','Spatial and temporal temperature changes'),('T=f(x,y,t)에서 x는 서경의 도수, y는 북위의 도수, t는1월1일부터 경과시간이다. (a) 세 편미분을 해석하라. (b) 호놀룰루(158,21), t=9에서 서·남쪽은 따뜻하고 동·북쪽은 차며 따뜻한 공기가 북동쪽으로 이동할 때 세 편미분의 부호를 예상하라.','For T=f(x,y,t), x measures degrees west, y degrees north, and t hours since January1, (a) interpret the three partials. (b) At Honolulu(158,21), t=9, warmer air lies west and south, cooler air east and north, and warm air moves northeast. Predict the signs.'),[('(a) 다른 두 변수를 고정할 때 각각 경도·위도·시간당 온도의 변화율이다.','(a) They are changes per unit longitude, latitude, and time, holding the other two variables fixed.'),('(b) 서경x가 증가하면 따뜻한 서쪽으로 가므로 양수, 북위y가 증가하면 찬 북쪽이므로 음수, 따뜻한 공기가 도착하므로 시간 미분은 양수이다.','(b) Increasing west longitude moves into warmer air, increasing latitude into cooler air, and incoming warm air raises temperature over time.')],same(r'\[f_x(158,21,9)>0,\quad f_y(158,21,9)<0,\quad f_t(158,21,9)>0.\]'),['a','b'])
for n,pt,sx in[(4,'(1,2)','>'),(5,'(-1,2)','<')]:
 add(n,('그래프에서 기울기 부호','Signs of slopes from a graph'),('교재 안장 모양 그래프에서 (a) '+r'\(f_x'+pt+r'\)'+'와 (b) '+r'\(f_y'+pt+r'\)'+'의 부호를 정하라.','For the source saddle-shaped graph, determine signs of (a) '+r'\(f_x'+pt+r'\)'+' and (b) '+r'\(f_y'+pt+r'\)'+'.'),[('y=2 단면은 x=0 부근에서 낮고 양옆으로 높아지는 곡선이다.','The y=2 section has a trough near x=0 and rises on both sides.'),('두 지정된 점에서 양의 y방향으로 움직이면 높이가 내려간다.','At both specified points, moving in positive y decreases the height.')],same(r'\[(a)\ f_x'+pt+sx+r'0;\qquad(b)\ f_y'+pt+r'<0.\]'),['a','b'])
add(6,('등고선으로 편미분 추정','Estimating partials from contours'),('교재 등고선에서 '+r'\(f_x(2,1),\ f_y(2,1)\)'+'을 추정하라. 해당 근방에서 오른쪽으로 등고선값이 증가하고 위쪽으로 감소하며 인접 등고선의 값 차이는2이다.','Estimate '+r'\(f_x(2,1),\ f_y(2,1)\)'+' from the source contour map. Nearby, values increase rightward and decrease upward, with increment2 between adjacent contours.'),[('수평선 y=1에서 값이2 증가하는 데 필요한 거리가 약0.5이므로 변화율은 약4이다.','Along y=1, an increase of2 takes about0.5 horizontal unit, giving a slope near4.'),('수직선 x=2에서 위쪽 약1단위 이동에 값이약2 줄어들므로 변화율은 약-2이다.','Along x=2, a rise of about1 vertical unit lowers f by about2, giving a slope near-2.')],same(r'\[f_x(2,1)\approx4,\qquad f_y(2,1)\approx-2.\]'),check=('그림에서 읽는 근사이므로 작은 눈금 판독 차이에 따른 오차가 허용된다.','These are graphical estimates, allowing small differences from reading the grid.'))
for n,F,pt,dx,dy,P in[(7,r'16-4x^2-y^2',r'(1,2)',r'-8',r'-4',r'(1,2,8)'),(8,r'\sqrt{4-x^2-4y^2}',r'(1,0)',r'-1/\sqrt3','0',r'(1,0,\sqrt3)')]:
 deriv=(r'f_x=-8x,\quad f_y=-2y')if n==7 else(r'f_x=-x/\sqrt{4-x^2-4y^2},\quad f_y=-4y/\sqrt{4-x^2-4y^2}')
 add(n,('편미분과 단면 접선','Partial derivatives and trace tangents'),('함수 '+r'\(f='+F+r'\)'+'의 '+r'\(f_x'+pt+',\ f_y'+pt+r'\)'+'를 구하고 접선 기울기로 해석하여 그려라.','For '+r'\(f='+F+r'\)'+' find '+r'\(f_x'+pt+',\ f_y'+pt+r'\)'+' and illustrate their meanings as tangent slopes.'),fs(deriv,r'P='+P)+[('x편미분은 y를 고정한 수직단면의 기울기이고, y편미분은 x를 고정한 단면의 기울기이다.','The x-partial is the tangent slope in the vertical trace with y fixed; the y-partial uses the trace with x fixed.')],same(r'\[f_x'+pt+'='+dx+r',\qquad f_y'+pt+'='+dy+r'.\]'))
# Original9–16 remain intact; compare their functions with the source separately.
first=[(17,y*(x+x*x*y)**5,[x,y],'g'),(18,x/(x+y)**2,[x,y],'f'),(19,(a*x+s.Symbol('b',real=True)*y)/(c*x+d*y),[x,y],'f'),(20,s.exp(v)/(u+v*v),[u,v],'w'),(21,(u*u*v-v**3)**5,[u,v],'g'),(22,s.sin(r*s.cos(theta)),[r,theta],'u'),(23,s.atan(p*q*q),[p,q],'R'),(24,x**y,[x,y],'f'),(27,x**3*y*z*z+2*y*z,[x,y,z],'f'),(28,x*y*y*s.exp(-x*z),[x,y,z],'f'),(29,s.log(x+2*y+3*z),[x,y,z],'w'),(30,y*s.tan(x+2*z),[x,y,z],'w'),(31,s.sqrt(t**4+u*u*s.cos(v)),[t,u,v],'p'),(32,x**(y/z),[x,y,z],'u'),(33,x*x*y*s.cos(z/t),[x,y,z,t],'h'),(34,(aa*x+bb*y*y)/(gg*z+dd*t*t),[x,y,z,t],r'\phi')]
for n,F,vs,name in first:calc(n,F,vs,name)
for n in[24,32]:b.E[n]['steps']['ko'].insert(0,'실수 거듭제곱의 일반적인 미분 영역 x>0에서 계산한다.');b.E[n]['steps']['en'].insert(0,'Work on x>0, the usual differentiable domain for a general real power.')
for n,F,deriv in[(25,r'F(x,y)=\int_y^x\cos(e^t)\,dt',r'F_x=\cos(e^x),\quad F_y=-\cos(e^y)'),(26,r'F(\alpha,\beta)=\int_\alpha^\beta\sqrt{t^3+1}\,dt',r'F_\alpha=-\sqrt{\alpha^3+1},\quad F_\beta=\sqrt{\beta^3+1}')]:
 add(n,('가변 적분구간 미분','Differentiating variable endpoints'),('1계 편도함수를 구하라. '+r'\('+F+r'\).','Find the first partials of '+r'\('+F+r'\).'),[('적분 상한의 미분은 적분함수값, 하한의 미분은 그 음수이다.','The upper-endpoint derivative is the integrand value; the lower-endpoint derivative is its negative.')]+fs(deriv),same(r'\['+deriv+r'.\]'))
add(35,('n변수 노름의 편미분','Partials of an n-variable norm'),('1계 편도함수를 구하라. '+r'\(u=\sqrt{x_1^2+\cdots+x_n^2}\).','Find all first partial derivatives of '+r'\(u=\sqrt{x_1^2+\cdots+x_n^2}\).'),fs(r'\frac{\partial u}{\partial x_i}=\frac12(\sum_jx_j^2)^{-1/2}(2x_i)')+[('원점에서는 해당 좌표축을 따라 절댓값 함수가 되므로 두쪽 편미분이 존재하지 않는다.','At the origin each coordinate restriction is an absolute-value function, so the two-sided partial does not exist.')],same(r'\[u_{x_i}=\frac{x_i}{\sqrt{\sum_jx_j^2}}\quad(\mathbf x\ne0);\qquad u_{x_i}(0)\text{ does not exist}.\]'))
add(36,('n변수 합성함수의 편미분','Partials of an n-variable composition'),('모든1계 편도함수를 구하라. '+r'\(u=\sin(x_1+2x_2+\cdots+nx_n)\).','Find all first partials of '+r'\(u=\sin(x_1+2x_2+\cdots+nx_n)\).'),fs(r'L=\sum_{j=1}^njx_j,\quad L_{x_i}=i',r'u_{x_i}=\cos L\cdot i'),same(r'\[u_{x_i}=i\cos\left(\sum_{j=1}^njx_j\right),\quad i=1,\ldots,n.\]'))
add(37,('지정점 편미분','Partial at a specified point'),('계산하라. '+r'\(R(s,t)=te^{s/t},\quad R_t(0,1)\).','Evaluate '+r'\(R(s,t)=te^{s/t},\quad R_t(0,1)\).'),fs(r'R_t=e^{s/t}+te^{s/t}(-s/t^2)=e^{s/t}(1-s/t)'),same(r'\[R_t(0,1)=1.\]'))
add(38,('역삼각함수 편미분','Partial of an inverse trigonometric function'),('계산하라. '+r'\(f(x,y)=y\arcsin(xy),\quad f_y(1,1/2)\).','Evaluate '+r'\(f(x,y)=y\arcsin(xy),\quad f_y(1,1/2)\).'),fs(r'f_y=\arcsin(xy)+\frac{xy}{\sqrt{1-x^2y^2}}'),same(r'\[f_y(1,1/2)=\pi/6+1/\sqrt3.\]'))
add(39,('로그 정의역 확인','Checking a logarithm domain'),('원문이 제시한 값을 검토하라. '+r'\(f=\ln\frac{1-\sqrt{x^2+y^2+z^2}}{1+\sqrt{x^2+y^2+z^2}},\quad f_y(1,2,2)\).','Examine the requested value in the printed exercise: '+r'\(f=\ln\frac{1-\sqrt{x^2+y^2+z^2}}{1+\sqrt{x^2+y^2+z^2}},\quad f_y(1,2,2)\).'),fs(r'r=\sqrt{x^2+y^2+z^2}=3,\quad(1-r)/(1+r)=-1/2')+[('원문의 실수 로그는 이 점에서 정의되지 않으므로 실수 편미분도 없다. 부록의1/6은 로그인수의 절댓값을 취한 수정식에 해당한다.','The printed real logarithm is undefined here, so its real partial derivative does not exist. The appendix value1/6 corresponds to correcting the logarithm with an absolute value.')]+fs(r'\widetilde f=\ln\left|\frac{1-r}{1+r}\right|,\quad\widetilde f_y=-\frac{2y}{r(1-r^2)},\quad\widetilde f_y(1,2,2)=1/6'),('원문 그대로의 실수 편미분은 미정의. 로그절댓값 수정 시1/6.','The printed real partial is undefined. With an absolute-value logarithm correction, it is1/6.'),check=('PDF1045 이미지와 원문 조건을 보존하여 정의역 오류와 형식적 계산을 분리했다.','The PDF1045 image and original conditions are preserved; the domain error is distinguished from the formal computation.'))
add(40,('지수에 대한 편미분','Differentiating a variable exponent'),('계산하라. '+r'\(f=x^{yz},\quad f_z(e,1,0)\).','Evaluate '+r'\(f=x^{yz},\quad f_z(e,1,0)\).'),fs(r'f=e^{yz\ln x},\quad f_z=y\ln x\,x^{yz}'),same(r'\[f_z(e,1,0)=1.\]'))
for n,F in[(41,x*x+2*y*y+3*z*z-1),(42,x*x-y*y+z*z-2*z-4),(43,s.exp(z)-x*y*z),(44,y*z+x*s.log(y)-z*z)]:
 zx=-s.diff(F,x)/s.diff(F,z);zy=-s.diff(F,y)/s.diff(F,z)
 add(n,('음함수 편미분','Implicit partial differentiation'),('음함수 미분으로 '+r'\(z_x,z_y\)'+'를 구하라. '+r'\('+tex(F)+'=0'+r'\).','Use implicit differentiation to find '+r'\(z_x,z_y\)'+' from '+r'\('+tex(F)+'=0'+r'\).'),fs(r'F_x+F_zz_x=0,\quad F_y+F_zz_y=0',r'F_z='+tex(s.diff(F,z))),same(r'\[z_x='+tex(zx)+r',\qquad z_y='+tex(zy)+r'.\]'),check=('z를 x,y의 미분가능함수로 나타낼 수 있고 F_z≠0인 점에서 적용한다.','These formulas apply where z is a differentiable function of x,y and F_z≠0.'))
add(45,('일반 함수의 합과 합성','Sums and compositions of general functions'),('각 경우 '+r'\(z_x,z_y\)'+'를 구하라: (a) '+r'\(z=f(x)+g(y)\)'+'; (b) '+r'\(z=f(x+y)\)'+'.','Find '+r'\(z_x,z_y\)'+' for (a) '+r'\(z=f(x)+g(y)\)'+' and (b) '+r'\(z=f(x+y)\)'+'.'),[('(a) 다른 변수만 포함한 항은 상수이다. (b) 내부함수 x+y의 각 편미분은1이다.','(a) A term involving only the other variable is constant. (b) Each partial of the inner function x+y is1.')]+fs(r'(a)\ z_x=f\prime(x),\ z_y=g\prime(y);\qquad(b)\ z_x=z_y=f\prime(x+y)'),same(r'\[(a)\ (f\prime(x),g\prime(y));\quad(b)\ (f\prime(x+y),f\prime(x+y)).\]'),['a','b'])
add(46,('곱·곱합성·몫합성','Products and composed products or quotients'),('각 경우 '+r'\(z_x,z_y\)'+'를 구하라: (a) '+r'\(z=f(x)g(y)\)'+'; (b) '+r'\(z=f(xy)\)'+'; (c) '+r'\(z=f(x/y)\)'+'.','Find '+r'\(z_x,z_y\)'+' for (a) '+r'\(z=f(x)g(y)\)'+'; (b) '+r'\(z=f(xy)\)'+'; (c) '+r'\(z=f(x/y)\)'+'.'),fs(r'(a)\ z_x=f\prime(x)g(y),\quad z_y=f(x)g\prime(y)',r'(b)\ z_x=yf\prime(xy),\quad z_y=xf\prime(xy)',r'(c)\ z_x=f\prime(x/y)/y,\quad z_y=-xf\prime(x/y)/y^2'),same(r'\[(a)\ (f\prime(x)g(y),f(x)g\prime(y));\quad(b)\ (yf\prime(xy),xf\prime(xy));\quad(c)\ (f\prime(x/y)/y,-xf\prime(x/y)/y^2).\]'),['a','b','c'])
for n,F,vs,name in[(47,x**4*y-2*x**3*y*y,[x,y],'f'),(48,s.log(a*x+s.Symbol('b',real=True)*y),[x,y],'f'),(49,y/(2*x+3*y),[x,y],'z'),(50,s.exp(-2*r)*s.cos(theta),[r,theta],'T'),(51,s.sin(ss*ss-t*t),[ss,t],'v'),(52,s.atan((x+y)/(1-x*y)),[x,y],'z')]:
 calc(n,F,vs,name,[(vs[0],vs[0]),(vs[0],vs[1]),(vs[1],vs[0]),(vs[1],vs[1])],('2계 편도함수','Second partial derivatives'))
for n,F in[(53,x**4*y**3-y**4),(54,s.exp(x*y)*s.sin(y)),(55,s.cos(x*x*y)),(56,s.log(x+2*y))]:calc(n,F,[x,y],'u',[(x,y),(y,x)],('혼합편미분의 교환','Equality of mixed partials'))
for n,F,orders,name in[(57,x**4*y*y-x**3*y,[(x,x,x),(x,y,x)],'f'),(58,s.sin(2*x+5*y),[(y,x,y)],'f'),(59,s.exp(x*y*z*z),[(x,y,z)],'f'),(60,s.exp(r)*s.sin(ss*t),[(r,ss,t)],'g'),(61,s.sqrt(u+v*v),[(u,u,v)],'W'),(62,s.log(r+ss*ss+t**3),[(r,ss,t)],'V'),(63,x/(y+2*z),[(x,y,z),(y,x,x)],'w')]:calc(n,F,[],name,orders)
add(64,('여섯 번의 편미분','A sixth-order mixed partial'),('지정한 편미분을 구하라. '+r'\(u=x^ay^bz^c,\quad\partial^6u/(\partial x\partial y^2\partial z^3)\).','Find '+r'\(u=x^ay^bz^c,\quad\partial^6u/(\partial x\partial y^2\partial z^3)\).'),[('x인자를 한 번, y인자를 두 번, z인자를 세 번 미분한다. 각 거듭제곱의 지수가 차례로 내려간다.','Differentiate the x-factor once, the y-factor twice, and the z-factor three times, lowering each exponent in turn.')]+fs(r'(x^a)\prime=ax^{a-1},\quad(y^b)\prime\prime=b(b-1)y^{b-2},\quad(z^c)\prime\prime\prime=c(c-1)(c-2)z^{c-3}'),same(r'\[ab(b-1)c(c-1)(c-2)x^{a-1}y^{b-2}z^{c-3}.\]'))
add(65,('정의로 다항식 편미분','Polynomial partials from the definition'),('극한 정의를 사용하여 두 편미분을 구하라. '+r'\(f=xy^2-x^3y\).','Use the limit definition to find both partials of '+r'\(f=xy^2-x^3y\).'),fs(r'\frac{f(x+h,y)-f(x,y)}h=y^2-y(3x^2+3xh+h^2)',r'\frac{f(x,y+h)-f(x,y)}h=x(2y+h)-x^3'),same(r'\[f_x=y^2-3x^2y,\qquad f_y=2xy-x^3.\]'))
add(66,('정의로 유리함수 편미분','Rational partials from the definition'),('극한 정의로 편미분을 구하라. '+r'\(f=x/(x+y^2)\).','Use the limit definition for '+r'\(f=x/(x+y^2)\).'),fs(r'\frac{f(x+h,y)-f(x,y)}h=\frac{y^2}{(x+h+y^2)(x+y^2)}',r'\frac{f(x,y+h)-f(x,y)}h=\frac{-x(2y+h)}{(x+(y+h)^2)(x+y^2)}'),same(r'\[f_x=\frac{y^2}{(x+y^2)^2},\qquad f_y=-\frac{2xy}{(x+y^2)^2}.\]'))
add(67,('미분 순서 선택','Choosing an efficient derivative order'),('편미분을 구하라. '+r'\(f=xy^2z^3+\arcsin(x\sqrt z),\quad f_{xzy}\).','Find '+r'\(f=xy^2z^3+\arcsin(x\sqrt z),\quad f_{xzy}\).'),[('미분가능한 내부 영역에서 혼합미분 순서를 바꾸어 y부터 미분하면 역삼각함수 항이 사라진다.','In the smooth interior, interchange the order and differentiate y first to remove the inverse-trigonometric term.')]+fs(r'f_y=2xyz^3,\quad f_{yx}=2yz^3,\quad f_{yxz}=6yz^2'),same(r'\[f_{xzy}=6yz^2.\]'))
add(68,('변수에 독립적인 항','Terms independent of a variable'),('편미분을 구하라. '+r'\(g=\sqrt{1+xz}+\sqrt{1-xy},\quad g_{yxz}\).','Find '+r'\(g=\sqrt{1+xz}+\sqrt{1-xy},\quad g_{yxz}\).'),[('첫 항은 y와 무관하므로 y미분에서 사라진다. 남은 항은 z와 무관하다.','The first term is independent of y and disappears upon y-differentiation. The remaining term is independent of z.'),(r'따라서 제곱근 내부가 양수인 매끄러운 영역에서 \(g_{yxz}=0\)이다.',r'Thus on the smooth region with positive radicands, \(g_{yxz}=0\).')],same(r'\[g_{yxz}=0.\]'))
# Save a coherent partial document while later applications are authored.
b.save();print('14.3 through68 complete')
