import sympy as S,json,math
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=[];plots={}
x,y,t=S.symbols('x y t',real=True);M=lambda a:r'\('+S.latex(S.simplify(a))+r'\)';pair=lambda a,b:dict(ko=a,en=b)
def add(n,k,e,ks,es,ka,ea,kc='모든 내부 정지점과 해당 경계 조건을 확인했다.',ec='All interior stationary points and applicable boundary conditions were checked.',parts=[]):
 pg=1054 if n<=3 else 1055 if n<=41 else 1056 if n<=61 else 1057
 E.append(dict(id=f'stewart9-exercise-14.7-{n}',number=n,subparts=parts,source=dict(printedPage=pg,pdfPage=pg+37),topic=pair('극값과 최적화','Extrema and optimization'),statement=pair(k,e),hint=pair('정지점을 찾고 헤세행렬 또는 직접 부등식으로 분류한다. 닫힌 영역에서는 경계도 검사한다.','Find stationary points and classify by the Hessian or direct inequalities; inspect boundaries on closed regions.'),steps=pair(ks,es),answer=pair(ka,ea),check=pair(kc,ec),conceptHref='../s14-7.html',status='math-verified'))
def classify(n,F,pts=None,numeric=False,domain='',extra='',graph=False):
 fx=S.diff(F,x);fy=S.diff(F,y);H=S.hessian(F,(x,y));det=S.det(H)
 if pts is None:pts=[(a[x],a[y]) for a in S.solve([fx,fy],(x,y),dict=True) if x in a and y in a and a[x].is_real is not False and a[y].is_real is not False]
 ks=['정지식: '+M(fx)+'=0, '+M(fy)+'=0.'];es=['Stationary equations: '+M(fx)+'=0, '+M(fy)+'=0.'];aks=[];aes=[]
 for xx,yy in pts:
  sub={x:xx,y:yy};val=S.simplify(F.subs(sub));dd=S.simplify(det.subs(sub));aa=S.simplify(H[0,0].subs(sub));dv=float(dd);av=float(aa)
  assert abs(float(fx.subs(sub)))<1e-6 and abs(float(fy.subs(sub)))<1e-6
  kind=('극소','minimum') if dv>1e-8 and av>0 else ('극대','maximum') if dv>1e-8 else ('안장점','saddle') if dv< -1e-8 else ('추가 판정 필요','inconclusive')
  loc=f'({float(xx):.3f},{float(yy):.3f})' if numeric else M(S.Tuple(xx,yy));vv=f'{float(val):.3f}' if numeric else M(val);dstr=f'{dv:.5g}' if numeric else M(dd)
  ks.append(loc+'에서 D='+dstr+', fxx='+M(aa)+': '+kind[0]+', f='+vv+'.');es.append('At '+loc+', D='+dstr+', fxx='+M(aa)+': '+kind[1]+', f='+vv+'.');aks.append(loc+' '+kind[0]+' '+vv);aes.append(loc+' '+kind[1]+' '+vv)
 if not pts:ks.append('정지식의 동시 해가 없으므로 열린 정의역에 극값이 없다.');es.append('The stationary equations have no common solution, so there are no extrema in the open domain.')
 st='f='+M(F)+'. '+domain
 add(n,st+('그래프에서 극값·안장점을 추정한 뒤 미분으로 정확히 분류하라.' if graph else '모든 극대·극소와 안장점을 구하라.'),st.replace('경계 x=0에는 국소 극값 없음.','no relative local extremum occurs on boundary x=0.')+('Estimate extrema and saddles graphically, then classify exactly by calculus.' if graph else 'Find all local maxima, minima, and saddle points.'),ks,es,('; '.join(aks) or '없음.')+extra,('; '.join(aes) or 'None.')+extra,'정지식에 모든 점을 대입해 잔차를 검사했고 각 헤세행렬 행렬식을 평가했다.','Every listed point was checked in both stationary equations and its Hessian determinant evaluated.')
 if graph:plots[n]=(F,(-2,2,-2,2))
for n,rows in [(1,[(4,1,2),(4,3,2)]),(2,[(-1,6,1),(-1,2,-8),(4,6,9)])]:
 ks=[];es=[];aks=[];aes=[]
 for i,(a,b,c) in enumerate(rows):
  d=a*c-b*b;k,e=('극소','minimum') if d>0 and a>0 else ('극대','maximum') if d>0 else ('안장점','saddle') if d<0 else ('판정 불능','inconclusive');tag=chr(97+i);ks.append(f'({tag}) D={a}·{c}−({b})²={d}. fxx={a}를 함께 사용한다.');es.append(f'({tag}) D={a}·{c}−({b})²={d}; also use fxx={a}.');aks.append(f'({tag}) {k}');aes.append(f'({tag}) {e}')
 add(n,'주어진 정지점의 (fxx,fxy,fyy)가 '+str(rows)+'이다. 각 경우 극값을 판정하라.','At a stationary point, (fxx,fxy,fyy) takes the listed values '+str(rows)+'. Classify each case.',ks,es,'; '.join(aks),'; '.join(aes),'D=0은 극값 부재가 아니라 이 검사만으로 판정하지 못함을 뜻한다.','D=0 means this test is inconclusive, not absence of an extremum.',[chr(97+i) for i in range(len(rows))])
classify(3,4+x**3+y**3-3*x*y,graph=True)
classify(4,3*x-x**3-2*y*y+y**4,graph=True)
for n,F in [(5,x*x+x*y+y*y+y),(6,x*y-2*x-2*y-x*x-y*y),(7,2*x*x-8*x*y+y**4-4*y**3),(8,x**3+y**3+3*x*y),(9,(x-y)*(1-x*y)),(10,y*(S.exp(x)-1)),(11,y*S.sqrt(x)-y*y-2*x+7*y),(12,2-x**4+2*x*x-y*y),(13,x**3-3*x+3*x*y*y),(14,x**3+y**3-3*x*x-3*y*y-9*x),(15,x**4-2*x*x+y**3-3*y),(16,x*x+y**4+2*x*y),(17,x*y-x*x*y-x*y*y),(18,(6*x-x*x)*(4*y-y*y)),(19,S.exp(x)*S.cos(y)),(20,(x*x+y*y)*S.exp(-x))]:classify(n,F,domain='x>0; 경계 x=0에는 국소 극값 없음. ' if n==11 else '')
classify(21,y*y-2*y*S.cos(x),[(0,1),(S.pi,-1),(2*S.pi,1),(S.pi/2,0),(3*S.pi/2,0)],domain='−1≤x≤7. ',extra=' 경계 x=−1,7에는 상대적 국소 극값이 없다. / No relative local extrema occur on x=−1,7.')
classify(22,S.sin(x)*S.sin(y),[(0,0),(S.pi/2,S.pi/2),(-S.pi/2,-S.pi/2),(S.pi/2,-S.pi/2),(-S.pi/2,S.pi/2)],domain='−π<x<π, −π<y<π. ')
add(23,r'\(f=x^2+4y^2-4xy+2\)는 무한히 많은 정지점에서 D=0이다. 모든 점에서 절대극소임을 보여라.',r'Show \(f=x^2+4y^2-4xy+2\) has infinitely many stationary points with D=0, all absolute minima.',[r'\(f=(x-2y)^2+2\), 따라서 기울기0은 x=2y와 동치이다.','헤세행렬은 [[2,−4],[−4,8]], D=16−16=0. 제곱 완성으로 f≥2이다.'],[r'\(f=(x-2y)^2+2\), so the gradient vanishes exactly when x=2y.','The Hessian is [[2,−4],[−4,8]], with D=0. Completing the square gives f≥2.'],'x=2y의 모든 점에서 최솟값2, D=0.','Every point of x=2y is an absolute minimum of value2, with D=0.')
add(24,r'\(f=x^2ye^{-x^2-y^2}\)의 (±1,±1/√2) 극값과 나머지 무한히 많은 정지점의 유형을 판정하라.',r'Classify extrema at (±1,±1/√2) and all remaining stationary points of \(f=x^2ye^{-x^2-y^2}\).',[r'\(f_x=2xy(1-x^2)e^{-x^2-y^2}, f_y=x^2(1-2y^2)e^{-x^2-y^2}\). 정지점은 x=0 전체와 네 고립점이다.','고립점에서 y>0은 극대, y<0은 극소이다. x=0에서는 D=0이나 근방의 부호가 y의 부호와 같다.','따라서 (0,b),b>0은 극소0, b<0은 극대0. 원점은 양·음 값이 모두 있어 안장점이다.'],[r'\(f_x=2xy(1-x^2)e^{-x^2-y^2}, f_y=x^2(1-2y^2)e^{-x^2-y^2}\). Stationary points are the entire axis x=0 and four isolated points.','At isolated points positive y gives maxima, negative y minima. On x=0 the determinant vanishes, but nearby signs agree with y.','Thus (0,b),b>0 are minima0, b<0 maxima0, while the origin is a saddle.'],r'(±1,1/√2): 극대 \(e^{-3/2}/\sqrt2\); (±1,−1/√2): 극소 \(-e^{-3/2}/\sqrt2\). x=0은 위 분류.',r'(±1,1/√2): maxima \(e^{-3/2}/\sqrt2\); (±1,−1/√2): minima \(-e^{-3/2}/\sqrt2\). The axis is classified above.','x²e^(−x²)≤e^(−1), |y|e^(−y²)≤1/√(2e)이므로 네 고립점은 절대극값이기도 하다.','Bounds x²e^(−x²)≤e^(−1) and |y|e^(−y²)≤1/√(2e) also prove the isolated extrema are absolute.')
classify(25,x*x+y*y+1/(x*x*y*y),[(a,b) for a in [-1,1] for b in [-1,1]],domain='xy≠0. ',extra=' 모든 극소는 절대최솟값3이다. / All minima are absolute, of value3.',graph=True)
classify(26,(x-y)*S.exp(-x*x-y*y),[(S.Rational(1,2),-S.Rational(1,2)),(-S.Rational(1,2),S.Rational(1,2))],graph=True)
classify(27,S.sin(x)+S.sin(y)+S.sin(x+y),[(S.pi/3,S.pi/3),(5*S.pi/3,5*S.pi/3),(S.pi,S.pi)],domain='0≤x≤2π,0≤y≤2π. ',graph=True)
# At (pi,pi), D=0 but cubic terms change sign.
e=E[-1];e['steps']['ko'].append('원점 이동 x=π+h,y=π+k에서 선도항은 hk(h+k)/2이므로 (π,π)는 안장점이다.');e['steps']['en'].append('With x=π+h,y=π+k, the leading term is hk(h+k)/2, so (π,π) is a saddle.');e['answer']['ko']=e['answer']['ko'].replace('추가 판정 필요','안장점');e['answer']['en']=e['answer']['en'].replace('inconclusive','saddle');plots[27]=(S.sin(x)+S.sin(y)+S.sin(x+y),(0,2*math.pi,0,2*math.pi))
classify(28,S.sin(x)+S.sin(y)+S.cos(x+y),[(S.pi/6,S.pi/6)],domain='0≤x≤π/4,0≤y≤π/4. ',graph=True);plots[28]=(S.sin(x)+S.sin(y)+S.cos(x+y),(0,math.pi/4,0,math.pi/4))
# Closed plotted rectangles also have relative boundary extrema, reported separately.
E[-2]['steps']['ko'].append('닫힌 사각형 자체에 상대적인 경계 극값까지 포함하면 (0,0)은 극소0, (2π,2π)는 극대0이다. 나머지 경계 정지점은 안장형이다.');E[-2]['steps']['en'].append('Relative to the closed square, (0,0) is a boundary local minimum0 and (2π,2π) a boundary local maximum0; remaining boundary stationary points are saddle-like.')
E[-1]['steps']['ko'].append('닫힌 사각형의 상대 경계 극소는 (0,0):1 및 (π/4,π/4):√2이다. 내부 극대3/2가 절대최대이고 (0,0)이 절대최소이다.');E[-1]['steps']['en'].append('Relative boundary minima are (0,0):1 and (π/4,π/4):√2. The interior maximum3/2 is absolute; (0,0) is the absolute minimum.')
def realroots(poly):return [float(S.re(a)) for a in S.nroots(poly,maxsteps=100) if abs(float(S.im(a)))<1e-10]
ys=realroots(2*y**3-4*y+1);pts=[(0,-2**(-1/3))]+[(sgn*math.sqrt(2*b),b) for b in ys if b>0 for sgn in [-1,1]]
classify(29,x**4+y**4-4*x*x*y+2*y,pts,numeric=True);E[-1]['steps']['ko'].append('최고차 양의 항들이 무한대에서 지배하여 절대최소는 표시된 극소값들 중 가장 작다. 위로는 무한하여 최고점은 없다.');E[-1]['steps']['en'].append('The positive leading terms make the function coercive, so the smallest listed minimum is absolute; there is no highest point.')
classify(30,y**6-2*y**4+x*x-y*y+y,[(0,b) for b in realroots(6*y**5-8*y**3-2*y+1)],numeric=True);E[-1]['steps']['ko'].append('무한대에서 f→∞이므로 가장 낮은 극소가 절대최소이고 최고점은 없다.');E[-1]['steps']['en'].append('Since f→∞ at infinity, the lower minimum is absolute and no highest point exists.')
classify(31,x**4+y**3-3*x*x+y*y+x-2*y+1,[(a,b) for a in realroots(4*x**3-6*x+1) for b in [(-1-math.sqrt(7))/3,(-1+math.sqrt(7))/3]],numeric=True);E[-1]['steps']['ko'].append('y→±∞에서 f→±∞이므로 최고·최저점은 없다.');E[-1]['steps']['en'].append('As y→±∞, f→±∞, so neither highest nor lowest point exists.')
a=float(S.nsolve(3*S.cos(3*x)-2*x*S.sin(3*x),.4));b=float(S.nsolve(2*y*S.cos(3*y)+3*S.sin(3*y),.9));classify(32,20*S.exp(-x*x-y*y)*S.sin(3*x)*S.cos(3*y),[(sg*a,yy) for sg in [-1,1] for yy in [-b,0,b]],numeric=True,domain='|x|≤1,|y|≤1. ');E[-1]['steps']['ko'].append('변수별 곱의 절댓값을 경계까지 비교하면 최고점은 (a,0), 최저점은 (−a,0), a≈'+str(round(a,3))+'.');E[-1]['steps']['en'].append('Comparing both one-variable factors including boundary endpoints gives highest at (a,0) and lowest at (−a,0), a≈'+str(round(a,3))+'.')
def polygon(n,F,vertices):
 # Edge-restricted derivatives enumerate every boundary candidate.
 candidates=set(vertices);details=[]
 for i,P in enumerate(vertices):
  Q=vertices[(i+1)%len(vertices)];xx=P[0]+t*(Q[0]-P[0]);yy=P[1]+t*(Q[1]-P[1]);g=S.expand(F.subs({x:xx,y:yy},simultaneous=True));roots=S.solve(S.diff(g,t),t)
  vals=[a for a in roots if a.is_real and 0<=float(a)<=1]
  for a in vals:candidates.add((S.simplify(xx.subs(t,a)),S.simplify(yy.subs(t,a))))
  details.append(M(g)+', 0≤t≤1; t='+(', '.join(M(a) for a in vals) or '—'))
 for pt in S.solve([S.diff(F,x),S.diff(F,y)],(x,y),dict=True):
  if x not in pt or y not in pt or pt[x].is_real is False or pt[y].is_real is False:continue
  xx,yy=pt[x],pt[y];cross=[float((vertices[(i+1)%len(vertices)][0]-a)*(yy-b)-(vertices[(i+1)%len(vertices)][1]-b)*(xx-a)) for i,(a,b) in enumerate(vertices)]
  if min(cross)>=-1e-9 or max(cross)<=1e-9:candidates.add((xx,yy))
 table=sorted([(S.simplify(F.subs({x:a,y:b})),a,b) for a,b in candidates],key=lambda row:float(row[0]));mn=table[0][0];mx=table[-1][0];mins=[S.Tuple(a,b) for val,a,b in table if S.simplify(val-mn)==0];maxs=[S.Tuple(a,b) for val,a,b in table if S.simplify(val-mx)==0]
 vals='; '.join(M(S.Tuple(a,b))+': '+M(val) for val,a,b in table)
 st='f='+M(F)+', D vertices='+str(vertices)+'. '
 add(n,st+'D에서 절대최대·최소를 구하라.',st+'Find absolute extrema on D.',['내부에서 fx=fy=0을 풀고 D 안의 점만 남긴다.','순서대로 각 변을 P+t(Q−P)로 쓰면 다음 단변수식과 내부 정지 매개변수를 얻는다: '+'; '.join(details),'꼭짓점·변 정지점·내부 정지점의 값: '+vals],['Solve fx=fy=0 in the interior, keeping points in D.','On successive edges P+t(Q−P), the restricted polynomials and stationary parameters are: '+'; '.join(details),'Values at all vertex, edge, and interior candidates: '+vals],'최소 '+M(mn)+' at '+','.join(M(a) for a in mins)+'; 최대 '+M(mx)+' at '+','.join(M(a) for a in maxs),'Minimum '+M(mn)+' at '+','.join(M(a) for a in mins)+'; maximum '+M(mx)+' at '+','.join(M(a) for a in maxs),'닫히고 유계인 다각형에서 연속이므로 극값이 존재하며 모든 경계 변을 따로 미분했다.','Continuity on the compact polygon guarantees extrema, and every edge was separately differentiated.')
for row in [(33,x*x+y*y-2*x,[(2,0),(0,2),(0,-2)]),(34,x+y-x*y,[(0,0),(0,2),(4,0)]),(35,x*x+y*y+x*x*y+4,[(-1,-1),(1,-1),(1,1),(-1,1)]),(36,x*x+x*y+y*y-6*y,[(-3,0),(3,0),(3,5),(-3,5)]),(37,x*x+2*y*y-2*x-4*y+1,[(0,0),(2,0),(2,3),(0,3)]),(40,x**3-3*x-y**3+12*y,[(-2,3),(2,3),(2,2),(-2,-2)])]:polygon(*row)
add(38,r'\(f=xy^2\), D: x≥0,y≥0,x²+y²≤3의 절대극값을 구하라.',r'Find absolute extrema of \(f=xy^2\) on x≥0,y≥0,x²+y²≤3.',['f≥0이고 두 축에서 f=0. 양의 내부에서는 fx=y²>0이므로 최대는 원호 위이다.','원호에서 y²=3−x²이므로 f=3x−x³,0≤x≤√3. f′=3−3x²는 x=1에서0이다.'],['The function is nonnegative and vanishes on both axes. For positive interior points fx=y²>0, so a maximum lies on the arc.','On the arc f=3x−x³,0≤x≤√3; f′=3−3x² vanishes at x=1.'],'최소0: D의 두 축 부분 전체. 최대2: (1,√2).','Minimum0 on both axis segments in D; maximum2 at (1,√2).')
add(39,r'\(f=2x^3+y^4\), D:x²+y²≤1의 절대극값을 구하라.',r'Find absolute extrema of \(f=2x^3+y^4\) on x²+y²≤1.',['내부 정지점은 (0,0), 값0. 원둘레에서 f=2x³+(1−x²)²이다.','경계 미분은 2x(2x−1)(x+2). [−1,1]에서 후보 x=−1,0,1/2,1의 값은 −2,1,13/16,2이다.'],['The interior stationary point is (0,0), value0. On the boundary f=2x³+(1−x²)².','Its derivative is 2x(2x−1)(x+2). Candidates x=−1,0,1/2,1 have values−2,1,13/16,2.'],'최소−2: (−1,0). 최대2: (1,0).','Minimum−2 at (−1,0); maximum2 at (1,0).')
F=-(x*x-1)**2-(x*x*y-x-1)**2
add(41,'f='+M(F)+'가 정지점이 두 개뿐이고 둘 다 극대임을 보여라. 두 봉우리가 보이는 그래프를 그려라.','Show f='+M(F)+' has exactly two stationary points, both maxima, and plot the two peaks.',['fy=−2x²(x²y−x−1). x=0이면 fx=−2≠0이므로 정지점이 아니다.','x≠0이면 x²y−x−1=0, fx=−4x(x²−1)=0이므로 x=±1. 이에 y=2 또는0이다.','f는 두 음의 제곱의 합으로0 이하이며 두 점에서0이다.'],['fy=−2x²(x²y−x−1). At x=0,fx=−2≠0, so there is no stationary point.','For x≠0, x²y−x−1=0 and fx=−4x(x²−1)=0, hence x=±1 and y=2 or0.','As a sum of negative squares, f≤0 and equals0 at both points.'],'(1,2), (−1,0)에서 절대극대0. 다른 정지점과 극소는 없다.','Absolute maxima0 at (1,2) and (−1,0); no other stationary points or minima.');plots[41]=(F,(-1.7,1.7,-1,3))
F=3*x*S.exp(y)-x**3-S.exp(3*y)
add(42,'f='+M(F)+'가 유일한 정지점에서 국소 극대이지만 절대극대는 아님을 보여주고 그래프로 설명하라.','Show f='+M(F)+' has a unique stationary point that is a local but not absolute maximum; illustrate graphically.',['fx=3eʸ−3x²=0, fy=3xeʸ−3e³ʸ=0에서 x=e²ʸ>0과 eʸ=x²를 얻어 (x,y)=(1,0).','헤세행렬 [[−6,3],[3,−6]]의 D=27>0,fxx<0이므로 극대, f=1.','그러나 y=0에서 f=3x−x³−1→∞ as x→−∞이다.'],['The stationary equations give x=e²ʸ>0 and eʸ=x², forcing (1,0).','The Hessian [[−6,3],[3,−6]] has D=27>0 and fxx<0, yielding local maximum1.','But along y=0, f=3x−x³−1→∞ as x→−∞.'],'유일한 정지점 (1,0), 국소극대1; 절대최대는 없다.','Unique stationary point (1,0), local maximum1; no absolute maximum.');plots[42]=(F,(-3,2,-1,1))
add(43,'점 (2,0,−3)에서 평면 x+y+z=1까지 최단거리를 구하라.','Find the shortest distance from (2,0,−3) to x+y+z=1.',['평면 법선은 (1,1,1). 점을 좌변−우변에 넣으면−2이다.','법선 길이√3으로 절댓값을 나누면 거리2/√3. 수선발은 (8/3,2/3,−7/3)이다.'],['The plane normal is (1,1,1), and its defining expression at the point is−2.','Divide the absolute value by normal length√3 to obtain2/√3; the foot is (8/3,2/3,−7/3).'],r'\(2/\sqrt3\).',r'\(2/\sqrt3\).')
add(44,'평면 x−2y+3z=6에서 (0,1,1)에 가장 가까운 점을 구하라.','Find the point on x−2y+3z=6 closest to (0,1,1).',['법선 n=(1,−2,3),||n||²=14이다.','수선발은 P+tn이고 평면에 넣으면1+14t=6, t=5/14이다.'],['The normal is n=(1,−2,3), with squared norm14.','The foot P+tn satisfies1+14t=6, so t=5/14.'],'(5/14,2/7,29/14).','(5/14,2/7,29/14).')
add(45,r'원뿔 \(z^2=x^2+y^2\)에서 (4,2,0)에 가장 가까운 점들을 구하라.',r'Find the closest points on \(z^2=x^2+y^2\) to (4,2,0).',['제약식을 거리제곱에 대입하면 (x−4)²+(y−2)²+x²+y².','이는 2(x−2)²+2(y−1)²+10이므로 x=2,y=1, z=±√5에서 최소이다.'],['Substitute the constraint into squared distance: (x−4)²+(y−2)²+x²+y².','This is2(x−2)²+2(y−1)²+10, minimized at x=2,y=1,z=±√5.'],'(2,1,±√5), 최단거리√10.','(2,1,±√5), shortest distance√10.')
add(46,'곡면 y²=9+xz에서 원점에 가장 가까운 점들을 구하라.','Find points of y²=9+xz closest to the origin.',['거리제곱=x²+y²+z²=9+x²+xz+z².','x²+xz+z²=(x+z/2)²+3z²/4≥0, 등호는 x=z=0이다.'],['Squared distance is9+x²+xz+z².','Complete the square: x²+xz+z²=(x+z/2)²+3z²/4≥0, with equality only at x=z=0.'],'(0,±3,0), 최단거리3.','(0,±3,0), shortest distance3.')
for n,total,objective in [(47,100,'product'),(48,12,'squares')]:
 if objective=='product':ks=['양수 a+b+c=100에서 AM–GM으로 abc≤(100/3)³이다.','등호는 세 수가 같을 때 성립한다.'];es=['AM–GM gives abc≤(100/3)³ for positive a+b+c=100.','Equality requires all three numbers equal.'];ka='세 수100/3, 최대곱1,000,000/27.';ea='All three are100/3; maximum product1,000,000/27.'
 else:ks=['a²+b²+c²≥(a+b+c)²/3=48이다.','등호 조건은 a=b=c=4.'];es=['a²+b²+c²≥(a+b+c)²/3=48.','Equality holds at a=b=c=4.'];ka='세 수4, 제곱합 최소48.';ea='All three are4; minimum sum of squares48.'
 add(n,f'합이{total}인 세 양수의 '+('곱을 최대화하라.' if objective=='product' else '제곱합을 최소화하라.'),f'For three positive numbers summing to{total}, '+('maximize their product.' if objective=='product' else 'minimize their sum of squares.'),ks,es,ka,ea)
add(49,'반지름 r의 구에 내접하는 직육면체의 최대부피를 구하라.','Find the largest volume of a rectangular box inscribed in a sphere of radius r.',['변 길이 a,b,c에 대해 대각선 제약 a²+b²+c²=4r²이다.','AM–GM으로 (abc)²≤(4r²/3)³, 등호는 a=b=c.'],['Side lengths satisfy a²+b²+c²=4r².','AM–GM gives (abc)²≤(4r²/3)³, with equality at a=b=c.'],r'변 \(2r/\sqrt3\), 최대부피 \(8r^3/(3\sqrt3)\).',r'Sides \(2r/\sqrt3\); maximum volume \(8r^3/(3\sqrt3)\).')
add(50,'부피1000 cm³의 닫힌 직육면체에서 겉넓이를 최소화하는 치수를 구하라.','Find dimensions minimizing the surface area of a closed box of volume1000 cm³.',['S=2(ab+bc+ca), abc=1000.','ab+bc+ca≥3(abc)^(2/3)=300, 등호는 a=b=c=10.'],['S=2(ab+bc+ca), abc=1000.','ab+bc+ca≥3(abc)^(2/3)=300, with equality at a=b=c=10.'],'10×10×10 cm, 최소겉넓이600 cm².','10×10×10 cm; minimum surface area600 cm².')
add(51,'첫 팔분공간에서 좌표평면에 세 면을 두고 반대 꼭짓점이 x+2y+3z=6인 직육면체의 최대부피를 구하라.','Find the largest first-octant box with three faces in coordinate planes and opposite vertex on x+2y+3z=6.',['양수 x,2y,3z의 합은6. 곱6xyz≤2³이다.','등호는 x=2y=3z=2이다.'],['The positive quantities x,2y,3z sum to6, so6xyz≤2³.','Equality holds at x=2y=3z=2.'],'치수(2,1,2/3), 최대부피4/3.','Dimensions(2,1,2/3); maximum volume4/3.')
add(52,'겉넓이64 cm²의 닫힌 직육면체에서 최대부피의 치수를 구하라.','Find dimensions of the maximum-volume closed box with surface area64 cm².',['ab+bc+ca=32. AM–GM으로 (abc)²≤(32/3)³이다.','등호 조건 ab=bc=ca는 양수 치수가 모두 같음을 뜻한다.'],['ab+bc+ca=32, so AM–GM yields (abc)²≤(32/3)³.','Equality ab=bc=ca forces all positive side lengths equal.'],r'각 변 \(4\sqrt{2/3}\) cm.',r'Each side is \(4\sqrt{2/3}\) cm.')
add(53,'12개 모서리 길이의 합이 c인 직육면체의 최대부피 치수를 구하라.','Find dimensions maximizing a box’s volume when its twelve edges have total length c.',['4(a+b+d)=c, 따라서 abc 대신 abd≤((a+b+d)/3)³=(c/12)³.','등호는 a=b=d=c/12이다.'],['4(a+b+d)=c, and abd≤((a+b+d)/3)³=(c/12)³.','Equality requires a=b=d=c/12.'],'각 변c/12, 최대부피c³/1728.','Each side c/12; maximum volume c³/1728.')
add(54,'부피 V인 뚜껑 없는 수조의 밑면 재료는 옆면 유리의 면적당 가격5배이다. 재료비를 최소화하는 치수를 구하라.','An open aquarium of volume V has base material costing five times as much per area as glass sides. Find cost-minimizing dimensions.',['유리 단가로 나눈 비용 C=5ab+2h(a+b), h=V/(ab).','Ca=5b−2V/a²=0,Cb=5a−2V/b²=0으로 a=b, a³=2V/5. 비용은 경계에서 무한대로 가므로 이 유일한 정지점이 최소이다.'],['In glass-cost units C=5ab+2h(a+b), with h=V/(ab).','Stationarity gives5b−2V/a²=0 and5a−2V/b²=0, hence a=b and a³=2V/5. Cost diverges at domain extremes, so the unique stationary point is minimal.'],r'정사각 밑변 \((2V/5)^{1/3}\), 높이 \((25V/4)^{1/3}\).',r'Square base side \((2V/5)^{1/3}\); height \((25V/4)^{1/3}\).')
add(55,'부피32,000 cm³의 뚜껑 없는 직육면체 상자에서 종이를 최소화하는 치수를 구하라.','Find dimensions minimizing cardboard for an open box of volume32,000 cm³.',['밑변 a,b,높이 h에서 A=ab+2V/a+2V/b.','정지식 b=2V/a²,a=2V/b²는 a=b와 a³=64,000을 준다.'],['For base a,b and height h, A=ab+2V/a+2V/b.','Stationarity b=2V/a²,a=2V/b² gives a=b and a³=64,000.'],'밑면40×40 cm, 높이20 cm; 종이4800 cm².','Base40×40 cm, height20 cm; cardboard4800 cm².')
add(56,'건물 부피4000 m³, 밑변 a,b≥30 m, 높이h≥4 m. 동·서벽 손실10, 남·북벽8, 바닥1, 지붕5(단위/m²/day)이다. a는 동서 길이이다. (a) 비용 정의역을 그리고 (b) 제약하 최소 치수 (c) 벽 길이 제한을 없앤 개선 가능성을 구하라.','A4000 m³ building has base a,b≥30 m and height h≥4 m. East/west walls lose10, north/south walls8, floor1, roof5 units/m²/day; a is east–west length. (a) Sketch the domain; (b) minimize with constraints; (c) consider removing wall-length restrictions.',['(a) h=4000/(ab), 따라서 a≥30,b≥30,ab≤1000. 비용 H=16ah+20bh+6ab=64000/b+80000/a+6ab.','(b) 이 영역에서 Ha=−80000/a²+6b>0,Hb=−64000/b²+6a>0. 따라서 가장 작은 a=b=30이 최소이다. h=40/9, H=10200.','(c) 제한을 없애면 정지식에서 a/b=5/4, b³=25600/3, h=3b/8. 이 점은 h≥4도 만족하고 더 작은 손실을 준다.'],['(a) Since h=4000/(ab), the domain is a≥30,b≥30,ab≤1000. Heat loss is H=16ah+20bh+6ab=64000/b+80000/a+6ab.','(b) Throughout this region Ha=−80000/a²+6b>0 and Hb=−64000/b²+6a>0. Thus a=b=30 minimizes H, with h=40/9 and H=10200.','(c) Removing length restrictions yields a/b=5/4,b³=25600/3,h=3b/8. This also satisfies h≥4 and yields lower loss.'],r'(a) a≥30,b≥30,ab≤1000. (b) 30×30×(40/9) m. (c) \(b=(25600/3)^{1/3},a=5b/4,h=3b/8\); 가능.',r'(a) a≥30,b≥30,ab≤1000. (b) 30×30×(40/9) m. (c) \(b=(25600/3)^{1/3},a=5b/4,h=3b/8\); yes.','세 양의 비용 항에 AM–GM을 적용하면 자유 최적점의 전역 최소성도 확인된다.','AM–GM on the three positive cost terms also verifies the unconstrained global minimum.',['a','b','c'])
add(57,'직육면체 대각선 길이가 L일 때 가능한 최대부피를 구하라.','Find the largest volume of a box whose diagonal has length L.',['a²+b²+c²=L²에 AM–GM을 적용한다.','(abc)²≤(L²/3)³이고 등호는 a=b=c이다.'],['Apply AM–GM to a²+b²+c²=L².','(abc)²≤(L²/3)³, with equality at a=b=c.'],r'각 변 \(L/\sqrt3\), 최대부피 \(L^3/(3\sqrt3)\).',r'Each side \(L/\sqrt3\); maximum volume \(L^3/(3\sqrt3)\).')
add(58,r'작물 수확량 \(Y=kNPe^{-N-P}\), k>0,N,P≥0에서 최적 질소·인 수준을 구하라.',r'Maximize crop yield \(Y=kNPe^{-N-P}\) for k>0,N,P≥0.',['Y=k(Ne^(−N))(Pe^(−P))로 분리한다.','t e^(−t)의 미분은(1−t)e^(−t)로 t=1에서 유일한 최대 e^(−1)을 갖는다.'],['Factor Y=k(Ne^(−N))(Pe^(−P)).','The derivative of t e^(−t) is(1−t)e^(−t), giving its unique maximum e^(−1) at t=1.'],'N=P=1, 최대Y=k/e².','N=P=1; maximumY=k/e².')
add(59,'세 종의 비율 pi로 정의한 Shannon 지수 H=−Σpi ln pi를 다룬다. (a) 두 변수 함수 (b) 정의역 (c) 최대값과 비율을 구하라.','For three-species Shannon index H=−Σpi ln pi, find (a) a two-variable expression, (b) its domain, and (c) its maximum and proportions.',[r'(a) p=p₁,q=p₂라 하면 \(H=-p\ln p-q\ln q-(1-p-q)\ln(1-p-q)\).','(b) 로그식 그대로는 p>0,q>0,p+q<1. 0 ln0=0의 연속 확장을 쓰면 닫힌 삼각형도 포함된다.','(c) Hp=ln((1−p−q)/p), Hq=ln((1−p−q)/q)이므로 세 비율1/3. H는 엄격 오목하며 경계는 최대ln2이므로 전역최대이다.'],[r'(a) With p=p₁,q=p₂, \(H=-p\ln p-q\ln q-(1-p-q)\ln(1-p-q)\).','(b) The literal log formula has p>0,q>0,p+q<1. Its continuous extension0 ln0=0 includes the closed triangle.','(c) Hp=ln((1−p−q)/p), Hq=ln((1−p−q)/q), so each proportion is1/3. Strict concavity and boundary maximumln2 establish global maximality.'],'최대ln3, p₁=p₂=p₃=1/3.','Maximumln3 at p₁=p₂=p₃=1/3.','확장 정의역과 로그 자체의 정의역을 구분했다.','The log domain is distinguished from its continuous extension.',['a','b','c'])
add(60,'p,q,r≥0,p+q+r=1일 때 서로 다른 대립유전자 비율 P=2pq+2pr+2qr가2/3 이하임을 보여라.','Show P=2pq+2pr+2qr≤2/3 for nonnegative p,q,r summing to1.',['P=(p+q+r)²−(p²+q²+r²)=1−(p²+q²+r²).','제곱합은 합의 제곱/3 이상이므로 P≤1−1/3.'],['P=1−(p²+q²+r²).','The sum of squares is at least the square of the sum divided by3, so P≤1−1/3.'],'P≤2/3, 등호는 p=q=r=1/3.','P≤2/3, with equality at p=q=r=1/3.')
add(61,r'데이터 (xi,yi)의 잔차제곱합 \(S(m,b)=\sum_i(y_i-mx_i-b)^2\)을 최소화하는 직선의 두 정상방정식을 유도하라.',r'Derive the normal equations for the line minimizing \(S(m,b)=\sum_i(y_i-mx_i-b)^2\).',[r'\(S_b=-2\sum_i(y_i-mx_i-b)=0\).',r'\(S_m=-2\sum_ix_i(y_i-mx_i-b)=0\).','목적함수는 제곱합인 볼록 이차식이므로 정상방정식의 해는 전역최소이다. xi가 모두 같지 않으면 헤세행렬은 양의 정부호로 해가 유일하다.'],[r'\(S_b=-2\sum_i(y_i-mx_i-b)=0\).',r'\(S_m=-2\sum_ix_i(y_i-mx_i-b)=0\).','A sum of squared affine functions is convex, so normal-equation solutions are global minima. If the xi are not all equal, the Hessian is positive definite and the solution is unique.'],r'\(m\sum x_i+nb=\sum y_i\), \(m\sum x_i^2+b\sum x_i=\sum x_iy_i\).',r'\(m\sum x_i+nb=\sum y_i\), \(m\sum x_i^2+b\sum x_i=\sum x_iy_i\).','xi가 모두 같으면 기울기·절편이 따로 유일하지 않아도 그 x에서의 예측값은 평균y이다.','If all xi coincide, slope and intercept are not individually unique, but the fitted value at that x is the mean y.')
add(62,'(1,2,3)을 지나고 첫 팔분공간에서 좌표평면과 최소부피를 자르는 평면을 구하라.','Find the plane through (1,2,3) cutting off the smallest first-octant volume with coordinate planes.',['양의 절편 A,B,C의 평면은 x/A+y/B+z/C=1이며 1/A+2/B+3/C=1.','p=1/A,q=2/B,r=3/C라 놓으면 V=ABC/6=1/(pqr). AM–GM으로 pqr≤1/27이므로 V≥27.'],['Positive intercepts A,B,C satisfy1/A+2/B+3/C=1.','Let p=1/A,q=2/B,r=3/C. Then V=ABC/6=1/(pqr), and AM–GM gives pqr≤1/27, hence V≥27.'],'평면 x/3+y/6+z/9=1, 최소부피27.','Plane x/3+y/6+z/9=1; minimum volume27.')
E.sort(key=lambda a:a['number']);assert [a['number'] for a in E]==list(range(1,63))
D=dict(section='14.7',source=dict(title='Calculus',edition='9',language='en',printedPages=[1054,1055,1056,1057],pdfPages=[1091,1092,1093,1094]),scope=dict(kind='exercise',numbers=list(range(1,63)),total=62,note=pair('전체62문항과 모든 소문항.','All62 exercises and every subpart.')),exercises=E)
(R/'exercise-content/s14-7.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
# Original wireframe plots for explicitly requested graphical exercises.
A=R/'exercise-content/assets'
for n,(F,box) in plots.items():
 fn=S.lambdify((x,y),F,'math');a,b,c,d=box;segments=[];values=[]
 for i in range(25):
  for swap in [False,True]:
   pts=[]
   for j in range(61):
    xx=a+(b-a)*(i/24 if swap else j/60);yy=c+(d-c)*(j/60 if swap else i/24)
    try:zz=fn(xx,yy)
    except (ValueError,ZeroDivisionError):continue
    if math.isfinite(zz):pts.append((xx,yy,zz));values.append(zz)
   segments.append(pts)
 lo=min(values);hi=max(values)
 if n==25:lo=3;hi=15
 if n==41:lo=-15;hi=0
 project=lambda xx,yy,zz:(400+190*(xx-a)/(b-a)-140*(yy-c)/(d-c),390+55*(xx-a)/(b-a)+55*(yy-c)/(d-c)-300*(zz-lo)/max(1,hi-lo))
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 850 550"><rect width="850" height="550" fill="white"/>',f'<text x="425" y="30" text-anchor="middle" font-family="sans-serif">14.7.{n}: original function wireframe</text>']
 for pts in segments:
  run=[]
  for xx,yy,zz in pts:
   if lo<=zz<=hi:run.append(project(xx,yy,zz))
   elif run:out.append('<polyline points="'+' '.join(f'{u:.2f},{v:.2f}' for u,v in run)+'" fill="none" stroke="#3875ad" stroke-width="1"/>');run=[]
  if run:out.append('<polyline points="'+' '.join(f'{u:.2f},{v:.2f}' for u,v in run)+'" fill="none" stroke="#3875ad" stroke-width="1"/>')
 out.append(f'<text x="425" y="515" text-anchor="middle" font-family="sans-serif">x: [{a:.2f}, {b:.2f}], y: [{c:.2f}, {d:.2f}], z: [{lo:.2f}, {hi:.2f}]</text></svg>');name=f's14-7-{n}.svg';(A/name).write_text('\n'.join(out));next(e for e in E if e['number']==n)['figure']=dict(src='../exercise-content/assets/'+name,alt=pair('함수를 직접 표본화한 곡면 그래프','Surface graph sampled directly from the function'),caption=pair('표시된 좌표 범위의 자체 곡면. 극값의 정확한 위치는 해설의 미분 계산으로 판정한다.','Original surface over the displayed coordinate ranges. Calculus in the solution determines exact extrema.'))
out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 650 450"><rect width="650" height="450" fill="white"/><text x="325" y="30" text-anchor="middle">Feasible base dimensions: a,b ≥ 30, ab ≤ 1000</text>'];proj=lambda a,b:(100+90*(a-29),360-90*(b-29));pts=[proj(30,30),proj(100/3,30)]+[proj(a,1000/a) for a in [100/3-i*(10/3)/60 for i in range(61)]];out.append('<polygon points="'+' '.join(f'{a},{b}' for a,b in pts)+'" fill="#c6dcef" stroke="#3875ad"/>');out.append('<text x="145" y="320">(30,30): minimum</text><text x="380" y="185">ab=1000</text></svg>');name='s14-7-56.svg';(A/name).write_text('\n'.join(out));next(e for e in E if e['number']==56)['figure']=dict(src='../exercise-content/assets/'+name,alt=pair('건물 밑면의 허용영역','Feasible building base dimensions'),caption=pair('직선 a=30,b=30과 쌍곡선 ab=1000으로 둘러싸인 영역.','Region bounded by a=30,b=30 and hyperbola ab=1000.'))
(R/'exercise-content/s14-7.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n');print('14.7:62 cards;',len(plots)+1,'figures')
