import sympy as S,json,math,itertools
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=[];plots={};x,y,z,r,s,t,u,v,w,p,a,b,k,l,m=S.symbols('x y z r s t u v w p alpha beta k l m',real=True);M=lambda q:r'\('+S.latex(S.simplify(q))+r'\)';pair=lambda a,b:dict(ko=a,en=b)
def add(n,ko,en,ks,es,ka,ea,kc='원문 조건과 정의역을 확인하고 계산을 독립 대입했다.',ec='Source conditions and domains were checked and calculations independently substituted.',parts=[]):
 pg=1070 if n<=17 else 1071 if n<=47 else 1072
 E.append(dict(id=f'stewart9-review-14.9-{n}',number=n,subparts=parts,source=dict(printedPage=pg,pdfPage=pg+37),topic=pair('14장 종합 복습','Chapter14 review'),statement=pair(ko,en),hint=pair('함수의 정의역과 미분 조건을 먼저 확인하고 해당 미분·극값 공식을 적용한다.','Check the domain and differentiability assumptions, then apply the relevant derivative or extremum formula.'),steps=pair(ks,es),answer=pair(ka,ea),check=pair(kc,ec),conceptHref='../s14-8.html',status='math-verified'))
add(1,r'\(f=\ln(x+y+1)\)의 정의역을 구하고 그려라.',r'Find and sketch the domain of \(f=\ln(x+y+1)\).',['로그 인수는 양수여야 하므로 x+y+1>0.','직선 y=−x−1 위쪽의 열린 반평면이며 경계선은 제외한다.'],['A logarithm requires x+y+1>0.','This is the open half-plane above y=−x−1; exclude its boundary.'],'y>−x−1.','y>−x−1.')
add(2,r'\(f=\sqrt{4-x^2-y^2}+\sqrt{1-x^2}\)의 정의역을 구하고 그려라.',r'Find and sketch the domain of \(f=\sqrt{4-x^2-y^2}+\sqrt{1-x^2}\).',['두 근호 안이 모두0 이상이어야 한다.','반지름2의 원판과 수직 띠−1≤x≤1의 교집합이다.'],['Both radicands must be nonnegative.','Intersect the radius2 disk with the vertical strip−1≤x≤1.'],'x²+y²≤4, |x|≤1; 경계 포함.','x²+y²≤4, |x|≤1; boundaries included.')
add(3,'f=1−y²의 그래프를 그려라.','Sketch the graph of f=1−y².',['x값은 높이에 영향을 주지 않는다.','yz평면의 아래로 열린 포물선 z=1−y²를 x방향으로 평행 이동한다.'],['Height is independent of x.','Translate the downward parabola z=1−y² parallel to the x-axis.'],'꼭대기 직선 y=0,z=1인 포물기둥.','Parabolic cylinder with ridge y=0,z=1.');plots[3]=(1-y*y,(-2,2,-2,2))
add(4,'f=x²+(y−2)²의 그래프를 그려라.','Sketch f=x²+(y−2)².',['z≥0이며 최소는 x=0,y=2에서0.','수평 절단은 중심(0,2), 반지름√z인 원이다.'],['z≥0 with minimum0 at (0,2).','Horizontal sections are circles centered at (0,2) of radius√z.'],'꼭짓점(0,2,0), 위로 열린 원형 포물면.','Upward circular paraboloid with vertex(0,2,0).');plots[4]=(x*x+(y-2)**2,(-2,2,0,4))
add(5,r'\(f=\sqrt{4x^2+y^2}\)의 등위곡선을 여러 개 그려라.',r'Sketch several level curves of \(f=\sqrt{4x^2+y^2}\).',['f=c이면 c≥0이고 4x²+y²=c².','c>0에서 x반축c/2,y반축c인 타원. c=0은 원점이다.'],['Level f=c requires c≥0 and4x²+y²=c².','For c>0 these are ellipses with semiaxes c/2 and c; c=0 is the origin.'],'4x²+y²=c², c≥0.','4x²+y²=c², c≥0.')
add(6,'f=eˣ+y의 등위곡선을 여러 개 그려라.','Sketch several level curves of f=eˣ+y.',['f=c를 y에 대해 풀면 y=c−eˣ.','−eˣ 곡선을 위아래로 평행 이동한 가족이다.'],['Solve f=c for y: y=c−eˣ.','These are vertical translates of−eˣ.'],'y=c−eˣ, c∈R.','y=c−eˣ, c∈R.')
add(7,'0≤x,y≤2의 곡면은 경계에서 높이0이고 네 내부 사분영역에 봉우리·골짜기가 번갈아 있다. 이 원문 곡면의 대략적 등고선 지도를 그려라.','On0≤x,y≤2 the source surface has zero-height boundaries and alternating peaks and troughs in four interior quarters. Sketch its qualitative contour map.',['봉우리 두 개 주위에는 양의 폐곡선, 골짜기 두 개 주위에는 음의 폐곡선을 그린다.','가운데 교차하는0등고선으로 네 영역을 나눈다. 동일한 정성적 형태의 대표 함수 sin(πx)sin(πy)를 자체 도해에 사용한다.'],['Draw positive nested closed contours around two peaks and negative contours around two troughs.','Crossing central zero contours separate the four regions. The original diagram uses the representative sin(πx)sin(πy) with the same qualitative pattern.'],'번갈아 있는 두 양의 중심·두 음의 중심, 가운데0등고선 교차.','Two alternating positive centers and two negative centers, separated by crossing zero contours.','도해 함수는 원문의 정확한 식으로 주장하지 않는 정성적 예이다.','The illustrative function is a qualitative example, not a claimed exact source formula.')
add(8,'원문 등고선은10 간격이며 (3,2)는50과60선 사이, 오른쪽으로 갈수록 값이 작다. x=2의 y=1부근 등고선이 y=2보다 촘촘하다. (a) f(3,2) (b) fx 부호 (c) fy(2,1)과fy(2,2)를 비교하라.','Source contours differ by10; (3,2) lies between50 and60, with values decreasing rightward. Along x=2, contours near y=1 are closer than near y=2. (a) Estimate f(3,2), (b) sign of fx, and (c) compare fy(2,1),fy(2,2).',['(a) 두 인접선 사이에서 대략55로 읽는다. (b) 오른쪽으로 높이가 낮아지므로 fx<0.','(c) 두 곳 모두 위로 갈수록 값이 증가하나 y=1에서 동일 값 변화가 더 짧은 거리에서 일어난다.'],['(a) Interpolate approximately55. (b) Values fall rightward, so fx<0.','(c) Values increase upward at both points, but the same increase takes less distance near y=1.'],'(a) 약55. (b) 음수. (c) fy(2,1)>fy(2,2).','(a) Approximately55. (b) Negative. (c) fy(2,1)>fy(2,2).',parts=['a','b','c'])
for n,P in [(9,(1,1)),(10,(0,0))]:
 if n==9:ks=['분모는 기준점에서3≠0이므로 연속성으로 직접 대입한다.','2·1·1/(1+2)=2/3.'];es=['The denominator is3≠0 at the point, so use continuity.','2·1·1/(1+2)=2/3.'];ka=ea='2/3.'
 else:ks=['y=0으로 접근하면 함수는0.','y=x≠0으로 접근하면2/3. 두 경로 극한이 다르다.'];es=['Along y=0 the function equals0.','Along y=x≠0 it equals2/3; the path limits differ.'];ka='극한 없음.';ea='The limit does not exist.'
 add(n,r'\(2xy/(x^2+2y^2)\)의 '+str(P)+'에서 극한을 구하라.',r'Find the limit of \(2xy/(x^2+2y^2)\) at '+str(P)+'.',ks,es,ka,ea)
add(11,'온도표의 (x,y)는m, T는°C. 필요한 값은 T(4,4)=72,T(8,4)=86,T(6,2)=87,T(6,6)=75,T(4,2)=74,T(4,6)=68,T(8,2)=90,T(8,6)=80이다. (a) Tx,Ty(6,4)와단위 (b) u=(1,1)/√2 방향미분·해석 (c) Txy를 추정하라.','For temperature data with coordinates in metres and T in°C, T(4,4)=72,T(8,4)=86,T(6,2)=87,T(6,6)=75,T(4,2)=74,T(4,6)=68,T(8,2)=90,T(8,6)=80. Estimate (a) Tx,Ty at(6,4) and units, (b) the derivative for u=(1,1)/√2 and interpret it, (c) Txy.',['(a) 중앙차분 Tx≈(86−72)/4=3.5, Ty≈(75−87)/4=−3°C/m.','(b) 방향미분≈(3.5−3)/√2=1/(2√2)°C/m, 대각선 방향 이동거리당 온도가 증가한다.','(c) 사각 중앙 혼합차분 [80−90−68+74]/16=−1/4°C/m².'],['(a) Centered differences give Tx≈3.5 and Ty≈−3°C/m.','(b) The directional derivative is(3.5−3)/√2=1/(2√2)°C/m, an increase per diagonal travel distance.','(c) The centered mixed difference is[80−90−68+74]/16=−1/4°C/m².'],'(a)3.5,−3°C/m. (b)1/(2√2)°C/m. (c)−0.25°C/m².','(a)3.5,−3°C/m. (b)1/(2√2)°C/m. (c)−0.25°C/m².',parts=['a','b','c'])
add(12,'온도 T(6,4)=80°C, 표에서 Tx≈3.5,Ty≈−3°C/m이다. (6,4)에서 선형근사를 구하고 T(5,3.8)을 추정하라.','With T(6,4)=80°C and table estimates Tx≈3.5,Ty≈−3°C/m, linearize at(6,4) and estimate T(5,3.8).',['L=80+3.5(x−6)−3(y−4).','x−6=−1,y−4=−0.2를 대입하면80−3.5+0.6=77.1.'],['L=80+3.5(x−6)−3(y−4).','Using displacements−1,−0.2 gives80−3.5+0.6=77.1.'],'L=80+3.5(x−6)−3(y−4), T(5,3.8)≈77.1°C.','L=80+3.5(x−6)−3(y−4), T(5,3.8)≈77.1°C.')
def derivatives(n,F,vs,order=1):
 labels=[];ks=[];es=[]
 for i in vs:
  di=S.diff(F,i)
  if order==1:labels.append('f_{'+S.latex(i)+'}='+S.latex(S.simplify(di)));ks.append('다른 변수를 고정하고 '+M(i)+'로 미분: '+M(di)+'.');es.append('Hold other variables fixed and differentiate in '+M(i)+': '+M(di)+'.')
  else:
   ks.append('1계 '+M(i)+' 미분: '+M(di)+'.');es.append('First derivative in '+M(i)+': '+M(di)+'.')
   for j in vs:labels.append('f_{'+S.latex(i)+S.latex(j)+'}='+S.latex(S.simplify(S.diff(di,j))))
 ans=r'\('+';\quad '.join(labels)+r'\).';add(n,'f='+M(F)+f'의 모든 {order}계 편도함수를 구하라.','For f='+M(F)+f', find all order-{order} partial derivatives.',ks,es,ans,ans,'혼합편미분은 식이 매끄러운 정의역에서 서로 교환됨을 검사했다.','Mixed partials were checked to commute on the smooth domain.')
for row in [(13,(5*y**3+2*x*x*y)**8,[x,y]),(14,(u+2*v)/(u*u+v*v),[u,v]),(15,a*a*S.log(a*a+b*b),[a,b]),(16,S.exp(x*z)*S.sin(y/z),[x,y,z]),(17,u*S.atan(v*S.sqrt(w)),[u,v,w])]:derivatives(*row)
add(18,r'\(C=1449.2+4.6T-0.055T^2+0.00029T^3+(1.34-0.01T)(S-35)+0.016D\). T=10°C,S=35‰,D=100m에서 세 편도함수와 물리적 의미를 구하라.',r'For \(C=1449.2+4.6T-0.055T^2+0.00029T^3+(1.34-0.01T)(S-35)+0.016D\), find the three partials at T=10°C,S=35‰,D=100m and interpret them.',['CT=4.6−0.11T+0.00087T²−0.01(S−35)=3.587.','CS=1.34−0.01T=1.24, CD=0.016. 각 값은 다른 두 조건을 고정한 음속 변화율이다.'],['CT=4.6−0.11T+0.00087T²−0.01(S−35)=3.587.','CS=1.24,CD=0.016, each holding the other two conditions fixed.'],'CT=3.587(m/s)/°C, CS=1.24(m/s)/‰, CD=0.016(m/s)/m.','CT=3.587(m/s)/°C, CS=1.24(m/s)/‰, CD=0.016(m/s)/m.')
for row in [(19,4*x**3-x*y*y,[x,y]),(20,x*S.exp(-2*y),[x,y]),(21,x**k*y**l*z**m,[x,y,z]),(22,r*S.cos(s+2*t),[r,s,t])]:derivatives(*row,order=2)
add(23,r'\(z=xy+xe^{y/x}\)에서 \(xz_x+yz_y=xy+z\)임을 보여라.',r'For \(z=xy+xe^{y/x}\), prove \(xz_x+yz_y=xy+z\).',[r'\(z_x=y+e^{y/x}(1-y/x),z_y=x+e^{y/x}\).','x,y를 곱해 더하면 지수항의 y계수가 소거되어2xy+xe^(y/x)=xy+z이다.'],[r'\(z_x=y+e^{y/x}(1-y/x),z_y=x+e^{y/x}\).','Multiply by x,y and add; the y-exponential terms cancel, leaving2xy+xe^(y/x)=xy+z.'],r'\(xz_x+yz_y=xy+z\), x≠0.',r'\(xz_x+yz_y=xy+z\), x≠0.')
add(24,r'z=sin(x+sin t)에서 \(z_xz_{xt}=z_tz_{xx}\)임을 보여라.',r'For z=sin(x+sin t), prove \(z_xz_{xt}=z_tz_{xx}\).',['q=x+sin t로 두면 zx=cosq,zt=cosq cost,zxx=−sinq,zxt=−sinq cost.','양쪽 곱은 모두−sinq cosq cost이다.'],['Let q=x+sin t. Then zx=cosq,zt=cosq cost,zxx=−sinq,zxt=−sinq cost.','Both products equal−sinq cosq cost.'],r'\(z_xz_{xt}=z_tz_{xx}\).',r'\(z_xz_{xt}=z_tz_{xx}\).')
def plane(n,F,P,graph=False):
 sub=dict(zip([x,y,z],P));G=S.Matrix([S.diff(F,j).subs(sub) for j in [x,y,z]]);assert F.subs(sub)==0;eq=S.expand(G.dot(S.Matrix([x,y,z])-S.Matrix(P)));line=S.Matrix(P)+t*G
 st=M(F)+'=0, P='+M(S.Tuple(*P))+'. '
 add(n,st+'접평면과 법선을 구하라.'+(' 세 대상을 함께 그려라.' if graph else ''),st+'Find the tangent plane and normal.'+(' Plot all three objects.' if graph else ''),['P의 법선은 기울기 '+M(G)+'.','기울기와 위치차의 내적을0으로 놓으면 접평면, P에서 기울기 방향으로 직선을 그으면 법선이다.'],['The normal at P is the gradient '+M(G)+'.','Zero dot product with displacement gives the tangent plane; the line through P in this gradient direction is normal.'],'접평면 '+M(eq)+'=0; 법선 '+M(line)+', t∈R.','Tangent plane '+M(eq)+'=0; normal '+M(line)+', t∈R.',parts=[] if graph else ['a','b'])
for row in [(25,3*x*x-y*y+2*x-z,[1,-2,1]),(26,S.exp(x)*S.cos(y)-z,[0,0,1]),(27,x*x+2*y*y-3*z*z-3,[2,-1,1]),(28,x*y+y*z+z*x-3,[1,1,1]),(29,S.sin(x*y*z)-x-2*y-3*z,[2,-1,0]),(30,x*x+y**4-z,[1,1,2],True)]:plane(*row)
add(31,'x²+4y²−z²=4에서 접평면이2x+2y+z=5와 평행한 점들을 구하라.','Find points on x²+4y²−z²=4 where the tangent plane is parallel to2x+2y+z=5.',['법선 (2x,8y,−2z)=λ(2,2,1)이므로 x=λ,y=λ/4,z=−λ/2.','곡면에 넣으면 λ²=4.'],['The normal equation gives x=λ,y=λ/4,z=−λ/2.','Substitution into the surface gives λ²=4.'],'(2,1/2,−1), (−2,−1/2,1).','(2,1/2,−1), (−2,−1/2,1).')
add(32,'u=ln(1+se²ᵗ)의 전미분 du를 구하라.','Find the total differential of u=ln(1+se²ᵗ).',['us=e²ᵗ/(1+se²ᵗ),ut=2se²ᵗ/(1+se²ᵗ).','du=us ds+ut dt로 모은다.'],['us=e²ᵗ/(1+se²ᵗ),ut=2se²ᵗ/(1+se²ᵗ).','Assemble du=us ds+ut dt.'],r'\(du=\frac{e^{2t}}{1+se^{2t}}ds+\frac{2se^{2t}}{1+se^{2t}}dt\).',r'\(du=\frac{e^{2t}}{1+se^{2t}}ds+\frac{2se^{2t}}{1+se^{2t}}dt\).')
add(33,r'\(f=x^3\sqrt{y^2+z^2}\)를 (2,3,4)에서 선형화하고 (1.98,3.01,3.97)의 값을 추정하라.',r'Linearize \(f=x^3\sqrt{y^2+z^2}\) at(2,3,4) and estimate its value at(1.98,3.01,3.97).',['기준값40, 기울기(60,24/5,32/5).','변위(−0.02,0.01,−0.03)의 내적은−1.2+0.048−0.192=−1.344이다.'],['Base value40 and gradient(60,24/5,32/5).','Dot with displacement(−0.02,0.01,−0.03):−1.2+0.048−0.192=−1.344.'],'L=40+60(x−2)+(24/5)(y−3)+(32/5)(z−4); 추정38.656.','L=40+60(x−2)+(24/5)(y−3)+(32/5)(z−4); estimate38.656.')
add(34,'직각삼각형 두 변5m,12m에 각각 최대오차0.2cm가 있다. (a) 넓이 (b) 빗변 최대오차를 미분으로 추정하라.','A right triangle has legs5m,12m, each with maximum error0.2cm. Estimate maximum errors in (a) area and (b) hypotenuse using differentials.',['오차를0.002m로 바꾼다. (a) dA=(y/2)dx+(x/2)dy로 최대(6+2.5)0.002=0.017m².','(b) c=13, dc=(5/13)dx+(12/13)dy이므로 최대17·0.002/13=0.00261538m.'],['Convert the error to0.002m. (a) dA=(y/2)dx+(x/2)dy gives maximum0.017m².','(b) c=13 and dc=(5/13)dx+(12/13)dy give maximum0.00261538m.'],'(a) 약0.017m². (b) 약0.26154cm.','(a) Approximately0.017m². (b) Approximately0.26154cm.',parts=['a','b'])
F=x*x*y**3+z**4;sub={x:p+3*p*p,y:p*S.exp(p),z:p*S.sin(p)};der=sum(S.diff(F,j).subs(sub,simultaneous=True)*S.diff(sub[j],p) for j in sub);assert S.simplify(der-S.diff(F.subs(sub,simultaneous=True),p))==0
add(35,r'u=x²y³+z⁴, x=p+3p²,y=peᵖ,z=p sinp일 때 du/dp를 연쇄법칙으로 구하라.',r'For u=x²y³+z⁴,x=p+3p²,y=peᵖ,z=p sinp, find du/dp by the chain rule.',['ux=2xy³,uy=3x²y²,uz=4z³.','u′=2xy³(1+6p)+3x²y²eᵖ(1+p)+4z³(sinp+p cosp), 주어진 x,y,z를 대입한다.'],['ux=2xy³,uy=3x²y²,uz=4z³.','u′=2xy³(1+6p)+3x²y²eᵖ(1+p)+4z³(sinp+p cosp); substitute the given x,y,z.'],M(der)+'.',M(der)+'.','직접 합성식을 미분한 결과와 기호적으로 일치함을 검사했다.','Symbolically checked against direct differentiation of the composite.')
add(36,'v=x²sin y+yeˣʸ,x=s+2t,y=st에서 s=0,t=1의 vs,vt를 구하라.','For v=x²sin y+yeˣʸ,x=s+2t,y=st, find vs,vt at s=0,t=1.',['입력은 (x,y)=(2,0), vx=0,vy=5.','xs=1,ys=t=1,xt=2,yt=s=0이므로 vs=5,vt=0.'],['The inner point is (2,0), where vx=0,vy=5.','With xs=1,ys=1,xt=2,yt=0, the chain rule gives vs=5,vt=0.'],'vs=5, vt=0.','vs=5, vt=0.')
add(37,'z=f(g(s,t),h(s,t)),g(1,2)=3,h(1,2)=6,gs=−1,gt=4,hs=−5,ht=10,fx(3,6)=7,fy(3,6)=8이다. zs,zt(1,2)를 구하라.','For z=f(g(s,t),h(s,t)),g(1,2)=3,h(1,2)=6,gs=−1,gt=4,hs=−5,ht=10,fx(3,6)=7,fy(3,6)=8. Find zs,zt at(1,2).',['zs=fx gs+fy hs=7(−1)+8(−5).','zt=fx gt+fy ht=7·4+8·10.'],['zs=fx gs+fy hs=7(−1)+8(−5).','zt=fx gt+fy ht=7·4+8·10.'],'zs=−47,zt=108.','zs=−47,zt=108.')
add(38,'w=f(t,u,v)이고 t,u,v는 각각 p,q,r,s의 함수이다. 나무도표와 네 연쇄법칙을 쓰라.','Let w=f(t,u,v), with t,u,v each depending on p,q,r,s. Draw a tree and state the four chain rules.',['w에서 t,u,v로 가지를 내고 각 중간변수에서 p,q,r,s로 가지를 낸다.','각 입력 j에 대해 세 경로의 곱을 더한다.'],['Branch from w to t,u,v and from each intermediate to p,q,r,s.','For each input j, sum the products on its three paths.'],r'\(w_j=w_t t_j+w_u u_j+w_v v_j,\quad j=p,q,r,s\).',r'\(w_j=w_t t_j+w_u u_j+w_v v_j,\quad j=p,q,r,s\).')
add(39,r'z=y+f(x²−y²)에서 \(yz_x+xz_y=x\)임을 보여라.',r'For z=y+f(x²−y²), prove \(yz_x+xz_y=x\).',['q=x²−y²라 하면 zx=2x f′(q),zy=1−2y f′(q).','y,x를 곱해 더하면 f′ 항이 소거되고 x가 남는다.'],['Let q=x²−y². Then zx=2x f′(q),zy=1−2y f′(q).','Multiplication by y,x and addition cancel the f′ terms, leaving x.'],r'\(yz_x+xz_y=x\).',r'\(yz_x+xz_y=x\).')
add(40,'삼각형 두 변 x=40in,y=50in, 끼인각θ=π/6에서 x′=3in/s,y′=−2in/s,θ′=0.05rad/s이다. 넓이 변화율을 구하라.','A triangle has x=40in,y=50in, included angleθ=π/6, with x′=3in/s,y′=−2in/s,θ′=0.05rad/s. Find its area rate.',['A=xy sinθ/2, A′=(x′y+xy′)sinθ/2+xy cosθ θ′/2.','대입하면 (150−80)/4+1000(√3/2)(0.05).'],['A=xy sinθ/2, so A′=(x′y+xy′)sinθ/2+xy cosθ θ′/2.','Substitution gives(150−80)/4+1000(√3/2)(0.05).'],'17.5+25√3 in²/s.','17.5+25√3 in²/s.')
add(41,r'z=f(u,v),u=xy,v=y/x,f∈C²일 때 \(x^2z_{xx}-y^2z_{yy}=-4uvf_{uv}+2vf_v\)를 증명하라.',r'For z=f(u,v),u=xy,v=y/x,f∈C², prove \(x^2z_{xx}-y^2z_{yy}=-4uvf_{uv}+2vf_v\).',[r'\(z_{xx}=y^2f_{uu}-2y^2f_{uv}/x^2+y^2f_{vv}/x^4+2yf_v/x^3\).',r'\(z_{yy}=x^2f_{uu}+2f_{uv}+f_{vv}/x^2\).','각각 x²,y²를 곱해 빼면 fuu,fvv가 소거되며 y²=uv,y/x=v이다.'],[r'\(z_{xx}=y^2f_{uu}-2y^2f_{uv}/x^2+y^2f_{vv}/x^4+2yf_v/x^3\).',r'\(z_{yy}=x^2f_{uu}+2f_{uv}+f_{vv}/x^2\).','Multiply by x²,y² and subtract; fuu,fvv cancel, while y²=uv and y/x=v.'],r'\(x^2z_{xx}-y^2z_{yy}=-4uvf_{uv}+2vf_v\), x≠0.',r'\(x^2z_{xx}-y^2z_{yy}=-4uvf_{uv}+2vf_v\), x≠0.')
add(42,'cos(xyz)=1+x²y²+z²에서 zx,zy를 조사하라.','Investigate zx,zy for cos(xyz)=1+x²y²+z².',['F=cos(xyz)−1−x²y²−z²로 두면 형식적으로 zx=−Fx/Fz,zy=−Fy/Fz를 쓸 수 있다.',r'형식은 \(z_x=-\frac{yz\sin(xyz)+2xy^2}{xy\sin(xyz)+2z},\quad z_y=-\frac{xz\sin(xyz)+2x^2y}{xy\sin(xyz)+2z}\).','그러나 실수에서 좌변≤1, 우변≥1이므로 모든 해는 z=0,xy=0이다. 따라서 Fz=0이고 열린 xy근방에 z(x,y)를 정의하는 곡면이 아니다.'],['Set F=cos(xyz)−1−x²y²−z². Formally one would use zx=−Fx/Fz,zy=−Fy/Fz.',r'The formal expressions are \(z_x=-\frac{yz\sin(xyz)+2xy^2}{xy\sin(xyz)+2z},\quad z_y=-\frac{xz\sin(xyz)+2x^2y}{xy\sin(xyz)+2z}\).','For real solutions the left side≤1 and right side≥1 force z=0,xy=0. Thus Fz=0 everywhere feasible, and no surface z(x,y) exists on an open xy neighborhood.'],'형식적 비는 위와 같지만 실제 실수해에서 모두0/0이다. 이 제약은 통상적인 zx,zy를 정의하지 않는다.','The formal ratios above are0/0 on every real solution. The constraint does not define ordinary zx,zy.','음함수정리의 Fz≠0 가정을 실제로 검사한 결과이다.','This conclusion checks the actual nonzero-Fz hypothesis of the implicit function theorem.')
derivatives(43,x*x*S.exp(y*z*z),[x,y,z]);E[-1]['statement']['ko']='f='+M(x*x*S.exp(y*z*z))+'의 기울기를 구하라.';E[-1]['statement']['en']='Find the gradient of f='+M(x*x*S.exp(y*z*z))+'.';E[-1]['answer']=pair(M(S.Matrix([2*x*S.exp(y*z*z),x*x*z*z*S.exp(y*z*z),2*x*x*y*z*S.exp(y*z*z)])),M(S.Matrix([2*x*S.exp(y*z*z),x*x*z*z*S.exp(y*z*z),2*x*x*y*z*S.exp(y*z*z)])))
add(44,'미분가능 함수의 방향미분은 언제 (a) 최대 (b) 최소 (c)0 (d) 최대값의 절반인가?','When is a differentiable function’s directional derivative (a) maximal, (b) minimal, (c) zero, and (d) half its maximum?',[r'기울기가0이 아니면 \(D_uf=\|\nabla f\|\cos\theta\).','cosθ가 각각1,−1,0,1/2가 되는 각을 찾는다. 기울기가0이면 모든 방향미분이0이므로 모든 단위 방향이 네 조건을 만족한다.'],[r'For nonzero gradient, \(D_uf=\|\nabla f\|\cos\theta\).','Use cosθ=1,−1,0,1/2 respectively. For zero gradient every unit direction satisfies all four zero-valued conditions.'],'비영 기울기와 각: (a)0° (b)180° (c)90° (d)60°.','Angles to a nonzero gradient: (a)0° (b)180° (c)90° (d)60°.',parts=['a','b','c','d'])
for n,F,vs,P,V in [(45,x*x*S.exp(-y),[x,y],[-2,0],[4,-3]),(46,x*x*y+x*S.sqrt(1+z),[x,y,z],[1,2,3],[2,1,-2])]:
 G=S.Matrix([S.diff(F,j).subs(dict(zip(vs,P))) for j in vs]);V=S.Matrix(V);U=V/S.sqrt(V.dot(V));value=S.simplify(G.dot(U))
 add(n,'f='+M(F)+', P='+M(S.Tuple(*P))+', v='+M(V)+'의 방향미분을 구하라.','Find the directional derivative for f='+M(F)+', P='+M(S.Tuple(*P))+', v='+M(V)+'.',['P의 기울기는 '+M(G)+', 단위 방향은 '+M(U)+'.','내적을 취하면 '+M(value)+'.'],['The gradient at P is '+M(G)+', and the unit direction '+M(U)+'.','Their dot product is '+M(value)+'.'],M(value),M(value))
for n,F,vs,P in [(47,x*x*y+S.sqrt(y),[x,y],[2,1]),(48,z*S.exp(x*y),[x,y,z],[0,1,2])]:
 G=S.Matrix([S.diff(F,j).subs(dict(zip(vs,P))) for j in vs]);N=S.sqrt(G.dot(G));U=G/N;ans='rate='+M(N)+', u='+M(U)
 add(n,'f='+M(F)+', P='+M(S.Tuple(*P))+'에서 최대증가율과 방향을 구하라.','Find maximum increase rate and direction for f='+M(F)+' at P='+M(S.Tuple(*P))+'.',['기울기는 '+M(G)+'.','최대율은 그 길이, 방향은 기울기를 길이로 나눈 단위벡터이다.'],['The gradient is '+M(G)+'.','The maximum rate is its norm; normalize the gradient for its direction.'],ans,ans)
add(49,'허리케인 풍속 등고선은5kn 간격이다. Homestead에서 눈 방향의 국소 선간격은 지도 축척상 약10mi이다. 그 방향 풍속 변화율을 추정하라.','Hurricane wind contours differ by5kn. Near Homestead, their spacing toward the eye is about10mi by the map scale. Estimate the directional wind-speed derivative.',['눈 쪽으로 이동하면 등고선 값이 커진다.','인접선의 풍속 증가5kn을 방향거리 약10mi로 나눈다.'],['Wind speed increases toward the eye.','Divide the adjacent5kn increase by approximately10mi along that direction.'],'약 +0.5kn/mi.','Approximately +0.5kn/mi.','지도에서 국소 선간격을 판독한 근사로 위치에 따라 증가율은 달라진다.','A graphical local-spacing estimate; the rate changes with location.')
add(50,'z=2x²−y²와 z=4의 교선에서 (−2,2,4)의 접선을 구하라.','Find the tangent line to z=2x²−y²,z=4 at(−2,2,4).',['두 법선은 (4x,−2y,−1)=(−8,−4,−1), (0,0,1).','외적은 (−4,8,0)으로 (1,−2,0)에 평행하다.'],['Normals are (−8,−4,−1) and(0,0,1).','Their cross product(−4,8,0) is parallel to(1,−2,0).'],'x=−2+t,y=2−2t,z=4.','x=−2+t,y=2−2t,z=4.')
def extrema(n,F,pts=None,numeric=False,graph=False):
 fx=S.diff(F,x);fy=S.diff(F,y);H=S.hessian(F,(x,y));det=S.det(H)
 if pts is None:pts=[(a[x],a[y]) for a in S.solve([fx,fy],(x,y),dict=True)]
 ks=['정지식 '+M(fx)+'=0, '+M(fy)+'=0을 푼다.'];es=['Solve '+M(fx)+'=0 and '+M(fy)+'=0.'];ka=[];ea=[]
 for xx,yy in pts:
  sub={x:xx,y:yy};d=S.simplify(det.subs(sub));aa=S.simplify(H[0,0].subs(sub));val=S.simplify(F.subs(sub));assert abs(float(fx.subs(sub)))<1e-7 and abs(float(fy.subs(sub)))<1e-7
  kind=('안장점','saddle') if float(d)<0 else ('극소','minimum') if float(aa)>0 else ('극대','maximum');P=f'({float(xx):.3f},{float(yy):.3f})' if numeric else M(S.Tuple(xx,yy));V=f'{float(val):.3f}' if numeric else M(val)
  ks.append(P+'의 D='+M(d)+', fxx='+M(aa)+', '+kind[0]+'.');es.append(P+' has D='+M(d)+', fxx='+M(aa)+', hence '+kind[1]+'.');ka.append(P+' '+kind[0]+' '+V);ea.append(P+' '+kind[1]+' '+V)
 add(n,'f='+M(F)+'의 극값과 안장점을 구하라.'+(' 그래프도 그려 추정을 확인하라.' if graph else ''),'Find extrema and saddles of f='+M(F)+('. Plot to check estimates.' if graph else '.'),ks,es,'; '.join(ka),'; '.join(ea))
 if graph:plots[n]=(F,(-2,2,-2,2))
for row in [(51,x*x-x*y+y*y+9*x-6*y),(52,x**3-6*x*y+8*y**3),(53,3*x*y-x*x*y-x*y*y),(54,(x*x+y)*S.exp(y/2))]:extrema(*row)
add(55,'f=4xy²−x²y²−xy³를 꼭짓점(0,0),(0,6),(6,0)의 닫힌 삼각형에서 최적화하라.','Find absolute extrema of f=4xy²−x²y²−xy³ on the closed triangle with vertices(0,0),(0,6),(6,0).',['f=xy²(4−x−y). 양의 내부 정지점은 fx=y²(4−2x−y)=0, fy=xy(8−2x−3y)=0에서(1,2), 값4.','좌표축 경계의 값0. 빗변 x+y=6에서는 f=−2x(6−x)²로0≤x≤6, 정지점 x=2에서−64.'],['Write f=xy²(4−x−y). The positive interior stationary point is(1,2), value4, from fx=y²(4−2x−y)=0 and fy=xy(8−2x−3y)=0.','Axis boundaries give0. On x+y=6, f=−2x(6−x)² for0≤x≤6, minimized at x=2 with value−64.'],'최대4:(1,2). 최소−64:(2,4).','Maximum4 at(1,2); minimum−64 at(2,4).')
add(56,r'\(f=e^{-x^2-y^2}(x^2+2y^2)\)를 x²+y²≤4에서 최적화하라.',r'Find absolute extrema of \(f=e^{-x^2-y^2}(x^2+2y^2)\) on x²+y²≤4.',['내부 정지점은 (0,0),(±1,0),(0,±1), 값은0,1/e,2/e이다.','경계 r²=4에서 f=e^(−4)(4+y²), 값범위[4e^(−4),8e^(−4)]. 이 값들을 내부와 비교한다.'],['Interior stationary points are(0,0),(±1,0),(0,±1), with values0,1/e,2/e.','On r²=4, f=e^(−4)(4+y²), ranging from4e^(−4) to8e^(−4). Compare with the interior values.'],'최소0:(0,0). 최대2/e:(0,±1).','Minimum0 at(0,0); maximum2/e at(0,±1).')
extrema(57,x**3-3*x+y**4-2*y*y,graph=True)
F=12+10*y-2*x*x-8*x*y-y**4;roots=[float(S.re(q)) for q in S.nroots(2*y**3-8*y-5) if abs(float(S.im(q)))<1e-9];pts=[(-2*b,b) for b in roots];extrema(58,F,pts,numeric=True,graph=True);plots[58]=(F,(-5,5,-3,3));highest=max([(float(F.subs({x:a,y:b})),a,b) for a,b in pts]);E[-1]['statement']['ko']+=' 소수 셋째 자리까지 계산하고 최고점을 구하라.';E[-1]['statement']['en']+=' Give three-decimal coordinates and find the highest point.';E[-1]['steps']['ko'].append('f=12+10y+8y²−y⁴−2(x+2y)²는 무한대에서−∞이므로 가장 큰 극대가 절대최대이다.');E[-1]['steps']['en'].append('Completing squares gives f=12+10y+8y²−y⁴−2(x+2y)², tending to−∞ at infinity, so the larger maximum is absolute.');E[-1]['answer']['ko']+=f'; 최고점({highest[1]:.3f},{highest[2]:.3f},{highest[0]:.3f}).';E[-1]['answer']['en']+=f'; highest point({highest[1]:.3f},{highest[2]:.3f},{highest[0]:.3f}).'
add(59,'f=x²y를 x²+y²=1에서 승수법으로 최적화하라.','Optimize f=x²y under x²+y²=1 by multipliers.',['2xy=2λx,x²=2λy. x=0이면 y=±1,값0.','x≠0이면 λ=y,x²=2y²이고 제약으로 y=±1/√3,x=±√(2/3).'],['Equations2xy=2λx,x²=2λy give x=0,y=±1, values0.','For x≠0, λ=y,x²=2y², so y=±1/√3,x=±√(2/3).'],r'최대 \(2/(3\sqrt3)\): y=1/√3. 최소 \(-2/(3\sqrt3)\): y=−1/√3. 둘 다 x=±√(2/3).',r'Maximum \(2/(3\sqrt3)\) for y=1/√3; minimum \(-2/(3\sqrt3)\) for y=−1/√3; both with x=±√(2/3).')
add(60,'f=1/x+1/y를 1/x²+1/y²=1에서 승수법으로 최적화하라.','Optimize f=1/x+1/y under1/x²+1/y²=1 by multipliers.',['−1/x²=λ(−2/x³),−1/y²=λ(−2/y³)에서 x=y=2λ.','제약으로 x=y=±√2. u=1/x,v=1/y로 바꾸면 단위원의 u+v이고 |u+v|≤√2이다.'],['Multiplier equations give x=y=2λ.','The constraint gives x=y=±√2. With u=1/x,v=1/y, the objective is u+v on a unit circle, bounded by±√2.'],'최대√2:(√2,√2), 최소−√2:(−√2,−√2).','Maximum√2 at(√2,√2); minimum−√2 at(−√2,−√2).')
add(61,'xyz를 x²+y²+z²=3에서 승수법으로 최적화하라.','Optimize xyz under x²+y²+z²=3 using multipliers.',['yz=2λx,xz=2λy,xy=2λz. 비영좌표에서는 x²=y²=z²=1이다.','좌표0인 후보는 목적값0. 세 부호의 곱에 따라±1이 나오며 |xyz|≤1이다.'],['Equations yz=2λx,xz=2λy,xy=2λz give x²=y²=z²=1 for nonzero coordinates.','Zero-coordinate candidates give0. Sign products give±1, and |xyz|≤1.'],'최대1: |x|=|y|=|z|=1, xyz>0. 최소−1: 같은 절댓값, xyz<0.','Maximum1 where all magnitudes are1 and xyz>0; minimum−1 where all magnitudes are1 and xyz<0.')
F=x*x+2*y*y+3*z*z;zz=t;yy=(t-1)/2;xx=(3-3*t)/2;g=S.expand(F.subs({x:xx,y:yy,z:zz},simultaneous=True));tc=S.solve(S.diff(g,t),t)[0];P=[S.simplify(a.subs(t,tc)) for a in [xx,yy,zz]];val=S.simplify(g.subs(t,tc))
add(62,'f=x²+2y²+3z²를 x+y+z=1,x−y+2z=2에서 승수법으로 최적화하라.','Optimize f=x²+2y²+3z² under x+y+z=1,x−y+2z=2 using multipliers.',['승수식은 (2x,4y,6z)=λ(1,1,1)+μ(1,−1,2)이며 제약과 함께 선형 연립계이다.','독립 확인으로 z=t,y=(t−1)/2,x=3(1−t)/2를 대입하면 f='+M(g)+'. 정지점 t='+M(tc)+'.'],['The multiplier system (2x,4y,6z)=λ(1,1,1)+μ(1,−1,2), together with constraints, is linear.','Independently substitute z=t,y=(t−1)/2,x=3(1−t)/2 to get f='+M(g)+', stationary at t='+M(tc)+'.'],'최소 '+M(val)+' at '+M(S.Tuple(*P))+'; 최대 없음.','Minimum '+M(val)+' at '+M(S.Tuple(*P))+'; no maximum.','축소 이차식의 최고차계수가 양수이므로 유일한 전역최소이며 위로 무한하다.','The reduced quadratic has positive leading coefficient, proving a unique global minimum and unboundedness above.')
# xy²z³=2 gives weighted squared-coordinate proportions1:2:3.
q=1/S.sqrt(3)
add(63,'xy²z³=2에서 원점에 가장 가까운 점들을 구하라.','Find points closest to the origin on xy²z³=2.',['거리제곱 x²+y²+z²의 승수식에 각각 x,y,z를 곱하면 2x²=2λ,2y²=4λ,2z²=6λ.','따라서 x²:y²:z²=1:2:3. x²=q라 놓으면 |xy²z³|=6√3 q³=2이므로 q³=1/(3√3), q=1/√3. x,z는 같은 부호여야 한다.'],['Multiplying squared-distance multiplier equations by x,y,z gives2x²=2λ,2y²=4λ,2z²=6λ.','Thus x²:y²:z²=1:2:3. Setting x²=q gives6√3 q³=2, hence q=1/√3; x,z must have matching signs.'],r'\(x=\pm3^{-1/4},y=\pm\sqrt2\,3^{-1/4},z=\pm3^{1/4}\), x,z 같은 부호; y 독립. 최단거리 \(\sqrt{2\sqrt3}\).',r'\(x=\pm3^{-1/4},y=\pm\sqrt2\,3^{-1/4},z=\pm3^{1/4}\), with matching x,z signs and independent y sign; shortest distance \(\sqrt{2\sqrt3}\).','가중 AM–GM으로 주어진 곱에서 제곱거리의 전역최소도 확인된다.','Weighted AM–GM also proves global minimality of the squared distance at the fixed product.')
add(64,'직선16x+15y=100 위의 점에서 (−3,0),(3,0)까지 거리합을 최소화한다. (a) 목적함수·등고선·최소점·값 (b) 그 점에서 기울기 평행을 확인하라.','Minimize the sum of distances to(−3,0),(3,0) over16x+15y=100. (a) Give the objective, contours, minimizing point and value; (b) verify parallel gradients.',[r'(a) \(f=\sqrt{(x+3)^2+y^2}+\sqrt{(x-3)^2+y^2}\). 등위곡선 f=c>6은 초점(±3,0)의 타원이다.',r'c=10이면 타원 \(x^2/25+y^2/16=1\). 직선은 (4,12/5)에서 이 타원에 접하고 거리들은37/5,13/5로 합10이다.',r'(b) 그 점의 \(\nabla f=(640,600)/481=(40/481)(16,15)=(40/481)\nabla g\).'],[r'(a) \(f=\sqrt{(x+3)^2+y^2}+\sqrt{(x-3)^2+y^2}\). Levels f=c>6 are ellipses with foci(±3,0).',r'For c=10, the ellipse is \(x^2/25+y^2/16=1\). The line is tangent at(4,12/5), whose distances are37/5 and13/5, summing to10.',r'(b) There \(\nabla f=(640,600)/481=(40/481)(16,15)=(40/481)\nabla g\).'],'최소10, (a,b)=(4,12/5).','Minimum10 at(a,b)=(4,12/5).','거리합은 볼록함수이므로 제약선에서 정지한 점은 전역최소이다.','A sum of distances is convex, so its stationary point on the constraint line is a global minimum.',['a','b'])
add(65,'직사각형 위에 이등변삼각형 지붕을 얹은 오각형의 둘레가 P이다. 넓이를 최대화하는 다섯 변의 길이를 구하라.','A pentagon consists of a rectangle topped by an isosceles triangle and has perimeter P. Find the five side lengths maximizing area.',['밑변 b,직사각 높이 h,지붕 상승 a,빗변 l=√(a²+b²/4). 넓이 bh+ba/2, 둘레 b+2h+2l=P.','승수식의 h성분에서 λ=b/2, a성분에서 a=l/2. 따라서 지붕각30°, b=√3l이다.','b성분은 h+a/2=λ(1+b/(2l)), 따라서 h=(1+√3)l/2. 둘레식으로 l=P/(3+2√3).'],['Let base b, rectangle height h, roof rise a and slope l=√(a²+b²/4). Area is bh+ba/2 and perimeter b+2h+2l=P.','The h multiplier equation gives λ=b/2; the a equation gives a=l/2, hence roof angle30° and b=√3l.','The b equation gives h+a/2=λ(1+b/(2l)), yielding h=(1+√3)l/2 and l=P/(3+2√3).'],r'\(l=P/(3+2\sqrt3)\). 지붕 두 변 l,l; 수직 두 변 \((1+\sqrt3)l/2\); 밑변 \(\sqrt3l\).',r'Let \(l=P/(3+2\sqrt3)\). Roof sides l,l; vertical sides \((1+\sqrt3)l/2\); base \(\sqrt3l\).','각 θ에서 빗변 최적화 후 면적은 P²cosθ/[4(2+2cosθ−sinθ)]. 그 미분 부호는1−2sinθ이므로30°에서 유일한 최대이다.','After optimizing slope length at fixedθ, area is P²cosθ/[4(2+2cosθ−sinθ)]. Its derivative has sign1−2sinθ, giving the unique maximum at30°.')
E.sort(key=lambda a:a['number']);assert [a['number'] for a in E]==list(range(1,66))
D=dict(section='14.9',source=dict(title='Calculus',edition='9',language='en',printedPages=[1070,1071,1072],pdfPages=[1107,1108,1109]),scope=dict(kind='review',numbers=list(range(1,66)),total=65,note=pair('Chapter14 Review Exercises 전체65문항과 모든 소문항.','All65 Chapter14 Review Exercises and every subpart.')),exercises=E)
(R/'exercise-content/s14-9.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n');print('Chapter14 Review:65 cards')
# Save figure requests separately; plotting script reads them without rerunning authorship.
(R/'exercise-checks/s14-9-plot-data.json').write_text(json.dumps({str(n):dict(formula=str(F),box=box) for n,(F,box) in plots.items()},indent=2))
