import sympy as S,json,math
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=[]
x,y,z,s,t,r,u,v,p,q=S.symbols('x y z s t r u v p q',real=True)
la=lambda a:S.latex(S.simplify(a)); pair=lambda k,e:dict(ko=k,en=e); M=lambda a:r'\('+la(a)+r'\)'; vec=lambda a:S.Matrix(a)
def add(n,ko,en,ks,es,ka,ea,kc='정의역과 단위벡터 조건을 확인하고 계산을 다시 대입했다.',ec='The domain and unit-vector conditions were checked and results substituted back.',parts=[]):
 pg=1043 if n<=19 else 1044 if n<=41 else 1045 if n<=64 else 1046
 E.append(dict(id=f'stewart9-exercise-14.6-{n}',number=n,subparts=parts,source=dict(printedPage=pg,pdfPage=pg+37),topic=pair('방향미분과 기울기벡터','Directional derivatives and gradients'),statement=pair(ko,en),hint=pair('기울기와 단위 방향벡터의 내적을 사용한다. 등위면의 기울기는 법선이다.','Use the dot product of the gradient with a unit direction. A level-surface gradient is normal.'),steps=pair(ks,es),answer=pair(ka,ea),check=pair(kc,ec),conceptHref='../s14-6.html',status='math-verified'))
def dd(n,F,vs,P,V,mode='direction'):
 G=vec([S.diff(F,j) for j in vs]);GP=G.subs(dict(zip(vs,P)));V=vec(V);U=V/S.sqrt(V.dot(V));ans=S.simplify(GP.dot(U));h=S.symbols('h',real=True);direct=S.diff(F.subs({j:P[i]+h*U[i] for i,j in enumerate(vs)},simultaneous=True),h).subs(h,0);assert S.simplify(direct-ans)==0
 info=M(F)+', P='+M(vec(P))+', '+('Q='+M(vec([P[i]+V[i] for i in range(len(P))])) if mode=='toward' else 'v='+M(V))
 parts=['a','b','c'] if mode=='gradient' else []
 goal='기울기 함수, P의 기울기, 방향미분을 구하라.' if parts else '주어진 방향의 방향미분을 구하라.'
 ks=['기울기: '+M(G)+'.','P에서 '+M(GP)+'. 단위 방향은 '+M(S.simplify(U))+'.','내적을 계산하면 '+M(ans)+'.'];es=['Gradient: '+M(G)+'.','At P: '+M(GP)+'. Unit direction: '+M(S.simplify(U))+'.','The dot product is '+M(ans)+'.']
 a=('(a) '+M(G)+'; (b) '+M(GP)+'; (c) ' if parts else '')+M(ans)+'.'
 add(n,info+'. '+goal,info+'. '+('Find the gradient, its value at P, and the directional derivative.' if parts else 'Find the directional derivative in the specified direction.'),ks,es,a,a,'직선 경로 P+hu를 먼저 대입한 단변수 미분과 기호적으로 일치한다.','Symbolically agrees with differentiating the line restriction at h=0.',parts)
def maximum(n,F,vs,P):
 G=vec([S.diff(F,j) for j in vs]);GP=G.subs(dict(zip(vs,P)));N=S.sqrt(GP.dot(GP));U=S.simplify(GP/N);assert S.simplify(U.dot(U)-1)==0
 st=M(F)+', P='+M(vec(P))+'. ';ans='rate='+M(N)+', u='+M(U)+'.'
 add(n,st+'최대 증가율과 방향을 구하라.',st+'Find the maximum rate of increase and its direction.',['기울기는 '+M(G)+'.','P에서 '+M(GP)+'. 코시–슈바르츠 부등식의 등호는 기울기와 같은 방향에서 성립한다.'],['The gradient is '+M(G)+'.','At P it is '+M(GP)+'. Cauchy–Schwarz is sharp in the gradient direction.'],ans,ans)
add(1,'Kearney K에서 Sioux City S까지 300 km이다. 등압선은 4 mb 간격이고 K 근처에서 KS 방향의 인접선 간격은 약 50 km이다. K에서 S 방향의 압력 변화율과 단위를 추정하라.','Kearney K to Sioux City S is 300 km. Isobars differ by 4 mb; near K their spacing along KS is about 50 km. Estimate the pressure derivative toward S and its units.',['S 쪽으로 등압선 값이 낮아진다.','인접선 사이의 압력 차이를 해당 방향 거리로 나눈다: −4/50≈−0.08.'],['Pressure decreases toward S.','Divide the adjacent pressure difference by distance along the direction: −4/50≈−0.08.'],'약 −0.08 mb/km.','Approximately −0.08 mb/km.','원문 그림에서 KS 길이에 대한 국소 선간격을 읽은 근사이다. 전체 구간 평균과 국소 미분을 구별한다.','A graphical local-spacing estimate relative to KS; this is not the average over the full segment.')
add(2,'Dubbo에서 Sydney 방향으로 기온 등고선 값이 낮아진다. 원문 지도는 3°C 간격이며 그 방향에서 Dubbo를 끼는 30°C와 27°C 등온선의 거리는 약 160 km이다. 방향미분과 단위를 추정하라.','Temperature decreases from Dubbo toward Sydney. The source has 3°C contour intervals; along this direction the 30°C and 27°C contours bracketing Dubbo are about 160 km apart. Estimate the directional derivative and its units.',['지도 축척으로 두 등온선 사이 방향 거리를 추정한다.','변화율≈(27−30)/160=−0.01875.'],['Estimate directional distance between the bracketing contours using the map scale.','Rate≈(27−30)/160=−0.01875.'],'약 −0.02°C/km.','Approximately −0.02°C/km.','그림 측정에 따라 근삿값이 달라지며 음의 부호는 Sydney 쪽 냉각과 일치한다.','Graphical readings vary; the negative sign agrees with cooling toward Sydney.')
add(3,r'풍속 v와 실제온도 T에 따른 체감온도 f에 대해 f(−15,30)=−26,f(−25,30)=−39,f(−20,20)=−30,f(−20,40)=−34이다. \(u=(1,1)/\sqrt2\) 방향의 Duf(−20,30)을 추정하라.',r'Wind chill f(T,v) has f(−15,30)=−26,f(−25,30)=−39,f(−20,20)=−30,f(−20,40)=−34. Estimate Duf(−20,30) for \(u=(1,1)/\sqrt2\).',['중앙차분 fT≈13/10, fv≈−4/20이다.',r'따라서 \(D_uf\approx(1.3-0.2)/\sqrt2=11\sqrt2/20\).'],['Centered differences give fT≈13/10 and fv≈−4/20.',r'Thus \(D_uf\approx(1.3-0.2)/\sqrt2=11\sqrt2/20\).'],r'\(11\sqrt2/20\approx0.778\).',r'\(11\sqrt2/20\approx0.778\).')
for n,F,P,ang in [(4,x*y**3-x*x,[1,2],S.pi/3),(5,y*S.cos(x*y),[0,1],S.pi/4),(6,S.sqrt(2*x+3*y),[3,1],-S.pi/6),(7,S.atan(x*y),[2,-3],3*S.pi/4)]:dd(n,F,[x,y],P,[S.cos(ang),S.sin(ang)])
for n,F,vs,P,V in [(8,x*x*S.exp(y),[x,y],[3,0],[3,-4]),(9,x/y,[x,y],[2,1],[3,4]),(10,x*x*S.log(y),[x,y],[3,1],[-5,12]),(11,x*x*y*z-x*y*z**3,[x,y,z],[2,-1,1],[0,4,-3]),(12,y*y*S.exp(x*y*z),[x,y,z],[0,1,-1],[3,4,12])]:dd(n,F,vs,P,V,'gradient')
for row in [(13,S.exp(x)*S.sin(y),[x,y],[0,S.pi/3],[-6,8]),(14,x/(x*x+y*y),[x,y],[1,2],[3,5]),(15,s*S.sqrt(t),[s,t],[2,4],[2,-1]),(16,u*u*S.exp(-v),[u,v],[3,0],[3,4]),(17,x*x*y+y*y*z,[x,y,z],[1,2,3],[2,-1,2]),(18,x*y*y*S.atan(z),[x,y,z],[2,1,1],[1,1,1]),(19,S.log(3*r+6*s+9*t),[r,s,t],[1,1,1],[4,12,6])]:dd(*row)
add(20,'원문 벡터 그림에서 (2,2)의 기울기는 대략 (2.5,−2.5), 단위 u는 왼쪽에서 약 10° 위를 향한다. 방향미분을 추정하라.','In the source vector plot, the gradient at (2,2) is approximately (2.5,−2.5), and unit u points about 10° above left. Estimate the directional derivative.',['u≈(−cos10°,sin10°)를 사용한다.','내적≈−2.5cos10°−2.5sin10°≈−2.90.'],['Use u≈(−cos10°,sin10°).','The dot product is approximately −2.5cos10°−2.5sin10°≈−2.90.'],'약 −2.9.','Approximately −2.9.','화살표의 좌표와 각을 읽는 문제이므로 근삿값이다. 두 벡터의 둔각과 음의 부호가 일치한다.','Graphical coordinates and angles make this approximate. The obtuse angle agrees with a negative derivative.')
for n,F,P,Q in [(21,x*x*y*y-y**3,[1,2],[-3,5]),(22,x/y**2,[3,-1],[-2,11]),(23,S.sqrt(x*y),[2,8],[5,4]),(24,x*y*y*z**3,[2,1,1],[0,-3,5]),(25,x*y-x*y*y*z*z,[2,-1,1],[5,1,7])]:dd(n,F,[x,y] if len(P)==2 else [x,y,z],P,[Q[i]-P[i] for i in range(len(P))],'toward')
add(26,'등고선 그림의 P,Q,R에서 기울기 방향을 그려라. P와 R에서는 높은 값이 왼쪽 위, Q에서는 높은 값이 오른쪽 아래에 있다.','Draw gradient directions at P,Q,R in the contour plot. Higher values lie upper-left of P and R and lower-right of Q.',['각 점에서 등고선에 수직인 두 방향 중 값이 증가하는 쪽을 택한다.','P: 왼쪽 위. Q: 오른쪽 아래. R: 왼쪽 위. 길이는 등고선 간격의 역수에 비례하므로 방향만 확정한다.'],['Choose the normal direction toward larger contour values at each point.','P: upper-left; Q: lower-right; R: upper-left. Length is inversely related to contour spacing, so only direction is determined here.'],'P↖, Q↘, R↖.','P↖, Q↘, R↖.','기울기는 등고선 접선과 수직이며 높은 값 쪽이다.','Gradients are perpendicular to contour tangents and point toward larger values.')
for row in [(27,5*x*y*y,[x,y],[3,-2]),(28,s/(s*s+t*t),[s,t],[-1,1]),(29,S.sin(x*y),[x,y],[1,0]),(30,x*S.log(y*z),[x,y,z],[1,2,S.Rational(1,2)]),(31,x/(y+z),[x,y,z],[8,1,3]),(32,S.atan(p*q*r),[p,q,r],[1,2,1])]:maximum(*row)
add(33,r'(a) 미분가능 함수의 가장 빠른 감소 방향과 감소율을 증명하라. (b) \(f=x^4y-x^2y^3\)의 (2,−3)에 적용하라.',r'(a) Prove the fastest-decrease direction and rate for a differentiable function. (b) Apply to \(f=x^4y-x^2y^3\) at (2,−3).',[r'(a) \(D_uf=\nabla f\cdot u\ge-\|\nabla f\|\), 등호는 \(u=-\nabla f/\|\nabla f\|\)에서 성립한다.','(b) 기울기는 (12,−92)=4(3,−23)이다.'],[r'(a) \(D_uf=\nabla f\cdot u\ge-\|\nabla f\|\), with equality for \(u=-\nabla f/\|\nabla f\|\).','(b) The gradient is (12,−92)=4(3,−23).'],r'(b) \(u=(-3,23)/\sqrt{538}\), \(D_uf=-4\sqrt{538}\).',r'(b) \(u=(-3,23)/\sqrt{538}\), \(D_uf=-4\sqrt{538}\).','기울기가0이면 모든 방향미분이0이고 유일한 최급감소 방향은 없다.','If the gradient is zero, every directional derivative is zero and no unique steepest direction exists.',['a','b'])
add(34,r'\(f=x^2+xy^3\)의 (2,1)에서 방향미분이2인 모든 단위 방향을 구하라.',r'Find all unit directions giving derivative2 for \(f=x^2+xy^3\) at (2,1).',['기울기는 (5,6). 따라서 5a+6b=2 및 a²+b²=1을 푼다.',r'기울기 방향 성분은 \(2(5,6)/61\), 수직 성분은 \(\pm\sqrt{57}(-6,5)/61\)이다.'],['The gradient is (5,6); solve 5a+6b=2 and a²+b²=1.',r'The parallel component is \(2(5,6)/61\), and the perpendicular component is \(\pm\sqrt{57}(-6,5)/61\).'],r'\(u=(2(5,6)\pm\sqrt{57}(-6,5))/61\).',r'\(u=(2(5,6)\pm\sqrt{57}(-6,5))/61\).','두 벡터의 제곱길이는(244+3477)/3721=1이며 내적은2이다.','Both squared lengths are (244+3477)/3721=1 and both dot products equal2.')
add(35,r'\(f=x^2+y^2-2x-4y\)가 i+j 방향으로 가장 빨리 증가하는 점들을 구하라.',r'Find points where \(f=x^2+y^2-2x-4y\) increases fastest in direction i+j.',['기울기 (2x−2,2y−4)는 (1,1)의 양의 배수여야 한다.','2x−2=2y−4>0을 풀면 y=x+1,x>1이다.'],['The gradient (2x−2,2y−4) must be a positive multiple of (1,1).','Solve 2x−2=2y−4>0 to obtain y=x+1,x>1.'],'y=x+1, x>1.','y=x+1, x>1.','(1,2)에서는 기울기가0이어서 특정 최대 증가 방향이 없다.','At (1,2) the gradient is zero and has no distinguished maximum-increase direction.')
add(36,r'깊이 \(z=200+0.02x^2-0.001y^3\)(m)인 호수에서 (80,60)에서 원점으로 향한다. 깊이는 증가하는가? 거리당 변화율은?',r'Lake depth is \(z=200+0.02x^2-0.001y^3\) metres. From (80,60) head toward the origin. Does depth increase, and at what rate per distance?',['기울기는 (0.04x,−0.003y²)=(3.2,−10.8).','원점 방향 단위벡터는 (−0.8,−0.6), 내적은−2.56+6.48=3.92이다.'],['The gradient is (0.04x,−0.003y²)=(3.2,−10.8).','The unit direction is (−0.8,−0.6), giving −2.56+6.48=3.92.'],'깊어지며 3.92 m/m.','Depth increases at 3.92 m/m.')
add(37,'온도는 원점 거리의 역수에 비례하며 T(1,2,2)=120이다. (a) 이 점에서 (2,1,3) 방향 변화율을 구하라. (b) 가장 빨리 온도가 증가하는 방향을 설명하라.','Temperature is inversely proportional to distance from the origin and T(1,2,2)=120. (a) Find the derivative toward (2,1,3). (b) Explain the fastest-increase direction.',[r'\(T=360/\sqrt{x^2+y^2+z^2}\), 기울기는 \(-360(x,y,z)/(x^2+y^2+z^2)^{3/2}\).',r'(a) P에서 기울기는 \(-40(1,2,2)/3\), 방향은 \((1,-1,1)/\sqrt3\). (b) 음의 방사방향이다.'],[r'\(T=360/\sqrt{x^2+y^2+z^2}\), with gradient \(-360(x,y,z)/(x^2+y^2+z^2)^{3/2}\).',r'(a) At P the gradient is \(-40(1,2,2)/3\), and direction \((1,-1,1)/\sqrt3\). (b) The gradient is inward radial.'],r'(a) \(-40/(3\sqrt3)\). (b) 원점 쪽.',r'(a) \(-40/(3\sqrt3)\). (b) Toward the origin.','원점에서는 모델이 정의되지 않는다.','The model is undefined at the origin.',['a','b'])
for n,F,P,Q in [(38,200*S.exp(-x*x-3*y*y-9*z*z),[2,-1,2],[3,-3,3]),(39,5*x*x-3*x*y+x*y*z,[3,4,5],[4,5,4])]:
 G=vec([S.diff(F,j) for j in [x,y,z]]).subs(dict(zip([x,y,z],P)));V=vec(Q)-vec(P);A=S.simplify(G.dot(V)/S.sqrt(V.dot(V)));N=S.sqrt(G.dot(G));U=S.simplify(G/N)
 st='f='+M(F)+', P='+M(vec(P))+', v='+M(V)+'. '
 add(n,st+'(a) 주어진 방향 변화율, (b) 최대 증가 방향, (c) 최대 증가율을 구하라.',st+'Find (a) the directional rate, (b) fastest-increase direction, and (c) maximum rate.',['P에서 기울기는 '+M(G)+'.','(a) 방향벡터를 정규화해 내적한다. (b,c) 기울기를 정규화하고 그 길이를 계산한다.'],['The gradient at P is '+M(G)+'.','(a) Normalize the direction and take a dot product. (b,c) Normalize the gradient and calculate its norm.'],'(a) '+M(A)+'; (b) '+M(U)+'; (c) '+M(N)+'.','(a) '+M(A)+'; (b) '+M(U)+'; (c) '+M(N)+'.',parts=['a','b','c'])
add(40,r'언덕 \(z=1000-0.005x^2-0.01y^2\)의 (60,40,966)에 서 있다. x는 동쪽, y는 북쪽이며 단위는m이다. (a) 남쪽 (b) 북서쪽 이동의 경사와 오르내림, (c) 최급상승 방향·율·수평면과 각을 구하라.',r'On \(z=1000-0.005x^2-0.01y^2\) at (60,40,966), x points east and y north, in metres. Find slope and ascent/descent for (a) south, (b) northwest; (c) steepest-ascent direction, rate, and inclination.',['기울기는 (−0.6,−0.8), 길이는1이다.','(a) (0,−1)과 내적은0.8. (b) (−1,1)/√2와 내적은−0.2/√2.','(c) 남서쪽 (−3,−4)/5이며 tanα=1이다.'],['The gradient is (−0.6,−0.8), of norm1.','(a) Dotting with (0,−1) gives0.8. (b) Dotting with (−1,1)/√2 gives−0.2/√2.','(c) Direction is southwest, (−3,−4)/5, and tanα=1.'],r'(a) 상승0.8 m/m. (b) 하강, \(-\sqrt2/10\) m/m. (c) (−3,−4)/5, 1 m/m, 45°.',r'(a) Ascent0.8 m/m. (b) Descent, \(-\sqrt2/10\) m/m. (c) (−3,−4)/5, 1 m/m, 45°.',parts=['a','b','c'])
add(41,'A(1,3),B(3,3),C(1,7),D(6,15). A에서 AB 방향미분은3, AC 방향미분은26이다. AD 방향미분을 구하라.','Let A(1,3),B(3,3),C(1,7),D(6,15). At A the derivatives along AB and AC are3 and26. Find the derivative along AD.',['AB,AC는 각각 양의 x,y 방향이므로 기울기는 (3,26).','AD=(5,12), 길이13이므로 내적은 (15+312)/13이다.'],['AB and AC point along positive x and y, so the gradient is (3,26).','AD=(5,12) has length13; the dot product is (15+312)/13.'],'327/13.','327/13.')
add(42,'Blue River Pine 공원의 지형도에서 A는 Mud Lake 남쪽의 사면에 있고 B는 능선 서쪽 사면에 있다. A에서 호수까지, B에서 낮은 계곡으로 향하는 최급하강 곡선을 그려라.','On the Blue River Pine topographic map, A is on the slope south of Mud Lake and B on the western slope of the ridge. Sketch steepest-descent curves from A to the lake and from B toward the lower valley.',['각 등고선을 직각으로 통과하고 더 낮은 고도 쪽으로 진행한다. A에서는 처음 북서쪽으로 내려가다가 호수 방향으로 휜다.','B에서는 서쪽 내지 남서쪽 낮은 계곡 쪽으로 진행한다. 경로는 일직선일 필요가 없다.'],['Cross each contour at right angles toward lower elevations. From A initially descend northwest, then curve toward the lake.','From B descend west to southwest toward the lower valley. Paths need not be straight.'],'A: 북서쪽에서 호수 쪽으로 굽는 하강선. B: 서쪽–남서쪽 계곡으로 향하는 하강선.','A: a descending curve initially northwest, bending toward the lake. B: west–southwest into the valley.','도해는 원문 지도를 복제하지 않은 경로 원리의 개략도이며 정밀 지리 경로가 아니다.','The diagram illustrates the descent principle and is not a precise geographic reconstruction.')
add(43,r'미분가능한 u,v와 상수 a,b에 대해 기울기의 (a) 선형성, (b) 곱, (c) 몫, (d) 거듭제곱 규칙을 증명하라.',r'For differentiable u,v and constants a,b, prove gradient rules for (a) linear combinations, (b) products, (c) quotients, and (d) powers.',[r'각 좌표 j에서 \(\partial_j(au+bv)=a\partial_j u+b\partial_jv\)이고 곱·몫·연쇄법칙도 보통 미분과 같다.','각 좌표의 등식을 벡터로 모으면 네 규칙을 얻는다.'],[r'For each coordinate j, \(\partial_j(au+bv)=a\partial_j u+b\partial_jv\); the ordinary product, quotient, and chain rules also apply.','Assemble the coordinate identities into vector identities.'],r'(a) \(\nabla(au+bv)=a\nabla u+b\nabla v\). (b) \(\nabla(uv)=u\nabla v+v\nabla u\). (c) \(\nabla(u/v)=(v\nabla u-u\nabla v)/v^2\). (d) \(\nabla(u^n)=nu^{n-1}\nabla u\).',r'(a) \(\nabla(au+bv)=a\nabla u+b\nabla v\). (b) \(\nabla(uv)=u\nabla v+v\nabla u\). (c) \(\nabla(u/v)=(v\nabla u-u\nabla v)/v^2\). (d) \(\nabla(u^n)=nu^{n-1}\nabla u\).','몫은 v≠0, 실수 거듭제곱은 미분가능한 정의역에서 적용한다.','The quotient requires v≠0; real powers require a differentiable domain.',['a','b','c','d'])
add(44,'등고선 그림의 (4,6)에서 기울기를 추정하라. 그 부근에서 x가1 증가하면 함수는 약1 증가하고, y가1 증가하면 약2 감소한다.','Estimate the gradient at (4,6) from the contour plot. Locally, increasing x by1 raises the function by about1, while increasing y by1 lowers it by about2.',['수평 및 수직 절단선에서 등고선 값 차이를 거리로 나눈다.','fx≈1,fy≈−2를 모아 기울기 벡터를 만든다.'],['Divide contour-value differences by horizontal and vertical distances.','Combine fx≈1,fy≈−2 into the gradient.'],'기울기≈(1,−2).','Gradient≈(1,−2).','남동쪽 방향이 높은 등고선 쪽이며 등고선 접선에 대략 수직이다. 수치는 그림 판독에 따른 근사이다.','The southeast direction points toward higher contours and is approximately normal to them. Values are graphical estimates.')
add(45,r'\(f=x^3+5x^2y+y^3\), \(u=(3,4)/5\)일 때 (2,1)의 두 번 방향미분을 구하라.',r'For \(f=x^3+5x^2y+y^3\), \(u=(3,4)/5\), find the second directional derivative at (2,1).',[r'\(D_u^2f=u^TH_fu\). (2,1)의 헤세행렬은 \(\begin{pmatrix}22&20\\20&6\end{pmatrix}\).','행렬곱은 (9·22+24·20+16·6)/25이다.'],[r'\(D_u^2f=u^TH_fu\). At (2,1), the Hessian is \(\begin{pmatrix}22&20\\20&6\end{pmatrix}\).','The matrix product is (9·22+24·20+16·6)/25.'],'774/25.','774/25.')
add(46,r'(a) \(u=(a,b)\)에 대해 \(D_u^2f=a^2f_{xx}+2abf_{xy}+b^2f_{yy}\)를 증명하라. (b) \(f=xe^{2y}\), v=(4,6)에 적용하라.',r'(a) Prove \(D_u^2f=a^2f_{xx}+2abf_{xy}+b^2f_{yy}\) for \(u=(a,b)\). (b) Apply to \(f=xe^{2y}\), v=(4,6).',[r'(a) \((a\partial_x+b\partial_y)^2f\)를 전개하고 연속 혼합편미분의 교환을 사용한다.',r'(b) \(u=(2,3)/\sqrt{13}\), \(f_{xx}=0,f_{xy}=2e^{2y},f_{yy}=4xe^{2y}\).'],[r'(a) Expand \((a\partial_x+b\partial_y)^2f\), using equality of continuous mixed partials.',r'(b) \(u=(2,3)/\sqrt{13}\), \(f_{xx}=0,f_{xy}=2e^{2y},f_{yy}=4xe^{2y}\).'],r'(b) \((24+36x)e^{2y}/13\).',r'(b) \((24+36x)e^{2y}/13\).','C² 조건하에 전개가 성립하며 벡터 v를 먼저 단위화했다.','The expansion uses C² regularity, and v was normalized first.',['a','b'])
planes=[]
def plane(n,F,P,graph=False):
 G=vec([S.diff(F,j) for j in [x,y,z]]).subs(dict(zip([x,y,z],P)));assert F.subs(dict(zip([x,y,z],P)))==0;assert G.dot(G)!=0
 eq=S.expand(G.dot(vec([x,y,z])-vec(P)));line=vec(P)+t*G;assert S.simplify(G.dot(S.diff(line,t))-G.dot(G))==0
 st=M(F)+'=0, P='+M(vec(P))+'. '
 add(n,st+('(a) 접평면 (b) 법선 방정식을 구하라. 곡면·접평면·법선을 함께 그려라.' if graph else '(a) 접평면 (b) 법선 방정식을 구하라.'),st+('Find (a) the tangent plane and (b) normal line; plot all three.' if graph else 'Find (a) the tangent plane and (b) normal line.'),['좌변의 P에서의 기울기는 '+M(G)+'.','접평면은 기울기와 위치차의 내적이0인 평면이다. 법선은 P를 지나며 기울기에 평행하다.'],['The left side has gradient '+M(G)+' at P.','The tangent plane has zero dot product with displacement from P. The normal line passes through P parallel to the gradient.'],'(a) '+M(eq)+'=0. (b) '+M(line)+', t∈R.','(a) '+M(eq)+'=0. (b) '+M(line)+', t∈R.','원래 곡면에 P를 대입해0, 법선의 길이가0이 아님을 확인했다.','P satisfies the surface equation, and the normal has nonzero norm.',['a','b']);planes.append((n,F,P,list(G)))
for row in [(47,2*(x-2)**2+(y-1)**2+(z-3)**2-10,[3,3,5]),(48,x-y*y-z*z-1,[3,1,-1]),(49,x*y*y*z**3-8,[2,2,1]),(50,x*y+y*z+z*x-5,[1,2,1]),(51,x+y+z-S.exp(x*y*z),[0,0,1]),(52,x**4+y**4+z**4-3*x*x*y*y*z*z,[1,1,1]),(53,x*y+y*z+z*x-3,[1,1,1],True),(54,x*y*z-6,[1,2,3],True)]:plane(*row)
for n,F,P,level in [(55,x*y,[3,2],6),(56,x*x+y*y-4*x,[1,2],1)]:
 G=vec([S.diff(F,j) for j in [x,y]]).subs(dict(zip([x,y],P)));eq=S.expand(G.dot(vec([x,y])-vec(P)))
 add(n,'f='+M(F)+', P='+M(vec(P))+'. P의 기울기를 그리고 등위곡선과 접선을 함께 그려라.','f='+M(F)+', P='+M(vec(P))+'. Draw the gradient at P, the level curve, and its tangent.',['기울기는 '+M(G)+', P를 지나는 등위곡선은 '+M(F)+'='+str(level)+'.','접선의 법선으로 기울기를 사용한다.'],['The gradient is '+M(G)+', and the level curve through P is '+M(F)+'='+str(level)+'.','Use the gradient as the tangent-line normal.'],'접선: '+M(eq)+'=0; 기울기 '+M(G)+'.','Tangent: '+M(eq)+'=0; gradient '+M(G)+'.')
for n,st,formula,grad in [(57,r'x^2/a^2+y^2/b^2+z^2/c^2=1',r'xx_0/a^2+yy_0/b^2+zz_0/c^2=1',r'(2x_0/a^2,2y_0/b^2,2z_0/c^2)'),(58,r'x^2/a^2+y^2/b^2-z^2/c^2=1',r'xx_0/a^2+yy_0/b^2-zz_0/c^2=1',r'(2x_0/a^2,2y_0/b^2,-2z_0/c^2)'),(59,r'z/c=x^2/a^2+y^2/b^2',r'2xx_0/a^2+2yy_0/b^2=(z+z_0)/c',r'(2x_0/a^2,2y_0/b^2,-1/c)')]:
 add(n,r'곡면 \('+st+r'\)의 (x₀,y₀,z₀)에서 접평면 공식을 증명하라(a,b,c>0).',r'Prove the tangent-plane formula at (x₀,y₀,z₀) for \('+st+r'\), where a,b,c>0.',[r'곡면 좌변에서 우변을 뺀 함수의 기울기는 \('+grad+r'\).','기울기와 (x−x₀,y−y₀,z−z₀)의 내적을0으로 놓고 기준점의 곡면 방정식을 사용한다.'],[r'The defining function has gradient \('+grad+r'\).','Set its dot product with (x−x₀,y−y₀,z−z₀) to zero and use the surface equation at the base point.'],r'\('+formula+r'\).',r'\('+formula+r'\).','각 곡면에서 기울기는0이 아니므로 접평면이 존재한다.','The gradient is nonzero on each surface, ensuring a tangent plane.')
add(60,r'타원면 \(x^2+y^2+2z^2=1\)에서 접평면이 x+2y+z=1과 평행한 점을 구하라.',r'Find points of \(x^2+y^2+2z^2=1\) whose tangent planes are parallel to x+2y+z=1.',['(2x,2y,4z)는 (1,2,1)에 평행하므로 (x,y,z)=t(1,2,1/2).','제약식은 (11/2)t²=1이다.'],['Parallel normals give (x,y,z)=t(1,2,1/2).','The constraint becomes (11/2)t²=1.'],r'\(\pm(2,4,1)/\sqrt{22}\).',r'\(\pm(2,4,1)/\sqrt{22}\).')
add(61,r'\(x^2-y^2-z^2=1\)의 접평면이 z=x+y와 평행한 점이 있는지 알아보라.',r'Determine whether \(x^2-y^2-z^2=1\) has tangent planes parallel to z=x+y.',['법선의 평행 조건은 (x,y,z)=t(1,−1,1)이다.','곡면식에 대입하면 −t²=1로 실수 해가 없다.'],['Parallel normals require (x,y,z)=t(1,−1,1).','Substitution gives −t²=1, impossible over the reals.'],'그런 점은 없다.','There are no such points.')
add(62,r'\(3x^2+2y^2+z^2=9\)와 \(x^2+y^2+z^2-8x-6y-8z+24=0\)가 (1,1,2)에서 같은 접평면을 가짐을 보여라.',r'Show that \(3x^2+2y^2+z^2=9\) and \(x^2+y^2+z^2-8x-6y-8z+24=0\) share a tangent plane at (1,1,2).',['점을 두 곡면에 대입해 모두 만족함을 확인한다.','기울기는 각각 (6,4,4), (−6,−4,−4)이므로 법선이 평행하다.'],['The point satisfies both surface equations.','Their gradients are (6,4,4) and (−6,−4,−4), hence parallel.'],'공통 접평면: 3x+2y+2z=9.','Common tangent plane: 3x+2y+2z=9.')
add(63,r'원뿔 \(x^2+y^2=z^2\)의 모든 정칙점 접평면이 원점을 지남을 증명하라.',r'Prove that every regular-point tangent plane to \(x^2+y^2=z^2\) passes through the origin.',['기준점에서 법선은 (2x₀,2y₀,−2z₀).','접평면 x₀x+y₀y−z₀z=x₀²+y₀²−z₀²의 우변은0이다.'],['The normal at the base point is (2x₀,2y₀,−2z₀).','The tangent plane is x₀x+y₀y−z₀z=x₀²+y₀²−z₀²=0.'],'x₀x+y₀y−z₀z=0은 원점을 지난다.','x₀x+y₀y−z₀z=0 contains the origin.','꼭짓점에서는 기울기가0이므로 정칙점 접평면 공식을 적용하지 않는다.','The gradient vanishes at the vertex, where the regular tangent-plane formula does not apply.')
add(64,r'구면 \(x^2+y^2+z^2=r^2\), r>0의 모든 법선이 원점을 지남을 보여라.',r'Show every normal line of \(x^2+y^2+z^2=r^2\), r>0, passes through the origin.',['P의 법선방향은 기울기2P이다.','법선 P+2tP에 t=−1/2를 넣으면0이 된다.'],['The normal direction at P is the gradient2P.','The normal P+2tP equals0 when t=−1/2.'],'모든 법선은 원점을 지난다.','Every normal passes through the origin.')
add(65,r'포물면 \(z=x^2+y^2\)의 (1,1,2)에서 법선이 곡면과 다시 만나는 점을 구하라.',r'Find the second intersection of the normal to \(z=x^2+y^2\) at (1,1,2) with the surface.',['법선은 (1+2t,1+2t,2−t).','대입하면 2−t=2(1+2t)², 즉 t(8t+9)=0. 새 교점은 t=−9/8이다.'],['The normal is (1+2t,1+2t,2−t).','Substitution gives 2−t=2(1+2t)², or t(8t+9)=0. The new intersection has t=−9/8.'],'(−5/4,−5/4,25/8).','(−5/4,−5/4,25/8).')
add(66,r'타원면 \(4x^2+y^2+4z^2=12\)의 (1,2,1)에서 법선과 구면 \(x^2+y^2+z^2=102\)의 교점을 구하라.',r'Intersect the normal to \(4x^2+y^2+4z^2=12\) at (1,2,1) with \(x^2+y^2+z^2=102\).',['법선 방향 (8,4,8)을 줄여 (2,1,2)로 쓴다.','(1+2t,2+t,1+2t)를 구면에 넣으면 3t²+4t−32=0, t=8/3 또는−4이다.'],['Reduce normal direction (8,4,8) to (2,1,2).','Substituting (1+2t,2+t,1+2t) into the sphere gives 3t²+4t−32=0, so t=8/3 or−4.'],'(19/3,14/3,19/3), (−7,−2,−7).','(19/3,14/3,19/3), (−7,−2,−7).')
add(67,r'\(\sqrt x+\sqrt y+\sqrt z=\sqrt c\)의 양의 좌표점에서 접평면의 세 축절편 합이 c임을 보여라.',r'For \(\sqrt x+\sqrt y+\sqrt z=\sqrt c\), show that the sum of tangent-plane axis intercepts at a positive-coordinate point is c.',[r'기준점을 (a,b,d)라 하면 접평면은 \(x/\sqrt a+y/\sqrt b+z/\sqrt d=\sqrt c\).',r'절편은 \(\sqrt{ac},\sqrt{bc},\sqrt{dc}\), 합은 \(\sqrt c(\sqrt a+\sqrt b+\sqrt d)=c\).'],[r'At (a,b,d), the tangent plane is \(x/\sqrt a+y/\sqrt b+z/\sqrt d=\sqrt c\).',r'Intercepts are \(\sqrt{ac},\sqrt{bc},\sqrt{dc}\), summing to \(\sqrt c(\sqrt a+\sqrt b+\sqrt d)=c\).'],'세 절편의 합은 c.','The sum is c.','좌표가0인 점은 제곱근 미분이 특이하므로 이 접평면 유도는 양의 좌표에 적용한다.','Square-root derivatives are singular at zero coordinates, so this derivation applies to positive coordinates.')
add(68,'첫 팔분공간의 곡면 xyz=1의 접평면과 좌표평면이 만드는 사면체의 부피가 일정함을 보여라.','Show the tetrahedron bounded by coordinate planes and a tangent plane of xyz=1 in the first octant has constant volume.',['기준점 (a,b,c),abc=1에서 접평면은 x/a+y/b+z/c=3.','축절편3a,3b,3c이므로 부피=(3a)(3b)(3c)/6=9/2.'],['At (a,b,c),abc=1, the tangent plane is x/a+y/b+z/c=3.','Its intercepts are3a,3b,3c, giving volume(3a)(3b)(3c)/6=9/2.'],'부피9/2.','Volume9/2.')
for n,F,G,P in [(69,x*x+y*y-z,4*x*x+y*y+z*z-9,[-1,1,2]),(70,y+z-3,x*x+y*y-5,[1,2,1])]:
 sub=dict(zip([x,y,z],P));N1=vec([S.diff(F,j).subs(sub) for j in [x,y,z]]);N2=vec([S.diff(G,j).subs(sub) for j in [x,y,z]]);V=N1.cross(N2);assert V.dot(N1)==V.dot(N2)==0;line=vec(P)+t*V
 add(n,M(F)+'=0, '+M(G)+'=0의 교선에서 P='+M(vec(P))+'의 접선 방정식을 구하라.'+(' 곡면들과 접선도 그려라.' if n==70 else ''),'Find the tangent line of the intersection '+M(F)+'=0, '+M(G)+'=0 at P='+M(vec(P))+('. Plot the surfaces and tangent.' if n==70 else '.'),['두 법선은 '+M(N1)+', '+M(N2)+'.','교선 접선 방향은 외적 '+M(V)+'.'],['Surface normals are '+M(N1)+' and '+M(N2)+'.','Their cross product '+M(V)+' is tangent to the intersection.'],M(line)+', t∈R.',M(line)+', t∈R.','외적이0이 아니며 두 법선과의 내적은 모두0임을 검사했다.','The cross product is nonzero and its dot products with both normals are zero.')
for n,helix,surf,ts,sine in [(71,r'(\cos\pi t,\sin\pi t,t)',r'z=x^2+y^2','t=1',1/S.sqrt(5*(S.pi*S.pi+1))),(72,r'(\cos(\pi t/2),\sin(\pi t/2),t)',r'x^2+y^2+z^2=2','t=±1',S.sqrt(2)/S.sqrt(S.pi*S.pi+4))]:
 angle=float(S.asin(sine)*180/S.pi)
 add(n,r'나선 \(r(t)='+helix+r'\)와 곡면 \('+surf+r'\)이 교차할 때 곡선과 곡면의 각을 구하라.',r'Find the angle between helix \(r(t)='+helix+r'\) and surface \('+surf+r'\) at their intersections.',['곡면에 나선을 대입하면 '+ts+'이다.',r'접선벡터 v와 곡면법선 N을 구한다. 접선과 평면의 예각 α는 \(\sin\alpha=|v\cdot N|/(\|v\|\|N\|)\).','따라서 sinα='+M(sine)+'.'],['Substitution into the surface gives '+ts+'.',r'Compute curve tangent v and surface normal N. The acute line–plane angle satisfies \(\sin\alpha=|v\cdot N|/(\|v\|\|N\|)\).','Thus sinα='+M(sine)+'.'],f'α≈{angle:.3f}°'+(' (두 교점 모두).' if n==72 else '.'),f'α≈{angle:.3f}°'+(' at both intersections.' if n==72 else '.'),'법선과 접선 사이 각의 여각을 사용했다.','The line–plane angle is the complement of the line–normal angle.')
add(73,'F=0과 G=0의 교점에서 두 곡면이 직교하는 조건을 기울기로 나타내라.','Express the orthogonality condition for surfaces F=0 and G=0 at an intersection in terms of gradients.',[r'접평면의 법선은 각각 \(\nabla F,\nabla G\)이다.','두 접평면이 직교할 필요충분조건은 두 법선의 내적이0인 것이다.'],[r'Tangent-plane normals are \(\nabla F,\nabla G\).','The tangent planes are perpendicular exactly when their normals have zero dot product.'],r'\(\nabla F\cdot\nabla G=0\), 두 기울기는0이 아님.',r'\(\nabla F\cdot\nabla G=0\), with both gradients nonzero.','특이점에서 법선이0이면 이 정칙점 판정을 적용할 수 없다.','A zero normal at a singular point invalidates this regular-point criterion.')
add(74,r'원뿔 \(z^2=x^2+y^2\)와 구면 \(x^2+y^2+z^2=r^2\),r>0이 직교함을 대수·기하적으로 설명하라.',r'Explain algebraically and geometrically why \(z^2=x^2+y^2\) and \(x^2+y^2+z^2=r^2\),r>0, intersect orthogonally.',[r'법선 내적은 \((-2x,-2y,2z)\cdot(2x,2y,2z)=4(z^2-x^2-y^2)=0\).','구면법선인 반지름은 원뿔의 모선 방향이어서 원뿔 접평면 안에 있다. 따라서 두 법선은 수직이다.'],[r'The normal dot product is \((-2x,-2y,2z)\cdot(2x,2y,2z)=4(z^2-x^2-y^2)=0\).','The sphere’s radial normal lies along a cone generator in the cone tangent plane, so it is perpendicular to the cone normal.'],'교점마다 두 곡면은 직교한다.','The surfaces are orthogonal at every intersection.','r>0이므로 교점은 원뿔 꼭짓점이 아니고 두 법선은0이 아니다.','Since r>0, intersections avoid the cone vertex and both normals are nonzero.')
add(75,'평행하지 않은 단위벡터 u=(u₁,u₂),v=(v₁,v₂) 방향미분이 각각 A,B일 때 fx,fy를 복원하라.','Recover fx,fy from derivatives A,B in nonparallel unit directions u=(u₁,u₂),v=(v₁,v₂).',['연립식 u₁fx+u₂fy=A, v₁fx+v₂fy=B를 푼다.','행렬식 Δ=u₁v₂−u₂v₁는 평행하지 않으므로0이 아니다.'],['Solve u₁fx+u₂fy=A and v₁fx+v₂fy=B.','The determinant Δ=u₁v₂−u₂v₁ is nonzero by nonparallelism.'],'fx=(Av₂−Bu₂)/Δ, fy=(u₁B−v₁A)/Δ.','fx=(Av₂−Bu₂)/Δ, fy=(u₁B−v₁A)/Δ.')
add(76,r'\(f(x,y)=\sqrt[3]{xy}\). (a) 원점에서 연속이고 두 편도함수는 존재하지만 두 축 이외 방향미분은 존재하지 않음을 보여라. (b) 그래프로 이유를 설명하라.',r'For \(f(x,y)=\sqrt[3]{xy}\), (a) show continuity and both partials at the origin, but failure of directional derivatives off the coordinate axes. (b) Explain using a graph.',[r'(a) 곱과 실수 세제곱근은 연속이며 축 위에서 f=0이므로 fx(0,0)=fy(0,0)=0이다.',r'ab≠0이면 \(f(ha,hb)/h=\sqrt[3]{ab}\,|h|^{2/3}/h\), 절댓값이 무한대로 발산하여 유한 미분이 없다.','(b) 비축방향 단면은 원점에서 수직 첨점을 가지지만 좌표축 단면은 수평 직선이다.'],[r'(a) Products and real cube roots are continuous; f vanishes on both axes, so fx(0,0)=fy(0,0)=0.',r'For ab≠0, \(f(ha,hb)/h=\sqrt[3]{ab}\,|h|^{2/3}/h\), whose magnitude diverges, so no finite derivative exists.','(b) Off-axis sections have vertical cusps at the origin, while axial sections are horizontal lines.'],'연속, fx=fy=0; 비축방향의 유한 방향미분은 없다.','Continuous, fx=fy=0; no finite directional derivative off the axes.','양쪽 차분몫의 부호도 서로 달라 일방 무한기울기를 유한 방향미분으로 잘못 취급하지 않는다.','Opposite-sided difference quotients have opposite signs; infinite one-sided slopes are not finite derivatives.',['a','b'])
add(77,r'f가 x₀=(a,b)에서 미분가능하면 \(\lim_{x\to x_0}[f(x)-f(x_0)-\nabla f(x_0)\cdot(x-x_0)]/\|x-x_0\|=0\)임을 보여라.',r'If f is differentiable at x₀=(a,b), prove \(\lim_{x\to x_0}[f(x)-f(x_0)-\nabla f(x_0)\cdot(x-x_0)]/\|x-x_0\|=0\).',['미분가능성 정의로 나머지는 ε₁Δx+ε₂Δy이며 ε₁,ε₂→0이다.','|Δx|,|Δy|≤√(Δx²+Δy²)이므로 나눈 나머지 절댓값≤|ε₁|+|ε₂|→0.'],['By differentiability, the remainder is ε₁Δx+ε₂Δy, where ε₁,ε₂→0.','Since |Δx|,|Δy|≤√(Δx²+Δy²), the normalized remainder has magnitude≤|ε₁|+|ε₂|→0.'],'극한은0.','The limit is0.','분모가0인 기준점 자체를 제외한 극한이며 끼워넣기 정리를 적용한다.','The limit excludes the base point where the denominator is zero and follows by squeezing.')
E.sort(key=lambda e:e['number']);assert [a['number'] for a in E]==list(range(1,78))
D=dict(section='14.6',source=dict(title='Calculus',edition='9',language='en',printedPages=[1043,1044,1045,1046],pdfPages=[1080,1081,1082,1083]),scope=dict(kind='exercise',numbers=list(range(1,78)),total=77,note=pair('전체77문항과 모든 소문항.','All77 exercises and every subpart.')),exercises=E)
(R/'exercise-content/s14-6.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n');print('14.6:77 cards; line-restriction derivatives and surface normals verified')
