import sympy as S,json,math,itertools
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=[];x,y,z,t,lam,mu=S.symbols('x y z t lambda mu',real=True);M=lambda a:r'\('+S.latex(S.simplify(a))+r'\)';pair=lambda a,b:dict(ko=a,en=b)
def add(n,k,e,ks,es,ka,ea,kc='제약식과 후보값을 대입하고 극값 존재 조건을 확인했다.',ec='Constraints, candidate values, and existence of extrema were checked.',parts=[]):
 pg=1064 if n<=10 else 1065 if n<=40 else 1066
 E.append(dict(id=f'stewart9-exercise-14.8-{n}',number=n,subparts=parts,source=dict(printedPage=pg,pdfPage=pg+37),topic=pair('라그랑주 승수','Lagrange multipliers'),statement=pair(k,e),hint=pair('목적함수의 기울기를 제약식 기울기의 선형결합으로 놓고 특이점과 경계도 검사한다.','Set the objective gradient equal to a linear combination of constraint gradients; also check singularities and boundaries.'),steps=pair(ks,es),answer=pair(ka,ea),check=pair(kc,ec),conceptHref='../s14-8.html',status='math-verified'))
def lag(n,F,G,vs,pts,note_k='',note_e=''):
 eq=[S.diff(F,a)-lam*S.diff(G,a) for a in vs];table=[]
 for p in pts:
  sub=dict(zip(vs,p));assert S.simplify(G.subs(sub))==0;val=S.simplify(F.subs(sub));table.append((val,p))
 table.sort(key=lambda row:float(row[0]));mn=table[0][0];mx=table[-1][0];mini=[M(S.Tuple(*p)) for v,p in table if S.simplify(v-mn)==0];maxi=[M(S.Tuple(*p)) for v,p in table if S.simplify(v-mx)==0]
 ks=['승수 방정식: '+'; '.join(M(a)+'=0' for a in eq)+', '+M(G)+'=0.','각 좌표가0인 경우를 따로 포함해 풀고 다음 후보값을 비교한다: '+'; '.join(M(S.Tuple(*p))+': '+M(v) for v,p in table)];es=['Multiplier equations: '+'; '.join(M(a)+'=0' for a in eq)+', '+M(G)+'=0.','Include zero-coordinate cases separately and compare these candidate values: '+'; '.join(M(S.Tuple(*p))+': '+M(v) for v,p in table)]
 if note_k:ks.append(note_k);es.append(note_e)
 st='f='+M(F)+', '+M(G)+'=0. '
 add(n,st+'라그랑주 승수로 최대·최소를 구하라.',st+'Find maximum and minimum values by Lagrange multipliers.',ks,es,'최소 '+M(mn)+' at '+', '.join(mini)+'; 최대 '+M(mx)+' at '+', '.join(maxi),'Minimum '+M(mn)+' at '+', '.join(mini)+'; maximum '+M(mx)+' at '+', '.join(maxi))
add(1,'f의 등고선은10 간격이다. 제약곡선 g=8은 위쪽에서 f=60 등고선에 접하고 아래쪽에서는 f=30 등고선에 접하는 모양이다. 제약상 최대·최소를 추정하라.','Contours of f differ by10. The constraint g=8 touches the f=60 contour above and the f=30 contour below. Estimate the constrained extrema.',['제약곡선이 만나는 가장 큰 값과 가장 작은 값의 등고선을 찾는다.','극값에서는 보통 제약과 등고선이 접하므로 해당 접촉값을 읽는다.'],['Find the largest and smallest contour values reached by the constraint.','At regular extrema the constraint and contour are tangent; read the contact values.'],'최대 약60, 최소 약30.','Maximum approximately60; minimum approximately30.','원문 그림에서 값을 읽은 근삿값이다.','These are approximate values read from the source figure.')
lag(2,x*x+y,x*x+y*y-1,[x,y],[(0,-1),(0,1),(S.sqrt(3)/2,S.Rational(1,2)),(-S.sqrt(3)/2,S.Rational(1,2))],'(a) 자체 도해에서 접하는 포물선 값이 최소−1, 최대5/4로 보인다. (b) 위 승수계산과 일치한다.','(a) The original plot shows tangent parabolas at values−1 and5/4. (b) The multiplier calculation agrees.');E[-1]['subparts']=['a','b'];E[-1]['statement']['ko']+=' (a) 원과 여러 등위포물선을 그려 추정하고 (b) 정확한 값과 비교하라.';E[-1]['statement']['en']+=' (a) Plot the circle and several level parabolas to estimate; (b) compare exact results.'
lag(3,x*x-y*y,x*x+y*y-1,[x,y],[(1,0),(-1,0),(0,1),(0,-1)])
lag(4,x*x*y,x*x+y**4-5,[x,y],[(a,b) for a in [-2,2] for b in [-1,1]]+[(0,5**S.Rational(1,4)),(0,-5**S.Rational(1,4))])
lag(5,x*y,4*x*x+y*y-8,[x,y],[(a,b) for a in [-1,1] for b in [-2,2]])
lag(6,x*S.exp(y),x*x+y*y-2,[x,y],[(-1,1),(1,1)],'x=0은 첫 승수 방정식과 모순. x≠0이면 x²=y, y²+y=2에서 y=1만 가능하다.','x=0 contradicts the first multiplier equation. For x≠0, x²=y and y²+y=2 force y=1.')
lag(7,2*x*x+6*y*y,x**4+3*y**4-1,[x,y],[(a/S.sqrt(2),b/S.sqrt(2)) for a in [-1,1] for b in [-1,1]]+[(1,0),(-1,0),(0,3**(-S.Rational(1,4))),(0,-3**(-S.Rational(1,4)))])
lag(8,x*y*S.exp(-x*x-y*y),2*x-y,[x,y],[(0,0),(1/S.sqrt(5),2/S.sqrt(5)),(-1/S.sqrt(5),-2/S.sqrt(5))],'제약을 직접 넣으면 2x²e^(−5x²)≥0이고 무한대에서0으로 간다. 원점에서 최소0을 실제 달성한다.','Direct substitution gives2x²e^(−5x²)≥0, tending to0 at infinity. Its minimum0 is attained at the origin.')
lag(9,2*x+2*y+z,x*x+y*y+z*z-9,[x,y,z],[(2,2,1),(-2,-2,-1)])
lag(10,S.exp(x*y*z),2*x*x+y*y+z*z-24,[x,y,z],[(2*a,2*S.sqrt(2)*b,2*S.sqrt(2)*c) for a,b,c in itertools.product([-1,1],repeat=3)],'지수는 증가함수라 xyz를 최적화해도 된다. 좌표가0인 승수 후보의 값은1로 두 극값 사이이다.','The exponential is increasing, so optimize xyz. Zero-coordinate multiplier candidates have value1 between the two extremes.')
lag(11,x*y*y*z,x*x+y*y+z*z-4,[x,y,z],[(a,S.sqrt(2)*b,c) for a,b,c in itertools.product([-1,1],repeat=3)],'좌표0인 후보는 목적값0이다. 비영 좌표의 승수식은 x²=z²=y²/2를 준다.','Zero-coordinate candidates give0. For nonzero coordinates, multiplier equations give x²=z²=y²/2.')
lag(12,x*x+y*y+z*z,x*x+y*y+z*z+x*y-12,[x,y,z],[(2,2,0),(-2,-2,0),(2*S.sqrt(3),-2*S.sqrt(3),0),(-2*S.sqrt(3),2*S.sqrt(3),0),(0,0,2*S.sqrt(3)),(0,0,-2*S.sqrt(3))])
for n,F,G,power in [(13,x*x+y*y+z*z,x**4+y**4+z**4-1,4),(14,x**4+y**4+z**4,x*x+y*y+z*z-1,2)]:
 pts=[]
 for k in [1,2,3]:
  for indices in itertools.combinations(range(3),k):
   # All sign/permutation variants share the same candidate value; give a representative and state symmetry.
   arr=[0,0,0]
   for i in indices:arr[i]=S.Integer(k)**(-S.Rational(1,power))
   pts.append(tuple(arr))
 lag(n,F,G,[x,y,z],pts,'표는 좌표 부호 대칭을 대표한다. 각 비영 좌표의 부호를 독립적으로 바꾼 점들도 같은 극값을 준다.','The table represents coordinate-sign symmetry. Independently changing signs of nonzero coordinates gives the same extrema.');E[-1]['answer']['ko']+=' 모든 독립적인 부호변경 포함.';E[-1]['answer']['en']+=' Include every independent sign change.'
for n,dim in [(15,'4'),(16,'n')]:
 a=r'2' if n==15 else r'\sqrt n';coords=r'1/2' if n==15 else r'1/\sqrt n'
 add(n,f'{dim}차원 단위구면에서 좌표합의 최대·최소를 라그랑주 승수로 구하라.',f'Find extrema of the coordinate sum on the unit sphere in {dim} dimensions by Lagrange multipliers.',[r'각 좌표식 \(1=2\lambda x_i\)에 의해 모든 좌표가 같다. λ=0은 불가능하다.',r'제약식에 넣으면 각 좌표는 같은 부호의 \(\pm '+coords+r'\)이다.'],[r'The coordinate equations \(1=2\lambda x_i\) make all coordinates equal, and λ cannot be zero.',r'The constraint gives all coordinates the same sign, \(\pm '+coords+r'\).'],r'최대 \('+a+r'\), 최소 \(-'+a+r'\).',r'Maximum \('+a+r'\), minimum \(-'+a+r'\).')
add(17,'§3.7.3: 곱100인 두 양수의 합을 승수법으로 최소화하라.','§3.7.3: Minimize the sum of two positive numbers with product100 by multipliers.',['f=x+y,g=xy−100. 1=λy,1=λx에서 x=y.','양수 제약으로 x=y=10. xy=100을 유지하며 x가0 또는∞로 가면 합이∞이므로 최소이다.'],['For f=x+y,g=xy−100,1=λy and1=λx give x=y.','Positivity gives x=y=10. The sum diverges at either end of the constraint, establishing the minimum.'],'10과10, 최소합20.','10 and10; minimum sum20.')
add(18,'§3.7.8: 넓이1000 m²인 직사각형의 최소둘레 치수를 승수법으로 구하라.','§3.7.8: Use multipliers to minimize perimeter of a1000 m² rectangle.',['2=λy,2=λx로 x=y, xy=1000을 푼다.','경계로 치수가 퇴화하면 둘레는 무한히 증가한다.'],['Equations2=λy and2=λx give x=y; use xy=1000.','Perimeter diverges as either dimension degenerates.'],'각 변10√10 m, 최소둘레40√10 m.','Each side10√10 m; minimum perimeter40√10 m.')
add(19,'§3.7.7: 둘레100 m인 직사각형의 최대넓이 치수를 승수법으로 구하라.','§3.7.7: Use multipliers to maximize the area of a rectangle with perimeter100 m.',['y=2λ,x=2λ이므로 x=y.','2x+2y=100에서 x=y=25. 퇴화 경계 넓이는0.'],['Equations y=2λ,x=2λ give x=y.','Then2x+2y=100 yields x=y=25; degenerate boundary area is0.'],'25×25 m, 최대넓이625 m².','25×25 m; maximum area625 m².')
add(20,'§3.7.18: 정사각 밑면·뚜껑 없는 상자의 부피32,000 cm³를 유지하며 재료를 승수법으로 최소화하라.','§3.7.18: Minimize material for an open square-base box of volume32,000 cm³ using multipliers.',['목적 A=a²+4ah, 제약 a²h=32000.','2a+4h=λ2ah,4a=λa²에서 λ=4/a, 이어 a=2h.'],['Minimize A=a²+4ah subject to a²h=32000.','Equations2a+4h=λ2ah and4a=λa² give λ=4/a and a=2h.'],'밑변40 cm, 높이20 cm.','Base side40 cm; height20 cm.')
add(21,'§3.7.25: 직선 y=2x+3에서 원점에 가장 가까운 점을 승수법으로 구하라.','§3.7.25: Find the closest point to the origin on y=2x+3 using multipliers.',['거리제곱 f=x²+y², 제약2x−y+3=0. 2x=2λ,2y=−λ.','x=−2y를 제약에 넣으면 y=3/5,x=−6/5.'],['For squared distance,2x=2λ and2y=−λ under2x−y+3=0.','Substitute x=−2y into the constraint to get y=3/5,x=−6/5.'],'(−6/5,3/5), 거리3/√5.','(−6/5,3/5), distance3/√5.')
add(22,'§3.7.24: 길이+원둘레≤108 in인 원통 우편관의 최대부피 치수를 승수법으로 구하라(교재의 주어진 제한).','§3.7.24: Use the textbook constraint length+circumference≤108 in to maximize a cylindrical mailing tube’s volume by multipliers.',['제약은 최적점에서 h+2πr=108. 목적 πr²h의 승수식은2πrh=2πλ,πr²=λ.','h=πr이므로3πr=108이다.'],['The constraint is active: h+2πr=108. Multiplier equations are2πrh=2πλ andπr²=λ.','Thus h=πr and3πr=108.'],'반지름36/π in, 길이36 in, 최대부피46656/π in³.','Radius36/π in, length36 in, maximum volume46656/π in³.','이는 교재에 주어진 수학적 제약이며 현재 우편 규정 확인을 뜻하지 않는다.','This solves the textbook’s stated mathematical constraint, without asserting current postal rules.')
add(23,'xy=1에서 x²+y²의 최소를 승수법으로 구하고 최대가 없음을 보여라.','Minimize x²+y² under xy=1 by multipliers and show no maximum exists.',['2x=λy,2y=λx와 xy=1에서 x²=y², 따라서 (1,1),(−1,−1).','두 점의 값은2. 직접 x²+x^(−2)≥2이고 |x|→∞에서는 무한대이다.'],['Equations2x=λy,2y=λx with xy=1 yield x²=y², hence (1,1),(−1,−1).','Both values are2; directly x²+x^(−2)≥2 and diverges as |x|→∞.'],'최소2: (±1,±1), 부호 동일. 최대 없음.','Minimum2 at (±1,±1), matching signs; no maximum.')
add(24,r'x+2y+3z=10에서 \(f=x^2+2y^2+3z^2\)의 최소를 승수법으로 구하고 최대가 없음을 보여라.',r'Minimize \(f=x^2+2y^2+3z^2\) on x+2y+3z=10 using multipliers and show no maximum exists.',['2x=λ,4y=2λ,6z=3λ이므로 x=y=z=5/3.','양의 정부호 이차식이므로 이 정지점이 유일한 최소. 평면 위 (10−2t,t,0)에서는 f→∞이다.'],['Equations2x=λ,4y=2λ,6z=3λ give x=y=z=5/3.','Positive definiteness gives the unique minimum; along (10−2t,t,0) on the plane, f→∞.'],'최소50/3: (5/3,5/3,5/3). 최대 없음.','Minimum50/3 at (5/3,5/3,5/3); no maximum.')
add(25,r'x³+y³=16에서 \(e^{xy}\)의 최대를 승수법으로 구하고 최소가 없음을 보여라.',r'Maximize \(e^{xy}\) under x³+y³=16 by multipliers and show no minimum exists.',['단조성으로 xy를 최대화한다. y=3λx²,x=3λy²에서 x³=y³, 즉 x=y=2이다.','실수 제약에서 s=x+y>0이며 x³+y³=s³−3xys=16. s³≥16이고 xy=(s³−16)/(3s); 실제 실근 조건 s²−4xy≥0은 s³≤64이다. 따라서 xy≤4.','x→∞, y=(16−x³)^(1/3)일 때 xy→−∞, 목적값은0으로 가지만0을 취하지 않는다.'],['Monotonicity permits maximizing xy. Equations y=3λx²,x=3λy² imply x=y=2.','For real feasible points s=x+y>0. From s³−3xys=16 and real-root discriminant s²−4xy≥0, s³≤64; hence xy≤4.','As x→∞ and y is the real cube root of16−x³, xy→−∞, so the exponential approaches but never attains0.'],'최대e⁴: (2,2). 최소 없음, 하한0.','Maximume⁴ at (2,2); no minimum, infimum0.','s³≥16은 xy≥0인 경우에만 필요하며, xy<0인 점은 이미 xy≤4를 만족한다.','The auxiliary inequality s³≥16 is needed only when xy≥0; points with xy<0 already satisfy xy≤4.')
add(26,'x²+y+z²=1에서 f=4x+2y+z의 최대와 최소 존재 여부를 구하라.','Find the maximum of f=4x+2y+z on x²+y+z²=1 and determine whether a minimum exists.',['승수식4=2λx,2=λ,1=2λz이므로 x=1,z=1/4,y=−1/16.','직접 y를 제거하면 f=33/8−2(x−1)²−2(z−1/4)²이다.'],['Multiplier equations4=2λx,2=λ,1=2λz give x=1,z=1/4,y=−1/16.','Eliminating y gives f=33/8−2(x−1)²−2(z−1/4)².'],'최대33/8: (1,−1/16,1/4). 아래로 무한하여 최소 없음.','Maximum33/8 at (1,−1/16,1/4); unbounded below, no minimum.')
add(27,r'\(f=x^2+y^2+4x-4y\)를 x²+y²≤9에서 최적화하라.',r'Find extrema of \(f=x^2+y^2+4x-4y\) on x²+y²≤9.', ['내부 정지점 (−2,2)은 원판 안이며 f=−8. 제곱완성 f=(x+2)²+(y−2)²−8도 최소를 확인한다.','경계 승수식 (2x+4,2y−4)=λ(2x,2y)은 (x,y)=±(3/√2,−3/√2)를 준다. 경계값9±12√2를 비교한다.'],['The interior stationary point (−2,2) lies in the disk, with f=−8; completing squares confirms minimality.','Boundary multiplier equations give (x,y)=±(3/√2,−3/√2), with values9±12√2.'],r'최소−8: (−2,2). 최대 \(9+12\sqrt2\): \((3/\sqrt2,-3/\sqrt2)\).',r'Minimum−8 at (−2,2); maximum \(9+12\sqrt2\) at \((3/\sqrt2,-3/\sqrt2)\).')
add(28,r'\(f=2x^2+3y^2-4x-5\)를 x²+y²≤16에서 최적화하라.',r'Find extrema of \(f=2x^2+3y^2-4x-5\) on x²+y²≤16.',['내부는 (1,0), f=−7. 경계 승수식은4x−4=2λx,6y=2λy.','y=0 후보 (±4,0)와 λ=3 후보 (−2,±2√3)를 비교한다. 또는 경계 f=47−(x+2)²이다.'],['Interior point (1,0) gives−7. Boundary equations are4x−4=2λx,6y=2λy.','Compare y=0 candidates (±4,0) with λ=3 candidates (−2,±2√3); on the boundary f=47−(x+2)².'],'최소−7: (1,0). 최대47: (−2,±2√3).','Minimum−7 at (1,0); maximum47 at (−2,±2√3).')
add(29,r'\(f=e^{-xy}\)를 x²+4y²≤1에서 최적화하라.',r'Find extrema of \(f=e^{-xy}\) on x²+4y²≤1.',['내부 정지점은 원점, 값1. 경계에서 −y=2λx,−x=8λy로 x²=4y².','제약과 함께 |x|=1/√2,|y|=1/(2√2), xy=±1/4를 얻는다.'],['The interior stationary point is the origin, value1. Boundary equations−y=2λx,−x=8λy yield x²=4y².','Thus |x|=1/√2,|y|=1/(2√2), and xy=±1/4.'],r'최소 \(e^{-1/4}\): 같은 부호. 최대 \(e^{1/4}\): 반대 부호. 좌표 절댓값은 \((1/\sqrt2,1/(2\sqrt2))\).',r'Minimum \(e^{-1/4}\) for matching signs; maximum \(e^{1/4}\) for opposite signs, with coordinate magnitudes \((1/\sqrt2,1/(2\sqrt2))\).')
add(30,'f=z, 제약 x²+y²=z²와 x+y+z=24의 극값을 조사하라.','Investigate extrema of f=z under x²+y²=z² and x+y+z=24.',['승수식 (0,0,1)=λ(2x,2y,−2z)+μ(1,1,1)에서 λ=0은 모순이므로 x=y이다.','x=y를 제약에 넣으면 z=−24±24√2, x=y=24∓12√2.','가능한 z는 (24−z)²≤2z², 즉 z≥−24+24√2 또는 z≤−24−24√2이다. 두 가지 모두 비유계이다.'],['From (0,0,1)=λ(2x,2y,−2z)+μ(1,1,1), λ=0 is impossible, so x=y.','This gives z=−24±24√2 and x=y=24∓12√2.','Feasible z satisfy (24−z)²≤2z², hence z≥−24+24√2 or z≤−24−24√2; both branches are unbounded.'],r'전역 최대·최소 없음. 양의 가지 국소최소 \(-24+24\sqrt2\); 음의 가지 국소최대 \(-24-24\sqrt2\).',r'No global maximum or minimum. Positive-branch local minimum \(-24+24\sqrt2\); negative-branch local maximum \(-24-24\sqrt2\).','승수 후보가 있다고 전역극값이 존재한다고 결론내리지 않고 전체 가능한 z범위를 검사했다.','The entire feasible z range was checked rather than mistaking multiplier candidates for global extrema.')
add(31,'f=x+y+z, 제약 x²+z²=2,x+y=1의 극값을 구하라.','Find extrema of f=x+y+z under x²+z²=2 and x+y=1.',['승수식 (1,1,1)=λ(2x,0,2z)+μ(1,1,0)에서 μ=1,λ≠0,x=0.','그러면 y=1,z=±√2이다. 직접 f=1+z이고 |z|≤√2.'],['Equations (1,1,1)=λ(2x,0,2z)+μ(1,1,0) give μ=1,λ≠0,x=0.','Thus y=1,z=±√2; directly f=1+z with |z|≤√2.'],'최소1−√2: (0,1,−√2). 최대1+√2: (0,1,√2).','Minimum1−√2 at (0,1,−√2); maximum1+√2 at (0,1,√2).')
add(32,'f=x²+y²+z², 제약 x−y=1,y²−z²=1의 극값을 구하라.','Find extrema of f=x²+y²+z² under x−y=1 and y²−z²=1.',['승수식은 (2x,2y,2z)=λ(1,−1,0)+μ(0,2y,−2z). z≠0이면 μ=−1, x=y+1과 함께 y=−1/3이 되어 제약에 모순.','따라서 z=0,y=±1,x=y+1. 값은 (0,−1,0)에서1, (2,1,0)에서5.','직접 f=3y²+2y, |y|≥1이므로 첫 점이 절대최소, 두 번째는 다른 가지의 국소최소이고 위로 무한이다.'],['Multiplier equations are (2x,2y,2z)=λ(1,−1,0)+μ(0,2y,−2z). If z≠0, μ=−1 leads to y=−1/3, contradicting the constraint.','Thus z=0,y=±1,x=y+1; values are1 at (0,−1,0) and5 at (2,1,0).','Directly f=3y²+2y on |y|≥1, so the first is absolute minimum, the second a branch-local minimum, and f is unbounded above.'],'절대최소1: (0,−1,0). 국소최소5: (2,1,0). 최대 없음.','Absolute minimum1 at (0,−1,0); local minimum5 at (2,1,0); no maximum.')
add(33,'f=yz+xy, 제약 xy=1,y²+z²=1의 극값을 구하라.','Find extrema of f=yz+xy under xy=1 and y²+z²=1.',['승수식 (y,z+x,y)=λ(y,x,0)+μ(0,2y,2z). y≠0이므로 λ=1, 이어 z=2μy,y=2μz로 z=±y.','y²=z²=1/2, x=1/y이며 f=1+yz이다.'],['Equations (y,z+x,y)=λ(y,x,0)+μ(0,2y,2z) give λ=1 since y≠0. Then z=2μy,y=2μz, hence z=±y.','Thus y²=z²=1/2,x=1/y and f=1+yz.'],r'최대3/2: \((\pm\sqrt2,\pm1/\sqrt2,\pm1/\sqrt2)\) 같은 부호. 최소1/2: z가 x,y와 반대 부호.',r'Maximum3/2 at \((\pm\sqrt2,\pm1/\sqrt2,\pm1/\sqrt2)\) with matching signs; minimum1/2 when z has opposite sign to x,y.','2|yz|≤y²+z²=1은 이 후보들의 전역 극값을 보장한다.','The bound2|yz|≤y²+z²=1 guarantees these are global extrema.')
add(34,'f=2x+3y, 제약 √x+√y=5. (a) 승수법 시도 (b) f(25,0) 비교 (c) 그래프 최적화 (d) 승수법의 한계 (e) f(9,4)의 의미를 설명하라.','For f=2x+3y subject to √x+√y=5, (a) try multipliers, (b) compare f(25,0), (c) solve graphically, (d) explain the limitation, and (e) interpret f(9,4).',['(a) 양의 좌표에서2=λ/(2√x),3=λ/(2√y)이므로 √x=3,√y=2, f=30.','(b) f(25,0)=50>30. (c) 끝점 (0,25)의 f=75가 최대.','(d) 끝점에서 제약함수의 편도함수가 유한하게 존재하지 않아 정칙 승수조건을 적용할 수 없다.','(e) t=√x∈[0,5]로 쓰면 f=2t²+3(5−t)²=5(t−3)²+30. 따라서 f(9,4)=30은 최소이다.'],['(a) At positive coordinates2=λ/(2√x),3=λ/(2√y), giving √x=3,√y=2 and f=30.','(b) f(25,0)=50>30. (c) The other endpoint (0,25) gives the maximum75.','(d) The constraint’s partial derivatives are not finite at the endpoints, so the regular multiplier condition does not apply there.','(e) With t=√x∈[0,5], f=5(t−3)²+30; hence f(9,4)=30 is the minimum.'],'최대75: (0,25). 최소30: (9,4). f(25,0)=50.','Maximum75 at (0,25); minimum30 at (9,4); f(25,0)=50.',parts=['a','b','c','d','e'])
add(35,'f=x를 y²+x⁴−x³=0에서 최소화한다. (a) 승수법 (b) 원점의 실제 최소와 승수식 불성립 (c) 실패 이유를 설명하라.','Minimize f=x on y²+x⁴−x³=0. (a) Try multipliers; (b) show the actual minimum at the origin fails their condition; (c) explain why.',['(a) 1=λ(4x³−3x²),0=2λy. λ≠0이므로 y=0; x=0 또는1 중 승수식을 만족하는 것은 x=1뿐이다.','(b) 제약은 y²=x³(1−x)로 0≤x≤1. 최소는 (0,0)의0이나 그 점에서 ∇g=(0,0),∇f=(1,0).','(c) 제약의 특이점에서 비영 기울기 가정이 깨졌다.'],['(a) Equations1=λ(4x³−3x²),0=2λy force y=0. Of x=0,1, only x=1 satisfies the multiplier equation.','(b) Since y²=x³(1−x),0≤x≤1. The minimum is0 at (0,0), where ∇g=(0,0),∇f=(1,0).','(c) The nonzero constraint-gradient hypothesis fails at the singular point.'],'최소0: (0,0), 승수 없음. 승수 후보 (1,0)은 최대1.','Minimum0 at (0,0), with no multiplier; the multiplier candidate (1,0) is the maximum1.',parts=['a','b','c'])
F=x**3+y**3+3*x*y;theta=S.symbols('theta',real=True);fth=F.subs({x:3+3*S.cos(theta),y:3+3*S.sin(theta)},simultaneous=True);df=S.diff(fth,theta);roots=[]
for seed in [2*math.pi*i/40 for i in range(40)]:
 try:rt=float(S.nsolve(df,seed))%(2*math.pi)
 except ValueError:continue
 if all(abs(rt-q)>1e-7 for q in roots):roots.append(rt)
values=sorted([(float(fth.subs(theta,a)),3+3*math.cos(a),3+3*math.sin(a)) for a in roots]);assert len(roots)==2
add(36,r'\(f=x^3+y^3+3xy\), \((x-3)^2+(y-3)^2=9\). (a) 등고선 그림으로 극값을 추정하고 (b) 승수 연립방정식을 수치적으로 풀어 비교하라.',r'For \(f=x^3+y^3+3xy\) on \((x-3)^2+(y-3)^2=9\), (a) estimate extrema graphically and (b) solve multiplier equations numerically.',['(a) 도해에서 작은 값은 왼쪽 아래, 큰 값은 오른쪽 위 쪽에 있다.',r'(b) \(3x^2+3y=2\lambda(x-3),3y^2+3x=2\lambda(y-3)\)와 제약을 푼다.','원의 x=3+3cosθ,y=3+3sinθ 매개화로 모든 정지값을 확인: '+'; '.join(f'({a:.6f},{b:.6f}):{v:.6f}' for v,a,b in values)],['(a) The plot places smaller values lower-left and larger values toward upper-right.',r'(b) Solve \(3x^2+3y=2\lambda(x-3),3y^2+3x=2\lambda(y-3)\) and the constraint.','The circle parametrization x=3+3cosθ,y=3+3sinθ verifies all stationary values: '+'; '.join(f'({a:.6f},{b:.6f}):{v:.6f}' for v,a,b in values)],f'최소{values[0][0]:.6f} at ({values[0][1]:.6f},{values[0][2]:.6f}); 최대{values[-1][0]:.6f} at ({values[-1][1]:.6f},{values[-1][2]:.6f}).',f'Minimum{values[0][0]:.6f} at ({values[0][1]:.6f},{values[0][2]:.6f}); maximum{values[-1][0]:.6f} at ({values[-1][1]:.6f},{values[-1][2]:.6f}).','독립 매개화 미분으로 두 정지점을 찾았고 제약식 잔차를 검사했다.','Independent parametrization derivatives located two stationary points and constraints were checked.',['a','b'])
add(37,r'생산 \(P=bL^\alpha K^{1-\alpha}\), b>0,0<α<1과 비용 mL+nK=p에서 최대 생산의 L,K를 승수법으로 구하라.',r'Maximize \(P=bL^\alpha K^{1-\alpha}\), b>0,0<α<1, under mL+nK=p by multipliers.',['생산이 양수인 내부에서 로그 목적 αlnL+(1−α)lnK를 써도 같다.','α/L=λm,(1−α)/K=λn에 L,K를 곱해 더하면1=λp이다.','따라서 노동·자본에 예산의 α,1−α 몫을 배분한다. 경계 생산은0이고 로그 목적은 엄격 오목이다.'],['In the positive interior, maximize the equivalent log objective αlnL+(1−α)lnK.','From α/L=λm,(1−α)/K=λn, multiply by L,K and add to obtain1=λp.','Allocate fractions α and1−α of the budget to labor and capital. Boundary production is0 and the log objective is strictly concave.'],r'\(L=\alpha p/m,\quad K=(1-\alpha)p/n\).',r'\(L=\alpha p/m,\quad K=(1-\alpha)p/n\).')
add(38,r'생산 \(bL^\alpha K^{1-\alpha}=Q>0\)를 고정하고 비용 mL+nK를 최소화하라.',r'Minimize mL+nK with fixed production \(bL^\alpha K^{1-\alpha}=Q>0\).',['승수식의 비는 m/n=αK/((1−α)L)이므로 K/L=(1−α)m/(αn)=ρ이다.','제약은 bρ^(1−α)L=Q, 따라서 L=(Q/b)ρ^(α−1),K=(Q/b)ρ^α.','제약을 따라 L→0 또는∞이면 비용이∞이므로 유일한 정지점이 전역최소이다.'],['The multiplier ratio gives m/n=αK/((1−α)L), so K/L=ρ=(1−α)m/(αn).','The constraint becomes bρ^(1−α)L=Q, hence L=(Q/b)ρ^(α−1),K=(Q/b)ρ^α.','Along the constraint cost diverges as L→0 or∞, so the unique stationary point is globally minimal.'],r'\(L=\frac Qb[\frac{\alpha n}{(1-\alpha)m}]^{1-\alpha},\quad K=\frac Qb[\frac{(1-\alpha)m}{\alpha n}]^\alpha\).',r'\(L=\frac Qb[\frac{\alpha n}{(1-\alpha)m}]^{1-\alpha},\quad K=\frac Qb[\frac{(1-\alpha)m}{\alpha n}]^\alpha\).')
add(39,'주어진 둘레 p에서 최대넓이 직사각형이 정사각형임을 승수법으로 증명하라.','Prove by multipliers that a maximum-area rectangle with perimeter p is a square.',['목적 xy, 제약2x+2y=p의 승수식은 y=2λ,x=2λ이다.','따라서 x=y=p/4. 퇴화 경계 넓이가0이므로 내부 후보가 최대이다.'],['For objective xy and constraint2x+2y=p, y=2λ,x=2λ.','Thus x=y=p/4; the degenerate boundary has zero area, establishing maximality.'],'정사각형 변p/4, 최대넓이p²/16.','Square sidep/4, maximum areap²/16.')
add(40,'둘레 p인 삼각형의 최대넓이가 정삼각형에서 달성됨을 Heron 공식과 승수법으로 증명하라.','Use Heron’s formula and multipliers to show the maximum-area triangle of perimeter p is equilateral.',['s=p/2는 고정. 넓이제곱 s(s−x)(s−y)(s−z)를 최대화하며 x+y+z=p이다.','양의 넓이 내부에서 로그 미분을 쓰면 −1/(s−x)=−1/(s−y)=−1/(s−z)=λ이므로 x=y=z.','퇴화 경계에서는 넓이가0. 유일한 내부 후보가 최대이다.'],['With s=p/2 fixed, maximize squared area s(s−x)(s−y)(s−z) subject to x+y+z=p.','Logarithmic multiplier equations give−1/(s−x)=−1/(s−y)=−1/(s−z)=λ, hence equal sides.','Degenerate boundary triangles have zero area, so the unique interior candidate is maximal.'],r'변p/3의 정삼각형, 최대넓이 \(\sqrt3p^2/36\).',r'Equilateral sidesp/3, maximum area \(\sqrt3p^2/36\).')
previous=json.loads((R/'exercise-content/s14-7.json').read_text())
alt={
41:(43,['거리제곱의 승수식 2(P−(2,0,−3))=λ(1,1,1). 제약에 넣으면 λ=4/3, P=(8/3,2/3,−7/3).','볼록 이차목적과 평면 제약이므로 이 정지점은 유일한 최소이다.'],['For squared distance,2(P−(2,0,−3))=λ(1,1,1). The constraint gives λ=4/3 and P=(8/3,2/3,−7/3).','A strictly convex quadratic on a plane makes this the unique minimum.']),
42:(44,['거리제곱의 승수식은2(P−(0,1,1))=λ(1,−2,3). 제약에 넣으면 λ=5/7이다.','따라서 P=(0,1,1)+(5/14)(1,−2,3).'],['The squared-distance equations are2(P−(0,1,1))=λ(1,−2,3). The constraint gives λ=5/7.','Hence P=(0,1,1)+(5/14)(1,−2,3).']),
43:(45,['거리제곱의 승수식은 (x−4,y−2,z)=λ(x,y,−z). z≠0이면 λ=−1에서 x=2,y=1,z=±√5이다.','z=0인 제약점은 꼭짓점 원점뿐이다. 그 거리제곱20과 두 후보값10을 비교한다.'],['Squared-distance equations are (x−4,y−2,z)=λ(x,y,−z). For z≠0, λ=−1 gives x=2,y=1,z=±√5.','The only feasible z=0 point is the singular vertex. Compare its squared distance20 with the candidates’10.']),
44:(46,['(2x,2y,2z)=λ(−z,2y,−x). y≠0이면 λ=1, 2x=−z,2z=−x이므로 x=z=0,y=±3.','y=0이면 xz=−9, x²+z²≥18이므로 후보의 거리제곱9보다 크다.'],['Equations (2x,2y,2z)=λ(−z,2y,−x) give λ=1 when y≠0, hence x=z=0,y=±3.','If y=0, then xz=−9 and x²+z²≥18, exceeding squared distance9 at the candidates.']),
45:(47,['양수 내부에서 yz=λ,xz=λ,xy=λ. 세 식을 나누면 x=y=z, 합 제약으로100/3.','0을 허용한 경계 곱은0이고 후보 곱은 양수이므로 최대이다.'],['Interior equations yz=λ,xz=λ,xy=λ force equal positive coordinates, each100/3.','The closed-simplex boundary product is0, whereas the candidate is positive.']),
46:(48,['2x=λ,2y=λ,2z=λ와 합12에서 x=y=z=4.','양의 정부호 헤세행렬로 제약평면의 유일한 최소이다.'],['Equations2x=λ,2y=λ,2z=λ with sum12 give x=y=z=4.','The positive-definite Hessian ensures the unique minimum on the constraint plane.']),
47:(49,['변 길이 a,b,c의 제약 a²+b²+c²=4r²에서 bc=2λa,ac=2λb,ab=2λc.','각 식에 a,b,c를 곱하면 a²=b²=c². 양수 치수와 제약으로 세 변2r/√3. 퇴화 경계부피는0.'],['Under a²+b²+c²=4r², multiplier equations are bc=2λa,ac=2λb,ab=2λc.','Multiply by a,b,c to obtain equal squares, hence positive sides2r/√3. Degenerate boundary volumes are0.']),
48:(50,['2(b+c)=λbc,2(a+c)=λac,2(a+b)=λab. abc로 나눠 비교하면 a=b=c이다.','부피1000에서 세 변10. 비용은 제약 경계에서 무한대이므로 최소이다.'],['Equations2(b+c)=λbc,2(a+c)=λac,2(a+b)=λab imply a=b=c after division and comparison.','Volume1000 gives sides10. Surface area diverges toward the constraint extremes, ensuring minimality.']),
49:(51,['yz=λ,xz=2λ,xy=3λ이므로 x=2y=3z.','제약 x+2y+3z=6에서 x=2,y=1,z=2/3. 경계부피는0.'],['Equations yz=λ,xz=2λ,xy=3λ yield x=2y=3z.','The plane constraint gives x=2,y=1,z=2/3; boundary volumes are0.']),
50:(52,['로그 부피의 승수식은1/a=2λ(b+c),1/b=2λ(a+c),1/c=2λ(a+b).','각 식에 a,b,c를 곱해 빼면 ab=bc=ca. 겉넓이64에서 세 변4√(2/3).'],['Log-volume equations are1/a=2λ(b+c),1/b=2λ(a+c),1/c=2λ(a+b).','Multiplying by a,b,c and subtracting gives ab=bc=ca. Surface area64 yields sides4√(2/3).']),
51:(53,['제약4(a+b+d)=c에 대해 로그 부피 승수식은1/a=4λ,1/b=4λ,1/d=4λ.','세 변은 같으며 합 제약으로 c/12이다.'],['Log-volume multiplier equations under4(a+b+d)=c are1/a=4λ,1/b=4λ,1/d=4λ.','All sides are equal, hence c/12.']),
52:(54,['비용5ab+2h(a+b), 제약abh=V의 승수식은5b+2h=λbh,5a+2h=λah,2(a+b)=λab.','첫 두 식에 a,b를 곱해 빼면 a=b. 셋째 식과 함께 h=5a/2, a³=2V/5이다.'],['For cost5ab+2h(a+b) under abh=V, equations are5b+2h=λbh,5a+2h=λah,2(a+b)=λab.','Multiplying the first two by a,b and subtracting gives a=b. Then h=5a/2 and a³=2V/5.']),
53:(57,['제약 a²+b²+c²=L²에서 bc=2λa,ac=2λb,ab=2λc.','양수 치수에 대해 a²=b²=c², 따라서 a=b=c=L/√3이다.'],['Under a²+b²+c²=L², bc=2λa,ac=2λb,ab=2λc.','Positive dimensions give equal squares and hence a=b=c=L/√3.'])}
for n,(old,ks,es) in alt.items():
 q=next(e for e in previous['exercises'] if e['number']==old)
 add(n,q['statement']['ko']+' 라그랑주 승수법으로 풀라.',q['statement']['en']+' Solve with Lagrange multipliers.',ks,es,q['answer']['ko'],q['answer']['en'],q['check']['ko'],q['check']['en'])
add(54,'직육면체의 길이+둘레≤108 in이라는 교재 제약 아래 최대부피 포장의 치수를 승수법으로 구하라.','Use multipliers to maximize a box volume under the textbook constraint length+girth≤108 in.',['길이 l,단면 a,b에 대해 l+2a+2b=108이 최적점에서 성립한다.','ab=λ,lb=2λ,la=2λ에서 l=2a=2b. 제약에 넣으면 l=36,a=b=18이다.'],['For length l and cross-section a,b, the active constraint is l+2a+2b=108.','Equations ab=λ,lb=2λ,la=2λ give l=2a=2b, hence l=36,a=b=18.'],'36×18×18 in, 최대부피11664 in³.','36×18×18 in; maximum volume11664 in³.','길이36은 나머지 두 치수18보다 크며 경계 퇴화부피는0이다.','Length36 exceeds the other dimensions18, and degenerate boundary volumes are0.')
add(55,'반구 지붕과 평평한 바닥을 붙인 원기둥 저장고의 총 겉넓이 S가 고정되었다. 최대부피일 때 원기둥 높이와 반지름이 같음을 승수법으로 보여라.','A cylindrical silo has a hemispherical roof and flat floor, with fixed total surface area S. Prove using multipliers that maximum volume occurs when cylinder height equals radius.',[r'\(V=\pi r^2h+2\pi r^3/3\), \(S=3\pi r^2+2\pi rh\).','h미분에서 πr²=λ2πr, 즉 λ=r/2. r미분식2πrh+2πr²=λ(6πr+2πh)에 대입하면 h=r.','경계 h=0 또는r→0의 부피보다 내부 후보가 크다. 직접 제약 제거식 V=Sr/2−5πr³/6도 같은 유일한 최대를 준다.'],[r'\(V=\pi r^2h+2\pi r^3/3\), \(S=3\pi r^2+2\pi rh\).','The h equation gives λ=r/2. Substitution into2πrh+2πr²=λ(6πr+2πh) yields h=r.','The boundary cases h=0 orr→0 give smaller volumes. The reduced expression V=Sr/2−5πr³/6 confirms the unique maximum.'],r'\(h=r=\sqrt{S/(5\pi)}\).',r'\(h=r=\sqrt{S/(5\pi)}\).')
a1=(50-5*S.sqrt(10))/3;a2=(50+5*S.sqrt(10))/3;V1=S.simplify(a1*a1*(50-2*a1));V2=S.simplify(a2*a2*(50-2*a2))
add(56,'겉넓이1500 cm², 전체 모서리 길이200 cm인 직육면체의 최대·최소부피를 구하라.','Find maximum and minimum box volumes with surface area1500 cm² and total edge length200 cm.',['a+b+c=50,ab+bc+ca=750. 승수식 bc=λ+μ(b+c) 및 순환식을 빼면 (b−a)(c−μ)=0 등이다. 모두 다르면 a=b=c=μ라는 모순이므로 적어도 두 변이 같다.','a=b=u,c=50−2u에서3u²−100u+750=0. 따라서 u=(50±5√10)/3.','변이0인 경계라면 두 나머지 합50,곱750이어야 하나 곱≤625여서 불가능하다. 따라서 두 후보 부피를 비교하면 충분하다.'],['Constraints are a+b+c=50,ab+bc+ca=750. Subtracting multiplier equations gives (b−a)(c−μ)=0 and cyclic variants; at least two sides must coincide.','Set a=b=u,c=50−2u. Then3u²−100u+750=0, giving u=(50±5√10)/3.','A zero-side boundary would require two sides of sum50 and product750, impossible since product≤625. Thus compare the two candidate volumes.'],'최대 '+M(V1)+' cm³ at '+M(S.Tuple(a1,a1,50-2*a1))+'; 최소 '+M(V2)+' cm³ at '+M(S.Tuple(a2,a2,50-2*a2))+' 및 순열.','Maximum '+M(V1)+' cm³ at '+M(S.Tuple(a1,a1,50-2*a1))+'; minimum '+M(V2)+' cm³ at '+M(S.Tuple(a2,a2,50-2*a2))+' and permutations.')
add(57,'평면 x+y+2z=2와 포물면 z=x²+y²의 교선에서 원점에 가장 가깝고 먼 점을 구하라.','Find nearest and farthest points from the origin on the intersection of x+y+2z=2 and z=x²+y².',['거리제곱은 z+z²이며 z≥0에서 증가한다. 따라서 z를 승수법으로 최적화한다.','(0,0,1)=λ(1,1,2)+μ(2x,2y,−1)에서 μ≠0, x=y. 2x+4x²=2이므로 x=1/2 또는−1.','각각 z=1/2 또는2이고 거리제곱은3/4 또는6이다.'],['Squared distance is z+z², increasing for z≥0, so optimize z by multipliers.','Equations (0,0,1)=λ(1,1,2)+μ(2x,2y,−1) force μ≠0,x=y. Then2x+4x²=2 yields x=1/2 or−1.','The corresponding z values are1/2 and2, with squared distances3/4 and6.'],'최근점(1/2,1/2,1/2), 거리√3/2. 최원점(−1,−1,2), 거리√6.','Nearest(1/2,1/2,1/2), distance√3/2; farthest(−1,−1,2), distance√6.')
add(58,'원뿔 z²=x²+y²와 평면4x−3y+8z=5의 교선을 (a) 그리고 (b) 승수법으로 최고·최저점을 구하라.','For z²=x²+y² and4x−3y+8z=5, (a) plot the intersection and (b) find highest and lowest points by multipliers.',['(a) 아래 원뿔은 평면과 만나지 않고 위 원뿔에서 타원이 생긴다.','(b) (0,0,1)=λ(−2x,−2y,2z)+μ(4,−3,8)에서 (x,y)가 (4,−3)에 평행하다.','|4x−3y|≤5z와 평면식으로 |5−8z|≤5z, 즉5/13≤z≤5/3. 등호일 때 좌표를 복원한다.'],['(a) The lower cone does not meet the plane; their intersection on the upper cone is an ellipse.','(b) Equations (0,0,1)=λ(−2x,−2y,2z)+μ(4,−3,8) make (x,y) parallel to (4,−3).','Using |4x−3y|≤5z in the plane gives |5−8z|≤5z, hence5/13≤z≤5/3. Recover coordinates at equality.'],'최저점(4/13,−3/13,5/13). 최고점(−4/3,1,5/3).','Lowest(4/13,−3/13,5/13); highest(−4/3,1,5/3).',parts=['a','b'])
# Complete algebraic eliminations verify all real multiplier candidates for59–60.
Y,W=S.symbols('Y W');H=45*W**2-54*W+45+16*Y**4-144*Y**2;K=(Y-W)*S.diff(H,W)-Y*S.diff(H,Y);res=S.factor(S.resultant(H,K,W)/25920);rows=[]
for rt in S.nroots(res,maxsteps=200):
 if abs(float(S.im(rt)))>1e-9:continue
 yy=float(S.re(rt))
 for ww in S.nroots(H.subs(Y,yy),maxsteps=200):
  if abs(float(S.im(ww)))>1e-9:continue
  ww=float(S.re(ww))
  if abs(float(K.subs({Y:yy,W:ww})))>1e-5:continue
  xx=(1+ww)/(2*yy);zz=(1-ww)/(2*yy);assert abs(9*xx*xx+4*yy*yy+36*zz*zz-36)<1e-7;assert abs(yy*(xx+zz)-1)<1e-8;rows.append((yy*math.exp(xx-zz),xx,yy,zz))
rows.sort();assert len(rows)==4
add(59,r'\(f=ye^{x-z}\), 제약 \(9x^2+4y^2+36z^2=36,xy+yz=1\)의 최대·최소를 CAS와 승수법으로 구하라.',r'Find extrema of \(f=ye^{x-z}\) under \(9x^2+4y^2+36z^2=36,xy+yz=1\) using CAS and multipliers.',[r'승수계는 \((ye^{x-z},e^{x-z},-ye^{x-z})=\lambda(18x,8y,72z)+\mu(y,x+z,y)\)와 두 제약이다.','y≠0이므로 w=y(x−z)로 바꾸면 x=(1+w)/(2y),z=(1−w)/(2y). 제약 H=45w²−54w+45+16y⁴−144y²=0이며 정지조건은 (y−w)Hw−yHy=0.','w를 소거한 다항식: '+M(res)+'. 모든 실근에서 복원해 원래 제약과 정지식을 검사한다. 후보: '+'; '.join(f'({a:.6f},{b:.6f},{c:.6f}):{v:.6f}' for v,a,b,c in rows)],[r'The multiplier system is \((ye^{x-z},e^{x-z},-ye^{x-z})=\lambda(18x,8y,72z)+\mu(y,x+z,y)\) with both constraints.','Since y≠0, put w=y(x−z), giving x=(1+w)/(2y),z=(1−w)/(2y). Then H=45w²−54w+45+16y⁴−144y²=0, with stationarity (y−w)Hw−yHy=0.','Eliminating w gives '+M(res)+'. Recover all real-root candidates and check original constraints and stationarity: '+'; '.join(f'({a:.6f},{b:.6f},{c:.6f}):{v:.6f}' for v,a,b,c in rows)],f'최소{rows[0][0]:.6f} at {tuple(round(a,6) for a in rows[0][1:])}; 최대{rows[-1][0]:.6f} at {tuple(round(a,6) for a in rows[-1][1:])}.',f'Minimum{rows[0][0]:.6f} at {tuple(round(a,6) for a in rows[0][1:])}; maximum{rows[-1][0]:.6f} at {tuple(round(a,6) for a in rows[-1][1:])}.','제약집합은 타원면의 닫힌 부분으로 콤팩트하다. 소거다항식의 모든 실근을 복원하고 가짜근을 걸러 전역 비교했다.','The feasible set is a closed subset of an ellipsoid and compact. All real elimination roots were recovered, extraneous roots filtered, and values globally compared.')
A=4-z*z;B=A-z;C=16*B-A*(2*z+1)**2;poly=S.expand(C*C-64*B*B*z*z*A);rows=[]
for rt in S.nroots(poly,maxsteps=200):
 if abs(float(S.im(rt)))>1e-9:continue
 zz=float(S.re(rt));xx=float(C.subs(z,zz)/(8*B.subs(z,zz)*zz));yy=xx*(2*zz+1)/(2*(xx-zz));assert abs(xx*xx-yy*yy-zz)<1e-8 and abs(xx*xx+zz*zz-4)<1e-8;rows.append((xx+yy+zz,xx,yy,zz))
rows.sort();assert len(rows)==4
add(60,'f=x+y+z, 제약 x²−y²=z,x²+z²=4의 최대·최소를 CAS와 승수법으로 구하라.','Find extrema of f=x+y+z under x²−y²=z,x²+z²=4 using CAS and multipliers.',['승수식은 (1,1,1)=λ(2x,−2y,−1)+μ(2x,0,2z). 두 법선 외적과 목적기울기의 내적을0으로 놓으면2xy−2yz−2xz−x=0.','A=4−z²,B=4−z²−z,C=16B−A(2z+1)²로 두면 x=C/(8Bz), y=x(2z+1)/(2(x−z)).','제약으로 얻은 소거다항식 '+M(poly)+'의 모든 실근을 복원한다. 후보: '+'; '.join(f'({a:.6f},{b:.6f},{c:.6f}):{v:.6f}' for v,a,b,c in rows)],['The multiplier equation is (1,1,1)=λ(2x,−2y,−1)+μ(2x,0,2z). Orthogonality to the constraint-normal cross product gives2xy−2yz−2xz−x=0.','Let A=4−z²,B=4−z²−z,C=16B−A(2z+1)². Then x=C/(8Bz), y=x(2z+1)/(2(x−z)).','Recover all real roots of the elimination polynomial '+M(poly)+'. Candidates: '+'; '.join(f'({a:.6f},{b:.6f},{c:.6f}):{v:.6f}' for v,a,b,c in rows)],f'최소{rows[0][0]:.6f} at {tuple(round(a,6) for a in rows[0][1:])}; 최대{rows[-1][0]:.6f} at {tuple(round(a,6) for a in rows[-1][1:])}.',f'Minimum{rows[0][0]:.6f} at {tuple(round(a,6) for a in rows[0][1:])}; maximum{rows[-1][0]:.6f} at {tuple(round(a,6) for a in rows[-1][1:])}.','정지식에서 복원분모 z,B,x−z가0인 경우는 제약과 양립하지 않는다. 네 복원점의 제약 잔차는10⁻⁸ 미만이다.','Zero recovery denominators z,B,x−z are inconsistent with stationarity and constraints. All four recovered constraint residuals are below10⁻⁸.')
add(61,'f=3x²+y², 제약 x²+y²=4y의 최대·최소를 승수법으로 구하고 최소의 승수가0임을 보여라.','Find extrema of f=3x²+y² under x²+y²=4y by multipliers, and show the minimum has multiplier0.',['6x=2λx,2y=λ(2y−4). x=0이면 제약으로 y=0 또는4, 값0 또는16.','x≠0이면 λ=3, y=3,x=±√3, 값18.','최소점 (0,0)의 두 번째 승수식0=−4λ에서 λ=0이다.'],['Equations6x=2λx,2y=λ(2y−4). If x=0, then y=0 or4, with values0 or16.','If x≠0, λ=3, y=3,x=±√3, giving18.','At minimum point (0,0),0=−4λ forces λ=0.'],'최소0: (0,0), λ=0. 최대18: (±√3,3).','Minimum0 at (0,0), λ=0; maximum18 at (±√3,3).')
add(62,r'(a) \(\sum x_iy_i\)를 \(\sum x_i^2=\sum y_i^2=1\)에서 최대화하라. (b) 정규화 치환으로 Cauchy–Schwarz 부등식을 증명하라.',r'(a) Maximize \(\sum x_iy_i\) under \(\sum x_i^2=\sum y_i^2=1\). (b) Prove Cauchy–Schwarz by normalization.',[r'(a) 승수식 \(y_i=2\lambda x_i,x_i=2\mu y_i\). 단위 조건에서 λ=μ=±1/2, 목적값은±1이다. 최대1은 x=y에서 달성된다.',r'(b) 영벡터가 아니면 \(x_i=a_i/\sqrt{\sum a_j^2},y_i=b_i/\sqrt{\sum b_j^2}\)를 대입하고 두 양의 분모를 곱한다. 영벡터이면 양변0으로 자명하다.'],[r'(a) Multiplier equations are \(y_i=2\lambda x_i,x_i=2\mu y_i\). Unit constraints give λ=μ=±1/2 and values±1; maximum1 occurs at x=y.',r'(b) For nonzero vectors use \(x_i=a_i/\sqrt{\sum a_j^2},y_i=b_i/\sqrt{\sum b_j^2}\), then multiply by the positive denominators. A zero vector makes the inequality immediate.'],r'(a) 최대1. (b) \(\sum a_ib_i\le\sqrt{\sum a_i^2}\sqrt{\sum b_i^2}\).',r'(a) Maximum1. (b) \(\sum a_ib_i\le\sqrt{\sum a_i^2}\sqrt{\sum b_i^2}\).','−b도 적용하면 절댓값 형태를 얻고 등호는 선형종속에서 성립한다(위쪽 부등식은 같은 방향).','Applying the result to−b gives the absolute-value form; equality means linear dependence, with matching directions for the upper inequality.',['a','b'])
add(63,r'(a) 양수 xi의 합이 c일 때 \((x_1\cdots x_n)^{1/n}\)의 최대를 승수법으로 구하라. (b) 산술평균–기하평균 부등식과 등호조건을 도출하라.',r'(a) Maximize \((x_1\cdots x_n)^{1/n}\) for positive xi summing to c using multipliers. (b) Deduce AM–GM and its equality condition.', ['(a) 목적 f>0의 편미분은 f/(nxi). 승수식 f/(nxi)=λ에서 모든 xi가 같다.','합 제약으로 xi=c/n, f=c/n. 닫힌 단체로 연속 확장하면 경계 곱0이므로 내부 후보가 최대이다.','(b) c=Σxi를 대입한다. 유일한 내부 등호조건은 모든 수가 같음이다.'],['(a) Partial derivatives of positive f are f/(nxi); multiplier equations make all xi equal.','Thus xi=c/n and f=c/n. On the closed-simplex extension the boundary product is0, so the interior candidate is maximal.','(b) Substitute c=Σxi. Equality occurs precisely when all numbers coincide.'],r'\((x_1\cdots x_n)^{1/n}\le(x_1+\cdots+x_n)/n\), 등호는 모두 같을 때.',r'\((x_1\cdots x_n)^{1/n}\le(x_1+\cdots+x_n)/n\), with equality exactly when all numbers are equal.',parts=['a','b'])
E.sort(key=lambda a:a['number']);assert [a['number'] for a in E]==list(range(1,64))
D=dict(section='14.8',source=dict(title='Calculus',edition='9',language='en',printedPages=[1064,1065,1066],pdfPages=[1101,1102,1103]),scope=dict(kind='exercise',numbers=list(range(1,64)),total=63,note=pair('전체63문항과 모든 소문항. 다른 절 참조도 자급형 문제와 승수법 풀이로 전개.','All63 exercises and every subpart, including self-contained multiplier solutions to cross-referenced exercises.')),exercises=E)
(R/'exercise-content/s14-8.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n');print('14.8:63 cards; symbolic constraints and complete numerical elimination verified')
