from early_helpers import *
from math import sin,cos,sqrt,exp,pi
b=Book('14.2',[998,999])
def add(n,title,st,steps,ans,parts=[],check=None):b.add(n,998 if n<=44 else 999,title,st,steps,ans,parts,check=check)
add(1,('극한과 함수값','Limit versus value'),('극한이 '+r'\(\lim_{(x,y)\to(3,1)}f(x,y)=6\)'+'일 때 f(3,1)에 대해 무엇을 알 수 있는가? 연속이라면 어떠한가?','Given '+r'\(\lim_{(x,y)\to(3,1)}f(x,y)=6\)'+' what follows about f(3,1), and what changes if f is continuous?'),[('극한은 목표점 이외의 가까운 점에서 결정되므로 그 점의 함수값을 제한하지 않는다.','The limit is determined by nearby points other than the target, so it imposes no value at that point.'),('연속이면 함수값과 극한이 같아야 한다.','Continuity requires the value to equal the limit.')],('일반적으로 값은 임의이거나 정의되지 않을 수 있다. 연속이면 f(3,1)=6.','The value can be arbitrary or undefined in general; if continuous, f(3,1)=6.'))
add(2,('현상의 연속성','Continuity of physical models'),('(a) 경도·위도·시간에 따른 외기온도, (b) 같은 변수에 따른 지표 높이, (c) 거리·시간에 따른 택시요금이 연속인지 설명하라.','Discuss continuity of (a) outdoor temperature versus longitude, latitude, time; (b) elevation versus those variables; (c) taxi fare versus distance and time.'),[('(a) 보통의 연속적 온도 모형에서는 위치·시간의 작은 변화가 온도의 작은 변화를 준다.','(a) An ordinary continuous temperature model changes only slightly under small changes in location and time.'),('(b) 절벽을 이상화하면 수평 위치의 작은 변화에 높이가 급변하며 지진 같은 시간 변화도 고려해야 한다.','(b) Idealized cliffs can cause jumps under small horizontal displacements; events such as earthquakes can also introduce abrupt temporal changes.'),('(c) 미터기의 정해진 거리·시간 기준에서 요금이 일정 금액씩 뛰므로 계단형이다.','(c) A meter charges in fixed increments at distance or time thresholds, producing jumps.')],('(a) 통상 연속으로 모델링. (b) 절벽 등에서 불연속이 가능한 모형. (c) 요금이 올라가는 지점에서 불연속.','(a) Ordinarily modeled as continuous. (b) May be discontinuous at cliffs or abrupt events. (c) Discontinuous at fare-increment thresholds.'),['a','b','c'])
add(3,('수치표와 극한','Numerical evidence and a limit'),('원점 근처의 수치표로 극한을 예상하고 증명하라. '+r'\(f=(x^2y^3+x^3y^2-5)/(2-xy)\).','Use a numerical table near the origin to conjecture and prove the limit of '+r'\(f=(x^2y^3+x^3y^2-5)/(2-xy)\).'),[('t=0.1,0.01,0.001 순으로 f(t,t)≈-2.512553,-2.500125,-2.500001이고 f(t,-t)≈-2.487562,-2.499875,-2.499999이다. f(t,0)=-2.5이다.','For t=0.1,0.01,0.001, f(t,t)≈-2.512553,-2.500125,-2.500001 and f(t,-t)≈-2.487562,-2.499875,-2.499999. Also f(t,0)=-2.5.'),('분모는 원점에서 2≠0이고 분자·분모가 다항식이므로 대입으로 증명된다.','The denominator equals2 at the origin; polynomial continuity and the quotient law justify substitution.')],same(r'\[\lim_{(x,y)\to(0,0)}f(x,y)=-5/2.\]'))
add(4,('수치 경로가 보여 주는 불일치','Different numerical paths'),('원점 근처 표를 만들고 극한의 존재 여부를 설명하라. '+r'\(f=2xy/(x^2+2y^2)\).','Make a table near the origin and settle the limit for '+r'\(f=2xy/(x^2+2y^2)\).'),[('t=0.1,0.01,0.001의 각 행에서 f(t,0)=0, f(t,t)=2/3, f(t,2t)=4/9이다.','For each t=0.1,0.01,0.001, the table gives f(t,0)=0, f(t,t)=2/3, f(t,2t)=4/9.'),('서로 다른 경로에서 서로 다른 상수 극한이므로 단일 극한은 없다.','Distinct paths have different constant limits, so there is no single limit.')],('극한은 존재하지 않는다.','The limit does not exist.'))
limits=[
(5,r'x^2y^3-4y^2',r'(3,2)',r'3^2\cdot2^3-4\cdot2^2','56'),
(6,r'x^2y+3xy^2+4',r'(5,-2)',r'5^2(-2)+3(5)(-2)^2+4','14'),
(7,r'\frac{x^2y-xy^3}{x-y+2}',r'(-3,1)',r'\frac{9+3}{-3-1+2}','-6'),
(8,r'\frac{x^2y+xy^2}{x^2-y^2}',r'(2,-1)',r'\frac{-4+2}{4-1}','-2/3'),
(9,r'y\sin(x-y)',r'(\pi,\pi/2)',r'\frac\pi2\sin(\pi-\pi/2)',r'\pi/2'),
(10,r'e^{\sqrt{2x-y}}',r'(3,2)',r'e^{\sqrt{6-2}}',r'e^2'),
(11,r'\frac{x^2y^3-x^3y^2}{x^2-y^2}',r'(1,1)',r'\frac{x^2y^2(y-x)}{(x-y)(x+y)}=-\frac{x^2y^2}{x+y}',r'-1/2'),
(12,r'\frac{\cos y-\sin2y}{\cos x\cos y}',r'(\pi,\pi/2)',r'\frac{\cos y(1-2\sin y)}{\cos x\cos y}=\frac{1-2\sin y}{\cos x}','1'),
(19,r'(x^2y-xy^2+3)^3',r'(-1,-2)',r'[-2+4+3]^3','125'),
(20,r'e^{xy}\sin(xy)',r'(\pi,1/2)',r'e^{\pi/2}\sin(\pi/2)',r'e^{\pi/2}'),
(21,r'\frac{3x-2y}{4x^2-y^2}',r'(2,3)',r'\frac{6-6}{16-9}','0'),
(22,r'\frac{2x-y}{4x^2-y^2}',r'(1,2)',r'\frac{2x-y}{(2x-y)(2x+y)}=\frac1{2x+y}','1/4'),
(24,r'\frac{x^3-y^3}{x^2+xy+y^2}',r'(0,0)',r'\frac{(x-y)(x^2+xy+y^2)}{x^2+xy+y^2}=x-y','0'),
(25,r'\frac{x^2+y^2}{\sqrt{x^2+y^2+1}-1}',r'(0,0)',r'\frac{x^2+y^2}{\sqrt{x^2+y^2+1}-1}=\sqrt{x^2+y^2+1}+1','2')]
for n,f,pt,work,a in limits:
 add(n,('연속성과 약분으로 극한 계산','Limits by continuity and cancellation'),('극한을 구하라. '+r'\(\lim_{(x,y)\to'+pt+'}'+f+r'\).','Evaluate '+r'\(\lim_{(x,y)\to'+pt+'}'+f+r'\).'),fs(work)+[('원래 정의역에서 필요한 약분·유리화를 한 뒤 연속인 식에 목표점을 대입한다.','After any required cancellation or rationalization on the original domain, substitute into the resulting continuous expression.')],same(r'\[L='+a+r'.\]'))
paths=[
(13,r'\frac{y^2}{x^2+y^2}',r'(0,0)',r'y=0:\ f(x,0)=0',r'x=0:\ f(0,y)=1'),
(14,r'\frac{2xy}{x^2+3y^2}',r'(0,0)',r'y=0:\ f(x,0)=0',r'y=x:\ f(x,x)=1/2'),
(15,r'\frac{(x+y)^2}{x^2+y^2}',r'(0,0)',r'y=0:\ f(x,0)=1',r'y=x:\ f(x,x)=2'),
(16,r'\frac{x^2+xy^2}{x^4+y^2}',r'(0,0)',r'x=0:\ f(0,y)=0',r'y=x:\ f(x,x)=\frac{1+x}{1+x^2}\to1'),
(17,r'\frac{y^2\sin^2x}{x^4+y^4}',r'(0,0)',r'y=0:\ f(x,0)=0',r'y=x:\ f(x,x)=\frac{\sin^2x}{2x^2}\to1/2'),
(18,r'\frac{y-x}{1-y+\ln x}',r'(1,1)',r'y=x:\ f(x,x)=0',r'y=1:\ f(x,1)=\frac{1-x}{\ln x}\to-1'),
(23,r'\frac{xy^2\cos y}{x^2+y^4}',r'(0,0)',r'x=0:\ f(0,y)=0',r'x=y^2:\ f(y^2,y)=\cos y/2\to1/2'),
(26,r'\frac{xy^4}{x^2+y^8}',r'(0,0)',r'x=0:\ f(0,y)=0',r'x=y^4:\ f(y^4,y)=1/2'),
(28,r'\frac{xy+yz}{x^2+y^2+z^2}',r'(0,0,0)',r'(x,y,z)=(t,0,0):\ f=0',r'(x,y,z)=(t,t,0):\ f=1/2'),
(29,r'\frac{xy+yz^2+xz^2}{x^2+y^2+z^4}',r'(0,0,0)',r'(x,y,z)=(t,0,0):\ f=0',r'(x,y,z)=(t,t,0):\ f=1/2'),
(30,r'\frac{x^4+y^2+z^3}{x^4+2y^2+z}',r'(0,0,0)',r'(x,y,z)=(t,0,0):\ f=1',r'(x,y,z)=(0,t,0):\ f=1/2'),
(35,r'\frac{2x^2+3xy+4y^2}{3x^2+5y^2}',r'(0,0)',r'y=0:\ f(x,0)=2/3',r'x=0:\ f(0,y)=4/5'),
(36,r'\frac{xy^3}{x^2+y^6}',r'(0,0)',r'x=0:\ f(0,y)=0',r'x=y^3:\ f(y^3,y)=1/2')]
for n,f,pt,p1,p2 in paths:
 var='(x,y,z)'if n in[28,29,30]else'(x,y)';intro=('그래프를 사용해 극한이 없는 이유를 설명하라.','Use a graph to explain nonexistence of the limit.')if n in[35,36]else('극한이 존재하지 않음을 보이라.','Show that the limit does not exist.')
 add(n,('서로 다른 접근경로','Different approach paths'),(intro[0]+r'\(\lim_{'+var+r'\to'+pt+'}'+f+r'\).',intro[1]+r'\(\lim_{'+var+r'\to'+pt+'}'+f+r'\).'),fs(p1,p2)+[('두 경로가 같은 점에 접근하지만 극한값이 다르므로 전체 극한이 존재하지 않는다.','Both paths approach the same point but have distinct limits, so the full limit does not exist.')],('극한은 존재하지 않는다.','The limit does not exist.'))
add(27,('세 변수의 연속함수 극한','Continuous limit in three variables'),('극한을 구하라. '+r'\(\lim_{(x,y,z)\to(6,1,-2)}\sqrt{x+z}\cos(\pi y)\).','Evaluate '+r'\(\lim_{(x,y,z)\to(6,1,-2)}\sqrt{x+z}\cos(\pi y)\).'),[('목표점에서 제곱근 내부가4>0이므로 근방에서 연속이다.','The square-root argument is4>0 at the target, so the expression is continuous nearby.')]+fs(r'\sqrt{6-2}\cos\pi=-2'),same(r'\[L=-2.\]'))
squeezes=[(31,r'xy\sin\frac1{x^2+y^2}',r'(x,y)',r'|xy\sin(1/(x^2+y^2))|\le|xy|\le(x^2+y^2)/2\to0'),(32,r'\frac{xy}{\sqrt{x^2+y^2}}',r'(x,y)',r'\left|\frac{xy}{\sqrt{x^2+y^2}}\right|\le\frac{\sqrt{x^2+y^2}}2\to0'),(33,r'\frac{xy^4}{x^4+y^4}',r'(x,y)',r'\left|\frac{xy^4}{x^4+y^4}\right|\le|x|\to0'),(34,r'\frac{x^2y^2z^2}{x^2+y^2+z^2}',r'(x,y,z)',r'0\le\frac{x^2y^2z^2}{x^2+y^2+z^2}\le y^2z^2\to0')]
for n,f,var,ineq in squeezes:
 pt='(0,0,0)'if n==34 else'(0,0)';add(n,('조임정리','Squeeze theorem'),('조임정리로 계산하라. '+r'\(\lim_{'+var+r'\to'+pt+'}'+f+r'\).','Use the Squeeze Theorem: '+r'\(\lim_{'+var+r'\to'+pt+'}'+f+r'\).'),fs(ineq)+[('절댓값의 상한이 모든 경로에서0으로 가므로 원래 함수도0으로 간다.','The bound tends to zero uniformly over all approach paths, forcing the function to zero.')],same(r'\[L=0.\]'))
add(37,('합성함수의 연속영역','Continuity domain of a composition'),('합성함수 h=g∘f와 연속인 점들의 집합을 구하라. '+r'\(g(t)=t^2+\sqrt t,\ f(x,y)=2x+3y-6\).','Find h=g∘f and its continuity set for '+r'\(g(t)=t^2+\sqrt t,\ f(x,y)=2x+3y-6\).'),fs(r'h=(2x+3y-6)^2+\sqrt{2x+3y-6}',r'2x+3y-6\ge0'),same(r'\[h=(2x+3y-6)^2+\sqrt{2x+3y-6},\quad C=\{(x,y):2x+3y\ge6\}.\]'),check=('경계도 정의역에 상대적인 연속성에 포함된다.','The boundary is included when continuity is understood relative to the domain.'))
add(38,('로그 합성함수','Composition with a logarithm'),('합성함수 h=g∘f와 연속영역을 구하라. '+r'\(g(t)=t+\ln t,\ f(x,y)=(1-xy)/(1+x^2y^2)\).','Find h=g∘f and its continuity set for '+r'\(g(t)=t+\ln t,\ f(x,y)=(1-xy)/(1+x^2y^2)\).'),fs(r'1+x^2y^2>0,\quad f>0\iff xy<1',r'h=\frac{1-xy}{1+x^2y^2}+\ln\frac{1-xy}{1+x^2y^2}'),same(r'\[h=\frac{1-xy}{1+x^2y^2}+\ln\frac{1-xy}{1+x^2y^2},\quad C=\{(x,y):xy<1\}.\]'))
continuous=[
(39,r'e^{1/(x-y)}',r'x\ne y','x=y에서 식이 정의되지 않으며 x-y→0⁺에서는 무한대로, x-y→0⁻에서는0으로 간다.','The formula is undefined at x=y, diverges for x-y→0⁺, and tends to0 for x-y→0⁻.'),
(40,r'\frac1{1-x^2-y^2}',r'x^2+y^2\ne1','단위원 양쪽에서 분모가0으로 가므로 값이 발산한다.','The denominator tends to zero at the unit circle, producing divergent values on either side.'),
(41,r'\frac{xy}{1+e^{x-y}}',r'(x,y)\in\mathbb R^2','분모가 항상 양수이다.','The denominator is always positive.'),
(42,r'\cos\sqrt{1+x-y}',r'y\le1+x','제곱근은 내부가0이상일 때 연속이며 코사인과의 합성도 연속이다.','The square root is continuous on nonnegative inputs, as is its composition with cosine.'),
(43,r'\frac{1+x^2+y^2}{1-x^2-y^2}',r'x^2+y^2\ne1','분모가0인 단위원을 제외한다.','Exclude the unit circle, where the denominator vanishes.'),
(44,r'\frac{e^x+e^y}{e^{xy}-1}',r'xy\ne0','분모가0인 조건은 xy=0, 즉 두 좌표축이다.','The denominator vanishes precisely when xy=0, on the two coordinate axes.'),
(45,r'\sqrt x+\sqrt{1-x^2-y^2}',r'x\ge0,\quad x^2+y^2\le1','두 제곱근 내부가 모두0이상이어야 한다.','Both square-root arguments must be nonnegative.'),
(46,r'\ln(1+x-y)',r'y<1+x','로그 내부가 양수이어야 한다.','The logarithm requires a positive argument.'),
(47,r'\arcsin(x^2+y^2+z^2)',r'x^2+y^2+z^2\le1','제곱합은 비음수이므로 arcsin의 [-1,1] 조건은 제곱합≤1이다.','Since the sum of squares is nonnegative, the arcsine domain condition reduces to sum≤1.'),
(48,r'\sqrt{y-x^2}\ln z',r'y\ge x^2,\quad z>0','제곱근과 로그의 정의역 조건을 동시에 적용한다.','Apply both the square-root and logarithm domain restrictions.')]
for n,f,region,k,e in continuous:
 intro=('그래프를 그리고 불연속이 나타나는 곳을 식으로 설명하라.','Graph and explain the discontinuities from the formula.')if n<=40 else('연속인 점들의 집합을 구하라.','Find the set of points where the function is continuous.')
 add(n,('연속영역','Continuity set'),(intro[0]+r'\(f='+f+r'\).',intro[1]+r'\(f='+f+r'\).'),[(k,e),('정의역 안에서는 연속함수의 합성·곱·몫의 연속성을 적용한다.','On the domain, apply continuity of sums, compositions, products, and quotients.')],('다음 조건을 만족하는 모든 점에서 연속이다. '+r'\['+region+r'.\]','Continuous at all points satisfying '+r'\['+region+r'.\]'))
add(49,('정의한 값과 극한의 불일치','Mismatch between assigned value and limit'),('연속인 점들의 집합을 구하라. '+r'\(f(x,y)=x^2y^3/(2x^2+y^2)\)'+'는 원점 밖에서 정의되고 f(0,0)=1이다.','Find the continuity set for '+r'\(f(x,y)=x^2y^3/(2x^2+y^2)\)'+' away from the origin, with f(0,0)=1.'),fs(r'|f(x,y)|\le |y|^3/2\to0')+[('원점 극한0은 지정된 함수값1과 다르다. 원점 밖에서는 분모가 양수이다.','The limit0 differs from the assigned value1. Away from the origin the denominator is positive.')],same(r'\[C=\mathbb R^2\setminus\{(0,0)\}.\]'))
add(50,('경로에 따른 불연속','Path-dependent discontinuity'),('연속인 점들의 집합을 구하라. '+r'\(f(x,y)=xy/(x^2+xy+y^2)\)'+'는 원점 밖에서 정의되고 f(0,0)=0이다.','Find the continuity set for '+r'\(f(x,y)=xy/(x^2+xy+y^2)\)'+' away from the origin, with f(0,0)=0.'),fs(r'x^2+xy+y^2=(x+y/2)^2+3y^2/4>0\quad((x,y)\ne(0,0))',r'f(x,0)=0,\quad f(x,x)=1/3'),same(r'\[C=\mathbb R^2\setminus\{(0,0)\}.\]'))
for n,f,work,ans in[(51,r'\frac{x^3+y^3}{x^2+y^2}',r'f=r(\cos^3\theta+\sin^3\theta),\quad |f|\le2r\to0','0'),(52,r'(x^2+y^2)\ln(x^2+y^2)',r'f=r^2\ln(r^2);\quad t=r^2\to0^+,\quad\lim_{t\to0^+}t\ln t=0','0'),(53,r'\frac{e^{-x^2-y^2}-1}{x^2+y^2}',r'f=\frac{e^{-r^2}-1}{r^2}\to-1','-1')]:
 add(n,('극좌표로 극한 계산','Limit via polar coordinates'),('극좌표로 계산하라. '+r'\(\lim_{(x,y)\to(0,0)}'+f+r'\).','Use polar coordinates to evaluate '+r'\(\lim_{(x,y)\to(0,0)}'+f+r'\).'),fs(r'x=r\cos\theta,\quad y=r\sin\theta,\quad r\to0^+',work),same(r'\[L='+ans+r'.\]'))
add(54,('좌표함수의 극한 증명','Epsilon-delta coordinate limits'),('ε–δ 정의로 '+r'\(\lim_{(x,y)\to(a,b)}x=a,\ \lim_{(x,y)\to(a,b)}y=b,\ \lim_{(x,y)\to(a,b)}c=c\)'+'를 증명하라.','Prove from the epsilon-delta definition that '+r'\(\lim_{(x,y)\to(a,b)}x=a,\ \lim_{(x,y)\to(a,b)}y=b,\ \lim_{(x,y)\to(a,b)}c=c\)'+'.'),fs(r'|x-a|\le\sqrt{(x-a)^2+(y-b)^2},\quad |y-b|\le\sqrt{(x-a)^2+(y-b)^2}')+[('첫 두 식은 δ=ε로 증명된다. 상수함수는 |c-c|=0<ε이므로 임의의 δ>0을 택한다.','For the first two choose δ=ε. For the constant function |c-c|=0<ε, so any positive δ works.')],('세 극한 모두 성립한다.','All three limits hold.'))
add(55,('원형 sinc 곡면','Radial sinc surface'),('극좌표로 원점 극한을 확인하고 그려라. '+r'\(f=\sin(x^2+y^2)/(x^2+y^2)\).','Confirm the origin limit using polar coordinates and graph '+r'\(f=\sin(x^2+y^2)/(x^2+y^2)\).'),fs(r'f=\frac{\sin(r^2)}{r^2},\quad r\to0^+',r'\lim_{t\to0}\frac{\sin t}{t}=1'),same(r'\[\lim_{(x,y)\to(0,0)}f=1.\]'),check=('원점에서는 원래 식이 정의되지 않지만 값1로 연속 확장할 수 있다.','The original formula is undefined at the origin but extends continuously by assigning1.'))
add(56,('좌표축에서의 연속 확장','Continuous extension on coordinate axes'),('함수를 그리고 연속성을 논하라. '+r'\(f(x,y)=\sin(xy)/(xy)\ (xy\ne0),\quad f=1\ (xy=0)\).','Graph and discuss continuity of '+r'\(f(x,y)=\sin(xy)/(xy)\ (xy\ne0),\quad f=1\ (xy=0)\).'),[('sinc(t)=sin t/t를 t=0에서1로 정의하면 실수 전체에서 연속이다.','Defining sinc(t)=sin t/t as1 at t=0 makes it continuous on the real line.'),(r'\(f(x,y)=\operatorname{sinc}(xy)\)는 연속함수의 합성이다.',r'\(f(x,y)=\operatorname{sinc}(xy)\) is a composition of continuous functions.')],same(r'\[C=\mathbb R^2.\]'))
add(57,('좁은 띠를 놓치는 접근경로','Approach paths missing a narrow strip'),('함수 '+r'\(f=1\)'+'은 '+r'\(0<y<x^4\)'+'에서, 나머지에서는0이다. (a) '+r'\(y=mx^a,\ 0<a<4\)'+' 경로에서 원점 극한이0임을 보이고 (b) 원점 불연속, (c) 불연속인 두 곡선을 구하라.','Let '+r'\(f=1\)'+' on '+r'\(0<y<x^4\)'+' and0 elsewhere. (a) Show the origin limit along '+r'\(y=mx^a,\ 0<a<4\)'+' is0; (b) show discontinuity at the origin; (c) identify two complete discontinuity curves.'),[('(a) 경로가 실수로 정의되는 가지에서 m≤0이면 y≤0이다. m>0이면 |y|/x⁴=|m||x|^{a-4}→∞이므로 결국 띠 밖이다.','(a) On a real branch of the path, nonpositive y is outside the strip. For positive y, |y|/x⁴=|m||x|^{a-4}→∞, so the path is eventually above the strip.')]+fs(r'(b)\ y=x^4/2:\ f=1\quad(x\ne0);\qquad f(0,0)=0')+[('(c) y=0과 y=x⁴의 각 점은 값0인 경계에 있고 띠 안의 값1인 점들이 임의로 가깝다. 다른 점에서는 주변에서 상수이다.','(c) Every point of y=0 or y=x⁴ has value0, with points of value1 arbitrarily close. Elsewhere the function is locally constant.')],('(a) 경로극한0. (b) 원점 불연속. (c) 불연속 집합은 y=0 또는 y=x⁴.','(a) Path limit0. (b) Discontinuous at the origin. (c) The discontinuity set is y=0 or y=x⁴.'),['a','b','c'])
add(58,('노름 함수의 연속성','Continuity of the norm'),('함수 '+r'\(f(\mathbf x)=|\mathbf x|\)'+'가 '+r'\(\mathbb R^n\)'+' 전체에서 연속임을 보이라.','Show '+r'\(f(\mathbf x)=|\mathbf x|\)'+' is continuous on '+r'\(\mathbb R^n\)'+'.'),fs(r'\big||\mathbf x|-|\mathbf a|\big|\le|\mathbf x-\mathbf a|')+[('역삼각부등식에서 δ=ε를 택하면 모든 a에서 연속성 정의를 만족한다.','The reverse triangle inequality with δ=ε proves continuity at every a.')],('노름은 Lipschitz 상수1이며 모든 점에서 연속이다.','The norm is1-Lipschitz and continuous everywhere.'))
add(59,('내적 함수의 연속성','Continuity of a dot product'),('고정 벡터 c에 대해 '+r'\(f(\mathbf x)=\mathbf c\cdot\mathbf x\)'+'가 '+r'\(\mathbb R^n\)'+' 전체에서 연속임을 보이라.','For fixed c prove '+r'\(f(\mathbf x)=\mathbf c\cdot\mathbf x\)'+' is continuous on '+r'\(\mathbb R^n\)'+'.'),fs(r'|f(\mathbf x)-f(\mathbf a)|=|\mathbf c\cdot(\mathbf x-\mathbf a)|\le|\mathbf c|\,|\mathbf x-\mathbf a|')+[('c≠0이면 δ=ε/|c|를 택한다. c=0이면 함수가 상수0이므로 자명하다.','For c≠0 choose δ=ε/|c|. For c=0 the function is identically zero.')],('모든 점에서 연속이다.','It is continuous everywhere.'))
# Radial graphs retain the directional limit differences at the puncture.
b.plot(35,[(lambda u,v:(u*cos(v),u*sin(v),(2*cos(v)**2+3*cos(v)*sin(v)+4*sin(v)**2)/(3*cos(v)**2+5*sin(v)**2)),(.025,1),(0,2*pi),'Different heights along different angles')])
b.plot(36,[(lambda u,v:(u,v,u*v**3/(u*u+v**6) if u*u+v**6 else 0),(-1,1),(-1,1),'Approach x=0:0; approach x=y³:1/2')])
b.plot(39,[([lambda u,v:(v+u,v,exp(1/u)),lambda u,v:(v-u,v,exp(-1/u))],(.3,2),(-1,1),'The missing line x=y')])
b.plot(40,[(lambda u,v:(u*cos(v),u*sin(v),1/(1-u*u)),(0,.9),(0,2*pi),'Inside unit circle'),(lambda u,v:(u*cos(v),u*sin(v),1/(1-u*u)),(1.1,2),(0,2*pi),'Outside unit circle')])
b.plot(55,[(lambda u,v:(u*cos(v),u*sin(v),sin(u*u)/(u*u) if u else 1),(0,4),(0,2*pi),'sin(r²)/r²; center limit1')])
b.plot(56,[(lambda u,v:(u,v,sin(u*v)/(u*v) if u*v else 1),(-4,4),(-4,4),'Continuous sinc(xy)')])
assert sorted(b.E)==list(range(1,60));b.save();print('14.2:59 complete')
