import sympy as S,json,math
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=[];pair=lambda a,b:dict(ko=a,en=b)
def add(n,k,e,ks,es,ka,ea,kc='정의역, 경계, 등호 성립 조건을 독립 확인했다.',ec='Domains, boundaries, and equality conditions were independently checked.',parts=[]):
 pg=1073 if n<=6 else 1074
 E.append(dict(id=f'stewart9-problems-plus-14.10-{n}',number=n,subparts=parts,source=dict(printedPage=pg,pdfPage=pg+37),topic=pair('14장 심화 문제','Chapter14 Problems Plus'),statement=pair(k,e),hint=pair('원래 조건에 맞는 정의역을 정하고 대칭·미분·부등식을 결합한다.','Respect the original domain and combine symmetry, derivatives, and inequalities.'),steps=pair(ks,es),answer=pair(ka,ea),check=pair(kc,ec),conceptHref='../s14-8.html',status='math-verified'))
add(1,'길이L,폭W 직사각형을 변에 평행한 두 선으로 네 직사각형으로 나눈다. 네 넓이 제곱합의 최대·최소를 구하라.','Cut an L-by-W rectangle into four rectangles with two lines parallel to its sides. Find extrema of the sum of squared subareas.',['절단 위치 x,y에서 제곱합은 [x²+(L−x)²][y²+(W−y)²]로 인수분해된다.','각 인수는 중심 x=L/2,y=W/2에서 최소 L²/2,W²/2. 경계 x=0 또는L,y=0 또는W에서는 최대 L²,W².','네 부분 모두 양의 넓이를 요구하면 절단 위치는 열린 구간이다. 이 경우 최대값은 달성되지 않고 경계에 다가갈 때의 상한만 있다.'],['For cuts at x,y, the sum factors as[x²+(L−x)²][y²+(W−y)²].','Each factor is minimized at its midpoint, with values L²/2,W²/2; on endpoints the factors reach L²,W².','If all four pieces must have positive area, cuts lie in open intervals. The maximum is then unattained, with only a limiting supremum.'],'최소L²W²/4: 중앙 절단. 퇴화 허용 최대L²W²: 꼭짓점 절단; 네 양의 조각 조건에서는 최대 없음, 상한L²W².','Minimum L²W²/4 at midpoint cuts. Allowing degeneracy, maximum L²W² at corner cuts; with four positive pieces there is no maximum, only supremum L²W².')
add(2,r'상어는 농도 \(C=e^{-(x^2+2y^2)/10^4}\)가 가장 빨리 증가하는 방향으로 헤엄친다. (a) 등위곡선과 경로를 그리고 (b) (x₀,y₀)에서 출발한 경로의 미분방정식을 풀라.',r'A shark follows steepest increase of \(C=e^{-(x^2+2y^2)/10^4}\). (a) Sketch contours and a path; (b) solve the path differential equation from(x₀,y₀).',[r'(a) C=c는 \(x^2+2y^2=-10^4\ln c\),0<c≤1의 타원이다. 기울기는 \((-2xC,-4yC)/10^4\)로 원점 쪽이다.',r'(b) x≠0에서 \(dy/dx=C_y/C_x=2y/x\). 분리하면 y=Ax²이고 A=y₀/x₀²이다.',r'모든 축 경우를 포함하는 방향 매개화는 \(x=x_0e^{-s},y=y_0e^{-2s},s\ge0\). s는 실제 시간으로 고정하지 않은 경로 매개변수이다.'],[r'(a) Level C=c is \(x^2+2y^2=-10^4\ln c\),0<c≤1, an ellipse. The gradient \((-2xC,-4yC)/10^4\) points inward.',r'(b) For x≠0, \(dy/dx=C_y/C_x=2y/x\), yielding y=Ax² with A=y₀/x₀².',r'A parametrization covering axial cases is \(x=x_0e^{-s},y=y_0e^{-2s},s\ge0\); s is a path parameter, not specified physical time.'],r'x₀≠0: \(y=(y_0/x_0^2)x^2\), 출발점에서 원점 쪽 부분. x₀=0: y축을 따라 원점으로.',r'For x₀≠0: \(y=(y_0/x_0^2)x^2\), the segment from the initial point toward the origin. For x₀=0 follow the y-axis inward.','매개경로 접벡터(−x,−2y)는 농도 기울기의 양의 배수이므로 방향이 일치한다.','The path tangent(−x,−2y) is a positive multiple of the concentration gradient.',['a','b'])
add(3,'폭w의 금속판을 밑면w−2x와 같은 길이x의 두 옆면을 갖는 대칭 사다리꼴 홈통으로 굽힌다. 옆면은 수평과각θ를 이룬다. (a) 단면적 최대 치수 (b) 반원형 홈통과 비교하라.','Bend a width-w sheet into a symmetric trapezoidal gutter with base w−2x and side lengths x at angleθ to horizontal. (a) Maximize cross-sectional area; (b) compare a semicircular gutter.',[r'(a) 높이 xsinθ, 윗폭 w−2x+2xcosθ이므로 \(A=x\sin\theta[w-(2-\cos\theta)x]\).','고정 θ에서 x=w/[2(2−cosθ)], 최대면적 w²sinθ/[4(2−cosθ)]. θ미분의 부호는2cosθ−1이므로 θ=π/3.','따라서 x=w/3,밑면w/3,높이√3w/6,면적√3w²/12.','(b) 반원에서는 πr=w로 면적πr²/2=w²/(2π), 이는√3w²/12보다 크다.'],[r'(a) Height xsinθ and top width w−2x+2xcosθ give \(A=x\sin\theta[w-(2-\cos\theta)x]\).','For fixedθ, x=w/[2(2−cosθ)], giving area w²sinθ/[4(2−cosθ)]. Its angular derivative has sign2cosθ−1, so θ=π/3.','Thus x=w/3,base w/3,height√3w/6,and area√3w²/12.','(b) For a semicircle πr=w and area w²/(2π), exceeding√3w²/12.'],'(a) 세 금속 변 모두w/3, θ=60°, 면적√3w²/12. (b) 반원 면적w²/(2π)가 더 크다.','(a) All three metal segments have lengthw/3, θ=60°, area√3w²/12. (b) Semicircular area w²/(2π) is larger.',parts=['a','b'])
add(4,r'원점 밖에서는 \(f=(x+y+z)^r/(x^2+y^2+z^2)\), 원점에서는0이다. R³ 전체에서 연속이 되는 지수를 조사하라.',r'Let \(f=(x+y+z)^r/(x^2+y^2+z^2)\) off the origin and f=0 at the origin. Determine exponents giving continuity on R³.',[r'ρ=√(x²+y²+z²)라 하면 Cauchy–Schwarz로 \(|x+y+z|\le\sqrt3\rho\). 실수 거듭제곱이 정의되면 \(|f|\le3^{r/2}\rho^{r-2}\)이므로 r>2에서 원점 연속.',r'y=z=0,x>0의 경로에서는 f=x^(r−2)이므로 r≤2이면0으로 수렴하지 않는다.','추가 정의역 조건: x+y+z가 음수도 취하므로 임의의 실수 r에 대해 원래 거듭제곱이 실수값인 것은 아니다. 통상 정수 지수이면 r≥3; 기약 유리수의 홀수 분모에 의한 실수 거듭제곱이면 r>2가 필요충분이다.'],[r'Let ρ=√(x²+y²+z²). Cauchy–Schwarz gives \(|x+y+z|\le\sqrt3\rho\); wherever the real power is defined, \(|f|\le3^{r/2}\rho^{r-2}\), proving origin continuity for r>2.',r'Along y=z=0,x>0, f=x^(r−2), which fails to tend to0 for r≤2.','There is also a domain condition: x+y+z can be negative, so arbitrary real powers need not be real-valued. For integer exponents the answer is r≥3; for reduced rational powers with odd denominator, r>2 is necessary and sufficient.'],'원점 극한 조건 r>2. R³의 실수값 원래식을 요구하면 음의 밑에 정의되는 지수도 필요; 정수 지수에서는3,4,5,… .','The origin limit requires r>2. A real-valued formula on all R³ also requires powers defined for negative bases; for integer exponents:3,4,5,… .','원점 연속 조건과 식이 R³ 전체에서 정의되는 조건을 구분했다.','The origin limit condition is distinguished from being defined on all R³.')
add(5,'f가 미분가능할 때 z=xf(y/x)의 모든 접평면이 공통점을 지남을 보여라.','For differentiable f, prove all tangent planes to z=xf(y/x) share a point.',['q=y/x로 두면 zx=f(q)−qf′(q),zy=f′(q).','따라서 xzx+yzy=xf(q)=z. 기준점(a,b,z₀)의 접평면 z−z₀=zx(x−a)+zy(y−b)에서 상수항이 소거된다.'],['With q=y/x, zx=f(q)−qf′(q),zy=f′(q).','Thus xzx+yzy=z. In the tangent plane at(a,b,z₀), the constant term cancels by this identity.'],'모든 접평면은 원점(0,0,0)을 지난다.','Every tangent plane contains(0,0,0).','x≠0인 곡면의 정칙 그래프점에서 적용한다. 원점 자체가 곡면 정의역에 없어도 접평면은 원점을 지난다.','Apply at graph points with x≠0. The origin need not belong to the surface domain for all tangent planes to contain it.')
x,y=S.symbols('x y',positive=True);F=x**x+y**y-1000;G=x**y+y**x-100;J=S.Matrix([F,G]).jacobian([x,y]);rows=[];history=[]
for start in [(S.Float(2,40),S.Float(4.5,40)),(S.Float(4.5,40),S.Float(2,40))]:
 pt=S.Matrix(start);hist=[]
 for i in range(12):
  sub={x:pt[0],y:pt[1]};fv=S.Matrix([F,G]).subs(sub).evalf(40);err=max(abs(float(a)) for a in fv);hist.append((i,float(pt[0]),float(pt[1]),err))
  if err<1e-28:break
  pt=(pt-J.subs(sub).evalf(40).inv()*fv).evalf(40)
 assert max(abs(float(a)) for a in S.Matrix([F,G]).subs({x:pt[0],y:pt[1]}))<1e-20
 rows.append(tuple(float(a) for a in pt));history.append(hist)
add(6,r'(a) f(x,y)=0,g(x,y)=0의 두 접평면을 이용해 2변수 Newton 갱신식을 유도하라. (b) \(x^x+y^y=1000,x^y+y^x=100\)의 양의 교점을 소수 여섯째 자리까지 구하라.',r'(a) Derive the two-variable Newton update from tangent planes for f(x,y)=g(x,y)=0. (b) Find positive intersections of \(x^x+y^y=1000,x^y+y^x=100\) to six decimal places.',[r'(a) 두 선형화 f+fxΔx+fyΔy=0,g+gxΔx+gyΔy=0을 푼다. \(D=f_xg_y-f_yg_x\ne0\)이면 \(\Delta x=-(fg_y-f_yg)/D,\Delta y=-(f_xg-fg_x)/D\).',r'(b) \(f_x=x^x(\ln x+1), f_y=y^y(\ln y+1),g_x=yx^{y-1}+y^x\ln y,g_y=x^y\ln x+xy^{x-1}\).','초깃값(2,4.5)와 대칭점에서 직접 Newton 반복을 수행한다. 첫 경로: '+'; '.join(f'{i}:({a:.9f},{b:.9f}),residual={err:.2e}' for i,a,b,err in history[0])],[r'(a) Solve f+fxΔx+fyΔy=0,g+gxΔx+gyΔy=0. If \(D=f_xg_y-f_yg_x\ne0\), then \(\Delta x=-(fg_y-f_yg)/D,\Delta y=-(f_xg-fg_x)/D\).',r'(b) \(f_x=x^x(\ln x+1), f_y=y^y(\ln y+1),g_x=yx^{y-1}+y^x\ln y,g_y=x^y\ln x+xy^{x-1}\).','Run Newton iterations from(2,4.5) and its symmetric point. First trajectory: '+'; '.join(f'{i}:({a:.9f},{b:.9f}),residual={err:.2e}' for i,a,b,err in history[0])],r'(a) \(x_{n+1}=x_n+\Delta x,y_{n+1}=y_n+\Delta y\). (b) '+', '.join(f'({a:.6f},{b:.6f})' for a,b in rows)+'.',r'(a) \(x_{n+1}=x_n+\Delta x,y_{n+1}=y_n+\Delta y\). (b) '+', '.join(f'({a:.6f},{b:.6f})' for a,b in rows)+'.','40자리 연산으로 원래 두 방정식 잔차10⁻²⁰ 미만을 확인했다. 양의 좌표에서 수행하며 반복 중 야코비안은 비특이였다.','At40-digit precision, both original residuals are below10⁻²⁰. Iteration used positive coordinates and nonsingular Jacobians.',['a','b'])
add(7,'타원 x²/a²+y²/b²=1이 원 x²+y²=2y를 감쌀 때 타원 넓이를 최소화하는 a,b>0을 구하라.','Find a,b>0 minimizing the area of x²/a²+y²/b²=1 while enclosing the circle x²+y²=2y.',['원의 두 점(±√3/2,3/2)을 포함해야 하므로3/(4a²)+9/(4b²)≤1.','AM–GM으로 그 좌변≥3√3/(2ab), 따라서 ab≥3√3/2. 등호는 a²=3/2,b²=9/2에서 가능하다.','이 타원에서 원둘레의 x²=2y−y²를 대입하면 x²/a²+y²/b²=1−4(y−3/2)²/9≤1이므로 원 전체를 포함한다.'],['Containing the circle points(±√3/2,3/2) requires3/(4a²)+9/(4b²)≤1.','AM–GM bounds the left side below by3√3/(2ab), hence ab≥3√3/2. Equality is possible at a²=3/2,b²=9/2.','For that ellipse, substituting x²=2y−y² along the circle gives1−4(y−3/2)²/9≤1, proving the entire circle is enclosed.'],'a=√(3/2),b=3/√2, 최소넓이3√3π/2.','a=√(3/2),b=3/√2; minimum area3√3π/2.')
add(8,r'\(f=(ax+by+c)^2/(x^2+y^2+1)\)의 상한과 최대값 존재 여부를 조사하라(교재는 최대값이 a²+b²+c²라고 주장한다).',r'Investigate the upper bound and attainment for \(f=(ax+by+c)^2/(x^2+y^2+1)\); the source claims the maximum is a²+b²+c².',[r'Cauchy–Schwarz를 (a,b,c),(x,y,1)에 적용하면 \((ax+by+c)^2\le(a^2+b^2+c^2)(x^2+y^2+1)\).','c≠0이면 두 벡터가 평행한 (x,y)=(a/c,b/c)에서 등호가 성립한다.','c=0,(a,b)≠(0,0)이면 세 번째 성분 때문에 평행할 수 없어 유한 점에서 등호가 불가능하다. (x,y)=t(a,b), |t|→∞에서 f→a²+b²로 상한만 달성한다. a=b=c=0이면 f≡0.'],[r'Cauchy–Schwarz for(a,b,c),(x,y,1) gives \((ax+by+c)^2\le(a^2+b^2+c^2)(x^2+y^2+1)\).','If c≠0, equality holds at(x,y)=(a/c,b/c).','If c=0 and(a,b)≠(0,0), the third coordinate prevents parallelism and finite attainment. Along(x,y)=t(a,b), |t|→∞, f→a²+b², giving only the supremum. If a=b=c=0, f≡0.'],'항상 상한a²+b²+c². c≠0이면 최대이며 (a/c,b/c)에서 달성. c=0,(a,b)≠(0,0)이면 최대 없음. 모두0이면 최대0.','The supremum is always a²+b²+c². If c≠0 it is a maximum at(a/c,b/c). If c=0 and(a,b)≠(0,0), no maximum exists. If all are0, the maximum is0.','교재의 최대값 주장에는 c=0의 비영(a,b) 예외가 필요하다.','The source’s maximum claim requires an exception when c=0 with nonzero(a,b).')
D=dict(section='14.10',source=dict(title='Calculus',edition='9',language='en',printedPages=[1073,1074],pdfPages=[1110,1111]),scope=dict(kind='problems-plus',numbers=list(range(1,9)),total=8,note=pair('Chapter14 Problems Plus 전체8문항과 모든 소문항.','All8 Chapter14 Problems Plus exercises and every subpart.')),exercises=E)
(R/'exercise-content/s14-10.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n');print('Chapter14 Problems Plus:8 cards; Newton residuals verified')
(R/'exercise-checks/s14-10-newton-report.json').write_text(json.dumps(dict(roots=rows,iterations=history),indent=2)+'\n')
