import sympy as S,json,math
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=[]
x,y,z,s,t,r,u,v,w,p,q,a,b,c,th=S.symbols('x y z s t r u v w p q alpha beta gamma theta',real=True)
la=lambda e:S.latex(S.simplify(e));pair=lambda k,e:dict(ko=k,en=e)
def add(n,st,sk,se,ak,ae,ck,ce,parts=[]):
 pg=1029 if n<=17 else 1030 if n<=41 else 1031 if n<=56 else 1032
 E.append(dict(id=f'stewart9-exercise-14.5-{n}',number=n,subparts=parts,source=dict(printedPage=pg,pdfPage=pg+37),topic=pair('연쇄법칙과 음함수미분','Chain rule and implicit differentiation'),statement=pair(*st),hint=pair('각 의존 경로의 미분을 곱하고 모든 경로를 더한다.','Multiply derivatives along each dependency path, then sum all paths.'),steps=pair(sk,se),answer=pair(ak,ae),check=pair(ck,ce),conceptHref='../s14-5.html',status='math-verified'))
def chain(n,name,F,vars,subs,outer,point=None,both=False):
 mapping=dict(zip(vars,subs));comp=F.subs(mapping,simultaneous=True);der=[];sk=[];se=[]
 for var in outer:
  terms=[S.diff(F,j).subs(mapping,simultaneous=True)*S.diff(k,var) for j,k in zip(vars,subs)];d=S.simplify(sum(terms));direct=S.diff(comp,var);assert S.simplify(d-direct)==0
  eq=' + '.join('('+la(term)+')' for term in terms)
  sk.append(f'\\({name}_{la(var)}={eq}={la(d)}\\).');se.append(f'\\({name}_{la(var)}={eq}={la(d)}\\).')
  der.append(S.simplify(d.subs(point)) if point else d)
 data=',\\quad '.join(la(j)+'='+la(k) for j,k in zip(vars,subs));goal=','.join(la(v) for v in outer)
 st=(f'\\({name}={la(F)};\quad {data}\\). {goal}에 대한 미분을 '+('두 방법(연쇄법칙, 직접 대입)으로 구하라.' if both else '연쇄법칙으로 구하라.'),f'\\({name}={la(F)};\quad {data}\\). Find derivatives with respect to {goal} '+('by both chain rule and direct substitution.' if both else 'by the chain rule.'))
 if point:ps=', '.join(la(j)+'='+la(vv) for j,vv in point.items());st=(st[0]+f' \\({ps}\\)에서 평가하라.',st[1]+f' Evaluate at \\({ps}\\).')
 if both:sk.append(f'직접 대입식은 \\({name}={la(comp)}\\). 이를 미분하면 같은 결과이다.');se.append(f'Direct substitution gives \\({name}={la(comp)}\\); differentiating yields the same result.')
 if point:sk.append('마지막에 지정된 기준점 값을 대입한다.');se.append('Finally substitute the specified evaluation point.')
 ans='\\('+',\\quad '.join(name+'_{'+la(var)+'}='+la(d) for var,d in zip(outer,der))+'\\).'
 add(n,st,sk,se,ans,ans,'합성함수를 먼저 대입한 뒤 기호 미분한 결과와 연쇄법칙 결과의 차이가0임을 검사했다. 식은 원래 함수와 모든 미분이 정의되는 영역에서 적용한다.','Symbolic differentiation after direct substitution agrees identically with the chain-rule result. Use the formulas where the original functions and derivatives are defined.')
rows=[(1,'z',x*x*y+x*y*y,[x,y],[3*t,t*t],[t],True),(2,'z',x*y*S.exp(y),[x,y],[t*t,5*t],[t],True),(3,'z',x*y**3-x*x*y,[x,y],[t*t+1,t*t-1],[t],False),(4,'z',(x-y)/(x+2*y),[x,y],[S.exp(S.pi*t),S.exp(-S.pi*t)],[t],False),(5,'z',S.sin(x)*S.cos(y),[x,y],[S.sqrt(t),1/t],[t],False),(6,'z',S.sqrt(1+x*y),[x,y],[S.tan(t),S.atan(t)],[t],False),(7,'w',x*S.exp(y/z),[x,y,z],[t*t,1-t,1+2*t],[t],False),(8,'w',S.log(S.sqrt(x*x+y*y+z*z)),[x,y,z],[S.sin(t),S.cos(t),S.tan(t)],[t],False),(9,'z',x*x+y*y,[x,y],[2*s+3*t,s+t],[s,t],True),(10,'z',x*x*S.sin(y),[x,y],[s*s*t,s*t],[s,t],True),(11,'z',(x-y)**5,[x,y],[s*s*t,s*t*t],[s,t],False),(12,'z',S.atan(x*x+y*y),[x,y],[s*S.log(t),t*S.exp(s)],[s,t],False),(13,'z',S.log(3*x+2*y),[x,y],[s*S.sin(t),t*S.cos(s)],[s,t],False),(14,'z',S.sqrt(x)*S.exp(x*y),[x,y],[1+s*t,s*s-t*t],[s,t],False),(15,'z',S.sin(th)/r,[r,th],[s*t,s*s+t*t],[s,t],False),(16,'z',S.tan(u/v),[u,v],[2*s+3*t,3*s-2*t],[s,t],False)]
for n,name,F,vs,sub,ov,both in rows:chain(n,name,F,vs,sub,ov,both=both)
add(17,('p(t)=f(g(t),h(t)), g(2)=4,g′(2)=−3,h(2)=5,h′(2)=6,fx(4,5)=2,fy(4,5)=8이다. p′(2)를 구하라.','For p(t)=f(g(t),h(t)), g(2)=4,g′(2)=−3,h(2)=5,h′(2)=6,fx(4,5)=2,fy(4,5)=8. Find p′(2).'),['p′=fx g′+fy h′이며 f의 미분은 (g(2),h(2))=(4,5)에서 평가한다.','p′(2)=2(−3)+8(6)=42.'],['Use p′=fx g′+fy h′, evaluating f derivatives at(g(2),h(2))=(4,5).','p′(2)=2(−3)+8(6)=42.'],'42.','42.','각 미분의 평가점과 합성 순서를 확인했다.','Evaluation points and composition order were checked.')
add(18,('R(s,t)=G(u(s,t),v(s,t)). (1,2)에서 u=5,us=4,ut=−3,v=7,vs=2,vt=6이고 Gu(5,7)=9,Gv(5,7)=−2이다. Rs,Rt를 구하라.','R(s,t)=G(u(s,t),v(s,t)). At(1,2):u=5,us=4,ut=−3,v=7,vs=2,vt=6, and Gu(5,7)=9,Gv(5,7)=−2. Find Rs,Rt.'),['Rs=Gu us+Gv vs=9·4−2·2=32.','Rt=Gu ut+Gv vt=9(−3)−2·6=−39.'],['Rs=Gu us+Gv vs=9·4−2·2=32.','Rt=Gu ut+Gv vt=9(−3)−2·6=−39.'],'Rs(1,2)=32,Rt(1,2)=−39.','Rs(1,2)=32,Rt(1,2)=−39.','두 결과는 G의 행벡터(9,−2)와 안쪽 함수 야코비안의 곱이다.','These are the product of G’s derivative row(9,−2) and the inner Jacobian.')
add(19,(r'\(g(u,v)=f(e^u+\sin v,e^u+\cos v)\). 표의 (f,g,fx,fy)는 (0,0)에서(3,6,4,8), (1,2)에서(6,3,2,5)이다. gu(0,0),gv(0,0)를 구하라.',r'For \(g(u,v)=f(e^u+\sin v,e^u+\cos v)\), the table lists(f,g,fx,fy)=(3,6,4,8) at(0,0) and(6,3,2,5) at(1,2). Find gu(0,0),gv(0,0).'),['(u,v)=(0,0)은 안쪽 좌표(x,y)=(1,2)로 간다. 따라서 fx=2,fy=5를 사용한다.','gu=2·1+5·1=7, gv=2·1+5·0=2.'],['The inner coordinates at(u,v)=(0,0) are(x,y)=(1,2), so use fx=2,fy=5.','gu=2·1+5·1=7, gv=2·1+5·0=2.'],'gu=7,gv=2.','gu=7,gv=2.','f의(0,0)행을 잘못 사용하는 것을 피하고 합성함수의 실제 입력을 대조했다.','The actual input to f is(1,2), not the(0,0) row.')
add(20,(r'\(g(r,s)=f(2r-s,s^2-4r)\). f의 (0,0)에서 fx=4,fy=8이다. gr(1,2),gs(1,2)를 구하라.',r'For \(g(r,s)=f(2r-s,s^2-4r)\), f has fx=4,fy=8 at(0,0). Find gr(1,2),gs(1,2).'),['(r,s)=(1,2)에서 안쪽 입력은(0,0).','gr=2fx−4fy=−24, gs=−fx+2s fy=28.'],['The inner input at(r,s)=(1,2) is(0,0).','gr=2fx−4fy=−24, gs=−fx+2s fy=28.'],'gr=−24,gs=28.','gr=−24,gs=28.','안쪽 두 함수의 미분행렬로 같은 결과를 얻는다.','The inner Jacobian gives the same result.')
trees=[]
for n,name,inners,outers in [(21,'u',['x','y'],['r','s','t']),(22,'w',['x','y','z'],['u','v']),(23,'T',['p','q','r'],['x','y','z']),(24,'R',['t','u'],['w','x','y','z'])]:
 formula=';\\quad '.join(name+'_'+ov+'='+ '+'.join(name+'_'+iv+'\\,'+iv+'_'+ov for iv in inners) for ov in outers)
 add(n,(f'{name}는 {",".join(inners)}의 함수이고 각 중간변수는 {",".join(outers)}에 의존한다. 나무도표를 그리고 모든 연쇄법칙 식을 쓰라.',f'{name} depends on {",".join(inners)}, each depending on {",".join(outers)}. Draw a dependency tree and write all chain rules.'),[f'꼭대기 {name}에서 각 중간변수로 가지를 내고 각 중간변수에서 모든 입력변수로 가지를 낸다.','같은 최하위 변수에 이르는 경로마다 두 미분을 곱한 뒤 더한다.'],[f'Branch from {name} to each intermediate variable, and from each intermediate to every input.','For each terminal input, multiply derivatives along each path and sum.'],f'\\({formula}\\).',f'\\({formula}\\).','각 식의 항 수는 중간변수 수와 같다.','Each derivative has one term per intermediate variable.');trees.append((n,name,inners,outers))
for args in [(25,'z',x**4+x*x*y,[x,y],[s+2*t-u,s*t*u*u],[s,t,u],{s:4,t:2,u:1}),(26,'T',v/(2*u+v),[u,v],[p*q*S.sqrt(r),p*S.sqrt(q)*r],[p,q,r],{p:2,q:1,r:4}),(27,'w',x*y+y*z+z*x,[x,y,z],[r*S.cos(th),r*S.sin(th),r*th],[r,th],{r:2,th:S.pi/2}),(28,'P',S.sqrt(u*u+v*v+w*w),[u,v,w],[x*S.exp(y),y*S.exp(x),S.exp(x*y)],[x,y],{x:0,y:2}),(29,'N',(p+q)/(p+r),[p,q,r],[u+v*w,v+u*w,w+u*v],[u,v,w],{u:2,v:3,w:4}),(30,'U',x*S.exp(t*y),[x,y,t],[a*a*b,b*b*c,c*c*a],[a,b,c],{a:-1,b:2,c:1})]:chain(*args)
for n,F in [(31,y*S.cos(x)-x*x-y*y),(32,S.cos(x*y)-1-S.sin(y)),(33,S.atan(x*x*y)-x-x*y*y),(34,S.exp(y)*S.sin(x)-x-x*y),(35,x*x+2*y*y+3*z*z-1),(36,x*x-y*y+z*z-2*z-4),(37,S.exp(z)-x*y*z),(38,y*z+x*S.log(y)-z*z)]:
 dep=y if n<=34 else z;ind=[x] if n<=34 else [x,y];den=S.diff(F,dep);ans=';\\quad '.join(f'{la(dep)}_{la(j)}={la(-S.diff(F,j)/den)}' for j in ind)
 add(n,(f'\\({la(F)}=0\\)에서 '+('dy/dx' if n<=34 else 'zx,zy')+'를 음함수미분으로 구하라.',f'For \\({la(F)}=0\\), find '+('dy/dx' if n<=34 else 'zx,zy')+' by implicit differentiation.'),[f'좌변을 F라 쓰고 \\(F_{la(dep)}={la(den)}\\)를 계산한다.',f'각 독립변수 j에 대해 \\({la(dep)}_j=-F_j/F_{la(dep)}\\)를 적용한다.'],[f'Call the left side F; its dependent-variable derivative is \\(F_{la(dep)}={la(den)}\\).',f'For each independent variable j, use \\({la(dep)}_j=-F_j/F_{la(dep)}\\).'],f'\\({ans}\\), \\({la(den)}\\ne0\\).',f'\\({ans}\\), \\({la(den)}\\ne0\\).','답을 미분된 제약식에 넣으면0이 된다. 로그가 있을 때 양의 인수 조건도 필요하다.','Substituting into the differentiated constraint gives zero; logarithms also require positive arguments.')
add(39,(r'벌레 경로 \(x=\sqrt{1+t},y=2+t/3\)(cm), T(x,y)(°C), Tx(2,3)=4,Ty(2,3)=3이다. t=3 s에서 온도 변화율을 구하라.',r'A bug follows \(x=\sqrt{1+t},y=2+t/3\)(cm), with temperature T(x,y)(°C), Tx(2,3)=4,Ty(2,3)=3. Find the temperature rate at t=3 s.'),['t=3에서 위치(2,3), x′=1/4,y′=1/3이다.','dT/dt=Tx x′+Ty y′=4/4+3/3=2.'],['At t=3 the position is(2,3), with x′=1/4,y′=1/3.','dT/dt=Tx x′+Ty y′=4/4+3/3=2.'],'2°C/s.','2°C/s.','공간 변화율(°C/cm)×속도(cm/s)의 합이다.','Each term is a spatial rate(°C/cm) times velocity(cm/s).')
add(40,('밀 생산량 W(T,R)의 WT=−2,WR=8이며 T′=0.15°C/year,R′=−0.1 cm/year이다. (a) 편도함수 부호를 해석하고 (b) 생산량 변화율을 추정하라.','For wheat production W(T,R), WT=−2,WR=8,T′=0.15°C/year,R′=−0.1 cm/year. (a) Interpret the partial signs; (b) estimate the production rate.'),['(a) 강수량을 고정하면 온도 증가는 생산을 감소시키고, 온도를 고정하면 강수 증가는 생산을 증가시킨다.','(b) W′=−2(0.15)+8(−0.1)=−1.1.'],['(a) At fixed rainfall, warming decreases production; at fixed temperature, more rainfall increases production.','(b) W′=−2(0.15)+8(−0.1)=−1.1.'],'(a) 온도 음, 강수 양 영향. (b) 생산단위/year로−1.1.','(a) Negative temperature effect, positive rainfall effect. (b) −1.1 production units/year.','두 시간 변화가 모두 생산 감소 방향이다.','Both time trends decrease production.',['a','b'])
add(41,(r'\(C=1449.2+4.6T-0.055T^2+0.00029T^3+0.016D\)(m/s). 원문 잠수 그래프의 t=20 min 부근은 T≈13°C,T′≈−0.10°C/min,D′≈0.6 m/min이다. 잠수자가 겪는 음속 변화율을 추정하고 단위를 말하라.',r'For \(C=1449.2+4.6T-0.055T^2+0.00029T^3+0.016D\)(m/s), the source dive graphs near t=20 min give T≈13°C,T′≈−0.10°C/min,D′≈0.6 m/min. Estimate the experienced sound-speed rate and state units.'),[r'\(C\prime=(4.6-0.11T+0.00087T^2)T\prime+0.016D\prime\).','T=13과 그림에서 읽은 기울기를 대입하면3.31703(−0.10)+0.016(0.6)≈−0.3221.'],[r'\(C\prime=(4.6-0.11T+0.00087T^2)T\prime+0.016D\prime\).','Insert T=13 and the graph-estimated slopes:3.31703(−0.10)+0.016(0.6)≈−0.3221.'],'약−0.32(m/s)/min.','Approximately−0.32(m/s)/min.','그림 기울기를 읽는 정밀도에 따른 근삿값이며 초당 변화율로 바꾸려면60으로 나눈다.','This estimate depends on graphical slope accuracy; divide by60 for rate per second.')
add(42,('원뿔 r′=1.8 in/s,h′=−2.5 in/s이다. r=120 in,h=140 in일 때 부피 변화율을 구하라.','A cone has r′=1.8 in/s,h′=−2.5 in/s. Find the volume rate when r=120 in,h=140 in.'),[r'\(V=\pi r^2h/3\), \(V\prime=\pi(2rhr\prime+r^2h\prime)/3\).',r'\(V\prime=\pi[2(120)(140)(1.8)+120^2(-2.5)]/3\).'],[r'\(V=\pi r^2h/3\), \(V\prime=\pi(2rhr\prime+r^2h\prime)/3\).',r'\(V\prime=\pi[2(120)(140)(1.8)+120^2(-2.5)]/3\).'],r'\(8160\pi\) in³/s.',r'\(8160\pi\) in³/s.','반지름 증가의 양의 기여가 높이 감소보다 커서 부피가 증가한다.','The positive radial contribution exceeds the negative height contribution.')
add(43,('상자 l=1 m,w=h=2 m, l′=w′=2 m/s,h′=−3 m/s일 때 (a) 부피, (b) 겉넓이, (c) 대각선 길이의 변화율을 구하라.','For a box with l=1 m,w=h=2 m,l′=w′=2 m/s,h′=−3 m/s, find rates of(a) volume,(b) surface area,(c) diagonal length.'),['(a) V′=wh l′+lh w′+lw h′=8+4−6=6.',r'(b) S′=2[(w+h)l′+(l+h)w′+(l+w)h′]=2(8+6−9)=10.',r'(c) \(d=\sqrt{l^2+w^2+h^2}=3\), \(d\prime=(ll\prime+ww\prime+hh\prime)/d=(2+4-6)/3=0\).'],['(a) V′=wh l′+lh w′+lw h′=8+4−6=6.','(b) S′=2[(w+h)l′+(l+h)w′+(l+w)h′]=2(8+6−9)=10.',r'(c) \(d=\sqrt{l^2+w^2+h^2}=3\), \(d\prime=(ll\prime+ww\prime+hh\prime)/d=(2+4-6)/3=0\).'],'(a)6 m³/s,(b)10 m²/s,(c)0 m/s.','(a)6 m³/s,(b)10 m²/s,(c)0 m/s.','대각선의 순간변화0이 모든 시간에서 일정하다는 뜻은 아니다.','Zero instantaneous diagonal rate does not imply constancy for all time.',['a','b','c'])
add(44,('V=IR에서 R=400Ω,I=0.08A,V′=−0.01V/s,R′=0.03Ω/s이다. 전류 변화율을 구하라.','For V=IR with R=400Ω,I=0.08A,V′=−0.01V/s,R′=0.03Ω/s, find I′.'),['미분하면 V′=I′R+IR′이다.','I′=(V′−IR′)/R=(−0.01−0.08·0.03)/400.'],['Differentiate to get V′=I′R+IR′.','I′=(V′−IR′)/R=(−0.01−0.08·0.03)/400.'],'−0.000031 A/s.','−0.000031 A/s.','전압 감소와 저항 증가 모두 전류를 감소시킨다.','Falling voltage and rising resistance both decrease current.')
add(45,('PV=8.31T에서 P=20 kPa,T=320 K,P′=0.05 kPa/s,T′=0.15 K/s일 때 V′를 구하라.','For PV=8.31T,P=20 kPa,T=320 K,P′=0.05 kPa/s,T′=0.15 K/s, find V′.'),['V=8.31T/P=132.96 L.','V′=(8.31T′−VP′)/P=(1.2465−6.648)/20.'],['V=8.31T/P=132.96 L.','V′=(8.31T′−VP′)/P=(1.2465−6.648)/20.'],'−0.270075 L/s.','−0.270075 L/s.','압력 증가의 수축 효과가 온도 상승의 팽창 효과보다 크다.','Pressure-induced contraction exceeds temperature-induced expansion.')
L0=30;K0=8;P0=1.47*L0**.65*K0**.35;rate=P0*(.65*(-2)/30+.35*.5/8)
add(46,(r'생산액 \(P=1.47L^{0.65}K^{0.35}\)(million dollars), L은1000노동시간,K는million dollars 단위이다. L=30,K=8에서 노동시간은연2000시간 감소, 자본은연$500,000 증가한다. 생산액 변화율을 구하라.',r'Production \(P=1.47L^{0.65}K^{0.35}\) is in million dollars,L in thousand labor hours,K in million dollars. At L=30,K=8,labor decreases2000 hours/year and capital increases$500,000/year. Find the production rate.'),['단위변환 L′=−2,K′=0.5.',r'\(P\prime=P[0.65L\prime/L+0.35K\prime/K]\).'],['Convert units:L′=−2,K′=0.5.',r'\(P\prime=P[0.65L\prime/L+0.35K\prime/K]\).'],f'약{rate:.6f} million dollars/year (약${abs(rate)*1e6:,.0f}/year 감소).',f'Approximately{rate:.6f} million dollars/year (a decrease of about${abs(rate)*1e6:,.0f}/year).','노동의 단위를2000 그대로 넣지 않고1000시간 단위−2로 바꿨다.','Labor change was converted to−2 in thousand-hour units, rather than inserting2000.')
add(47,('삼각형 두 변 a,b가 a′=3 cm/s,b′=−2 cm/s로 변하지만 넓이는 일정하다. a=20 cm,b=30 cm,끼인각θ=π/6일 때 θ′를 구하라.','Triangle sides have a′=3 cm/s,b′=−2 cm/s while area stays constant. Find θ′ when a=20 cm,b=30 cm and included angleθ=π/6.'),[r'\(A=ab\sin\theta/2\). \(0=(a\prime b+ab\prime)\sin\theta+ab\cos\theta\,\theta\prime\).',r'\(\theta\prime=-(a\prime/a+b\prime/b)\tan\theta=-(3/20-2/30)/\sqrt3\).'],[r'\(A=ab\sin\theta/2\). \(0=(a\prime b+ab\prime)\sin\theta+ab\cos\theta\,\theta\prime\).',r'\(\theta\prime=-(a\prime/a+b\prime/b)\tan\theta=-(3/20-2/30)/\sqrt3\).'],r'\(-1/(12\sqrt3)\) rad/s.',r'\(-1/(12\sqrt3)\) rad/s.','ab가 증가하므로 넓이 일정 조건에서 작은 예각이 감소해야 한다.','Since ab increases, the acute angle must decrease to maintain area.')
freq=460*(332+34)/(332-40);frate=460*(1.2*(332-40)+(332+34)*1.4)/(332-40)**2
add(48,(r'도플러 식 \(f_o=f_s(c+v_o)/(c-v_s)\), c=332m/s,fs=460Hz이다. 서로 접근하는 관측 열차 vo=34m/s,vo′=1.2m/s²,음원 열차 vs=40m/s,vs′=1.4m/s²일 때 fo와fo′를 구하라.',r'For Doppler formula \(f_o=f_s(c+v_o)/(c-v_s)\),c=332m/s,fs=460Hz,approaching trains have vo=34m/s,vo′=1.2m/s²,vs=40m/s,vs′=1.4m/s². Find fo and fo′.'),[r'\(f_o=460(366/292)\).',r'\(f_o\prime=f_s[(c-v_s)v_o\prime+(c+v_o)v_s\prime]/(c-v_s)^2\).'],[r'\(f_o=460(366/292)\).',r'\(f_o\prime=f_s[(c-v_s)v_o\prime+(c+v_o)v_s\prime]/(c-v_s)^2\).'],f'fo≈{freq:.4f}Hz,fo′≈{frate:.4f}Hz/s.',f'fo≈{freq:.4f}Hz,fo′≈{frate:.4f}Hz/s.','접근 가속도 두 항이 모두 양수여서 들리는 주파수가 상승한다.','Both approaching accelerations contribute positively, increasing perceived frequency.')
add(49,(r'z=f(x,y),x=r cosθ,y=r sinθ. (a) zr,zθ를 구하고 (b) \(z_x^2+z_y^2=z_r^2+z_\theta^2/r^2\)를 증명하라.',r'For z=f(x,y),x=r cosθ,y=r sinθ,(a)find zr,zθ and(b)prove \(z_x^2+z_y^2=z_r^2+z_\theta^2/r^2\).'),[r'(a) \(z_r=z_x\cos\theta+z_y\sin\theta\), \(z_\theta=r(-z_x\sin\theta+z_y\cos\theta)\).',r'(b) 두 식을 제곱해 더하면 교차항이 소거되고 \(\sin^2\theta+\cos^2\theta=1\)이다.'],[r'(a) \(z_r=z_x\cos\theta+z_y\sin\theta\), \(z_\theta=r(-z_x\sin\theta+z_y\cos\theta)\).',r'(b) Square and add; cross terms cancel and \(\sin^2\theta+\cos^2\theta=1\).'],r'(a) 위 두 식. (b) \(z_x^2+z_y^2=z_r^2+z_\theta^2/r^2\),r>0.',r'(a) The two displayed formulas. (b) \(z_x^2+z_y^2=z_r^2+z_\theta^2/r^2\),r>0.','직교 좌표 회전은 벡터의 제곱길이를 보존한다.','An orthogonal rotation preserves squared vector length.',['a','b'])
add(50,(r'u=f(x,y),x=eˢ cos t,y=eˢ sin t일 때 \(u_x^2+u_y^2=e^{-2s}(u_s^2+u_t^2)\)를 증명하라.',r'For u=f(x,y),x=eˢ cos t,y=eˢ sin t,prove \(u_x^2+u_y^2=e^{-2s}(u_s^2+u_t^2)\).'),[r'\(u_s=xu_x+yu_y,u_t=-yu_x+xu_y\).',r'제곱을 더하면 \(u_s^2+u_t^2=(x^2+y^2)(u_x^2+u_y^2)=e^{2s}(u_x^2+u_y^2)\).'],[r'\(u_s=xu_x+yu_y,u_t=-yu_x+xu_y\).',r'Summing squares gives \(u_s^2+u_t^2=(x^2+y^2)(u_x^2+u_y^2)=e^{2s}(u_x^2+u_y^2)\).'],r'\(u_x^2+u_y^2=e^{-2s}(u_s^2+u_t^2)\).',r'\(u_x^2+u_y^2=e^{-2s}(u_s^2+u_t^2)\).','e²ˢ는 항상 양수여서 나눌 수 있다.','e²ˢ is always positive, so division is valid.')
add(51,(r'연속 2계 도함수의 f,g에 대해 \(z=f(x+at)+g(x-at)\)가 \(z_{tt}=a^2z_{xx}\)를 만족함을 보여라.',r'For f,g with continuous second derivatives,show that \(z=f(x+at)+g(x-at)\) satisfies \(z_{tt}=a^2z_{xx}\).'),[r'\(z_{xx}=f\prime\prime(x+at)+g\prime\prime(x-at)\).',r'\(z_t=af\prime(x+at)-ag\prime(x-at)\)를 한 번 더 미분하면 두 항 모두 a²가 붙는다.'],[r'\(z_{xx}=f\prime\prime(x+at)+g\prime\prime(x-at)\).',r'Differentiate \(z_t=af\prime(x+at)-ag\prime(x-at)\) again; both terms acquire a².'],r'\(z_{tt}=a^2[f\prime\prime(x+at)+g\prime\prime(x-at)]=a^2z_{xx}\).',r'\(z_{tt}=a^2[f\prime\prime(x+at)+g\prime\prime(x-at)]=a^2z_{xx}\).','역방향 파동의 두 번 미분에서(−a)²=a²이다.','The backward-moving term gives(−a)²=a² after two differentiations.')
add(52,(r'u=f(x,y),x=eˢcos t,y=eˢsin t, f∈C²일 때 \(u_{xx}+u_{yy}=e^{-2s}(u_{ss}+u_{tt})\)를 증명하라.',r'For u=f(x,y),x=eˢcos t,y=eˢsin t and f∈C²,prove \(u_{xx}+u_{yy}=e^{-2s}(u_{ss}+u_{tt})\).'),[r'\(u_{ss}=x^2u_{xx}+2xyu_{xy}+y^2u_{yy}+xu_x+yu_y\).',r'\(u_{tt}=y^2u_{xx}-2xyu_{xy}+x^2u_{yy}-xu_x-yu_y\).',r'더하면 \((x^2+y^2)(u_{xx}+u_{yy})=e^{2s}(u_{xx}+u_{yy})\)이다.'],[r'\(u_{ss}=x^2u_{xx}+2xyu_{xy}+y^2u_{yy}+xu_x+yu_y\).',r'\(u_{tt}=y^2u_{xx}-2xyu_{xy}+x^2u_{yy}-xu_x-yu_y\).',r'The sum is \((x^2+y^2)(u_{xx}+u_{yy})=e^{2s}(u_{xx}+u_{yy})\).'],r'\(u_{xx}+u_{yy}=e^{-2s}(u_{ss}+u_{tt})\).',r'\(u_{xx}+u_{yy}=e^{-2s}(u_{ss}+u_{tt})\).','혼합편미분과1계항이 각각 소거된다.','Mixed second derivatives and first-order terms cancel separately.')
add(53,('z=f(x,y),x=r²+s²,y=2rs이고 f∈C²이다. zrs를 구하라.','Let z=f(x,y),x=r²+s²,y=2rs with f∈C². Find zrs.'),['zr=2r fx+2s fy이다.',r's로 미분하면 \(z_{rs}=2r(2sf_{xx}+2rf_{xy})+2f_y+2s(2sf_{yx}+2rf_{yy})\).'],['zr=2r fx+2s fy.',r'Differentiating in s gives \(z_{rs}=2r(2sf_{xx}+2rf_{xy})+2f_y+2s(2sf_{yx}+2rf_{yy})\).'],r'\(z_{rs}=4rs(f_{xx}+f_{yy})+4(r^2+s^2)f_{xy}+2f_y\), f의 미분은(r²+s²,2rs)에서 평가.',r'\(z_{rs}=4rs(f_{xx}+f_{yy})+4(r^2+s^2)f_{xy}+2f_y\), evaluating f derivatives at(r²+s²,2rs).','곱의 법칙에서2s를 미분한2fy항을 포함한다.','The term2fy comes from differentiating the coefficient2s.')
add(54,('z=f(x,y),x=r cosθ,y=r sinθ,f∈C²이다. (a)zr,(b)zθ,(c)zrθ를 구하라.','For z=f(x,y),x=r cosθ,y=r sinθ,f∈C²,find(a)zr,(b)zθ,(c)zrθ.'),[r'(a) \(z_r=f_x\cos\theta+f_y\sin\theta\). (b) \(z_\theta=r(-f_x\sin\theta+f_y\cos\theta)\).',r'(c) (a)를 θ로 미분한다. 미분계수에는 연쇄법칙, 사인·코사인 계수에는 곱의 법칙을 적용한다.'],[r'(a) \(z_r=f_x\cos\theta+f_y\sin\theta\). (b) \(z_\theta=r(-f_x\sin\theta+f_y\cos\theta)\).',r'(c) Differentiate(a) inθ, applying the chain rule to f derivatives and the product rule to trigonometric coefficients.'],r'(a) \(f_x\cos\theta+f_y\sin\theta\). (b) \(r(-f_x\sin\theta+f_y\cos\theta)\). (c) \(r\sin\theta\cos\theta(f_{yy}-f_{xx})+r\cos(2\theta)f_{xy}-f_x\sin\theta+f_y\cos\theta\).',r'(a) \(f_x\cos\theta+f_y\sin\theta\). (b) \(r(-f_x\sin\theta+f_y\cos\theta)\). (c) \(r\sin\theta\cos\theta(f_{yy}-f_{xx})+r\cos(2\theta)f_{xy}-f_x\sin\theta+f_y\cos\theta\).','zθ를 r로 미분해도 같은 식이 나오며 C²로 fxy=fyx이다.','Differentiating zθ in r gives the same expression; C² ensures fxy=fyx.',['a','b','c'])
add(55,(r'z=f(x,y),x=r cosθ,y=r sinθ일 때 \(z_{xx}+z_{yy}=z_{rr}+z_r/r+z_{\theta\theta}/r^2\)를 증명하라.',r'For z=f(x,y),x=r cosθ,y=r sinθ,prove \(z_{xx}+z_{yy}=z_{rr}+z_r/r+z_{\theta\theta}/r^2\).'),[r'\(z_{rr}=f_{xx}\cos^2\theta+2f_{xy}\sin\theta\cos\theta+f_{yy}\sin^2\theta\).',r'\(z_{\theta\theta}=r^2[f_{xx}\sin^2\theta-2f_{xy}\sin\theta\cos\theta+f_{yy}\cos^2\theta]-rz_r\).','둘째 식을 r²로 나누고 첫째 및 zr/r을 더하면 혼합항과1계항이 소거된다.'],[r'\(z_{rr}=f_{xx}\cos^2\theta+2f_{xy}\sin\theta\cos\theta+f_{yy}\sin^2\theta\).',r'\(z_{\theta\theta}=r^2[f_{xx}\sin^2\theta-2f_{xy}\sin\theta\cos\theta+f_{yy}\cos^2\theta]-rz_r\).','Divide the second formula by r² and add the first and zr/r; cross and first-order terms cancel.'],r'\(z_{xx}+z_{yy}=z_{rr}+z_r/r+z_{\theta\theta}/r^2\),r>0.',r'\(z_{xx}+z_{yy}=z_{rr}+z_r/r+z_{\theta\theta}/r^2\),r>0.','극좌표가 특이한 r=0에는 분모 있는 공식을 직접 적용하지 않는다.','Do not apply the divided formula directly at the polar-coordinate singularity r=0.')
add(56,(r'\(f=x^2y+2xy^2+5y^3\)가3차 동차함수임을 확인하라.',r'Verify that \(f=x^2y+2xy^2+5y^3\) is homogeneous of degree3.'),[r'\(f(tx,ty)=t^3x^2y+2t^3xy^2+5t^3y^3\).','모든 항에서 t³을 인수로 뽑는다.'],[r'\(f(tx,ty)=t^3x^2y+2t^3xy^2+5t^3y^3\).','Factor t³ from every term.'],r'\(f(tx,ty)=t^3f(x,y)\).',r'\(f(tx,ty)=t^3f(x,y)\).','각 단항식의 총 차수가3이다.','Every monomial has total degree3.')
add(57,(r'f(tx,ty)=tⁿf(x,y),f∈C²일 때 (a) \(xf_x+yf_y=nf\), (b) \(x^2f_{xx}+2xyf_{xy}+y^2f_{yy}=n(n-1)f\)를 증명하라.',r'For f(tx,ty)=tⁿf(x,y),f∈C²,prove(a) \(xf_x+yf_y=nf\), and(b) \(x^2f_{xx}+2xyf_{xy}+y^2f_{yy}=n(n-1)f\).'),[r'(a) t로 미분하면 \(xf_x(tx,ty)+yf_y(tx,ty)=nt^{n-1}f(x,y)\). t=1을 넣는다.',r'(b) 다시 t로 미분하면 \(x^2f_{xx}+2xyf_{xy}+y^2f_{yy}\)가 왼쪽에 나오고 t=1에서 오른쪽은n(n−1)f이다.'],[r'(a) Differentiation in t gives \(xf_x(tx,ty)+yf_y(tx,ty)=nt^{n-1}f(x,y)\); set t=1.',r'(b) Differentiate again in t: the left side becomes \(x^2f_{xx}+2xyf_{xy}+y^2f_{yy}\), while at t=1 the right side is n(n−1)f.'],'(a),(b)의 두 항등식 성립.','Both identities hold.','f의 x,y는 t미분에서 고정된 계수이다.','x,y remain fixed coefficients when differentiating in t.',['a','b'])
add(58,(r'n차 동차함수 f의 편도함수가 \(f_x(tx,ty)=t^{n-1}f_x(x,y)\)를 만족함을 보여라.',r'For homogeneous degree-n f,show \(f_x(tx,ty)=t^{n-1}f_x(x,y)\).'),[r'동차식 f(tx,ty)=tⁿf(x,y)를 x로 미분하면 \(t f_x(tx,ty)=t^nf_x(x,y)\).','t≠0에서 나누고, 연속성으로 t=0에서의 성립도 해석한다(n=1이면 우변은fx(x,y)).'],[r'Differentiate f(tx,ty)=tⁿf(x,y) in x to get \(t f_x(tx,ty)=t^nf_x(x,y)\).','Divide for t≠0, then use continuity at t=0(the n=1 right side is fx(x,y)).'],r'\(f_x(tx,ty)=t^{n-1}f_x(x,y)\).',r'\(f_x(tx,ty)=t^{n-1}f_x(x,y)\).','1계 미분으로 동차 차수가1 낮아진다.','A first derivative lowers homogeneity degree by1.')
add(59,(r'F(x,y,z)=0이 각 변수를 나머지 둘의 함수로 정의하고 Fx,Fy,Fz≠0일 때 \((\partial z/\partial x)(\partial x/\partial y)(\partial y/\partial z)=-1\)임을 보여라.',r'If F(x,y,z)=0 implicitly defines each variable in terms of the other two and Fx,Fy,Fz≠0,prove \((\partial z/\partial x)(\partial x/\partial y)(\partial y/\partial z)=-1\).'),[r'각 편미분에서 나머지 제3변수를 고정하면 \(z_x=-F_x/F_z,x_y=-F_y/F_x,y_z=-F_z/F_y\).','세 비를 곱하면 모든 Fx,Fy,Fz가 약분되고 음수 부호3개가 남는다.'],[r'Keeping the third variable fixed each time gives \(z_x=-F_x/F_z,x_y=-F_y/F_x,y_z=-F_z/F_y\).','Multiply the ratios: all Fx,Fy,Fz factors cancel, leaving three minus signs.'],'곱은−1.','The product is−1.','서로 다른 고정변수를 쓰므로 보통 단변수 역함수 미분의 곱1과 혼동하지 않는다.','Different variables are held fixed, so this is not the product1 from ordinary one-variable inverse derivatives.')
add(60,(r'F(x,y)=0,Fy≠0,F∈C²일 때 \(y\prime\prime=-(F_{xx}F_y^2-2F_{xy}F_xF_y+F_{yy}F_x^2)/F_y^3\)를 증명하라.',r'For F(x,y)=0,Fy≠0,F∈C²,prove \(y\prime\prime=-(F_{xx}F_y^2-2F_{xy}F_xF_y+F_{yy}F_x^2)/F_y^3\).'),[r'처음 미분은 \(F_x+F_yy\prime=0\), 따라서 \(y\prime=-F_x/F_y\).',r'다시 전미분하면 \(F_{xx}+2F_{xy}y\prime+F_{yy}(y\prime)^2+F_yy\prime\prime=0\).',r'y′의 비를 넣고 통분하여 y″를 푼다.'],[r'First, \(F_x+F_yy\prime=0\), so \(y\prime=-F_x/F_y\).',r'Differentiating again gives \(F_{xx}+2F_{xy}y\prime+F_{yy}(y\prime)^2+F_yy\prime\prime=0\).',r'Substitute the ratio for y′, combine denominators, and solve for y″.'],r'\(y\prime\prime=-\frac{F_{xx}F_y^2-2F_{xy}F_xF_y+F_{yy}F_x^2}{F_y^3}\).',r'\(y\prime\prime=-\frac{F_{xx}F_y^2-2F_{xy}F_xF_y+F_{yy}F_x^2}{F_y^3}\).','연쇄법칙에서 F의 y의존성도 미분하여 혼합항2개가 생긴다.','Differentiating the y-dependence of F creates both mixed terms.')
E.sort(key=lambda e:e['number']);assert [e['number'] for e in E]==list(range(1,61))
D=dict(section='14.5',source=dict(title='Calculus',edition='9',language='en',printedPages=[1029,1030,1031,1032],pdfPages=[1066,1067,1068,1069]),scope=dict(kind='exercise',numbers=list(range(1,61)),total=60,note=pair('전체60문항과모든소문항.','All60 exercises and every subpart.')),exercises=E)
assets=R/'exercise-content/assets';assets.mkdir(exist_ok=True)
for n,name,inners,outers in trees:
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 360"><rect width="900" height="360" fill="white"/>'];out.append(f'<text x="450" y="40" text-anchor="middle" font-size="25">{name}</text>')
 for i,iv in enumerate(inners):
  ix=900*(i+.5)/len(inners);out.append(f'<line x1="450" y1="55" x2="{ix}" y2="130" stroke="#567"/><text x="{ix}" y="155" text-anchor="middle" font-size="25">{iv}</text>')
  for j,ov in enumerate(outers):
   ox=900*(i+(j+.5)/len(outers))/len(inners);out.append(f'<line x1="{ix}" y1="165" x2="{ox}" y2="270" stroke="#789"/><text x="{ox}" y="300" text-anchor="middle" font-size="22">{ov}</text>')
 out.append('</svg>');namefile=f's14-5-{n}.svg';(assets/namefile).write_text('\n'.join(out));next(e for e in E if e['number']==n)['figure']=dict(src='../exercise-content/assets/'+namefile,alt=pair('연쇄법칙 의존관계 나무도표','Chain-rule dependency tree'),caption=pair('각 뿌리에서 잎까지 경로의 미분을 곱하고 같은 입력변수의 경로를 더한다.','Multiply derivatives along each root-to-leaf path and sum paths sharing the same input variable.'))
(R/'exercise-content/s14-5.json').write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n');print('14.5:60 cards,4 original trees; direct chain-rule checks passed')
