from early_helpers import *
from math import *
import sympy as s
b=Book('14.1',list(range(984,990)))
def add(n,st,steps,ans,parts=[],topic=('다변수함수와 그래프','Functions of several variables')):b.add(n,984 if n<=17 else 985 if n<=31 else 986 if n<=36 else 987 if n<=60 else 988 if n<=70 else 989,topic,st,steps,ans,parts)
def eq(n,F,A,detail,parts=[]):add(n,(r'\('+F+r'\). '+detail[0],r'\('+F+r'\). '+detail[1]),[('주어진 값을 순서대로 대입하고 정의역의 조건을 함께 확인한다.','Substitute the indicated values and retain the domain restrictions.')]+fs(A),same(r'\['+A+r'\]'),parts)
eq(1,r'f(x,y)=\frac{x^2y}{2x-y^2}',r'(a)\ -3/7,\quad(b)\ 4/5,\quad(c)\ \frac{(x+h)^2y}{2(x+h)-y^2},\quad(d)\ \frac{x^2}{2-x}\ (x\ne0,2)',('f(1,3), f(-2,-1), f(x+h,y), f(x,x)를 구하라.','Find f(1,3), f(-2,-1), f(x+h,y), and f(x,x).'),list('abcd'))
eq(2,r'g(x,y)=x\sin y+y\sin x',r'(a)\ 0,\quad(b)\frac{\pi\sqrt2}4+\frac\pi4,\quad(c)\ 0,\quad(d)\ x\sin(y+h)+(y+h)\sin x',('g(π,0), g(π/2,π/4), g(0,y), g(x,y+h)를 구하라.','Find g(π,0), g(π/2,π/4), g(0,y), and g(x,y+h).'),list('abcd'))
add(3,(r'\(g=x^2\ln(x+y)\). (a) g(3,1), (b) 정의역과 그림, (c) 치역을 구하라.',r'For \(g=x^2\ln(x+y)\), find (a) g(3,1), (b) its domain and sketch, and (c) its range.'),fs(r'g(3,1)=9\ln4',r'x+y>0\iff y>-x')+[('x=1로 고정하면 y>-1에서 ln(1+y)가 모든 실숫값을 갖는다.','With x=1, ln(1+y) attains every real value as y ranges above -1.')],same(r'(a) (9ln4); (b) (y>-x), 경계 제외 / boundary excluded; (c) (mathbb R).'),list('abc'))
add(4,(r'\(h=e^{\sqrt{y-x^2}}\). (a) h(-2,5), (b) 정의역과 그림, (c) 치역을 구하라.',r'For \(h=e^{\sqrt{y-x^2}}\), find (a) h(-2,5), (b) its domain and sketch, and (c) its range.'),fs(r'h(-2,5)=e,\quad y-x^2\ge0,\quad\sqrt{y-x^2}\in[0,\infty)'),same(r'(a) (e); (b) (yge x^2); (c) ([1,infty)).'),list('abc'))
eq(5,r'F(x,y,z)=\sqrt y-\sqrt{x-2z}',r'F(3,4,1)=1,\quad D=\{y\ge0,\ z\le x/2\}',('값 F(3,4,1)과 정의역을 구하고 공간에서 설명하라.','Evaluate F(3,4,1) and describe its domain in space.'),list('ab'))
eq(6,r'f=\ln(z-\sqrt{x^2+y^2})',r'f(4,-3,6)=\ln1=0,\quad D=\{z>\sqrt{x^2+y^2}\}',('값 f(4,-3,6)과 정의역을 구하라. 정의역은 위쪽 원뿔 내부이며 경계는 제외된다.','Evaluate f(4,-3,6) and describe the domain: inside the upper cone, excluding its boundary.'),list('ab'))
domains={7:(r'\sqrt{x-2}+\sqrt{y-1}',r'x\ge2,\ y\ge1','두 근호가 각각 0 이상인 오른쪽 위 사분면.','The upper-right region where both radicands are nonnegative.'),8:(r'\sqrt[4]{x-3y}',r'y\le x/3','직선 아래의 닫힌 반평면.','The closed half-plane below the line.'),9:(r'\sqrt x+\sqrt{4-4x^2-y^2}',r'x\ge0,\quad4x^2+y^2\le4','타원판의 오른쪽 절반, 모든 경계 포함.','The right half of the closed elliptical disk.'),10:(r'\ln(x^2+y^2-9)',r'x^2+y^2>9','반지름 3인 원 바깥, 원 제외.','Outside the radius-3 circle, excluding the circle.'),11:(r'\frac{x-y}{x+y}',r'x+y\ne0','직선 y=-x를 제외한 평면.','The plane with the line y=-x removed.'),12:(r'\frac{\ln(2-x)}{1-x^2-y^2}',r'x<2,\quad x^2+y^2\ne1','x=2 왼쪽에서 단위원을 제거한다.','Take the region left of x=2 and remove the unit circle.'),13:(r'\frac{\sqrt{xy}}{x+1}',r'xy\ge0,\quad x\ne-1','제1·3사분면 및 좌표축에서 x=-1인 점을 제거한다.','The first/third quadrants and axes, with points at x=-1 removed.'),14:(r'\arcsin(x+y)',r'-1\le x+y\le1','두 평행선 사이의 닫힌 띠.','The closed strip between two parallel lines.'),15:(r'\sqrt{4-x^2}+\sqrt{9-y^2}+\sqrt{1-z^2}',r'|x|\le2,\ |y|\le3,\ |z|\le1','닫힌 직육면체.','A closed rectangular box.'),16:(r'\ln(16-4x^2-4y^2-z^2)',r'4x^2+4y^2+z^2<16','반축 2,2,4인 타원체 내부, 표면 제외.','The interior of an ellipsoid with semiaxes 2,2,4; exclude its surface.')}
for n,(F,D,k,e)in domains.items():add(n,(r'\(f='+F+r'\)의 정의역을 구하고 그려라.',r'Find and sketch the domain of \(f='+F+r'\).'),[('짝수근의 내부는 0 이상, 로그의 내부는 양수, 분모는 0이 아니어야 한다. 역사인의 입력은 [-1,1]이다.','Require even radicands to be nonnegative, logarithm arguments positive, denominators nonzero, and arcsine inputs in [-1,1].')]+fs(D)+[(k,e)],(r'\('+D+r'\). '+k,r'\('+D+r'\). '+e))
S=.1091*160**.425*70**.725
add(17,(r'체표면적 모델 \(S=.1091w^{.425}h^{.725}\)에서 w는 lb, h는 in, S는 ft²이다. (a) f(160,70)의 값과 의미, (b) 자신의 치수를 이용한 값을 구하라.',r'For body area \(S=.1091w^{.425}h^{.725}\), with w in lb, h in in, and S in ft², (a) interpret f(160,70); (b) use your own measurements.'),fs(r'S=.1091(160)^{.425}(70)^{.725}\approx'+f'{S:.4f}')+[('자신의 양의 체중과 키를 같은 단위로 바꾸어 식에 넣는다. 개인 치수가 없으면 수치는 정해지지 않는다.','Convert your positive weight and height to the stated units and substitute. No unique personal value is determined without measurements.')],('160 lb, 70 in인 사람은 약 20.5 ft². (b)는 개인 치수에 따라 달라진다.','About 20.5 ft² for a person weighing 160 lb and standing 70 in. Part (b) depends on personal measurements.'),list('ab'))
P=1.47*120**.65*20**.35
add(18,(r'연간 생산액 \(P=1.47L^{.65}K^{.35}\)에서 L은 천 노동시간, K와 P는 백만 달러이다. P(120,20)을 구하고 해석하라.',r'Annual production is \(P=1.47L^{.65}K^{.35}\); L is in thousands of labor-hours, K and P in millions of dollars. Evaluate and interpret P(120,20).'),fs(r'P(120,20)=1.47(120)^{.65}(20)^{.35}\approx'+f'{P:.4f}'),(f'노동 120,000시간, 자본 2천만 달러일 때 연간 생산액 약 {P:.2f}백만 달러.',f'120,000 labor-hours and $20 million of capital predict about ${P:.2f} million of annual production.'))
windrows=[[5,4,3,2,1,1,0,-1,-1,-2,-2,-3],[0,-2,-3,-4,-5,-6,-6,-7,-8,-9,-9,-10],[-5,-7,-9,-11,-12,-12,-13,-14,-15,-16,-16,-17],[-10,-13,-15,-17,-18,-19,-20,-21,-22,-23,-23,-24],[-15,-19,-21,-23,-24,-25,-26,-27,-29,-30,-30,-31],[-20,-24,-27,-29,-30,-32,-33,-34,-35,-36,-37,-38],[-25,-30,-33,-35,-37,-38,-39,-41,-42,-43,-44,-45],[-30,-36,-39,-41,-43,-44,-46,-48,-49,-50,-51,-52],[-35,-41,-45,-48,-49,-51,-52,-54,-56,-57,-58,-60],[-40,-47,-51,-54,-56,-57,-59,-61,-63,-64,-65,-67]]
def table(rows,header):return r'\[\begin{array}{'+'c'*len(header)+r'}'+r'\text{'+str(header[0])+r'}&'+'&'.join(map(str,header[1:]))+r'\\\hline '+r'\\'.join('&'.join(map(str,row))for row in rows)+r'\end{array}\]'

wt=table(windrows,['T / v',5,10,15,20,25,30,40,50,60,70,80])
add(19,('표의 W=f(T,v)는 T(°C), v(km/h)의 체감온도이다. (a) f(-15,40), (b) f(-20,v)=-30인 v, (c) f(T,20)=-49인 T를 구하고 뜻을 설명하라. (d) f(-5,v), (e) f(T,50)의 뜻과 변화를 설명하라.'+wt,'The table gives wind chill W=f(T,v), T in °C and v in km/h. Find and interpret (a) f(-15,40), (b) v with f(-20,v)=-30, (c) T with f(T,20)=-49. Describe (d) f(-5,v) and (e) f(T,50).'+wt),[('행은 기온, 열은 풍속이다. (a)는 행 -15와 열 40을 읽는다. (b)는 행 -20에서 -30을, (c)는 열 20에서 -49를 찾는다.','Rows select temperature and columns wind speed. Read row -15/column 40; find -30 in row -20 and -49 in column 20.'),('기온을 -5로 고정하면 풍속 증가에 따라 체감온도가 내려가되 하락 폭은 줄어든다. 풍속 50에서 실제 기온이 높아질수록 체감온도도 거의 선형으로 오른다.','At T=-5, wind chill decreases with speed at a diminishing rate. At speed 50, wind chill increases approximately linearly with temperature.')],('(a) -27°C; (b) 20 km/h; (c) -35°C. (d) 기온 -5°C의 풍속별 체감온도. (e) 풍속 50 km/h의 기온별 체감온도.','(a) -27°C; (b) 20 km/h; (c) -35°C. (d) Wind chill versus speed at -5°C. (e) Wind chill versus temperature at 50 km/h.'),list('abcde'))
ht=table([[80,77,78,79,81,82,83],[85,82,84,86,88,90,93],[90,87,90,93,96,100,106],[95,93,96,101,107,114,124],[100,99,104,110,120,132,144]],['T / h',20,30,40,50,60,70])
add(20,('표의 I=f(T,h)는 T(°F)와 상대습도 h(%)의 체감온도이다. (a) f(95,70)의 값·의미, (b) f(90,h)=100의 h, (c) f(T,50)=88의 T, (d) f(80,h)와 f(100,h)의 의미·변화를 비교하라.'+ht,'For apparent temperature I=f(T,h), T is °F and h relative humidity (%). (a) Evaluate/interpret f(95,70); (b) solve f(90,h)=100; (c) solve f(T,50)=88; (d) compare f(80,h) and f(100,h).'+ht),[('지정한 행·열을 읽으면 (a)124, (b)60, (c)85이다. 고정 기온에서 습도만 변화시키는 것이 (d)의 두 함수다.','Reading the appropriate row and column gives (a)124, (b)60, (c)85. Both functions in (d) vary humidity at a fixed temperature.'),('습도 20%→70%에서 80°F의 체감온도는 77→83°F, 100°F에서는 99→144°F로 변한다. 높은 기온에서 습도의 영향이 훨씬 크다.','From 20% to 70% humidity, the index rises 77→83°F at 80°F but 99→144°F at 100°F. Humidity has a much stronger effect at the higher temperature.')],('(a)124°F; (b)60%; (c)85°F; (d) 둘 다 증가하며 100°F에서 훨씬 빨리 증가한다.','(a)124°F; (b)60%; (c)85°F; (d) Both increase, much more rapidly at 100°F.'),list('abcd'))
wave=table([[10,2,2,2,2,2,2,2],[15,4,4,5,5,5,5,5],[20,5,7,8,8,9,9,9],[30,9,13,16,17,18,19,19],[40,14,21,25,28,31,33,33],[50,19,29,36,40,45,48,50],[60,24,37,47,54,62,67,69]],['v / t',5,10,15,20,30,40,50])
add(21,('파고 h=f(v,t)(ft), 풍속 v(knots), 지속시간 t(h)의 표이다. (a) f(40,15), (b) f(30,t), (c) f(v,30)의 의미와 변화를 설명하라.'+wave,'The table gives wave height h=f(v,t) in ft, wind speed v in knots, and duration t in hours. Explain (a) f(40,15), (b) f(30,t), and (c) f(v,30).'+wave),[('40행·15열에서 25 ft를 얻는다. 풍속30행은 시간이 길어질수록 파고가 9→19 ft로 증가하면서 평탄해진다.','Row 40, column 15 gives 25 ft. At speed 30, height increases from 9 to 19 ft and levels off with time.'),('시간30열의 파고는 풍속에 따라 2,5,9,18,31,45,62 ft로 증가한다.','The duration-30 column increases through 2,5,9,18,31,45,62 ft as wind speed rises.')],('(a)40 knots 바람이 15 h 지속되면 25 ft. (b)30 knots에서 시간별 파고, 증가 후 포화. (c)30 h 후 풍속별 파고, 증가.','(a)40-knot wind for 15 h gives 25 ft. (b) Height versus time at 30 knots, increasing then leveling off. (c) Height versus speed after 30 h, increasing.'),list('abc'))
eq(22,r'C(x,y,z)=2.50x+4y+4.50z+8000',r'C(3000,5000,4000)=53500,\qquad D=\mathbb Z_{\ge0}^3',('소·중·대 상자 단가가 $2.50,$4,$4.50이고 고정비가 $8000이다. (a) 비용함수, (b) 3000·5000·4000개 생산비와 뜻, (c) 실제 정의역을 구하라.','Small/medium/large boxes cost $2.50/$4/$4.50 each with $8000 fixed cost. Find (a) the cost function, (b) the cost of 3000/5000/4000 boxes and its meaning, (c) the physical domain.'),list('abc'))
surfdata={23:(r'y',lambda x,y:y,'평면 z=y; x축을 포함한다.','Plane z=y containing the x-axis.'),24:(r'x^2',lambda x,y:x*x,'y방향으로 뻗는 포물기둥.','Parabolic cylinder parallel to y.'),25:(r'10-4x-5y',lambda x,y:10-4*x-5*y,'절편 (2.5,0,0),(0,2,0),(0,0,10)의 평면.','Plane with intercepts (2.5,0,0),(0,2,0),(0,0,10).'),26:(r'\cos y',lambda x,y:cos(y),'x방향으로 뻗는 코사인 기둥.','Cosine cylinder parallel to x.'),27:(r'\sin x',lambda x,y:sin(x),'y방향으로 뻗는 사인 기둥.','Sine cylinder parallel to y.'),28:(r'2-x^2-y^2',lambda x,y:2-x*x-y*y,'꼭짓점 (0,0,2), 아래로 열린 회전포물면.','Downward circular paraboloid with vertex (0,0,2).'),29:(r'x^2+4y^2+1',lambda x,y:x*x+4*y*y+1,'꼭짓점 (0,0,1), 위로 열린 타원포물면.','Upward elliptic paraboloid with vertex (0,0,1).'),30:(r'\sqrt{4x^2+y^2}',lambda x,y:sqrt(4*x*x+y*y),'z≥0인 타원뿔의 위쪽 절반.','Upper half of an elliptic cone.'),31:(r'\sqrt{4-4x^2-y^2}',None,'4x²+y²+z²=4의 z≥0 부분: 타원체 위쪽 절반.','Upper half z≥0 of ellipsoid 4x²+y²+z²=4.')}
for n,(F,f,k,e)in surfdata.items():add(n,(r'\(z='+F+r'\)를 그려라.',r'Sketch \(z='+F+r'\).'),[('x 또는 y를 고정한 단면을 그리고 이를 나머지 방향으로 연결한다. 높이 z=k의 단면도 확인한다.','Plot the traces at fixed x or y and connect them in the remaining direction; also inspect traces z=k.'),(k,e)],(k,e))
b.save()
add(32,('다음 함수를 원본의 그래프 I–VI와 연결하고 이유를 설명하라. '+r'(a) \(1/(1+x^2+y^2)\), (b) \(1/(1+x^2y^2)\), (c) \(\ln(x^2+y^2)\), (d) \(\cos\sqrt{x^2+y^2}\), (e) \(|xy|\), (f) \(\cos(xy)\).','Match the six functions to source graphs I–VI and justify: '+r'(a) \(1/(1+x^2+y^2)\), (b) \(1/(1+x^2y^2)\), (c) \(\ln(x^2+y^2)\), (d) \(\cos\sqrt{x^2+y^2}\), (e) \(|xy|\), (f) \(\cos(xy)\).'),[('(a)는 원형 봉우리, (b)는 두 축 전체에서 높이1인 십자 능선이다. (c)는 원점에서 -∞로 내려가는 회전곡면, (d)는 동심원 파동이다.','(a) is a circular peak; (b) has height-1 ridges along both axes. (c) plunges to -∞ at the origin, while (d) has concentric ripples.'),('(e)는 축에서0이고 네 사분면으로 올라간다. (f)는 축에서1이고 xy가 일정한 쌍곡선을 따라 같은 높이를 갖는다.','(e) vanishes on the axes and rises in all quadrants. (f) equals1 on the axes and has hyperbolic level curves.')],same('(a) III; (b) I; (c) IV; (d) V; (e) VI; (f) II.'),list('abcdef'))
add(33,('원본 등고선 지도에서 f(-3,3), f(3,-2)를 추정하고 지형의 모양을 설명하라. 등고선 간격은 높이10이다.','Use the source contour map to estimate f(-3,3) and f(3,-2), then describe the terrain. Consecutive contours differ by10.'),[('(-3,3)은 높이50과60 사이에서 60에 더 가깝고, (3,-2)는30과40 사이에 있다.','(-3,3) lies between levels50 and60, closer to60; (3,-2) lies between30 and40.'),('닫힌 곡선 안쪽으로 값이 커지므로 중앙에 언덕이 있다. 음의 y쪽 등고선이 더 조밀하므로 그쪽 경사가 더 급하다.','Values increase inside the nested closed curves, forming a hill. More closely spaced contours on the negative-y side indicate a steeper slope.')],('약56, 약35. 중앙의 봉우리에서 음의 y방향으로 더 가파르게 내려간다.','Approximately56 and35. A central hill falls more steeply toward negative y.'))
add(34,('북미의 원본 등압선 지도에서 (a) Chicago C, Nashville N, San Francisco S, Vancouver V의 기압(mb)을 추정하고 (b) 바람이 가장 강한 곳을 고르라.','From the source North American isobar map, (a) estimate pressure (mb) at Chicago C, Nashville N, San Francisco S, and Vancouver V; (b) identify the strongest wind.'),[('표시된 인접 등압선은4 mb 차이다. C는1012와1016 사이, N은1012 부근, S는1008과1012 사이, V는1012와1016 사이에서 읽는다.','Adjacent labeled isobars differ by4 mb. C is between1012 and1016, N near1012, S between1008 and1012, and V between1012 and1016.'),('도시 주변 선 간격을 비교한다. S 주변이 가장 조밀하므로 기압의 공간 변화가 가장 커 바람도 가장 강하다.','Compare the spacing near the cities. It is tightest near S, indicating the largest pressure gradient and strongest wind.')],('(a) C≈1014, N≈1012, S≈1010, V≈1014 mb(지도 판독 오차 약1–2 mb). (b) San Francisco.','(a) C≈1014, N≈1012, S≈1010, V≈1014 mb, with roughly1–2 mb reading uncertainty. (b) San Francisco.'),list('ab'))
add(35,('호수의 수온 등고선에서 연중160일·깊이10 m와 연중180일·깊이5 m의 온도를 추정하라.','Estimate lake temperature from the isotherms at day160/depth10 m and day180/depth5 m.'),[('첫 점은8°C와12°C 선 사이에서12°C에 더 가깝다. 둘째 점은16°C와20°C 사이에서20°C에 매우 가깝다.','The first point lies between8°C and12°C, closer to12°C. The second is between16°C and20°C, very close to20°C.')],('약11°C와19.5°C. 그림으로 읽는 근삿값이다.','Approximately11°C and19.5°C; these are graphical estimates.'))
add(36,('등간격 높이의 동심원 지도 I은 바깥으로 갈수록 간격이 줄고 II는 반지름 간격이 일정하다. 원뿔과 포물면을 대응시켜라.','For equally spaced contour heights, map I has decreasing radial spacing outward, while map II has constant radial spacing. Identify the cone and paraboloid.'),fs(r'z=r^2\Rightarrow r_k=\sqrt k,\quad \sqrt{k+1}-\sqrt k\downarrow0',r'z=r\Rightarrow r_k=k')+[('반지름이 커질수록 포물면의 기울기는 커지지만 원뿔의 기울기는 일정하다.','The paraboloid steepens as radius increases, whereas the cone has constant slope.')],('I: 포물면, II: 원뿔.','I: paraboloid; II: cone.'))
add(37,('원본 그림12의 Lonesome Mountain에서 A와 B 부근의 지형을 설명하라.','Describe the terrain near A and B on the source Lonesome Mountain map (Figure12).'),[('A 부근에서는 서로 다른 높이의 등고선이 좁게 모이고, B 부근에서는 넓게 떨어져 있다. 같은 고도차를 더 짧은 수평거리에서 오르면 경사가 크다.','Contours are close near A and widely separated near B. The same elevation change over a shorter horizontal distance means a greater slope.')],('A: 급경사. B: 거의 평평하거나 완만한 경사.','A: steep. B: nearly flat or gently sloping.'))
add(38,('원본의 네 봉우리 곡면을 보고 개략적인 등고선 지도를 그려라.','Sketch a contour map for the source surface with four peaks.'),[('낮은 높이에서는 봉우리들을 함께 둘러싼 곡선이 나타날 수 있다. 높이가 봉우리 사이 안부보다 커지면 각 봉우리 주위에 분리된 닫힌 고리가 생긴다.','Low contours may surround several peaks together. Above the saddles between peaks, the contours split into separate closed loops.'),('각 고리 안쪽으로 높이가 증가한다. 높은 두 봉우리는 더 높은 높이에서도 고리가 남고 낮은 두 봉우리는 먼저 사라진다.','Values increase inward around each peak. The taller peaks retain contours at heights where the shorter peaks no longer do.')],('네 중심 주위의 닫힌 등고선 묶음. 낮은 등고선은 합쳐지고 높은 등고선은 봉우리마다 분리된다.','Four clusters of nested closed curves; low contours can merge, while high contours isolate the peaks.'))
add(39,(r'교재 모델 \(B(m,h)=m/h^2\)에서 m은 kg, h는 m이다. B=18.5,25,30,40의 등고선을 그리고 교재의 범위 18.5≤B≤25를 칠하라. m=62,h=1.52가 이 범위인지 판단하라.',r'For the textbook model \(B(m,h)=m/h^2\), m in kg and h in m, draw levels18.5,25,30,40 and shade the textbook interval18.5≤B≤25. Test m=62,h=1.52.'),fs(r'm=kh^2\quad(k=18.5,25,30,40),\qquad18.5h^2\le m\le25h^2',r'B(62,1.52)=62/1.52^2\approx26.8352'),('등고선은 양의 영역의 포물선이다. B≈26.84이므로 교재가 제시한18.5–25 구간에는 속하지 않는다.','The contours are parabolas in the positive region. B≈26.84, outside the interval18.5–25 specified in the exercise.'))
add(40,(r'\(B=m/h^2\)에서 키200 cm·질량80 kg에 해당하는 등고선을 그리고, 같은 등고선 위의 다른 두 키·질량을 찾아라.',r'For \(B=m/h^2\), sketch the contour through height200 cm and mass80 kg, and give two other height–mass pairs on it.'),fs(r'B=80/2^2=20,\qquad m=20h^2',r'h=1.5\Rightarrow m=45;\qquad h=1.8\Rightarrow m=64.8'),('m=20h²(h>0). 예:150 cm·45 kg,180 cm·64.8 kg.','m=20h² (h>0). Examples:150 cm/45 kg and180 cm/64.8 kg.'))
rough={41:('중심에 조밀한 동심원, 바깥으로 높이가 증가하고 간격이 커진다.','Concentric contours are tight near the center and spread outward as their values increase.','가운데 깊이 내려가는 회전 대접/깔때기 모양. 중앙에서는 급하고 바깥에서는 완만하다.','A rotational bowl/funnel, steep near the center and flatter outward.'),42:('위로 열린 포물선 모양 등고선에서 아래쪽으로 값이 증가한다.','Upward-opening parabolic contours increase in value downward.','y방향으로 내려가며 높아지고 x방향으로 휘는 곡면; 같은 높이차의 선 간격이 좁은 곳에서 급하다.','A surface rising toward decreasing y, curved in x; tightly spaced contours indicate steeper regions.'),43:('제1사분면에서 두 축과 y=x의 높이는0이고 두 부채꼴 내부에서 높이가 커진다.','In the first quadrant, both axes and y=x have height0, with increasing values inside the two sectors.','대각선 골짜기와 두 축 사이에 양쪽으로 올라가는 두 능선.','Two rising ridges separated by a diagonal valley, with zero-height boundaries on the axes.'),44:('마름모꼴 등고선의 높이는 중심에서3, 바깥으로2,1,0,-1,-2,-3으로 감소한다.','Diamond contours decrease outward from level3 through2,1,0,-1,-2,-3.','네 평면 조각이 꼭짓점에서 만나는 사각뿔형 산. 모형 z=4-|x|-|y|로 재현 가능하다.','A four-sided pyramidal hill; a model is z=4-|x|-|y|.')}
for n,(k,e,ak,ae)in rough.items():add(n,('원본 등고선 지도로 곡면을 개략적으로 그려라. '+k,'Sketch a surface from the source contour map. '+e),[(k,e),('각 높이의 곡선을 그 높이만큼 들어 올려 서로 이어 붙인다. 정확한 함수식은 그림만으로 유일하게 결정되지 않는다.','Lift each contour to its labeled height and connect the resulting curves. The exact function is not uniquely determined by the map.')],(ak,ae))
levels={45:(r'x^2-y^2',r'x^2-y^2=k','k>0이면 x방향, k<0이면 y방향으로 열린 쌍곡선. k=0은 y=±x.','Hyperbolas opening in x for k>0 and in y for k<0; k=0 gives y=±x.'),46:(r'xy',r'xy=k','k≠0은 직각쌍곡선, k=0은 두 좌표축.','Rectangular hyperbolas for k≠0; the two axes for k=0.'),47:(r'\sqrt x+y',r'y=k-\sqrt x,\quad x\ge0','동일한 반포물선 모양 곡선을 세로로 평행이동한다.','Vertically translated square-root curves.'),48:(r'\ln(x^2+4y^2)',r'x^2+4y^2=e^k','반축 e^(k/2), e^(k/2)/2인 동심 타원; 원점 제외.','Concentric ellipses with semiaxes e^(k/2) and e^(k/2)/2; exclude the origin.'),49:(r'ye^x',r'y=ke^{-x}','k의 부호에 따라 x축 위·아래에 놓인 지수곡선.','Exponential curves above/below the x-axis according to the sign of k.'),50:(r'y-\arctan x',r'y=k+\arctan x','아크탄젠트 곡선의 세로 평행이동; 수평점근선 k±π/2.','Vertical translations of arctan x with horizontal asymptotes k±π/2.'),51:(r'\sqrt[3]{x^2+y^2}',r'x^2+y^2=k^3,\quad k\ge0','반지름 k^(3/2)의 동심원; k=0은 원점.','Concentric circles of radius k^(3/2); k=0 is the origin.'),52:(r'\frac y{x^2+y^2}',r'x^2+(y-\frac1{2k})^2=\frac1{4k^2}\ (k\ne0)','원점을 뺀 원들이 원점에 접한다. k=0은 원점을 뺀 x축.','Circles tangent at the excluded origin. For k=0, the x-axis with the origin removed.')}
for n,(F,L,k,e)in levels.items():add(n,(r'\(f='+F+r'\)의 등고선을 여러 높이에 대해 그려라.',r'Draw several level curves of \(f='+F+r'\).'),[('f(x,y)=k를 세우고 y 또는 표준곡선 식으로 정리한다.','Set f(x,y)=k and rearrange as y(x) or a standard curve.')]+fs(L)+[(k,e)],(r'\('+L+r'\). '+k,r'\('+L+r'\). '+e))
add(53,(r'\(f=x^2+9y^2\)의 곡면과 등고선을 함께 그려 비교하라.',r'Draw and compare the graph and contours of \(f=x^2+9y^2\).'),fs(r'z=k\Rightarrow x^2+9y^2=k,\quad k\ge0')+[('높이가 커지면 타원의 반축은 √k와 √k/3으로 커진다. y방향 단면은 x방향보다 더 좁다.','As height grows, the semiaxes are √k and √k/3. The y-section is narrower than the x-section.')],('원점이 꼭짓점인 위로 열린 타원포물면; 동심 타원 등고선.','Upward elliptic paraboloid with vertex at the origin and concentric elliptical contours.'))
add(54,(r'\(f=\sqrt{36-9x^2-4y^2}\)의 곡면과 등고선을 함께 그려 비교하라.',r'Draw and compare the graph and contours of \(f=\sqrt{36-9x^2-4y^2}\).'),fs(r'9x^2+4y^2+z^2=36,\ z\ge0',r'z=k\Rightarrow9x^2+4y^2=36-k^2,\quad0\le k\le6'),('반축2,3,6인 타원체의 위쪽 절반. 높이가 증가하면 타원 등고선은 작아져 z=6에서 점이 된다.','Upper half of an ellipsoid with semiaxes2,3,6. Its contours shrink to a point at z=6.'))
add(55,(r'\(T=100/(1+x^2+2y^2)\)인 금속판의 등온선을 그려라.',r'Draw isotherms for a plate with \(T=100/(1+x^2+2y^2)\).'),fs(r'T=k\Rightarrow x^2+2y^2=100/k-1,\quad0<k\le100'),('중심 (0,0)의 타원. 예:k=20,25,50,100에서 우변은4,3,1,0; 중심 온도100이 가장 높다.','Concentric ellipses. For k=20,25,50,100, the right side is4,3,1,0; the center has maximum temperature100.'))
add(56,(r'양수 c,r에 대해 전위 \(V=c/\sqrt{r^2-x^2-y^2}\)의 등전위선을 그려라.',r'For c,r>0, draw equipotentials of \(V=c/\sqrt{r^2-x^2-y^2}\).'),fs(r'V=k\Rightarrow x^2+y^2=r^2-c^2/k^2,\quad k\ge c/r'),('원판 내부의 동심원. k=c/r은 중심 한 점이고, k→∞이면 반지름이 r에 아래쪽에서 접근한다. 경계 원은 정의역에 없다.','Concentric circles inside the disk. k=c/r gives the center; their radii approach r from below as k→∞. The boundary is excluded.'))
complexf={57:(r'xy^2-x^3','영등고선 x=0,y=±x에서 세 골짜기와 세 능선이 번갈아 만나는 monkey saddle.','A monkey saddle with three alternating valleys and ridges, separated by x=0 and y=±x.'),58:(r'xy^3-yx^3','영등고선 x=0,y=0,y=±x를 따라 네 골짜기와 네 능선이 만나는 dog saddle.','A dog saddle with four alternating valleys and ridges, separated by x=0,y=0,y=±x.'),59:(r'e^{-(x^2+y^2)/3}(\sin(x^2)+\cos(y^2))','좌표축에 대칭인 진동하는 봉우리·골짜기. 중심 높이1이고 진폭은 반지름 증가에 따라0으로 감쇠한다.','Oscillating peaks and valleys symmetric in each axis. The center has height1 and amplitudes decay to0 with radius.'),60:(r'\cos x\cos y','두 방향 주기2π의 교대 봉우리·골짜기. 범위[-1,1], 영등고선 x=π/2+kπ 또는 y=π/2+kπ.','Alternating peaks and valleys periodic by2π in each variable. Range[-1,1]; zeros on x=π/2+kπ or y=π/2+kπ.')}
for n,(F,k,e)in complexf.items():add(n,(r'\(f='+F+r'\)를 여러 범위·시점으로 그리고 등고선과 비교하라.',r'Graph \(f='+F+r'\) over several windows/viewpoints and compare with its contours.'),[('먼저 x=0,y=0 단면과 f=0 등고선을 찾고, 대칭성을 사용해 봉우리와 골짜기의 배치를 확인한다.','Inspect the x=0,y=0 traces and zero contours, then use symmetry to locate ridges and valleys.'),(k,e)],(k,e))
matches={61:(r'\sin(xy)','C','II','xy가 일정한 쌍곡선에서 값이 일정하고 축에서 멀어지면 진동이 촘촘해진다.','Values are constant on hyperbolas xy=constant, and oscillations tighten away from the axes.'),62:(r'e^x\cos y','A','IV','y방향의 주기적 진동이 x 증가에 따라 지수적으로 커진다.','Periodic y-oscillations grow exponentially as x increases.'),63:(r'\sin(x-y)','F','I','등고선 x-y=상수는 기울기1인 평행선이고 표면은 일정한 진폭의 평행 파동이다.','Contours x-y=constant are parallel lines of slope1, giving constant-amplitude parallel waves.'),64:(r'\sin x-\sin y','E','III','두 독립적인 사인파의 합으로 주기적 봉우리 격자가 나타난다.','Two independent sine waves produce a periodic lattice of peaks.'),65:(r'(1-x^2)(1-y^2)','B','VI','원점의 높이1, x=±1 또는 y=±1에서0, 네 모서리 방향으로 양의 큰 높이.','Height1 at the origin, zeros on x=±1 or y=±1, and large positive values toward the corners.'),66:(r'\frac{x-y}{1+x^2+y^2}','D','V','y=x에서0이고 양쪽에 봉우리와 골짜기가 있으며 먼 곳에서0으로 간다. k≠0의 등고선은 원이다.','Zero on y=x, with a peak and valley on opposite sides and decay to0 far away. Nonzero contours are circles.')}
for n,(F,G,C,k,e)in matches.items():add(n,(r'\(z='+F+r'\)를 원본의 (a)그래프 A–F, (b)등고선 I–VI와 대응시키고 이유를 설명하라.',r'Match \(z='+F+r'\) with (a) a source graph A–F and (b) a source contour map I–VI, with reasons.'),[(k,e)],(f'(a) {G}; (b) {C}. '+k,f'(a) {G}; (b) {C}. '+e),list('ab'))
levelsurf={67:(r'2y-z+1',r'z=2y+1-k','법선 (0,2,-1)이 같은 평행한 평면들.','Parallel planes with normal (0,2,-1).'),68:(r'x+y^2-z^2',r'x=k-y^2+z^2','x방향으로 평행이동한 쌍곡포물면.','Hyperbolic paraboloids translated in x.'),69:(r'x^2+y^2-z^2',r'x^2+y^2-z^2=k','k>0: 한 겹 쌍곡면; k=0: 이중원뿔; k<0: z축의 두 겹 쌍곡면.','k>0: one-sheet hyperboloid; k=0: double cone; k<0: two-sheet hyperboloid on the z-axis.'),70:(r'x^2+2y^2+3z^2',r'x^2+2y^2+3z^2=k','k>0: 반축 √k,√(k/2),√(k/3)의 타원체; k=0: 원점; k<0: 공집합.','k>0: ellipsoids with semiaxes √k,√(k/2),√(k/3); k=0: origin; k<0: empty.')}
for n,(F,L,k,e)in levelsurf.items():add(n,(r'\(f='+F+r'\)의 등위면을 설명하라.',r'Describe the level surfaces of \(f='+F+r'\).'),fs(L)+[('상수 k의 부호와 제곱항의 부호를 비교하여 표준 이차곡면과 대응시킨다.','Compare the signs of k and the squared terms with the standard quadric equations.'),(k,e)],(k,e))
b.save()
add(71,('g의 그래프를 f에서 얻는 변환을 설명하라. (a)g=f+2, (b)g=2f, (c)g=-f, (d)g=2-f.','Describe how to obtain the graph of g from f: (a)g=f+2, (b)g=2f, (c)g=-f, (d)g=2-f.'),[('입력 좌표 (x,y)는 같고 높이 z만 각각 z+2,2z,-z,2-z로 바뀐다.','The input (x,y) stays fixed while height z becomes z+2,2z,-z,2-z respectively.')],('(a)위로2 이동. (b)높이2배 확대. (c)xy평면에 반사. (d)xy평면에 반사 후 위로2 이동(평면 z=1에 반사).','(a)Translate up2. (b)Stretch heights by2. (c)Reflect across the xy-plane. (d)Reflect across the xy-plane, then shift up2 (equivalently reflect in z=1).'),list('abcd'))
add(72,('변환을 설명하라. (a)g(x,y)=f(x-2,y), (b)g(x,y)=f(x,y+2), (c)g(x,y)=f(x+3,y-4).','Describe the shifts: (a)g(x,y)=f(x-2,y), (b)g(x,y)=f(x,y+2), (c)g(x,y)=f(x+3,y-4).'),[('원래 점 (a,b,f(a,b))가 새 곡면에서 같은 높이를 갖게 되는 입력 좌표를 역으로 푼다.','Solve for the new input coordinates that retain the height at an original point (a,b,f(a,b)).')]+fs(r'(a,b)\mapsto(a+2,b),\quad(a,b-2),\quad(a-3,b+4)'),('평행이동 벡터는 (a)(2,0,0), (b)(0,-2,0), (c)(-3,4,0).','Translation vectors: (a)(2,0,0), (b)(0,-2,0), (c)(-3,4,0).'),list('abc'))
add(73,(r'\(f=3x-x^4-4y^2-10xy\)를 여러 시점으로 그리고 최대값, 국소최대·최소를 조사하라.',r'Graph \(f=3x-x^4-4y^2-10xy\) from several viewpoints and investigate global/local maxima and local minima.'),fs(r'f=-4(y+5x/4)^2-x^4+25x^2/4+3x',r'f_y=0\Rightarrow y=-5x/4,\quad f_x=0\Rightarrow4x^3-25x/2-3=0')+[('세 실근은 약 -1.632676,-0.244688,1.877364이다. 끝의 두 점에서 x방향 2계도함수 -12x²+12.5가 음수이고 가운데는 양수이다. y방향은 항상 아래로 굽는다.','The three roots are about -1.632676,-0.244688,1.877364. The reduced x-second derivative -12x²+12.5 is negative at the outer roots and positive at the middle root; the y-direction always curves downward.'),('완전제곱식에서 무한대 방향으로 f→-∞이고, 두 국소최대값을 비교하면 15.2381이 더 크다.','The completed-square form gives f→-∞ at infinity. Comparing the two local maxima identifies15.2381 as the global maximum.')],('국소최대: (-1.632676,2.040845,4.656577), (1.877364,-2.346705,15.238120). 두 번째가 전역최대. 국소최소 없음; (-0.244688,0.305860)은 안장점.','Local maxima: (-1.632676,2.040845,4.656577) and (1.877364,-2.346705,15.238120); the latter is global. No local minima. (-0.244688,0.305860) is a saddle.'))
add(74,(r'\(f=xye^{-x^2-y^2}\)의 그래프를 그리고 최대·최소 및 국소극값을 조사하라.',r'Graph \(f=xye^{-x^2-y^2}\) and investigate global/local extrema.'),fs(r'f_x=ye^{-r^2}(1-2x^2),\quad f_y=xe^{-r^2}(1-2y^2)',r'|xy|\le r^2/2\Rightarrow|f|\le\tfrac12r^2e^{-r^2}\le\frac1{2e}')+[('등호에는 r²=1, |x|=|y|가 필요하다. 원점 주변에서는 xy의 부호가 달라져 안장점이다.','Equality requires r²=1 and |x|=|y|. Near the origin the sign changes with xy, making it a saddle.')],(r'최대 (1/(2e)): ((1/sqrt2,1/sqrt2),(-1/sqrt2,-1/sqrt2)). 최소 (-1/(2e)): 부호가 반대인 두 점. 모두 국소극값이기도 하다.',r'Maximum (1/(2e)) at the two equal-sign pairs ((pm1/sqrt2,pm1/sqrt2)); minimum (-1/(2e)) at the two opposite-sign pairs. All are local extrema as well.'))
add(75,(r'\(f=(x+y)/(x^2+y^2)\)를 여러 범위에서 그리고 무한대 및 원점 부근의 거동을 설명하라.',r'Graph \(f=(x+y)/(x^2+y^2)\) over several windows and describe behavior at infinity and near the origin.'),fs(r'|f|\le\frac{\sqrt2}{\sqrt{x^2+y^2}}\longrightarrow0\quad(r\to\infty)',r'f(t,0)=1/t,\quad f(t,-t)=0'),('반지름이 무한대로 가면0. 원점에서는 경로에 따라 발산하거나0이므로 극한이 없고 위·아래로 모두 유계가 아니다.','The function tends to0 as radius tends to infinity. At the origin it diverges along some paths and equals0 on another, so it has no limit and is unbounded above and below.'))
add(76,(r'\(f=xy/(x^2+y^2)\)를 그리고 무한대 및 원점 부근의 거동을 조사하라.',r'Graph \(f=xy/(x^2+y^2)\) and investigate behavior at infinity and near the origin.'),fs(r'f(r\cos\theta,r\sin\theta)=\tfrac12\sin2\theta,\quad |f|\le1/2',r'f(t,t)=1/2,\quad f(t,2t)=2/5,\quad f(t,0)=0'),('반지름과 무관하고 방향에만 의존한다. 원점 극한도 무한대의 공통 극한도 없다. 두 변수 모두 커지는 경우에도 y=x와 y=2x가 서로 다른 값을 준다.','The value depends only on direction, not radius. There is no common limit at the origin or at infinity; even when both variables grow, y=x and y=2x give different values.'))
add(77,(r'\(f=e^{cx^2+y^2}\)의 모양이 c에 따라 어떻게 변하는지 그래프로 조사하라.',r'Investigate with graphs how \(f=e^{cx^2+y^2}\) depends on c.'),fs(r'\ln z=cx^2+y^2,\quad z>0')+[('c>0이면 두 방향 모두 위로 휘며 중심 최소1인 타원형 그릇이고 c가 클수록 x방향이 좁다. c=1은 회전대칭이다.','For c>0 both directions curve upward, giving an elliptic bowl with minimum1; larger c narrows it in x. c=1 is rotationally symmetric.'),('c=0이면 x와 무관한 z=e^(y²) 기둥이다. c<0이면 x방향은0으로 내려가고 y방향은 위로 올라가 원점 높이1에서 안장 모양이다.','For c=0 this is the cylinder z=e^(y²). For c<0 it decays toward0 in x and rises in y, producing a saddle near height1 at the origin.')],('전이 c=0. 양수: 타원형 그릇; 0: 기둥; 음수: 안장.','Transition at c=0: positive gives an elliptic bowl, zero a cylinder, negative a saddle.'))
add(78,(r'\(z=(ax^2+by^2)e^{-x^2-y^2}\)의 모양이 a,b에 따라 어떻게 변하는지 조사하고 대표 그래프를 그려라.',r'Investigate how \(z=(ax^2+by^2)e^{-x^2-y^2}\) depends on a,b and plot representative cases.'),fs(r'z=r^2e^{-r^2}(a\cos^2\theta+b\sin^2\theta),\quad r^2e^{-r^2}\le e^{-1}')+[('각 방향에서 값의 부호는 a cos²θ+b sin²θ로 정해진다. 모든 곡면은 원점에서0이고 먼 곳에서도0으로 간다.','In each direction the sign is that of a cos²θ+b sin²θ. Every surface is0 at the origin and tends to0 at infinity.'),('둘 다 양수이면 양의 언덕, 둘 다 음수이면 뒤집힌 음의 골짜기. a=b≠0이면 r=1에 둥근 최대/최소 능선이 생긴다. 서로 다른 양수라면 더 큰 계수의 축 ±1에서 최대이며 다른 축의 r=1은 안장이다.','Two positive coefficients give positive hills; two negative ones reverse the picture. If a=b≠0, r=1 is a circular extremal ridge. For unequal positive coefficients, maxima lie at ±1 on the larger-coefficient axis; the other axis gives saddles.'),('부호가 반대이면 양의 계수 축에서 두 봉우리, 음의 축에서 두 골짜기가 생긴다. 하나가0이면 그 축 전체 높이가0이며, 둘 다0이면 평면이다.','Opposite signs give two peaks along the positive-coefficient axis and two valleys along the negative one. A zero coefficient gives a zero-height axis; both zero give a plane.')],(r'전역 상한 (max(0,a,b)/e), 하한 (min(0,a,b)/e). 0은 원점에서 실제로 달성된다. 모양은 부호와 크기 비교로 결정된다.',r'Global maximum (max(0,a,b)/e) and minimum (min(0,a,b)/e); zero is attained at the origin. Signs and relative magnitudes determine the shape.'))
add(79,(r'\(z=x^2+y^2+cxy\)를 조사하고 이차곡면 유형이 달라지는 c를 구하라.',r'Investigate \(z=x^2+y^2+cxy\) and identify the values where its quadric type changes.'),fs(r'u=(x+y)/\sqrt2,\quad v=(x-y)/\sqrt2',r'z=(1+c/2)u^2+(1-c/2)v^2')+[('두 계수가 양수이면 타원포물면, 하나가0이면 포물기둥, 부호가 반대이면 쌍곡포물면이다. c=0에서는 두 계수가 같아 특별히 회전포물면이다.','Two positive coefficients give an elliptic paraboloid, one zero gives a parabolic cylinder, and opposite signs give a hyperbolic paraboloid. At c=0 it is specifically a circular paraboloid.')],('|c|<2: 타원포물면(c=0은 회전형); c=±2: 포물기둥; |c|>2: 쌍곡포물면. 유형 전이는 ±2, 회전대칭 특별값은0.','|c|<2: elliptic paraboloid (c=0 circular); c=±2: parabolic cylinder; |c|>2: hyperbolic paraboloid. Type transitions occur at±2, with the rotationally symmetric special case0.'))
add(80,(r'\(r=\sqrt{x^2+y^2}\)로 두고 z=r,e^r,ln r,sin r,1/r을 그려라. 일반적인 z=g(r)는 일변수 그래프에서 어떻게 얻는가?',r'Let \(r=\sqrt{x^2+y^2}\). Plot z=r,e^r,ln r,sin r,1/r, and explain how to obtain z=g(r) from a one-variable graph.'),[('r≥0인 반쪽 곡선 z=g(r)를 수직 z축 둘레로 회전시킨다. ln r,1/r에서는 r=0을 제외한다.','Revolve the half-curve z=g(r), r≥0, around the vertical z-axis. Exclude r=0 for ln r and1/r.'),('r은 원뿔, e^r은 높이1에서 급하게 올라가는 회전면, ln r은 원점에서-∞로 내려가는 깔때기, sin r은 동심원 파동, 1/r은 중심에서+∞로 올라가 먼 곳에서0인 회전면이다.','r gives a cone; e^r rises from height1; ln r is a funnel descending to-∞ at the center; sin r gives concentric waves;1/r rises to+∞ at the center and decays to0 far away.')],('z=g(r)의 r≥0 부분을 z축 둘레로 회전한 곡면이며, 모든 등고선은 해당 반지름의 원(또는 여러 원)이다.','Revolve the r≥0 part of z=g(r) about the z-axis; each level set is a circle or a collection of circles at the corresponding radii.'))
raw=[[100,100,100],[101,105,107],[112,110,114],[122,117,122],[124,122,131],[122,121,138],[143,125,149],[152,134,163],[151,140,176],[126,123,185],[155,143,198],[159,147,208],[153,148,216],[177,155,226],[184,156,236],[169,152,244],[189,156,266],[225,183,298],[227,198,335],[223,201,366],[218,196,387],[231,194,407],[179,146,417],[240,161,431]]
xs=[log(L/K)for P,L,K in raw];ys=[log(P/K)for P,L,K in raw];xm=sum(xs)/24;ym=sum(ys)/24;alpha=sum((x-xm)*(y-ym)for x,y in zip(xs,ys))/sum((x-xm)**2 for x in xs);inter=ym-alpha*xm
rt=table([[1899+i]+row for i,row in enumerate(raw)],['Year','P','L','K']);lt=table([[1899+i,f'{x:.6f}',f'{y:.6f}']for i,(x,y)in enumerate(zip(xs,ys))],['Year','ln(L/K)','ln(P/K)'])
add(81,('Cobb–Douglas 함수 P=bL^αK^(1-α)에 대해 (a) ln(P/K)=ln b+αln(L/K)를 보이라. (b) 아래1899–1922년 자료를 로그변환하고 최소제곱 직선을 구하라. (c) P≈1.01L^.75K^.25를 얻어라.'+rt,'For P=bL^αK^(1-α), (a) prove ln(P/K)=ln b+αln(L/K); (b) log-transform the1899–1922 data below and fit a least-squares line; (c) obtain P≈1.01L^.75K^.25.'+rt),fs(r'\ln(P/K)=\ln b+\alpha\ln L+(1-\alpha)\ln K-\ln K=\ln b+\alpha\ln(L/K)')+[(lt,lt)]+fs(r'\widehat\alpha=\frac{\sum(x_i-\bar x)(y_i-\bar y)}{\sum(x_i-\bar x)^2}='+f'{alpha:.8f}',r'\widehat\beta=\bar y-\widehat\alpha\bar x='+f'{inter:.8f}',r'\widehat b=e^{\widehat\beta}='+f'{exp(inter):.8f}'),(f'회귀식 y≈{alpha:.6f}x+{inter:.6f}. 따라서 P≈{exp(inter):.6f}L^{alpha:.6f}K^{1-alpha:.6f}≈1.01L^.75K^.25.',f'Fit: y≈{alpha:.6f}x+{inter:.6f}. Thus P≈{exp(inter):.6f}L^{alpha:.6f}K^{1-alpha:.6f}≈1.01L^.75K^.25.'),list('abc'))
M=lambda f:fs(f)[0][0]
b.E[3]['answer']=pair('(a) '+M('9\\ln4')+'(b) y>-x, 경계 제외. (c) '+M('\\mathbb R'),'(a) '+M('9\\ln4')+'(b) y>-x, boundary excluded. (c) '+M('\\mathbb R'))
b.E[4]['answer']=pair(M(r'(a)\ e;\quad(b)\ y\ge x^2;\quad(c)\ [1,\infty)'))
b.E[74]['answer']=pair(M(r'f_{max}=1/(2e),\quad f_{min}=-1/(2e),\quad |x|=|y|=1/\sqrt2')+'최대는 두 좌표의 부호가 같은 곳, 최소는 반대인 곳이며 각각 국소극값이기도 하다.',M(r'f_{max}=1/(2e),\quad f_{min}=-1/(2e),\quad |x|=|y|=1/\sqrt2')+'Equal signs give the maxima; opposite signs give the minima. All are also local extrema.')
b.E[78]['answer']=pair(M(r'f_{max}=\max(0,a,b)/e,\quad f_{min}=\min(0,a,b)/e')+'0은 원점에서 달성된다. 모양은 계수의 부호와 크기 비교로 결정된다.',M(r'f_{max}=\max(0,a,b)/e,\quad f_{min}=\min(0,a,b)/e')+'Zero is attained at the origin. Signs and relative magnitudes determine the shape.')

b.save()
