import json,math,html,sys,re
from pathlib import Path
import sympy as S
import mpmath as mp
BASE=Path(__file__).resolve().parents[1];items=[];mp.mp.dps=60;x=S.symbols('x',real=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 p=311 if q<=7 else 312 if q<=15 else 313 if q<=32 else 314
 st=[M(t)for t in lines];items.append(dict(id=f'stewart9-exercise-4.1-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('넓이와 거리의 합 근사','Area and distance approximations'),statement=bi(M(eq)+' '+tk,M(eq)+' '+te),hint=bi('구간의 폭과 표본점의 높이를 곱하여 합하고, 증가·감소에 따라 상하합을 구별한다.','Sum interval width times sample height, using monotonicity to distinguish lower and upper sums.'),steps=bi(st+([k]if k else[]),st+([e]if e else[])),answer=bi(M(ans)),check=bi('극한의 방향·정의역·부호를 확인하고 식 또는 도형의 조건을 대조했다.','Limit direction, domain, and signs were checked against the formula or geometric conditions.'),conceptHref='../../calc1/index.html',status='math-verified'))
i,n=S.symbols('i n',integer=True,positive=True)
def addfig(q,svg,caption=None):
 p=BASE/f'exercise-content/assets/s4-1-{q}.svg';p.write_text(svg);ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('함수와 넓이 근사 직사각형의 자체 도해','Original illustration of a function and its approximating rectangles'),'caption':caption or bi('표시한 함수 또는 원문 그림에서 읽은 표본값으로 직접 그린 직사각형.','Rectangles drawn directly from the stated function or samples read from the source graph.')}
def rectplot(q,fn,a,b,cases,ylim=None,caption=None):
 a,b=float(a),float(b);samples=[float(fn(a+(b-a)*j/500))for j in range(501)];height=430*len(cases);out=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 660 {height}"><rect width="660" height="{height}" fill="white"/>'];ymax=(max(samples)*1.13 or 1)if ylim is None else ylim
 for k,(N,mode)in enumerate(cases):
  off=k*430;dx=(b-a)/N;X=lambda z:60+550*(z-a)/(b-a);Y=lambda z:off+350-300*z/ymax
  out.append(f'<text x="60" y="{off+25}" font-size="16">{mode}, n={N}, width={(b-a)/N:.5g}</text><path d="M60 {off+45}V{off+350}H620" stroke="#8090a3" fill="none"/>')
  for j in range(N):
   lo=a+j*dx;hi=lo+dx
   if mode=='L':z=lo
   elif mode=='R':z=hi
   elif mode=='M':z=(lo+hi)/2
   else:
    candidates=[lo,hi]+([0]if lo<0<hi else[]);z=(max if mode=='upper'else min)(candidates,key=fn)
   v=float(fn(z));out.append(f'<rect x="{X(lo):.4f}" y="{Y(v):.4f}" width="{X(hi)-X(lo):.4f}" height="{Y(0)-Y(v):.4f}" fill="#b9d6ef" fill-opacity=".62" stroke="#5b8cb6" stroke-width=".8"/>')
  pts=' '.join(f'{X(a+(b-a)*j/500):.3f},{Y(samples[j]):.3f}'for j in range(501));out.append(f'<polyline points="{pts}" fill="none" stroke="#b8443d" stroke-width="2.4"/>')
  for j in range(5):
   xx=a+(b-a)*j/4;yy=ymax*j/4;out.append(f'<text x="{X(xx)-12}" y="{off+373}" font-size="11">{xx:.4g}</text><text x="5" y="{Y(yy)+4}" font-size="10">{yy:.4g}</text>')
  out.append(f'<text x="60" y="{off+411}" font-size="12">Blue: approximating rectangles. Red: function or sample interpolant.</text>')
 out.append('</svg>');addfig(q,''.join(out),caption)
def interp(vals,step=1,start=0):
 def f(z):
  t=(float(z)-start)/step;j=min(len(vals)-2,max(0,int(math.floor(t))));return vals[j]+(vals[j+1]-vals[j])*(t-j)
 return f
def sums(f,a,b,N,kind):
 dx=(b-a)/N
 if kind in ['L','R','M']:return S.simplify(dx*sum(f.subs(x,a+(j+({'L':0,'R':1,'M':S.Rational(1,2)}[kind]))*dx)for j in range(N)))
 return S.simplify(dx*sum((max if kind=='upper'else min)([f.subs(x,a+j*dx),f.subs(x,a+(j+1)*dx)]+([f.subs(x,0)]if a+j*dx<0<a+(j+1)*dx else[]))for j in range(N)))
def numtext(z):return f'{float(z):.9f}'
v1=[5,4,3.15,2.4,1.75,1.2,.8,.5,.25,.1,0];f1=interp(v1)
l5=2*sum(v1[j]for j in range(2,11,2));u5=2*sum(v1[j]for j in range(0,10,2));l10=sum(v1[1:]);u10=sum(v1[:-1])
calc(1,r'x=0,1,\ldots,10;\quad f(x)\approx(5,4,3.15,2.4,1.75,1.2,0.8,0.5,0.25,0.1,0)','감소하는 원문 그래프를 표본 높이로 나타냈다. (a) 직사각형 다섯 개 (b) 열 개로 넓이의 하한·상한을 추정하고 각각 그려라.','The decreasing source graph is represented by the sampled heights. Estimate lower and upper areas using (a) five and (b) ten rectangles, illustrating each.',[r'\Delta x=10/n;\quad\text{decreasing }f\Rightarrow R_n\le A\le L_n',rf'\text{{(a)}}\quad R_5={l5:.3f},\quad L_5={u5:.3f}',rf'\text{{(b)}}\quad R_{{10}}={l10:.3f},\quad L_{{10}}={u10:.3f}'],rf'\text{{(a)}}\quad A\approx[{l5:.2f},{u5:.2f}];\quad\text{{(b)}}\quad A\approx[{l10:.2f},{u10:.2f}]','그림에서 읽은 높이는 근삿값이므로 최종 숫자도 판독 오차를 포함한 추정이다. 직사각형 개수가 늘면 상하합 사이의 폭이 줄어든다.','Heights read from the graph are approximate, so the resulting numbers include reading uncertainty. More rectangles narrow the lower–upper gap.',sub='ab');rectplot(1,f1,0,10,[(5,'R'),(5,'L'),(10,'R'),(10,'L')])
v2=[9,8.9,8.8,8.5,8.2,7.8,7.2,6.6,5.9,5,4,2.7,1];f2=interp(v2);L2=2*sum(v2[0:12:2]);R2=2*sum(v2[2:13:2]);M2=2*sum(v2[1:12:2])
calc(2,r'x=0,1,\ldots,12;\quad f(x)\approx(9,8.9,8.8,8.5,8.2,7.8,7.2,6.6,5.9,5,4,2.7,1)','감소하는 원문 곡선에서 (a) 여섯 구간의 왼끝·오른끝·중점합 (b,c) 상하 추정 여부 (d) 가장 좋은 추정을 구하라.','For the decreasing source curve, find (a) six-interval left, right, and midpoint estimates, (b,c) which are upper or lower, and (d) the best estimate.',[r'\Delta x=2,\quad L_6=2\sum_{j=0}^5f(2j),\quad R_6=2\sum_{j=1}^6f(2j),\quad M_6=2\sum_{j=0}^5f(2j+1)',rf'L_6\approx{L2:.3f},\quad R_6\approx{R2:.3f},\quad M_6\approx{M2:.3f}'],rf'\text{{(a)}}\quad(L_6,R_6,M_6)\approx({L2:.2f},{R2:.2f},{M2:.2f});\quad\text{{(b)}}\ L_6\text{{ upper}};\quad\text{{(c)}}\ R_6\text{{ lower}};\quad\text{{(d)}}\ M_6','중점 직사각형은 각 구간의 높이 오차가 더 잘 상쇄되어 그림에서는 가장 가까운 추정으로 보인다. 표본 높이를 반올림했으므로 답에는 약간의 판독 차이가 가능하다.','Midpoint heights balance interval errors better and appear closest for this smooth graph. Rounded graph readings allow small variation in the numerical estimates.',sub='abcd');rectplot(2,f2,0,12,[(6,'L'),(6,'R'),(6,'M')])
for q,f,a,b in [(3,1/x,S.Integer(1),S.Integer(2)),(4,S.sin(x),S.Integer(0),S.pi/2)]:
 rs=sums(f,a,b,4,'R');ls=sums(f,a,b,4,'L');direction='decreasing'if q==3 else'increasing'
 calc(q,rf'f(x)={S.latex(f)},\quad {S.latex(a)}\le x\le{S.latex(b)},\quad n=4','(a) 오른끝합과 그림, 과소·과대 여부 (b) 왼끝합으로 같은 작업을 하라.','(a) Compute and draw the right-endpoint estimate, identifying under/overestimation, and (b) repeat with left endpoints.',[rf'\Delta x={S.latex((b-a)/4)},\quad R_4=\Delta x\sum_{{i=1}}^4f(a+i\Delta x)',rf'R_4={S.latex(rs)}\approx{numtext(rs)},\quad L_4={S.latex(ls)}\approx{numtext(ls)}'],rf'\text{{(a)}}\ R_4={S.latex(rs)}\text{{ '+('underestimate'if q==3 else'overestimate')+r'};\quad\text{(b)}\ L_4='+S.latex(ls)+r'\text{ '+('overestimate'if q==3 else'underestimate')+'}','함수의 단조성으로 각 직사각형과 곡선의 높이를 비교한다.','Monotonicity compares each rectangle’s height with the function.',sub='ab');rectplot(q,S.lambdify(x,f,'math'),a,b,[(4,'R'),(4,'L')])
f=1+x*x;vals={(N,k):sums(f,S.Integer(-1),S.Integer(2),N,k)for N in[3,6]for k in['R','L','M']}
calc(5,r'f(x)=1+x^2,\quad-1\le x\le2','(a) 오른끝 (b) 왼끝 (c) 중점으로 각각 직사각형 세 개와 여섯 개의 근사와 그림을 구하고 (d) 가장 정확한 것을 고르라.','Compute and draw three- and six-rectangle estimates using (a) right, (b) left, and (c) midpoint samples; (d) choose the most accurate.',[rf'{k}_{{{N}}}={S.latex(v)}'for (N,k),v in vals.items()]+[r'A=6\quad\text{(independent exact-area check)}'],r'R_3=8,\ R_6=55/8;\quad L_3=5,\ L_6=43/8;\quad M_3=23/4,\ M_6=95/16;\quad\text{best }M_6','중점 근사는 일반적으로 오차가 잘 상쇄되며, 이 예에서도 여섯 개 중점 직사각형이 가장 가깝다.','Midpoint sampling is generally effective, and the six-rectangle midpoint value is closest here.',sub='abcd');rectplot(5,lambda z:1+z*z,-1,2,[(N,k)for k in['R','L','M']for N in[3,6]])
f=1/(1+x*x);vals={(N,k):sums(f,S.Integer(-2),S.Integer(2),N,k)for N in[4,8]for k in['R','M']}
calc(6,r'f(x)=1/(1+x^2),\quad-2\le x\le2','(a) 함수 그래프 (b) 네 직사각형의 오른끝·중점합과 그림 (c) 여덟 직사각형으로 개선하라.','(a) Plot the function, (b) compute and draw four-rectangle right and midpoint estimates, and (c) improve using eight rectangles.',[r'f\text{ is even, maximal at zero, and decreases as }|x|\text{ grows}']+[rf'{k}_{{{N}}}={S.latex(v)}\approx{numtext(v)}'for (N,k),v in vals.items()],r';\quad '.join(rf'{k}_{{{N}}}\approx{numtext(v)}'for(N,k),v in vals.items()),sub='abc');rectplot(6,lambda z:1/(1+z*z),-2,2,[(N,k)for N in[4,8]for k in['R','M']])
for q,f,a,b,counts in [(7,6-x*x,S.Integer(-2),S.Integer(2),[2,4,8]),(8,1+S.cos(x/2),-S.pi,S.pi,[3,4,6])]:
 vals={(N,k):sums(f,a,b,N,k)for N in counts for k in['lower','upper']}
 calc(q,rf'f(x)={S.latex(f)},\quad{S.latex(a)}\le x\le{S.latex(b)},\quad n\in\{{'+','.join(str(j)for j in counts)+r'\}','지정 구간 수마다 구간별 최소·최대 높이로 하합·상합을 구하고 도해로 나타내라.','For each specified interval count, use the minimum and maximum heights on every interval to compute and draw lower and upper sums.',[r'\Delta x=(b-a)/n;\quad\text{include the maximum at }x=0\text{ when an interval contains zero}']+[rf'{k}_{{{N}}}={S.latex(v)}\approx{numtext(v)}'for(N,k),v in vals.items()],r';\quad '.join(rf'{k}_{{{N}}}={S.latex(v)}'for(N,k),v in vals.items()));rectplot(q,S.lambdify(x,f,'math'),a,b,[(N,k)for N in counts for k in['lower','upper']])
v9=[0,6.2,10.8,14.9,18.1,19.4,20.2];low=.5*sum(v9[:-1]);up=.5*sum(v9[1:])
calc(9,r't=(0,0.5,1,1.5,2,2.5,3)\ \mathrm s;\quad v=(0,6.2,10.8,14.9,18.1,19.4,20.2)\ \mathrm{ft/s}','속력이 계속 증가하는 달리기 선수의 첫 삼 초 이동거리의 하한·상한을 추정하라.','Estimate lower and upper bounds for the first three seconds of travel when the runner’s speed increases throughout.',[r'\Delta t=0.5\ \mathrm s;\quad L=0.5\sum_{i=0}^5v_i,\quad R=0.5\sum_{i=1}^6v_i',rf'L={low:.3f}\ \mathrm{{ft}},\quad R={up:.3f}\ \mathrm{{ft}}'],rf'{low:.2f}\le d\le{up:.2f}\ \mathrm{{ft}}')
v10=[182.9,168,106.6,99.8,124.5,176.1,175.6];left=sum(v10[:-1])/360;right=sum(v10[1:])/360
calc(10,r't=(0,10,20,30,40,50,60)\ \mathrm s;\quad v=(182.9,168.0,106.6,99.8,124.5,176.1,175.6)\ \mathrm{mi/h}','경주 차량의 일 분 이동거리를 (a) 시작 속력 (b) 끝 속력으로 추정하고 (c) 상한·하한 여부를 논하라.','Estimate the car’s one-minute distance using (a) initial and (b) final speeds on each interval, and (c) discuss whether these are bounds.',[r'\Delta t=10/3600=1/360\ \mathrm h',rf'L={left:.9f}\ \mathrm{{mi}},\quad R={right:.9f}\ \mathrm{{mi}}'],rf'\text{{(a)}}\ {left:.6f}\ \mathrm{{mi}};\quad\text{{(b)}}\ {right:.6f}\ \mathrm{{mi}};\quad\text{{(c)}}\ \text{{neither is guaranteed to be a bound}}','속력이 감소했다 증가하는 등 한 방향으로만 변하지 않는다. 구간 사이의 실제 거동도 표만으로 확정되지 않아 한쪽 합을 전체 상한이나 하한으로 단정할 수 없다.','Speed changes direction rather than remaining monotone. The readings also do not determine behavior between samples, so neither endpoint sum is guaranteed as a global bound.',sub='abc')
rates=[8.7,7.6,6.8,6.2,5.7,5.3];low=2*sum(rates[1:]);up=2*sum(rates[:-1])
calc(11,r't=(0,2,4,6,8,10)\ \mathrm h;\quad r=(8.7,7.6,6.8,6.2,5.7,5.3)\ \mathrm{L/h}','누출률이 계속 감소할 때 십 시간 동안 누출된 양의 하한·상한을 추정하라.','Estimate lower and upper amounts leaked over ten hours when the leakage rate decreases throughout.',[r'\Delta t=2\ \mathrm h;\quad R_5=2\sum_{i=1}^5r_i,\quad L_5=2\sum_{i=0}^4r_i',rf'R_5={low:.4f},\quad L_5={up:.4f}'],rf'{low:.2f}\le Q\le{up:.2f}\ \mathrm L')
t12=[0,10,15,20,32,59,62];v12=[0,185,319,447,742,1325,1445];lo=sum((b-a)*v12[j]for j,(a,b)in enumerate(zip(t12,t12[1:])));hi=sum((b-a)*v12[j+1]for j,(a,b)in enumerate(zip(t12,t12[1:])));trap=(lo+hi)/2
calc(12,r't=(0,10,15,20,32,59,62)\ \mathrm s;\quad v=(0,185,319,447,742,1325,1445)\ \mathrm{ft/s}','간격이 고르지 않은 우주왕복선 속도 자료로 발사 후 육십이 초의 높이를 추정하라.','Estimate height sixty-two seconds after launch from unequally spaced shuttle velocity measurements.',[r'\Delta t=(10,5,5,12,27,3)\ \mathrm s',rf'L=\sum v_{{i-1}}\Delta t_i={lo}\ \mathrm{{ft}},\quad R=\sum v_i\Delta t_i={hi}\ \mathrm{{ft}}',rf'T=\sum\frac{{v_{{i-1}}+v_i}}2\Delta t_i=(L+R)/2={trap:.1f}\ \mathrm{{ft}}'],rf'h(62)\approx{trap:.1f}\ \mathrm{{ft}}','구간별 선형 보간을 가정한 사다리꼴 추정이다. 각 구간에서 속도가 증가한다고 가정하면 두 끝점합이 상하 추정을 준다. 뒤의 백이십오 초 자료는 이 시간까지의 높이에 쓰지 않는다.','This trapezoidal estimate uses linear interpolation on each interval. If velocity increases within each interval, the endpoint sums give lower and upper estimates. The later one-hundred-twenty-five-second reading is not used for this height.')
# Read graph midpoints; connect them only as an original visualization of the estimates.
v13=[56,40,28,18,10,3];v14=[30,65,87,103,113,119]
for q,vals,step,unit,conversion,eq in [(13,v13,1,'ft',1,r't_i^*=(0.5,1.5,2.5,3.5,4.5,5.5)\ \mathrm s;\quad v_i\approx(56,40,28,18,10,3)\ \mathrm{ft/s}'),(14,v14,5,'km',3600,r't_i^*=(2.5,7.5,12.5,17.5,22.5,27.5)\ \mathrm s;\quad v_i\approx(30,65,87,103,113,119)\ \mathrm{km/h}')]:
 val=step*sum(vals)/conversion;calc(q,eq,'원문 속도 그래프에서 읽은 중점 높이로 이동거리를 추정하라.','Estimate travel distance from midpoint heights read from the source velocity graph.',[rf'\Delta t={step}/{conversion}\ \mathrm{{'+('h'if q==14 else's')+r'}',rf'd\approx\Delta t\sum v_i={val:.9f}\ \mathrm{{{unit}}}'],rf'd\approx{val:.6f}\ \mathrm{{{unit}}}'+(rf'={1000*val:.3f}\ \mathrm m'if q==14 else''),'속도 곡선 아래 넓이가 이동거리이다. 곡선을 읽는 정확도에 따라 비슷한 범위의 다른 추정도 가능하다.','Distance is the area under the speed curve. Similar estimates may differ slightly with graph-reading precision.');allvals=([70]+vals+[0])if q==13 else([0]+vals+[120]);times=[0]+[(j+.5)*step for j in range(6)]+[6*step]
 def curve(z,ts=times,vs=allvals):
  j=next((j for j in range(len(ts)-1)if ts[j]<=z<=ts[j+1]),len(ts)-2);return vs[j]+(vs[j+1]-vs[j])*(z-ts[j])/(ts[j+1]-ts[j])
 rectplot(q,curve,0,6*step,[(6,'M')])
f=-x*(x-21)*(x+1);total=sums(f,S.Integer(0),S.Integer(12),6,'M')
calc(15,r'N(t)=-t(t-21)(t+1),\quad0\le t\le12','주어진 감염 세포 밀도 모형의 누적량을 여섯 구간의 중점합으로 추정하라.','Estimate cumulative infected-cell density over time using six midpoint subintervals of the stated model.',[r'\Delta t=2,\quad t_i^*=1,3,5,7,9,11',r'M_6=2[N(1)+N(3)+N(5)+N(7)+N(9)+N(11)]',rf'M_6={S.latex(total)}'],S.latex(total)+r'\ \text{infected-cell density}\cdot\text{day}','단위는 혈장 부피당 감염세포 수에 시간을 곱한 것이다. 문제에서 제시한 다항식 모형을 사용한 계산이다.','Units are infected cells per plasma volume times days. The calculation uses the polynomial model stated in the exercise.');rectplot(15,S.lambdify(x,f,'math'),0,12,[(6,'M')])
for q,f,a,b in [(16,2*x/(x*x+1),1,3),(17,2+S.sin(x)**2,0,S.pi),(18,x*x+S.sqrt(1+2*x),4,7),(19,x*S.sqrt(x**3+8),1,5)]:
 dx=(S.sympify(b)-a)/n;xi=a+i*dx;term=S.simplify(dx*f.subs(x,xi));calc(q,rf'f(x)={S.latex(f)},\quad{S.latex(a)}\le x\le{S.latex(b)}','넓이를 오른끝 리만합의 극한으로 나타내되 극한을 계산하지 마라.','Express the area as a limit of right-endpoint Riemann sums without evaluating it.',[rf'\Delta x={S.latex(dx)},\quad x_i={S.latex(xi)}'],r'A=\lim_{n\to\infty}\sum_{i=1}^n '+S.latex(term))
for q,expr,fn,a,b in [(20,r'\lim_{n\to\infty}\sum_{i=1}^n\frac1n(i/n)^5',r'x^5',0,1),(21,r'\lim_{n\to\infty}\sum_{i=1}^n\frac2n\frac1{1+2i/n}',r'1/(1+x)',0,2),(22,r'\lim_{n\to\infty}\sum_{i=1}^n\frac3n\sqrt{1+3i/n}',r'\sqrt{1+x}',0,3),(23,r'\lim_{n\to\infty}\sum_{i=1}^n\frac\pi{4n}\tan(i\pi/(4n))',r'\tan x',0,r'\pi/4')]:
 bs=str(b);calc(q,expr,'극한을 계산하지 말고 이 넓이를 갖는 평면 영역을 하나 찾아라.','Identify one plane region whose area equals the limit, without evaluating it.',[r'\Delta x=(b-a)/n,\quad x_i=a+i\Delta x',r'f(x)='+fn+r',\quad a=0,\quad b='+bs],r'\{(x,y):0\le x\le'+bs+r',\quad0\le y\le '+fn+r'\}')
calc(24,r'f(x)=x^3,\quad0\le x\le1','(a) 넓이의 합 극한을 쓰고 (b) 세제곱 합 공식으로 계산하라.','(a) Express area as a sum limit and (b) evaluate it using the sum-of-cubes formula.',[r'R_n=\frac1n\sum_{i=1}^n(i/n)^3=\frac1{n^4}\sum_{i=1}^ni^3',r'\sum_{i=1}^ni^3=[n(n+1)/2]^2',r'R_n=(n+1)^2/(4n^2)\to1/4'],r'\text{(a)}\ A=\lim_{n\to\infty}\frac1{n^4}\sum_{i=1}^ni^3;\quad\text{(b)}\ A=1/4',sub='ab')
calc(25,r'f\ge0\text{ continuous and strictly increasing on }[a,b],\quad\Delta x=(b-a)/n','(a) 좌우합과 정확한 넓이의 관계 (b) 두 합 차이의 공식과 재배열 도해 (c) 오른끝합의 오차 상계를 증명하라.','Prove (a) the relation of endpoint sums to area, (b) the difference formula with a rearrangement diagram, and (c) the right-sum error bound.',[r'L_n<A<R_n',r'R_n-L_n=\Delta x\sum_{i=1}^n[f(x_i)-f(x_{i-1})]',r'R_n-L_n=\Delta x[f(b)-f(a)]',r'R_n-A<R_n-L_n=\frac{b-a}n[f(b)-f(a)]'],r'\text{(a)}\ L_n<A<R_n;\quad\text{(b)}\ R_n-L_n=\frac{b-a}n[f(b)-f(a)];\quad\text{(c)}\ R_n-A<\frac{b-a}n[f(b)-f(a)]','폭이 모두 같으므로 연속 높이 증가분을 위로 쌓으면 처음과 끝 높이의 차이만큼인 한 직사각형이 된다. 증가를 넓은 뜻의 비감소로 정의할 때는 부등호를 약한 부등호로 바꾼다.','Equal widths allow consecutive height increments to stack into one rectangle of height equal to the endpoint difference. If increasing is interpreted as nondecreasing, use non-strict inequalities.',sub='abc')
# Rearrange four difference strips, using f(x)=1+x^2 and unit-width subintervals.
out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 700 400"><rect width="700" height="400" fill="white"/><text x="30" y="25" font-size="15">Equal-width increments stack to height f(b)-f(a)</text>'];colors=['#3679b1','#6ea95e','#d29744','#b16ca4'];base=350;scale=18
for j,height in enumerate([1,3,5,7]):
 xx=40+j*85;out.append(f'<rect x="{xx}" y="{base-height*scale}" width="50" height="{height*scale}" fill="{colors[j]}"/><text x="{xx+20}" y="{base-height*scale-7}" font-size="13">{height}</text>')
acc=0
for j,height in enumerate([1,3,5,7]):out.append(f'<rect x="540" y="{base-(acc+height)*scale}" width="50" height="{height*scale}" fill="{colors[j]}"/>');acc+=height
out+=['<text x="385" y="210" font-size="30">→</text><text x="515" y="40" font-size="13">1+3+5+7=16</text><text x="40" y="380" font-size="13">Each strip has width Δx; total area = Δx [f(b)-f(a)].</text></svg>'];addfig(25,''.join(out))
calc(26,r'f(x)=\sin x,\quad0\le x\le\pi/2','앞 오차 상계로 오른끝합 오차가 영점영영영일보다 작도록 하는 구간 수를 하나 구하라.','Use the preceding bound to choose a subinterval count giving right-sum error below 0.0001.',[r'R_n-A<\frac{\pi/2}n[\sin(\pi/2)-\sin0]=\pi/(2n)',r'\pi/(2n)\le10^{-4}\text{ whenever }n\ge15708'],r'n=15708\text{ suffices}')
for q,f,b,guess in [(27,x**4,S.Integer(1),r'1/5'),(28,S.cos(x),S.pi/2,r'1')]:
 results=[(N,sum(float(f.subs(x,b*j/N))*float(b)/N for j in range(1,N+1)))for N in[10,30,50,100]]
 calc(q,rf'f(x)={S.latex(f)},\quad0\le x\le{S.latex(b)},\quad n=10,30,50,100','등폭 구간의 오른끝합을 계산하고 정확한 넓이를 추측하라.','Compute equal-width right-endpoint sums and conjecture the exact area.',[r'R_n=(b/n)\sum_{i=1}^nf(ib/n)']+[rf'R_{{{N}}}={v:.10f}'for N,v in results],r'A='+guess,'여러 구간 수에서의 합이 제시한 값에 접근한다. 답은 합의 극한으로도 확인할 수 있다.','The sums approach the stated value as the interval count grows. The conjecture can also be verified from the sum limit.')
for q,f,a,b,lo,hi in [(29,1/(1+x*x),0,1,.780,.791),(30,x/(x+2),1,4,1.603,1.624)]:
 vals={(N,k):sums(f,S.Integer(a),S.Integer(b),N,k)for N in[10,30,50]for k in['L','R']};lower=vals[50,'R'if q==29 else'L'];upper=vals[50,'L'if q==29 else'R'];assert lo<float(lower)<float(upper)<hi
 calc(q,rf'f(x)={S.latex(f)},\quad{a}\le x\le{b},\quad n=10,30,50','(a) 왼끝·오른끝합 (b) 직사각형 그림 (c) 제시한 두 수 사이에 정확한 넓이가 있음을 증명하라.','Find (a) left and right sums, (b) rectangle plots, and (c) a proof that the exact area lies between the stated two bounds.',[rf'{k}_{{{N}}}\approx{float(v):.10f}'for(N,k),v in vals.items()]+[rf'{lo:.3f}<{float(lower):.10f}<A<{float(upper):.10f}<{hi:.3f}'],rf'{lo:.3f}<A<{hi:.3f}','함수가 단조이므로 오십 구간의 끝점합이 엄밀한 상하합이 된다. 반올림값만 비교하지 않고 정확한 유리수 합으로 부등식을 확인했다.','Monotonicity makes the fifty-interval endpoint sums rigorous bounds. The inequalities were checked with exact rational sums, not only rounded values.',sub='abc');rectplot(q,S.lambdify(x,f,'math'),a,b,[(N,k)for N in[10,30,50]for k in['L','R']])
for q,f,a,b in [(31,x**5,0,2),(32,x**4+5*x*x+x,2,7)]:
 dx=S.Rational(b-a)/n;term=dx*f.subs(x,a+i*dx);rs=S.factor(S.summation(S.expand(term),(i,1,n)));val=S.limit(rs,n,S.oo);assert val==S.integrate(f,(x,a,b))
 calc(q,rf'f(x)={S.latex(f)},\quad{a}\le x\le{b}','(a) 넓이의 합 극한 (b) 컴퓨터 대수로 유한합 (c) 그 극한으로 정확한 넓이를 구하라.','Find (a) the area sum limit, (b) the finite sum using computer algebra, and (c) the exact area by its limit.',[rf'\Delta x={S.latex(dx)},\quad x_i={S.latex(a+i*dx)}',r'R_n=\sum_{i=1}^n '+S.latex(term),r'R_n='+S.latex(rs),r'A=\lim_{n\to\infty}R_n='+S.latex(val)],r'\text{(a)}\ A=\lim_{n\to\infty}\sum_{i=1}^n '+S.latex(term)+r';\quad\text{(b)}\ R_n='+S.latex(rs)+r';\quad\text{(c)}\ A='+S.latex(val),'SymPy의 기호 합산으로 유한합을 구하고 독립적인 원시함수 계산과 대조했다.','The finite sum was obtained by SymPy symbolic summation and checked independently against an antiderivative.',sub='abc')
calc(33,r'f(x)=\cos x,\quad0\le x\le b,\quad0<b\le\pi/2','컴퓨터 대수로 유한합과 그 극한을 구하여 넓이를 계산하라. 끝점이 원주율의 절반일 때도 구하라.','Use computer algebra for the finite sum and its limit to calculate the area, including the case of upper endpoint pi over two.',[r'R_n=\frac bn\sum_{i=1}^n\cos(ib/n)',r'\sum_{i=1}^n\cos(i\theta)=\frac{\sin(n\theta/2)\cos((n+1)\theta/2)}{\sin(\theta/2)}',r'R_n=\frac bn\frac{\sin(b/2)\cos((n+1)b/(2n))}{\sin(b/(2n))}',r'\frac{b/n}{\sin(b/(2n))}\to2,\quad A=2\sin(b/2)\cos(b/2)=\sin b'],r'A=\sin b;\quad b=\pi/2\Rightarrow A=1','사인 차의 소거합으로 같은 유한합 공식을 독립 검증할 수 있다.','A telescoping difference of sines independently verifies the finite cosine-sum identity.')
calc(34,r'\text{Regular }n\text{-gon inscribed in a circle of radius }r,\quad n\ge3','(a) 중심에서 같은 삼각형들로 나누어 넓이 공식을 구하고 (b) 그 극한이 원의 넓이임을 증명하라.','(a) Partition into congruent central triangles to derive the area formula and (b) prove its limit is the circle area.',[r'\text{Each central angle}=2\pi/n,\quad\text{triangle area}=\tfrac12r^2\sin(2\pi/n)',r'A_n=\tfrac12nr^2\sin(2\pi/n)',r'A_n=\pi r^2\frac{\sin(2\pi/n)}{2\pi/n}\to\pi r^2'],r'\text{(a)}\ A_n=\tfrac12nr^2\sin(2\pi/n);\quad\text{(b)}\ \lim A_n=\pi r^2',sub='ab')
items.sort(key=lambda e:e['number']);assert[e['number']for e in items]==list(range(1,35))
raw={'section':'4.1','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[311,312,313,314],'pdfPages':[348,349,350,351]},'scope':{'kind':'exercise','numbers':list(range(1,35)),'total':34,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s4-1.json')
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
 for fld in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[fld]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[fld]['en'])
z=S.symbols('z');geometric=S.summation(z**i,(i,1,n));assert S.simplify(geometric.subs(z,S.Rational(2))-2*(2**n-1))==0
for N in [3,10,50]:
 b=mp.mpf('1.2');direct=sum(mp.cos(j*b/N)for j in range(1,N+1));closed=mp.sin(b/2)*mp.cos((N+1)*b/(2*N))/mp.sin(b/(2*N));assert abs(direct-closed)<mp.mpf('1e-55')
assert sums(1+x*x,S.Integer(-1),S.Integer(2),3,'R')==8
assert sums(1+x*x,S.Integer(-1),S.Integer(2),6,'L')==S.Rational(43,8)
(BASE/'exercise-content/s4-1.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('4.1: 34 cards; source graph readings, exact rectangle sums, unit conversions, symbolic finite sums and independent cosine-sum identity verified')
