import json,math,html,sys,re
from pathlib import Path
import sympy as S
import mpmath as mp
BASE=Path(__file__).resolve().parents[1];items=[];mp.mp.dps=60;x=S.symbols('x',real=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 p=324 if q<=8 else 325 if q<=35 else 326 if q<=61 else 327
 st=[M(t)for t in lines];items.append(dict(id=f'stewart9-exercise-4.2-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('정적분과 부호 있는 넓이','Definite integrals and signed area'),statement=bi(M(eq)+' '+tk,M(eq)+' '+te),hint=bi('구간의 폭과 표본점의 높이를 곱하여 합하고, 증가·감소에 따라 상하합을 구별한다.','Sum interval width times sample height, using monotonicity to distinguish lower and upper sums.'),steps=bi(st+([k]if k else[]),st+([e]if e else[])),answer=bi(M(ans)),check=bi('극한의 방향·정의역·부호를 확인하고 식 또는 도형의 조건을 대조했다.','Limit direction, domain, and signs were checked against the formula or geometric conditions.'),conceptHref='../../calc1/index.html',status='math-verified'))
i,n=S.symbols('i n',integer=True,positive=True)
def addfig(q,svg,caption=None):
 p=BASE/f'exercise-content/assets/s4-2-{q}.svg';p.write_text(svg);ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('함수와 넓이 근사 직사각형의 자체 도해','Original illustration of a function and its approximating rectangles'),'caption':caption or bi('표시한 함수 또는 원문 그림에서 읽은 표본값으로 직접 그린 직사각형.','Rectangles drawn directly from the stated function or samples read from the source graph.')}
def rectplot(q,fn,a,b,cases,ylim=None,caption=None):
 a,b=float(a),float(b);samples=[float(fn(a+(b-a)*j/600))for j in range(601)];height=430*len(cases);out=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 660 {height}"><rect width="660" height="{height}" fill="white"/>'];lo=min(0,min(samples));hi=max(0,max(samples));pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad
 for k,(N,mode)in enumerate(cases):
  off=k*430;dx=(b-a)/N;X=lambda z:60+550*(z-a)/(b-a);Y=lambda z:off+350-300*(z-lo)/(hi-lo)
  out.append(f'<text x="60" y="{off+25}" font-size="16">{mode}, n={N}</text><path d="M60 {off+45}V{off+350}M60 {Y(0)}H620" stroke="#8090a3" fill="none"/>')
  for j in range(N):
   aa=a+j*dx;bb=aa+dx;z=aa if mode=='L'else bb if mode=='R'else(aa+bb)/2;v=float(fn(z));color='#b9d6ef'if v>=0 else'#efcba8'
   if mode=='signed area':
    v0,v1=float(fn(aa)),float(fn(bb));out.append(f'<polygon points="{X(aa)},{Y(0)} {X(aa)},{Y(v0)} {X(bb)},{Y(v1)} {X(bb)},{Y(0)}" fill="{color}"/>')
   else:out.append(f'<rect x="{X(aa):.4f}" y="{min(Y(v),Y(0)):.4f}" width="{X(bb)-X(aa):.4f}" height="{abs(Y(0)-Y(v)):.4f}" fill="{color}" fill-opacity=".72" stroke="#758da7" stroke-width=".8"/>')
  pts=' '.join(f'{X(a+(b-a)*j/600):.3f},{Y(samples[j]):.3f}'for j in range(601));out.append(f'<polyline points="{pts}" fill="none" stroke="#b8443d" stroke-width="2.4"/>')
  for j in range(5):
   xx=a+(b-a)*j/4;yy=lo+(hi-lo)*j/4;out.append(f'<text x="{X(xx)-12}" y="{off+373}" font-size="11">{xx:.4g}</text><text x="5" y="{Y(yy)+4}" font-size="10">{yy:.4g}</text>')
  out.append(f'<text x="60" y="{off+411}" font-size="12">Blue: positive contribution. Orange: negative contribution.</text>')
 out.append('</svg>');addfig(q,''.join(out),caption)
def interp(vals,step=1,start=0):
 def f(z):
  t=(float(z)-start)/step;j=min(len(vals)-2,max(0,int(math.floor(t))));return vals[j]+(vals[j+1]-vals[j])*(t-j)
 return f
def sums(f,a,b,N,kind):
 dx=(b-a)/N
 if kind in ['L','R','M']:return S.simplify(dx*sum(f.subs(x,a+(j+({'L':0,'R':1,'M':S.Rational(1,2)}[kind]))*dx)for j in range(N)))
 return S.simplify(dx*sum((max if kind=='upper'else min)([f.subs(x,a+j*dx),f.subs(x,a+(j+1)*dx)]+([f.subs(x,0)]if a+j*dx<0<a+(j+1)*dx else[]))for j in range(N)))
def numtext(z):return f'{float(z):.9f}'
for q,f,a,b,N,kind in [(1,x-1,-6,4,5,'R'),(2,S.cos(x),0,3*S.pi/4,6,'L'),(3,x*x-4,0,3,6,'M')]:
 a=S.sympify(a);b=S.sympify(b);v=sums(f,a,b,N,kind);dx=(b-a)/N;offset={'R':1,'L':0,'M':S.Rational(1,2)}[kind]
 calc(q,rf'f(x)={S.latex(f)},\quad {S.latex(a)}\le x\le {S.latex(b)},\quad n={N},\quad\text{{samples: }}{kind}','리만합을 계산하고 그림으로 무엇을 근사하는지 설명하라.','Compute the Riemann sum and explain its signed-area meaning with a diagram.',[rf'\Delta x={S.latex(dx)},\quad x_j^*=a+(j+{S.latex(offset)})\Delta x\quad(j=0,\ldots,{N-1})',rf'{kind}_{N}=\Delta x\sum_{{j=0}}^{{{N-1}}}f(x_j^*)={S.latex(v)}\approx{float(v):.9f}'],rf'{kind}_{N}={S.latex(v)}\approx{float(v):.6f}','양의 높이 직사각형 넓이에서 음의 높이 직사각형의 넓이를 뺀 값으로 정적분을 근사한다. 총 기하학적 넓이와 구별한다.','The sum approximates the integral as positive rectangle areas minus negative rectangle areas, rather than total unsigned area.');rectplot(q,S.lambdify(x,f,'math'),a,b,[(N,kind)])
f=1/x;rv=sums(f,S.Integer(1),S.Integer(2),4,'R');mv=sums(f,S.Integer(1),S.Integer(2),4,'M')
calc(4,r'f(x)=1/x,\quad1\le x\le2,\quad n=4','(a) 오른끝 (b) 중점 리만합을 소수 여섯째 자리까지 계산하고 각각 그림과 해석을 제시하라.','Compute (a) right-endpoint and (b) midpoint sums to six decimals, with diagrams and interpretations.',[r'\Delta x=1/4;\quad R:\ 5/4,3/2,7/4,2;\quad M:\ 9/8,11/8,13/8,15/8',rf'R_4={S.latex(rv)},\quad M_4={S.latex(mv)}'],rf'\text{{(a)}}\ R_4\approx{float(rv):.6f};\quad\text{{(b)}}\ M_4\approx{float(mv):.6f}','곡선이 양수이므로 두 합은 곡선 아래 넓이의 근사이다. 감소함수의 오른끝합은 과소 추정이다.','Because the curve is positive, both sums approximate its area above the axis. The right sum underestimates the decreasing function.',sub='ab');rectplot(4,lambda z:1/z,1,2,[(4,'R'),(4,'M')])
vals5=[-1,2,-1,0,1,2,3,1,-1,-2,0];vals6=[0,1,1.5,1,0,-1,-1.5,-.5,.5,0,-1,-.5,.5]
for q,vs,a,b,dx,N in [(5,vals5,0,10,1,5),(6,vals6,-2,4,.5,6)]:
 fn=interp(vs,dx,a);h=(b-a)/N;L=h*sum(fn(a+j*h)for j in range(N));R=h*sum(fn(a+(j+1)*h)for j in range(N));V=h*sum(fn(a+(j+.5)*h)for j in range(N))
 calc(q,rf'x={a},{a+dx},\ldots,{b};\quad f(x)\approx('+','.join(str(z)for z in vs)+rf'),\quad n={N}','원문 그래프의 표본값으로 (a) 오른끝 (b) 왼끝 (c) 중점 정적분 근사를 구하라.','Use the source graph sample readings to estimate the integral by (a) right endpoints, (b) left endpoints, and (c) midpoints.',[rf'\Delta x={h};\quad L=\Delta x\sum_{{j=0}}^{{{N-1}}}f(a+j\Delta x),\quad R=\Delta x\sum_{{j=1}}^{N}f(a+j\Delta x)',r'M=\Delta x\sum f(a+(j+1/2)\Delta x)'],rf'\text{{(a)}}\ R\approx{R:.3f};\quad\text{{(b)}}\ L\approx{L:.3f};\quad\text{{(c)}}\ M\approx{V:.3f}','그림에서 읽은 근삿값이므로 약간의 판독 차이가 가능하다. 축 아래 높이는 음수로 합산한다.','Graph readings are approximate and may vary slightly. Heights below the axis enter with negative sign.',sub='abc');rectplot(q,fn,a,b,[(N,'R'),(N,'L'),(N,'M')])
calc(7,r'x=(10,14,18,22,26,30),\quad f(x)=(-12,-6,-2,1,3,8)','증가함수의 표로 정적분의 상하한을 추정하라.','Use the increasing-function table to bound the integral.',[r'\Delta x=4,\quad L_5=4(-12-6-2+1+3)=-64',r'R_5=4(-6-2+1+3+8)=16'],r'-64\le\int_{10}^{30}f(x)\,dx\le16')
vs=[-3.4,-2.1,-.6,.3,.9,1.4,1.8];L=2*sum(vs[0:6:2]);R=2*sum(vs[2:7:2]);V=2*sum(vs[1:6:2])
calc(8,r'x=(3,4,5,6,7,8,9),\quad f(x)=(-3.4,-2.1,-0.6,0.3,0.9,1.4,1.8)','세 구간의 (a) 오른끝 (b) 왼끝 (c) 중점합을 구하고 증가함수일 때 정확한 적분과 비교하라.','Compute three-interval (a) right, (b) left, and (c) midpoint sums and compare with the exact integral if the function is increasing.',[r'\Delta x=2;\quad R_3=2[f(5)+f(7)+f(9)],\quad L_3=2[f(3)+f(5)+f(7)],\quad M_3=2[f(4)+f(6)+f(8)]'],rf'\text{{(a)}}\ R_3={R:.1f}\text{{ upper}};\quad\text{{(b)}}\ L_3={L:.1f}\text{{ lower}};\quad\text{{(c)}}\ M_3={V:.1f}','증가 조건만으로 중점합의 과소·과대 여부는 정해지지 않는다.','Monotonicity alone does not determine whether the midpoint sum is above or below the integral.',sub='abc')
midrows=[(9,x*x,0,8,4),(10,8*x+3,0,2,4),(11,S.sin(S.sqrt(x)),0,8,4),(12,S.sqrt(x**3+1),0,1,5),(13,x/(x*x+8),1,3,5),(14,x*S.sin(x)**2,0,S.pi,4)]
for q,f,a,b,N in midrows:
 v=sums(f,S.sympify(a),S.sympify(b),N,'M');calc(q,rf'\int_{{{S.latex(a)}}}^{{{S.latex(b)}}}{S.latex(f)}\,dx,\quad n={N}','중점법으로 근사하라.'+(' 소수 넷째 자리까지 반올림하라.'if q>=11 else''),'Approximate using the Midpoint Rule.'+(' Round to four decimal places.'if q>=11 else''),[rf'\Delta x={S.latex((S.sympify(b)-a)/N)},\quad x_j^*=a+(j+1/2)\Delta x',rf'M_{N}=\Delta x\sum_{{j=0}}^{{{N-1}}}f(x_j^*)={float(v):.10f}'],rf'M_{N}\approx{float(v):.4f}'if q>=11 else rf'M_{N}={S.latex(v)}')
f=x/(x*x+8);res=[(N,sums(f,S.Integer(1),S.Integer(3),N,'M'))for N in[5,10,20]]
calc(15,r'f(x)=x/(x^2+8),\quad1\le x\le3,\quad n=5,10,20','컴퓨터 대수로 앞 중점 근사를 확인하고 두 번 세분화하여 직사각형 그림과 값을 구하라.','Use computer algebra to verify the previous midpoint approximation, refine twice, and plot the rectangles.',[rf'M_{{{N}}}\approx{float(v):.10f}'for N,v in res],r';\quad '.join(rf'M_{{{N}}}\approx{float(v):.6f}'for N,v in res));rectplot(15,S.lambdify(x,f,'math'),1,3,[(N,'M')for N in[5,10,20]])
f=x/(x+1);lo=sums(f,S.Integer(0),S.Integer(2),100,'L');hi=sums(f,S.Integer(0),S.Integer(2),100,'R');assert S.Rational(8946,10000)<lo<hi<S.Rational(9081,10000)
calc(16,r'f(x)=x/(x+1),\quad0\le x\le2,\quad n=100','컴퓨터로 좌우합을 계산하여 주어진 적분의 수치 상하한을 증명하라.','Compute left and right sums to establish numerical bounds for the integral.',[r'f^{\prime}(x)=1/(x+1)^2>0\Rightarrow L_{100}<I<R_{100}',rf'L_{{100}}={float(lo):.10f},\quad R_{{100}}={float(hi):.10f}'],r'0.8946<\int_0^2x/(x+1)\,dx<0.9081','부등식은 반올림 표시 전에 정확한 유리수 합으로 확인했다.','The inequalities were checked using exact rational sums before displaying rounded values.')
res=[(N,float(S.pi/N)*sum(math.sin(float(S.pi*j/N))for j in range(1,N+1)))for N in[5,10,50,100]]
calc(17,r'\int_0^\pi\sin x\,dx,\quad n=5,10,50,100','컴퓨터로 오른끝합의 표를 만들고 접근하는 값을 추측하라.','Tabulate right sums computationally and conjecture their limiting value.',[rf'R_{{{N}}}={v:.10f}'for N,v in res]+[r'R_n=(\pi/n)\cot(\pi/(2n))\to2'],r'2')
fn=lambda z:mp.sqrt(1+z**4);vals=[(N,2/mp.mpf(N)*sum(fn(2*mp.mpf(j)/N)for j in range(N)),2/mp.mpf(N)*sum(fn(2*mp.mpf(j)/N)for j in range(1,N+1)))for N in[5,10,50,100]];lo0,hi0=vals[-1][1:];lowleft=sum(fn(mp.mpf(j)/100)for j in range(100))/100;upleft=sum(fn(mp.mpf(j)/100)for j in range(1,101))/100
calc(18,r'f(x)=\sqrt{1+x^4},\quad n=5,10,50,100','영부터 이의 좌우합 표와 적분 범위를 구하라. 음의 일부터 이의 적분에도 같은 방식으로 말할 수 있는지 설명하라.','Tabulate left/right sums and bound the integral from zero to two. Explain whether the same argument applies from minus one to two.',[rf'n={N}:\quad L_n={float(l):.10f},\quad R_n={float(r):.10f}'for N,l,r in vals]+[rf'{float(lo0):.10f}<\int_0^2f<{float(hi0):.10f}',r'f\text{ decreases on }[-1,0]\text{ and increases on }[0,2]',r'\int_{-1}^2f=\int_0^1f+\int_0^2f\quad\text{by evenness}',rf'{float(lowleft+lo0):.10f}<\int_{{-1}}^2f<{float(upleft+hi0):.10f}'],rf'{float(lo0):.8f}<\int_0^2f<{float(hi0):.8f}','두 번째 구간에서는 전 구간 단조성이 없으므로 단순히 왼끝합이 하한이라고 하는 논증을 그대로 쓰지 않는다. 영에서 나누거나 짝대칭을 이용하면 표시한 상하한을 얻을 수 있다.','The second interval is not monotone throughout, so a blanket left-is-lower argument does not apply. Splitting at zero or using evenness yields the displayed bounds.')
for q,term,f,a,b in [(19,r'\sin x_i/(1+x_i)',r'\sin x/(1+x)',0,r'\pi'),(20,r'x_i\sqrt{1+x_i^3}',r'x\sqrt{1+x^3}',2,5),(21,r'5(x_i^*)^3-4x_i^*',r'5x^3-4x',2,7),(22,r'x_i^*/[(x_i^*)^2+4]',r'x/(x^2+4)',1,3)]:
 calc(q,r'\lim_{n\to\infty}\sum_{i=1}^n['+term+rf']\Delta x,\quad[a,b]=[{a},{b}]','합의 극한을 주어진 구간의 정적분으로 나타내라.','Express the sum limit as a definite integral on the stated interval.',[r'\Delta x=(b-a)/n,\quad f(x)='+f],rf'\int_{{{a}}}^{{{b}}}'+f+r'\,dx')
polyrows=[(23,x-x*x,0,4),(24,x**3+5*x*x,1,3),(27,3*x,0,2),(28,x*x,0,3),(29,5*x+2,0,3),(30,6-x*x,0,4),(31,3*x*x+7*x,1,5),(32,4*x*x+x+2,-1,2),(33,x**3-3*x*x,0,1),(34,2*x-x**3,0,2),(37,4*x,0,3),(38,2-x/2,-1,4),(39,3-2*x,0,8),(40,x*x-3*x,0,4)]
for q,f,a,b in polyrows:
 dx=S.Rational(b-a)/n;xi=a+i*dx;term=S.expand(f.subs(x,xi));rs=S.factor(S.summation(term*dx,(i,1,n)));val=S.limit(rs,n,S.oo);assert val==S.integrate(f,(x,a,b));lines=[rf'\Delta x={S.latex(dx)},\quad x_i={S.latex(xi)}',r'R_n='+S.latex(dx)+r'\sum_{i=1}^n\left['+S.latex(term)+r'\right]',r'R_n='+S.latex(rs),r'\lim_{n\to\infty}R_n='+S.latex(val)]
 tk='정적분의 정의에 따라 유한합과 그 극한으로 계산하라.';te='Evaluate from the definite-integral definition by computing the finite sum and its limit.';sub=''
 if q in[23,24]:tk='제시된 오른끝합을 유도하고 그 극한으로 정적분을 계산하라.';te='Derive the displayed right-endpoint sum and evaluate its limit.'
 if q in[37,38]:tk='(a) 정의의 합 극한으로 계산하고 (b) 넓이 해석으로 확인하라.';te='(a) Evaluate by the defining sum limit and (b) confirm geometrically.';sub='ab';lines+=[r'\text{Triangle area }(3)(12)/2=18'if q==37 else r'\text{Triangle area }(5)(5/2)/2=25/4']
 if q in[39,40]:
  rv=sums(f,S.Integer(a),S.Integer(b),8,'R');tk='(a) 오른끝 여덟 구간합 (b) 직사각형 도해 (c) 정의로 정확한 적분 (d) 양·음 넓이 차와 도해를 구하라.';te='Find (a) an eight-interval right sum, (b) rectangles, (c) the exact integral from its definition, and (d) a signed-area interpretation and diagram.';sub='abcd';lines.insert(0,rf'R_8={S.latex(rv)}');lines+=[r'A_+=9/4,\quad A_-=169/4,\quad A_+-A_-=-40'if q==39 else r'A_+=11/6,\quad A_-=9/2,\quad A_+-A_-=-8/3']
 ans=('R_8='+S.latex(rv)+r';\quad 'if q in[39,40]else'')+r'I='+S.latex(val)
 calc(q,rf'\int_{{{a}}}^{{{b}}}{S.latex(f)}\,dx',tk,te,lines,ans,'양수 부분은 더하고 음수 부분은 뺀다. 필요한 정수 거듭제곱 합은 기호 합산으로 계산했다.','Positive regions add and negative regions subtract. Integer power sums were evaluated symbolically.',sub=sub)
 if q in[37,38]:rectplot(q,S.lambdify(x,f,'math'),a,b,[(300,'signed area')])
 if q in[39,40]:rectplot(q,S.lambdify(x,f,'math'),a,b,[(8,'R'),(400,'signed area')])
for q,f,a,b in [(25,S.sqrt(4+x*x),1,3),(26,x*x+1/x,2,5)]:
 dx=S.Rational(b-a)/n;xi=a+i*dx;calc(q,rf'\int_{{{a}}}^{{{b}}}{S.latex(f)}\,dx','오른끝 리만합의 극한으로 나타내되 계산하지 마라.','Express as a right-endpoint Riemann-sum limit without evaluating it.',[rf'\Delta x={S.latex(dx)},\quad x_i={S.latex(xi)}'],r'\lim_{n\to\infty}\sum_{i=1}^n '+S.latex(dx*f.subs(x,xi)))
calc(35,r'f\text{ joins }(0,1),(2,3),(3,3),(7,-3),(9,-2)\text{ by line segments}','기하학적 넓이로 (a) 영부터 이 (b) 영부터 오 (c) 오부터 칠 (d) 삼부터 칠 (e) 삼부터 칠의 절댓값 적분 (f) 이부터 영의 적분을 구하라.','Use geometric areas to evaluate integrals (a) zero to two, (b) zero to five, (c) five to seven, (d) three to seven, (e) absolute value from three to seven, and (f) two to zero.',[r'\int_0^2f=2(1+3)/2=4',r'\int_2^3f=3,\quad\int_3^5f=(2)(3)/2=3,\quad\int_5^7f=-3',r'\int_3^7f=3-3=0,\quad\int_3^7|f|=3+3=6',r'\int_2^0f=-\int_0^2f'],r'\text{(a)}\ 4;\quad\text{(b)}\ 10;\quad\text{(c)}\ -3;\quad\text{(d)}\ 0;\quad\text{(e)}\ 6;\quad\text{(f)}\ -4',sub='abcdef')
f35=lambda z:1+z if z<=2 else 3 if z<=3 else S.Rational(3,2)*(5-z)if z<=7 else-3+(z-7)/2;rectplot(35,f35,0,9,[(450,'signed area')])
calc(36,r'g(x)=\begin{cases}4-2x&0\le x\le2\\-\sqrt{4-(x-4)^2}&2\le x\le6\\x-6&6\le x\le7\end{cases}','직선 둘과 아래쪽 반원으로 된 그래프에서 (a) 영부터 이 (b) 이부터 육 (c) 영부터 칠의 적분을 넓이로 구하라.','For the two line segments and lower semicircle, evaluate integrals (a) zero to two, (b) two to six, and (c) zero to seven using areas.',[r'\int_0^2g=(2)(4)/2=4',r'\int_2^6g=-\pi(2)^2/2=-2\pi',r'\int_6^7g=(1)(1)/2=1/2'],r'\text{(a)}\ 4;\quad\text{(b)}\ -2\pi;\quad\text{(c)}\ 9/2-2\pi',sub='abc');rectplot(36,lambda z:4-2*z if z<=2 else-math.sqrt(max(0,4-(z-4)**2))if z<=6 else z-6,0,7,[(420,'signed area')])
geom=[(41,10-5*x,-2,5,r'A_+=(4)(20)/2=40,\quad A_-=(3)(15)/2=45/2',S.Rational(35,2)),(42,2*x-1,-1,3,r'A_+=(5/2)(5)/2=25/4,\quad A_-=(3/2)(3)/2=9/4',S.Integer(4)),(43,S.Abs(x)/2,-4,3,r'I=(4)(2)/2+(3)(3/2)/2',S.Rational(25,4)),(44,S.Abs(2*x-1),0,1,r'I=2\cdot(1/2)(1)/2',S.Rational(1,2)),(45,1+S.sqrt(9-x*x),-3,0,r'I=\text{rectangle }3\cdot1+\text{quarter disk }\pi3^2/4',3+9*S.pi/4),(46,2*x-S.sqrt(16-x*x),-4,4,r'\int_{-4}^4 2x\,dx=0,\quad\int_{-4}^4\sqrt{16-x^2}\,dx=\pi4^2/2',-8*S.pi)]
for q,f,a,b,line,val in geom:calc(q,rf'\int_{{{a}}}^{{{b}}}{S.latex(f)}\,dx','기하학적 넓이와 부호로 계산하라.','Evaluate using geometric areas and signs.',[line],S.latex(val))
a,b=S.symbols('a b',real=True)
for q,power in[(47,1),(48,2)]:
 dx=(b-a)/n;rs=S.simplify(S.summation(S.expand((a+i*dx)**power*dx),(i,1,n)));val=S.factor(S.limit(rs,n,S.oo));calc(q,rf'\int_a^b x^{power}\,dx','일반 끝점을 갖는 적분의 거듭제곱 공식을 정의로 증명하라.','Prove the power-integral formula for general endpoints from the definition.',[r'a<b:\quad\Delta x=(b-a)/n,\quad x_i=a+i\Delta x',r'R_n='+S.latex(rs),r'\lim R_n='+S.latex(val),r'a=b:\ I=0;\quad a>b:\ \text{reverse the limits}'],rf'\int_a^b x^{power}\,dx='+S.latex((b**(power+1)-a**(power+1))/(power+1)))
calc(49,r'\int_0^\pi\sin(5x)\,dx','합의 극한으로 나타내고 컴퓨터 대수의 유한합 공식을 사용하여 계산하라.','Express the integral as a sum limit and evaluate using a computer-algebra finite-sum identity.',[r'R_n=(\pi/n)\sum_{i=1}^n\sin(5\pi i/n)',r'\sum_{i=1}^n\sin(i\theta)=\frac{\sin(n\theta/2)\sin((n+1)\theta/2)}{\sin(\theta/2)}',r'\theta=5\pi/n:\quad R_n=(\pi/n)\cot(5\pi/(2n))\quad(n\ge3)',r'R_n=\frac25\frac{5\pi/(2n)}{\sin(5\pi/(2n))}\cos(5\pi/(2n))\to2/5'],r'2/5')
dx=S.Integer(8)/n;term=dx*(2+8*i/n)**6;rs=S.factor(S.summation(S.expand(term),(i,1,n)));val=S.limit(rs,n,S.oo)
calc(50,r'\int_2^{10}x^6\,dx','합의 극한을 세우고 컴퓨터 대수로 유한합과 극한을 계산하라.','Set up the sum limit, then use computer algebra to compute the sum and limit.',[r'R_n=(8/n)\sum_{i=1}^n(2+8i/n)^6',r'R_n='+S.latex(rs),r'\lim R_n='+S.latex(val)],S.latex(val))
calc(51,r'\int_1^1\sqrt{1+x^4}\,dx','같은 두 끝점의 적분을 계산하라.','Evaluate the integral with equal endpoints.',[r'\int_a^a f(x)\,dx=0'],r'0')
calc(52,r'\int_0^\pi\sin^4x\,dx=3\pi/8','적분 변수 이름을 바꾸고 끝점 순서를 뒤집은 적분을 구하라.','Evaluate the integral after renaming the integration variable and reversing its limits.',[r'\int_\pi^0\sin^4\theta\,d\theta=-\int_0^\pi\sin^4\theta\,d\theta'],r'-3\pi/8')
for q,eq,lines,ans in[(53,r'\int_0^1(5-6x^2)\,dx',[r'5\int_0^1 1\,dx-6\int_0^1x^2\,dx=5-6(1/3)'],r'3'),(54,r'\int_2^5(1+3x^4)\,dx',[r'\int_2^5 1\,dx+3\int_2^5x^4\,dx=3+3(5^5-2^5)/5'],r'9294/5'),(55,r'\int_1^4(2x^2-3x+1)\,dx',[r'2(4^3-1^3)/3-3(4^2-1^2)/2+(4-1)'],r'45/2'),(56,r'\int_0^{\pi/2}(2\cos x-5x)\,dx',[r'2\int_0^{\pi/2}\cos x\,dx-5\int_0^{\pi/2}x\,dx=2-5(\pi/2)^2/2'],r'2-5\pi^2/8')]:calc(q,eq,'앞의 적분값과 선형성으로 계산하라.','Use earlier integral values and linearity to evaluate.',lines,ans)
calc(57,r'\int_{-2}^2f+\int_2^5f-\int_{-2}^{-1}f','하나의 정적분으로 합쳐라.','Combine into a single definite integral.',[r'\int_{-2}^2f+\int_2^5f=\int_{-2}^5f',r'\int_{-2}^5f-\int_{-2}^{-1}f=\int_{-1}^5f'],r'\int_{-1}^5 f(x)\,dx')
calc(58,r'\int_2^8f(x)\,dx=7.3,\quad\int_2^4f(x)\,dx=5.9','사부터 팔의 적분을 구하라.','Find the integral from four to eight.',[r'\int_4^8f=\int_2^8f-\int_2^4f=7.3-5.9'],r'1.4')
calc(59,r'\int_0^9f(x)\,dx=37,\quad\int_0^9g(x)\,dx=16;\quad I=\int_0^9[2f(x)+3g(x)]\,dx','두 함수의 선형결합 적분을 구하라.','Evaluate the integral of the specified linear combination.',[r'\int_0^9[2f(x)+3g(x)]\,dx=2(37)+3(16)'],r'122')
calc(60,r'f(x)=\begin{cases}3&x<3\\x&x\ge3\end{cases}','영부터 오의 적분을 구하라.','Find the integral from zero to five.',[r'\int_0^5f=\int_0^3 3\,dx+\int_3^5x\,dx=9+(25-9)/2'],r'17')
calc(61,r'A=\int_0^8f,\ B=\int_0^3f,\ C=\int_3^8f,\ D=\int_4^8f,\ E=f^{\prime}(1)','원문 그래프는 영부터 삼에서 음수이고 삼부터 팔에서 양수이다. 음의 넓이는 약 삼점칠, 입력 일의 기울기는 약 음의 영점육이며, 영부터 사까지의 부호 있는 넓이는 음수이다. 다섯 양을 작은 순서로 정렬하라.','The source graph is negative from zero to three and positive from three to eight. Its negative area is about 3.7, the slope at one about −0.6, and its signed area from zero to four is negative. Order the five quantities.',[r'B\approx-3.7<E\approx-0.6<0<A',r'D-A=-\int_0^4f>0\Rightarrow A<D',r'C-D=\int_3^4f>0\Rightarrow D<C'],r'B<E<A<D<C')
calc(62,r'F(x)=\int_2^x f(t)\,dt;\quad f>0\ (0<t<2),\quad f<0\ (2<t<5)','이 부호를 보이는 원문 그래프에서 영·일·이·삼·사의 누적적분값 중 가장 큰 것을 고르라.','For the source graph with these signs, choose the largest accumulated integral at zero, one, two, three, and four.',[r'F(2)=0;\quad x<2:\ F(x)=-\int_x^2f<0',r'2<x\le4:\quad F(x)=\int_2^xf<0'],r'F(2)=0\text{ is largest (choice C)}')
calc(63,r'\text{Three lobes on }[-4,-2],[-2,0],[0,2]\text{ each have unsigned area }3,\text{ with signs }-,+,-','주어진 넓이 정보로 함수에 이배 입력과 상수 오를 더한 적분을 구하라.','Use the lobe areas to integrate the function plus twice the input and the constant five.',[r'\int_{-4}^2f=-3+3-3=-3',r'\int_{-4}^2 2x\,dx=2^2-(-4)^2=-12,\quad\int_{-4}^2 5\,dx=30'],r'\int_{-4}^2[f(x)+2x+5]\,dx=15')
calc(64,r'm=\min f,\quad M=\max f\text{ on }[0,2]','정적분이 놓이는 범위를 구하고 사용한 성질을 설명하라.','Bound the integral and identify the property used.',[r'm\le f(x)\le M\Rightarrow m(2-0)\le\int_0^2f\le M(2-0)'],r'2m\le\int_0^2f(x)\,dx\le2M','함숫값의 상하한을 구간 길이에 곱하는 적분 비교 성질을 사용했다.','Use the integral comparison bound obtained by multiplying function bounds by interval length.')
calc(65,r'\int_0^4(x^2-4x+4)\,dx\ge0','적분값을 직접 계산하지 않고 증명하라.','Prove without evaluating the integral.',[r'x^2-4x+4=(x-2)^2\ge0',r'\int_0^4(x-2)^2\,dx\ge\int_0^4 0\,dx=0'],r'\int_0^4(x^2-4x+4)\,dx\ge0')
calc(66,r'\int_0^1\sqrt{1+x^2}\,dx\le\int_0^1\sqrt{1+x}\,dx','적분함수의 대소 관계로 증명하라.','Prove by comparing the integrands.',[r'0\le x\le1\Rightarrow x^2\le x',r'\sqrt{1+x^2}\le\sqrt{1+x}'],r'\int_0^1\sqrt{1+x^2}\,dx\le\int_0^1\sqrt{1+x}\,dx')
for q,eq,lines,ans in[(67,r'I=\int_{-1}^1\sqrt{1+x^2}\,dx',[r'1\le\sqrt{1+x^2}\le\sqrt2\quad(-1\le x\le1)',r'b-a=2'],r'2\le I\le2\sqrt2'),(68,r'I=\int_{\pi/6}^{\pi/3}\sin x\,dx',[r'1/2\le\sin x\le\sqrt3/2',r'b-a=\pi/6'],r'\pi/12\le I\le\sqrt3\pi/12'),(69,r'I=\int_0^1x^3\,dx',[r'0\le x^3\le1,\quad b-a=1'],r'0\le I\le1'),(70,r'I=\int_0^3\frac{dx}{x+4}',[r'1/7\le1/(x+4)\le1/4,\quad b-a=3'],r'3/7\le I\le3/4'),(71,r'I=\int_{\pi/4}^{\pi/3}\tan x\,dx',[r'1\le\tan x\le\sqrt3,\quad b-a=\pi/12'],r'\pi/12\le I\le\sqrt3\pi/12'),(72,r'I=\int_0^2(x^3-3x+3)\,dx',[r'f^{\prime}(x)=3(x^2-1)',r'f(0)=3,\quad f(1)=1,\quad f(2)=5',r'1\le f(x)\le5,\quad b-a=2'],r'2\le I\le10'),(73,r'I=\int_{-1}^1\sqrt{1+x^4}\,dx',[r'0\le x^4\le1\Rightarrow1\le\sqrt{1+x^4}\le\sqrt2',r'b-a=2'],r'2\le I\le2\sqrt2'),(74,r'I=\int_\pi^{2\pi}(x-2\sin x)\,dx',[r'f^{\prime}(x)=1-2\cos x=0\Rightarrow x=5\pi/3',r'f(\pi)=\pi,\quad f(2\pi)=2\pi,\quad f(5\pi/3)=5\pi/3+\sqrt3',r'\min f=\pi,\quad\max f=5\pi/3+\sqrt3,\quad b-a=\pi'],r'\pi^2\le I\le5\pi^2/3+\sqrt3\pi')]:calc(q,eq,'함숫값의 상하한과 구간 길이로 적분을 추정하라.','Estimate the integral using function bounds and interval length.',lines+[r'm(b-a)\le I\le M(b-a)'],ans)
calc(75,r'\int_1^3\sqrt{x^4+1}\,dx\ge26/3','함수 비교로 부등식을 증명하라.','Prove the inequality by comparison.',[r'\sqrt{x^4+1}\ge\sqrt{x^4}=x^2',r'\int_1^3\sqrt{x^4+1}\,dx\ge\int_1^3x^2\,dx=(27-1)/3'],r'\int_1^3\sqrt{x^4+1}\,dx\ge26/3')
calc(76,r'\int_0^{\pi/2}x\sin x\,dx\le\pi^2/8','함수 비교로 부등식을 증명하라.','Prove the inequality by comparison.',[r'0\le\sin x\le1,\quad x\ge0\Rightarrow x\sin x\le x',r'\int_0^{\pi/2}x\sin x\,dx\le\int_0^{\pi/2}x\,dx=(\pi/2)^2/2'],r'\int_0^{\pi/2}x\sin x\,dx\le\pi^2/8')
calc(77,r'A=\int_1^2\sqrt x\,dx,\quad B=\int_1^2\sqrt{1/x}\,dx,\quad C=\int_1^2\sqrt[4]x\,dx','계산 없이 가장 큰 적분을 고르라.','Choose the largest integral without evaluating.',[r'1<x\le2:\quad x^{1/2}>x^{1/4}>x^{-1/2}',r'A>C>B'],r'A=\int_1^2\sqrt x\,dx\text{ is largest}')
calc(78,r'A=\int_0^{1/2}\cos(x^2)\,dx,\quad B=\int_0^{1/2}\cos\sqrt x\,dx','계산 없이 두 적분을 비교하라.','Compare the integrals without evaluating.',[r'0<x\le1/2:\quad x^2<\sqrt x<\pi',r'\cos\text{ is strictly decreasing on }[0,\pi]',r'\cos(x^2)>\cos\sqrt x'],r'A>B')
calc(79,r'\int_a^b cf(x)\,dx=c\int_a^b f(x)\,dx','적분 가능한 함수와 실수 상수에 대해 상수배 성질을 리만합으로 증명하라.','Prove the scalar-multiple property from Riemann sums for an integrable function and a real constant.',[r'\sum_i cf(x_i^*)\Delta x_i=c\sum_i f(x_i^*)\Delta x_i',r'\lim_{\|P\|\to0}c\sum_i f(x_i^*)\Delta x_i=c\int_a^b f(x)\,dx',r'a=b:\ 0=c\cdot0;\quad a>b:\ \text{reverse limits}'],r'\int_a^b cf=c\int_a^b f','상수가 음수이거나 영이어도 유한합의 항등식과 극한의 상수배 법칙은 그대로 성립한다.','The finite-sum identity and constant-multiple limit law hold for negative and zero constants as well.')
calc(80,r'f\text{ is continuous on }[a,b],\quad a<b;\quad \left|\int_a^b f\right|\le\int_a^b|f|;\quad\left|\int_a^b f(x)\sin(2x)\,dx\right|\le\int_a^b|f|','(a) 양·음의 부분이 있는 그래프의 넓이로 절댓값 부등식을 설명하고 (b) 일반적으로 증명하며 (c) 사인 인자를 넣은 부등식을 증명하라.','(a) Explain the absolute-value inequality using positive and negative graph areas, (b) prove it in general, and (c) prove its version with a sine factor.',[r'\text{(a)}\ P=\text{positive area},\quad N=\text{negative unsigned area}',r'\left|\int_a^b f\right|=|P-N|\le P+N=\int_a^b|f|',r'\text{(b)}\ -|f(x)|\le f(x)\le|f(x)|',r'-\int_a^b|f|\le\int_a^b f\le\int_a^b|f|',r'\text{(c)}\ \left|\int_a^b f(x)\sin(2x)\,dx\right|\le\int_a^b|f(x)\sin(2x)|\,dx\le\int_a^b|f(x)|\,dx'],r'\left|\int_a^b f\right|\le\int_a^b|f|;\quad\left|\int_a^b f(x)\sin(2x)\,dx\right|\le\int_a^b|f|',sub='abc')
rectplot(80,lambda z:-math.sin(z),-math.pi,2*math.pi,[(450,'signed area')],caption=bi('부호 있는 넓이 설명을 위한 자체 예시. 파란 넓이의 합을 양의 넓이, 주황 넓이의 합을 음의 부분의 절댓값으로 두면 같은 증명이 임의의 그래프에 적용된다.','Original illustrative example: let the total blue area be the positive area and the total orange area the unsigned negative area. The same argument applies to any graph.'))
calc(81,r'f(x)=\begin{cases}0&x\in\mathbb Q\\1&x\notin\mathbb Q\end{cases},\quad0\le x\le1','리만합으로 이 함수가 적분 가능하지 않음을 증명하라.','Use Riemann sums to prove that this function is not integrable.',[r'\text{Every nonempty interval contains rational and irrational points}',r'\text{All rational tags: }\sum_i f(x_i^*)\Delta x_i=0',r'\text{All irrational tags: }\sum_i f(x_i^*)\Delta x_i=\sum_i\Delta x_i=1',r'\|P\|\to0:\quad0\ne1'],r'f\text{ is not Riemann integrable on }[0,1]','분할의 망을 아무리 작게 해도 표본점 선택에 따라 서로 다른 두 극한이 생긴다.','Arbitrarily fine partitions give two different limits depending on the tags.')
calc(82,r'f(x)=\begin{cases}0&x=0\\1/x&0<x\le1\end{cases}','첫 구간의 표본점을 영에 매우 가깝게 골라 리만 적분이 존재하지 않음을 보여라.','Choose the first tag very close to zero to show that no Riemann integral exists.',[r'\Delta x=1/n,\quad x_1^*=1/n^3\in(0,1/n)\quad(n\ge2)',r'f(x_1^*)\Delta x=n^3/n=n^2',r'\sum_{i=1}^n f(x_i^*)\Delta x\ge n^2\to\infty'],r'f\text{ is not Riemann integrable on }[0,1]','나머지 표본점은 각 구간 안에서 아무렇게나 골라도 모든 항이 음수가 아니므로 하한이 유지된다.','Every remaining tag contributes a nonnegative term, so this lower bound holds regardless of their choice.')
calc(83,r'\lim_{n\to\infty}\frac{1^4+2^4+\cdots+n^4}{n^5}','주어진 극한을 정적분으로 나타내라.','Express the limit as a definite integral.',[r'\frac1{n^5}\sum_{i=1}^n i^4=\sum_{i=1}^n(i/n)^4(1/n)',r'\Delta x=1/n,\quad x_i=i/n,\quad0\le x\le1'],r'\int_0^1x^4\,dx')
calc(84,r'\lim_{n\to\infty}\frac1n\left[\frac1{1+(1/n)^2}+\frac1{1+(2/n)^2}+\cdots+\frac1{1+(n/n)^2}\right]','주어진 극한을 정적분으로 나타내라.','Express the limit as a definite integral.',[r'\Delta x=1/n,\quad x_i=i/n,\quad f(x)=1/(1+x^2)',r'\lim_{n\to\infty}\sum_{i=1}^n f(x_i)\Delta x=\int_0^1 f(x)\,dx'],r'\int_0^1\frac{dx}{1+x^2}')
calc(85,r'I=\int_1^2\frac{dx}{x^2},\quad x_i=1+i/n,\quad x_i^*=\sqrt{x_{i-1}x_i}','각 부분구간 끝점의 기하평균을 표본점으로 사용하여 정의에서 적분값을 계산하라.','Evaluate from the definition using the geometric mean of each pair of subinterval endpoints as the tag.',[r'x_{i-1}\le\sqrt{x_{i-1}x_i}\le x_i\quad(x_{i-1}>0)',r'\frac{\Delta x}{(x_i^*)^2}=\frac{n}{(n+i-1)(n+i)}=n\left(\frac1{n+i-1}-\frac1{n+i}\right)',r'\sum_{i=1}^n\frac{\Delta x}{(x_i^*)^2}=n\left(\frac1n-\frac1{2n}\right)=\frac12',r'\Delta x\to0:\quad I=\lim_{n\to\infty}\frac12=\frac12'],r'1/2')
for ex in items:
 q=ex['number']
 if 65<=q<=78:ex['hint']=bi('적분함수의 점별 대소 관계를 먼저 구한 뒤 적분의 비교 성질을 적용한다.','First compare the integrands pointwise, then apply the integral comparison property.')
 if q in [79,81,82,83,84,85]:ex['hint']=bi('부분구간의 폭과 표본점을 명시하여 리만합을 직접 써 본다.','Specify subinterval widths and tags, then write the Riemann sum explicitly.')
 if q==80:ex['hint']=bi('양의 부분과 음의 부분의 넓이를 구분하고 절댓값의 삼각부등식을 사용한다.','Separate the positive and negative areas and use the triangle inequality.')
items.sort(key=lambda e:e['number']);assert[e['number']for e in items]==list(range(1,86))
raw={'section':'4.2','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[324,325,326,327],'pdfPages':[361,362,363,364]},'scope':{'kind':'exercise','numbers':list(range(1,86)),'total':85,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s4-2.json')
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
 for fld in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[fld]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[fld]['en'])
for N in [3,10,50]:
 direct=sum(mp.sin(5*mp.pi*j/N)for j in range(1,N+1));closed=mp.cot(5*mp.pi/(2*N));assert abs(direct-closed)<mp.mpf('1e-54')
assert S.simplify(n/((n+i-1)*(n+i))-n*(1/(n+i-1)-1/(n+i)))==0
for N in [2,7,100]:assert sum(S.Rational(N,(N+j-1)*(N+j))for j in range(1,N+1))==S.Rational(1,2)
for q,f,a,b,line,val in geom:assert S.simplify(S.integrate(f,(x,a,b))-val)==0
for q,f,a,b,val in[(37,4*x,0,3,18),(38,2-x/2,-1,4,S.Rational(25,4)),(39,3-2*x,0,8,-40),(40,x*x-3*x,0,4,-S.Rational(8,3)),(54,1+3*x**4,2,5,S.Rational(9294,5)),(55,2*x*x-3*x+1,1,4,S.Rational(45,2))]:assert S.integrate(f,(x,a,b))==val
(BASE/'exercise-content/s4-2.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('4.2: 85 cards; schema, SVG XML, geometric areas, polynomial integrals, sine finite sums, and geometric-tag telescoping sums verified')
