import json,math,html,sys,re
from pathlib import Path
import sympy as S
import mpmath as mp
BASE=Path(__file__).resolve().parents[1];items=[];mp.mp.dps=60;x=S.symbols('x',real=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 p=335 if q<=3 else 336 if q<=44 else 337 if q<=70 else 338
 st=[M(t)for t in lines];items.append(dict(id=f'stewart9-exercise-4.3-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('미적분학의 기본정리','Fundamental theorem of calculus'),statement=bi(M(eq)+' '+tk,M(eq)+' '+te),hint=bi('적분함수의 연속성을 확인하고, 누적적분의 미분 또는 원시함수의 끝점 차를 적용한다.','Check continuity, then differentiate the accumulated integral or subtract antiderivative endpoint values.'),steps=bi(st+([k]if k else[]),st+([e]if e else[])),answer=bi(M(ans)),check=bi('극한의 방향·정의역·부호를 확인하고 식 또는 도형의 조건을 대조했다.','Limit direction, domain, and signs were checked against the formula or geometric conditions.'),conceptHref='../../calc1/index.html',status='math-verified'))
i,n=S.symbols('i n',integer=True,positive=True)
def addfig(q,svg,caption=None):
 p=BASE/f'exercise-content/assets/s4-3-{q}.svg';p.write_text(svg);ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('함수와 넓이 근사 직사각형의 자체 도해','Original illustration of a function and its approximating rectangles'),'caption':caption or bi('표시한 함수 또는 원문 그림에서 읽은 표본값으로 직접 그린 직사각형.','Rectangles drawn directly from the stated function or samples read from the source graph.')}
def rectplot(q,fn,a,b,cases,ylim=None,caption=None):
 a,b=float(a),float(b);samples=[float(fn(a+(b-a)*j/600))for j in range(601)];height=430*len(cases);out=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 660 {height}"><rect width="660" height="{height}" fill="white"/>'];lo=min(0,min(samples));hi=max(0,max(samples));pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad
 for k,(N,mode)in enumerate(cases):
  off=k*430;label='Signed area'if mode=='signed area'else mode+', n='+str(N);dx=(b-a)/N;X=lambda z:60+550*(z-a)/(b-a);Y=lambda z:off+350-300*(z-lo)/(hi-lo)
  out.append(f'<text x="60" y="{off+25}" font-size="16">{label}</text><path d="M60 {off+45}V{off+350}M60 {Y(0)}H620" stroke="#8090a3" fill="none"/>')
  for j in range(N):
   aa=a+j*dx;bb=aa+dx;z=aa if mode=='L'else bb if mode=='R'else(aa+bb)/2;v=float(fn(z));color='#b9d6ef'if v>=0 else'#efcba8'
   if mode=='signed area':
    v0,v1=float(fn(aa)),float(fn(bb));out.append(f'<polygon points="{X(aa)},{Y(0)} {X(aa)},{Y(v0)} {X(bb)},{Y(v1)} {X(bb)},{Y(0)}" fill="{color}"/>')
   else:out.append(f'<rect x="{X(aa):.4f}" y="{min(Y(v),Y(0)):.4f}" width="{X(bb)-X(aa):.4f}" height="{abs(Y(0)-Y(v)):.4f}" fill="{color}" fill-opacity=".72" stroke="#758da7" stroke-width=".8"/>')
  pts=' '.join(f'{X(a+(b-a)*j/600):.3f},{Y(samples[j]):.3f}'for j in range(601));out.append(f'<polyline points="{pts}" fill="none" stroke="#b8443d" stroke-width="2.4"/>')
  for j in range(5):
   xx=a+(b-a)*j/4;yy=lo+(hi-lo)*j/4;out.append(f'<text x="{X(xx)-12}" y="{off+373}" font-size="11">{xx:.4g}</text><text x="5" y="{Y(yy)+4}" font-size="10">{yy:.4g}</text>')
  out.append(f'<text x="60" y="{off+411}" font-size="12">Blue: positive contribution. Orange: negative contribution.</text>')
 out.append('</svg>');addfig(q,''.join(out),caption)
def curves(q,fnlist,a,b,title=''):
 samples=[[(a+(b-a)*j/600,float(fn(a+(b-a)*j/600)))for j in range(601)]for label,fn in fnlist];ys=[v for pts in samples for z,v in pts];lo=min(0,min(ys));hi=max(0,max(ys));pad=max(.2,(hi-lo)*.1);lo-=pad;hi+=pad;X=lambda z:60+550*(z-a)/(b-a);Y=lambda v:355-300*(v-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 660 430"><rect width="660" height="430" fill="white"/>',f'<text x="60" y="25" font-size="16">{html.escape(title)}</text>',f'<path d="M60 {Y(0)}H615 M{X(0) if a<=0<=b else 60} 55V355" stroke="#8b94a2" fill="none"/>'];colors=['#bd443d','#2475b5','#368c65']
 for k,((label,fn),pts)in enumerate(zip(fnlist,samples)):
  out.append('<polyline points="'+' '.join(f'{X(z):.3f},{Y(v):.3f}'for z,v in pts)+f'" fill="none" stroke="{colors[k]}" stroke-width="2.5"/>');out.append(f'<text x="{60+k*180}" y="411" fill="{colors[k]}" font-size="14">{html.escape(label)}</text>')
 for j in range(7):
  xx=a+(b-a)*j/6;yy=lo+(hi-lo)*j/6;out.append(f'<text x="{X(xx)-8}" y="376" font-size="11">{xx:.3g}</text><text x="3" y="{Y(yy)+4}" font-size="11">{yy:.3g}</text>')
 out.append('</svg>');addfig(q,''.join(out),bi('원문 조건으로 계산한 함수 또는 명시한 그래프 판독값의 자체 도해.','Original plot calculated from the stated function or explicitly described source-graph readings.'))
def polygon_f(points):
 def f(z):
  k=next((k for k in range(len(points)-1)if z<=points[k+1][0]),len(points)-2);aa,fa=points[k];bb,fb=points[k+1];return fa+(fb-fa)*(z-aa)/(bb-aa)
 def g(z):
  v=0
  for (aa,fa),(bb,fb)in zip(points,points[1:]):
   if z<=aa:break
   end=min(z,bb);d=end-aa;v+=fa*d+(fb-fa)*d*d/(2*(bb-aa))
  return v
 return f,g
calc(1,r'\frac{d}{dx}\int_a^x f(t)\,dt=f(x),\qquad\int_a^x F^{\prime}(t)\,dt=F(x)-F(a)','미분과 적분이 서로 역과정이라는 말의 정확한 뜻과 조건을 설명하라.','Explain precisely in what sense differentiation and integration are inverse processes, including the conditions.',[r'f\text{ continuous}\Rightarrow G(x)=\int_a^x f(t)\,dt\Rightarrow G^{\prime}=f',r'F^{\prime}=f\text{ continuous}\Rightarrow\int_a^x F^{\prime}(t)\,dt=F(x)-F(a)'],r'D\left(\int_a^x f\right)=f;\quad\int_a^x DF=F(x)-F(a)','적분한 뒤 미분하면 원래 함수가 된다. 미분한 뒤 적분하면 처음 함수를 상수 차이까지 복원한다.','Differentiating the accumulated integral restores the integrand. Integrating a derivative restores the function up to the initial constant.')
f2base,g2base=polygon_f([(0,1),(2,-1),(6,3)])
f2=lambda z:f2base(z)if z<=6 else 3*math.sqrt(max(0,1-(z-6)**2))
g2=lambda z:g2base(z)if z<=6 else 4+1.5*((z-6)*math.sqrt(max(0,1-(z-6)**2))+math.asin(min(1,z-6)))
calc(2,r'g(x)=\int_0^x f(t)\,dt;\quad f\text{ joins }(0,1),(2,-1),(6,3)\text{ linearly, then curves to }(7,0)','(a) 영부터 육까지 정수에서 누적적분값을 구하고 (b) 칠에서 추정하며 (c) 최댓값·최솟값의 위치를 찾고 (d) 누적함수를 그려라. 마지막 곡선 아래 넓이는 그림에서 약 이점사로 읽힌다.','(a) Evaluate at integer inputs from zero through six, (b) estimate at seven, (c) locate the maximum and minimum, and (d) sketch the accumulated integral. The final curved region has area approximately 2.4 from the graph.',[r'(g(0),g(1),g(2),g(3),g(4),g(5),g(6))=(0,1/2,0,-1/2,0,3/2,4)',r'g(7)\approx4+2.4=6.4',r'g^{\prime}=f>0\text{ on }(0,1)\cup(3,7),\quad g^{\prime}<0\text{ on }(1,3)',r'g(x)=x-x^2/2\ (0\le x\le2);\quad g(x)=(x-3)^2/2-1/2\ (2\le x\le6)'],r'\text{(a)}\ (0,1/2,0,-1/2,0,3/2,4);\quad\text{(b)}\ g(7)\approx6.4;\quad\text{(c)}\ \max\text{ at }7,\ \min\text{ at }3','마지막 곡선은 정확한 식이 주어지지 않았다. 도해는 그 구간을 타원 호로 근사하여 누적함수의 모양을 보이며 추정값을 정확한 값으로 취급하지 않는다.','No exact equation is supplied for the final curve. The diagram uses an elliptical-arc approximation there to illustrate the accumulated function; its estimate is not treated as exact.',sub='abcd');curves(2,[('f (last arc approximate)',f2),('g',g2)],0,7)
f3,g3=polygon_f([(0,2),(1,2),(2,4),(3,0),(5,-2),(6,-2),(7,0)])
calc(3,r'g(x)=\int_0^x f(t)\,dt;\quad f\text{ joins }(0,2),(1,2),(2,4),(3,0),(5,-2),(6,-2),(7,0)','(a) 입력 영·일·이·삼·육에서 함수값 (b) 증가 구간 (c) 최댓값 위치를 찾고 (d) 그래프를 그려라.','Find (a) the values at zero, one, two, three, and six, (b) the increasing interval, (c) the maximum location, and (d) sketch the graph.',[r'g(0)=0,\quad g(1)=2,\quad g(2)=2+(2+4)/2=5',r'g(3)=5+(1)(4)/2=7,\quad g(6)=7-(2)(2)/2-2=3',r'g^{\prime}=f>0\text{ on }(0,3),\quad g^{\prime}<0\text{ on }(3,7)',r'g(7)=2;\quad g\text{ is piecewise quadratic or linear}'],r'\text{(a)}\ (0,2,5,7,3);\quad\text{(b)}\ (0,3);\quad\text{(c)}\ x=3,\ g(3)=7',sub='abcd');curves(3,[('f',f3),('g',g3)],0,7)
f4,g4=polygon_f([(0,0),(2,5),(4,1),(8,-1),(11,2)])
calc(4,r'g(x)=\int_0^x f(t)\,dt;\quad f\text{ joins }(0,0),(2,5),(4,1),(8,-1),(11,2)','(a) 도함수 그래프 (b) 입력 삼에서 함수·일계·이계 도함수 값 (c) 육과 (d) 구에서 극값 유형을 구하라.','Find (a) the derivative graph, (b) the function and first two derivative values at three, and classify the extrema at (c) six and (d) nine.',[r'\text{(a)}\ g^{\prime}(x)=f(x)',r'\text{(b)}\ g(3)=\tfrac12(2)(5)+\tfrac12(5+3)(1)=9,\quad g^{\prime}(3)=3,\quad g^{\prime\prime}(3)=-2',r'\text{(c)}\ f:\ +\to-\text{ at }6\Rightarrow\text{local maximum}',r'\text{(d)}\ f:\ -\to+\text{ at }9\Rightarrow\text{local minimum}'],r'\text{(a)}\ g^{\prime}=f;\quad\text{(b)}\ (9,3,-2);\quad\text{(c)}\ \text{local maximum};\quad\text{(d)}\ \text{local minimum}',sub='abcd');curves(4,[("g'=f",f4)],0,11)
for q,f,G,area in[(5,S.Integer(3),3*x,r'\text{rectangle: }g(x)=3x'),(6,3*x,3*x*x/2,r'\text{triangle: }g(x)=\tfrac12 x(3x)=3x^2/2')]:
 calc(q,r'f(t)='+S.latex(f.subs(x,S.Symbol('t')))+r',\quad x\ge0','(a) 넓이의 기하학으로 누적함수 공식을 구하고 (b) 미분하여 기본정리를 확인하라.','(a) Obtain the accumulated-area formula geometrically and (b) differentiate it to verify the fundamental theorem.',[area,r'g^{\prime}(x)='+S.latex(S.diff(G,x))+r'=f(x)'],r'g(x)='+S.latex(G)+r',\quad g^{\prime}(x)='+S.latex(f),sub='ab')
for q,f,a in[(7,x*x,1),(8,2+S.sin(x),0)]:
 F=S.integrate(f,x);G=F-F.subs(x,a);calc(q,rf'g(x)=\int_{{{a}}}^x '+S.latex(f.subs(x,S.Symbol('t')))+r'\,dt','누적적분이 나타내는 영역을 그리고 (a) 기본정리의 제일부와 (b) 적분 후 미분으로 도함수를 구하라.','Sketch the accumulated region and differentiate (a) by FTC Part 1 and (b) by evaluating first and differentiating.',[r'\text{(a)}\ g^{\prime}(x)='+S.latex(f),r'\text{(b)}\ g(x)='+S.latex(G),r'\frac{d}{dx}g(x)='+S.latex(S.diff(G,x))],r'g^{\prime}(x)='+S.latex(f),'도해는 위끝점이 고정 아래끝점보다 큰 예시이며, 순서가 반대이면 적분의 부호가 바뀐다.','The diagram illustrates an upper endpoint larger than the fixed lower endpoint; reversing the order reverses the integral sign.',sub='ab');rectplot(q,S.lambdify(x,f,'math'),a,3,[(300,'signed area')])
derivs=[(9,r'g(x)=\int_0^x\sqrt{t+t^3}\,dt',r'g^{\prime}(x)=\sqrt{x+x^3}',r'x>0'),(10,r'g(x)=\int_1^x\cos(t^2)\,dt',r'g^{\prime}(x)=\cos(x^2)',r'x\in\mathbb R'),(11,r'g(w)=\int_0^w\sin(1+t^3)\,dt',r'g^{\prime}(w)=\sin(1+w^3)',r'w\in\mathbb R'),(12,r'h(u)=\int_0^u\frac{\sqrt t}{t+1}\,dt',r'h^{\prime}(u)=\frac{\sqrt u}{u+1}',r'u>0'),(13,r'F(x)=\int_x^0\sqrt{1+\sec t}\,dt',r'F^{\prime}(x)=-\sqrt{1+\sec x}',r'-\pi/2<x<\pi/2'),(14,r'R(y)=\int_y^2t^3\sin t\,dt',r'R^{\prime}(y)=-y^3\sin y',r'y\in\mathbb R'),(15,r'h(x)=\int_2^{1/x}\sin^4t\,dt',r'h^{\prime}(x)=-\sin^4(1/x)/x^2',r'x\ne0'),(16,r'h(x)=\int_1^{\sqrt x}\frac{z^2}{z^4+1}\,dz',r'h^{\prime}(x)=\frac{\sqrt x}{2(x^2+1)}',r'x>0'),(17,r'y=\int_1^{3x+2}\frac{t}{1+t^3}\,dt',r'y^{\prime}=\frac{3(3x+2)}{1+(3x+2)^3}',r'x>-1'),(18,r'y=\int_0^{x^4}\cos^2\theta\,d\theta',r'y^{\prime}=4x^3\cos^2(x^4)',r'x\in\mathbb R'),(19,r'y=\int_{\sqrt x}^{\pi/4}\theta\tan\theta\,d\theta',r'y^{\prime}=-\tfrac12\tan\sqrt x',r'0<x<\pi^2/4'),(20,r'y=\int_{1/x}^4\sqrt{1+1/t}\,dt',r'y^{\prime}=\frac{\sqrt{1+x}}{x^2}',r'x>0')]
for q,eq,ans,dom in derivs:
 calc(q,eq,'기본정리의 제일부로 도함수를 구하라.','Differentiate using FTC Part 1.',[r'\frac{d}{dx}\int_a^{u(x)}f(t)\,dt=f(u(x))u^{\prime}(x)',r'\frac{d}{dx}\int_{u(x)}^a f(t)\,dt=-f(u(x))u^{\prime}(x)',r'\text{Interior domain: }'+dom,ans],ans)
ints=[(21,x**3,-1,2),(22,x*x-4*x,0,4),(23,2*S.sin(x),S.pi/2,2*S.pi),(24,S.sqrt(x)-1,0,4),(25,x*x+2*x-4,1,3),(26,x**100,-1,1),(27,S.Rational(4,5)*x**3-S.Rational(3,4)*x*x+S.Rational(2,5)*x,0,2),(28,1-8*x**3+16*x**7,0,1),(29,S.sqrt(x),1,9),(30,x**-S.Rational(2,3),1,8),(31,x*x+x**S.Rational(3,2),0,4),(32,1/x**2+1/x**3,1,3),(33,S.cos(x),S.pi/2,0),(34,S.pi,-5,5),(35,(x+2)*(x-3),0,1),(36,(4-x)*S.sqrt(x),0,4),(37,(2+x*x)/S.sqrt(x),1,4),(38,(3*x-2)*(x+1),-1,2),(39,(x**4+1)/x**2,1,2),(41,S.sec(x)*S.tan(x),0,S.pi/3),(42,S.csc(x)**2,S.pi/4,S.pi/3),(43,(1+x)**3,0,1),(44,S.sqrt(3/x),1,18),(47,S.sqrt(x),0,4),(48,x**3,0,1),(49,4-x*x,-2,2),(50,2*x-x*x,0,2),(51,x**S.Rational(1,3),0,27),(52,x**-4,1,6),(53,S.sin(x),0,S.pi),(54,S.sec(x)**2,0,S.pi/3),(84,2*S.sin(x)-S.exp(x),0,3),(85,1/(2*x),1,9),(86,10**x,0,1),(87,4/S.sqrt(1-x*x),S.Rational(1,2),1/S.sqrt(2)),(88,4/(1+x*x),0,1),(89,S.exp(x+1),-1,1),(90,(x**3-2*x*x-x)/x**2,1,3)]
intchecks=[]
for q,f,a,b in ints:
 F=S.integrate(S.expand(f),x);val=S.simplify(F.subs(x,b)-F.subs(x,a));assert S.simplify(S.diff(F,x)-f)==0;intchecks.append((q,str(val)))
 k='기본정리의 제이부로 정적분을 계산하라.';e='Evaluate the definite integral using FTC Part 2.';morek='';moree='';lines=[r'F(x)='+S.latex(F)+r',\quad F^{\prime}(x)='+S.latex(f),r'I=F('+S.latex(b)+r')-F('+S.latex(a)+r')='+S.latex(val)]
 if q in [21,22,23,24]:
  k+=' 그래프를 그리고 부호 있는 넓이를 설명하라.';e+=' Sketch and interpret the signed area.'
  extra={21:r'A_+=4,\quad A_-=1/4,\quad I=A_+-A_-=15/4',22:r'f\le0\text{ on }[0,4],\quad I=-32/3,\quad\text{unsigned area}=32/3',23:r'A_+=2,\quad A_-=4,\quad I=-2',24:r'A_-=1/3,\quad A_+=5/3,\quad I=4/3'};lines.append(extra[q])
 if 47<=q<=50:k='주어진 곡선과 가로축으로 둘러싸인 영역을 그리고 넓이를 구하라.';e='Sketch the region enclosed by the curve and the horizontal axis and find its area.'
 if 51<=q<=54:
  k='그래프로 넓이를 대략 추정한 후 정확한 값을 구하라.';e='Estimate the area graphically, then find the exact value.';est={51:'61',52:'0.33',53:'2',54:'1.7'}[q];lines.insert(0,r'\text{Graph estimate: }A\approx'+est)
 if 47<=q<=54:lines.append(r'f(x)\ge0\text{ on the interval, so }A=I')
 calc(q,rf'I=\int_{{{S.latex(a)}}}^{{{S.latex(b)}}}\left('+S.latex(f)+r'\right)\,dx',k,e,lines,S.latex(val))
 if q in [21,22,23,24,47,48,49,50,51,52,53,54]:rectplot(q,S.lambdify(x,f,'math'),a,b,[(450,'signed area')])
calc(40,r'\int_5^5\sqrt{t^2+\sin t}\,dt','정적분을 계산하라.','Evaluate the definite integral.',[r'\int_a^a f(t)\,dt=0'],r'0')
calc(45,r'I=\int_0^\pi f(x)\,dx,\quad f(x)=\begin{cases}\sin x&0\le x<\pi/2\\\cos x&\pi/2\le x\le\pi\end{cases}','경계에서 나누어 정적분을 구하라.','Split at the boundary and evaluate.',[r'I=\int_0^{\pi/2}\sin x\,dx+\int_{\pi/2}^\pi\cos x\,dx',r'I=[-\cos x]_0^{\pi/2}+[\sin x]_{\pi/2}^\pi=1-1'],r'0')
calc(46,r'I=\int_{-2}^2f(x)\,dx,\quad f(x)=\begin{cases}2&-2\le x\le0\\4-x^2&0<x\le2\end{cases}','경계에서 나누어 정적분을 구하라.','Split at the boundary and evaluate.',[r'I=\int_{-2}^0 2\,dx+\int_0^2(4-x^2)\,dx',r'I=4+[4x-x^3/3]_0^2=4+8-8/3'],r'28/3')
for q,eq,lines,ans in[(55,r'\int_{-2}^1x^{-4}\,dx\stackrel{?}=[-x^{-3}/3]_{-2}^1=-3/8',[r'x=0\text{ is inside }[-2,1];\quad x^{-4}\text{ is unbounded there}',r'\int_\epsilon^1x^{-4}\,dx=(\epsilon^{-3}-1)/3\to+\infty'],r'\text{Invalid: no finite integral; improper integral diverges to }+\infty'),(56,r'\int_{-1}^2\frac4{x^3}\,dx\stackrel{?}=[-2/x^2]_{-1}^2=3/2',[r'x=0\text{ is an interior singularity}',r'\int_{-1}^{-\epsilon}4x^{-3}\,dx=2-2/\epsilon^2\to-\infty',r'\int_\epsilon^2 4x^{-3}\,dx=2/\epsilon^2-1/2\to+\infty'],r'\text{Invalid: the two one-sided improper integrals diverge}'),(57,r'\int_{\pi/3}^\pi\sec\theta\tan\theta\,d\theta\stackrel{?}=[\sec\theta]_{\pi/3}^\pi=-3',[r'\theta=\pi/2\text{ is an interior singularity}',r'\sec\theta\tan\theta=\sin\theta/\cos^2\theta\ge0',r'\int_{\pi/3}^{\pi/2-\epsilon}\sec\theta\tan\theta\,d\theta=\csc\epsilon-2\to+\infty'],r'\text{Invalid: the improper integral diverges to }+\infty'),(58,r'\int_0^\pi\sec^2x\,dx\stackrel{?}=[\tan x]_0^\pi=0',[r'x=\pi/2\text{ is an interior singularity}',r'\int_0^{\pi/2-\epsilon}\sec^2x\,dx=\cot\epsilon\to+\infty'],r'\text{Invalid: the improper integral diverges to }+\infty')]:calc(q,eq,'등식에 잘못 적용한 정리의 조건을 설명하라.','Identify the failed hypothesis behind the claimed equality.',lines,ans,'특이점을 가로질러 원시함수의 끝점 차만 계산할 수 없다.','One cannot subtract antiderivative endpoint values across the interior singularity.')
for q,eq,lines,ans in[(59,r'g(x)=\int_{2x}^{3x}\frac{u^2-1}{u^2+1}\,du',[r'f(u)=(u^2-1)/(u^2+1)',r'g^{\prime}(x)=3f(3x)-2f(2x)'],r'3\frac{9x^2-1}{9x^2+1}-2\frac{4x^2-1}{4x^2+1}'),(60,r'g(x)=\int_{1-2x}^{1+2x}t\sin t\,dt',[r'f(t)=t\sin t',r'g^{\prime}(x)=2f(1+2x)-(-2)f(1-2x)'],r'2(1+2x)\sin(1+2x)+2(1-2x)\sin(1-2x)'),(61,r'h(x)=\int_{\sqrt x}^{x^3}\cos(t^2)\,dt',[r'h^{\prime}(x)=\cos((x^3)^2)(3x^2)-\cos((\sqrt x)^2)/(2\sqrt x),\quad x>0'],r'3x^2\cos(x^6)-\frac{\cos x}{2\sqrt x}'),(62,r'g(x)=\int_{\tan x}^{x^2}\frac{dt}{\sqrt{2+t^4}}',[r'g^{\prime}(x)=\frac{2x}{\sqrt{2+(x^2)^4}}-\frac{\sec^2x}{\sqrt{2+(\tan x)^4}}',r'\cos x\ne0'],r'\frac{2x}{\sqrt{2+x^8}}-\frac{\sec^2x}{\sqrt{2+\tan^4x}}')]:calc(q,eq,'양쪽 끝점이 변하는 적분을 미분하라.','Differentiate the integral with two variable endpoints.',[r'\frac{d}{dx}\int_{a(x)}^{b(x)}f(t)\,dt=f(b(x))b^{\prime}(x)-f(a(x))a^{\prime}(x)']+lines,ans)
calc(63,r'F(x)=\int_\pi^x\frac{\cos t}{t}\,dt','입력이 원주율인 점에서 접선의 방정식을 구하라.','Find the tangent line at the point whose input is pi.',[r'F(\pi)=0,\quad F^{\prime}(x)=\cos x/x',r'F^{\prime}(\pi)=-1/\pi',r'y-F(\pi)=F^{\prime}(\pi)(x-\pi)'],r'y=-(x-\pi)/\pi')
calc(64,r'f(x)=\int_0^x(1-t^2)\cos^2t\,dt','증가하는 구간을 구하라.','Find the interval of increase.',[r'f^{\prime}(x)=(1-x^2)\cos^2x',r'\cos^2x\ge0;\quad 1-x^2>0\iff-1<x<1',r'|x|>1:\quad f^{\prime}(x)\le0'],r'(-1,1)','구간 밖의 코사인 영점에서는 도함수가 잠시 영이 되지만 증가 구간이 생기지는 않는다.','Isolated cosine zeros outside this interval make the derivative zero but do not create intervals of increase.')
calc(65,r'y=\int_0^x\frac{t^2}{t^2+t+2}\,dt','그래프가 아래로 오목한 구간을 구하라.','Find where the curve is concave downward.',[r'y^{\prime}=\frac{x^2}{x^2+x+2}',r'y^{\prime\prime}=\frac{2x(x^2+x+2)-x^2(2x+1)}{(x^2+x+2)^2}=\frac{x(x+4)}{(x^2+x+2)^2}',r'x^2+x+2=(x+1/2)^2+7/4>0',r'x(x+4)<0\iff-4<x<0'],r'(-4,0)')
calc(66,r'F(x)=\int_1^x f(t)\,dt;\quad f\text{ increases to a local maximum at }-1,\text{ decreases to a minimum at }1,\text{ then increases}','이 그래프 정보로 누적함수가 아래로 오목한 구간을 구하라.','Use the graph information to find where the accumulated function is concave downward.',[r'F^{\prime}=f,\quad F^{\prime\prime}=f^{\prime}',r'F^{\prime\prime}<0\iff f\text{ is decreasing}'],r'(-1,1)')
calc(67,r'f(1)=12,\quad f^{\prime}\text{ continuous},\quad\int_1^4f^{\prime}(x)\,dx=17','입력 사에서 함수값을 구하라.','Find the function value at four.',[r'f(4)-f(1)=\int_1^4f^{\prime}=17',r'f(4)=12+17'],r'f(4)=29')
calc(68,r'f(x)=\int_0^{\sin x}\sqrt{1+t^2}\,dt,\quad g(y)=\int_3^y f(x)\,dx','입력이 원주율의 육분의 일일 때 누적함수의 이계 도함수를 구하라.','Find the second derivative of the accumulated function at pi over six.',[r'g^{\prime}(y)=f(y),\quad g^{\prime\prime}(y)=f^{\prime}(y)',r'f^{\prime}(x)=\sqrt{1+\sin^2x}\cos x',r'g^{\prime\prime}(\pi/6)=\sqrt{1+1/4}(\sqrt3/2)'],r'\sqrt{15}/4')
sroot=mp.findroot(lambda z:mp.fresnels(z)-mp.mpf('.2'),.75);siroot=mp.findroot(lambda z:mp.si(z)-1,1);infroot=mp.findroot(lambda z:z*mp.cos(z)-mp.sin(z),4.5)
calc(69,r'S(x)=\int_0^x\sin(\pi t^2/2)\,dt','(a) 극대 위치 (b) 위로 오목한 구간을 구하고 (c) 함수값이 영점이인 방정식을 그래프로 풀어 소수 둘째 자리까지 표시하라.','Find (a) local maximum locations, (b) intervals of upward concavity, and (c) graphically solve for function value 0.2 to two decimal places.',[r'S^{\prime}(x)=\sin(\pi x^2/2),\quad S^{\prime\prime}(x)=\pi x\cos(\pi x^2/2)',r'\text{(a), }x>0:\quad x=\sqrt{4k+2},\quad k=0,1,2,\ldots',r'x<0:\quad x=-\sqrt{4k},\quad k=1,2,\ldots',r'\text{(b), }x>0:\quad(0,1)\cup\bigcup_{k=1}^{\infty}(\sqrt{4k-1},\sqrt{4k+1})',r'x<0:\quad\bigcup_{k=0}^{\infty}(-\sqrt{4k+3},-\sqrt{4k+1})',r'\text{(c)}\ S(x)=0.2\Rightarrow x\approx'+mp.nstr(sroot,12)],r'\text{(a)}\ \sqrt{4k+2}\ (k\ge0),\ -\sqrt{4k}\ (k\ge1);\quad\text{(b)}\ x\cos(\pi x^2/2)>0;\quad\text{(c)}\ x\approx'+f'{float(sroot):.2f}','정의역을 전체 실수로 보아 음의 입력도 포함했다. 양의 입력만 그린 그림에서는 양의 쪽 해만 읽는다. 처음 양의 극솟값 이후의 극솟값들은 증가하므로 추가적인 방정식 해가 없다.','Negative inputs are included for the full real domain. A plot restricted to positive inputs shows only the positive branches. Successive positive-side local minima increase after the first one, so they add no equation roots.',sub='abc');curves(69,[('S(x)',lambda z:float(mp.fresnels(z))),('target 0.2',lambda z:.2)],-4,4)
calc(70,r'\operatorname{Si}(x)=\int_0^x\frac{\sin t}{t}\,dt,\quad(\sin t)/t\big|_{t=0}=1','(a) 그래프 (b) 극대 위치 (c) 원점 오른쪽 첫 변곡점 (d) 수평 점근선 (e) 함수값이 일인 방정식의 소수 첫째 자리 해를 구하라.','Find (a) the graph, (b) local maximum locations, (c) the first inflection point right of the origin, (d) horizontal asymptotes, and (e) the solution with function value one to one decimal place.',[r'\operatorname{Si}^{\prime}(x)=\sin x/x,\quad\operatorname{Si}^{\prime}(0)=1',r'\text{(b)}\ x=(2k+1)\pi\ (k\ge0),\quad x=-2k\pi\ (k\ge1)',r'\operatorname{Si}^{\prime\prime}(x)=\frac{x\cos x-\sin x}{x^2}',r'\text{(c)}\ \tan x=x,\quad x\approx'+mp.nstr(infroot,12)+r',\quad\operatorname{Si}(x)\approx'+mp.nstr(mp.si(infroot),12),r'\text{(d)}\ \lim_{x\to\pm\infty}\operatorname{Si}(x)=\pm\pi/2',r'\text{(e)}\ \operatorname{Si}(x)=1\Rightarrow x\approx'+mp.nstr(siroot,12)],r'\text{(b)}\ (2k+1)\pi\ (k\ge0),\ -2k\pi\ (k\ge1);\quad\text{(c)}\ ('+f'{float(infroot):.6f},{float(mp.si(infroot)):.6f}'+r');\quad\text{(d)}\ y=\pm\pi/2;\quad\text{(e)}\ x\approx'+f'{float(siroot):.1f}','수평 점근선은 그래프의 진동 중심과 일치한다. 엄밀한 값은 감쇠인자를 넣은 적분이 그 인자의 역수의 역탄젠트가 됨을 이용하여 확인할 수 있다. 원점은 도함수의 제거 가능한 특이점이다.','The horizontal asymptotes match the oscillation centers in the graph. Their exact values can be confirmed using the exponentially damped integral, which equals the arctangent of the reciprocal damping parameter. The apparent singularity of the derivative at zero is removable.',sub='abcde');curves(70,[('Si(x)',lambda z:float(mp.si(z))),('pi/2',lambda z:math.pi/2),('-pi/2',lambda z:-math.pi/2)],-20,20)
def lobes(spec):
 def f(z):
  a,c,b,A=next((v for v in spec if z<=v[2]),spec[-1]);return A*math.sin(math.pi*(z-a)/(2*(c-a)))if z<=c else A*math.cos(math.pi*(z-c)/(2*(b-c)))
 def g(z):
  v=0
  for a,c,b,A in spec:
   if z<=a:break
   u=min(z,c);v+=A*2*(c-a)/math.pi*(1-math.cos(math.pi*(u-a)/(2*(c-a))))
   if z>c:u=min(z,b);v+=A*2*(b-c)/math.pi*math.sin(math.pi*(u-c)/(2*(b-c)))
  return v
 return f,g
for q,spec,eq,down,ma,mi,am in[(71,[(0,.4,1,.45),(1,2.1,3,-1.45),(3,4,5,2),(5,6,7,-2.45),(7,8,9,2.8)],r'f\text{ has zeros }0,1,3,5,7,9;\quad\text{successive lobe signs }+,-,+,-,+',r'(0.4,2.1)\cup(4,6)\cup(8,9)',r'1,5',r'3,7',r'9'),(72,[(0,.8,2,.52),(2,2.8,4,-.25),(4,4.8,6,.17),(6,6.8,8,-.125),(8,8.8,10,.095)],r'f\text{ has zeros }0,2,4,6,8,10;\quad\text{successive lobe signs }+,-,+,-,+',r'(0.8,2.8)\cup(4.8,6.8)\cup(8.8,10)',r'2,6',r'4,8',r'2')]:
 f,g=lobes(spec);calc(q,r'g(x)=\int_0^x f(t)\,dt;\quad '+eq,'원문 그래프의 봉우리 위치와 넓이를 사용하여 (a) 국소 극대·극소 위치 (b) 절대 최댓값 위치 (c) 아래로 오목한 구간을 구하고 (d) 누적함수를 그려라. 도해의 곡선 및 봉우리 수치는 원문에서 읽은 근사이다.','Using the source graph peak locations and lobe areas, find (a) local maximum and minimum locations, (b) the absolute maximum location, (c) downward-concavity intervals, and (d) sketch the accumulated function. Curves and peak values in the diagram are approximate source readings.',[r'g^{\prime}=f,\quad g^{\prime\prime}=f^{\prime}',r'\text{(a)}\ +\to-:\ x='+ma+r';\quad-\to+:\ x='+mi,r'\text{(b)}\ \text{Compare successive signed lobe sums: maximum at }x='+am,r'\text{(c)}\ f\text{ decreases on approximately }'+down,r'\text{(d)}\ g(0)=0;\quad\text{follow the accumulated signed areas}'],r'\text{(a)}\ \max:\ '+ma+r',\quad\min:\ '+mi+r';\quad\text{(b)}\ x='+am+r';\quad\text{(c)}\ '+down,'국소 극값은 내부점 기준으로 표시했다. 끝점은 절대 최댓값 비교에 포함했다.','Local extrema refer to interior points; endpoints are included when comparing absolute maxima.',sub='abcd');curves(q,[('f (approximate source readings)',f),('g (corresponding sketch)',g)],0,spec[-1][2])
calc(73,r'\lim_{n\to\infty}\sum_{i=1}^n\left(\frac{i^4}{n^5}+\frac{i}{n^2}\right)','단위구간의 리만합으로 해석하여 극한을 구하라.','Recognize a Riemann sum on the unit interval and evaluate.',[r'\sum_{i=1}^n[(i/n)^4+i/n](1/n)\to\int_0^1(x^4+x)\,dx',r'\int_0^1(x^4+x)\,dx=[x^5/5+x^2/2]_0^1'],r'7/10')
calc(74,r'\lim_{n\to\infty}\frac1n\left(\sqrt{1/n}+\sqrt{2/n}+\cdots+\sqrt{n/n}\right)','단위구간의 리만합으로 해석하여 극한을 구하라.','Recognize a Riemann sum on the unit interval and evaluate.',[r'\sum_{i=1}^n\sqrt{i/n}(1/n)\to\int_0^1\sqrt x\,dx',r'\int_0^1\sqrt x\,dx=[2x^{3/2}/3]_0^1'],r'2/3')
calc(75,r'g(x)=\int_a^x f(t)\,dt,\quad h<0;\quad m=\min_{[x+h,x]}f,\quad M=\max_{[x+h,x]}f','기본정리 증명의 차분몫 부등식이 음의 증분에서도 성립함을 증명하라.','Justify the difference-quotient bound in the FTC proof for a negative increment.',[r'm(-h)\le\int_{x+h}^x f(t)\,dt\le M(-h)',r'\frac{g(x+h)-g(x)}h=\frac{-\int_{x+h}^x f(t)\,dt}{h}=\frac1{-h}\int_{x+h}^x f(t)\,dt',r'-h>0\Rightarrow m\le\frac{g(x+h)-g(x)}h\le M'],r'm\le\frac{g(x+h)-g(x)}h\le M')
calc(76,r'f\text{ continuous},\quad g,h\text{ differentiable}','양 끝점이 함수인 적분의 미분 공식을 증명하라.','Prove the derivative formula for an integral with two variable endpoints.',[r'F(u)=\int_a^u f(t)\,dt\Rightarrow F^{\prime}(u)=f(u)',r'\int_{g(x)}^{h(x)}f(t)\,dt=F(h(x))-F(g(x))',r'\frac{d}{dx}[F(h(x))-F(g(x))]=f(h(x))h^{\prime}(x)-f(g(x))g^{\prime}(x)'],r'\frac{d}{dx}\int_{g(x)}^{h(x)}f(t)\,dt=f(h(x))h^{\prime}(x)-f(g(x))g^{\prime}(x)')
calc(77,r'x\ge0;\quad1\le\sqrt{1+x^3}\le1+x^3;\quad1\le\int_0^1\sqrt{1+x^3}\,dx\le1.25','(a) 제곱근 함수의 상하한을 증명하고 (b) 단위구간 적분의 범위를 얻어라.','(a) Prove bounds for the square-root function and (b) deduce bounds for its integral on the unit interval.',[r'\text{(a)}\ u=1+x^3\ge1\Rightarrow1\le\sqrt u\le u',r'1\le\sqrt{1+x^3}\le1+x^3',r'\text{(b)}\ \int_0^1 1\,dx\le\int_0^1\sqrt{1+x^3}\,dx\le\int_0^1(1+x^3)\,dx=5/4'],r'\text{(a)}\ 1\le\sqrt{1+x^3}\le1+x^3;\quad\text{(b)}\ 1\le\int_0^1\sqrt{1+x^3}\,dx\le1.25',sub='ab')
calc(78,r'0\le x\le1;\quad\cos(x^2)\ge\cos x;\quad\int_0^{\pi/6}\cos(x^2)\,dx\ge1/2','(a) 입력의 제곱에 대한 코사인과 입력에 대한 코사인을 비교하고 (b) 영부터 원주율 육분의 일까지 적분의 하한을 증명하라.','(a) Compare cosine at the squared input with cosine at the input and (b) bound the integral from zero to pi over six.',[r'\text{(a)}\ 0\le x^2\le x\le1<\pi,\quad\cos\text{ decreases on }[0,\pi]',r'\cos(x^2)\ge\cos x',r'\text{(b)}\ \pi/6<1\Rightarrow\int_0^{\pi/6}\cos(x^2)\,dx\ge\int_0^{\pi/6}\cos x\,dx=\sin(\pi/6)'],r'\text{(a)}\ \cos(x^2)\ge\cos x;\quad\text{(b)}\ \int_0^{\pi/6}\cos(x^2)\,dx\ge1/2',sub='ab')
calc(79,r'I=\int_5^{10}\frac{x^2}{x^4+x^2+1}\,dx','더 간단한 함수와 비교하여 적분의 상하한을 구하라.','Compare with a simpler function to obtain lower and upper bounds.',[r'0\le\frac{x^2}{x^4+x^2+1}\le\frac{x^2}{x^4}=x^{-2}',r'0\le I\le\int_5^{10}x^{-2}\,dx=[-1/x]_5^{10}=1/10'],r'0\le I\le0.1')
calc(80,r'f(x)=\begin{cases}0&x<0\\x&0\le x\le1\\2-x&1<x\le2\\0&x>2\end{cases},\quad g(x)=\int_0^x f(t)\,dt','(a) 누적함수의 조각별 식 (b) 두 함수 그래프 (c) 각 함수의 미분 가능 위치를 구하라.','Find (a) a piecewise formula for the accumulated integral, (b) both graphs, and (c) where each function is differentiable.',[r'x<0:\ g(x)=0;\quad0\le x\le1:\ g(x)=\int_0^x t\,dt=x^2/2',r'1<x\le2:\ g(x)=1/2+\int_1^x(2-t)\,dt=2x-x^2/2-1',r'x>2:\ g(x)=1',r'f\text{ is continuous everywhere but has corners at }0,1,2',r'g^{\prime}=f\text{ everywhere}'],r'g(x)=\begin{cases}0&x<0\\x^2/2&0\le x\le1\\2x-x^2/2-1&1<x\le2\\1&x>2\end{cases};\quad f\text{ differentiable on }\mathbb R\setminus\{0,1,2\};\quad g\text{ differentiable on }\mathbb R',sub='abc');curves(80,[('f',lambda z:0 if z<0 or z>2 else z if z<=1 else 2-z),('g',lambda z:0 if z<0 else z*z/2 if z<=1 else 2*z-z*z/2-1 if z<=2 else 1)],-1,3)
calc(81,r'6+\int_a^x\frac{f(t)}{t^2}\,dt=2\sqrt x\quad(x>0)','항등식을 만족하는 함수와 아래끝점을 구하라.','Find the function and lower endpoint satisfying the identity.',[r'\frac{f(x)}{x^2}=\frac1{\sqrt x}\Rightarrow f(x)=x^{3/2}',r'x=a:\quad6=2\sqrt a\Rightarrow a=9',r'6+\int_9^x t^{-1/2}\,dt=6+2\sqrt x-6=2\sqrt x'],r'f(x)=x^{3/2},\quad a=9')
calc(82,r'h(1)=-2,\ h^{\prime}(1)=2,\ h^{\prime\prime}(1)=3,\ h(2)=6,\ h^{\prime}(2)=5,\ h^{\prime\prime}(2)=13;\quad h^{\prime\prime}\text{ continuous}','일에서 이까지 이계 도함수의 적분을 구하라.','Integrate the second derivative from one to two.',[r'\int_1^2h^{\prime\prime}(u)\,du=h^{\prime}(2)-h^{\prime}(1)=5-2'],r'3')
calc(83,r'f(t)\text{ continuous depreciation rate},\quad A>0,\quad C(t)=\frac{A+\int_0^t f(s)\,ds}{t},\quad t>0','(a) 감가율의 적분 (b) 평균비용 함수의 의미를 설명하고 (c) 최적 정비주기의 조건을 구하라.','Explain (a) the integral of depreciation, (b) the meaning of the average-cost function, and (c) the condition for an optimal overhaul interval.',[r'\text{(a)}\ L(t)=\int_0^t f(s)\,ds=\text{total loss in value}',r'\text{(b)}\ C(t)=\text{average overhaul plus depreciation cost per month}',r'\text{(c)}\ C^{\prime}(t)=\frac{tf(t)-A-\int_0^t f(s)\,ds}{t^2}=\frac{f(t)-C(t)}t',r'C^{\prime}(T)=0\Rightarrow C(T)=f(T)',r'\text{If }f\text{ is differentiable, }C^{\prime\prime}(T)=f^{\prime}(T)/T',r'A=1,\quad f(t)=\max(0,10+4t-t^2):\quad tf(t)-A-\int_0^t f=2t^2-\tfrac23t^3-1\quad(2\le t\le3)',r'N(2)=5/3>0,\quad N(3)=-1<0,\quad N^{\prime}(t)=2t(2-t)<0\ (2<t<3)\Rightarrow\text{a local maximum in }(2,3)'],r'\text{Interior optimum requires }C(T)=f(T);\quad f^{\prime}(T)>0\text{ makes such a point a strict local minimum}','연속성만으로 원문의 최소 주장까지는 결론낼 수 없다. 정상점 식은 필요조건이며 감가율 증가 또는 도함수의 음에서 양으로의 부호 변화가 최소를 보장한다. 평균비용을 최소화하면 한 달당 정비·감가 비용이 최소가 된다.','Continuity alone does not establish the stated minimum conclusion. The stationary equation is necessary; increasing depreciation or a negative-to-positive derivative change ensures a minimum. Minimizing average cost minimizes overhaul and depreciation expense per month.',sub='abc')
items.sort(key=lambda e:e['number']);assert[e['number']for e in items]==list(range(1,91))
raw={'section':'4.3','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[335,336,337,338],'pdfPages':[372,373,374,375]},'scope':{'kind':'exercise','numbers':list(range(1,91)),'total':90,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s4-3.json')
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
 for fld in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[fld]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[fld]['en'])
 for fld in ['statement','hint','steps','answer','check']:assert not re.search('[가-힣ぁ-ヿ]',str(ex[fld]['en'])),(ex['number'],fld)
assert [g3(j)for j in[0,1,2,3,6]]==[0,2,5,7,3]
assert g4(3)==9 and f4(3)==3
assert abs(mp.fresnels(sroot)-mp.mpf('.2'))<mp.mpf('1e-55')
assert abs(mp.si(siroot)-1)<mp.mpf('1e-55')
assert abs(infroot*mp.cos(infroot)-mp.sin(infroot))<mp.mpf('1e-55')
(BASE/'exercise-checks/s4-3-independent.json').write_text(json.dumps({'antiderivatives_checked':intchecks,'fresnel_root':str(sroot),'si_root':str(siroot),'si_inflection':[str(infroot),str(mp.si(infroot))]},ensure_ascii=False,indent=2)+'\n')
(BASE/'exercise-content/s4-3.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('4.3: 90 cards; source diagrams, symbolic antiderivatives, high-precision roots, schema, language fields and SVG XML checked')
