import json,math,html,sys,re
from pathlib import Path
import sympy as S
import mpmath as mp
BASE=Path(__file__).resolve().parents[1];items=[];mp.mp.dps=60;x=S.symbols('x',real=True)
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':k if e is None else e}
def calc(q,eq,tk,te,lines,ans,k='',e='',sub=''):
 p=345 if q<=49 else 346 if q<=67 else 347 if q<=73 else 348
 st=[M(t)for t in lines];items.append(dict(id=f'stewart9-exercise-4.4-{q}',number=q,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('부정적분과 순변화 정리','Indefinite integrals and net change'),statement=bi(M(eq)+' '+tk,M(eq)+' '+te),hint=bi('적분함수의 연속성을 확인하고, 누적적분의 미분 또는 원시함수의 끝점 차를 적용한다.','Check continuity, then differentiate the accumulated integral or subtract antiderivative endpoint values.'),steps=bi(st+([k]if k else[]),st+([e]if e else[])),answer=bi(M(ans)),check=bi('극한의 방향·정의역·부호를 확인하고 식 또는 도형의 조건을 대조했다.','Limit direction, domain, and signs were checked against the formula or geometric conditions.'),conceptHref='../../calc1/index.html',status='math-verified'))
i,n=S.symbols('i n',integer=True,positive=True)
def addfig(q,svg,caption=None):
 p=BASE/f'exercise-content/assets/s4-4-{q}.svg';p.write_text(svg);ex=next(e for e in items if e['number']==q);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('함수와 넓이 근사 직사각형의 자체 도해','Original illustration of a function and its approximating rectangles'),'caption':caption or bi('표시한 함수 또는 원문 그림에서 읽은 표본값으로 직접 그린 직사각형.','Rectangles drawn directly from the stated function or samples read from the source graph.')}
def rectplot(q,fn,a,b,cases,ylim=None,caption=None):
 a,b=float(a),float(b);samples=[float(fn(a+(b-a)*j/600))for j in range(601)];height=430*len(cases);out=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 660 {height}"><rect width="660" height="{height}" fill="white"/>'];lo=min(0,min(samples));hi=max(0,max(samples));pad=max(.1,(hi-lo)*.12);lo-=pad;hi+=pad
 for k,(N,mode)in enumerate(cases):
  off=k*430;label='Signed area'if mode=='signed area'else mode+', n='+str(N);dx=(b-a)/N;X=lambda z:60+550*(z-a)/(b-a);Y=lambda z:off+350-300*(z-lo)/(hi-lo)
  out.append(f'<text x="60" y="{off+25}" font-size="16">{label}</text><path d="M60 {off+45}V{off+350}M60 {Y(0)}H620" stroke="#8090a3" fill="none"/>')
  for j in range(N):
   aa=a+j*dx;bb=aa+dx;z=aa if mode=='L'else bb if mode=='R'else(aa+bb)/2;v=float(fn(z));color='#b9d6ef'if v>=0 else'#efcba8'
   if mode=='signed area':
    v0,v1=float(fn(aa)),float(fn(bb));out.append(f'<polygon points="{X(aa)},{Y(0)} {X(aa)},{Y(v0)} {X(bb)},{Y(v1)} {X(bb)},{Y(0)}" fill="{color}"/>')
   else:out.append(f'<rect x="{X(aa):.4f}" y="{min(Y(v),Y(0)):.4f}" width="{X(bb)-X(aa):.4f}" height="{abs(Y(0)-Y(v)):.4f}" fill="{color}" fill-opacity=".72" stroke="#758da7" stroke-width=".8"/>')
  pts=' '.join(f'{X(a+(b-a)*j/600):.3f},{Y(samples[j]):.3f}'for j in range(601));out.append(f'<polyline points="{pts}" fill="none" stroke="#b8443d" stroke-width="2.4"/>')
  for j in range(5):
   xx=a+(b-a)*j/4;yy=lo+(hi-lo)*j/4;out.append(f'<text x="{X(xx)-12}" y="{off+373}" font-size="11">{xx:.4g}</text><text x="5" y="{Y(yy)+4}" font-size="10">{yy:.4g}</text>')
  out.append(f'<text x="60" y="{off+411}" font-size="12">Blue: positive contribution. Orange: negative contribution.</text>')
 out.append('</svg>');addfig(q,''.join(out),caption)
def curves(q,fnlist,a,b,title=''):
 samples=[[(a+(b-a)*j/600,float(fn(a+(b-a)*j/600)))for j in range(601)]for label,fn in fnlist];ys=[v for pts in samples for z,v in pts];lo=min(0,min(ys));hi=max(0,max(ys));pad=max(.2,(hi-lo)*.1);lo-=pad;hi+=pad;X=lambda z:60+550*(z-a)/(b-a);Y=lambda v:355-300*(v-lo)/(hi-lo)
 out=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 660 430"><rect width="660" height="430" fill="white"/>',f'<text x="60" y="25" font-size="16">{html.escape(title)}</text>',f'<path d="M60 {Y(0)}H615 M{X(0) if a<=0<=b else 60} 55V355" stroke="#8b94a2" fill="none"/>'];colors=['#bd443d','#2475b5','#368c65']
 for k,((label,fn),pts)in enumerate(zip(fnlist,samples)):
  out.append('<polyline points="'+' '.join(f'{X(z):.3f},{Y(v):.3f}'for z,v in pts)+f'" fill="none" stroke="{colors[k]}" stroke-width="2.5"/>');out.append(f'<text x="{60+k*180}" y="411" fill="{colors[k]}" font-size="14">{html.escape(label)}</text>')
 for j in range(7):
  xx=a+(b-a)*j/6;yy=lo+(hi-lo)*j/6;out.append(f'<text x="{X(xx)-8}" y="376" font-size="11">{xx:.3g}</text><text x="3" y="{Y(yy)+4}" font-size="11">{yy:.3g}</text>')
 out.append('</svg>');addfig(q,''.join(out),bi('원문 조건으로 계산한 함수 또는 명시한 그래프 판독값의 자체 도해.','Original plot calculated from the stated function or explicitly described source-graph readings.'))
def polygon_f(points):
 def f(z):
  k=next((k for k in range(len(points)-1)if z<=points[k+1][0]),len(points)-2);aa,fa=points[k];bb,fb=points[k+1];return fa+(fb-fa)*(z-aa)/(bb-aa)
 def g(z):
  v=0
  for (aa,fa),(bb,fb)in zip(points,points[1:]):
   if z<=aa:break
   end=min(z,bb);d=end-aa;v+=fa*d+(fb-fa)*d*d/(2*(bb-aa))
  return v
 return f,g
checks=[]
for q,f,F,line in[(1,S.cos(x)**2,x/2+S.sin(2*x)/4,r'F^{\prime}=1/2+\cos(2x)/2=\cos^2x'),(2,S.tan(x)**2,S.tan(x)-x,r'F^{\prime}=\sec^2x-1=\tan^2x'),(3,1/(x*x*S.sqrt(1+x*x)),-S.sqrt(1+x*x)/x,r'F^{\prime}=\frac{\sqrt{1+x^2}}{x^2}-\frac1{\sqrt{1+x^2}}=\frac1{x^2\sqrt{1+x^2}},\quad x\ne0')]:
 assert S.simplify(S.trigsimp(S.diff(F,x)-f))==0;calc(q,r'\int '+S.latex(f)+r'\,dx='+S.latex(F)+r'+C','우변을 미분하여 공식을 확인하라.','Verify the formula by differentiating the right side.',[r'\frac{d}{dx}C=0',line],r'\frac{d}{dx}\left('+S.latex(F)+r'+C\right)='+S.latex(f))
calc(4,r'\int x\sqrt{a+bx}\,dx=\frac2{15b^2}(3bx-2a)(a+bx)^{3/2}+C','우변을 미분하여 공식을 확인하고 매개변수 조건을 밝히라.','Verify by differentiation and state the parameter conditions.',[r'b\ne0,\quad a+bx>0',r'F^{\prime}=\frac2{15b^2}\left[3b(a+bx)^{3/2}+(3bx-2a)\frac{3b}2\sqrt{a+bx}\right]',r'F^{\prime}=\frac{\sqrt{a+bx}}{5b}[2(a+bx)+(3bx-2a)]=x\sqrt{a+bx}'],r'F^{\prime}(x)=x\sqrt{a+bx}\quad(b\ne0)','상수가 영인 경우 제시된 식은 정의되지 않으며, 근호 안 상수가 음수가 아니라면 이차식의 원시함수를 별도로 쓰면 된다.','When the coefficient of the input is zero, the displayed formula is undefined; if the remaining radicand is nonnegative, use the elementary quadratic antiderivative instead.')
indef=[(5,3*x*x+4*x+1),(6,5+2*S.sqrt(x)),(7,x+S.cos(x)),(8,x**S.Rational(1,3)+x**-S.Rational(1,3)),(9,x**S.Rational(13,10)+7*x**S.Rational(5,2)),(10,x**S.Rational(5,4)),(11,5+S.Rational(2,3)*x*x+S.Rational(3,4)*x**3),(12,x**6-2*x**5-x**3+S.Rational(2,7)),(13,(x+4)*(2*x+1)),(14,S.sqrt(x)*(x*x+3*x+2)),(15,(1+S.sqrt(x)+x)/S.sqrt(x)),(16,x*x+1+x**-2),(17,2+S.tan(x)**2),(18,S.sec(x)*(S.sec(x)+S.tan(x))),(19,3*S.csc(x)**2),(20,S.sin(2*x)/S.sin(x)),(21,S.cos(x)+x/2),(22,(1-x*x)**2),(75,S.sin(x)+S.sinh(x)),(77,x*x+1+1/(x*x+1))]
manual={17:x+S.tan(x),18:S.tan(x)+S.sec(x),19:-3*S.cot(x),20:2*S.sin(x)}
for q,f in indef:
 simp=S.trigsimp(S.expand(f));F=manual[q]if q in manual else S.integrate(simp,x);assert S.simplify(S.trigsimp(S.diff(F,x)-f))==0;checks.append((q,str(F)))
 lines=[r'f(x)='+S.latex(simp),r'\int f(x)\,dx='+S.latex(F)+r'+C',r'\frac{d}{dx}\left('+S.latex(F)+r'\right)='+S.latex(f)];k='가장 일반적인 부정적분을 구하라.';e='Find the general indefinite integral.'
 if q in[21,22]:k+=' 적분상수가 다른 여러 함수를 같은 좌표평면에 그려라.';e+=' Graph several members with different constants together.'
 if q==8:lines.append(r'x\ne0;\quad x^{1/3}=\text{real cube root};\quad C\text{ may differ across }0')
 if q==20:lines.insert(0,r'\sin(2x)/\sin x=2\cos x\quad(\sin x\ne0)');lines.append(r'C\text{ may differ on components between }k\pi')
 calc(q,r'\int\left('+S.latex(f)+r'\right)\,dx',k,e,lines,S.latex(F)+r'+C')
 if q in[21,22]:fn=S.lambdify(x,F,'math');curves(q,[(f'C={c}',lambda z,c=c:fn(z)+c)for c in[-2,0,2]],-2,2)
ints=[(23,x*x-3,-2,3),(24,4*x**3-3*x*x+2*x,1,2),(25,8*x**3-6*x**-2,1,4),(26,S.Rational(1,8)+x/2+x**S.Rational(1,3)/3,0,8),(27,(2*x-3)*(4*x*x+1),0,2),(28,x**-2-4*x**-3,1,2),(29,4*S.sin(x)-3*S.cos(x),0,S.pi),(30,x*(1-x)**2,-1,1),(31,(4+6*x)/S.sqrt(x),1,4),(32,(2-1/x**2)**2,1,2),(33,4*S.sec(x)**2,S.pi/6,S.pi/3),(34,S.sqrt(x)-3*S.cos(x),0,S.pi/2),(35,x*(x**S.Rational(1,3)+x**S.Rational(1,4)),0,1),(36,2*x**-S.Rational(1,3)-x**S.Rational(1,3),1,8),(37,S.sqrt(5/x),1,4),(38,S.csc(x)*S.cot(x),S.pi/6,S.pi/2),(39,(1+S.cos(x)**2)/S.cos(x)**2,0,S.pi/4),(40,(S.sin(x)+S.sin(x)*S.tan(x)**2)/S.sec(x)**2,0,S.pi/3),(41,S.sqrt(x)*(x-x**S.Rational(1,3)),0,64),(42,(1+x*x)**3,0,1),(76,2*S.exp(x)/(S.sinh(x)+S.cosh(x)),-10,10),(78,(x-1)**3/x**2,1,2),(79,(x*x-1)/(x**4-1),0,1/S.sqrt(3))]
for q,f,a,b in ints:
 simp=S.trigsimp(S.expand(f));simp=S.simplify(simp);F=S.integrate(simp,x);val=S.simplify(F.subs(x,b)-F.subs(x,a));assert S.simplify(S.trigsimp(S.diff(F,x)-f))==0;checks.append((q,str(val)))
 calc(q,rf'\int_{{{S.latex(a)}}}^{{{S.latex(b)}}}\left('+S.latex(f)+r'\right)\,dx','식을 간단히 한 뒤 정적분을 계산하라.','Simplify the integrand and evaluate the definite integral.',[r'f(x)='+S.latex(simp),r'F(x)='+S.latex(F),r'I=F('+S.latex(b)+r')-F('+S.latex(a)+r')='+S.latex(val)],S.latex(val))
for q,eq,lines,ans in[(43,r'\int_2^5|x-3|\,dx',[r'I=\int_2^3(3-x)\,dx+\int_3^5(x-3)\,dx',r'I=1/2+2'],r'5/2'),(44,r'\int_0^2|2x-1|\,dx',[r'I=\int_0^{1/2}(1-2x)\,dx+\int_{1/2}^2(2x-1)\,dx',r'I=1/4+9/4'],r'5/2'),(45,r'\int_{-1}^2(x-2|x|)\,dx',[r'x-2|x|=3x\ (x<0),\quad x-2|x|=-x\ (x\ge0)',r'I=\int_{-1}^0 3x\,dx-\int_0^2x\,dx=-3/2-2'],r'-7/2'),(46,r'\int_0^{3\pi/2}|\sin x|\,dx',[r'\sin x\ge0\ (0\le x\le\pi),\quad\sin x\le0\ (\pi\le x\le3\pi/2)',r'I=\int_0^\pi\sin x\,dx-\int_\pi^{3\pi/2}\sin x\,dx=2+1'],r'3')]:calc(q,eq,'절댓값 안의 부호가 바뀌는 점에서 나누어 계산하라.','Split where the expression inside the absolute value changes sign.',lines,ans)
for q,f in[(47,1-2*x-5*x**4),(48,2*x+3*x**4-2*x**6)]:
 roots=sorted(float(S.re(z))for z in S.nroots(f,maxsteps=200)if abs(float(S.im(z)))<1e-12);aa,bb=roots;F=S.integrate(f,x);A=float(F.subs(x,bb)-F.subs(x,aa));calc(q,r'y='+S.latex(f),'그래프로 가로축과의 교점을 추정하고 곡선 아래·가로축 위 영역의 넓이를 구하라.','Estimate the horizontal-axis intercepts graphically and the area below the curve and above the axis.',[r'f(x)=0\Rightarrow a\approx'+f'{aa:.10f}'+r',\quad b\approx'+f'{bb:.10f}',r'f(x)\ge0\quad(a\le x\le b)',r'A=\int_a^b f(x)\,dx=\left['+S.latex(F)+r'\right]_a^b\approx'+f'{A:.10f}'],r'a\approx'+f'{aa:.6f}'+r',\quad b\approx'+f'{bb:.6f}'+r',\quad A\approx'+f'{A:.6f}');rectplot(q,S.lambdify(x,f,'math'),aa,bb,[(450,'signed area')]);checks.append((q,dict(roots=roots,area=A)))
calc(49,r'x=2y-y^2,\quad x=0,\quad0\le y\le2','세로축 오른쪽과 포물선 왼쪽에 놓이는 영역을 가로 띠로 적분하여 넓이를 구하라.','Integrate horizontal strips to find the area right of the vertical axis and left of the parabola.',[r'\text{strip width}=x_{\rm right}-x_{\rm left}=2y-y^2',r'A=\int_0^2(2y-y^2)\,dy=[y^2-y^3/3]_0^2=4-8/3'],r'4/3')
calc(50,r'y=\sqrt[4]x,\quad x=0,\quad y=1','입력을 출력의 함수로 바꾸고 출력 변수로 적분하여 둘러싸인 넓이를 구하라.','Express the horizontal coordinate as a function of the vertical coordinate and integrate to find the enclosed area.',[r'x=y^4,\quad0\le y\le1',r'A=\int_0^1(y^4-0)\,dy=[y^5/5]_0^1'],r'1/5')
interpret=[(51,r'w^{\prime}(t)\text{ in lb/year};\quad\int_5^{10}w^{\prime}(t)\,dt',r'\int_5^{10}w^{\prime}(t)\,dt=w(10)-w(5)','아이가 다섯 살부터 열 살까지 늘어난 몸무게이며 단위는 파운드이다.','The child’s weight gain from age five to ten, measured in pounds.'),(52,r'I(t)=Q^{\prime}(t);\quad\int_a^b I(t)\,dt',r'\int_a^b I(t)\,dt=Q(b)-Q(a)','해당 시간 동안 도선을 통과한 전하의 순변화이며 단위는 쿨롱이다.','The net charge transferred through the wire over the interval, in coulombs.'),(53,r'r(t)\text{ in gal/min};\quad\int_0^{120}r(t)\,dt',r'\int_0^{120}r(t)\,dt=\text{total leaked volume}','처음 두 시간 동안 탱크에서 새어 나온 기름의 양이며 단위는 갤런이다.','The oil leaked from the tank during the first two hours, in gallons.'),(54,r'n(0)=100;\quad100+\int_0^{15}n^{\prime}(t)\,dt',r'100+\int_0^{15}n^{\prime}(t)\,dt=n(15)','시작한 지 열다섯 주 후의 벌 개체수이다.','The bee population fifteen weeks after the start.'),(55,r'R^{\prime}(x)\text{ marginal revenue};\quad\int_{1000}^{5000}R^{\prime}(x)\,dx',r'\int_{1000}^{5000}R^{\prime}(x)\,dx=R(5000)-R(1000)','판매량을 천 개에서 오천 개로 늘릴 때 총수입이 증가한 금액이다.','The increase in revenue as sales increase from one thousand to five thousand units.'),(56,r'f(x)=h^{\prime}(x)\text{ trail slope};\quad\int_3^5 f(x)\,dx',r'\int_3^5f(x)\,dx=h(5)-h(3)','출발점에서 삼 마일 지점과 오 마일 지점 사이의 고도 순변화이다. 경사에서 사용한 높이 단위가 결과의 단위가 된다.','The net elevation change between the three-mile and five-mile points. Its unit is the elevation unit used in defining the slope.'),(57,r'h(t)\text{ in beats/min};\quad\int_0^{30}h(t)\,dt',r'\int_0^{30}h(t)\,dt=\text{total heartbeat count}','운동을 시작한 뒤 처음 삼십 분 동안의 총 심장박동수이다.','The total number of heartbeats during the first thirty minutes of exercise.')]
contexts={
 51:bi('나이 t(년)에 따른 아이의 몸무게를 w(t)(파운드)라 한다.','Let w(t) be a child’s weight in pounds at age t years.'),
 52:bi('시간 t(초)까지 도선을 통과한 전하 Q(t)(쿨롱)의 변화율 I(t)는 전류이다.','Q(t) is charge in coulombs passing through a wire by time t seconds; I(t) is the current.'),
 53:bi('시간 t(분)에 탱크에서 기름이 새는 속도가 r(t)이다.','r(t) is the oil leakage rate from a tank at time t minutes.'),
 54:bi('관찰 시작 후 t주일 때 벌의 개체수를 n(t)라 한다.','n(t) counts the bees t weeks after observation begins.'),
 55:bi('x개를 판매했을 때의 총수입을 R(x)라 한다.','R(x) is total revenue from selling x units.'),
 56:bi('등산로 출발점에서 x마일 떨어진 지점의 고도를 h(x)라 한다.','h(x) is elevation at a point x miles along a trail from its start.'),
 57:bi('운동 시작 후 t분일 때의 분당 심박수를 h(t)라 한다.','h(t) is heart rate in beats per minute, t minutes into exercise.'),
}
for q,eq,line,k,e in interpret:
 calc(q,eq,contexts[q]['ko']+' 정적분이 나타내는 양과 단위를 설명하라.',contexts[q]['en']+' Explain the quantity represented by the integral and its units.',[line],line,k,e);items[-1]['answer']=bi(k+' '+M(line),e+' '+M(line))
calc(58,r'[x]=\mathrm{ft},\quad[a(x)]=\mathrm{lb/ft}','도함수와 이부터 팔까지 정적분의 단위를 각각 구하라.','Find the units of the derivative and of the definite integral from two to eight.',[r'[da/dx]=(\mathrm{lb/ft})/\mathrm{ft}=\mathrm{lb/ft^2}',r'\left[\int_2^8a(x)\,dx\right]=(\mathrm{lb/ft})\mathrm{ft}=\mathrm{lb}'],r'[da/dx]=\mathrm{lb/ft^2};\quad\left[\int_2^8a(x)\,dx\right]=\mathrm{lb}')
calc(59,r'[x]=\mathrm m,\quad[f(x)]=\mathrm N','영부터 백까지 적분의 단위를 구하라.','Find the units of the integral from zero to one hundred.',[r'\left[\int_0^{100}f(x)\,dx\right]=\mathrm{N\,m}=\mathrm J'],r'\mathrm{N\,m}\text{ (joules)}')
v60,s60=polygon_f([(0,0),(2,5),(3,2),(4,2),(6,0),(8,0),(10,-4),(12,0)])
calc(60,r'v(t)\ (\mathrm{m/s})\text{ joins }(0,0),(2,5),(3,2),(4,2),(6,0),(8,0),(10,-4),(12,0);\quad s(0)=0','충전소를 출발한 차량의 (a) 이·사·육·팔·십·십이 초에서 충전소까지 거리 (b) 가장 멀리 있는 시각 (c) 총 이동거리를 구하라.','For a vehicle starting at its charging station, find (a) distances from the station at two, four, six, eight, ten, and twelve seconds, (b) when it is farthest away, and (c) total distance traveled.',[r's(t)=\int_0^t v(u)\,du',r's(2)=5,\quad s(4)=5+7/2+2=21/2',r's(6)=s(8)=25/2,\quad s(10)=25/2-4=17/2,\quad s(12)=9/2',r's(t)\ge0\text{ throughout, so distance from station}=s(t)',r'D=\int_0^{12}|v(t)|\,dt=25/2+8=41/2'],r'\text{(a)}\ (5,10.5,12.5,12.5,8.5,4.5)\ \mathrm m;\quad\text{(b)}\ 6\le t\le8;\quad\text{(c)}\ 20.5\ \mathrm m',sub='abc');curves(60,[('v (m/s)',v60),('s (m)',s60)],0,12)
for q,v,a,b,c in[(61,3*x-5,0,3,S.Rational(5,3)),(62,x*x-2*x-3,2,4,S.Integer(3))]:
 F=S.integrate(v,x);disp=S.simplify(F.subs(x,b)-F.subs(x,a));D=S.simplify(F.subs(x,a)+F.subs(x,b)-2*F.subs(x,c));calc(q,rf'v(t)={S.latex(v.subs(x,S.Symbol("t")))},\quad {a}\le t\le{b}\quad(\mathrm{{m/s}})','(a) 변위와 (b) 총 이동거리를 구하라.','Find (a) displacement and (b) total distance.',[r'v(t)=0\Rightarrow t='+S.latex(c),r'v<0\text{ before this point and }v>0\text{ after it}',r'\text{(a)}\ \Delta s=\int_a^b v(t)\,dt='+S.latex(disp),r'\text{(b)}\ D=-\int_a^{'+S.latex(c)+r'}v(t)\,dt+\int_{'+S.latex(c)+r'}^b v(t)\,dt='+S.latex(D)],r'\text{(a)}\ '+S.latex(disp)+r'\ \mathrm m;\quad\text{(b)}\ '+S.latex(D)+r'\ \mathrm m',sub='ab')
calc(63,r'a(t)=t+4\ \mathrm{m/s^2},\quad v(0)=5\ \mathrm{m/s},\quad0\le t\le10','(a) 속도와 (b) 해당 시간 동안의 이동거리를 구하라.','Find (a) velocity and (b) distance traveled over the interval.',[r'v(t)=5+\int_0^t(u+4)\,du=5+4t+t^2/2>0',r'D=\int_0^{10}(5+4t+t^2/2)\,dt=[5t+2t^2+t^3/6]_0^{10}=1250/3'],r'\text{(a)}\ v(t)=5+4t+t^2/2\ \mathrm{m/s};\quad\text{(b)}\ D=1250/3\ \mathrm m',sub='ab')
calc(64,r'a(t)=2t+3\ \mathrm{m/s^2},\quad v(0)=-4\ \mathrm{m/s},\quad0\le t\le3','(a) 속도와 (b) 해당 시간 동안의 이동거리를 구하라.','Find (a) velocity and (b) distance traveled over the interval.',[r'v(t)=-4+\int_0^t(2u+3)\,du=t^2+3t-4=(t+4)(t-1)',r'v<0\ (0<t<1),\quad v>0\ (1<t<3)',r'F(t)=t^3/3+3t^2/2-4t,\quad F(1)=-13/6,\quad F(3)=21/2',r'D=-[F(1)-F(0)]+[F(3)-F(1)]=89/6'],r'\text{(a)}\ v(t)=t^2+3t-4\ \mathrm{m/s};\quad\text{(b)}\ D=89/6\ \mathrm m',sub='ab')
calc(65,r'\rho(x)=9+2\sqrt x\ \mathrm{kg/m},\quad0\le x\le4','막대의 총질량을 구하라.','Find the total mass of the rod.',[r'm=\int_0^4\rho(x)\,dx=[9x+4x^{3/2}/3]_0^4=36+32/3'],r'140/3\ \mathrm{kg}')
calc(66,r'r(t)=200-4t\ \mathrm{L/min},\quad0\le t\le50','처음 십 분 동안 탱크에서 나간 물의 양을 구하라.','Find the amount of water leaving the tank during the first ten minutes.',[r'V=\int_0^{10}(200-4t)\,dt=[200t-2t^2]_0^{10}=2000-200'],r'1800\ \mathrm L')
calc(67,r't=(0,10,20,30,40,50,60,70,80,90,100)\ \mathrm s,\quad v=(0,38,52,58,55,51,56,53,50,47,45)\ \mathrm{mi/h}','중점법으로 자동차가 이동한 거리를 추정하라.','Estimate distance traveled using the Midpoint Rule.',[r'n=5,\quad\Delta t=20\ \mathrm s=20/3600\ \mathrm h',r't_i^*=10,30,50,70,90',r'D\approx\frac{20}{3600}(38+58+51+53+47)=247/180'],r'D\approx1.37222\ \mathrm{mi}')
calc(68,r't=(0,1,2,3,4,5,6)\ \mathrm s,\quad r=(2,10,24,36,46,54,60)\ \mathrm{tonnes/s}','화산 분출량의 (a) 상하 추정과 (b) 중점 추정을 구하라.','Find (a) upper and lower estimates and (b) a midpoint estimate of the erupted mass.',[r'\text{(a)}\ L_6=1(2+10+24+36+46+54)=172',r'R_6=1(10+24+36+46+54+60)=230',r'\text{(b)}\ M_3=2[r(1)+r(3)+r(5)]=2(10+36+54)=200'],r'\text{(a)}\ 172\le Q(6)\le230\ \mathrm{tonnes}\text{ if }r\text{ is increasing between samples};\quad\text{(b)}\ Q(6)\approx200\ \mathrm{tonnes}','표가 증가하므로 관측 사이에서도 분출률이 증가한다고 가정한 상하 추정이다. 이 가정이 없으면 유한한 표본값만으로 엄밀한 상하한을 보장할 수 없다.','The upper and lower estimates assume the rate increases between observations as the table suggests. Finite samples alone cannot guarantee rigorous bounds without that assumption.',sub='ab')
calc(69,r'\text{July days }(18,19,20,21,22,23,24,25,26),\quad r=(5275,6401,2554,4249,3016,3821,2462,2628,3003)\ \mathrm{ft^3/s}','매일 같은 시각의 유입률로 십팔일부터 이십육일까지 유입된 물의 부피를 중점법으로 추정하라.','Use the readings at the same time each day to estimate inflow volume from the eighteenth through the twenty-sixth by the Midpoint Rule.',[r'n=4,\quad\Delta t=2\text{ days}=172800\ \mathrm s',r'\text{midpoint days}=19,21,23,25',r'V\approx172800(6401+4249+3821+2628)=172800(17099)'],str(172800*17099)+r'\ \mathrm{ft^3}')
calc(70,r'V(0)=25000\ \mathrm L;\quad r(0.5),r(1.5),r(2.5),r(3.5)\approx(1500,1800,750,-700)\ \mathrm{L/day}','원문 그래프에서 읽은 중점 유입·유출률로 사 일 후의 물의 양을 추정하라.','Use the midpoint net flow rates read from the source graph to estimate the water volume after four days.',[r'\Delta t=1\text{ day},\quad V(4)=V(0)+\int_0^4 r(t)\,dt',r'V(4)\approx25000+1(1500+1800+750-700)=28350'],r'V(4)\approx2.84\times10^4\ \mathrm L','그래프 판독에 따른 근사이며 유출 구간의 음의 부호를 유지한다.','This is a graph-reading approximation; the outflow contribution retains its negative sign.')
calc(71,r'a(1),a(3),a(5)\approx(0.5,10,10)\ \mathrm{ft/s^2}','가속도 그래프에서 읽은 값과 중점법으로 육 초 동안의 속도 증가량을 추정하라.','Use the acceleration readings from the graph and the Midpoint Rule to estimate the velocity increase over six seconds.',[r'n=3,\quad\Delta t=2\ \mathrm s',r'\Delta v=\int_0^6a(t)\,dt\approx2[a(1)+a(3)+a(5)]',r'\Delta v\approx2(0.5+10+10)'],r'\Delta v\approx41\ \mathrm{ft/s}')
calc(72,r'D(1),D(3),D(5),D(7)\approx(0.30,0.50,0.55,0.82)\ \mathrm{Mb/s}','자정부터 오전 팔 시까지의 전송률 그래프를 중점법으로 적분하여 전송량을 추정하라.','Use midpoint readings from the midnight-to-eight traffic graph to estimate the total data transmitted.',[r'n=4,\quad\Delta t=2\ \mathrm h=7200\ \mathrm s',r'Q\approx7200(0.30+0.50+0.55+0.82)=15624\ \mathrm{Mb}'],r'Q\approx1.56\times10^4\ \mathrm{Mb}\approx15.6\ \mathrm{Gb}','단위는 비트 기준이며 바이트로 바꾸려면 팔로 나눈다. 그래프 표본값은 근사이다.','These are bit units; divide by eight for bytes. The graph readings are approximate.')
powerval=[11.2,10.5,10.9,13.8,15.2,15.6,15.3,15.1,15.0,16.3,14.8,12.9]
calc(73,r't_i^*=(1,3,5,7,9,11,13,15,17,19,21,23)\ \mathrm h;\quad P(t_i^*)\approx(11.2,10.5,10.9,13.8,15.2,15.6,15.3,15.1,15.0,16.3,14.8,12.9)\ \mathrm{GW}','하루 전력사용 그래프의 중점 표본값으로 총 에너지를 추정하라.','Estimate total daily energy using these midpoint readings from the power-consumption graph.',[r'E=\int_0^{24}P(t)\,dt,\quad\Delta t=2\ \mathrm h',r'E\approx2\sum_{i=1}^{12}P(t_i^*)=2(166.6)=333.2\ \mathrm{GWh}',r'1\ \mathrm{GWh}=3.6\times10^{12}\ \mathrm J'],r'E\approx333\ \mathrm{GWh}\approx1.20\times10^{15}\ \mathrm J','그래프 눈금에서 읽은 값이므로 마지막 소수까지 정확한 측정값을 의미하지 않는다.','These values are read from graph scales; the last decimals do not represent exact measurements.')
tdata=[0,10,15,20,32,59,62,125];vdata=[0,185,319,447,742,1325,1445,4151];A=S.Matrix([[1,t,t*t,t**3]for t in tdata]);V=S.Matrix(vdata);coef=(A.T*A).inv()*A.T*V;P=sum(coef[k]*x**k for k in range(4));height=S.integrate(P,(x,0,125));assert all(z==0 for z in A.T*(A*coef-V));model='+'.join(f'({float(coef[k]):.12g})t^{k}'for k in range(4))
calc(74,r't=(0,10,15,20,32,59,62,125)\ \mathrm s;\quad v=(0,185,319,447,742,1325,1445,4151)\ \mathrm{ft/s}','우주왕복선 관측자료를 (a) 삼차 다항식으로 회귀하고 (b) 발사 후 백이십오 초의 높이를 추정하라.','(a) Fit a cubic polynomial to the shuttle velocity data and (b) estimate its height at one hundred twenty-five seconds after launch.',[r'p(t)=c_0+c_1t+c_2t^2+c_3t^3',r'\min_c\sum_i[p(t_i)-v_i]^2\Rightarrow(X^{T}X)c=X^{T}v',r'p(t)\approx'+model,r'h(125)-h(0)\approx\int_0^{125}p(t)\,dt=\left[c_0t+\frac{c_1t^2}2+\frac{c_2t^3}3+\frac{c_3t^4}4\right]_0^{125}\approx'+f'{float(height):.8f}'],r'\text{(a)}\ p(t)\approx'+model+r';\quad\text{(b)}\ h(125)-h(0)\approx'+f'{float(height):.2f}'+r'\ \mathrm{ft}','전체 자료에 대한 비제약 최소제곱 삼차회귀다. 회귀식이 원점을 정확히 지나도록 별도의 제약을 가한 모형과는 다를 수 있다. 높이는 발사 지점을 기준으로 한 증가량이다.','This is an unconstrained cubic least-squares fit to all observations. A fit separately constrained to pass through the origin may differ. Height is the increase relative to the launch point.',sub='ab');curves(74,[('cubic velocity fit (ft/s)',S.lambdify(x,P,'math'))],0,125);checks.append((74,{'coefficients':[str(c)for c in coef],'height':str(height)}))
calc(80,r'A=\int_0^a e^x\,dx,\quad B=\int_0^b e^x\,dx,\quad B=3A,\quad a>0','큰 영역의 오른쪽 끝점을 작은 영역의 끝점으로 나타내라.','Express the right endpoint of the larger area in terms of the smaller one.',[r'A=e^a-1,\quad B=e^b-1',r'e^b-1=3(e^a-1)\Rightarrow e^b=3e^a-2',r'b=\ln(3e^a-2),\quad3e^a-2>1'],r'b=\ln(3e^a-2)')
items.sort(key=lambda e:e['number']);assert[e['number']for e in items]==list(range(1,81))
raw={'section':'4.4','source':{'title':'Calculus','edition':'9','language':'en','printedPages':[345,346,347,348],'pdfPages':[382,383,384,385]},'scope':{'kind':'exercise','numbers':list(range(1,81)),'total':80,'note':bi('일반 Exercises의 모든 주번호와 소문항.','All main-numbered ordinary Exercises and their subparts.')},'exercises':items}
sys.path.insert(0,str(BASE));from build_exercises import validate_document
validate_document(raw,BASE/'exercise-content/s4-4.json')
import xml.etree.ElementTree as ET
for ex in items:
 if 'figure'in ex:ET.parse(BASE/'exercise-content/assets'/Path(ex['figure']['src']).name)
 for fld in ['statement','answer']:assert re.findall(r'\\\((.*?)\\\)',ex[fld]['ko'])==re.findall(r'\\\((.*?)\\\)',ex[fld]['en'])
 for fld in ['statement','hint','steps','answer','check']:assert not re.search('[가-힣ぁ-ヿ]',str(ex[fld]['en'])),(ex['number'],fld)
assert [s60(j)for j in[2,4,6,8,10,12]]==[5,10.5,12.5,12.5,8.5,4.5]
assert abs(sum(powerval)-166.6)<1e-10
assert S.integrate(x*x+3*x-4,(x,1,3))-S.integrate(x*x+3*x-4,(x,0,1))==S.Rational(89,6)
(BASE/'exercise-checks/s4-4-independent.json').write_text(json.dumps(checks,ensure_ascii=False,indent=2)+'\n')
(BASE/'exercise-content/s4-4.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print('4.4: 80 cards; derivative checks, exact integrals, roots, regression normal equations, unit conversions, schema and SVG XML checked')
