import json,math,html
from pathlib import Path
BASE=Path(__file__).resolve().parents[1]
items=[]
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':e if e is not None else k}
def add(n,sk,se,hk,he,steps,ak,ae,ck,ce,sub=''):
 p=648 if n<=10 else 649 if n<=24 else 650
 items.append(dict(id=f'stewart9-exercise-9.1-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('미분방정식 모델과 해의 검증','Differential equation models and solution verification'),statement=bi(sk,se),hint=bi(hk,he),steps={'ko':[x[0] for x in steps],'en':[x[1] for x in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
models=[
(1,'나무 줄기 반지름의 시간 변화율이 반지름에 반비례한다.','A tree trunk radius changes at a rate inversely proportional to its radius.',r'r=r(t)',r'\frac{dr}{dt}=\frac{k}{r},\quad r>0','반비례는 역수의 상수배이다.','Inverse proportionality means a constant times the reciprocal.'),
(2,'낙하체의 속도 변화율이 일정하다.','A falling body has a constant rate of change of velocity.',r'v=v(t)',r'\frac{dv}{dt}=a\quad(a\text{ constant})','일정한 속도 변화율은 일정한 가속도이다.','A constant velocity rate means constant acceleration.'),
(3,'최고 속력이 주어지고, 차의 속력 증가율은 최고 속력과 현재 속력의 차이에 비례한다.','A car accelerates at a rate proportional to the gap between its maximum and current speed.',r'v=v(t),\ M\text{ maximum}',r'\frac{dv}{dt}=k(M-v),\quad k>0','현재 속력이 최고 속력에 접근할수록 차이가 줄어든다.','The speed gap shrinks as the current speed approaches the maximum.'),
(4,'고정 인구에서 감염자 증가율은 감염자 수와 비감염자 수의 곱에 비례한다.','In a fixed population, the infection rate is proportional to the product of infected and uninfected counts.',r'N\text{ total},\ y=y(t)\text{ infected}',r'\frac{dy}{dt}=ky(N-y),\quad k>0','비감염자 수는 전체 인구에서 감염자 수를 뺀 값이다.','The uninfected count is the total minus the infected count.'),
(5,'고정 인구에서 광고를 들은 사람의 증가율은 아직 듣지 못한 사람 수에 비례한다.','In a fixed population, awareness of an advertisement grows at a rate proportional to the unaware count.',r'N\text{ total},\ y=y(t)\text{ aware}',r'\frac{dy}{dt}=k(N-y),\quad k>0','아직 듣지 못한 사람 수를 비례식에 넣는다.','Use the unaware count in the proportionality law.')]
for n,k,e,v,a,reason,re in models:
 add(n,k+' '+M(v)+' 미분방정식으로 나타내라.',e+' '+M(v)+' Formulate a differential equation.','변화율을 시간 도함수로 쓴다.','Express the rate as a time derivative.',[(reason,re),('비례상수를 도입하면 '+M(a)+'.','Introducing a proportionality constant gives '+M(a)+'.')],M(a),M(a),'식의 우변이 주어진 비례 관계를 그대로 만족한다.','The right-hand side has exactly the specified proportionality.')
verify=[(6,r'\sin x-\cos x',r"y'+y=2\sin x",r"y'=\cos x+\sin x",r"y'+y=2\sin x",True,'모든 실수','all real numbers'),(7,r'\frac23e^x+e^{-2x}',r"y'+2y=2e^x",r"y'=\frac23e^x-2e^{-2x}",r"y'+2y=2e^x",True,'모든 실수','all real numbers'),(8,r'\tan x',r"y'-y^2=1",r"y'=\sec^2x",r"y'-y^2=\sec^2x-\tan^2x=1",True,'코사인이 영이 아닌 각 열린 구간','each open interval without a cosine zero'),(9,r'\sqrt{x}',r"xy'-y=0",r"y'=\frac1{2\sqrt{x}}",r"xy'-y=-\frac{\sqrt{x}}2",False,'양의 실수','positive real numbers'),(10,r'\sqrt{1-x^2}',r"yy'-x=0",r"y'=-\frac{x}{\sqrt{1-x^2}}",r"yy'-x=-2x",False,'근호가 양수인 열린 구간','the open interval where the radical is positive'),(11,r'x^3',r"x^2y''-6y=0",r"y''=6x",r"x^2y''-6y=6x^3-6x^3=0",True,'모든 실수','all real numbers'),(12,r'\ln x',r"xy''-y'=0",r"y'=1/x,\ y''=-1/x^2",r"xy''-y'=-2/x",False,'양의 실수','positive real numbers')]
for n,y,eq,der,res,yes,dom,de in verify:
 st=M('y='+y)+', '+M(eq)
 add(n,st+' 함수가 방정식의 해인지 판정하라.',st+' Determine whether the function solves the equation.','필요한 도함수를 직접 대입한다.','Differentiate and substitute.',[(M(der)+'.',M(der)+'.'),('대입 결과 '+M(res)+'.','Substitution yields '+M(res)+'.')],('해이다. 정의역: ' if yes else '해가 아니다. 검사 구간: ')+dom+'.',('It is a solution on ' if yes else 'It is not a solution; tested on ')+de+'.','방정식은 한 점이 아니라 정의역의 열린 구간 전체에서 성립해야 한다.','A differential equation must hold throughout an open interval, not merely at one point.')
add(13,M(r'y=-t\cos t-t')+'가 '+M(r"ty'=y+t^2\sin t,\ y(\pi)=0")+'을 만족함을 보여라.', 'Verify '+M(r'y=-t\cos t-t')+' for '+M(r"ty'=y+t^2\sin t,\ y(\pi)=0")+'.','방정식과 초기값을 따로 검사한다.','Check the equation and initial value separately.',[(M(r"y'=-\cos t+t\sin t-1")+'.',M(r"y'=-\cos t+t\sin t-1")+'.'),(M(r"ty'=-t\cos t+t^2\sin t-t=y+t^2\sin t")+'.',M(r"ty'=-t\cos t+t^2\sin t-t=y+t^2\sin t")+'.')],M(r'y(\pi)=-\pi(-1)-\pi=0')+'; 해이다.',M(r'y(\pi)=-\pi(-1)-\pi=0')+'; it is a solution.','나눗셈 없이 원래 식을 검사했으므로 시간 영에서도 성립한다.','Checking the undivided equation also covers time zero.')
add(14,M(r'y=5e^{2x}+x')+'가 '+M(r"y'-2y=1-2x,\ y(0)=5")+'을 만족함을 보여라.','Verify '+M(r'y=5e^{2x}+x')+' for '+M(r"y'-2y=1-2x,\ y(0)=5")+'.','미분 후 지수항을 소거한다.','Differentiate and cancel the exponential terms.',[(M(r"y'=10e^{2x}+1")+'.',M(r"y'=10e^{2x}+1")+'.'),(M(r"y'-2y=10e^{2x}+1-10e^{2x}-2x=1-2x")+'.',M(r"y'-2y=10e^{2x}+1-10e^{2x}-2x=1-2x")+'.')],M(r'y(0)=5')+'; 해이다.',M(r'y(0)=5')+'; it is a solution.','방정식과 초기조건이 모두 맞는다.','Both the equation and initial condition hold.')
add(15,'(a) '+M(r'y=e^{rx}')+'가 '+M(r"2y''+y'-y=0")+'을 푸는 상수를 구하라. (b) 두 지수해의 임의 선형결합도 해임을 보여라.','(a) Find the constants for which '+M(r'y=e^{rx}')+' solves '+M(r"2y''+y'-y=0")+'. (b) Verify any linear combination of the two exponential solutions.','지수함수는 영이 아니므로 특성다항식을 푼다.','The exponential is nonzero, so solve its characteristic polynomial.',[(M(r'(2r^2+r-1)e^{rx}=0,\quad(2r-1)(r+1)=0')+'.',M(r'(2r^2+r-1)e^{rx}=0,\quad(2r-1)(r+1)=0')+'.'),('미분 연산은 선형이므로 각 항의 잔차가 영이면 합의 잔차도 영이다.','Differentiation is linear, so a combination of zero residuals remains zero.')],M(r'r=1/2,-1;\quad y=ae^{x/2}+be^{-x}')+' (임의의 상수).',M(r'r=1/2,-1;\quad y=ae^{x/2}+be^{-x}')+' (arbitrary constants).','각 기저함수를 원래 식에 대입하면 영이다.','Each basis function gives zero in the original equation.','ab')
add(16,'(a) '+M(r'y=\cos kt')+'가 '+M(r"4y''=-25y")+'를 만족하는 상수를 구하라. (b) '+M(r'y=A\sin kt+B\cos kt')+'도 검증하라.','(a) Find the constants for which '+M(r'y=\cos kt')+' satisfies '+M(r"4y''=-25y")+'. (b) Verify '+M(r'y=A\sin kt+B\cos kt')+'.','두 번 미분하면 주파수 제곱이 나온다.','Differentiate twice to obtain the squared frequency.',[(M(r'y^{\prime\prime}=-k^2\cos kt,\quad4k^2=25')+'.',M(r'y^{\prime\prime}=-k^2\cos kt,\quad4k^2=25')+'.'),('사인항과 코사인항 모두 같은 2계 도함수 관계를 만족한다.','Both sine and cosine terms satisfy the same second-derivative relation.')],M(r'k=\pm5/2;\quad y=A\sin(5t/2)+B\cos(5t/2)')+'.',M(r'k=\pm5/2;\quad y=A\sin(5t/2)+B\cos(5t/2)')+'.','주파수의 부호는 임의 사인계수에 흡수된다.','Changing the frequency sign is absorbed into the sine coefficient.','ab')
add(17,M(r"y''+y=\sin x")+'의 해를 고르라: (a) '+M(r'\sin x')+', (b) '+M(r'\cos x')+', (c) '+M(r'\tfrac12x\sin x')+', (d) '+M(r'-\tfrac12x\cos x')+'.','Select the solutions of '+M(r"y''+y=\sin x")+': (a) '+M(r'\sin x')+', (b) '+M(r'\cos x')+', (c) '+M(r'\tfrac12x\sin x')+', (d) '+M(r'-\tfrac12x\cos x')+'.','곱의 미분법을 두 번 적용한다.','Apply the product rule twice.',[('좌변의 값은 순서대로 '+M(r'0,0,\cos x,\sin x')+'.','The left-hand sides are respectively '+M(r'0,0,\cos x,\sin x')+'.'),('따라서 마지막 함수만 원하는 우변과 일치한다.','Only the last function produces the required right-hand side.')],'(d)만 해이다.','Only (d) is a solution.','한 점에서의 일치가 아닌 함수의 항등적 일치를 검사했다.','The comparison is an identity of functions, not agreement at a point.','abcd')
add(18,'(a) '+M(r'y=(\ln x+C)/x')+'를 '+M(r"x^2y'+xy=1")+'에 대입 검증하라. (b) 여러 해를 그려라. (c) '+M(r'y(1)=2')+', (d) '+M(r'y(2)=1')+'인 해를 구하라.','(a) Verify '+M(r'y=(\ln x+C)/x')+' in '+M(r"x^2y'+xy=1")+'. (b) Plot several members. Find the solutions with (c) '+M(r'y(1)=2')+' and (d) '+M(r'y(2)=1')+'.','몫의 미분법과 각 초기조건을 사용한다.','Use the quotient rule and each initial condition.',[(M(r"y'=(1-\ln x-C)/x^2,\quad x^2y'+xy=1")+'.',M(r"y'=(1-\ln x-C)/x^2,\quad x^2y'+xy=1")+'.'),('그림은 여러 상수에서의 해와 두 초기값 해를 보여준다. 초기값 대입으로 '+M(r'C=2,\ C=2-\ln2')+'.','The plot shows several members and both initial-value solutions. Substitution gives '+M(r'C=2,\ C=2-\ln2')+'.')],M(r'\text{(c) }y=(\ln x+2)/x;\quad\text{(d) }y=(\ln x+2-\ln2)/x;\quad x>0'),M(r'\text{(c) }y=(\ln x+2)/x;\quad\text{(d) }y=(\ln x+2-\ln2)/x;\quad x>0'),'두 식에 각각 주어진 입력을 넣으면 초기값이 복원된다.','The specified inputs reproduce both initial values.','abcd')
add(19,M(r"y'=-y^2")+'에 대해 (a) 해의 증가·감소를 설명하라. (b) '+M(r'y=1/(x+C)')+'를 검증하라. (c) 이 족에 없는 해를 찾아라. (d) '+M(r'y(0)=0.5')+'를 풀어라.','For '+M(r"y'=-y^2")+': (a) describe monotonicity; (b) verify '+M(r'y=1/(x+C)')+'; (c) find a solution absent from that family; (d) impose '+M(r'y(0)=0.5')+'.','우변의 부호와 상수해를 검사한다.','Inspect the sign and constant solutions.',[('(a) '+M(r"y'\le0")+'이므로 해는 비증가한다. (b) '+M(r"y'=-(x+C)^{-2}=-y^2")+'.','(a) '+M(r"y'\le0")+' makes every solution nonincreasing. (b) '+M(r"y'=-(x+C)^{-2}=-y^2")+'.'),('(c) 영함수도 해이며 유한한 상수로 표현할 수 없다. (d) '+M(r'1/C=1/2\Rightarrow C=2')+'.','(c) The zero function is a solution absent for finite constants. (d) '+M(r'1/C=1/2\Rightarrow C=2')+'.')],M(r'\text{(c) }y=0;\quad\text{(d) }y=1/(x+2),\quad -2<x<\infty'),M(r'\text{(c) }y=0;\quad\text{(d) }y=1/(x+2),\quad -2<x<\infty'),'초기점을 포함하는 최대 구간은 분모의 영점을 넘을 수 없다.','The maximal interval containing the initial point cannot cross the denominator zero.','abcd')
add(20,M(r"y'=xy^3")+'에 대해 (a) 영 근처와 큰 입력에서 기울기를 논하라. (b) '+M(r'y=(c-x^2)^{-1/2}')+'를 검증하고 (c) 여러 해를 그려라. (d) '+M(r'y(0)=2')+'를 풀어라.','For '+M(r"y'=xy^3")+': (a) discuss slopes near zero and at large inputs; (b) verify '+M(r'y=(c-x^2)^{-1/2}')+'; (c) plot members; (d) solve with '+M(r'y(0)=2')+'.','기울기는 입력과 함수값 세제곱의 곱이다.','The slope is the input times the cube of the solution value.',[('(a) 유한한 해는 영 근처에서 거의 수평이다. 큰 입력만으로 급경사를 보장하지는 않으며 함수값도 알아야 한다.','(a) A finite solution is nearly horizontal near zero. A large input alone does not force a steep slope; the solution value also matters.'),(M(r"y'=x(c-x^2)^{-3/2}=xy^3")+'; 실수 해에는 '+M(r'c>0,\ |x|<\sqrt c')+'가 필요하다.',M(r"y'=x(c-x^2)^{-3/2}=xy^3")+'; real members require '+M(r'c>0,\ |x|<\sqrt c')+'.'),('그림은 중앙의 수평 접선과 끝점 근처의 발산을 보인다. '+M(r'c^{-1/2}=2\Rightarrow c=1/4')+'.','The curves have horizontal tangents at their centers and diverge at their endpoints. '+M(r'c^{-1/2}=2\Rightarrow c=1/4')+'.')],M(r'y=1/\sqrt{1/4-x^2},\quad |x|<1/2'),M(r'y=1/\sqrt{1/4-x^2},\quad |x|<1/2'),'원점의 값은 이이고 분모의 양수 조건이 최대 구간을 정한다.','The value at zero is two, and positivity of the denominator determines the maximal interval.','abcd')
add(21,M(r'P\ge0,\quad P^{\prime}=1.2P(1-P/4200)')+'에서 (a) 증가, (b) 감소, (c) 평형 인구를 구하라.','For '+M(r'P\ge0,\quad P^{\prime}=1.2P(1-P/4200)')+', find (a) increasing, (b) decreasing, and (c) equilibrium populations.','두 인자의 부호를 나눈다.','Make a sign chart for the two factors.',[('영점은 '+M(r'P=0,4200')+'이고 두 영점 사이에서는 두 인자가 양수이다.','The zeros are '+M(r'P=0,4200')+'; between them both factors are positive.'),('수용력보다 크면 두 번째 인자가 음수이다.','Above carrying capacity the second factor is negative.')],M(r'\text{(a) }0<P<4200;\quad\text{(b) }P>4200;\quad\text{(c) }P(t)\equiv0,4200'),M(r'\text{(a) }0<P<4200;\quad\text{(b) }P>4200;\quad\text{(c) }P(t)\equiv0,4200'),'수학적으로 음의 인구도 허용하면 그 구간에서도 감소한다.','If negative populations are allowed mathematically, solutions also decrease there.','abc')
add(22,M(r"v'=-v[v^2-(1+a)v+a],\quad0<a<1")+'의 (a) 평형, (b) 증가, (c) 감소 구간을 구하라.','For '+M(r"v'=-v[v^2-(1+a)v+a],\quad0<a<1")+', find (a) equilibria, (b) increasing ranges, and (c) decreasing ranges.','이차식을 인수분해한다.','Factor the quadratic.',[(M(r"v'=-v(v-a)(v-1)")+'이므로 세 경계값에서 부호가 바뀐다.',M(r"v'=-v(v-a)(v-1)")+' changes sign at the three boundary values.'),('작은 구간부터 부호는 '+M(r'+,-,+,-')+'.','From left to right the signs are '+M(r'+,-,+,-')+'.')],M(r'\text{(a) }v=0,a,1;\quad\text{(b) }v<0\text{ or }a<v<1;\quad\text{(c) }0<v<a\text{ or }v>1'),M(r'\text{(a) }v=0,a,1;\quad\text{(b) }v<0\text{ or }a<v<1;\quad\text{(c) }0<v<a\text{ or }v>1'),'각 구간의 시험값을 세 인자에 넣어 부호를 확인했다.','Test values in the four intervals confirm the signs.','abc')
add(23,M(r"y'=e^t(y-1)^2")+'의 해일 수 없는 이유를 설명하라: (a) 증가하다가 극대 후 감소하는 곡선, (b) 높이 일에서 양의 기울기로 통과하는 증가곡선.','Explain why neither graph can solve '+M(r"y'=e^t(y-1)^2")+': (a) a curve that rises then falls after a maximum; (b) a rising curve crossing height one with positive slope.','우변의 부호와 영이 되는 높이를 검사한다.','Check the sign and the height where the right-hand side vanishes.',[('(a) 우변은 항상 음이 아니므로 감소하는 부분은 불가능하다.','(a) The right-hand side is nonnegative, so a decreasing segment is impossible.'),('(b) '+M(r"y=1\Rightarrow y'=0")+'이므로 그 높이에서 반드시 수평 접선이어야 한다.','(b) '+M(r"y=1\Rightarrow y'=0")+' requires a horizontal tangent at that height.')],'(a) 음의 기울기, (b) 평형 높이에서 영이 아닌 기울기가 모순이다.','(a) Negative slope and (b) nonzero slope at the equilibrium height are contradictions.','우변이 매끄러워 유일성이 성립하므로 비상수 해가 평형해를 가로지를 수도 없다.','Smoothness gives uniqueness, so a nonconstant solution cannot cross the equilibrium solution.','ab')
add(24,'원점의 수직선에서 양의 기울기를 가지며 그 오른쪽에서 양의 극대를 지난 뒤 감소하는 곡선에 맞는 식을 고르라: '+M(r"\text{A: }y'=1+xy;\quad\text{B: }y'=-2xy;\quad\text{C: }y'=1-2xy")+'.','A curve has positive slope on the vertical axis, reaches a positive maximum to its right, then decreases. Choose '+M(r"\text{A: }y'=1+xy;\quad\text{B: }y'=-2xy;\quad\text{C: }y'=1-2xy")+'.','수직축에서의 기울기와 제일사분면에서 감소 가능한지 검사한다.','Check the slope on the vertical axis and the possibility of decrease in the first quadrant.',[('B는 수직축에서 기울기 영이므로 제외된다. A는 제일사분면에서 항상 증가하므로 제외된다.','B forces zero slope on the vertical axis. A forces positive slope throughout the first quadrant.'),('C는 축에서 기울기 일이면서 '+M(r'xy>1/2')+'이면 감소한다.','C gives slope one on the axis and decreases when '+M(r'xy>1/2')+'.')],'C.','C.','양의 극대에서는 마지막 식의 우변이 영이 될 수 있다.','Only the last equation can have zero slope at the positive maximum.')
add(25,'식과 개형을 대응시켜라. '+M(r"\text{(a) }y'=1+x^2+y^2;\ \text{(b) }y'=xe^{-x^2-y^2};\ \text{(c) }y'=(1+e^{x^2+y^2})^{-1};\ \text{(d) }y'=\sin(xy)\cos(xy)")+'. I: 원점에서 최소인 골짜기; II: 수평 영함수; III: 양쪽으로 가팔라지는 증가곡선; IV: 양끝에서 완만해지는 증가곡선.','Match equations to shapes. '+M(r"\text{(a) }y'=1+x^2+y^2;\ \text{(b) }y'=xe^{-x^2-y^2};\ \text{(c) }y'=(1+e^{x^2+y^2})^{-1};\ \text{(d) }y'=\sin(xy)\cos(xy)")+'. I: a valley with minimum at the origin; II: the zero function; III: an increasing curve steepening at both ends; IV: an increasing curve flattening at both ends.','우변의 부호와 크기, 영함수 대입 결과를 비교한다.','Compare signs, magnitudes, and substitution of the zero function.',[('(a)는 기울기가 항상 일 이상이며 원점에서 멀어질수록 커진다. (b)는 입력의 부호를 따르므로 왼쪽에서 감소하고 오른쪽에서 증가한다.','(a) has slope at least one, growing away from the origin. (b) follows the sign of the input, decreasing on the left and increasing on the right.'),('(c)는 양의 기울기가 멀리서 영으로 작아진다. (d)는 영함수가 우변을 영으로 만든다.','(c) has positive slopes tending toward zero far away. (d) vanishes on the zero function.')],M(r'\text{(a) III, (b) I, (c) IV, (d) II}'),M(r'\text{(a) III, (b) I, (c) IV, (d) II}'),'원점의 기울기는 순서대로 일, 영, 이분의 일, 영이다.','The respective slopes at the origin are one, zero, one half, and zero.','abcd')
for n,var,limit,start,eq,sol,kdesc,edesc,sub in [
(26,'T','20','95',r"T'=-k(T-20),\ T(0)=95,\ k>0",r'T(t)=20+75e^{-kt}','실내 온도 이십 도에서 구십오 도 커피의 (a) 냉각 속도 변화, (b) 뉴턴 냉각식과 초기조건 및 모델의 타당성, (c) 해의 개형을 설명하라.','Coffee starts at ninety-five degrees in a room at twenty degrees. Discuss (a) how cooling speed changes, (b) Newton’s equation, initial condition and suitability, and (c) the solution graph.','abc'),
(27,'P','M','P_0',r"P'=k(M-P),\ k>0",r'P(t)=M-(M-P_0)e^{-kt},\quad P_0<M','학습 수행도의 (a) 가장 빠른 향상 시점과 이후 변화, (b) 최대 수행도까지의 차이에 비례하는 향상률 모델의 의미, (c) 가능한 해의 개형을 설명하라.','For learning performance, discuss (a) when improvement is fastest and how it changes, (b) a rate proportional to the remaining gap to maximum performance, and (c) a possible solution graph.','abc'),
(28,'L',r'L_\infty','L_0',r"L'=k(L_\infty-L),\ k>0",r'L(t)=L_\infty-(L_\infty-L_0)e^{-kt},\quad0<L_0<L_\infty','물고기의 길이 성장률이 점근 길이와 현재 길이 차이에 비례한다. (a) 모델을 쓰고 (b) 전형적인 초기값 해를 그려라.','A fish grows in length at a rate proportional to the gap from its asymptotic length. (a) Formulate the equation and (b) sketch a typical initial-value solution.','ab')]:
 st=M(var+'='+var+'(t)')
 steps=[('차이가 클수록 변화율의 크기가 크다. 모델은 '+M(eq)+'.','A larger gap gives a larger rate magnitude. The model is '+M(eq)+'.'),('변수분리 또는 직접 미분으로 '+M(sol)+'을 얻는다.','Separation or direct differentiation yields '+M(sol)+'.')]
 if n==26:steps.append(('처음 가장 빨리 식고 점점 냉각 속도가 작아진다. 일정 실내 온도와 비례 법칙을 가정한 정성적 모델이며 정확한 적합성은 측정이 필요하다.','Cooling is fastest initially and slows over time. This qualitative model assumes constant ambient temperature and proportional heat loss; quantitative adequacy requires measurements.'))
 else:steps.append(('처음 증가율이 가장 크고, 이후 증가율이 영으로 줄어든다. 해는 증가하며 위로 오목하지 않고 아래로 오목하다.','The initial growth rate is largest and then decreases toward zero. The solution increases and is concave downward.'))
 add(n,kdesc+' '+st,edesc+' '+st,'평형값과 현재값의 차이를 이용한다.','Use the gap between equilibrium and current value.',steps,M(eq)+'; '+M(sol),M(eq)+'; '+M(sol),'직접 미분으로 식을 확인했고, 시간 영에서 초기값과 무한 시간에서 평형값을 복원했다.','Direct differentiation verifies the equation; time zero and the long-time limit recover the initial and equilibrium values.',sub)
add(29,M(r"c'=kt^{-b}(c_s-c),\quad k,c_s>0,\ 0<b<1")+'에 대해 '+M(r'c(t)=c_s(1-e^{-\alpha t^{1-b}}),\quad\alpha=k/(1-b)')+'를 양의 시간에서 검증하고 용해 과정의 의미를 설명하라.','For '+M(r"c'=kt^{-b}(c_s-c),\quad k,c_s>0,\ 0<b<1")+', verify '+M(r'c(t)=c_s(1-e^{-\alpha t^{1-b}}),\quad\alpha=k/(1-b)')+' at positive times and interpret dissolution.','연쇄법칙을 적용한 뒤 포화 농도와의 차이를 계산한다.','Use the chain rule and compute the gap to saturation.',[(M(r"c'=c_s\alpha(1-b)t^{-b}e^{-\alpha t^{1-b}}=kc_st^{-b}e^{-\alpha t^{1-b}}")+'.',M(r"c'=c_s\alpha(1-b)t^{-b}e^{-\alpha t^{1-b}}=kc_st^{-b}e^{-\alpha t^{1-b}}")+'.'),(M(r'c_s-c=c_se^{-\alpha t^{1-b}}')+'이므로 우변이 도함수와 같다. 농도는 영에서 포화값으로 증가하고 용해 속도는 감소한다.',M(r'c_s-c=c_se^{-\alpha t^{1-b}}')+' makes the right-hand side equal the derivative. Concentration rises from zero toward saturation while dissolution slows.')],M(r'\lim_{t\downarrow0}c(t)=0,\quad\lim_{t\to\infty}c(t)=c_s,\quad c^{\prime}>0,\ c^{\prime\prime}<0\ (t>0)'),M(r'\lim_{t\downarrow0}c(t)=0,\quad\lim_{t\to\infty}c(t)=c_s,\quad c^{\prime}>0,\ c^{\prime\prime}<0\ (t>0)'),'방정식은 시간 영에서 특이하다. 양의 시간의 해를 연속적으로 영까지 연장할 수 있지만 시작 순간의 기울기는 무한히 커진다.','The equation is singular at time zero. The positive-time solution extends continuously to zero, but its initial slope diverges.')
# Numerically generated original figures; all curves use explicit functions or RK4.
AS=BASE/'exercise-content/assets';AS.mkdir(exist_ok=True)
def svg(n,panels):
 w=720;ph=290;H=ph*len(panels);out=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {H}" role="img"><rect width="100%" height="100%" fill="#fff"/>']
 for j,(title,xlim,ylim,curves) in enumerate(panels):
  top=j*ph;X=lambda x:60+(x-xlim[0])/(xlim[1]-xlim[0])*620;Y=lambda y:top+245-(y-ylim[0])/(ylim[1]-ylim[0])*195
  out.append(f'<text x="60" y="{top+24}" font-size="15" fill="#172b4d">{html.escape(title)}</text><rect x="60" y="{top+50}" width="620" height="195" fill="#f6f8fc" stroke="#ccd5df"/>')
  for axis,val in [('x',0),('y',0)]:
   if axis=='x' and ylim[0]<=val<=ylim[1]:out.append(f'<path d="M60 {Y(0)}H680" stroke="#8894a4"/>')
   if axis=='y' and xlim[0]<=val<=xlim[1]:out.append(f'<path d="M{X(0)} {top+50}V{top+245}" stroke="#8894a4"/>')
  for z,(label,coords) in enumerate(curves):
   col=['#1463c2','#c44933','#17926f','#8953b4','#bf8800'][z%5];segments=[];path=''
   for x,y in coords:
    if math.isfinite(y) and ylim[0]<=y<=ylim[1]:path+=('M' if not path else 'L')+f'{X(x):.2f},{Y(y):.2f}'
    elif path:segments.append(path);path=''
   if path:segments.append(path)
   for path in segments:out.append(f'<path d="{path}" fill="none" stroke="{col}" stroke-width="2"/>')
   out.append(f'<text x="{65+(z%3)*205}" y="{top+263+(z//3)*17}" font-size="12" fill="{col}">{html.escape(label)}</text>')
  out.append(f'<text x="62" y="{top+45}" font-size="11">y: {ylim[0]} .. {ylim[1]}</text><text x="510" y="{top+45}" font-size="11">x/t: {xlim[0]} .. {xlim[1]}</text>')
 out.append('</svg>');p=AS/f's9-1-{n}.svg';p.write_text(''.join(out))
 ex=next(e for e in items if e['number']==n);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('해설의 함수로 생성한 개형과 해곡선','Shapes and solution curves generated from the functions in the explanation'),'caption':bi('자체 계산 도해. 축 범위와 각 곡선의 식 또는 매개변수를 표시했다.','Original computed diagram with axis ranges and formulas or parameters.')}
def sampled(f,a,b,N=500):return [(a+(b-a)*i/N,f(a+(b-a)*i/N)) for i in range(N+1)]
svg(18,[('Solution family: y=(ln x+C)/x',(.1,5),(-4,5),[(f'C={c:.3f}',sampled(lambda x:(math.log(x)+c)/x,.1,5)) for c in [-1,0,1,2,2-math.log(2)]])])
svg(20,[('Positive solution family: y=1/sqrt(c-x^2)',(-2,2),(0,8),[(f'c={c}',sampled(lambda x:1/math.sqrt(c-x*x),-.995*math.sqrt(c),.995*math.sqrt(c))) for c in [.25,1,4]])])
svg(23,[('Schematic contradiction (a): a decreasing segment',(-1,4),(-.5,3),[('y=1+0.25(t-1)^3-0.1(t-1)^4',sampled(lambda t:1+.25*(t-1)**3-.1*(t-1)**4,-.4,4))]),('Schematic contradiction (b): crossing y=1 with positive slope',(-1,4),(-.5,3),[('y=1+tanh(t-1)',sampled(lambda t:1+math.tanh(t-1),-1,4)),('y=1',sampled(lambda t:1,-1,4))])])
def rk(f,a,b,y0,N=1200):
 h=(b-a)/N;x=a;y=y0;pts=[(x,y)]
 for i in range(N):
  k1=f(x,y);k2=f(x+h/2,y+h*k1/2);k3=f(x+h/2,y+h*k2/2);k4=f(x+h,y+h*k3)
  y+=h*(k1+2*k2+2*k3+k4)/6;x=a+(i+1)*h;pts.append((x,y))
 return pts
def both(f,b,y=0):return list(reversed(rk(f,0,-b,y)))+rk(f,0,b,y)[1:]
svg(24,[('C: y prime = 1-2xy, y(0)=2',(-1.5,4),(0,3),[('RK4 solution',list(reversed(rk(lambda x,y:1-2*x*y,0,-1.5,2)))+rk(lambda x,y:1-2*x*y,0,4,2)[1:])])])
svg(25,[('I: (b)',(-2,2),(-.1,.7),[('y prime = x exp(-x^2-y^2)',both(lambda x,y:x*math.exp(-x*x-y*y),2))]),('II: (d)',(-2,2),(-1,1),[('y=0',sampled(lambda x:0,-2,2))]),('III: (a)',(-1,1),(-3,3),[('y prime = 1+x^2+y^2',both(lambda x,y:1+x*x+y*y,1))]),('IV: (c)',(-3,3),(-1,1),[('y prime = 1/(1+exp(x^2+y^2))',both(lambda x,y:1/(1+math.exp(x*x+y*y)),3))])])
svg(26,[('Cooling example: k=1', (0,5),(0,100),[('T=20+75 exp(-t)',sampled(lambda t:20+75*math.exp(-t),0,5)),('ambient T=20',sampled(lambda t:20,0,5))])])
svg(27,[('Learning example: M=1, P(0)=0, k=1',(0,5),(0,1.1),[('P=1-exp(-t)',sampled(lambda t:1-math.exp(-t),0,5)),('maximum M=1',sampled(lambda t:1,0,5))])])
svg(28,[('Fish growth example: asymptotic length=10, L(0)=2, k=1',(0,5),(0,11),[('L=10-8 exp(-t)',sampled(lambda t:10-8*math.exp(-t),0,5)),('asymptotic length=10',sampled(lambda t:10,0,5))])])
assert len(items)==29 and [i['number'] for i in items]==list(range(1,30))
d=dict(section='9.1',source=dict(title='Calculus',edition='9',language='en',printedPages=[648,649,650],pdfPages=[685,686,687]),scope=dict(kind='exercise',numbers=list(range(1,30)),total=29,note=bi('일반 연습문제 전체 29문항과 모든 소문항.','All 29 ordinary exercises and every subpart.')),exercises=items)
p=BASE/'exercise-content/s9-1.json';p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
import sys
sys.path.insert(0,str(BASE));import build_exercises as b
b.validate_document(d,p);print('9.1: 29 validated cards; 8 SVGs')
