import json,math,html,sys
from pathlib import Path
BASE=Path(__file__).resolve().parents[1]; items=[]
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':e if e is not None else k}
def add(n,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=657 if n<=16 else 658 if n<=27 else 659
 items.append(dict(id=f'stewart9-exercise-9.2-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('방향장과 오일러 방법','Direction fields and Euler’s method'),statement=bi(sk,se),hint=bi('우변으로 기울기를 계산하고 초기점에서 해를 추적한다.','Compute slopes from the right-hand side and follow the solution from its initial point.'),steps={'ko':[x[0] for x in steps],'en':[x[1] for x in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
def rk(f,a,b,y0,N=1200):
 h=(b-a)/N;x=a;y=y0;pts=[(x,y)]
 for i in range(N):
  try:
   k1=f(x,y);k2=f(x+h/2,y+h*k1/2);k3=f(x+h/2,y+h*k2/2);k4=f(x+h,y+h*k3)
   y+=h*(k1+2*k2+2*k3+k4)/6;x=a+(i+1)*h
   if not math.isfinite(y) or abs(y)>1000:break
   pts.append((x,y))
  except (ValueError,OverflowError,ZeroDivisionError):break
 return pts
def both(f,lo,hi,y=0,x0=0):return list(reversed(rk(f,x0,lo,y)))+rk(f,x0,hi,y)[1:]
def sampled(f,a,b,N=500):return [(a+(b-a)*i/N,f(a+(b-a)*i/N)) for i in range(N+1)]
def euler(f,x,y,h,n):
 pts=[(x,y)]
 for i in range(n):y+=h*f(x,y);x=pts[0][0]+(i+1)*h;pts.append((x,y))
 return pts
def svg(n,title,f,xlim,ylim,curves):
 w=720;out=[f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 435" role="img"><rect width="100%" height="100%" fill="white"/><text x="50" y="25" font-size="16">{html.escape(title)}</text>'];X=lambda x:50+(x-xlim[0])/(xlim[1]-xlim[0])*620;Y=lambda y:365-(y-ylim[0])/(ylim[1]-ylim[0])*310
 out.append('<rect x="50" y="55" width="620" height="310" fill="#f6f8fc" stroke="#bbc5d0"/>')
 if f:
  for i in range(25):
   for j in range(17):
    x=xlim[0]+(xlim[1]-xlim[0])*i/24;y=ylim[0]+(ylim[1]-ylim[0])*j/16
    try:s=f(x,y)*(310/(ylim[1]-ylim[0]))/(620/(xlim[1]-xlim[0]));dx=7/math.sqrt(1+s*s);dy=s*dx
    except (ValueError,OverflowError,ZeroDivisionError):continue
    if abs(s)>1e8:continue
    out.append(f'<path d="M{X(x)-dx:.2f},{Y(y)+dy:.2f}L{X(x)+dx:.2f},{Y(y)-dy:.2f}" stroke="#a8b9cd" stroke-width="1"/>')
 if ylim[0]<=0<=ylim[1]:out.append(f'<path d="M50 {Y(0)}H670" stroke="#8894a4"/>')
 if xlim[0]<=0<=xlim[1]:out.append(f'<path d="M{X(0)} 55V365" stroke="#8894a4"/>')
 for z,(label,coords) in enumerate(curves):
  col=['#1463c2','#c44933','#17926f','#8953b4','#bf8800','#444'][z%6];path='';paths=[]
  for x,y in coords:
   if math.isfinite(y) and ylim[0]<=y<=ylim[1]:path+=('M' if not path else 'L')+f'{X(x):.2f},{Y(y):.2f}'
   elif path:paths.append(path);path=''
  if path:paths.append(path)
  for path in paths:out.append(f'<path d="{path}" fill="none" stroke="{col}" stroke-width="2"/>')
  out.append(f'<text x="{50+(z%3)*205}" y="{390+(z//3)*18}" font-size="12" fill="{col}">{html.escape(label)}</text>')
 out.append(f'<text x="50" y="48" font-size="11">y: {ylim[0]} .. {ylim[1]}</text><text x="500" y="48" font-size="11">x/t: {xlim[0]} .. {xlim[1]}</text></svg>')
 p=BASE/f'exercise-content/assets/s9-2-{n}.svg';p.write_text(''.join(out));ex=next(e for e in items if e['number']==n);ex['figure']={'src':f'../exercise-content/assets/{p.name}','alt':bi('계산한 방향장과 해곡선 또는 오일러 다각선','Computed slope field with solution curves or Euler polygons'),'caption':bi('자체 계산 그림. 수치 곡선에는 4차 Runge–Kutta 방법을 사용했다.','Original computed figure. Numerical solution curves use fourth-order Runge–Kutta integration.')}
add(1,M(r"y'=x\cos(\pi y)")+'의 (a) '+M(r'y(0)=0,0.5,1,1.6')+'인 해를 그리고 (b) 모든 평형해를 구하라.','For '+M(r"y'=x\cos(\pi y)")+', (a) plot the solutions with '+M(r'y(0)=0,0.5,1,1.6')+' and (b) find all equilibria.', [('영 입력에서는 기울기가 영이며, 오른쪽 반평면에서는 코사인의 부호를 따른다. 해들은 입력에 대해 대칭이다.','Slopes vanish at zero input; to the right they follow the cosine sign. The solutions are even functions of the input.'),('초기값 영과 일은 모두 높이 이분의 일로 접근한다. 초기값 이분의 일은 상수이고, 초기값 일점육은 높이 이점오로 접근한다.','The curves starting at zero and one approach height one half. The one-half solution is constant, and the curve starting at 1.6 approaches height 2.5.')],M(r'y\equiv n+1/2,\quad n\in\mathbb Z')+'; 초기값 곡선은 그림과 같다.',M(r'y\equiv n+1/2,\quad n\in\mathbb Z')+'; the initial-value curves are plotted.','우변의 코사인이 영인 높이에서는 모든 입력에 대해 기울기가 영이다.','At each cosine zero the slope vanishes for every input.','ab')
svg(1,'y prime = x cos(pi y)',lambda x,y:x*math.cos(math.pi*y),(-2,2),(0,2.6),[(f'y(0)={c}',both(lambda x,y:x*math.cos(math.pi*y),-2,2,c)) for c in [0,.5,1,1.6]])
add(2,M(r"y'=\tan(\pi y/2)")+'에 대해 (a) '+M(r'y(0)=1,0.2,2;\ y(1)=3')+'을 각각 검토하고 가능한 해를 그려라. (b) 평형해를 구하라.','For '+M(r"y'=\tan(\pi y/2)")+', (a) examine '+M(r'y(0)=1,0.2,2;\ y(1)=3')+' and plot any classical solutions. (b) Find equilibria.', [('홀수 높이에서는 탄젠트가 정의되지 않는다. 따라서 첫 번째와 네 번째 초기값 문제에는 고전적 미분가능 해가 없다.','The tangent is undefined at odd integer heights. Thus the first and fourth initial-value problems have no classical differentiable solution.'),(M(r'\sin(\pi y/2)=\sin(\pi/10)e^{\pi x/2}')+'로 두 번째 해를 얻으며 높이 일에 도달하기 전까지만 정의된다. 세 번째는 상수해이다.',M(r'\sin(\pi y/2)=\sin(\pi/10)e^{\pi x/2}')+' gives the second solution until it reaches height one. The third is constant.')],M(r'\text{(ii) }y=\frac2\pi\arcsin(\sin(\pi/10)e^{\pi x/2}),\quad x<\frac2\pi\ln\csc(\pi/10);\quad\text{(iii) }y=2;\quad\text{(b) }y=2n,\ n\in\mathbb Z'),M(r'\text{(ii) }y=\frac2\pi\arcsin(\sin(\pi/10)e^{\pi x/2}),\quad x<\frac2\pi\ln\csc(\pi/10);\quad\text{(iii) }y=2;\quad\text{(b) }y=2n,\ n\in\mathbb Z'),'방향장의 수직처럼 보이는 선분은 무한 기울기의 고전적 해를 허용하지 않는다.','Nearly vertical field segments do not permit an infinite derivative in a classical solution.','ab')
end=2/math.pi*math.log(1/math.sin(math.pi/10));svg(2,'tan(pi y/2): odd heights excluded',lambda x,y:math.tan(math.pi*y/2),(-2,2),(0,4),[('y(0)=0.2',sampled(lambda x:2/math.pi*math.asin(math.sin(math.pi/10)*math.exp(math.pi*x/2)),-2,end-1e-5)),('y=2',sampled(lambda x:2,-2,2))])
fields=[(3,r'2-y','III',lambda x,y:2-y,'수평 줄마다 같은 기울기이고 높이 이에서 영이다.','Each horizontal row has a constant slope, zero at height two.'),(4,r'x(2-y)','I',lambda x,y:x*(2-y),'수직축과 높이 이에서 모두 기울기가 영이며 수직축 양쪽에서 부호가 바뀐다.','Slopes vanish on the vertical axis and at height two, reversing across the vertical axis.'),(5,r'x+y-1','IV',lambda x,y:x+y-1,'기울기 영의 선은 우하향 대각선이다.','The zero-slope line is a descending diagonal.'),(6,r'\sin x\sin y','II',lambda x,y:math.sin(x)*math.sin(y),'양 축에서 기울기가 영이며 주기적으로 부호가 변한다.','Slopes vanish on both axes and change sign periodically.')]
for n,eq,label,f,k,e in fields:
 add(n,M("y'="+eq)+'를 원문의 방향장 I–IV와 대응시키고 설명하라.', 'Match '+M("y'="+eq)+' to source fields I–IV and explain.',[(k,e),('자체 계산 방향장에서 같은 영기울기 집합과 부호 패턴을 확인한다.','The computed field confirms the same zero-slope set and sign pattern.')],label+'.',label+'.','기울기의 위치 의존성을 원문 도해와 대조했다.','The slope dependence matches the source diagram.')
 svg(n,f'Field {label}: y prime = {eq}',f,(-3,3),(-3,4),[])
for n,eq,formula,f in [(7,r'x(2-y)',r'y=2+(c-2)e^{-x^2/2}',lambda x,y:x*(2-y)),(8,r'2-y',r'y=2+(c-2)e^{-x}',lambda x,y:2-y)]:
 add(n,'방향장 '+('I' if n==7 else 'III')+'에서 '+M(r'y(0)=1,2.5,3.5')+'인 해를 그려라. 해당 식은 '+M("y'="+eq)+'.','Using field '+('I' if n==7 else 'III')+', plot solutions with '+M(r'y(0)=1,2.5,3.5')+'. Its equation is '+M("y'="+eq)+'.', [('높이 이가 평형이므로 그 차이를 새로운 종속변수로 보면 변수분리가 된다.','Subtract the equilibrium height two and separate variables.'),('초기값을 상수에 넣으면 '+M(formula)+'.','Inserting the initial value gives '+M(formula)+'.')],M(formula+r',\quad c=1,2.5,3.5'),M(formula+r',\quad c=1,2.5,3.5'),'직접 미분과 초기점 대입으로 세 곡선을 검증했다.','Differentiation and substitution at the initial point verify all three curves.','abc')
 svg(n,'Initial values 1, 2.5, 3.5',f,(-2,3),(0,5),[(f'c={c}',sampled(lambda x:2+(c-2)*math.exp(-x*x/2 if n==7 else -x),-2,3)) for c in [1,2.5,3.5]])
for n,eq,formula,f,fn in [(9,r'y/2',r'y=Ce^{x/2},\ C=-1,0,1',lambda x,y:y/2,lambda x,c:c*math.exp(x/2)),(10,r'x-y+1',r'y=x+Ce^{-x},\ C=-1,0,1',lambda x,y:x-y+1,lambda x,c:x+c*math.exp(-x))]:
 add(n,M("y'="+eq)+'의 방향장과 세 해곡선을 그려라.','Draw a slope field and three solution curves for '+M("y'="+eq)+'.',[('우변이 영인 곳을 찾아 수평 선분을 배치하고 나머지 점에서는 우변의 기울기를 사용한다.','Locate zero slopes and use the right-hand side for the other field segments.'),('직접 풀어 얻는 해족에서 서로 다른 세 상수를 고른다.','Choose three constants from the solved family.')],M(formula),M(formula),'그림의 모든 해는 원래 미분방정식을 만족한다.','Every plotted curve satisfies the original differential equation.')
 svg(n,'Three solution curves',f,(-2,3),(-4,5),[(f'C={c}',sampled(lambda x:fn(x,c),-2,3)) for c in [-1,0,1]])
plotcases=[(11,r'y-2x',r'y(1)=0',lambda x,y:y-2*x,1,0,r'y=2x+2-4e^{x-1}',(-1,2),(-5,5)),(12,r'xy-x^2',r'y(0)=1',lambda x,y:x*y-x*x,0,1,r'y=e^{x^2/2}\left(1-\int_0^x t^2e^{-t^2/2}\,dt\right)',(-2,2),(-4,5)),(13,r'y+xy',r'y(0)=1',lambda x,y:y+x*y,0,1,r'y=e^{x+x^2/2}',(-2,1.4),(0,7)),(14,r'x+y^2',r'y(0)=0',lambda x,y:x+y*y,0,0,r'y(1)\approx0.557162',(-2,1.5),(-1,4)),(15,r'x^2y-\tfrac12y^2',r'y(0)=1',lambda x,y:x*x*y-.5*y*y,0,1,r'y=\frac{e^{x^3/3}}{1+\frac12\int_0^x e^{t^3/3}\,dt}',(-1,2),(0,6)),(16,r'\cos(x+y)',r'y(0)=1',lambda x,y:math.cos(x+y),0,1,r'y=2\arctan(x+\tan(1/2))-x',(-2,3),(-3,3))]
for n,eq,init,f,x0,y0,ans,xlim,ylim in plotcases:
 steps=[('지정된 초기점에서 우변을 계산하여 첫 접선 방향을 정한다. 방향장의 선분을 따라 해곡선을 연속적으로 잇는다.','Compute the right-hand side at the initial point for its tangent, then follow the slope field continuously.'),('그림의 수치 곡선은 4차 Runge–Kutta로 계산했다. '+M(ans)+'.','The numerical curve uses fourth-order Runge–Kutta. '+M(ans)+'.')]
 if n==11:steps.insert(1,('선형방정식의 특수해는 '+M(r'2x+2')+'이며 초기값으로 지수항 계수를 정한다.','A particular solution is '+M(r'2x+2')+'; the initial value fixes the exponential coefficient.'))
 if n==12:steps.insert(1,('적분인자는 '+M(r'e^{-x^2/2}')+'이다. 곱의 도함수를 적분한다.','The integrating factor is '+M(r'e^{-x^2/2}')+'. Integrate the resulting product derivative.'))
 if n==13:steps.insert(1,(M(r'\ln y=x+x^2/2+C')+'와 초기값을 사용한다.',M(r'\ln y=x+x^2/2+C')+' and the initial value determine the solution.'))
 if n==14:steps.insert(1,('원점의 접선은 수평이고 바로 오른쪽에서 기울기가 양수가 된다. 해는 유한 시간에 발산하므로 그림의 표시 구간 밖으로 임의 연장하지 않는다.','The initial tangent is horizontal and slopes become positive just to the right. The solution eventually blows up in finite time and must not be extended arbitrarily.'))
 if n==15:steps.insert(1,('역수 치환 '+M(r'v=1/y')+'으로 '+M(r"v'+x^2v=1/2")+'를 얻는다.','The reciprocal substitution '+M(r'v=1/y')+' gives '+M(r"v'+x^2v=1/2")+'.'))
 if n==16:steps.insert(1,('합을 치환하면 '+M(r'u=x+y,\ u^{\prime}=1+\cos u')+'이고 반각치환으로 적분된다.','Set '+M(r'u=x+y,\ u^{\prime}=1+\cos u')+' and integrate using a half-angle substitution.'))
 add(n,M("y'="+eq+r',\ '+init)+'의 방향장과 초기값 해를 그려라.'+(' 손으로 따라간 개형과 계산 곡선을 비교하라.' if n>=15 else ''),'Plot the direction field and initial-value solution of '+M("y'="+eq+r',\ '+init)+'.'+(' Compare a slope-following sketch with the computed curve.' if n>=15 else ''),steps,M(ans)+'; 그림 참조.',M(ans)+'; see the plot.','해의 초기값과 도함수의 우변 일치를 검사했다. 수치 곡선은 격자 간격을 반으로 줄여 재계산했다.','The initial value and differential equation were checked. Numerical curves were recomputed with half the step size.')
 svg(n,f'Exercise {n}: initial-value curve',f,xlim,ylim,[('RK4 solution',both(f,*xlim,y0,x0))])
add(17,M(r"y'=y^3-4y,\ y(0)=c")+'의 방향장과 여러 해를 그리고 양의 무한 시간에서 유한 극한이 존재하는 초기값과 그 극한을 구하라.','Plot the field and several solutions of '+M(r"y'=y^3-4y,\ y(0)=c")+' and determine which initial values have finite forward-time limits.',[(M(r"y'=y(y-2)(y+2)")+'의 부호를 나눈다. 가운데 두 구간에서는 해가 영을 향하고 바깥에서는 멀어진다.',M(r"y'=y(y-2)(y+2)")+' points toward zero on the two inner intervals and away on the outer intervals.'),('바깥 해는 단순한 무한 시간 발산이 아니라 유한 시간 폭주하므로 무한 시간 극한의 정의역 자체가 없다.','Outer solutions blow up in finite time, so they are not even defined up to infinite forward time.')],M(r'|c|<2:\ \lim y=0;\quad c=\pm2:\ \lim y=\pm2;\quad |c|>2:\ \text{no finite limit}'),M(r'|c|<2:\ \lim y=0;\quad c=\pm2:\ \lim y=\pm2;\quad |c|>2:\ \text{no finite limit}'),'세 상수해를 대입 검증하고 각 구간의 우변 부호를 확인했다.','Substitution verifies the three equilibria, and sign checks verify the phase line.')
svg(17,'Phase line and representative solutions',lambda x,y:y**3-4*y,(0,1.2),(-3,3),[(f'c={c}',rk(lambda x,y:y**3-4*y,0,1.2,c)) for c in [-2.2,-2,-1,1,2,2.2]])
add(18,'자율방정식 '+M(r"y'=f(y)")+'의 그래프는 영점 '+M(r'-2,-1,1,2')+'를 갖고 왼쪽부터 부호가 '+M(r'+,-,+,-,+')+'이다. 방향장을 그리고 초기값에 따른 장기 거동을 설명하라.','For the autonomous equation '+M(r"y'=f(y)")+', the graph has zeros '+M(r'-2,-1,1,2')+' and signs '+M(r'+,-,+,-,+')+' from left to right. Sketch the field and classify long-time behavior.', [('음의 이와 양의 일은 양쪽에서 화살표가 모이는 안정 평형이고, 음의 일과 양의 이는 불안정 평형이다.','Minus two and plus one are attracting equilibria; minus one and plus two are repelling equilibria.'),('각 평형 사이에서는 우변의 부호를 따라 움직이며 평형을 넘지 않는다. 양의 이보다 큰 해는 증가하며 유한 평형 극한이 없다.','Between equilibria solutions follow the sign and cannot cross an equilibrium. Above plus two they increase without a finite equilibrium limit.')],M(r'c<-1:\ \lim y=-2;\quad c=-1:\ y=-1;\quad -1<c<2:\ \lim y=1;\quad c=2:\ y=2;\quad c>2:\ \text{no finite limit}'),M(r'c<-1:\ \lim y=-2;\quad c=-1:\ y=-1;\quad -1<c<2:\ \lim y=1;\quad c=2:\ y=2;\quad c>2:\ \text{no finite limit}'),'도해는 같은 영점과 부호를 갖는 자체 예시 함수로 생성했으며 원문 그래프만으로 바깥 해의 폭주 시간은 결정하지 않는다.','The illustration uses an original function with the same zeros and signs; the source graph alone does not determine outer blow-up time.')
svg(18,'Representative f(y)=(y^2-4)(y^2-1)/4',lambda x,y:(y*y-4)*(y*y-1)/4,(0,4),(-3,3),[(f'c={c}',rk(lambda x,y:(y*y-4)*(y*y-1)/4,0,4,c)) for c in [-2.7,-1.5,-.5,1.5,2,2.3]])
vals=[euler(lambda x,y:y,0,1,h,round(.4/h)) for h in [.4,.2,.1]];errors=[math.exp(.4)-p[-1][1] for p in vals]
add(19,M(r"y'=y,\ y(0)=1")+'에서 (a) '+M(r'h=0.4,0.2,0.1')+'로 '+M(r'y(0.4)')+'를 근사하라. (b) 지수함수와 오일러 다각선을 그려 과대·과소 여부를 설명하라. (c) 오차와 반분 효과를 구하라.','For '+M(r"y'=y,\ y(0)=1")+', (a) approximate '+M(r'y(0.4)')+' with '+M(r'h=0.4,0.2,0.1')+'. (b) Plot the exponential and Euler polygons and classify bias. (c) Compute errors and the effect of halving the step.',[(M(r'y_{n+1}=(1+h)y_n,\ y_n=(1+h)^n')+'이므로 마지막 값을 계산한다.',M(r'y_{n+1}=(1+h)y_n,\ y_n=(1+h)^n')+' gives each endpoint.'),('정확해는 위로 볼록하여 접선 다각선이 아래에 놓인다. '+M(r'e^{0.4}\approx1.491824698')+'.','The exact solution is convex, placing tangent polygons below it. '+M(r'e^{0.4}\approx1.491824698')+'.')],M(r'y_E=1.4,1.44,1.4641;\quad E=0.091824698,0.051824698,0.027724698')+'; 모두 과소이며 오차는 점차 약 절반이 된다.',M(r'y_E=1.4,1.44,1.4641;\quad E=0.091824698,0.051824698,0.027724698')+'; all underestimate, with errors approaching a factor-of-two reduction.','점화식을 반복한 값과 거듭제곱 공식을 독립 대조했다.','Repeated updates were checked against the power formula.','abc')
svg(19,'Euler polygons vs exp(x)',None,(0,.4),(1,1.5),[('exact exp(x)',sampled(math.exp,0,.4))]+[(f'h={h}',p) for h,p in zip([.4,.2,.1],vals)])
add(20,'원문 방향장은 각 수평 줄의 기울기가 양수이며 높이가 커질수록 완만해진다. 원점을 지나는 해의 오일러 다각선을 '+M(r'h=1,0.5')+'로 그리고 과대·과소 여부를 설명하라.','The source field has positive slopes constant along horizontal rows, becoming shallower at greater heights. Sketch Euler polygons from the origin with '+M(r'h=1,0.5')+' and classify their bias.', [('초기 선분의 기울기를 읽어 첫 단계를 그리고 새 끝점에서의 선분 기울기로 다음 단계를 연결한다. 원문 그림에 식이 없으므로 수치는 그래프에서 읽는 근사값이다.','Read the initial slope, take one step, then use the slope at the new endpoint. Since no formula is supplied, coordinates are graphical approximations.'),('높이가 증가할수록 기울기가 작아져 실제 해는 아래로 오목하다. 접선으로 진행하는 오일러 다각선은 해보다 높다.','The slope decreases as the solution rises, so the curve is concave down. Forward tangent steps lie above the solution.')],'두 간격 모두 과대근사. 간격을 반으로 줄이면 다각선이 해에 더 가까워진다.','Both step sizes overestimate; the half-step polygon lies closer to the solution.','자체 그림은 같은 방향장 특성을 갖는 대표 모델을 사용한 개형이며 원문에 없는 정확한 식을 주장하지 않는다.','The original figure uses a representative model with the same field properties, without claiming an unspecified exact source equation.')
svg(20,'Schematic field: y prime = 1/(1+y); graphical estimates',lambda x,y:1/(1+y),(0,2),(0,2),[('representative exact curve',sampled(lambda x:math.sqrt(1+2*x)-1,0,2)),('Euler h=1',euler(lambda x,y:1/(1+y),0,0,1,2)),('Euler h=0.5',euler(lambda x,y:1/(1+y),0,0,.5,4))])
for n,eq,f,x0,y0,h,N,target in [(21,r'y-2x',lambda x,y:y-2*x,1,0,.5,4,'y_1,y_2,y_3,y_4'),(22,r'x^2y-\tfrac12y^2',lambda x,y:x*x*y-.5*y*y,0,1,.2,5,'y(1)'),(23,r'y+xy',lambda x,y:y+x*y,0,1,.1,5,'y(0.5)')]:
 pts=euler(f,x0,y0,h,N);table=r'\begin{array}{c|r}x_n&y_n\\'+r'\\'.join(f'{x:.2f}&{y:.9f}' for x,y in pts)+r'\end{array}'
 ans=','.join(f'{p[1]:.9f}' for p in pts[1:]) if n==21 else rf'{target}\approx{pts[-1][1]:.9f}'
 add(n,M("y'="+eq+rf',\ y({x0})={y0},\ h={h}')+'에서 오일러 방법으로 '+M(target)+'을 구하라.','Use Euler’s method for '+M("y'="+eq+rf',\ y({x0})={y0},\ h={h}')+' to estimate '+M(target)+'.',[(M(r'x_{n+1}=x_n+h,\quad y_{n+1}=y_n+hf(x_n,y_n)')+'을 반복한다.',M(r'x_{n+1}=x_n+h,\quad y_{n+1}=y_n+hf(x_n,y_n)')+' is iterated.'),(M(table),M(table))],M(ans),M(ans),'중간값을 반올림하지 않고 마지막 표시만 반올림했다.','Intermediate values retain full precision; only displayed results are rounded.')
pts24=[euler(lambda x,y:math.cos(x+y),0,0,h,round(.6/h)) for h in [.2,.1]]
add(24,M(r"y'=\cos(x+y),\ y(0)=0")+'에서 '+M(r'y(0.6)')+'을 (a) '+M(r'h=0.2')+', (b) '+M(r'h=0.1')+'로 근사하라.','Estimate '+M(r'y(0.6)')+' for '+M(r"y'=\cos(x+y),\ y(0)=0")+' using (a) '+M(r'h=0.2')+' and (b) '+M(r'h=0.1')+'.',[(M(r'y_{n+1}=y_n+h\cos(x_n+y_n)')+'을 각 간격으로 반복한다.',M(r'y_{n+1}=y_n+h\cos(x_n+y_n)')+' is iterated for each step size.'),('각각 세 번과 여섯 번 갱신한다.','Use three and six updates, respectively.')],M(rf'\text{{(a) }}{pts24[0][-1][1]:.9f};\quad\text{{(b) }}{pts24[1][-1][1]:.9f}'),M(rf'\text{{(a) }}{pts24[0][-1][1]:.9f};\quad\text{{(b) }}{pts24[1][-1][1]:.9f}'),'정확해 '+M(r'y=2\arctan x-x')+'와 비교하면 간격 축소로 오차가 줄어든다.','Comparison with the exact solution '+M(r'y=2\arctan x-x')+' confirms improved accuracy for the smaller step.','ab')
hs=[1,.1,.01,.001];vs=[euler(lambda x,y:3*x*x*(2-y),0,3,h,round(1/h))[-1][1] for h in hs];exact=2+math.exp(-1)
table=r'\begin{array}{c|r|r}h&y_E&y_{exact}-y_E\\'+r'\\'.join(f'{h}&{v:.9f}&{exact-v:.9f}' for h,v in zip(hs,vs))+r'\end{array}'
add(25,M(r"y'+3x^2y=6x^2,\ y(0)=3")+'에서 (a) '+M(r'h=1,0.1,0.01,0.001')+'로 '+M(r'y(1)')+'을 계산하라. (b) '+M(r'y=2+e^{-x^3}')+'을 검증하고 (c) 오차의 변화를 비교하라.','For '+M(r"y'+3x^2y=6x^2,\ y(0)=3")+', (a) compute '+M(r'y(1)')+' with '+M(r'h=1,0.1,0.01,0.001')+'. (b) Verify '+M(r'y=2+e^{-x^3}')+' and (c) compare errors.',[(M(r'y_{n+1}=y_n+3hx_n^2(2-y_n)')+'으로 반복한다.',M(r'y_{n+1}=y_n+3hx_n^2(2-y_n)')+' is iterated.'),(M(r'y^{\prime}=-3x^2e^{-x^3},\quad y^{\prime}+3x^2y=6x^2,\quad y(0)=3')+'.',M(r'y^{\prime}=-3x^2e^{-x^3},\quad y^{\prime}+3x^2y=6x^2,\quad y(0)=3')+'.')],M(table)+'; 작은 간격에서는 열 배 축소할 때 오차 크기도 약 열 배 작아진다.',M(table)+'; for small steps, dividing the step by ten reduces the error magnitude by about ten.','음의 부호는 과대근사임을 뜻한다. 첫 거친 간격은 점근적 오차비에서 제외해야 한다.','Negative signed errors indicate overestimation. The coarsest step need not follow the asymptotic error ratio.','abc')
f26=lambda x,y:x**3-y**3;v26=euler(f26,0,1,.01,200)[-1][1];ref=rk(f26,0,2,1,4000)[-1][1]
add(26,M(r"y'=x^3-y^3,\ y(0)=1")+'에서 (a) '+M(r'h=0.01')+'로 '+M(r'y(2)')+'를 근사하고 (b) 컴퓨터 해곡선과 비교하라.','For '+M(r"y'=x^3-y^3,\ y(0)=1")+', (a) estimate '+M(r'y(2)')+' using '+M(r'h=0.01')+' and (b) compare with a computed solution curve.',[(M(r'y_{n+1}=y_n+0.01(x_n^3-y_n^3)')+'을 이백 번 반복한다.',M(r'y_{n+1}=y_n+0.01(x_n^3-y_n^3)')+' is iterated two hundred times.'),('참조 곡선은 더 작은 간격의 4차 방법으로 계산한다.','Compute a reference curve using a finer fourth-order method.')],M(rf'y_E(2)\approx{v26:.9f};\quad y_{{RK4}}(2)\approx{ref:.9f};\quad E\approx{ref-v26:.9f}'),M(rf'y_E(2)\approx{v26:.9f};\quad y_{{RK4}}(2)\approx{ref:.9f};\quad E\approx{ref-v26:.9f}'),'참조 계산의 간격을 반으로 줄여 표시된 자릿수의 안정성을 확인했다.','Halving the reference step confirms stability of the displayed digits.','ab')
svg(26,'Euler h=0.01 and fine RK4',f26,(0,2),(0,2),[('RK4 reference',rk(f26,0,2,1,4000)),('Euler h=0.01',euler(f26,0,1,.01,200))])
v27=euler(lambda t,q:12-4*q,0,0,.1,5)[-1][1]
add(27,'직렬 저항–축전기 회로에서 '+M(r'R=5,\ C=0.05,\ E=60,\quad RQ^{\prime}+Q/C=E')+'. (a) 방향장, (b) 극한 전하, (c) 평형해, (d) 영 초기전하의 해곡선, (e) '+M(r'h=0.1')+'로 반 초 뒤 전하를 구하라.','For a resistor-capacitor circuit, '+M(r'R=5,\ C=0.05,\ E=60,\quad RQ^{\prime}+Q/C=E')+'. Find (a) the field, (b) limiting charge, (c) equilibrium, (d) the solution from zero charge, and (e) its half-second Euler estimate with '+M(r'h=0.1')+'.',[(M(r'Q^{\prime}=12-4Q,\quad Q(t)=3(1-e^{-4t})')+'이므로 높이 삼 아래에서는 증가하고 위에서는 감소한다.',M(r'Q^{\prime}=12-4Q,\quad Q(t)=3(1-e^{-4t})')+' increases below height three and decreases above it.'),(M(r'Q_{n+1}=0.6Q_n+1.2,\quad Q_0=0')+'을 다섯 번 갱신한다.',M(r'Q_{n+1}=0.6Q_n+1.2,\quad Q_0=0')+' is updated five times.')],M(rf'Q_{{eq}}=\lim_{{t\to\infty}}Q(t)=3\ {{\rm C}};\quad Q_E(0.5)={v27:.5f}\ {{\rm C}}'),M(rf'Q_{{eq}}=\lim_{{t\to\infty}}Q(t)=3\ {{\rm C}};\quad Q_E(0.5)={v27:.5f}\ {{\rm C}}'),'정확한 반 초 값은 '+M(r'3(1-e^{-2})\approx2.593994')+'으로 오일러 값보다 작다.','The exact half-second charge '+M(r'3(1-e^{-2})\approx2.593994')+' is smaller than the Euler estimate.','abcde')
svg(27,'RC charging: Q prime = 12-4Q',lambda t,q:12-4*q,(0,1),(0,4),[('Q=3(1-exp(-4t))',sampled(lambda t:3*(1-math.exp(-4*t)),0,1)),('equilibrium Q=3',sampled(lambda t:3,0,1)),('Euler h=0.1',euler(lambda t,q:12-4*q,0,0,.1,10))])
v28=euler(lambda t,T:-.02*(T-20),0,95,2,5)[-1][1]
add(28,'초기 구십오 도의 커피를 이십 도 방에 둔다. 칠십 도에서 분당 일 도씩 식는다. (a) 냉각식을 정하고 (b) 방향장과 초기값 해 및 극한을 구하며 (c) '+M(r'h=2')+'로 십 분 뒤 온도를 근사하라.','Coffee begins at ninety-five degrees in a twenty-degree room and cools at one degree per minute when at seventy degrees. (a) Determine its equation; (b) plot the field and solution and give its limit; (c) estimate its ten-minute temperature with '+M(r'h=2')+'.',[(M(r'-1=-k(70-20)\Rightarrow k=0.02')+'.',M(r'-1=-k(70-20)\Rightarrow k=0.02')+'.'),(M(r'T^{\prime}=-0.02(T-20),\quad T(t)=20+75e^{-0.02t}')+'이다. 오일러 갱신은 '+M(r'T_{n+1}=0.96T_n+0.8')+'.',M(r'T^{\prime}=-0.02(T-20),\quad T(t)=20+75e^{-0.02t}')+'. Euler updates use '+M(r'T_{n+1}=0.96T_n+0.8')+'.')],M(rf'\lim_{{t\to\infty}}T(t)=20^\circ{{\rm C}};\quad T_E(10)={v28:.8f}^\circ{{\rm C}}'),M(rf'\lim_{{t\to\infty}}T(t)=20^\circ{{\rm C}};\quad T_E(10)={v28:.8f}^\circ{{\rm C}}'),'폐형식 오일러 값 '+M(r'20+75(0.96)^5')+'과 반복 계산이 일치한다.','The closed-form Euler value '+M(r'20+75(0.96)^5')+' agrees with iteration.','abc')
svg(28,'Coffee cooling; t in minutes',lambda t,T:-.02*(T-20),(0,100),(0,100),[('T=20+75 exp(-0.02t)',sampled(lambda t:20+75*math.exp(-.02*t),0,100)),('ambient T=20',sampled(lambda t:20,0,100)),('Euler first 10 min',euler(lambda t,T:-.02*(T-20),0,95,2,5))])
assert len(items)==28
raw=dict(section='9.2',source=dict(title='Calculus',edition='9',language='en',printedPages=[657,658,659],pdfPages=[694,695,696]),scope=dict(kind='exercise',numbers=list(range(1,29)),total=28,note=bi('전체 28문항 및 모든 소문항.','All 28 exercises and every subpart.')),exercises=items)
p=BASE/'exercise-content/s9-2.json';p.write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n');sys.path.insert(0,str(BASE));import build_exercises as b;b.validate_document(raw,p)
print('9.2: 28 cards; 23 SVGs; Euler answers',vs,v26,ref,v27,v28)
