import json,math,html,sys,ast
from pathlib import Path
BASE=Path(__file__).resolve().parents[1];items=[]
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':e if e is not None else k}
def add(n,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=664 if n<=25 else 665 if n<=44 else 666 if n<=54 else 667
 items.append(dict(id=f'stewart9-exercise-9.3-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('변수분리와 응용','Separation of variables and applications'),statement=bi(sk,se),hint=bi('변수를 분리해 적분하고, 나눗셈에서 빠지는 해와 정의역을 검사한다.','Separate and integrate; check domains and solutions lost in division.'),steps={'ko':[x[0] for x in steps],'en':[x[1] for x in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
rows=[
(1,r"y'=3x^2y^2",r'\int y^{-2}\,dy=\int3x^2\,dx',r'-1/y=x^3+C',r'y=1/(C-x^3)\quad\text{or}\quad y=0','분모가 영이 아닌 각 열린 구간에서 정의된다.','Use open intervals where the denominator is nonzero.'),
(2,r"y'=x/y^4",r'\int y^4\,dy=\int x\,dx',r'y^5/5=x^2/2+C',r'y^5=\tfrac52x^2+C,\quad y\ne0','영함수는 원래 식이 정의되지 않아 해가 아니다.','The zero function is excluded by the original equation.'),
(3,r"y'=x\sqrt y",r'\int y^{-1/2}\,dy=\int x\,dx',r'2\sqrt y=x^2/2+C',r'y=(x^2/4+C)^2,\quad x^2/4+C\ge0;\qquad y=0','양의 가지는 괄호가 음이 아니어야 한다. 영점에서 영해와 미분가능하게 붙인 대기시간 해도 허용된다.','The bracket must be nonnegative. Differentiable patching to the zero solution at zeros also permits waiting-time solutions.'),
(4,r"xy'=y+3",r'\int\frac{dy}{y+3}=\int\frac{dx}{x}',r'\ln|y+3|=\ln|x|+C',r'y=Cx-3','원래 나눠지지 않은 식에 대입하면 입력 영에서도 성립한다.','Substitution in the undivided equation also verifies the solution at zero input.'),
(5,r"xyy'=x^2+1",r'\int y\,dy=\int(x+1/x)\,dx',r'y^2/2=x^2/2+\ln|x|+C',r'y^2=x^2+2\ln|x|+C,\quad x\ne0,\ y\ne0','양변이 양의 제곱을 주는 열린 구간에서 한 부호 가지를 고른다.','Choose one sign branch on an interval where the squared value is positive.'),
(6,r"y'+xe^y=0",r'\int e^{-y}\,dy=-\int x\,dx',r'e^{-y}=x^2/2+C',r'y=-\ln(x^2/2+C),\quad x^2/2+C>0','로그 안의 양수 조건은 지수함수의 양수 조건과 같다.','The positive logarithm argument matches positivity of the exponential.'),
(7,r"(e^y-1)y'=2+\cos x",r'\int(e^y-1)\,dy=\int(2+\cos x)\,dx',r'e^y-y=2x+\sin x+C',r'e^y-y=2x+\sin x+C','종속변수 영에서는 좌변 기울기 계수가 영이지만 우변은 양수이므로 고전적 해가 그 높이를 지나지 못한다.','At zero height the derivative coefficient vanishes while the right side is positive, so a classical solution cannot pass through it.'),
(8,r"y'=2x(y^2+1)",r'\int\frac{dy}{1+y^2}=\int2x\,dx',r'\arctan y=x^2+C',r'y=\tan(x^2+C)','탄젠트의 극점을 포함하지 않는 각 열린 구간에서 사용한다.','Use an open interval excluding tangent poles.'),
(9,r"p'=t^2p-p+t^2-1",r'\int\frac{dp}{p+1}=\int(t^2-1)\,dt',r'\ln|p+1|=t^3/3-t+C',r'p=Ce^{t^3/3-t}-1','상수계수 영은 나누면서 빠졌던 평형해를 포함한다.','A zero coefficient includes the equilibrium lost when dividing.'),
(10,r"z'+e^{t+z}=0",r'\int e^{-z}\,dz=-\int e^t\,dt',r'e^{-z}=e^t+C',r'z=-\ln(e^t+C),\quad e^t+C>0','원래 식에 직접 미분 대입해 부호를 확인한다.','Direct differentiation confirms the sign in the original equation.'),
(11,r"\theta'=\frac{t\sec\theta}{\theta e^{t^2}}",r'\int\theta\cos\theta\,d\theta=\int te^{-t^2}\,dt',r'\theta\sin\theta+\cos\theta=-\tfrac12e^{-t^2}+C',r'\theta\sin\theta+\cos\theta+\tfrac12e^{-t^2}=C','종속변수와 그 코사인이 영이 아닌 곳에서만 원래 식이 정의된다.','The original equation requires both the dependent variable and its cosine to be nonzero.'),
(12,r"\frac{dH}{dR}=\frac{RH^2\sqrt{1+R^2}}{\ln H}",r'\int\frac{\ln H}{H^2}\,dH=\int R\sqrt{1+R^2}\,dR',r'-\frac{\ln H+1}{H}=\frac13(1+R^2)^{3/2}+C',r'\frac{\ln H+1}{H}+\frac13(1+R^2)^{3/2}=C,\quad H>0,\ H\ne1','좌변을 미분하면 원래 식이 복원된다.','Implicit differentiation recovers the original equation.'),
(13,r"y'=xe^y,\ y(0)=0",r'\int e^{-y}\,dy=\int x\,dx',r'e^{-y}=1-x^2/2',r'y=-\ln(1-x^2/2),\quad |x|<\sqrt2','초기값이 일차 상수를 정하고 로그의 양수 조건이 최대 구간을 정한다.','The initial value fixes the constant and positivity gives the maximal interval.'),
(14,r"P'=\sqrt{Pt},\ P(1)=2",r'\int P^{-1/2}\,dP=\int t^{1/2}\,dt',r'\sqrt P=t^{3/2}/3+\sqrt2-1/3',r'P(t)=(t^{3/2}/3+\sqrt2-1/3)^2,\quad t\ge0','선택한 제곱근 가지가 음이 아닌지 확인한다. 열린 해구간은 양의 시간이며 영까지 연속 연장된다.','The chosen square-root branch is nonnegative. The open solution interval is positive time, with a continuous extension to zero.'),
(15,r"A'=Ab^2\cos(br),\ A(0)=b^3",r'\int\frac{dA}{A}=\int b^2\cos(br)\,dr',r'A=Ce^{b\sin(br)}',r'A(r)=b^3e^{b\sin(br)}','매개변수 영이면 직접 영해가 된다.','A zero parameter gives the zero solution directly.'),
(16,r"x^2y'=k\sec y,\ y(1)=\pi/6",r'\int\cos y\,dy=\int kx^{-2}\,dx',r'\sin y=k+1/2-k/x',r'y=\arcsin(k+1/2-k/x)','초기점 포함 구간에서 입력은 양수이고 역삼각함수의 인자는 절댓값이 일보다 작아야 한다.','On the interval containing the initial point, the input is positive and the arcsine argument has absolute value less than one.'),
(17,r"u'=\frac{2t+\sec^2t}{2u},\ u(0)=-5",r'\int2u\,du=\int(2t+\sec^2t)\,dt',r'u^2=t^2+\tan t+25',r'u=-\sqrt{t^2+\tan t+25}','초기값 때문에 음의 가지를 고른다. 탄젠트가 유한하고 근호가 양수인 초기점 포함 구간을 사용한다.','The initial value selects the negative branch; use its interval where the tangent is finite and the radical is positive.'),
(18,r"x+3y^2\sqrt{x^2+1}\,y'=0,\ y(0)=1",r'\int3y^2\,dy=-\int\frac{x}{\sqrt{x^2+1}}\,dx',r'y^3=2-\sqrt{1+x^2}',r'y=(2-\sqrt{1+x^2})^{1/3},\quad |x|<\sqrt3','양 끝에서 종속변수가 영이 되지만 원래 식은 성립할 수 없어 최대 구간을 종료한다.','At either endpoint the dependent variable vanishes while the original equation cannot hold, ending the maximal interval.'),
(19,r"x\ln x=y(1+\sqrt{3+y^2})y',\ y(1)=1",r'\int y(1+\sqrt{3+y^2})\,dy=\int x\ln x\,dx',r'y^2/2+(3+y^2)^{3/2}/3=x^2\ln x/2-x^2/4+41/12',r'\frac{y^2}{2}+\frac{(3+y^2)^{3/2}}3=\frac{x^2\ln x}2-\frac{x^2}4+\frac{41}{12},\quad x>0,\ y>0','양의 가지는 모든 양의 입력에서 존재하며 초기점을 통과한다.','The positive branch exists for every positive input and passes through the initial point.'),
(20,r"y'=\frac{x\sin x}{y},\ y(0)=-1",r'\int y\,dy=\int x\sin x\,dx',r'y^2=1+2\sin x-2x\cos x',r'y=-\sqrt{1+2\sin x-2x\cos x}','근호가 양수인 초기점 포함 연결구간을 사용한다.','Use the connected interval containing zero on which the radical is positive.'),
(21,r"y'=x/y,\ y(0)=2",r'\int y\,dy=\int x\,dx',r'y^2=x^2+4',r'y=\sqrt{x^2+4}','양의 가지가 초기값을 만족하고 모든 실수에서 미분가능하다.','The positive branch meets the initial value and is differentiable on the real line.'),
(22,r"f'=xf-x,\ f(0)=2",r'\int\frac{df}{f-1}=\int x\,dx',r'f-1=Ce^{x^2/2}',r'f(x)=1+e^{x^2/2}','초기값과 미분식을 직접 검증한다.','Direct substitution checks the initial value and differential equation.'),
(23,r"y'=x+y,\quad u=x+y",r"u'=1+y'=1+u",r'\ln|u+1|=x+C',r'y=Ce^x-x-1','상수계수 영도 포함하여 나눗셈에서 빠지는 해를 복원했다.','The zero coefficient restores the solution lost in division.'),
(24,r"xy'=y+xe^{y/x},\quad v=y/x",r"y'=v+xv',\quad v'=e^v",r'e^{-v}=C-x',r'y=-x\ln(C-x),\quad x\ne0,\ C-x>0','입력 영에서는 원래 지수의 비가 정의되지 않는다.','The ratio in the original exponential is undefined at zero input.')]
for n,eq,sep,integ,ans,k,e in rows:
 verbk='주어진 치환으로 풀어라.' if n>=23 else ('초기값 문제를 풀어라.' if n>=13 else '미분방정식을 풀어라.')
 verbe='Solve using the indicated substitution.' if n>=23 else ('Solve the initial-value problem.' if n>=13 else 'Solve the differential equation.')
 add(n,M(eq)+' '+verbk,M(eq)+' '+verbe,[(M(sep)+'.',M(sep)+'.'),(M(integ)+'.',M(integ)+'.')],M(ans),M(ans),k,e)
add(25,'(a) '+M(r"y'=2x\sqrt{1-y^2}")+'를 풀어라. (b) '+M(r'y(0)=0')+'의 해를 그리고 (c) '+M(r'y(0)=2')+'의 해 존재를 판정하라.','(a) Solve '+M(r"y'=2x\sqrt{1-y^2}")+'. (b) Plot a solution with '+M(r'y(0)=0')+'. (c) Determine existence for '+M(r'y(0)=2')+'.',[(M(r'\arcsin y=x^2+C')+'이므로 사인 가지를 얻지만 코사인이 음이 아닌 구간에서만 원래 근호와 맞는다. 상수해도 따로 확인한다.',M(r'\arcsin y=x^2+C')+' gives sine branches, but the cosine must be nonnegative to match the original square root. Constant solutions must be included.'),('초기값 영의 해는 처음 사인 가지를 따라가다가 높이 일에서 상수해로 연장된다. 초기값 이는 실수 정의역 밖이다.','The zero-initial solution initially follows a sine branch and extends constantly at height one. Initial height two lies outside the real domain.')],M(r'\text{(a) }y=\sin(x^2+C),\ \cos(x^2+C)\ge0;\quad y\equiv\pm1;\quad\text{(b) }y=\begin{cases}\sin x^2&|x|\le\sqrt{\pi/2}\\1&|x|\ge\sqrt{\pi/2}\end{cases}')+' (c) 실수해 없음.',M(r'\text{(a) }y=\sin(x^2+C),\ \cos(x^2+C)\ge0;\quad y\equiv\pm1;\quad\text{(b) }y=\begin{cases}\sin x^2&|x|\le\sqrt{\pi/2}\\1&|x|\ge\sqrt{\pi/2}\end{cases}')+' (c) No real solution.','평형 높이에서 사인 가지와 상수 구간을 미분가능하게 붙인 해들도 가능하다. 표시한 초기값 해는 접합점에서 양쪽 도함수가 영이다.','Differentiable patching of sine and constant branches at equilibrium heights is also possible. Both derivatives vanish at the joins of the displayed solution.','abc')
add(26,M(r'e^{-y}y^{\prime}+\cos x=0')+'을 풀고 여러 해를 그려 적분상수의 효과를 설명하라.','Solve '+M(r'e^{-y}y^{\prime}+\cos x=0')+', plot several solutions, and describe the effect of the integration constant.',[(M(r'(e^{-y})^{\prime}=\cos x')+'이므로 '+M(r'e^{-y}=\sin x+C')+'.',M(r'(e^{-y})^{\prime}=\cos x')+' gives '+M(r'e^{-y}=\sin x+C')+'.'),('상수가 커지면 같은 입력에서 해가 낮아지고, 상수가 일보다 크면 전체 실수축에서 주기함수가 된다.','Larger constants lower the curve at fixed input. Constants greater than one give periodic solutions on the whole real line.')],M(r'y=-\ln(C+\sin x),\quad C+\sin x>0'),M(r'y=-\ln(C+\sin x),\quad C+\sin x>0'),'로그 인자가 영으로 접근하면 해는 양의 무한대로 발산한다.','The solution diverges upward as the logarithm argument approaches zero.')
add(27,M(r"y'=\sin x/\sin y,\ y(0)=\pi/2")+'를 풀고 초기점을 포함하는 해를 그려라.','Solve '+M(r"y'=\sin x/\sin y,\ y(0)=\pi/2")+' and plot the branch containing the initial point.',[(M(r'-\cos y=-\cos x+C')+'에 초기값을 넣는다.',M(r'-\cos y=-\cos x+C')+' and the initial condition fix the constant.'),(M(r'\cos y=\cos x-1')+'에서 초기점에 맞는 역코사인 가지를 고른다.',M(r'\cos y=\cos x-1')+' selects the arccosine branch through the initial point.')],M(r'y=\arccos(\cos x-1),\quad-\pi/2<x<\pi/2'),M(r'y=\arccos(\cos x-1),\quad-\pi/2<x<\pi/2'),'끝점에서는 분모의 사인이 영이 되어 원래 미분방정식이 정의되지 않는다.','At either endpoint the denominator sine vanishes, so the original equation is undefined.')
add(28,M(r"y'=\frac{x\sqrt{x^2+1}}{ye^y}")+'를 풀고 여러 음함수 해를 그려 상수의 영향을 설명하라.','Solve '+M(r"y'=\frac{x\sqrt{x^2+1}}{ye^y}")+', plot several implicit solutions, and describe the parameter effect.',[(M(r'\int ye^y\,dy=\int x\sqrt{x^2+1}\,dx')+'를 부분적분과 치환적분으로 계산한다.',M(r'\int ye^y\,dy=\int x\sqrt{x^2+1}\,dx')+' uses integration by parts and substitution.'),('좌변 함수는 영 높이에서 최소값 음의 일을 갖는다. 양의 가지에서는 상수를 늘리면 곡선이 올라가고 음의 가지에서는 내려간다.','The left side has minimum minus one at zero height. Increasing the constant raises positive branches and lowers negative branches.')],M(r'(y-1)e^y=\tfrac13(1+x^2)^{3/2}+C,\quad y\ne0'),M(r'(y-1)e^y=\tfrac13(1+x^2)^{3/2}+C,\quad y\ne0'),'양의 가지에는 우변이 음의 일보다 커야 하며 음의 가지에는 음의 일과 영 사이여야 한다.','Positive branches require a right side greater than minus one; negative branches require a value between minus one and zero.')
for n,eq,sep,ans,reason,re in [(29,r"y'=y^2",r'-1/y=x+C',r'y=1/(C-x)\quad\text{or}\quad y=0','영이 아닌 해는 증가하고 수직 점근선을 가진다.','Nonzero solutions increase and have vertical asymptotes.'),(30,r"y'=xy",r'\ln|y|=x^2/2+C',r'y=Ce^{x^2/2}','영함수는 평형이고 양의 해는 원점에서 최소, 음의 해는 원점에서 최대이다.','Zero is an equilibrium; positive curves have a minimum at zero input and negative curves a maximum.')]:
 add(n,M(eq)+'의 (a) 방향장과 예상 해를 그리고 (b) 식을 풀어 (c) 실제 곡선과 비교하라.','For '+M(eq)+', (a) plot a field and sketch solutions, (b) solve, and (c) compare computed curves.',[(reason,re),('변수분리로 '+M(sep)+'를 얻는다. 곡선의 접선은 각 점의 방향장과 일치한다.','Separation gives '+M(sep)+'. Tangents to the solution curves agree with the field at every point.')],M(ans),M(ans),'해를 미분해 우변과 일치함을 확인하고 상수해도 포함했다.','Differentiation verifies the right side; constant solutions are included.','abc')
for n,eq,der,orth,sep,ans in [(31,r'x^2+2y^2=k^2',r'y^{\prime}=-x/(2y)',r'y^{\prime}=2y/x',r'\ln|y|=2\ln|x|+C',r'y=Cx^2\quad\text{and the vertical axis}'),(32,r'y^2=kx^3',r'y^{\prime}=3y/(2x)',r'y^{\prime}=-2x/(3y)',r'3y\,dy=-2x\,dx',r'2x^2+3y^2=C,\quad C>0'),(33,r'y=k/x',r'y^{\prime}=-y/x',r'y^{\prime}=x/y',r'y\,dy=x\,dx',r'y^2-x^2=C'),(34,r'y=1/(x+k)',r'y^{\prime}=-y^2',r'y^{\prime}=1/y^2',r'y^2\,dy=dx',r'y^3=3x+C')]:
 add(n,M(eq)+'의 직교궤적을 구하고 두 족을 함께 그려라.','Find orthogonal trajectories of '+M(eq)+' and plot both families.', [('원래 족을 미분해 상수를 제거하면 '+M(der)+'.','Differentiate and eliminate the parameter to get '+M(der)+'.'),('기울기의 음의 역수를 취해 '+M(orth)+'를 얻고 '+M(sep)+'를 적분한다.','Take the negative reciprocal '+M(orth)+' and integrate '+M(sep)+'.')],M(ans),M(ans),'유한하고 영이 아닌 두 기울기의 곱은 음의 일이다. 수직·수평 접선은 접선벡터로 직교성을 확인한다.','The two finite nonzero slopes multiply to minus one. Vertical-horizontal cases are checked using tangent vectors.')
for n,eq,ivp,sep,ans in [(35,r'y(x)=2+\int_2^x[t-ty(t)]\,dt',r"y'=x(1-y),\ y(2)=2",r'\ln|1-y|=-x^2/2+C',r'y=1+e^{2-x^2/2}'),(36,r'y(x)=2+\int_1^x\frac{dt}{ty(t)},\quad x>0',r"y'=1/(xy),\ y(1)=2",r'y^2=2\ln x+4',r'y=\sqrt{4+2\ln x},\quad x>e^{-2}'),(37,r'y(x)=4+\int_0^x2t\sqrt{y(t)}\,dt',r"y'=2x\sqrt y,\ y(0)=4",r'2\sqrt y=x^2+4',r'y=(2+x^2/2)^2')]:
 add(n,'적분방정식 '+M(eq)+'을 풀어라.','Solve the integral equation '+M(eq)+'.',[('미적분학의 기본정리와 아래끝점을 대입하면 '+M(ivp)+'.','The fundamental theorem and lower endpoint give '+M(ivp)+'.'),('변수분리와 초기값을 사용해 '+M(sep)+'.','Separation and the initial value give '+M(sep)+'.')],M(ans),M(ans),'도함수와 아래끝점에서의 값이 원래 적분식 양변에서 같으므로 기본정리에 의해 식 전체가 성립한다.','Equal derivatives and equal values at the lower endpoint verify the entire integral identity.')
add(38,M(r'(t^2+1)f^{\prime}(t)+f(t)^2+1=0,\quad f(3)=2,\quad t\ne1')+'인 함수를 구하라.','Find a function satisfying '+M(r'(t^2+1)f^{\prime}(t)+f(t)^2+1=0,\quad f(3)=2,\quad t\ne1')+'.',[(M(r'\arctan f=-\arctan t+C,\quad C=\arctan2+\arctan3')+'.',M(r'\arctan f=-\arctan t+C,\quad C=\arctan2+\arctan3')+'.'),('탄젠트 덧셈공식으로 '+M(r'\tan C=-1')+'을 사용하면 유리함수로 단순화된다.','The tangent addition formula gives '+M(r'\tan C=-1')+' and simplifies the result to a rational function.')],M(r'f(t)=\frac{t+1}{t-1},\quad t>1'),M(r'f(t)=\frac{t+1}{t-1},\quad t>1'),'직접 미분한 잔차는 영이고 입력 삼에서 값 이는 맞는다. 초기점을 포함하는 최대 구간은 일보다 큰 입력이다.','Direct differentiation gives zero residual and the value at three is two. The maximal interval through the initial point is above one.')
for n,eq,sep,ans,k,e in [(39,r"Q'=12-4Q,\ Q(0)=0",r'\ln|3-Q|=-4t+C',r'Q(t)=3(1-e^{-4t}),\quad\lim_{t\to\infty}Q(t)=3','저항 오 옴, 용량 영점영오 패럿, 전압 육십 볼트 회로의 전하를 구하고 극한을 설명하라.','Find the charge and its limit for the five-ohm, 0.05-farad, sixty-volt circuit.'),(40,r"T'=-0.02(T-20),\ T(0)=95",r'\ln|T-20|=-0.02t+C',r'T(t)=20+75e^{-0.02t}','커피 냉각 모델의 정확한 온도 함수를 구하라. 시간 단위는 분이다.','Find the exact coffee temperature in the cooling model, with time measured in minutes.'),(41,r"P'=k(M-P),\ k>0",r'\ln|M-P|=-kt+C',r'P(t)=M+Ce^{-kt},\quad\lim_{t\to\infty}P(t)=M','학습 수행도 모델을 풀고 장기 극한을 구하라.','Solve the learning performance model and find its long-time limit.')]:
 add(n,k+' '+M(eq),e+' '+M(eq),[('변수분리로 '+M(sep)+'을 얻는다.','Separation yields '+M(sep)+'.'),('지수화 후 초기값 또는 임의 상수를 사용한다. 양의 시간 무한대에서 감쇠항은 영으로 간다.','Exponentiate and use the initial value or arbitrary constant. The decaying term tends to zero at large positive time.')],M(ans),M(ans),'직접 미분과 초기조건 또는 일반상수를 대입해 검증했다.','Direct differentiation and substitution verify the initial condition or general constant.')
add(42,'반응 농도 모델 '+M(r"x'=k(a-x)(b-x),\ x(0)=0,\ a,b,k>0")+'을 (a) 서로 다른 초기 농도와 (b) 같은 초기 농도에서 풀어라. (b) 이십 초에서 생성물 농도가 초기 반응물 농도의 절반이면 식을 단순화하라.','Solve the concentration model '+M(r"x'=k(a-x)(b-x),\ x(0)=0,\ a,b,k>0")+' for (a) unequal and (b) equal initial concentrations. In (b), simplify when half the initial reactant concentration is converted after twenty seconds.',[(M(r'\frac1{b-a}\ln\frac{b-x}{a-x}=kt+\frac1{b-a}\ln\frac ba')+'를 부분분수 적분으로 얻는다.',M(r'\frac1{b-a}\ln\frac{b-x}{a-x}=kt+\frac1{b-a}\ln\frac ba')+' follows by partial fractions.'),('같은 농도일 때는 '+M(r'1/(a-x)=kt+1/a')+'. 절반 조건은 '+M(r'ak=1/20')+'을 준다.','Equal concentrations give '+M(r'1/(a-x)=kt+1/a')+'. The half-conversion condition gives '+M(r'ak=1/20')+'.')],M(r'\text{(a) }x=\frac{ab(e^{(b-a)kt}-1)}{be^{(b-a)kt}-a};\quad\text{(b) }x=\frac{a^2kt}{1+akt}=\frac{at}{20+t}\ \text{under the half-conversion condition}'),M(r'\text{(a) }x=\frac{ab(e^{(b-a)kt}-1)}{be^{(b-a)kt}-a};\quad\text{(b) }x=\frac{a^2kt}{1+akt}=\frac{at}{20+t}\ \text{under the half-conversion condition}'),'초기값은 영이며 장기 농도는 두 초기 농도 중 작은 값에 접근한다.','The initial value is zero and the limiting concentration is the smaller initial concentration.','ab')
add(43,'주어진 반응 모델 '+M(r"x'=k(a-x)\sqrt{b-x},\ x(0)=0,\ a,b,k>0")+'에서 (a) 같은 초기 농도일 때 시간 함수를, (b) '+M(r'a>b')+'일 때 농도의 시간 역함수를 구하라.','For the specified reaction model '+M(r"x'=k(a-x)\sqrt{b-x},\ x(0)=0,\ a,b,k>0")+', find (a) concentration as a function of time for equal initial concentrations and (b) time as a function of concentration for '+M(r'a>b')+'.', [('(a) '+M(r'2(a-x)^{-1/2}=kt+2a^{-1/2}')+'이다.','(a) Separation gives '+M(r'2(a-x)^{-1/2}=kt+2a^{-1/2}')+'.'),('(b) '+M(r'u=\sqrt{b-x},\quad dx=-2u\,du')+'를 넣어 역탄젠트 적분으로 바꾼다.','(b) Set '+M(r'u=\sqrt{b-x},\quad dx=-2u\,du')+' to obtain an arctangent integral.')],M(r'\text{(a) }x=a-\frac{a}{(1+\tfrac12k\sqrt a\,t)^2};\quad\text{(b) }t=\frac2{k\sqrt{a-b}}\left[\arctan\sqrt{\frac b{a-b}}-\arctan\sqrt{\frac{b-x}{a-b}}\right],\quad0\le x\le b'),M(r'\text{(a) }x=a-\frac{a}{(1+\tfrac12k\sqrt a\,t)^2};\quad\text{(b) }t=\frac2{k\sqrt{a-b}}\left[\arctan\sqrt{\frac b{a-b}}-\arctan\sqrt{\frac{b-x}{a-b}}\right],\quad0\le x\le b'),'초기점에서 시간이 영이며 농도 증가에 필요한 시간이 양수이다. 모델의 농도 변수 정의는 제시된 방정식을 따른다.','Time is zero initially and increases with concentration. Concentration variables follow the supplied mathematical model.','ab')
add(44,'동심 구면 사이 온도가 '+M(r"T''+\frac2rT'=0,\quad T(1)=15,\ T(2)=25")+'을 만족한다. 두 구면 사이의 온도를 구하라.','Find the temperature between concentric spheres satisfying '+M(r"T''+\frac2rT'=0,\quad T(1)=15,\ T(2)=25")+'.',[(M(r'S=T^{\prime},\quad S^{\prime}/S=-2/r\Rightarrow S=C/r^2')+'.',M(r'S=T^{\prime},\quad S^{\prime}/S=-2/r\Rightarrow S=C/r^2')+'.'),('한 번 더 적분하면 '+M(r'T=A+B/r')+'이며 두 경계값으로 상수를 정한다.','A second integration gives '+M(r'T=A+B/r')+'; the two boundary values determine the constants.')],M(r'T(r)=35-20/r,\quad1\le r\le2'),M(r'T(r)=35-20/r,\quad1\le r\le2'),'경계 온도와 이계 미분방정식에 직접 대입하면 모두 일치한다.','Both boundary temperatures and the second-order equation check directly.')
add(45,'농도 모델 '+M(r"C'=r-kC,\quad C(0)=C_0,\quad k>0")+'에서 (a) 해를 구하고 (b) 초기 농도가 평형보다 낮을 때 장기 거동을 해석하라.','For the concentration model '+M(r"C'=r-kC,\quad C(0)=C_0,\quad k>0")+', (a) solve and (b) interpret long-time behavior when the initial concentration is below equilibrium.',[(M(r'\int\frac{dC}{r-kC}=t+K')+'를 적분한 후 초기값을 넣는다.',M(r'\int\frac{dC}{r-kC}=t+K')+' is integrated and fitted to the initial value.'),('유입과 제거가 같아지는 평형을 아래쪽에서 향한다.','The concentration approaches the balance between inflow and removal from below.')],M(r'C(t)=r/k+(C_0-r/k)e^{-kt};\quad C_0<r/k\Rightarrow C(t)\uparrow r/k'),M(r'C(t)=r/k+(C_0-r/k)e^{-kt};\quad C_0<r/k\Rightarrow C(t)\uparrow r/k'),'초기값과 평형을 복원하고 도함수의 부호가 양수임을 확인한다.','The initial and equilibrium values are recovered, and the derivative is positive.','ab')
add(46,'유통 화폐 총액은 백억 달러이고 매일 오천만 달러가 은행으로 들어온다. 들어온 구권을 신권으로 교체하며 처음 신권은 없다. (a) 신권 양의 초기값 모델, (b) 해, (c) 신권 비중 구십 퍼센트까지 걸리는 시간을 구하라.','A fixed ten-billion-dollar circulation sends fifty million dollars through banks daily. Banks replace incoming old notes with new ones; initially none are new. Find (a) the initial-value model, (b) its solution, and (c) time to ninety-percent replacement.', [('일일 입금 중 구권 비율만큼이 새로운 신권 유입이다. 십억 달러 단위로 '+M(r"x'=0.05(1-x/10),\quad x(0)=0")+'.','Only the old-note fraction of daily deposits adds new currency. In billions of dollars, '+M(r"x'=0.05(1-x/10),\quad x(0)=0")+'.'),('완전 혼합을 가정해 지수감쇠식으로 풀고 구십 퍼센트 조건을 넣는다.','Assuming uniform mixing, solve the exponential decay of old notes and impose ninety percent replacement.')],M(r'x(t)=10(1-e^{-t/200});\quad t_{90}=200\ln10\approx460.517\ \text{days}'),M(r'x(t)=10(1-e^{-t/200});\quad t_{90}=200\ln10\approx460.517\ \text{days}'),'일일 유입과 전체량의 비율은 이백분의 일이며 시간 단위는 일이다.','The daily turnover fraction is one two-hundredth, with time in days.','abc')
for n,sk,se,eq,ans,sub in [
(47,'천 리터 소금물에 소금 십오 킬로그램이 있고 분당 십 리터 순수가 유입되어 같은 양이 빠진다. (a) 시간별 소금량, (b) 이십 분 뒤 양을 구하라.','A thousand-liter tank initially contains fifteen kilograms of salt. Pure water enters at ten liters per minute and an equal mixed flow leaves. Find (a) salt mass over time and (b) after twenty minutes.',r"S'=-S/100,\ S(0)=15",r'S(t)=15e^{-t/100}\ \mathrm{kg};\quad S(20)=15e^{-0.2}\approx12.28096\ \mathrm{kg}','ab'),
(48,'백팔십 세제곱미터 방의 이산화탄소 비율은 처음 영점일오 퍼센트이다. 영점영오 퍼센트 공기가 분당 이 세제곱미터로 유입되고 같은 양의 혼합 공기가 나간다. 시간별 백분율과 극한을 구하라.','A 180-cubic-meter room begins at 0.15 percent carbon dioxide. Air at 0.05 percent enters at two cubic meters per minute and mixed air leaves equally fast. Find the percentage over time and its limit.',r"p'=(0.05-p)/90,\ p(0)=0.15",r'p(t)=0.05+0.10e^{-t/90}\ \%;\quad\lim p=0.05\ \%',''),
(49,'오백 갤런 맥주의 알코올 비율이 처음 사 퍼센트이다. 육 퍼센트 맥주가 분당 오 갤런으로 들어오며 같은 유량으로 혼합액이 나간다. 한 시간 뒤 알코올 비율을 구하라.','A five-hundred-gallon vat begins with four-percent beer. Six-percent beer enters at five gallons per minute while the same mixed flow leaves. Find the alcohol percentage after one hour.',r"p'=(6-p)/100,\ p(0)=4",r'p(60)=6-2e^{-0.6}\approx4.90238\ \%',''),
(50,'천 리터 순수에 리터당 영점영오 킬로그램 소금물이 분당 오 리터, 영점영사 킬로그램 소금물이 분당 십 리터 유입된다. 혼합액은 분당 십오 리터 배출된다. (a) 시간별 소금량과 (b) 한 시간 뒤 양을 구하라.','A thousand liters of pure water receives brine at 0.05 kilograms per liter flowing at five liters per minute and brine at 0.04 kilograms per liter flowing at ten liters per minute. Mixed outflow is fifteen liters per minute. Find (a) salt mass over time and (b) after one hour.',r"S'=0.65-0.015S,\ S(0)=0",r'S(t)=\frac{130}3(1-e^{-0.015t})\ \mathrm{kg};\quad S(60)=\frac{130}3(1-e^{-0.9})\approx25.71531\ \mathrm{kg}','ab')]:
 add(n,sk,se,[('변화율은 유입 물질량에서 유출 물질량을 뺀 값이다. 부피가 일정하여 '+M(eq)+'.','The rate is inflow minus outflow. Constant volume gives '+M(eq)+'.'),('평형과의 차이를 분리 적분한 뒤 지정된 시간에 대입한다.','Separate the difference from equilibrium and evaluate at the requested time.')],M(ans),M(ans),'초기값과 유입 농도에 따른 평형값을 확인했다.','The initial value and equilibrium implied by the inflow concentration were checked.',sub)
add(51,'빗방울 질량이 '+M(r"m'=km,\quad k>0")+'로 증가하고 아래 방향 속도가 '+M(r'(mv)^{\prime}=gm')+'을 만족한다. 종단속도를 구하라.','A raindrop mass obeys '+M(r"m'=km,\quad k>0")+' and its downward velocity satisfies '+M(r'(mv)^{\prime}=gm')+'. Find terminal velocity.', [('곱의 미분법으로 '+M(r'mv^{\prime}+kmv=gm')+'이고 양의 질량으로 나눈다.','The product rule gives '+M(r'mv^{\prime}+kmv=gm')+'; divide by positive mass.'),(M(r'v^{\prime}=g-kv,\quad v=g/k+(v_0-g/k)e^{-kt}')+'.',M(r'v^{\prime}=g-kv,\quad v=g/k+(v_0-g/k)e^{-kt}')+'.')],M(r'v_{terminal}=g/k'),M(r'v_{terminal}=g/k'),'가속도와 질량 증가에 따른 운동량 항이 평형에서 일치한다.','At equilibrium gravity balances the momentum contribution from mass growth.')
add(52,'질량이 일정한 물체가 '+M(r"mv'=f(v),\quad v(0)=v_0>0,\ s(0)=s_0")+'를 따른다. (a) '+M(r'f(v)=-kv')+', (b) '+M(r'f(v)=-kv^2')+'에서 속도·위치·총 이동거리를 구하라.','A constant-mass object obeys '+M(r"mv'=f(v),\quad v(0)=v_0>0,\ s(0)=s_0")+'. Find velocity, position, and total distance for (a) '+M(r'f(v)=-kv')+' and (b) '+M(r'f(v)=-kv^2')+'.', [('(a) 속도는 지수감쇠하며 한 번 더 적분하면 위치가 된다.','(a) Velocity decays exponentially; one more integration gives position.'),('(b) 역속도가 시간에 대해 선형이다. 위치는 로그함수이고 무한 시간에서 로그가 발산한다.','(b) Reciprocal velocity is linear in time. Position is logarithmic and grows without bound over infinite time.')],M(r'\text{(a) }v=v_0e^{-kt/m},\ s=s_0+\frac{mv_0}k(1-e^{-kt/m}),\ D=mv_0/k;\quad\text{(b) }v=\frac{mv_0}{m+kv_0t},\ s=s_0+\frac mk\ln(1+kv_0t/m),\ D=\infty'),M(r'\text{(a) }v=v_0e^{-kt/m},\ s=s_0+\frac{mv_0}k(1-e^{-kt/m}),\ D=mv_0/k;\quad\text{(b) }v=\frac{mv_0}{m+kv_0t},\ s=s_0+\frac mk\ln(1+kv_0t/m),\ D=\infty'),'위치를 미분하면 속도, 속도를 미분하면 저항력이 복원된다. 정지 초기값의 이동거리는 영이다.','Differentiating position recovers velocity and differentiating velocity recovers drag. A zero initial velocity gives zero distance.','ab')
add(53,'성장률 관계 '+M(r'\frac1{L_1}\frac{dL_1}{dt}=\frac{k}{L_2}\frac{dL_2}{dt}')+'에서 (a) 두 길이 사이의 식을 구하고 (b) 생체량과 세포 부피의 비례 지수 '+M(r'k=0.0794')+'를 적용하라.','Given '+M(r'\frac1{L_1}\frac{dL_1}{dt}=\frac{k}{L_2}\frac{dL_2}{dt}')+', (a) relate the two sizes and (b) apply exponent '+M(r'k=0.0794')+' to cell biomass and volume.',[(M(r'\frac{dL_1}{L_1}=k\frac{dL_2}{L_2}')+'를 적분한다.',M(r'\frac{dL_1}{L_1}=k\frac{dL_2}{L_2}')+' is integrated.'),(M(r'\ln L_1=k\ln L_2+C')+'에 지수함수를 적용한다.',M(r'\ln L_1=k\ln L_2+C')+' is exponentiated.')],M(r'\text{(a) }L_1=AL_2^k;\quad\text{(b) }B=AV^{0.0794},\quad A>0'),M(r'\text{(a) }L_1=AL_2^k;\quad\text{(b) }B=AV^{0.0794},\quad A>0'),'양의 크기에서 로그가 정의되며 로그미분으로 원래 관계가 복원된다.','Positive sizes permit logarithms; logarithmic differentiation restores the original relation.','ab')
add(54,M(r"V'=a(\ln b-\ln V)V,\quad a,b>0")+'의 (a) 해족과 (b) '+M(r'V(0)=1')+'의 해를 구하라.','Find (a) the solution family of '+M(r"V'=a(\ln b-\ln V)V,\quad a,b>0")+' and (b) the solution with '+M(r'V(0)=1')+'.', [(M(r'u=\ln(V/b),\quad u^{\prime}=-au')+'로 선형 감쇠식이 된다.',M(r'u=\ln(V/b),\quad u^{\prime}=-au')+' gives linear decay.'),(M(r'u=Ce^{-at}')+'에서 다시 지수화하고 초기값을 넣는다.',M(r'u=Ce^{-at}')+' is exponentiated and fitted to the initial value.')],M(r'\text{(a) }V=b\exp(Ce^{-at});\quad\text{(b) }V=b\exp[-(\ln b)e^{-at}]=b^{1-e^{-at}}'),M(r'\text{(a) }V=b\exp(Ce^{-at});\quad\text{(b) }V=b\exp[-(\ln b)e^{-at}]=b^{1-e^{-at}}'),'해는 항상 양수이며 초기값 일과 장기값을 직접 복원한다.','The solution stays positive and directly recovers the initial and limiting values.','ab')
add(55,'조직 면적 증가율이 '+M(r'\sqrt A')+'와 '+M(r'M-A')+'의 곱에 비례한다. (a) 모델과 최대 성장 면적, (b) 면적의 시간 함수를 구하라.','Tissue area grows at a rate proportional to the product of '+M(r'\sqrt A')+' and '+M(r'M-A')+'. Find (a) the model and area of fastest growth and (b) the area as a function of time.',[(M(r'A^{\prime}=k\sqrt A(M-A),\quad\frac{d}{dA}[k\sqrt A(M-A)]=\frac{k(M-3A)}{2\sqrt A}')+'이므로 내부 극대는 전체 면적의 삼분의 일이다.',M(r'A^{\prime}=k\sqrt A(M-A),\quad\frac{d}{dA}[k\sqrt A(M-A)]=\frac{k(M-3A)}{2\sqrt A}')+' has its interior maximum at one third of the final area.'),(M(r'u=\sqrt A,\quad\frac{2\,du}{M-u^2}=k\,dt,\quad\frac1{\sqrt M}\ln\frac{\sqrt M+u}{\sqrt M-u}=kt+C')+'을 적분한다.',M(r'u=\sqrt A,\quad\frac{2\,du}{M-u^2}=k\,dt,\quad\frac1{\sqrt M}\ln\frac{\sqrt M+u}{\sqrt M-u}=kt+C')+' integrates the growing branch.')],M(r'A_{fast}=M/3;\quad A(t)=M\tanh^2(\tfrac12k\sqrt M\,t+C),\quad\tfrac12k\sqrt M\,t+C\ge0;\quad A\equiv0,M'),M(r'A_{fast}=M/3;\quad A(t)=M\tanh^2(\tfrac12k\sqrt M\,t+C),\quad\tfrac12k\sqrt M\,t+C\ge0;\quad A\equiv0,M'),'식은 면적이 영과 최종값 사이인 성장 모델에 해당한다. 음의 쌍곡탄젠트 인자는 제곱근 부호와 맞지 않는다. 영해 뒤에 성장 가지를 붙이는 대기시간 해도 가능하다.','This formula describes the growth range between zero and final area. A negative hyperbolic-tangent argument would violate the square-root sign. Waiting-time solutions can join a zero segment to a growing branch.','ab')
add(56,'바다 얼음의 두께와 열손실이 '+M(r'\frac{dQ}{dt}=\frac{kA}{h}(T_w-T_a),\quad T_w>T_a')+'를 따른다. 밀도는 '+M(r'D')+', 단위 질량의 응고 잠열은 '+M(r'L')+'이다. (a) 열손실과 두께 증가 관계, (b) 시간 미분방정식과 얇은 얼음의 성장 속도, (c) '+M(r'h(0)=h_0')+'의 해를 구하라.','Sea-ice thickness and heat loss obey '+M(r'\frac{dQ}{dt}=\frac{kA}{h}(T_w-T_a),\quad T_w>T_a')+'. Density is '+M(r'D')+' and latent heat per mass is '+M(r'L')+'. Find (a) the heat-thickness relation, (b) the time equation and why thin ice grows faster, and (c) the solution with '+M(r'h(0)=h_0')+'.', [('얇은 층의 질량은 단면적·두께·밀도의 곱이므로 '+M(r'\Delta Q\approx LAD\Delta h,\quad dh/dQ=1/(LAD)')+'.','The thin layer has mass area times thickness times density, so '+M(r'\Delta Q\approx LAD\Delta h,\quad dh/dQ=1/(LAD)')+'.'),('연쇄법칙을 쓰면 단면적이 약분된다. '+M(r'h\,dh=\frac{k(T_w-T_a)}{LD}\,dt')+'를 적분한다.','The chain rule cancels the area. Integrate '+M(r'h\,dh=\frac{k(T_w-T_a)}{LD}\,dt')+'.')],M(r'h^{\prime}=\frac{k(T_w-T_a)}{LDh};\quad h(t)=\sqrt{h_0^2+\frac{2k(T_w-T_a)}{LD}t}')+'; 얇을수록 더 빨리 두꺼워진다.',M(r'h^{\prime}=\frac{k(T_w-T_a)}{LDh};\quad h(t)=\sqrt{h_0^2+\frac{2k(T_w-T_a)}{LD}t}')+'; thinner ice thickens faster.','상수 온도차와 양의 두께에서 유효하다. 두께 영에서는 식이 특이하며 양의 시간 해를 연속 연장할 수 있다.','The model assumes constant temperature difference and positive thickness. Zero thickness is singular, although the positive-time solution has a continuous extension.','abc')
add(57,'지구 표면에서 위로 쏜 물체가 '+M(r'mv^{\prime}=-mgR^2/(x+R)^2')+'를 따른다. (a) 최고 높이와 초기 속도의 관계, (b) 탈출속도, (c) '+M(r'R=3960\ \mathrm{mi},\quad g=32\ \mathrm{ft/s^2}')+'일 때 두 단위의 수치를 구하라.','A body launched upward obeys '+M(r'mv^{\prime}=-mgR^2/(x+R)^2')+'. Find (a) the relation between maximum height and launch speed, (b) escape velocity, and (c) numerical speeds in feet and miles per second for '+M(r'R=3960\ \mathrm{mi},\quad g=32\ \mathrm{ft/s^2}')+'.', [('연쇄법칙으로 '+M(r'v\,dv=-\frac{gR^2}{(x+R)^2}\,dx')+'이다. 표면부터 최고점까지 적분한다.','The chain rule gives '+M(r'v\,dv=-\frac{gR^2}{(x+R)^2}\,dx')+'. Integrate from the surface to maximum height.'),(M(r'-v_0^2/2=gR^2(1/(R+h)-1/R)')+'이며 높이 무한대의 극한을 취한다. 수치 계산 전 반지름을 피트로 바꾼다.',M(r'-v_0^2/2=gR^2(1/(R+h)-1/R)')+' yields the infinite-height limit. Convert the radius to feet before numerical evaluation.')],M(r'v_0=\sqrt{\frac{2gRh}{R+h}};\quad v_e=\sqrt{2gR}\approx36580.9131\ \mathrm{ft/s}\approx6.9282\ \mathrm{mi/s}'),M(r'v_0=\sqrt{\frac{2gRh}{R+h}};\quad v_e=\sqrt{2gR}\approx36580.9131\ \mathrm{ft/s}\approx6.9282\ \mathrm{mi/s}'),'에너지 적분에서 질량이 소거되고 속도 제곱의 단위가 길이 제곱 나누기 시간 제곱이 된다.','Mass cancels in the energy integral and squared speed has units of length squared per time squared.','abc')
# Reuse only plotting function definitions, without executing another authoring script.
src=(BASE/'exercise-checks/s9-2-author.py').read_text();tree=ast.parse(src)
funcs=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ['rk','both','sampled','svg']]
code=ast.unparse(ast.Module(body=funcs,type_ignores=[])).replace('s9-2-','s9-3-');exec(compile(code,'plot-helpers','exec'))
svg(25,'Real initial-value solution; constant continuation',lambda x,y:2*x*math.sqrt(max(0,1-y*y)) if abs(y)<=1 else math.nan,(-2,2),(-1.1,1.2),[('y(0)=0',sampled(lambda x:math.sin(x*x) if abs(x)<=math.sqrt(math.pi/2) else 1,-2,2))])
svg(26,'y=-ln(C+sin x)',None,(-4,4),(-2,4),[(f'C={c}',sampled(lambda x:-math.log(c+math.sin(x)) if c+math.sin(x)>0 else math.nan,-4,4)) for c in [.5,1,2,3]])
svg(27,'y=arccos(cos x-1)',None,(-1.57,1.57),(1.4,3.2),[('initial branch',sampled(lambda x:math.acos(math.cos(x)-1),-1.57,1.57))])
def inverseG(q,positive):
 if q<=-1 or (not positive and q>=0):return math.nan
 lo,hi=(0,10) if positive else (-40,0)
 for _ in range(70):
  mid=(lo+hi)/2;v=(mid-1)*math.exp(mid)
  if (v<q)==positive:lo=mid
  else:hi=mid
 return (lo+hi)/2
svg(28,'Implicit branches: (y-1)exp(y)=(1+x^2)^(3/2)/3+C',None,(-2,2),(-5,3),[(f'C={c}, '+('positive' if pos else 'negative'),sampled(lambda x:inverseG((1+x*x)**1.5/3+c,pos),-2,2)) for c,pos in [(-1.2,True),(-1.2,False),(-.7,True),(-.7,False),(1,True)]])
svg(29,'y prime = y^2',lambda x,y:y*y,(-3,3),(-4,4),[('y=0',sampled(lambda x:0,-3,3))]+[(f'C={c}',sampled(lambda x:1/(c-x) if abs(c-x)>.015 else math.nan,-3,3)) for c in [-2,0,2]])
svg(30,'y prime = xy',lambda x,y:x*y,(-2,2),(-5,5),[(f'C={c}',sampled(lambda x:c*math.exp(x*x/2),-2,2)) for c in [-1,-.5,0,.5,1]])
def param(f,g,a=0,b=2*math.pi):return [(f(a+(b-a)*i/600),g(a+(b-a)*i/600)) for i in range(601)]
svg(31,'Ellipses and orthogonal parabolas',None,(-3,3),(-3,3),[(f'ellipse k={k}',param(lambda t:k*math.cos(t),lambda t:k/math.sqrt(2)*math.sin(t))) for k in [1,2]]+[(f'y={c}x^2',sampled(lambda x:c*x*x,-3,3)) for c in [-1,-.4,.4,1]])
svg(32,'Cubic families and orthogonal ellipses',None,(-3,3),(-3,3),[(f'k={k}, sign={sg}',sampled(lambda x:sg*math.sqrt(k*x**3) if k*x**3>=0 else math.nan,-3,3)) for k,sg in [(1,1),(1,-1),(-1,1),(-1,-1)]]+[(f'ellipse C={c}',param(lambda t:math.sqrt(c/2)*math.cos(t),lambda t:math.sqrt(c/3)*math.sin(t))) for c in [2,8]])
svg(33,'Hyperbolas and orthogonal hyperbolas',None,(-3,3),(-3,3),[(f'xy={k}',sampled(lambda x:k/x if abs(x)>.025 else math.nan,-3,3)) for k in [-1,1]]+[(f'y^2-x^2={c}, sign={sg}',sampled(lambda x:sg*math.sqrt(x*x+c) if x*x+c>=0 else math.nan,-3,3)) for c,sg in [(1,1),(1,-1),(-1,1),(-1,-1)]])
svg(34,'Reciprocals and orthogonal cubic curves',None,(-3,3),(-3,3),[(f'k={k}',sampled(lambda x:1/(x+k) if abs(x+k)>.025 else math.nan,-3,3)) for k in [-1,0,1]]+[(f'y^3=3x+{c}',sampled(lambda x:math.copysign(abs(3*x+c)**(1/3),3*x+c),-3,3)) for c in [-2,0,2]])
assert len(items)==57
raw=dict(section='9.3',source=dict(title='Calculus',edition='9',language='en',printedPages=[664,665,666,667],pdfPages=[701,702,703,704]),scope=dict(kind='exercise',numbers=list(range(1,58)),total=57,note=bi('일반 연습문제 전체 57문항 및 모든 소문항.','All 57 ordinary exercises and every subpart.')),exercises=items)
p=BASE/'exercise-content/s9-3.json';p.write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n');sys.path.insert(0,str(BASE));import build_exercises as b;b.validate_document(raw,p)
print('9.3:57 cards,10 figures')
print('50',130/3*(1-math.exp(-.9)),'57',math.sqrt(2*32*3960*5280),math.sqrt(2*32*3960*5280)/5280)
