import json,math,html,sys,ast
from pathlib import Path
BASE=Path(__file__).resolve().parents[1];items=[]
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':e if e is not None else k}
def add(n,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=676 if n<=4 else 677 if n<=13 else 678 if n<=19 else 679
 items.append(dict(id=f'stewart9-exercise-9.4-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('인구 성장 모델','Population growth models'),statement=bi(sk,se),hint=bi('평형과 변수분리 해를 이용하고 단위를 일치시킨다.','Use equilibria and separated solutions, keeping units consistent.'),steps={'ko':[x[0] for x in steps],'en':[x[1] for x in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
src=(BASE/'exercise-checks/s9-2-author.py').read_text();tree=ast.parse(src);funcs=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ['rk','both','sampled','svg','euler']];exec(compile(ast.unparse(ast.Module(body=funcs,type_ignores=[])).replace('s9-2-','s9-4-'),'helpers','exec'))
def logistic(t,K,k,p):return K/(1+(K/p-1)*math.exp(-k*t))
for n,eq,K,k,p in [(1,r"P'=0.04P(1-P/1200),\ P(0)=60",1200,.04,60),(2,r"P'=0.02P-0.0004P^2,\ P(0)=40",50,.02,40)]:
 A=K/p-1;answer=rf'M={K},\quad k={k};\quad P(t)=\frac{{{K}}}{{1+{A:g}e^{{-{k}t}}}};\quad P(10)\approx{logistic(10,K,k,p):.6f}'
 add(n,M(eq)+'에서 (a) 수용력과 성장계수, (b) 해, (c) 십 주 뒤 인구를 구하라.','For '+M(eq)+', find (a) carrying capacity and growth coefficient, (b) the solution, and (c) the ten-week population.', [('표준형 '+M(r"P'=kP(1-P/M)")+'과 계수를 비교한다.','Compare coefficients with '+M(r"P'=kP(1-P/M)")+'.'),(M(r'P=M/(1+Ae^{-kt}),\quad A=M/P(0)-1')+'에 초기값을 넣고 시간을 대입한다.',M(r'P=M/(1+Ae^{-kt}),\quad A=M/P(0)-1')+' uses the initial value and requested time.')],M(answer),M(answer),'직접 미분과 초기값을 확인했다. 인구는 초기값과 수용력 사이에 있다.','Differentiation and initial values check; the population stays between its initial value and carrying capacity.','abc')
add(3,M(r"P'=0.05P-0.0005P^2")+'의 (a) 수용력·계수, (b) 작은 기울기·최대 기울기·증감, (c) '+M(r'P(0)=20,40,60,80,120,140')+'의 그래프와 변곡점, (d) 평형해와의 관계를 설명하라.','For '+M(r"P'=0.05P-0.0005P^2")+', give (a) capacity and coefficient, (b) small and maximal slopes and monotonicity, (c) curves and inflections for '+M(r'P(0)=20,40,60,80,120,140')+', and (d) their relation to equilibria.', [('수용력은 백이고 영과 백 근처에서 기울기가 작다. 오십에서 증가율이 최대이며 값은 일점이오이다.','Capacity is one hundred; slopes are small near zero and one hundred. The maximal rate is 1.25 at fifty.'),('백 아래에서는 증가하고 위에서는 감소하며 모든 양의 초기값은 백으로 수렴한다. 이십·사십의 곡선만 양의 시간에 오십을 지나 변곡한다. 육십·팔십은 아래로 오목, 백이십·백사십은 위로 볼록이다.','Below one hundred solutions increase; above it they decrease, all tending to one hundred. Only the twenty and forty curves cross fifty and inflect at positive times. The sixty and eighty curves are concave down; the 120 and 140 curves are convex.')],M(r'M=100,\ k=0.05;\quad P(t)=100/[1+(100/P_0-1)e^{-0.05t}];\quad P_{eq}=0,100;\quad P_{infl}=50'),M(r'M=100,\ k=0.05;\quad P(t)=100/[1+(100/P_0-1)e^{-0.05t}];\quad P_{eq}=0,100;\quad P_{infl}=50'),'평형해를 가로지르지 않으며 이계 도함수의 부호가 서술한 오목성을 준다.','Solutions cannot cross equilibria; the second derivative gives the stated concavities.','abcd')
svg(3,'Logistic field; capacity 100',lambda t,p:.05*p-.0005*p*p,(0,70),(0,150),[(f'P0={p}',sampled(lambda t:logistic(t,100,.05,p),0,70)) for p in [20,40,60,80,120,140]])
v4=euler(lambda t,p:.0015*p*(1-p/6000),0,1000,1,50)[-1][1];ex4=logistic(50,6000,.0015,1000)
add(4,'수용력 '+M(r'M=6000')+', 연 성장계수 '+M(r'k=0.0015')+'의 (a) 방정식, (b) 방향장, (c) '+M(r'P_0=1000,2000,4000,8000')+'인 해와 오목성, (d) 초기값 천과 '+M(r'h=1')+'의 오십 년 오일러값, (e) 정확해와 비교, (f) 해의 그래프를 구하라.','With capacity '+M(r'M=6000')+' and annual coefficient '+M(r'k=0.0015')+', find (a) the equation, (b) field, (c) curves and concavity for '+M(r'P_0=1000,2000,4000,8000')+', (d) the fifty-year Euler estimate from one thousand with '+M(r'h=1')+', (e) the exact solution and comparison, and (f) its graph.',[(M(r'P^{\prime}=0.0015P(1-P/6000)')+'은 수용력 아래에서 증가하고 위에서 감소한다. 삼천에서 변곡하며 초기값 천과 이천은 이를 향해 처음 위로 볼록하게 증가한다.',M(r'P^{\prime}=0.0015P(1-P/6000)')+' increases below capacity and decreases above it. Inflection occurs at three thousand; the one-thousand and two-thousand curves start convex.'),('초기값 사천은 아래로 오목하며 팔천은 위로 볼록하게 감소한다. 오일러 갱신은 '+M(r'P_{n+1}=P_n+0.0015P_n(1-P_n/6000)')+'.','The four-thousand curve is concave down; the eight-thousand curve decreases convexly. Euler updates use '+M(r'P_{n+1}=P_n+0.0015P_n(1-P_n/6000)')+'.')],M(rf'P(t)=6000/(1+5e^{{-0.0015t}});\quad P_E(50)={v4:.6f};\quad P(50)={ex4:.6f};\quad E={ex4-v4:.6f}'),M(rf'P(t)=6000/(1+5e^{{-0.0015t}});\quad P_E(50)={v4:.6f};\quad P(50)={ex4:.6f};\quad E={ex4-v4:.6f}'),'변곡점은 인구 증가율이 최대인 지점이다. 오십 년 구간에서는 초기값 천의 해가 위로 볼록하여 오일러 값은 과소이다.','An inflection marks maximal growth rate. The solution from one thousand remains convex over fifty years, so Euler underestimates.','abcdef')
svg(4,'Capacity 6000; time in years',lambda t,p:.0015*p*(1-p/6000),(0,2500),(0,8500),[(f'P0={p}',sampled(lambda t:logistic(t,6000,.0015,p),0,2500)) for p in [1000,2000,4000,8000]])
add(5,'물고기 생체량이 '+M(r'y^{\prime}=0.71y(1-y/(8\times10^7)),\quad y(0)=2\times10^7')+'을 따른다. (a) 일 년 뒤 질량과 (b) '+M(r'4\times10^7')+'킬로그램까지의 시간을 구하라.','Fish biomass satisfies '+M(r'y^{\prime}=0.71y(1-y/(8\times10^7)),\quad y(0)=2\times10^7')+'. Find (a) mass after one year and (b) time to '+M(r'4\times10^7')+' kilograms.',[(M(r'y=8\times10^7/(1+3e^{-0.71t})')+'에 시간을 넣는다.',M(r'y=8\times10^7/(1+3e^{-0.71t})')+' gives the requested mass.'),('수용력의 절반에서는 분모가 이이므로 '+M(r'3e^{-0.71t}=1')+'.','At half-capacity the denominator is two, giving '+M(r'3e^{-0.71t}=1')+'.')],M(rf'y(1)\approx{logistic(1,8e7,.71,2e7):.2f}\ \mathrm{{kg}};\quad t=\ln3/0.71\approx{math.log(3)/.71:.6f}\ \mathrm{{yr}}'),M(rf'y(1)\approx{logistic(1,8e7,.71,2e7):.2f}\ \mathrm{{kg}};\quad t=\ln3/0.71\approx{math.log(3)/.71:.6f}\ \mathrm{{yr}}'),'질량이 증가하여 수용력 아래에 머무는지 확인했다.','The biomass increases and remains below capacity.','ab')
add(6,M(r"P'=0.4P-0.001P^2,\ P(0)=50")+'의 (a) 수용력, (b) 초기 증가율, (c) 수용력 절반까지의 시간을 구하라.','For '+M(r"P'=0.4P-0.001P^2,\ P(0)=50")+', find (a) capacity, (b) initial growth rate, and (c) time to half capacity.',[(M(r'M=0.4/0.001=400,\quad P^{\prime}(0)=0.4(50)-0.001(50)^2')+'.',M(r'M=0.4/0.001=400,\quad P^{\prime}(0)=0.4(50)-0.001(50)^2')+'.'),(M(r'P=400/(1+7e^{-0.4t})')+'에서 인구 이백을 대입한다.',M(r'P=400/(1+7e^{-0.4t})')+' is set equal to two hundred.')],M(r'M=400;\quad P^{\prime}(0)=17.5;\quad t=\ln7/0.4\approx4.864775\ \mathrm{yr}'),M(r'M=400;\quad P^{\prime}(0)=17.5;\quad t=\ln7/0.4\approx4.864775\ \mathrm{yr}'),'계수와 초기 증가율을 원래 식으로 직접 대조했다.','Coefficients and initial rate were checked in the original equation.','abc')
add(7,'로지스틱 인구의 초기값은 천, 수용력은 만이고 일 년 뒤 이천오백이다. 그 뒤 삼 년 더 지났을 때 인구를 구하라.','A logistic population starts at one thousand, has capacity ten thousand, and reaches 2,500 after one year. Find the population three additional years later.',[(M(r'P=10000/(1+9e^{-kt}),\quad P(1)=2500\Rightarrow e^{-k}=1/3')+'.',M(r'P=10000/(1+9e^{-kt}),\quad P(1)=2500\Rightarrow e^{-k}=1/3')+'.'),('요구 시점은 시작 후 사 년이다.','The requested time is four years from the start.')],M(r'P(4)=10000/(1+9/81)=9000'),M(r'P(4)=10000/(1+9/81)=9000'),'일 년 값과 사 년 값을 같은 해에 대입하여 시간 기준을 확인했다.','Substitution at years one and four checks the time origin.')
def scatter(n,data,xlim,ylim):
 p=BASE/f'exercise-content/assets/s9-4-{n}.svg';s=p.read_text();dots=''.join(f'<circle cx="{50+(x-xlim[0])/(xlim[1]-xlim[0])*620:.2f}" cy="{365-(y-ylim[0])/(ylim[1]-ylim[0])*310:.2f}" r="3.5" fill="#172b4d"/>' for x,y in data);p.write_text(s.replace('</svg>',dots+'</svg>'))
yeast=list(zip(range(0,20,2),[18,39,80,171,336,509,597,640,664,672]));rate8=math.log(39/18)/2;K8=680
m8=rf'P_E(t)=18e^{{{rate8:.9f}t}};\quad P_L(t)=680/(1+(662/18)e^{{-{rate8:.9f}t}})'
table8=r'\begin{array}{r|r|r|r}t&\mathrm{observed}&P_E&P_L\\'+r'\\'.join(f'{t}&{y}&{18*math.exp(rate8*t):.2f}&{logistic(t,K8,rate8,18):.2f}' for t,y in yeast)+r'\end{array}'
data8=M(r'\begin{array}{c|rrrrrrrrrr}t&0&2&4&6&8&10&12&14&16&18\\P&18&39&80&171&336&509&597&640&664&672\end{array}')
add(8,'효모 관측 '+data8+'에서 (a) 산점도와 수용력, (b) 초기 상대성장률, (c) 지수·로지스틱 모델, (d) 표·그래프 비교, (e) 칠 시간 값을 구하라.','For yeast observations '+data8+', find (a) a scatter plot and capacity estimate, (b) initial relative growth, (c) exponential and logistic models, (d) a table and plot comparison, and (e) the seven-hour estimate.', [('마지막 값들이 약 육백팔십에 가까워지므로 이를 수용력으로 추정한다. 첫 두 관측의 로그 비를 시간차로 나눈 평균 상대성장률을 초기값의 추정으로 사용한다.','The last values approach about 680, used as the estimated capacity. The log ratio of the first two observations divided by elapsed time estimates the initial relative growth rate.'),(M(rf'k\approx\ln(39/18)/2={rate8:.9f}')+'. 이 추정 선택에 따라 모델은 유일하지 않다. '+M(table8),M(rf'k\approx\ln(39/18)/2={rate8:.9f}')+'. Models are not unique because this is an estimation choice. '+M(table8))],M(m8)+ '; '+M(rf'P_L(7)\approx{logistic(7,K8,rate8,18):.6f}'),M(m8)+ '; '+M(rf'P_L(7)\approx{logistic(7,K8,rate8,18):.6f}'),'지수모델은 후반에 크게 과대예측한다. 이 초기 성장률 기반 로지스틱은 중반을 과소예측하지만 포화 현상을 표현한다. 모든 점 회귀를 한 결과로 오인하지 않아야 한다.','The exponential greatly overpredicts later values. This initial-rate logistic model underpredicts midrange growth but captures saturation; it is not an all-data regression.','abcde')
svg(8,'Yeast: observations and initial-rate models',None,(0,18),(0,900),[('exponential',sampled(lambda t:18*math.exp(rate8*t),0,18)),('logistic',sampled(lambda t:logistic(t,K8,rate8,18),0,18))]);scatter(8,yeast,(0,18),(0,900))
k9=.020/6.1;A9=20/6.1-1
ans9=rf'P^{{\prime}}={k9:.9f}P(1-P/20),\quad P(t)=20/(1+({A9:.9f})e^{{-{k9:.9f}t}});\quad P(10)={logistic(10,20,k9,6.1):.6f},\ P(100)={logistic(100,20,k9,6.1):.6f},\ P(500)={logistic(500,20,k9,6.1):.6f}'
add(9,'주어진 교재 자료에서 이천 년 인구는 육십일 억, 연 출생은 삼천오백만–사천만, 사망은 천오백만–이천만이다. 수용력 이백억으로 (a) 로지스틱 모델, (b) 이천십 년 추정과 관측 육십구 억 비교, (c) 이천백·이천오백 년 예측을 구하라.','Using the supplied textbook data, population in 2000 is 6.1 billion, annual births 35–40 million and deaths 15–20 million. With capacity twenty billion, find (a) a logistic model, (b) a 2010 estimate versus the stated 6.9 billion, and (c) predictions for 2100 and 2500.', [('출생과 사망 범위의 중간값 차이인 연 이천만을 사용한다. 시간은 이천 년부터의 연수, 인구는 십억 단위이다. 문제의 제안대로 순증가 상대율을 성장계수로 근사한다.','Use the difference of range midpoints, twenty million yearly. Time is years since 2000 and population is in billions. Following the question’s approximation, use the net relative increase as the logistic coefficient.'),(M(r'k\approx(0.0375-0.0175)/6.1')+'를 표준해에 대입한다. 주어진 낮은 출생·사망 자료 때문에 이천십 년 관측을 상당히 과소예측한다.',M(r'k\approx(0.0375-0.0175)/6.1')+' is inserted into the standard solution. The supplied low vital-rate data substantially underpredict the stated 2010 observation.')],M(ans9),M(ans9),'관측 및 예측은 교재에 주어진 역사적 숫자로 계산한 모델 결과이며 현재의 인구 자료를 대체하지 않는다. 초기 증가율 근사는 정확한 보정과 구별했다.','These are model calculations from the supplied historical figures. The approximate growth coefficient is distinguished from exact initial-rate calibration.','abc')
k10=math.log((800/282-1)/(800/309-1))/10;t500=math.log((800/282-1)/(800/500-1))/k10
add(10,'미국 인구 단위를 백만으로 두고 수용력 팔백, 이천 년 이백팔십이, 이천십 년 삼백구를 사용한다. (a) 모델, (b) 성장계수, (c) 이천백·이천이백 년 인구, (d) 오억 명을 넘는 연도를 구하라.','Use US population in millions with capacity eight hundred, 282 in 2000 and 309 in 2010. Find (a) the model, (b) the growth coefficient, (c) populations in 2100 and 2200, and (d) the year it exceeds five hundred million.',[(M(r'P(t)=800/(1+(518/282)e^{-kt})')+'에 십 년 관측을 넣는다.',M(r'P(t)=800/(1+(518/282)e^{-kt})')+' is fitted to the ten-year observation.'),(M(r'k=\tfrac1{10}\ln\frac{(800/282-1)}{(800/309-1)}')+'을 사용해 원하는 시간과 인구를 계산한다.',M(r'k=\tfrac1{10}\ln\frac{(800/282-1)}{(800/309-1)}')+' gives the requested values and threshold time.')],M(rf'k={k10:.9f};\quad P(100)={logistic(100,800,k10,282):.6f};\quad P(200)={logistic(200,800,k10,282):.6f};\quad\mathrm{{year}}=2000+{t500:.6f}={2000+t500:.6f}'),M(rf'k={k10:.9f};\quad P(100)={logistic(100,800,k10,282):.6f};\quad P(200)={logistic(200,800,k10,282):.6f};\quad\mathrm{{year}}=2000+{t500:.6f}={2000+t500:.6f}'),'모델에 이천 년과 이천십 년을 넣으면 두 관측을 정확히 복원한다.','Substituting 2000 and 2010 recovers both observations exactly.','abcd')
k11=math.log(11.5)/4;time11=math.log(11.5*9)/k11
add(11,'소문 확산률이 들은 비율과 못 들은 비율의 곱에 비례한다. (a) 식, (b) 해를 구하라. (c) 천 명 마을에서 오전 여덟 시 팔십 명, 정오 오백 명이 들었다면 구백 명에 도달하는 시간을 구하라.','Rumor spread is proportional to the product of aware and unaware fractions. Find (a) the equation and (b) its solution. (c) In a town of one thousand, eighty people know at 8 am and five hundred at noon. When do nine hundred know?', [(M(r'y^{\prime}=ky(1-y),\quad y=1/(1+Ae^{-kt})')+'이고 초기 비율로 '+M(r'A=11.5')+'.',M(r'y^{\prime}=ky(1-y),\quad y=1/(1+Ae^{-kt})')+' and the initial fraction give '+M(r'A=11.5')+'.'),('정오 조건으로 '+M(r'k=\ln(11.5)/4')+'이며 구십 퍼센트 조건의 분모는 십분의 구의 역수이다.','The noon condition gives '+M(r'k=\ln(11.5)/4')+'; the ninety-percent condition fixes the denominator.')],M(rf't_{{90}}=\ln(103.5)/k\approx{time11:.6f}\ \mathrm{{hours\ after\ 8\ am}}')+'; 오후 약 세 시 삼십육 분.',M(rf't_{{90}}=\ln(103.5)/k\approx{time11:.6f}\ \mathrm{{hours\ after\ 8\ am}}')+'; approximately 3:36 pm.','영과 일의 상수해도 방정식의 해이다. 초기·정오 비율을 대입 검사했다.','Zero and one are also constant solutions. The initial and noon fractions were checked.','abc')
k12=math.log(36/11);t12=math.log(24)/k12
add(12,'호수에 물고기 사백 마리를 넣었고 수용력은 만 마리이다. 첫해에 세 배가 되었다. (a) 로지스틱 인구식과 (b) 오천 마리까지 걸리는 시간을 구하라.','A lake starts with four hundred fish, has capacity ten thousand, and triples its fish population in the first year. Find (a) the logistic population and (b) time to five thousand.',[(M(r'P=10000/(1+24e^{-kt})')+'에 일 년 뒤 천이백을 대입한다.',M(r'P=10000/(1+24e^{-kt})')+' is fitted to twelve hundred after one year.'),(M(r'e^{-k}=11/36')+'이고 절반 수용력에서는 '+M(r'24e^{-kt}=1')+'.',M(r'e^{-k}=11/36')+' and half capacity requires '+M(r'24e^{-kt}=1')+'.')],M(rf'P(t)=\frac{{10000}}{{1+24(11/36)^t}};\quad t=\frac{{\ln24}}{{\ln(36/11)}}\approx{t12:.6f}\ \mathrm{{yr}}'),M(rf'P(t)=\frac{{10000}}{{1+24(11/36)^t}};\quad t=\frac{{\ln24}}{{\ln(36/11)}}\approx{t12:.6f}\ \mathrm{{yr}}'),'첫해의 세 배 조건과 절반 수용력 조건을 각각 검증했다.','The first-year tripling and half-capacity conditions both check.','ab')
add(13,'로지스틱식 '+M(r'P^{\prime}=kP(1-P/M)')+'에서 (a) 이계 도함수를 구하고 (b) 증가율이 최대인 인구를 증명하라.','For '+M(r'P^{\prime}=kP(1-P/M)')+', (a) derive its second derivative and (b) prove the population of maximal growth.',[(M(r'P^{\prime\prime}=kP^{\prime}(1-2P/M)')+'에 원래 식을 넣는다.',M(r'P^{\prime\prime}=kP^{\prime}(1-2P/M)')+' uses the original equation.'),('성장 구간에서 앞의 인자는 양수이고 마지막 인자만 수용력 절반에서 부호를 바꾼다.','On the growing interval the first factors are positive; the last changes sign at half capacity.')],M(r'P^{\prime\prime}=k^2P(1-P/M)(1-2P/M);\quad P_{fast}=M/2,\quad P^{\prime}_{max}=kM/4'),M(r'P^{\prime\prime}=k^2P(1-P/M)(1-2P/M);\quad P_{fast}=M/2,\quad P^{\prime}_{max}=kM/4'),'증가율을 인구의 이차함수로 보고 꼭짓점을 구해도 같은 결과이다.','The vertex of growth rate as a quadratic in population gives the same result.','ab')
add(14,'수용력을 십으로 고정한 '+M(r'P(t)=10/[1+(10/P_0-1)e^{-kt}]')+'에서 초기값과 성장계수를 바꾸어 여러 곡선을 그리고 효과를 설명하라.','With fixed capacity ten, plot '+M(r'P(t)=10/[1+(10/P_0-1)e^{-kt}]')+' for different initial values and growth coefficients and describe their effects.', [('같은 양의 성장계수에서 초기값이 큰 곡선은 다른 곡선보다 위에 있으며 모든 양의 초기값은 수용력에 접근한다.','For a fixed positive growth coefficient, larger initial values produce higher curves; all positive initial values approach capacity.'),('성장계수를 키우면 시간축을 압축하여 평형에 더 빨리 접근한다. 수용력 아래 곡선의 변곡 시간은 '+M(r't_i=\ln(10/P_0-1)/k')+'.','Increasing the coefficient compresses time and speeds convergence. For a below-capacity curve the inflection time is '+M(r't_i=\ln(10/P_0-1)/k')+'.')],'초기값은 시작 높이와 변곡 시점을, 성장계수는 시간 척도를 바꾼다.','The initial value changes starting height and inflection time; the coefficient changes the time scale.','수용력 이상에서 시작하면 감소하므로 동일한 증가곡선 설명을 적용하지 않는다.','Curves starting above capacity decrease, so the growing-curve description does not apply there.')
svg(14,'Changing initial value and growth coefficient',None,(0,12),(0,13),[(f'P0={p}, k={k}',sampled(lambda t:logistic(t,10,k,p),0,12)) for p,k in [(1,.5),(3,.5),(7,.5),(12,.5),(1,.25),(1,1)]])
def nelder(fn,start,step=.2):
 n=len(start);simp=[start[:]]+[[v+(step if i==j else 0) for i,v in enumerate(start)] for j in range(n)]
 for _ in range(2500):
  simp.sort(key=fn);fs=[fn(p) for p in simp]
  if max(abs(a-b) for a,b in zip(simp[0],simp[-1]))<1e-10:break
  c=[sum(p[i] for p in simp[:-1])/n for i in range(n)];worst=simp[-1];r=[2*c[i]-worst[i] for i in range(n)];fr=fn(r)
  if fr<fs[0]:
   e=[3*c[i]-2*worst[i] for i in range(n)];simp[-1]=e if fn(e)<fr else r
  elif fr<fs[-2]:simp[-1]=r
  else:
   target=r if fr<fs[-1] else worst;q=[(c[i]+target[i])/2 for i in range(n)]
   if fn(q)<min(fr,fs[-1]):simp[-1]=q
   else:simp=[simp[0]]+[[.5*(p[i]+simp[0][i]) for i in range(n)] for p in simp[1:]]
 return min(simp,key=fn)
def fit(data,start,kind='logistic'):
 def pred(q,t):
  try:
   pars=[math.exp(v) for v in q]
   return pars[0]/(1+pars[1]*math.exp(-pars[2]*t)) if kind=='logistic' else pars[0]*math.exp(pars[1]*t)
  except OverflowError:return 1e200
 def loss(q):
  try:return sum((pred(q,t)-y)**2 for t,y in data)
  except OverflowError:return 1e300
 q=nelder(loss,[math.log(v) for v in start]);q2=nelder(loss,[v+.1 for v in q]);assert abs(loss(q)-loss(q2))<1e-4
 return [math.exp(v) for v in q],math.sqrt(loss(q)/len(data))
data15=list(zip(range(0,50,5),[955,1007,1091,1189,1255,1264,1252,1237,1227,1222]));pars15,rm15=fit([(t,y-900) for t,y in data15],[340,6,.2]);K15,A15,k15=pars15
fmt15=rf'P(t)=900+\frac{{{K15:.6f}}}{{1+{A15:.6f}e^{{-{k15:.9f}t}}}}'
tbl15=M(r'\begin{array}{c|rrrrrrrrrr}t&0&5&10&15&20&25&30&35&40&45\\P&955&1007&1091&1189&1255&1264&1252&1237&1227&1222\end{array}')
add(15,'트리니다드 토바고의 천 명 단위 자료 '+tbl15+'에서 (a) 산점도, (b) 구백을 뺀 값의 로지스틱 회귀, (c) 다시 구백을 더한 모델·그래프·정확도, (d) 조건부 장기 예측을 구하라. 시간 영은 천구백칠십 년이다.','For Trinidad and Tobago data in thousands '+tbl15+', find (a) a scatter plot, (b) logistic regression after subtracting nine hundred, (c) the shifted-back model, graph and fit, and (d) its conditional long-term prediction. Time zero is 1970.', [('이동한 관측값에 대해 원래 인구 척도의 잔차 제곱합을 최소화하는 세 매개변수 로지스틱 회귀를 수행한다.','Fit a three-parameter logistic by minimizing squared residuals on the population scale after shifting the data.'),('초기 증가와 포화를 대략 표현하지만 후반 관측의 감소는 단조 증가 로지스틱으로 재현할 수 없다.','The curve approximates early growth and saturation but cannot reproduce the later observed decline with a monotone logistic.')],M(fmt15)+ '; '+M(rf'\mathrm{{RMSE}}={rm15:.6f};\quad\lim P=900+{K15:.6f}={900+K15:.6f}\ \mathrm{{thousand}}'),M(fmt15)+ '; '+M(rf'\mathrm{{RMSE}}={rm15:.6f};\quad\lim P=900+{K15:.6f}={900+K15:.6f}\ \mathrm{{thousand}}'),'다른 초기 매개변수로 다시 최적화해 같은 잔차 최소값을 확인했다. 미래 해석은 모델이 계속 유효하다는 가정에 따른다.','A different optimizer start confirms the same residual minimum. Extrapolation is conditional on continued model validity.','abcd')
svg(15,'Shifted logistic regression; observations are dots',None,(0,55),(900,1300),[('shifted logistic',sampled(lambda t:900+K15/(1+A15*math.exp(-k15*t)),0,55))]);scatter(15,data15,(0,55),(900,1300))
data16=list(zip([i/2 for i in range(14)],[30,49,68,101,138,167,204,232,255,284,302,307,310,317]));pars16,rm16=fit(data16,[335,10,.9]);pe16,re16=fit(data16,[60,.3],'exponential');K16,A16,k16=pars16;B16,r16=pe16
st16=M(r'\begin{array}{c|rrrrrrr}t&0&0.5&1&1.5&2&2.5&3\\P&30&49&68&101&138&167&204\\t&3.5&4&4.5&5&5.5&6&6.5\\P&232&255&284&302&307&310&317\end{array}')
add(16,'이천십 년부터의 연수와 트위터 사용자 백만 단위 자료 '+st16+'에 지수·로지스틱 모델을 적합하고 산점도와 함께 그려 적합도를 논하라.','Fit exponential and logistic models to years since 2010 and Twitter users in millions '+st16+'. Plot both with observations and compare fit.', [('두 모델 모두 관측 사용자 수 척도에서 잔차 제곱합을 최소화했다. 로그 척도 회귀와는 다른 기준임을 명시한다.','Both fits minimize squared residuals on the observed user-count scale, explicitly distinct from regression on logarithms.'),('지수모델은 포화와 증가율 감소를 표현하지 못한다. 로지스틱은 두 특징을 반영하여 잔차가 훨씬 작다.','The exponential cannot capture saturation and slowing growth. The logistic captures both and has much smaller residuals.')],M(rf'P_E={B16:.6f}e^{{{r16:.9f}t}},\quad\mathrm{{RMSE}}_E={re16:.6f};\quad P_L=\frac{{{K16:.6f}}}{{1+{A16:.6f}e^{{-{k16:.9f}t}}}},\quad\mathrm{{RMSE}}_L={rm16:.6f}'),M(rf'P_E={B16:.6f}e^{{{r16:.9f}t}},\quad\mathrm{{RMSE}}_E={re16:.6f};\quad P_L=\frac{{{K16:.6f}}}{{1+{A16:.6f}e^{{-{k16:.9f}t}}}},\quad\mathrm{{RMSE}}_L={rm16:.6f}'),'두 회귀를 다른 시작값으로 재검산했다. 여기서는 주어진 과거 자료의 적합만 평가한다.','Both regressions were checked from different starts; this assesses fit to the supplied historical data.')
svg(16,'Original-scale least-squares fits',None,(0,6.5),(0,450),[('exponential',sampled(lambda t:B16*math.exp(r16*t),0,6.5)),('logistic',sampled(lambda t:K16/(1+A16*math.exp(-k16*t)),0,6.5))]);scatter(16,data16,(0,6.5),(0,450))
add(17,M(r'P^{\prime}=kP-m,\quad k=\alpha-\beta>0,\quad P(0)=P_0')+'에서 (a) 해, (b) 증가 조건, (c) 일정·감소 조건을 구하라. (d) 천팔백사십칠 년 아일랜드의 인구 팔백만, 순상대증가율 연 일점육 퍼센트, 연 이민 이십일만을 대입하라.','For '+M(r'P^{\prime}=kP-m,\quad k=\alpha-\beta>0,\quad P(0)=P_0')+', find (a) the solution, (b) growth conditions, and (c) constant or declining cases. (d) Apply population eight million, annual net relative growth 1.6 percent, and emigration 210,000 for Ireland in 1847.', [('평형 인구를 빼면 '+M(r'(P-m/k)^{\prime}=k(P-m/k)')+'가 된다.','Subtract the equilibrium to get '+M(r'(P-m/k)^{\prime}=k(P-m/k)')+'.'),('초기 평형 차이의 부호가 성장 여부를 결정한다. 사례에서는 자연 순증가 십이만팔천보다 이민이 많다.','The initial difference from equilibrium determines growth. In the example, emigration exceeds the natural net increase of 128,000.')],M(r'P=m/k+(P_0-m/k)e^{kt};\quad m<kP_0:\ \text{growth};\ m=kP_0:\ \text{constant};\ m>kP_0:\ \text{decline};\quad P^{\prime}(0)=-82000\ \mathrm{yr}^{-1}'),M(r'P=m/k+(P_0-m/k)e^{kt};\quad m<kP_0:\ \text{growth};\ m=kP_0:\ \text{constant};\ m>kP_0:\ \text{decline};\quad P^{\prime}(0)=-82000\ \mathrm{yr}^{-1}'),'감소 모델은 인구가 영에 도달할 때까지 물리적으로 사용한다. 음의 인구로의 형식적 연장은 인구 해석이 없다.','The declining model is physically used only until population reaches zero; formal negative values have no population interpretation.','abcd')
T18=3/(1-8**(-.01));k18=(2**(-.01)-16**(-.01))/.03
add(18,M(r'y^{\prime}=ky^{1+c},\quad k,c>0,\quad y(0)=y_0>0')+'에서 (a) 해, (b) 유한 폭주시간을 구하라. (c) 지수 일점영일, 처음 두 마리, 삼 개월 뒤 열여섯 마리인 토끼 모델의 폭주시간을 구하라.','For '+M(r'y^{\prime}=ky^{1+c},\quad k,c>0,\quad y(0)=y_0>0')+', find (a) the solution and (b) finite blow-up time. (c) Use exponent 1.01, two rabbits initially, and sixteen after three months.',[(M(r'\int y^{-1-c}\,dy=kt+C\Rightarrow y^{-c}=y_0^{-c}-ckt')+'.',M(r'\int y^{-1-c}\,dy=kt+C\Rightarrow y^{-c}=y_0^{-c}-ckt')+'.'),('괄호가 처음 영이 되는 시간이 유한하고 양수이다. 관측값의 음의 지수 차이로 계수를 정한다.','The bracket first vanishes at a finite positive time. The difference of negative powers of the observed populations determines the coefficient.')],M(rf'y=(y_0^{{-c}}-ckt)^{{-1/c}},\quad T=y_0^{{-c}}/(ck);\quad T_{{rabbit}}=3/(1-8^{{-0.01}})\approx{T18:.6f}\ \mathrm{{months}}'),M(rf'y=(y_0^{{-c}}-ckt)^{{-1/c}},\quad T=y_0^{{-c}}/(ck);\quad T_{{rabbit}}=3/(1-8^{{-0.01}})\approx{T18:.6f}\ \mathrm{{months}}'),'폭주는 수학적 모델의 예측으로 해당 시간 왼쪽에서만 해가 유한하다.','Blow-up is the mathematical model’s prediction; the finite solution is defined only before that time.','abc')
add(19,'어획 모델 '+M(r'P^{\prime}=0.08P(1-P/1000)-15')+'의 (a) 마지막 항 의미, (b) 방향장, (c) 평형, (d) 초기값별 해의 거동, (e) 초기 인구 이백·삼백의 정확해와 그래프를 구하라. 시간 단위는 주이다.','For the harvesting model '+M(r'P^{\prime}=0.08P(1-P/1000)-15')+', find (a) the final term’s meaning, (b) field, (c) equilibria, (d) behavior by initial population, and (e) exact curves from two hundred and three hundred. Time is in weeks.', [('마지막 항은 매주 열다섯 마리를 제거한다는 뜻이다. '+M(r'P^{\prime}=-0.00008(P-250)(P-750)')+'이므로 이백오십이 불안정, 칠백오십이 안정 평형이다.','The last term removes fifteen fish each week. '+M(r'P^{\prime}=-0.00008(P-250)(P-750)')+' makes 250 unstable and 750 stable.'),('이백오십보다 적으면 감소하여 영에 도달한다. 이백오십과 칠백오십 사이에서는 증가하고, 칠백오십 위에서는 감소하여 칠백오십으로 간다.','Below 250 the population falls to zero. Between 250 and 750 it grows; above 750 it declines toward 750.'),(M(r'\frac{P-750}{P-250}=Ae^{-0.04t},\quad A=\frac{P_0-750}{P_0-250}')+'를 부분분수로 얻는다.',M(r'\frac{P-750}{P-250}=Ae^{-0.04t},\quad A=\frac{P_0-750}{P_0-250}')+' follows from partial fractions.')],M(r'P_{200}=\frac{750-2750e^{-0.04t}}{1-11e^{-0.04t}};\quad P_{300}=\frac{750+2250e^{-0.04t}}{1+9e^{-0.04t}};\quad t_{ext}=25\ln(11/3)\approx32.4821\ \mathrm{weeks}'),M(r'P_{200}=\frac{750-2750e^{-0.04t}}{1-11e^{-0.04t}};\quad P_{300}=\frac{750+2250e^{-0.04t}}{1+9e^{-0.04t}};\quad t_{ext}=25\ln(11/3)\approx32.4821\ \mathrm{weeks}'),'첫 해는 영에 도달하는 때까지만 인구로 해석한다. 상수해 두 개도 따로 포함한다.','The first solution is a population only until it reaches zero. Both constant solutions are included separately.','abcde')
def harvest(t,p):
 if p in [250,750]:return p
 A=(p-750)/(p-250);val=(750-250*A*math.exp(-.04*t))/(1-A*math.exp(-.04*t));return val if val>=0 and (p>250 or t<=25*math.log(A/3)) else math.nan
svg(19,'Harvest 15/week: threshold 250, stable level 750',lambda t,p:.08*p*(1-p/1000)-15,(0,120),(0,1050),[(f'P0={p}',sampled(lambda t:harvest(t,p),0,120)) for p in [200,250,300,600,750,1000]])
add(20,M(r'P^{\prime}=0.08P(1-P/1000)-c,\quad c\ge0')+'에서 (a) 여러 어획률의 방향장을 그리고 (b) 평형 존재·멸종 조건, (c) 대수적 증명, (d) 지속 가능한 주간 어획 상한의 의미를 설명하라.','For '+M(r'P^{\prime}=0.08P(1-P/1000)-c,\quad c\ge0')+', (a) plot fields for several harvest rates, (b) classify equilibria and extinction, (c) prove the classification, and (d) explain a sustainable weekly catch limit.',[(M(r'P^{\prime}=20-c-0.00008(P-500)^2')+'로 완전제곱한다. 어획률 이십을 넘으면 항상 음수이다.',M(r'P^{\prime}=20-c-0.00008(P-500)^2')+' completes the square. Above twenty the rate is always negative.'),('이십보다 작으면 두 평형 사이에서 증가하고 아래 평형보다 적으면 멸종한다. 이십에서는 오백 이상으로 시작해야 영에 이르지 않는다.','Below twenty, growth occurs between the equilibria and populations below the lower threshold die out. At twenty, only populations starting at least five hundred avoid extinction.')],M(r'0\le c\le20:\quad P_\pm=500\pm\sqrt{(20-c)/0.00008};\quad c>20:\ \text{all positive initial populations die out}')+'; 이십보다 낮게 제한하고 낮은 평형보다 충분히 높은 개체수를 유지해야 한다.',M(r'0\le c\le20:\quad P_\pm=500\pm\sqrt{(20-c)/0.00008};\quad c>20:\ \text{all positive initial populations die out}')+'; keep catch below twenty and the stock safely above the lower equilibrium.','이십은 이상화 모델의 최대 지속 생산량이며 모든 초기 개체수를 보호하는 보장은 아니다.','Twenty is the idealized maximum sustainable yield, not a guarantee for every initial stock.','abcd')
# Separate field panels in one SVG, preserving the common source and axes.
svg(20,'Fields for catch c=0,15,20,25 (see panel labels)',None,(0,60),(0,1000),[])
p20=BASE/'exercise-content/assets/s9-4-20.svg';parts=[]
for c in [0,15,20,25]:
 svg(20,f'Harvest c={c}',lambda t,p:.08*p*(1-p/1000)-c,(0,60),(0,1000),[]);s=p20.read_text();parts.append(s[s.index('>')+1:s.rindex('</svg>')])
p20.write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 1740">'+''.join(f'<g transform="translate(0,{435*i})">{s}</g>' for i,s in enumerate(parts))+'</svg>')
add(21,'최소 생존 개체수 모델 '+M(r'P^{\prime}=kP(1-P/M)(1-m/P),\quad0<m<M')+'에서 (a) 증감을 보이고 (b) '+M(r'k=0.08,M=1000,m=200')+'의 방향장·평형·해를 그려라. (c) 일반 초기값 해를 구하고 (d) 최소값 아래의 유한시간 멸종을 증명하라.','For the threshold model '+M(r'P^{\prime}=kP(1-P/M)(1-m/P),\quad0<m<M')+', (a) prove monotonicity; (b) plot the field, equilibria and curves for '+M(r'k=0.08,M=1000,m=200')+'; (c) solve for a general initial population; and (d) prove finite-time extinction below threshold.',[(M(r'P^{\prime}=\frac kM(M-P)(P-m)')+'이므로 두 평형 사이에서 증가하고 최소값 아래에서 감소한다.','Since '+M(r'P^{\prime}=\frac kM(M-P)(P-m)')+', populations increase between equilibria and decline below the lower threshold.'),(M(r'\lambda=k(M-m)/M,\quad A=(P_0-M)/(P_0-m),\quad(P-M)/(P-m)=Ae^{-\lambda t}')+'를 부분분수로 얻는다.',M(r'\lambda=k(M-m)/M,\quad A=(P_0-M)/(P_0-m),\quad(P-M)/(P-m)=Ae^{-\lambda t}')+' follows by partial fractions.'),('초기 인구가 최소값보다 작으면 분자가 양의 유한 시간에 영이 된다. 최소값보다 크면 최대 수용력으로 수렴한다.','Below threshold the numerator reaches zero at a finite positive time. Above threshold the population tends to carrying capacity.')],M(r'P=\frac{M-mAe^{-\lambda t}}{1-Ae^{-\lambda t}};\quad P\equiv m,M;\quad t_{ext}=\lambda^{-1}\ln\frac{m(M-P_0)}{M(m-P_0)}\quad(0<P_0<m)'),M(r'P=\frac{M-mAe^{-\lambda t}}{1-Ae^{-\lambda t}};\quad P\equiv m,M;\quad t_{ext}=\lambda^{-1}\ln\frac{m(M-P_0)}{M(m-P_0)}\quad(0<P_0<m)'),'원래 식은 인구 영에서 정의되지 않으므로 멸종 순간에 모델을 종료한다. 약분식의 음수 연장은 인구 해석이 없다.','The original equation is undefined at zero population, so the model ends at extinction. A negative extension of the canceled equation has no population interpretation.','abcd')
def threshold(t,p):
 if p in [200,1000]:return p
 A=(p-1000)/(p-200);lam=.064
 if p<200 and t>math.log(A/5)/lam:return math.nan
 return (1000-200*A*math.exp(-lam*t))/(1-A*math.exp(-lam*t))
svg(21,'Minimum viable population 200',lambda t,p:.08*(1-p/1000)*(p-200),(0,100),(0,1400),[(f'P0={p}',sampled(lambda t:threshold(t,p),0,100)) for p in [100,200,300,600,1000,1300]])
add(22,'Gompertz 모델 '+M(r'P^{\prime}=cP\ln(M/P),\quad P(0)=P_0>0,\ c>0')+'에서 (a) 해, (b) 극한, (c) '+M(r'M=1000,P_0=100,c=0.05')+'의 그래프와 교재 로지스틱 예제 비교, (d) 최대 증가율의 인구를 구하라.','For the Gompertz model '+M(r'P^{\prime}=cP\ln(M/P),\quad P(0)=P_0>0,\ c>0')+', find (a) the solution, (b) its limit, (c) a plot for '+M(r'M=1000,P_0=100,c=0.05')+' compared with the textbook logistic example, and (d) the population of maximal growth.',[(M(r'u=\ln(P/M),\quad u^{\prime}=-cu')+'를 풀어 초기값을 넣는다.',M(r'u=\ln(P/M),\quad u^{\prime}=-cu')+' is solved and fitted to the initial value.'),('증가율을 인구로 미분하면 '+M(r'c[\ln(M/P)-1]')+'이고 영점이 최대점이다. 두 모델 모두 에스자형으로 수용력에 접근하지만 변곡 높이가 다르다.','Differentiating the growth rate in population gives '+M(r'c[\ln(M/P)-1]')+'; its zero is the maximum. Both models approach capacity with sigmoid growth but differ in inflection height.')],M(r'P=M\exp[\ln(P_0/M)e^{-ct}],\quad\lim P=M;\quad P_{fast}=M/e'),M(r'P=M\exp[\ln(P_0/M)e^{-ct}],\quad\lim P=M;\quad P_{fast}=M/e'),'두 도함수와 초기조건을 직접 검사했다. 비교 로지스틱 예제는 수용력 천, 초기값 백, 성장계수 영점영팔이다.','Derivatives and the initial condition check directly. The comparison logistic example has capacity one thousand, initial value one hundred, and coefficient 0.08.','abcd')
svg(22,'Gompertz vs textbook logistic example',None,(0,100),(0,1050),[('Gompertz c=0.05',sampled(lambda t:1000*math.exp(math.log(.1)*math.exp(-.05*t)),0,100)),('logistic k=0.08',sampled(lambda t:logistic(t,1000,.08,100),0,100))])
add(23,M(r'P^{\prime}=kP\cos(rt-\phi),\quad P(0)=P_0>0,\ k,r,\phi>0')+'의 (a) 해와 (b) 매개변수별 그래프·장기 극한을 구하라.','For '+M(r'P^{\prime}=kP\cos(rt-\phi),\quad P(0)=P_0>0,\ k,r,\phi>0')+', find (a) the solution and (b) parameter-dependent plots and long-time behavior.',[(M(r'\ln(P/P_0)=\frac kr[\sin(rt-\phi)+\sin\phi]')+'을 적분으로 얻는다.',M(r'\ln(P/P_0)=\frac kr[\sin(rt-\phi)+\sin\phi]')+' follows by integration.'),('성장계수를 키우면 로그 진폭이 커진다. 주파수를 키우면 주기가 짧아지고 고정 성장계수에서 로그 진폭은 작아진다. 위상은 성장 시기를 옮기며 초기값 고정에 필요한 수직 계수에도 영향을 준다.','Increasing the growth coefficient enlarges log-amplitude. Increasing frequency shortens the period and reduces log-amplitude for fixed growth coefficient. Phase shifts growth timing and affects the scale needed to preserve the initial value.')],M(r'P=P_0\exp\{(k/r)[\sin(rt-\phi)+\sin\phi]\};\quad\mathrm{period}=2\pi/r')+'; 양의 비상수 주기함수여서 극한은 없다.',M(r'P=P_0\exp\{(k/r)[\sin(rt-\phi)+\sin\phi]\};\quad\mathrm{period}=2\pi/r')+'; the nonconstant positive periodic solution has no limit.','시간 영을 대입하면 위상항이 소거되어 초기값이 된다.','At time zero the phase terms cancel, recovering the initial value.','ab')
svg(23,'Seasonal growth: P0=1',None,(0,15),(0,8),[(f'k={k}, r={r}, phi={ph}',sampled(lambda t:math.exp(k/r*(math.sin(r*t-ph)+math.sin(ph))),0,15)) for k,r,ph in [(.5,1,.5),(1,1,.5),(.5,2,.5),(.5,1,1.5)]])
add(24,M(r'P^{\prime}=kP\cos^2(rt-\phi),\quad P(0)=P_0>0,\ k,r,\phi>0')+'의 (a) 해, (b) 매개변수 그래프와 장기 거동을 구하라.','For '+M(r'P^{\prime}=kP\cos^2(rt-\phi),\quad P(0)=P_0>0,\ k,r,\phi>0')+', find (a) the solution and (b) parameter-dependent plots and long-time behavior.',[(M(r'\cos^2u=(1+\cos2u)/2')+'를 적분에 쓴다.',M(r'\cos^2u=(1+\cos2u)/2')+' is used in the integral.'),('로그 성장의 평균은 성장계수의 절반이고 진동항은 유계이다. 성장계수는 평균 증가와 진폭을 함께 키우고 주파수는 주기와 진폭을 줄이며 위상은 완만한 구간의 시기를 바꾼다.','Mean logarithmic growth is half the growth coefficient and the oscillatory term is bounded. The growth coefficient increases mean growth and amplitude; frequency reduces period and amplitude; phase changes the timing of flatter portions.')],M(r'P=P_0\exp\left[\frac{kt}2+\frac{k}{4r}\{\sin(2rt-2\phi)+\sin2\phi\}\right],\quad\lim_{t\to\infty}P=\infty'),M(r'P=P_0\exp\left[\frac{kt}2+\frac{k}{4r}\{\sin(2rt-2\phi)+\sin2\phi\}\right],\quad\lim_{t\to\infty}P=\infty'),'도함수는 항상 음이 아니며 고립된 시점의 수평 접선에도 전체 함수는 엄격히 증가한다.','The derivative is nonnegative, and despite isolated horizontal tangents the solution is strictly increasing.','ab')
svg(24,'Squared seasonal growth: P0=1',None,(0,12),(0,30),[(f'k={k}, r={r}, phi={ph}',sampled(lambda t:math.exp(k*t/2+k/(4*r)*(math.sin(2*r*t-2*ph)+math.sin(2*ph))),0,12)) for k,r,ph in [(.3,1,.5),(.5,1,.5),(.3,2,.5),(.3,1,1.5)]])
add(25,'로지스틱 함수 '+M(r'P=M/(1+Ae^{-kt}),\quad A>0')+'를 평행이동·확대한 쌍곡탄젠트로 표현하라.','Express the logistic function '+M(r'P=M/(1+Ae^{-kt}),\quad A>0')+' as a shifted and scaled hyperbolic tangent.',[(M(r'1+\tanh u=2/(1+e^{-2u})')+'를 지수 정의에서 얻는다.',M(r'1+\tanh u=2/(1+e^{-2u})')+' follows from the exponential definition.'),(M(r'c=\ln A/k,\quad e^{-k(t-c)}=Ae^{-kt}')+'을 넣는다.',M(r'c=\ln A/k,\quad e^{-k(t-c)}=Ae^{-kt}')+' supplies the shift.')],M(r'P(t)=\frac M2\left[1+\tanh\left(\frac k2(t-c)\right)\right],\quad c=\frac{\ln A}{k}'),M(r'P(t)=\frac M2\left[1+\tanh\left(\frac k2(t-c)\right)\right],\quad c=\frac{\ln A}{k}'),'양의 상수 조건은 초기 인구가 양의 수용력보다 작은 에스자 성장 족을 뜻한다.','The positive constant describes the sigmoid family starting below positive carrying capacity.')
assert len(items)==25
raw=dict(section='9.4',source=dict(title='Calculus',edition='9',language='en',printedPages=[676,677,678,679],pdfPages=[713,714,715,716]),scope=dict(kind='exercise',numbers=list(range(1,26)),total=25,note=bi('전체 25문항과 모든 소문항.','All 25 exercises and every subpart.')),exercises=items)
p=BASE/'exercise-content/s9-4.json';p.write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n');sys.path.insert(0,str(BASE));import build_exercises as b;b.validate_document(raw,p)
print('9.4:25 cards,12 SVGs; regressions',pars15,rm15,pars16,rm16,pe16,re16)
print('11 time',time11,'19 extinction',25*math.log(11/3))
