import json,math,html,sys,ast
from pathlib import Path
BASE=Path(__file__).resolve().parents[1];items=[]
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':e if e is not None else k}
def add(n,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=684 if n<=33 else 685
 items.append(dict(id=f'stewart9-exercise-9.5-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('선형 미분방정식과 적분인자','Linear differential equations and integrating factors'),statement=bi(sk,se),hint=bi('표준형으로 정리하고 적분인자를 곱해 곱의 도함수를 만든다.','Put the equation in standard form and use an integrating factor to form a product derivative.'),steps={'ko':[x[0] for x in steps],'en':[x[1] for x in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
for n,eq,ans,k,e in [(1,r'y^{\prime}+x\sqrt y=x^2','nonlinear','미지함수의 제곱근이 들어가 선형이 아니다.','The square root of the unknown makes the equation nonlinear.'),(2,r'y^{\prime}-x=y\tan x',r'y^{\prime}-(\tan x)y=x','미지함수와 그 도함수가 일차이다.','The unknown and its derivative occur to the first power.'),(3,r'ue^t=t+\sqrt t\,u^{\prime}',r'u^{\prime}-\frac{e^t}{\sqrt t}u=-\sqrt t,\quad t>0','양의 시간에서 도함수의 계수로 나누면 표준형이 된다.','At positive time division by the derivative coefficient gives standard form.'),(4,r'R^{\prime}+t\cos R=e^{-t}','nonlinear','미지함수가 코사인 안에 들어가 선형이 아니다.','The cosine of the unknown makes the equation nonlinear.')]:
 add(n,M(eq)+'의 선형성을 판정하고 선형이면 표준형으로 쓰라.','Classify linearity of '+M(eq)+' and give standard form if linear.',[(k,e),('계수는 독립변수에만 의존해야 한다.','Coefficients may depend only on the independent variable.')],('비선형.' if ans=='nonlinear' else '선형: '+M(ans)),('Nonlinear.' if ans=='nonlinear' else 'Linear: '+M(ans)),'미지함수의 비선형 거듭제곱이나 함수 합성이 있는지 검사했다.','Checked for nonlinear powers or function compositions of the unknown.')
rows=[
(5,r'y^{\prime}+y=1',r'e^x',r'(e^xy)^{\prime}=e^x',r'y=1+Ce^{-x}','모든 실수에서 정의된다.','Defined on the whole real line.'),
(6,r'y^{\prime}-y=e^x',r'e^{-x}',r'(e^{-x}y)^{\prime}=1',r'y=(x+C)e^x','모든 실수에서 정의된다.','Defined on the whole real line.'),
(7,r'y^{\prime}=x-y',r'e^x',r'(e^xy)^{\prime}=xe^x',r'y=x-1+Ce^{-x}','부분적분으로 입력 곱 지수함수를 적분한다.','Integration by parts handles the input times the exponential.'),
(8,r'4x^3y+x^4y^{\prime}=\sin^3x',r'x^4',r'(x^4y)^{\prime}=\sin^3x',r'y=\frac{-\cos x+\frac13\cos^3x+C}{x^4},\quad x\ne0','분자의 적분상수 삼분의 이인 가지는 영에서 값 사분의 일로 매끄럽게 연장된다.','The branch with constant two thirds extends smoothly at zero with value one quarter.'),
(9,r'xy^{\prime}+y=\sqrt x',r'x',r'(xy)^{\prime}=\sqrt x',r'y=\frac23\sqrt x+\frac Cx,\quad x>0','실수 근호와 표준형이 양의 입력 구간을 요구한다.','The real radical and standard form require positive input.'),
(10,r'2xy^{\prime}+y=2\sqrt x',r'\sqrt x',r'(\sqrt x\,y)^{\prime}=1',r'y=\sqrt x+C/\sqrt x,\quad x>0','도함수의 계수를 먼저 나누고 적분인자를 적용한다.','Divide by the derivative coefficient before applying the factor.'),
(11,r'xy^{\prime}-2y=x^2,\quad x>0',r'x^{-2}',r'(y/x^2)^{\prime}=1/x',r'y=x^2(\ln x+C)','양의 입력 조건 때문에 로그에 절댓값이 필요 없다.','Positive input removes the need for an absolute value in the logarithm.'),
(12,r'y^{\prime}-3x^2y=x^2',r'e^{-x^3}',r'(e^{-x^3}y)^{\prime}=x^2e^{-x^3}',r'y=-1/3+Ce^{x^3}','상수해도 임의 상수 영으로 포함된다.','The constant solution is included by a zero arbitrary coefficient.'),
(13,r't^2y^{\prime}+3ty=\sqrt{1+t^2},\quad t>0',r't^3',r'(t^3y)^{\prime}=t\sqrt{1+t^2}',r'y=\frac{(1+t^2)^{3/2}/3+C}{t^3}','일 더하기 시간 제곱을 치환해 적분한다.','Substitute one plus time squared in the integral.'),
(14,r't\ln t\,r^{\prime}+r=te^t',r'\ln t',r'((\ln t)r)^{\prime}=e^t',r'r=\frac{e^t+C}{\ln t},\quad t>0,\ t\ne1','상수 음의 자연상수인 가지는 시간 일에서 값 자연상수로 연장되며 원래 식도 만족한다.','The branch with constant minus Euler’s number extends at time one with value Euler’s number and satisfies the original equation.'),
(15,r'y^{\prime}+y\cos x=x',r'e^{\sin x}',r'(e^{\sin x}y)^{\prime}=xe^{\sin x}',r'y=e^{-\sin x}\left(C+\int_0^xte^{\sin t}\,dt\right)','초등함수 원시함수가 없어도 정적분 표현은 정확한 해이다.','The definite-integral expression is exact even without an elementary antiderivative.'),
(16,r'y^{\prime}+2xy=x^3e^{x^2}',r'e^{x^2}',r'(e^{x^2}y)^{\prime}=x^3e^{2x^2}',r'y=\frac{2x^2-1}{8}e^{x^2}+Ce^{-x^2}','치환 후 부분적분으로 우변을 적분한다.','Substitution followed by integration by parts evaluates the right side.'),
(17,r'xy^{\prime}+y=3x^2,\ y(1)=4',r'x',r'xy=x^3+C,\quad C=3',r'y=x^2+3/x,\quad x>0','초기점을 포함하는 최대 구간은 양의 입력이다.','The maximal interval through the initial point is positive input.'),
(18,r'xy^{\prime}-2y=2x,\ y(2)=0',r'x^{-2}',r'y/x^2=-2/x+C,\quad C=1',r'y=x^2-2x','원래 나눠지지 않은 식에는 입력 영에서도 해가 매끄럽게 연장된다.','The solution extends smoothly through zero in the original undivided equation.'),
(19,r'x^2y^{\prime}+2xy=\ln x,\ y(1)=2',r'x^2',r'x^2y=x\ln x-x+C,\quad C=3',r'y=(x\ln x-x+3)/x^2,\quad x>0','로그가 양의 입력을 요구한다.','The logarithm requires positive input.'),
(20,r't^3y^{\prime}+3t^2y=\cos t,\ y(\pi)=0',r't^3',r't^3y=\sin t+C,\quad C=0',r'y=\sin t/t^3,\quad t>0','원래 초기점을 포함하는 구간에서 분모가 영인 시점을 제외한다.','Exclude the denominator zero on the interval containing the initial point.'),
(21,r'tu^{\prime}=t^2+3u,\quad t>0,\quad u(2)=4',r't^{-3}',r'u/t^3=-1/t+C,\quad C=1',r'u=t^3-t^2,\quad t>0','문제에 주어진 양의 시간 조건을 유지한다.','Retain the stated positive-time condition.'),
(22,r'xy^{\prime}+y=x\ln x,\ y(1)=0',r'x',r'xy=\tfrac12x^2\ln x-\tfrac14x^2+C,\quad C=1/4',r'y=\tfrac12x\ln x-\tfrac14x+1/(4x),\quad x>0','초기점에서 로그 항과 두 나머지 항이 정확히 상쇄된다.','At the initial point the logarithm vanishes and the remaining terms cancel.'),
(23,r'xy^{\prime}=y+x^2\sin x,\ y(\pi)=0',r'x^{-1}',r'y/x=-\cos x+C,\quad C=-1',r'y=-x(1+\cos x)','원래 식에서는 입력 영까지 매끄럽게 연장되는 가지이다.','This branch extends smoothly through zero in the original equation.'),
(24,r'(x^2+1)y^{\prime}+3x(y-1)=0,\ y(0)=2',r'(1+x^2)^{3/2}',r'[(1+x^2)^{3/2}(y-1)]^{\prime}=0',r'y=1+(1+x^2)^{-3/2}','분모가 항상 양수이므로 모든 실수에서 해가 정의된다.','The denominator is always positive, giving a global real solution.')]
for n,eq,mu,der,ans,k,e in rows:
 add(n,M(eq)+'을 풀어라.','Solve '+M(eq)+'.',[('적분인자는 '+M(r'\mu='+mu)+'.','The integrating factor is '+M(r'\mu='+mu)+'.'),(M(der)+'를 적분하고 필요한 초기조건을 적용한다.','Integrate '+M(der)+' and apply any initial condition.')],M(ans),M(ans),k+' 미분하여 원래 식의 잔차가 영임을 확인한다.',e+' Differentiation verifies zero residual in the original equation.')
for n,eq,mu,der,ans,k,e in [(25,r'xy^{\prime}+2y=e^x',r'x^2',r'(x^2y)^{\prime}=xe^x',r'y=[(x-1)e^x+C]/x^2,\quad x\ne0','상수를 증가시키면 각 영이 아닌 입력에서 곡선이 올라가고 차이는 상수 차이 나누기 입력 제곱이다.','Increasing the constant raises the curve at every nonzero input; the difference is the constant difference divided by input squared.'),(26,r'xy^{\prime}=x^2+2y',r'x^{-2}',r'(y/x^2)^{\prime}=1/x',r'y=x^2(\ln|x|+C),\quad x\ne0','상수 차이에 입력 제곱을 곱한 만큼 높이가 달라지며 원점에서는 모든 가지가 영으로 연장된다.','Curves differ by the constant difference times input squared, and all branches extend to zero at the origin.')]:
 add(n,M(eq)+'을 풀고 여러 해를 그려 상수 변화의 효과를 설명하라.','Solve '+M(eq)+', plot several solutions, and explain the effect of the constant.',[(M(r'\mu='+mu)+'를 곱하면 '+M(der)+'.','Multiplying by '+M(r'\mu='+mu)+' gives '+M(der)+'.'),(k,e)],M(ans),M(ans),'원래 식을 직접 대입해 확인했다. 원점은 정규화된 선형식에서 특이점이다.','Direct substitution verifies the solution. Zero is a singular point of the normalized linear equation.')
add(27,'Bernoulli 방정식 '+M(r'y^{\prime}+P(x)y=Q(x)y^n')+'에서 지수 영·일의 선형성을 확인하고 다른 지수에 대해 '+M(r'u=y^{1-n}')+'가 선형식을 주는지 증명하라.','For the Bernoulli equation '+M(r'y^{\prime}+P(x)y=Q(x)y^n')+', check linearity for exponents zero and one, then show '+M(r'u=y^{1-n}')+' gives a linear equation for other exponents.',[(M(r'n=0:\ y^{\prime}+Py=Q;\quad n=1:\ y^{\prime}+(P-Q)y=0')+'.',M(r'n=0:\ y^{\prime}+Py=Q;\quad n=1:\ y^{\prime}+(P-Q)y=0')+'.'),(M(r'u^{\prime}=(1-n)y^{-n}y^{\prime}')+'로 원래 식에 필요한 인자를 곱한다.',M(r'u^{\prime}=(1-n)y^{-n}y^{\prime}')+' supplies the multiplier for the original equation.')],M(r'u^{\prime}+(1-n)P(x)u=(1-n)Q(x)'),M(r'u^{\prime}+(1-n)P(x)u=(1-n)Q(x)'),'치환과 나눗셈이 정의되는 구간에서 성립한다. 영함수의 해 여부는 원래 식에서 따로 확인한다.','The transformation holds where its powers and divisions are defined. Check the zero solution separately in the original equation.')
add(28,M(r'xy^{\prime}+y=-xy^2')+'를 Bernoulli 치환으로 풀어라.','Solve '+M(r'xy^{\prime}+y=-xy^2')+' using a Bernoulli substitution.',[(M(r'u=1/y,\quad u^{\prime}-u/x=1')+'이므로 적분인자는 역입력이다.',M(r'u=1/y,\quad u^{\prime}-u/x=1')+' has reciprocal input as integrating factor.'),(M(r'(u/x)^{\prime}=1/x\Rightarrow u=x(\ln|x|+C)')+'.',M(r'(u/x)^{\prime}=1/x\Rightarrow u=x(\ln|x|+C)')+'.')],M(r'y=\frac1{x(\ln|x|+C)}\quad\text{or}\quad y=0'),M(r'y=\frac1{x(\ln|x|+C)}\quad\text{or}\quad y=0'),'비영해는 입력과 전체 분모가 영이 아닌 각 구간에서 유효하다.','Nonzero branches require nonzero input and denominator throughout the interval.')
add(29,M(r'y^{\prime}+2y/x=y^3/x^2')+'를 풀어라.','Solve '+M(r'y^{\prime}+2y/x=y^3/x^2')+'.',[(M(r'u=y^{-2},\quad u^{\prime}-4u/x=-2/x^2')+'이고 적분인자는 입력의 음의 사제곱이다.',M(r'u=y^{-2},\quad u^{\prime}-4u/x=-2/x^2')+' has input to the negative fourth power as integrating factor.'),(M(r'(u/x^4)^{\prime}=-2x^{-6}\Rightarrow u=2/(5x)+Cx^4')+'.',M(r'(u/x^4)^{\prime}=-2x^{-6}\Rightarrow u=2/(5x)+Cx^4')+'.')],M(r'y=\pm[2/(5x)+Cx^4]^{-1/2}\quad\text{or}\quad y=0'),M(r'y=\pm[2/(5x)+Cx^4]^{-1/2}\quad\text{or}\quad y=0'),'입력이 영이 아니고 대괄호가 양수인 연결구간을 선택한다.','Select connected intervals with nonzero input and a positive bracket.')
add(30,M(r'xy^{\prime\prime}+2y^{\prime}=12x^2')+'를 '+M(r'u=y^{\prime}')+'로 치환해 풀어라.','Solve '+M(r'xy^{\prime\prime}+2y^{\prime}=12x^2')+' using '+M(r'u=y^{\prime}')+'.',[(M(r'xu^{\prime}+2u=12x^2,\quad(x^2u)^{\prime}=12x^3')+'.',M(r'xu^{\prime}+2u=12x^2,\quad(x^2u)^{\prime}=12x^3')+'.'),(M(r'u=3x^2+C_1/x^2')+'를 한 번 더 적분한다.',M(r'u=3x^2+C_1/x^2')+' is integrated once more.')],M(r'y=x^3+C_1/x+C_2,\quad x\ne0'),M(r'y=x^3+C_1/x+C_2,\quad x\ne0'),'임의 상수의 부호는 새 이름에 흡수했다. 역입력 항이 없으면 영에서도 매끄럽게 연장된다.','The constant sign is absorbed into its name. Without the reciprocal term the solution extends smoothly through zero.')
add(31,'직렬 저항·인덕터 회로에서 '+M(r'E=40,\ L=2,\ R=10,\ I(0)=0')+'이다. (a) 전류식과 (b) 영점일 초 전류를 구하라.','A series resistor-inductor circuit has '+M(r'E=40,\ L=2,\ R=10,\ I(0)=0')+'. Find (a) current and (b) current at 0.1 seconds.',[(M(r'2I^{\prime}+10I=40\Rightarrow I^{\prime}+5I=20')+'.',M(r'2I^{\prime}+10I=40\Rightarrow I^{\prime}+5I=20')+'.'),('적분인자 '+M(r'e^{5t}')+'를 곱해 적분하고 초기값을 넣는다.','Multiply by integrating factor '+M(r'e^{5t}')+', integrate, and apply the initial value.')],M(r'I(t)=4(1-e^{-5t});\quad I(0.1)=4(1-e^{-1/2})\approx1.573877\ \mathrm A'),M(r'I(t)=4(1-e^{-5t});\quad I(0.1)=4(1-e^{-1/2})\approx1.573877\ \mathrm A'),'전류는 영에서 전압 나누기 저항인 사 암페어로 증가한다.','Current increases from zero toward voltage divided by resistance, four amperes.','ab')
f32=lambda t:.2*math.sin(60*t)-.6*math.cos(60*t)+1.6*math.exp(-20*t)
add(32,'교류 직렬 회로의 '+M(r'E(t)=40\sin60t,\ L=1,\ R=20,\ I(0)=1')+'에서 (a) 전류식, (b) 영점일 초 값, (c) 그래프를 구하라.','For the AC series circuit '+M(r'E(t)=40\sin60t,\ L=1,\ R=20,\ I(0)=1')+', find (a) current, (b) its value at 0.1 seconds, and (c) its graph.',[(M(r'I^{\prime}+20I=40\sin60t')+'의 사인·코사인 특수해 계수를 비교한다.',M(r'I^{\prime}+20I=40\sin60t')+' determines coefficients of a sine-cosine particular solution.'),(M(r'I_p=\tfrac15\sin60t-\tfrac35\cos60t')+'에 감쇠 동차해를 더하고 초기값으로 상수를 정한다.',M(r'I_p=\tfrac15\sin60t-\tfrac35\cos60t')+' is combined with a decaying homogeneous term and fitted to the initial value.')],M(rf'I(t)=\tfrac15\sin60t-\tfrac35\cos60t+\tfrac85e^{{-20t}};\quad I(0.1)\approx{f32(.1):.9f}\ \mathrm A'),M(rf'I(t)=\tfrac15\sin60t-\tfrac35\cos60t+\tfrac85e^{{-20t}};\quad I(0.1)\approx{f32(.1):.9f}\ \mathrm A'),'초기 전류 일과 원래 회로식 잔차 영을 확인했다.','The unit initial current and zero circuit-equation residual were verified.','abc')
add(33,'저항·축전기 회로의 '+M(r'R=5,\ C=0.05,\ E=60,\ Q(0)=0')+'에서 전하와 전류를 구하라.','Find charge and current in a resistor-capacitor circuit with '+M(r'R=5,\ C=0.05,\ E=60,\ Q(0)=0')+'.',[(M(r'RQ^{\prime}+Q/C=E\Rightarrow Q^{\prime}+4Q=12')+'.',M(r'RQ^{\prime}+Q/C=E\Rightarrow Q^{\prime}+4Q=12')+'.'),('적분인자는 '+M(r'e^{4t}')+'이다. 전하를 푼 뒤 미분한다.','The integrating factor is '+M(r'e^{4t}')+'. Solve for charge, then differentiate.')],M(r'Q=3(1-e^{-4t})\ \mathrm C,\quad I=Q^{\prime}=12e^{-4t}\ \mathrm A'),M(r'Q=3(1-e^{-4t})\ \mathrm C,\quad I=Q^{\prime}=12e^{-4t}\ \mathrm A'),'전류와 축전기 전압을 회로법칙에 대입하면 항상 육십 볼트가 된다.','Substitution of current and capacitor voltage into the circuit law always yields sixty volts.')
add(34,'저항·축전기 회로의 '+M(r'R=2,\ C=0.01,\ E(t)=10\sin60t,\ Q(0)=0')+'에서 전하와 전류를 구하라.','Find charge and current for the resistor-capacitor circuit '+M(r'R=2,\ C=0.01,\ E(t)=10\sin60t,\ Q(0)=0')+'.',[(M(r'Q^{\prime}+50Q=5\sin60t')+'를 적분인자 또는 미정계수로 푼다.',M(r'Q^{\prime}+50Q=5\sin60t')+' is solved using an integrating factor or undetermined coefficients.'),('초기값이 감쇠항의 계수를 정한다. 전류는 전하의 시간 도함수이다.','The initial value fixes the decaying term; current is the time derivative of charge.')],M(r'Q=\frac{5\sin60t-6\cos60t+6e^{-50t}}{122};\quad I=\frac{150\cos60t+180\sin60t-150e^{-50t}}{61}'),M(r'Q=\frac{5\sin60t-6\cos60t+6e^{-50t}}{122};\quad I=\frac{150\cos60t+180\sin60t-150e^{-50t}}{61}'),'처음 전하와 전류는 모두 영이며 회로식을 직접 만족한다.','Both initial charge and current are zero, and the circuit equation checks directly.')
add(35,'학습 모델 '+M(r'P^{\prime}=k(M-P),\quad k>0')+'을 선형방정식으로 풀고 학습 곡선을 그려라.','Solve the learning model '+M(r'P^{\prime}=k(M-P),\quad k>0')+' as a linear equation and plot a learning curve.',[(M(r'P^{\prime}+kP=kM')+'의 적분인자는 '+M(r'e^{kt}')+'.','The integrating factor for '+M(r'P^{\prime}+kP=kM')+' is '+M(r'e^{kt}')+'.'),(M(r'(e^{kt}P)^{\prime}=kMe^{kt}\Rightarrow P=M+Ce^{-kt}')+'.',M(r'(e^{kt}P)^{\prime}=kMe^{kt}\Rightarrow P=M+Ce^{-kt}')+'.')],M(r'P=M+(P_0-M)e^{-kt}'),M(r'P=M+(P_0-M)e^{-kt}'),'초기 수행도가 최대보다 낮으면 증가하고 아래로 오목하며 최대 수행도에 점근한다.','Starting below maximum, performance increases concavely downward toward the maximum.')
add(36,'학습 초기 수행도를 영으로 보고 시간별 생산량을 수행도 관측으로 사용한다. Jim은 첫째·둘째 시간에 이십오·사십오 개, Mark는 삼십오·오십 개를 처리했다. 각자의 최대 시간당 처리량을 학습 모델로 추정하라.','Treat hourly production counts as performance observations with zero initial performance. Jim processes twenty-five and forty-five units in the first two hours; Mark processes thirty-five and fifty. Estimate each maximum hourly throughput using the learning model.',[(M(r'P(t)=M(1-e^{-kt}),\quad q=e^{-k},\quad P(2)/P(1)=1+q')+'이다.','Use '+M(r'P(t)=M(1-e^{-kt}),\quad q=e^{-k},\quad P(2)/P(1)=1+q')+'.'),('각 작업자의 비율로 감쇠인자를 구한 다음 '+M(r'M=P(1)/(1-q)')+'에 넣는다.','Each ratio determines its decay factor; substitute into '+M(r'M=P(1)/(1-q)')+'.')],M(r'\mathrm{Jim}:q=0.8,\ M=125;\quad\mathrm{Mark}:q=3/7,\ M=61.25\quad\mathrm{units/hour}'),M(r'\mathrm{Jim}:q=0.8,\ M=125;\quad\mathrm{Mark}:q=3/7,\ M=61.25\quad\mathrm{units/hour}'),'두 관측을 다시 대입해 확인했다. 시간별 총량을 순간 수행도의 관측으로 해석하는 교재의 추정 모델을 사용했다.','Both observations are recovered. This uses the textbook estimation model interpreting hourly totals as sampled performance.')
c37=.4*(1-(100/140)**2.5)
add(37,'순수 백 리터 탱크에 농도 영점사 킬로그램/리터 소금물이 분당 오 리터 들어오고 혼합액은 분당 삼 리터 나간다. 소금량의 '+M(r'y^{\prime}=2-3y/(100+2t)')+'를 유도·풀이하고 이십 분 뒤 농도를 구하라.','A tank with one hundred liters of pure water receives 0.4-kilogram-per-liter brine at five liters per minute and drains mixed liquid at three liters per minute. Derive and solve '+M(r'y^{\prime}=2-3y/(100+2t)')+' and find concentration after twenty minutes.', [('부피는 '+M(r'V=100+2t')+'이고 유입 소금은 분당 이 킬로그램이다. 적분인자는 '+M(r'V^{3/2}')+'.','Volume is '+M(r'V=100+2t')+' and salt inflow is two kilograms per minute. The integrating factor is '+M(r'V^{3/2}')+'.'),(M(r'(V^{3/2}y)^{\prime}=2V^{3/2}\Rightarrow y=0.4V+C/V^{3/2}')+'에 영 초기값을 넣는다.',M(r'(V^{3/2}y)^{\prime}=2V^{3/2}\Rightarrow y=0.4V+C/V^{3/2}')+' is fitted to zero initial salt.')],M(rf'y=0.4(100+2t)-40000(100+2t)^{{-3/2}};\quad c(20)=0.4[1-(5/7)^{{5/2}}]\approx{c37:.9f}\ \mathrm{{kg/L}}'),M(rf'y=0.4(100+2t)-40000(100+2t)^{{-3/2}};\quad c(20)=0.4[1-(5/7)^{{5/2}}]\approx{c37:.9f}\ \mathrm{{kg/L}}'),'농도는 소금량을 변하는 부피로 나누어 계산했다. 초기 소금량은 영이다.','Concentration uses salt mass divided by the changing volume; the initial salt mass is zero.')
add(38,'사백 리터 탱크에 염소 영점영오 그램/리터 용액이 가득하다. 순수가 초당 사 리터 유입되고 혼합액은 초당 십 리터 유출된다. 염소량의 시간 함수를 구하라.','A four-hundred-liter tank starts full at 0.05 grams of chlorine per liter. Fresh water enters at four liters per second while mixed liquid drains at ten liters per second. Find chlorine mass over time.',[(M(r'V=400-6t,\quad y(0)=20,\quad y^{\prime}=-10y/(400-6t)')+'.',M(r'V=400-6t,\quad y(0)=20,\quad y^{\prime}=-10y/(400-6t)')+'.'),('변수분리 또는 적분인자로 '+M(r'\ln y=\tfrac53\ln(400-6t)+C')+'를 얻는다.','Separation or an integrating factor gives '+M(r'\ln y=\tfrac53\ln(400-6t)+C')+'.')],M(r'y(t)=20(1-3t/200)^{5/3}\ \mathrm g,\quad0\le t<200/3\ \mathrm s'),M(r'y(t)=20(1-3t/200)^{5/3}\ \mathrm g,\quad0\le t<200/3\ \mathrm s'),'탱크가 비는 시점에 양은 영으로 접근하며 그 뒤에는 동일 혼합 모델을 사용할 수 없다.','The mass tends to zero when the tank empties; the same mixing model no longer applies afterward.')
add(39,'정지 상태에서 낙하한 물체가 '+M(r'mv^{\prime}=mg-cv,\quad c>0,\quad v(0)=s(0)=0')+'을 따른다. (a) 선형방정식으로 속도, (b) 종단속도, (c) 낙하거리를 구하라.','A body dropped from rest satisfies '+M(r'mv^{\prime}=mg-cv,\quad c>0,\quad v(0)=s(0)=0')+'. Find (a) velocity via a linear equation, (b) terminal velocity, and (c) falling distance.', [('적분인자 '+M(r'e^{ct/m}')+'로 속도식을 푼다.','Use integrating factor '+M(r'e^{ct/m}')+' to solve for velocity.'),('속도를 시간 영부터 적분하여 낙하거리를 얻는다.','Integrate velocity from time zero for the distance.')],M(r'v=\frac{mg}c(1-e^{-ct/m});\quad v_\infty=mg/c;\quad s=\frac{mg}ct-\frac{m^2g}{c^2}(1-e^{-ct/m})'),M(r'v=\frac{mg}c(1-e^{-ct/m});\quad v_\infty=mg/c;\quad s=\frac{mg}ct-\frac{m^2g}{c^2}(1-e^{-ct/m})'),'위치와 속도의 초기값은 영이며 위치의 도함수는 속도와 같다.','Both initial position and velocity are zero, and the position derivative equals velocity.','abc')
add(40,M(r'v=\frac{mg}c(1-e^{-ct/m})')+'에서 질량 도함수를 구하고 같은 항력계수·시간에서 무거운 물체의 속도가 더 큰지 보여라.','Differentiate '+M(r'v=\frac{mg}c(1-e^{-ct/m})')+' in mass and show that with the same drag coefficient and elapsed time, greater mass gives greater speed.', [('곱과 연쇄법칙으로 질량 의존성을 모두 미분한다. '+M(r'u=ct/m>0')+'로 표시를 줄인다.','Differentiate both mass dependencies using product and chain rules. Write '+M(r'u=ct/m>0')+'.'),(M(r'e^u>1+u\quad(u>0)')+'이므로 대괄호가 양수이다.',M(r'e^u>1+u\quad(u>0)')+' makes the bracket positive.')],M(r'\frac{\partial v}{\partial m}=\frac gc[1-(1+ct/m)e^{-ct/m}]>0\quad(t>0)'),M(r'\frac{\partial v}{\partial m}=\frac gc[1-(1+ct/m)e^{-ct/m}]>0\quad(t>0)'),'질량 이외의 항력계수를 고정한 이 모델 안에서의 비교이다. 시간 영에서는 두 속도가 같다.','This comparison holds within the model with drag coefficient fixed; at time zero the velocities agree.')
add(41,'(a) '+M(r'z=1/P')+'가 '+M(r'P^{\prime}=kP(1-P/M)')+'를 선형식으로 바꾸는지 보이고 (b) 풀어서 로지스틱 공식과 비교하라.','(a) Show that '+M(r'z=1/P')+' converts '+M(r'P^{\prime}=kP(1-P/M)')+' into a linear equation and (b) solve and compare with the logistic formula.',[(M(r'z^{\prime}=-P^{\prime}/P^2=-k/P+k/M')+'이다.',M(r'z^{\prime}=-P^{\prime}/P^2=-k/P+k/M')+'.'),(M(r'z^{\prime}+kz=k/M,\quad z=1/M+Ce^{-kt}')+'에서 역수를 취한다.',M(r'z^{\prime}+kz=k/M,\quad z=1/M+Ce^{-kt}')+' is inverted.')],M(r'P=M/(1+CMe^{-kt})'),M(r'P=M/(1+CMe^{-kt})'),'상수 곱을 하나의 상수로 바꾸면 기존 로지스틱 공식과 같다. 영인 평형해는 역수 치환에서 빠져 따로 포함된다.','Absorbing the constant product gives the usual logistic formula. The zero equilibrium is omitted by the reciprocal substitution and included separately.','ab')
add(42,'계절 로지스틱 모델 '+M(r'P^{\prime}=k(t)P(1-P/M(t)),\quad P(0)=P_0>0,\quad M(t)>0')+'에서 (a) 역수 치환의 선형식, (b) 일반 적분식과 수용력 일정인 극한, (c) 성장계수 양의 상수·수용력 변화 시 극한을 구하라.','For the seasonal logistic model '+M(r'P^{\prime}=k(t)P(1-P/M(t)),\quad P(0)=P_0>0,\quad M(t)>0')+', find (a) the reciprocal linear equation, (b) its integral solution and the constant-capacity limit, and (c) the variable-capacity limit with a positive constant growth coefficient.', [(M(r'z=1/P,\quad z^{\prime}+k(t)z=k(t)/M(t),\quad K(t)=\int_0^t k(s)\,ds')+'.',M(r'z=1/P,\quad z^{\prime}+k(t)z=k(t)/M(t),\quad K(t)=\int_0^t k(s)\,ds')+'.'),(M(r'z(t)=e^{-K(t)}\left[1/P_0+\int_0^t\frac{k(s)e^{K(s)}}{M(s)}\,ds\right]')+'이 적분인자 해이다.',M(r'z(t)=e^{-K(t)}\left[1/P_0+\int_0^t\frac{k(s)e^{K(s)}}{M(s)}\,ds\right]')+' is the integrating-factor solution.'),('수용력 일정이면 적분이 직접 계산된다. 성장계수 상수이고 수용력이 양의 유한 극한으로 가면 로피탈 법칙으로 역인구의 극한이 그 역수가 된다.','With constant capacity the integral evaluates directly. With constant positive growth coefficient and capacity tending to a finite positive limit, l’Hospital’s rule makes the reciprocal population tend to its reciprocal.')],M(r'M\ \text{constant}:\ P=\frac{M}{1+(M/P_0-1)e^{-K(t)}},\quad K(t)\to\infty\Rightarrow P\to M;\quad k>0\ \text{constant}:\ z=e^{-kt}\left[1/P_0+\int_0^t\frac{ke^{ks}}{M(s)}\,ds\right],\quad M(t)\to L>0\Rightarrow P(t)\to L'),M(r'M\ \text{constant}:\ P=\frac{M}{1+(M/P_0-1)e^{-K(t)}},\quad K(t)\to\infty\Rightarrow P\to M;\quad k>0\ \text{constant}:\ z=e^{-kt}\left[1/P_0+\int_0^t\frac{ke^{ks}}{M(s)}\,ds\right],\quad M(t)\to L>0\Rightarrow P(t)\to L'),'연속 계수와 양의 전역해를 가정한다. 수용력 극한 영이면 역인구는 무한대로, 무한대이면 역인구는 영으로 가므로 확장된 극한도 같다. 후자는 적분의 고정 초기 구간과 유계 꼬리를 나누어 확인할 수 있다.','Assume continuous coefficients and a positive global solution. A zero capacity limit sends reciprocal population to infinity; an infinite capacity limit sends it to zero, so extended limits also agree. The latter follows by splitting the integral into a fixed initial interval and a bounded tail.','abc')
src=(BASE/'exercise-checks/s9-2-author.py').read_text();tree=ast.parse(src);funcs=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ['sampled','svg']];exec(compile(ast.unparse(ast.Module(body=funcs,type_ignores=[])).replace('s9-2-','s9-5-'),'helpers','exec'))
svg(25,'y=[(x-1)exp(x)+C]/x^2',None,(-3,3),(-5,10),[(f'C={c}',sampled(lambda x:((x-1)*math.exp(x)+c)/x**2 if abs(x)>.025 else (.5 if c==1 else math.nan),-3,3)) for c in [-1,0,1,2]])
svg(26,'y=x^2(ln|x|+C)',None,(-3,3),(-5,15),[(f'C={c}',sampled(lambda x:x*x*(math.log(abs(x))+c) if x else 0,-3,3)) for c in [-1,0,1,2]])
svg(32,'AC current in amperes',None,(0,.5),(-.8,1.2),[('I(t)',sampled(f32,0,.5))])
svg(35,'Learning: M=1, k=1, initial levels 0 and 0.3',None,(0,5),(0,1.1),[(f'P0={p}',sampled(lambda t:1+(p-1)*math.exp(-t),0,5)) for p in [0,.3]])
assert len(items)==42
raw=dict(section='9.5',source=dict(title='Calculus',edition='9',language='en',printedPages=[684,685,686],pdfPages=[721,722,723]),scope=dict(kind='exercise',numbers=list(range(1,43)),total=42,note=bi('전체 42문항과 모든 소문항.','All 42 exercises and every subpart.')),exercises=items)
p=BASE/'exercise-content/s9-5.json';p.write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n');sys.path.insert(0,str(BASE));import build_exercises as b;b.validate_document(raw,p)
print('9.5:42 cards,4 SVGs; concentration37=',c37)
