import json,math,html,sys,ast
from pathlib import Path
BASE=Path(__file__).resolve().parents[1];items=[]
def M(s):return r'\('+s+r'\)'
def bi(k,e=None):return {'ko':k,'en':e if e is not None else k}
def add(n,sk,se,steps,ak,ae,ck,ce,sub=''):
 p=691 if n<=2 else 692 if n<=9 else 693
 items.append(dict(id=f'stewart9-exercise-9.6-{n}',number=n,subparts=list(sub),source=dict(printedPage=p,pdfPage=p+37),topic=bi('포식자–피식자와 연립 모델','Predator-prey and coupled models'),statement=bi(sk,se),hint=bi('상호작용 항의 부호와 두 도함수의 영점을 함께 확인한다.','Inspect interaction signs and simultaneous derivative zeros.'),steps={'ko':[x[0] for x in steps],'en':[x[1] for x in steps]},answer=bi(ak,ae),check=bi(ck,ce),conceptHref='../../calc1/index.html',status='math-verified'))
add(1,'두 모형에서 피식자·포식자를 구별하고 다른 성장 제한이나 먹이 공급이 포함되는지 논하라. '+M(r'\text{(a) }x^{\prime}=-0.05x+0.0001xy,\ y^{\prime}=0.1y-0.005xy;\quad\text{(b) }x^{\prime}=0.2x-0.0002x^2-0.006xy,\ y^{\prime}=-0.015y+0.00008xy'), 'Identify prey and predator and discuss additional growth restrictions or food sources. '+M(r'\text{(a) }x^{\prime}=-0.05x+0.0001xy,\ y^{\prime}=0.1y-0.005xy;\quad\text{(b) }x^{\prime}=0.2x-0.0002x^2-0.006xy,\ y^{\prime}=-0.015y+0.00008xy'), [('(a) 만남 항이 첫 종에는 이롭고 둘째 종에는 해롭다. 포식자가 없으면 피식자는 제한 없는 지수성장을 한다.','(a) Encounters benefit the first species and harm the second. Without predators the prey grows exponentially without an additional restriction.'),('(b) 만남 항이 첫 종을 줄이고 둘째 종을 늘린다. 첫 종의 음의 제곱항은 포식 이외의 밀도 제한이다. 두 모형 모두 피식자가 없으면 포식자는 감소한다.','(b) Encounters reduce the first species and benefit the second. The negative squared term adds prey density limitation. In both systems predators decline without prey.')],M(r'\text{(a) prey }y,\ \text{predator }x;\quad\text{(b) prey }x,\ \text{predator }y')+'; 추가 먹이로 유지되는 포식자 성장은 없다.',M(r'\text{(a) prey }y,\ \text{predator }x;\quad\text{(b) prey }x,\ \text{predator }y')+'; neither model includes predator growth sustained by another food source.','각 상대 종을 영으로 놓아 단독 성장률을 확인했다.','Setting the other population to zero verifies each isolated growth law.','ab')
add(2,'상호작용이 협력인지 경쟁인지 판정하라. '+M(r'\text{(a) }x^{\prime}=0.12x-0.0006x^2+0.00001xy,\ y^{\prime}=0.08x+0.00004xy;\quad\text{(b) }x^{\prime}=0.15x-0.0002x^2-0.0006xy,\ y^{\prime}=0.2y-0.00008y^2-0.0002xy'), 'Classify interaction as cooperation or competition. '+M(r'\text{(a) }x^{\prime}=0.12x-0.0006x^2+0.00001xy,\ y^{\prime}=0.08x+0.00004xy;\quad\text{(b) }x^{\prime}=0.15x-0.0002x^2-0.0006xy,\ y^{\prime}=0.2y-0.00008y^2-0.0002xy'), [('(a) 다른 종을 늘리면 각 성장률이 증가한다. 원문 둘째 식의 첫 항은 첫 종에 비례하며 임의로 둘째 종으로 바꾸지 않았다.','(a) Increasing either species benefits the other’s growth. The first term in the second equation is proportional to the first species in the source; it is retained as printed.'),('(b) 두 교차항이 음수라 상대 종이 자원을 빼앗는 경쟁을 나타낸다. 자기 제곱항은 각 종의 자체 밀도 제한이다.','(b) Both cross terms are negative, modeling competition for resources; self-squared terms give within-species density limits.')],'(a) 협력, (b) 경쟁.','(a) Cooperation; (b) competition.','협력식의 양의 공급항 때문에 둘째 종이 영이어도 첫 종이 있으면 새 개체가 생기는 모델 특성이 있다.','The positive source term in the cooperative model can generate the second species even when absent, provided the first is present.','ab')
add(3,M(r'x^{\prime}=0.5x-0.004x^2-0.001xy,\quad y^{\prime}=0.4y-0.001y^2-0.002xy')+'에서 (a) 종 관계와 (b) 평형 및 의미를 구하라.','For '+M(r'x^{\prime}=0.5x-0.004x^2-0.001xy,\quad y^{\prime}=0.4y-0.001y^2-0.002xy')+', find (a) interaction type and (b) equilibria and meanings.', [('교차항이 모두 음수이므로 경쟁이다. 한 종이 영인 경우를 먼저 구한다.','Both cross terms are negative, giving competition. First solve cases where one population is zero.'),('둘 다 양수라면 '+M(r'4x+y=500,\quad2x+y=400')+'을 동시에 푼다.','For coexistence solve '+M(r'4x+y=500,\quad2x+y=400')+' simultaneously.')],M(r'(x,y)=(0,0),(125,0),(0,400),(50,300)'),M(r'(x,y)=(0,0),(125,0),(0,400),(50,300)'),'각각 전멸, 첫 종 단독, 둘째 종 단독, 공존 평형이다. 네 점에서 두 우변이 모두 영임을 확인했다.','They represent extinction, first-species-only, second-species-only, and coexistence. Both right sides vanish at all four points.','ab')
add(4,'스라소니는 산토끼를 먹고 산토끼는 버드나무를 먹는다. 토끼가 없으면 나무는 지수성장하고 스라소니는 지수감소한다. 스라소니와 나무가 모두 없으면 토끼는 지수감소한다. '+M(r'L,H,W')+'의 세 연립식을 쓰고 부호를 설명하라.','Lynx eat hares, which eat willows. Without hares, willows grow exponentially and lynx decline exponentially. Without lynx and willows, hares decline exponentially. Formulate a system for '+M(r'L,H,W')+' and explain the signs.', [('포식은 먹는 종에 양의 항, 먹히는 종에 음의 항을 준다. 종 사이 만남을 두 개체수의 곱으로 표현한다.','Feeding benefits the consumer and harms the consumed; encounter rates are products of populations.'),('단독 성장·감소 조건은 각 선형항의 부호를 정한다.','The isolated growth and decay assumptions determine the linear-term signs.')],M(r'L^{\prime}=-aL+bLH,\quad H^{\prime}=-cH-dLH+eHW,\quad W^{\prime}=fW-gHW,\quad a,b,c,d,e,f,g>0'),M(r'L^{\prime}=-aL+bLH,\quad H^{\prime}=-cH-dLH+eHW,\quad W^{\prime}=fW-gHW,\quad a,b,c,d,e,f,g>0'),'토끼를 영으로 놓고, 또 스라소니와 나무를 함께 영으로 놓아 제시된 감소·성장 조건을 복원했다.','Setting hares to zero, and separately setting lynx and willows to zero, recovers the stated isolated behavior.')
add(5,'토끼–여우 위상 곡선은 대략 '+M(r'(R,F)=(300,100)')+'에서 시작해 아래쪽을 오른쪽으로 돌아가는 닫힌 고리이다. 토끼는 약 삼백–이천사백, 여우는 약 십오–삼백이십 범위이다. (a) 변화 순서를 설명하고 (b) 시간별 두 개체수의 개형을 그려라.','A rabbit-fox trajectory starts near '+M(r'(R,F)=(300,100)')+' and follows a closed loop rightward along its lower arc. Rabbits range roughly from three hundred to 2,400 and foxes from fifteen to 320. (a) Describe the sequence and (b) sketch both time courses.', [('시작점은 토끼의 최소 부근이다. 여우가 감소하는 동안 토끼가 늘고, 여우 최소를 지난 뒤 두 종이 함께 증가한다.','The start is near the rabbit minimum. Rabbits rise while foxes fall, then both increase after the fox minimum.'),('토끼가 최대를 지나 감소해도 여우는 한동안 늘어난다. 여우 최대 뒤 둘 다 감소하다가 다시 토끼 최소로 돌아온다.','After rabbits peak and begin falling, foxes continue rising briefly. After the fox peak both fall until the rabbit minimum recurs.')],'두 개체수는 같은 주기로 진동하며 여우의 최대는 토끼 최대보다 늦다.','Both populations oscillate with the same period; the fox maximum lags the rabbit maximum.','원문에 시간 눈금이나 방정식이 없어 자체 그림의 시간은 임의 척도이며 수치는 개형을 위한 예시이다.','The source supplies no time scale or equation; the original sketch uses arbitrary time and illustrative values.','ab')
add(6,'토끼–여우 위상 곡선은 약 '+M(r'(R,F)=(600,160)')+'에서 왼쪽 아래로 움직이고 토끼 최소, 여우 최소, 토끼 최대 순으로 돌아 마지막에는 약 '+M(r'(950,65)')+'근처로 향한다. (a) 개체수 변화를 서술하고 (b) 시간 그래프를 그려라.','A rabbit-fox trajectory starts near '+M(r'(R,F)=(600,160)')+', moves down and left, passes a rabbit minimum, fox minimum, then rabbit maximum, and heads toward about '+M(r'(950,65)')+'. (a) Describe population changes and (b) sketch time graphs.', [('처음 둘 다 감소한다. 토끼는 먼저 최소에 이르러 증가하고 여우는 더 늦게 최소에 이른다.','Both initially decrease. Rabbits reach their minimum first and rise while foxes continue decreasing to a later minimum.'),('그 뒤 둘 다 증가하다 토끼가 먼저 최대를 지난다. 그림의 끝에서는 토끼가 감소하고 여우가 증가하며 진폭이 줄어드는 양상이 보인다.','Both then increase until rabbits peak first. Near the drawn endpoint, rabbits decrease and foxes increase with a reduced excursion.')],'토끼의 극값이 여우의 대응 극값보다 먼저 나타난다. 표시된 곡선은 닫힌 주기 궤도가 아니다.','Rabbit extrema precede corresponding fox extrema. The displayed path is not a closed periodic orbit.','그려진 부분만으로 정확한 장기 평형값을 단정하지 않았다. 자체 그림은 제시된 순서를 보이는 개형 보간이다.','The visible segment alone does not establish an exact limiting equilibrium. The original plot interpolates the stated qualitative sequence.','ab')
add(7,'두 시간 그래프에서 종 일은 약 사십오–이백이십오, 종 이는 오십–백구십오 사이를 반복하며 종 일의 최대가 먼저 나온다. 종 일을 가로축, 종 이를 세로축으로 하여 위상 곡선을 그려라.','Two time graphs repeat between roughly forty-five and 225 for species one and fifty and 195 for species two, with species one peaking first. Plot a phase trajectory with species one horizontally and species two vertically.', [('같은 시간의 두 값을 한 좌표쌍으로 찍는다. 종 일 최대에서 수평 운동이 멈추지만 종 이는 아직 증가한다.','Pair the two populations at the same time. At the first-species maximum horizontal motion stops while the second still increases.'),('극값들의 순서에 따라 아래·오른쪽·위·왼쪽을 돌아 닫힌 곡선을 만든다.','The order of extrema traces the lower, right, upper, then left parts of a closed curve.')],'반시계 방향의 닫힌 위상 고리.','A counterclockwise closed phase loop.','같은 시점의 값을 짝지었으며 종 사이의 지연을 위상 방향에 반영했다.','Values are paired at equal times, and the lag determines orientation.')
add(8,'종 일은 처음 팔백에서 증가해 약 천삼백으로 넘친 후 천이백으로 안정된다. 종 이는 칠백에서 약 백까지 줄었다가 이백으로 안정된다. 종 일을 가로축으로 위상 곡선을 그려라.','Species one starts at eight hundred, rises with an overshoot near thirteen hundred, then settles at twelve hundred. Species two starts at seven hundred, falls near one hundred, then settles at two hundred. Plot species one horizontally in the phase plane.', [('시작 좌표는 '+M(r'(800,700)')+'이며 처음 오른쪽 아래로 이동한다.','The start is '+M(r'(800,700)')+' and the initial motion is down and right.'),('둘째 종의 최소를 지나면 오른쪽 위로, 첫째 종의 최대 뒤에는 왼쪽으로 돌아 최종 평형에 가까워진다.','After the second-species minimum the path turns up and right; after the first-species maximum it turns left toward equilibrium.')],M(r'(800,700)\longrightarrow(1200,200)')+'; 감쇠하는 회전 경로.',M(r'(800,700)\longrightarrow(1200,200)')+'; a damped turning path.','직선 연결이 아니라 두 시간함수를 같은 시간 매개변수로 결합한다.','The trajectory combines both functions at the same time parameter rather than merely connecting endpoints.')
add(9,M(r'\frac{dW}{dR}=\frac{-0.02W+0.00002RW}{0.08R-0.001RW}')+'에서 (a) 보존되는 음함수 식을 구하고 (b) '+M(r'(R,W)=(1000,40)')+'을 지나는 궤도를 그려 비교하라.','For '+M(r'\frac{dW}{dR}=\frac{-0.02W+0.00002RW}{0.08R-0.001RW}')+', (a) derive an implicit invariant and (b) plot the trajectory through '+M(r'(R,W)=(1000,40)')+' for comparison.',[(M(r'(0.08/W-0.001)\,dW=(-0.02/R+0.00002)\,dR')+'로 분리한다.',M(r'(0.08/W-0.001)\,dW=(-0.02/R+0.00002)\,dR')+' separates variables.'),(M(r'0.02\ln R+0.08\ln W-0.00002R-0.001W=\ln C')+'를 지수화한다.',M(r'0.02\ln R+0.08\ln W-0.00002R-0.001W=\ln C')+' is exponentiated.')],M(r'\frac{R^{0.02}W^{0.08}}{e^{0.00002R+0.001W}}=C,\quad C=1000^{0.02}40^{0.08}e^{-0.06}'),M(r'\frac{R^{0.02}W^{0.08}}{e^{0.00002R+0.001W}}=C,\quad C=1000^{0.02}40^{0.08}e^{-0.06}'),'양의 사분면에서 공존점 천·팔십을 둘러싼 반시계 닫힌 궤도이다. 연립식을 따라 보존량의 도함수는 영이다.','In the positive quadrant it is a counterclockwise closed orbit around coexistence at one thousand and eighty. The invariant derivative along the system is zero.','ab')
add(10,'진딧물·무당벌레 모형 '+M(r'A^{\prime}=2A-0.01AL,\quad L^{\prime}=-0.5L+0.0001AL')+'에서 (a) 평형, (b) 위상 기울기, (c) 위상 초상, (d) '+M(r'(A_0,L_0)=(1000,200)')+'의 궤도와 변화, (e) 두 시간 그래프와 지연을 구하라.','For aphids and ladybugs '+M(r'A^{\prime}=2A-0.01AL,\quad L^{\prime}=-0.5L+0.0001AL')+', find (a) equilibria, (b) phase slope, (c) a phase portrait, (d) the trajectory and behavior from '+M(r'(A_0,L_0)=(1000,200)')+', and (e) time courses and lag.', [('동시에 두 도함수를 영으로 놓으면 전멸과 공존 평형을 얻는다. 양의 비평형 궤도는 공존점을 둘러싸는 반시계 닫힌 고리이다.','Simultaneous derivative zeros give extinction and coexistence. Positive nonequilibrium trajectories are counterclockwise closed loops around coexistence.'),('초기 진딧물 도함수는 영, 무당벌레 도함수는 음의 팔십이다. 무당벌레가 줄면서 진딧물은 최소에서 증가하며 그 증가를 뒤따라 무당벌레가 늘어난다.','Initially the aphid derivative is zero and the ladybug derivative is minus eighty. As ladybugs decline, aphids rise from a minimum; ladybugs subsequently follow the aphid rise.'),('진딧물 최대 뒤 무당벌레 최대가 나타나고 두 종의 주기는 같다.','The ladybug maximum follows the aphid maximum, and both species have the same period.')],M(r'(A,L)=(0,0),(5000,200);\quad\frac{dL}{dA}=\frac{L(-0.5+0.0001A)}{A(2-0.01L)}'),M(r'(A,L)=(0,0),(5000,200);\quad\frac{dL}{dA}=\frac{L(-0.5+0.0001A)}{A(2-0.01L)}'),'양의 궤도에서 '+M(r'0.0001A-0.5\ln A+0.01L-2\ln L')+'가 보존된다. 축 위의 해와 평형은 닫힌 양의 고리와 구별한다.','On positive trajectories '+M(r'0.0001A-0.5\ln A+0.01L-2\ln L')+' is conserved. Axis solutions and equilibria are distinct from positive closed loops.','abcde')
add(11,M(r'R^{\prime}=0.08R(1-0.0002R)-0.001RW,\quad W^{\prime}=-0.02W+0.00002RW')+'에서 (a) 늑대 부재의 토끼, (b) 평형, (c) '+M(r'(R_0,W_0)=(1000,40)')+'의 장기 거동, (d) 시간 그래프를 구하라.','For '+M(r'R^{\prime}=0.08R(1-0.0002R)-0.001RW,\quad W^{\prime}=-0.02W+0.00002RW')+', find (a) rabbits without wolves, (b) equilibria, (c) long-time behavior from '+M(r'(R_0,W_0)=(1000,40)')+', and (d) time plots.', [('늑대가 없으면 토끼는 수용력 오천의 로지스틱 성장을 한다. 양의 공존에서 토끼 천을 둘째 식에 의해 먼저 구한다.','Without wolves, rabbits follow logistic growth with capacity five thousand. The second equation first fixes rabbits at one thousand for coexistence.'),('공존점의 야코비안은 음의 대각합과 양의 행렬식을 가지며 고유값은 켤레복소수이다. 따라서 작은 진동은 감쇠한다. 주어진 궤도도 공존점으로 감긴다.','At coexistence the Jacobian has negative trace, positive determinant, and complex conjugate eigenvalues. Small oscillations damp, and the specified trajectory spirals into coexistence.')],M(r'(R,W)=(0,0),(5000,0),(1000,64);\quad R(t)\to1000,\ W(t)\to64'),M(r'(R,W)=(0,0),(5000,0),(1000,64);\quad R(t)\to1000,\ W(t)\to64'),'토끼의 극대가 늑대보다 먼저 오며 진폭은 줄어든다. 초기 도함수는 토끼 이십사, 늑대 영이다.','Rabbit peaks lead wolf peaks and amplitudes decrease. The initial derivatives are twenty-four rabbits and zero wolves.','abcd')
add(12,M(r'A^{\prime}=2A(1-0.0001A)-0.01AL,\quad L^{\prime}=-0.5L+0.0001AL')+'에서 (a) 무당벌레 부재, (b) 평형, (c) 위상 기울기, (d) 방향장·초상, (e) '+M(r'(A_0,L_0)=(1000,200)')+'의 변화, (f) 시간 그래프를 구하라.','For '+M(r'A^{\prime}=2A(1-0.0001A)-0.01AL,\quad L^{\prime}=-0.5L+0.0001AL')+', find (a) behavior without ladybugs, (b) equilibria, (c) phase slope, (d) field and portrait, (e) behavior from '+M(r'(A_0,L_0)=(1000,200)')+', and (f) time plots.', [('무당벌레가 없으면 진딧물은 수용력 만의 로지스틱 모형을 따른다. 양의 공존점은 진딧물 오천, 무당벌레 백이다.','Without ladybugs, aphids follow a logistic model with capacity ten thousand. Positive coexistence is five thousand aphids and one hundred ladybugs.'),('초기에 진딧물은 모델 시간당 이백, 무당벌레는 팔십씩 감소한다. 이후 진딧물이 먼저 회복하고 무당벌레가 뒤따른다.','Initially aphids decrease by two hundred and ladybugs by eighty per model time unit. Aphids recover first and ladybugs follow.'),('양의 궤도는 공존점에 접근하며 그 부근에서 감쇠 진동한다. 공존점 고유값은 '+M(r'(-1\pm i)/2')+'.','Positive trajectories approach coexistence with damped oscillations nearby. Coexistence eigenvalues are '+M(r'(-1\pm i)/2')+'.')],M(r'(A,L)=(0,0),(10000,0),(5000,100);\quad\frac{dL}{dA}=\frac{L(-0.5+0.0001A)}{A(2-0.0002A-0.01L)};\quad A\to5000,\ L\to100'),M(r'(A,L)=(0,0),(10000,0),(5000,100);\quad\frac{dL}{dA}=\frac{L(-0.5+0.0001A)}{A(2-0.0002A-0.01L)};\quad A\to5000,\ L\to100'),'양의 사분면에서 Dulac 인자 '+M(r'1/(AL)')+'의 발산은 '+M(r'-0.0002/L<0')+'여서 닫힌 비상수 주기궤도가 없다.','In the positive quadrant the Dulac multiplier '+M(r'1/(AL)')+' has divergence '+M(r'-0.0002/L<0')+', ruling out nonconstant closed periodic orbits.','abcdef')
def rk2(f,initial,end,N=15000):
 h=end/N;y=list(initial);out=[(0,*y)]
 for i in range(N):
  t=i*h;k1=f(*y);k2=f(*(y[j]+h*k1[j]/2 for j in range(2)));k3=f(*(y[j]+h*k2[j]/2 for j in range(2)));k4=f(*(y[j]+h*k3[j] for j in range(2)))
  y=[y[j]+h*(k1[j]+2*k2[j]+2*k3[j]+k4[j])/6 for j in range(2)];out.append(((i+1)*h,*y))
 return out
src=(BASE/'exercise-checks/s9-2-author.py').read_text();tree=ast.parse(src);funcs=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ['sampled','svg']];exec(compile(ast.unparse(ast.Module(body=funcs,type_ignores=[])).replace('s9-2-','s9-6-'),'helpers','exec'))
def panels(n,configs):
 p=BASE/f'exercise-content/assets/s9-6-{n}.svg';parts=[]
 for title,f,xl,yl,curves in configs:
  svg(n,title,f,xl,yl,curves);s=p.read_text();s=s[s.index('>')+1:s.rindex('</svg>')]
  # Add orientation arrows to phase curves, using data time order.
  if title.startswith('Phase'):
   for z,(label,pts) in enumerate(curves):
    for frac in [.15,.4,.7]:
     i=int((len(pts)-2)*frac);a,b=pts[i],pts[i+1]
     X=lambda x:50+(x-xl[0])/(xl[1]-xl[0])*620;Y=lambda y:365-(y-yl[0])/(yl[1]-yl[0])*310
     u,v=X(b[0])-X(a[0]),Y(b[1])-Y(a[1]);mag=math.hypot(u,v)
     if mag<1e-8 or not(xl[0]<b[0]<xl[1] and yl[0]<b[1]<yl[1]):continue
     u,v=u/mag,v/mag;px,py=X(b[0]),Y(b[1]);col=['#1463c2','#c44933','#17926f','#8953b4','#bf8800','#444'][z%6]
     s+=f'<path d="M{px-7*u+3*v:.2f},{py-7*v-3*u:.2f}L{px:.2f},{py:.2f}L{px-7*u-3*v:.2f},{py-7*v+3*u:.2f}" stroke="{col}" stroke-width="2" fill="none"/>'
  parts.append(s)
 p.write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 {435*len(parts)}">'+''.join(f'<g transform="translate(0,{435*i})">{s}</g>' for i,s in enumerate(parts))+'</svg>')
 next(e for e in items if e['number']==n)['figure']['caption']=bi('자체 계산 위상·시간 도해. 개형만 주어진 문항은 대표 함수 또는 보간을 사용했다. 위상도 화살표는 시간 증가 방향이다.','Original phase and time plots. Shape-only questions use representative functions or interpolation. Phase arrows show forward time.')
def configs(tr,title,labels=('prey','predator'),phase_limits=None):
 end=tr[-1][0];xs=[x for t,x,y in tr];ys=[y for t,x,y in tr];xl=(0,max(xs)*1.05);yl=(0,max(ys)*1.1)
 if phase_limits:xl,yl=phase_limits
 return [('Phase: '+title,None,xl,yl,[(labels[0]+' vs '+labels[1],[(x,y) for t,x,y in tr])]),(labels[0]+' over time',None,(0,end),xl,[(labels[0],[(t,x) for t,x,y in tr])]),(labels[1]+' over time',None,(0,end),yl,[(labels[1],[(t,y) for t,x,y in tr])])]
f5=lambda R,F:(R*(.1-.001*F),F*(-.2+.0002*R));tr5=rk2(f5,(300,100),80);panels(5,configs(tr5,'representative closed cycle; arbitrary time',('R','F')))
anchors=[(0,600,160),(1,250,130),(2,80,80),(3,250,40),(4,700,28),(5,1100,28),(6,1750,40),(7,1400,58),(8,950,65)]
tr6=[]
for a,b in zip(anchors,anchors[1:]):
 for i in range(80):
  q=i/80;u=(1-math.cos(math.pi*q))/2;tr6.append((a[0]+q,(1-u)*a[1]+u*b[1],(1-u)*a[2]+u*b[2]))
tr6.append(anchors[-1]);panels(6,configs(tr6,'schematic interpolation; arbitrary time',('R','F')))
f7=lambda t:(45+180*((1+math.cos(2*math.pi*(t-1)/5))/2)**3,50+145*((1+math.cos(2*math.pi*(t-1.9)/5))/2)**1.5)
tr7=[(10*i/1500,*f7(10*i/1500)) for i in range(1501)];panels(7,configs(tr7,'representative periodic graphs',('species 1','species 2'))[:1])
f8=lambda t:(1200-400*math.exp(-.3*t)*math.cos(.6*t),200+500*math.exp(-.55*t)*math.cos(.8*t));tr8=[(15*i/1500,*f8(15*i/1500)) for i in range(1501)];panels(8,configs(tr8,'representative damped graphs',('species 1','species 2'))[:1])
f9=lambda R,W:(R*(.08-.001*W),W*(-.02+.00002*R));tr9=rk2(f9,(1000,40),350);panels(9,configs(tr9,'conserved level through (1000,40)',('R','W'))[:1])
f10=lambda A,L:(A*(2-.01*L),L*(-.5+.0001*A));tr10=rk2(f10,(1000,200),30);cfg10=configs(tr10,'aphids and ladybugs',('A','L'),((0,20000),(0,450)))
# Additional positive orbits form the phase portrait; arrows use the vector field direction.
for initial in [(3000,200),(5000,100),(8000,200)]:
 tr=rk2(f10,initial,20);cfg10[0][4].append((str(initial),[(a,l) for t,a,l in tr]))
panels(10,cfg10)
f11=lambda R,W:(.08*R*(1-.0002*R)-.001*R*W,W*(-.02+.00002*R));tr11=rk2(f11,(1000,40),750);panels(11,configs(tr11,'damped rabbit-wolf trajectory',('R','W'),((600,1800),(30,85))))
f12=lambda A,L:(2*A*(1-.0001*A)-.01*A*L,L*(-.5+.0001*A));tr12=rk2(f12,(1000,200),35);cfg12=configs(tr12,'damped aphid-ladybug trajectories',('A','L'),((0,11000),(0,250)))
# Draw the requested field as un-oriented line elements and add oriented trajectories.
num=cfg12[0];cfg12[0]=(num[0],lambda a,l:f12(a,l)[1]/f12(a,l)[0],num[2],num[3],num[4])
for initial in [(3000,50),(8000,200),(9000,40)]:
 tr=rk2(f12,initial,35);cfg12[0][4].append((str(initial),[(a,l) for t,a,l in tr]))
panels(12,cfg12)
# Conservation and step refinement numerical QA.
H9=lambda r,w:.02*math.log(r)+.08*math.log(w)-.00002*r-.001*w
H10=lambda a,l:.0001*a-.5*math.log(a)+.01*l-2*math.log(l)
assert max(abs(H9(r,w)-H9(1000,40)) for t,r,w in tr9)<1e-8
assert max(abs(H10(a,l)-H10(1000,200)) for t,a,l in tr10)<1e-8
for f,init,end,tr in [(f9,(1000,40),350,tr9),(f10,(1000,200),30,tr10),(f11,(1000,40),750,tr11),(f12,(1000,200),35,tr12)]:
 fine=rk2(f,init,end,30000);assert max(abs(a-b) for a,b in zip(fine[-1][1:],tr[-1][1:]))<1e-3
assert len(items)==12
raw=dict(section='9.6',source=dict(title='Calculus',edition='9',language='en',printedPages=[691,692,693],pdfPages=[728,729,730]),scope=dict(kind='exercise',numbers=list(range(1,13)),total=12,note=bi('전체 12문항과 모든 소문항.','All 12 exercises and every subpart.')),exercises=items)
p=BASE/'exercise-content/s9-6.json';p.write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n');sys.path.insert(0,str(BASE));import build_exercises as b;b.validate_document(raw,p)
print('9.6:12 cards,8 multi-panel SVGs; invariants and step refinement passed')
